= Адаптація "Підсистеми управління Платформою та реєстрами"

[NOTE]
--
В даному розділі ми фіксуємо обсяг змін, які було виконано для реалізації підтримки Платформою регіонів обслуговування:

* Епіки (для відслідковування комітів в майбутньому)
* Функціональні сценарії
* Підсистеми, які підлягають зміні
* Компоненти підсистем, які підлягають зміні
* Суть змін / перелік дизайн-рішень у вигляді баллет-поінтів
--

== Епіки

* _[BN-08-03][S23][OSS] Розширення веб-інтерфейсу "Підсистеми управління Платформою та реєстрами" підтримкою регіону обслуговування_

== Структура операційної конфігурації

В рамках реалізації вимог, необхідно розширити шаблони конфігурацій Платформи та реєстрів додатковим налаштуванням `global.region`.

[NOTE]
Для підтримки зворотної сумісності версій, у разі відсутності налаштування `global.region`, застосовується значення за замовчуванням `ua`.

=== Конфігурація Платформи

Налаштування `global.region` встановлюється при розгортанні нового екземпляра Платформи у значення, яке було передано у вигляді змінної оточення `platformRegion` інсталятору Платформи.

.control-plane-gerrit:cluster-mgmt.git/deploy-templates/values.yaml
[source, yaml]
----
global:
  region: ua # [ua, global]
----

=== Конфігурація реєстру

Налаштування `global.region` встановлюється при створенні нового реєстру на Платформі у значення, яке відповідає поточному налаштуванню `global.region` на рівні конфігурації Платформи.

.control-plane-gerrit:registry-tenant-template.git/deploy-templates/values.yaml
[source, yaml]
----
global:
  region: ua # [ua, global]
----
