= Адаптація "Компоненти керування станом ресурсів Платформи"

[NOTE]
--
В даному розділі ми фіксуємо обсяг змін, які було виконано для реалізації підтримки Платформою регіонів обслуговування:

* Епіки (для відслідковування комітів в майбутньому)
* Функціональні сценарії
* Підсистеми, які підлягають зміні
* Компоненти підсистем, які підлягають зміні
* Суть змін / перелік дизайн-рішень у вигляді баллет-поінтів
--

== Епіки

* _[BN-08-03][S23][OSS] Розширення інсталятора Платформи можливістю задати регіон обслуговування_

== Розгортання екземпляра Платформи

При розгортанні нового екземпляра Платформи Реєстрів, інсталятор підтримує можливість задати регіон для обслуговування за допомогою змінної оточення _platformRegion_. За відсутності приймається значення за замовчуванням _ua_.

[source, bash]
----
$ sudo docker run --rm \
    --name control-plane-installer-<VERSION> \
    --...
    --env platformRegion=<ua|global> \
    --entrypoint "/bin/sh" control-plane-installer:<VERSION> \
    -c "./install.sh -i"
----

