= Підтримка концепції _регіонів обслуговування_ Платформою Реєстрів

[IMPORTANT]
--
Сторінка технічної документації є баченням майбутньої реалізації, актуальність якого може бути застарілою.
--

== Загальний опис

Наразі існує необхідність

== Актори та ролі користувачів

* Технічний адміністратор Платформи

== Функціональні сценарії

* ...

== Загальні принципи та положення

*


* CD-пайплайн розгортання реєстру на CI/CD підтримує можливість вибору регіону для обслуговування
* Тестування регіону "_global_" проводиться

Збірка інсталятора
* ...

* Вводиться поняття "Регіону"
* Екзепляр Платформи знає для якого регіону він був зібраний через відповідний параметр у `values.yaml`.
* Збірка інсталлеру мість в назві регіон для якого вона була зібрана.
* Набір компонентів в архіві інсталлеру Платформи може змінюватись в залежності від регіону. Наприклад, `conset-data` або `empty-template-registry-regulation` тощо не мають бути присутні в архіві.
* Компонент має знати в якому регіоні він працює через відповідний параметр у `values.yaml` та
** має підлаштувати себе сам під роботу в цьому регіоні (feature toggle). Наприклад, адмін-консоль, кабінети, dso тощо.
** або його підлаштує пайплайн розгортання реєстру (параметри helm chart). Наприклад, bp-modeller-extensions (element template) налаштується через registry-configuration chart, а `sign-widget-mock` — через `external-integration-mocks` chart.
* Реалізація налаштувань та адаптація кожного компонента не входить в обсяг робіт, та буде відбуватись у рамках інших епіків.
* Global версія Платформи і її компоненти будуть містити всі необхідні ресурси, щоб працювати і в тому числі в UA регіоні. Наприклад, в Global версію Keycloak все ще будуть пакуватись автентифікатори.

=== Компоненти системи та їх призначення в рамках дизайну рішення

У даному розділі наведено перелік компонент системи, які задіяні або потребують змін/створення в рамках реалізації функціональних вимог згідно з технічним дизайном рішення.

|===
|Компонент|Службова назва|Призначення / Суть змін

|_Автентифікатор громадян_
|*keycloak-ds-citizen-authenticator*
|Застосування стратегії нечіткого порівняння повного імені особи при автентифікації

|_Автентифікатор посадових осіб_
|*keycloak-ds-officer-authenticator*
|Застосування стратегії нечіткого порівняння повного імені посадової особи при автентифікації

|===

== Автентифікація користувачів кабінетів

=== Автентифікація

...

=== Самореєстрація

...

== Накладання підпису та валідація

=== Кваліфікований електронний підпис

...

=== Цифрова печатка

...

== Розгортання екземпляра Платформи

При розгортанні нового екземпляра Платформи Реєстрів, інсталятор підтримує можливість задати регіон для обслуговування за допомогою змінної оточення _platformRegion_. За відсутності приймається значення за замовчуванням _ua_.

[source, bash]
----
$ sudo docker run --rm \
    --name control-plane-installer-<VERSION> \
    --...
    --env platformRegion=<ua|global> \
    --entrypoint "/bin/sh" control-plane-installer:<VERSION> \
    -c "./install.sh -i"
----

== Структура операційної конфігурації

В рамках реалізації вимог, необхідно розширити шаблони конфігурацій Платформи та реєстрів додатковим налаштуванням `global.region`.

[NOTE]
Для підтримки зворотної сумісності версій, у разі відсутності налаштування `global.region`, застосовується значення за замовчуванням `ua`.

=== Конфігурація Платформи

Налаштування `global.region` встановлюється при розгортанні нового екземпляра Платформи у значення, яке було передано у вигляді змінної оточення `platformRegion` інсталятору Платформи.

.control-plane-gerrit:cluster-mgmt.git/deploy-templates/values.yaml
[source, yaml]
----
global:
  region: ua # [ua, global]
----

=== Конфігурація реєстру

Налаштування `global.region` встановлюється при створенні нового реєстру на Платформі у значення, яке відповідає поточному налаштуванню `global.region` на рівні конфігурації Платформи.

.control-plane-gerrit:registry-tenant-template.git/deploy-templates/values.yaml
[source, yaml]
----
global:
  region: ua # [ua, global]
----

== Відкриті питання

* Reverse engineering opensource збірки Платформи?
* Тестування Global версії. SIT?
