= Підтримка концепції _регіонів обслуговування_ Платформою Реєстрів

[IMPORTANT]
--
Розділ технічної документації є баченням майбутньої реалізації, актуальність якого може бути застарілою.
--

== Загальні принципи та положення

* Рішення _Платформи Реєстрів_ надає можливості розгортання екземплярів Платформи для створення реєстрів з урахуванням регіональних вимог
* _Компонент керування станом ресурсів Платформи_ включає набір компонент та скриптів розгортання для всіх регіонів, які підтримуються _Платформою Реєстрів_
* _Платформа Реєстрів_ підтримує два регіони обслуговування:
** _ua_ - розробка реєстрів з урахуванням регіональних вимог та особливостей
** _global_ - розробка реєстрів з генералізованими вимогами
* Цільовий регіон обслуговування вказується адміністратором при встановленні нового екземпляра _Платформи Реєстрів_
* Екземпляр _Платформи Реєстрів_ передбачає обслуговування єдиного регіону, вказаного при її інсталяції та не може бути змінений
* Реєстри наслідують регіон обслуговування екземпляра Платформи при їх створенні через _Веб-інтерфейс управління Платформою та реєстрами_
* Реєстр передбачає обслуговування єдиного регіону, налаштованого на рівні екземпляра Платформи
* У якості підходу для управління поведінкою підсистем Платформи та реєстрів згідно до налаштованого регіону обслуговування прийнято використання _Feature Toggle_ на рівні коду та автоматизації
* Кожен компонент підсистем Платформи та реєстрів параметризується змінною з налаштуванням регіону обслуговування для адаптації поведінки
* _CD_-пайплайн розгортання реєстру на _CI/CD_ підтримує можливість вибору регіону для обслуговування
* Тестування _Платформи Реєстрів_ для регіону обслуговування _global_ виконується в ручному режимі, паралельно основному процесу розробки для _ua_ регіону
* Демонстрація можливостей Платформи та реєстрів, які обслуговують _global_ регіон виконується на базі окремо створеного регламенту, згідно з ключовими сценаріями використання