= Підтримка концепції _регіонів обслуговування_ Платформою Реєстрів

[IMPORTANT]
--
Сторінка технічної документації є баченням майбутньої реалізації, актуальність якого може бути застарілою.
--

== Загальний опис

...

== Актори та ролі користувачів

* ...

== Функціональні сценарії

* ...

== Загальні принципи та положення

* ...

* Вводиться поняття "Регіону"
+
[source,yaml]
----
global:
  region: global #valid values: global, ua
----
+
* Екзепляр Платформи знає для якого регіону він був зібраний через відповідний параметр у `values.yaml`.
* Збірка інсталлеру мість в назві регіон для якого вона була зібрана.
* Набір компонентів в архіві інсталлеру Платформи може змінюватись в залежності від регіону. Наприклад, `conset-data` або `empty-template-registry-regulation` тощо не мають бути присутні в архіві.
* Компонент має знати в якому регіоні він працює через відповідний параметр у `values.yaml` та
** має підлаштувати себе сам під роботу в цьому регіоні (feature toggle). Наприклад, адмін-консоль, кабінети, dso тощо.
** або його підлаштує пайплайн розгортання реєстру (параметри helm chart). Наприклад, bp-modeller-extensions (element template) налаштується через registry-configuration chart, а `sign-widget-mock` — через `external-integration-mocks` chart.
* Реалізація налаштувань та адаптація кожного компонента не входить в обсяг робіт, та буде відбуватись у рамках інших епіків.
* Global версія Платформи і її компоненти будуть містити всі необхідні ресурси, щоб працювати і в тому числі в UA регіоні. Наприклад, в Global версію Keycloak все ще будуть пакуватись автентифікатори.

== Відкриті питання

* Reverse engineering opensource збірки Платформи?
* Тестування Global версії. SIT?
