:imagesdir: ../../../../../images
= Підсистема управління налаштуваннями користувачів

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Підсистема, яка забезпечує можливості управління персональними налаштуваннями через кабінет користувача.

== Функції підсистеми

- Пошук налаштувань користувача за ідентифікатором користувача
- Пошук налаштувань користувача за ідентифікатором користувача, отриманим з токена доступу
- Активація каналу зв'язку шляхом введення / оновлення даних атрибутів каналу (наприклад: поштова адреса)
- Підтвердження каналу зв'язку шляхом відправлення повідомлень зі згенерованими OTP-кодами
- Деактивація каналу зв'язку
- Валідація введених налаштувань користувача (за патерном email, відсутністю в blacklist тощо)

== Технічний дизайн підсистеми

image::architecture/registry/operational/user-settings/user-settings-overview.drawio.svg[float="center",align="center"]


Для отримання налаштувань користувача з бізнес процесу підсистема надає 
метод

* _Отримання налаштувань користувача за ідентифікатором_: використовується для змоги надсилати повідомлення користувачам на обрані ними канали зв'язку.

Цей метод доступний лише зсередини операційної зони реєстру для _Підсистеми виконання бізнес процесів_.



Для роботи з налаштуваннями через кабінет користувача надаються наступні методи:

* _Отримання налаштувань_: повертає налаштування поточного користувача, який виконав вхід у систему.
* _Валідація email_: валідує email, внесений у якості адреси для каналу зв'язку, за встановленим набором правил, таких як валідація за regexp, перевірка унікальності, перевірка на входження до blacklist та ін.
* _Верифікація каналу зв'язку_: генерує та зберігає код підтвердження (OTP) та ініціює його відправлення підсистемою нотифікації користувачів за вказаним каналом зв'язку. 
* _Активація каналу зв'язку_: перевіряє вказаний користувачем код OTP та активує канал зв'язку користувача або створює нове налаштування для каналу, якщо його ще не існує.
* _Деактивація каналу зв'язку_: деактивує канал зв'язку.

Ці методи роботи з налаштуваннями доступні через Підсистему управління зовнішнім трафіком, та вимагають автентифікації користувача. Робота з налаштуваннями виконується лише для поточного користувача, який виконав вхід у систему. Зміна налаштувань іншого користувача неможлива за дизайном.

=== Аудит та журналювання подій

Події активації/деактивації каналів зв'язку фіксуються у журналі аудиту з повним контекстом. Використовуються наступні назви подій:

* _USER_NOTIFICATION_CHANNEL_ACTIVATION_: Активація каналу зв'язку
* _USER_NOTIFICATION_CHANNEL_DEACTIVATION_: Деактивація каналу зв'язку

[NOTE]
Детальніше з дизайном _Підсистеми журналювання подій аудиту_ можна ознайомитися
xref:arch:architecture/registry/operational/audit/overview.adoc[за посиланням]

== Складові підсистеми

|===
|Назва компоненти|Представлення в реєстрі|Походження|Репозиторій|Призначення

|_Сервіс управління налаштуваннями користувачів_
|`user-settings-service-api-deployment`
|origin
|https://github.com/epam/edp-ddm-user-settings-service-api
|-

|_Операційна БД налаштувань користувачів_
|`operational:settings`
|origin
|https://github.com/epam/edp-ddm-registry-postgres/tree/main/platform-db/changesets/settings
|-
|===

== Атрибути якості підсистеми

=== _Observability_

_Підсистема управління налаштуваннями користувачів_ підтримує журналювання та збір метрик продуктивності для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--

=== Auditability

_Підсистема управління налаштуваннями користувачів_ фіксує значимі технічні та бізнес події, пов'язані з експлуатацією системи кінцевими користувачами використовуючи xref:arch:architecture/registry/operational/audit/overview.adoc[підсистему журналювання подій аудиту].