= Нереляційне сховище даних

== Загальний опис

_xref:arch:architecture/registry/operational/user-settings/overview.adoc[Підсистема управління налаштуваннями користувачів]_ використовує розподілену _in-memory_ базу даних xref:arch:architecture/platform-technologies.adoc#redis[Redis] з  xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc[_Підсистеми управління нереляційними базами даних_] для зберігання автоматично згенерованих _OTP_-кодів (_One-Time Password_) зі встановленим _Time-To-Live_ для записів згідно налаштувань реєстру.

Дані зберігаються у вигляді _Hash_-таблиці з сегрегацією об’єктів на рівні префіксів в ідентифікаторах (_<keyspace>:<key>_).

== Структури даних

=== channel-verification-codes

Зберігання об'єктів автоматично згенерованих _OTP_-кодів для підтвердження каналів зв'язку з користувачем.

.Паттерн генерації ключа для запису
[source]
----
channel-verification-codes:{userId}/{channel}
----

.Опис структури для зберігання OTP для активації каналу зв'язку
|===
|Ключ|Тип даних|Опис

|`id`
|_String_
|Унікальний ідентифікатор

|`otpData.address`
|_String_
|_РНОКПП_ користувача

|`otpData.verificationCode`
|_String_
|_OTP_-код для підтвердження
|===