= Операційна БД налаштувань користувачів

== Загальний опис

Призначенням бази даних `settings` є зберігання персональних налаштувань користувачів.

== Схема бази даних

[plantuml, settings-schema, svg]
----
@startuml
hide circle
skinparam linetype ortho
skinparam monochrome true

entity "**notification_channel**" {
  + ""id"": //uuid [PK]//
  --
  *""settings_id"": //uuid [FK]//
  *""channel"": //channel_enum //
  ""address"": //text //
  ""deactivation_reason"": //text //
  *""is_activated"": //boolean //
  *""created_at"": //timestamp with time zone //
  *""updated_at"": //timestamp with time zone //
}

entity "**settings**" {
  + ""id"": //uuid [PK]//
  --
  *""keycloak_id"": //uuid //
}

"**notification_channel**"   }--  "**settings**"
@enduml
----
.Умовні позначення
[%collapsible]
====
include::partial$architecture-workspace/documentation-templates/component-design-template/db-schema-legend.adoc[]
====

== Структури даних

=== notification_channel

Налаштування каналів зв'язку користувача

[options="header",cols="a"]
|======
|Ім'я колонки +
Опис
| `*id* _uuid_ *(PK)*` + 
Ідентифікатор рядка 
| `*settings_id* _uuid_` (references <<_settings>>.id) + 
Ідентифікатор налаштування користувача 
| `*channel* _enum_` + 
Назва каналу зв’язку для використання шаблону повідомлення

* EMAIL - Відправка поштових повідомлень
* DIIA - Відправка push-нотифікацій у мобільний додаток Дія
| `address _text_` + 
Адреса для відправлення повідомлень (опційна, в залежності від типу каналу зв’язку) 
| `deactivation_reason _text_` + 
Причина попередньої деактивації каналу 
| `*is_activated* _boolean_` + 
Чи активований даний канал 
| `*created_at* _timestamp with time zone_` + 
Дата/Час створення запису 
| `*updated_at* _timestamp with time zone_` + 
Дата/Час оновлення запису 

|======
[options="header",cols="a"]
|======
|Обмеження унікальності
|`settings_id,channel`
|======

=== settings

Налаштування користувача

[options="header",cols="a"]
|======
|Ім'я колонки +
Опис
| `*id* _uuid_ *(PK)*` + 
Ідентифікатор рядка 
| `*keycloak_id* _uuid_` + 
Зовнішній ідентифікатор користувача в keycloak 

|======
[options="header",cols="a"]
|======
|Обмеження унікальності
|`keycloak_id`
|======