include::ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

= Platform administrative zone

include::ROOT:partial$admonitions/language-en.adoc[]

== General description

The _Platform administrative zone_ comprises subsystems
that manage the state and settings of the Platform instance and its deployed registries.
We utilize the _**GitOps** approach_ to handle updates. This method automatically applies modifications to the appropriate version control repositories.

//_Підсистема управління Платформою та Реєстрами_ адміністративної зони надає веб-інтерфейси для адміністраторів, за допомогою яких можна керувати оновленням, конфігурацією, масштабуванням, резервним копіюванням, відновленням та іншими службовими функціями _Платформи_.
_The Platform and registries management subsystem_ in the administrative zone offers web interfaces for administrators to manage updates, configurations, scalability, backup, restoration, and other service functions.

[TIP]
--
//Детальніше з ролями службових адміністраторів можна ознайомитись у розділі xref:arch:architecture/platform/operational/user-management/platform-actors-roles.adoc#_службові_адміністратори[Актори та ролі Платформи].
For more information on the roles of service administrators, please refer to the xref:arch:architecture/platform/operational/user-management/platform-actors-roles.adoc#службові_адміністратори[Actors and roles section of the Platform].
--

== Technical design

//На даній діаграмі зображено підсистеми, які входять в _Адміністративну зону Платформи_ та їх взаємодію з іншими підсистемами в рамках реалізації функціональних сценаріїв.
This diagram illustrates the subsystems that are part of the Platform administrative zone and their interactions with other subsystems in the implementation of functional scenarios.

image::architecture/platform/administrative/administrative-zone-subsystems.svg[]

//== Підсистеми адміністративної зони Платформи
== Platform administrative zone subsystems

|===
//|Назва підсистеми|Службова назва
|Subsystem name|Service name

//|xref:architecture/platform/administrative/control-plane/overview.adoc[Підсистема управління Платформою та реєстрами]
|xref:architecture/platform/administrative/control-plane/overview.adoc[]
|_control-plane_

|xref:architecture/platform/administrative/config-management/overview.adoc[]
|_config-management_

|===
