= Platform administrative zone
include::ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::ROOT:partial$admonitions/language-en.adoc[]

== General description

The *_Platform administrative zone_* comprises subsystems
that manage the state and settings of the Platform instance and its deployed registries.
We utilize the _**GitOps** approach_ to handle updates. This method automatically applies modifications to the appropriate version control repositories.

_The Platform and registries management subsystem_ in the administrative zone offers web interfaces for administrators to manage updates, configurations, scalability, backup, restoration, and other service functions.

[TIP]
--
For more information on the roles of service administrators, please refer to the xref:arch:architecture/platform/operational/user-management/platform-actors-roles.adoc#службові_адміністратори[Actors and roles section of the Platform].
--

== Technical design

This diagram illustrates the subsystems that are part of the Platform administrative zone and their interactions with other subsystems in the implementation of functional scenarios.

image::architecture/platform/administrative/administrative-zone-subsystems.svg[]

== Platform administrative zone subsystems

|===
|Subsystem name|Service name

|xref:architecture/platform/administrative/control-plane/overview.adoc[]
|_control-plane_

|xref:architecture/platform/administrative/config-management/overview.adoc[]
|_config-management_

|===
