= Автентифікація посадових осіб, єдина для групи реєстрів завдяки ручним налаштуванням

== Загальний опис
При роботі посадової особи в декількох реєстрах, які по своїй природі є спорідненими, виникає потреба виконувати
автентифікацію в кожен кабінет окремо використувуючі для цього один і той самий ключ, але виконучі логін в різних кабінетах.
Для спрощення досвіду користувача необхідно розробити підхід для забезпечення SSO в рамках групи реєстрів для мінімізації
однотипних дій користувача.

== Функціональні сценарії
* Створення групи реєстрів для SSO адміністратором платформи
* Налаштування SSO для групи реєстрів адміністратором платформи
* Автентифікація посадової особи в кабінет за допомогою ключа
* Автентифікація посадової особи в кабінет за допомогою id.gov.ua
* Автореєстрація посадової особи
* Створення користувачів адміністратором реєстру через Кейклоак
* Створення користувачів адміністратором реєстру через Адмін Портал (імпорт csv файлу)
* Налаштування ролей користувачів адміністратором реєстру
* Налаштування атрибутів користувачів адміністратором реєстру

== Ролі користувачів
* Адміністратор платформи
* Адміністратор реєстру
* Посадова особа

== Загальні принципи та положення
* Споріднені реєстри (група реєстрів) - реєстри які належать одній організації і схожі за призначенням
* Споріднені реєстри мають спільну базу користувачів посадових осіб
* Посадова особа повинна виконувати логін 1 раз коли працює в споріднених реєстрах
* Рішення повинно максимально бути побудовано на ручних налаштуваннях по інструкції
* Мастер ріалм федерації реєстрів - Кейклоак реалм, який має спільну базу користувачів для групи споріднених реєстрів
* Ріалм посадових осіб використовує мастер ріалм федерації реєстрів для автентифікації як Identity Provider (IdP)
* До групи споріднених реєстрів можуть бути підключені як нові реєстри, так і існуючі реєстри з власною базою користувачів
* Імпорт користувачів через файл може бути виконаний тільки на рівні окремого реєстру
* Налаштування ролей посадових осіб виконується на рівні окремого реєстру
* Налаштування ідентифікуючих системних атрибутів (fullName, edrpou, drfo) виконується на рівні мастер ріалму
* Налаштування додаткових атрибутів виконується на рівні окремого реєстру
* Мастер ріалм підтримує режим автореєстрації посадових осіб
* Мастер ріалм підтримує інтеграцію з id.gov.ua для автентифікації посадових осіб
* При вході в кабінет немає можливості обрати, чи виконати логін в реєстровому реалмі чи в мастер реалмі

== Високорівневий дизайн рішення

=== Компонентна діаграма
image:architecture-workspace/platform-evolution/registry-federation/component.svg[]

|===
|Компонент |Назва |Тип |Розташування  |Опис

|Identity Provider
|federation-idp
|keycloak-oidc
|Реєстровий ріалм
|Інтеграція з мастер ріалмом для ідентифікації

|Authenticator Execution
|federation-idp
|Identity Provider Redirector
|Реєстровий ріалм / Authentication dso-officer-auth-flow
|У конфігурації налаштовується ідентіті провайдер federation-idp за замовчуванням

|Identity Provider Mapper
|fullName
|Attribute Importer
|Реєстровий ріалм / Identity Provider federation-idp
|Імпорт атрибута fullName з мастер ріалму при автентифікації користувача

|Identity Provider Mapper
|drfo
|Attribute Importer
|Реєстровий ріалм / Identity Provider federation-idp
|Імпорт атрибута drfo з мастер ріалму при автентифікації користувача

|Identity Provider Mapper
|edrpou
|Attribute Importer
|Реєстровий ріалм / Identity Provider federation-idp
|Імпорт атрибута edrpou з мастер ріалму при автентифікації користувача

|Realm
|registry-federation-<group-name>
|Realm
|Keycloak
|Мастер Ріалм для спільного управління користувачами споріднених реєстрів та SSO. <group-name> - назва обрана для
спільної групиреєстрів

|Client
|<registry-name>-client
|openid-connect
|registry-federation-<group-name> Realm
|Клієнт для інтеграції реєстровий ріалм - мастер ріалм. Конфігурація повинна бути погоджена з налаштуванням
Identity Provider federation-idp в реєстровому ріалмі (client id, client secret, redirect uri).
<registry-name> - назва реєстру в федерації

|Client Scope
|dso-identity
|openid-connect
|registry-federation-<group-name> Realm
|Client Scope для одноразового налаштування мапперів fullName, drfo, edrpou з мастер ріалму. Створений client scope
необхідно вказати як client scope за замовчуванням (Default Client Scopes)

|Client Scope Mapper
|fullName
|User Attribute
|registry-federation-<group-name> Realm / Client Scope dso-identity
|Створюється для мапінгу атрибута fullName з мастер ріалму

|Client Scope Mapper
|drfo
|User Attribute
|registry-federation-<group-name> Realm / Client Scope dso-identity
|Створюється для мапінгу атрибута drfo з мастер ріалму

|Client Scope Mapper
|edrpou
|User Attribute
|registry-federation-<group-name> Realm / Client Scope dso-identity
|Створюється для мапінгу атрибута edrpou з мастер ріалму

|Authentication
|dso-officer-auth-flow
|Top Level Flow / generic
|registry-federation-<group-name> Realm
|Створюється з аналогічними налаштуваннями як і в реєстровому ріалмі для dso-officer-auth-flow.
Примітка: dso-officer-auth execution повинен бути з вимкненим Required типом або під обгорткою Authentication Flow
з типом Alternative для можливості первинної перевірки по Cookie та SSO

|Authentication
|federation-idp first broker login
|Top Level Flow / generic
|Реєстровий ріалм
|Authentication flow для першого входу через federation-idp. Повинен бути вибраний як first broker login в налаштуваннях
Identity Provider federation-idp

|Authenticator Execution
|registry-federation-authenticator
|registry-federation-authenticator
|Реєстровий ріалм / Authentication federation-idp first broker login
|Автентифікатор для обробки першого входу через мастер ріалм. Потребує додаткової розробки

|===

=== Діаграма діяльності registry-federation-authenticator
image:architecture-workspace/platform-evolution/registry-federation/activity.svg[]

==== Конфігурація registry-federation-authenticator

|===
|Назва |Тип |Опис

|Alias
|String
|Назва конфігурації

|Enable officer auto registration
|Boolean
|Параметр для включення режиму автореєстрації посадових осіб

|Default role for officer auto registration
|Array of Strings
|Перелік ролей для автореєстрації посадових осіб

|===


[NOTE]
====
При використанні Identity Provider першим логіном вважається ситуація коли у жодному обліковому записі реєстрового реалму
не знайдений identity provider link на обліковий запис в мастер ріалмі
====

== Обсяг робіт

=== Попередня декомпозиція
* Розробка registry-federation-authenticator (розширення AbstractIdpAuthenticator) з випуском нової версії Кейклоак
* Розробка інструкцій для ручних налаштувань федерації реалмів з наступним сценарієм:
** Реєстри нові (користувачів в реєстрових реалмах ще немає)
** Автентифікація в мастер ріалмі виконується по підпису
** Користувачі повинні бути попередньо створені в мастер ріалмі в Кейклоак (без імпорту)
** На рівні реєстрового ріалму налаштована автореєстрація
** Налаштування атрибутів та ролей відбувається на рівні реєстрового ріалму після першого логіну користувача


=== Обмеження рішення
* Більшість налаштувань виконується вручну
* При помилці в реєстровому ріалмі буде показана стандартна сторінка Кейклоак з помилкою
* Створення користувачів відбувається в ручному режимі в Кейклоак в мастер ріалмі


=== Додаткові задачі на технічний борг
* Зробити можливість вибору режиму ALTERNATIVE для execution з типом dso-officer-auth-flow
* IdGovUaOfficerAuthenticator. При включеній автореєстрації і випадку, коли буде знадено за атрибутами більше ніж одного
користувача, буде створено ще одного користувача
* Переробити підхід до призначення ролей за замовчуванням на стандартний замість логіки в автентифікаторах
* Перейти на единий автентифікатор по обробці першого входу через idp для всіх кейсів
* IdGovUaOfficerAuthenticator. При генерації помилки перекидає на сторінку з dso автентифікатором навіть якщо за
замовчуванням стоїть idp id.gov.ua