openapi: 3.0.0
paths:
  '/api/form-submissions/{formKey}/validate':
    post:
      operationId: FormSubmissionsController_validate
      parameters:
        - name: X-Request-Id
          in: header
          required: false
          schema:
            type: string
        - name: X-B3-SpanId
          in: header
          required: false
          schema:
            type: string
        - name: X-B3-TraceId
          in: header
          required: false
          schema:
            type: string
        - name: X-Access-Token
          required: true
          in: header
          description: Токен доступу користувача
          schema:
            type: string
        - name: formKey
          required: true
          in: path
          description: Унікальний ідентифікатор схеми UI-форми
          examples:
            '1':
              value: '1'
            user:
              value: user
            admin:
              value: admin
            edit-personprofile-firstbpmn:
              value: edit-personprofile-firstbpmn
            edit-personprofile-secondbpmn:
              value: edit-personprofile-secondbpmn
            add-startform:
              value: add-startform
            add-lab-file:
              value: add-lab-file
            sign-lab-file:
              value: sign-lab-file
            edit-lab-file:
              value: edit-lab-file
            sign-edited-lab-file:
              value: sign-edited-lab-file
            mdtuddm-12887:
              value: mdtuddm-12887
            mdtuddm-11573:
              value: mdtuddm-11573
            mdtuddm-16614-complex-validation:
              value: mdtuddm-16614-complex-validation
            day-and-datetime:
              value: day-and-datetime
            test-password:
              value: test-password
            form-with-all-fields-for-validation:
              value: form-with-all-fields-for-validation
            auto-form-with-files-upload-validation-soma:
              value: auto-form-with-files-upload-validation-soma
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormSchemaDTO'
      responses:
        '200':
          description: OK
        '400':
          description: Некоректно сформований запит
        '401':
          description: Помилка автентифікації (відсутній токен доступу)
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  message:
                    type: string
        '404':
          description: Помилка автентифікації (відсутній токен доступу)
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  message:
                    type: string
        '422':
          description: Помилка валідації даних відносно схеми UI-форми
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  code:
                    type: string
                    example: VALIDATION_ERROR
                  details:
                    type: object
                    properties:
                      errors:
                        type: array
                        items:
                          properties:
                            value:
                              type: string
                              example: '"null"'
                            field:
                              type: string
                              example: entities
                            message:
                              type: string
                              example: must not be null
                        example:
                          - value: 'null'
                            field: entities
                            message: must not be null
        '500':
          description: Серверна помилка обробки запиту
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  message:
                    type: string
  '/api/form-submissions/{formKey}/fields/{fieldKey}/validate':
    post:
      operationId: FormSubmissionsController_validateField
      parameters:
        - name: X-Request-Id
          in: header
          required: false
          schema:
            type: string
        - name: X-B3-SpanId
          in: header
          required: false
          schema:
            type: string
        - name: X-B3-TraceId
          in: header
          required: false
          schema:
            type: string
        - name: X-Access-Token
          required: true
          in: header
          description: Токен доступу користувача
          schema:
            type: string
        - name: formKey
          required: true
          in: path
          description: Унікальний ідентифікатор схеми UI-форми
          examples:
            '1':
              value: '1'
            user:
              value: user
            admin:
              value: admin
            edit-personprofile-firstbpmn:
              value: edit-personprofile-firstbpmn
            edit-personprofile-secondbpmn:
              value: edit-personprofile-secondbpmn
            add-startform:
              value: add-startform
            add-lab-file:
              value: add-lab-file
            sign-lab-file:
              value: sign-lab-file
            edit-lab-file:
              value: edit-lab-file
            sign-edited-lab-file:
              value: sign-edited-lab-file
            mdtuddm-12887:
              value: mdtuddm-12887
            mdtuddm-11573:
              value: mdtuddm-11573
            mdtuddm-16614-complex-validation:
              value: mdtuddm-16614-complex-validation
            day-and-datetime:
              value: day-and-datetime
            test-password:
              value: test-password
            form-with-all-fields-for-validation:
              value: form-with-all-fields-for-validation
            auto-form-with-files-upload-validation-soma:
              value: auto-form-with-files-upload-validation-soma
          schema:
            type: string
        - name: fieldKey
          required: true
          in: path
          description: Унікальний ідентифікатор поля в межах UI-форми
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormFieldValidationDTO'
      responses:
        '200':
          description: OK з поверненням результату
          content:
            application/json:
              schema:
                properties:
                  isValid:
                    type: boolean
                    example: true
        '400':
          description: Некоректно сформований запит
        '401':
          description: Помилка автентифікації (відсутній токен доступу)
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  message:
                    type: string
        '404':
          description: 'Схема UI-форми за вказаним {form-key} відсутня'
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  message:
                    type: string
        '422':
          description: Помилка валідації даних відносно схеми UI-форми
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  code:
                    type: string
                    example: VALIDATION_ERROR
                  details:
                    type: object
                    properties:
                      errors:
                        type: array
                        items:
                          properties:
                            field:
                              type: string
                              example: entities
                            message:
                              type: string
                              example: must not be null
                        example:
                          - field: entities
                            message: must not be null
        '500':
          description: Серверна помилка обробки запиту
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  message:
                    type: string
        '501':
          description: Операція не підтримується системою
  '/api/form-submissions/{formKey}/fields/check':
    post:
      operationId: FormSubmissionsController_checkFields
      parameters:
        - name: X-Request-Id
          in: header
          required: false
          schema:
            type: string
        - name: X-B3-SpanId
          in: header
          required: false
          schema:
            type: string
        - name: X-B3-TraceId
          in: header
          required: false
          schema:
            type: string
        - name: X-Access-Token
          required: true
          in: header
          description: Токен доступу користувача
          schema:
            type: string
        - name: formKey
          required: true
          in: path
          description: Унікальний ідентифікатор схеми UI-форми
          examples:
            '1':
              value: '1'
            user:
              value: user
            admin:
              value: admin
            edit-personprofile-firstbpmn:
              value: edit-personprofile-firstbpmn
            edit-personprofile-secondbpmn:
              value: edit-personprofile-secondbpmn
            add-startform:
              value: add-startform
            add-lab-file:
              value: add-lab-file
            sign-lab-file:
              value: sign-lab-file
            edit-lab-file:
              value: edit-lab-file
            sign-edited-lab-file:
              value: sign-edited-lab-file
            mdtuddm-12887:
              value: mdtuddm-12887
            mdtuddm-11573:
              value: mdtuddm-11573
            mdtuddm-16614-complex-validation:
              value: mdtuddm-16614-complex-validation
            day-and-datetime:
              value: day-and-datetime
            test-password:
              value: test-password
            form-with-all-fields-for-validation:
              value: form-with-all-fields-for-validation
            auto-form-with-files-upload-validation-soma:
              value: auto-form-with-files-upload-validation-soma
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormFieldsCheckDTO'
      responses:
        '200':
          description: OK з поверненням результату
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: number
                    example: 200
                  fields:
                    type: object
                    example:
                      name: true
                      email: true
        '422':
          description: Помилка валідації даних відносно схеми UI-форми
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  code:
                    type: string
                    example: VALIDATION_ERROR
                  details:
                    type: object
                    properties:
                      errors:
                        type: array
                        items:
                          properties:
                            field:
                              type: string
                              example: entities
                            message:
                              type: string
                              example: must not be null
                        example:
                          - field: entities
                            message: must not be null
info:
  title: API
  description: ''
  version: dev
  contact: {}
tags: []
servers: []
components:
  schemas:
    FormSchemaDTO:
      type: object
      properties:
        data:
          type: object
        processInstanceId:
          type: string
      required:
        - data
    FormFieldValidationDTO:
      type: object
      properties:
        fileName:
          type: string
        contentType:
          type: string
        size:
          type: number
      required:
        - fileName
        - contentType
        - size
    FormFieldsCheckDTO:
      type: object
      properties:
        fields:
          description: Перелік полів форми для первірки
          type: array
          items:
            type: string
      required:
        - fields