openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  /api/forms/{key}:
    get:
      tags:
        - form-schema-provider-controller
      summary: отримати ресурс по ідентифікатору
      description: Використовується для отримання об’єктів. Не змінює стан ресурсу
      operationId: getForm
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK з результатом
          content:
            '*/*':
              schema:
                type: object
                properties:
                  empty:
                    type: boolean
                additionalProperties:
                  type: object
        '401':
          description: Помилка аутентифікації (відсутній токен або цифровий підпис)
        '403':
          description: Недостатньо прав для виконання операції (роль користувача не передбачає доступу до даного ресурсу)
        '500':
          description: Внутрішня помилка сервера
        '501':
          description: Не імплементовано (використовується для заглушок)
    put:
      tags:
        - form-schema-provider-controller
      summary: змінити ресурс
      description: Використовується для зміни вже існуючого ресурсу з вказанням id
      operationId: updateForm
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: OK з результатом
    delete:
      tags:
        - form-schema-provider-controller
      summary: видалити ресурс
      description: Використовується для видалення ресурсу з вказанням id
      operationId: deleteFormByKey
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK з результатом
  /api/forms:
    post:
      tags:
        - form-schema-provider-controller
      summary: створити ресурс
      description: Використовується для створення ресурсу.
      operationId: saveForm
      parameters:
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        '200':
          description: OK з результатом
        '400':
          description: Некоректні вхідні дані (наприклад, неправильний тип поля)
        '401':
          description: Помилка аутентифікації (відсутній токен або цифровий підпис)
        '403':
          description: Недостатньо прав для виконання операції (роль користувача не передбачає доступу до даного ресурсу)
        '422':
          description: Помилка валідації, запит містить дані, що не відповідають правилам вказаним в домені
        '500':
          description: Внутрішня помилка сервера
        '501':
          description: Не імплементовано (використовується для заглушок)
components:
  schemas: {}
