@startuml

abstract class  Validator {
  {abstract} validate()
}

class TimeInfoPresenceValidator extends Validator{
  validate()
 }
class SealValidator extends Validator{
  validate()
 }

interface SignatureService {
  ValidationResult verify(String xAccessToken, String data, String signature) throws Exception;
  ValidationResult verifySeal(String data, String signature) throws Exception;
  SignResponseDto sign(String data) throws Exception
}

SignatureService *-- Validator

@enduml