@startuml
participant "Сервіс платформи" as client  order 10
participant "КЕП сервіс" as digital_ops  order 20
participant "АЦСК" as ca  order 30
skinparam responseMessageBelowArrow true

title Накладання системного підпису
  client -> digital_ops: Дані
    activate digital_ops
    digital_ops -> digital_ops: Обчислення хешу данних
     digital_ops -> ca: Запит мітки часу
     activate ca
     digital_ops <-- ca: мітка часу
     digital_ops -> ca: Запит списка відкликаних сертифікатів
     digital_ops <-- ca: Список відкликаних сертифікатів
     deactivate ca
    digital_ops -> digital_ops: Накладання цифрової печатки на хеш
    digital_ops -> client: Підпис
    deactivate digital_ops

@enduml