@startuml
participant "Сервіс платформи" as client  order 10
participant "КЕП сервіс" as digital_ops  order 20
participant "АЦСК" as ca  order 30
skinparam responseMessageBelowArrow true

title Перевірка підпису чиновника
  client -> digital_ops: Дані форми, підпис
    activate digital_ops
    digital_ops -> digital_ops: Обчислення хешу данних
    opt Отримання сертифікату у разі відсутності його у підписі
    digital_ops -> ca: Запит сертифікату
    activate ca
    digital_ops <-- ca: Сертифікат підпису
    deactivate ca
    end
    digital_ops -> digital_ops: Перевірка підпису та отримання данних про підписуючого
    digital_ops -> digital_ops: Перевірка наявності обов'язкових полів ПІБ/РНОКПП/ЄДРПОУ у підписі
    alt Помилка валідації
    client <-- digital_ops: Помилка відсутності ПІБ/РНОКПП/ЄДРПОУ
    end
    digital_ops -> digital_ops: Перевірка наявності мітки часу
    alt Помилка валідації
    client <-- digital_ops: Помилка відсутності мітки часу
    end
    digital_ops -> digital_ops: Перевірка відповідності мітки часу дозволеному інтервалу
    alt Помилка валідації
    client <-- digital_ops: Помилка перевищення інтервалу часу
    end
    digital_ops -> digital_ops: Перевірка відповідності даних користувача з ЕЦП даним в JWT токені (ПІБ/РНОКПП/ЄДРПОУ)
    alt Помилка валідації
    client <-- digital_ops: Помилка невідповідності власника ЕЦП даним в JWT токені
    end
    digital_ops -> client: Відповідь
    deactivate digital_ops

@enduml