= Архітектурний робочий розділ

== План робіт по технічній документації

* [ ] Внести описи та ключові функції до розділів підсистем Платформи та Реєстру
* [ ] Виявити статті розділу "Архітектура Платформи", які продубльовано в інструкціях користувачів та видалити дублікати
* [ ] Визначити актуальність залишку технічних статей у розділі "Архів технічної документації" та рознести по відповідним розділам або видалити
* [ ] Довнести дані до секцій "Складові підсистеми" на базі зібраної автоматичним шляхом інформації для розділів підсистем Платформи та Реєстру
* [ ] Фіналізувати структуру документування низькорівневого дизайну сервісу
* [ ] Створити референтний приклад документування низькорівневого дизайну сервісу
* [ ] Фіналізувати структуру документування _transition_-дизайну
* [ ] Задокументувати шаблон та структуру документування низькорівневого дизайну бібліотек
* [ ] Створити діаграму логічної архітектури Платформи
* [ ] Створити діаграму розгортання Платформи
* [ ] Створити сторінку розрахунку вартості ресурсів Платформи
* [ ] Створити набір типових візуальних діаграм у якості прикладу для уніфікації підходу до опису дизайну Платформи