= Архітектурний робочий розділ

== План робіт по технічній документації

* [x] Опис архітектурного процесу та дизайн-активностей
* [x] Контекстна діаграма Платформи
* [x] Бізнес-контекст / Концепція Платформи
* [x] Бізнес / доменний глосарій Платформи
* [x] Перелік загальних бібліотек Платформи
* [x] Актуальний перелік акторів / ролей користувачів
* [x] Технологічний стек Платформи
* [x] Перелік сервісів та підсистем Платформи
* [x] Структурна схема Платформи
* [ ] Підхід до документування низькорівневого дизайну сервісів Платформи [_Review_]
* [ ] Підхід до документування "_transition_" дизайну еволюції Платформи [_Review_]
* [ ] Підхід до структурування розділів з дизайном підсистем Платформи [_WIP_]
** [ ] Аналіз архівних статей технічної документації та переміщення у нову структуру архітектурної документації
** [ ] Заповнення секції "Складові підсистеми" на базі зібраної автоматичним шляхом інформації
** [ ] Заповнення рутових сторінок підсистем інформацією про функції, описом, тощо.
* [ ] Референтний приклад документування низькорівневого дизайну сервісу Платформи
* [ ] Логічна архітектура Платформи
* [ ] Діаграма розгортання Платформи
* [ ] Розрахунок вартості ресурсів Платформи
* [ ] Підхід до документування дизайну бібліотек Платформи
* [ ] Набір типових візуальних діаграм у якості прикладу для уніфікації підходу до опису дизайну Платформи