= Архітектурний процес

== Декомпозиція активностей

=== Цільові активності

* Аналіз вимог та формування _transition_-дизайнів (_FF: 0.3_)
* Опрацювання зовнішніх запитів на консалтинг (_FF: 0.3_)

=== Регулярні активності

* Формування архітектурної документації Платформи (_FF: 0.15_)
* Проведення архітектурного рев'ю (_FF: 0.1_)
* Підтримка команд розробки в реалізації _transition_-дизайнів (_FF: 0.1_)
* Загальний технологічний консалтинг команд розробки (_L2, L3, тощо._) (_FF: 0.1_)
* Організаційні проектні мітинги (_FF: 0.25_)

== Перелік регулярних мітингів

* Статус-мітинги архітектурної групи
* Зустрічі з МЦ
* ICE-оцінювання беклогу
* Презентація _transition_-дизайнів
* Архітектурна сесія

== Оцінювання аналізу та формування технічного дизайну

[NOTE]
https://kb.epam.com/display/MDTUDDM/Backlog+items+estimation+and+prioritezation

[IMPORTANT]
Необхідно відкалібрувати _estimate_time(Ease)_

[source]
----
DueDate = kick_off_date() + ideal_time_prediction(Ease)? / (8h * FocusFactor) + time(ArchReview) + time(SecReview)

Example #1:
 kick_off_date = 15.Feb
 ideal_time_prediction(6) = 56.4h

 DueDate = 15.Feb + 56.4h / (8h * 0.3) + 4h + 4h = 22.Mar

Example #2:
 kick_off_date = 10.Feb
 ideal_time_prediction(8) = 18h

 DueDate = 10.Feb + 18h / (8h * 0.3) + 4h + 4h = 23.Feb
----

== Розробка технічного дизайну

image::architecture-workspace/architecture-process.svg[]

== Розділи технічної документації

* xref:arch:architecture/platform-overview.adoc[Архітектурна документація] - _розділ з архітектурною документацією, яка відображає поточний стан версії Платформи_
* xref:arch:architecture-workspace/platform-evolution/overview.adoc[Еволюція Платформи] - _розділ для внесення transition-дизайнів, створених під реалізацію фіч для випуску нової версії Платформи_
* xref:arch:architecture-workspace/research/overview.adoc[Дослідження та прототипування] - _розділ для фіксації результатів досліджень та прототипів, виконаних у процесі розвитку Платформи_

== Принципи ведення документації

* Цілісне відображення актуального стану архітектури рішення для обраної версії
* Відсутність дублювання інформації як у межах _Antora_ документації та і з іншими базами знань (_Confluence_)
* Узгоджене використання єдиної термінології, визначеної у глосарії
* Єдиний підхід до структурування документації за принципом _top-down_ для рішення в цілому, підсистем та окремих компонент
* Єдиний підхід до структурування статей розділу дизайну підсистем та окремих компонентів
* Єдиний підхід до створення архітектурних діаграм (стиль, гамма, легенда, іменування, тощо.)
* Єдиний підхід до формування та структурування контенту статей опису "transition"-дизайну