= Архітектурний процес

== Розробка технічного дизайну

image::architecture-workspace/architecture-process.svg[]

== Розділи технічної документації

* xref:arch:architecture/platform-overview.adoc[Архітектурна документація] - _розділ з архітектурною документацією, яка відображає поточний стан версії Платформи_
* xref:arch:architecture-workspace/platform-evolution/overview.adoc[Еволюція Платформи] - _розділ для внесення transition-дизайнів, створених під реалізацію фіч для випуску нової версії Платформи_
* xref:arch:architecture-workspace/research/overview.adoc[Дослідження та прототипування] - _розділ для фіксації результатів досліджень та прототипів, виконаних у процесі розвитку Платформи_

== Принципи ведення документації

* Цілісне відображення актуального стану архітектури рішення для обраної версії
* Відсутність дублювання інформації як у межах _Antora_ документації та і з іншими базами знань (_Confluence_)
* Узгоджене використання єдиної термінології, визначеної у глосарії
* Єдиний підхід до структурування документації за принципом _top-down_ для рішення в цілому, підсистем та окремих компонент
* Єдиний підхід до структурування статей розділу дизайну підсистем та окремих компонентів
* Єдиний підхід до створення архітектурних діаграм (стиль, гамма, легенда, іменування, тощо.)
* Єдиний підхід до формування та структурування контенту статей опису "transition"-дизайну