== Загальні принципи реалізації
- Механізм дозволяє проводити CRUD операції відносно об'єктів доменної моделі
- Одночасне редагування регламенту реєстру як з використанням адмін порталу, так і шляхом зміни конфігураційних файлів в репозиторії регламенту
- Стан структури БД і метаданих повністю відображений DataModelSnapshot документами
- Структура DataModelSnapshot json документів описана за допомогою JSONSchema
- DataModelSnapshot документи (з JSONSchema) мають бути використані як структура обміну даними на рівні RestAPI між Front-End додатком та Backend сервісами
- Вирішення конфліктів при редагуванні регламенту реєстру з використанням адмінпорталу необхідний лише на рівні DataModelSnapshot документів
- Підтримання консистентними DataModelSnapshot моделі та liquibase changelog
- Процес синхронізації DataModelSnapshot моделі по liquibase changelog є ідемпотентним
- Зміни внесені через адміністративний портал знаходяться в окремому liquibase changeset. Ідентифікатор версії-кандидату є частиною liquibase changeset id атрибуту.

