@startuml
skinparam shadowing false
skinparam DatabaseBackgroundColor white
skinparam DatabaseBorderColor #2688d4
skinparam QueueBackgroundColor white
skinparam QueueBorderColor #2688d4
skinparam NoteBackgroundColor white
skinparam NoteBorderColor #2688d4
skinparam sequence {
    ArrowColor #2688d4
    ActorBorderColor #2688d4
    LifeLineBorderColor #2688d4
    ParticipantBorderColor #2688d4
    ParticipantBackgroundColor white
    BoxBorderColor #2688d4
    BoxBackgroundColor white
}

participant "Клієнтський додаток\n кабінету користувача" as portal
participant "Kong \nAPI Management" as kong
participant "Сервіс управління \nзадачами користувачів" as user_task_management
participant "Сервіс виконання \nбізнес-процесів" as bpms
database "Redis\nin-memory сховище \n(bpm-form-submissions.*)" as redis

activate portal
  portal -> kong: Отримання мета-даних \nта збережених даних UI-форми задачі: \nGET /api/task/{id}
  activate kong
    kong -> user_task_management: GET /api/task/{id} \n*X-Access-Token
      activate user_task_management
        user_task_management -> bpms: Отримання мета-даних задачі \n<taskId>
        bpms --> user_task_management: Мета-дані задачі БП
        note left
          {
            "id": "",
            "taskDefinitionKey": "",
            "formKey": "",
            "name": "",
            "assignee": ""
          }
        end note
        user_task_management -> redis: Отримання збережених даних UI-форми задачі\n<processInstanceId, taskDefinitionKey>
        redis --> user_task_management: Дані, внесені при виконанні задачі БП
        note left
          {
            "data": {
              ...
            }
          }
        end note
        user_task_management -> user_task_management: Формування результату
        user_task_management --> kong: 200: Мета-дані та дані форми задачі
        kong --> portal: 200 - Мета-дані та дані форми задачі
      deactivate user_task_management
  deactivate kong
deactivate portal
@enduml