@startuml
skinparam shadowing false
skinparam DatabaseBackgroundColor white
skinparam DatabaseBorderColor #2688d4
skinparam QueueBackgroundColor white
skinparam QueueBorderColor #2688d4
skinparam NoteBackgroundColor white
skinparam NoteBorderColor #2688d4
skinparam sequence {
    ArrowColor #2688d4
    ActorBorderColor #2688d4
    LifeLineBorderColor #2688d4
    ParticipantBorderColor #2688d4
    ParticipantBackgroundColor white
    BoxBorderColor #2688d4
    BoxBackgroundColor white
}

participant "Клієнтський додаток\n кабінету користувача" as portal
participant "Kong \nAPI Management" as kong
participant "Сервіс управління \nзадачами користувачів" as user_task_management
participant "Сервіс валідації \nданих UI-форм" as form_submission_validation
database "Redis\nin-memory сховище \n(bpm-form-submissions.*)" as redis

activate portal
  portal -> kong: Проміжне збереження даних UI-форми задачі: \nPOST /api/task/{id}/save
  note left
    {
      "data": {
        ...
      }
    }
  end note
  activate kong
    kong -> user_task_management: POST /api/task/{id}/save \n*X-Access-Token
      activate user_task_management
        user_task_management -> form_submission_validation: Валідація даних згідно схеми UI-форми: \nPOST /api/form-submissions/{form-key}/validate
        note left
          {
            "data": {
              ...
            }
          }
        end note
        form_submission_validation --> user_task_management: Результат валідації
        alt Валідацію даних пройдено
          user_task_management -> redis: Збереження проміжних даних UI-форми задачі\n<processInstanceId, taskDefinitionKey>
          redis --> user_task_management
          user_task_management --> kong: 200
          kong --> portal: 200 - Дані успішно збережено
        else Валідацію даних не пройдено
          user_task_management --> kong: 422
          kong --> portal: 422 - Валідацію даних не пройдено
        end
      deactivate user_task_management
  deactivate kong
deactivate portal
@enduml