= Компонент Select

TIP: Очікується оновлення документа.

== Основні положення

=== Формат даних

.Submission
[source,typescript]
----
Object
// Приклад: {id: 123, label: 'Label' }
----

=== API для JS вставок

==== Отримання опцій у JS вставках

.Latest Select
[source,typescript]
----
// Отримати поточні опції можна через виклик getFormattedOptions()
// Це масив об'єктів типу { value: Option }, де Option - сам об'єкт опції, наприклад с API ендпоінту
const options: Array<{ value: Option }> = instance.getFormattedOptions();
----

.Legacy Select
[source,typescript]
----
// Отримати поточні опції можна через параметр selectOptions
// Це масив об'єктів типу { value: Option }, де Option - сам об'єкт опції, наприклад с API ендпоінту
const options: Array<{ value: Option }> = instance.selectOptions;
----

== Головні функції

=== Custom Default Value
[sidebar]
--
У цій функції використовується JS вставка. xref:bp-modeling/forms/components/general/eval.adoc[Див.]
--

=== Calculated Value

[sidebar]
--
У цій функції використовується JS вставка. xref:bp-modeling/forms/components/general/eval.adoc[Див.]
--

== Часті сценарії використання

=== Вибір з API-еднпоінту

xref:bp-modeling/forms/components/select/bp-select-component-form-io.adoc[Окрема стаття]

=== Обрати єдиний елемент по фільтру

Досить часто необхідно відфільтрувати з API один елемент та одразу обрати його. Так можно організувати сценарій однозначного вибору одного поля відповідно до значення іншого. Можна використати перевірку ``instance.getFormattedOptions().length === 1`` -  якщо у нас в списку тільки один елемент, ми одразу присвоюємо цей елемента в значення ``value``.

Необхідно заповнити значення параметра *Calculated Value* таким чином:

.Latest Select
[source,javascript]
----
if (instance.getFormattedOptions().length === 1) {
  value = instance.getFormattedOptions()[0].value;
}
----

.Legacy Select
[source,javascript]
----
if (instance.selectOptions.length === 1) {
  value = instance.selectOptions[0].value;
}
----
