= Автентифікація посадових осіб, єдина для групи реєстрів завдяки ручним налаштуванням

== Загальний опис
При роботі посадової особи в декількох реєстрах, які по своїй природі є спорідненими, виникає потреба виконувати
автентифікацію в кожен кабінет окремо використовуючи для цього один і той самий ключ, але виконуючи логін в різних кабінетах.
Для спрощення досвіду користувача необхідно розробити підхід для забезпечення SSO в рамках групи реєстрів для мінімізації
однотипних дій користувача.

== Функціональні сценарії
* Створення _Федерації споріднених реєстрів_ для SSO адміністратором платформи
* Налаштування SSO для _Федерації споріднених реєстрів_ адміністратором платформи
* Автентифікація посадової особи в кабінет за допомогою ключа
* Автентифікація посадової особи в кабінет за допомогою id.gov.ua
* Автореєстрація посадової особи
* Створення користувачів адміністратором реєстру через _Підсистему управління користувачами та ролями_
* Створення користувачів адміністратором реєстру через _Підсистему моделювання регламенту реєстру_ (імпорт csv файлу)
* Налаштування ролей користувачів адміністратором реєстру
* Налаштування атрибутів користувачів адміністратором реєстру

== Ролі користувачів
* Адміністратор платформи
* Адміністратор реєстру
* Адміністратор _Федерації споріднених реєстрів_
* Посадова особа

== Загальні принципи та положення
* _Споріднені реєстри_ мають спільну базу користувачів посадових осіб
* Посадова особа повинна виконувати логін 1 раз коли працює в _Споріднених реєстрах_
* Рішення повинно максимально бути побудовано на ручних налаштуваннях по інструкції
* До _Федерації споріднених реєстрів_ можуть бути підключені як нові реєстри, так і існуючі реєстри з власною базою користувачів
* Налаштування ролей посадових осіб виконується на рівні  _Ріалму реєстру федерації_
* Налаштування ідентифікуючих системних атрибутів (fullName, edrpou, drfo) виконується на рівні _Мастер-ріалму федерації споріднених реєстрів_
* Налаштування додаткових атрибутів виконується на рівні _Ріалму реєстру федерації_
* _Мастер-ріалм федерації споріднених реєстрів_ підтримує режим автореєстрації посадових осіб
* _Мастер-ріалм федерації споріднених реєстрів_ підтримує інтеграцію з id.gov.ua для автентифікації посадових осіб
* _Identity provider link_ - посилання в обліковому записі посадової особи в _Ріалмі реєстру федерації_ на обліковий
запис в _Мастер-ріалмі федерації споріднених реєстрів_
* При перестворені облікового запису в _Мастер-ріалмі федерації споріднених реєстрів_ при існуючому _Identity provider
link_ в _Ріалмі реєстру федерації_ обліковий запис в _Ріалмі реєстру федерації_ повинен бути оновлени з
новим _Identity provider link_
* Адміністратор _Федерації споріднених реєстрів_ виконує налаштування SSO для _Федерації споріднених реєстрів_ та має
адмін доступ на _Мастер-ріалм федерації споріднених реєстрів_
* Права Адміністратору _Федерації споріднених реєстрів_ надає _Адміністратор платформи_ в ручному режимі в _Підсистемі
управління користувачами та ролями_
* Налаштування автентифікації у _Підсистемі управління Платформою та реєстрами_ не підтримуються при ручних налаштуваннях
_Федерації споріднених реєстрів_
* Всі ручні налаштування повинні бути зроблені у відповідних Helm чартах реєстрів. Налаштування _Мастер-ріалм федерації
споріднених реєстрів_ повинно бути занесено в один зі _Споріднених реєстрів_.
* Keycloak Client CR в _Мастер-ріалмі федерації споріднених реєстрів_ задається на рівні helm chart _Ріалму реєстру
федерації_. Для цього Адміністратор платформи повинен додати відповідні права SA (Keycloak Client CR) з назвою
<registry-name>-admin в проекті _user-management_.

[TIP]
--
Детальніше з концептами та принципами Федерації споріднених реєстрів можна ознайомитися за посиланням xref:arch:architecture-workspace/research/registry-federation/registry-federation.adoc[]
--

== Високорівневий дизайн рішення

=== Компонентна діаграма
image:architecture/platform/operational/user-management/platform-evolution/registry-federation/component.svg[]

|===
|Компонент |Назва |Тип |Розташування  |Опис

|Identity Provider
|federation-idp
|keycloak-oidc
|Реєстровий ріалм
|Інтеграція з мастер ріалмом для ідентифікації

|Authenticator Execution
|federation-idp
|Identity Provider Redirector
|Реєстровий ріалм / Authentication dso-officer-auth-flow
|У конфігурації налаштовується ідентіті провайдер federation-idp за замовчуванням

|Identity Provider Mapper
|fullName
|Attribute Importer
|Реєстровий ріалм / Identity Provider federation-idp
|Імпорт атрибута fullName з мастер ріалму при автентифікації користувача

|Identity Provider Mapper
|drfo
|Attribute Importer
|Реєстровий ріалм / Identity Provider federation-idp
|Імпорт атрибута drfo з мастер ріалму при автентифікації користувача

|Identity Provider Mapper
|edrpou
|Attribute Importer
|Реєстровий ріалм / Identity Provider federation-idp
|Імпорт атрибута edrpou з мастер ріалму при автентифікації користувача

|Realm
|registry-federation-<group-name>
|Realm
|Keycloak
|Мастер Ріалм для спільного управління користувачами споріднених реєстрів та SSO. <group-name> - назва обрана для
спільної групиреєстрів

|Client
|<registry-name>-client
|openid-connect
|registry-federation-<group-name> Realm
|Клієнт для інтеграції реєстровий ріалм - мастер ріалм. Конфігурація повинна бути погоджена з налаштуванням
Identity Provider federation-idp в реєстровому ріалмі (client id, client secret, redirect uri).
<registry-name> - назва реєстру в федерації

|Client Scope
|dso-identity
|openid-connect
|registry-federation-<group-name> Realm
|Client Scope для одноразового налаштування мапперів fullName, drfo, edrpou з мастер ріалму. Створений client scope
необхідно вказати як client scope за замовчуванням (Default Client Scopes)

|Client Scope Mapper
|fullName
|User Attribute
|registry-federation-<group-name> Realm / Client Scope dso-identity
|Створюється для мапінгу атрибута fullName з мастер ріалму

|Client Scope Mapper
|drfo
|User Attribute
|registry-federation-<group-name> Realm / Client Scope dso-identity
|Створюється для мапінгу атрибута drfo з мастер ріалму

|Client Scope Mapper
|edrpou
|User Attribute
|registry-federation-<group-name> Realm / Client Scope dso-identity
|Створюється для мапінгу атрибута edrpou з мастер ріалму

|Authentication
|dso-officer-auth-flow
|Top Level Flow / generic
|registry-federation-<group-name> Realm
|Створюється з аналогічними налаштуваннями як і в реєстровому ріалмі для dso-officer-auth-flow.
Примітка: dso-officer-auth execution повинен бути з вимкненим Required типом або під обгорткою Authentication Flow
з типом Alternative для можливості первинної перевірки по Cookie та SSO

|Authentication
|federation-idp first broker login
|Top Level Flow / generic
|Реєстровий ріалм
|Authentication flow для першого входу через federation-idp. Повинен бути вибраний як first broker login в налаштуваннях
Identity Provider federation-idp

|Authenticator Execution
|registry-federation-authenticator
|registry-federation-authenticator
|Реєстровий ріалм / Authentication federation-idp first broker login
|Автентифікатор для обробки першого входу через мастер ріалм. Потребує додаткової розробки

|===

=== Діаграма діяльності registry-federation-authenticator
image:architecture/platform/operational/user-management/platform-evolution/registry-federation/activity.svg[]

.Приклад можливого видалення idp provider link
[source, java]
----
  @Override
  protected void authenticateImpl(
      AuthenticationFlowContext context,
      SerializedBrokeredIdentityContext serializedCtx,
      BrokeredIdentityContext identityContext) {
    // delete existing identity provider link for user
    context.getSession().users().removeFederatedIdentity(context.getRealm(), context.getUser(), identityContext.getIdpConfig().getAlias());
    ...
    }
----

==== Конфігурація registry-federation-authenticator

|===
|Назва |Тип |Опис

|Alias
|String
|Назва конфігурації

|Enable officer auto registration
|Boolean
|Параметр для включення режиму автореєстрації посадових осіб

|Default role for officer auto registration
|Array of Strings
|Перелік ролей для автореєстрації посадових осіб

|===


[NOTE]
====
При використанні Identity Provider першим логіном вважається ситуація коли у жодному обліковому записі реєстрового реалму
не знайдений identity provider link на обліковий запис в мастер ріалмі
====

== Обсяг робіт

=== Попередня декомпозиція
* Розробка registry-federation-authenticator (розширення AbstractIdpAuthenticator) з випуском нової версії Кейклоак
* Розробка інструкцій для ручних налаштувань _Федерації споріднених реєстрів_ з наступним сценарієм:
** Реєстри нові (користувачів в _Ріалмах реєстру федерації_ ще немає)
** Автентифікація в _Мастер-ріалм федерації споріднених реєстрів_ виконується по підпису
** Користувачі повинні бути попередньо створені в _Мастер-ріалм федерації споріднених реєстрів_ в _Підсистемі управління
користувачами та ролями_ (без імпорту через csv файл)
** На рівні _Ріалму реєстру федерації_ налаштована автореєстрація
** Налаштування атрибутів та ролей відбувається на рівні _Ріалму реєстру федерації_ після першого логіну користувача


=== Обмеження рішення
* Більшість налаштувань виконується вручну
* При помилці в _Ріалмі реєстру федерації_ буде показана стандартна сторінка Кейклоак з помилкою
* Створення користувачів відбувається в ручному режимі _Мастер-ріалм федерації споріднених реєстрів_
в _Підсистемі управління користувачами та ролями_
* Імпорт користувачів через файл може бути виконаний тільки на _Ріалму реєстру федерації_
* При вході в кабінет немає можливості обрати, чи виконати логін в _Ріалмі реєстру федерації_ чи в
_Мастер-ріалм федерації споріднених реєстрів_


=== Додаткові задачі на технічний борг
* Зробити можливість вибору режиму ALTERNATIVE для execution з типом dso-officer-auth-flow
* IdGovUaOfficerAuthenticator. При включеній автореєстрації і випадку, коли буде знадено за атрибутами більше ніж одного
користувача, буде створено ще одного користувача
* Переробити підхід до призначення ролей за замовчуванням на стандартний замість логіки в автентифікаторах
* Перейти на единий автентифікатор по обробці першого входу через idp для всіх кейсів
* IdGovUaOfficerAuthenticator. При генерації помилки перекидає на сторінку з dso автентифікатором навіть якщо за
замовчуванням стоїть idp id.gov.ua