= Інтеграційні розширення

== Контракт взаємодії з Дата Фабрикою
Додатково, до викликів автоматично додаються системні змінні контексту виклику у якості заголовків:

- *X-Access-Token* - Токен доступу до системи користувача, під яким виконується операція
- *X-Source-System* - Назви підсистеми, яка виконує запит ("*Low-code Platform*")
- *X-Source-Application* - Назва компоненти підсистеми, яка ініціює запит ("*business-process-management*")
- *X-Source-Business-Process* - Назва бізнес-процесу, яку визначив адміністратор регламенту при моделюванні (_Process Name_)
- *X-Source-Business-Process-Definition-Id* - Унікальний ідентифікатор бізнес-процесу, яку визначив адміністратор регламенту при моделюванні (_Process Id_)
- *X-Source-Business-Process-Instance-Id* - Автоматично згенерований UUID-ідентифікатор екземпляру бізнес-процесу, в рамках якого виконується запит (Генерується автоматично)
- *X-Source-Business-Activity* - Назва сервісної задачі, яку визначив адміністратор регламенту при моделюванні (_Name_)
- *X-Source-Business-Activity-Definition-Id* - Унікальний ідентифікатор сервісної задачі, яку визначив адміністратор регламенту при моделюванні (_Id_)
- *X-Source-Business-Activity-Instance-Id* - Автоматично згенерований UUID-ідентифікатор екземпляру сервісної задачі бізнес-процесу, в рамках якої виконується запит

Додатково, в залежності від конектора, можуть додаватися наступні HTTP заголовоки:

- _X-Digital-Signature_ - Посилання на Ceph документ в якому зберігається підпис користувача, який був накладений на дані UI-форми при внесенні
- _X-Digital-Signature-Derived_ - Посилання на Ceph документ в якому зберігається системний підпис, який було автоматично накладено на тіло запиту