= Каталог типових розширень для моделювання бізнес-процесів
---------------------------------------------------------

== Загальний опис

Каталог містить типові розширення які дозволяють створювати заздалегідь визначені конфігурації для елементів BPMN (система умовних позначень (нотація) та їх опису для моделювання бізнес-процесів), такі як сервісні та користувацькі задачі. Після застосування через панель властивостей вони надають налаштовані користувацькі вхідні параметри для користувача.

.Вміст каталогу:
- Базові розширення.
- Інтеграційні розширення.
- Перелік плагінів.

== Загальні принципи

- Спрощення розробки бізнес-процесів завдяки використанню елементів типових розширень та плагінів у https://camunda.com/bpmn/tool[Camunda Modeler].

== Загальний опис типових розширень

- Типові розширення представлені у вигляді `JSON` файлів, та можуть мати наступній вигляд:

image::arch:architecture/registry/administrative/regulation-management/services/business-process-modeler-extensions/list-json.svg[]

- `Camunda Modeler` надає можливість використовувати елементи типових розширень при розробці бізнес-процесів, достатньо лише вибрати бажаний шаблон з переліку та застосувати:

image::arch:architecture/registry/administrative/regulation-management/services/business-process-modeler-extensions/template-list.svg[]

[NOTE]
Більш докладно про створення та застосування типових розширень можна ознайомитися xref:business-process-modeler-extensions:development.adoc[тут]

== Розповсюдження типових розширень

- Простий CI процес який зводиться до створення jar файлу та публікації його в Nexus

image::arch:architecture/registry/administrative/regulation-management/services/business-process-modeler-extensions/extension-lib-pipeline.svg[]

- Для того щоб отримати каталог типових розширень з Nexus, потрібно:

* Перейти за https://nexus-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/#browse/browse:extensions[посиланням] та знайти папку `business-process-modeler-extensions`.

* З'явиться список папок з ім'ям `version.build` (наприклад, 0.0.1-SNAPSHOT.12). Виберіть папку з останньою версією.
* У папці, виберіть файл .zip.
* На вкладці «Summary» клацніть кнопкою миші посилання «Path». Почнеться скачування zip-архіву.
* Каталог матиме наступну структуру:

image::arch:architecture/registry/administrative/regulation-management/services/business-process-modeler-extensions/bpme-dir.svg[]

* Розпакуйте з заміною завантажений zip-файл в підпапку `resources` вашого локального  https://github.com/camunda/camunda-modeler/tree/master/docs/search-paths#app-data-directory[{APP_DATA_DIRECTORY}] або https://github.com/camunda/camunda-modeler/tree/master/docs/search-paths#user-data-directory[{USER_DATA_DIRECTORY}] каталогу.