//:imagesdir: ../../../../images

= Доступ до контенту файлів реєстру через зовнішні API

[IMPORTANT]
--
Сторінка технічної документації є баченням майбутньої реалізації, актуальність якого може бути застарілою.
--

NOTE: Work In Progress

== Загальний опис
У цій статті буде розглянута реалізація можливості віддавати контент файлів збережених у реєстрі через зовнішні API. Наразі ця можливість відсутня і контент файлів можливо отримати тільки з бізнес процесу який є частиною реєстру в якому зберігається файл.

== Актори та ролі користувачів
* Розробник регламенту
* Зовнішні системи

== Загальні принципи та положення

* Поведінка і контракт існуючих критеріїв пошуку не змінюється. 
* Зберігається зворотна сумісність конфігурації критеріїв пошуку.    

== Функціональні сценарії

* Налаштування критеріїв пошуку
* Генерація сервісів критеріїв пошуку
* Доступ до контенту файлів через публічний АРІ
* Доступ до контенту файлів через міжреєстрову взаємодію без Трембіти
* Доступ до контенту файлів через міжреєстрову взаємодію через Трембіту
* Доступ до контенту файлів для публічної форми (майбутня функціональність) з EditGrid 

== Поточна реалізація

image::architecture-workspace/platform-evolution/rest-file-transfer/file-transfer-current.drawio.svg[]

В поточній реалізації доступ до файлів реалізований лише для підсистеми виконання бізнес-процесів. Працює він наступним чином:
 
 * Підсистема виконання бізнес-процесів робить виклик на registry-rest-api і окрім всього іншого передає в хедері запиту ідентифікатор бізнес-процесу
 * registry-rest-api по хедеру розуміє що запит прийшов з підсистеми виконання бізнес-процесів
 * registry-rest-api отримує дані що запитані з БД реєстру.
 * Якщо серед даних є дані типу _type_file_, тобто дані що містять ідентифікатори файлів в бакеті file-ceph-bucket, то всі ці файли копіюються у бакет lowcode-file-storage по шляху який дорівнює ідентифікатор бізнес-процесу та який є доступним для підсистеми виконання бізнес-процесів.
 * Підсистема виконання бізнес-процесів отримує відповідь з даними що запитані, включаючи ідентифікатори файлів.
 * Підсистема виконання бізнес-процесів читає вміст файлів з lowcode-file-storage

Всі інші запити до registry-rest-api та його копій (ext та pub) не отримують ідентифікатор бізнес-процесу в хедері та не повертають ідентифікатори файлів (замість них пусте поле) та не копіюють файли з file-ceph-bucket в lowcode-file-storage.

Таким чином для зовнішніх систем не передбачено жодного механізму для отримання контенту файлів що збережені в реєстрі.

== Варіанти рішення

=== Повернення контенту як додаткового атрибуту типу _type_file_ в Base64

При формуванні відповіді додавати контент в структуру type_file новим атрибутом.

.Приклад
[source, yaml]
----
"someFile": [
    {
      "id": "string",
      "checksum": "string"
      "content": "V2h5IHdvdWxkIHlvdSBkZWNvZGUgaXQ/"
    }
----

==== Переваги
* Проста реалізація. Не потребує змін за межами підсистеми управління даними реєстру.
* Безпека гарантується наявною авторизацією 

==== Недоліки
* Значно збільшене навантаження та риск відмови сервісів API. SC можуть повертати багато рядків що містять файли. Додавання контенту для них зробить відповідь надмірно великою.
* Не дає можливості клієнту API обирати завантажувати йому контент файлу чи ні

=== Повернення контенту як presigned посилання на _file-ceph-bucket_

Генерувати https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html[presigned URL] з обмеженим часом дії та повертати його.

.Приклад
----
<host>:<port>/<bucket>/<key>?AWSAccessKeyId=<access_key>&Signature=<signature>&Expires=<expires>
----

==== Переваги
* Стандартний метод для файлів що зберігаються в S3 сумісному сховищі.
* Достатні гарантії безпеки. Посилання діє обмежений час і щоб отримати посилання користувач має пройти авторизацію (включно з RBAC) на доступ до даних реєстру що містять посилання на файл.

==== Недоліки
* Необхідно відкривати CEPH S3 REST API для зовнішніх систем.
* Нетривіальна взаємодія через ШБО. Пускати S3 REST через ШБО? Генерувати якийсь SOAP? Віддавати файли повз ШБО?

=== Повернення контенту як посилання на новий rest/soap endpoint

Створювати REST ендпоинт для отримання контенту файлу за ідентифікатором та повертати цей ідентифікатор у відповіді на запити по SC чи сутностям що мають файли.

Тут головне питання що може бути таким ідентифікатором файлу.

Якщо це ceph id  - неможливо провести авторизацію так як вона налаштована тільки для сутностей в БД

Якщо це id запису в БД + назва колонки (типу `GET /licenses/{id}/licenseFileContent`) - можна провести авторизацію, але як виявилося це не може бути ідентифікатором. По перше не всі SC повертають id і якщо його нема у view то ми не можемо його отримати і в registry-rest-api. По друге - ми дозволяємо і більш того маємо в референтних прикладах можливість створювати масив файлів. Таким чином в одному запису в БД в одній колонці можуть бути декілька файлів.

== Корисні посилання

https://github.com/nordic-institute/X-Road/issues/209#issuecomment-538424890[x-road(Трембіта) - рекомендації з передачі фалів через ШБО]

https://github.com/vrk-kpa/xroad-fileservice[x-road(Трембіта) - приклад сервісу що передає фали через ШБО]