== Базові принципи

* Розробка регламенту реєстру відбувається з використанням адміністративного порталу, що дозволяє будувати конфігурацію типового регламенту реєстру. Інтерфейс адміністративного порталу дозволяє виконувати всю необхідну конфігурацію регламенту реєстру без володіння глибокими уміннями програмування.

* Розробка регламенту реєстру ведеться шляхом створення версій-кандидатів регламенту реєстру, що містять зміни до регламенту реєстру.

* Одна версія-кандидат регламенту реєстру може розроблятися декількома користувачами одночасно.

* Можлива розробка декількох версій-кандидатів одночасно.

* Версія кандидат регламенту реєстру має містити відповідні автоматизовані сценарії тестування внесених змін. Дані сценарії виконуються автоматизовано в Jenkins pipeline регламенту реєстру. Результат виконання відображається в адмін порталі.

* Можливість автоматичного та напівавтоматичного випуску оновлень буде досягнута шляхом конфігурації існуючого механізму просування змін між оточеннями з використанням ControlPlane. Автоматичний випуск оновлень в якості показника працездатності версії буде використовувати автоматизовані сценарії тестування.

* Існує можливість розгортання тимчасового реєстру по регламенту з версії-кандидату для перевірки внесених змін. Під час цього використовується тимчасовий тенант-реєстр з розгорнутою лише операційною зоною. Кількість тимчасових тенант-реєстрів, працюючих одночасно, обмежена.

* При розгортанні тимчасового тенант оточення використовується механізм анонімізації даних, отриманих с промислового оточення.

* Окремо існуючий backup тенант в prod оточенні буде завжди містити останню версію змін з мастер версії регламенту реєстру.

* Всі зміни що вносяться до регламенту реєстру повинні пройти всі етапи тестування, що передбачені процесом релізу.

* Hotfixes можуть відбуватись на staging оточенні. Такі ж самі зміни повинні бути виконані на development оточенні.

* Можливість внесення змін по деяких частинах регламенту реєстру може обмежена для об’єктів, що були створені поза межами поточної версії-кандидату регламенту реєстру. Об’єкти, що були створені в рамках поточної версії-кандидату регламенту реєстру можуть бути змінені без обмежень.

* Адмін портал дозволяє переглядати зміни версії-кандидату відносно мастер версії регламенту реєстру.

* Адмін портал дозволяє проводити актуалізацію версії конфігураційних файлів по мастер версії шляхом виконання rebase операції в git.

* Зміни, що внесені без використання адмін порталу можуть не відображатись в історії змін версії кандидату регламенту реєстру.

* Під час роботи над версією-кандидатом регламенту реєстру можливе внесення змін в конфігураційні файли регламенту реєстру без використання адмін порталу.

* Конфлікти змін в конфігураційних файлах будуть вирішуватись з використанням gerrit/git.

* Резервне копіювання стану реєстру відбувається в момент зміни стану регламенту реєстру. Резервне копіювання складається з двох частин:
** Збереження версії регламенту реєстру шляхом створення тегів в git
** Резервне копіювання БД

* Відтворення дефектів на тимчасовому тенант оточенні можливе шляхом розгортання відповідної версії регламенту реєстру використовуючи tag в git та відтворення стану БД с резервної копії