== Ключові вимоги

- Пришвидшити розробку регламентів _типових_ реєстрів
- Знизити вимоги до кваліфікації команди моделювання регламентів _типових_ реєстрів
- Виключити необхідність встановлення додаткового ПЗ на локальній машині для початку розробки регламенту
- Централізувати розробку та адміністрування усіх складових регламенту реєстру у єдиному інтерфейсі
- Уніфікувати процес автентифікації посадових осіб / адміністраторів регламенту за допомогою КЕП
- Забезпечити можливості ведення паралельної розробки декількох послуг реєстру
- Забезпечити можливості ведення паралельної розробки послуги реєстру декількома розробниками одночасно
- Забезпечити можливості актуалізації стану регламенту згідно останніх внесених змін для послуги у процесі розробки
- Забезпечити можливості тестування та демонстрації послуг у процесі розробки з використанням анонімізованих даних реєстру
- Забезпечити можливості перегляду, тестування та демонстрації останньої версії-кандидата регламенту реєстру
- Забезпечити цілісність регламенту реєстру у процесі розробки
- Забезпечити автоматизовану перевірку якості внесених змін до регламенту
- Забезпечити процес інспекції внесених змін до регламенту
- Візуалізувати історію внесення змін до регламенту та випуску оновлень
- Забезпечити можливості внесення змін у вигляді коду до _складних_ регламентів командою розробки через службові інтерфейси
- Забезпечити можливості автоматичного та напівавтоматичного випуску оновлень регламенту реєстру
- Забезпечити можливості відтворення дефектів з промислового оточення та випуску оновлень з виправленнями
- Унеможливити внесення прямих змін до регламенту на промисловому оточенні
- Забезпечити створення резервної копії регламенту при випуску оновлень
- Забезпечити можливість відновлення регламенту з резервної копії