== Базові принципи

- Розбробка регламенту реєстру ведеться шляхом створення версій-кандидатів регламенту реєстру, що містять зміни до регламменту реєстру.
- Одна версія-кандидат регламенту реєстру може розроблятися декількома користувачами одночасно.
- Можлива розробка декількох версій-кандидатів одночасно.
- Існує можливість розгортання тимчасового реєстру по регламенту з версії-кандидату для перевірки внесених змін. Під час цього використовується тимчасовий тенант реєстр з розгорнутою лише операційною зоною. Кількість тімчасових тенент-реєстрів працюючих одночасно обмежена.
- Можливість внесення змін по деяким частинам регламенту реєстру може обмежена для об'єктів, що були створені поза межами поточної версії-кандидату регламенту реєстру. Об'єкти, що були створені в рамках поточної версії-кандидату регламенту реєстру можуть бути змінені без обмежень.
- Під час роботи над версією-кандидатом регламенту реєстру можливе внесення змін в регламент реєстру шляхом внесення змін в конфігураційні фали регламенту реєстру без використання адмін порталу. Такі зміни можуть бути внесені через git. Зміни, що внесені в версію-кандидат регламенту реєстру можуть не відображатись на інтерфейсі адмін порталу та в історії внесених змін.
- Адмін портал дозволяє вирішувати конфлікти тільки по змінам, що були внесені через адмін портал. Конфлікти по конфігураційним файлам, що були змінені розробниками реєстру через git повинні бути вирішені з використанням gerrit/git.