@startuml
skinparam shadowing false
skinparam DatabaseBackgroundColor white
skinparam DatabaseBorderColor #2688d4
skinparam QueueBackgroundColor white
skinparam QueueBorderColor #2688d4
skinparam NoteBackgroundColor white
skinparam NoteBorderColor #2688d4
skinparam EntityBackgroundColor white
skinparam EntityBorderColor #2688d4
skinparam ControlBackgroundColor white
skinparam ControlBorderColor #2688d4
skinparam ActorBackgroundColor white

skinparam sequence {
    ArrowColor #2688d4
    ActorBorderColor #2688d4
    LifeLineBorderColor #2688d4
    ParticipantBorderColor #2688d4
    ParticipantBackgroundColor white
    BoxBorderColor #2688d4
    BoxBackgroundColor white
}

actor "Адміністратор \nплатформи" as platform_admin
participant "Control Plane \nConsole \n**(control-plane)**" as control_plane

participant "Зовнішній \nПоштовий Сервер \n**(external-mail-server)**" as external_mail_server

entity "OpenShift \n'control-plane' \nnamespace" as openshift_control_plane_namespace

box Platform Jenkins
  control "Пайплайн створення реєстру" as registry_creation_pipeline
end box

participant "Платформенний \nПоштовий Сервер \n**(platform-mail-server)**" as platform_mail_server

entity "OpenShift \n'<registry>' \nnamespace" as openshift_registry_namespace
participant "Сервіс нотифікацій \nкористувачів \n**(notification-service)**" as notification_service

platform_admin -> control_plane: Створення / Редагування конфігурації реєстру
activate control_plane
control_plane -> control_plane: Внесення назви реєстру (**<platform-name>**)
control_plane -> control_plane: Вибір опції використання платформенного \nабо зовнішнього поштового сервера

alt Обрано опцію використання зовнішнього поштового серверу
  control_plane -> control_plane: Внесення даних налаштувань SMTP поштового сервера
  note left
    "smtp.host": '<external-mail-server-host>'
    "smtp.port": '<external-mail-server-port>'
    "username": '<username>'
    "password": '<password>'
  end note

  control_plane -> external_mail_server: Тестування підключення
  external_mail_server -> control_plane: Результат підключення

  alt Підключення до зовнішнього поштового серверу виконано успішно
  control_plane -> control_plane: Формування даних для створення ConfigMap\n**<registry_name>-notification-service-email-channel-configuration**
  control_plane -> openshift_control_plane_namespace: Створення ConfigMap\n**<registry_name>-notification-service-email-channel-configuration**
  note left
    "notifications.email.host": '<external-mail-server-host>'
    "notifications.email.port": '<external-mail-server-port>'
    "notifications.email.properties.mail.smtp.auth": true
    "notifications.email.properties.mail.smtp.starttls": true
    "notifications.email.properties.mail.transport.protocol": 'smtp'
  end note

  control_plane -> control_plane: Формування даних для створення Secret\n**<registry_name>-notification-service-email-channel-configuration**
  control_plane -> openshift_control_plane_namespace: Створення Secret\n**<registry_name>-notification-service-email-channel-configuration**
  note left
    "notifications.email.username": '<username@external-domain>'
    "notifications.email.password": '<password>'
  end note
  end
else Обрано опцію використання платформенного поштового серверу
  control_plane -> control_plane: Формування адреси поштової скриньки реєстру \n(**<registry_name>@<registry.platform-domain>**)
  control_plane -> control_plane: Генерація пароля для доступу до поштової скриньки реєстру \n(**<registry_name>@<registry.platform-domain>**)

  control_plane -> control_plane: Автоматичне формування налаштувань SMTP \nплатформенного поштового сервера
  note left
    "smtp.host": '<platform-mail-server-host>'
    "smtp.port": '<platform-mail-server-port>'
    "username": '**<registry_name>@<registry.platform-domain>**'
    "notifications.email.password": '**<autogenerated-password>**'
  end note

  control_plane -> control_plane: Формування даних для створення ConfigMap\n**<registry_name>-notification-service-email-channel-configuration**
  control_plane -> openshift_control_plane_namespace: Створення ConfigMap\n**<registry_name>-notification-service-email-channel-configuration**
  note left
    "notifications.email.host": '<platform-mail-server-host>'
    "notifications.email.port": '<platform-mail-server-port>'
    "notifications.email.properties.mail.smtp.auth": true
    "notifications.email.properties.mail.smtp.starttls": true
    "notifications.email.properties.mail.transport.protocol": 'smtp'
  end note

  control_plane -> control_plane: Формування даних для створення Secret\n**<registry_name>-notification-service-email-channel-configuration**
  control_plane -> openshift_control_plane_namespace: Створення Secret\n**<registry_name>-notification-service-email-channel-configuration**
  note left
    "notifications.email.username": '**<registry_name>@<registry.platform-domain>**'
    "notifications.email.password": '**<autogenerated-password>**'
  end note
end

control_plane -> registry_creation_pipeline: Запуск пайплайну створення реєстру
deactivate control_plane

activate registry_creation_pipeline
alt Обрано опцію використання платформенного поштового серверу
  registry_creation_pipeline -> platform_mail_server: Створення поштової скриньки \n(**<registry_name>@<registry.platform-domain>**)
  note left
    "username": '**<registry_name>@<registry.platform-domain>**'
    "password": '<notifications.email.password>'
  end note
  platform_mail_server --> registry_creation_pipeline
end

== Підготовка налаштувань підключення до SMTP сервера (ConfigMap) для реєстру ==
registry_creation_pipeline -> openshift_control_plane_namespace: Експорт ConfigMap\n**<registry_name>-notification-service-email-channel-configuration**
registry_creation_pipeline -> registry_creation_pipeline: Формування даних для створення ConfigMap\n**notification-service-email-channel-configuration**
registry_creation_pipeline -> openshift_registry_namespace: Створення ConfigMap\n**notification-service-email-channel-configuration**
registry_creation_pipeline -> openshift_control_plane_namespace: Видалення ConfigMap\n**<registry_name>-notification-service-email-channel-configuration**

== Підготовка налаштувань підключення до SMTP сервера (Secret) для реєстру ==
registry_creation_pipeline -> openshift_control_plane_namespace: Експорт Secret\n**<registry_name>-notification-service-email-channel-configuration**
registry_creation_pipeline -> registry_creation_pipeline: Формування даних для створення Secret\n**notification-service-email-channel-configuration**
registry_creation_pipeline -> openshift_registry_namespace: Створення Secret\n**notification-service-email-channel-configuration**
registry_creation_pipeline -> openshift_control_plane_namespace: Видалення Secret\n**<registry_name>-notification-service-email-channel-configuration**

== Налаштування доступу до SMTP сервера для сервісів реєстру ==

alt Обрано опцію використання зовнішнього поштового серверу
  registry_creation_pipeline -> openshift_registry_namespace: Створення Istio ServiceEntry для зовнішнього поштового сервера
  note left
    apiVersion: networking.istio.io/v1alpha3
    kind: ServiceEntry
    metadata:
      name: external-mail-server
    spec:
      hosts:
      - <notifications.email.host>
      location: MESH_EXTERNAL
      ports:
      - number: <notifications.email.port>
        name: tcp-smtp
        protocol: TCP
      resolution: DNS
  end note
  registry_creation_pipeline -> openshift_registry_namespace: Обмеження доступу до ServiceEntry \nзовнішнього поштового сервера тільки для **notification-service**
else Обрано опцію використання платформенного поштового серверу
  registry_creation_pipeline -> openshift_registry_namespace: Створення NetworkPolicy для доступу **notification-service** до платформенного поштового сервера
end

== Застосування налаштувань до сервісів реєстру ==
registry_creation_pipeline -> notification_service: Рестарт сервісу **notification-service**
notification_service -> openshift_registry_namespace: Читання ConfigMap та  Secret\n**notification-service-email-channel-configuration**
registry_creation_pipeline --> platform_admin

deactivate registry_creation_pipeline

@enduml
