= Аудит розробки реєстру
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

CAUTION: Сторінка у процесі розробки.

[NOTE]
====
МЕТА: ::

* Про що документ: аудит (Протокол перевірки) будь-якого реєстру на кожному етапі його розробки.

* Цільова аудиторія: розробники реєстру.

* Наскільки розробка відповідає адекватним вимогам.

* На виході маємо отримати щось накшталт опитувальника: контрольні питання для кожної команди, на кожному етапі розробки реєстру (регламенту), які дозволять перевірити себе розробникам та забезпечити працездатність реєстру після виходу в промислове середовище.

* На яких етапах розробки й що саме потрібно перевіряти (це може бути щось універсальне, а може бути специфічні випадки)

Наприклад, ми маємо відповісти на подібні питання: ::

* Що важливо при розробці бізнес-процесів?
* Що варто пам'ятати при розробці звітів?
* Яке підводне каміння потрібно взяти до уваги?

Звернути увагу на: ::
xref:platform-develop:platform-prod-deployment.adoc#checklist-launch-public-service[Контрольний список для запуску публічного сервісу].

Також звернути увагу на: ::

xref:platform-develop:platform-prod-deployment.adoc#avoid-typical-prod-issues-in-services[Запобігання типовим проблемам із певними сервісами у промисловому середовищі].
+
Наприклад:

* Перевірте, що такої помилки не трапляється, див. детальніше xref:...
* Зверніть увагу на можливе значне навантаження на процесор у Java-сервісах. Щоб його не допустити, пильнуйте за ... параметрами.
====

== Аналіз типового референтного регламенту

[%interactive]
* [ ] Ознайомлення з референтним регламентом реєстру для зрозуміння вимог та очікувань щодо структури даних, бізнес-процесів, прав доступу, інтеграцій тощо.

== Розробка моделі даних реєстру

=== Розробка логічної моделі даних

[%interactive]
* [ ] Аудит логічної моделі даних після розробки: визначення, чи відповідає модель даних вимогам та логіці реєстру.
+
TIP: Користуйтеся найкращими практиками моделювання баз даних.

=== Розробка фізичної моделі даних

[%interactive]
* [ ] Перевірка на цілісність даних. +
Переконатися, що дані зберігаються цілісно та не мають відсутності обов'язкових значень, а також не порушують обмеження на цілісність.

* [ ] Перевірка на зайві дані. +
Переконатися, що база даних не містить зайвих, непотрібних даних, які можуть спотворити результати запитів та аналітики.

* [ ] Перевірка на використання індексів. +
Впевнитися, що належним чином використовуються індекси для підвищення продуктивності запитів.

* [ ] Перевірка на ефективність запитів. +
Переконатися, що запити до бази даних відповідають стандартам ефективності та оптимізації.

* [ ] Перевірка на консистентність даних. +
Переконатися, що дані у базі є консистентними та не порушують обмежень, встановлених у регламенті.

* [ ] Забезпечення безпеки даних. +
Впровадити заходи для забезпечення безпеки даних, включаючи обмеження доступу та шифрування.

* [ ] Забезпечення аудиту даних. +
Переконатися, що імплементація бази даних дозволяє ведення аудиту дій з даними для відстеження змін та виявлення потенційних проблем.

* [ ] Перевірка на дублювання даних. +
Переконайтеся, що одні й ті ж дані НЕ з'являються у базі даних більше одного разу. Дублювання даних може виникнути через помилки в процесі запису, імпорту або оновлення даних, що призводить до неточностей та невідповідності даних.

* [ ] Резервне копіювання БД +
Переконатися, що існують механізми регулярного резервного копіювання та відновлення бази даних.

* [ ] Перевірка нормальних форм. +
Перевірка, чи таблиці в базі даних відповідають нормальним формам для забезпечення оптимізації та точності роботи з даними.

* [ ] Використання зовнішніх ключів. +
Забезпечити використання зовнішніх ключів для зв'язку таблиць та усунення дублювання даних.

* [ ] Забезпечення цілісності даних. +
Використовувати відповідні обмеження (контрольні ключі, зовнішні ключі, обмеження на цілісність) для забезпечення цілісності даних під час змін.

* [ ] Оптимізація запитів. +
Застосовувати нормалізацію для зменшення складності запитів та оптимізації продуктивності роботи з даними.

* [ ] Розробка архітектури. +
Аналізувати, як нормалізовані дані впливають на архітектуру бази даних та її можливість розширення.

* [ ] Рівень нормалізації для конкретних даних. +
Враховуючи особливості конкретних даних, визначити оптимальний рівень нормалізації для збереження цілісності та ефективності роботи з даними.

=== Регулярна перевірка фізичної імплементації розробленої структури даних

[%interactive]
* [ ] Проводити регулярний аудит фізичної імплементації розробленої моделі даних. Наприклад, щомісяця виконувати перевірки на дублювання даних, нормалізацію, наявність адекватних індексів тощо (_див. розширений список перевірок у п. вище_).

=== Надання прав доступу до даних на рівні фізичної моделі

[%interactive]
* [ ] Налаштуйте доступ до даних на рівні дата-моделі:
** Надання доступу до представлень (VIEW) для зовнішніх систем або інших реєстрів на Платформі (SOAP або REST).
** Надання публічного доступу до представлень БД для неавторизованих користувачів або систем.
** ...

* [ ] Підготуйте дані для первинного завантаження даних до БД (наповнення таблиць довідників тощо).
* [ ] Виконайте первинне завантаження даних відповідно до встановлених обмежень за допомогою БД-процедури.
* [ ] Перевірте, що всі дані завантажилися вірно.

== Аудит бізнес-процесів

Перелік кроків аудиту бізнес-процесів регламенту реєстру:

* Розробка бізнес-процесів.
* Перевірка працездатності бізнес-процесів.


== Аудит UI-Форм

* Дизайн та розробка користувацьких інтерфейсів (UI-форм) відповідно до специфікацій.

* Перевірка функціональності та зовнішнього вигляду реалізованих UI-форм.

== Інші аспекти розробки регламенту

* Витяги
* Звіти
* Зовнішні інтеграції
* Сповіщення
* Ролі та авторизація
* тощо