= Скриптування вивантаження файлів за віддаленою адресою з послідуючим збереженням до реєстру у бізнес-процесі

== Загальний опис

Для повноцінної обробки даних, отриманих у результаті взаємодії з зовнішніми системами з бізнес-процесів, існує необхідність вивантажувати файли за їх віддаленими адресами та зберігати у сховище реєстру.

У якості рішення розглянуто реалізацію службової _JUEL_-функції, яка надає можливість зі скриптових задач БП ініціювати вивантаження за віддаленою адресою та збереження отриманого файлу до _Об'єктного сховища проміжних даних БП_ для подальшого використання при формуванні запиту у _Фабрику Даних_ реєстру.

== Актори та ролі користувачів

* Розробник регламенту

== Функціональні сценарії

* Вивантаження файлу за віддаленою адресою та завантаження до _Об'єктного сховища проміжних даних БП_ у скриптових задачах бізнес-процесів

== Загальні принципи та положення

* Ініціювання вивантаження та збереження файлу з БП через _JUEL_-функцію виконується під системним користувачем
* Збереження файлів за віддаленою адресою дозволено лише для службового / внутрішнього використання у межах виконання бізнес-процесу
* Розмір файлів, які можуть бути вивантажені обмежено налаштуваннями на рівні системи
* Вивантаження та збереження файлів виконується за межами бізнес-процесу _Сервісом цифрових документів_
* Збережені через _JUEL_-функцію цифрові документи підлягаються видаленню по завершенню виконання бізнес-процесу

== Технічний дизайн рішення

На даній діаграмі зображено залучені для реалізації вимог сервіси та взаємодію між ними. Додатково зображено важливі особливості, які необхідно брати до уваги в рамках реалізації.

image::architecture-workspace/platform-evolution/remote-file-transfer.svg[remote-file-transfer,700]

[NOTE]
Вивантаження файлів за віддаленою адресою потребує наявності відповідного _Istio Service Entry_, який було створено в автоматичному або ручному режимі.

=== API збереження цифрового документу за віддаленою адресою

Призначенням API-роута є вивантаження файлу, який знаходиться за віддаленою адресою у межах налаштованих обмежень за розміром та подальше його збереження до _Об'єктного сховища проміжних даних БП_.

[NOTE]
Вивантаження файлу з віддаленого сервера та завантаження до об'єктного сховища має бути реалізовано з використанням стрімінгу та відповідних обмежень на використання пам'яті серверного додатка.

==== Авторизація доступу

* Не публічний / для внутрішньої міжсервісної взаємодії

==== Специфікація API-роута

_POST /internal-api/documents/{processInstanceId}/_

.Заголовки запиту
|===
|Заголовок|Тип|Опис

|*X-Access-Token*
|JWT
|Токен доступу

|===

.Параметри запиту
|===
|Параметр|Тип|Частина запиту|Опис

|*processInstanceId*
|Текстовий
|Параметр запиту
|Ідентифікатор бізнес-процесу, в рамках якого виконується завантаження файла

|*remoteFileLocation*
|URL
|Параметр запиту
|Віддалене розташування файлу для вивантаження

|*filename*
|Текстовий
|Параметр запиту
|Назва файлу

|===

.Структура тіла відповіді
|===
|Json Path|Тип|Опис

|*$.id*
|UUID
|Унікальний ідентифікатор цифрового документу, зформований з використанням генератора псевдо-випадкових чисел

|*$.name*
|Текстовий
|Оригінальне ім’я файла

|*$.type*
|Текстовий
|Тип контенту файла (_application/pdf, image/png, image/jpeg_, etc.)

|*$.checksum*
|Тестовий
|Автоматично згенерований геш на контент файла з використанням SHA256 алгоритму

|*$.size*
|Числовий
|Розмір файла

|===

.Приклад відповіді
[source, json]
----
{
  "id": "{UUID}",
  "name": "{fileName}",
  "type": "{contentType}",
  "checksum": "{sha256}",
  "size": 0
}
----

.Коди відповіді
|===
|Код|Опис

a|[green]#201#
|Created з поверненням тіла відповіді
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації (відсутній токен доступу)
|[yellow]#422#
| Помилка валідації (недопустимий розмір файлу, тощо.)
a|[red]#500#
|Серверна помилка обробки запиту
|===

=== Системні налаштування

Розширити конфігурацію _Сервісу цифрових документів_ додатковими налаштуваннями:

* _max-remote-file-size_ - Обмеження на розмір файлу для вивантаження за  віддаленою адресою (*default*: 10MB)

== Моделювання регламенту реєстру

=== Розширення для моделювання

Необхідно реалізувати наступну _JUEL_-функцію:

* _save_digital_document_from_url(String remoteFileUrl, String targetFileName): DocumentMetadata_

.Структура об'єкту мета-даних цифрового документа
[source, groovy]
----
class DocumentMetadata {
  String id       // Унікальний ідентифікатор цифрового документу
  String name     // Оригінальне ім’я файла
  String type     // Тип контенту файла
  String checksum // SHA256-геш на контент файлу
  Long size       // Розмір файла
}
----

=== Референтні приклади моделювання

.Приклад використання _save_digital_document_from_url_ при розробці скриптової задачі бізнес-процесу
[source,groovy]
----
try {
  def documentMetadata = save_digital_document_from_url("http://...", "digital-document.ext") // Temporary save file to object storage

  def fileReference = [
    id: documentMetadata.id,
    checksum: documentMetadata.checksum
  ]
} catch (ValidationException ex) {
 // File size exceeded "max-remote-file-size" value
}
----

== Міграція даних при оновленні реєстру

У разі, якщо існуючий реєстр використовує внутрішній API зі скриптових задач для вивантаження та збереження файлів, розробники регламенту мають перейти до використання JUEL-функції в рамках оновлення самостійно.

== Високорівневий план розробки

=== Технічні експертизи

* _BE / Camunda_

=== План розробки

* Розширення API _Сервісу цифрових документів_ службовим роутом вивантаження та збереження файлів
* Розширення / реалізація Java-клієнта для _Сервісу цифрових документів_
* Реалізація _JUEL_-функції для завантаження файлів від імені системного користувача у _Сервіс цифрових документів_
* Розробка інструкцій для розробника регламенту та референтних прикладів