= Використання Knative функцій для розширення можливостей реєстру

include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

Knative функції - це можливість створювати Serverless застосунки для кластерів на основі Kubernetes. Вони представляють з себе open-source аналог для таких популярних рішень як AWS Lambda, Google Cloud Functions та інших.

В регламент реєстру можна додавати функції які працюють на основі Knative Serving, тобто обробляють http запити. Ці функції можуть бути написані на таких мовах програмування/фреймворках:

* Javascript
* Typescript
* C#
* Go
* Java (Spark)
* Java (Spring),
* Kotlin
* PHP
* Python
* Ruby
* Scala
* Shell

[TIP]
 Детальніше ознайомитись з Knative Serving можна за посиланням https://knative.dev/docs/serving/

== Налаштування оточення для роботи
Для локальної розробки та тестування роботи функцій на кластері, треба встановити *Docker*, *Kubernetes CLI*, *OpenShift CLI*, *Knative CLI*, та *NodeJS*. За детальними інструкціями встановлення цих інструментів зверніться до документації відповідних інструментів, так як цей процес сильно залежить від вашої ОС (Windows, MacOS, Linux)

[TIP]
В цій інструкції ми будемо розглядати роботу з функціями, які написані на  Javascript (Typescript), у випадку вибору іншої мови програмування для написання Knative функцій, NodeJS встановлювати непотрібно, натомість треба встановити необхідні інструменти для роботи з обраною мовою програмування.

== Створення Knative функції
Після коректної інсталяції Knative CLI, в вашому терміналі з'являється доступ до утіліти `kn func` або просто `func`. За допомогою ціє утіліти можна створювати, видаляти, збирати та деплоїти функції.
Для створення функції введіть в терміналі команду

[, bash]
----
kn func create -l typescript my-first-knative-func
----

* `typescript` - обрана мова програмування. Змініть на `node`, якщо бажаєте використовувати Javascript
* `my-first-knative-func` - директорія (та назва функції) в якій буде створено вашу функцію. Якщо буде потреба змінити назву функції, це можна зробити пізніше в конфігураційному файлі `func.yaml`. Вибір назви функції важливий, так як назва буде присутня в URL по якому буде доступна функція.

Після виконання цієї команди, утіліта `func` створить готовий до запуску та деплою проект, згідно вбудованого в *Knative CLI* шаблону. Якщо Вам потрібно більше опцій, або Ви бажаєте використати свій шаблон, ознайомтесь з документацією `kn func create` набравши в терміналі команду `kn func create --help`

== Локальна розробка функцій
Для розробки, запуску та тестування функцій рекомендується 2 найбільш зручні варіанти. *Локальний запуск* та *Запуск на кластері*

=== Локальний запуск
Підійде для перевірки та запуску функцій, які не потребують ресурсів кластеру/платформи/реєстру. Цей спосіб також буде зручним для виконання `debug` процедур. Так як в даному випадку, функції виконуються повністю локально і задіюється мінімум інструментів, які також можуть викликати помилки. Такий режим запуску аналогічний запуску звичайного NodeJS застосунку. Цей спосіб також поділяється на 2 режими запуску:

- *Javascript Only* - тут мається на увазі, що функція при запуску задіює тільки javascript інструменти та бібліотеки. Для запуску в такому режимі вам потрібно послідовно виконати 3 команди в терміналі.

 * `npm i` - встановлення модулів *JS*, потрібно запустити тільки перший раз
 * `npm run build` - збірка проекту, потрібна зажди після змін в коді, але повністю непотрібна якщо Ваша функція не використовує typescript
 * `npm run start` - запуск функції
- *Run in docker* - в даному випадку NodeJS код пакується в Docker контейнер ідентичний тому який буде працювати на кластері, але запускається локально. Для запуску в такому режимі виконайте команду в терміналі `kn func run`. Ця функція виконає збірку docker image, встановить необхідні модулі *NodeJS*, та запустить Вашу функцію в Docker контейнері. При запуску в такому режимі *Knative CLI* спитає Вас адресу Вашого *docker registry*. Якщо ви не збираєтесь запускати цю функцію на кластері, а просто хочете запустити, та перевірити роботу функції, ви можете вказати будь яку адресу (наприклад example.com/my-apps). Щоб кожного разу при запуску не вписувати адресу *docker registry* ви можете скористатись опцією `--registry` або `-r`. В такому разі команда запуску буде виглядати так - `kn func run -r example.com/my-apps`

Після запуску в терміналі Ви побачите лог роботи функції, та *HTTP* адресу за якою ви можете викликати функцію. За замовчуванням це буде `http://localhost:8080`. Ви можете використати ваш браузер або *Postman* (чи аналогічне ПО) для тестування вашої функції.

Якщо ви не збираєтесь тестувати Вашу функцію запускаючи її на кластері, то *Локального запуску* вам буде достатньо. На цьому етапі ваша функція повністю готова для додавання в регламент реєстру (цей процес описано нижче). Якщо у вас є потреба взаємодіяти з Вашої функції зі змінними бізнес-процесу, або з API сервісів реєстру, то для тестування її роботи вам знадобиться підхід з *Запуском на кластері*

=== Запуск на кластері
Для постійної та правильної роботи Knative функції, її потрібно додати в Ваш регламент реєстру. Але для спрощення тестування роботи функції, існує можливість тимчасово додати її на ваш кластер. Для цього вам знадобиться мати доступ до *OpenShift*.

[WARNING]
====
Станом на зараз для виконання деплою функції через Knative CLI, а не шляхом додавання функції у регламент, необхідно розширити правило для ролі _Адміністратора регламенту_.
Роль знаходиться за шляхом *OpenShift*  > *User Management*  > *Roles* > використовуючи пошук, знайдіть роль з назвою: _cp-registry-admin-{YOUR_NAMESPACE}-namespace_

*У YAML змініть rules для визначених verbs з:*
[, yaml]
----
rules:
  - verbs:
      - get
      - list
      - watch
----

*На:*
[, yaml]
----
rules:
  - verbs:
      - '*'
----

====

[IMPORTANT]
====
Всі додані таким способом Knative функції буде видалено після наступного розгортання регламенту
====

Для початку вам треба авторизуватись в *OpenShift CLI*. Для цього вам необхідно отримати команду для авторизації, та виконати її в Вашому терміналі. Як це зробити ви можете дізнатись xref:registry-develop:registry-admin/remote_connection.adoc[тут], пункт 7


[, bash]
----
oc login --token=sha256~1aWEXnvr4IBVNsrdepqDl5Q10NkhokW7nt-s_-trO8k --server=https://api.cicd2.mdtu-ddm.projects.epam.com:6443
----

Після успішного логіну, необхідно дізнатися адресу сховища артефактів (Nexus).

Якщо тип сховища артефактів на вашому реєстрі _Реєстрове_, отримати URL можна наступним чином:

[, bash]
----
oc get route docker-registry -n YOUR_NAMESPACE
----

Де `YOUR_NAMESPACE` треба замінити на неймспейс Вашого реєстру. У відповіді ви отримаєте URL виду `nexus-docker-hosted-YOUR_NAMESSPACE.YOUR_DOMAIN`

Якщо тип сховища артефактів на вашому реєстрі _Платформне_:

[, bash]
----
URL необхідно запросити у адміністратора Платформи
----

Наступним кроком необхідно отримати логін та пароль від вашого *docker-registry*. Це зручніше зробити зайшовши в веб інтерфейс Вашого *OpenShift*, перейти в розділ Workloads > Secrets.


Якщо тип сховища артефактів на вашому реєстрі _Платформне_:
[, bash]
----
необхідний секрет *platform-nexus-docker-registry-namespaced*.
----


Якщо тип сховища артефактів на вашому реєстрі _Реєстрове_:
[, bash]
----
необхідний секрет *nexus-docker-registry-namespaced*.
----

Секрет збережений в *json* форматі, але в ньому легко знайти значення для *username* та *password*
Тепер маючи *Docker registry URL*, *namespace*, *username*, та *password*
Ви можете задеплоїти *Knative* функцію на кластер, за допомогою команди

[, bash]
----
kn func deploy -r DOCKER_REGISTRY_URL -n NAMESPACE
----

Після цього, запущена команда спитає вас про логін та пароль для *docker registry*, які ви отримали раніше

[TIP]
====
Для зручності, щоб не вводити кожного разу логін та пароль від *docker registry*, ви можете скористатись командою `docker login`.
====

Якщо деплой пройде успішно, ви побачите повідомлення про це в терміналі, та отримаєте URL за яким буде доступна функція на Вашому кластері.

== Додавання конфіг-мап та секретів Openshift в Knative функцію
Після створення функції, в директорії функції з'являється конфігураційний файл функції `func.yaml`. Він дозволяє нам налаштувати зокрема використання секретів та конфіг-мап *Openshift*. Розглянемо приклад додавання секретів в env змінні функції
[, yaml]
----
run:
  envs:
  - name: REDIS_PASSWORD
    value: '{{ secret:redis-auth:password }}'
----

В полі `value`, ми бачимо інструкцію для Knative, яка бере значення секрету та зберігає його в env змінну `REDIS_PASSWORD`

* `secret` - ключове слово, яке вказує на те що буде використано *OpenShift* секрет, замість `secret` тут може бути вказано `configMap`, що буде означати *OpenShift* конфіг-мапу.
* `redis-auth` - назва секрету
* `password` - поле в секреті, яке буде використано

В результаті цих налаштувань, в вашому коді Javascript функції, секрет буде доступний в змінній `process.env.REDIS_PASSWORD`

[TIP]
====
Для детального ознайомлення з налаштуваннями в файлі `func.yaml` зверніться до офіційної документації https://github.com/knative/func/blob/main/docs/reference/func_yaml.md#local-environment-variables[за посиланням]
====

== Приклади використання Knative функцій

Для демонстрації роботи Knative функцій було написано 2 референтних бізнес-процеси. Вони написані з використанням `typescript` та працюють з дата-фабрикою

* *reference-knative-read-transform* - простий приклад отримання даних з дата-фабрики, з перетворенням масиву отриманих даних
* *reference-knative-write-transform* - приклад зміни даних колонки у всій таблиці дата-фабрики. Читання та запис в дата-фабрику, інтеграція з *Redis* та *digital-signature-ops* сервісами

[TIP]
====
[%collapsible]
.Де можна знайти приклад референтного бізнес-процесу?
=====
include::registry-develop:partial$snippets/demo-reg-reference-examples-ua.adoc[]
=====
====

Виклик knative функцій з бізнес-процесу відбувається за допомогою http-connector

[WARNING]
====
Наразі, knative функції можна викликати з бізнес-процесу тільки використовуючи URL, який залежить від реєстру (неймспейсу), тому при перенесені БП з одного реєстру на інший, або використанні референтних БП, обов'язково потрібно відредагувати URL в inputParameters http-connector

Наприклад, так виглядає URL однієї з функцій референтного БП
`http://knative-write-transform.${REGISTRY_NAMESPACE}.svc.cluster.local`
Тут строку `${REGISTRY_NAMESPACE}` треба замінити на на неймспейс вашого реєстру. Уявімо що назва вашого неймспейсу `pets-reg`, тоді повний URL функції для Вашого реєстру буде виглядати так `http://knative-write-transform.pets-reg.svc.cluster.local`
====

== Розгортання Knative функцій на реєстрі
Для використання створеної Вами функції в реєстрі, вона має бути доставлена в Ваш регламент реєстру. Функція представляє з себе директорію в якій знаходиться вихідний код функції та її конфігураційні файли. Цю директорію потрібно додати в git репозиторій вашого регламенту. Функції додаються в директорію *knative*. Якщо такої директорії ще не існує в Вашому git репозиторії, її необхідно створити.

[TIP]
====
Якщо Ви робили локальний запуск функції, то в директорії вашої функції буде створена директорія *node_modules* (в ній зберігаються javascript модулі необхідні  для локального запуску), яку варто видалити. Вона займає багато місця на диску, та не використовується при розгортанні в реєстрі

Також варто перевірити вміст вашого файлу `func.yaml`. При локальному запуску функції там можуть створитися зайві ключі які можуть впливати на розгортання функції. Варто видалити такі ключі `registry`, `image`, `imageDigest`, та `deploy`
====