= [DRAFT] Валідація на перевірку пустих обов'язкових полів на рівні шаблону задач в бізнес процесі

== Загальний опис
В процесі моделювання бізнес процесів використовуються шаблони для типових задач з описом відповідного контракту. Для
вхідних параметрів такого роду шаблонів налаштовується валідація, яка відпрацьовує на стороні клієнта в
застосунку Адмін Портал. Але через обмеженість функціоналу валідацію можна застосувати не для всіх шаблонів. Через це
відсутність обов'язкового поля моделювальник побачить тільки при виконанні бізнес процесу, а не при його моделюванні.
В рамках цього рішення необхідно розробити механізм перевірки валідності вхідних параметрів в пайплайні перевірки регламенту та в пайплайні публікації. Додатково необхідно дослідити можливість розширення функціоналу валідації в Адмін Порталі

== Концепти
* Шаблони задач - Camunda element templates, які спрощують процес моделювання бізнес процесів. Детальніше https://docs.camunda.io/docs/components/modeler/desktop-modeler/element-templates/about-templates//[за посиланням]
* Пайплайн перевірки - Jenkins Code Review pipeline, який запускається при внесенні змін в версію кандидат, або
безпосередньо в МР в Gerrit
* Пайплайн публікації - Jenkins Build pipeline, який запускається при внесенні змін в мастер версію

== Функціональні сценарії
* Використання шаблонів задач при моделюванні бізнес процесів регламенту реєстру в Адмін Порталі
* Використання шаблонів задач при моделюванні бізнес процесів регламенту реєстру в десктопному Camunda Modeler
* Валідація вхідних параметрів шаблонів задач в пайплайні перевірки регламенту при моделюванні регламенту
* Валідація вхідних параметрів шаблонів задач в пайплайні публікації при моделюванні регламенту
* Валідація вхідних параметрів шаблонів задач в Адмін Порталі при моделюванні регламенту
* Валідація вхідних параметрів шаблонів задач в пайплайні публікації при розгортанні регламенту на продакшен оточенні

== Ролі користувачів
* Розробник регламенту
* Адміністратор реєстру

== Загальні принципи та положення
=== Валідація на пайплайнах
* На пайплайні перевірки регламенту валідація повинна проходити за тим самим механізмом, що і на пайплайні публікації
* Валідація вхідних параметрів шаблонів задач повинна виконуватися за допомогою утіліти
registry-regulations-validator-cli
* При наявності помилок валідації вхідних параметрів шаблонів задач, пайплайн перевірки регламенту повинен викидати
помилку з повідомленням, яке є достатнім для розуміння помилки
* Для правил валідації використовується та сама версія шаблонів задач, що і для Адмін Порталу
* Версія шаблонів задач відповідає версії реєстру. Тобто шаблони задач можуть бути змінені тільки в момент оновлення
версії реєстру
* Для збереження шаблонів задач використовується ConfigMap, яка оновлюється при оновленні версії реєстру
* Для опису правил валідації використовується стандарний механізм element templates (constraints)
* В рамках поточного рішення підтримується тільки notEmpty constraint валідація (100% випадків використання в версії
платформи 1.9.5)

=== Валідація на клієнті (в Адмін Порталі)
* При розробці шаблону задач можна вказати тип поля вхідного параметра
* Валідація на клієнті підтримується тільки при вказанні типу вхідного параметра
* В Camunda версії 7.x є можливість не вказувати тип вхідного параметра
* На даний момент підтримуються наступні типи вхідних параметрів: String, Text, Boolean, Dropdown and Hidden
* Для переліку шаблонів задач в платформі потрібне використання типу Map, який не підтримується в Camunda версії 7.x/8.x
* Якщо не вказувати тип вхідного параметра, у моделювальника буде можливість самостійно обрати тип Map зі списку
* Типізовані вхідні параметри відображаються в секції Custom Properties, в той час, як нетипізовані - в секції
Input Parameters
* По результатам POC можливі 2 варіанти вірішення проблеми з Map:
** Розширення Element tempates підтримкою Map
** Розміщувати нетипізовані вхідні параметри в секції Custom Properties

== Високорівневий дизайн рішення

.Компонентна діаграма
image::architecture-workspace/platform-evolution/template-validation/component.svg[]
