:toc-title: Content
//:toc: auto
:toclevels: 5
:experimental:
:table-caption:             Table
:appendix-caption:
//:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Deploying the Platform on target environments

include::platform:ROOT:partial$admonitions/language-en.adoc[]

The Platform for state registries is *_cloud-agnostic_*, meaning it can function effectively on different cloud services without relying on a specific environment. This flexibility enables clients and developers to choose the most appropriate cloud service for their needs and preferences without being bound to a single provider.

The Platform must be deployed on virtual infrastructures that are officially supported, which currently include:

* [*] *Public clouds*: such as https://aws.amazon.com/[Amazon Web Services (AWS)], https://azure.microsoft.com/[Microsoft Azure (Azure)], and https://cloud.google.com/[Google Cloud Platform (GCP)]. These services provide access to virtual resources over the Internet and are available to the public.

* [*] *Private clouds*: These are clouds intended solely for the use of one organization. For instance, https://www.vmware.com/products/vsphere.html[VMWare vSphere] is a platform enabling the creation of private, especially on-premises cloud infrastructures.

The infrastructures above should install an OKD cluster, the version of which complies with the Platform's requirements, as laid out in the official documentation of the Platform: xref:admin:installation/okd-requirements.adoc[Platform's OKD cluster requirements].

Follow the official Platform documentation guidelines to carry out the installation and configuration process.

== Section overview

* xref:installation/platform-deployment/platform-aws-deployment.adoc[]
* xref:installation/platform-deployment/platform-azure-deployment.adoc[]
* xref:installation/platform-deployment/platform-gcp-deployment.adoc[]
* xref:installation/platform-deployment/platform-vsphere-deployment.adoc[]

