= Deploying the Platform from scratch in a public _AWS_ cloud environment
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

This guide provides detailed information on deploying the Platform from scratch in an _AWS_ environment, starting from creating an AWS account and ending with installing the Platform with all additional configurations.

== Prerequisites

Before deploying and configuring the platform, be sure to perform the following steps.

[#preconditions-first-stage]
=== Required elements for the initial stage

Before starting any actions, you need to have a set of resources that are mandatory for the subsequent steps:

Documentation: ::

* [*] Document xref:release-notes:release-notes.adoc[Release notes];
* [*] Document xref:release-notes:breaking-changes.adoc[Backward incompatible changes];
* [*] Document xref:update/overview.adoc[]. It is needed only for the platform update procedure.

Digital signature certificates (digital-signature-ops certificates): ::

* [*] *_Key-6.dat_* -- the organization's private key (_for file key only_);
* [*] *_allowed-key.yaml_* -- a list of all issued keys. Initially, this is only the primary _Key-6.dat_. When changing the key, information about the new key is added there without deleting the old one;
* [*] *_CAs.json_* -- a list of all CAs, taken from the https://iit.com.ua/downloads[ІIT] website;
* [*] *_CACertificates.p7b_* - the public key, taken from the https://iit.com.ua/downloads[ІIT] website.

Configuration files for file and hardware keys: ::

* 3 files filled with values—for file carrier (_see attached examples_):

* [*] _link:{attachmentsdir}/aws-deployment/sign.key.device-type[sign.key.device-type]_ -- specify the type of carrier for the key (file);
* [*] _link:{attachmentsdir}/aws-deployment/sign.key.file.issuer[sign.key.file.issuer]_ -- specify the CA that issued the key (replace the value in the file with your own);
* [*] _link:{attachmentsdir}/aws-deployment/sign.key.file.password[sign.key.file.password]_ -- specify the password for the file key (replace the value in the file with your own).

+
4 files with empty values—for hardware carrier (_create 4 empty files with corresponding names_):

* [*] *_sign.key.hardware.device_* -- type of carrier for the key (hardware);
* [*] *_sign.key.hardware.password_* -- hardware key password;
* [*] *_sign.key.hardware.type_* -- key type;
* [*] *_osplm.ini_* -- INI configuration.

+
TIP: More details on loading/updating keys and digital signature certificates can be found on the xref:registry-management/system-keys/control-plane-platform-keys.adoc[] page.

=== Creating an AWS account

Before installing OpenShift Container Platform on Amazon Web Services (AWS), you need to create an AWS account.

This can be done using the official documentation on the AWS website: https://aws.amazon.com/premiumsupport/knowledge-center/create-and-activate-aws-account/[How do I create and activate a new AWS account?]

=== Setting up an AWS account

Before installing OpenShift Container Platform, you need to configure your Amazon Web Services (AWS) account.

[#setup-route-53]
==== Setting up Route 53

To install OpenShift Container Platform, you need to register a domain. This can be done using the *Route 53* service, or you can use any other domain name registrar.

Also, the Amazon Web Services (AWS) account being used must have a dedicated public hosting zone in the Route 53 service.

TIP: Detailed description can be found in the official documentation on the OKD website: https://docs.openshift.com/container-platform/4.12/installing/installing_aws/installing-aws-account.html#installation-aws-route53_installing-aws-account[Configuring Route 53].

[#setup-external-domain]
==== Setting up an external domain

If a non-AWS Route 53 domain name registrar was used to create the domain, domain delegation must be performed. To do this, follow these steps:

* Go to the created AWS account and create a public hosting zone in the *Route 53* service (as described in p. xref:#setup-route-53[]). Name it the same as the created external domain.
* Enter the created public hosting zone and view the record of type *`NS`* (*Name Servers* -- these are the name servers that respond to DNS queries for the domain). The value will list the name servers. Save the names of these servers for use in subsequent steps.
* Go to the external domain name registrar where the domain was created.
* Open the settings of this domain and find the settings related to NS servers;
* Edit the NS servers according to the NS servers taken from the public hosting zone in the AWS account.

==== AWS account limits

The OpenShift Container Platform cluster uses several Amazon Web Services (AWS) components, and standard _service limits_ affect the cluster installation possibility.

A list of AWS components whose limits may affect the installation and operation of the OpenShift Container Platform cluster is provided in the documentation on the OKD website: https://docs.openshift.com/container-platform/4.12/installing/installing_aws/installing-aws-account.html#installation-aws-limits_installing-aws-account[AWS account limits].

NOTE: You must also increase the CPU limit for *_on-demand_* virtual machines in your Amazon Web Services (AWS) account. The necessary actions for this are described in the official documentation on the AWS website: https://aws.amazon.com/premiumsupport/knowledge-center/ec2-on-demand-instance-vcpu-increase/[How do I request an EC2 vCPU limit increase for my On-Demand Instance?]

==== Creating an IAM user

. Before installing OpenShift Container Platform, create an _IAM user_, using the official documentation on the AWS website: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html[Creating an IAM user in your AWS account].

. In addition, perform the following important requirements:

* Remove any *Service control policies (SCPs*) restrictions from the AWS account.
+
NOTE: During cluster creation, an associated AWS OpenID Connect (OIDC) identity provider is also created. This OIDC provider configuration is based on an open key located in the AWS region *`us-east-1`*. Clients with AWS SCP must allow the use of the AWS region *`us-east-1`* even if the cluster will be deployed in another region. Without proper policy settings, permission errors may occur immediately, as the OKD installer checks the correctness of these settings.
+
TIP: Detailed information can be obtained in the official documentation, in section *1.1. DEPLOYMENT PREREQUISITES* of the https://access.redhat.com/documentation/en-us/red_hat_openshift_service_on_aws/4/pdf/prepare_your_environment/red_hat_openshift_service_on_aws-4-prepare_your_environment-en-us.pdf[Red Hat OpenShift Service on AWS 4. Prepare your environment] document.

* Correctly set the *_permissions boundary_* for the created IAM user.
+
Below is an example of a permissions boundary policy. You can use it, or completely remove any permissions boundary.
+
[%collapsible]
._Example. Setting the *permissions boundary_ policy
====
[source,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "NotAction": [
                "iam:*"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "iam:Get*",
                "iam:List*",
                "iam:Tag*",
                "iam:Untag*",
                "iam:GenerateServiceLastAccessedDetails",
                "iam:GenerateCredentialReport",
                "iam:SimulateCustomPolicy",
                "iam:SimulatePrincipalPolicy",
                "iam:UploadSSHPublicKey",
                "iam:UpdateServerCertificate",
                "iam:CreateInstanceProfile",
                "iam:CreatePolicy",
                "iam:DeletePolicy",
                "iam:CreatePolicyVersion",
                "iam:DeletePolicyVersion",
                "iam:SetDefaultPolicyVersion",
                "iam:CreateServiceLinkedRole",
                "iam:DeleteServiceLinkedRole",
                "iam:CreateInstanceProfile",
                "iam:AddRoleToInstanceProfile",
                "iam:DeleteInstanceProfile",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:UpdateRole",
                "iam:UpdateRoleDescription",
                "iam:DeleteRole",
                "iam:PassRole",
                "iam:DetachRolePolicy",
                "iam:DeleteRolePolicy",
                "iam:UpdateAssumeRolePolicy",
                "iam:CreateGroup",
                "iam:UpdateGroup",
                "iam:AddUserToGroup",
                "iam:RemoveUserFromGroup",
                "iam:PutGroupPolicy",
                "iam:DetachGroupPolicy",
                "iam:DetachUserPolicy",
                "iam:DeleteGroupPolicy",
                "iam:DeleteGroup",
                "iam:DeleteUserPolicy",
                "iam:AttachUserPolicy",
                "iam:AttachGroupPolicy",
                "iam:PutUserPolicy",
                "iam:DeleteUser",
                "iam:CreateRole",
                "iam:AttachRolePolicy",
                "iam:PutRolePermissionsBoundary",
                "iam:PutRolePolicy"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [


                "iam:CreateAccessKey",
                "iam:DeleteAccessKey",
                "iam:UpdateAccessKey",
                "iam:CreateLoginProfile",
                "iam:DeleteLoginProfile",
                "iam:UpdateLoginProfile",
                "iam:ChangePassword",
                "iam:CreateVirtualMFADevice",
                "iam:EnableMFADevice",
                "iam:ResyncMFADevice",
                "iam:DeleteVirtualMFADevice",
                "iam:DeactivateMFADevice",
                "iam:CreateServiceSpecificCredential",
                "iam:UpdateServiceSpecificCredential",
                "iam:ResetServiceSpecificCredential",
                "iam:DeleteServiceSpecificCredential"
            ],
            "Resource": "*"
        }
    ]
}
----
====

TIP: The process of creating an IAM user is described in detail in the official documentation on the OKD website: https://docs.openshift.com/container-platform/4.12/installing/installing_aws/installing-aws-account.html#installation-aws-iam-user_installing-aws-account[Creating an IAM user].

==== Required AWS permissions for the IAM user

To deploy all components of the OpenShift Container Platform cluster, the IAM user needs permissions, which must be attached to this user. +
An example of such permissions is provided in the documentation on the OKD website: https://docs.openshift.com/container-platform/4.12/installing/installing_aws/installing-aws-account.html#installation-aws-permissions_installing-aws-account[Required AWS permissions for the IAM user].

[#create-additional-accounts]
=== Creating additional accounts

Before installing OpenShift Container Platform on Amazon Web Services (AWS), you need to create a Docker Hub and Red Hat account. +
This is necessary to generate the *`docker pull secret`*, which will be used later.

==== Creating a Docker Hub account

* Some services use images located in Docker Hub repositories. To be able to use them, you need to create an account using the official documentation on the Docker website: https://docs.docker.com/docker-id/[Docker ID accounts].

* Additionally, you may encounter a limit on the number of image downloads per day. This will prevent services from starting. To avoid this, you need to upgrade your subscription to the Pro level. This will change the limit from 200 docker images/6 hours to 5000 docker images/day. This can be done using the official documentation on the Docker website: https://docs.docker.com/subscription/upgrade/[Upgrade your subscription].

==== Creating a Red Hat account

To download the necessary images for installing OpenShift Container Platform, you need to create a Red Hat Account. Detailed instructions on how to do this are described in the official documentation: https://access.redhat.com/articles/5832311[Red Hat Login ID and Account].

This is necessary to download the generated pull secret later (detailed in section xref:#okd-aws-install-preparation[]). It will allow authentication and downloading container images for OpenShift Container Platform components.

[#deploy-additional-recources-for-okd]
== Deploying additional resources for installing OKD cluster in AWS

To successfully install the cluster and platform, the following resources need to be deployed in AWS. The diagram below shows the infrastructure scheme with these resources. This is done to simplify the platform installation and avoid undesirable errors that may be associated with installing from a local computer.

image:installation/aws/installation-aws-1.svg[image,width=468,height=375]

=== Description of additional resources

A more detailed description of additional resources from the diagram is shown below:

* *S3 bucket* -- used for storing the Terraform state;
* *DynamoDB table* -- used for storing information about Terraform state locking;
* *NAT Gateway* -- used to provide a private server with internet access;
* *Bastion* -- used as an intermediate server to provide secure and restricted access to the server in the private network. Later, an SSH tunnel will be created to the deployer-node through this bastion;
* *Deployer-node* -- a server in the private network through which the cluster and Platform installation will take place.

These resources can be deployed using the prepared Terraform code in the following steps.

==== Recommended bastion settings

The table below shows the recommended settings for the bastion.

.Bastion settings
[width="100%",cols="6%,33%,61%",options="header",]
|===

|*No.* |*Setting option* |*Value*

|1 |Instance type |t2.nano
|2 |vCPUs |1
|3 |RAM |0.5 GiB
|4 |CPU Credits/hr |3
|5 |Platform |Ubuntu
|6 |AMI name |ubuntu-bionic-18.04-amd64-server-20210224
|7 |Volume |8 Gb

|===

==== Recommended deployer-node settings

The table below shows the recommended settings for the deployer-node.

.Deployer-node settings
[width="100%",cols="6%,33%,61%",options="header",]
|===

|*No.* |*Setting option* |*Value*
|1 |Instance type |t2.medium
|2 |vCPUs |2
|3 |RAM |4 GiB
|4 |CPU Credits/hr |24
|5 |Platform |Ubuntu
|6 |AMI name |ubuntu-bionic-18.04-amd64-server-20210224
|7 |Volume |150 Gb

|===

=== Additional settings

==== Installing necessary tools

To proceed, you need to install the necessary tools on your local computer:

* unzip;
* https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html[aws cli v2];
* https://docs.docker.com/engine/install/[terraform v1.6.6].

You can check the correctness of the tool installation with the following commands:

.Checking tool installation
====

.Checking unzip
----
$ unzip -v
----

.Checking aws cli
----
$ aws --version
----

.Checking terraform
----
$ terraform version
----

====

==== Setting up AWS CLI

Authenticate in your AWS account using AWS CLI. To do this, execute the following command:

.*Authenticate in AWS account*
[source,bash]
----
$ aws configure
AWS Access Key ID [None]: ********************
AWS Secret Access Key [None]: ***************************************
Default region name [None]: eu-central-1
Default output format [None]: json
----

TIP: The process of authenticating in an AWS account using AWS CLI is described in detail in the official documentation on the AWS website: https://docs.aws.amazon.com/cli/latest/userguide/cli-authentication-user.html#cli-authentication-user-configure.title[Configure the AWS CLI].

==== Setting up AWS cross account

Before running the Terraform code, it needs to be downloaded. To do this, you need access to the AWS S3 bucket where it is located. This is possible only if a special IAM role is created. This can be done by following these steps:

. Create an AWS IAM role.
+
[source,bash]
----
$ aws iam create-role \
      --role-name UserCrossAccountRole \
      --description "Role for uploading terraform files from AWS S3" \
      --assume-role-policy-document '{
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": "sts:AssumeRole",
                    "Effect": "Allow",
                    "Principal": {
                        "AWS": "arn:aws:iam::<YourAccountId>:root"
                    }
                }
            ]
          }'
----
+
[NOTE]
====
* *`<YourAccountId>`* -- add your AWS account ID here.
====

. Create an AWS IAM policy.
+
[source,bash]
----
$ aws iam create-policy \
      --policy-name UserCrossAccountPolicy \
      --policy-document '{
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Action": "sts:AssumeRole",
                    "Effect": "Allow",
                    "Resource": "arn:aws:iam::764324427262:role/CustomCrossAccountRole"
                }
            ]
          }'
----

. Attach the policy to the role.
+
[source,bash]
----
$ aws iam attach-role-policy \
      --role-name UserCrossAccountRole \
      --policy-arn arn:aws:iam::<YourAccountId>:policy/UserCrossAccountPolicy
----
+
[NOTE]
====
* *`<YourAccountId>`* -- add your AWS account ID here.
====

. Add the necessary values for the role to the `config` file.
+
[source,bash]
----
$ cat <<EOT >> ~/.aws/config
[profile user-cross-account-role]
role_arn = arn:aws:iam::764324427262:role/CustomCrossAccountRole
source_profile = default
EOT
----

. To access files from an external AWS account, contact the support team. You need them to add your AWS account ID to the trusted list (trust relationship) for the `CustomCrossAccountRole` role in their AWS account.

==== Downloading Terraform code

. Download the archive with the Terraform code.
+
[source,bash]
----
$ aws s3 cp s3://mdtu-ddm-platform-installer/terraform/terraform.zip terraform.zip  --profile user-cross-account-role
----

. Unzip the Terraform code into a separate directory.
+
[source,bash]
----
$ unzip terraform.zip -d ~/terraform
----

=== Description of Terraform code

As an example of automating the process, Terraform code has been implemented, which can be customized and used to deploy the infrastructure.

==== Initial Terraform code

This is the Terraform code that will create resources for the subsequent steps. These resources include:

* S3 Bucket;
* DynamoDB Table.

Initial code. Description of Terraform files: ::

* `main.tf` -- the main Terraform configuration file. It contains modules for creating:
** S3 bucket;
** DynamoDB table.
* `providers.tf` -- used to define the version of Terraform, required plugins, and AWS provider parameters;
* `variables.tf` -- used to describe all variables used in the Terraform configuration;
* `terraform.tfvars` -- contains values for specific variables defined in the Terraform configuration files. If necessary, change the values for the following parameters to the required ones:
** `region` -- this variable is used to define the AWS region where the resources will be created;
** `tags` -- this variable is used to add tags (labels) for resources.

==== Main Terraform code

The main Terraform code deploys all the necessary resources. The template description is provided below.

.Main code. Description of Terraform files
* `main.tf` -- the main Terraform configuration file. It contains modules for creating:
** `VPC`;
** `ec2_bastion`;
** `ec2_instance`;
** `key_pair`.
* `providers.tf` -- used to define the version of Terraform, required plugins, and AWS provider parameters. Be sure to change the values for the following parameters to the required ones:
** `bucket` -- this variable contains the name of the S3 bucket. Change <ACCOUNT_ID> to the AWS account ID.
* `iam-node-role.tf` -- used to create a special IAM role with the necessary permissions. This will allow setting up AWS cross-account resource access and downloading Docker images for the container and Installer;
* `elastic-ip.tf` – used to create an AWS Elastic IP (EIP) resource using Terraform;
* `security-groups.tf` - creates Security Groups that allow SSH connections (TCP port 22) for bastion and deployer-node;
* `ssh-key.tf` - contains code for creating an SSH private key, saving the key to a file, and setting its access permissions;
* `files/user_data.sh.tpl` - a script template that will be executed when creating or updating an EC2 instance in the AWS environment. This script will do the following for the deployer-node:
** install Docker;
** install Unzip;
** install AWS CLI v2;
** additionally set up AWS cross-account resource access.
* `variables.tf` -- used to describe all variables used in the Terraform configuration;
* `terraform.tfvars` -- contains values for specific variables defined in the Terraform configuration files. If necessary, change the values for the following parameters to the required ones:
** `region` -- this variable is used to define the AWS region where the resources will be created;
** `platform_name` -- this variable is used to add the name for the cluster and AWS resources;
** `ingress_cidr_blocks` -- to connect via SSH to the deployer-node, add the required IP address here;
** `prefix_list_ids` -- if you need to open several addresses for connection, create a prefix-list and use its ID in this parameter;
** `tags` -- this variable is used to add tags (labels) for resources.

=== Running the Terraform code

After making the changes in the previous steps, the Terraform code is now ready to run.

==== Running the initial Terraform code
. Sequentially execute the following commands to navigate to the directory with the initial Terraform code and initialize the Terraform working directory.
+
[source,bash]
----
$ cd ~/terraform/initCode

$ terraform init
----

. Use the following command to apply the changes defined in the configuration files and create the resources.
+
[source,bash]
----
$ terraform apply -auto-approve
----

. Wait for the resources to be created.

==== Running the main Terraform code
. Sequentially execute the following commands to navigate to the directory with the main Terraform code and initialize the Terraform working directory.
+
[source,bash]
----
$ cd ~/terraform/mainCode

$ terraform init
----

. Use the following command to apply the changes defined in the configuration files and create the resources.
+
[source,bash]
----
$ terraform apply -auto-approve
----

. Wait for the resources to be created.

=== Connecting to the deployer-node

To connect from a local computer to the deployer-node, you need to create an SSH tunnel. This should be done with the following command:

.Creating an SSH tunnel
====
----
$ ssh -i <SSH_KEY> -L 1256:<NODE_PRIVATE_IP>:22 -N -f ubuntu@<BASTION_PUBLIC_IP>
----
====

After creating the SSH tunnel, you can connect to the deployer-node. This should be done with the following command:

.Connecting via SSH
====
----
$ ssh -i <SSH_KEY> ubuntu@localhost -p 1256
----
====

[IMPORTANT]
====
Purpose of the deployer-node ::

All further steps, namely cluster installation and platform setup, should be performed from the deployer-node.
====

=== Running the openshift-install container

To use the docker image of the *`openshift-install`* container for installing the cluster, follow the steps below.

. Authenticate in AWS ECR.
+
[source,bash]
----
$ sudo aws ecr get-login-password --profile cross-account-role --region eu-central-1 | docker login --username AWS --password-stdin 764324427262.dkr.ecr.eu-central-1.amazonaws.com
----

. Download the docker image.
+
[source,bash]
----
$ docker pull 764324427262.dkr.ecr.eu-central-1.amazonaws.com/openshift-install:v3
----

. Add a tag to the downloaded docker image.
+
[source,bash]
----
$ docker tag 764324427262.dkr.ecr.eu-central-1.amazonaws.com/openshift-install:v3 openshift-install:v3
----

. Create a new directory to store all cluster data:
+
[source,bash]
----
$ mkdir ~/openshift-cluster
----

. Navigate to the created directory.
+
[source,bash]
----
$ cd ~/openshift-cluster
----

. Run the *`openshift-install`* container.
+
[source,bash]
----
$ sudo docker run --rm -it --name openshift-install-v3 \
    --user root:$(id -g) \
    --net host \
    -v $(pwd):/tmp/openshift-cluster \
    --env AWS_ACCESS_KEY_ID=<ACCESS_KEY> \
    --env AWS_SECRET_ACCESS_KEY=<SECRET_ACCESS_KEY> \
    openshift-install:v3 bash
----

//TODO: HEREEEEEEEEEEEEEEEEE