:toc-title: Content
//:toc: auto
:toclevels: 5
:experimental:
:table-caption:             Table
:appendix-caption:
//:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Deploying the Platform on target environments

The successful deployment of the Platform for state registries relies on the utilization of officially supported virtual infrastructures. At present, these infrastructures include recognized cloud services like https://aws.amazon.com/[Amazon Web Services (AWS)] and https://www.vmware.com/products/vsphere.html[VMWare vSphere].

To ensure optimal compatibility and functionality, these infrastructures should have an OKD cluster installed. The version of this cluster needs to align with the Platform's requirements outlined in the official Platform documentation: xref:admin:installation/okd-requirements.adoc[].

Follow the guidelines in the official Platform documentation to carry out the process of installation and configuration.

== Overview

* xref:admin:installation/platform-deployment/platform-aws-deployment.adoc[]
* xref:admin:installation/platform-deployment/platform-vsphere-deployment.adoc[]

