= Зберігання схем UI-форм та валідація даних користувачів
include::ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::ROOT:partial$admonitions/language-ua.adoc[]

== Функціональні сценарії

- Отримання даних схем UI-форм для відображення у кабінетах користувачів
- Валідація даних, внесених користувачами через UI-форми задач згідно налаштованих правил
- Валідація файлів, завантажених користувачами через UI-форми задач згідно налаштованих правил
- Валідація даних, які використовуються як вхідні параметри для ініціювання бізнес-процесів зовнішніми системами

== Базові принципи та мотивація для редизайну

- Забезпечення єдиного підходу до реалізації _cross-cutting_ вимог, які накладаються на _Edge_-сервіси реєстру з публічно доступним API, завдяки використанню єдиного технологічного стеку та, як результат, повторне використання стандартного набору технік, бібліотек, тощо.
- Забезпечення високого рівня _сohesion_ при дизайні сервісів платформи
- Стандартизація типів сховищ для даних, якими оперує Платформа
- Тип сховища для даних має відповідати нефункціональним вимогам, які виставляються до операцій над цими даними

== Обсяг редизайну сервісів

В рамках редизайну, для реалізації функціональних сценаріїв необхідно ввести наступні нові компоненти:

- _Сервіс постачання UI-форм_ (*form-schema-provider*)
- _Сервіс валідації даних UI-форм_ (*form-submission-validation*)

[NOTE]
Кожен компонент має бути інтегрованим в екосистеми реєстру та реалізовувати повною мірою усі _cross-cutting_ вимоги.

Компоненти, які підлягають змінам:

- _Сервіс управління процесами користувачів_ (*user-process-management*)
- _Сервіс управління задачами користувачів_ (*user-task-management*)
- _Сервіс цифрових документів_ (*digital-documents*)
- _Пайплайн публікації регламенту_ (*jenkins*)

Компоненти, які підлягають заміщенню / видаленню з виконанням міграції даних:

- _Сервіс постачання UI-форм_ (*form-management-provider*)
- _Сховище даних схем UI-форм_ (*form-management-provider-db*)

== Цільовий дизайн системи

На даній діаграмі зображено цільовий стан сервісів платформи та взаємодію між ними. Додатково зображено важливі особливості, які необхідно брати до уваги в рамках реалізації.

image::architecture/registry/operational/bpms/bpm-form-schema.svg[form-schema-provider, 800]

=== Компоненти системи та їх призначення в рамках цільового дизайну

|===
|Компонент|Службова назва| Сценарії використання

|_Сервіс валідації даних UI-форм_
|*form-submission-validation*
|Валідація даних та файлів, внесених користувачем через UI-форми задач бізнес-процесів на відповідність налаштованим правилам

|_Сервіс постачання UI-форм_
|*form-schema-provider*
|Обробка запитів на отримання схем UI-форм з боку кабінетів користувачів

|_Сервіс управління задачами користувачів_
|*user-task-management*
|Збереження даних користувача та підпису, отриманих у процесі виконання задач бізнес-процесів та проведення валідації на відповідність налаштованим правилам

|_Сервіс управління процесами користувачів_
|*user-process-management*
|Збереження вхідних даних, отриманих від користувача через стартову UI-форму бізнес-процесу та проведення валідації на відповідність налаштованим правилам

|_Сервіс-шлюз для інтеграції з зовнішніми системами_
|*bp-webservice-gateway*
|Збереження вхідних даних, необхідних для ініціювання бізнес-процесу у разі виклику зовнішніми системами

|_Сервіс цифрових документів_
|*digital-documents*
|Зберігання та валідація файлів, завантажених користувачами

|_Пайплайн публікації регламенту_
|*jenkins*
|Публікація змін схем UI-форм задач бізнес-процесів до цільового оточення реєстру

|_Розподілене in-memory сховище даних_
|*redis*
|Зберігання / Кешування даних схем UI-форм

|===

=== Налаштування політик міжсервісної взаємодії

В рамках реалізації вимог, необхідно додати відповідні мережеві політики _NetworkPolicy_, які дозволяють взаємодію для наступних компонентів:

- *kong* -> *form-schema-provider*
- *form-submission-validation* -> *form-schema-provider*
- *user-process-management* -> *form-submission-validation*
- *user-task-management* -> *form-submission-validation*
- *digital-documents* -> *form-submission-validation*
- *form-schema-provider* -> *redis*

=== Сервіс постачання схем UI-форм

Даний _Java_-сервіс відповідає за обробку запитів на отримання схем UI-форм для задач бізнес-процесів. У якості сховища даних використовується _Redis Sentinel_.

[TIP]
Детальніше з описом _Redis Sentinel_ можно ознайомитись у розділі xref:architecture/registry/operational/bpms/bpm-interim-data-storage.adoc#_відмовостійке_key_value_сховище_даних_на_базі_redis_sentinel[Відмовостійке key-value сховище даних на базі Redis Sentinel].

==== Зберігання даних UI-форм

UI-форми зберігаються за допомогою _Redis Hash_-структури з використанням підходу сегрегації об'єктів через _Keyspaces_-префікси (_<keyspace>:<key>_).

Для об'єктів схем UI-форм використовується *bpm-form-schemas* _keyspace_.

.Приклад паттерну генерації ключа для запису / читання об'єкту:
[source]
----
bpm-form-schemas:{form-key}
----

==== API доступу до схем UI-форм

[WARNING]
Отримання доступу до API можливе лише в рамках виконання запиту автентифікованого користувача в системі

===== Отримання схеми UI-форми за ідентифікатором [_Публічний_]

[NOTE]
Данний API-роут є публічним та має бути опублікованим для зовнішнього доступу через окремий _Kong Route_.

_GET /api/forms/{form-key}_

|===
|Параметр|Тип|Частина запиту|Опис

|*X-Access-Token*
|JWT
|HTTP заголовок
|Токен доступу користувача

|*form-key*
|Текстовий
|Параметр запиту
|Унікальний ідентифікатор схеми UI-форми
|===

.Приклад відповіді
[source, json]
----
{
  "type": "form",
  "display": "form",
  "title": "Назва форми задачі",
  "name": "form-key",
  "path": "form-key",
  "components": [
  ]
}
----

.Коди помилок
|===
|Код|Опис

a|[green]#200#
|OK з поверненням результату даних схеми UI-форми
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації (відсутній токен доступу)
a|[yellow]#404#
|Схема UI-форми за вказаним {form-key} відсутня
a|[red]#500#
|Серверна помилка обробки запиту
|===

===== Створення нової схеми UI-форми [_Внутрішній_]

[WARNING]
Призначенням API-роута є службове використання _Пайплайном публікації регламенту_ для наповнення даними сховища даних схем UI-форм (*redis*). Роут не доступний для зовнішнього доступу через _Kong_.

_POST /api/forms/_

|===
|Параметр|Тип|Частина запиту|Опис

|*X-Access-Token*
|JWT
|HTTP заголовок
|Токен доступу користувача
|===

.Приклад тіла запиту
[source, json]
----
{
  "type": "form",
  "display": "form",
  "title": "Назва форми задачі",
  "name": "form-key",
  "path": "form-key",
  "components": [
  ]
}
----

.Коди помилок
|===
|Код|Опис

a|[green]#201#
|Created з поверненням результату даних схеми UI-форми
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації (відсутній токен доступу)
a|[red]#500#
|Серверна помилка обробки запиту
|===

===== Внесення змін до існуючої схеми UI-форми [_Внутрішній_]

[WARNING]
Призначенням API-роута є службове використання _Пайплайном публікації регламенту_ для наповнення даними сховища даних схем UI-форм (*redis*). Роут не доступний для зовнішнього доступу через _Kong_.

_PUT /api/forms/{form-key}_

|===
|Параметр|Тип|Частина запиту|Опис

|*X-Access-Token*
|JWT
|HTTP заголовок
|Токен доступу користувача

|*form-key*
|Текстовий
|Параметр запиту
|Унікальний ідентифікатор схеми UI-форми
|===

.Приклад тіла запиту
[source, json]
----
{
  "type": "form",
  "display": "form",
  "title": "Назва форми задачі",
  "name": "form-key",
  "path": "form-key",
  "components": [
  ]
}
----

.Коди помилок
|===
|Код|Опис

a|[green]#200#
|OK з поверненням результату даних схеми UI-форми
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації (відсутній токен доступу)
a|[yellow]#404#
|Схема UI-форми за вказаним {form-key} відсутня
a|[red]#500#
|Серверна помилка обробки запиту
|===

=== Сервіс валідації даних UI-форм

Даний _NodeJS_-сервіс відповідає за валідацію даних згідно правил, визначених у схемі UI-форми за допомогою бібліотеки _formio.js_.

Додатково реалізує підтримку серверної валідації для файлів, завантажених користувачами.

[NOTE]
Детальніше з документацією бібліотеки Form.IO можна ознайомитись https://github.com/formio/formio.js/[за посиланням].

==== API валідації даних UI-форм

[WARNING]
Отримання доступу до API можливе лише в рамках виконання запиту автентифікованого користувача в системі. API-роути не доступні для зовнішнього доступу через _Kong_ та використовуються лише внутрішніми сервісами реєстру.

===== Валідація даних згідно визначених у схемі UI-форми правил (_Внутрішній_)

_POST /api/form-submissions/{form-key}/validate_

|===
|Параметр|Тип|Частина запиту|Опис

|*X-Access-Token*
|JWT
|HTTP заголовок
|Токен доступу користувача

|*form-key*
|Текстовий
|Параметр запиту
|Унікальний ідентифікатор схеми UI-форми, відносно якої необхідно провести валідацію даних
|===

.Приклад тіла запиту з даними UI-форми
[source, json]
----
{
  "data": {
    "field-key1": "Joe",
    "field-key2": "joe@example.com",
    "field-key3": "123123123"
  }
}
----

.Приклад відповіді у разі помилок валідації даних
[source, json]
----
{
  "name": "ValidationError",
  "details": [
    {
      "message": "Name is required",
      "level": "error",
      "path": [
        "name"
      ],
      "context": {
        "validator": "required",
        "setting": true,
        "key": "name",
        "label": "Name",
        "value": ""
      }
    },
    {
      "message": "Edrpou must have at least 2 characters.",
      "level": "error",
      "path": [
        "edrpou"
      ],
      "context": {
        "validator": "minLength",
        "setting": 2,
        "key": "edrpou",
        "label": "Edrpou",
        "value": "1"
      }
    }
  ]
}
----

.Коди помилок
|===
|Код|Опис

a|[green]#200#
|OK
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації (відсутній токен доступу)
a|[red]#422#
|Помилка валідації даних відносно схеми UI-форми
a|[red]#500#
|Серверна помилка обробки запиту
|===

[IMPORTANT]
Після виконання редизайну сервісів, необхідно провести редизайн API валідації задля забезпечення консистентності контрактів по поверненню помилок валідації.

===== Валідація даних окремого поля згідно визначених у схемі UI-форми правил (_Внутрішній_)

_POST /api/form-submissions/{form-key}/fields/{field-key}/validate_

[NOTE]
На даний момент підтримується лише валідація файлових полів. У разі, якщо _{field-key}_ належить полю іншого типу, система повинна повернути *501* _(NOT_IMPLEMENTED)_.

|===
|Параметр|Тип|Частина запиту|Опис

|*X-Access-Token*
|JWT
|HTTP заголовок
|Токен доступу користувача

|*form-key*
|Текстовий
|Параметр запиту
|Унікальний ідентифікатор схеми UI-форми

|*field-key*
|Текстовий
|Параметр запиту
|Унікальний ідентифікатор поля в межах UI-форми
|===

.Приклад тіла запиту з даними про завантажений файл UI-форми для валідації
[source, json]
----
{
  "documentKey": "",
  "filename": "",
  "contentType": "",
  "size": 0
}
----

.Приклад відповіді для валідації файлових полів
[source, json]
----
{
  "traceId": "<trace-id>",
  "code": 422,
  "message": "The type of the downloaded file is not supported.",
  "details": []
}
----

.Коди помилок
|===
|Код|Опис

a|[green]#200#
|OK з поверненням результату даних схеми UI-форми
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації (відсутній токен доступу)
a|[yellow]#404#
|Схема UI-форми за вказаним _{form-key}_ відсутня
a|[red]#500#
|Серверна помилка обробки запиту
a|[red]#501#
|Операція не підтримується системою
|===

=== Пайплайн публікації регламенту

Для наповнення даними нового сховища схем UI-форм *bpm-form-schemas* _Redis keyspace_ в рамках публікації регламенту, необхідно внести зміни у _Stage_ *upload-form-changes* з використанням внутрішнього API новоствореного сервісу _Сервісу постачання UI-форм_ (*form-schema-provider*).

== Бекапування та відновлення даних схем UI-форм

Створення резервної копії та відновлення даних, які зберігаються у сховищі  _Redis_ виконується згідно до загальної процедури з використанням захищеного сховища бекапів.

[TIP]
Детальніше можно ознайомитись у розділі xref:admin:backup-restore/control-plane-backup-restore.adoc[Бекап та відновлення реєстру].

== Міграція _даних схем UI-форм_

На данний момент, схеми UI-форм реєстру зберігаються у сховищі _MongoDB_ *form-management-provider-db*.

В рамках переходу до нової версії, необхідно провести наповнення даними нового сховища *bpm-form-schemas* _Redis keyspace_ для кожного реєстру.

=== Процедура міграції опція №1:

- Отримання усіх файлів схем UI-форм регламенту реєстру з *<registry-regulation>/forms* директорії
- Створення відповідних записів схем UI-форм через внутрішній API _Сервісу постачання UI-форм_ з використанням алгоритму, визначеного у _UploadFormChanges.groovy_ відповідного кроку _Пайплайну публікації регламенту_

=== Процедура міграції опція №2:

- Сформувати _Gerrit MR_ зі змінами типу: _touch <<registry-regulation>/forms/*.json>_
- Інтегрувати _Gerrit MR_ у _master_-гілку, таким чином ініціювати запуск "Пайплайну публікації регламенту"
- Дочекатися проходження кроку *upload-form-changes* та перевірити наявність записів у *bpm-form-schemas* _Redis keyspace_