= Проміжне збереження даних, внесених через UI-форми задач бізнес-процесів

== Функціональні сценарії

- Збереження даних, внесених через UI-форму користувачем, без завершення виконання задачі [_Необхідно реалізувати_]
- Відображення попередньо збережених даних на UI-формі при поверненні до виконання задачі [_Підтримується_]

== Базові принципи

- Проміжне збереження доступне тільки для даних, які вносяться через UI-форми задач (_UserTask_) в рамках ініційованого бізнес-процесу
- Функція проміжного збереження не доступна для даних, які були внесені через _стартову форму_ бізнес-процесу без фактичного ініціювання його виконання
- Функція проміжного збереження не доступна для задач підпису даних (_CitizenSignTask_ та _OfficerSignTask_)
- Проміжне збереження є системною функцією, яка доступна безумовно для вищезазначених UI-форм та не потребує окремого налаштування адміністратором
- Ініціювання проміжного збереження даних, внесених через UI-форму задачі у виконанні є свідомим вибором користувача в залежності від обставин через виклик системної функції на UI-формі
- Проміжне збереження даних не є автоматичним / періодичним процесом для UI-форми у процесі внесення даних користувачем
- Проміжне збереження даних доступне тільки за умови, що дані відповідають налаштованим правилам валідації на відповідній UI-формі
- При поверненні до виконання задачі бізнес-процесу, для якої було ініційовано виклик системної функції збереження даних, внесених користувачем через відповідну UI-форму, система забезпечує автоматичне заповнення збереженими даними для продовження роботи

== Технічний дизайн

На даній діаграмі зображено залучені для реалізації вимог сервіси платформи та взаємодію між ними. Додатково зображено важливі особливості, які необхідно брати до уваги в рамках реалізації.

image::architecture/registry/operational/bpms/bpm-interim-save-load-form-data.svg[bpm-interim-save-load-form-data, 800]

=== Компоненти системи та їх призначення в рамках дизайну рішення

У даному розділі наведено перелік компонент системи, які задіяні або потребують змін/створення в рамках реалізації функціональних вимог згідно технічного дизайну рішення.

|===
|Компонент|Службова назва|Сценарії використання

|_Кабінети посадової особи та громадянина_
|- *officer-portal*

- *citizen-portal*
|- Безумовне відображення системної функції проміжного збереження даних для UI-форм задач бізнес-процесів [_Необхідно реалізувати_]

- Ініціювання системної функції проміжного збереження даних для UI-форм задач бізнес-процесів [_Необхідно реалізувати_]

- Відображення збережених даних на UI-формі при поверненні до виконання задачі [_Підтримується_]

|_Сервіс управління задачами користувачів_
|*user-task-management*
|- Обробка запитів на проміжне збереження даних в рамках роботи над задачами користувачів [_Необхідно реалізувати_]

- Обробка запитів на отримання тимчасово збережених даних UI-форми задачі для подальшого відображення [_Підтримується_]

|_Сервіс валідації даних UI-форм_
|*form-submission-validation*
|Валідація даних, внесених користувачем через UI-форми задач бізнес-процесів на відповідність налаштованим правилам

|_Розподілене in-memory сховище даних_
|*redis*
|Зберігання проміжних даних на час виконання бізнес-процесів

|===

=== Взаємодія компонентів системи

==== Збереження даних, внесених через UI-форму користувачем, без завершення виконання задачі

[plantuml, bpm-save-interim-form-submission, svg]
----
include::partial$architecture/registry/operational/bpms/bpm-save-interim-form-submission.puml[]
----

==== Відображення попередньо збережених даних на UI-формі при поверненні до виконання задачі

[plantuml, bpm-populate-interim-form-submission, svg]
----
include::partial$architecture/registry/operational/bpms/bpm-populate-interim-form-submission.puml[]
----

=== Розширення API системи для реалізації сценаріїв

==== Збереження проміжних даних UI-форми задачі

[WARNING]
Отримання доступу до API можливе лише в рамках виконання запиту автентифікованого користувача в системі.
Даний API-роут має бути опублікованим для зовнішнього доступу через окремий _Kong Route_.

_POST /api/task/{id}/save_

|===
|Параметр|Тип|Частина запиту|Опис

|*X-Access-Token*
|JWT
|HTTP заголовок
|Токен доступу користувача

|*id*
|Текстовий
|Параметр запиту
|Унікальний ідентифікатор задачі у виконанні
|===

.Приклад тіла запиту
[source, json]
----
{
  "data": {
    ...
  }
}
----

.Коди помилок
|===
|Код|Опис

a|[green]#200#
|OK з поверненням результату у вигляді збережених даних
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації (відсутній токен доступу)
a|[red]#422#
|Помилка валідації даних відносно схеми UI-форми задачі
a|[red]#500#
|Серверна помилка обробки запиту
|===

==== Отримання попередньо збережених даних UI-форми задачі БП

[WARNING]
Отримання доступу до API можливе лише в рамках виконання запиту автентифікованого користувача в системі.
Даний API-роут має бути опублікованим для зовнішнього доступу через окремий _Kong Route_.

_GET /api/task/{id}_

|===
|Параметр|Тип|Частина запиту|Опис

|*X-Access-Token*
|JWT
|HTTP заголовок
|Токен доступу користувача

|*id*
|Текстовий
|Параметр запиту
|Унікальний ідентифікатор задачі у виконанні
|===

.Приклад відповіді на запит
[source, json]
----
{
  "id": "",
  "taskDefinitionKey": "",
  "formKey": "",
  "name": "",
  "assignee": "",
  "data": {
    ...
  }
}
----

.Коди помилок
|===
|Код|Опис

a|[green]#200#
|OK з поверненням результату у вигляді мета-даних задачі та збережених даних
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації
a|[yellow]#403#
|Помилка авторизації
a|[yellow]#404#
|Задача за вказаним _{id}_ відсутня
a|[red]#500#
|Серверна помилка обробки запиту
|===
