= Об'єктне сховище даних

== Загальний опис

_xref:arch:architecture/registry/operational/bpms/overview.adoc[Підсистема виконання бізнес-процесів]_ використовує об'єктне сховище xref:arch:architecture/platform-technologies.adoc#ceph[Ceph] з  xref:arch:architecture/platform/operational/distributed-data-storage/overview.adoc[_Підсистеми розподіленого зберігання даних_] для тимчасового збереження файлів цифрових документів, завантажених користувачами через UI-форми або сервісними задачами в бізнес-процесах.

== Структури даних

=== lowcode-file-storage

Бакет для тимчасового зберігання цифрових документів, завантажених в рамках виконання БП.

.Паттерн генерації ключа об'єкта
[source]
----
process/{processInstanceId}/{UUID}
----

.Опис атрибутів мета-даних об'єкту
|===
|Атрибут|Тип даних|Опційність|Опис

|`id`
|_String (UUID)_
|_Обов'язкове_
|Унікальний ідентифікатор

|`filename`
|_String_
|_Обов'язкове_
|Назва файлу

|`checksum`
|_String_
|_Обов'язкове_
|Чек-сума файлу

|`fieldname`
|_String_
|_Опційне_
|Назва поле на формі.

|`formkey`
|_String_
|_Опційне_
|Назва форми з якої завантажено файл

|===

.Опис структури документу для зберігання
|===
|Тип даних|Опис

|_byte[]_
|Контент файлу
|===