= Робота з цифровими документами у кабінеті користувача

include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

Поточний технічний дизайн сфокусований на загальних аспектах реалізації вимог щодо роботи із файлами через Кабінети користувача та на особливостях взаємодії між підсистемами "_Lowcode_" та "_Дата Фабрика_" в цьому контексті.

[NOTE]
Детальніше з дизайном компоненти "_Сервіс цифрових документів_" підсистеми "_Lowcode_" можна ознайомитися
xref:digital-document-service:digital-document-service.adoc[за посиланням]

== Функціональні можливості

Для забезпечення вимог по роботі з цифровими документами через кабінет користувача, платформа надає наступні можливості:

- Завантаження цифрових документів користувачами через UI-форми задач бізнес-процесів
- Вивантаження та перегляд цифрових документів користувачами через UI-форми задач бізнес-процесів

== Загальні принципи реалізації

- Файли цифрових документів, завантажені через UI-форми задач, підлягають збереженню в об'єктному сховищі _Ceph_ до моменту закінчення бізнес-процесу
- Для усіх файлів цифрових документів, завантажених через UI-форми задач, генерується _SHA256_-геш та зберігається у вигляді атрибуту Ceph-документа для подальшого використання при накладанні підпису
- Файли цифрових документів, завантажені через UI-форми задач, та дані форми зберігаються у вигляді окремих Ceph-документів в різних бакетах (_lowcode-file-storage_ та _lowcode-form-data-storage_)
- Для забезпечення цілістності даних, отриманих від користувача та завантажених ним файлів цифрових документів через UI-форму, Ceph-документ даних форми містить унікальні ідентифікатори Ceph-документів файлів та згенеровані з них _SHA256_-геші
- Файли цифрових документів не є об'єктом виконання операцій на рівні бізнес-процесів на відміну від їх ідентифікаторів
- При накладанні підпису приватним ключем користувача на дані форми з завантаженими файлами цифрових документів, підпис генерується на документ даних UI-форми, який містить унікальні ідентифікатори Ceph-документів та _SHA256_-геші файлів
- Обмін цифровими документами між підсистемами платформи "_Low-code_" та "_Дата Фабрика_" реалізується внаслідок обміну унікальних ідентифікаторів та їх Ceph-документів через окремий Ceph-бакет "_lowcode-file-storage_"
- Усі документи, які завантажені в рамках бізнес-процесу,  зберігаються у вигляді Ceph-об'єктів в "_lowcode-file-storage_" бакеті під ключами з ознакою групування за префіксом (_process/{processInstanceId}/{id}_) процесу
- Бакет "_low-code-file-storage_" призначений для тимчасового зберігання цифрових документів у процесі виконання бізнес-процесів. Для перманентного зберігання використовується окремий бакет "_Дата Фабрики_" - "_registry-file-storage_"

== Взаємодія компонентів системи

На даній діаграмі зображено задіяні для реалізації вимог сервіси платформи та взаємодію між ними. Додатково зображено важливі особливості, які необхідно прийняти до уваги в рамках реалізації.

image::architecture/registry/operational/bpms/file-management.svg[]

=== Сервіс цифрових документів
За реалізацію вимог по роботи з ціфровими документами через кабінет, відповідає окремий компонент "_Сервіс цифрових документів_", який використовує _Ceph_ у якості сховища файлів.

[NOTE]
Детальніше з дизайном компоненти "_Сервіс цифрових документів_" можна ознайомитися
xref:digital-document-service:digital-document-service.adoc[за посиланням]

=== Обмін цифровими документами між підсистемами платформи

- Файли цифрових документів є невід'ємною частиною сутності, в рамках створення якої вони були збережені
- _REST API_ підсистеми "_Дата Фабрика_" оперує лише UUID-ідентифікаторами та _SHA256_-гешами на рівні структур даних сутностей
- При виконанні запиту на збереження сутності, яка містить UUID-ідентифікатори, Дата Фабрика очікує, що в бакеті "_lowcode-file-storage_" є наявні Ceph-документи з ключами, які відповідають конвенції іменування _process/{processInstanceId}/{UUID}_ (значення _processInstanceId_ передається у вигляді заголовка "*X-Source-Business-Process-Instance-Id*" разом з запитом), _SHA256_-геші яких співпадають з тими, які були передані разом с запитом
- При виконанні запиту на отримання сутності, яка містить UUID-ідентифікатори, Дата Фабрика гарантує клієнту наявність у бакеті "_lowcode-file-storage_" Ceph-документів з ключами, які відповідають конвенції іменування _process/{processInstanceId}/{UUID}_ (значення _processInstanceId_ передається у вигляді заголовка "*X-Source-Business-Process-Instance-Id*" разом з запитом), _SHA256_-геші яких співпадають з тими, які передані як частина сутності
- Доступ до файлів, завантажених як вкладення до сутності, на рівні підсистеми "Low-code" можливий лише через отримання даних цієї сутності та послідуюче отримання документа за UUID-ідентифікатором документа через компоненту "_Сервіс цифрових документів_"

[plantuml, file_exchange, svg]
----
include::partial$architecture/registry/operational/bpms/digital-documents-exchange.puml[]
----

=== Контракт взаємодії між підсистемами платформи

.Канонічний вигляд тіла запиту до Дата Фабрики на збереження даних сутності з файловими вкладеннями
[source,json]
----
{
  "<file_property_name>": [
    {
      "id": "{UUID}",
      "checksum": "{SHA256-hash}"
    }
  ]
}
----

.Канонічний вигляд відповіді Дата Фабрики на запит отримання даних сутності з файловими вкладеннями
[source,json]
----
{
  "<file_property_name>": [
    {
      "id": "{UUID}",
      "checksum": "{SHA256-hash}"
    }
  ]
}
----

=== Загальна структура Ceph-об'єктів, які задіяні в обміні між "Lowcode" та "Дата Фабрикою"

|===
|Назва атрибуту|Атрибут JSON-документа|Атрибут Ceph об'єкта|Значення

|Ключ Ceph-об'єкта
|
|key
|Унікальний ідентифікатор Ceph-документу для збереження файла в області доступу поточного бізнес-процесу. Автоматично формується на базі згенерованого *id* згідно конвенції  _process/<processInstanceId>/<id>_

|Ідентифікатор цифрового документу
|id
|UserMetaData.id
|Унікальний ідентифікатор файла, зформований з використанням генератора псевдо-випадкових чисел (_cad2e994-0e32-4a9f-9959-b420e20d4522_)

|Назва файлу
|name
|UserMetaData.name
|<Назва файлу>

|Тип контента
|type
|Content-Type (UserMetaData.type)
|application/pdf, image/png, image/jpeg

|Розмір
|size
|Content-Length (UserMetaData.size)
|<Розмір файлу>

|Контент документа
|content
|input
|<Контент файла>

|Геш документа
|checksum
|(UserMetaData.checksum)
|Згенерований SHA256-геш файла
|===

== Сценарії взаємодії користувача з системою

=== Завантаження цифрових документів

На даній діаграмі зображено сценарій внесення даних з файловими вкладеннями в рамках виконання задачі користувачем, обробка даних в рамках бізнес-процесу та використання їх для попереднього заповнення наступної задачі користувача.

[plantuml, file_upload, svg]
----
include::partial$architecture/registry/operational/bpms/file-upload.puml[]
----

.Канонічний вигляд структури документа у тілі запиту на збереження даних форми через серверний додаток
[source, json]
----
{
  "data": {
      "<file_property_name>": [
        {
          "id": "{UUID}",
          "checksum": "{SHA256-hash}"
        }
      ]
  }
}
----

.Опис формату збереження документів в Ceph у процесі обробки запиту на виконання задачі
[source, json]
----
{
  "data": {
      "<file_property_name>": [
        {
          "id": "{UUID}",
          "checksum": "{SHA256-hash}"
        }
      ]
  },
  "x-access-token": "<X-Access-Token>"
}
----

=== Вивантаження цифрових документів

На даній діаграмі зображено сценарій отримання сутності з файловими вкладеннями, яка була попередньо збережена у Дата Фабриці та послідуюча її підготовка для відображення на UI-формі задачі користувача.

[plantuml, file_download, svg]
----
include::partial$architecture/registry/operational/bpms/file-download.puml[]
----

.Канонічний вигляд відповіді серверного додатоку на запит отримання даних форми
[source, json]
----
{
  "data": {
      "<file_property_name>": [
        {
          "id": "{UUID}",
          "checksum": "{SHA256-hash}"
        }
      ]
  }
}
----

=== Підпис даних UI-форм з цифровими документами

На даній діаграмі зображено сценарій підпису даних з файловими вкладеннями в рамках виконання задачі користувачем, обробка даних в рамках бізнес-процесу та їх збереження в Дата Фабрику.

[plantuml, file_signing, svg]
----
include::partial$architecture/registry/operational/bpms/file-signing.puml[]
----

.Канонічний вигляд структури документа у тілі запиту на збереження підписаних даних форми через серверний додаток
[source, json]
----
{
  "data": {
      "<file_property_name>": [
        {
          "id": "{UUID}",
          "checksum": "{SHA256-hash}"
        }
      ]
  },
  "signature": "<e-Signature>"
}
----

.Опис формату збереження документів з підписом в Ceph
[source, json]
----
{
  "data": {
      "passport_scans": [
        {
          "id": "{UUID}",
          "checksum": "{SHA256-hash}"
        }
      ]
  },
  "x-access-token": "<X-Access-Token>",
  "signature": "<e-Signature>"
}
----

== Моделювання UI-форм

=== Типова конфігурація поля типу "_File_" для налаштування адміністратором регламента
|===
|Розділ меню|Назва налаштування|Значення|Опис
|Display
|Label
|<На розсуд адміністратора>
|Текстовий опис поля для користувача

|API
|Property Name
|<На розсуд адміністратора>
|Назва поля у JSON-документі структури даних

|File
|Storage
|URL
|Збереження контента завантаженого файла на сервері

|File
|Url
|/documents
|Адреса сервісу цифрових документів

|File
|Display as Image(s)
|false
|Відображення піктограм для зображень, замість табличного вигляду

|Data
|Multiple Values
|false
|Підтримка завантаження декількох файлів

|File
|File Pattern
|application/pdf,image/jpeg,image/png
|Паттерн файлів, дозволених для завантаження

|File
|File Maximum Size
|<На розсуд адміністратора>
|Максимальний розмір одного файлу
|===

=== JSON-схема опису структури UI-форми з полем типу "File"
[source, json]
----
{
  "components": [
    {
      "label": "<file_property_label>",
      "storage": "url",
      "key": "<file_property_name>",
      "type": "file",
      "url": "/documents",
      "input": true
    }
  ]
}
----