= Нереляційне сховище даних

[NOTE]
--
Сторінка технічної документації у процесі розробки.
--

== Структури даних

=== bpm-form-submissions

Дані, отримані через UI-форми

Під ключем `bpm-form-submissions` зберігається перелік унікальних ключів (`set`) під якими зберігаються безпосередньо дані у вигляді hash-таблиці за окремими ключами які мають префікс `bpm-form-submissions`

.Опис структури для зберігання
|===
|Ключ |Тип даних|Опис

|id
|String
|Унікальний ідентифікатор

|accessToken
|String
|JWT-токен користувача

|_class
|String +
(com.epam.digital.data.platform.storage.form.model.FormDataRedis)
|Службове поле для збереження типу при серіалізації

|data
|String (JSON)
|Дані форми
|===

=== bpm-message-payloads

Дані, які були породжені у результаті міжпроцесної взаємодії

Під ключем `bpm-message-payloads` зберігається перелік унікальних ключів (`set`) під якими зберігаються безпосередньо дані у вигляді hash-таблиці за окремими ключами які мають префікс `bpm-message-payloads`

.Опис структури для зберігання
|===
|Ключ|Тип даних|Опис

|id
|String
|Унікальний ідентифікатор форми

|data
|String (JSON)
|Дані форми

|_class
|String +
(com.epam.digital.data.platform.storage.message.model.MessagePayloadRedis)
|Службове поле для збереження типу при серіалізації

|===

=== bpm-form-schemas

Схеми UI-форм

Дані зберігаються у вигляді hash-таблиці

.Опис структури для зберігання
|===
|Ключ |Тип даних|Опис

|id
|String
|Унікальний ідентифікатор назва форми

|_class
|String +
(com.epam.digital.data.platform.form.provider.entity.FormSchema)
|Службове поле для збереження типу при серіалізації

|formData
|String (JSON)
|Опис структури форми
|===



=== bpm-form-scripts

Зовнішні скрипти для UI-форм

.Опис структури JSON-документу для зберігання
|===
|Атрибут (_JSON-path_)|Тип даних|Опис

|
|
|
|===

.Приклад JSON-документу для зберігання
[source,json]
----
{

}
----