= Нереляційне сховище даних
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

_xref:arch:architecture/registry/operational/bpms/overview.adoc[Підсистема виконання бізнес-процесів]_ використовує розподілену _in-memory_ базу даних xref:arch:architecture/platform-technologies.adoc#redis[Redis] з  xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc[_Підсистеми управління нереляційними базами даних_] для зберігання проміжних даних, породжених у межах виконання бізнес-процесів та даних, необхідних для побудови UI-форм кабінетів користувачів.

== Структури даних

=== bpm-form-submissions

Зберігання даних, внесених користувачами через UI-форми, цифрових підписів та даних, переданих у якості вхідних параметрів бізнес-процесу зовнішніми системами.

[NOTE]
--
Під ключем _bpm-form-submissions_ зберігається перелік унікальних ключів (_set_) під якими зберігаються безпосередньо дані у вигляді hash-таблиці за окремими ключами які мають префікс _bpm-form-submissions_.
--

.Паттерн генерації ключа для запису даних UI-форми
[source]
----
bpm-form-submissions:process/{processInstanceId}/task/{taskDefinitionKey}
----

.Паттерн генерації ключа для запису даних стартової UI-форми бізнес-процесу
[source]
----
bpm-form-submissions:process-definition/{processDefinitionKey}/start-form/{UUID}
----

.Паттерн генерації ключа для запису з даними цифрової печатки реєстру
[source]
----
bpm-form-submissions:lowcode_{rootProcessInstanceId}_{processInstanceId}_system_signature_ceph_key
----

.Паттерн генерації ключа для запису з даними цифрової печатки реєстру для батч-операцій
[source]
----
bpm-form-submissions:lowcode_{processInstanceId}_system_signature_ceph_key_{index}"
----

.Опис структури для зберігання даних
|===
|Ключ |Тип даних|Опис

|`id`
|_String_
|Унікальний ідентифікатор

|`accessToken`
|_String_
|_JWT_-токен користувача

|`data`
|_String_ (_JSON_)
|Дані

|`signature`
|_String_
|Цифровий підпис
|===

=== bpm-message-payloads

Зберігання даних, переданих у якості вхідних параметрів з повідомленням для ініціювання бізнес-процесу.

[NOTE]
--
Під ключем _bpm-message-payloads_ зберігається перелік унікальних ключів (_set_) під якими зберігаються безпосередньо дані у вигляді hash-таблиці за окремими ключами які мають префікс _bpm-message-payloads_.
--

.Паттерн генерації ключа для запису
[source]
----
bpm-message-payloads:process-definition/{processDefinitionKey}/start-message/{UUID}
----

.Опис структури для зберігання даних
|===
|Ключ|Тип даних|Опис

|`id`
|_String_
|Унікальний ідентифікатор

|`data`
|_String_ (_JSON_)
|Дані вхідних параметрів (тіла повідомлення)
|===

=== bpm-form-schemas

Зберігання описів структур UI-форм в JSON-форматі, сумісному з _Form.IO_.

[NOTE]
--
Дані зберігаються у вигляді _Hash_-таблиці з сегрегацією об’єктів на рівні префіксів в ідентифікаторах (_<keyspace>:<key>_).
--

.Паттерн генерації ключа для запису
[source]
----
bpm-form-schemas:{formKey}
----

.Опис структури для зберігання
|===
|Ключ |Тип даних|Опис

|`id`
|_String_
|Унікальний ідентифікатор - ключ UI-форми

|`formData`
|_String_ (_JSON_)
|Опис структури форми и JSON-форматі
|===

=== bpm-form-scripts

[WARNING]
--
Дана секція потребує уточнення по результату реалізації технічного дизайну xref:arch:architecture/registry/administrative/regulation-management/platform-evolution/form-scripts/form-scripts.adoc[].
--

Зберігання коду скриптів для використання в UI-формах кабінетів користувачів.

[NOTE]
--
Дані зберігаються у вигляді _Hash_-таблиці з сегрегацією об’єктів на рівні префіксів в ідентифікаторах (_<keyspace>:<key>_).
--

.Паттерн генерації ключа для запису
[source]
----
bpm-form-scripts:{scriptName}
----

.Опис структури для зберігання
|===
|Ключ |Тип даних|Опис

|`id`
|_String_
|Унікальний ідентифікатор - назва файлу зі скриптом в регламенті

|`formScript`
|_String_
|Контент файлу зі скриптом в регламенті
|===