:toc-title: ЗМІСТ
:toc: auto
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Посадова інструкція для технічного адміністратора платформи

== Обов'язки та вимоги до технічного адміністратора платформи

Обов'язки та вимоги до кандидата на посаду технічного адміністратора платформи включають, та не обмежуються наступними категоріями:

Забезпечення надійності та безпеки платформи: ::

* Відстеження вразливостей та надання рекомендацій по усуненню проблем.
* Контроль за використанням сильних паролів та їх періодичне оновлення.
* Налаштування та використання Kong для управління доступом до внутрішніх ресурсів.
* Розуміння принципів та практик DevSecOps.
* Виконання регулярних аудитів безпеки платформи.

Управління технічними складовими платформи: ::

* Розгортання компонентів платформи на хмарних оточеннях, зокрема AWS та vSphere.
* Використання OKD та Kubernetes для керування компонентами платформи та реєстрів.
* Розгортання та конфігурація компонентів інфраструктури платформи з використанням Terraform.

Управління контейнерами: ::

* Розгортання, налаштування та керування контейнерами з використанням Cri-o Runtime та Kubernetes на базі OKD-кластера.
* Виконання аналізу та оптимізація роботи контейнерів.
* Вміння використовувати Helm для розгортання пакетів та керування конфігурацією Kubernetes.
* Налагодження та моніторинг міжсервісної взаємодії з використанням Istio.
* Розуміння принципів для моніторингу та трейсингу сервісів. Використання Kiali та Jaeger.

Резервне копіювання та відновлення: ::

* Налаштування резервного копіювання та аварійного відновлення ресурсів платформи з використанням Velero та pgBackRest.
* Досвід роботи з об'єктними сховищами, зокрема Minio для збереження бекапів.

Моніторинг та логування: ::

* Моніторинг та аналіз метрик системи з використанням Grafana та Prometheus.
* Забезпечення роботи системи логування з використанням Elasticsearch Fluentd та Kibana.

Автоматизація: ::

* Знання Jenkins для організації процесів _безперервної інтеграції_ та _розгортання_ (CI/CD).
* Навички налаштування та використання VCS git та Gerrit для проведення інтеграції, версіонування та рецензування коду.
* Знання Nexus для збереження та управління артефактами.

Управління користувачами та доступом: ::

* Налаштування та керування системою Keycloak.
* Контроль за доступом користувачів до ресурсів.

Керування секретами: ::

* Розуміння та досвід роботи зі сховищами секретів, такими як Hashicorp Vault тощо.
* Налаштування та управління ролями, політиками та доступом до секретів.

Автентифікація та авторизація: ::

* Розуміння та досвід роботи з системами автентифікації, зокрема Keycloak та Kong API management.
* Розуміння механізмів авторизації, зокрема RBAC та Kubernetes RBAC Authorization.

Управління базами даних: ::

* Розгортання, налаштування та керування базами даних PostgreSQL з використанням CrunchyData Postgres Operator та Pgpool.
* Моніторинг та аналіз метрик баз даних з використанням Grafana та Prometheus.

Брокери повідомлень: ::

* Використання Kafka для обробки великих потоків даних, знання механізмів обробки помилок, реплікації та управління доступом.
* Розгортання та налаштування Kafka Schema Registry для управління схемами даних та Strimzi для керування та моніторингу Kafka-кластера.

== Пов'язанні сторінки

Детальну інформацію щодо технологій, які має використовувати адміністратор при роботі з платформою, ви можете переглянути на сторінці xref:arch:architecture/platform-technologies.adoc[].

////

== Вимоги

== Освіта

Вища технічна освіта, наприклад, диплом бакалавра чи магістра з комп'ютерних наук, інформаційної безпеки чи інженерії програмного забезпечення.