@startuml
actor "Користувач" as user
participant "Kong" as kong
participant "Сервіс управління\nпроцесами користувача" as user_process_mng
box "Сервіс виконання бізнес-процесів"
participant "Сервіс виконання бізнес-процесів" as bpms
participant "CamundaAuthorizationFilter" as filter
participant "SecurityContext" as context
participant "CamundaAuthProvider" as provider
participant "IdentityService" as identityService
participant "RestService" as restService
database "Camunda Database" as db

skinparam responseMessageBelowArrow true

title Авторизація в системі

note left of user : Користувач вже \nпройшов автентифікацію\nу Keycloak
user -> kong : Запит на надання послуги\nSessionID
activate kong
kong -> kong : Отримання токена\nкористувача за SessionID
kong -> user_process_mng : Запит на надання послуги\nAccess Token
activate user_process_mng
user_process_mng -> user_process_mng : Перевірка наявності ролі\nofficer чи citizen\nу токені
alt Немає системних ролей
user_process_mng -> user : 403\nНеавторизований доступ
end
user_process_mng -> bpms : Запит на надання послуги
activate bpms
bpms -> filter
activate filter
filter -> context : Запит\nна авторизаційний\nоб'єкт
activate context
context -> filter : Авторизаційний об'єкт\nна базі токена
deactivate context
filter -> provider : Створити авторизаційний об'єкт Camunda
activate provider
provider -> identityService : Встановити\nавторизаційний\nоб'єкт Camunda\nГрупи = ролі
deactivate provider
note right of identityService : Зберігання на базі ThreadLocal
deactivate identityService
filter -> restService : Запит на надання послуги
activate restService
restService -> identityService : Зчитати\nавторизаційний\nоб'єкт Camunda
activate identityService
identityService -> restService : Авторизаційний\nоб'єкт Camunda
deactivate identityService
restService -> db : Отримання прав\nдоступу за користувачем\nта групами
activate db
db -> restService : Права доступу
deactivate db
restService -> restService : Перевірка контексту\nзапиту за\nправами доступу
alt Немає прав на роботу з бізнес-процесом
restService -> user : 403\nНеавторизований доступ

end
restService -> filter : Успішний старт бізнес-процесу
deactivate restService
filter -> provider : Очистити\nавторизацію
activate provider
provider -> identityService : Очистити\nавторизацію
deactivate provider
filter -> bpms
deactivate filter
bpms -> user_process_mng : 200 OK
deactivate bpms
user_process_mng -> kong : 200 OK
deactivate user_process_mng
kong -> user : 200 OK
deactivate kong






@enduml