@startuml
actor "Розробник регламенту" as dev
participant "Сховище регламенту" as gerrit
participant "Пайплайн публікації" as pipe
entity "Keycloak CR API" as cr
participant "Keycloak" as keycloak

skinparam responseMessageBelowArrow true

title Налаштування ролей регламенту

dev -> gerrit: Зміни до файлів\nрегламентних ролей
activate gerrit
gerrit -> gerrit: Процес рев'ю змін
gerrit -> pipe: Відслідковує нові зміни
activate pipe
gerrit -> dev: 200, OK
deactivate gerrit
pipe -> pipe: Інші кроки\nпайплайну публікацій
loop Для файлу roles/citizen.yml та roles/officer.yml
pipe -> cr: Створити\nKeyclokRealmRoleBatch CR
activate cr
cr -> keycloak: Ролі створюються\nKeycloak Operator'ом
activate keycloak
deactivate keycloak
cr -> pipe
deactivate cr
end

deactivate pipe

@enduml