{
  "openapi": "3.0.3",
  "info": {
    "title": "Registry regulations admin-portal",
    "description": "This document describes changes in REST API of 'Registry regulations admin-portal'",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:7070",
      "description": "Generated server url"
    }
  ],
  "tags": [
    {
      "name": "Registry regulations master Business processes management Rest API"
    },
    {
      "name": "Registry regulations Master version Forms management Rest API"
    }
  ],
  "paths": {
    "/versions/master/forms/{formName}": {
      "put": {
        "tags": [
          "Registry regulations Master version Forms management Rest API"
        ],
        "description": "Update existing form within master version",
        "operationId": "updateForm",
        "parameters": [
          {
            "name": "X-Access-Token",
            "in": "header",
            "description": "Token used for endpoint security",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "If-Match",
            "in": "header",
            "description": "ETag to verify whether user has latest data",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "formName",
            "in": "path",
            "description": "Name of the form to be updated",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "string"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {

              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {

              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {

              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "412": {
            "description": "Precondition Failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Registry regulations Master version Forms management Rest API"
        ],
        "description": "Create new form within master versionn",
        "operationId": "formCreate",
        "parameters": [
          {
            "name": "X-Access-Token",
            "in": "header",
            "description": "Token used for endpoint security",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "formName",
            "in": "path",
            "description": "Name of the new form to be created",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "string"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {

              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {

              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {

              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "412": {
            "description": "Precondition Failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Registry regulations Master version Forms management Rest API"
        ],
        "description": "Delete existing form within master version",
        "operationId": "deleteForm",
        "parameters": [
          {
            "name": "X-Access-Token",
            "in": "header",
            "description": "Token used for endpoint security",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "If-Match",
            "in": "header",
            "description": "ETag to verify whether user has latest data",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "formName",
            "in": "path",
            "description": "Name of the form to be updated",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No Content",
            "content": {
              "application/json": {

              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {

              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {

              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "412": {
            "description": "Precondition Failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          }
        }
      },
    },
    "/versions/master/business-processes/{businessProcessName}": {
      "put": {
        "tags": [
          "Registry regulations master Business processes management Rest API"
        ],
        "description": "Update business process",
        "operationId": "updateBusinessProcess",
        "parameters": [
          {
            "name": "X-Access-Token",
            "in": "header",
            "description": "Token used for endpoint security",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "businessProcessName",
            "in": "path",
            "description": "Process name",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "string"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "text/xml": {

              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {

              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {

              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "412": {
            "description": "Precondition Failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Registry regulations master Business processes management Rest API"
        ],
        "description": "Create new business process",
        "operationId": "createBusinessProcess",
        "parameters": [
          {
            "name": "X-Access-Token",
            "in": "header",
            "description": "Token used for endpoint security",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "businessProcessName",
            "in": "path",
            "description": "Name of the new process to be created",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "string"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "text/xml": {

              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {

              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {

              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "412": {
            "description": "Precondition Failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Registry regulations master Business processes management Rest API"
        ],
        "description": "Delete business process",
        "operationId": "deleteBusinessProcess",
        "parameters": [
          {
            "name": "X-Access-Token",
            "in": "header",
            "description": "Token used for endpoint security",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "businessProcessName",
            "in": "path",
            "description": "Process name",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No content",
            "content": {
              "text/xml": {

              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {

              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {

              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "412": {
            "description": "Precondition Failed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Entity",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DetailedErrorResponse"
                }
              }
            }
          }
        }
      },
    }
  },
  "components": {
    "schemas": {
      "DetailedErrorResponse": {
        "required": [
          "code",
          "details",
          "traceId"
        ],
        "type": "object",
        "properties": {
          "traceId": {
            "type": "string",
            "description": "Request identifier"
          },
          "code": {
            "type": "string",
            "description": "Error code"
          },
          "details": {
            "type": "string",
            "description": "Error details"
          },
          "localizedMessage": {
            "type": "string",
            "description": "Localized error message"
          }
        }
      }
    }
  }
}