= Управління ресурсами сервісів адміністративної зони реєстру

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

|===
|Назва компоненти|Репозиторій|Суть зміни

|Restic Daemonset
|`backup-management`
a|В Values.gotmpl зменшити кількість виділених ресурсів. Зміна торкнеться всіх реєстрів на Платформі. Приклад:
----
resources:
  limits:
    cpu: 1500m
  requests:
    cpu: 500m
    memory: 512Mi
----

|Jenkins
|`jenkins-operator`
|В поточному імаджі використовується startup script що задає java opts Xmx від заданого значення `container.limits`.
Єдина можливість обмежити Jenkins — задання `container.limits`, що автоматично вбʼє контейнер.

|Gerrit
|gerrit-operator
a|Для обмеження кількості споживаємих ресурсів памʼяті, необхідно визначити `heapLimit` в `/var/gerrit/review_site/etc/gerrit.config`. Приклад:
----
[container]
  heapLimit = 512M
----

|Nexus
|`nexus-operator`
a|Визначається в `/opt/sonatype/nexus/bin/nexus.vmoptions` Приклад:
----
-Xmx512m
-Xms256m
-XX:MaxDirectMemorySize=512m
-XX:+UnlockDiagnosticVMOptions
-XX:+LogVMOutput
----

|===