= Управління ресурсами реєстру

[NOTE]
--
З поточним станом можна ознайомитись за посиланням xref:attachment$/architecture-workspace/registry-resources.xlsx[Управління ресурсами реєстру].
--

== Управління ресурсами сервісів адміністративної зони

* Gerrit
* Jenkins
* Nexus
* Restic
* ...

=== Зміна кількості виділених ресурсів для сервісів адміністративної зони

|===
|Назва компоненти|Репозиторій|Суть зміни

|Restic Daemonset
|`backup-management`
a|В Values.gotmpl зменшити кількість виділених ресурсів. Зміна торкнеться всіх реєстрів на Платформі. Приклад:
----
resources:
  limits:
    cpu: 1500m
  requests:
    cpu: 500m
    memory: 512Mi
----

|Jenkins
|`jenkins-operator`
|В поточному імаджі використовується startup script що задає java opts Xmx від заданого значення `container.limits`.
Єдина можливість обмежити Jenkins — задання `container.limits`, що автоматично вбʼє контейнер.

|Gerrit
|gerrit-operator
a|Для обмеження кількості споживаємих ресурсів памʼяті, необхідно визначити `heapLimit` в `/var/gerrit/review_site/etc/gerrit.config`. Приклад:
----
[container]
  heapLimit = 512M
----

|Nexus
|`nexus-operator`
a|Визначається в `/opt/sonatype/nexus/bin/nexus.vmoptions` Приклад:
----
-Xmx512m
-Xms256m
-XX:MaxDirectMemorySize=512m
-XX:+UnlockDiagnosticVMOptions
-XX:+LogVMOutput
----

|===

== Управління ресурсами сайд-карів сервісів реєстру

* Видалення CPU requests / liimts та Memory requests / limits

