= Observability

include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

_Атрибут якості визначає наявність та рівень можливостей по оцінці та спостереженню поточного стану системи у процесі її експлуатації на базі згенерованих системою даних подій, метрик та трейсингових даних._

_Платформа Реєстрів_ надає адміністраторам та службі підтримки широкі можливості для моніторингу стану підсистем платформи та розгорнутих на ній реєстрів завдяки постійному збору метрик, подій та трейсингових даних з подальшим їх збереженням для аналізу через візуальні дашборди службових веб-інтерфейсів. Швидкість реагування на інциденти забезпечується механізмом відправки сповіщень відповідно до налаштованих адміністратором правил.

[TIP]
--
Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:arch:architecture/platform/operational/monitoring/overview.adoc[Підсистема моніторингу подій та сповіщення]
* xref:arch:architecture/platform/operational/logging/overview.adoc[Підсистема журналювання подій]
* xref:arch:architecture/platform/operational/distributed-tracing/overview.adoc[Підсистема трасування запитів]
--