= Scalability

== Загальний опис

_Атрибут якості визначає здатність системи опрацьовувати підвищення навантаження без значного впливу на загальну продуктивність, або здатність швидко адаптуватись завдяки збільшенню ресурсів._

_Платформа Реєстрів_ побудована на базі xref:arch:architecture/container-platform/container-platform.adoc[платформи оркестрації контейнерів _OpenShift_], що забезпечує можливості ефективного масштабування підсистем та компонентів реєстру відповідно до поточного навантаження.

xref:arch:architecture/platform/administrative/control-plane/overview.adoc[Підсистема управління Платформою та Реєстрами] надає адміністраторам веб-інтерфейс управління ресурсами кластера та реєстрів з підтримкою двох підходів до масштабування:

* _Вертикальне масштабування_ (_scale-up_) - виділення додаткових ресурсів CPU та пам'яті окремим компонентам, зміни типів та характеристик віртуальних машин кластера, збільшення розмірів системних дисків, тощо.
* _Горизонтальне масштабування_ (_scale-out_) - збільшення ресурсів кластера та реєстру шляхом розгортання додаткових віртуальних машин, створення додаткових копій компонентів з ціллю балансування навантаження, тощо.

[TIP]
--
Детальніше з процедурою масштабування _Платформи Реєстрів_ можна ознайомитись у відповідних розділах:

* xref:admin:scaling/vertical-scaling-master-nodes.adoc[Вертикальне масштабування master nodes для OKD у AWS та vSphere]
* xref:admin:file-system/ceph_scaling.adoc[Масштабування розміру файлової системи Ceph]
* xref:architecture/container-platform/cluster_node_autoscaler.adoc[Автоматичне горизонтальне масштабування екземплярів нод кластера]

Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:arch:architecture/container-platform/container-platform.adoc#_scalability[Платформа оркестрації контейнерів]
* xref:arch:architecture/registry/operational/relational-data-storage/overview.adoc#_scalability[Підсистема управління реляційними базами даних]
* xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc#_scalability[Підсистема управління нереляційними базами даних]
* xref:arch:architecture/platform/operational/distributed-data-storage/overview.adoc#_scalability[Підсистема розподіленого зберігання даних]
--
