= Portability

== Загальний опис

_Даний атрибут якості визначає ступінь незалежності системи від типу інфраструктури, на якій вона може бути розгорнута._

В архітектуру рішення _Платформи Реєстрів_ закладено можливості розгортання в публічному та приватному хмарних середовищах або на власній локальній інфраструктурі.

За процедуру встановлення відповідає xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи], який розроблено з урахуванням сумісності між різними постачальниками інфраструктури.

Поточна версія _Платформи Реєстрів_ має задокументовані та протестовані процедури на прикладі двох типів хмарної інфраструктури:

* Публічне хмарне середовище (_AWS_)
* Приватне хмарне середовище (_vSphere_)

[TIP]
--
Детальніше з процедурою встановлення _Платформи Реєстрів_ можна ознайомитись у відповідних розділах:

* xref:admin:installation/platform-deployment/platform-vsphere-deployment.adoc[Розгортання Платформи в цільовому ЦОД на базі приватної хмари vSphere]
* xref:admin:installation/platform-deployment/platform-aws-deployment.adoc[Розгортання Платформи з нуля в AWS-середовищі]

Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи]
* xref:architecture/container-platform/container-platform.adoc#_portability[Платформа оркестрації контейнерів]
--