= Operability
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

_Атрибут якості визначає наявність та рівень можливостей по обслуговуванню та управлінню налаштуваннями системи у процесі експлуатації._

_Платформа Реєстрів_ надає технічним адміністратором широкі можливості по керуванню центральними компонентами _Платформи_ та розгорнутими на ній реєстрами за допомогою службових веб-інтерфейсів _Підсистеми управління Платформою та реєстрами_.

[TIP]
--
Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:arch:architecture/platform/administrative/control-plane/overview.adoc[]
* xref:arch:architecture/platform/administrative/control-plane/configuration-structure/platform-configuration-structure.adoc[]
* xref:arch:architecture/platform/administrative/control-plane/configuration-structure/registry-configuration-structure.adoc[]
--