= Auditability
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

_Атрибут якості визначає здатність системи фіксувати та надавати інформацію про вагомі технічні та бізнес-події, пов'язані з експлуатацією системи кінцевими користувачами. Надана інформація може бути використана для виявлення та розв'язання проблем у коректності функціонування системи._

В архітектуру рішення _Платформи Реєстрів_ закладено транзакційну модель змін даних реєстру. Зміни до бази даних проводяться лише у межах регламентованих бізнес-процесів з обов'язковим збереженням версійності та підтвердженням змін цифровим підписом користувача або цифровою печаткою реєстру.

Всі важливі системні та бізнес події, пов'язані з експлуатацією реєстру кінцевими користувачами, фіксуються в журналі аудиту для довготривалого зберігання та аналізу.

[TIP]
--
Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:arch:architecture/registry/operational/audit/overview.adoc[Підсистема журналювання подій аудиту]
--