= Auditability

== Загальний опис

_Даний атрибут якості визначає здатність системи фіксувати та надавати інформацію про значимі технічні та бізнес події, пов'язані з експлуатацією системи кінцевими користувачами. Надана інформація може бути використана для виявлення та вирішення проблем в коректності функціонування системи._

В архітектуру рішення _Платформи Реєстрів_ закладено транзакційну модель змін даних реєстру. Зміни до бази даних проводяться лише у межах регламентованих бізнес-процесів з обов'язковим збереженням версійності та підтвердженням змін цифровим підписом користувача або цифровою печаткою реєстру.

Всі важливі системні та бізнес події, пов'язані з експлуатацією реєстру кінцевими користувачами, фіксуються в журналі аудиту для довготривалого зберігання та аналізу.

[TIP]
--
Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:arch:architecture/registry/operational/audit/overview.adoc[Підсистема журналювання подій аудиту]
--