= Availability

== Загальний опис

_Атрибут якості визначає процентне відношення часу, в якій система перебуває в стані доступності та готовності для опрацювання запитів._

_Платформа Реєстрів_ підтримує розгортання в режимі високої доступності як центральних компонентів Платформи, так і реєстрових компонентів.

Висока доступність забезпечується завдяки застосуванню:

* _Active redundancy_ для критичних компонентів
* _Affinity_ та _anti-affinity_ політик розподілу застосунків на віртуальних машинах кластера
* Автоматичному балансуванню навантаження на резервні екземпляри застосунків
* Використанню _rolling_-підходу до розгортання оновлень з мінімальним впливом на користувачів

Показники доступності _Платформи_ та розгорнутих на ній реєстрів не може перевищити _SLA_ дата центру/дата центрів, де буде встановлена платформа та включає доступність компонентів починаючи з шару xref:arch:architecture/container-platform/container-platform.adoc[Платформи оркестрації контейнерів].

[TIP]
--
Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:arch:architecture/container-platform/container-platform.adoc[Платформа оркестрації контейнерів]
* xref:arch:architecture/registry/operational/messaging/overview.adoc[Підсистема асинхронного обміну повідомленнями]
* xref:arch:architecture/registry/operational/relational-data-storage/overview.adoc[Підсистема управління реляційними базами даних]
* xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc[Підсистема управління нереляційними базами даних]
--

== Цільові метрики

При визначенні цільових значень для вищезгаданих метрик, враховується класифікація реєстрів та умови їх експлуатації.

[NOTE]
--
Наведені показники передбачають розгортання _Платформи Реєстрів_ в 2-х дата-центрах або зонах доступності в залежності від типу обраної інфраструктури.
--

.Цільові значення доступності для реєстрів
|===
.2+|Метрика .2+|Клас реєстру 4+^|Цільове значення
|_Продуктивні години_|_Години пік_|_Вечірні години_|_Тіньові години_

.3+|_Availability_ |_Стратегічний_|`99.9%`|`99.9%`|`99.9%`|`95%`
|_Тактичний_|`99.9%`|`99.9%`|`99.9%`|`95%`
|_Оперативний_|`99%`|`99%`|`99%`|`90%`
|===