= Modifiability

== Загальний опис

_Атрибут якості визначає рівень складності та швидкість внесення змін в систему з ціллю розширення функціональних можливостей та виправлення дефектів._

_Платформа Реєстрів_ забезпечує _Low-code_ підхід до розробки та розгортання реєстрів у вигляді _цифрового регламенту реєстру_, що включає декларативні описи моделі даних, бізнес-процесів інформаційних та адміністративних послуг, організаційної структури, зовнішніх інтеграцій та інших.

_Підсистема моделювання регламенту реєстру_ надає _розробникам регламенту_ службові веб-інтерфейси для розробки функціональності реєстрів:

* Моделювання та внесення змін до регламенту реєстру
* Проведення інспекції змін перед внесенням їх до регламенту реєстру
* Перегляд результатів автоматичної перевірки змін в регламент реєстру
* Версіонування регламенту реєстру з історією внесення змін
* Управління налаштуваннями реєстру

_Підсистема розгортання регламенту реєстру_ надає _розробникам регламенту_ забезпечує функції автоматизованого розгортання оновлень функціональності реєстрів:

* Перевірка цілісності регламенту реєстру
* Застосування змін та налаштування операційних сервісів реєстру

[TIP]
--
Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:arch:architecture/registry/administrative/regulation-management/registry-regulation/registry-regulation.adoc[]
* xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[]
--