= Portability

include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

_Атрибут якості визначає ступінь незалежності системи від типу інфраструктури, на якій вона може бути розгорнута._

В архітектуру рішення _Платформи Реєстрів_ закладено можливості розгортання в публічному та приватному хмарних середовищах або на власній локальній інфраструктурі.

За процедуру встановлення відповідає xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи], який розроблено з урахуванням сумісності між різними постачальниками інфраструктури.

Поточна версія _Платформи Реєстрів_ підтримує розгортання у публічне та приватне хмарне середовище:

* https://aws.amazon.com/[Amazon Web Services (AWS)]
* https://azure.microsoft.com/[Microsoft Azure (Azure)]
* https://cloud.google.com/[Google Cloud Platform (GCP)]
* https://www.vmware.com/products/vsphere.html[VMWare vSphere]

[TIP]
--
Детальніше з процедурою встановлення _Платформи Реєстрів_ можна ознайомитись у відповідних розділах:

* xref:admin:installation/platform-deployment/platform-deployment-overview.adoc[]

Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи]
* xref:architecture/container-platform/container-platform.adoc#_portability[Платформа оркестрації контейнерів]
--