= Observability

== Загальний опис

_Цей атрибут якості визначає здатність системи фіксувати та надавати детальну інформацію у вигляді журналів подій, метрик моніторингу та даних трасування транзакцій користувачів з метою спрощення ідентифікації та розв'язання проблем адміністраторами системи._

_Платформа Реєстрів_ надає адміністраторам та службі підтримки широкі можливості для моніторингу стану підсистем платформи та розгорнутих на ній реєстрів завдяки постійному збору метрик, подій та трейсингових даних з подальшим їх збереженням для аналізу через візуальні дашборди службових вебінтерфейсів. Швидкість реагування на інциденти забезпечується механізмом відправки сповіщень відповідно до налаштованих адміністратором правил.

[TIP]
--
Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:arch:architecture/platform/operational/monitoring/overview.adoc[Підсистема моніторингу подій та сповіщення]
* xref:arch:architecture/platform/operational/logging/overview.adoc[Підсистема журналювання подій]
* xref:arch:architecture/platform/operational/distributed-tracing/overview.adoc[Підсистема трасування запитів]
--