= Availability

== Загальний опис

_Даний атрибут якості визначає процентне відношення часу, в якій система перебуває в стані доступності та готовності для опрацювання запитів._

Доступність _Платформи_ та розгорнутих на ній реєстрів не може перевищити _SLA_ дата центру/дата центрів, де буде встановлена платформа та включає доступність компонентів починаючи з шару xref:arch:architecture/container-platform/container-platform.adoc[Платформи оркестрації контейнерів].

[TIP]
--
Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:arch:architecture/container-platform/container-platform.adoc[Платформа оркестрації контейнерів]
* xref:arch:architecture/registry/operational/messaging/overview.adoc[Підсистема асинхронного обміну повідомленнями]
* xref:arch:architecture/registry/operational/relational-data-storage/overview.adoc[Підсистема управління реляційними базами даних]
* xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc[Підсистема управління нереляційними базами даних]
--

== Цільові метрики

При визначенні цільових значень для вищезгаданих метрик, враховується класифікація реєстрів та умови їх експлуатації.

Реєстри за цільовим призначенням поділяються на:

* _Стратегічні_
* _Тактичні_
* _Оперативні_

Умови експлуатації поділяються на:

* _Продуктивні години_ - робочі години чиновника з 8 по 18 протягом робочих днів
* _Години пік_ - 3 години протягом продуктивних годин
* _Вечірні години_ - +2 години після продуктивних годин
* _Тіньові години_ - всі інші години

|===
.2+|Метрика .2+|Клас реєстру 4+^|Цільове значення
|_Продуктивні години_|_Години пік_|_Вечірні години_|_Тіньові години_

.3+|_Availability_ |_Стратегічний_|`99.9%`|`99.9%`|`99.9%`|`95%`
|_Тактичний_|`99.9%`|`99.9%`|`99.9%`|`95%`
|_Оперативний_|`99%`|`99%`|`99%`|`90%`
|===

[NOTE]
--
Необхідно розгортати платформу більше ніж в 1 дата центрі для того, щоб досягнути ці цифри.
--