= Digital registry regulations
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== General description

The **_Registry regulations**_ is a digital representation of important aspects of the registry functioning, consisting of declarative descriptions of the organizational structure, data model, information and administrative services, access rights, templates of excerpts and messages, settings of integrations with external systems, etc.
//_Регламент реєстру_ - це цифрове представлення важливих аспектів функціонування реєстру, що складається з декларативних описів організаційної структури, моделі даних, інформаційних та адміністративних послуг, прав доступу, шаблонів витягів та повідомлень, налаштувань інтеграцій з зовнішніми системами, тощо.

The _registry regulation_ together with the _operational registry configuration_ constitute a necessary and sufficient description of the functionalities implemented in the registry and settings to ensure that the appropriate level of quality of their provision to end users.
//_Регламент реєстру_ разом з _операційною конфігурацією реєстру_ складають необхідний та достатній опис функціональних можливостей, які реалізує реєстр та налаштувань для забезпечення відповідного рівня якості їх надання кінцевим користувачам.

_The Platform for state registries_ implements a _Low-code_ approach to development of digital regulations using service web interfaces -- xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Registry Regulation Modeling Subsystems]. Registry regulations, along with change history, are stored in the appropriate version control repository _Git_ (_Gerrit_) of the registry instance on the _Platform_ to ensure auditability and rollback.
//_Платформа Реєстрів_ реалізує _Low-code_ підхід до розробки цифрового регламенту за допомогою службових веб-інтерфейсів xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Підсистеми моделювання регламенту реєстру]. Регламент реєстру разом з історією змін зберігається у відповідному репозиторії системи контролю версій _Git_ (_Gerrit_) екземпляра реєстру на _Платформі_ задля забезпечення вимог аудиту та можливості відновлення до попередніх версій.

The xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[registry regulations deployment subsystem] handles validation, automated testing, and applying changes to the regulations of the registry operational zone services.
//За валідацію, автоматизоване тестування та застосування змін регламенту до сервісів _Операційної зони_ екземпляра реєстру відповідає xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[].

== Structure

=== Logical representation

This flowchart shows the components of the _registry regulations_ that are currently supported by the _Platform_ to implement the functionality of the registries.
//На даній структурній діаграмі представлено складові частини _регламенту реєстру_, які наразі підтримуються _Платформою_ для реалізації функціональних можливостей реєстрів.

image::architecture/registry/administrative/regulation-management/registry-regulation/regulation-structure.svg[width=800,float="center",align="center"]

When modeling regulations, the relationships shown in the diagram below are supported between their components.
//При моделюванні регламенту, між його складовими підтримуються зв'язки, зображені на діаграмі нижче.

image::architecture/registry/administrative/regulation-management/registry-regulation/regulation-dependencies.svg[width=800,float="center",align="center"]

=== Physical representation

The registry regulations are represented in the _Git_ repository as a set of directories with files. Each file is responsible for configuring a separate aspect of registry functioning according to requirements.
//Регламент реєстру представлений в _Git_-репозиторії набором директорій з файлами, кожна з яких відповідає за налаштування окремого аспекту функціонування реєстру згідно вимог.

[plantuml, registry-regulation-structure, svg]
----
@startsalt
{
{T
+ <&folder> <i><registry-regulation></i>
++ <&folder> <b>data-model</b>
+++ <&file> main-liquibase.xml
+++ <&file> <i><liquibase-file></i>.xml
+++ <&file> ...
++ <&folder> <b>bpmn</b>
+++ <&file> <i><bp-name></i>.bpmn
+++ <&file> ...
++ <&folder> <b>bp-grouping</b>
+++ <&file> bp-grouping.yml
++ <&folder> <b>dmn</b>
+++ <&file> <i><rule-name></i>.dmn
+++ <&file> ...
++ <&folder> <b>forms</b>
+++ <&file> <i><form-name></i>.json
+++ <&file> ...
++ <&folder> <b>form-scripts</b>
+++ <&file> <i><script-name></i>.js
+++ <&file> ...
++ <&folder> <b>roles</b>
+++ <&file> citizen.yml
+++ <&file> officer.yml
++ <&folder> <b>bp-auth</b>
+++ <&file> citizen.yml
+++ <&file> external-system.yml
+++ <&file> officer.yml
++ <&folder> <b>excerpts-csv</b>
+++ <&file> <i><template-name></i>.json
+++ <&file> ...
++ <&folder> <b>excerpts-docx</b>
+++ <&file> <i><template-name></i>.docx
+++ <&file> ...
++ <&folder> <b>excerpts</b>
+++ <&folder> <i><template-name></i>
++++ <&file> index.html.ftl
+++ <&folder> ...
++ <&folder> <b>reports</b>
+++ <&file> <i><report-name></i>.json
+++ ...
++ <&folder> <b>notifications</b>
+++ <&folder> <b>inbox</b> (<i>channel</i>)
++++ <&folder> <i><template-name></i>
+++++ <&file> notification.ftl
+++++ <&file> notification.yml
++++ <&folder> ...
+++ <&folder> <b>email</b> (<i>channel</i>)
++++ <&folder> <i><template-name></i>
+++++ <&file> notification.ftlh
+++++ <&file> notification.yml
++++ <&folder> ...
+++ <&folder> <b>diia</b> (<i>channel</i>)
++++ <&folder> <i><template-name></i>
+++++ <&file> notification.diia
+++++ <&file> notification.yml
++++ <&folder> ...
++ <&folder> <b>bp-trembita</b>
+++ <&file> configuration.yml
+++ <&file> external-system.yml
++ <&folder> <b>global-vars</b>
+++ <&file> camunda-global-system-vars.yml
++ <&folder> <b>settings</b>
+++ <&file> settings.yml
++ <&folder> <b>mock-integrations</b>
+++ <&file> <i><external-system-name></i>.json
+++ <&file> ...
++ <&folder> <b>autotests</b>
+++ <&file> ...
++ <&file> settings.yml
}
}
@endsalt
----

== Components

=== General registry settings

[IMPORTANT]
--
Redesign planned and documented. You can find out more in the xref:architecture-workspace/platform-evolution/registry-settings/registry-settings.adoc[Management of registry settings at the regulation level] section.
//Заплановано та задокументовано редизайн. Детальніше можна ознайомитись у розділі xref:arch:architecture-workspace/platform-evolution/registry-settings/registry-settings.adoc[]
--

This component of the regulations is responsible for configuring registry customizations, and is represented in the repository as two directories and settings files in the _YAML_ format:
//Дана складова частина регламенту відповідає за налаштування кастомізацій реєстру та представлена в репозиторії двома директоріями та файлами налаштувань в _YAML_-форматі:

- `./settings/settings.yml`: Registry customization settings (short name, full name, etc.)
//- `./settings/settings.yml` - Налаштування кастомізацій реєстру (коротка назва, повна назва, тощо.)

.The format of defining general registry settings in the _YAML_ format:
//.Формат визначення загальних налаштувань реєстру в _YAML_-форматі:
[source, yaml]
----
settings:
  general:
    title: "<Setting value>"
    titleFull: "<Setting value>"
----

- `./global-vars/camunda-global-system-vars.yml`: Registry settings (applied portal theme, email address of Support, etc.)
//- `./global-vars/camunda-global-system-vars.yml` - Налаштування реєстру (активна тема кабінетів, поштова адреса служби підтримки, тощо.)

.The format of defining general registry settings in the _YAML_ format:
//.Формат визначення загальних налаштувань реєстру в _YAML_-форматі:
[source, yaml]
----
supportEmail: "<Setting value>"
themeFile: "<Setting value>"
----

[TIP]
--
You can find out more about design of the subsystems responsible for configuring and applying general registry settings in the corresponding sections:
//Детальніше з дизайном підсистем, які відповідають за налаштування та застосування загальних налаштувань реєстру можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Registry regulations modeling subsystem]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[Registry regulations deployment subsystem]
* xref:arch:architecture/registry/operational/portals/overview.adoc[User portals subsystem]
--

=== Registry data model
//=== Модель даних реєстру

This component of the regulations is represented as an individual directory:
//Дана складова частина регламенту представлена окремою директорією:

* `./data-model` - contains a set of _Liquibase_ files for management of:
//* `./data-model` - містить набір _Liquibase_-файлів для управління:
** Physical model of the database
//** Фізичною моделлю бази даних
** Specification of API access to data
//** Специфікацією API доступу до даних
** Data access rights
//** Правами доступу до даних
** Data for initial download
//** Даними для первинного завантаження

[TIP]
--
You can learn more about the design of the subsystems responsible for modeling and using the data model in the corresponding sections:
//Детальніше з дизайном підсистем, які відповідають за моделювання та використання моделі даних можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Registry regulations modeling subsystem]
* xref:arch:architecture/libraries/liquibase-ddm-ext/overview.adoc[Library of Liquibase extensions]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[Registry regulations deployment subsystem]
* xref:arch:architecture/registry/operational/registry-management/overview.adoc[Registry data management subsystem]
--

=== Registry business processes
//=== Бізнес-процеси реєстру

This component of the regulations is responsible for the models of business processes, business rules and is represented as individual directories:
//Дана складова частина регламенту відповідає за моделі бізнес-процесів, бізнес-правил та представлена окремими директоріями:

- `./bpmn`: Contains files in _BPMN_ format with models of administrative and information registry services.
//- `./bpmn` - містить файли у _BPMN_-форматі з моделями адміністративних та інформаційних послуг реєстру
- `./dmn`: Contains files in _DMN_ format with models of business rules for using in registry business processes.
//- `./dmn` - містить файли у _DMN_-форматі з моделями бізнес-правил для використання в бізнес-процесах реєстру
- `./bp-grouping/bp-grouping.yml`: Contains settings of grouping and the order of display in portals of user of business processes of the registry administrative and information services.
//- `./bp-grouping/bp-grouping.yml` - містить налаштування групування та порядку відображення в кабінетах користувачів бізнес-процесів адміністративних та інформаційних послуг реєстру

.The format of defining settings for business processes grouping in the _YAML_ format:
//.Формат визначення налаштувань групування бізнес-процесів в _YAML_-форматі:
[source, yaml]
----

groups:
  - name: "<Group name>"
    processDefinitions:
      - "<Business process key>"
      - ...
  - ...
ungrouped:
  - "<Business process key>"
  - ...

----

[TIP]
--
You can read more about the design of subsystems responsible for modeling and using business processes and business rules in the relevant sections:
//Детальніше з дизайном підсистем, які відповідають за моделювання та використання бізнес-процесів та бізнес-правил можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Registry regulations modeling subsystem]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[Registry regulations deployment subsystem]
* xref:arch:architecture/registry/operational/bpms/overview.adoc[Business processes management subsystem]
* xref:arch:architecture/registry/operational/portals/overview.adoc[User portals subsystem]
--

=== UI forms of registry business processes
//=== UI-форми бізнес-процесів реєстру

This component of the regulations is responsible for setting up UI forms of user tasks in the registry business processes. It is represented as two directories:
//Дана складова частина регламенту відповідає за налаштування UI-форм користувацьких задач бізнес-процесів реєстру. Представлена двома директоріями:

- `./forms`: Contains files with a description of the UI form structures in _JSON_ format, compatible with _Form.UI_.
//- `./forms` - містить файли з описом структур UI-форм у _JSON_-форматі, сумісному з _Form.UI_
- `./form-scripts`: Contains _JavaScript_ files describing functions used in UI forms.
//- `./form-scripts` - містить _JavaScript_-файли з описом функцій, які використовується в UI-формах

[TIP]
--
You can find out more about the design of subsystems responsible for modeling and using UI forms in business processes in the relevant sections:
//Детальніше з дизайном підсистем, які відповідають за моделювання та використання UI-форм бізнес-процесів можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Registry regulations modeling subsystem]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[Registry regulations deployment subsystem]
* xref:arch:architecture/registry/operational/bpms/overview.adoc[Business processes management subsystem]
--

=== Registry user roles
//=== Ролі користувачів реєстру

This component of the regulations is responsible for setting up the roles of registry users and is represented in the repository as an individual directory with two settings files in _YAML_ format:
//Дана складова частина регламенту відповідає за налаштування ролей користувачів реєстру та представлена в репозиторії окремою директорією з двома файлами налаштувань в _YAML_-форматі:

- `./roles/citizen.yml`: Contains a list of the citizen roles.
//- `./roles/citizen.yml` - містить перелік ролей отримувачів послуг реєстру
- `./roles/officer.yml`: Contains a list of the officer roles.
//- `./roles/officer.yml` - містить перелік ролей надавачів послуг реєстру

.The format of defining the registry regulatory roles in _YAML_ format:
//.Формат визначення регламентних ролей реєстру в _YAML_-форматі:
[source, yaml]
----
roles:
  - name: "<Role service name>"
    description: "<Description of regulations role>"
  - ...
----

=== Access rights to the registry business processes
//=== Права доступу до бізнес-процесів реєстру

This component of the regulations is responsible for setting access rights to business processes and is represented in the repository as an individual directory with three settings files in _YAML_ format:
//Дана складова частина регламенту відповідає за налаштування прав доступу до бізнес-процесів та представлена в репозиторії окремою директорією з трьома файлами налаштувань в _YAML_-форматі:

- `./bp-auth/officer.yml`: Settings of access rights for officers to business processes.
//- `./bp-auth/officer.yml` - Налаштувань прав доступу надавачів послуг до бізнес-процесів
- `./bp-auth/citizen.yml`: Settings of access rights for citizens to business processes.
//- `./bp-auth/citizen.yml` - Налаштувань прав отримувачів надавачів послуг до бізнес-процесів
- `./bp-auth/external-system.yml`: Settings of access rights for external systems to business processes.
//- `./bp-auth/external-system.yml` - Налаштувань прав доступу зовнішніх систем до бізнес-процесів

.The format of defining access rights to business processes in _YAML_ format:
//.Формат визначення прав доступу до бізнес-процесів в _YAML_-форматі:

[source, yaml]
----
authorization:
  realm: "<realm: [officer,citizen,external-system]>"
  process_definitions:
    - process_definition_id: "<Business process key>"
      process_name: "<Business process name>"
      process_description: "<Business process description>"
      roles:
        - '<Role>'
        - '...'
    - ...
----

[TIP]
--
You can learn more about the design of the subsystems responsible for setting up and using access rights in the corresponding sections:
//Детальніше з дизайном підсистем, які відповідають за налаштування та використання прав доступу можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Registry regulations modeling subsystem]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[Registry regulations deployment subsystem]
* xref:arch:architecture/registry/operational/bpms/overview.adoc[Business processes management subsystem]
* xref:arch:architecture/registry/operational/portals/overview.adoc[User portals subsystem]
* xref:arch:architecture/registry/operational/external-integrations/overview.adoc[External integrations subsystem]
--

=== Templates for analytical reports
//=== Шаблони аналітичних звітів

This component of the regulations is responsible for setting up dashboard templates for viewing data and registry audit event logs. It is represented as the relevant directory:
//Дана складова частина регламенту відповідає за налаштування шаблонів інформаційних панелей для перегляду даних та журналу подій аудиту реєстру. Представлена відповідною директорією:

- `./reports`: Contains templates of information panels as _JSON_-format files compatible with _Redash_.
//- `./reports` - містить шаблони інформаційних панелей у вигляді файлів _JSON_-формату, сумісного з _Redash_

[TIP]
--
You can find out more about the design of the subsystems responsible for modeling and using dashboard templates in the corresponding sections:
//Детальніше з дизайном підсистем, які відповідають за моделювання та використання шаблонів інформаційних панелей можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Registry regulations modeling subsystem]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[Registry regulations deployment subsystem]
* xref:arch:architecture/registry/operational/reporting/overview.adoc[Registry analytical reporting subsystem]
--

=== Templates of excerpts from the registry
//=== Шаблони витягів з реєстру

This component of the regulations is responsible for setting templates for generating excerpts from the registry. It is represented as three directories, taking into account the types of excerpts supported by the _Platform for state registries_:
//Дана складова частина регламенту відповідає за налаштування шаблонів для генерації витягів з реєстру. Представлена трьома директоріями з урахуванням типів витягів, які підтримуються _Платформою Реєстрів_:

- `./excerpts`: Contains template files in _FTLH_ format for generating _PDF_ excerpts.
//- `./excerpts` - містить файли шаблонів у _FTLH_-форматі для генерації _PDF_-витягів
- `./excerpts-docx`: Contains template files in _DOCX_ format for generating _DOCX_ excerpts.
//- `./excerpts-docx` - містить файли шаблонів у _DOCX_-форматі для генерації _DOCX_-витягів
- `./excerpts-csv`: Contains template files in _JSON_ format for generating _CSV_ excerpts.
//- `./excerpts-csv` - містить файли шаблонів у _JSON_-форматі для генерації _CSV_-витягів

[TIP]
--
You can learn more about the design of the subsystems responsible for modeling and using excerpt templates in the corresponding sections:
//Детальніше з дизайном підсистем, які відповідають за моделювання та використання шаблонів витягів можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Registry regulations modeling subsystem]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[Registry regulations deployment subsystem]
* xref:arch:architecture/registry/operational/excerpts/overview.adoc[Registry excerpts generation subsystem]
--

=== Templates for registry information notifications
//=== Шаблони інформаційних повідомлень реєстру

This component of the regulations is responsible for setting up templates for sending informational messages to registry users. It is represented as three directories, taking into account the communication channels supported by the _Platform for state registries_:
//Дана складова частина регламенту відповідає за налаштування шаблонів для відправки інформаційних повідомлень користувачам реєстру. Представлена трьома директоріями з урахуванням каналів зв'язку, які підтримуються _Платформою Реєстрів_:

- `./notifications/inbox`: Contains template files in _FTL_ format for generating _in-app_ notifications.
//- `./notifications/inbox` - містить файли шаблонів у _FTL_-форматі для генерації _in-app_-повідомлень
- `./notifications/email`: Contains template files in _FTLH_ format for generating the body of email notifications.
//- `./notifications/email` - містить файли шаблонів у _FTLH_-форматі для генерації тіла поштових повідомлень
- `./notifications/diia`: Contains template files in the _DIIA_ text format used in the _Diya_ ecosystem to generate notifications.
//- `./notifications/diia` - містить файли шаблонів у текстовому _DIIA_-форматі, який застосовується в екосистемі _Дія_ для генерації повідомлень

[TIP]
--
You can read more about the design of the subsystems responsible for modeling and using information notification templates in the corresponding sections:
//Детальніше з дизайном підсистем, які відповідають за моделювання та використання шаблонів інформаційних повідомлень можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Registry regulations modeling subsystem]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[Registry regulations deployment subsystem]
* xref:arch:architecture/registry/operational/notifications/overview.adoc[User notification subsystem]
--

=== Registry integration with external systems
//=== Інтеграція реєстру з зовнішніми системами

This component of the regulations is responsible for setting up the outgoing and incoming integrations of the registry and is represented as an individual directory with two settings files in _YAML_ format:
//Дана складова частина регламенту відповідає за налаштування вихідних та вхідних інтеграцій реєстру та представлена окремою директорією з двома файлами налаштувань в _YAML_-форматі:

- `./bp-trembita/configuration.yml`: Configuration of integration points with external systems according to registry configuration.
//- `./bp-trembita/configuration.yml` - Налаштування точок інтеграції з зовнішніми системами згідно конфігурації реєстру

.The format of defining general registry settings in _YAML_ format:
//.Формат визначення загальних налаштувань реєстру в _YAML_-форматі:
[source, yaml]
----
external-systems:
  external-system-name1:
        operations:
          ...
  external-system-name2:
        operations:
          ...
  ...
----

- `./bp-trembita/external-systems.yml`: API settings for calling business processes by external systems.
//- `./bp-trembita/external-systems.yml` - Налаштування API для виклику бізнес-процесів зовнішніми системами

.The format of defining general registry settings in _YAML_ format:
//.Формат визначення загальних налаштувань реєстру в _YAML_-форматі:
[source, yaml]
----
trembita:
  process_definitions:
    - process_definition_id: '<Business process key>'
      start_vars: []
      return_vars: []
   - ...
----

[TIP]
--
You can learn more about the design of the subsystems, responsible for configuring and using the settings for integrations with external systems, in the corresponding sections:
//Детальніше з дизайном підсистем, які відповідають за налаштування та використання налаштувань інтеграцій з зовнішніми системами можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Registry regulations modeling subsystem]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[Registry regulations deployment subsystem]
* xref:arch:architecture/registry/operational/bpms/overview.adoc[Business processes management subsystem]
* xref:arch:architecture/registry/operational/external-integrations/overview.adoc[External integrations subsystem]
--

=== Registry regulations testing
//=== Тестування регламенту реєстру

This component of the regulations is responsible for setting up the API modeling of external systems and a set of automated tests. It is represented as two directories:
//Дана складова частина регламенту відповідає за налаштування симуляції API зовнішніх систем та набір автоматизованих тестів. Представлена двома директоріями:

- `./autotests`: A suite of _BDD_ functional tests for automated registry testing.
//- `./autotests` - набір _BDD_ функціональних тестів для автоматизованого тестування реєстру
- `./mock-integrations`: A set of _JSON_-files in _Wiremock_-format with a description of the API rules for mocking external systems for the purpose of their further modeling in the process of manual and automated registry testing.
//- `./mock-integrations` - набір _JSON_-файлів у _Wiremock_-форматі з описом правил мокування API зовнішніх систем з ціллю їх подальшої симуляції у процесі ручного та автоматизованого тестування реєстру.

[TIP]
--
You can read more about the design of the subsystems responsible for modeling and using the regulation component in the corresponding sections:
//Детальніше з дизайном підсистем, які відповідають за моделювання та використання складової регламенту можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Registry regulations modeling subsystem]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[Registry regulations deployment subsystem]
* xref:arch:architecture/registry/operational/ext-systems-simulation/overview.adoc[External systems simulation API subsystem]
--