:toc-title: ЗМІСТ
:toc: auto
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
//:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:
= Платформа для розгортання та супроводження державних електронних реєстрів

== Що таке платформа?

_Платформа_ -- це інструмент для швидкого створення, моделювання, розгортання та керування державними реєстрами для ефективного надання державних послуг в режимі онлайн. Платформа дозволяє досягати оптимального балансу між вимогами безпеки даних, швидкістю розгортання, вартістю володіння реєстрами та обміном даними з іншими реєстрами.

.Контекстна діаграма Платформи
image::tech:architecture-workspace/ddm-platform-context.svg[]

== Проблематика

=== Поточна ситуація з реєстрами в Україні

В Україні існує понад 350 державних реєстрів, які належать різним власникам. Кожен реєстр створюється та підтримується за допомогою окремої команди та експлуатується у власній інфраструктурі (on premise чи хмарній).

NOTE: Поточну ситуацію можна класифікувати як `децентралізовану` та `нерегульовану`.

Під `децентралізованою` слід розуміти зберігання даних в окремих власників на окремій інфраструктурі, що є дуже важливим моментом з огляду несення відповідальності за збір, збереження та використання даних.

Під `нерегульованою` слід розуміти, що не існує можливості гарантувати коректну взаємодію між реєстрами через захищені транспорти, виконання вимог щодо збереження даних, повторне використання підходів та заощадження ресурсів.

=== Концепція платформи для розгортання реєстрів в Україні та розв'язання проблеми

З огляду на поточну ситуацію та можливі ризики з визначенням відповідальності за збереження даних, Платформа дозволяє перейти до `децентралізованого` та `регульованого` підходу.

Такий підхід гарантує збереження чіткого власника даних, і, як наслідок, збереження відповідальності за дані. З іншого боку -- це активує можливість розробки та модернізації платформи для створення реєстрів як комплексу програмно-апаратних засобів для імплементації вимог, сформованих та контрольованих Міністерством цифрової трансформації України.

[architecture-principles]
==== Загальні архітектурні принципи побудови платформи

Регульований підхід дозволяє з технічного боку будувати та розвивати платформу, спираючись на ключові архітектурні принципи: ::

* ІС «Платформа» побудована на принципах мікросервісної архітектури на базі Cloud-платформи, побудованої на основі https://docs.openshift.com/[RedHat OpenShift].

* Один екземпляр ІС «Платформа» підтримує розгортання та роботу декількох реєстрів.
//* ІС «Платформа» має бути розрахованою на 10.000 одночасно працюючих користувачів.

* ІС «Платформа» задовільняє належним безпековим вимогам щодо НД ТЗІ та КСЗІ, а також відмовостійкості системи.

* Розробка реєстру, розгорнутого на ІС «Платформа», базується на принципах Low-code (BPMN, користувацькі форми, API для бази даних, REST API-взаємодія між сервісами).

* ІС «Платформа» підтримує логування (фіксацію подій) та моніторинг компонентів реєстру.
+
Усі зміни на платформі та в реєстрах і доступи до даних логуються. Журнали доступу надійно захищені від змін.

* ІС «Платформа» забезпечує резервне копіювання компонентів та даних реєстру, центральних компонентів платформи, а також відновлення master-нод кластера ІС «Платформа». Це убезпечує користувачів від втрати будь-яких критично важливих даних.

* Платформа забезпечує надійний захист конфіденційних даних.
+
Конфіденційні дані є надійно захищеними від непередбаченого доступу і «витоку» інформації.

* Платформа забезпечує надійність зберігання даних.
+
БД кожного окремого реєстру захищена від втрати даних та знищення.

* Платформа дозволяє зберігати всю історію змін.
+
З реєстру дані не видаляються. Оновлення даних відбувається з обов'язковим збереженням версійності. Журнал транзакцій захищений від змін.

* Платформа підтримує транзакційну модель змін у реєстрі.
+
Зміни у базі даних не відбуваються відбуватися напряму. Усі дії з БД проводяться лише у межах регламентованих бізнес-процесів. Усі транзакції є підтверджені (наприклад, запити на зміни, підписані КЕП).

* Платформа забезпечує унеможливлення несанкціонованих змін. Зміни у даних реєстру неможливі:
** без відповідних прав доступу;
** без аутентифікації та авторизації;
** за межами регламентованих бізнес-процесів.

* Платформа забезпечує можливість розподілу прав на основі https://uk.wikipedia.org/wiki/%D0%9A%D0%B5%D1%80%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F_%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%BE%D0%BC_%D0%BD%D0%B0_%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D1%96_%D1%80%D0%BE%D0%BB%D0%B5%D0%B9[RBAC].
+
Розподіл прав організовано таким чином, що немає «суперадміна», який може виконати будь-які дії у системі. Це дозволяє нівелювати ризики незаконних дій із даними системи.

== З чого почати?

Цей сайт є базою знань та справжнім колодязем інформації, яка допоможе вам краще зрозуміти продукт.

Меню навігації містить такі основні розділи за призначенням: ::

* Хочете дізнатися про нові розробки та поліпшення? Переходьте до секції xref:release-notes:overview.adoc[]

* Якщо ви адміністратор інфраструктури платформи, адміністратор безпеки, або доступу, зверніться до розділу xref:admin:overview.adoc[].

* Якщо ви з команди супроводу та розробки реєстрів, які розгортаються на базі платформи, зверніться до розділу xref:registry-develop:overview.adoc[].

* Якщо ви адміністратор реєстру, або адміністратор регламенту, зверніться до розділу xref:registry-develop:registry-admin/index.adoc[].

* Якщо ви моделювальник, або адміністратор даних, працюєте зі структурами операційних даних та декларативним описом моделі, формуєте аналітичну звітність, зверніться до розділу xref:registry-develop:data-modeling/index.adoc[].

* Якщо ви моделювальник бізнес-процесів, UI-форм для бізнес-процесів, працюєте з BPMN, DMN та JSON-структурами, зверніться до розділу xref:registry-develop:bp-modeling/index.adoc[].

* Якщо ви хочете поглибити власні знання щодо роботи зі структурами регламенту, для вас розроблено спеціальний xref:registry-develop:study-project/index.adoc[]. Він містить перелік практичних навчальних на контрольних завдань для адміністраторів регламенту та всіх охочих.

* Якщо ви посадова особа, або отримувач послуг реєстру, працюєте з особовими кабінетами в рамках бізнес-процесів реєстру, зверніться до розділу xref:user:overview.adoc[].

* Якщо ви розробник, архітектор, або просто технічний гуру, зверніться до секції xref:tech:overview.adoc[].

* Цікавлять готові відповіді на часті запитання? Зверніться до розділу xref:faq:faq.adoc[].

// INTRODUCTION SECTION

////

METAINFO

Документація
Цей документ є адаптацією Epam SAD 2.6 і містить технічний опис системи розгортання електронних реєстрів.

=== Структура документа

Документація розділена на два типи:

- Документація яка обмежена описом одного конкретного компонента системи (секція *Компоненти* цього документу) - така документація має лежати в тому ж репозиторії, що і код, і підтримуватись всіма членами команди та контребьютерами в данний репозиторій

- Документація що описує міжкомпонентну взаємодію, загальні характеристи платформи які стосуються кожного компонента або не належать жодному - така документація зберігається як код в окремому https://gitbud.epam.com/mdtu-ddm/general/ddm-architecture[репозиторії]
////