:toc-title: ЗМІСТ
:toc: auto
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
//:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:
= Платформа для розгортання та супроводження державних електронних реєстрів

== Що таке Платформа?

_Платформа_ -- це інструмент (інформаційна система) для швидкого створення, моделювання, розгортання та керування державними реєстрами для ефективного надання державних послуг в режимі онлайн. Платформа дозволяє досягати оптимального балансу між вимогами безпеки даних, швидкістю розгортання, вартістю володіння реєстрами та обміном даними з іншими реєстрами.

.Контекстна діаграма Платформи
image::tech:architecture-workspace/ddm-platform-context.svg[]

== Проблематика

=== Поточна ситуація з реєстрами в Україні

В Україні існує понад 350 державних реєстрів, які належать різним власникам. Кожен реєстр створюється та підтримується за допомогою окремої команди та експлуатується у власній інфраструктурі (апаратне забезпечення чи хмарна).

Поточну ситуацію можна класифікувати як [.underline]#децентралізовану# та [.underline]#нерегульовану#: ::

Під [.underline]#децентралізованою# слід розуміти зберігання даних в окремих власників на окремій інфраструктурі, що є дуже важливим моментом з огляду несення відповідальності за збір, збереження та використання даних.
+
Під [.underline]#нерегульованою# слід розуміти, що не існує можливості гарантувати коректну взаємодію між реєстрами через захищені з'єднання, виконання вимог щодо збереження даних, повторне використання підходів та заощадження ресурсів.

=== Концепція платформи для розгортання реєстрів в Україні та розв'язання проблеми

З огляду на поточну ситуацію та можливі ризики з визначенням відповідальності за збереження даних, Платформа дозволяє перейти до [.underline]#децентралізованого# та [.underline]#регульованого# підходу.

Такий підхід гарантує збереження визначеного власника даних, і, своєю чергою, збереження відповідальності за дані. З іншого боку -- це активує можливість розробки та модернізації платформи для створення реєстрів як комплексу програмно-апаратних засобів для імплементації вимог, що сформовані та регульовані Міністерством цифрової трансформації України.

[architecture-principles]
==== Загальні архітектурні принципи побудови Платформи

Регульований підхід дозволяє з технічного боку будувати та розвивати платформу, спираючись на ключові архітектурні принципи: ::

* [*] Платформа побудована на принципах [.underline]#мікросервісної архітектури# на базі хмарної інфраструктури, побудованої на основі https://www.okd.io/[OKD].

* [*] Один екземпляр Платформи підтримує розгортання та роботу декількох реєстрів.
//* ІС «Платформа» має бути розрахованою на 10.000 одночасно працюючих користувачів.

* [*] Платформа відповідає належним безпековим вимогам https://cip.gov.ua/ua/news/perelik-dokumentiv-sistemi-tekhnichnogo-zakhistu-informaciyi-nd-tzi[НД ТЗІ] та https://cip.gov.ua/ua/news/poradi-rekomendaciyi-shodo-stvorennya-kszi-v-its-yaki-vikoristovuyutsya-dlya-nadannya-poslug-dostupu-do-merezhi-internet[КСЗІ], і є [.underline]#відмовостійкою#.

* [*] Розробка реєстру, що розгорнуто на Платформі, базується на принципах https://en.wikipedia.org/wiki/Low-code_development_platform[Low-code] (https://bpmn.io/[BPMN], користувацькі форми, Декларативний опис API для бази даних, REST API-взаємодія між сервісами").

* [*] Система підтримує [.underline]#логування (фіксацію подій)# та [.underline]#моніторинг# компонентів реєстру.
+
Таким чином усі зміни на платформі та в реєстрах і доступи до даних логуються. Журнали доступу надійно захищені від змін.

* [*] Система забезпечує [.underline]#резервне копіювання компонентів та даних# реєстру, центральних компонентів платформи, а також відновлення майстер-нод кластера OpenShift. Це убезпечує користувачів від втрати будь-яких критично важливих даних.

* [*] Платформа забезпечує [.underline]#надійний захист конфіденційних даних#. Конфіденційні дані надійно захищені від непередбаченого доступу і «витоку» інформації.

* [*] Платформа забезпечує [.underline]#надійність зберігання даних#, завдяки чому база даних кожного окремого реєстру захищена від втрати даних та знищення.

* [*] Платформа дозволяє [.underline]#зберігати всю історію змін#. З реєстру дані не видаляються. Оновлення даних відбувається з обов'язковим збереженням версійності. Журнал транзакцій захищений від змін.

* [*] Платформа підтримує [.underline]#транзакційну модель змін# у реєстрі. Зміни до бази даних не виконуються напряму. Усі дії з БД проводяться лише у межах регламентованих бізнес-процесів. Усі транзакції є підтверджені (наприклад, запити на зміни, підписані КЕП тощо).

* [*] Платформа [.underline]#унеможливлює несанкціоновані зміни#. Зміни у даних реєстру неможливі:

** без відповідних прав доступу (згідно зі змодельованими бізнес-процесами);
** без автентифікації та авторизації;
** за межами регламентованих бізнес-процесів.

* [*] Платформа забезпечує [.underline]#можливість розподілу прав# на основі xref:registry-develop:bp-modeling/bp/access/roles-rbac-bp-modelling.adoc[RBAC]. Розподіл прав організовано таким чином, що немає «супер адміністратора», який може виконати будь-які дії у системі. Це дозволяє нівелювати ризики незаконних дій із даними системи.

== З чого почати?

Цей сайт є базою знань, яка допоможе вам краще зрозуміти продукт.

Меню навігації містить такі основні розділи за призначенням: ::

* Хочете дізнатися про нові розробки та поліпшення, переходьте до секції xref:release-notes:overview.adoc[].

* Якщо ви адміністратор інфраструктури платформи, адміністратор безпеки, або доступу, зверніться до розділу xref:admin:overview.adoc[].

* Якщо ви з команди розробки та супроводу реєстрів, які розгортаються на базі платформи, зверніться до розділу xref:registry-develop:overview.adoc[].

* Якщо ви адміністратор реєстру, або адміністратор регламенту, зверніться до розділу xref:registry-develop:registry-admin/index.adoc[].

* Якщо ви моделювальник даних, працюєте зі структурами операційних даних та декларативним описом моделі, формуєте аналітичну звітність, зверніться до розділу xref:registry-develop:data-modeling/index.adoc[].

* Якщо ви моделювальник бізнес-процесів, UI-форм для бізнес-процесів, працюєте з BPMN, DMN та JSON-структурами, зверніться до розділу xref:registry-develop:bp-modeling/index.adoc[].

* Для поглиблення знань щодо роботи зі структурами регламенту, для вас розроблено спеціальний xref:registry-develop:study-project/index.adoc[]. Він містить перелік навчальних та контрольних завдань для розвитку практичних навичок моделювання регламенту.

* Якщо ви посадова особа, або отримувач послуг реєстру, працюєте з особистим кабінетом у рамках бізнес-процесів, зверніться до розділу xref:user:overview.adoc[].

* Якщо ви розробник, архітектор, або просто технічний гуру, зверніться до секції xref:tech:overview.adoc[].

* Цікавлять готові відповіді на часті запитання? Зверніться до розділу xref:faq:faq.adoc[].

// INTRODUCTION SECTION

////

METAINFO

Документація
Цей документ є адаптацією Epam SAD 2.6 і містить технічний опис системи розгортання електронних реєстрів.

=== Структура документа

Документація розділена на два типи:

- Документація яка обмежена описом одного конкретного компонента системи (секція *Компоненти* цього документу) - така документація має лежати в тому ж репозиторії, що і код, і підтримуватись всіма членами команди та контребьютерами в данний репозиторій

- Документація що описує міжкомпонентну взаємодію, загальні характеристи платформи які стосуються кожного компонента або не належать жодному - така документація зберігається як код в окремому https://gitbud.epam.com/mdtu-ddm/general/ddm-architecture[репозиторії]
////
