[glossary]
= Глосарій та Акроніми Платформи

[glossary]
API Платформи реєстрів:: <<API-Фабрики-даних>>
[[API-Фабрики-даних]]API Фабрики даних:: Програмний інтерфейс фабрики даних, доступний для інших компонентів платформи, що надає набір функцій для взаємодії з даними реєстру.
BPMN (Business Process Model and Notation):: Нотація і модель бізнес-процесів — система умовних позначень для моделювання бізнес-процесів
CC (Competency Center):: Команда яка відповідає за консультації команд розробки реєстрів і агрегацію запитів по новому функціоналу та наявним багам. 
[[Control-Plane]]Control Plane:: Сукупність компонентів платформи, що забезпечує спрощення керування центральними компонентами платформи, дозволяє керувати реєстрами та агрегує посилання до всіх WEB API центральних компонентів.
DMN (Decision Model and Notation):: Нотація для моделювання бізнес-правил за допомогою таблиць прийняття рішень.
GitOps-підхід:: Спосіб реалізації безперервного розгортання для нативних хмарних додатків. Основна ідея GitOps полягає в тому що будь-які зміни у конфігурації кластера OpenShift, компонентів кластера та компонентів Платформи відбуваються через внесення змін до конфігурації відповідних компонентів у git-гілках цих компонентів.
Low-code:: Підхід до створення, налаштування та модифікації системи та додатків, який практично не вимагає написання програмного коду. В контексті Платформи це компоненти за допомогою яких цей підхід реалізується.
OpenShift:: Система автоматичного розгортання, масштабування та управління застосунками у контейнерах.
RBAC (Role Based Access Control):: Керування доступом на основі ролей. Привілеї не призначаються користувачам безпосередньо а отримуються ними тільки через свою роль (або ролі), управління індивідуальними правами користувача по суті зводиться до призначення йому ролей
[[UI-форма]]UI-форма:: Форма задачі користувача кабінету для внесення даних у рамках виконання бізнес-процесу. 
Автентифікація:: Перевірка достовірності пред'явленого користувачем ідентифікатора.
Авторизація:: Надання і перевірка прав на здійснення будь-яких операцій в системі.
Адмін портал:: <<Кабінет-адміністратора-регламентів>>
Адміністративна послуга:: Послуга що передбачає зміну певного статусу чи інших даних в реєстрі. На Платформі це бізнес-процес, реалізований на рівні окремого реєстру, результатом якого є внесення змін до даних реєстру.
Аналітична БД:: База даних яка обслуговує аналітичні інструменти, зокрема Redash. Отримує данні реєстру через логічну реплікацію з операційної бази даних. Доступна лише на читання.
[[Аналітичний-звіт]]Аналітичні звіти:: Попередньо налаштовані загальні статистичні дані за реєстром. Побудовані за допомогою сервісу аналітичної звітності Redash. Можуть містити графіки, таблиці, картки показників та примітки щодо ефективності робочого процесу.
Бізнес-процес:: Набір операцій спрямованих на досягнення певного результату шляхом обробки даних. BPMN моделі бізнес процесів є частиною регламенту реєстру.
Версія-кандидат регламенту реєстру:: Логічне представлення стану мастер-версії після застосування змін, сформованих в рамках відповідного запиту на внесення змін.
Витяг:: Документ згенерований в рамках надання інформаційних послуг через бізнес-процеси, який може бути завантажений користувачем, який замовив інформаційну послугу. Представлений окремим шаблоном на рівні регламенту реєстру.
Відкриті дані:: Публічна інформація у форматі, що дозволяє її автоматизоване оброблення електронними засобами, вільний та безоплатний доступ до неї, а також її подальше використання
Група реєстрів:: Реєстри що належать одному власнику та є спорідненими.
Дані реєстру:: Інформація що зберігається в базі даних реєстру
Дашборд:: <<Аналітичний-звіт>>
ДРФО:: Державний реєстр фізичних осіб - платників податків. Використовується у сенсі "код ДРФО" див. <<РНОКПП,РНОКПП>>
Електронний підпис:: В рамках цього документу це КЕП, УЕП, ЕЦП фізичної чи юридичної особи або електронна печатка юридичної особи. Використання КЕП, УЕП в залежності від ситуації залежить від чинних вимог законів та законодавства.
ЕЦП (Електронний цифровий підпис)::  Дані в електронній формі, отримані за результатами криптографічного перетворення, які додаються до інших даних або документів і забезпечують їх цілісність та ідентифікацію автора.
ЄДР:: Єдиний державний реєстр юридичних осіб, фізичних осіб-підприємців та громадських формувань.
ЄДРПОУ:: Код ЄДРПОУ (Єдиного державного реєстру підприємств та організацій України) — унікальний ідентифікаційний номер юридичної особи в Єдиному державному реєстрі підприємств та організацій України
Запит на внесення змін:: Логічне представлення сукупності змін відносно поточної _мастер-версії_ регламенту, до якого застосовуються перевірки цілісності, якості та інспекції перед безпосереднім застосуванням до _мастер-версії_.
Інтерфейс адмін-консолі:: <<Control-Plane>>
Інформаційна панель:: <<Аналітичний-звіт>>
Інформаційна послуга::  Бізнес-процес, реалізований на рівні окремого реєстру, результатом якого є отримання даних реєстру у визначеній формі. Передбачає підтвердження того чи іншого статусу в реєстрі. Результатом "Послуги" буде витяг, або підтвердження прав.
[[Кабінет-адміністратора-регламентів]]Кабінет адміністратора регламентів:: Клієнтський веб-додаток для адміністрування реєстрів. Інтерфейс дозволяє виконувати необхідну конфігурацію регламенту реєстру без володіння глибокими уміннями програмування.
Кабінет користувача:: Загальна назва для кабінету отримувача послуг і кабінету посадової особи.
Кабінет отримувача послуг:: Веб-інтерфейс для взаємодії з реєстром у вигляді клієнтського додатку кабінету орієнтований на обслуговування громадян.
Кабінет посадової особи:: Веб-інтерфейс для взаємодії з реєстром у вигляді клієнтського додатку кабінету орієнтований на обробку задач посадовою особою.
КЕП (Кваліфікований електронний підпис):: Електронний підпис користувача, що використовується для аутентифікації та підпису внесених ним даних.
Керування кластером (платформою):: Абстракція в рамках Control Plane, що дозволяє керувати центральними компонентами системи
Компоненти реєстру:: Компоненти платформи, що встановлюється окремо для кожного реєстру.
Конфігурація реєстру:: Налаштування компонентів реєстру доступне в control plane та репозиторії реєстру в відповідності з gitops підходом.
Конфіденційні дані:: Дані для доступу до яких потрібна авторизація.
КСЗІ (Комплексна система захисту інформації):: Сукупність організаційних та інженерних заходів та програмно-апаратних засобів, що забезпечують захист інформації в системі.
Майстер-версія регламенту:: <<Мастер-версія-регламенту>>
[[Мастер-версія-регламенту]]Мастер-версія регламенту:: Поточна версія регламенту, розгорнута на екземплярі реєстру.
Модель даних:: Описи змісту, структури та обмежень цілісності, які використовуються для створення та підтримки бази даних реєстру. Представлена визначенням у liquibase форматі на рівні регламенту реєстру.
Об'єкти (Приналежність даних)::  Будь-яка сутність, якою володіє суб'єкт.
Онбординг громадян (отримувачів послуг):: Процес орієнтований на створення всіх необхідних записів у БД для взаємодії користувача з реєстром (профіль користувача, налаштування, призначення ролі користувача)
Операційна БД:: База даних яка обслуговує додатки та сервіси реєстру та зберігає дані реєстру, налаштування, дані бізнес процесів та інші операційні дані.
Операційне сховище бізнес-процесів:: Реляційне сховище, в якому зберігаються розгорнуті моделі бізнес-процесів, поточний стан виконання екземплярів процесів та породжені ними дані, налаштування авторизацій та загальні налаштування.
Отримувач послуг:: Користувач який взаємодіє з реєстром з ціллю отримання адміністративних та інформаційних послуг. Ця роль може призначатися фізичній особі, представнику ФОП або юридичної особи. Системна роль. 
Пакетне завантаження (імпорт користувачив):: Процес створення великої кількості користувачів-посадових осіб в реєстрі шляхом імпорту з CSV файлу.
Первинна автентифікації / авто-реєстрації громадян (отримувачів послуг):: Процес створення користувача - отримувача послуг реєстру та встановлення профілю взаємодії з кабінетом отримувача послуг на основі даних отриманих з особистого ключа КЕП та даних, отриманих у результаті інтеграції з ЄДР.
[[Персональні-дані]]Персональні дані:: Відомості чи сукупність відомостей про фізичну особу, яка ідентифікована або може бути конкретно ідентифікована. Класифікація даних як персональних відбувається на рівні створення моделі даних реєстру, що застосовує відповідні механізми обробки і доступу.
Платформа (IC «Платформа»):: Розгорнута інформаційна система реєстру, яка надає органам влади можливість створювати та в рамках повноважень вести реєстри за моделлю SaaS “Реєстр як сервіс”. Передбачається розгортання платформи як в хмарі, так і на базі власного ЦОД, а також розгортання платформи як для одного реєстру, так і для групи реєстрів.
Платформа ведення реєстрів:: OpenShift кластер зі встановленими компонентами необхідні для створення та ведення реєстрів.
Платформа даних:: <<Фабрика-даних>>
Платформні ключі цифрового підпису:: Ключі що використовуються для інтеграції з id.gov.ua.
Платформні компоненти:: <<Центральні компоненти>>
Посадова особа:: Представник державного органу, що взаємодіє із реєстром у рамках виконання своїх службових обов'язків. Системна роль.
Послуга:: Один або декілька бізнес-процесів в реєстрі спрямовані на опрацювання запиту особи.
Публічно доступні дані:: Дані для доступу до яких не потрібна авторизація
Регламент/правила реєстру::  Набір моделей даних, бізнес-процесів, налаштувань, за якими реєстр буде реалізовувати свої функції.
Реєстр:: Спеціалізований інформаційний ресурс, призначений для зберігання та обробки юридично важливої інформації про людей, їх права та обов'язки, а також майно та ресурси.
Реєстровий пайплайн:: Процес що виконує застосування конфігурації реєстру.
Реєстрові  ключі цифрового підпису:: Ключі що використовуються для підписання трансформованих даних бізнес форм і підписування витягів.
Рейт-ліміти:: Обмеження кількості запитів від одного користувача.
[[РНОКПП]]РНОКПП (Реєстраційний номер облікової картки платника податків):: Елемент Державного реєстру фізичних осіб України (ДРФО) , який надається фізичним особам-платникам податків та інших обов'язкових платежів та зберігається за ними протягом усього їхнього життя.
Розгортання регламенту реєстру:: Процедура створення або оновлення сервісів реєстру, бізнес-процесів та структури бази даних реєстру згідно з регламентом реєстру. 
Ролі регламенту:: Ролі які створюються під час розгортання регламенту реєстру та налаштовуються в регламенті реєстру.
Роль користувача:: Системні ролі та ролі регламенту, які призначені користувачу. 
СЕВДЕІР / Трембіта:: Система електронної взаємодії державних електронних інформаційних ресурсів.
Системні ролі:: Ролі які створюються Платформою під час розгортання реєстру або встановлення Платформи.
Суб’єкти (Приналежність даних):: будь-яка фізична або юридична особа, що має право власності над об'єктом.
Схема UI-форми:: Формальний опис структури, полів та валідаційних правил UI-форми. Представлена як файл на рівні регламенту реєстру.
Сховище історичних даних бізнес-процесів:: База даних в якій зберігаються значущі історичні події виконання бізнес-процесів (історія ініційованих користувачем та завершених бізнес-процесів та виконаних задач користувача).
Сховище проміжних даних бізнес-процесів:: Розподілене сховище пар ключ-значення, в якому тимчасово зберігаються дані, внесені користувачами через UI-форми задач бізнес-процесів.
[[Фабрика-даних]]Фабрика даних:: Підсистема платформи відповідальна за збереження даних та надання доступу до них.
Форма:: <<UI-форма>>
[[Центральні-компоненти]]Центральні компоненти:: компоненти системи, що спільно використовуються усіма реєстрами та існують в єдиному екземплярі на кластері.
Цифрові документи:: Файли вкладення які можуть бути завантажені, вивантажені та переглянуті користувачами через UI-форми задач бізнес-процесів. Зберігаються в об'єктному сховищі реєстру. Зміст цифрових документів не є об'єктом виконання операцій на рівні бізнес-процесів.
ЦОД:: Центр обробки даних (Data center).
ШБО "Трембіта":: Шлюз Безпечного Обміну — захищений інтерфейс для електронної взаємодії між державними системами, який розгортається в межах Платформи реєстрів як сервіс і дозволяє використовувати власні ресурси для отримання інформації із зовнішніх систем.