= Функція _get_variable()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`get_variable(String variableName): Object`* використовується для доступу до змінних контексту.

== Параметри

.Параметри функції
|===
|*Аргумент*        | *Опис*
| `variableName`   | Ім'я змінної, значення якої потрібно отримати.
|===

== Що повертає

Ця функція повертає об'єкт типу `Object`, що містить значення змінної з контексту. Якщо змінна з таким іменем не існує, функція поверне `null`.

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

NOTE: Функція `get_variable(String variableName)` дозволяє отримати значення змінної з контексту виконання.

== Приклади використання

Цей розділ демонструє приклади використання JUEL-функції у Groovy-скриптах бізнес-процесу.

Нижче показано приклади використання функції `get_variable()` контекстно, разом із функціями xref:bp-modeling/bp/juel-functions/variables/set-variable.adoc[_set_variable()_] та xref:bp-modeling/bp/juel-functions/variables/set-transient-variable.adoc[_set_transient_variable()_]

=== Скрипт 1: встановлення значення змінної

[source,groovy]
----
set_variable('processData', 'Деякі важливі дані процесу')

// Встановлення тимчасової змінної 'tempData' для короткочасного використання
set_transient_variable('tempData', 'Тимчасові дані')
----

У цьому прикладі змінна `processData` зберігається у контексті виконання за допомогою функції `set_variable()`, а змінна `tempData` встановлюється як тимчасова за допомогою `set_transient_variable()`.

=== Скрипт 2: отримання значення змінних на іншому етапі процесу

Приклад нижче демонструє, як отримати значення змінних, збережених раніше у процесі, за допомогою функції `get_variable()`.

[source,groovy]
----
def processData = get_variable('processData')
println "Retrieved process data: ${processData}"

// Отримання значення тимчасової змінної 'tempData' (якщо вона ще існує)
def tempData = get_variable('tempData')
println "Retrieved temporary data: ${tempData}"
----

=== Пояснення

. У *Скрипті 1* змінна `processData` зберігається у контексті виконання за допомогою функції `set_variable()`. Це значення буде доступне на будь-якому етапі процесу.

. Змінна `tempData` встановлюється як тимчасова за допомогою `set_transient_variable()`. Вона доступна лише протягом поточного виконання і може не зберігатися до наступного етапу процесу.

. У *Скрипті 2* ці значення витягуються з контексту виконання за допомогою функції `get_variable()`, і їх можна використовувати для подальших дій у процесі.

== Пов'язані сторінки

* xref:bp-modeling/bp/juel-functions/variables/set-variable.adoc[]
* xref:bp-modeling/bp/juel-functions/variables/set-transient-variable.adoc[]