= Функція _set_variable()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`set_variable(String variableName, Object variableValue)`* використовується у скриптових завданнях бізнес-процесу для встановлення або оновлення змінних контексту.

== Параметри

.Параметри функції
|===
|*Аргумент*        | *Опис*
| `variableName`   | Ім'я змінної, яку потрібно встановити або оновити.
| `variableValue`  | Значення змінної, яке потрібно встановити.
|===

== Що повертає

Ця функція не повертає значення.

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

[NOTE]
====
Функція `set_variable(String variableName, Object variableValue)` дозволяє встановити або оновити змінні в контексті виконання. Змінні, встановлені цією функцією, зберігаються в Camunda DB і залишаються доступними до завершення процесу.

Якщо потрібно встановити тимчасову змінну у процесі, яка буде доступна лише між певними станами очікування бізнес-процесу, використовуйте функцію xref:bp-modeling/bp/juel-functions/variables/set-transient-variable.adoc[_set_transient_variable()_].
====

== Приклади використання

Цей розділ демонструє приклади використання JUEL-функції у скриптових завданнях бізнес-процесу.

Поданий нижче Groovy-скрипт конвертує JSON у CSV, зберігає CSV у цифровому сховищі документів та зберігає метадані нового документа в процесній змінній.

.Приклад використання функції `set_variable()`
[source,groovy]
----
def result = [:]
result['uploadedFile'] = [metadata]
set_variable('result', S(result, 'application/json'))
----

TIP: Застосування функції `set_variable()` детально представлено у референтному прикладі на сторінці xref:best-practices/bp-upload-edit-file.adoc[].

== Пов'язані сторінки

* xref:bp-modeling/bp/juel-functions/variables/set-transient-variable.adoc[]
* xref:bp-modeling/bp/juel-functions/variables/get-variable.adoc[]
* xref:best-practices/bp-upload-edit-file.adoc[]