= Функція _set_variable()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`set_variable(String variableName, Object variableValue)`* використовується для встановлення або оновлення змінних контексту.

== Параметри

.Параметри функції
|===
|*Аргумент*        | *Опис*
| `variableName`   | Ім'я змінної, яку потрібно встановити або оновити.
| `variableValue`  | Значення змінної, яке потрібно встановити.
|===

== Що повертає

Ця функція не повертає значення.

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

[NOTE]
====
Функція `set_variable(String variableName, Object variableValue)` дозволяє встановити або оновити змінні в контексті виконання. Змінні, встановлені цією функцією, зберігаються в Camunda DB і залишаються доступними до завершення процесу.

Якщо потрібно встановити тимчасову змінну у процесі, яка буде доступна лише між певними станами очікування бізнес-процесу, використовуйте функцію xref:bp-modeling/bp/juel-functions/set-transient-variable.adoc[_set_transient_variable()_].
====

== Приклад

Цей розділ демонструє приклади використання JUEL-функції у завданнях бізнес-процесу.

//TODO: ADD

TIP: Застосування функції `set_variable()` детально представлено у референтному прикладі на сторінці xref:best-practices/bp-context-variable-management.adoc[].