= Функція _set_transient_variable()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`set_transient_variable(String variableName, Object variableValue)`* використовується для встановлення або оновлення тимчасових змінних контексту.

== Параметри

.Параметри функції
|===
|*Аргумент*        | *Опис*
| `variableName`   | Ім'я змінної, яку потрібно встановити або оновити.
| `variableValue`  | Значення змінної, яке потрібно встановити.
|===

== Що повертає

Ця функція не повертає значення.

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

[NOTE]
====
Функція `set_transient_variable(String variableName, Object variableValue)` використовується для встановлення тимчасових змінних у процесі, які будуть доступні лише між певними станами очікування бізнес-процесу (найчастіше це -- завдання користувача). Такі змінні зберігаються всередині поду `bpms`-сервісу.

Якщо потрібно встановити або оновити змінні в контексті виконання, які зберігатимуться в Camunda DB і залишатимуться доступними до завершення процесу, використовуйте функцію xref:bp-modeling/bp/juel-functions/set-variable.adoc[_set_variable()_].
====

== Приклад

Цей розділ демонструє приклади використання JUEL-функції у завданнях бізнес-процесу.

//TODO: ADD

TIP: Застосування функції `set_transient_variable()` детально представлено у референтному прикладі на сторінці xref:best-practices/bp-transient-variable-management.adoc[].