@startuml
actor "Адміністратор платформи" as admin  order 10
participant "Bash-installer" as bashInstaller  order 20
participant "Nexus Registry" as nexus  order 30
participant "Ceph" as ceph  order 30
participant "Keycloak" as keycloak  order 40
participant "Helm-installer" as installer  order 50
participant "CotrolPlane components" as cp  order 60
participant "Cluster-management helm in Gerrit" as gerrit  order 70
participant "Gitops Job Jenkins" as jenkins  order 80
participant "Інші компоненти" as other  order 90

title Детальна інсталяція платформи
autonumber

admin -> bashInstaller: запускає інсталлер
activate bashInstaller
    bashInstaller -> nexus: встановлює Nexus Docker Registry (разом з імеджами)
    bashInstaller -> ceph: встановлює Ceph
    bashInstaller -> keycloak: встановлює Keycloak
    bashInstaller -> installer: запускає helmfile installer
    activate installer
        installer -> cp: встановлює CP компоненти
        activate cp
            cp -> jenkins: встановлює jenkins
            cp -> gerrit: встановлює image з clustermanagement repo
            activate gerrit
                gerrit -> gerrit: інціалізує clustermanagement repo з helm
            return
        return
    return
return
activate cp
  activate jenkins
    cp -> jenkins: створює gitops job для clustermanagement
    cp -> jenkins: запускає gitops job для clustermanagement
    jenkins -> gerrit: checkout helmfile
    jenkins -> jenkins: запускає helmfile
    jenkins -> other: встановлює
  deactivate jenkins
  cp -> keycloak: створює realm для Control Plane
  cp -> cp: інтегрує всі компоненти з keycloak
deactivate cp

@enduml