@startuml

title Діаграма взаємодії компонентів платформи

package "DDM platform Install" as ddm_platform_install{
  [Denovo OKD Install] as denovo_okd_install
  [DDM Core Install] as ddm_core_install
}
ddm_core_install -down-> ddm_components_install: deploys Nexus, Ceph and Platform Keycloak


package "DDM Core components Install" as ddm_components_install {
  [Nexus registry]
  [Platform Keycloak]
  [Object Storage]
}

ddm_core_install -down-> ddm_cp_install: deploys Control Plane components

package "DDM Control Plane (CP) install" as ddm_cp_install {
  [DDM CP Edp Operators] as ddm_cp_edp_operators
  note top of ddm_cp_edp_operators
    Helm contains:
      -keycloak-operator
      -EDP Keycloak Realm
      -jenkins-operator
      -gerrit-operator
      -codebase-operator
      -nexus-operator
  end note
  [DDM CP Applicaiton] as ddm_cp_app
  note top of ddm_cp_app
    Helm contains:
      -EDP Admin Console CR for ddm control plane
  end note
  [DDM CP Gerrit] as ddm_gerrit
  note top of ddm_gerrit
    Helm contains:
      -EDP Gerrit CR
      -EDP GitServer CR
      -EDP Codebase CR for cluster-management
  end note
  [DDM CP Jenkins] as ddm_jenkins
  note top of ddm_jenkins
    Helm contains:
      -EDP Jenkins CR
      -EDP JenkinsScript CR
      -Job Provisioner ConfigMap
  end note
}

package "Infra Components" as infra_components {
  [logging]
  [storage]
  [monitoring]
  [service-mesh]
  [user-management]
  [backup-management]
}

denovo_okd_install -[hidden]down-> ddm_components_install
ddm_gerrit -down-> infra_components : collects all helm charts into one folder with concrete versions,\nwhich should be converted to repository """cluster-mgmt"""  in a template folder
ddm_gerrit -[hidden]down-> infra_components
ddm_gerrit -down-> registry_components : collects all helm charts into one folder with concrete versions,\nwhich should be converted to repository """regitstry-tenant-template"""


package "Registry Components" as registry_components {
  [keycloak-operator]
  [jenkins-operator]
  [gerrit-operator]
  [codebase-operator]
  [kong]
  [kafka]
  [citus]
  [bpms]
  [formio]
  [officer-portal]
  [user-process-management]
  [business-process-administration-portal]
  [user-task-management]
  [digital-signature-ops]
  [dataplatform-jenkins-agent]
}



package "Registry Regulations" as registry_regulations {
  [registry-regulation-template]
}

ddm_gerrit -down-> registry_regulations : creates repository """regitstry-regulations-template"""

legend
 Each component is a dedicated git repository
end legend

@enduml
