@startuml

title Діаграма взаємодії компонентів платформи

package "DDM platform Install" as ddm_platform_install{
  [Denovo OKD Install] as denovo_okd_install
  [DDM Core Install] as ddm_core_install
}
ddm_core_install -down-> ddm_components_install: deploys Nexus, Ceph and Platform Keycloak


package "DDM Core components Install" as ddm_components_install {
  [catalog-source]
  [storage]
  [logging]
  [service-mesh]
  package "Outside Openshift" #DDDDDD {
    [platform-vault]
    [platform-minio]
  }
  [control-plane-nexus]
  package "user-management" {
    [digital-signature-ops]
    [keycloak]
    [hashicorp-vault]
  }
}

ddm_core_install -down-> ddm_cp_install: deploys Control Plane components

package "DDM Control Plane (CP) install" as ddm_cp_install {
  [keycloak-operator ]
  [codebase-operator ]
  [control-plane-console ]
  [control-plane-gerrit] as ddm_gerrit
  [control-plane-jenkins]
}

package "Infra Components" as infra_components {
  [logging ]
  [storage ]
  [monitoring ]
  [service-mesh ]
  package "user-management" as user-management_infra {
    [digital-signature-ops ]
    [keycloak ]
    [hashicorp-vault ]
  }
  [backup-management ]
  [catalog-source ]
}

denovo_okd_install -[hidden]down-> ddm_components_install
ddm_gerrit -down-> infra_components : collects all helm charts into one folder with concrete versions,\nwhich should be converted to repository """cluster-mgmt"""  in a template folder
ddm_gerrit -[hidden]down-> infra_components
ddm_gerrit -down-> registry_components : collects all helm charts into one folder with concrete versions,\nwhich should be converted to repository """registry-tenant-template"""


package "Registry Components" as registry_components {
  [bpms]
  [officer-portal]
  [jenkins-operator]
  [gerrit-operator]
  [codebase-operator]
  [user-process-management]
  [bp-admin-portal]
  [user-task-management]
  [digital-signature-ops]
  [kong]
  [form-management]
  [admin-portal]
  [redash-chart]
  [pg-exporter-chart]
  [citus]
  [strimzi-kafka-operator]
  [nexus]
  [keycloak-operator]
  [kafka-schema-registry]
  [citizen-portal]
  [user-settings-service-persistence]
  [user-settings-service-api]
  [bp-webservice-gateway]
  [digital-document-service]
  [hashicorp-vault]
  [excerpt-service-api]
  [excerpt-worker]
  [dataplatform-jenkins-agent]
}



package "Registry Regulations" as registry_regulations {
  [registry-regulation-template-minimal]
  [registry-regulation-template-recommended]
}

ddm_gerrit -down-> registry_regulations : creates repository """registry-regulations-template"""

legend
 Each component is a dedicated git repository
end legend

@enduml