apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakAuthFlow
metadata:
  name: {{ .Values.registryFederation.name }}-dso-officer-auth-flow
  annotations:
    "helm.sh/resource-policy": keep
spec:
  alias: dso-officer-auth-flow
  authenticationExecutions:
    - authenticator: ds-officer-authenticator
      requirement: ALTERNATIVE
      priority: 1
      authenticatorConfig:
        alias: ds-officer-authenticator-configuration
        config:
          dsoUrl: 'http://digital-signature-ops:8080/api/esignature/owner'
          widgetUrl: '{{ .Values.registryFederation.widgetUrl }}'
          widgetHeight: '{{ .Values.registryFederation.widgetHeight }}'
          selfRegistrationEnabled: '{{ .Values.registryFederation.selfRegistrationEnabled }}'
          {{ if eq .Values.registryFederation.selfRegistrationEnabled "true" }}
          selfRegistrationDefaultRoles: 'default-roles-registry-federation-{{ .Values.registryFederation.name }}'
          {{- else -}}
          selfRegistrationDefaultRoles: ''
          {{- end }}
          startPageUrl: 'https://{{ .Values.keycloak.host }}'
          themeFile: white-theme.js
    - authenticator: auth-cookie
      requirement: ALTERNATIVE
      priority: 0
  builtIn: false
  providerId: basic-flow
  realm: registry-federation-{{ .Values.registryFederation.name }}
  topLevel: true