apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakRealm
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  name: registry-federation-{{ .Values.registryFederation.name }}
spec:
  keycloakOwner: main
  realmName: registry-federation-{{ .Values.registryFederation.name }}
  ssoRealmEnabled: false
  themes:
    loginTheme: dso-officer-login-theme
  browserSecurityHeaders:
    contentSecurityPolicy: "frame-src 'self' https://{{ (urlParse .Values.registryFederation.widgetUrl).host }}; frame-ancestors 'self'; object-src 'none';"
  browserFlow: dso-officer-auth-flow