= JUEL-функції у бізнес-процесах
:toc:
:toclevels: 5
:toc-title: ЗМІСТ
:sectanchors:

== Загальний опис

У https://camunda.com/products/camunda-platform/modeler/[Camunda] ви можете використовувати скрипти в різних місцях xref:registry-develop:bp-modeling/bp/bp-modeling-instruction.adoc[бізнес-процесу]. Наприклад, при роботі зі https://docs.camunda.org/manual/7.4/reference/bpmn20/tasks/script-task/[Script Task]. Camunda Engine підтримує скриптування мовами JavaScript, Groovy або JUEL тощо.

У розрізі Платформи реєстрів реалізовано підтримку скриптування за допомогою Groovy та http://juel.sourceforge.net/[JUEL (Java Unified Expression Language)] -- уніфікованої скриптової мови виразів Java -- з використанням спеціальних розроблених JUEL-функцій, для спрощення моделювання бізнес-процесів.

Перелік доступних функцій: ::

. xref:#fn-intiator[Функція] `initiator()`.
. xref:#fn-completer[Функція] `completer()`.
. xref:#submission-fn[Функція] `submission()`.
. xref:#fn-sign-submission[Функція] `sign_submission(<activity_id|event_id>)`.
. xref:#fn-system-user[Функція] `system_user()`.

:sectnums:

[#fn-intiator]
== Функція initiator()

Функція `initiator()` призначена для отримання та подальшого використання xref:registry-develop:bp-modeling/bp/bp-modeling-instruction.adoc#initial-event[ініціатора] (`initiator`) в процесі. +
Повертає клас `UserDto`.

TIP: `UserDto` -- клас, що є обгорткою даних користувача (тут -- ініціатора).
Завжди містить у собі `userName`, токен і `JwtClaimsDto` до першої задачі користувача.

[initiator-methods]
=== Методи взаємодії

Функція надає наступні методи:

* `getUserName()` -- повертає ім'я користувача, що можна використовувати в полях `Assignee` та `Candidate Users` задач користувача.
* `getAccessToken()` -- повертає токен користувача, що можна використовувати в інтеграційних конекторах для інтеграції від імені користувача.
* `getDrfo()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `drfo` користувача.
* `getEdrpou()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `edrpou` користувача.
* `getFullName()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `fullName` користувача.

NOTE: Токен ініціатора, а разом з ним і всі атрибути Keycloak, будуть доступні тільки до першої користувацької задачі (**User Task**) у бізнес-процесі.

[#fn-completer]
== Функція completer()

Функція `completer(<task_id>)` дозволяє отримати виконавця користувацької задачі для подальшого використання у процесі. +
Повертає клас `UserDto`.

TIP: `UserDto` -- клас, що є обгорткою даних користувача (тут -- ініціатора).
Завжди містить у собі `userName`, токен і `JwtClaimsDto` до першої задачі користувача.

[completer-methods]
=== Методи взаємодії

Функція надає наступні методи:

* `getUserName()` -- повертає ім'я користувача, що можна використовувати в полях `Assignee` та `Candidate Users` задач користувача.
* `getAccessToken()` -- повертає токен користувача, що можна використовувати в інтеграційних конекторах для інтеграції від імені користувача.
* `getDrfo()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `drfo` користувача.
* `getEdrpou()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `edrpou` користувача.
* `getFullName()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `fullName` користувача.

NOTE: Функція `completer(<task_id>)` доступна для використання після успішного завершення користувацької задачі.

[#submission-fn]
== Функція submission()

Функція `submission(<activity_id|event_id>)` дозволяє отримати дані форми користувацької задачі та повертає клас `UserFormDataDto`.

TIP: `UserFormDataDto` -- _клас, що є обгорткою даних форми користувача._

NOTE: Функція `submission(<activity_id|event_id>)` доступна для використання після успішного завершення користувацької задачі або стартової форми.

[#fn-sign-submission]
== Функція sign_submission()

Функція `sign_submission(<activity_id|event_id>)` використовується для отримання підпису та даних форми користувацьких задач. +
Повертає клас `SignUserFormDataDto`.

TIP: `SignUserFormDataDto` -- _клас, що є обгорткою для даних форми користувача, підпису та ключа CEPH-документа, де зберігається підпис._

NOTE: _Функція `sign_submission(<activity_id|event_id>)` доступна для використання після успішного завершення задачі, що потребує валідації підписом користувача, або стартової форми._

[#fn-system-user]
== Функція system_user()

Функція `system_user()` необхідна для отримання системного користувача з Keyclock. +
Повертає клас `UserDto`.

TIP: `UserDto` -- _клас, що є обгорткою даних користувача (тут -- ініціатора).
Завжди містить у собі `userName`, токен і `JwtClaimsDto` до першої задачі користувача._

[system-user-methods]
=== Методи взаємодії

Функція надає наступні методи:

* `getUserName()` -- повертає ім'я користувача, що можна використовувати в полях `Assignee` та `Candidate Users` задач користувача.
* `getAccessToken()` -- повертає токен користувача, що можна використовувати в інтеграційних конекторах для інтеграції від імені користувача.
* `getDrfo()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `drfo` користувача.
* `getEdrpou()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `edrpou` користувача.
* `getFullName()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `fullName` користувача.