= Часткове оновлення сутності у Фабриці даних
:toc:
:toc-title: ЗМІСТ
:toclevels: 5
:sectnums:
:sectnumlevels: 5
:sectanchors:

WARNING: Документ у процесі формування.

== Загальний опис

Для всіх таблиць у Фабриці даних, з якими взаємодіють сервіси, Платформою використовується 4 основних HTTP-методи: `POST`, `GET`, `PUT` та `DELETE`.

Для оновлення сутності у Фабриці даних використовується метод `PUT` та відповідний імплементований делегат *Update entity in data factory*.
При використанні `PUT`, у тілі запита необхідно вказувати значення усіх полів таблиці, навіть тих, які оновлення не потребують. Така поведінка передбачена для методу `PUT` за замовчуванням.

.Приклад
====
Наприклад, маємо таблицю, яка містить 5 полів: `Ім'я`, `Прізвище`, `По батькові`, `Дата народження`, `Місце роботи`. Нам потрібно оновити лише 1-ше поле (`Ім'я`) з 5-ти.

При використанні метода `PUT`, необхідно буде встановити значення для кожного з 5-ти полів об'єкта.
Інакше всі незаповнені поля автозаповняться як `NULL`.
====

Функціональність часткового оновлення сутності (`partialUpdate`) розв'язує цю проблему. Часткове оновлення на рівні API використовує HTTP-метод `PATCH`. Цей метод ігнорує всі незаповнені поля, не зазначені у тілі запита. Він опрацьовує лише ті параметри, які потребують оновлення.

Відповідно на рівні API реалізовано окремий ендпоінт для роботи із методом `PATCH`, який дозволяє частково оновити сутність у базі даних (_див. xref:#api-implementation[]_).

Для взаємодії з API та можливості надсилати бізнес-дані до БД, на рівні бізнес-процесів розроблено типове розширення -- делегат `${dataFactoryConnectorPartialUpdateDelegate}`, для якого імплементовано однойменний шаблон *Update entity in data factory partially*, представлений у вигляді JSON-файлу _dataFactoryConnectorNestedCreateDelegate.json_.

Делегат потрібний для того, щоб оновлювати значення конкретних параметрів у таблицях БД.


//TODO: Add info
== Використання та налаштування у бізнес-процесі


[#api-implementation]
== Імплементація на рівні API

На рівні API Фабрики даних реалізовано окремий ендпоінт для роботи із методом `PATCH` для часткового оновлення сутності у БД.

.Параметри запита для часткового оновлення сутності у БД
====
Метод та ресурс: ::
----
PATCH /partial/<resource-name>/<resource-id>
----

Тіло запита: ::
[source,json]
----
{
	"firstName":"Іван",
	"lastName":"Сидоренко",
	"birthday":"2020-01-01"
}
----
====

== Імплементація на рівні моделі даних

На рівні структури даних, у файлі _createSearchConditions.xml_ необхідно додати відповідний changeSet із тегом `<ext:partialUpdate>`.

Це дозволить автоматично створити окремий `PATCH`-ендпоінт на рівні API для підтримки функції часткового оновлення сутності.

.Приклад. changeSet для часткового оновлення сутності у БД
====
[source,xml]
----
<changeSet author="registry owner" id="partial update person_profile">
	<ext:partialUpdate>
		<ext:table name="person_profile">
			<ext:column name="last_name"/>
			<ext:column name="first_name"/>
			<ext:column name="birthday"/>
		</ext:table>
	</ext:partialUpdate>
</changeSet>
----
====
