:sectanchors:
:sectlinks:
= Резервне копіювання та відновлення

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

Цей розділ надає всебічну інформацію про стратегії аварійного відновлення для забезпечення стійкості кластера в умовах збоїв. Основний акцент зроблено на відновленні кластера після збоїв, також надаються деталі щодо процедур відновлення мастер-нод кластера Openshift.

Далі, розділ розкриває методи резервного копіювання та відновлення центральних компонентів Платформи, забезпечуючи розуміння критичних аспектів безпеки та надійності.

Також включено інформацію про резервне копіювання та відновлення середовища реєстру, з урахуванням додаткового механізму створення резервних копій та відновлення баз даних реєстру.

Цей розділ є важливим ресурсом для розуміння повного спектра опцій відновлення, доступних для підтримки безперебійної роботи вашої системи.

== Огляд секції

.*Відновлення кластера*
[%collapsible]
====
* xref:admin:disaster-recovery/cluster-disaster-recovery.adoc[Аварійне відновлення роботи кластера у випадку збоїв]
* xref:backup-restore/master_ip_repair.adoc[Відновлення master-нод кластера]
====

.*Центральні компоненти*
[%collapsible]
====
* xref:backup-restore/control-plane-components-backup-restore.adoc[Резервне копіювання та відновлення центральних компонентів]
* xref:backup-restore/backup-schedule-cluster-mgmt.adoc[Керування розкладом створення резервних копій центральних компонентів та часом їх зберігання]
====

.*Середовище реєстру*
[%collapsible]
====
* xref:backup-restore/control-plane-backup-restore.adoc[Резервне копіювання та відновлення екземпляра реєстру]
* xref:backup-restore/backup-schedule-registry-components.adoc[Керування розкладом резервного копіювання реєстру]
* xref:backup-restore/postgres-backup-restore.adoc[Резервне копіювання та відновлення БД реєстру]
====
