= Спрощений процес розробки регламенту через мастер-версію для форм і бізнес-процесів та захист від перезапису змін

== Загальний опис
В процесі розробки або виправлення незначних помилок які не потребують значних змін в регламенті розробнику все одно
доводиться робити велику кількість дій, а саме: створення версії кандидати в Адмін порталі, внесення змін в регламент та
інтеграція змін в мастер-версію. Це вимагає великої кількості часу та зусиль. Для покращення досвіду моделювання
необхідно надати можливість вносити зміни в безпосередньо в мастер-версію регламенту.

== Функціональні сценарії
* Редагування форми безпосередньо в мастер-версії регламенту реєстру
* Редагування бізнес-процесу безпосередньо в мастер-версії регламенту реєстру
* Створення форми безпосередньо в мастер-версії регламенту реєстру
* Створення бізнес-процесу безпосередньо в мастер-версії регламенту реєстру
* Редагування форми в мастер-версії регламенту реєстру зі спрощеним процесом створення версії кандидату
* Редагування бізнес-процесу в мастер-версії регламенту реєстру зі спрощеним процесом створення версії кандидату
* Створення форми в мастер-версії регламенту реєстру зі спрощеним процесом створення версії кандидату
* Створення бізнес-процесу в мастер-версії регламенту реєстру зі спрощеним процесом створення версії кандидату
* Копіювання форми в мастер-версії регламенту реєстру
* Копіювання бізнес-процесу в мастер-версії регламенту реєстру
* Видалення форми в мастер-версії регламенту реєстру
* Видалення бізнес-процесу в мастер-версії регламенту реєстру

[NOTE]
--
Всі функціональні сценарії відносяться до _Веб-інтерфейсу моделювання регламенту_
--


== Ролі користувачів
* Розробник регламенту

== Загальні принципи та положення
* Розробник регламенту може редагувати,створювати або видаляти форму або бізнес-процес безпосередньо в мастер-версії
регламенту реєстру
* _Сутність_ - це загальна назва форми або бізнес-процесу в цьому документі
* Спрощений процес створення версії кандидату містить в собі автоматизовану послідовність кроків при натисканні кнопки
редагування/створення/видалення _сутності_, а саме внесення інформації про версію-кандидат, створення версії кандидату,
внесення змін в _сутність_ та збереження змін в версії кандидату
* При редагуванні, створенні та видаленні _сутності_ необхідно забезпечити захист від перезапису змін, які можуть бути
внесені іншими моделювальниками
* При створенні сутності повинна виконуватися перевірка на наявність сутності з таким іменем
* При редагуванні та видаленні сутності повинна виконуватися перевірка на те що зміни застосовуються відносно останньої
версії сутності (незалежно у версії-кандидаті чи мастер-версії)
* При перевірці на зміни повинно враховуватися що зміни можуть бути внесені як через Адмін портал, так і напряму у
Gerrit
* При редагуванні та видаленні сутності (http method PUT, DELETE) використовується загальний
xref:arch:architecture/registry/administrative/regulation-management/services/registry-regulation-management/rest-api/rest-api-partials/optimistic-locking.adoc[]
підхід який використовується в системі
* При наявності змін, що конфліктують система після обробки такого запиту повинна залишатися в консистентному стані
* При наявності змін, що конфліктують користувач повинен власноруч скопіювати контент, який редагував, оновити сторінку
з _сутністю_ та внести зміни вручну
* При заведенні змін безпосередньо в мастер повинен створюватися Gerrit MR з параметром submit та private. Submit -
вказує на те, що зміни повинні бути відразу інтегровані. Private - використовується для розділення для маркування змін,
які не потребуються запуски пайплайну перевірки регламенту (додаткове налаштування в Jenkins-Gerrit інтеграції)

== Високорівневий дизайн рішення

.Компонентна діаграма
image::architecture/registry/administrative/regulation-management/evolution/master-development/component.svg[]

.Діаграма діяльності. Створення сутності
image::architecture/registry/administrative/regulation-management/evolution/master-development/create-entity.svg[]

.Діаграма діяльності. Оновлення сутності
image::architecture/registry/administrative/regulation-management/evolution/master-development/update-entity.svg[]

.Діаграма діяльності. Видалення сутності
image::architecture/registry/administrative/regulation-management/evolution/master-development/delete-entity.svg[]

=== Захист від перезапису

.Створення форми/бізнес-процесу. Захист від перезапису змін
[plantuml, req1, svg]
----
@startuml
actor User as user
participant rrm as "RRM"
participant git as "Local Git repo"
participant gerrit as "Origin Gerrit"
actor counterpart as "Counterpart"

user -> rrm: creates form/bp
activate rrm
group Concurrent validation
    rrm -> git: file exists?
    git --> rrm: response
end

alt file already exists
    rrm --> user: HTTP 412 Precondition Failed
end

alt concurrent work in Admin Portal
    counterpart -> git: creates form/bp with the same name
else concurrent work in Gerrit
    counterpart -> gerrit: creates form/bp\nwith the same name
end

rrm -> rrm: do some side stuff
rrm -> rrm: acquire lock
activate rrm #DarkSalmon
group Concurrent validation
    rrm -> git: file exists?
    git --> rrm: response
end

alt file already exists
    rrm --> user: HTTP 412 Precondition Failed
end
rrm -> git: write file content

rrm -> git: git add\ngit commit\ngit push
git -> gerrit: push changes
alt merge conflict
    gerrit --> git: merge conflicts
    git --> rrm: merge conflicts
    rrm -> git: git fetch
    git -> gerrit: git fetch
    rrm -> git: hard reset on origin head branch
    rrm --> user: HTTP 412 Precondition Failed
end
rrm -> rrm: release lock
deactivate rrm
rrm --> user: ok
deactivate rrm

@enduml
----

.Оновлення форми/бізнес-процесу. Захист від перезапису змін
[plantuml, req2, svg]
----
@startuml
actor User as user
participant rrm as "RRM"
participant git as "Local Git repo"
participant gerrit as "Origin Gerrit"
actor counterpart as "Counterpart"

user -> rrm: update form/bp
activate rrm
group Concurrent validation
    rrm -> git: get file content
    git --> rrm: file content
    rrm -> rrm: compare etags
end

alt etags are different
    rrm --> user: HTTP 412 Precondition Failed
end

alt concurrent work in Admin Portal
    counterpart -> git: updates form/bp
else concurrent work in Gerrit
    counterpart -> gerrit: updates form/bp
end

rrm -> rrm: do some side stuff
rrm -> rrm: acquire lock
activate rrm #DarkSalmon
group Concurrent validation
    rrm -> git: get file content
    git --> rrm: file content
    rrm -> rrm: compare etags
end
alt etags are different
    rrm --> user: HTTP 412 Precondition Failed
end
rrm -> git: write file content

rrm -> git: git add\ngit commit\ngit push
git -> gerrit: push changes
alt merge conflict
    gerrit --> git: merge conflicts
    git --> rrm: merge conflicts
    rrm -> git: git fetch
    git -> gerrit: git fetch
    rrm -> git: hard reset on origin head branch
    rrm --> user: HTTP 412 Precondition Failed
end
rrm -> rrm: release lock
deactivate rrm
rrm --> user: ok
deactivate rrm

@enduml
----

.Видалення форми/бізнес-процесу. Захист від перезапису змін
[plantuml, req3, svg]
----
@startuml
actor User as user
participant rrm as "RRM"
participant git as "Local Git repo"
participant gerrit as "Origin Gerrit"
actor counterpart as "Counterpart"

user -> rrm: deletes form/bp
activate rrm
group Concurrent validation
    rrm -> git: get file content
    git --> rrm: file content
    rrm -> rrm: compare etags
end

alt etags are different
    rrm --> user: HTTP 412 Precondition Failed
end

alt concurrent work in Admin Portal
    counterpart -> git: updates form/bp
else concurrent work in Gerrit
    counterpart -> gerrit: updates form/bp
end

rrm -> rrm: do some side stuff
rrm -> rrm: acquire lock
activate rrm #DarkSalmon
group Concurrent validation
    rrm -> git: get file content
    git --> rrm: file content
    rrm -> rrm: compare etags
end
alt etags are different
    rrm --> user: HTTP 412 Precondition Failed
end
rrm -> git: deletes content

rrm -> git: git add\ngit commit\ngit push
git -> gerrit: push changes
alt merge conflict
    gerrit --> git: merge conflicts
    git --> rrm: merge conflicts
    rrm -> git: git fetch
    git -> gerrit: git fetch
    rrm -> git: hard reset on origin head branch
    rrm --> user: HTTP 412 Precondition Failed
end
rrm -> rrm: release lock
deactivate rrm
rrm --> user: ok
deactivate rrm

@enduml
----

== Обсяг робіт

=== Попередня декомпозиція
* [FE] Додати можливість створення/редагування форми/бізнес-процесу з мастер-версії
* [BE] Розширити API для роботи з формами та бізнес-процесами в мастер-версії
* [DEVOPS] Налаштувати пайплайн перевірки регламенту на роботу тільки з публічними змінами Gerrit (exclude Private
changes)
* [FE] Додати спрощений процес створення версії кандидату зі сторінки створення _сутності_
* [FE] Додати посилання на Jenkins для відстежування результату публікації регламенту в Адмін Порталі
* [FE] Додати обробку помилок з конфліктами з підказками по діям користувачу
* [BE] Реалізувати _BusinessProcessEtagInterceptor_ для перевірки etag при оновленні бізнес-процесу
* [BE] Додати перевірку на дублікат імен при створенні сутності на рівні _VersionedFileRepository_
* [BE] Додати перевірку по etag при оновленні сутності на рівні _VersionedFileRepository_
* [BE] Додати обробку merge conflicts при публікації змін в Gerrit
* [BE] Розширити HeadFileRepositoryImpl підтримкою запису файлів в репозиторій
* [BE] Розширити HeadFileRepositoryImpl підтримкою видалення файлів в репозиторій
* [FE] Додати можливість копіювання _сутності_ в мастер-версії
* [FE] Додати можливість видалення _сутності_ в мастер-версії
* [DEVOPS] Додати права сервіс акаунту RRM на виконання update by submit операції в Gerrit

=== Зміни в REST API

.Registry Regulation Management
[%collapsible]
====
swagger::{attachmentsdir}/architecture/registry/administrative/regulation-management/evolution/master-development/rrm-swagger.yml[]
====

=== Обмеження рішення
* При змінах, що конфліктують користувачу потрібно власноруч скопіювати контент, оновити сторінку та повторити збереження
з аналізом конфліктів
* Поточний дизайн не покриває фактичне видалення форм та бізнес-процесів в Form-management-provider та BPMS відповідно