:toc-title: On this page:
:toc: auto
:toclevels: 5
:experimental:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:


//= Підсистема управління міжсервісною взаємодією
= Cross-service communication management subsystem

NOTE: 🌐 This document is available in both English and Ukrainian. Use the language toggle in the top right corner to switch between versions.

//== Загальний опис
== General description

////
_Підсистема управління міжсервісною взаємодією_ реалізовуючи мережевий паттерн _Service Mesh_ допомагає розробникам та
адміністраторам реєстрів безпечно підключати зовнішні системи до Платформи реєстрів та навпаки, захищає та моніторить
компоненти Платформи та реєстрів, надає набір компонентів для керування зовнішнім/внутрішнім трафіком, мережевими
політиками, телеметрією та безпекою, забезпечує балансування навантаження, маршрутизацію трафіку та шифрування.
////

_Interservice interaction management subsystem_ implementing the _Service Mesh_ network pattern helps developers and
registry administrators securely connect external systems to the Registry Platform and vice versa, protects and monitors
components of the Platform and registries, provides a set of components for managing external/internal traffic, network
policies, telemetry and security, provides load balancing, traffic routing and encryption.

[TIP]
--
//Детальніше з переліком сервісів, що входять у _Service Mesh_ можна ознайомитись у розділі xref:arch:architecture/platform/operational/service-mesh/service-mesh-components.adoc[]
You can read more about the list of services included in _Service Mesh_ in the section xref:arch:architecture/platform/operational/service-mesh/service-mesh-components.adoc[]
--

//== Функції підсистеми
== Subsystem functions

////
* Підсистема надає механізми для захисту сервісів від атак та зловмисних дій, зокрема, автентифікацію, авторизацію,
шифрування та контроль доступу.
* Підсистема дозволяє контролювати, як трафік переходить між сервісами, зокрема, визначає маршрутизацію та балансування навантаження.
* Підсистема забезпечує збір та відображення різноманітних метрик, що дозволяє адміністраторам Платформи переглядати
та аналізувати роботу компонентів реєстрів та Платформи, зокрема, рівень доступності та продуктивності.
* Створення та керування політиками безпеки та обмеження доступу до компонентів Платформи та реєстрів.
////
* The subsystem provides mechanisms to protect services from attacks and malicious actions, in particular, authentication, authorization,
encryption and access control.
* The subsystem allows you to control how traffic passes between services, in particular, it determines routing and load balancing.
* The subsystem provides collection and display of various metrics, which allows Platform administrators to view
and to analyze the operation of components of the registers and the Platform, in particular, the level of availability and performance.
* Creating and managing security policies and restricting access to Platform components and registries.


//== Технічний дизайн підсистеми
== Subsystem technical design

image::architecture/platform/operational/service-mesh/service-mesh-subsystem.svg[width=600,float="center",align="center"]

//== Компоненти підсистеми
== Subsystem components

////
|===
|Назва компоненти|Namespace|Deployment|Походження|Репозиторій|Призначення

|Istio control plane
|`istio-system`
|`istiod`
|3rd-party
.4+|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/infrastructure/service-mesh[gerrit:/mdtu-ddm/infrastructure/service-mesh]
a|Istiod - це головний компонент підсистеми, який забезпечує основні функції service mesh, такі як маршрутизація трафіку,
керування трафіком та забезпечення безпеки. Istiod складається з декількох компонентів, а саме:

* Pilot - керує маршрутизацією трафіку та забезпечує балансування навантаження між сервісами.
* Citadel - відповідає за безпеку трафіку, шифрування, автентифікацію та авторизацію. Citadel створює та розповсюджує сертифікати для кожного сервісу в мережі.
* Galley - використовується для обробки та перевірки конфігураційних даних Istio Envoy.
* Sidecar Injector - автоматично додає Envoy контейнери до потрібних подів компонент Платформи та реєстрів.

|_Istio оператор_
|`istio-operator`
|`istio-operator`
|3rd-party
|Istio оператор дозволяє встановлювати, налаштовувати та керувати різними компонентами `istiod`. Це спрощує налаштування
та розгортання `istio` як компонента Платформи

|_Prometheus_
|`istio-system`
|`prometheus`
|3rd-party
|Prometheus - це компонент моніторингу та аналізу метрик продуктивності, що використовується разом з Istio для збору,
аналізу та візуалізації метрик компонентів Платформи та реєстрів.

|_Веб-інтерфейс управління та моніторингу Service Mesh_
|`istio-system`
|`kiali`
|3rd-party
|Компонент, що забезпечує адміністраторів Платформи та реєстрів можливістю налаштовувати та аналізувати стан
компонентів service-mesh Платформи та реєстрів, здійснювати моніторинг компонентів що входять в service-mesh в реальному
часі та швидко виявляти проблеми в мережі.

|_Kiali оператор_
|`istio-system`
|`kiali-operator`
|3rd-party
|Допоміжне програмне забезпечення, яке виконує функції розгортання, налаштування та відновлення Kiali, як
компонента підсистеми Платформи.
|===
////

|===
|Component name|Namespace|Deployment|Source|Repository|Appointment

|Istio control plane
|`istio-system`
|`istiod`
|3rd-party
.4+|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/infrastructure/service-mesh[gerrit:/mdtu-ddm/infrastructure/service-mesh]
a|Istiod - it is the main component of the subsystem that provides the main functions of the service mesh, such as traffic routing,
traffic management and security. Istiod consists of several components, namely:

* Pilot - manages traffic routing and provides load balancing between services.
* Citadel - responsible for traffic security, encryption, authentication and authorization. Citadel creates and distributes certificates for every service on the network.
* Galley - used to process and validate Istio Envoy configuration data.
* Sidecar Injector - automatically adds Envoy containers to the required pods of Platform components and registries.

|_Istio operator_
|`istio-operator`
|`istio-operator`
|3rd-party
|Istio operator allows you to install, configure, and manage various `istiod' components. This simplifies the setup
and deployment of `istio' as a component of the Platform

|_Prometheus_
|`istio-system`
|`prometheus`
|3rd-party
|Prometheus is a performance metrics monitoring and analysis component used with Istio to collect,
analysis and visualization of metrics of Platform components and registers.

|_Service Mesh management and monitoring web interface_
|`istio-system`
|`kiali`
|3rd-party
|A component that provides Platform administrators and registries with the ability to configure and analyze status
components of service-mesh Platforms and registries, monitor components included in service-mesh in real life
time and quickly detect problems in the network.

|_Kiali operator_
|`istio-system`
|`kiali-operator`
|3rd-party
|Utility software that performs Kiali deployment, configuration and recovery functions as
component of the Platform subsystem.
|===

//== Технологічний стек
== Technology stack

//При проектуванні та розробці підсистеми, були використані наступні технології:
During the design and development of the subsystem, the following technologies were used:

* xref:arch:architecture/platform-technologies.adoc#istio[Istio]
* xref:arch:architecture/platform-technologies.adoc#kiali[Kiali]
* xref:arch:architecture/platform-technologies.adoc#prometheus[Prometheus]
* xref:arch:architecture/platform-technologies.adoc#istio-operator[Istio Operator]
* xref:arch:architecture/platform-technologies.adoc#kiali-operator[Kiali Operator]

//== Атрибути якості підсистеми
== Subsystem quality attributes
////
=== _Observability_
Підсистема надає можливість спостерігати за Платформою та реєстрами та забезпечує збір метрик, що допомагає
адміністраторам розуміти поведінку та продуктивність компонентів Платформи та реєстрів для виявлення проблем та поліпшення їх продуктивності.

=== _Security_
Підсистема забезпечує захист компонентів Платформи та реєстрів від зовнішніх атак та внутрішніх загроз шляхом автентифікації,
авторизації, обмеження мережевої взаємодії, перевірки _JWT_-токенів, шифруванням трафіку між сервісами (_mTLS_) що повністю відповідає підходу Zero-trust.

Присутній механізм обмеження доступу до інтерфейсу який в свою чергу мінімізує поверхню атаки підсистеми ззовні. 

Підсистема відповідє вимогам криптостійкості використовуючі надійні шифри та TLS 1.2 або вище. Сертифікати згенеровані підсистемою зберігаються в безпечному, зашифрованому сховищі доступ до яких контролюється. 

Вся комунікація між компонентами підсистеми відбувається по захищеному каналу звязку з обовязковою ідентифікацією та автентифікацією.

=== _Reliability_
Підсистема забезпечує стійкість компонентів Платформи та реєстрів до відмов шляхом автоматичного перенаправлення
трафіку, виконання повторних спроб запитів,

=== _Performance_
Підсистема забезпечує балансування навантаження між компонентами Платформи та реєстрів та надає можливість використання
різних стратегій балансування, що дозволяє підвищити продуктивність додатків та керувати їх версіями.
////
=== Observability
The subsystem provides the ability to monitor the Platform and registries and provides the collection of helpful metrics for
administrators to understand the behavior and performance of Platform components and registries to identify issues and improve their performance.

=== Security
The subsystem provides protection of Platform components and registries against external attacks and internal threats through authentication,
authorization, restriction of network interaction, verification of _JWT_ tokens, encryption of traffic between services (_mTLS_), which fully corresponds to the Zero-trust approach.

There is a mechanism for limiting access to the interface, which in turn minimizes the attack surface of the subsystem from the outside.

The subsystem will meet the requirements of cryptoresistance using strong ciphers and TLS 1.2 or higher. Certificates generated by the subsystem are stored in a secure, encrypted storage, access to which is controlled.

All communication between subsystem components takes place over a secure communication channel with mandatory identification and authentication.

=== Reliability
The subsystem ensures the resistance of Platform components and registries to failures by means of automatic redirection
traffic, retries of requests

=== Performance
The subsystem provides load balancing between the components of the Platform and registries and provides the possibility of use
different balancing strategies, which allows you to increase the performance of applications and manage their versions.
