= S3 Ceph Object Storage політики
:note-caption:          ПРИМІТКА

Політика S3 Ceph Object Storage — це об’єкт, який дозволяє керувати доступом до певних ресурсів в S3 Ceph Object Storage.
Є можливість вказати дозволи для кожного ресурсу, щоб дозволити або заборонити дії, які вимагає користувач або роль.
Також є можливість захистити дані або заощадити кошти за допомогою політик життєвого циклу, щоб зробити дані конфіденційними або автоматично видаляти.

== Політики життєвого циклу файлів в Ceph Object Storage

Конфігурація життєвого циклу S3 – це JSON-файл, який складається з набору правил із попередньо визначеними діями, які S3 Ceph Object Storage має виконувати з об’єктами протягом їхнього життя. Політика має наступний вигляд:
[source,json]
----
{
  "Rules": [
    {
      "Expiration": {
        "Days": 30
      },
      "ID": "lifecycle-expiration-rule",
      "Status": "Enabled",
      "NoncurrentVersionExpiration": {
        "NoncurrentDays": 30
      },
      "AbortIncompleteMultipartUpload": {
        "DaysAfterInitiation": 30
      }
    }
  ]
}
----

Дана поліси зазначає що файли, які були створені 30 днів тому підлягають закінченню терміну дії та автоматичному видаленню.

NOTE: Поле Days повинно дорівнювати 1 або більше. Додаткова інформація може бути знайдена в документації Amazon S3: https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html

Щоб створити політику життєвого циклу в S3 Ceph Object Storage, потрібно завантажити її в потрібний бакет за допомогою AWS CLI:
[source,bash]
----
aws --profile <ПРОФІЛЬ_З_КЛЮЧАМИ_ДОСТУПУ> --endpoint=<АДРЕСА_S3_БАКЕТУ> s3api get-bucket-versioning --bucket <НАЗВА_БАКЕТУ>
----

Перевірити наявніть політики в S# Ceph Object Storage можна наступною командою:

[source,bash]
----
aws --profile <ПРОФІЛЬ_З_КЛЮЧАМИ_ДОСТУПУ> --endpoint=<АДРЕСА_S3_БАКЕТУ> s3api get-bucket-lifecycle-configuration --bucket <НАЗВА_БАКЕТУ>
----