:toc-title: On this page:
:toc: auto
:toclevels: 5
:experimental:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

//= S3 Ceph Object Storage політики
= S3 Ceph Object Storage policy

//Політика S3 Ceph Object Storage — це об’єкт, який дозволяє керувати доступом до певних ресурсів в S3 Ceph Object Storage.
//Є можливість вказати дозволи для кожного ресурсу, щоб дозволити або заборонити дії, які вимагає користувач або роль.
//Також є можливість захистити дані або заощадити кошти за допомогою політик життєвого циклу, щоб зробити дані конфіденційними або автоматично видаляти.
S3 Ceph Object Storage policy allows you to control access to resources in an S3 Ceph Object Storage. It enables specifying permissions for each resource to allow or deny actions requested by users or roles. Additionally, you can use lifecycle policies to protect data confidentiality or cut costs by automatically deleting expired objects.

//== Політики життєвого циклу файлів в Ceph Object Storage
== Lifecycle policies for files in a Ceph Object Storage

//Конфігурація життєвого циклу S3 – це JSON-файл, який складається з набору правил із попередньо визначеними діями, які S3 Ceph Object Storage має виконувати з об’єктами протягом їхнього життя. Політика має наступний вигляд:
The S3 lifecycle is configured via a JSON file that contains a set of rules with predefined actions that an S3 Ceph Object Storage should perform on objects during their lifecycle. The policy is defined in the following format:

[source,json]
----
{
  "Rules": [
    {
      "Expiration": {
        "Days": 30
      },
      "ID": "lifecycle-expiration-rule",
      "Status": "Enabled",
      "NoncurrentVersionExpiration": {
        "NoncurrentDays": 30
      },
      "AbortIncompleteMultipartUpload": {
        "DaysAfterInitiation": 30
      }
    }
  ]
}
----

//Дана поліси зазначає що файли, які були створені 30 днів тому підлягають закінченню терміну дії та автоматичному видаленню.
This policy states that files created 30 days ago are subject to expiration and automatic deletion.

//NOTE: Поле Days повинно дорівнювати 1 або більше. Додаткова інформація може бути знайдена в документації Amazon S3: https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html
NOTE: The *Days* field value cannot be less than 1. To learn more, refer to the AWS documentation: https://docs.aws.amazon.com/AmazonS3/latest/userguide/intro-lifecycle-rules.html[Lifecycle configuration elements].

//Щоб створити політику життєвого циклу в S3 Ceph Object Storage, потрібно завантажити її в потрібний бакет за допомогою AWS CLI:
To create a lifecycle policy in S3 Ceph Object Storage, you need to upload it to the corresponding bucket using the AWS CLI:

[source,bash]
----
aws --profile <profile-with-access-keys> --endpoint=<S3-bucket-address> s3api get-bucket-versioning --bucket <bucket-name>
----

//TODO: ua typo: S# -> S3
//Перевірити наявніть політики в S# Ceph Object Storage можна наступною командою:
To check whether the S3 Ceph Object Storage policy exists, use the following command:

[source,bash]
----
aws --profile <profile-with-access-keys> --endpoint=<S3-bucket-address> s3api get-bucket-lifecycle-configuration --bucket <bucket-name>
----