:toc-title: ЗМІСТ
//:toc: auto
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Налаштування глобальних змінних реєстру

Адміністратор регламенту може налаштовувати глобальні змінні для реєстру. Глобальні змінні є частиною регламенту та зберігаються у файлі *_global-vars/camunda-global-system-vars.yml_*.

Глобальні змінні можна використовувати для: ::

//- налаштування шляху до фабрики даних (`dataFactoryBaseUrl`);
* Налаштування поштової адреси служби підтримки (параметр `*supportEmail*`). Змінна `supportEmail` використовується на сторінках усіх критичних помилок у Кабінетах посадової особи та отримувача послуг.
* Налаштування теми інтерфейсу кабінетів посадової особи, отримувача послуг та адміністратора регламентів реєстру (параметр `*themeFile*`).

[WARNING]
====
Зараз доступні для налаштування лише параметри `*supportEmail*` та `*themeFile*`. Внесення будь-яких інших змінних у файл є забороненим. Крім того, не допускається додавання коментарів. Якщо ви хочете прибрати зайвий параметр, просто видаліть його.
====

Формат конфігурації змінних наступний: ::
+
----
<назва змінної>: <значення змінної>
----

Налаштувати поштову адресу служби підтримки можна так: ::
+
----
supportEmail: help@support.com
----

Налаштувати тему інтерфейсу кабінетів можна так: ::
+
----
themeFile: dark-theme.js
----
+
NOTE: За замовчуванням усі портали використовують світлу тему. Вкажіть цей параметр, якщо хочете застосувати темну.

Внесіть зміни до майстер-гілки Gerrit-репозиторію, та зачекайте, доки Jenkins-пайплайн `*Master-Build-registry-regulations*` застосує обрану конфігурацію до регламенту вашого реєстру.

[TIP]
====
Використовуйте зручний інтерфейс Кабінету адміністратора регламентів для управління глобальними налаштуваннями реєстру.

Детальніше -- на сторінці xref:registry-develop:registry-admin/admin-portal/registry-modeling/registry-global-settings.adoc[].
====