= Розгортання демо реєстру з прикладами як правильно моделювати бізнес-процеси
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

Надання можливості технічному адміністратору Платформи розгорнути демо реєстр з референтними прикладами по моделюванню
бізнес-процесів та створенню регламенту.

== Загальний опис

Для розгортання демо реєстру технічним адміністратором Платформи, йому потрібен наявний референтний приклад регламенту.

=== Ролі користувачів
* Технічний адміністратор Платформи

== Загальні принципи та положення
* Репозиторій з референтними прикладами `consent-data` присутній в Платформному сервісі інспекції та зберігання змін
конфігурації Gerrit
* В документації є розділ для адміністраторів Платформи з інструкціями щодо розгортання, підтримки та обслуговування
демо реєстру

== Дизайн рішення
=== Пакування репозиторію з референтними прикладами регламенту реєстру

Для цього на рівні збірки інсталера Платформи запаковується репозиторій `consent-data` як `gitsource` компонент в
control-plane-gerrit.

Consent-data має версіонуватись та оновлюватись разом з Платформою.

=== Написання докладної технічної інструкції по розгортанню демо реєстра та його регламенту

Інструкція має бути присутня в Анторі в окремому розділі з референсними прикладами та містити наступні розділи:

* Як розгорнути демо реєстр
* Як зміст репозиторію `consent-data` перенести до `registry-regulations` та які зміни потрібно зробити в ньому
(змінити посилання на Nexus тощо)
* Як оновити демо реєстр та його регламент після оновлення Платформи
* Як повернути демо реєстр в початковий стан, якщо щось пішло не так

=== Компоненти реєстру та їх призначення в рамках дизайну рішення
|===
|Компонент|Службова назва|Призначення / Суть змін
|Інсталятор Платформи|control-plane-installer|Оновлення стейджа PushControlPlaneLibrary
|Технічний репозиторій DevOps|devops-technical|Оновлення пайплайну для оновлення версій бібліотек
|Cервіс інспекції та зберігання змін конфігурації|control-plane-gerrit|Оновлення stageCR.json
|Технічна документація Платформи|ddm-architecture|Оновлення інструкцій технічного адміністратора Платформи

|===

== План розробки
=== Технічні експертизи
* DevOps

=== План розробки
* Запакувати `consent-data` в `control-plane-gerrit`
* Написати інструкцію для технічного адміністратора Платформи