@startuml
skinparam responseMessageBelowArrow true

participant "Web клієнт" as client order 1
participant "Модуль роботи\nз версіями" as versionModule order 2
participant "Модуль роботи\nз Gerrit" as gerritModule order 3

title Відхилення версії-кандидату

client-> versionModule: відхилити версію-кандидат
activate versionModule
  versionModule -> gerritModule: надіслати запит на decline\nchange request за ідентифікатором
  activate gerritModule
    alt версії-кандидата не існує
      versionModule <-- gerritModule: помилка операції decline\nчерез те що не існує такого\nchange request
      client <-- versionModule: помилка зі статусом\n404 Not Found
    end
  versionModule <-- gerritModule
  deactivate gerritModule

  client <-- versionModule: відповідь зі статусом\n204 No Content
deactivate versionModule
@enduml