@startuml
skinparam responseMessageBelowArrow true

participant "Web клієнт" as client order 1
participant "Модуль роботи\nз версіями" as versionModule order 2
participant "Модуль роботи\nз Gerrit" as gerritModule order 3

title Отримання інформації про майстер-версію регламенту

client-> versionModule: запит на отримання інформації\nпро майстер-версію регламенту
activate versionModule
  versionModule -> gerritModule: отримати інформацію про\nостанній застосований\nchange request
  activate gerritModule
    versionModule <-- gerritModule: інформація про останній\nchange request
  deactivate gerritModule

  client <-- versionModule: інформація про майстер-версію
deactivate versionModule
@enduml