@startsalt
{
{T
+<&folder> docs
++<&folder> modules
+++<&folder> registry-regulation-management
++++<&folder> pages
+++++<&folder> rest-api-includes
++++++<&file> intro.adoc

+++++<&folder> versions
++++++<&folder> candidates
+++++++<&folder> <versionCandidateId>
++++++++<&folder> POST
+++++++++<&file> spec.adoc

+++++++<&folder> GET
++++++++<&file> spec.adoc

+++++<&folder> rest-api-generated
++++++ ...

+<&folder> target
++<&folder> generated-snippets
+++++<&folder> versions
++++++<&folder> candidates
+++++++<&folder> <versionCandidateId>
++++++++<&folder> POST
+++++++++<&file> http-request.adoc
+++++++++<&file> http-response.adoc

++++++++<&folder> GET
+++++++++<&file> http-request.adoc
+++++++++<&file> http-response.adoc

+++++++<&folder> GET
++++++++<&file> http-request.adoc
++++++++<&file> http-response.adoc

}
}
@endsalt