@startsalt
{
{T
+<&folder> docs
++<&folder> modules
+++<&folder> registry-regulation-management
++++<&folder> pages
+++++<&folder> rest-api-includes
++++++ ...
+++++<&folder> rest-api-generated
++++++ ...

+<&folder> target
++<&folder> <b>generated-snippets</b>
+++++<&folder> versions
++++++<&folder> candidates
+++++++<&folder> <versionCandidateId>
++++++++<&folder> POST
+++++++++<&file> http-request.adoc
+++++++++<&file> http-response.adoc

++++++++<&folder> GET
+++++++++<&file> http-request.adoc
+++++++++<&file> http-response.adoc

+++++++<&folder> GET
++++++++<&file> http-request.adoc
++++++++<&file> http-response.adoc

}
}
@endsalt