= Тестування атрибутів якості

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

Розділ _Тестування атрибутів якості_ надає всеосяжний опис різних підходів до тестування, необхідних для забезпечення найвищої якості Платформи.
Цей розділ включає три основні секції, кожна з яких присвячена конкретному типу тестування:

Функціональне тестування::
Фокусується на перевірці функцій Платформи для забезпечення їхньої правильної роботи. Основна мета функціонального тестування -- переконатися, що програмне забезпечення функціонує згідно зі встановленими специфікаціями та очікуваннями користувачів.
Це сприяє виявленню невідповідностей та дефектів у поведінці системи, гарантуючи, що вона надає очікувану користь.

Тестування продуктивності::
Аналізує продуктивність, надійність та можливість масштабування Платформи під час різних режимів навантаження.
Цей процес включає виявлення "вузьких місць" та інших проблем, які необхідно розв'язати для оптимізації користувацького досвіду, а також для забезпечення здатності Платформи та реєстрів ефективно обробляти очікуваний обсяг користувачів та транзакцій.

Тестування безпеки::
Тестування безпеки має вирішальне значення для виявлення вразливостей та потенційних загроз всередині Платформи.
Це включає тестування здатності системи захищати дані, витримувати атаки,
та забезпечувати конфіденційність, цілісність та доступність Платформи тощо.

== Огляд секції

* xref:testing:functional-testing/functional-testing.adoc[Функціональне тестування]
* xref:testing:performance-testing/performance-testing.adoc[Тестування продуктивності]
** xref:testing:performance-testing/perf-report/perf-report-overview.adoc[]
*** xref:testing:performance-testing/perf-report/1-9-2/perf-test-1-9-2.adoc[]
*** xref:testing:performance-testing/perf-report/1-9-3/perf-test-1-9-3.adoc[]
*** xref:testing:performance-testing/perf-report/1-9-4/perf-test-1-9-4.adoc[]
*** xref:testing:performance-testing/perf-report/1-9-5/perf-test-1-9-5.adoc[]
* xref:testing:security-testing/security-testing.adoc[Тестування безпеки]