= Portability
include::ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== Overview

_The quality attribute defines the extent of system independence from the type of infrastructure it can be deployed on._

The _Registry Platform_ architecture includes the capabilities for deployment in private or public cloud environments, or custom local infrastructure.

The installation procedure is managed by the xref:architecture/platform-installer/overview.adoc[Component for managing the state of Platform resources], which is designed with different infrastructure providers compatibility.

The current version of the _Registry Platform_ support deployment in public and private cloud environments:

* https://aws.amazon.com/[Amazon Web Services (AWS)]
* https://azure.microsoft.com/[Microsoft Azure (Azure)]
* https://cloud.google.com/[Google Cloud Platform (GCP)]
* https://www.vmware.com/products/vsphere.html[VMWare vSphere]

[TIP]
--
Find more information on installing the _Registry Platform_ in the corresponding sections:

* xref:admin:installation/platform-deployment/platform-deployment-overview.adoc[]

Find more details on relevant subsystems and component technical design in the following chapters:

* xref:architecture/platform-installer/overview.adoc[Component for managing the state of Platform resources]
* xref:architecture/container-platform/container-platform.adoc#_portability[Container orchestration platform]
--