= Verifiability
include::ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== Overview

_The quality attribute defines the complexity level of system testing and debugging when applying changes._

The _Registry Platform_ provides a wide range of capabilities for quality control and provision in the process of Registry development:

* Checking Registry regulations for errors when applying changes
* Automated testing using functional _BDD_-tests when applying changes
* Configuring external integrations simulation to test Registry in isolated environment

[TIP]
--
Find more details on relevant subsystems and component technical design in the following chapters:

* xref:arch:architecture/registry/administrative/regulation-management/registry-regulation/registry-regulation.adoc[]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[]
* xref:arch:architecture/registry/operational/ext-systems-simulation/overview.adoc[]
--