= Security
include::ROOT:partial$templates/document-attributes/default-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== Overview

//_Атрибут якості визначає здатність системи захищати дані та інформацію від несанкціонованого доступу, забезпечуючи при цьому доступ авторизованим користувачам і системам._
_The quality attribute defines the capability of a system to protect data and information from unauthorized access, providing access to authorized users and systems at the same time._

//Архітектура безпеки _Платформи Реєстрів_ відповідає за три загальноприйняті характеристики:
The _Registry Platform_ security architecture is responsible for three general characteristics:


////
* _Конфіденційність_ – властивість захисту даних або сервісів від несанкціонованого доступу.
* _Цілісність_ – властивість того, що дані або послуги не піддаються несанкціонованим маніпуляціям.
* _Доступність_ - властивість, що система буде доступна для цільового використання.
////
* _Confidentiality_ – protection of data and resources from unauthorized access.
* _Integrity_ – avoidance of unauthorized tampering with data or services.
* _Availability_ - availability of the system for intended use.

[TIP]
--
//Детальніше можна ознайомитись у відповідних розділах:
Find more details in the corresponding sections:

* xref:arch:architecture/security/overview.adoc[]
* xref:testing:security-testing/security-testing.adoc[]
--