= Availability
include::ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== Overview

_The quality attribute defines the percentage of time the system is available and ready to process requests._

The _Registry Platform_ supports highly available deployment for central Platform components and Registry components.

High availability is achieved by using:

* _Active redundancy_ for critical components
* _Affinity_ and _anti-affinity_ application distribution policies on cluster VMs
* Automated load balancing to back up application instances
* _Rolling_-approach to update deployments with minimal disruption for users

[NOTE]
--
The described values are calculated for the _Registry Platform_ deployment on two datacenters of availability zones, depending on the selected infrastructure.
--

[TIP]
--
Find more details on relevant subsystems and component technical design in the following chapters:

* xref:arch:architecture/container-platform/container-platform.adoc[Container orchestration platform]
* xref:arch:architecture/registry/operational/messaging/overview.adoc[Asynchronous messaging subsystem]
* xref:arch:architecture/registry/operational/relational-data-storage/overview.adoc[y]
* xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc[Non-relational database management subsystem]
--

== Target metrics

When defining target values for the aforementioned metrics, the classification of Registries, and operational conditions are taken into account.

[NOTE]
--
To achieve these values, the Platform must be deployed on more than one datacenter.
--

.Registry target availability values
|===
.2+|Metric .2+|Registry class 4+^|Target value
|_Production hours_|_Peak hours_|_Evening hours_|_Shadow hours_

.3+|_Availability_ |_Strategic_|`99.9%`|`99.9%`|`99.9%`|`95%`
|_Tactical_|`99.9%`|`99.9%`|`99.9%`|`95%`
|_Operative_|`99%`|`99%`|`99%`|`90%`
|===