= Класи ІТ-систем, які можна побудувати на Платформі реєстрів
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Що таке платформа реєстрів?

_Платформа реєстрів_ -- це гнучкий, безпечний цифровий low-code бекенд для побудови різних типів ІТ-систем. Розгляньмо детально.

* _Гнучкість_: Платформа реєстрів є хмарно-агностичною, тобто вона може ефективно функціонувати на різних хмарних сервісах, не залежачи від певного середовища.
* _Безпека_: Як один з інструментів цифрової трансформації державних послуг в Україні, Платформа побудована з урахуванням безпеки.
* _Low-code_: Використання Платформи не вимагає залучення великих команд або експертів високого рівня. Адміністрування системи може здійснюватися з мінімальним програмуванням, а кінцевим користувачам потрібні лише базові комп'ютерні навички.
* _Цифровий бекенд_: У стандартній конфігурації Платформа забезпечує інфраструктуру та компоненти, які необхідні для побудови ІТ-системи відповідно до потреб вашого бізнесу.
* _ІТ-системи_: Платформа дозволяє розмістити різні класи ІТ-систем з широким спектром функціональних можливостей у різних галузях та застосуваннях.

[NOTE,caption=GDPR-readiness]
Платформа розроблена з урахуванням вимог _Закону про захист персональних даних_, і, відповідно, з урахуванням до GDPR, з метою відповідності основним принципам та вимогам регулювання конфіденційності даних. Щоб дізнатися більше про наші стандарти та відповідність (включаючи право бути забутим), зверніться до сторінки https://epam.github.io/edp-ddm-architecture/en/platform/1.9.6/arch/architecture/security/standards-and-compliance.html[*Standards and compliance*].

== Які ІТ-системи можна побудувати на Платформі?

Платформа може бути адаптована для розміщення широкого спектра ІТ-систем. Ось лише деякі з можливостей, які вже були реалізовані на практиці.

=== За призначенням 

* _Реєстр_. Реєстр підтримує й управляє цифровими записами, пов'язаними з громадянами, підприємствами, організаціями або іншими організаціями. Ця інформація може включати дані про фізичних осіб, ліцензії, дозволи, майно, компанії та багато іншого. Реєстри можуть бути використані для забезпечення точності даних, полегшення надання ефективних цифрових послуг та забезпечення безперебійного обміну інформацією між різними агентствами та департаментами.
* _Система звітності_. Система звітності використовується для збору, аналізу та формування звітів на основі даних та інформації, пов'язаної з операціями, послугами та продуктивністю. Системи звітності допомагають приймати рішення, орієнтовані на дані, підвищують прозорість та забезпечують підзвітність громадськості та зацікавленим сторонам.
* _Каталог_. Каталог -- це цифрова база даних, яка містить структуровану інформацію про різні суб'єкти, посадових осіб, департаменти, агентства, служби та ресурси. Ці каталоги служать централізованим і легкодоступним джерелом інформації для громадян, підприємств та інших зацікавлених сторін. Каталоги призначені для полегшення ефективної навігації та пошуку відповідної інформації, покращення доступу громадськості та прозорості.
* _Система управління скаргами_. Система управління скаргами використовується підприємствами, державними установами або організаціями для ефективного отримання, обробки та реагування на скарги та відгуки замовників, клієнтів або зацікавлених сторін. Вона забезпечує структурований підхід до розгляду та вирішення скарг, забезпечуючи своєчасне та ефективне відстеження кожної скарги.

=== За галузями 

Ось кілька прикладів того, як Платформа реалізується в різних галузях промисловості України.

* *Медицина*. _Реєстр медичних виробів_ є одним з найважливіших реєстрів охорони здоров'я, що містить понад 450 000 медичних виробів, дозволених до розповсюдження в Україні. Кожен запис містить детальну інформацію про продукт, таку як виробник, відповідальні особи та відповідні декларації.
* *Освіта*. _Реєстр учнів і шкіл_ є одним з найбільших реєстрів, розроблених Міністерством освіти і науки. Він допомагає аналізувати та планувати розвиток шкільної освіти, а також впроваджувати цифрову систему оцінювання.
* *Видавнича справа*. _Реєстр видавців_ надає громадськості відкриті дані про існуючих видавців і дозволяє подати заявку в Інтернеті на отримання дозволу на публікацію. Він забезпечує обробку перевірки поданих даних і навіть зменшення помилок під час реєстрації.
* *Сільське господарство*. _Реєстр суб'єктів племінної справи у тваринництві_ служить єдиним джерелом про породи тварин, які мають родовідну цінність. Реєстр може використовуватися як базовий довідник порід тварин у різних системах у сфері тваринництва. Основна мета - підтримання єдиної номенклатури та актуальної інформації.
* *ЗМІ*. _Реєстр суб'єктів у сфері медіа._ покликаний посилити процес реєстрації та отримання дозволів у сфері засобів масової інформації. Система може бути використана для отримання дозволів та реєстрації онлайн за допомогою автоматизованого процесу перевірки. Крім того, він підтримує проведення конкурсів на отримання дозволів, що робить весь процес більш прозорим і зручним.

Ці приклади є лише малою частиною того, чого можна досягти за допомогою Платформи. Кожна реалізація залежить від індивідуального формулювання завдання.

== Які ІТ-системи не можна будувати на Платформі? 

Ми не рекомендуємо використовувати можливості Платформи для наступних цілей:

* _Веброзробка_. Платформа працює через декілька вебінтерфейсів, але _НЕ_ має розглядатися як інструмент для створення вебсайтів.
* _Інструмент аналітики_. Платформа підтримує створення обмеженої частини аналітичних звітів та інформаційні панелі, але вони призначені для внутрішнього моніторингу і не слугують як основна функціональність. Однак Платформа може бути інтегрована з будь-якою іншою аналітичною системою.
* _Біржовий або торговий майданчик_. Функціональність Платформи _НЕ_ орієнтована на онлайн-торгівлю.