:sectanchors:
:sectlinks:
:note-caption: Примітка
= Командам розробки та супроводу реєстрів

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

Ефективна розробка та підтримка реєстрів залежать від добре організованих команд та спеціалізованих ролей. У цьому розділі ви дізнаєтеся про наступне:

* [*] *_Адміністратори реєстру_*: відповідальні за координацію, моніторинг та забезпечення стабільної роботи реєстру.

* [*] *_Моделювальники даних_*: Експерти, які створюють та оптимізують структури даних у реєстрі.

* [*] *_Моделювальники бізнес-процесів_*: Ключові спеціалісти, які ведуть розробку, моделювання та вдосконалюють робочі процеси реєстру.

* [*] *_Навчання_*: Обрані ресурси та матеріали для підвищення кваліфікації адміністраторів та розробників реєстру.

* [*] *_Найкращі практики_*: Перевірені часом методології та стратегії, засновані на галузевому досвіді, для забезпечення якісної розробки та підтримки реєстрів.

* [*] *_Аудит регламенту реєстру_*: Розділ містить перелік рекомендацій, які дозволяють оцінити якість регламенту реєстру та виявити можливі проблеми,
які можуть виникнути при його використанні. Рекомендації згруповані відповідно до структури
xref:arch:architecture/registry/administrative/regulation-management/registry-regulation/registry-regulation.adoc[Цифрового
 регламенту реєстру]. Перед впровадженням регламенту в промислову експлуатацію рекомендується провести повний аудит регламенту реєстру.

* [*] Додатково рекомендуємо ознайомитися із _класами IT-систем, які можна побудувати_ на Платформі реєстрів.

Запрошуємо докладно вивчити кожний підрозділ, де розкриваються всі аспекти роботи з реєстрами.

== Огляд секції

* xref:registry-admin/index.adoc[]
* xref:data-modeling/index.adoc[]
* xref:bp-modeling/index.adoc[]
* xref:registry-admin-study/registry-admin-study.adoc[]
* xref:study-project/index.adoc[]
* xref:best-practices/best-practices-overview.adoc[]
* xref:registry-audit-instruction/registry-audit-instruction.adoc[]
* xref:registry-develop:it-system-classes.adoc[Класи IT-систем, які можна побудувати на Платформі реєстрів]