= Гіс модуль

== Загальні вимоги

* Відображення мап, супутникових знімків які підтримуються сторонніми системами в порталі посадових осіб або громадян, з можливісттю їх перемикання між собою та зміни масштабу.

* Відображення об`єктів реєстру які мають прив`язку до місцевості на мапі (слої).

* Включення декількох слоїв на мапі.

* Пошук об`єктів реєстру на мапі за атрибутами.

* Можливість вибору координати точки, внесення ліній або полігонів шляхом нанесення їх на карту в бізнес процесі.

* Гео-кодування - пошук координати на мапі за публічною адресою або назвою об`єкту

* Зворотне гео-кодування - пошук адреси або назви об`єкту за координатами

== Структура рішення

image::datafactory/gis-context.svg[]


== Компоненти

=== Компонент Form.io (LeafletJs)
В основі компонента Form.io лежить бібліотека LeafletJs в якій інтегруються всі аспекти гео-модуля.

=== GeoServer
*GeoJSON* - формат даних який може бути інтерпретований Лефлует і відобаржений на карті +
*Feature* - інформація про обєкт точку +
*Layer* - растровий або векторний набір даних представлений

Сервер з відкритим кодом який дозволяє отримувати данні з БД у вигляді GeoJSON.

=== GeoServer Publisher
Застосунок командного рядка який здійснює автоматичну конфігурацію GeoServer-а, шляхом виконання викликів до адміністративного API GeoServer-а

=== Nominatim

[NOTE]
Робота запланована на реліз 1.8

== Розгортання

image:datafactory/gis-deployment.svg[]

Гіс модуль є частиною окремого шаблону реєстру. У випадку розгортання реєстру з такого шаблону буде додатково встановлено GeoServer та Nominatim. +
Конфігурація GeoServer та публікація слоїв відбувається під час розгортання регламенту.

== Конфігурація

Конфігурація гео-модуля полягає в створенні підключення до БД та публікації структур які містять тип геометрія як слої в GeoServer-і. Конфігурація відбувається на єтапі розгортання регламенту на кроці `publish-geoserver-configuration` основного pipeline `registry-regulations`
