= Модуль ГІС

== Загальні вимоги

* Відображення мап, супутникових знімків які підтримуються сторонніми системами в порталі посадових осіб або громадян, з можливістю їх перемикання між собою та зміни масштабу.

* Відображення об'єктів реєстру які мають прив'язку до місцевості на мапі -- шари (layers).

* Включення декількох шарів на мапі.

* Пошук об'єктів реєстру на мапі за атрибутами.

* Можливість вибору координати точки, внесення ліній або полігонів шляхом нанесення їх на карту в бізнес-процесі.

* Геокодування -- пошук координати на мапі за публічною адресою або назвою об'єкта.

* Зворотне геокодування -- пошук адреси або назви об`єкту за координатами

== Структура рішення

image::datafactory/gis-context.svg[]


== Компоненти

=== Компонент Form.io (LeafletJs)
В основі компонента Form.io лежить бібліотека `LeafletJs`, в якій інтегруються всі аспекти геомодуля.

=== GeoServer

Сервер з відкритим кодом, який дозволяє отримувати дані з БД у вигляді GeoJSON.

* *GeoJSON* -- формат даних, який може бути інтерпретований LeafletJS і відображений на карті +
* *Feature* -- інформація про об'єкт точку +
* *Layer* -- растровий або векторний набір даних, представлений набором географічних об'єктів.

=== GeoServer Publisher
Застосунок командного рядка який здійснює автоматичну конфігурацію GeoServer-а, шляхом виконання викликів до адміністративного API `GeoServer`-а.

=== Nominatim

[NOTE]
Робота запланована на реліз 1.8

== Розгортання

image:datafactory/gis-deployment.svg[]

Гіс модуль є частиною окремого шаблону реєстру. У випадку розгортання реєстру з такого шаблону буде додатково встановлено GeoServer та Nominatim. +
Конфігурація GeoServer та публікація шарів відбувається під час розгортання регламенту.

== Конфігурація

Конфігурація геомодуля полягає в створенні підключення до БД та публікації структур, які містять тип "геометрія" (`geometry`) як шари у `GeoServer`-і. Конфігурація відбувається на етапі розгортання регламенту на кроці `publish-geoserver-configuration` основного pipeline `registry-regulations`.
