= Налаштування Кабінету отримувача послуг реєстру

Налаштування Кабінету отримувача послуг реєстру є частиною Платформи і розгортаються незалежно від регламенту.

image::datafactory/settings.drawio.svg[]

== Перелік налаштувань
|===
|Назва параметра |Опис

|email
|електронна пошта отримувача послуг (обов'язкове поле)

|phone
|телефон людини (по замовчуванню: null)

|communicationIsAllowed
|дозвіл на використання контактних даних для сповіщень  (по замовчуванню: false)

|===

== Сервіс для доступу до налаштувань

=== Структура сервіса

Сервіс складається з двох частин settings API та settings. +

*Settings API* - надає REST інтерфейс для операцій з налаштуваннями +
*Settings* - сервіс для роботи з БД.

=== Операції з налаштуваннями
Всі операції вимагають аутентифікацію. Отримання налаштувань можливе лише для поточного користувача.
Ключем для пошуку є keycloak_id який передається в JWT токені.

=== Отримання всіх налаштувань
У разі відсутності налаштувань для користувача повертаються налаштування по замовчуванню.

*GET /settings*

Приклад відповіді:
[source, json]
----
{
  "settings_id":  "uuid",
  "e-mail": "test@test.com",
  "phone": "+380441111111",
  "communicationIsAllowed": true
}
----

=== Зміна налаштувань
Данний метод підтримує створення налаштувань у разі їх відсутності.

.Приклад запита

*PUT /settings*
[source, json]
----
{
  "e-mail": "test@test.com",
  "phone": "+380444444444",
  "communicationIsAllowed": true
}
----

.Приклад відповіді:

HTTP-код та ідентифікатор створених налаштувань:
[source, json]
----
{
  "settings_id": "uuid"
}
----

== Модель бази даних

[NOTE]
У випадку необхідності введення статусу/ролі користувача таблиця "subject_settings" може бути розширена відповідними полями.

[plantuml]
----
@startuml
skinparam monochrome true
left to right direction

namespace registry {
object "Subject" as s  {
  id: uuid
  ...
}

object "subject_settings" as sp {
  id: uuid
  subject_id: uuid
  settings_id: uuid
}
}

namespace platform {

object "Settings" as settings  {
  id: uuid
  keycloak_id: uuid
  email: text
  phone: text
  communicationIsAllowed: boolean
}

}

s ||--|| sp
sp ||---|| settings

@enduml
----

== Бізнес-процеси Кабінету отримувача послуг

[plantuml, test, svg]
----
@startuml
skinparam monochrome true

actor "Людина\nПредставник Юр.особи\nФОП" as person
participant "Kaбінет людини" as ui
participant KeyCloack as security

participant "Low code" as low

participant "Точки інтеграції\n регламенту" as reg
participant "Сервіс\n налаштувань" as settings


== Перший логін ==
person -> ui: логін з КЕП
ui -> security: аутентифікація
security -> security: перевірка КЕП
security --> ui: ok 
ui --> person: кабінет

== Створення налаштуавнь \ закінчення реєстрації ==
person -> ui: Закінчити реєстрацію
ui -> low: старт БП
low -> reg: пошук/створення суб'єкта
return id
low -> settings: створення налаштувань \n
return id
low -> reg: зв'язка налаштувань та суб'єкта
return
low -> security: зміна ролі
return ok
low --> ui: ok
ui --> person: все ок
== Зміна налаштувань профіля == 
person -> ui: нові налаштування
ui -> settings: нові налаштування + jwt
settings -> settings: зміна налаштувань
settings --> ui: ok
ui --> person: все ок
@enduml
----


