== Розмежування прав доступу на рівні ролей
=== Вступ
Lowcode платформа повинна запобігати неавторизований доступ до системи в процесі використання кабінетів людини
та чиновників. Окрім цього адміністратор регламенту повинен мати можливість налаштування прав доступу
на рівні бізнес-процесів та створення ролей для регламенту.

=== Ролі
image::lowcode/auth-roles-deployment.svg[]

==== Типи ролей
Доступ до функціоналу платформи для чиновників та людин надається виключно через Kong Api Gateway.
Кожен запит повинен бути зазделегіть автентіфікован у Keycloak. В залежності від контексту запиту
автетификація виконується у реалмі officer чи citizen. Також обліковий запис користувача має одну чи
декілька ролей.

Ролі розподіляються на 3 групи:

- Системні - *officer* для реалму чиновників та *citizen* для реалму людин. Ці ролі створюються в процесі
розгортання платформи та надаються за замовчуванням користувачам відповідного реалму.
Їх видалення може привести до неконсистентного стану системи.
- Системні ролі суб'єкта - ролі, які відображають категорію громадянина.
(*individual*, *entrepreneur*, *legal*, *unregistred_individual*, *unregistred_entrepreneur*, *unregistred_legal*).
На відміну від системних ролей *officer* та *citizen* не викорістовуються для обмеження доступу на рівні
API. Потрібні для онбордінга людини в системі та розмежування послуг за категорією на рівні регламенту.
Детальніше про категорії громадян можна дізнатися за xref::lowcode/citizen-authentication.adoc[посиланням]
- Регламентні - ролі, які є частиною регламенту та створються в процесі публікації змін до регламенту.

Наявність системних ролей відповідає за доступ до системи в цілому. Тобто, сервіс управління задачами
користувача та сервіс управління бізнес-процесами користвача надає доступ до ресурсів тільни за наявності
ролі officer чи citizen.

Регламентні ролі використовуються для надання доступу до окремих бізнес-процесів. Розмежування прав
доступу до бізнес-процесів є також частиною регламенту.

==== Мапінг ролей

Модель авторизації Camunda engine використовує групи для налаштування спільних правил доступу до ресурсів.
В процесі запиту на сервіс виконання бізнес-процесів виконується мапінг ролей, що є в токені на групи
в Camunda. Тобто якщо користувач має роль officer-first-rank, яка була надана йому у Keycloak, то при
виконанні запиту він отримує права доступу, що належать групі officer-first-rank у Camunda engine.


==== Діаграма послідовності процесу авторизації

[plantuml]
----
include::partial$lowcode/auth-flow.puml[]
----

=== Запуск бізнес-процесу

image::lowcode/auth-camunda-group-auth.svg[]

Для того, щоб користувач системи мав право на запуск бізнес-процесу потрібно виконання наступних правил:

- Користувач має налаштовану роль у Keycloak, яка має відповідну групу у Camunda
- Група в Camunda має налаштовані авторизаційні правила для відповідного бізнес-процесу
(Process definition authorization). Приклад:

[frame="none"]
|===
|Type| Group | Permissions | Resource Id

| Allow
| officer-first-rank
| READ, CREATE_INSTANCE
| add-lab
|===

- Групи в Camunda має налаштовані авторизаційні правила для створення нових екземплярів бізнес-процесів
(Process instance authorization). Приклад:

[frame="none"]
|===
|Type| Group | Permissions | Resource Id

| Allow
| officer-first-rank
| CREATE
| *
|===

=== Корисні посилання

https://docs.camunda.org/manual/latest/webapps/admin/authorization-management/#grant-permission-to-start-processes-from-tasklist[Camunda Start Process Permission]

