== Процес онбордингу громадян та управління ролями представників суб'єктів

Процес реєстрації нових користувачів у кабінеті громадян складається з двох етапів:

- Автентифікація з використанням особистого ключа КЕП з послідуючим створенням запису у окремому Keycloak Realm
- Проходження бізнес-процесу онбордингу у особистому кабінеті громадянина після успішної автентифікації

=== Системні ролі для автентифікованих та зареєстрованих користувачів

Задля відокремлення бізнес-процесів, які доступні користувачам, які не пройшли процедуру онбордингу від тих, хто її успішно завершив, платформа надає окремі системні ролі для контроля доступу до бізнес-процесів, які поділяються на дві логічні групи.

*Користувачі, які пройшли автентифікацію та мають запис в Keycloak Realm громадян:*

- *UNREGISTERED_INDIVIDUAL* (фізична особа)
- *UNREGISTERED_ENTREPRENEUR* (ФОП або представник)
- *UNREGISTERED_LEGAL* (представник юридичної особи)

*Користувачі, які пройшли автентифікацію, мають запис в Keycloak Realm громадян та завершили бізнес-процес онбордингу у кабінеті:*

- *INDIVIDUAL* (фізична особа)
- *ENTREPRENEUR* (ФОП або представник)
- *LEGAL* (представник юридичної особи)

=== Процес онбордингу / реєстрації громадян

Типовий бізнес-процес онбордингу для всіх типів суб'єктів (зображений на діаграмі) є орієнтованим на створення всіх необхідних записів у БД для взаємодії користувача з реєстром та включає наступні етапи:

- Перевірка наявності та створення (у разі відсутності) суб'єкта на базі інформації в наявності у записі користувача в Keycloak
- Створення профіля користувача для встановлення зв'язку з цільовим суб'єктом
- Створення налаштувань користувача на базі інформації, отриманої у процесі виконання бізнес-процесу
- Заміщення #UNREGISTERED_# ролі користувача у Keycloak на роль, яка визначає наступні послуги, які стають доступні для виконання через кабінет громадянина

image::lowcode/citizen-onboarding.svg[]

[WARNING]
Після завершення бізнес-процесу онбордингу, користувачу необхідно переавтентифікуватись задля того, щоб зміна ролі набула чинності.

=== Управління ролями на рівні суб'єкта

Для реалізації управління доступними операціями по відношенню до об'єктів, які належать цільовому  суб'єкту, система надає можливість визначати набір додаткових ролей на рівні регламенту та їх доступ до бізнес-процесів.

Для представників юридичних осіб, першочерговим є визначення директора юридичної особи через виконання окремого бізнес-процесу з підтвердженням з боку чиновника, який обслуговує цільовий реєстр. У результаті виконання БП, користувач, який його ініціюваав, отримує додаткову регламентну роль *ДИРЕКТОР*, яка надає доступ до до бізнес-процесів, змодельованих на рівні регламенту:

- управління суб'єктом
- наданням ролей користувачам, асоційованим з суб'єктом (представникам ФОП / юридичної особи)
- деактивація представників
- тощо.



