= Робота з цифровими документами у кабінеті користувача

== Функціональні можливості

Для забезпечення вимог по роботі з цифровими документами через кабінет користувача, платформа надає наступні можливості:

- Моделювання UI-форм задач бізнес-процесів з використанням полів типу "_File_" через адміністративний інтерфейс
- Завантаження цифрових документів через UI-форми задач
- Вивантаження цифрових документів через UI-форми задач
- Налаштування обмежень на завантаження файлів цифрових документів

== Базові принципи реалізації

- Файли цифрових документів, завантажені через UI-форми задач, підлягають збереженню в об'єктному сховищі _Ceph_ до моменту закінчення бізнес-процесу
- Для усіх файлів цифрових документів, завантажених через UI-форми задач, генерується _SHA256_-геш та зберігається у вигляді атрибуту Ceph-документа для подальшого використання при накладанні підпису
- Файли цифрових документів, завантажені через UI-форми задач, та дані форми зберігаються у вигляді окремих Ceph-документів в різних бакетах (_lowcode-file-storage_ та _lowcode-form-data-storage_)
- Для забезпечення цілістності даних, отриманих від користувача та завантажених ним файлів цифрових документів через UI-форму, Ceph-документ даних форми включає в себе UUID-ідентифікатори Ceph-документів файлів та згенеровані з них _SHA256_-геші
- Файли цифрових документів не є об'єктом виконання операцій на рівні бізнес-процесів на відміну від їх UUID-ідентифікаторів
- При накладанні підпису приватним ключем користувача на дані форми з завантаженими файлами цифрових документів, підпис генерується на документ даних UI-форми, який містить UUID-ідентифікатори Ceph-документів та _SHA256_-геші файлів
- Обмін цифровими документами між підсистемами платформи "_Low-code_" та "_Дата Фабрика_" реалізується за рахунок обміну UUID-ідентифікаторами та їх Ceph-документами через окремий Ceph-бакет "_lowcode-file-storage_"
- Бакет "_low-code-file-storage_" призначений для тимчасового зберігання цифрових документів у процесі виконання бізнес-процесів. Для перманентного зберігання використовується окремий бакет "_Дата Фабрики_" - "_registry-file-storage_"

== Взаємодія компонентів системи

На даній діаграмі зображено задіяні для реалізації вимог сервіси платформи та взаємодію між ними. Додатково зображено важливі особливості, які необхідно прийняти до уваги в рамках реалізації та моделювання.

image::lowcode/file-management.svg[]

=== Сервіс цифрових документів
За реалізацію вимог по роботи з ціфровими документами через кабінет, відповідає окремий компонент "_Сервіс цифрових документів_", який використовує _Ceph_ у якості сховища файлів та надає наступний API для роботи з ними:

- Завантаження файлів цифрових документів
- Генерація _SHA256_-геш при завантаженні
- Отримання мета-даних завантажених файлів
- Вивантаження файлів цифрових документів
- Видалення файлів цифрових документів

[NOTE]
Детальніше з дизайном компоненти "_Сервіс цифрових документів_" можна ознайомитися xref:digita-document-service/digital-document-service.adoc[за посиланням]

=== Обмін цифровими документами між підсистемами платформи

- Файли цифрових документів є невід'ємною частиною сутності, в рамках створення якої вони були збережені
- "_REST API_" підсистеми "_Дата Фабрика_" оперує лише UUID-ідентифікаторами та _SHA256_-гешами на рівні структур даних сутностей
- При виконанні запиту на збереження сутності, яка містить UUID-ідентифікатори, Дата Фабрика очікує, що в бакеті "_lowcode-file-storage_" є наявні Ceph-документи за цими UUID-ами, _SHA256_-геші яких співпадають з тими, які були передані разом с запитом
- При виконанні запиту на отримання сутності, яка містить UUID-ідентифікатори, Дата Фабрика гарантує клієнту наявність у бакеті "_lowcode-file-storage_" Ceph-документів за цими UUID-ами, _SHA256_-геші яких співпадають з тими, які передані як частина сутності
- Доступ до файлів, завантажених як вкладення до сутності, на рівні підсистеми "Low-code" можливий лише через отримання даних цієї сутності та послідуюче отримання документа за UUID-ідентифікатором Ceph-документа через компоненту "_Сервіс цифрових документів_"

[plantuml, file_exchange, svg]
----
include::partial$lowcode/digital-documents-exchange.puml[]
----

=== Контракт взаємодії між підсистемами платформи

.Канонічний вигляд тіла запиту до Дата Фабрики на збереження даних сутності з файловими вкладеннями
[source,json]
----
{
  "<file_property_name>": [
    {
      "id": "{UUID}",
      "hash": "{SHA256-hash}"
    }
  ]
}
----

.Канонічний вигляд відповіді Дата Фабрики на запит отримання даних сутності з файловими вкладеннями
[source,json]
----
{
  "<file_property_name>": [
    {
      "id": "{UUID}",
      "hash": "{SHA256-hash}"
    }
  ]
}
----

== Сценарії взаємодії користувача з системою

=== Завантаження цифрових документів

На даній діаграмі зображено сценарій внесення даних з файловими вкладеннями в рамках виконання задачі користувачем, обробка даних в рамках бізнес-процесу та використання їх для попереднього заповнення наступної задачі користувача.

[plantuml, file_upload, svg]
----
include::partial$lowcode/file-upload.puml[]
----

.Канонічний вигляд структури документа у тілі запиту на збереження даних форми через серверний додаток
[source, json]
----
{
  "data": {
      "<file_property_name>": [
        {
          "id": "{UUID}",
          "hash": "{SHA256-hash}"
        }
      ]
  }
}
----

.Опис формату збереження документів в Ceph у процесі обробки запиту на виконання задачі
[source, json]
----
{
  "data": {
      "<file_property_name>": [
        {
          "id": "{UUID}",
          "hash": "{SHA256-hash}"
        }
      ]
  },
  "x-access-token": "<X-Access-Token>"
}
----

=== Вивантаження цифрових документів

На даній діаграмі зображено сценарій отримання сутності з файловими вкладеннями, яка була попередньо збережена у Дата Фабриці та послідуюча її підготовка для відображення на UI-формі задачі користувача.

[plantuml, file_download, svg]
----
include::partial$lowcode/file-download.puml[]
----

.Канонічний вигляд відповіді серверного додатоку на запит отримання даних форми
[source, json]
----
{
  "data": {
      "<file_property_name>": [
        {
          "id": "{UUID}",
          "hash": "{SHA256-hash}"
        }
      ]
  }
}
----

=== Підпис даних UI-форм з цифровими документами

На даній діаграмі зображено сценарій підпису даних з файловими вкладеннями в рамках виконання задачі користувачем, обробка даних в рамках бізнес-процесу та їх збереження в Дата Фабрику.

[plantuml, file_signing, svg]
----
include::partial$lowcode/file-signing.puml[]
----


.Канонічний вигляд структури документа у тілі запиту на збереження підписаних даних форми через серверний додаток
[source, json]
----
{
  "data": {
      "<file_property_name>": [
        {
          "id": "{UUID}",
          "hash": "{SHA256-hash}"
        }
      ]
  },
  "signature": "<e-Signature>"
}
----

.Опис формату збереження документів з підписом в Ceph
[source, json]
----
{
  "data": {
      "passport_scans": [
        {
          "id": "{UUID}",
          "hash": "{SHA256-hash}"
        }
      ]
  },
  "x-access-token": "<X-Access-Token>",
  "signature": "<e-Signature>"
}
----

== Моделювання UI-форм

=== Типова конфігурація поля типу "_File_" для налаштування адміністратором регламента
|===
|Розділ меню|Назва налаштування|Значення|Опис
|Display
|Label
|<На розсуд адміністратора>
|Текстовий опис поля для користувача

|API
|Property Name
|<На розсуд адміністратора>
|Назва поля у JSON-документі структури даних

|File
|Storage
|URL
|Збереження контента завантаженого файла на сервері

|File
|Display as Image(s)
|false
|Відображення піктограм для зображень, замість табличного вигляду

|Data
|Multiple Values
|<На розсуд адміністратора>
|Підтримка завантаження декількох файлів

|File
|File Pattern
|application/pdf,image/jpeg,image/png
|Паттерн файлів, дозволених для завантаження

|File
|File Maximum Size
|<На розсуд адміністратора>
|Максимальний розмір одного файлу

|File
|File Maximum Number
|<На розсуд адміністратора>
|Максимальна кількість файлів для завантаження [red]#(не підтримується Form.IO)#
|===

=== JSON-схема опису структури UI-форми з полем типу "File"
[source, json]
----
{
  "components": [
    {
      "label": "<file_property_label>",
      "storage": "url",
      "key": "<file_property_name>",
      "type": "file",
      "url": "/documents",
      "input": true
    }
  ]
}
----

== Відкриті питання

- #Авторизація доступу користувачів до файлів цифрових документів#, завантажених в рамках бізнес-процесів. Наразі, усі автентифіковані користувачі можут отримати доступ до цифрового документу в "_lowcode-file-storage_" через "Сервіс цифрових документів" за прямим посиланням, знаючи UUID. Дозволити доступ до цифрових документів тільки для запитів, ініційованих в рамках виконання задач бізнес-процесу, в рамках якого вони були завантажені або отримані з підсистеми "_Дата Фабрика_"
- #Переповнення Ceph-бакету тимчасового зберігання цифрових документів#. Необхідно налаштувати політику видалення документів, породжених в рамках виконання бізнес-процесу у разі його завершення. Необхідно враховувати, що один і той же документ (з однаковим UUID) може використовуватись у різних бізнес-процесах
- #Розмежування "однакових" цифрових документів (які мають один UUID), отриманих в рамках різних бізнес-процесів#. Розглянути використання комбінованого ключа для Ceph-документів файлів вигляду "<process-instance-UUID/document-UUID>"
- У разі, якщо накладання підпису приватним ключем користувача на SHA256-геш файла цифрового документа недостатньо, існує можливість накладання підпису на файл перед завантаженням на сервер з послідуючим збереженням підпису у вигляді окремого атрибута Ceph-документу
