= Підсистема зовнішніх інтеграцій

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Підсистема, призначення якої є забезпечення інтероперабельності платформи шляхом налаштування можливості надавати доступ до бізнес-процесів та API читання даних, а також надання інтерфейсів для взаємодії зовнішніх систем з реєстром через СЕВДЕІР "Трембіта".

== Функції підсистеми

* Ініціювання автоматичних та напівавтоматичних бізнес-процесів реєстру
* Виконання пошукових операцій по даним реєстру
* Отримання записів за унікальним ідентифікатором з реєстру
* Надання API для виклику бізнес-процесів реєстру сторонніми для реєстру системами.
* Надання доступу іншим реєстрам або системам до окремих запитів читання _Підсистеми управління даними реєстру_.
* Маршрутизація запитів до зовнішніх реєстрів до яких було надано доступ.

== Технічний дизайн підсистеми

.Логічна діаграма підсистеми
image::arch:architecture/registry/operational/external-integrations/cross-registry-integration-context.svg[]

.Розгорнуті сценарії послідовності даних
image::arch:architecture/registry/operational/external-integrations/cross-registry-integration-flow.svg[]

В рамках цієї підсистеми виникає взаємодія між двома реєстрами розгорнутими на одній платформі, що створює звʼязок реєстр джерело даних та реєстр споживач даних.

Реєстр джерело даних - реєстр тримач даних який дозволяє операції читання цих даних за допомогою окремих пошукових запитів.

Реєстр споживач даних - реєстр якому було надано доступ до пошукових запитів _реєстру джерела даних_

Ключовий аспект який дозволяє таку взаємодію це створення сервісного користувача в реєстрі джерелі для реєстру споживача даних та використання його при здійсненні запитів.
Отримання облікових даних сервісного користувача та операція автентифікації здійснюється _API-шлюзом міжреєстрової взаємодії_ розгорнутим в реєстрі споживачі даних.
Сам _API-шлюз міжреєстрової взаємодії_ доступний для автентифікованих користувачів реєстру споживача даних.

Окремим випадком є надання доступу до даних сторонній системі споживачу даних. В даному сценарії створюється окремий сервісний користувач, а його облікові дані передаються адміністраторам системи тоді автентифікація і обмін токенів має відбуватись безпосередньо сторонньою системою.

== Складові підсистеми

|===
|Назва компоненти|Представлення в реєстрі|Походження|Репозиторій|Призначення

|_API-шлюз для викликів БП зовнішніми системами_
|`bp-webservice-gateway`
|origin
| https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/low-code-platform/platform/backend/applications/bp-webservice-gateway[bp-webservice-gateway]
|Шлюз надання доступу для виклику бізнес процесів сторонніми системами через _ШБО Трембіта_ та напряму через _Підсистему управління
зовнішнім трафіком_.

|_API-шлюз для читання даних реєстру зовнішніми системами_
|`registry-soap-api-deployment`
|origin
|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/data-architecture/libraries/soap-api-core-base-image[core], https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/data-architecture/libraries/service-generation-utility[generation]
|Компонент який надає _SOAP_ інтерфейс для читання даних через _ШБО Трембіта_.

|_API-шлюз міжреєстрової взаємодії_
|`platform-gateway-deployment`
|origin
|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/low-code-platform/platform/backend/applications/platform-gateway[platform-gateway]
|Сервіс виконання запитів до реєстрів платформи від імені сервісних користувачів.

|_Сервіс синхронного управління даними реєстру для міжреєстрової взаємодії_
|`registry-rest-api-ext`
|origin
|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/data-architecture/libraries/rest-api-core-base-image[core], https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/data-architecture/libraries/service-generation-utility[generation]
|Виділений екземпляр сервісу синхронного управління даними для надання доступу до читання даних іншим реєстрам на платформі.

|_Сервіс синхронного управління даними реєстру для публічного доступу до даних_
|`registry-rest-api-public`
|origin
|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/data-architecture/libraries/rest-api-core-base-image[core], https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/data-architecture/libraries/service-generation-utility[generation]
|Виділений екземпляр сервісу синхронного управління даними для надання доступу до читання даних з публічним доступом

|===

== Технологічний стек

* xref:arch:architecture/platform-technologies.adoc#java[Java]
* xref:arch:architecture/platform-technologies.adoc#spring[Spring]
* xref:arch:architecture/platform-technologies.adoc#spring-boot[Spring Boot]
* xref:arch:architecture/platform-technologies.adoc#spring-cloud[Spring Cloud]

== Атрибути якості підсистеми

=== _Interoperability_

_Підсистема зовнішніх інтеграцій_ підтримує сумісність з іншими системами за рахунок надання стандартизованих інтерфейсів для взаємодії з платформою (_REST_, _SOAP_).

=== _Scalability_

_Підсистема зовнішніх інтеграцій_ підтримує як горизонтальне, так і вертикальне масштабування.


[TIP]
--
Детальніше з масштабуванням підсистем можна ознайомитись у відповідних розділах:

* xref:architecture/container-platform/container-platform.adoc[]
--

=== _Observability_

_Підсистема зовнішніх інтеграцій_ підтримує журналювання та збір метрик продуктивності для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--

=== _Security_

В _Підсистемі зовнішніх інтеграцій_ всі комунікації здійснюються з використанням асинхронного шифрування трафіку TLS. Всі запити до сервісів які безпосередньо здійснюють операції над даними реєстру вимагають автентифікацію. Запити між реєстрами в середині _Платформи_ здійснюються за внутрішніми іменами сервісів (внутрішня мережа).
