= Підсистема зовнішніх інтеграцій
include::ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

Підсистема надає стандартизовані інтерфейси для взаємодії на базі _REST_ та _SOAP_ протоколів з ціллю забезпечення інтероперабельності реєстру з зовнішніми системами.

_Підсистема зовнішніх інтеграцій_ підтримує наступні опції налаштування інформаційного обміну:

* Через використання шини безпечного обміну "_Трембіта_" у якості захищеного транспорту.
* Через налаштування прямих інтеграцій з зовнішніми системами, які не є учасниками інформаційного обміну _СЕВДЕІР "Трембіта"_.
* Через налаштування прямих інтеграцій з реєстрами, які розгорнуті на одному екземплярі _Платформи Реєстрів_.
* Через публічно-доступний _API_.

Зовнішніми системами для інтеграції можуть виступати як сторонні інформаційні системи, так і реєстри, розгорнуті на окремих екземплярах _Платформи Реєстрів_.

== Функції підсистеми

* Надання API для ініціювання автоматичних та напівавтоматичних бізнес-процесів реєстру сторонніми системами.
* Надання API пошукових операцій по даним реєстру стороннім системам.
* Маршрутизація запитів при міжреєстровій взаємодії на одному екземплярі _Платформи Реєстрів_.

== Технічний дизайн підсистеми

.Логічна діаграма підсистеми
image::arch:architecture/registry/operational/external-integrations/cross-registry-integration-context.svg[]

.Розгорнуті сценарії послідовності даних
image::arch:architecture/registry/operational/external-integrations/cross-registry-integration-flow.svg[]

=== Міжреєстрова взаємодія

В рамках цієї підсистеми виникає взаємодія між двома реєстрами розгорнутими на одній платформі, що створює звʼязок реєстр джерело даних та реєстр споживач даних.

_Реєстр джерело даних_ - реєстр тримач даних який дозволяє операції читання цих даних за допомогою окремих пошукових запитів.

_Реєстр споживач даних_ - реєстр якому було надано доступ до пошукових запитів _реєстру джерела даних_

Ключовий аспект який дозволяє таку взаємодію це створення сервісного користувача в реєстрі джерелі для реєстру споживача даних та використання його при здійсненні запитів.
Отримання облікових даних сервісного користувача та операція автентифікації здійснюється _API-шлюзом міжреєстрової взаємодії_ розгорнутим в реєстрі споживачі даних.
Сам _API-шлюз міжреєстрової взаємодії_ доступний для автентифікованих користувачів реєстру споживача даних.

Окремим випадком є надання доступу до даних сторонній системі споживачу даних. В даному сценарії створюється окремий сервісний користувач, а його облікові дані передаються адміністраторам системи. В такому разі автентифікація і обмін токенів має відбуватись безпосередньо сторонньою системою.

== Аудит та журналювання подій

Події маніпуляцій з даними реєстру через сторонні системи фіксуються у журналі аудиту з повним контекстом.
Окрім подій xref:arch:architecture/registry/operational/registry-management/overview.adoc#_аудит_та_журналювання_подій[підсистеми управління даними реєстру] фіксуються додатково наступні події:

|===
|Тип події|Спосіб фіксації|Службова назва|Опис

|_USER_EVENT_|До та після події|SOAP request. Method: ${methodName}|Запит на читання даних з фіксацією конкретного методу.
|_USER_EVENT_|Під час виникнення|EXCEPTION|Помилка отримання даних.
|===

[NOTE]
--
Детальніше з дизайном _Підсистеми журналювання подій аудиту_ можна ознайомитися
xref:arch:architecture/registry/operational/audit/overview.adoc[за посиланням].
--

== Складові підсистеми

|===
|Назва компоненти|Представлення в реєстрі|Походження|Репозиторій|Призначення

|_API-шлюз для викликів БП зовнішніми системами_
|`bp-webservice-gateway`
|origin
a|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/data-architecture/libraries/bp-webservice-gateway-core-image[gerrit:/bp-webservice-gateway-core-image]

https://github.com/epam/edp-ddm-service-generation-utility[github:/epam/edp-ddm-service-generation-utility]
|Шлюз надання доступу для виклику бізнес процесів сторонніми системами через _ШБО Трембіта_ та напряму через _Підсистему управління
зовнішнім трафіком_.

|_API-шлюз міжреєстрової взаємодії_
|`platform-gateway-deployment`
|origin
|https://github.com/epam/edp-ddm-platform-gateway[github:/epam/edp-ddm-platform-gateway]
|Сервіс виконання запитів до реєстрів платформи від імені сервісних користувачів.

|_API-шлюз для читання даних реєстру зовнішніми системами_
|`registry-soap-api-deployment`
|origin
a|https://github.com/epam/edp-ddm-soap-api-core-base-image[github:/epam/edp-ddm-soap-api-core-base-image]

https://github.com/epam/edp-ddm-service-generation-utility[github:/epam/edp-ddm-service-generation-utility]
|Компонент який надає _SOAP_ інтерфейс для читання даних через _ШБО Трембіта_.

|_Сервіс синхронного управління даними реєстру для міжреєстрової взаємодії_
|`registry-rest-api-ext`
|origin
.2+a|https://github.com/epam/edp-ddm-rest-api-core-base-image[github:/epam/edp-ddm-rest-api-core-base-image]

https://github.com/epam/edp-ddm-service-generation-utility[github:/epam/edp-ddm-service-generation-utility]
|Виділений екземпляр сервісу синхронного управління даними для надання доступу до читання даних іншим реєстрам на платформі.

|_Сервіс синхронного управління даними реєстру для публічного доступу до даних_
|`registry-rest-api-public`
|origin
|Виділений екземпляр сервісу синхронного управління даними для надання доступу до читання даних з публічним доступом

|===

== Технологічний стек

При проектуванні та розробці підсистеми, були використані наступні технології:

* xref:arch:architecture/platform-technologies.adoc#java[Java]
* xref:arch:architecture/platform-technologies.adoc#spring[Spring]
* xref:arch:architecture/platform-technologies.adoc#spring-boot[Spring Boot]
* xref:arch:architecture/platform-technologies.adoc#spring-cloud[Spring Cloud]

== Атрибути якості підсистеми

=== _Interoperability_

_Підсистема зовнішніх інтеграцій_ підтримує сумісність з іншими системами за рахунок надання стандартизованих інтерфейсів для взаємодії з реєстром (_REST_, _SOAP_).

=== _Scalability_

_Підсистема зовнішніх інтеграцій_ підтримує як горизонтальне, так і вертикальне масштабування.


[TIP]
--
Детальніше з масштабуванням підсистем можна ознайомитись у відповідних розділах:

* xref:architecture/container-platform/container-platform.adoc[]
--

=== _Observability_

_Підсистема зовнішніх інтеграцій_ підтримує журналювання та збір метрик продуктивності для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--

=== _Security_

В _Підсистемі зовнішніх інтеграцій_ всі комунікації здійснюються з використанням асинхронного шифрування трафіку TLS. Всі запити до сервісів які безпосередньо здійснюють операції над даними реєстру вимагають автентифікацію. Запити між реєстрами в середині _Платформи_ здійснюються за внутрішніми іменами сервісів (внутрішня мережа).
