= Підсистема зовнішніх інтеграцій

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Підсистема, призначення якої є забезпечення інтероперабельності платформи шляхом налаштування можливості надавати доступ до бізнес-процесів та API читання даних, а також читати данні та викликати бізнес-процеси в інших реєстрах.

Підсистема, призначенням якої є надання інтерфейсів для взаємодії зовнішніх систем з реєстром через СЕВДЕІР "Трембіта".

== Функції підсистеми

* Ініціювання автоматичних та напівавтоматичних бізнес-процесів реєстру
* Виконання пошукових операцій по даним реєстру
* Отримання записів за унікальним ідентифікатором з реєстру
* Надання API для виклику бізнес-процесів реєстру сторонніми для реєстру системами.
* Надання доступу іншим реєстрам або системам до окремих запитів читання _Підсистеми управління даними реєстру_.
* Маршрутизація запитів до зовнішніх реєстрів до яких було надано доступ.

== Технічний дизайн підсистеми

image::arch:architecture/registry/operational/external-integrations/cross-registry-integration-context.svg[]

В рамках цієї підсистеми виникає взаємодія між двома реєстрами розгорнутими на одній платформі, що створює звʼязок реєстр джерело даних та реєстр споживач даних.

Реєстр джерело даних - реєстр тримач даних який дозволяє операції читання цих даних за допомогою окремих пошукових запитів.

Реєстр споживач даних - реєстр якому було надано доступ до пошукових запитів _реєстру джерела даних_

Ключовий аспект який дозволяє таку взаємодію це створення сервісного користувача в реєстрі джерелі для реєстру споживача даних та використання його при здійсненні запитів.
Отримання облікових даних сервісного користувача та операція автентифікації здійснюється _API-шлюзом міжреєстрової взаємодії_ розгорнутим в реєстрі споживачі даних.
Сам _API-шлюз міжреєстрової взаємодії_ доступний для автентифікованих користувачів реєстру споживача даних.

Окремим випадком є надання доступу до даних сторонній системі споживачу даних. В даному сценарії створюється окремий сервісний користувач, а його облікові дані передаються адміністраторам системи тоді автентифікація і обмін токенів має відбуватись безпосередньо сторонньою системою.

== Складові підсистеми

|===
|Назва компоненти|Представлення в реєстрі|Походження|Репозиторій|Призначення

|_API-шлюз для викликів БП зовнішніми системами_
|`bp-webservice-gateway`
|origin
|-
|-

|_API-шлюз для читання даних реєстру зовнішніми системами_
|`registry-soap-api-deployment`
|origin
|-
|-

|_API-шлюз міжреєстрової взаємодії_
|`platform-gateway-deployment`
|origin
|-
|-

|_Сервіс синхронного управління даними реєстру для міжреєстрової взаємодії_
|`registry-rest-api-ext`
|origin
|-
|-

|===

== Технологічний стек

* ...

== Атрибути якості підсистеми

...