@startuml
!theme bluegray
start
if (**Validate version**
  OldVer>=NewVer) then (yes)
  #red:ERROR;
  kill
endif
:**Update DB schema**;
:**Update Version to {NewVer} in registry metadata**;
split
  :**Create new**
  **projects/codebases/repos**

  //{RegName}-rest-api-{NewVer}//
  //{RegName}-kafka-api-{NewVer}//
  //{RegName}-model-{NewVer}//;
split again
  if (Exposed Search Conditions exist?) then (yes)
    :**Create new**
    **project/codebase/repo**

    //{RegName}-soap-api-{NewVer}//;
  endif
end split
:**Create new build pipelines for each project**

//{project-name}//;
:**Generate code for all projects**;
:**Commit generated code**;
:**Run Build pipelines for all projects**;
:**Add docker images to Nexus**

//{project-name}-{repoChecksum}-{agentVersion}:{NewVer}//;
:**Deploy services**;
end
legend right
    |Name| Description |
    |{OldVer}|Поточна версія реєстру|
    |{NewVer}|Версія реєстру що розгортається|
    |{RegName}|Ім'я реєстру|
    |{project-name}| Ім'я згенерованого проекту/репозиторію|
    |{repoChecksum}| md5sum вмісту регламенту реєстру|
    |{agentVersion}| Версія дженкінс агента|
endlegend
@enduml