:sectlinks:
= Елементи моделювання

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

У цьому розділі представлені основні елементи, необхідні для створення та оптимізації бізнес-процесів. Ви дізнаєтеся про:

* [*] *Задачі (Tasks):* фундаментальні дії, які виконуються в рамках процесу.
* [*] *Шлюзи (Gateways):* керують потоком процесу, залежно від визначених умов.
* [*] *Події (Events):* відіграють важливу роль у старті, завершенні та реагуванні на зміни в процесі.
* [*] *Підпроцеси (Subprocesses):* дозволяють структурувати складні процеси для кращого управління.
* [*] *Слухачі виконання (Execution listeners):* надають зворотний зв'язок і контроль над процесом.

Цей допоможе вам ефективно керувати бізнес-процесами, забезпечуючи продуктивність та гнучкість у роботі.

== Огляд секції

* xref:bp-modeling/bp/bpmn/tasks/overview.adoc[]
* xref:bp-modeling/bp/bpmn/gateways/event-based-gateway.adoc[Шлюзи]
* xref:bp-modeling/bp/bpmn/events/events-overview.adoc[]
* xref:bp-modeling/bp/bpmn/subprocesses/subprocess-overview.adoc[]
* xref:bp-modeling/bp/bpmn/execution-listeners.adoc[]