= Інструменти адміністратора Платформи
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Вступ

Адміністратор Платформи має опанувати певний набір адміністративних інструментів для підтримки та моніторингу працездатності кластера, де розгорнута Платформа.

TIP: Детальніше про обов'язки адміністратора Платформи дивіться на сторінці xref:admin:admin-study/admin-profile.adoc[].

== Налаштування локального середовища

Для повноцінної та зручної роботи із Платформою, вам необхідно налаштувати локальне середовище. Для цього встановіть на вашій локальній машині наступний перелік інструментів:

include::registry-develop:partial$snippets/study/local-environment-setup-ua.adoc[]

== Інструменти розробки: робоче середовище

include::registry-develop:partial$snippets/study/platform-tools-ua.adoc[]

Адміністратор Платформи має вміти використовувати інструменти xref:admin:registry-management/control-plane-quick-links.adoc#platform-admin-zone[адміністративної зони Платформи] та xref:admin:registry-management/control-plane-quick-links.adoc#platform-operational-zone[операційної зони Платформи]. 
Ми також рекомендуємо ознайомитися з інструментами адміністративної та операційної зон реєстру, оскільки адміністраторам Платформи інколи доводиться брати участь у реєстрових процесах.