== Модель даних

=== Загальний опис

Модуль для організації роботи з конфігурацією моделі даних.

.Надає наступний функціонал:
- Отримання списку всіх бізнес-процесів регламенту
- Дозволені CRUD операції над бізнес-процесами регламенту

=== Описання структури DataModelSnapshot

[plantuml, registry-regulation-management db-tables-management-er, svg]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/data-model/db-tables-management-er.puml[]
----

== Допустимі операції з об'єктами доменної моделі

IMPORTANT: Об'єкти моделі даних, що не були інтегровані в мастер версію регламенту реєстру, можуть бути змінені будь-яким чином не зважаючи на нижче вказані обмеження.

=== Допустимі операції з об'єктами доменної моделі, що ввійшли в мастер версію

|===
|Назва entity|Create| Update| Delete

|Table|Y|Y|N
|Column|Y|Y|N
|Index|Y|Y|Y
|Constraint|Y|Y|Y
|ForeignKey|Y|Y|Y
|AccessRule|Y|Y|Y|
|===

=== Опис структури файлів на файловій системі

DataModelSnapshot model має наступну структуру файлів на файловій системі

image::arch:architecture/registry/administrative/regulation-management/services/registry-regulation-management/data-model/tables-management-datamodel-filestructure.svg[]

- Перелік таблиць визначається переліком файлів на файловій системі
- Ім'я файлу таблиць відповідає назві таблиці та має наступний вигляд: `<table-name>.json`
- Ім'я файлу role permission відповідає назві id role permission та має наступний вигляд: `<role-id>.json`

=== Загальна діаграма взаємодії компонентів системи під час редагування моделі даних регламенту реєстру

image::arch:architecture/registry/administrative/regulation-management/services/registry-regulation-management/data-model/tables-management-component-structure.svg[]

==== Типи JSON документів:
DataModelSnapshot model - JSON документи, що відображають стан моделі даних регламенту реєстру

Diff Document - документ, що відображає різницю між двома станами моделі даних регламенту реєстру

History Document - документ, що відображає історію змін мастер версії або версії- кандидату регламенту реєстру

==== Основні принципи
- RestAPI використовує структури даних описані json схемами DataModelSnapshot документів
- Пайплайн перевірки конфігурації регламенту реєстру використовується для актуалізації DataModelSnapshot document's в разі  внесення змін няпряму в  пуккше  розробником реєстру
- Зміни внесені через адміністративний портал знаходяться в окремому liquibase changeset. Ідентифікатор версії-кандидату є частиною liquibase changeset id атрибуту.

=== DataModelSnapshot entities json schema

==== Table JsonSchema
[source,json]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/data-model/schema/DataModelSnapshotSchema-table.json[]
----

==== Table Document example
[source,json]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/data-model/schema/examples/table-example.json[]
----

==== Role permissions JsonSchema
[source,json]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/data-model/schema/DataModelSnapshotSchema-role-permission.json[]
----

==== Role permissions document example
[source,json]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/data-model/schema/examples/role-permission-example.json[]
----
