{{- $root := .Values }}
{{- $release := .Release }}
{{- range $registry := $root.registryFederation.registries }}
---
apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakAuthFlow
metadata:
  name: registry-federation-authenticator
  annotations:
    helm.sh/resource-policy: keep
  namespace: {{ $registry.name }}
spec:
  alias: registry-federation-authenticator
  authenticationExecutions:
    - authenticator: registry-federation-authenticator
      requirement: ALTERNATIVE
      priority: 0
      authenticatorConfig:
        alias: registry-federation-authenticator
        config:
          selfRegistrationEnabled: '{{ $registry.selfRegistrationEnabled }}'
          selfRegistrationDefaultRoles: unregistered-officer
  builtIn: false
  providerId: basic-flow
  realm: officer-portal
  topLevel: true
{{- end }}