= Налаштування підключення для виклику зовнішніх SOAP-сервісів через ШБО "Трембіта"

Щоб мати змогу використовувати розроблені на Платформі SOAP-інтеграційні конектори до зовнішніх сервісів та отримувати інформацію від інших реєстрів через ШБО "Трембіта", необхідно попередньо виконати конфігурації на рівні регламенту реєстру.

Для цього потрібно налаштувати параметри `trembita-exchange-gateway` у конфігураційному файлі _bp-trembita/configuration.yml_.

.Приклад конфігурації підключення до сервісу ЄДР
[%collapsible]
====
[source,yaml]
----
trembita-exchange-gateway:
  registries:
    edr-registry:
      user-id: 'DDM'
      protocol-version: '4.0'
      trembita-url: 'https://trembita-edr-registry-mock.apps.cicd2.mdtu-ddm.projects.epam.com/mockEDRService'
      authorization-token: 'token'
      client:
        x-road-instance: 'SEVDEIR-TEST'
        member-class: 'GOV'
        member-code: '43395033'
        subsystem-code: 'IDGOV_TEST_01'
      service:
        x-road-instance: 'SEVDEIR-TEST'
        member-class: 'GOV'
        member-code: '00015622'
        subsystem-code: '2_MJU_EDR_prod'
----
====

.Приклад конфігурації підключення до сервісу ДРАЦС
[%collapsible]
====
[source,yaml]
----
trembita-exchange-gateway:
  registries:
    dracs-registry:
          trembita-url: 'https://trembita-dracs-registry-mock.apps.cicd2.mdtu-ddm.projects.epam.com/dracsMock'
          user-id: 'DDM'
          protocol-version: '4.0'
          client:
            x-road-instance: 'SEVDEIR-TEST'
            member-class: 'GOV'
            member-code: '43395033'
            subsystem-code: 'IDGOV_TEST_01'
          service:
            x-road-instance: 'SEVDEIR-TEST'
            member-class: 'GOV'
            member-code: '22956058'
            subsystem-code: 'TEST_DRAC'
----
====
.Опис структурних параметрів
[width="100%",cols="30%,70%",options="header",]
|===
|Параметр|Опис

|registries|Назва реєстру, до якого буде сформовано запит
2+|_Заголовки, що ідентифікують користувача, який робить запит_
|trembita-url|Адреса до ШБО
|user-id|Ідентифікатор користувача, який ініціює запит
|protocol-version|Версія протоколу, за яким обмінюються повідомлення ШБО.

_На цей час версія протоколу 4.0_

2+|_Заголовок (client), який ідентифікує учасника сервісу_
|x-road-instance|Код середовища, який ідентифікує екземпляр учасника
|member-class|Ідентифікатор класу учасника
|member-code|Ідентифікатор учасника
|subsystem-code|Код, який ідентифікує підсистему учасника, якщо сервіс надається підсистемою

2+|_Заголовок (service), який ідентифікує сервіс_
|x-road-instance|Код середовища, який ідентифікує екземпляр сервісу
|member-class|Ідентифікатор класу сервісу
|member-code|Ідентифікатор сервісу
|subsystem-code|Код, який ідентифікує підсистему сервісу, якщо сервіс надається підсистемою
|===

Повний каталог вебсервісів системи ШБО "Трембіта", де можна отримати необхідні ідентифікатори, представлено за посиланнями:

* link:https://directory-test.trembita.gov.ua:8443/[Каталог вебсервісів (тестове середовище)]
* link:https://directory-prod.trembita.gov.ua:8443/[Каталог вебсервісів (промислове середовище)]