= Підсистема розподіленого зберігання даних

== Загальний опис

Підсистема, що забезпечує функціонування об’єктного (S3 сумісного), блочного та файлового сховища в Платформі.

== Функції підсистеми

* Підтримка функціонування обʼєктного, файлового та блочного сховища
* Моніторинг сховища
* Масштабування та аварійне відновлення обʼєктного, файлового та блочного сховища

== Технічний дизайн підсистеми

На даній діаграмі зображено компоненти, які входять в _Підсистему розподіленого зберігання даних_ та їх взаємодію з іншими підсистемами.

image::architecture/platform/operational/distributed-data-storage/distributed-data-storage.drawio.svg[width=800,float="center",align="center"]

TIP: Для більш детальної інформації про компоненти _ceph_ та _rook_ зверніться до офіціальної документації
https://docs.ceph.com/en/quincy/architecture/[ceph architecture] та https://rook.io/docs/rook/v1.10/Getting-Started/storage-architecture/[rook architecture]

== Складові підсистеми

|===
|Назва компоненти|Namespace|Deployment|Походження|Репозиторій|Призначення

|_Операційне об'єктне сховище реєстру_
|`<registry>`
a|
* `ceph:lowcode-file-storage`
* `ceph:datafactory-ceph-bucket`
* `ceph:file-excerpt-bucket`
* `ceph:excerpt-signature-bucket`
|-
|-
|-

|_Ceph дашборд_
|openshift-storage
|rook-ceph-dashboard
|3rd-party
|-
|Переглядання основних Ceph метрик, стану сховища та логів підсистеми розподіленого зберігання файлів

|_Rook Ceph Operator_
|openshift-storage
|rook-ceph-operator
|3rd-party
|-
|Допоміжне програмне забезпечення, яке виконує функції оркестрування Ceph сховища

|_OpenShift Container Storage Operator_
|openshift-storage
|ocs-operator
|3rd-party
|https://github.com/red-hat-storage/ocs-operator[github:/red-hat-storage/ocs-operator]
|Допоміжне програмне забезпечення, яке виконує функції оркестрування Ceph сховища

|_Ceph Metadata Server_
|openshift-storage
|rook-ceph-mds
|3rd-party
|-
|Компонент, що керує метаданими файлів в Ceph сховищі

|_Ceph Manager_
|openshift-storage
|rook-ceph-mgr
|3rd-party
|-
|Компонент, що працює для забезпечення моніторингу сховища Ceph та взаємодії із зовнішніми системами моніторингу та керування.

|_Ceph Monitor_
|openshift-storage
|rook-ceph-mon
|3rd-party
|-
|Компонент, що підтримує "мапу" стану Ceph сховища та мапу OSD (Object Storage Device)

|_Ceph Object Storage Device_
|openshift-storage
|rook-ceph-osd
|3rd-party
|-
|Програмне забезпечення Ceph сховища, яке взаємодіє з логічними дисками кластера OpenShift.

|_Ceph Object Gateway_
|openshift-storage
|rook-ceph-rgw
|3rd-party
|-
|Компонент Ceph сховища, який забезпечує шлюз до об’єктного Amazon S3 API сховища

|_Ceph RBD CSI Driver_
|openshift-storage
|rook-ceph-rgw
|3rd-party
|-
|-

|_CephFS CSI Driver_
|openshift-storage
|rook-ceph-rgw
|3rd-party
|-
|-

|_OCS Metrics Exporter_
|openshift-storage
|ocs-metrics-exporter
|3rd-party
|-
|-

|_Rook Ceph Crash Collector_
|openshift-storage
|ocs-metrics-exporter
|3rd-party
|-
|-

|===

== Технологічний стек

* xref:arch:architecture/platform-technologies.adoc#ceph[Ceph]
* xref:arch:architecture/platform-technologies.adoc#rook-operator[Rook]
* xref:arch:architecture/platform-technologies.adoc#okd[okd]

== Атрибути якості підсистеми

=== _Scalability_
Підсистема розподіленого зберігання даних розроблена для горизонтального масштабування на сотні або навіть тисячі вузлів
зберігання даних, забезпечуючи при цьому величезні обсяги зберігання даних. Підсистема має динамічну здатність
масштабування що дозволяє кластерам зростати або зменшуватися за потреби.

=== _Reliability_
Підсистема розподіленого зберігання даних використовує реплікацію даних та _erasure coding (EC)_ методи для захисту від
втрати даних та забезпечення відмовостійкості підсистеми. У разі відмови вузла або пристрою зберігання, підсистема
автоматично реплікує втрачені дані на інших робочіх вузлах для підтримання надійного збереження даних.

=== _Resilience_
Підсистема розподіленого зберігання даних залишається працездатною, навіть коли стикається з проблемами мережі або
відмовами вузлів зберігання даних. Завдяки динамічному балансуванню навантаження та методам розподілу даних в поєднанні
з відмовостійким проектуванням забезпечується стійкість в умовах апаратних або програмних проблем.

=== _Performance_
Завдяки паралельному читанню за запису даних, адаптивному балансуванню навантаження підсистема розподіленого зберігання даних
забезпечує високу пропускну здатність та продуктивність.
