@startuml

class Payload {
  JSON body
  DigitalSignature ds
}

class DigitalSignature {
  DigitalSignatureSource source
  String hash
  JSON body
  UUID business_process_instance
  DigitalSignature original
}

enum DigitalSignatureSource {
  USER
  SYSTEM
}

Payload --* DigitalSignature
DigitalSignature -left-* DigitalSignature
DigitalSignature -right-* DigitalSignatureSource


@enduml