site:
  title: MDTU-DDM 
  url: https://docs.demo.com
  start_page: datafactory:ROOT:index.adoc
content:
  sources:
  - url: ./
    branches: HEAD
  - url: git@gitbud.epam.com:mdtu-ddm/data-architecture/libraries/service-generation-utility.git
    branches: HEAD
    start_path: docs
  # - url: ../template-kafka-api 
  #   branches: HEAD
  #   start_path: docs
  # - url: ../template-rest-api 
  #   branches: HEAD
  #   start_path: docs
  # - url: ../template-model 
  #   branches: HEAD
  #   start_path: docs
  # - url: ../liquibase-ddm-ext
  #   branches: HEAD
  #   start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: 'https://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true