# Antora playbook for generating site based on remote content repositories
site:
  title: Платформа для розгортання та супроводження державних електронних реєстрів
  url: https://docs.demo.com
  start_page: platform:ROOT:index.adoc
output:
  dir: ./build/site
content:
  sources:
  - url: ./
    branches: ["1.6.0", "master"]
  - url: git@gitbud.epam.com:mdtu-ddm/data-architecture/libraries/service-generation-utility.git
    branches: ["1.6.0", "master"]
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/data-architecture/application/template-rest-api.git
    branches: ["1.6.0", "master"]
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/data-architecture/application/template-kafka-api.git
    branches: ["1.6.0", "master"]
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/data-architecture/libraries/data-model.git
    branches: ["1.6.0", "master"]
    start_path: docs

  - url: git@gitbud.epam.com:mdtu-ddm/general/keycloak-ds-officer-authenticator.git
    branches: ["1.6.0", "master"]
    start_path: docs

  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/backend/applications/digital-signature-ops.git
    branches: ["1.6.0", "master"]
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/backend/applications/digital-document-service.git
    branches: ["1.6.0", "master"]
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/backend/applications/user-task-management.git
    branches: ["1.6.0", "master"]
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/backend/applications/user-process-management.git
    branches: ["1.6.0", "master"]
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/backend/applications/bp-admin-portal.git
    branches: ["1.6.0", "master"]
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/business-process-modeler-extensions.git
    branches: ["1.6.0", "master"]
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/backend/utilities/camunda-auth-cli.git
    branches: ["1.6.0", "master"]
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/backend/applications/form-management.git
    branches: ["1.6.0", "master"]
    start_path: docs

  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/backend/applications/bpms.git
    branches: ["hotfix-r1-6", "master"]
    start_path: docs

  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/frontend/libraries/web-components-library.git
    branches: ["hotfix-r1-6", "master"]
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/frontend/applications/officer-portal.git
    branches: ["hotfix-r1-6", "master"]
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/frontend/applications/citizen-portal.git
    branches: ["hotfix-r1-6", "master"]
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/frontend/applications/admin-portal.git
    branches: ["hotfix-r1-6", "master"]
    start_path: docs

  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/frontend/applications/common-web-app.git
    branches: HEAD
    start_path: docs

  - url: git@gitbud.epam.com:mdtu-ddm/infrastructure/backup-management.git
    branches: ["1.6.0", "master"]
    start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: 'https://plantuml.apps.cicd2.mdtu-ddm.projects.epam.com'
    plantuml-fetch-diagram: true
