# Antora playbook for generating site based on remote content repositories
site:
  title: Платформа для розгортання та супроводження державних електронних реєстрів
  url: https://docs.demo.com
  start_page: platform:ROOT:index.adoc
output:
  dir: ./build/site
content:
  sources:
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/general/ddm-architecture
    branches: ["1.6.0", "1.7.0", "1.8.0", "master"]
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/data-architecture/libraries/service-generation-utility
    branches: ["1.6.0", "1.7.0", "1.8.0", "master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/data-architecture/application/template-rest-api
    branches: ["1.6.0", "1.7.0", "1.8.0", "master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/data-architecture/application/template-kafka-api
    branches: ["1.6.0", "1.7.0", "1.8.0", "master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/data-architecture/libraries/data-model
    branches: ["1.6.0", "1.7.0", "1.8.0", "master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/general/keycloak-ds-officer-authenticator
    branches: ["1.6.0", "1.7.0", "1.8.0", "master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/backend/applications/digital-signature-ops
    branches: ["1.6.0", "1.7.0", "1.8.0", "master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/backend/applications/digital-document-service
    branches: ["1.6.0", "1.7.0", "1.8.0", "master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/backend/applications/user-task-management
    branches: ["1.6.0", "1.7.0", "1.8.0", "master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/backend/applications/user-process-management
    branches: ["1.6.0", "1.7.0", "1.8.0", "master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/backend/applications/bp-admin-portal
    branches: ["1.6.0", "1.7.0", "1.8.0", "master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/business-process-modeler-extensions
    branches: ["1.6.0", "1.7.0", "1.8.0", "master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/backend/utilities/camunda-auth-cli
    branches: ["1.6.0", "1.7.0", "1.8.0", "master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/backend/applications/form-management
    branches: ["1.6.0", "1.7.0", "1.8.0", "master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/backend/applications/bpms
    branches: ["hotfix-r1-6", "1.7.0", "1.8.0", "master"]
    start_path: docs
#  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/frontend/libraries/web-components-library
#    branches: ["hotfix-r1-6", "1.7.0", "master"]
#    start_path: docs
#  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/frontend/applications/officer-portal
#    branches: ["hotfix-r1-6", "master"]
#    start_path: docs
#  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/frontend/applications/citizen-portal
#    branches: ["hotfix-r1-6", "master"]
#    start_path: docs
#  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/frontend/applications/admin-portal
#    branches: ["hotfix-r1-6", "master"]
#    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/frontend/applications/common-web-app
    branches: ["1.8.0", "master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/backend/applications/registry-regulation-management
    branches: ["master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/infrastructure/backup-management
    branches: ["1.6.0", "1.7.0", "1.8.0", "master"]
    start_path: docs
  - url: https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm/low-code-platform/platform/backend/low-code-platform-maven-tiles
    branches: ["master"]
    start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: 'https://plantuml.apps.cicd2.mdtu-ddm.projects.epam.com'
    plantuml-fetch-diagram: true
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
    languages: [ru, en]