# Antora playbook for generating site based on remote content repositories
site:
  title: MDTU-DDM
  url: https://docs.demo.com
  start_page: mdtuddm:ROOT:index.adoc
output:
  dir: ./build/site
content:
  sources:
  - url: ./
    branches: HEAD
  - url: git@gitbud.epam.com:mdtu-ddm/data-architecture/libraries/service-generation-utility.git
    branches: HEAD
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/data-architecture/application/template-rest-api.git
    branches: HEAD
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/data-architecture/application/template-kafka-api.git
    branches: HEAD
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/data-architecture/libraries/data-model.git
    branches: HEAD
    start_path: docs

  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/backend/applications/digital-signature-ops.git
    branches: HEAD
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/backend/applications/business-process-management.git
    branches: HEAD
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/backend/applications/user-task-management.git
    branches: HEAD
    start_path: docs
  - url: git@gitbud.epam.com:mdtu-ddm/low-code-platform/platform/backend/applications/user-process-management.git
    branches: HEAD
    start_path: docs

  - url: git@gitbud.epam.com:mdtu-ddm/infrastructure/backup-management.git
    branches: HEAD
    start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: 'https://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true