openapi: 3.0.3
info:
  title: Form service provider API
  description: This document describes REST API of 'Form schema provider service'
  version: "1.0"
paths:
  /api/forms/{key}:
    get:
      tags:
      - form-schema-provider-controller
      summary: Download form by key
      description: |-
        ### Endpoint purpose:
         This endpoint allows to download a form. The form is returned as a JSON object.
      operationId: getForm
      parameters:
      - name: X-Access-Token
        in: header
        description: Token used for endpoint security
        required: true
        schema:
          type: string
      - name: key
        in: path
        description: Form key
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Returns uploaded form metadata
          content:
            application/json:
              schema:
                type: string
              example: |-
                {
                  "title": "Test Form",
                  "path": "test-form",
                  "name": "test-form",
                  "display": "form",
                  "components": [
                    {
                      "type": "button",
                      "label": "Submit",
                      "key": "submit",
                      "size": "md",
                      "..."
                    }
                  ],
                }
        "401":
          description: You are not authorized to get the form
          content:
            application/json: {}
        "404":
          description: Form Not Found
          content:
            application/json: {}
        "500":
          description: Internal server error
          content:
            application/json: {}
    put:
      tags:
      - form-schema-provider-controller
      summary: Update form for business process
      description: |-
        ### Endpoint purpose:
         This endpoint allows to update a form that being used by process instance for get user input data.
      operationId: updateForm
      parameters:
      - name: X-Access-Token
        in: header
        description: Token used for endpoint security
        required: true
        schema:
          type: string
      - name: key
        in: path
        description: Form key
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: string
            example: |-
              {
                "title": "Test Form",
                "path": "test-form",
                "name": "test-form",
                "display": "form",
                "components": [
                  {
                    "type": "button",
                    "label": "Submit",
                    "key": "submit",
                    "size": "md",
                    "..."
                  }
                ],
              }
        required: true
      responses:
        "200":
          description: Form updated successfully
        "400":
          description: Bad Request.
          content:
            application/json: {}
        "401":
          description: You are not authorized to update the form
          content:
            application/json: {}
        "500":
          description: Internal server error
          content:
            application/json: {}
    delete:
      tags:
      - form-schema-provider-controller
      summary: Delete form by key
      description: |-
        ### Endpoint purpose:
         This endpoint allows the deletion of a specific form.
      operationId: deleteFormByKey
      parameters:
      - name: X-Access-Token
        in: header
        description: Token used for endpoint security
        required: true
        schema:
          type: string
      - name: key
        in: path
        description: Form key
        required: true
        schema:
          type: string
      responses:
        "204":
          description: Form deleted successfully
        "401":
          description: You are not authorized to delete the form
          content:
            application/json: {}
        "403":
          description: Forbidden
          content:
            application/json: {}
        "500":
          description: Internal server error
          content:
            application/json: {}
  /api/forms:
    post:
      tags:
      - form-schema-provider-controller
      summary: Upload form for business process
      description: |-
        ### Endpoint purpose:
         This endpoint allows to upload a form that being used by process instance for get user input data.
      operationId: saveForm
      parameters:
      - name: X-Access-Token
        in: header
        description: Token used for endpoint security
        required: true
        schema:
          type: string
      requestBody:
        content:
          text/plain:
            schema:
              type: string
            example: |-
              {
                "title": "Test Form",
                "path": "test-form",
                "name": "test-form",
                "display": "form",
                "components": [
                  {
                    "type": "button",
                    "label": "Submit",
                    "key": "submit",
                    "size": "md",
                    "..."
                  }
                ],
              }
        required: true
      responses:
        "201":
          description: Form saved successfully
        "400":
          description: Bad Request.
          content:
            application/json: {}
        "401":
          description: You are not authorized to add the form
          content:
            application/json: {}
        "500":
          description: Internal server error
          content:
            application/json: {}
components: {}
