@startuml
skinparam monochrome true
'skinparam backgroundColor #aaaaaa

Actor "Registry Admin" as RegAdmin
Actor "Change Admin" as ChAdmin
participant Gerrit

RegAdmin -> Gerrit: commit\nchangeSet
note right: data-model/role_permissions.xml
opt
note over ChAdmin, Gerrit: review process
...
else on success
ChAdmin -> Gerrit: merge\nchangeSet

end
Gerrit -> Jenkins: start\npipeline
note over Jenkins: registry-regulations\ndata-model\ncreate-schema
...
Jenkins -> Citus: redefine values for\nddm_role_permission
Jenkins -> Datafactory: regenerate API
...
note over Citus,Datafactory:permission changes\nare in effect

@enduml