= Registry regulations admin-portal Rest API

== Description
API includes managing operations over registry regulations entities:

- Forms
- Business processes
- Data model
- Global settings

=== RestAPI structure

image::arch:architecture/registry/administrative/regulation-management/services/registry-regulation-management/rest-api-structure.svg[registry-regulation-management RestAPI structure]


=== Optimistic locking

Optimistic locking is done using https://www.rfc-editor.org/rfc/rfc2616.html#page-126[RFC-2616]

Statements:

- ETag header contains a hash sum of entity content
- If-Match header instruction should be used for checking the state of the resource
- If the request header does not contain ETag, then client will overwrite existing resources in any case

[plantuml, admin-portal-restapi-optimistic-locking, svg]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/rest-api/rest-api-optimistic-locking.puml[]
----

[NOTE]
Client is not restricted to not use ETag's. In this case optimistic locking mechanism won't be used and owerwrites could happens for a resources. More details could be found xref:registry-regulation-management:rest-api/rest-api-partials/optimistic-locking.adoc [here].

=== Version control management usecase

[plantuml, admin-portal-version-management-usecase, svg]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/rest-api/restapi-version-management.puml[]
----

