= Інтеграційні SOAP-конектори до інших реєстрів
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

Ви можете взаємодіяти за SOAP-протоколом з реєстрами, що знаходяться поза межами Платформи, за допомогою Шлюзу безпечного обміну даними -- ШБО "Трембіта".

ШБО "Трембіта" є захищеним інтерфейсом для електронної взаємодії між державними системами. Він розгортається поруч із Платформою як сервіс і дозволяє використовувати його ресурси для інформаційного обміну між системами.

На Платформі передбачені типові інтеграційні розширення -- конектори (_також -- делегати_), що дозволяють здійснювати комунікацію із зовнішніми сервісами за протоколом SOAP через інтерфейс ШБО "Трембіта".

Кожний конектор використовується у бізнес-процесах для обміну даними між реєстрами на Платформі та зовнішніми реєстрами.

WARNING: Наразі функціонування розроблених конекторів можливе лише з використанням серверів-заглушок, що імітують живе з'єднання.

[CAUTION]
====
Щоб використовувати розроблені на Платформі SOAP-інтеграційні конектори для доступу до зовнішніх сервісів та отримання інформації з інших реєстрів через ШБО "Трембіта", необхідно попередньо виконати конфігурації на рівні реєстру в адміністративній панелі Control Plane.

_Детальніше про налаштування інтеграцій через ШБО "Трембіта" ви можете переглянути у статті xref:registry-develop:registry-admin/external-integration/cp-integrate-trembita.adoc[]_.
====

[soap-connectors-catalog]
== Каталог SOAP-інтеграційних розширень

Наразі на Платформі функціонують наступні розширення:

{empty}

++++

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Каталог SOAP-інтеграційних розширень</title>
    <style>
        .custom-table {
            width: 100%;
            border-collapse: collapse;
        }
        .custom-table th, .custom-table td {
            border: 1px solid #ddd;
            padding: 8px;
        }
        .custom-table th {
            text-align: center;
            background-color: white;
        }
        .status-active {
            background-color: #cffadb;
        }
        .code {
            font-family: monospace;
            background-color: #f9f9f9;
            padding: 2px 4px;
            border-radius: 3px;
        }
    </style>
</head>
<body>

<table class="custom-table">
    <tr>
        <th>Категорія</th>
        <th>Бізнес-назва</th>
        <th>Службова назва</th>
        <th>Статус</th>
        <th>Має новішу версію (v2+)</th>
    </tr>
    <tr>
        <td rowspan="2">Розширення-конектори для отримання даних з ЄДР</td>
        <td><a href="edr/subject-detail-edr-registry.html">Отримання деталізованої інформації за суб'єктом в ЄДР</a></td>
        <td><code>subjectDetailEdrRegistryConnectorDelegate</code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><a href="edr/search-subjects-edr-registry.html">Отримання інформації за суб'єктом в ЄДР</a></td>
        <td><code>searchSubjectsEdrRegistryConnectorDelegate</code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td rowspan="2">Розширення-конектори для отримання даних із ДРАЦС</td>
        <td><a href="dracs/get-certificate-by-birthdate.html">Отримання даних за свідоцтвом про народження (дата)</a></td>
        <td><code>getCertificateByBirthdateDracsRegistryDelegate</code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><a href="dracs/get-certificate-by-name.html">Отримання даних за свідоцтвом про народження (ПІБ)</a></td>
        <td><code>getCertificateByNameDracsRegistryDelegate</code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td>Розширення-конектор для отримання даних з ЄІБДВПО</td>
        <td><a href="eibdvpo/idp-exchange.html">Отримання інформації за довідкою ВПО</a></td>
        <td><code>idpExchangeServiceRegistryConnector</code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td rowspan="2">Загальні конектори</td>
        <td><a href="universal-connectors/soap-http-connector.html">SOAP HTTP-конектор</a></td>
        <td><code>soapHttpConnector</code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><a href="universal-connectors/trembita-soap-connector-delegate.html">Trembita SOAP-конектор</a></td>
        <td><code>trembitaSoapConnectorDelegate</code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
</table>

</body>
</html>

++++

