@startuml

autonumber
skinparam responseMessageBelowArrow true

actor "Адміністратор\n регламенту" as User
actor "Інспектор\n регламенту" as Reviewer

participant "Адміністративний портал" as FrontEnd
participant "Сервіс управління\n регламентом реєстру" as BackendService
participant "Сервіс інспекції змін" as Gerrit
participant "Сервіс публікації\n регламенту реєстру" as Jenkins

activate User
User -> FrontEnd: Ствоерння версії-кандидата регламенту
FrontEnd -> BackendService: Ствоерння версії-кандидата регламенту
activate BackendService
BackendService -> Gerrit: Створення окремої гілки
activate Gerrit
BackendService -> Gerrit: Отримання актуальної версії DataModelSnapshot
BackendService <-- Gerrit: DataModelSnapshot

BackendService -> Gerrit: Отримання історії змін DataModelSnapshot
FrontEnd <-- BackendService: DataModelSnapshot

BackendService -> BackendService: Опрацювання історії змін
FrontEnd <-- BackendService: History
User <-- FrontEnd: Версія-кандидат регламенту

User -> FrontEnd: Запит на збереження змін\n версії-кандидата регламенту
FrontEnd -> BackendService: Нова версія DataModelSnapshot

User -> FrontEnd: Запит на інспекцію змін\n версії-кандидата регламенту
FrontEnd -> BackendService: Відправка на review версії-кандидата

deactivate User

BackendService -> Gerrit: Отримання DataModelSnapshot документу\n актуальної на момент створення гілки змін
BackendService <-- Gerrit: DataModelSnapshot

BackendService -> Gerrit: Отримання зміненої DataModelSnapshot
BackendService <-- Gerrit: DataModelSnapshot
BackendService -> BackendService: побудова Diff документу
BackendService -> BackendService: перетворення Diif документу\n в liquibase changeset

BackendService -> BackendService: Додавання до liquibase сhangelog\n інформації з liquibase changeset
BackendService -> Gerrit: Збереження liquibase changeset
deactivate BackendService

activate Reviewer
Reviewer -> FrontEnd: Запит на інспекцію версії
FrontEnd -> BackendService: Запит на інспекцію версії

activate BackendService
BackendService -> Gerrit: Отримання статусу стану версії-кандидата
BackendService <-- Gerrit: Статус стану (конфлікти та тести)
BackendService -> Gerrit: Отримання DataModelSnapshot\n з гілки змін версії-кандидата

'Add diff here

BackendService -> Gerrit: Отримання документу з історією змін
BackendService <-- Gerrit: History
FrontEnd <-- BackendService: Версія-кандидат
Reviewer <-- FrontEnd: Версія-кандидат

Reviewer -> FrontEnd: Запит на застосування змін
deactivate Reviewer

FrontEnd -> BackendService: Запит на застосування змін

BackendService -> Gerrit: Merge PR
deactivate BackendService

Gerrit --> Jenkins: Відправка івенту на запуск RegistryRegulationJob

activate Jenkins
Jenkins -> Jenkins: Створення структури БД\n та заповнювання таблиці метаданних\n використовуючи liquibase changelog
Jenkins -> Jenkins: Створення DataModelSnapshot\n використовуючи БД

Jenkins -> Gerrit: Збереження актуалізованного DataModelSnapshot
deactivate Jenkins
Gerrit -> Gerrit: merge changes to master
deactivate Gerrit

@enduml