= Configuring logo and favicon for registry portals
include::platform:ROOT:partial$templates/document-attributes/default-set-en.adoc[]

== Overview

Registry admins and developers can now customize logo images, loaders, and favicons for user portals and the Administrative Portal within each registry on the Platform. This feature enhances personalization capabilities, enabling the creation of unique and consistent visual styles tailored to individual resources.

== Key features

* *Customizable logos:* Ability to update default logo images, loaders, and favicons for each registry.

* *Unified visual style:* Logos configured at the registry regulations level are automatically applied to the Administrative Portal and User Portals.

* *Flexible customization:* Ability to configure different logos for multiple registries within the same Platform, ensuring a tailored approach for each environment.

* *Change implementation via Gerrit:* Logo, loader, and favicon images are configured through the Gerrit system, ensuring an efficient and streamlined customization process.

[TIP]
====
* *Header logo* — An image or emblem displayed at the top of a page or application, such as on the navigation bar. It helps users identify the brand or platform.

* *Loader logo* — An image shown during the loading process of a page or operation. For instance, instead of a simple "spinner," your product logo might appear while users wait for something to load.

* *Favicon* — A small icon displayed on the browser tab next to the site name. It helps users quickly identify the tab among others.
====

== Configuration steps

[step-1]
=== Step 1: Clone the registry regulations repo

Clone the regulations repository for the registry to your local machine using the following command:

[source,bash]
----
git clone <repository_url>
----

[step-2]
=== Step 2: Update images locally

Replace the logo, loader, and favicon images by copying the respective files into the `assets` folder of the regulations repository:

* `header-logo.svg`
* `loader-logo.svg`
* `favicon.png`

[NOTE]
The favicon file must be in `.png` format with dimensions of 32x32 pixels.

[step-3]
=== Step 3: Commit changes to the repository

Run the following commands in the Git console for the registry repository:

[source,bash]
----
git add .
git commit -m "updated logos"
git push origin HEAD:refs/for/master
----

[step-4]
=== Step 4: Apply changes via Gerrit

Access the registry's Gerrit service and perform a `git merge` of the changes by applying the created Merge Request (MR) to the `master` version of the regulations.

[step-5]
=== Step 5: Wait for build completion

Wait for the successful completion of the *MASTER-Build-registry-regulation* job in the registry Jenkins.

[step-6]
=== Step 6: Verify changes

. Access the following portals:

* Officer portal;
* Citizen portal;
* Administrative Portal.

. Verify that the header logo, loader, and favicon images have been updated as per the files in the `master` branch of the repository.

== Interface behavior notes

* Updated logos and other images are automatically displayed across all pages of the user and administrative portals.
* All configurations are stored in the `master` branch of the repository and applied without requiring manual intervention or additional actions from portal users.
