@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

package "liquibase-core" {
class AbstractChange
class AbstractSqlGenerator<T>
class AbstractSqlStatement
class AddColumnChange
class CreateIndexChange
class CreateTableChange
}

package "extension.change-core" {
class DdmAbstractViewChange
class DdmAddColumnChange
class DdmCreateAnalyticsIndexChange
class DdmCreateAnalyticsViewChange
class DdmCreateCompositeEntityChange
class DdmCreateTableChange
class DdmCreateTypeChange
class DdmDistributeTableChange
class DdmDropAnalyticsViewChange
class DdmDropColumnChange
interface DdmArchiveAffectableChange << interface >>
}

package "extension.sqlgenerator-core" {
class DdmCreateAbstractViewGenerator
class DdmCreateDomainGenerator
class DdmCreateMany2ManyGenerator
class DdmCreateSimpleSearchConditionGenerator
}

package "extension.statement-core" {
class DdmCreateAbstractViewStatement
class DdmCreateDomainStatement
class DdmCreateMany2ManyStatement
}

AddColumnChange                                      -[#000082,plain]-^  AbstractChange
CreateIndexChange                                    -[#000082,plain]-^  AbstractChange                                      
CreateTableChange                                    -[#000082,plain]-^  AbstractChange                                      
DdmAbstractViewChange                                -[#000082,plain]-^  AbstractChange                                      
DdmAddColumnChange                                   -[#000082,plain]-^  AddColumnChange                                     
DdmAddColumnChange                                   -[#008200,dashed]-^  DdmArchiveAffectableChange                          
DdmCreateAbstractViewGenerator                       -[#000082,plain]-^  AbstractSqlGenerator                                
DdmCreateAbstractViewStatement                       -[#000082,plain]-^  AbstractSqlStatement                                
DdmCreateAnalyticsIndexChange                        -[#000082,plain]-^  CreateIndexChange                                   
DdmCreateAnalyticsViewChange                         -[#000082,plain]-^  DdmAbstractViewChange                               
DdmCreateCompositeEntityChange                       -[#000082,plain]-^  AbstractChange                                      
DdmCreateDomainGenerator                             -[#000082,plain]-^  AbstractSqlGenerator
DdmCreateDomainStatement                             -[#000082,plain]-^  AbstractSqlStatement                                
DdmCreateMany2ManyGenerator                          -[#000082,plain]-^  AbstractSqlGenerator
DdmCreateMany2ManyStatement                          -[#000082,plain]-^  AbstractSqlStatement                                
DdmCreateSimpleSearchConditionGenerator              -[#000082,plain]-^  AbstractSqlGenerator
DdmCreateTableChange                                 -[#000082,plain]-^  CreateTableChange
DdmCreateTypeChange                                  -[#000082,plain]-^  AbstractChange                                      
DdmDistributeTableChange                             -[#000082,plain]-^  AbstractChange
DdmDropAnalyticsViewChange                           -[#000082,plain]-^  AbstractChange
DdmDropColumnChange                                  -[#000082,plain]-^  AbstractChange
@enduml
