= Алгоритм виконання операцій з таблицями та полями в базі даних
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

[#delete-tables]
== Видалення таблиць

Крок I. Аналіз ::

. Визначити таблиці, які необхідно видалити (_включаючи історичні таблиці_).
. Визначити чи є в інших таблицях поля з *foreign keys*, що посилаються на таблиці, які необхідно видалити.
. Визначити *Search Conditions*, які створені для таблиць з перших двох пунктів.
. Визначити *Analytics Views*, в яких використовуються поля таблиць з перших двох пунктів.

Крок II. Видалення ::

Створити *changeSet*-и для:

* видалення *Analytics Views*;
* видалення *Search Conditions*;
* видалення таблиць та історичних таблиць (_для перших двох пунктів в першому кроці_).

Крок III. Додавання ::

Створити *changeSet*-и для:

* створення таблиць з яких видалили поля з foreign keys, що посилались на видалені таблиці;
* створення *Search Conditions* для таблиць, в яких видалили поля з *foreign keys*, що посилалися на таблиці, які видалили;
* створення *Analytics Views* для таблиць, в яких видалили поля з *foreign keys*, що посилалися на таблиці, які видалили.

[#add-tables]
== Додавання таблиць

Крок I. Аналіз ::

. Визначити таблиці, які необхідно додати.
. Визначити інші таблиці, що будуть посилатися на таблиці (_нові поля з **foreign keys**_), які необхідно додати.
. Визначити *Search Conditions*, які треба створити для нових таблиць та *Search Conditions*, в які треба додати поля з *foreign keys* на нові таблиці.
. Визначити *Analytics Views*, в яких будуть використовуватись поля нових таблиць та *Analytics Views*, в яких будуть використовуватись поля з *foreign keys* на нові таблиці.

Крок II. Видалення ::
Створити *changeSet*-и для:

* видалення наявних *Search Conditions*, в яких будуть використовуватись поля з *foreign keys* на нові таблиці (_якщо необхідні зміни в наявних **Search Conditions**_);
* видалення наявних *Analytics Views*, в яких будуть використовуватись поля з *foreign keys* на нові таблиці (_якщо необхідні зміни в наявних **Analytics Views**_).

Крок III. Додавання ::

Створити *changeSet*-и для:

* створення таблиць (_історичні таблиці створюються автоматично_);
* додавання полів з *foreign keys* на додані таблиці в наявні таблиці;
* створення *Search Conditions* для доданих таблиць та створення *Search Conditions* для таблиць, в які додали поля з *foreign keys* на додані таблиці;
* створення *Analytics Views* для доданих таблиць та створення *Analytics Views* для таблиць, в які додали поля з *foreign keys* на додані таблиці.

[#add-fields]
== Додавання полів в таблицях

Крок I. Аналіз ::

. Визначити таблиці, в які необхідно додати поля.
. Визначити інші таблиці, в яких додані поля будуть використані як *foreign keys*.
. Визначити *Search Conditions*, що створені для таблиць, в які необхідно додати поля, та *Search Conditions*, де додані поля будуть використані як *foreign keys*.
. Визначити *Analytics Views*, в яких використовуються поля таблиць, в які необхідно додати поля, та *Analytics Views*, в яких додані поля будуть використані як *foreign keys*.

Крок II. Видалення ::

Створити *changeSet*-и для:

* видалення *Search Conditions* для таблиць, в які будуть додані поля, та *Search Conditions*, в яких додані поля будуть використані як *foreign keys* (_якщо необхідні зміни в наявних_ **Search Conditions**_);
+
[source,xml]
----
<changeSet author="registry owner" id="drop search document_type">
    <ext:dropSearchCondition name="document_type"/>
</changeSet>
----

* видалення *Analytics Views* для таблиць, в яких будуть використовуватись додані поля та *Analytics Views*, в яких додані поля будуть використані як *foreign keys* (_якщо необхідні зміни в наявних **Analytics Views**_).
+
[source,xml]
----
<changeSet author="registry owner" id="drop report_table">
    <ext:dropAnalyticsView name="report_table"/>
</changeSet>
----

Крок III. Додавання ::

Створити *changeSet*-и для:

* додавання полів в таблиці;
+
[source,xml]
----
<changeSet id="add new columns to staff" author="registry owner">
    <ext:addColumn tableName="staff" ext:historyFlag="true">
        <column name="order_date" type="DATE" remarks="Дата наказу"/>
    </ext:addColumn>
</changeSet>
----

* додавання полів таблиць, в яких додані поля будуть використані як *foreign keys*;
+
[source,xml]
----
<changeSet id="add column" author="registry owner">
    <ext:addColumn tableName="address" ext:historyFlag="true">
        <column name="region_id" type="UUID" remarks="Місце проживання - область">
            <constraints nullable="true"
                         foreignKeyName="fk_region_id"
                         referencedTableName="katottg_dictionary"
                         referencedColumnNames="katottg_id"/>
        </column>
    </ext:addColumn>
</changeSet>
----
* створення *Search Conditions* для таблиць, в які додали поля, та *Search Conditions*, в яких додані поля будуть використані як *foreign keys* (_якщо необхідні зміни в наявних **Search Conditions**_);
+
[source,xml]
----
<changeSet author="registry owner" id="create SC edu-by-external-id view">
   <ext:createSearchCondition name="edu_by_external_id" limit="all">
       <ext:table name="edu">
           <ext:column name="edu_id"/>
…
           <ext:column name="edu_id_external" searchType="equal"/>
       </ext:table>
   </ext:createSearchCondition>
</changeSet>
----
* створення *Analytics Views* для таблиць, в яких будуть використовуватись додані поля, та *Analytics Views*, в яких додані поля будуть використані як *foreign keys* (_якщо необхідні зміни в наявних **Analytics Views**_).
+
[source,xml]
----
<changeSet author="registry_owner" id="full_expose_transaction table_v2">
   <ext:createAnalyticsView name="exposed_transaction_table_v2">
       <ext:table name="transaction" alias="transaction">
           <ext:column name="transaction_id"/>
           …
           <ext:column name="order_id"/>
       </ext:table>
   </ext:createAnalyticsView>
</changeSet>

----

[#delete-fields]
== Видалення полів в таблицях

IMPORTANT: Не можна видаляти поля таблиці, в яких зберігається *primary key*.

Крок I. Аналіз ::

. Визначити поля таблиць, які необхідно видалити.
. Визначити таблиці, в яких поля, що видаляються, використані як *foreign keys*.
. Визначити *Search Conditions*, які використовують поля цих таблиць, та *Search Conditions*, в яких ці поля використовуються як *foreign keys*.
. Визначити *Analytics Views*, в яких використовуються поля цих таблиць, та *Analytics Views*, в яких ці поля використані як *foreign keys*.

Крок II. Видалення ::

Створити *changeSet*-и для:

* видалення *Search Conditions* з полями таблиць, які необхідно видалити, та *Search Conditions*, в яких ці поля використані як *foreign keys*;
* видалення *Analytics Views* з полями таблиць, які необхідно видалити, та *Analytics Views*, в яких ці поля використані як *foreign keys*;
* видалення полів таблиць, в яких поля, що видаляються, використані як *foreign keys*;
* видалення полів таблиць.

Крок III. Додавання ::

Створити *changeSet*-и для:

* створення *Search Conditions* для таблиць, в яких видалили поля, та *Search Conditions*, в яких видалені поля використовувалися як *foreign keys*,
* створення *Analytics Views* для таблиць, в яких видалили поля, та *Analytics Views*, в яких видалені поля використовувалися як *foreign keys*.

[#change-field-format]
== Зміна формату полів у таблицях

Крок I. Аналіз ::
Визначити поля таблиць, в яких необхідно змінити формат.

Крок II. Змінення ::

Створити *changeSet*-и для:

* змінення форматів полів таблиць.
+
[source,xml]
----
<changeSet  author="registry owner" id="modifyDataType-example">
    <modifyDataType
        columnName="id"
        newDataType="int"
        tableName="person"/>
</changeSet>
----
+
IMPORTANT: При зміні формату полів не змінюється їх назва. Якщо немає блоків з логічного порівняння даних, то вносити зміни до *Analytics Views* та *Search Conditions* необов'язково. Якщо є блоки з логічним порівнянням даних, то треба вносити зміни до тих блоків (_видалити старі **Search Conditions**, **Analytics Views** та створити нові після зміни формату полів_). Інакше можливі помилки при виконанні збірки регламенту.