= Налаштування доступу до API-представлень реєстру
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

Окрім надання доступу до реєстру для інших реєстрів або зовнішніх систем в адміністративній панелі Control Plane (_див. xref:admin:registry-management/control-plane-registry-grant-access.adoc[]_), адміністратор реєстру має відкрити доступ до представлень (view) та REST API-ендпоінтів, які згенеровані на базі цих представлень, на рівні моделі даних.

Налаштування доступу до REST API представлень (view) реєстру відбувається за допомогою спеціальних атрибутів доступу на рівні моделі даних Liquibase. Це дозволяє відкрити доступ до API реєстру, що створюються із відповідних представлень, іншим реєстрам на Платформі або зовнішнім системам.

Для цього використовується спеціальний тег *`<exposeSearchCondition>`*.

TIP: Опис тегу `<exposeSearchCondition>` ви можете також переглянути на сторінці xref:data-modeling/data/physical-model/liquibase-ddm-ext.adoc[].

== Основні атрибути

Тег приймає наступні атрибути: ::
+
.Атрибути тегу <exposeSearchCondition>
[%header,cols="3*"]
|===
| Атрибут | Призначення | Значення за замовчуванням

| `name` | Назва критерію пошуку | Не вказано
| `platform` | Надає доступ до представлень та REST API реєстру для іншого реєстру на Платформі | `false`
| `externalSystem` | Надає доступ до представлень та REST API реєстру для зовнішньої системи | `false`
| `trembita` | Надає доступ до представлень реєстру для сервісів-учасників СЕВ ДЕІР через інтерфейс ШБО "Трембіта" за протоколом SOAP | `false`
| `publicAccess` | Визначає, чи має бути публічний доступ до пошукового критерію/представлення | `false`
|===

== Приклади

._Приклад XML-схеми з атрибутами platform, externalSystem та trembita_
[source, XML]
----
<ext:exposeSearchCondition name="exampleViewName" platform="true" externalSystem="true" trembita="false"/>
----

._Приклад XML-схеми з атрибутом publicAccess_
[source, XML]
----
<exposeSearchCondition publicAccess="true" name="vpo_person_type_contains_name_public_test"/>
----

== Рекомендації

* Усі атрибути за замовчуванням мають значення `false`. Врахуйте це, коли працюєте з тегом `<exposeSearchCondition>`.
* Переконайтеся, що атрибут `name` завжди вказаний, оскільки він є обов'язковим для ідентифікації критерію пошуку.

