openapi: 3.0.3
info:
  title: Business process web service gateway API
  description: This document describes REST API of 'Business process web service gateway'
  version: "1.0"
tags:
- name: bp-webservice-gateway-api
  description: Business process web service gateway Rest API
paths:
  /api/start-bp:
    post:
      tags:
      - bp-webservice-gateway-api
      summary: Start process instance
      description: |-
        ### Endpoint purpose:
         This endpoint allows you to start a business process instance based on the provided _businessProcessDefinitionKey_ in request body.
        ### Business process start validation:
         This endpoint requires valid _businessProcessDefinitionKey_ and _startVariables_. If no business process definition found or required parameters are missing, then _422_ response code returned.
      operationId: startBp
      parameters:
      - name: X-Access-Token
        in: header
        description: Token used for endpoint security
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartBpRestRequest'
            example:
              businessProcessDefinitionKey: my-business-process
              startVariables:
                variable1: value1
                variable2: value2
                variable3: null
        required: true
      responses:
        "200":
          description: Returns result variable of business process
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartBpResponse'
              example:
                resultVariables:
                  return_var_1: return_value_1
                  return_var_2: null
        "404":
          description: Business process definition not found in trembita.process_definitions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemErrorDto'
        "422":
          description: Business process definition cannot be started or missing required
            start variable for the business process
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemErrorDto'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SystemErrorDto'
components:
  schemas:
    StartBpRestRequest:
      type: object
      properties:
        businessProcessDefinitionKey:
          type: string
        startVariables:
          type: object
          additionalProperties:
            type: object
    StartBpResponse:
      required:
      - resultVariables
      type: object
      properties:
        resultVariables:
          type: object
          additionalProperties:
            type: object
    SystemErrorDto:
      type: object
      properties:
        traceId:
          type: string
        code:
          type: string
        message:
          type: string
        localizedMessage:
          type: string
