@startuml
actor Тестувальник

participant "Кластер стейджингу" as Stage
participant "Встановити кластер" as Install
participant "Оновити кластер" as Update
participant "Пре-продакшен кластер" as PreProd
participant "Продакшен кластер" as Prod

Tester -> Stage: Виконати модульне тестування
Tester -> Stage: Виконати інтеграційне тестування
Tester -> Stage: Виконати візуальне тестування
Tester -> Stage:  Виконати аналіз Sonar

activate Stage
Stage -> Install: Виконати регресійне тестування
Stage -> Install: Виконати інтеграційне тестування
Stage -> Install: Виконати системне тестування
Stage -> Install: Виконати візуальне тестування
Stage -> Install: Встановити ручне тестування

activate Install
Install -> Update: Виконати регресійне тестування
Install -> Update: Виконати інтеграційне тестування
Install -> Update: Виконати системне тестування
Install -> Update: Виконати візуальне тестування
Install -> Update: Оновити ручне тестування

activate Update
Update -> PreProd: Виконати тестування на прийняття

activate PreProd
PreProd -> Prod: Виконати тестування на прийняття

activate Prod
Prod -> Prod: Провести тести на прийомку з представником клієнта

deactivate Стейджинг
deactivate Встановлення
deactivate Оновлення
deactivate ПреПродакшен
deactivate Продавшен

@enduml
