= Архітектурний процес

== Розробка дизайну

image::architecture-workspace/architecture-process.svg[]

== Декомпозиція активностей розробки дизайну

* Підготовка до мітингів та обговорення вимог з МЦ
* Обговорення / узгодження / формування вимог з BA
* Аналіз поточного стану системи / формування дизайну / скетчінг
* Документування технічного дизайну для реалізації епіку у вигляді "feature design transition" / проміжні артифакти для команди розробки
* Аналіз та оцінка ризиків безпеки змін в рамках реалізації рішення згідно дизайну
* Узгодження об'єму виконання епіку / дизайну з BA/TL/DM та внесення коректив до "transition" дизайну
* Ведення робіт по Proof-of-Concepts (у разі необхідності)
* Внесення змін до основного розділу Технічної Документації для відображення цілісного стану архітектури системи на базі обраного "transition"-дизайну
* Підготовка високорівневого плану реалізації епіку для спрощення декомпозиції TL
* Презентація технічного дизайну на грумінгах/арх сесії/плануваннях
* Підтримка/супервіжн команди розробки у процесі реалізації
* Ревью реалізації епіку по завершенню для перевірки відповідності дизайну
* Внесення коректив у розділ Технічної Документації згідно фактичної реалізації

== Принципи ведення документації

* Цілісне відображення актуального стану архітектури рішення для обраної версії
* Відсутність дублювання інформації як у межах _Antora_ документації та і з іншими базами знань (_Confluence_)
* Узгоджене використання єдиної термінології, визначеної у глосарії
* Єдиний підхід до структурування документації за принципом _top-down_ для рішення в цілому, підсистем та окремих компонент
* Єдиний підхід до структурування статей розділу дизайну підсистем та окремих компонентів
* Єдиний підхід до створення архітектурних діаграм (стиль, гамма, легенда, іменування, тощо.)
* Єдиний підхід до формування та структурування контенту статей опису "transition"-дизайну