[glossary]
== Глосарій та Акроніми Платформи

[glossary]
API Платформи реєстрів:: <<API-Фабрики-даних>>
[[API-Фабрики-даних]]API Фабрики даних:: Програмний інтерфейс фабрики даних, доступний для інших компонентів платформи, що надає набор функцій для взаємодії з даними реєстру.
BPMN (Business Process Model and Notation):: Нотація і модель бізнес-процесів — система умовних позначень для моделювання бізнес-процесів
CC:: competency center
[[Control-Plane]]Control Plane:: Сукупніть компонентів платформи, що забезпечує спрощення керування центральними компонентами платформи, дозволяє керувати реєстрами та агрегує посиллання до всіх WEB API центральних компонентів.
DMN (Decision Model and Notation):: Нотація для моделювання процесів прийняття рішень.
GitOps-підхід:: Спосіб реалізації безперервного розгортання для нативних хмарних додатків. Основна ідея GitOps полягає в тому що будь-які зміни у конфігурації кластера OpenShift, компонентів кластера та компонентів Платформи відбуваються через внесення змін до конфігурації відповідних компонентів у git-гілках цих компонентів.
Low-code:: Підхід до створення, налаштування та модифікації системи та додатків, який практично не вимагає написання програмного коду. В контексті Платформи це компоненти за допомогою яких цей підхід реалізується.
OpenShift:: Система автоматичного розгортання, масштабування та управління застосунками у контейнерах.
RBAC:: Керування доступом на основі ролей. Привілеї не призначаються користувачам безпосередньо а отримуються ними тільки через свою роль (або ролі), управління індивідуальними правами користувача по суті зводиться до призначення йому ролей
[[UI-форма]]UI-форма:: Частина регламенту реєстру 
Автентифікація::
Авторизація::
Адміністративна послуга:: Послуга що передбачає зміну певного статусу чи інших даних в реєстрі. На Платформі це бізнес-процес, реалізований на рівні окремого реєстру, результатом якого є внесення змін до даних реєстру.
Аналітична БД:: База даних яка обслуговує аналітичні інструменти, зокрема Redash. Отримує данні через логічну реплікацію з операційної бази даних. Доступна лише на читання.
[[Аналітичний-звіт]]Аналітичні звіти:: Попередньо налаштовані загальні статистичні дані за реєстром. Побудовані за допомогою сервісу аналітичної звітності Redash. Можуть містити графіки, таблиці, картки показників та примітки щодо ефективності підприємчого процесу.
Бізнес-Процес:: Набір операцій спрямованих на досягнення певного результату шляхом обробки даних.
Версія-кандидат регламенту реєстру:: Логічне представлення стану мастер-версії після застосування змін, сформованих в рамках відповідного запиту на внесення змін.
Витяг:: Документ згенерований в рамках надання інформаційних послуг через бізнес-процеси, який може бути завантажений користувачем, який замовив інформаційну послугу. Представлений окремим шаблоном на рівні регламенту реєстру.
Відкриті дані:: Публічна інформація у форматі, що дозволяє її автоматизоване оброблення електронними засобами, вільний та безоплатний доступ до неї, а також її подальше використання
Група реєстрів:: Реєстри що належать одному власнику та є спорідненими.
Дані реєстру:: Інформація що зберігається в базі даних реєстру
Дашборд:: <<Аналітичний-звіт>>
ДРФО:: Державний реєстр фізичних осіб - платників податків. Використовується у сенсі "код ДРФО"
Електронний підпис:: в рамках цього документу це КЕП, УЕП, ЕЦП фізичної чи юридичної особи або електронна печатка юридичної особи. Використання КЕП, УЕП в залежності від ситуації залежить від чинних вимог законів та законодавства
ЕЦП (Електронний цифровий підпис):: Електронний цифровий підпис.
ЄДРПОУ:: 
Запит на внесення змін:: Логічне представлення сукупності змін відносно поточної _мастер-версії_ регламенту, до якого застосовуються перевірки цілісності, якості та інспекції перед безпосереднім застосуванням до _мастер-версії_.
Інтерфейс адмін-консолі:: <<Control-Plane>>
Інформаційна панель:: <<Аналітичний-звіт>>
Інформаційна послуга::  бізнес-процес, реалізований на рівні окремого реєстру, результатом якого є отримання даних реєстру у визначеній формі. Передбачає підтвердження того чи іншого статусу в реєстрі. Результатом "Послуги" буде витяг, або підтвердження прав.
Кабінет адміністратора регламентів (Адмін портал):: клієнтський веб-додаток для адміністрування реєстрів, наразі ми маємо функціонал моделювання UI форм для бізнес-процесів, але в майбутньому планується розширення функціоналу./ Інтерфейс який дозволяє виконувати всю необхідну конфігурацію регламенту реєстру без володіння глибокими уміннями програмування.
Кабінет користувача:: citizen-portal та officer-portal
Кабінет отримувача послуг:: citizen-portal
Кабінет посадової особи:: officer-portal
КЕП:: кваліфікований електронний підпис
Керування кластером (платформою):: абстракція в рамках Control Plane, що дозволяє керувати центральними компонентами системи
Комплексна система захисту інформації (КСЗІ):: сукупність організаційних і інженерних мір та програмно-апаратних засобів, що забезпечують захист інформації в системі.
Компоненти реєстру:: *Реєстрові* компоненти, що встановлюється окремо для кожного реєстру
Конфігурація реєстру:: values.yaml, control plane gitops
Конфіденційні дані:: с авторизацией
Мастер-версія регламенту:: Версія регламенту, розгорнута на окремому екземпляри реєстру, яка відповідає вимогам цілісності, стабільності, якості та сумісності відносно останньої версії, розгорнутої на промисловому оточенні.
Модель даних::
Об’єкти (Приналежність даних)::  будь-яка сутність, якою володіє суб’єкт
Онбоардинг громадян(отримувач послуг):: процес орієнтований на створення всіх необхідних записів у БД для взаємодії користувача з реєстром (профіль користувача, налаштування, призначення ролі користувача)
Операційна БД:: база даних яка обслуговує додатки та сервіси реєстру
Операційне сховище бізнес-процесів::
Отримувач послуг:: системна роль; особа отримує послуги від посадової особи/Системи. Ця роль може призначатися фізичній особі, представнику ФОП або юридичної особи.
Пакетне завантаження (імпорт користувачив)::
Первинна автентифікації / авто-реєстрації громадян(отримувач послуг)::
Персональні дані:: відомості чи сукупність відомостей про фізичну особу, яка ідентифікована або може бути конкретно ідентифікована;
Платформа (IC «Платформа»):: розгорнута система (ІСР) в хмарі, яка надає органам влади можливість створювати та в рамках повноважень вести реєстри за моделлю SaaS “Реєстр як сервіс”). В тому числі передбачити розгортання платформи як в хмарі, так і на базі власного ЦОД. Та розгортання платформи як для одного реєстру, так і для групи реєстрів.
Платформа ведення реєстрів:: OpenShift кластер зі встановленими компонентами необхідні для створення та ведення реєстрів.
Платформа даних:: Фабрика даних
Платформні ключі цифрового підпису::
Посадова особа:: системна роль; посадова особа – представник державного органу, що взаємодіє із Реєстром у рамках виконання своїх службових обов'язків
Послуга:: один або декілька Бізнес-Процесів в реєстрі спрямовані на опрацювання запиту особи.
Публічно доступні дані:: без авторизации
Регламент/правила реєстру::  це набір Моделей даних, бізнес-процесів, Налаштувань, за якими Реєстр буде реалізовувати свої функції.
Реєстр:: спеціалізований інформаційний ресурс, призначений для зберігання та обробки юридично важливої інформації про людей, їх права та обов'язки, а також майно та ресурси.
Реєстровий пайплайн:: выполняет применение конфигурации реестра
Реєстрові  ключі цифрового підпису:: 
Рейт-ліміти:: обмеження кількості запитів від одного користувача.
РНОКПП:: Реєстраційний номер облікової картки платника податків
Розгортання регламенту реєстру::
Ролі регламенту::
Роль користувача:: Системні ролі та ролі регламенту, які призначені користувачу. 
СЕВДЕІР / Трембіта:: Система електронної взаємодії державних електронних інформаційних ресурсів.
Суб’єкти (Приналежність даних):: будь-яка фізична або юридична особа, що має право власності над об’єктом.
Сховище історичних даних бізнес-процесів::
Сховище проміжних даних бізнес-процесів::
Фабрика даних::
Фізичні особи-підприємці та їх представники::
Фізичні особи::
Форма:: <<UI-форма>>
Центральні компоненти:: компоненти системи, що спільно використуваються усіма реєстрами та існують в єдиному екземплярі на кластері.
Цифрові документи::
ЦОД:: Центр обробки даних (Data center).
Чутливі дані:: див. Персональні дані // прояснить с Игорем и Богданом
ШБО:: Шлюз Безпечного Обміну
Юридичні особи та їх представник::


//“Підпорядкований” реєстр (стосовно сутності):: це реєстр який ключову інформацію по сутності отримує з іншого (Майстер) реєстру. В залежності від сутності по якій йде мова реєстр може виступати як Майстер, так і підпорядкований. Все залежить від моделі обміну даних, що буде побудована. 
//Атрибут/поле сутності:: значення в реєстрі, що описує якусь властивість сутності, важливу для подальшого використання
//Інформацією з обмеженим доступом:: конфіденційна, таємна та службова інформація 
//Інформаційна система керування реєстром (ІСКР):: це набір інструментів (софт), що будуть забезпечувати необхідний функціонал Реєстру, тобто спеціалізоване програмне забезпечення призначене для забезпечення діяльності реєстру, ведення його налаштування захисту та обміну інформацією з іншими системами.
//Інформаційна система реєстру  (ІСР):: система до складу якої входять дані, софт, хостинг засоби передачі інформації та процеси пов’язані із реєстром
//Майстер-реєстр (стосовно сутності):: це головний реєстр для сутності, першоджерело. Усі зміни цієї сутності повинні відбуватись у Майстер-реєстрі. Інші реєстри повинні отримувати інформацію про сутності, а також інформацію про зміни з відповідного Майстер-реєстру
//Реєстр оперативного рівня:: той, який призначений для вузькоспеціалізованого використання обмеженим переліком суб'єктів в межах наданих їм законодавством повноважень; як правило, не є майстер-реєстром для інших реєстрів.
//Реєстр стратегічного рівня:: той, який призначений для загального користування усіма (найширшим переліком) суб'єктами інформаційних відносин в межах наданих їм повноважень та (чи) прав.
//Реєстр тактичного рівня:: той, який призначений для спеціалізованого використання обмеженим переліком суб'єктів в рамках наданих законодавством їм повноважень.
//Рівні ієрархії реєстрів в системі реєстрів:: стратегічний, тактичний, оперативний.
//Система керування реєстром (СКР):: комплекс організаційних, юридичних, інформаційних, технічних та технологічних ресурсів, призначених для забезпечення функціонування реєстру в залежності від його призначення. 
//Система реєстрів:: ієрархічно побудована сукупність співзалежних державних електронних реєстрів, що охоплюють всі аспекти цивільного життя та функціонування держави.
//Стейкхолдер:: зацікавлена ​​особа. Стосовно до інформаційної системи:: особа (група осіб), що прямо або побічно реалізує в системі свій інтерес, або особа (група осіб), на яку система впливає.
//Хеш-структура:: сукупність даних, що однозначно характеризують набір реєстрових даних щодо об’єкта, їх зв’язок з іншими даними в цьому та/ або інших реєстрах та їх стан до реєстраційних дій, а також зміни реєстрових даних, що відбулися внаслідок реєстраційних дій, структурована та автентифікована згідно із законом, згідно з яким створено відповідний реєстр; підлягає показу в документах, що створюються під час ведення реєстрів, та безстроковому зберіганню у публічному розподіленому реєстрі разом з ідентифікатором об’єкта і використовується для відстеження змін у відповідних наборах реєстрових даних та їх відновлення (у разі несанкціонованої зміни або пошкодження) у відповідних реєстрах.
//RaaS:: registry-as-a-service
//Адміністратор безпеки::
//Адміністратор доступу::
//Адміністратор платформи:: створення та послідуюче налаштування реєстрів _Адміністративний інтерфейс управління платформою_ (_канали зв'язків, тощо._)
//Адміністратор регламенту:: створення шаблонів повідомлень, моделювання бізнес-процесів з кроками відправлення повідомлень користувачам
//Адміністратор реєстру:: налаштування реєстру через _Адміністративний інтерфейс управління платформою_ (_канали зв'язків, тощо._)
//Геосервер:: комонент реєстру який ...
//Ендпоінт:: зовнішня точка доступа
//Інфраструктура::
//Кабінет адміністратора::
//Користувач::
//Моделювальник бізнес-процесів:: адміністратор реєстру
//Моделювальник даних:: адміністратор реєстру
//Тенант оточення::