openapi: 3.0.0
paths:
  /api/form-submissions/{formKey}/validate:
    post:
      operationId: FormSubmissionsController_validate
      summary: Validate form data against scheme
      description: |-
        ### Endpoint purpose:
         This endpoint allows you to validate form data against a specified UI-form scheme. It accepts the form key in the URL, user authentication, and the form schema in the request body.
        ### Validation:
         This endpoint requires a valid _formKey_ in the URL, which is the unique identifier of the UI-form scheme. If the provided form key does not exist, a _404 Not Found_ status code is returned. The endpoint also validates the form data against the specified UI-form scheme. Validation includes checking for required fields and the overall structure of the submitted data. In case of validation errors, the endpoint returns _422 Unprocessable Entity_. The response body includes details about the errors found during validation.
      parameters:
        - &ref_0
          name: X-Request-Id
          in: header
          required: false
          schema:
            type: string
        - &ref_1
          name: X-B3-SpanId
          in: header
          required: false
          schema:
            type: string
        - &ref_2
          name: X-B3-TraceId
          in: header
          required: false
          schema:
            type: string
        - name: X-Access-Token
          required: true
          in: header
          description: Token used for endpoint security
          schema:
            type: string
        - name: formKey
          required: true
          in: path
          description: Unique identifier of UI-form scheme
          examples:
            "1":
              value: "1"
            user:
              value: user
            admin:
              value: admin
            edit-personprofile-firstbpmn:
              value: edit-personprofile-firstbpmn
            edit-personprofile-secondbpmn:
              value: edit-personprofile-secondbpmn
            add-startform:
              value: add-startform
            add-lab-file:
              value: add-lab-file
            sign-lab-file:
              value: sign-lab-file
            edit-lab-file:
              value: edit-lab-file
            sign-edited-lab-file:
              value: sign-edited-lab-file
            mdtuddm-12887:
              value: mdtuddm-12887
            mdtuddm-11573:
              value: mdtuddm-11573
            mdtuddm-16614-complex-validation:
              value: mdtuddm-16614-complex-validation
            day-and-datetime:
              value: day-and-datetime
            test-password:
              value: test-password
            form-with-all-fields-for-validation:
              value: form-with-all-fields-for-validation
            auto-form-with-files-upload-validation-soma:
              value: auto-form-with-files-upload-validation-soma
            submission-conversions-day:
              value: submission-conversions-day
            submission-conversions-phone:
              value: submission-conversions-phone
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FormSchemaDTO"
      responses:
        "200":
          description: OK
        "400":
          description: Bad request
        "401":
          description: Authentication error (X-Access-Token missing)
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  message:
                    type: string
        "404":
          description: Form scheme not found
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  message:
                    type: string
        "422":
          description: Failed form data validation against UI-form scheme
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  code:
                    type: string
                    example: VALIDATION_ERROR
                  details:
                    type: object
                    properties:
                      errors:
                        type: array
                        items:
                          properties:
                            value:
                              type: string
                              example: '"null"'
                            field:
                              type: string
                              example: entities
                            message:
                              type: string
                              example: must not be null
                        example:
                          - value: "null"
                            field: entities
                            message: must not be null
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  message:
                    type: string
      tags: &ref_3
        - Form submission validation
  /api/form-submissions/{formKey}/fields/{fieldKey}/validate:
    post:
      operationId: FormSubmissionsController_validateField
      summary: Validate form file field value
      description: |-
        ### Endpoint purpose:
         This endpoint allows to validate a specific file field against a UI form schema.
        ### Validation:
         This endpoint provides validation of file field by size, content type and validation for existance in form scheme.
      parameters:
        - *ref_0
        - *ref_1
        - *ref_2
        - name: X-Access-Token
          required: true
          in: header
          description: Token used for endpoint security
          schema:
            type: string
        - name: formKey
          required: true
          in: path
          description: Unique identifier of UI-form scheme
          examples:
            "1":
              value: "1"
            user:
              value: user
            admin:
              value: admin
            edit-personprofile-firstbpmn:
              value: edit-personprofile-firstbpmn
            edit-personprofile-secondbpmn:
              value: edit-personprofile-secondbpmn
            add-startform:
              value: add-startform
            add-lab-file:
              value: add-lab-file
            sign-lab-file:
              value: sign-lab-file
            edit-lab-file:
              value: edit-lab-file
            sign-edited-lab-file:
              value: sign-edited-lab-file
            mdtuddm-12887:
              value: mdtuddm-12887
            mdtuddm-11573:
              value: mdtuddm-11573
            mdtuddm-16614-complex-validation:
              value: mdtuddm-16614-complex-validation
            day-and-datetime:
              value: day-and-datetime
            test-password:
              value: test-password
            form-with-all-fields-for-validation:
              value: form-with-all-fields-for-validation
            auto-form-with-files-upload-validation-soma:
              value: auto-form-with-files-upload-validation-soma
            submission-conversions-day:
              value: submission-conversions-day
            submission-conversions-phone:
              value: submission-conversions-phone
          schema:
            type: string
        - name: fieldKey
          required: true
          in: path
          description: Unique identifier of field within UI-form
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FormFieldValidationDTO"
      responses:
        "200":
          description: OK with return result
          content:
            application/json:
              schema:
                properties:
                  isValid:
                    type: boolean
                    example: true
        "400":
          description: Bad request
        "401":
          description: Authentication error (X-Access-Token missing)
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  message:
                    type: string
        "404":
          description: Form scheme not found by provided {form-key}
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  message:
                    type: string
        "422":
          description: Failed form data validation against UI-form scheme
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  code:
                    type: string
                    example: VALIDATION_ERROR
                  details:
                    type: object
                    properties:
                      errors:
                        type: array
                        items:
                          properties:
                            field:
                              type: string
                              example: entities
                            message:
                              type: string
                              example: must not be null
                        example:
                          - field: entities
                            message: must not be null
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  message:
                    type: string
        "501":
          description: Not Implemented
      tags: *ref_3
  /api/form-submissions/{formKey}/fields/check:
    post:
      operationId: FormSubmissionsController_checkFields
      summary: Check form fields for existance
      description: |-
        ### Endpoint purpose:
         This endpoint allows to check list of form firlds for existance.
        ### Validation:
         Endpoint retrieves form scheme by _formKey_ and checks for existance provided fields in request body, returns _422_ status code if no such fields.
      parameters:
        - *ref_0
        - *ref_1
        - *ref_2
        - name: X-Access-Token
          required: true
          in: header
          description: Token used for endpoint security
          schema:
            type: string
        - name: formKey
          required: true
          in: path
          description: Unique identifier of UI-form scheme
          examples:
            "1":
              value: "1"
            user:
              value: user
            admin:
              value: admin
            edit-personprofile-firstbpmn:
              value: edit-personprofile-firstbpmn
            edit-personprofile-secondbpmn:
              value: edit-personprofile-secondbpmn
            add-startform:
              value: add-startform
            add-lab-file:
              value: add-lab-file
            sign-lab-file:
              value: sign-lab-file
            edit-lab-file:
              value: edit-lab-file
            sign-edited-lab-file:
              value: sign-edited-lab-file
            mdtuddm-12887:
              value: mdtuddm-12887
            mdtuddm-11573:
              value: mdtuddm-11573
            mdtuddm-16614-complex-validation:
              value: mdtuddm-16614-complex-validation
            day-and-datetime:
              value: day-and-datetime
            test-password:
              value: test-password
            form-with-all-fields-for-validation:
              value: form-with-all-fields-for-validation
            auto-form-with-files-upload-validation-soma:
              value: auto-form-with-files-upload-validation-soma
            submission-conversions-day:
              value: submission-conversions-day
            submission-conversions-phone:
              value: submission-conversions-phone
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FormFieldsCheckDTO"
      responses:
        "200":
          description: OK with reurn result
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: number
                    example: 200
                  fields:
                    type: object
                    example:
                      name: true
                      email: true
        "422":
          description: Failed form data validation against UI-form scheme
          content:
            application/json:
              schema:
                properties:
                  traceId:
                    type: string
                    example: 6bf6c1c1d713ec2f
                  code:
                    type: string
                    example: VALIDATION_ERROR
                  details:
                    type: object
                    properties:
                      errors:
                        type: array
                        items:
                          properties:
                            field:
                              type: string
                              example: entities
                            message:
                              type: string
                              example: must not be null
                        example:
                          - field: entities
                            message: must not be null
      tags: *ref_3
info:
  title: Form submission validation API
  description: ""
  version: "1.0"
  contact: {}
tags: []
servers: []
components:
  schemas:
    FormSchemaDTO:
      type: object
      properties:
        data:
          type: object
          example:
            formField1: value1
            formField2: value2
        processInstanceId:
          type: string
          example: d5a40376-6360-11ee-88e8-0a580a81041b
      required:
        - data
    FormFieldValidationDTO:
      type: object
      properties:
        fileName:
          type: string
          example: file.csv
        contentType:
          type: string
          example: text/csv
        size:
          type: number
          example: 10
      required:
        - fileName
        - contentType
        - size
    FormFieldsCheckDTO:
      type: object
      properties:
        fields:
          description: List of form fields for verification
          example:
            - name
            - email
          type: array
          items:
            type: string
      required:
        - fields
