openapi: 3.0.1
info:
  title: Platform-gateway rest API
  description: This document describes Rest API of 'Platform-gateway'
  version: "1.0"
tags:
  - name: platform-gateway-rest-api
    description: Platform gateway rest API
paths:
  /data-factory/{registry}/**:
    get:
      tags:
        - platform-gateway-rest-api
      summary: Access data from the data factory service
      description: |-
        ### Endpoint purpose:
          Retrieves authentication information from Vault, obtains a token from Keycloak based on this authentication information, replaces the existing token in the request header with the new token, passes the request further down the filter chain for processing..
      parameters:
        - in: path
          name: registry
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
        '404':
          description: Resource not found
        '500':
          description: Internal server error

  /bp-gateway/{registry}/**:
    post:
      tags:
        - platform-gateway-rest-api
      summary: Send data to the bp-gateway service
      description: |-
        ### Endpoint purpose:
          The purpose of this filter is to dynamically adjust the URL routing based on the target registry extracted from the request. It enables routing to different destinations or services in a Kubernetes environment by manipulating the route information in the request.
      parameters:
        - in: path
          name: registry
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: string
                  description: Data to be sent to bp-gateway
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request
        '500':
          description: Internal server error

  /api/public/data-factory/**:
    get:
      tags:
        - platform-gateway-rest-api
      summary: Access public data from the data factory service
      description: |-
        ### Endpoint purpose:
         This filter is responsible for adding basic authentication headers to incoming requests based on the configuration provided in the basic authentication (based on login/password). It's used to protect certain routes or resources by ensuring that the client provides valid basic authentication credentials..
      responses:
        '200':
          description: Successful response
        '404':
          description: Resource not found
        '500':
          description: Internal server error