@startuml
skinparam responseMessageBelowArrow true

participant "Web клієнт" as client order 1
participant "Модуль роботи\nз версіями" as versionModule order 2
participant "Модуль роботи\nз Gerrit" as gerritModule order 3
participant "Модуль роботи\nз Git" as gitModule order 4

title Створення версії-кандидата регламенту

client-> versionModule: запит на створення версії-кандидата
activate versionModule
  versionModule -> gerritModule: створити новий\nchange request
  activate gerritModule
    versionModule <-- gerritModule: ідентифікатор\nнового change request
  deactivate gerritModule

  versionModule -> gerritModule: отримати інформацію\nпро change request за\nідентифікатором
  activate gerritModule
    versionModule <-- gerritModule: інформація про\nновий change request
  deactivate gerritModule

  versionModule -> gitModule: ініціювати клонування репозиторію\nдля нової створеної версії-кандидата
  activate gitModule
  versionModule <-- gitModule

  client <-- versionModule: інформація про нову\nстворену версію-кандидата
  deactivate versionModule

  gitModule -> gitModule: завершити клонування\nрепозиторію
@enduml