@startuml
skinparam responseMessageBelowArrow true

participant "Web клієнт" as client order 1
participant "Модуль роботи\nз версіями" as versionModule order 2
participant "Модуль роботи\nз Gerrit" as gerritModule order 3

title Отримання інформації про версію-кандидат регламенту

client-> versionModule: запит на отримання інформації\nпро версію-кандидата
activate versionModule
  versionModule -> gerritModule: отримати інформацію про\nchange request за ідентифікатором
  activate gerritModule

    alt версії-кандидата не існує
      versionModule <-- gerritModule: помилка отримання інформації
      client <-- versionModule: помилка зі статусом\n404 Not Found
    end
    versionModule <-- gerritModule: інформацію про change request
  deactivate gerritModule

  client <-- versionModule: інформація про версію-кандидата
deactivate versionModule
@enduml