@startuml
skinparam responseMessageBelowArrow true

participant "Web клієнт" as client order 1
participant "Модуль роботи\nз версіями" as versionModule order 2
participant "Модуль роботи\nз Gerrit" as gerritModule order 3

title Отримання списку всіх версій-кандидатів регламенту

client-> versionModule: запит на отримання\nсписку версій-кандидатів
activate versionModule
  versionModule -> gerritModule: отримати список всіх відкритих\n(не застосованих) change request
  activate gerritModule
    versionModule <-- gerritModule: список відкритих change request
  deactivate gerritModule

  client <-- versionModule: список версій-кандидатів
deactivate versionModule
@enduml