= Підсистема міжреєстрових інтеграцій

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Підсистема, призначення якої є забезпечення інтероперабельності платформи шляхом налаштування можливості надавати доступ до бізнес-процесів та API читання даних, а також читати данні та викликати бізнес-процеси в інших реєстрах.

== Функції підсистеми

* Надання API для виклику бізнес-процесів реєстру сторонніми для реєстру системами.
* Надання доступу іншим реєстрам або системам до окремих запитів читання _Підсистеми управління даними реєстру_.
* Маршрутизація запитів до зовнішніх реєстрів до яких було надано доступ.

== Технічний дизайн підсистеми

image::arch:architecture/registry/operational/cross-registry-integrations/cross-registry-integration-context.svg[]

В рамках цієї підсистеми виникає взаємодія між двома реєстрами розгорнутими на одній платформі, що створює звʼязок реєстр джерело даних та реєстр споживач даних.

Реєстр джерело даних - реєстр тримач даних який дозволяє операції читання цих даних за допомогою окремих пошукових запитів.

Реєстр споживач даних - реєстр якому було надано доступ до пошукових запитів _реєстру джерела даних_

Ключовий аспект який дозволяє таку взаємодію це створення сервісного користувача в реєстрі джерелі для реєстру споживача даних та використання його при здійсненні запитів.
Отримання облікових даних сервісного користувача та операція автентифікації здійснюється _API-шлюзом міжреєстрової взаємодії_ розгорнутим в реєстрі споживачі даних.
Сам _API-шлюз міжреєстрової взаємодії_ доступний для автентифікованих користувачів реєстру споживача даних.

Окремим випадком є надання доступу до даних сторонній системі споживачу даних. В даному сценарії створюється окремий сервісний користувач, а його облікові дані передаються адміністраторам системи тоді автентифікація і обмін токенів має відбуватись безпосередньо сторонньою системою.

== Складові підсистеми

|===
|Назва компоненти|Представлення в реєстрі|Тип додатка|Походження|Призначення

|_API-шлюз міжреєстрової взаємодії_
|`platform-gateway-deployment`
|backend
|origin
|-

|_Сервіс синхронного управління даними реєстру для міжреєстрової взаємодії_
|`registry-rest-api-ext`
|backend
|origin
|-
|===