= Налаштування атрибутів доступу до REST API-представлень реєстру
//:toc:
:toc-title: ЗМІСТ
:experimental:
:example-caption: Приклад
:important-caption: ВАЖЛИВО
:note-caption: ПРИМІТКА
:tip-caption: ПІДКАЗКА
:warning-caption: ПОПЕРЕДЖЕННЯ
:caution-caption: УВАГА
:example-caption: Example
:figure-caption: Figure
:table-caption: Table
:appendix-caption: Appendix
:toclevels: 5
//:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

== Загальний опис

Окрім надання доступу до реєстру для інших реєстрів або зовнішніх систем в адміністративній панелі Control Plane (_див. xref:admin:registry-management/control-plane-registry-grant-access.adoc[]_), адміністратор реєстру має відкрити доступ до представлень (view) та REST API-ендпоінтів, які згенеровані на базі цих представлень, на рівні моделі даних.

Налаштування доступу до REST API представлень (view) реєстру відбувається за допомогою спеціальних атрибутів доступу на рівні моделі даних Liquibase. Це дозволяє відкрити доступ до API реєстру, що створюються із відповідних представлень, іншим реєстрам на Платформі або зовнішнім системам.

Для цього використовується спеціальний тег `<exposeSearchCondition>`.

TIP: Опис тегу `<exposeSearchCondition>` ви можете також переглянути на сторінці xref:data-modeling/data/physical-model/liquibase-ddm-ext.adoc[].

Тег `<exposeSearchCondition>` приймає 1 атрибут для назви критерію пошуку (search condition), а також 3 атрибути для різних сценаріїв використання:

* Надання доступу до представлень та REST API реєстру для іншого реєстру на Платформі -- для цього використовується атрибут `platform`.
* Надання доступу до представлень та REST API реєстру для зовнішньої системи -- для цього використовується атрибут `externalSystem`.
* Надання доступу до представлень реєстру для сервісів-учасників СЕВ ДЕІР через інтерфейс ШБО "Трембіта" за протоколом SOAP -- для цього використовується атрибут `trembita`.

._Приклад XML-схеми використання тегу та його атрибутів у моделі даних_
====

[source, XML]
----
<ext:exposeSearchCondition name="viewForDrop" platform="true" externalSystem="true" trembita="false"/>
----

[NOTE]
=====
* `name` -- назва представлення для критерію пошуку (search condition)
* `platform` -- для надання доступу має бути у значенні `"true"`
* `externalSystem` -- для надання доступу має бути у значенні `"true"`.
* `trembita` -- для надання доступу має бути у значенні `"true"`

Якщо необхідно закрити доступ до представлень API реєстру, то відповідні атрибути мають бути у значенні `false`.

Поточна конфігурація показує, що доступ до даних реєстру може бути відкритий для іншого реєстру на Платформі, а також для зовнішньої системи. Для сервісів, що отримуватимуть дані через SOAP-інтерфейс ШБО "Трембіта", доступ до даних є закритим.
=====
====

