@startuml
autonumber
skinparam ParticipantPadding 20
title "API rate limiting - Unauthenticated user"

'This is a single line comment

/'
This is a multi-
line comment
'/

actor "User" as User
box "Kong API Gateway"
entity "Rate Limiting plugin" as ratel
end box
participant "Upstream Service" as service

User -> ratel : Request to the service
ratel -> ratel : Check rate limit for a client by IP address
alt Rate limit not reached
ratel -> service: Forwarding request to the upstream service
service --> User : Service response
else Rate limit exceeded
ratel --> User: HTTP 429: { "message": "API rate limit exceeded" }
end

@enduml