@startuml
autonumber
skinparam ParticipantPadding 20
title "API Rate Limiting - Authenticated User"

'This is a single line comment

/'
This is a multi-
line comment
'/

actor "User" as User
box "Kong API Gateway"
entity "OIDC plugin" as oidc
entity "Rate limiting plugin" as ratel
end box
participant "Upstream Service" as service

note over User: Cookie: session=xxx
User -> oidc : Request with session ID

oidc -> oidc : Check user session and add headers

note over oidc
X-Access-Token: aaa
X-ID-Token: bbb
X-Userinfo: ccc
token-claim: 123
end note

oidc -> ratel : Transfer request for processing to the next plugin
ratel -> ratel : Check rate limits for client \n by IP or "token claim" header
alt Rate limit is not reached
ratel -> service: Forward request to upstream service
service --> User : Service response
else API rate limit exceeded
ratel --> User: HTTP 429: { "message": "API rate limit exceeded" }
end

@enduml
