= Початкове завантаження даних

== Загальний опис

Мета завантаження історичних даних з інших джерел до реєстру на Платформі.
Історичні данні можуть бути як просто данними таблиць так і повʼязаними з ними файлами.


== Ролі користувачів

* Технічний-адміністратор реєстру
* Адміністратор реєстру (_адміністратор даних_)


== Загальні принципи та положення

* Підтримуються тільки завантаження даних в CSV-форматі.
* Завантаження даних може відбуватись тільки в порожні таблиці.
* Структура файла має повністю відповідати структурі таблиці.
* Завантаження відбувається в режимі streaming так, що нема необхідності завантажувати весь файл в памʼять.
* Завантаження файлів до ceph кошика тимчасового зберігання даних відбувається через s3-сумісний компонент на веб-інтерфейсі.
* Доступ з інтерфейсу адміністрування даних реєстру для додавання та видалення файлів надається тільки до кошику тимчасового зберігання.
* При первинному завантаженні даних, запис здійснюється не через процедуру.
* При первинному завантаженні даних, не застосовуються перевірки RBAC та RLS.
* Зберігання звʼязків між операційною та історичною таблицями відбувається прозоро в утиліті первинного завантаження даних таблиць.
* В один момент часу можна готуватись завантаження тільки для однієї таблиці, оскільки всі інші файли будуть переноситись як повʼязані.



== Високорівневий дизайн рішення

image::architecture-workspace/platform-evolution/initial-load/initial-load.svg[]

=== Сервіси та їх призначення

*Веб-інтерфейс адміністрування даних реєстру* - веб-інтерфейс для створення процесів завантаження посадових осіб та первинного завантаження даних.

*Сервіс адміністрування даних реєстру* - сервіс який надає REST API для створення запитів на завантаження посадових осіб, завантаження  первинних даних.

*Утиліта первинного завантаження сутностей в таблиці* - утиліта яка за допомогою динамічної генерації SQL на підставі структури вхідного CSV-файлу, зберігає дані в БД підтримуючи звяʼзок таблиці сутності та історичної таблиці.


== Розгортання сервісів

=== Схема розгортання

image::architecture-workspace/platform-evolution/initial-load/deployment.svg[]

=== Ключові сценарії взаємодії сервісів

==== Створення адміністраторів для роботи з сервісом адміністрування даних реєстру.

При створенні адміністраторів з роллю (_data-administrator_), вказуються додатково _ЄДРПУО_, _ДРФО_, _ПІБ_.

image::architecture-workspace/platform-evolution/initial-load/load-phase.svg[]

==== Створення тимчасової схеми в операційній БД

[NOTE]
Використання цієї функціональності можливо лише для реєстрів в режимі розробки.

Адміністратор реєстру через, адміністративний інтерфейс управління платформою (control-plane), для реєстру може увімкнути та вимкнути тимчасову схему.
При вмиканні тимчасової схеми відбувається створення схеми (`sandbox`) в операційній БД та створюється додатково вебінтерфейс перегляду даних реєстру(`pgAdmin`) та користувач з доступом тільки до цієї схеми.
А при вимиканні схема видаляється з усіма даними, користувачем та видаленням вебінтерфейсу перегляду даних реєстру.

==== Завантаження даних в тимчасову схему

[NOTE]
Використання цієї функціональності можливо лише для реєстрів в режимі розробки.

Тимчасова схема використовується для розробки, і в ній дозволені прямі маніпуляції з даними, створення та видалення таблиць. Операції в цій схемі здійснюються за допомогою веб-застосунку `pgAdmin`.
Основною метою даної схеми в контексті первинного завантаження є:

* Приведення наявних даних (історичних даних) до вигляду який відповідає сутностям в реєстрі на Платформі. +
_Наприклад: Конвертація типів, зміна структури зберігання даних тощо._
* Побудова звʼязків між сутностями реєстру та історичними даними. _Наприклад: Використання посилання на довідники які вже використовуються реєстром на Платформі._

==== Завантаження даних до кошика тимчасового зберігання даних

Завантаження CSV файлу та, при потребі, повʼязаних з даними файлів, до s3 сумісного сховища відбувається безпосередньо з веб-інтерфейс адміністрування даних реєстру. Завантаження файлів може відбуватись в декілька ітерацій. Після завантаження файлів вони відображаються в табличному вигляді.

Також з даного інтерфейсу можливо видаляти файли.

==== Завантаження готових даних в операційну базу реєстру

Після завантаження даних до _кошика тимчасового зберігання даних_ відповідальна особа має вказати в яку структуру БД будуть завантажуватись дані та підписати запит своїм КЕП.

Процес завантаження включає в себе потокову обробку файлу таким чином, що кожен рядок CSV зберігається у відповідну структуру та додатково створюється запис про вставку в історичній таблиці, при чому в якості підпису та інформації хто створив запис виступає підпис та інформація про посадову особу яка підписала запит завантаження даних.

==== Завантаження даних з пов'язаними файлами в операційну дану реєстру

При наявності в таблиці колонок типу файл, в значенні цієї колонки має бути шлях до цього файлу в s3-кошику.
В такому варіанті файл буде збережено до кошика для зберігання файлів та побудовано  звʼязок з відповідним записом.

== Низькорівневий дизайн сервісів

=== Адміністративний інтерфейс управління платформою

==== Ключові сценарії

* Створення та видалення тимчасової схеми
* Налаштування параметрів віджета для перевірки КЕП
* Створення адміністраторів.

==== Перемикач створення та видалення тимчасовї схеми



==== Екран для конфігурації віджета

По аналогії з кабінетом надавача і отримувача послуг створити екран _Налаштування автентифікації для адміністраторів_ в якому буде існувати тільки частина конфігурації віджета підпису.

==== Створення адміністратора

Розширення вікна створення адміністратора полями ЄДРПУО, ДРФО, ПІБ та поля ролі.

[NOTE]
Зараз передбачено відокремлення тільки однієї ролі _data-administrator_ разом з тим необхідно передбачити можливість декількох ролей.

.Схема створення адміністратора з можливістю підписання запитів на завантаження даних.
[source, yaml]
----
administrators:
    - username: admin@platform.ua
      email: admin@platform.ua
      firstName: Admin
      lastName: Adminchenko
      #Розширення конфігурації
      roles:
          - data-administrator
      authVaultSecret: registry-kv/registry/%registry_name%/administrators/admin@platform.ua
      passwordVaultSecretKey: password
      edrpuoVaultSecretKey: edrpuo
      drfoSecretKey: drfo
      fullNameSecretKey: fullName
----

.edp-library-pipeline resources/templates/keycloakRealmUser.yaml
[source, yaml]
----
apiVersion: v1.edp.epam.com/v1alpha1
kind: KeycloakRealmUser
metadata:
  name: ${resourceName}
  namespace: user-management
spec:
  #Розширення шаблону
  attributes:
    drfo: "%drfo%"
    edrpuo: "%edrpuo%"
    fullName: "%fullName%"
  #Існуюча конфігурація
  firstName: ${firstName}
  lastName: ${lastName}
  username: ${username}
  email: ${email}
  password: ${password}
  realm: openshift
  enabled: true
  emailVerified: true
  keepResource: true
  roles: ${roles}
  groups: ${groups}
  requiredUserActions:
    - UPDATE_PASSWORD
----


=== Веб-інтерфейс адміністрування даних реєстру

==== Ключові сценарії

* Запуск процесу завантаження користувачів
* Завантаження файлів до тимчасового кошика зберігання.
* Запуск процесу завантаження даних до таблиць.

==== Структура меню

Передбачено два сценарії використання веб-інтерфейсу для завантаження даних або завантаження посадових осіб.

* Завантаження даних в реєстр
** Підготовка даних
** Завантаження даних до реєстру
* Завантаження посадових осіб

Пункт меню _Завантаження даних до реєстру_ відображається тільки для адміністраторів які мають роль _data-administrator_.

==== Компонент по роботі з S3-кошиком


==== Компонент по роботі з S3-кошиком

Компонент представляє собою існуючий drag-n-drop таблицю для файлів, з реалізацією завантаження на події компоненти. (додавання, видалення, завантаження).

При завантаженні компонента відбувається перегляд відповідного s3-кошика.

Для того, щоб не створювати додаткове навантаження на _Сервіс адміністрування даних реєстру_ при роботі з S3-кошиком яким міг би виступати лише як _proxy_ для _Rados Gateway_ компонент інтерфейсу працює безпосередньо з _Rados Gateway_.

Для автентифікації JS s3-клієнта, ключ і секрет отримується запитому до  _Сервісу адміністрування даних реєстру_.

=== Сервіс адміністрування даних реєстру

==== Ключові сценарії

* Запуск _K8s Job_ по завантаженню.
* Отримання статусу виконання Job.
* Отримання ключа і секрета для доступу до s3-кошика.


==== Технічний стек
Як основний _framework_ використовується Spring Boot 3.15 та використання _Native Image_ та _in container build_.

==== Запуск утиліти як K8s Job

Після підписання запиту на завантаження даних

=== Утиліта первинного завантаження сутностей в таблиці

==== Ключові сценарії

* Копіювання даних з тимчасового кошика зберігання даних до кошика архівного зберігання даних.
* Запис даних з _csv_ файлів до операційної БД в таблиці сутностей та історичних таблиць.

==== Технічний стек
Як основний _framework_ використовується Spring Boot 3.15 та використання _Native Image_ та _in container build_.


==== Вхідні параметри

USER_ACCESS_TOKEN - токен користувача який ініціалізував процес завантаження даних+
TABLE_NAME - назва таблиці в яку відбувається завантаження +
CSV_FILE - назва csv файла дані з якого будуть завантажуватись в таблицю вказану в параметрі TABLE_NAME +
REQUEST_ID - ідентифікатор `X-B3-TraceId` для відслідковування +
REQUEST -  JSON структура +

==== Аудит

Для процесу збереження

==== Завантаження даних до операційних таблиць.


[source, xml]
----
<createTable tableName="person" ext:historyFlag="true">
    <column name="user_id" type="UUID" defaultValueComputed="uuid_generate_v4()">
        <constraints nullable="false" primaryKey="true" primaryKeyName="pk_property_id"/>
    </column>
    <column name="first_name" type="TEXT"/>
    <column name="last_name" type="TEXT"/>
    <column name="passport" type="FILE"/>
    <column name="inn" type="TEXT"/>
</createTable>
----

.Приклад SCV файла
[source, csv]
----
firstName;lastName;passport;inn
Петро;Петренко;паспорт_петренко.pdf;11111111
Кирил;Кириленко;passports/scan.jpg;22222222
----


.Приклад організації s3-кошика init-data-load-raw для завантаження даних
[plantuml]
----
@startsalt
{
{T
 +<&file> person.csv
 +<&file> паспорт_петренко.pdf
 ++<&folder> passports
 +++<&file> scan.jpg
}
}
@endsalt
----


Етапи завантаження даних:

* Збереження даних в таблиці відбувається через виконання _pg copy_ динамічно формуючі _SQL_ запит.
* Для історичної таблиці окрім даних з _csv_ файлу додаються дані з токена та підпису.


[NOTE]
З міркувань швидкодії всі файли переносяться до сховища файлів без перевірки використання їх в даних таблиці.

.Перенесення повʼязаних файлів
[plantuml]
----
control "Initail data load job" as job
collections "file-ceph-bucket" as file
collections "inital-data-load-raw" as raw
database "Registry DB" as db


job -> raw: отримання переліку файлів
return перелік файлів
job -> job: виключення csv файлу з переліку
loop
job -> raw: отримання файлу та генерація uuid для нього
return контент файлу
job -> db: збереження відповідного uuid та назви файлу в таблицю метаданих
return створення запису
job -> file: збереження файлу з uuid в якості імені
return збережено
end
----

У випадку непередбачуваного переривання процесу завантаження, пов'язані файли можуть бути видалені, відповідно до таблиці метаданих.

