= Початкове завантаження даних

== Загальний опис

Перенос даних з існуючих цифрових реєстрів на платформу.

== Функціональні сценарії

* Перевірка файла який відправляються
* Завантаження файлу

== Ролі користувачів

* Моделювальник
* Власник реєстру


== Загальні принципи та положення

* Підтримуються тільки завантаження даних в CSV-форматі.
* Завантаження даних може відбуватись тільки в порожні таблиці.
* Структура файла має повністю відповідати структурі таблиці.
* Завантаження відбувається в режимі streaming так, що нема необхідності завантажувати весь файл в памʼять.
* Завантаження файлів до ceph кошика тимчасового зберігання даних відбувається через s3-сумісний компонент на веб-інтерфейсі.
* Доступ з інтерфейсу управління даними реєстру для додавання та видалення файлів надається тільки до кошику тимчасового зберігання.
* При первинному завантаженні даних, запис здійснюється не через процедуру.
* При первинному завантаженні даних, не застосовуються перевірки RBAC та RLS.
* Зберігання звʼязків між операційною та історичною таблицями відбувається прозоро в утиліті первинного завантаження даних таблиць.



== Високорівневий дизайн рішення

image::architecture-workspace/platform-evolution/initial-load/initial-load.svg[]

=== Сервіси та їх призначення

*Веб-інтерфейс управління даними реєстру* - веб-інтерфейс для створення процесів завантаження посадових осіб та первинного завантаження даних.

*Сервіс управління даними реєстру* - сервіс який надає REST API для створення запитів на завантаження посадових осіб, завантаження  первинних даних.

*Утиліта первинного завантаження сутностей в таблиці* - утиліта яка за допомогою динамічної генерації SQL на підставі структури вхідного CSV-файлу, зберігає дані в БД підтримуючи звяʼзок таблиці сутності та історичної таблиці.

=== Ключові сценарії взаємодії сервісів

image::architecture-workspace/platform-evolution/initial-load/load-phase.svg[]

==== Створення тимчасової схеми в операційній БД

[NOTE]
Використання цієї функціональності можливо лише для реєстрів в режимі розробки.

Адміністратор реєстру через, адміністративний інтерфейс управління платформою (control-plane), для реєстру може увімкнути та вимкнути тимчасову схему.
При вмиканні тимчасової схеми відбувається створення схеми (`sandbox`) в операційні БД та створюється додатково вебінтерфейс перегляду даних реєстру(`pgAdmin`) та користувач з доступом тільки до цієї схеми.
А при вимиканні схема видаляється з усіма даними, користувачем та видаленням вебінтерфейсу перегляду даних реєстру.

==== Завантаження даних в тимчасову схему

[NOTE]
Використання цієї функціональності можливо лише для реєстрів в режимі розробки.

Тимчасова схема використовується для розробки, і в ній дозволені прямі маніпуляції з даними, створення та видалення таблиць. Операції в цій схемі здійснюються за допомогою веб-застосунку `pgAdmin`.
Основною метою даної схеми в контексті первинного завантаження є:

* Приведення наявних даних (історичних даних) до вигляду який відповідає сутностям в реєстрі на Платформі. +
_Наприклад: Конвертація типів, зміна структури зберігання даних тощо._
* Побудова звʼязків між сутностями реєстру та історичними даними. _Наприклад: Використання посилання на довідники які вже використовуються реєстром на Платформі._

==== Завантаження даних до кошика

Завантаження CSV файлу та, при потребі, повʼязаних з даними файлів, до s3 сумісного сховища відбувається безпосередньо з веб-інтерфейс управління даними реєстру. Завантаження файлів може відбуватись в декілька ітерацій. Після завантаження файлів вони відображаються в табличному вигляді.

==== Завантаження готових даних в операційну базу реєстру

Після завантаження даних до _кошика тимчасового зберігання даних_ відповідальна особа має вказати в яку структуру БД будуть завантажуватись дані та підписати запит своїм КЕП.

Процес завантаження включає в себе потокову обробку файлу таким чином, що кожен рядок CSV зберігається у відповідну структуру та додатково створюється запис про вставку в історичній таблиці, при чому в якості підпису та інформації хто створив запис виступає підпис та інформація про посадову особу яка підписала запит завантаження даних.

==== Завантаження даних з повʼязаними файлами в операційну дану реєстру


== Низькорівневий дизайн сервісів

=== Компонентна / структурна діаграма

[TIP]
...

=== Компоненти та їх призначення

|===
|Компонент|Призначення

|...
|...
|===

=== Ключові сценарії

* ...
* ...
* ...

=== Налаштування сервісів
