@startuml
skinparam monochrome true

actor "Користувач" as user
participant "Клієнтський додаток\n кабінету користувача" as cabinet
participant "Kong \nAPI Management" as kong
participant "Сервіс управління \n бізнес-процесами користувача" as user_process_mngmnt

box "Виконання бізнес-процесів"
participant "Сервіс виконання бізнес-процесів" as bpms
end box

box "Підсистема звітності" #LightBlue
participant "API генерації витягів" as report_generation_api
end box

skinparam responseMessageBelowArrow false
title Ініціювання генерації витягу через бізнес-процес

user -> cabinet: Замовлення послуги генерації витягу
activate cabinet
  cabinet -> cabinet: Введення вхідних даних через стартову форму
  cabinet -> kong: Запит на ініціювання бізнес-процесу
  activate kong
    kong -> user_process_mngmnt: Запит на ініціювання бізнес-процесу
    activate user_process_mngmnt
      user_process_mngmnt -> bpms: Запит на ініціювання бізнес-процесу
      activate bpms
        bpms -> bpms: Обробка вхідних даних
        bpms -> bpms: Визначення типу витягу
        bpms -> bpms: Підготовка даних для формування запиту на генерацію
        bpms -> bpms: Накладання системного підпису на дані запиту
        note over bpms, report_generation_api: Тип витягу, необхідність накладання системного підпису, вхідні дані для генерації та Access Token користувача-ініціатора
        bpms -> report_generation_api: Запит на генерацію витягу [asyncBefore / sync]
        report_generation_api -> bpms: Ідентифікатор згенерованого витягу
        alt Повернення управління у кабінет при асинхронному запиті на генерацію витягу [asyncBefore]
        bpms -> cabinet: Перехід управління до користувача
        cabinet -> cabinet: Перехід до сторінки "Послуги у виконанні"
        cabinet -> user: Перегляд послуг у виконанні зі статусом генерації витягу
        end
        loop Полінг статусу генерації витягу
          note over bpms, report_generation_api: Ідентифікатор витягу та Access Token системного користувача
          bpms -> report_generation_api: Отримання статусу генерації витягу за ідентифікатором
          bpms -> bpms: Перевірка статусу генерації витягу
          alt Витяг згенеровано успішно
            bpms -> bpms: Збереження ідентифікатору у змінній SYS_VAR_PROCESS_EXCERPT_ID
            bpms -> bpms: Збереження результату процесу у змінній SYS_VAR_PROCESS_COMPLETION_RESULT
            bpms -> bpms: Завершення бізнес-процесу процесу
          else Виникла помилка генерації витягу
            bpms -> bpms: Збереження результату процесу у змінній SYS_VAR_PROCESS_COMPLETION_RESULT
            bpms -> bpms: Завершення бізнес-процесу процесу
          end
        end
        alt Блокування користувача кабінету при синхронному запиті на генерацію витягу до завершення процесу [sync]
          bpms -> cabinet: Перехід управління до користувача
          cabinet -> cabinet: Перехід на сторінку "Замовлені послуги"
          cabinet -> user: Перегляд замовлених послуг з можливістю завантаження витягу
        end

        == Отримання інформації про завершення генерації витягу  ==
        user -> cabinet: Перевірка статусу замовлених послуг
        cabinet -> cabinet: Перехід на сторінку "Замовлені послуги"
        cabinet -> user: Перегляд замовлених послуг з можливістю завантаження витягу
      deactivate bpms
    deactivate user_process_mngmnt
  deactivate kong
 deactivate cabinet

@enduml