:sectanchors:
:sectlinks:
= User documentation

The *_User documentation_* section encompasses comprehensive guides and tutorials tailored for end users of our system. This section is divided into two primary categories:

Officers and service providers ::

* [*] Get a broad perspective with the *_Officer portal overview_*.
* [*] Learn how to *_generate excerpts_* to extract crucial information.
* [*] Efficiently manage data through *_sorting and pagination_* techniques.

Citizens and service recipients ::
* [*] Dive into the *_Citizen portal overview_* to get familiar with the functionalities tailored for citizens.
* [*] Gain knowledge on *_Generating excerpts in PDF format_* for easy sharing and printing.
* [*] Connect with others through *_Sending messages to users_*.
* [*] Utilize the *_Sorting and pagination_* features for better data management.

Additionally, users can dive deep into common category for all users ::

* [*] *_Registry user authentication_* to understand the security and login protocols and approaches.
* [*] *_Contact Support_* for any immediate assistance or queries.
* [*] *_Files_* to generate and work with various documents in different formats.
* [*] Stay informed with *_Notifying about successful task completion in user portals_* to track the progress of your requests.
* [*] Ensure your actions are precise with *_Alerting pop-up windows for action confirmation in user portals_*.

This section is crafted to provide users with a clear roadmap, helping them navigate the Platform quickly and efficiently.

== Section overview

** Officers and services providers
*** xref:user:officer/officer-portal-overview.adoc[Officer portal overview]
*** xref:user:officer/reports/overview.adoc[Generating excerpts]
*** xref:user:officer/overview.adoc[Sorting and pagination]

** Citizens and service recipients
*** xref:user:citizen/citizen-portal-overview.adoc[Citizen portal overview]
*** xref:user:citizen/citizen-get-excerpts.adoc[Generating excerpts in PDF format]
*** xref:user:citizen/user-notifications/user-notifications-overview.adoc[Sending messages to users]
*** xref:user:citizen/sorting-pagination/citizen-portal-bp-sorting-pagination.adoc[Sorting and pagination]

** Common for users
*** xref:user:citizen-officer-portal-auth.adoc[Registry user authentication]
*** xref:user:error-email-support.adoc[Contact support]
*** xref:user:bp-files/upload-multiple-files-p7s-asic.adoc[Files]
//*** xref:user:bp-files/editgrid-file-download.adoc[]
*** xref:user:user-notifications-success-task.adoc[Pop-up notifications]
*** xref:user:alerting-popups.adoc[Alerting pop-up windows]