@startuml
skinparam monochrome true

participant "Клієнтський додаток\n кабінету користувача" as cabinet
participant "Kong \nAPI Management" as kong
participant "Сервіс \nцифрових документів" as digital_documents
participant "Сервіс \nвиконання \nбізнес-процесів" as bpms
participant "Сервіс \nмета-даних \nUI-форм" as form_provider
skinparam responseMessageBelowArrow true

title Валідація файлів при завантаженні через кабінет

activate cabinet
  cabinet -> kong: Запит на завантаження файлу: \nPOST "/documents/{processInstanceId}/{taskId}/{fieldName}"\n* Ідентифікатор сесії Kong; \n* Мета-атрибути файлу; \n* Бінарний контент файлу;
  activate kong
    kong -> digital_documents: Запит на завантаження файлу: \nPOST "/documents/{processInstanceId}/{taskId}/{fieldName}"\n* X-Access-Token; \n* Мета-атрибути файлу; \n* Бінарний контент файлу;
    activate digital_documents
      digital_documents -> bpms: Отримання зв'язаної з задачею UI-форми за {taskId}
      bpms --> digital_documents: <formKey>
      digital_documents -> form_provider: Запит на отримання мета-даних UI-форми за {formKey}
      note right digital_documents
        {
          "components": [
            {
              "label": "<file_property_label>",
              "storage": "url",
              "key": "<file_property_name>",
              "type": "file",
              "url": "/documents",
              "input": true
            }
          ]
        }
      end note
      form_provider --> digital_documents: JSON-документ опису UI-форми
      digital_documents -> digital_documents: Пошук опису поля за key={fieldName} в мета-даних форми
      alt Опис поля з key={fieldName} не знайдено для форми задачі
        digital_documents --> cabinet: 403: Доступ заборонено
      end
      digital_documents -> digital_documents: Формування композитного валідатора файлу \nна базі опису правил для поля у мета-даних форми \n(File Pattern, File Maximum Size)
      digital_documents -> digital_documents: Визначення ім'я, типу та розміру файлу <filename, type, size>
      digital_documents -> digital_documents: Валідація <filename, type, size> згідно налаштованих обмежень
      alt Порушені налаштовані адміністратором обмеження на завантаження файлів для файлового поля
        digital_documents --> cabinet: 422: Помилка валідації
      end
      digital_documents -> digital_documents: Збереження Ceph-об'єкта для файлу
      digital_documents -> digital_documents: Підготовка відповіді з мета-даними збереженого документу
    digital_documents --> kong: 200 OK: <uuid, id, url, name, size, type, checksum>
    deactivate digital_documents
    kong -> cabinet: 200 OK: <uuid, id, url, name, size, type, checksum>
  deactivate kong
deactivate cabinet

@enduml