:toc-title: ЗМІСТ
:toc: auto
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Модель розгортання регламенту та пайплайн публікацій

== Розгортання регламенту

Розгортання системи відбувається на підставі одного або декількох регламентів.

Адміністратор регламенту формує та ініціює розгортання регламенту реєстру, що передбачає внесення змін до набору сутностей -- елементів регламенту.

TIP: Структура та опис типових сутностей подані у розділі xref:#registry-regulations-structure[].

Розгортання регламенту реєстру автоматизовано інструментами CI/CD. За розгортання регламенту відповідає Jenkins-пайплайн `*MASTER-Build-registry-regulations*` та пов'язані пайплайни.

TIP: Детальніше про пайплайн публікації регламенту дивіться у розділі xref:#registry-regulations-pipeline[].

[#registry-regulations-structure]
== Структура регламенту

Каталог регламенту реєстру має чітко визначену структуру директорій. Нижче показано схему типового регламенту.

.Структура типового регламенту реєстру
====
[plantuml]
----
@startsalt
{
{T
+ <&folder> registry-regulations

++ <&folder> bp-auth
+++ <&file> role.yml
+++ ...

++ <&folder> bp-trembita
+++ <&file> config.yml
+++ ...

++ <&folder> bpmn
+++ <&file> process.bpmn
+++ ...

++ <&folder>data-model
+++ <&folder> data-load
++++ <&file> dict.csv
++++ ...
+++ <&file> model.xml
+++ ...

++ <&folder> dmn
+++ <&file> rule.dmn

++ <&folder> excerpts
+++ <&file> index.html.ftl
+++ ...

++ <&folder> excerpts-csv
+++ <&file> excerpt.csv
+++ ...
++ <&folder> excerpts-docx
+++ <&file> excerpt.docx
+++ ...

++ <&folder> forms
+++ <&file> form.json
++++ ...

++ <&folder> global-vars
+++ <&file> global-vars.yml

++ <&folder> notifications
+++ <&folder> diia
++++ <&folder> notification-template
+++++ <&file> notification.diia
+++++ <&file> notification.yml
++++ <&folder> channel-confirmation
+++++ <&file> notification.diia
+++++ <&file> notification.yml
+++ <&folder> email
++++ <&folder> notification-template
+++++ <&file> notification.ftlh
+++++ <&file> notification.yml
++++ <&folder> channel-confirmation
+++++ <&file> notification.ftlh
+++++ <&file> notification.yml
+++ <&folder> inbox
++++ <&file> notification.ftl
++++ <&file> notification.yml

++ <&folder> reports
+++ <&file> report.json
+++ ...

++ <&folder> roles
+++ <&file> role.yml
+++ ...

++ <&folder> settings
+++ <&file> settings.yml

+ <&file> settings.yaml

}
}
@endsalt
----
====

.Пояснення до структури регламенту
[width="100%",cols="19%,19%,62%",options="header"]
|===

| Регламент
| Директорія/Файл
| Опис

| _registry-regulations_
|
| Верхньорівнева папка, що містить вкладені директорії із сутностями регламенту.

|
| _bp-auth_
| Папка, що містить `YAML`-файли доступу до бізнес-процесів для реалмів `citizen` (отримувач послуг), `officer` (посадова особа/надавач послуг) та `external-system` (зовнішні системи та реєстри).

|
| _bp-trembita_
| Папка, що містить конфігураційні файли для налаштування взаємодії із зовнішніми сервісами та системами через SOAP-інтерфейси ШБО «Трембіта», а також через REST.

|
| _bpmn_
| Папка, що містить схеми бізнес-процесів у форматі ._bpmn_ (різновид XML)

|
| _data-model_
| Папка, що містить схеми для розгортання БД та API-представлень, а також CSV-довідники для подальшого наповнення даними таблиць-довідників.

|
| _dmn_
| Папка, що містить змодельовані перевірчі правила (таблиці прийняття рішень) у форматі ._dmn_ (різновид XML)

|
| _excerpts_
| Папка, що містить шаблони PDF-витягів реєстру

|
| _excerpts-csv_
| Папка, що містить шаблони витягів-звітів у форматі CSV

|
| _excerpts-docx_
| Папка, що містить шаблони проєктів наказів у форматі DOCX

|
| _forms_
| Папка, що містить змодельовані користувацькі форми введення даних у форматі JSON

|
| _global-vars_
| Папка, що містить глобальні змінні бізнес-процесів реєстру

|
| _notifications_
| Папка, що містить шаблони для відправлення повідомлень через канали зв'язку `diia`, `email`, та `inbox`.

|
| _reports_
| Папка, що містить сформовану аналітичну звітність (запити та дашборди) у JSON-форматі

|
| _roles_
| Папка, що містить конфігураційні файли для налаштування ролей у реєстрі (officer.yml -- для призначення посадових осіб різних рангів, `citizen.yml` -- для визначення отримувачів послуг)

|
| _settings_
| Папка, що містить загальні налаштування регламенту (повна та скорочена назви реєстру тощо)

|
| _settings.yaml_
| Конфігураційний файл, що містить системні налаштування реєстру та деяких сервісів

|===


=== Сценарії використання

Виділяють 3 основні сценарії розгортання: ::

* [.underline]#Створення реєстру# -- розгортання системи на підставі завантаженого регламенту.

* [.underline]#Внесення критичних змін# -- має супроводжуватись обов'язковим збільшенням версії в її другому розряді.
До критичних змін можна віднести будь-які зміни до моделі даних та бізнес-процесів.

* [.underline]#Внесення незначних змін# -- при внесенні навіть незначних змін версія має бути збільшена у своєму третьому розряді. Незначними змінами вважаються ті для внесення яких не потрібний рестарт сервісів.

=== Безперервна інтеграція та безперервне доставлення (CI/CD)

Розгортання регламенту реєстру автоматизовано інструментами CI/CD. За розгортання регламенту відповідає Jenkins-пайплайн `*MASTER-Build-registry-regulations*` та пов'язані пайплайни.

У розробці програмного забезпечення *CI/CD* або *CICD* — це комбінована практика безперервної інтеграції та безперервного доставлення або безперервного розгортання.

.Схема розгортання регламенту реєстру за допомогою CI/CD
image::arch:archive/deployment-pipeline.svg[]

[#registry-regulations-pipeline]
== Пайплайн MASTER-Build-registry-regulations та його особливості

//TODO: Update

Кроки можна розділити на службові та породжувальні. Всі службові кроки -- є обов'язковими для виконання. Породжувальні -- кроки які відповідальні за розгортання/внесення змін до компонентів можуть бути пропущені, якщо змін вносити не треба.

[plantuml, preparation, svg]
----
@startuml
title Підготовчі кроки
skinparam monochrome true

left to right direction

rectangle "Checkout" as checkout
rectangle "Зчитування змін\nу репозиторії\nреєстру" as getChanges
rectangle "Валідація\nконфігураційних\nфайлів" as validation
rectangle "Штатне\nвимкнення\nсервісів" as shutdown
rectangle "Створення\nрезервної\nкопії" as backup
rectangle "Створення\nролей БД\nдля Redash" as redashRoles
rectangle "Створення\nсніппетів\nдля Redash" as redashSnippets

checkout --> getChanges
getChanges --> validation
validation --> shutdown
shutdown --> backup
backup --> redashRoles
redashRoles --> redashSnippets

@enduml
----

[plantuml, deployment, svg]
----
@startuml
title Розгортання системи
skinparam monochrome true

left to right direction


rectangle "Розгортання\n моделі даних" as createDatafactory
rectangle "Розгортання\n бізнес процесів" as createBpmn
rectangle "Створення\n правил" as createDmn
rectangle "Створення\n форм" as createForms
rectangle "Створення\n звітів" as createReports
rectangle "Запуск автотестів" as autotest

createDatafactory --> createBpmn
createBpmn --> createDmn
createDmn --> createForms
createForms --> createReports
createReports --> autotest
@enduml
----

[plantuml, error, svg]
----
@startuml
title Обробка помилок
skinparam monochrome true

left to right direction


rectangle "Розгортання\n моделі даних" as stepExample
rectangle "..." as abstractStep
rectangle "Запуск автотестів" as autotest
rectangle "Відновлення стану\n з резервної копії" as rollback


stepExample -[dashed]-> rollback: помилка виконання
abstractStep -[dashed]-> rollback: помилка виконання
autotest -[dashed]-> rollback: тести не пройшли
@enduml
----

==== Зчитування змін у репозиторії реєстру
Після клонування репозиторія реєстру відбувається перевірка файлів регламенту на наявність внесених змін.

==== Валідація конфігураційних файлів
Перевірка відповідності завантаженого регламенту схемам та правилам. +
Наприклад: відповідність зміни версії до типу внесенних змін.

==== Розгортання моделі даних
Оскільки розгортання моделі даних являє собою складний процес, то його створення винесено в окремий pipeline (див. *Розгортання моделі даних та дата сервісів*)

==== Автотести
Не перевіряють логіку бізнес процесів чи комунікацію між компонентами системи. Основна задача таких тестів - перевірити чи всі компоненти стартували успішно.

==== Розгортання моделі даних та дата сервісів
[plantuml, datamodel, svg]
----
@startuml
title Розгортання моделі даних
skinparam monochrome true

rectangle "Checkout" as checkout
rectangle "Ініціалізація\nкомпонентів\nреєстру" as initRegistry
rectangle "Створення\nсхеми БД" as createSchema
rectangle "Створення\nпроєктів дата\nсервісів" as createProjects
rectangle "Створення\nпайплайнів" as createPipelines
rectangle "Клонування\nпроєктів" as cloneProjects
rectangle "Генерування\nкоду проєктів" as generateProjects
rectangle "Вивантаження\nкоду проєктів" as commitProjects
rectangle "Білд коду\nпроєктів" as buildProjects
rectangle "Деплой дата\nсервісів" as deployProjects

checkout -> initRegistry
initRegistry -> createSchema
createSchema -> createProjects
createProjects -> createPipelines
createPipelines --> cloneProjects
cloneProjects -l-> generateProjects
generateProjects -l-> commitProjects
commitProjects -l-> buildProjects
buildProjects -l-> deployProjects
@enduml
----

==== Ініціалізація компонентів реєстру
Ініціалізація компонентів, необхідних для розгортання регламенту (Citus, Redash, Keycloak і т.д.).

==== Створення схеми БД
Встановлення схеми бази даних регламенту засобами бібліотеки Liquibase.

==== Створення проєктів дата сервісів
Створення проєктів у реєстровому Gerrit для зберігання згенерованого коду дата сервісів.

==== Створення пайплайнів
Створення пайплайнів дата сервісів у реєстровому Jenkins.

==== Клонування проєктів
Клонування проєктів із реєстрового Gerrit-а на Jenkins агент.

==== Генерування коду проєктів
Генерування коду дата сервісів у склоновані проєкти.

==== Вивантаження коду проєктів
Вивантаження згенерованого коду в реєстровий Gerrit.

==== Білд коду проєктів
Запуск білд пайплайнів дата сервісів. Результатом роботи пайплайнів є зібрані артифакти дата сервісів, що вивантажуються в реєстровий Nexus, а також Docker імеджі (що містять артифакти та всі залежності), які вивантажуються в реєстровий Nexus Docker Registry.

==== Деплой дата сервісів
Розгортання Helm charts дата сервісів у реєстровому неймспейсі засобами Helm на основі Docker імеджів, отриманих в результаті роботи білд пайплайнів.

==== Видалення регламенту
Пайплайн розгортання дата моделі, а також пайплайни розгортання дата сервісів мають відповідні Delete-release пайплайни для видалення. Запуск cleanup-job тригерить запуск цих пайплайнів. В результаті усі дата компоненти повністю видаляються, БД реєстру очищається, пайплайн розгортання реєстру (як і пайплайн розгортання дата моделі) перестворюється.

[plantuml, deleteRelease, svg]
----
@startuml
title Процес видалення
skinparam monochrome true

rectangle "checkout" as checkout
rectangle "Ініціалізація\nкомпонентів\nреєстру" as initRegistry
rectangle "Запуск\nDelete-release\nпайплайнів" as cleanupTrigger
rectangle "Видалення\nкомпоненту\nmodel" as modelComponent
rectangle "Видалення\nкомпоненту\nrest-api" as restComponent
rectangle "Видалення\nкомпоненту\nkafka-api" as kafkaComponent
rectangle "Видалення\nкомпоненту\nsoap-api" as soapComponent
rectangle "Видалення registry-regulations" as deleteRegistryRegulations
rectangle "Відновлення registry-regulations" as recreateRegistryRegulations

checkout -> initRegistry
initRegistry -> cleanupTrigger
cleanupTrigger -d-> modelComponent
cleanupTrigger -d-> restComponent
cleanupTrigger -d-> kafkaComponent
cleanupTrigger -d-> soapComponent
modelComponent -d-> deleteRegistryRegulations
restComponent -d-> deleteRegistryRegulations
kafkaComponent -d-> deleteRegistryRegulations
soapComponent -d-> deleteRegistryRegulations
deleteRegistryRegulations -d-> recreateRegistryRegulations
@enduml
----

==== Історія змін даних
[plantuml, historyExcerptor, svg]
----
@startuml
title Генерування витягів історії змін даних
skinparam monochrome true

rectangle "Ініціалізація\nкомпонентів\nреєстру" as initRegistry
rectangle "Валідація\nвведених даних" as dataValidation
rectangle "checkout" as checkout
rectangle "Створення\nOpenShift job" as createExcerptorJob
rectangle "Генерування\nвитягу" as getHistoryReport

initRegistry -> dataValidation
dataValidation -> checkout
checkout -> createExcerptorJob
createExcerptorJob -> getHistoryReport
@enduml
----

==== Валідація введених даних
Перевірка того, що введена назва таблиці існує в БД, перевірка формату введеного UUID таблиці.

==== Створення OpenShift job
Створення OpenShift job для генерування витягу на основі введених назви та UUID таблиці.

==== Генерування витягу
Створення витягу історії змін даних і прикріплення до Jenkins пайплайна лінки для можливості завантаження витягу у форматі PDF.