= Приналежність даних -- суб'єкти та об'єкти

[IMPORTANT]
--
Сторінка технічної документації є баченням майбутньої реалізації, актуальність якого може бути застарілою.
--

Під суб'єктом розуміється будь-яка фізична або юридична особа, що має право власності над об'єктом. Відповідно, об'єктом вважається будь-яка сутність, якою володіє суб'єкт. Для позначення сутності БД об'єктом використовується відповідний XML шаблон.

== XML шаблон для визначення об'єктів

.Визначення сутності об'єктом в момент створення
[source, xml]
----
<createTable tableName="property" ext:historyFlag="true" ext:isObject="true">
    <column name="property_id" type="UUID" defaultValueComputed="uuid_generate_v4()">
        <constraints nullable="false" primaryKey="true" primaryKeyName="pk_property_id"/>
    </column>
    <column name="name" type="TEXT"/>
</createTable>
----

.Визначення об'єктом сутності що існує
[source, xml]
----
<ext:makeObject>
    <table name="property"/>
</ext:makeObject>
----

Використання атрибуту `ext:isObject="true"` або визначення існуючої таблиці об'єктом за допомогою тега `ext:makeObject` змінює структуру таблиці наступним чином:

* додається поле _subject_id_
* додається зовнішній ключ на таблицю _subject_

WARNING: Таблиця _subject_ вже має існувати в базі даних, інакше використання зазначених елементів в шаблоні призведе до помилки.

== Статура таблиці суб'єктів

Таблиця _subject_ створюється на етапі предеплоймента реєстру.

.Структура таблиці subject
[plantuml]
----
hide circle


entity subject {
    subject_id: UUID
    --
    subject_code: TEXT
    subject_type: ENUM
    --
    subject_status: ENUM
    subject_name: TEXT
}

entity "<object>" as obj {
    <object>_id: UUID
    --
    ...
    <other table fields>
    ...
    subject_id: UUID <<FK>>
}

subject ||-|{ obj
----

WARNING: Значення полів _subject_code_ та _subject_type_ являють собою унікальну комбінацію.

.значення типів enum
[plantuml]
----
enum subject_type {
INDIVIDUAL "Фізична особа"
ENTREPRENEUR "ФОП"
LEGA "Юридична особа"
OFFICER "Чиновник"
}

enum subject_status {
CANCELED "скасовано"
REGISTERED "зареєстровано"
SUSPENDING "в стані припинення"
SUSPENDED "припинено"
BANKRUPTCY "порушено справу про банкрутство"
{field} SANCTION "порушено справу про банкрутство   (санація)"
NOTVALID "зареєстровано, свідоцтво про державну реєстрацію недійсне"

}
----

Для пошуку даних по таблиці суб'єктів створюється Search Condition, що повертає _subject_id_ та _subject_status_ по _subject_code_ та _subject_type_.