= Розгортання

== Діаграма розгортання

image::admin-portal-deploy.svg[]

=== Розгортання додатку

- Адміністратор використовують браузер для доступу до веб-додатку
- *React* з *Redux* є основними бібліотеками для розробки веб додатку
- Після збірки додаток представляє собою набір файлів серед яких тільки один *html* файл, та деяка кількість *js*, *css* та інших необхідних статичних файлів
- Веб додаток адміністратора відображає контент використовуючи *Nginx* як вебсервер для статичного контенту. Єдиний *html* файл віддається на усіх веб-шляхах додатка.
- Конфігурація веб додатку відбувається через конфіг мапи *admin-portal-environment-js* та *admin-portal-nginx-config*

=== Зовнішні сервіси

- Авторизація користувачів веб додатку та отримання інформації про користувача відбувається за рахунок сервісу *Управління користувачами та ролями*
- Пошук даних в реєстрі з *API Дата фабрики*
- *registry-regulation-management* RestAPI сервіс для управління версіями-кандидатами та сутностями регламенту реєстру
- Redash - сервіс для отримання шаблонів звітів
