= Налаштування доступу до публічних даних реєстру
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Загальний опис

Сторонні системи та користувачі мають можливість отримувати публічну інформацію з реєстру в актуальному стані, обробляти та візуалізувати її без автентифікації, використовуючи публічні точки доступу API.

Цей документ складається з двох основних частин: створення та публікація точок доступу на рівні регламенту реєстру та налаштування доступу на рівні конфігурації реєстру.

== Сценарії використання

Платформа надає наступну функціональність для роботи із публічними даними у реєстрі: ::

* [*] Публікація пошукових запитів
* [*] Конфігурація ресурсів публічного API
* [*] Створення точок інтеграції для публічного API технічним адміністратором реєстру.
* [*] Отримання документації та використання публічного API.
* [*] Моніторинг стану та використання публічних пошукових критеріїв.
* [*] Зміна рейт-лімітів для наявних точок інтеграції.

== План дій з налаштування та використання

Скористайтеся наступним планом дій для налаштування та використання публічних API у реєстрі:

Налаштування на рівні регламенту: ::
+
[%interactive]
* [ ] xref:#regulations-modeling[]

* [ ] xref:#regulations-api-publish[]

* [ ] xref:#view-endpoints-openapi[]

Налаштування на рівні конфігурації реєстру: ::
+
[%interactive]
* [ ] xref:#control-plane-public-access[Налаштування доступу до публічних даних та рейт-лімітів]
* [ ] xref:#apply-changes-to-registry[]
* [ ] xref:#grafana-monitoring[]
* [ ] (_Додатково_) xref:#public-user-account[]


[#regulations-modeling]
== Моделювання регламенту

. Створення версії "кандидат": Розробник регламенту переходить в кабінет адміністратора та створює версію "кандидат" в розділі "таблиці".
. Додавання пошукового запиту: У файл опису структури додається новий пошуковий запит.
. Встановлення публічного доступу: Додається ченджсет для надання публічного доступу для доданого пошукового запиту, використовуючи тег exposeSearchCondition з новим параметром publicAccess.

- Створіть модель даних в рамках регламенту.
- В моделі даних, змоделюйте "Search Conditions" або пошукові критерії.
- Визначте потрібні пошукові критерії як публічно доступні через тег `exposeSearchCondition`.
- Наприклад:
+
[source,xml]
----
<exposeSearchCondition publicAccess="true" name="search_laboratories_by_city"/>
----

- Створіть новий ченджсет і вкажіть який пошуковий критерій ви хочете зробити публічним.

[#regulations-api-publish]
== Публікація API у регламенті

. Публікація змін: Після збереження всіх змін, розробник застосовує ці зміни до Master версії.

Опублікуйте модель даних, застосувавши зміни до майстер-гілки. Точка доступу до даних буде згенерована на базі кожного визначеного критерію.

[#view-endpoints-openapi]
== Перегляд опублікованих API у Swagger

. Перевірка змін: Після успішного проходження всіх етапів публікації, можна переглянути внесені пошукові запити, які доступні для публічного доступу, у специфікації. Для цього необхідно перейти в вебінтерфейс управління кластером Open Shift, знайти посилання на "platform-gateway-kong-proxy" та додати в адресу `/openapi`.

. Відкрийте openapi та знайдіть опубліковані публічні точки доступу.
. Скопіюйте ім'я ендпоінту до буфера обміну та перейдіть до наступного кроку налаштувань.


[NOTE]
====

Для зменшення навантаження на сервіс Kong API Gateway, для посилань до API-документації, для GET-запитів встановлюється TTL-based кешування. Відповідь кешується за допомогою плагіну `proxy-cache`.

Налаштувати значення кешу можна на рівні конфігурації плагіну через Gerrit. Значення за замовчуванням -- 15 хв.

Кеш зберігається в пам'яті API Gateway.
====

[#control-plane-public-access]
== Налаштування доступу до публічних даних

=== Налаштування реєстру у Control Plane

Відкрийте доступ публічних даних та налаштуйте рейт-ліміти.

. Увійдіть до адміністративної панелі *Control Plane*.
. Відкрийте вкладку Інформація про реєстр.
. Натисніть на секцію Публічний доступ.
. Натисніть кнопку Надати доступ.
. У новому вікні заповніть поля:
* Службова назва запита. +
Введіть службову назву запита. Наприклад, city-lab.

* Точка інтеграції. +
Вкажіть точку інтеграції, налаштовану розробником регламенту на етапі xref:#regulations-modeling[] та опубліковану в сервісі API реєстру. Наприклад, `/search-laboratories-by-city`.


* Встановіть рейт-ліміти на доступ -- кількість запитів від користувачів/систем за одиницю часу, наприклад, за годину, місяць тощо.
. Натисніть кнопку Надати.



- Перейдіть до секції *Запиту на оновлення* та підтвердіть застосування.

=== Перевірка роботи публічного доступу

. Відкрийте браузер у режимі Інкогніто й перейдіть за посиланням на доданий пошуковий запит.
. Неавтентифікований користувач повинен отримати дані у форматі JSON.



[CAUTION]
====
При досягненні ліміту, формується відповідь від API Gateway з кодом 429 та тілом
----
{ "message": "API rate limit exceeded" }
----
====

=== Керування доступом

- Для редагування точки інтеграції та лімітів:
- Натисніть на іконку *редагувати* біля відповідного запиту.
- Внесіть необхідні зміни та підтвердьте їх.
- Для блокування доступу натисніть на іконку *заблокувати*.
- Доступ можна відновити, натиснувши на іконку *розблокувати*.
- Для видалення доступу натисніть на іконку *видалити*.

Після кожної дії перевірте та xref:#apply-changes-to-registry[підтвердьте застосування змін] у секції *Запити на оновлення*.

CAUTION: Якщо видалити наявні точки інтеграції або тимчасово вимкнути їх, користувач отримає повідомлення про помилку HTTP 404 при спробі доступу.

[#apply-changes-to-registry]
== Застосування змін до реєстру

CAUTION: Секція у процесі розробки.

. Відкрийте секцію Запити на оновлення...

Після налаштування, конфігурація реєстру матиме такий вигляд:

[source,yaml]
----
publicApi:
  - name: city-lab
    enabled: true
    url: /search-laboratories-by-city
    limits:
        second: 5
        hour: 100
  - ...
----

Після виконання пайплайну розгортання, публічний доступ до даних через вказаний API-ендпоінт буде відкритий.

[#grafana-monitoring]
== Моніторинг показників у Grafana

CAUTION: Секція у процесі розробки.

=== Опис дашборду

Grafana-дашборд, призначений для моніторингу показників виконання і кількості запитів до публічних точок інтеграції від неавтентифікованих користувачів і сторонніх систем.

* Технічний адміністратор реєстру може користуватися даними з дашборду для відстеження динаміки й стану показників.
* Ці дані можуть допомогти у визначенні потреби в оптимізації налаштувань, таких як коригування лімітів на запити.

=== Доступ до дашборду

. Для доступу до дашборду, перейдіть за вказаним посиланням до сервісу Grafana в адміністративній панелі Control Plane.

. У рядку пошуку знайдіть *Public API Kong Metrics* та оберіть ваш реєстр.

=== Перегляд метрик дашборду

* Секція *Request rate*:
** Відображає кількість запитів по кожній точці інтеграції.
* Секція ...
** Моніторинг успішних запитів, помилок сервера, помилок клієнта та інших кодів відповіді.
* Секція "...":
** Статистика швидкодії: найдовший, середній, найшвидший запит.
- Секція *Latencies*:
- Аналіз динаміки показників за певний період часу й історичні дані.

[#public-user-account]
== Створення сервісного облікового запису для виконання публічних запитів

Попри те що формально точки інтеграції є публічними, для підтримання однорідності аудиту та логування в середині Платформи, такі запити будуть здійснюватись від імені службового користувача із realm `external-system`. Система автоматично створить службового користувача `public-user` для авторизації на рівні `platform-gateway`.

Переконайтеся, що такий системний користувач створений у відповідному реалмі сервісу Keycloak.

//TODO: Add screenshot

