= Моделювання бізнес-процесів і таблиць прийняття рішень
:sectanchors:
:sectlinks:

_Бізнес-процеси (БП)_ -- це базис для всіх послуг, що надають реєстри на Платформі. Вони засновані на BPMN -- стандартизованій системі умовних позначень для представлення та моделювання бізнес-процесів, що дозволяє організаціям впорядкувати операції, а також покращити ефективність та зв'язок між надавачами та отримувачами послуг. Моделювальники процесів використовують спеціалізовані інструменти BPMN, щоб створювати, редагувати, емулювати, та виконувати бізнес-процеси.

Моделювання БП -- великий розділ, який охоплює велику безліч сторінок. Детальніше про кожну з них ви можете дізнатися в огляді секції.

== Огляд секції

* [*] xref:bp-modeling/bp/what-is-bp.adoc[]
* [*] xref:bp-modeling/bp/bp-modeling-instruction.adoc[]
* [*] xref:bp-modeling/bp/element-templates/element-templates-overview.adoc[]
* [*] xref:bp-modeling/bp/juel-functions/juel-functions-overview.adoc[]
* [*] xref:bp-modeling/bp/bpmn/index.adoc[]
* [*] xref:bp-modeling/bp/modeling-facilitation/overview.adoc[]
* [*] xref:bp-modeling/bp/bp-alternative-branches.adoc[]
* [*] xref:bp-modeling/bp/access/roles-rbac-bp-modelling.adoc[Розмежування доступу до бізнес-процесів та задач]
* [*] xref:bp-modeling/bp/excerpts/bp-modeling-excerpt-csv-docx.adoc[]