= Моделювання бізнес-процесів і таблиць прийняття рішень
:sectanchors:
:sectlinks:

Бізнес-процеси (БП) - це базис для всіх послуг, що надає Платформа. Вони основані на BPMN -- стандартизованій системі умовних позначень для представлення та моделювання бізнес-процесів, що дозволяють організаціям впорядкувати операції, а також покращити ефективність та зв'язок між надавачами та отримувачами послуг. Моделювальники БП використовують спеціалізовані інструменти BPMN, щоб створювати, редагувати, емулювати, та виконувати бізнес-процеси.

Моделювання БП - велика тема із багатьма темами. Детальніше про кожну з них ви можете дізнатися на відповідних сторінках.

== Огляд секції

* [*] xref:bp-modeling/bp/what-is-bp.adoc[]
* [*] xref:bp-modeling/bp/bp-modeling-instruction.adoc[]
* [*] xref:bp-modeling/bp/element-templates/element-templates-overview.adoc[]
* [*] xref:bp-modeling/bp/bpmn/index.adoc[]
* [*] xref:bp-modeling/bp/modeling-facilitation/overview.adoc[]
* [*] xref:bp-modeling/bp/bp-alternative-branches.adoc[]
* [*] xref:bp-modeling/bp/access/roles-rbac-bp-modelling.adoc[Розмежування доступу до бізнес-процесів та задач]
* [*] xref:bp-modeling/bp/excerpts/bp-modeling-excerpt-csv-docx.adoc[]