= Що таке бізнес-процеси: аналіз, структура і типи операцій
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Вступ

Механізм робочих процесів Camunda (**Camunda BPMN Engine**) опрацьовує та виконує процеси, визначені в моделі бізнес-процесів і нотації (BPMN), глобальному стандарті моделювання процесів.

Побудова моделі бізнес-процесів є можливою завдяки додатку **Camunda Modeler** -- настільного додатка для редагування діаграм процесів BPMN, таблиць рішень DMN і форм.

TIP: Зверніться до офіційного джерела **Camunda** для отримання детальної інформації щодо моделювання та виконання бізнес-процесів і бізнес-правил (_див. xref:useful-links[Корисні посилання]_).

== Аналіз бізнес-процесів «AS IS»

=== Визначення бізнес-процесів

Послуги, що надаються фізичним і юридичним особам державними органами, базуються на стандартних бізнес-процесах. Такі процеси містять ряд операцій, які стосуються використання, зміни або видалення даних.

=== Структура та компоненти бізнес-процесу

_Бізнес-процес (БП)_ -- це послідовність дій або операцій, що мають специфічну мету: обробку інформації для досягнення конкретного результату. Кожен бізнес-процес складається з:

* _Тригерів_: Подій або умов, які запускають процес.
* _Задач_: Дій, що виконуються протягом процесу.
* _Результату_: Очікуваного виводу або зміни, яка відбувається після завершення процесу.

=== Зв'язок бізнес-процесів із реєстрами

Результат бізнес-процесу часто пов'язаний з реєстрами -- системами, де зберігається інформація. Реєстри можуть містити дані про різні аспекти діяльності організації: клієнтів, транзакції, ресурси тощо.

=== Аналіз помилок та їх коригування

Для оптимізації бізнес-процесів важливо розглядати можливі помилки, які можуть виникнути під час введення чи обробки даних. Наприклад:

* Якщо була допущена помилка у назві сутності, необхідно мати чітко визначений процес для її виправлення.
* Важливо розуміти, як такі виправлення впливають на інші елементи бази даних, особливо якщо ці елементи пов'язані з даними, які були виправлені.

== Бізнес-процеси й типові операції у реєстрах

=== Введення у бізнес-процеси

На _Платформі реєстрів_ бізнес-процеси моделюються моделювальниками та розробниками бізнес-процесів за допомогою інструментів візуального моделювання та управління low-code-підсистеми через функціональність створення бізнес-процесів, форм, взаємодій з іншими реєстрами/системами, та компонентами.

Бізнес-процеси складаються з _послідовності операцій_. Операція являє собою одну одиницю роботи, яку неможливо або не можна розбити на глибший рівень деталізації бізнес-процесів. Операції відповідають сутності **Activity** із BPMN.

_Атомарна операція_ -- це активність найнижчого рівня деталізації, що зображається в бізнес-процесі. Атомарні операції можуть бути згруповані в складені операції, такі як підпроцес, транзакція, інше (в залежності від можливостей BPMN Modeler) для подальшого перевикористання.

=== Типи атомарних операцій у реєстрах, підтримувані Платформою

Нижче подано список операцій для моделювання бізнес-процесів у розрізі BPMN-активностей.

.Компоненти BPMN для моделювання бізнес-процесів
[cols="1,2,4"]
|===
| № | Тип | Опис

3+|Події (*Events*)

| 1
| Стартова подія (*Start Event*)
| Позначає початок бізнес-процесу.

| 2
| Проміжна/Гранична подія (*Intermediate/Boundary Event*)
| Подія, яка відбувається під час виконання процесу.

| 3
| Кінцева подія (*End Event*)
| Позначає завершення бізнес-процесу.

3+|Учасники (*Participants*)

| 4
| Пул/Учасник (*Pool/Participant*)
| Представляє учасника або організаційну одиницю.

3+|Шлюзи (*Gateways*)

| 5
| XOR-Шлюз (*XOR Gateway*)
| Умовний шлюз для вибору одного зі шляхів.

| 6
| Паралельний Шлюз (*Parallel Gateway*)
| Дозволяє виконувати кілька шляхів одночасно.

| 7
| Інклюзивний Шлюз (*Inclusive Gateway*)
| Дозволяє вибрати один або декілька шляхів.

| 8
| Комплексний Шлюз (*Complex Gateway*)
| Для складних умов вибору шляху.

| 9
| Шлюз на основі подій (*Event-Based Gateway*)
| Вибір шляху на основі подій.

3+|Підпроцеси (*Subprocesses*)

| 10
| Розгорнутий підпроцес (*Expanded Subprocess*)
| Група дій, яка може бути представлена як окремий процес.

| 11
| Транзакційний підпроцес (*Transaction Subprocess*)
| Особлива група дій, яка повинна виконуватися атомарно.

| 12
| Подієвий підпроцес (*Event Subprocess*)
| Підпроцес, який стартує на основі подій.

3+|*Задачі*

| 13
| Задача відправлення (*Send Task*)
| Відправка повідомлення іншому учаснику.

| 14
| Задача отримання (*Receive Task*)
| Очікування повідомлення від іншого учасника.

| 15
| Користувацька задача (*User Task*)
| Задача, призначена для виконання користувачем.

| 16
| Ручна задача (*Manual Task*)
| Задача без автоматизації, яку виконує людина.

| 17
| Задача з бізнес-правилами (*Business Rule Task*)
| Виконання наперед визначеної логіки процесу.

| 18
| Сервісна задача (*Service Task*)
| Автоматична задача для виклику сервісів.

| 19
| Скриптова задача (*Script Task*)
| Автоматизована задача на основі скрипту.

| 20
| Задача виклику інших процесів (*Call Activity Task*)
| Викликає інший бізнес-процес або підпроцес.

| 21
| Підпроцес, що згортається (*Collapsed Subprocess Task*)
| Представлення підпроцесу як єдиного елементу.

| 22
| Розгорнутий підпроцес (`Expanded Subprocess Task`)
| Група дій, яка може бути представлена як окремий процес.

3+|Множинні екземпляри (*Multi-Instances*)

| 23
| Паралельні множинні інстанції (`Parallel Multi-Instance`)
| Задача або підпроцес, який виконується паралельно кілька разів.

| 24
| Послідовні множинні інстанції (`Sequential Multi-Instance`)
| Задача або підпроцес, який виконується послідовно.

|===

TIP: Детальніше про функціонування BPMN-елементів, які використовуються у бізнес-процесах реєстрів, ви можете дізнатися на сторінках розділу xref:bp-modeling/bp/bpmn/index.adoc[].

TIP: Для розширення бізнес-логіки та спрощення моделювання процесів Платформа пропонує бібліотеку типових розширень -- *Element Templates*. Докладніше про ці розширення читайте у розділі xref:bp-modeling/bp/element-templates/element-templates-overview.adoc[].

=== Найбільш поширені типові операції у реєстрах та сценарії використання

Нижче подано перелік найбільш поширених типових операцій у реєстрі.

==== Користувацька задача (User Task)

. Підписати документ.
+
_Наприклад, показати форму з можливістю підписання файлу КЕП з дозволеними розширеннями від надавачів електронних довірчих послуг для відповідного вихідного документа._

. Підпис даних, введених на попередніх формах, за допомогою КЕП.
+
_Наприклад, форма з можливістю завантаження файлу КЕП з дозволеними розширеннями від надавачів електронних довірчих послуг._

. Внести уточнення до даних, що не пройшли перевірку
+
_Наприклад, зобразити на формі (підсвітити) дані, що не пройшли перевірку, і дати можливість користувачу скорегувати їх перед переходом до наступного кроку._

. Завантажити цифровий документ (файл).
+
_Наприклад, форма з можливістю завантаження файлів з дозволеними розширеннями, дозволеного розміру з локального комп'ютера._

. Переглянути цифровий документ (файл).
+
_Наприклад, на формі переглянути завантажений файл для визначених форматів._

. Знайти дані в реєстрі за фільтром _(форма пошуку за параметрами)_.
+
_Наприклад, вказати значення параметрів, за якими будуть відфільтровані дані в реєстрі та показані на формі._

. Переглянути дані з реєстру за одним записом
+
_Наприклад, обрати один запис зі знайдених у результаті фільтрування і переглянути без внесення змін._

. Розподіл задач між надавачами послуг.
+
_Наприклад, форма для надавача послуг, уповноваженого розподіляти задачі, де він може встановити відповідність між задачею бізнес-процесу й особою, що має виконати цю задачу._

. Заповнити дані згідно з масками для кожного поля.
+
_Наприклад, на формі заповнити прізвище, ім'я, по батькові, використовуючи лише літери української абетки й такі спеціальні символи, як дефіс (`-`), апостроф (`'`), пробіл тощо_.

==== Сервісна задача (Service Task)

. Прочитати/отримати дані з вашого реєстру.
+
_Наприклад, створити точку інтеграції з Фабрикою даних, вказавши параметри налаштування інтеграції та з набором полів до прочитання._

. Прочитати/отримати дані з іншого реєстру.
+
_Наприклад, створити точку інтеграції з «Трембітою» вказавши параметри налаштування інтеграції та необхідні поля._

. Записати первинні дані у цей реєстр.
+
_Наприклад, створити точку інтеграції з Фабрикою даних, вказавши параметри налаштування інтеграції та набір полів для запису, й відповідні значення для кожного поля._

. Записати нову версію даних у цей реєстр.
+
_Наприклад, створити точку інтеграції з фабрикою даних, вказавши параметри налаштування інтеграції та набір полів для запису, й відповідні значення для кожного поля, ідентифікатор запису до якого вносяться зміни._

. Передати дані до іншого реєстру.
+
_Наприклад, створити точку інтеграції для публікації до «Трембіти», вказавши параметри налаштування інтеграції та необхідні поля._

. Створити документ _(включно зі збереженням)_.
+
_Наприклад, створити витяг з реєстру, де будуть відображатись дані для одного запису, і зберегти до файлу._

. Ініціювати інший бізнес-процес.
+
_Наприклад, виклик процесу читання даних в іншому реєстрі в рамках запису даних до реєстру (перевірка коду ЄДРПОУ)._

==== Задача скриптування (Script Task)

. Перевірка через скриптування.
+
_Наприклад, створення операції скриптування перевірки даних зі складними механізмами, такими як контрольна цифра в РНОКПП тощо._

. Розподіл задач між надавачами послуг.
+
_Наприклад, створення операції скриптування для складного обчислення відповідності між задачею бізнес-процесу і надавачем послуг, який має виконати цю задачу._

. Заповнити дані згідно з масками для кожного поля.
+
_Наприклад, створення операції скриптування для складних масок введення._

. Скасування бізнес-процесу.
+
_Наприклад, створення бізнес-правила, що скасовує бізнес-процес, якщо х днів не було дій з боку користувача._

. Зміна надавача послуг для виконання задачі.
+
_Наприклад, повернення задачі на розподіл, якщо х днів не було дій з боку посадової особи._

////
.**Операція з бізнес-правилами (Business Rule Task)**
* Валідація на основі таблиць прийняття рішень
* Розподіл задач між чиновниками

_Наприклад, створення бізнес-правила, що встановлює відповідність між задачею бізнес-процесу і чиновником -- хто має виконати цю задачу._

* Заповнити дані згідно з масками для кожного поля

_Наприклад, створення бізнес-правила, що перевіряє коректність введення._

* Скасування бізнес-процесу

_Наприклад, створення бізнес-правила, що скасовує бізнес-процес, якщо х днів не було дій з боку користувача._
////

[#useful-links]
== Корисні посилання

. https://docs.camunda.org/manual/latest/[Офіційне джерело Camunda].
. https://docs.camunda.org/manual/latest/modeler/bpmn/[Camunda Modeler BPMN].
. https://docs.camunda.org/manual/latest/modeler/dmn/[Camunda Modeler DMN].