@startsalt
{
{T
+ <&folder> registry-regulation
++ <&folder> bpmn
++ <&folder> dmn
++ ...
++ <&folder> <b>notifications</b>
+++ <&folder> templates
++++ <&folder> inbox (<i>channel</i>)
+++++ <&folder> excerpt-generated (<i>template_name</i>)
++++++ <&folder> ...
+++++ ...
++++ <&folder> email (<i>channel</i>)
+++++ <&folder> excerpt-generated (<i>template_name</i>)
++++++ <&file> ...
+++++ ...
++++ <&folder> diia (<i>channel</i>)
+++++ <&folder> excerpt-generated (<i>template_name</i>)
++++++ <&folder> ...
+++++ ...
}
}
@endsalt