= Horizontal scaling
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

//Реалізована горизонтально масштабована архітектура для бази даних _PostgreSQL_, призначена для динамічного додавання та видалення вузлів та дозволяє збільшувати продуктивність системи за потребою та економити ресурси, коли навантаження зменшується.
A horizontally scalable architecture implemented for the _PostgreSQL_ database supports dynamically adding and removing nodes, which enables you to increase system performance if needed and save resources when the load decreases.

//У цій архітектурі використовується _Crunchy PGO_ для управління _PostgreSQL_ та керування репліками "лише для читання", додаючи або видаляючи їх згідно з налаштуваннями.
Within this architecture, _Crunchy PGO_ manages _PostgreSQL_ and handles read-only replicas by adding or removing them according to the configuration.

//Додатково використовується _PgPool-II_ для маршрутизації всіх запитів до бази даних на відповідні вузли. _PgPool-II_ є потужним проміжним програмним забезпеченням, яке діє як проксі між клієнтами та вузлами бази даних _PostgreSQL_.
Additionally, _PgPool-II_ is used to route all requests to the database to the appropriate nodes. _PgPool-II_ is a powerful middleware that acts as a proxy between clients and _PostgreSQL_ database nodes.

//Всі запити на запис _PgPool-II_ відправляє до primary вузла, який відповідає за управління головною копією бази даних. У режимі синхронної реплікації всі репліки отримують запити та реплікують дані з первинного вузла. Це забезпечує, те що всі вузли мають однакові дані, і будь-які зміни, внесені в первинний вузол, з'являються на репліках в режимі реального часу.
_PgPool-II_ sends all write requests to the primary node, which manages the main copy of the database. In synchronous replication mode, all replicas receive requests and replicate data from the primary node. This ensures all nodes have the same data, and any changes made to the primary node appear on the replicas in real time.

//Для запитів, які не передбачають запис, _PgPool-II_ балансує навантаження між всіма вузлами. Це допомагає розподілити роботу між усіма вузлами та покращити загальну продуктивність та час відгуку системи.
For non-write queries, _PgPool-II_ balances the load across all nodes. This helps distribute load across all nodes and improves the overall system performance and response time.