= Processing analytical requests

include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

//Для обробки аналітичних запитів до БД реєстру архітектура передбачає окремий, аналітичний, екземпляр СКРБД.
Platform architecture provides a separate analytical DBMS instance for processing analytical requests to the registry database.

//Для передачі даних з операційної бази даних реєстру до аналітичної використовується логічна реплікація _PostgreSQL_. Вона підтримує синхронізацію даних в реальному часі з мінімальною затримкою, вибіркову реплікацію, гнучкість схеми аналітичної бази та має мінімальний вплив на продуктивність операційної бази даних.
Data is transferred from the registry operational database to the analytical database using _PostgreSQL_ logical replication. It supports real-time data synchronization with minimal latency, selective replication, and flexibility of the analytical database schema and has minimal impact on the performance of the operational database.

//Відокремлення бази даних для аналітичних робочих навантажень надає наступні можливості та переваги:
Using a separate database for analytical workloads provides the following capabilities and benefits:

//* Швидкість виконання запитів: Аналітичні робочі навантаження зазвичай включають складні запити та обробку великих наборів даних. З відокремленою базою даних, оптимізованою для аналітики, дані можуть бути структуровані та індексовані таким чином, що збільшують швидкість виконання запитів.
* Query speed: Analytical workloads typically involve complex queries and processing of large data sets. With a separate database optimized for analytics, data can be structured and indexed in ways that increase query performance.
//* Покращена масштабованість: Відокремлення аналітичного навантаження від операційного покращує масштабованість. Оскільки аналітичні запити зазвичай вимагають багато ресурсів, вони можуть сповільнювати інші процеси, які залежать від тієї ж бази даних. Шляхом відокремлення аналітичного навантаження, можливо масштабувати кожне навантаження незалежно, щоб задовольнити змінні вимоги.
* Enhanced scalability: Separating the analytical and operational workloads improves scalability. Because analytical queries are typically resource-intensive, they can slow down other processes that depend on the same database. By decoupling the analytical workload, it is possible to scale each workload independently to meet changing demands.
//* Зменшення ризику: Відокремлення аналітичного та операційного навантажень зменшує ризик відмови операційного екземпляру БД через помилки або проблеми з продуктивністю, пов'язані з аналітичними запитами.
* Reduced risk: Separating the analytical and operational workloads minimizes the risk of failure of an operational database instance due to errors or performance issues related to analytical queries.
//* Краще управління даними: Відокремлена аналітична база забезпечує чітке розмежування між операційними даними та аналітичними даними. Це полегшує забезпечення дотримання політик, пов'язаних із доступом до даних, безпекою та відповідністю.
* Better data management: A separate analytical database ensures a clear separation between operational and analytical data. This makes it easier to enforce policies related to data access, security, and compliance.