= Managing database users and schemas
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

//Облікові дані авторизації користувачів баз даних зберігаються у секретах Kubernetes.
Database user credentials are stored in Kubernetes secrets.

//Для керування змінами схеми використовується журнал змін _Liquibase_, який є повним списком усіх змін, внесених до схем баз даних. Цей журнал змін також містить інформацію про користувачів та привілеї, і використовує дані авторизації з секретів _Kubernetes_ для створення та зміни користувачів баз даних.
Schema changes are managed via the _Liquibase_ changelog, which contains a complete list of all changes made to database schemas. This changelog also includes information about users and privileges and uses authorization data from _Kubernetes_ secrets to create and modify database users.

//Усі журнали змін пакуються разом як задача _run-db-scripts_ під час релізу. Задача _run-db-scripts_ використовує _Liquibase_ для застосування журналів змін до бази даних.  Ця задача інтегрується в процес розгортання реєстру та виконується при кожному встановленні або оновленні реєстру. Це забезпечує однакове та автоматичне застосування будь-яких змін до схем баз даних чи привілеїв користувачів.
All changelogs are packaged together as a _run-db-scripts_ task at release time. The _run-db-scripts_ task uses _Liquibase_ to apply changelogs to the database. This task is integrated into the registry deployment process and is performed every time the registry is installed or updated. This ensures that changes to database schemas or user privileges are applied uniformly and automatically.

//В цілому, це рішення дозволяє ефективно та безпечно керувати користувачами та схемою бази даних, ведучи детальний журнал змін та автоматично виконуючи їх під час процесу розгортання.
Overall, this approach enables efficient and secure management of users and database schemas, keeping a detailed log of changes and automatically committing them during deployment.

[TIP]
--
//Із списком користувачів БД можна ознайомитися у розділі xref:arch:architecture/registry/operational/relational-data-storage/db-roles.adoc[Користувачі бази даних реєстру та їх привілеї].
For a list of available database user roles, see xref:arch:architecture/registry/operational/relational-data-storage/db-roles.adoc[]

//Із списком баз даних можна ознайомитися у розділі xref:arch:architecture/registry/operational/relational-data-storage/databases.adoc[Бази даних]
For a list of available databases, see xref:arch:architecture/registry/operational/relational-data-storage/databases.adoc[].

//Опис та схеми баз даних представлені у розділах відповідних підсистем яким належить БД.
For database description and schemas, refer to the sections of the subsystems to which the databases belong.
--