= Geographic objects and geolocation queries

include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

//Підтримка географічних об'єктів та геолокаційних запитів реалізована за допомогою розширення _PostGIS_
Support for geographic objects and geolocation queries is implemented via the _PostGIS_ extension.

//_PostGIS_ - це відкрите програмне забезпечення, розширення системи управління базами даних _PostgreSQL_. Воно дозволяє зберігати, обробляти та аналізувати географічні дані, такі як точки, лінії та полігони. _PostGIS_ надає широкий спектр функцій та операторів для роботи з просторовими даними, включаючи розрахунки відстаней, обчислення площі та просторові з'єднання.
_PostGIS_ is an open-source software extension of the _PostgreSQL_ database management system. It enables storing, processing, and analyzing geographic data such as points, lines, and polygons. _PostGIS_ provides various functions and operators for working with spatial data, including distance calculation, area calculation, and spatial connections.

//Ця функціональність зокрема використовується xref:arch:architecture/registry/operational/geo/overview.adoc[підсистемою управління гео-даними] для збереження, пошуку і візуалізації даних про географічні об'єкти.
In particular, this functionality is used by the xref:arch:architecture/registry/operational/geo/overview.adoc[_Geodata management subsystem_] to store, search, and visualize data about geographic objects.