@startuml
participant "Web Клієнт" as client  order 10
participant "Сервіс управління задачами" as service  order 20
participant "Cервіс виконання бізнес-процесів" as bpms order 30
skinparam responseMessageBelowArrow true

title Взяти задачу на виконання
  client -> service: Взяти задачу на виконання за ідентифікатором задачі
  activate service
  service -> bpms: Отримати задачу користувача за ідентифікатором
  activate bpms
  bpms -> service: Задача користувача, 200 OK
  deactivate bpms
  service -> service: Перевірити що задача не має assignee
  alt Задача вже має assignee
    service -> client: Помилка клієнта, 400 Bad Request
  end
  service -> service: Отримати username користувача з токену
  service -> bpms: Acигнувати задачу за ідентифікатором на користувача
  activate bpms
    bpms -> service: Задача призначена, 204 No content
  deactivate bpms
  service -> client: Задача призначена, 204 No content
  deactivate service
@enduml