@startuml
participant "Web Клієнт" as client  order 10
participant "Сервіс управління задачами" as service  order 20
participant "Cервіс виконання бізнес-процесів" as bpms order 30
skinparam responseMessageBelowArrow true

title Отримання переліку задач
  client -> service: Отримати перелік задач
  activate service
  service -> service: Отримати username користувача з токену
  service -> bpms: Отримати задачі без assignee або\nзадачі користувача
  activate bpms
  bpms -> service: Перелік задач користувача, 200 OK
  deactivate bpms
  service -> service : Додати атрибут assinged

  service -> bpms: Отримати ім'я послуг за ідентифікаторами послуг
  activate bpms
  bpms -> service: Ім'я послуг. 200 OK
  deactivate bpms
  service -> client: Перелік задач користувача
  deactivate service
@enduml