@startuml
participant "Web Клієнт" as client  order 10
participant "Сервіс управління задачами" as service  order 20
participant "Cервіс виконання бізнес-процесів" as bpms order 30
skinparam responseMessageBelowArrow true

title Отримання переліку виконаних задач
  client -> service: Отримати перелік виконаних задач
  activate service
  service -> service: Отримати username користувача з токену
  service -> bpms: Отримати виконані задачі за assignee
  activate bpms
  bpms -> service: Перелік виконаних задач користувача, 200 OK
  deactivate bpms
   service -> bpms: Отримати ім'я послуг за ідентифікаторами послуг
  activate bpms
  bpms -> service: Ім'я послуг. 200 OK
  deactivate bpms
  service -> client: Перелік виконаних задач користувача
  deactivate service
@enduml