@startuml
participant "Web Клієнт" as client  order 10
participant "Сервіс управління задачами" as service  order 20
participant "Cервіс виконання бізнес-процесів" as bpms order 30
skinparam responseMessageBelowArrow true

title Зняти задачу з виконання
  client -> service: Зняти задачу з виконання за ідентифікатором задачі
  activate service
  service -> bpms: Отримати задачу користувача за ідентифікатором
  activate bpms
  bpms -> service: Задача користувача, 200 OK
  deactivate bpms
  service -> service: Отримати username користувача з токену
  service -> service: Перевірити assignee задачі
  alt Задача призначена на іншого користувача
    service -> client: Помилка клієнта, 400 Bad Request
  end
  service -> bpms: Видалити assignee за ідентифікатором задачі
  activate bpms
    bpms -> service: Задача знята, 204 No content
  deactivate bpms
  service -> client: Задача знята, 204 No content
  deactivate service
@enduml