= Розрахунок вартості реєстру

== Типові конфігурації

При розгортанні реєстру за типовими шаблонами можна орієнтуватися на наступну вартість обчислювальних ресурсів.

|===
|Шаблон|Кількість ВМ|Сумарна вартість роботи ВМ, $ в год.|Сумарна вартість диску ВМ, $ в міс.|Сумарна вартість розподіленого сховища, $ в міс.|Сумарна вартість трафіку, $ в міс.|Вартість спільних сервісів, $ в міс.|Підсумкова вартість, $ в міс.

|Мінімальний|1|0.46|11.424|19.04|49.50|129.26|*319.62*
|Рекомендований|5|2.30|57.12|19.04|49.50|646.30|*1323.96*
|Великий|10|4.60|114.24|19.04|49.50|1292.61|*2579.39*
|===

[small]#Ціни дані за тарифами платформи хмарних обчислень Amazon Web Services на кінець 2022 р., за умови режиму роботи 12 годин на добу протягом робочого тижня.#


Більше деталей про те що входить у вартість можна знайти в електронній таблиці xref:attachment$/architecture/Розрахунок вартості реєстру.xlsx[розрахунок вартості реєстру] на сторінці _Калькулятор вартості_. 

== Калькулятор вартості

Для оцінки вартості ресурсів необхідних для роботи реєстру, який відповідає заданим вимогам, можна скористатися наступним калькулятором:

xref:attachment$/architecture/Розрахунок вартості реєстру.xlsx[Розрахунок вартості реєстру - Excel]

На сторінці _Вибір розміру реєстру_ в рядку _Ваш реєстр_ можна побачити результати розрахунку, а нижче, під результатом, вибір параметрів реєстру. 

=== Результати

Кількість ВМ:: Розрахована кількість віртуальних машин необхідна для роботи реєстру який відповідає заданим нижче параметрам.
Вартість:: Розрахована місячна вартість роботи за цінами платформи хмарних обчислень Amazon Web Services. Складається з вартості віртуальних машин необхідних для роботи реєстру та вартості користування спільними сервісами платформи реєстрів.

=== Вхідні параметри
==== Базові параметри

Режим високої доступності:: ?
Режим роботи:: Час коли реєстр працює.

==== Об'єм реєстру
Кількість бізнес сутностей:: Кількість таблиць в моделі даних реєстру
Максимальна кількість екземплярів бізнес сутностей (рядків в таблиці):: Кількість рядків у найбільшій таблиці реєстру.
Приблизний об'єм історичних даних в GB:: ?

==== Параметри реєстру
Наступні параметри задаються окреме для кожної з трьох категорій користувачів - посадові особи, громадяни, інші системи.

Кількість користувачів:: Кількість зареєстрованих користувачів які можу користуватися реєстром.
Кількість послуг (бізнес-процесів):: Кількість послуг які може надавати реєстр різним категоріям користувачів.
Середня кількість задач для користувачів на послугу:: ?
Середня кількість автоматизованих задач на послугу:: ?
Кількість звітів:: Загальна кількість змодельованих звітів, що використовуються посадовими особами.
Кількість витягів:: Загальна кількість змодельованих витягів.
Кількість надаваних послуг в місяць:: Загальна кількість всіх типів послуг надаваних протягом місяця.
