= Налаштування підключення для виклику зовнішніх SOAP-сервісів через ШБО "Трембіта"

Щоб мати змогу використовувати розроблені на Платформі SOAP-інтеграційні конектори до зовнішніх сервісів та отримувати інформацію від інших реєстрів через ШБО "Трембіта", необхідно попередньо виконати конфігурації на рівні регламенту реєстру.

Для цього потрібно налаштувати параметри `trembita-exchange-gateway` у конфігураційному файлі _bp-trembita/configuration.yml_.

.Приклад конфігурації підключення до сервісу ЄДР
[%collapsible]
====
[source,yaml]
----
trembita-exchange-gateway:
  registries:
    edr-registry:
      user-id: 'DDM'
      protocol-version: '4.0'
      trembita-url: 'https://trembita-edr-registry-mock.apps.envone.dev.registry.eua.gov.ua/mockEDRService'
      secret-name: 'trembita-registries-secrets'
      client:
        x-road-instance: 'SEVDEIR-TEST'
        member-class: 'GOV'
        member-code: '43395033'
        subsystem-code: 'IDGOV_TEST_01'
      service:
        x-road-instance: 'SEVDEIR-TEST'
        member-class: 'GOV'
        member-code: '00015622'
        subsystem-code: '2_MJU_EDR_prod'
----
====

.Приклад конфігурації підключення до сервісу ДРАЦС
[%collapsible]
====
[source,yaml]
----
trembita-exchange-gateway:
  registries:
    dracs-registry:
          trembita-url: 'https://trembita-dracs-registry-mock.apps.envone.dev.registry.eua.gov.ua/dracsMock'
          user-id: 'DDM'
          protocol-version: '4.0'
          client:
            x-road-instance: 'SEVDEIR-TEST'
            member-class: 'GOV'
            member-code: '43395033'
            subsystem-code: 'IDGOV_TEST_01'
          service:
            x-road-instance: 'SEVDEIR-TEST'
            member-class: 'GOV'
            member-code: '22956058'
            subsystem-code: 'TEST_DRAC'
----
====

.Приклад конфігурації підключення до сервісу ЄІБДВПО
[%collapsible]
====
[source,yaml]
----
trembita-exchange-gateway:
  registries:
    idp-exchange-service-registry:
        trembita-url: 'http://localhost:7780/trembita-mock-server'
        user-id: 'DDM'
        protocol-version: '4.0'
      client:
        x-road-instance: 'CLIENT-TEST'
        member-class: 'GOV'
        member-code: '666777666'
        subsystem-code: 'GOV_test'
      service:
        x-road-instance: 'IDP-TEST'
        member-class: 'GOV'
        member-code: '11115887'
        subsystem-code: 'IDP_test'
----
====

.Опис структурних параметрів
[width="100%",cols="30%,70%",options="header",]
|===
|Параметр|Опис

|registries|Назва реєстру, до якого буде сформовано запит
2+|_Заголовки, що ідентифікують користувача, який робить запит_
|trembita-url|Адреса до ШБО
|secret-name| Назва секрету. Регламент не повинен містити конфіденційних даних користувача. Токен авторизації `authorization-token` винесено за межі регламенту до налаштувань OpenShift.
|user-id|Ідентифікатор користувача, який ініціює запит
|protocol-version|Версія протоколу, за яким обмінюються повідомлення ШБО.

_На цей час версія протоколу 4.0_

2+|_Заголовок (client), який ідентифікує учасника сервісу_
|x-road-instance|Код середовища, який ідентифікує екземпляр учасника
|member-class|Ідентифікатор класу учасника
|member-code|Ідентифікатор учасника
|subsystem-code|Код, який ідентифікує підсистему учасника, якщо сервіс надається підсистемою

2+|_Заголовок (service), який ідентифікує сервіс_
|x-road-instance|Код середовища, який ідентифікує екземпляр сервісу
|member-class|Ідентифікатор класу сервісу
|member-code|Ідентифікатор сервісу
|subsystem-code|Код, який ідентифікує підсистему сервісу, якщо сервіс надається підсистемою
|===

[#list-of-services-trembita]
Перелік сервісів СЕВ ДЕІР "Трембіта", що використовуються на Платформі: ::

* Міністерство Юстицій:
** Єдиний державний реєстр (ЄДР):
*** link:https://directory-test.trembita.gov.ua:8443/SEVDEIR-TEST/GOV/00015622/2_MJU_EDR_prod/SearchSubjects[Сервіс пошуку суб'єкта в ЄДР (SearchSubjects)]
*** link:https://directory-test.trembita.gov.ua:8443/SEVDEIR-TEST/GOV/00015622/2_MJU_EDR_prod/SubjectDetail[Сервіс отримання детальної інформації про суб'єкта в ЄДР (SubjectDetail)]
** Державний реєстр актів цивільного стану (ДРАЦС):
*** link:https://directory-test.trembita.gov.ua:8443/SEVDEIR-TEST/GOV/00015622/3_MJU_DRACS_prod/GetCertByNumRoleNames[Сервіс отримання даних Свідоцтва про народження за вказаними серією і номером Свідоцтва та ПІБ (GetCertByNumRoleNames)]
*** link:https://directory-test.trembita.gov.ua:8443/SEVDEIR-TEST/GOV/00015622/3_MJU_DRACS_prod/GetCertByNumRoleBirthDate[Сервіс отримання даних Свідоцтва про народження за вказаними серією і номером Свідоцтва, та датою народження (GetCertByNumRoleBirthDate)]
* Міністерство Соціальної Політики:
** Єдина інформаційна база даних внутрішньо переміщених осіб (ЄІБДВПО):
*** link:https://directory-test.trembita.gov.ua:8443/SEVDEIR-TEST/GOV/37567866/51_IDP_prod/IDPexchangeService[Сервіс пошуку довідки ВПО (IDPexchangeService)]

[TIP]
====
Повний каталог вебсервісів системи ШБО "Трембіта", де можна отримати необхідні ідентифікатори, представлено за посиланнями:

* link:https://directory-test.trembita.gov.ua:8443/[Каталог вебсервісів (тестове середовище)]
* link:https://directory-prod.trembita.gov.ua:8443/[Каталог вебсервісів (промислове середовище)]
====