@startuml
!theme bluegray
|registry pipeline|
:**Create projects/codebases/repos**
rest-api
kafka-api
soap-api
model;
:**Create build pipelines**
rest-api
kafka-api
soap-api
model;
kill
|data-model pipeline|

:**Update DB schema**;
:**Update Version to {NewVer} in registry metadata**;
split
:**Generate code for //rest-api, kafka-api//**
**and //model// projects**;
split again
  if (Exposed Search Conditions exist?) then (yes)
    :**Generate code for //soap-api// project**;
  endif
end split;
:**Force push generated code**
**into static repos**;
:**Run Build pipelines for all generated projects**;
:**Overwrite or Create docker images in Nexus**

//{project-name}//;
#blue:**Clean up service's kafka topics**;
:**Deploy services**;

legend right
    |Name|Description|
    |{NewVer}|Deployment registry version|
    |{project-name}|Project/repository service name|
endlegend
@enduml