= Керування змінними середовища
:toc:
:toclevels: 5
:toc-title: ЗМІСТ
:sectnums:
:sectnumlevels: 5
:sectanchors:

== Загальний опис

Система надає можливість налаштування глобальних змінних для реєстру адміністратором регламенту.

Глобальні змінні є частиною регламенту та зберігаються у директорії з назвою _global-vars_.

Змінні налаштовуються у відповідних конфігураційних файлах із розширенням _.yml_.

Наразі глобальні змінні можуть бути використані для: ::

- налаштування шляху до фабрики даних (`dataFactoryBaseUrl`);
- налаштування Email служби підтримки (`supportEmail: support_test_mdtuddm@epam.com`).

== Формат глобальних змінних

Глобальні змінні мають наступний формат:

----
{Назва змінної}: параметр змінної
----

[TIP]
====
Наприклад, посилання до фабрики даних налаштовується у файлі _camunda-global-system-vars.yml_ і має наступний вигляд:

----
dataFactoryBaseUrl: http://registry-rest-api:8080
----
====

Конфігурація для Email служби підтримки також виконується у файлі _camunda-global-system-vars.yml_ і виглядає наступним чином:

----
supportEmail: some_email@somedomain.com
----

== Застосування глобальних змінних

Глобальна змінна `dataFactoryBaseUrl` застосовується у делегатах-конекторах до фабрики даних із підтримкою всіх CRUD операцій.

Змінна `supportEmail` використовується на сторінках усіх критичних помилок у Кабінетах посадової особи та отримувача послуг для відображення Email служби підтримки.