= Зменшення розміру файлу CACertificates.p7b
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Загальний опис

Файл CACertificates.p7b зберігає в собі сертифікати, що використовуються для валідації підписів/автентифікації користувачів в реєстрах Платформи. Даний файл зберігається в ресурсі Secret системи OKD(Kubernetes). З часом розмір цього файлу перевищив 1 МіБ, що створює проблему *«Secret exceeds max size»*, бо OKD(Kubernetes) дозволяє зберігати не більше 1 МіБ даних в цьому виді ресурсу.

Тому було створено інструкцію, яка пропонує розв'язання даної проблеми, шляхом зменшення розміру файлу CACertificates.p7b через його генерацію з попереднім видаленням старих сертифікатів.

== Передумови

- Середовище: Unix-подібна ОС, *bash*.

- Пакет: *openssl* ≥ 3.1.4

- Скрипт генерації CACertificates.p7b: link:{attachmentsdir}/otherl2/compile-p7b.zip[compile-p7b.zip]

== Виконання

=== Підготовка .cer

. Завантажте архів з скриптом генерації CACertificates.p7b та розпакуйте його. Створіть директорію *.cer* за шляхом знаходження скрипту генерації CACertificates.p7b.

. Завантажте архів із сертифікатами з IIT за link:https://iit.com.ua/download/productfiles/CACertificates.Test.All.zip[посиланням] та розпакуйте архів в директорію .cer за шляхом знаходження скрипту генерації CACertificates.p7b.

. Перевірте кожен сертифікат в директорії .cer на актуальність/необхідність та видаліть застарілі/непотрібні файли. Перевірити на файли можна двома шляхами:

.. Вручну:
+
1. Відкрити кожен сертифікат вручну через утиліту зчитування сертифікатів (на приклад у Windows) та перевірити, що поле “Valid from … to … ” є актуальним або чи є зазначений емітент необхідним.
+
2. Видалити неактуальні/непотрібні.

.. За допомогою скриптів у директорії .cer:
+
1. Відобразити всі неактуальні на сьогодні файли командою:
+
[source,bash]
----
for f in *.cer; do if [ "$(openssl x509 -inform der -in "$f" -noout -enddate | cut -d= -f2 | xargs -I{} date -d "{}" +%s)" -lt "$(date +%s)" ]; then echo "$f"; fi; done
----
+
2. Видалити неактуальні на сьогоднішні сертифікати наступною командою:
+
[source,bash]
----
for f in *.cer; do if [ "$(openssl x509 -inform der -in "$f" -noout -enddate | cut -d= -f2 | xargs -I{} date -d "{}" +%s)" -lt "$(date +%s)" ]; then rm "$f"; fi; done
----

=== Генерація CACertificates.p7b

. У директорії скрипту генерації надайте права на його виконання:
+
[source,bash]
----
chmod +x main.sh
----

. Запустіть скрипт:
+
[source,bash]
----
./main.sh
----
+
Результат — файл CACertificates.p7b у робочій папці.

. Переконайтесь, що його розмір ≤ 1000 КБ наступною командою:
+
[source,bash]
----
du -k CACertificates.p7b
----
+
Приклад виконання команди:
+
[source,bash]
----
$ du -k CACertificates.p7b
724    CACertificates.p7b
----
+
Якщо ліміт перевищено — видаліть ще сертифікати в кроці 3.1 та повторіть крок 3.2.

=== Опціонально: Редагування CAs.json

Якщо з директорії .cer видалено всі сертифікати окремого емітента:

. Завантажте актуальний CAs.json з IIT за link:https://iit.com.ua/download/productfiles/CAs.Test.All.json[посиланням].

. Видаліть записи вилучених емітентів, щоб уникнути некоректних посилань.

=== Перевірка працездатності згенерованого CACertificates.p7b

. Встановіть *CACertificates.p7b* (та, за потреби, *CAs.json*) на тестовий реєстр, таким чином запустивши build-pipeline реєстру.

.  Pod *digital-signature-ops* має перейти у *Running* без помилок.

Якщо підписи користувачів не проходять — перевірте, чи не видалено необхідний сертифікат, та повторіть генерацію.