= CD-процеси
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== EDP flow

=== Бібліотека
Найпростіший CI процес який зводиться до створення jar файлу та публікації його в Nexus

image::architecture/registry/administrative/regulation-publication/edp-lib-pipeline.svg[]

=== Додаток
Додатково до бібліотеки дозволяє збирати Docker image та публікувати його в registry. Окрім цього передбачено що кожен додаток розгортається за допомогою Helm chart який знаходиться в папці deploy-templates

image::architecture/registry/administrative/regulation-publication/edp-application-pipeline.svg[]

== Середовища розробки 

=== Інтеграція БД та АПІ для шаблонних сервісів

image::architecture/registry/administrative/regulation-publication/template-cd.svg[]

== Jenkins агент

image::architecture/registry/administrative/regulation-publication/jenkins-image.svg[]

== Розгортання реєстру (target)

image::architecture/registry/administrative/regulation-publication/target-cd.svg[]

== Перевірка змін

Фінальним артефактом який буде постачатись є https://gitbud.epam.com/mdtu-ddm/data-architecture/poc/devops-test/dataplatform-jenkins-agent[dataplatform-jenkins-agent]. Тому будь які зміни які вносяться в один з компонентів мають бути інтегровані та перевірені у зв'язці з іншими.

Агент складається з узгоджених версій:

* service-generation-utility
* службових структур для БД (процедури, історичні таблиці і т.п.)
* liquibase-ddm-ext
* blueprint-generator

Узгодження відбувається в Dockerfile.

Кроки для розгортання нової версії Дата Фабрики:

* зібрати змінений артефакт
* змінити версію в Jenkins агенті (Dockerfile)
* дочекатись зібраного артефакту
* змінити версію агента в Jenkins операторі https://gitbud.epam.com/mdtu-ddm/low-code-platform/platform/registry-regulations-publication/jenkins-operator/-/blob/master/deploy-templates/templates/jenkinsAgentsCm.yaml[ConfigMap] ключ: dataplatform-jenkins-agent-template
* дочекатись кінця збірки
* розгорнути дженкінс оператор в середовище розробки (dev. environment)
* розгорнути реєстр закомітивши регламент в gerrit
* перевірити що внесені зміни працюють (dev. testing)