= Підсистема цифрових підписів

== Загальний опис

Підсистема, яка реалізує пакет операцій по накладанню / перевірці цифрових печаток та перевірці цифрових підписів
з метою забезпечення контролю незмінності даних при міжсервісній взаємодії за допомогою спеціалізованих крипто-модулів.

== Функції підсистеми

* Отримання даних власника цифрового підпису
* Перевірка приналежності користувачу накладеного цифрового підпису даних
* Накладання цифрового підпису на дані що вносяться до реєстру або на цифровий документ електронною печаткою реєстру
* Перевірка приналежності накладеного електронної печатки реєстру

== Технічний дизайн підсистеми

image::architecture/registry/operational/digital-signatures/digital-signature-overview.drawio.svg[width=600,float="center",align="center"]

== Складові підсистеми

|===
|Назва компоненти|Представлення в реєстрі|Походження|Репозиторій|Призначення

|_Сервіс цифрових підписів_
|`digital-signature-ops`
|origin
|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/low-code-platform/platform/backend/applications/digital-signature-ops[gerrit:/mdtu-ddm/low-code-platform/platform/backend/applications/digital-signature-ops]
|Компонент цифрового підпису що використовує можливості бібліотеку цифрового підпису IIT Java та забезпечує функціонал
по роботі з цифровим підписом
|===

== Технологічний стек

При проектуванні та розробці підсистеми, були використані наступні технології:

* xref:arch:architecture/platform-technologies.adoc#java[Java]
* xref:arch:architecture/platform-technologies.adoc#spring[Spring]
* xref:arch:architecture/platform-technologies.adoc#spring-boot[Spring Boot]
* xref:arch:architecture/platform-technologies.adoc#spring-cloud[Spring Cloud]
* xref:arch:architecture/platform-technologies.adoc#eusigncp[EUSignCP-Java]

== Атрибути якості підсистеми

=== _Observability_

Підсистема цифрових підписів підтримує журналювання вхідних запитів та збір метрик продуктивності
для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--

=== _Portability_

Підсистема цифрових підписів може бути перенесена, розгорнута та керована однаково та надійно на різних платформах оркестрації контейнерів
що розгорнуті в різних хмарних середовищах або власній інфраструктурі в дата-центрі.

[TIP]
--
Детальніше можна ознайомитись у розділі xref:arch:architecture/container-platform/container-platform.adoc[Платформа оркестрації контейнерів]
--

=== _Interoperability_

Підсистема цифрових підписів здатна легко інтегруватися та працювати з іншими підсистемами та зовнішніми
системами такими як АЦСК використовуючи стандартні протоколи зв'язку. Це гарантує, що цифрові підписи, які створюються
підсистемою, можуть бути перевірені та довірені будь-яким отримувачем або сторонньою системою,
покращуючи загальну надійність та відповідність підписаних документів.

=== _Security_

Підсистема цифрових підписів використовує бібліотеку цифрового підпису IIT Java яка має позитивні експертні https://iit.com.ua/download/productfiles/EU13Conclusion.jpg[висновки] за результатами державної
експертизи у сфері КЗІ та може безкоштовно використовуватися у будь-яких прикладних системах без обмежень.

=== _Scalability_

Підсистема цифрових підписів підтримує як горизонтальне, так і вертикальне масштабування.
[TIP]
--
Детальніше з масштабуванням підсистем можна ознайомитись у розділі xref:architecture/container-platform/container-platform.adoc[]
--
