:sectlinks:
:sectanchors:
= Користувачам

Розділ *_Користувачам_* надає всебічні посібники та настанови, які адаптовані для кінцевих користувачів нашої системи. Цей розділ поділений на дві основні категорії:

Посадові особи та надавачі послуг ::
* [*] Ознайомтеся з _Кабінетом користувача_.
* [*] Дізнайтеся, як _формувати витяги_ *DOCX* та *CSV* для отримання важливої інформації.
* [*] Ефективно керуйте даними за допомогою технік _сортування та пагінації_.

Громадяни та отримувачі послуг ::
* [*] Зануртеся в _Огляд порталу громадянина_, та дізнайтеся більше про функціональність для громадян.
* [*] Отримайте знання про _Формування витягів у форматі **PDF**_ для легкого обміну та друку.
* [*] Дізнайтеся про *_Відправлення повідомлень користувачам_*.
* [*] Використовуйте можливості *_сортування та пагінації_* для кращого управління даними.

Додатково користувачі можуть заглибитися в загальну категорію ::

* [*] _Аутентифікація користувача у реєстрі_ допоможе зрозуміти протоколи безпеки та входу, а також принципи автентифікації користувачів.
* [*] _Звернення до підтримки_ для отримання негайної допомоги або консультацій.
* [*] _Файли_ для генерації та роботи з документами у різних форматах.
* [*] Будьте в курсі завдяки _сповіщенням про успішне завершення завдань в порталах користувача_.
* [*] Переконайтеся у точності своїх дій за допомогою _попереджувальних вікон для підтвердження дій у порталах користувача_.

Цей розділ створено для того, щоб надати користувачам чіткий курс, який допоможе їм швидко та ефективно орієнтуватися у функціях Платформи.

== Огляд секції

[%collapsible]
.*Посадові особи та надавачі послуг*
====
* xref:user:officer/officer-portal-overview.adoc[Огляд Кабінету користувача]
* xref:user:officer/reports/overview.adoc[Формування витягів]
* xref:user:officer/overview.adoc[Сортування та пагінація]
====

[%collapsible]
.*Громадяни та отримувачі послуг*
====
* xref:user:citizen/citizen-portal-overview.adoc[Огляд Кабінету отримувача послуг]
* xref:user:citizen/citizen-get-excerpts.adoc[Формування витягів у форматі PDF]
* xref:user:citizen/user-notifications/user-notifications-overview.adoc[Відправлення повідомлень користувачам]
* xref:user:citizen/sorting-pagination/citizen-portal-bp-sorting-pagination.adoc[Сортування та пагінація]
====

[%collapsible]
.*Загальний розділ для користувачів*
====
* xref:user:citizen-officer-portal-auth.adoc[Автентифікація користувачів у реєстрі]
* xref:user:error-email-support.adoc[Звернення до підтримки]
* xref:user:bp-files/upload-multiple-files-p7s-asic.adoc[Файли]
//* xref:user:bp-files/editgrid-file-download.adoc[]
* xref:user:user-notifications-success-task.adoc[Нотифікації про успішне виконання задач]
* xref:user:alerting-popups.adoc[Системні попереджувальні вікна для підтвердження дій]
====

