= Структура компонента
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Взаємодія із сервісами Платформи

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/business-process-administration-portal.svg[]

[NOTE,caption="Критичні залежності"]
_База даних Postgres_, піднята на іншому поді (`citus-master`), впливає на всю функціональність вебсервісу.

== Модульна/структурна діаграма

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/microservice-internals.svg[]

- Camunda authorization + Spring Security + Keycloak Plugin - для авторизації використовується механізм авторизації Camunda у зв'язку з Spring Security та Keycloak Plugin
- Camunda REST API + Spring Web - Web доступ до ресурсів Camunda
- Postgres - Використання бази даних Postgres
- Cockpit - використовується для моніторингу та операцій
- Tasklist - дозволяє працювати над користувацькими задачами
- Admin - використовується для настройки користувачів і груп
- Зовнішні залежності:
* Spring Cloud Kubernetes/Config - надає можливість конфігурувати сервіс через Config Map, Secrets
* Spring Boot Actuator - моніторинг
* SLF4J/Log4J - логування

[NOTE]
Детальніше ознайомитися зі стеком технологій можна на сторінці xref:arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/technologies.adoc[Технологічний стек].
