= Структура компонента

== Взаємодія з сервісами платформи

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/business-process-administration-portal.svg[]

.Критичні залежності:
* *База даних Postgres* -  яка піднята у іншій поді (citus-master), впливає на весь функціонал веб-сервісу.

== Модульна / структурна діаграма

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/microservice-internals.svg[]

- Camunda authorization + Spring Security + Keycloak Plugin - для авторизації використовується механізм авторизації Camunda у зв'язку з Spring Security та Keycloak Plugin
- Camunda REST API + Spring Web - Web доступ до ресурсів Camunda
- Postgres - Використання бази даних Postgres
- Cockpit - використовується для моніторингу та операцій
- Tasklist - дозволяє працювати над користувацькими задачами
- Admin - використовується для настройки користувачів і груп
- Зовнішні залежності:
* Spring Cloud Kubernetes/Config - надає можливість конфігурувати сервіс через Config Map, Secrets
* Spring Boot Actuator - моніторинг
* SLF4J/Log4J - логування

[NOTE]
Більш детальніше ознайомитися зі стеком технологій можна xref:arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/technologies.adoc[тут]
