= Функціональні можливості сервісу
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Стартова сторінка сервісу адміністрування бізнес-процесів:

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/camunda-welcome.svg[]

.Сервіс надає наступний функціонал:
- Camunda Cockpit https://business-proc-admin-lowcode-dev-dev.apps.cicd2.mdtu-ddm.projects.epam.com/camunda/app/cockpit/default/#/dashboard[lowcode-dev-cicd2-env-cockpit] - дозволяє відстежувати робочі процеси і рішення у виробництві, щоб виявляти, аналізувати і вирішувати технічні проблеми. Більш детальніше можна ознайомитися https://docs.camunda.org/manual/7.14/webapps/cockpit/[тут]
- Camunda Admin https://business-proc-admin-lowcode-dev-dev.apps.cicd2.mdtu-ddm.projects.epam.com/camunda/app/admin/default/#/[lowcode-dev-cicd2-env-admin]  - надає можливість налаштовувати користувачів і групи. Більш детальніше можна ознайомитися https://docs.camunda.org/manual/7.14/webapps/admin/[тут]
- Camunda Tasklist https://business-proc-admin-lowcode-dev-dev.apps.cicd2.mdtu-ddm.projects.epam.com/camunda/app/tasklist/default/#/?searchQuery=%5B%5D[lowcode-dev-cicd2-env-tasklist] - дозволяє кінцевим користувачам працювати над призначеними на них задачами. Більш детальніше можна ознайомитися https://docs.camunda.org/manual/7.14/webapps/tasklist/[тут]

== Основні сценарії:

=== Надання прав доступу користувачу у Camunda Admin

- У головному вікні Camunda Admin потрібно перейти на вкладку `Authorizations`

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/admin-main.svg[]

- Після чого, з приведеного переліку вибираємо потрібний нам розділ та переходимо на нього, наприклад `Deployment`

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/admin-deployment-auth.svg[]

- В правому куті потрібно натиснути кнопку `Create new authorization`

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/admin-create-auth.svg[]

- В полях для вводу потрібно заповнити користувача або групу, після чого вибрати з переліку потрібні права та підтвердити введені дані.

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/admin-add-auth.svg[]

- Як рузультат з'явиться новий запис, який надалі ми можемо редагувати або видалити.

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/admin-result.svg[]

[NOTE]
Більш детально про управління авторизацією можна ознайомитися https://docs.camunda.org/manual/7.14/webapps/admin/authorization-management/#application-access[тут]

=== Призначення задачі користувачу у Camunda Cockpit

- На головній сторінці Camunda Cockpit потрібно перейти на вкладку `Processes`

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/cockpit-main.svg[]

- Та вибрати з переліку потрібний бізнес-процес

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/cockpit-processes.svg[]

- Після чого, потрібно вибрати потрібний ідентифікатор єкземпляра процесу

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/cockpit-process-instance.svg[]

- Перейти на вкладку `User Task`

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/cockpit-user-task.svg[]

- У полі `Assignee` визначити користувача який буде виконувати цю задачу

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/cockpit-task-assign.svg[]

- Як результат побачимо, що для даної задачі користувач був визначений

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/cockpit-task-assign-result.svg[]

=== Призупинення бізнес-процесу у Camunda Cockpit

- На головній сторінці Camunda Cockpit потрібно перейти на вкладку `Processes`

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/cockpit-main.svg[]

- Та вибрати з переліку потрібний бізнес-процес

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/cockpit-processes.svg[]

- Після чого, у правому куті потрібно натиснути на кнопку як показано нижче:

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/stop-bp.svg[]

- Та підтвердити призупинення:

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/confirm-stop-bp.svg[]

- Отримаемо повідомлення про призупинення бізнес-процеса, натискаємо кнопку `OK`

image::arch:architecture/registry/administrative/operational-maintenance/services/business-process-administration-portal/stop-bp-result.svg[]

