@startuml
skinparam monochrome true

actor "Користувач" as user
participant "Клієнтський додаток\n кабінету користувача" as cabinet
participant "Kong \nAPI Management" as kong
participant "Сервіс \nцифрових документів" as digital_documents
participant "Об'єктне сховище Ceph \n(бакет: lowcode-file-storage)" as file_storage_ceph
participant "Сервіс управління \n задачами користувача" as user_task_mngmnt
participant "Сервіс виконання бізнес-процесів" as bpms
participant "Об'єктне сховище Ceph \n(бакет: lowcode-form-data-storage)" as form_data_ceph

skinparam responseMessageBelowArrow false
title Завантаження та використання файлів в рамках виконання задач користувачів

user -> cabinet: Перехід до виконання задачі \nдодавання файлових вкладень через UI-форму
return

user -> cabinet: Завантаження файлових вкладень\n через окрему UI-компоненту форми задачі
activate cabinet
  cabinet -> kong: Запит на завантаження файлу: \nPOST "/documents/{processInstanceId}/{taskId}/{fieldName}" \n* Ідентифікатор сесії Kong; \n* Мета-атрибути файлу; \n* Бінарний контент файлу;
  activate kong
    kong -> digital_documents: Запит на завантаження файлу: \nPOST "/documents/{processInstanceId}/{taskId}/{fieldName}" \n* X-Access-Token; \n* Мета-атрибути файлу; \n* Бінарний контент файлу;
    digital_documents -> digital_documents: Авторизація доступу до виконання операції
    digital_documents -> digital_documents: Валідація цифрового документу
    digital_documents -> digital_documents: Підготовка цифрового документу
    digital_documents -> file_storage_ceph: Збереження цифрового документу \n* Ключ: <process/{processInstanceId}/{UUID}>
    file_storage_ceph --> digital_documents
    digital_documents -> kong: Повернення мета-даних новоствореного документу
    note left
      {
          "id": "{UUID}",
          "name": "{filename}",
          "type:": "{mime-type}",
          "size": 1000,
          "checksum": "{sha256-hash}",
          "url": "https://.../documents/{processInstanceId}/{taskId}/{fieldName}/{id}"
      }
    end note
    kong --> cabinet: Повернення мета-даних новоствореного документу
  deactivate kong
return Повернення управління користувачу

user -> cabinet: Підтвердження виконання задачі внесення даних
activate cabinet
  cabinet -> cabinet: Клієнтська валідація даних форми

  cabinet -> cabinet: Приведення значень полів типу "File" згідно контракту \nвзаємодії з серверним додатком
  note left
    {
      "data": {
        "<file_property_name>": [
          {
            "id": "{UUID}",
            "checksum": "{SHA256-hash}"
          }
        ]
      }
    }
  end note

  cabinet -> kong: Підтвердження виконання задачі: POST "/task/{id}/complete" \n*Ідентифікатор сесії Kong \n*Дані форми з Ceph-посиланнями на файлові вкладення
  activate kong
    kong -> user_task_mngmnt: Підтвердження виконання задачі: POST "/task/{id}/complete" \n* X-Access-Token \n*Дані форми з Ceph-посиланнями на файлові вкладення
    activate user_task_mngmnt
      user_task_mngmnt -> user_task_mngmnt: Перевірка відповідності Assignee задачі\n поточному користувачу
      user_task_mngmnt -> user_task_mngmnt: Встановлення X-Access-Token \nдля JSON-документа даних форми

      user_task_mngmnt -> user_task_mngmnt: Генерація ідентифікатора Ceph-документа \nдля подальшого збереження даних \n(processInstanceId, taskDefinitionKey)
      user_task_mngmnt -> form_data_ceph: Збереження JSON-документа даних форми \n* Назва документа \n* JSON-документ даних форми з UUID файлів
      note right
        {
          "data": {
            "<file_property_name>": [
              {
                "id": "{UUID}",
                "checksum": "{SHA256-hash}"
              }
            ]
          },
          "x-access-token": "{X-Access-Token}"
        }
      end note

      form_data_ceph --> user_task_mngmnt

      user_task_mngmnt -> bpms: Підтвердження виконання задачі
      activate bpms
        bpms -> form_data_ceph: Отримання JSON-документа даних UI-форми \nза ідентифікатором задачі
        form_data_ceph --> bpms: JSON документ з UUID файлів
        bpms -> bpms: Підготовка даних для попереднього заповнення форми \nнаступної задачі перегляду файлових вкладень
        bpms -> form_data_ceph: Збереження JSON-документа даних UI-форми \nдля наступної задачи
        note right
          {
            "data": {
              "<file_property_name>": [
                {
                  "id": "{UUID}",
                  "checksum": "{SHA256-hash}"
                }
              ]
            }
          }
        end note

        form_data_ceph --> bpms
        bpms -> bpms: Перехід до очікування виконання наступної задачі
      return Повернення управління
      user_task_mngmnt --> user: Повернення управління користувачу
    deactivate
  deactivate
deactivate

@enduml