= Monitoring Platform systems (Grafana)
:sectlinks:
:sectanchors:

include::platform:ROOT:partial$admonitions/language-en.adoc[]

_Monitoring_ is a critical element of the effective operation of any IT platform. To ensure complete control over the functioning of our systems and to detect and remedy potential problems, we employ a powerful monitoring tool -- *_Grafana_*.

In Grafana, we've designed various dashboards that allow us to configure and track key performance indicators, including:

* The operation different Platform components (like Camunda or Strimzi Kafka);
* The status of databases and file system (e.g., PostgreSQL or Ceph cluster);
* Metrics and request statistics in Public API Kong;
* Analytical data via Redash;
* Cache memory status using Redis;
* Metrics from Spring Boot, Prometheus, and others.

These dashboards provide an in-depth analysis of our Platform's operation and the registries deployed on it. This aids us in ensuring stability and productivity and identifying potential deviations or issues before they become critical.

TIP: A complete list of available monitoring dashboards can be found on the page xref:arch:architecture/platform/operational/monitoring/overview.adoc[].

== Section overview

//* xref:registry-develop:registry-admin/grafana-monitoring/grafana-alerting-notifications.adoc[]
* xref:registry-develop:registry-admin/grafana-monitoring/grafana-camunda-metrics.adoc[]
* xref:registry-develop:registry-admin/grafana-monitoring/public-api-kong-metrics.adoc[]
