= Platform deployment architecture
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

The Registries Platform installation procedure is the responsibility of the xref:architecture/platform-installer/overview.adoc[Component for managing the state of Platform resources]. This Component is designed with consideration for compatibility between different infrastructure providers.

The installation procedure of the OpenShift container orchestration Platform is the responsibility of the https://github.com/okd-project/okd/releases[OKD installer] developed and supplied by RedHat.

[TIP]
--
For more information about the _OpenShift container orchestration Platform_ and the _Registry Platform_, see the relevant sections:

* xref:admin:installation/platform-deployment/platform-deployment-overview.adoc[Deploying the Platform of target environment]

For more details about the technical design of the subsystems and components engaged in the installation process, see the following sections:

* xref:architecture/platform-installer/overview.adoc[Component for managing the state of Platform resources]
* xref:architecture/container-platform/container-platform.adoc#_portability[Container orchestration platform]
--

The diagram below depicts the Registries Platform's infrastructure deployment in one region (AZ) of the AWS public cloud environment.

.Platform architecture on AWS
image::architecture/ddm-platform-infrastructure-deployment.drawio.svg[]
