= Platform logical architecture
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== Overview

The _Registries Platform_ is a distributed system with microservice architecture. Its design is based on the following fundamental ideas:

* Deployment infrastructure agnosticism

* Centralized development and updating

* Provision of _sufficient_ level of registry isolation

* Joint (_re-_)use of typical services by the registries

* Usage of secure transport for integrations

* Registry compliance with security, scalability and fault-tolerance requirements

== Architecture principles

* The _Registries Platform_ is built using open standards based on open-source technologies.

* The _Registries Platform_ is a distributed system with microservice architecture, where each component has a defined function, and inter-component interaction is based on standardized data exchange protocols.

The _Registries Platform_ is a _Cloud_native_ system based on the _OpenShift_ container orchestration platform to ensure reliability, scalability, and infrastructure agnosticism.

* The _Registries Platform_ uses _GitOps_-approach to automatize infrastructure configuration, component deployment, and the system as a whole.

* The _Registries Platform_ is based on _Zero-Trust_ security principles to ensure protected inter-service interaction with mandatory authentication, authorization, and traffic encryption.

* External access to the _Registries Platform_ components is provided via _API_-gateway with mandatory authentication and authorization.

* The _Registries Platform_ components use a standardized approach to monitoring metrics exporting, business-transactions data tracing, and event logging.

* The _Registries Platform_ component instances don't store critical data on the system state or any user session data in the memory.

* All user actions with the data and system-critical events of the _Registries Platform_ are subject to mandatory recording in an audit log.

* Registry business data deployed on the _Registries Platform_ are subject to mandatory encryption for long-term storing.

== High-level structure

This structure diagram shows the decomposition of the _Registries Platform_ on the _zone_ and _subsystem levels_, and the general interaction scenarios.

A separate system level may contain two zones with subsystems responsible for servicing administration and operational traffic.

The subsystems consist of services that address both functional and non-functional requirements.


image::architecture/ddm-platform-structural-view.svg[]

=== _Infrastructure_

The _Registries Platform_ supports deployment in public and private cloud environments.

=== _Container orchestration platform_

[TIP]
--

You can learn more about the container orchestration platform here:

* xref:architecture/container-platform/container-platform.adoc[]
--

=== _Central components of the Platform_

Every _Registries Platform_ instance includes a level of _Central components of the Platform_ and comprises two logical zones:

* xref:architecture/platform/administrative/overview.adoc[] -- subsystems that provide administrative functions for the Platform instance and the registries deployed in it

* xref:architecture/platform/operational/overview.adoc[] -- subsystems that provide general functions for the joint platform usage

=== _Registries_

One _Registries Platform_ instance can service a group of isolated registries. Two separate zones present each registry tenant:

* xref:architecture/registry/administrative/overview.adoc[] -- subsystems that provide development functions, deployment functions, and the service of digital registry regulations

* xref:architecture/registry/operational/overview.adoc[] -- subsystems that provide the functioning of the registry according to the deployed digital regulations

=== _Component for managing the state of platform resources_

[TIP]
--
You can learn more about the Platform resource state management component here:

* xref:architecture/platform-installer/overview.adoc[]
--

== Technology stack
The following high-level diagram displays the key technologies and their usage in realizing functional and non-functional requirements of the _Registries Platform_.

[TIP]
--
The complete list of technologies used in the _Registries Platform_ development can be found xref:architecture/platform-technologies.adoc[here].
--

image::architecture/ddm-platform-tech-view.drawio.svg[]