= Platform conceptual architecture
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== General context

This contextual diagram shows the _Platform for state registries_ in the ecosystem of the interfaced national information systems, and categories of users interacting with the system.

For interoperability purposes, the _Platform for state registries_ supports two main options for configuring data exchange:

* Using the Trembita safe exchange bus as a protected transport.
* Setting up direct integrations based on the _REST_ and _SOAP_ interaction protocols for the systems that are not participants of data exchange under _Trembita SEI SEIR_.

For integration purposes, the external systems can be both existing information systems and the registers deployed on the individual instances of the _Platform for state registries_.

image::architecture/ddm-platform-context.svg[]

[TIP]
--
You can learn more about the technical design of the _Platform for state registries_ in xref:arch:architecture/platform-logical.adoc[].
--

== Platform users

The main users of the _Platform for state registries_ can be divided into the following categories depending on the scenarios of their interaction with the system and access rights:

* _Unauthorized users_: The users with access only to public data and the authentication page.
* _Citizens_: Natural persons or legal entities who passed authentication and self-registration in the register to have access to electronic services.
* _Officers_: Official representatives of government bodies providing services under their official duties, or the entities registered as service providers (depending on the requirements of an individual register).

* _Developers of the Registry Regulations_: The users responsible for the _Lowcode_ development of the xref:arch:architecture/registry/administrative/regulation-management/registry-regulation/registry-regulation.adoc[Digital registry regulations]

* _Support Service (L2)_: The users responsible for monitoring of the system's technical metrics, incident response.
* _Service administrators_: A category of users responsible for maintaining and configuring registry instances.
* _Infrastructure administrators_: A category of users responsible for the installation and maintenance of the _Platform for state registries_.

[TIP]
--
You can find out more about the user categories of the _Platform for state registries_ in xref:arch:architecture/platform/operational/user-management/platform-actors-roles.adoc[].
--

== Interaction with external systems

=== Accredited Key Certification Center (AKCC)

The _Platform for state registries_ interacts with _Accredited Key Certification Centers_ for obtaining lists of revoked certificates, receiving a chain of user certificates and checking their status, forming a time stamp, etc.

[TIP]
--
You can learn more about the design of the integrated subsystems in the relevant sections:

* xref:arch:architecture/registry/operational/digital-signatures/overview.adoc[]
* xref:arch:architecture/platform/operational/user-management/overview.adoc[]
--

=== _Digital identification service (id.gov.ua)_

include::ROOT:partial$admonitions/ua-specific.adoc[]

The _Platform for state registries_ allows authentication of citizens and officers -- the registry service users -- using the _Integrated Electronic Identification System (IEIS)_.

////
[TIP]
--
You can learn more about the design of the integrated subsystems in the relevant sections:

* xref:arch:architecture/platform/operational/user-management/overview.adoc[]
--
////

=== _Trembita SEI SEIR_

include::ROOT:partial$admonitions/ua-specific.adoc[]

The _Platform for state registries_ is integrated into the _Trembita System of Electronic Interaction of State Electronic Information Resources (SEI SEIR)_ to ensure secure data exchange with the state registers and other information systems.

[TIP]
--
You can learn more about the design of the integrated subsystems in the relevant sections:

* xref:arch:architecture/platform/operational/user-management/overview.adoc[]
* xref:arch:architecture/registry/operational/bpms/overview.adoc[]
* xref:arch:architecture/registry/operational/external-integrations/overview.adoc[]
//* xref:arch:architecture/data-exchange/overview.adoc[]
--

=== _Diia services (diia.gov.ua)_

include::ROOT:partial$admonitions/ua-specific.adoc[]

The _Platform for state registries_ is integrated with the ecosystem of digital public services _Diia_ to improve and ensure the integrity of the end-users' experience when receiving public services.

////

[TIP]
--
You can learn more about the design of the integrated subsystems in the relevant sections:

* xref:arch:architecture/registry/operational/notifications/overview.adoc[]
--
////

=== _External mapping services_

The _Platform for state registries_ uses external cartographic services to download geospatial data, layers, and geocoding to provide the ability to enter, search and display the register subjects that are connected to an area.

[TIP]
--
You can learn more about the design of the integrated subsystems in the relevant sections:

* xref:arch:architecture/registry/operational/geo/overview.adoc[]
--

=== _External systems_

The _Platform for state registries_ supports external integrations via _Trembita SEG_, or direct integrations according to the requirements of the target registers and the level of interoperability of external systems.

[TIP]
--
You can learn more about the design of the integrated subsystems in the relevant sections:

* xref:arch:architecture/registry/operational/external-integrations/overview.adoc[]
* xref:arch:architecture/registry/operational/bpms/overview.adoc[]
--