= Схема бази даних audit

[plantuml, audit-schema, svg]
----
@startuml
hide circle
skinparam linetype ortho
skinparam monochrome true

entity "**audit_event**" {
  + ""id"": //text [PK]//
  --
  *""request_id"": //text //
  *""application_name"": //text //
  *""name"": //text //
  *""type"": //text //
  *""timestamp"": //timestamp without time zone //
  ""user_keycloak_id"": //text //
  ""user_name"": //text //
  ""user_drfo"": //text //
  ""source_system"": //text //
  ""source_application"": //text //
  ""source_business_process"": //text //
  ""source_business_process_definition_id"": //text //
  ""source_business_process_instance_id"": //text //
  ""source_business_activity"": //text //
  ""source_business_activity_id"": //text //
  ""context"": //text //
  *""received"": //timestamp without time zone //
}
@enduml
----
.Умовні позначення
[%collapsible]
====
include::partial$\architecture-workspace\documentation-templates\component-design-template\db-schema-legend.adoc[]
====
== audit_event
Подія аудиту

[options="header",cols="a"]
|======
|Ім'я колонки +
Опис
| `*id* _text_ *(PK)*` + 
Ідентифікатор події в БД 
| `*request_id* _text_` + 
Ідентифікатор запиту з MDC 
| `*application_name* _text_` + 
Назва додатку, який генерує подію 
| `*name* _text_` + 
Назва події 
| `*type* _text_` + 
Тип події 

* USER_ACTION - дія користувача
* SECURITY_EVENT - події аутентифікації, авторизації та перевірки підпису
* SYSTEM_EVENT - системна подія
| `*timestamp* _timestamp without time zone_` + 
Час, коли сталась подія 
| `user_keycloak_id _text_` + 
Ідентифікатор користувача 
| `user_name _text_` + 
ПІБ користувача, з яким асоційована подія 
| `user_drfo _text_` + 
ДРФО користувача 
| `source_system _text_` + 
Назва системи 
| `source_application _text_` + 
Назва додатку 
| `source_business_process _text_` + 
Назва бізнес процесу 
| `source_business_process_definition_id _text_` + 
Ідентифікатор типу бізнес процесу 
| `source_business_process_instance_id _text_` + 
Ідентифікатор запущеного бізнес процесу 
| `source_business_activity _text_` + 
Назва кроку в бізнес процесі 
| `source_business_activity_id _text_` + 
Ідентифікатор кроку в бізнес процесі 
| `context _text_` + 
JSON представлення деталей події 
| `*received* _timestamp without time zone_` + 
Час, коли повідомлення було записано в БД 

|======