== Аудит

=== Компоненти аудиту

image::architecture/registry/operational/audit/high-level-audit.svg[]


Всі аудито-важливі події фіксуються як події додатку (Application Events), за опрацювання цих подій відповідальна audit-lib бібліотека. 

Всі події опрацьовуються асинхронно і не вносять значний вплив на швидкодію основних сценаріїв додатків.

Запис в БД відбувається за допомогою Kafka https://kafka.apache.org/documentation.html#connect[connect-api], що дозволяє виділити опрацювання повідомлень подій в окремий додаток, який використовує вбудований інструментарій Kafka.
Використовується https://docs.confluent.io/kafka-connect-jdbc/current/sink-connector/index.html[Confluent JDBC Sink]

=== База даних та користувачі для доступу
БД  *<назва реєстру>_audit*  створюється окремо на кроці створення БД з Helm Chart'у

Користувач *audit_service_user* має доступ до <<_структура_події, таблиць>> де зберігаються всі події аудиту, права лише на вставку даних.


== Події
=== Структура події
[plantuml, event, svg]
----
@startuml
skinparam monochrome true

map Context {
  step => ...
  action => ...
  ... => ...
}
map Event {
  requestId => ідентифікатор запита з MDC
  name => назва події
  applicationName => назва додатку який генерує подію
  sourceSystem => ім'я системи з заголовків запиту
  sourceApplication => ім'я додатку з заголовків запиту
  sourceBusinessProcess => назва бізнес процесу з заголовків запиту
  sourceBusinessProcessDefinitionId => ідентифікатор типу бізнес процесу з заголовків запиту
  sourceBusinessProcessInstanceId => ідентифікатор запущеного бізнес процесу з заголовків запиту
  sourceBusinessActivity => назва кроку в бізнес процесі з заголовків запиту
  sourceBusinessActivityId => ідентифікатор кроку в бізнес процесі з заголовків запиту
  type => тип події SECURITY_EVENT/USER_ACTION
  timestamp => час коли сталась подія
  userName => ФІО користувач з яким асоційована подія
  userKeycloakId => ідентифікатор користувача
  userDrfo => ДРФО користувача
  context *-> Context
}
@enduml
----

=== Структура таблиці для збереження

[plantuml, table, svg]
----
@startuml
skinparam monochrome true

map Table {
  id => (uuid) ідентифікатор події в БД
  request_id => (uuid) ідентифікатор запита з MDC
  name => (varchar) назва події
  type => (varchar) тип події
  application_name => (varchar) назва додатку який генерує подію
  source_system => (varchar) ім'я системи
  source_application => (varchar) ім'я додатку
  source_business_process => (varchar) назва бізнес процесу
  source_business_process_definition_id => (uuid) ідентифікатор типу бізнес процесу
  source_business_process_instance_id => (uuid) ідентифікатор запущеного бізнес процесу
  source_business_activity => (varchar) назва кроку в бізнес процесі
  source_business_activity_id => (uuid) ідентифікатор кроку в бізнес процесі
  user_name => (varchar) ФІО користувач з яким асоційована подія
  user_keycloak_id => (uuid) ідентифікатор користувача
  user_drfo => (varchar) ДРФО користувача
  context => (varchar) JSON представлення деталей події,
  timestamp => (timestamp) час коли сталась подія
  received => (timestamp default now()) час коли повідомлення було записано в БД
}
@enduml
----

=== Основні події

Аудиту підлягають операції користувача в системі та окремі події системи.
Операції користувача фіксуються на початку операції на етапі звернення до сторонніх ресурсів системи (БД, Ceph) та в кінці операції.
Події системи фіксуються лише раз - в момент і в місці виникнення події. 

==== Операції користувача
* Спроба\Створення нового запису в БД
* Спроба\Зміна запису в БД
* Спроба\Видалення запису в БД
* Запит даних які носять конфіденційний характер

===== Структура контексту для операцій користувачів

[plantuml, context_create_delete, svg]
----
@startjson
{
    "action": "INSERT / DELETE",
    "step": "...",
    "tablename": "...",
    "row_id": "..."
}
@endjson
----

[plantuml, context_select_update, svg]
----
@startjson
{
    "action": "READ / UPDATE",
    "step": "...",
    "tablename": "...",
    "row_id": "...",
    "fields": "[...]"
}
@endjson
----

==== Події системи
* Отримані дані не відповідають підпису
* Відсутній JWT токен 

===== Структура контексту для подій системи
[plantuml, context_system, svg]
----
@startjson
{
    "action": "SIGN_BREACH / NO_JWT",
    "step": "..."
}
@endjson
----


== Візуалізація

Для візуалізації аудит логів використовується Redash.

[NOTE]
 Забеспечення пошуку по контексту подій та візуалізації поля контекст відбувається в окремих звітах в залежності від типу подій (структура контексту).
 Трансформація поля контекст відбувається за допомогою PostgreSQL.

== POC
https://gitbud.epam.com/mdtu-ddm/data-architecture/poc/audit[GitBud Repo]