= Аналіз Groovy-редакторів на відповідність ключовим вимогам

== Функціональні сценарії

[TIP]
Описати функціональні сценарії, які необхідно реалізувати в рамках дизайну рішення

- Створення та внесення змін до Groovy-скриптів бізнес-процесів

== Приклади коду для редагування

[source, groovy]
----
cephData['edrpou'] = subjectResponse.responseBody.elements().get(0).prop('subjectCode').value()
execution.removeVariable('payload')
set_transient_variable('payload', S(cephData, 'application/json'))
----

== Ключові вимоги до редактора

[TIP]
Описати основні вимоги, які необхідно врахувати в рамках обрання підходу для реалізації рішення

- ...

== Out of Scope

[TIP]
Описати вимоги, які не було розглянуто детально у процесі аналізу та дизайну

== Розглянуті рішення

[TIP]
Додати перелік рішень та технологій, які було розглянуто у процесі підготовки дизайну

- ...

== Аналіз на відповідність вимогам

[TIP]
Додати результати аналізу _pros/cons_ розглянутих рішень та технологій

|===
|Критерій / Функціональність|...

|...
|...

|===

== Рішення за результатами аналізу

[TIP]
Додати резолюцію за результатами проведеного аналізу

== Підтримка темування та стилізації

[TIP]
Описати механізм реалізації вимоги

== Інтерфейс веб-редактора

[TIP]
Додати екрани для візуалізації досвіду моделювання згідно функціональних сценаріїв