= Опис та структура Інсталера
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Визначення
Інсталятор:: набір програмних засобів для розгортання Платформи

Для розгортання Платформи управління реєстрами застосовується Інсталятор, який постачається у вигляді zip архіву

Структура Інсталятору:
[plantuml, structure, svg]
----
@startuml

package "Інсталятор" as installer {
    package "images" as images {
        [external docker images]
        [registry docker images]
    }
    package "nexus" as nexus {
        [liquibase-ext-schema]
    }
    package "repositories" as repositories {
        package "control-plane" as control-plane {
            [codebase-operator]
            [control-plane-console]
            [control-plane-gerrit]
            [control-plane-installer]
            [control-plane-jenkins]
            [ddm-architecture]
            [infrastructure-jenkins-agent]
            [keycloak-operator]
        }
        package "infra" as infra {
            [backup-management]
            [catalog-source]
            [control-plane-nexus]
            [external-integration-mock]
            [keycloak]
            [logging]
            [monitoring]
            [service-mesh]
            [storage]
            [user-management]
        }
        package "registry" as registry {
            [digital-signature-ops]
            [hashicorp-vault]
            [keycloak-operator]
        }
    }
    package "terraform" as terraform {
        [minio]
        [vault]
    }
    [control-plane-installer.img] as installer_image
    [docker_load.sh] as docker_load
    [functions.sh] as functions
    [install.sh] as install
}


@enduml
----


== Діаграма послідовності розгортання платформи
[plantuml, install_flow, svg]
----
@startuml

actor "Адміністратор платформи" as devops order 10
participant "Сервер інсталяції" as jumpbox  order 30
participant "Контейнер Інсталятора" as docker_load  order 35
participant "Інсталятор" as install.sh  order 40
participant "Openshift кластер" as openshift  order 45
participant "Vault" as vault  order 50
participant "Minio" as minio  order 55

autonumber

title Діаграма послідовності розгортання платформи

group Підготовка Інсталятора до розгортання
devops -> jumpbox: Завантаження архіву Інсталятора
devops -> jumpbox: Завантаження сертифікатів digital-signature-ops
devops -> jumpbox: Перевірка готовності сервера (пререквізити)
devops -> docker_load: Автентифікація в Опеншифт
devops -> docker_load: Встановлення параметрів (env)
devops -> docker_load: Запуск Інсталера (install.sh -i)
end

group Розгортання Платформи
install.sh -> install.sh: Перевірка вхідних параметрів
install.sh -> openshift: Увімкнення шифрування ETCD
install.sh -> openshift: Розгортання базових cluster-mgmt ресурсів\n(catalog-sources, storage, keycloak-operator-crd, logging, service-mesh)
install.sh -> openshift: Розгортання nexus (control-plane-nexus)
install.sh -> vault: Розгортання Vault
install.sh -> minio: Розгортання Minio
install.sh -> openshift: Завантаження докер імеджів в nexus (control-plane-nexus)
install.sh -> openshift: Розгортання user-management та завантаження digital-signature-ops сертифікатів
install.sh -> openshift: Розгортання Control Plane
install.sh -> openshift: Завантаження xsd в nexus (control-plane-nexus)
install.sh -> openshift: Завантаження параметрів доступу в Minio
devops -> jumpbox: Перевірка логу та збереження параметрів доступу до Control Plane в безпечному місці
end

@enduml
----

== Діаграма послідовності оновлення платформи
[plantuml, update_flow, svg]
----
@startuml

actor "Адміністратор платформи" as devops order 10
participant "Сервер інсталяції" as jumpbox  order 30
participant "Контейнер Інсталятора" as docker_load  order 35
participant "Інсталятор" as install.sh  order 40
participant "Openshift кластер" as openshift  order 45
participant "Vault" as vault  order 50
participant "Minio" as minio  order 55

autonumber

title Діаграма послідовності розгортання платформи

group Підготовка Інсталятора до розгортання
devops -> jumpbox: Завантаження архіву Інсталятора
devops -> jumpbox: Завантаження сертифікатів digital-signature-ops
devops -> jumpbox: Перевірка готовності сервера (пререквізити)
devops -> docker_load: Автентифікація в Опеншифт
devops -> docker_load: Встановлення параметрів (env)
devops -> docker_load: Запуск Інсталера (install.sh -u)
end

group Розгортання Платформи
install.sh -> install.sh: Перевірка вхідних параметрів
install.sh -> vault: Оновлення стану Vault
install.sh -> minio: Оновлення стану Minio
install.sh -> openshift: Завантаження докер образів в nexus (control-plane-nexus)
install.sh -> openshift: Розгортання Control Plane
install.sh -> openshift: Завантаження xsd в nexus (control-plane-nexus)
install.sh -> openshift: Завантаження параметрів доступу в Minio
devops -> jumpbox: Перевірка логу та коректності оновлення
end

@enduml

----

== Опис модулів Інсталятора (functions.sh)

INIT-CHECK:: перевірка необхідних параметрів та наявності сертифікатів digital-signature-ops (тільки для початкового розгортання)
ENCRYPTION-ETCD:: налаштування шифрування ETCD та затвердження сертифікатів Openshift
INSTALL-CLUSTER-MGMT:: розгортання базових компонент cluster-mgmt
* catalog-source
* storage
* keycloak-operator-crd (підкомпонент control-plane-installer)
* logging
* service-mesh

INSTALL-NEXUS:: розгортання control-plane-nexus (сховище докер образів та xsd)
VAULT-INSTALL:: розгортання центрального Vault
MINIO-INSTALL:: розгортання центрального Minio
INIT-NEXUS:: завантаження докер образів
INSTALL-ADDITIONAL-COMPONENTS:: завантаження digital-signature-ops сертифікатів та розгортання user-management
INSTALL-CONTROL-PLANE:: розгортання компонент Control Plane
NEXUS-RESOURCE-UPLOAD:: завантаження nexus ресурсів (xsd)
BACKUP-CREDENTIALS:: параметрів доступу в Minio
USAGE:: допоміжний модуль для виводу інформації про використання install.sh