= Підсистема керування станом ресурсів Платформи

== Загальний опис

Підсистема, що забезпечує можливості встановлення та оновлення екземпляра Платформи Реєстрів.

== Функції підсистеми

* Встановлення Платформи реєстрів
* Оновлення Платформи реєстрів
* Розгортання компоненти xref:arch:architecture/platform-secret-management/overview.adoc[]
* Розгортання компоненти xref:arch:architecture/platform-backup-storage/overview.adoc[]

== Технічний дизайн підсистеми

На даній діаграмі зображено компоненти, які входять в _Підсистему керування станом ресурсів Платформи_ та їх взаємодію з іншими підсистемами.

image::architecture/platform-installer/platform-installer-subsystem.drawio.svg[width=800,float="center",align="center"]

== Складові підсистеми

|===
|Назва компоненти|Представлення|Тип додатка|Походження|Призначення

|_Компонент керування станом ресурсів Платформи_
|`control-plane-installer`
|backend
|origin
|Архів з компонентів Платформи та реєстрів, скриптів та складових для розгортання Платформи реєстрів з сукупними компонентами
на підготовленій інфраструктурі

|===

== Технологічний стек

При проектуванні та розробці підсистеми, були використані наступні технології:

* xref:arch:architecture/platform-technologies.adoc#terraform[Terraform]
* xref:arch:architecture/platform-technologies.adoc#bash[Bash]
* xref:arch:architecture/platform-technologies.adoc#okd[OKD]

== Атрибути якості підсистеми

=== _Usability_

_Підсистема керування станом ресурсів Платформи_ проста для розуміння та використання та має чіткі і стислі інструкції застосування.

=== _Portability_

_Підсистема керування станом ресурсів Платформи_ розроблена з урахуванням сумісності між різними постачальниками інфраструктури та встановлюється
як у хмарні інфраструктурні середовища (AWS), так і в локальне серверне обладнання (vSphere).

=== _Upgradability_

Підсистема розроблена з урахуванням зворотної сумісності та зберігає наявні функції, інтеграції та взаємодію з користувачами,
тим самим зменшуючи порушення та забезпечуючи плавний перехід при впровадженні нових оновлень та поліпшень Платформи реєстрів.