= Сервіс цифрових документів

== Загальний опис

Сервіс призначений для _тимчасового_ / _проміжного_ зберігання файлів цифрових документів,  до яких необхідно надавати доступ через UI-форми кабінету користувача в рамках виконання задач бізнес-процесу.

== Функціональні вимоги

- Завантаження цифрових документів користувачами через UI-форми задач бізнес-процесів
- Вивантаження та перегляд цифрових документів користувачами через UI-форми задач бізнес-процесів
- Валідація цифрових документів при завантаженні на предмет відповідності обмеженням, налаштованим для файлових полів UI-форм

== Базові принципи реалізації

- Завантаження або вивантаження документів можливе лише через UI-форму задачі бізнес-процесу
- При завантаженні документу повинні застосовуватись валідаційні правила, ідентиччні до клієнтської валідації згідно налаштувань через інтерфейс адміністрування регламенту
- Цифрові документи, які були завантажені або зчитані з Дата Фабрики у процесі виконання бізнес-процесу, доступні лише  учасникам цього БП в рамках виконання їх задач через UI-форми
- При завантаженні документу, система автоматично генерує унікальний ідентифікатор _UUID_ та _SHA256_-геш для подальшого використання у бізнес-процесах
- У якості сховища даних, сервіс цифрових документів використовує розподілене об'єктне сховище Ceph та оперує документами в окремому бакеті "*lowcode-file-storage*"
- Усі документи, які завантажені в рамках бізнес-процесу,  зберігаються у вигляді Ceph-об'єктів під ключами з ознакою групування за префіксом (_process/{processInstanceId}/{id}_)
- Тимчасовість збереження реалізується завдяки автоматичному механізму видалення документів, які були завантажені в рамках БП у разі його завершення

[NOTE]
Назва бакету "*lowcode-file-storage*", який використовується для збереження цифрових документів має бути визначена на рівні конфігурації.

[WARNING]
Включення "digital-document-service" в Istio Service Mesh під питанням.

== Взаємодія компонентів системи

image::architecture/registry/operational/bpms/services/digital-document-service/context.svg[]

== Сценарії взаємодії

[plantuml,file_storage,svg]
----
include::partial$architecture/registry/operational/bpms/services/digital-document-service/digital-documents.puml[]
----

=== Генерація ідентифікаторів цифрових документів

Кожен цифровий документ у підсистемі "Low-code" визначається унікальним ідентифікатором файлу в рамках тенанта реєстру, зформований з використанням генератора псевдо-випадкових чисел (_cad2e994-0e32-4a9f-9959-b420e20d4522_) та який зберігається у вигляді окремого атрибуту мета-даних Ceph-об'єкта *id*.

[source, java]
----
var uuid = UUID.randomUUID();
----

Генерація ключа для збереження Ceph-об'єкта документу виконується згідно конвенції _process/{processInstanceId}/{id}, де _processInstanceId_ - це ідентифікатор бізнес-процеса у виконанні.

=== Генерація гешів цифрових документів

При завантаженні файлів, система автоматично генерує геш з використанням _SHA256_ алгоритму (з використанням бібліотеки _Apache Commons Codecs_), як більш безпечного по відношенню до _MD5_. При збереженні документу в Ceph, згенерована *checksum* записується у вигляді атрибуту на рівні мета-даних Ceph-об'єкта та використовується у процесі підпису даних UI-форми користувача.

[source, java]
----
var sha256hex = DigestUtils.sha256Hex(data);
----

WARNING: Розглянути можливість оптимізації шляхом інкрементального формування гешу у процесі обробки потоку данних при збереженні в Ceph.

=== Авторизація доступу

Доступ до API сервісу цифрових документів надається лише автентифікованим користувачам системи, які мають одну з ролей:

- _officer_
- _citizen_

У зв'язку з тим, що система дозволяє роботу з документами користувачам тільки через UI-форми задач бізнес-процесів, це накладає ряд додаткових умов на отримання доступу до завантаження, вивантаження та отримання мета-даних файлів, зокрема:

- Користувач може завантажувати документи в рамках бізнес-процесу тільки при наявності активної задачі, для якої він встановлений у якості *assignee*
- Користувач може отримувати доступ на вивантаження документів та мета-дані, завантажених ним або іншими користувачами в рамках цього ж бізнес-процесу, за умови наявності активної задачі, для якої він встановлений у якості *assignee*

=== Валідація цифрових документів при завантаженні

При завантаженні файлів через поля типу "_File_" на UI-формі задачі бізнес-процесу, повинні застосовуватись валідаційні правила, налаштовані в інтерфейсі адміністрування регламенту реєстру.

На данний момент для файлових полів підтримуються наступні налаштувавння обмежень:

- _File Pattern_ - обмеження за типом файлу (_application/pdf_, _image/png_, _image/jpeg_)
- _File Maximum Size_ - обмеження за розміром файлу

[plantuml,file_validation,svg]
----
include::partial$architecture/registry/operational/bpms/services/digital-document-service/digital-documents-validation.puml[]
----

=== Автоматичне видалення цифрових документів при завершенні бізнес-процесу

Цифрові документи, які зберігаються в окремому Ceph-бакеті "_lowcode-file-storage_" мають життєвий цикл пов'язаний із виконанням бізнес-процесу, в рамках якого вони були завантажені або зчитані з Дата Фабрики.

Згідно прийнятої конвенції генерації, всі вони зберігаються у вигляді об'єктів, ключі яких мають вигляд _process/{processInstanceId}/{id}_.

Для забезпечення видалення файлів при завершенні бізнес-процесу, розроблено окремий _ExecutionListener_ який реагує на відповідну подію та проводить видалення об'єктів з бакету для яких виконується умова наявності у ключі _префікса_ вигляду _process/{processInstanceId}, де _processInstanceId_ - це ідентифікатор екземпляра процесу, який підлягає завершенню з будь-якої з наступних причин:

- _COMPLETED_
- _INTERNALLY_TERMINATED_
- _EXTERNALLY_TERMINATED_

=== Структура Ceph-об'єкту для збереження цифрового документа

|===
|Назва атрибуту|Атрибут JSON-документа|Атрибут Ceph об'єкта|Значення

|Ключ Ceph-об'єкта
|
|key
|Унікальний ідентифікатор Ceph-документу для збереження файла в області доступу поточного бізнес-процесу. Автоматично формується на базі згенерованого *id* згідно конвенції  _process/<processInstanceId>/<id>_

|Ідентифікатор цифрового документу
|id
|UserMetaData.id
|Унікальний ідентифікатор файла, зформований з використанням генератора псевдо-випадкових чисел (_cad2e994-0e32-4a9f-9959-b420e20d4522_)

|Назва файлу
|name
|UserMetaData.name
|<Назва файлу>

|Тип контента
|type
|Content-Type (UserMetaData.type)
|application/pdf, image/png, image/jpeg

|Розмір
|size
|Content-Length (UserMetaData.size)
|<Розмір файлу>

|Контент документа
|content
|input
|<Контент файла>

|Геш документа
|checksum
|(UserMetaData.checksum)
|Згенерований SHA256-геш файла
|===

== Опис API сервісу

=== Завантаження файла цифрового документу

[source]
----
POST /documents/{processInstanceId}/{taskId}/{fieldName}
----

.Параметри шляху адреси
|===
|Назва |Опис

|*processInstanceId*
|Ідентифікатор бізнес-процесу, в рамках якого виконується завантаження файла
|*taskId*
|Ідентифікатор задачі користувача, в рамках виконання якої виконується завантаження файла через UI-форму
|*fieldName*
|Унікальна назва файлового поля UI-форми задачі користувача, для якого виконується завантаження файла
|===

.Заголовки запиту
|===
|Назва |Обов'язковий |Значення |Опис

|*X-Access-Token*
|Так
|{Access Token}
|Токен доступу до системи користувача, який виконує завантаження файла
|*Content-Type*
|Так
|_multipart/form-data_
|Тип даних запиту для завантаження файла
|===

.Структура відповіді на запит
|===
|Назва |Опис

|*id*
|Унікальний ідентифікатор цифрового документу, зформований з використанням генератора псевдо-випадкових чисел
|*name*
|Оригінальне ім'я файла
|*type*
|Тип контенту файла
|*size*
|Розмір файла
|*checksum*
|Автоматично згенерований геш на контент файла з використанням _SHA256_ алгоритму
|*url*
|Адреса для вивантаження файла, яка автоматично формується на базі параметрів поточного запиту в обробці, контекста запиту та *id*
|===

.Приклад запиту:
[source]
----
POST /documents/{processInstanceId}/{taskId}/{fieldName}
----
[source]
----
---------------573cf973d5228
Content-Disposition: form-data; filename="{filename}"
Content-Type: {mime-type}

PDF file content
---------------573cf973d5228--
----

.Приклад відповіді:

[source]
----
200 OK
Content-Type: application/json
----

[source, json]
----
{
    "id": "{id}",
    "name": "{filename}",
    "type:": "{mime-type}",
    "size": 1000,
    "checksum": "{sha256-hash}",
    "url": "https://.../documents/{processInstanceId}/{taskId}/{fieldName}/{id}"
}
----

.Коди відповідей, які повертаються при обробці запиту
|===
|Код|Опис

|[green]#200#
|OK з поверненням тіла відповіді
|[red]#400#
|Некоректно сформований запит
|[yellow]#401#
| Помилка автентифікації (відсутній токен доступу)
a|[yellow]#403#
| Недостатньо прав для виконання операції
|[yellow]#422#
| Помилка валідації (недопустимий тип або розмір файлу, тощо)
|[red]#500#
|Серверна помилка обробки запиту
|===

=== Вивантаження цифрового документу

[source]
----
GET /documents/{processInstanceId}/{taskId}/{fieldName}/{id}
----

.Параметри шляху адреси
|===
|Назва |Опис

|*processInstanceId*
|Ідентифікатор бізнес-процесу, в рамках якого виконується вивантаження файла
|*taskId*
|Ідентифікатор задачі користувача, в рамках виконання якої виконується вивантаження файла через UI-форму
|*fieldName*
|Унікальна назва файлового поля UI-форми задачі користувача, для якого виконується вивантаження файла
|*id*
|Унікальний ідентифікатор цифрового документу
|===

.Заголовки запиту
|===
|Назва |Обов'язковий |Значення |Опис

|*X-Access-Token*
|Так
|{Access Token}
|Токен доступу до системи користувача, який виконує вивантаження файла
|*Content-Type*
|Так
|_application/pdf_, _image/jpeg_, _image/png_
|Тип даних, який очікується у відповідь на запит
|===

.Приклад відповіді:

[source]
----
200 OK
Content-Type: application/pdf | image/jpeg | image/png
Content-Disposition: attachment; filename="sample.pdf"
Content-Length: 1000
----

[source]
----
File binary content
----

.Коди відповідей, які повертаються при обробці запиту
|===
|Код|Опис

|[green]#200#
|OK з поверненням тіла відповіді
|[red]#400#
|Некоректно сформований запит
|[yellow]#401#
| Помилка автентифікації (відсутній токен доступу)
a|[yellow]#403#
| Недостатньо прав для виконання операції
|[yellow]#404#
|Не знайдено документ за ідентифікатором
|[red]#500#
|Серверна помилка обробки запиту
|===

=== Пошук цифрових документів

[source]
----
POST /documents/{processInstanceId}/{taskId}/search
----

.Параметри шляху адреси
|===
|Назва |Опис

|*processInstanceId*
|Ідентифікатор бізнес-процесу, в рамках якого виконується завантаження файла
|*taskId*
|Ідентифікатор задачі користувача, в рамках виконання якої виконується завантаження файла через UI-форму
|===

.Заголовки запиту
|===
|Назва |Обов'язковий |Значення |Опис

|*X-Access-Token*
|Так
|{Access Token}
|Токен доступу до системи користувача, який виконує запит на пошук доступних документів
|*Content-Type*
|Так
|_application/json_
|Тип даних, який очікується у відповідь на запит
|===

.Структура елементів масиву у відповіді на запит
|===
|Назва |Опис

|*id*
|Унікальний ідентифікатор цифрового документу
|*name*
|Оригінальне ім'я файла
|*type*
|Тип контенту файла
|*size*
|Розмір файла
|*checksum*
|Автоматично згенерований геш на контент файла з використанням _SHA256_ алгоритму
|*url*
|Адреса для вивантаження файла, яка автоматично формується на базі параметрів поточного запиту в обробці
|===

.Приклад тіла запиту:
[source, json]
----
{
    "documents": [
      {
        "id": "{id1}",
        "fieldName": "{fieldName1}"
      },
      {
        "id": "{id2}",
        "fieldName": "{fieldName2}"
      }
    ]
}
----

.Приклад відповіді:

[source]
----
200 OK
Content-Type: application/json
----

[source, json]
----
[
    {
        "id": "{id}",
        "name": "{filename}",
        "type:": "{mime-type}",
        "size": 1000,
        "checksum": "{sha256-hash}",
        "url": "https://.../documents/{processInstanceId}/{taskId}/{fieldName}/{id}"
    }
]
----

.Коди відповідей, які повертаються при обробці запиту
|===
|Код|Опис

|[green]#200#
|OK з поверненням тіла відповіді
|[red]#400#
|Некоректно сформований запит
|[yellow]#401#
| Помилка автентифікації (відсутній токен доступу)
a|[yellow]#403#
| Недостатньо прав для виконання операції
|[red]#500#
|Серверна помилка обробки запиту
|===