:toc-title: On this page:
:toc: auto
:toclevels: 5
:experimental:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Non-relational data storage

NOTE: 🌐 This document is available in both English and Ukrainian. Use the language toggle in the top right corner to switch between versions.

//== Загальний опис
== General description

//_xref:arch:architecture/registry/administrative/ext-api-management/overview.adoc[Підсистема управління зовнішнім трафіком адміністративної зони реєстру]_ використовує розподілену _in-memory_ базу даних xref:arch:architecture/platform-technologies.adoc#redis[Redis] з  xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc[_Підсистеми управління нереляційними базами даних_] для зберігання даних сесій користувачів (_JWT_-токенів).
_xref:arch:architecture/registry/administrative/ext-api-management/overview.adoc[Registry administrative zone external traffic management subsystem]_ uses a distributed _in-memory_ database xref:arch:architecture/platform-technologies.adoc#redis[ Redis] with xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc[_Non-relational database management subsystems_] for storing user session data (_JWT_-tokens).
[NOTE]
--
//Детальніше з технічним підходом можна ознайомитися
You can read more about the technical approach
xref:arch:architecture/registry/operational/ext-api-management/api-gateway/kong-oidc.adoc#_управління_сесіями_користувачів[by link].
--

//== Структури даних
== Data structure

=== sessions_admin_tools

//Зберігання користувацьких _JWT_-токенів, ключ зберігається як стрічка в _HEX_-форматі.
Storage of custom _JWT_ tokens, the key is stored as a string in _HEX_ format.

[NOTE]
--
//Детальніше можна ознайомитись в документації бібліотеки https://github.com/bungle/lua-resty-session[lua-resty-session].
More details can be found in the documentation of the library https://github.com/bungle/lua-resty-session[lua-resty-session].
--