= Хмарний підпис

== Загальний опис

Для розширення можливих способів для автентифікації і підписання документів, а також для вирівнювання досвуіду користувача між всіма державними порталами, необхідно додати можливість для отримувача послуг мати змогу автентифікуватись за допомогою хмарного ключа.

== Функціональні сценарії

* Отримувач послуг може використати хмарний ключ для автентифікації за допомогою віджета.
* Отримувач послуг може використати хмарний ключ для автентифікації при використанні через сервіс `id.gov.ua`.
* Отримувач послуг при автентифікації за допомогою хмарного ключа отримує доступ до вже створеного облікового запису.
* Отримувач послуг може використати хмарний ключ для підписання документів.

== Ролі користувачів

* Отримувач послуг

== Загальні принципи та положення

* На даний момент існує два типи автентифікації для отримання _хмарного ключа_ або підписання даних _хмарним ключем_ - за допомогою сканування QR-коду, через `push`-нотифікацію в додатку надавача послуги _хмарний ключ_
* Кожен надавач послуги _хмарний ключ_ має свій тип підтвердження для отримання сертифікату або підписання даних.
* Механізм отримання сертифікату є частиною віджету для автентифікації.
* Опрацювання дії для підписання даних за допомогою _хмарного ключа_ відбувається кабінетом або додатком автентифікації
* Час очікування для сканування QR-коду _хмарного ключа_ уніфіковано з _Дія.Підписом_
* Опрацювання всіх типів _хмарних ключів_ може відбуватись тільки дженерично і додаткова поведінка для специфічних надавачів послуг _хмарний ключ_ - неможлива
* При підписанні даних або мітки часу помилки підписання даних або сканування QR-коду опрацьовуються однаково і не можуть бути відокремлені.

== Високорівневий дизайн рішення

.Автентифікація за допомогою віджета або підписання документів
[plantuml]
----
actor "Отримувач послуг" as user
participant "Браузер" as b
participant "Мобільний додаток" as m
participant "Віджет" as w
participant "Кабінет отримувача послуг" as portal
participant "Keycloak" as key

user -> b: перехід на захищену\nсторінку кабінету отримувача послуг
b -> portal: запит захищеної сторінки
portal -> portal: перевірка наявності сесії користувача
portal -> b: перенаправлення на сторінку автентифікації
b -> key: перехід на сторінку автентифікації
return сторінка з формою для автентифікації
b --> user
user -> b: вибір провайдера хмарного ключа
b -> w: запит на отримання сертифікату
alt
w --> b: QR-код з описом дії
b --> user: сторінка з QR-кодом
else
w --> m: `push`-нотіфікація
m --> user: повідомлення в додатку **надавача послуг**
user -> m: підтвердження отримання сертифікату
end
w --> b: відображення деталей сертифікату
b --> user:
user -> b: підтвердження обраного сертифікату
b -> w: підписання мітки часу
alt підтвердження входу через QR-код
w -> key: подія з QR-кодом
key --> b: сторінка підтвердження дії
b --> user: відображення QR-коду та таймера

else підтвердження входу через push-повідомлення
w -> m: push-повідомлення \nдля підтвердження дії автентифікація
m --> user: нотифікація додатку
user -> m: підтвердження дії отримувачем послуг
end

w --> key: підписання мітки часу
key --> key: процес автентифікації
key --> b: успішна автентифікація і перехід на захищену сторінку
b -> portal: запит захищеної сторінки
portal --> b: захищена сторінка
b --> user: екран кабінету отримувача послуг

----

Дана діаграма послідовності описує дії при автентифікації за допомогою _ІІТ-віджету_ або при підписанні документів за допомогою цього ж віджету.

Для сценарію використання сервісу `id.gov.ua` для автентифікації опрацювання всіх події відбувається поза платформою і дії платформи зводяться до створення користувача в підсистемі користувачів при успішному проходжені автентифікації.


== Високорівневий план розробки

=== Технічні експертизи

* FE
* BE

=== План розробки

* Обробка події віджета для відображення QR-коду
* Генералізація повідомлення при відображенні QR-коду та тамйаута
* Обробка помилок підписання
* Уніфікація створення користувача при першому логіні через червіс `id.gov.ua`


