= Налаштування логотипу реєстру

== Загальний опис

Обрані логотипи платформи мають застосовуватись також і для кабінетів реєстру.

== Актори та ролі користувачів

* Адміністратор платформи
* Технічний адміністратор реєстру
* Моделювальник реєстру
* Посадова особа
* Користувач citizen-portal

== Функціональні сценарії

* Перегляд логотипів обраних для платформи у порталах реєстру (officer, citizen, admin) та сторінках автентифікації.

== Загальні принципи та положення

* Кожен реєстр використовує логотипи обрані на рівні платформи
* До порталів мають застосовуватись наступні логотипи платформи:
** Логотип у навігаційному меню
** Логотип у вкладці браузера (favicon)
** Логотип у лоадеру
* Зміни логотипів платформи *не* повинні призводити до переразгортання реєстрів

== Компоненти системи та їх призначення в рамках дизайну рішення

У даному розділі наведено перелік компонент системи, які залучені або потребують змін в рамках реалізації функціональних вимог.

|===
|Підсистема|Компонент|Опис змін

|Підсистема управління Платформою та Реєстрами
|*control-plane-console*
|Додати заповнення параметрів логотипів у Codebase реєстру

|Репозиторій порталів платформи
|*common-web-app*
|Додати обробку логотипів які будуть потрапляти до порталів та сторінок автентифікації файли з Config Map у форматі base64 рядку.

|Репозиторій порталів платформи
|*keycloak*
|Використати логотипи з Config Map та передати їх додаткам сторінок автентифікації (officer, citizen).

|===

== Ключові сценарії

=== Зміна логотипів платформи

* перехід у налаштування платформи
* перехід на вкладку Загальне
* на цій вкладці обрати нові файли для логотипів платформи
* після збереження значення логотипів не застосовуються до реєстрів до їх переразгортання яке не запускається цією дією.

== Міграція існуючих реєстрів при оновленні

Усі існуючи екземпляри реєстрів отримають логотипи у рамках оновлення у якості значень за замовчуванням.

== Технічне рішення

=== Експертизи

* Devops
* BE (Java)
* FE (react)

=== Високорівневий дизайн рішення

.Передача логотипів до порталів
image::arch:architecture-workspace/platform-evolution/logo/logo_registry.svg[]

[source,yaml]
.deployments/officer-portal
----
volumeMounts:
  - name: main-logo
    mountPath: /usr/share/nginx/html/portal-officer/logos/main-logo
----

=== План розробки

==== Рівень порталів
* Значення логотипів за допомогою Config Map платформи (`platform-logos`) потрапляють у officer portal, citizen portal, admin-portal (Devops).
* Значення логотипів за допомогою Config Map платформи (`platform-logos`) потрапляють у keycloak який передає їх сторінкам автентифікації за допомогою template vars (Devops).
* Розгортання officer portal, citizen portal, admin-portal та keycloak залежить (needs) від `control-plane-console`, бо саме вона додає необхідну Config Map
* Значення файла логотипу використовується у рендерингу порталів та сторінок автентифікації у:
** Логотип у навігаційному меню
** Логотип у лоадеру
** Логотип у вкладці браузера (favicon)

== Поза скоупом

* Вибір окремих логотипів на рівні реєстру.
