= Налаштування логотипу реєстру

== Загальний опис

Обрані логотипи платформи мають застосовуватись також і для кабінетів реєстру.

== Актори та ролі користувачів

* Адміністратор платформи
* Моделювальник реєстру
* Посадова особа
* Користувач citizen-portal

== Функціональні сценарії

* Перегляд логотипів обраних для платформи у порталах реєстру (officer, citizen, admin).

== Загальні принципи та положення

* Кожен реєстр використовує логотипи обрані на рівні платформи
* До порталів мають застосовуватись наступні логотипи платформи:
** Логотип у навігаційному меню
** Логотип у вкладці браузера (favicon)
** Логотип у лоадеру
* Зміни логотипів платформи *не* повинні призводити до переразгортання реєстрів

== Компоненти системи та їх призначення в рамках дизайну рішення

У даному розділі наведено перелік компонент системи, які залучені або потребують змін в рамках реалізації функціональних вимог.

|===
|Підсистема|Компонент|Опис змін

|Репозиторій порталів платформи
|*common-web-app*
|Додати обробку логотипів які будуть потрапляти до порталів як файли з Config Map у форматі base64 тексту.

|===

== Ключові сценарії

=== Зміна логотипів платформи

* перехід у налаштування платформи
* перехід на вкладку Загальне
* на цій вкладці обрати нові файли для логотипів платформи
* після збереження значення логотипів не застосовуються до реєстрів до їх переразгортання яке не запускається цією дією.

== Міграція існуючих реєстрів при оновленні

Усі існуючи екземпляри реєстрів отримають логотипи у рамках оновлення у якості значень за замовчуванням.

== Технічне рішення

=== Експертизи

* Devops
* FE (react)

=== Високорівневий дизайн рішення

.Передача логотипів до порталів
image::arch:architecture-workspace/platform-evolution/logo/logo_registry.svg[]

[source,yaml]
.deployments/officer-portal
----
volumeMounts:
  - name: main-logo
    mountPath: /usr/share/nginx/html/portal-officer/logos/main-logo
----

=== План розробки

==== Рівень порталів
* Значення логотипів за допомогою Config Map платформи (`platform-logos`) потрапляють у officer portal, citizen portal, admin-portal (Devops).
** Config Map копіюється з рівня платформи на рівень реєстру під час розгортання реєстру.
** Зміна платформеної Config Map не призводить до зміни у реєстровій до запуску процесу перерозгортання реєстру
* ConfigMap маунтиться у окремі файли формату base64 які зчитується фронтенд додатком та використовуються як зображення
* Значення файлів логотипу використовується у рендерингу порталів у:
** Логотип у навігаційному меню
** Логотип у лоадеру
** Логотип у вкладці браузера (favicon)

== Поза скоупом

* Вибір окремих логотипів на рівні реєстру.
* Вплив логотипів на сторінки автентифікації
