:tip-caption: ПІДКАЗКА

= Оновлення

Цей розділ надає всебічне керівництво з оновлення Платформи та реєстру до конкретної версії збірки, наприклад, `1.9.x.28`. Він описує весь спектр необхідних процедур, від загальних методів оновлення Платформи, включно із ручним оновленням та використанням пайплайну `platform-deploy`, до спеціалізованих кроків, які необхідно виконати після оновлення.

У цьому розділі також міститься керівництво по оновленню OKD-кластера, яке охоплює всі необхідні процедури й рекомендації для забезпечення успішного оновлення з будь-якої попередньої версії OKD до актуальної, забезпечуючи безперервність і ефективність роботи кластера.

Тут ви також знайдете детальну інформацію про процес оновлення реєстру, з акцентом на критичні дії, які потрібно виконувати на різних етапах: перед, під час та після самого процесу оновлення. Зокрема, приділяється велика увага відомим потенційним проблемам та специфічним помилкам, що можуть виникнути у процесі апгрейду. Ця інформація дозволить вам комплексно зрозуміти процес для ефективного впровадження оновлень.

TIP: Розпочніть процес оновлення на сторінці xref:update/special-steps-for-update/special-steps.adoc[Оновлення Платформи та реєстрів до версії 1.9.7: спеціальні кроки].

== Огляд секції

* xref:update/special-steps-for-update/special-steps.adoc[]
* xref:admin:update/update_cluster-mgmt.adoc[]
* xref:admin:update/update-registry-components.adoc[]
* xref:admin:update/update-okd-4-12.adoc[]
* xref:admin:update/certificates-update.adoc[]