:tip-caption: ПІДКАЗКА

= Оновлення компонентів Платформи та реєстру

Цей розділ надає всебічне керівництво з оновлення Платформи та реєстру до конкретної версії збірки, наприклад, `1.9.x.28`. Він описує весь спектр необхідних процедур, від загальних методів оновлення платформи, включно із ручним оновленням та використанням пайплайну `platform-deploy`, до спеціалізованих кроків, які необхідно виконати після оновлення.

У цьому розділі ви знайдете детальну інформацію про процес оновлення реєстру, з акцентом на критичні дії, які потрібно виконувати на різних етапах: перед, під час та після самого процесу оновлення. Зокрема, приділяється велика увага відомим потенційним проблемам та специфічним помилкам, що можуть виникнути у процесі апгрейду. Ця інформація дозволить вам комплексно зрозуміти процес для ефективного впровадження оновлень.

TIP: Розпочніть процес оновлення на сторінці xref:update/special-steps-for-update/special-steps.adoc[].

== Огляд секції

* xref:update/special-steps-for-update/special-steps.adoc[]
* xref:admin:update/update_cluster-mgmt.adoc[]
* xref:admin:update/update-registry-components.adoc[]
* xref:admin:update/certificates-update.adoc[]