= Реалізація логічних умов у компонентах форми
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Загальний опис

У компонентах форми, таких як *Textfield*, *Textarea*, *Content*, *Number*, *Email*, *Date/Time*, *EditGrid*, *Select*, *Checkbox*, *Radiobutton*, *File*, *Data Import*, додано можливість налаштування необмеженої кількості логічних умов. Це можливо завдяки вкладці *Logic*, яка дозволяє кастомізувати поведінку компонентів залежно від заданих умов.

Одним із налаштувань є *Property* > *Disabled*, яке робить компонент неактивним (`disabled`), коли вказане значення відповідає умові.

CAUTION: На цей час реалізовано лише налаштування *Property* у стані `disabled`.

TIP: Ознайомтеся із налаштуваннями вкладки *Logic* в описах вказаних компонентів: xref:bp-modeling/forms/components/index.adoc[].

== Процес налаштування

. **Налаштування на вкладці Display**:

.. Відкрийте налаштування компонента, наприклад, *Text field*.
.. Перейдіть на вкладку *Display*.
.. Активуйте чекбокс *Disabled*.

. **Створення логічної умови на вкладці Logic**:

.. Перейдіть на вкладку *Logic*.
.. Натисніть кнопку *`Add Logic`* для створення нової логічної умови.
.. У полі *Name* введіть назву логічної умови.
.. У розділі *Trigger* встановіть параметри спрацьовування умови:

* В полі *Type* оберіть `Simple` або `Javascript`. Для `Simple`:

** В полі `When the form component` оберіть компонент.
** В полі `Has the value` введіть значення, що буде тригером.

* Для `Javascript` введіть відповідний код.

[start=3]
. **Налаштування дії умови**:

.. Натисніть `*Add Action`*.
.. У розділі *Action* встановіть параметри дії:

* У полі *Action Name* введіть назву дії.
* У полі *Type* оберіть `Property`.
* У полі *Component Property* оберіть `Disabled`.
* У полі *Set State* оберіть `False`.

.. Збережіть дію, натиснувши *`Save Action`*, або скасуйте, натиснувши *`Cancel`*.
.. Збережіть усі налаштовані параметри на вкладці *Logic*, натиснувши *`Save Logic`*.
.. Якщо потрібно, ви можете відредагувати або видалити логічну умову, використовуючи кнопки *`Edit`* або *`Delete`*.

. **Додавання декількох логічних умов**:

.. Ви можете додати більше умов, використовуючи `*Add Action`* під кожним доданим блоком *Action*.
.. Після додавання усіх умов, збережіть зміни для форми.

. **Перевірка налаштувань у розділі "Перегляд"**:

.. Перейдіть до розділу *Перегляд*.
.. Перевірте роботу логічних умов. Наприклад, при деактивованому параметрі (checkbox) *Зауваження присутні*, текстове поле *Коментар* має відображатися як неактивне.

.. Активуйте чекбокс *Зауваження присутні*, щоб переконатися, що текстове поле *Коментар* стає активним.
