= Підсистема управління користувачами та ролями

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Підсистема, що забезпечує управління користувачами та їх доступом, налаштуваннями автентифікації, авторизації,
single sign-on (SSO) та інтеграції з зовнішніми _Identity Providers_ в Платформи реєстрів.

== Функції підсистеми

* Автентифікація користувачів
* Авторизація користувачів
* Управління користувачами та ролями
* Налаштування механізмів аутентифікації
* Підпис документів системним цифровим підписом
* Перевірка дійсності цифрового підпису системи

== Технічний дизайн підсистеми

image::architecture/platform/operational/user-management/user-management.drawio.svg[width=600,float="center",align="center"]

== Компоненти підсистеми

|===
|Назва компоненти|Namespace|Deployment|Походження|Призначення

|_Сервіс управління користувачами та ролями_
|`user-management`
|`keycloak`
|3rd-party
|Аутентифікація та авторизація користувачів

|_Сервіс цифрових підписів_
|`user-management`
|`digital-signature-ops`
|origin
|Компонент цифрового підпису що використовує можливості бібліотеки цифрового підпису IIT Java та забезпечує функціонал
по роботі з цифровим підписом

|_Keycloak оператор_
|`user-management`
|`keycloak-operator`
|epam-origin
|Управління налаштуваннями сервісу аутентифікації

|_OpenShift OAuth_
|`openshift-authentication`
|`oauth-openshift`
|3rd-party
|Внутрішній OAuth сервер OpenShift для забезпечення аутентифікації та авторизації всередині Платформи оркестрації контейнерів.
Має інтеграцію з Keycloak

|_Оператор синхронізації користувацьких груп_
|`group-sync-operator`
|`group-sync-operator-controller-manager`
|3rd-party
|Синхронізація користувачів та ролей між платформою оркестрації OpenShift та Keycloak

|===

== Атрибути якості підсистеми

=== _Security_
Підсистема розроблена з урахуванням безпекової складової та підтримує різні протоколи аутентифікації, включаючи OpenID Connect,
OAuth 2.0 та SAML, що дозволяє забезпечити безпечний механізм аутентифікації та авторизації.

=== _Scalability_
Підсистема розроблена з урахуванням роботи з великою кількістю користувачів і високим трафіком, тому може бути масштабована за
необхідністю за допомогою інструментів Платформи оркестрації контейнерів.

[TIP]
--
Детальніше можна ознайомитись в розділі xref:arch:architecture/container-platform/container-platform.adoc[]
--

=== _Reliability_
Підсистема управління користувачами та ролями є високодоступною та ефективно працює при різних навантаженнях.
Вона розроблена таким чином, щоб впоратися з великою кількістю одночасних взаємодій користувачів та ефективно керувати
користувацькими даними без погіршення продуктивності системи.

=== _Observability_
Підсистема управління користувачами та ролями підтримує журналювання вхідних запитів та збір метрик продуктивності
для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--
