= Ролі регламенту

Система надає можливість розширювати перелік ролей для чиновників та громадян. В подальшому
ролі регламенту можуть бути використані для налаштування карти доступу на рівні фізичною моделі
чи налаштування доступу до окремих бізнес-процесів регламенту

[NOTE]
 Детальніше про налаштування доступу до бізнес-процесів можна ознайомитися
xref:architecture/platform/operational/user-management/registry-authz.adoc[за посиланням].

== Структура файлів
Регламентні ролі є частиною регламенту та зберігається у директорії з назвою *roles*. Ролі
налаштовуються окремо для чиновників та громадян у відповідних файлах *officer.yml* та
*citizen.yml*

[plantuml]
----
@startsalt
{
{T
+ <&folder> registry-regulations
++ <&folder> bpmn
++ <&folder> dmn
++ ...

++ <&folder> roles
+++ <&file> officer.yml
+++ <&file> citizen.yml
}
}
@endsalt
----
[source, yaml]
----
roles:
  - name: officer-first-rank
    description: Роль для чиновників першого рангу
  - name: officer-second-rank
    description: Роль для чиновників другого рангу
----

=== Опис структури елементів конфігурації
==== Role
|===
|Назва |Схема |Коментар

|*name*
|string
|Назва регламентної ролі. Повинна мати унікальне значення у реалмі.

|*description* (_optional_)
|string
|Короткий опис для ролі
|===

== Публікація змін
Регламентні ролі підпадають під загальні правила роботи з регламентом реєстру в контексті
відстеження та публікації змін. Тобто, у разі наявності змін до файлів регламентних ролей
(*roles/officer.yml*, *roles/citizen.yml*) пайплайн публікації змін до регламенту буде
запущений. В рамках виконання пайплайну крок *create-keycloak-roles* відповідає
за публікацію змін до регламентних ролей. При успішному проходженні цього кроку система буде
мати регламентні ролі відповідно до змісту файлів.

[NOTE]
Для налаштування ролей використовується Kubernetes CR KeycloakRealmRoleBatch як частина API
https://github.com/epam/edp-keycloak-operator/tree/master#keycloak-operator[Keycloak operator]

== Діаграма послідовності публікації змін

[plantuml]
----
include::partial$architecture/platform/operational/user-management/publish-registry-roles.puml[]
----

