= Підсистема управління зовнішнім трафіком

== Загальний опис підсистеми

Підсистема представлена інтегрованою в _OpenShift_ платформу програмною компонентою _OpenShift Router_, яка використовує _HAProxy_ у якості зворотного проксі-сервера / балансувальника та забезпечує надійну та захищену взаємодію зовнішніх клієнтів з сервісами Платформи.

Підсистема є центральною точкою входу зовнішнього трафіку до _OpenShift_-кластера та відіграє роль шлюза з функцією перенаправлення вхідного трафіку до сервісів Платформи та реєстрів, які на ній розгорнуті.

Підсистема використовує домен з кластерної _OpenShift_ конфігурації як домен для зовнішнього _API_-шлюзу за замовчуванням.
Цей домен також використовується при генерації доменного імені за замовчуванням для ресурсу _OpenShift Route_, якщо явно не вказане інше доменне ім'я.

== Функції підсистеми

* Перенаправлення вхідного зовнішнього трафіку на внутрішні сервіси згідно з налаштованими правилами маршрутизації
* Відслідковування змін налаштувань сервісів та актуалізація правил маршрутизації
* Моніторинг стану сервісів та розподілення трафіку на екземпляри, які доступні для обробки запитів
* Управління доступом по IP та мережам до підсистем Платформи та реєстрів
* Балансування навантаження через розподілення вхідного трафіку між сервісами
* Шифрування зовнішнього трафіку та дешифрування перед перенаправленням на внутрішні сервіси (_SSL/TLS Termination_)
* Збір даних метрик продуктивності для моніторингу
* Журналювання вхідних запитів

== Технічний дизайн підсистеми

image::architecture/platform/operational/external-traffic-management/external-traffic-subsystem.svg[width=600,float="center",align="center"]

== Компоненти підсистеми

|===
|Назва компоненти|Представлення в платформі|Походження|Призначення

|_Зовнішній API-шлюз операційної зони_
|`router-default`
|3rd-party
|_OpenShift Ingress Controller_ (також відомий як _OpenShift Router_) - це компонент, що керує маршрутизацією вхідного трафіку в _OpenShift_ кластері.

|_Оператор зовнішнього API-шлюзу операційної зони_
|`ingress-operator`
|3rd-party
|Відповідальний за розгортання та конфігурацію зовнішнього _API_-шлюзу операційної зони
|===

== Технологічний стек

* xref:arch:architecture/platform-technologies.adoc#okd[OKD]
* xref:arch:architecture/platform-technologies.adoc#haproxy[HAProxy]

== Атрибути якості підсистеми

=== _Scalability_

_Підсистема управління зовнішнім трафіком_ підтримує вертикальне та горизонтальне масштабування для обробки запитів у разі збільшення об'єму зовнішнього трафіку шляхом виділення додаткових ресурсів для _OpenShift Router_ поди або збільшення кількості _OpenShift Router_ под відповідно. Горизонтальне масштабування забезпечується механізмом _Horizontal Pod Autoscaler_ (_HPA_), який, базуючись на даних моніторингу метрик кількості запитів або використанню ресурсів, автоматично збільшує або зменшує кількість реплік _Router_ відповідно поточному навантаженню та цільовим показникам.

[TIP]
--
Детальніше можна ознайомитись у відповідних розділах:

* xref:architecture/container-platform/container-platform.adoc[]
--

=== _Availability_

_Підсистема управління зовнішнім трафіком_ підтримує розгортання в режимі високої доступності для забезпечення обробки вхідного трафіку у разі відмов. Висока доступність забезпечується завдяки застосуванню горизонтального масштабування та розгортанню дублюючих реплік _OpenShift Router_ под. Це дозволяє розподіляти зовнішній трафік по реплікам та гарантувати, що у разі відмови  _OpenShift Router_ поди, трафік буде перенаправлено на репліку.

[TIP]
--
Детальніше можна ознайомитись у відповідних розділах:

* xref:architecture/container-platform/container-platform.adoc[]
--

=== _Security_

_Підсистема управління зовнішнім трафіком_ надає гнучкий та широкий функціонал контролю та обмеження вхідного мережевого трафіку. 

Забезпечує цілісність та конфеденційність даних в каналі передачі інформації між клієнтами та сервісами платформи. Відповідає вимогам критпостійкості.

Підсистема не логує та не зберігає конфіденційну інформацію.

=== _Performance_

Висока продуктивність _Підсистеми управління зовнішнім трафіком_ досягається завдяки декільком чинникам:

* використанню високопродуктивного зворотнього проксі-сервера _HAProxy_.
* рівномірності розподілення трафіку між репліками _OpenShift Router_ под.
* автоматичному горизонтальному масштабуванню для досягнення цільових показників при збільшенні об'єму зовнішнього трафіку.

=== _Observability_

_Підсистема управління зовнішнім трафіком_ підтримує журналювання вхідних запитів та збір метрик продуктивності для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--
