= Розширення alterTableApi

include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

Тег `alterTableApi` розширення Liquibase надає можливість змінювати налаштування, що впливають на поведінку згенерованого коду API для створених таблиць реєстру.

== Liquibase-схема

.Приклад використання
[source,xml]
----
    <changeSet author="..." id="change api behavior">
        <ext:alterTableApi table="table_from_attribute">
            <ext:attribute name="bulkLoad" value="true"/>
            <ext:attribute name="readMode" value="async"/>
        </ext:alterTableApi>

        <ext:alterTableApi table="example_bulk">
            <ext:attribute name="bulkLoad" value="true"/>
        </ext:alterTableApi>
    </changeSet>
----

== Опис параметрів

Параметри для основного тегу

[cols="1,2,2"]
|===
| Назва параметру | Можливі значення | Опис
| *table* | Назви таблиць, які були створені попередніми Liquibase-ченжсетами | Таблиця, для якої необхідно застосувати зміни
|===

Параметри для вкладених тегів *attribute*

[cols="2,1,4"]
|===
| Назва атрибуту (name) | Можливі значення (value) | Опис
| *bulkLoad* | true/false | чи буде згенерований ендпоінт, що дозволяє транзакційно зберігати декілька сутностей в одному запиті
| *readMode* | sync/async | як буде відбуватись операція читання даних, синхронно чи асинхронно (синхронно - на рівні _registry-rest_api_, асинхронно - шляхом rest-api-> _registry-kafka-api_ -> rest-api)
|===

== Згенеровані запити до БД

Результатом опрацювання даного тегу будуть подібні запити до БД registry

Для атрибуту *bulkLoad*
[source,sql]
----
INSERT INTO public.ddm_liquibase_metadata(
    change_type, change_name, attribute_name, attribute_value)
VALUES ("bulkLoad", "table_from_attribute", "bulkLoad", "true");
----

Для атрибуту *readMode*
[source,sql]
----
INSERT INTO public.ddm_liquibase_metadata(
    change_type, change_name, attribute_name, attribute_value)
VALUES ("readMode", "alterTableApi", "table_from_attribute", "async");
----