= Non-relational database management subsystem
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== Overview

The _Non-relational database management subsystem_ stores the registry regulations components and intermediate data produced by the system in the process of user interactions.

== Subsystem functions

* Long-term storage of business process UI form schemas.
* Short-term storage of business process intermediate data.
* Short-term storage of JWT tokens of authenticated users.

== Technical design

image::architecture/registry/operational/nonrelational-data-storage/redis.svg[float="center",align="center"]

The _Non-relational database management subsystem_ uses _Redis_ as a key-value store, while the _Redis Sentinel_ mechanism ensures fault tolerance.

The _Kubernetes_ operator https://github.com/spotahome/redis-operator[Redis Operator by Spotahome] is used to automate the deployment and management of the _Redis_ cluster with _Redis Sentinel_.

_Redis Sentinel_ is a distributed system consisting of multiple instances of _Sentinel_ processes that interact with each other.

_Redis Sentinel_ has the following features:

* Master node failure is confirmed by several _Sentinel_ instances forming a quorum, reducing the chances of false triggers.
* _Sentinel_ is a fault-tolerant system that can perform its functions even when some _Sentinel_ instances are not operational.

_Redis Sentinel_ provides the following capabilities:

* *Monitoring*: _Sentinel_ ensures that _Redis master_ and _replica_ instances are working correctly.

* *Alerting*: _Sentinel_ can notify administrators when a _Redis_ instance failure is identified.

* *Automatic recovery* -- If a _Redis master_ instance stops working, _Sentinel_ initiates the process of determining a new _Redis master_ instance and reconfiguring other _Redis replicas_ to interact with the new _master_.

[TIP]
--

For details, refer to https://redis.io/docs/manual/sentinel/[Redis Sentinel documentation].
--

[#subsystem-components]
== Subsystem components


[options="header",cols="a,a,a,a,a"]
|===

|Component name |Registry representation |Source |Repository |Function

|_Sentinel service_
|`rfs-redis-sentinel`
|3rd-party
|https://github.com/epam/edp-ddm-redis-sentinel[github:/epam/edp-ddm-redis-sentinel]

|Managing high availability and automatic failover between Redis servers.

|_Redis key-value store_
|`rfr-redis-sentinel`
|3rd-party
|https://github.com/redis/redis[github:/redis/redis]

|Storing data in memory in key-value format.

|_Kubernetes operator for Redis_
|`redis-operator`
|3rd-party
|https://github.com/epam/edp-ddm-redis-operator[github:/epam/edp-ddm-redis-operator]

|Deploying and configuring Redis Sentinel resources.
|===

== Classification of data stored in Redis

|===

|Namespace |Owner subsystem |Description

|xref:arch:architecture/registry/operational/ext-api-management/redis-storage.adoc#_sessions[sessions]
|xref:arch:architecture/registry/operational/ext-api-management/overview.adoc[External traffic management subsystem of the registry operational zone]
|User JWT tokens.

|xref:arch:architecture/registry/administrative/ext-api-management/redis-storage.adoc#_sessions_admin_tools[sessions_admin_tools]
|xref:arch:architecture/registry/administrative/ext-api-management/overview.adoc[External traffic management subsystem of the registry administrative zone]
|User JWT tokens.

|xref:arch:architecture/registry/operational/bpms/redis-storage.adoc#_bpm_form_submissions[bpm-form-submissions]
.4+.^|xref:arch:architecture/registry/operational/bpms/overview.adoc[Business process management subsystem]
|Data received through UI forms.
|xref:arch:architecture/registry/operational/bpms/redis-storage.adoc#_bpm_message_payloads[bpm-message-payloads]
|Data generated as a result of cross-process interaction.
|xref:arch:architecture/registry/operational/bpms/redis-storage.adoc#_bpm_form_schemas[bpm-form-schemas]
|UI form schemas.
|xref:arch:architecture/registry/operational/bpms/redis-storage.adoc#_bpm_form_scripts[bpm-form-scripts]
|External scripts for UI forms.

|xref:arch:architecture/registry/operational/user-settings/redis-storage.adoc#_channel_verification_codes[channel-verification-codes]
|xref:arch:architecture/registry/operational/user-settings/overview.adoc[User settings management subsystem]
|OTP codes to confirm the user communication channel.
|===

== Technological stack

The following technologies were used when designing and developing the subsystem:

* xref:arch:architecture/platform-technologies.adoc#redis[Redis]
* xref:arch:architecture/platform-technologies.adoc#redis-sentinel[Redis Sentinel]
* xref:arch:architecture/platform-technologies.adoc#redis-operator[Redis Operator]

== Subsystem quality attributes

=== _Scalability_

The _Non-relational database management subsystem_ supports vertical scaling in case of increased load by allocating additional resources for subsystem pods.

The subsystem also supports horizontal scaling by adding replicas and balancing reads between them.

=== _Security_

The _Non-relational database management subsystem_ protects the cross-service communication channel using _SSL/TLS_ traffic encryption.

Interaction with subsystem services requires client authentication.


Data is stored in the _Distributed data storage subsystem_ using its security capabilities.

=== _Availability_

The _Non-relational database management subsystem_ is configured for high availability with _Redis Sentinel_.

=== _Observability_

The _Non-relational database management subsystem_ logs incoming requests and collects performance metrics for analysis through the web interfaces of the respective Platform subsystems.

[TIP]
--
For details on the subsystem design, see:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--

===  _Reliability_

Reliability of the _Non-relational database management subsystem_ is ensured by the xref:architecture/platform/operational/backup-recovery/overview.adoc[_Backup and restore subsystem_], which includes backing up Redis storage file systems.