@startsalt
{
{T
+<&folder> docs
++<&folder> modules
+++<&folder> <b><module-name></b>
++++<&folder> pages
+++++<&folder> rest-api-includes
++++++<&file> intro.adoc

+++++<&folder> <b><endpoint path 1></b>
++++++<&folder> <endpoint method>
+++++++<&file> spec.adoc
+++++ ...
+++++<&folder> <b><endpoint path n></b>
++++++<&folder> <endpoint method>
+++++++<&file> spec.adoc

+++++<&folder> rest-api-generated
++++++ ...

}
}
@endsalt