@startsalt
{
{T
+<&folder> docs
++<&folder> modules
+++<&folder> registry-regulation-management
++++<&folder> pages
+++++<&folder> rest-api-includes
++++++<&file> intro.adoc

++++++<&folder> <b>versions</b>
+++++++<&folder> candidates
++++++++<&folder> <versionCandidateId>
+++++++++<&folder> POST
++++++++++<&file> spec.adoc

++++++++<&folder> GET
+++++++++<&file> spec.adoc

++++++<&folder> rest-api-generated
+++++++ ...

}
}
@endsalt