@startsalt
{
{T
+<&folder> docs
++<&folder> modules
+++<&folder> registry-regulation-management
++++<&folder> pages
+++++<&folder> rest-api-includes
++++++<&file> <b>intro.adoc</b>

+++++<&folder> rest-api-generated
++++++ ...

}
}
@endsalt