= Версіонування регламенту бізнес-процесів [WIP]

_Регламент бізнес-процесів_ реалізує наступні взаємозв'язані аспекти функціонування реєстру:

- _BPMN_ - набір моделей бізнес-процесів у BPMN-нотації, які описують доступні адміністративні та інформаційні послуги, які надаються посадовими особами реєстру громадянам
- _DMN_ - набір табличних моделей прийняття рішень у DMN-нотації, які використовуються у моделях бізнес-процесів для декларативного опису процесу прийняття рішень та його повторного використання
- _FORMS_ - набір описів структури UI-форм у JSON-форматі, які використовуються для відображення та внесення даних користувачами кабінетів в рамках виконання задач бізнес-процесів
- _SCRIPTS_ - набір скриптів, розроблених за допомогою мови програмування Groovy для подальшого використання в бізнес-процесах для реалізації правил трансформації даних, бізнес-логіки, тощо.

== Базові принципи

- Цілісність _Регламенту бізнес-процесів_ та сумісність складових його частин при внесенні змін досягається за допомогою статичного аналізу / перевірок цілісності
- Гарантії цілісності та сумісності при розгортанні _Регламенту бізнес-процесів_ на цільове оточення досягаються за рахунок створення єдиної версії _deployment_-ресурсу з використанням останніх версій усіх складових регламенту та фіксації їх взаємодії на рівні _Binding=deployment_
- Версійність _Регламенту бізнес-процесів_ досягається завдяки підтримці версійності на рівні _deployment_-ресурсів, що гарантує коректність паралельного виконання бізнес-процесів, які є частинами різних версій _deployment_-ресурсу за умови сумісності з зовнішніми системами та іншими складовими _Регламенту Реєстру_

== Цілісність та сумісність складових регламенту бізнес-процесів

Для забезпечення цілісності та сумісності регламенту бізнес-процесів,

* Використання Groovy-скриптів у бізнес-процесах можливо двома способами:
** _Script Type = "Inline Script":_ Внесення коду скрипта в BPMN-опис моделі бізнес-процесу
** _Script Type = "External Resource":_ Використання окремо створеного файла скрипта, який було розгорнуто в одній з бізнес-процесом версії _deployment_-ресурсу за допомогою посилання _Resource = "deployment://<script-file>"_
* Використання DMN бізнес-правил у бізнес-процесах рекомендовано з визначенням _Binding=deployment_ та розгортанням в одній з бізнес-процесом версії _deployment_-ресурсу
* Використання UI-форм за допомогою визначення _Form Key_ на користувацьких задачах бізнес-процесу, за умови, що схему UI-форми було розгорнуто в одній з бізнес-процесом версії _deployment_-ресурсу
* Використання глобальних вбудованих бізнес-процесів через _Call Activity_ з визначенням _Binding=deployment_

== Структура регламенту бізнес-процесів

_Регламент бізнес-процесів_ представлений у вигляді 4-х директорій з файлами в Git-репозиторії регламенту реєстру, кожна з яких відповідаю за окремий аспект функціонування бізнес-процесів реєстру.

[plantuml, bp-regulation-structure, svg]
----
@startsalt
{
{T
+ <&folder> registry-regulation
++++ <&folder> <b>bpmn</b>
++++++ <&file> process.bpmn
++++++ <&file> ...
++++ <&folder> <b>dmn</b>
++++++ <&file> rule.dmn
++++++ <&file> ...
++++ <&folder> <b>forms</b>
++++++ <&file> form.json
++++++ <&file> ...
++++ <&folder> <b>scripts</b>
++++++ <&file> script.groovy
++++++ <&file> ...
++++ ...
}
}
@endsalt
----

== Взаємодія компонент системи

image::lowcode/bpm-versioning.svg[form-schema-provider, 800]

== Пайплайн публікації регламенту бізнес-процесів

Для забезпечення цілісності та сумісності змін регламенту між _BPMN_, _DMN_, _схемами UI-форм_ та _скриптами_, використовується підхід публікації змін у вигляді єдиної версії _deployment_-ресурсу.

На діаграмі зображено зміни, які необхідно внести у _Пайплайн публікації регламенту_ для реалізації вимог _наскрізної_ версійності.

image::lowcode/bpms-deployment-publication-pipeline.svg[bpms-deployment-publication-pipeline, 800]

.Приклад створення нової версії "registry-regulation" _deployment_, яка об'єднує перелік пов'язаних ресурсів
[source, bash]
----
curl -w \
  -H "Accept: application/json" \
  -H "X-Access-Token: <x-access-token>" \
  -F "deployment-name=registry-regulation" \
  -F "deployment-source=jenkins" \
  -F "enable-duplicate-filtering=false" \
  -F "deploy-changed-only=false" \
# for each bpmn/*.bpmn
  -F "<bpmn-file-name>=@bpmn/<bpmn-file>" \
# for each dmn/*.dmn
  -F "<dmn-file-name>=@dmn/<dmn-file>" \
# for each forms/*.json
  -F "<form-file-name>=@forms/<form-file>" \
# for each scripts/*.groovy
  -F "<script-file-name>=@scripts/<script-file>" \
  http://bpms:8080/api/deployment/create
----

[NOTE]
Детальніше з Camunda API створення _deployment_-ресурсу можна ознайомитись за https://docs.camunda.org/manual/7.17/reference/rest/deployment/post-deployment/[посиланням].

=== Зберігання та кешування схем UI-форм бізнес-процесів

У якості основного сховища даних схем UI-форм використовується _Операційне сховище бізнес-процесів_, де кожна UI-форма представлена у вигляді файлу, закріпленому за конкретною версією _deployment_-ресурсу.

При обробці запиту на отримання схеми UI-форми, _Сервіс постачання UI-форм_ ініціює процес отримання версії форми, яка відповідає поточному бізнес-процесу з _Сервісу виконання бізнес-процесів_ та кешує дані у вигляді _Redis Hash_-структури для пришвидшення майбутніх запитів.

Для збереження даних схем UI-форм за допомогою _Redis Hash_-структури, використовується підхід сегрегації об'єктів через _Keyspaces_-префікси (_<keyspace>:<key>_):

- *bpm-form-schemas*

.Приклад паттерну генерації ключа для запису / читання об'єкту:
[source]
----
bpm-form-schemas:process-definition/${processDefinitionId}/form/{formKey}
----

[NOTE]
Для пришвидшення обробки запитів на отримання схем UI-форм, розглянути використання підходу https://redis.io/docs/manual/client-side-caching/[Кешування на клієнті] у реалізації _Сервісу постачання UI-форм_.

[plantuml, bpm-form-schema-retrieval, svg]
----
include::partial$lowcode/bpm-form-schema-retrieval.puml[]
----