= Версіонування та зберігання схем UI-форм

== Технічний дизайн рішення

На даній діаграмі зображено залучені для реалізації вимог сервіси платформи та взаємодію між ними. Додатково зображено важливі особливості, які необхідно брати до уваги в рамках реалізації.

image::lowcode/form-schema-provider.svg[form-schema-provider, 800]

=== Компоненти системи та їх призначення в рамках дизайну рішення

|===
|Компонент|Службова назва| Сценарії використання

|_Сервіс виконання бізнес-процесів_
|*bpms*
|Управління регламентом бізнес-процесів, розгорнутому у вигляді окремої версії _deployment_-ресурсу

|_Сервіс управління задачами користувачів_
|*user-task-management*
|Збереження даних користувача та підпису, отриманих у процесі виконання задач бізнес-процесів та проведення валідації на відповідність налаштованим правилам

|_Сервіс управління процесами користувачів_
|*user-process-management*
|Збереження вхідних даних, отриманих від користувача через стартову UI-форму бізнес-процесу та проведення валідації на відповідність налаштованим правилам

|_Сервіс-шлюз для інтеграції з зовнішніми системами_
|*bp-webservice-gateway*
|Збереження вхідних даних, необхідних для ініціювання бізнес-процесу у разі виклику зовнішніми системами

|_Сервіс цифрових документів_
|*digital-documents*
|Зберігання та валідація файлів, завантажених користувачами

|_Сервіс валідації даних, внесених користувачем_
|*form-submission-validation*
|Валідація даних та файлів, внесених користувачем через UI-форми задач бізнес-процесів на відповідність налаштованим правилам

|_Сервіс постачання схем UI-форм задач бізнес-процесів_
|*form-schema-provider*
|Обробка запитів на отримання схем UI-форм з боку кабінетів користувачів

|_Пайплайн публікації регламенту_
|*jenkins*
|Публікація змін регламенту бізнес-процесів у вигляді нової версії _deployment_-ресурсу

|_Операційне сховище бізнес-процесів_
|*citus-master*
|Зберігання cхем UI-форм разом з регламентом бізнес-процесів у вигляді _deployment_-ресурсу

|_Розподілене in-memory сховище даних_
|*redis*
|Кешування даних схем UI-форм для пришвидшення обробки запитів

|===

=== Налаштування політик міжсервісної взаємодії

В рамках реалізації вимог, необхідно додати відповідні мережеві політики _NetworkPolicy_, які дозволяють взаємодію для наступних компонентів:

- *kong* -> *form-schema-provider*
- *form-submission-validation* -> *form-schema-provider*
- *user-process-management* -> *form-submission-validation*
- *user-task-management* -> *form-submission-validation*
- *digital-documents* -> *form-submission-validation*
- *form-schema-provider* -> *bpms*
- *form-schema-provider* -> *redis*

=== Зберігання та кешування схем UI-форм бізнес-процесів

У якості основного сховища даних схем UI-форм використовується _Операційне сховище бізнес-процесів_, де кожна UI-форма представлена у вигляді файлу, закріпленому за конкретною версією _deployment_-ресурсу.

При обробці запиту на отримання схеми UI-форми, _Сервіс постачання UI-форм_ ініціює процес отримання версії форми, яка відповідає поточному бізнес-процесу з _Сервісу виконання бізнес-процесів_ та кешує дані у вигляді _Redis Hash_-структури для пришвидшення майбутніх запитів.

Для збереження даних схем UI-форм за допомогою _Redis Hash_-структури, використовується підхід сегрегації об'єктів через _Keyspaces_-префікси (_<keyspace>:<key>_):

- *bpm-form-schemas*

.Приклад паттерну генерації ключа для запису / читання об'єкту:
[source]
----
bpm-form-schemas:process-definition/${processDefinitionId}/form/{formKey}
----

[NOTE]
Для пришвидшення обробки запитів на отримання схем UI-форм, розглянути використання підходу https://redis.io/docs/manual/client-side-caching/[Кешування на клієнті] у реалізації _Сервісу постачання UI-форм_.

=== Пайплайн публікації регламенту бізнес-процесів

Для забезпечення цілісності та сумісності змін регламенту між BPMN, DMN, схемами UI-форм та скриптами, використовується підхід публікації змін у вигляді єдиної версії _deployment_-ресурсу.

На діаграмі зображено зміни, які необхідно внести у _Пайплайн публікації регламенту_ для реалізації вимог _наскрізної_ версійності.

image::lowcode/bpms-deployment-publication-pipeline.svg[bpms-deployment-publication-pipeline, 800]

.Приклад створення нової версії "registry-regulation" _deployment_, яка об'єднує перелік пов'язаних ресурсів
[source, bash]
----
curl -w \
  -H "Accept: application/json" \
  -H "X-Access-Token: <x-access-token>" \
  -F "deployment-name=registry-regulation" \
  -F "deployment-source=jenkins" \
  -F "enable-duplicate-filtering=false" \
  -F "deploy-changed-only=false" \
# for each bpmn/*.bpmn
  -F "<bpmn-file-name>=@bpmn/<bpmn-file>" \
# for each dmn/*.dmn
  -F "<dmn-file-name>=@dmn/<dmn-file>" \
# for each forms/*.json
  -F "<form-file-name>=@forms/<form-file>" \
# for each scripts/*.groovy
  -F "<script-file-name>=@scripts/<script-file>" \
  http://bpms:8080/api/deployment/create
----

[NOTE]
Детальніше з Camunda API створення _deployment_-ресурсу можна ознайомитись за https://docs.camunda.org/manual/7.17/reference/rest/deployment/post-deployment/[посиланням].