= Рекомендації щодо інтеграції екосистеми Дії та платформи реєстрів

== Глосарій

* _Послуга в Дії_ - _<визначення>_
* _Адміністративна послуга реєстру_ - бізнес-процес, реалізований на рівні окремого реєстру, результатом якого є внесення змін до даних реєстру
* _Інформаційна послуга реєстру_ - бізнес-процес, реалізований на рівні окремого реєстру, результатом якого є отримання даних реєстру у визначеній формі

== Цілі

* Стандартизація підходу до інтеграції послуг реєстрів на Платформі в екосистему Дії
* Відсутність необхідності дублювання даних в екосистемі Дії та реєстрах
* Забезпечення можливостей отримання актуальних даних реєстрів через Дію

== Функціональні сценарії

* Ініціювання надання адміністративної або інформаційної послуги реєстру через Дію
* Отримання інформації по статусу надання адміністративної або інформаційної послуги реєстру через Дію
* Відправка повідомлення про завершення процесу надання адміністративної або інформаційної послуги реєстру у Дію
* Отримання результату надання адміністративної або інформаційної послуги реєстру через Дію
* Підтвердження, у разі необхідності, окремих етапів процесу надання адміністративної або інформаційної послуги реєстру користувачами через Дію
* Відправка інформаційних повідомлень у процесі надання адміністративної або інформаційної послуги реєстру користувачам через Дію
* Отримання актуальних даних реєстру через Дію

== Загальні принципи

* Дія є єдиним вікном доступу до адміністративних та інформаційних послуг реєстрів
* Дія надає можливість користувачам сформувати запит на отримання послуги не зберігаючи конфіденційних даних та передає запит на виконання в цільовий реєстр
* Подальша взаємодія користувача з ініційованим бізнес-процесом реєстру обмежується діями підтвердження окремих етапів обробки послуги реєстру
* Дія надає користувачу актуальну інформацію про статус та результат виконання замовленої послуги
* Реєстр є єдиним безпечним сховищем даних та відповідає за їх цілісність та актуальність
* Реєстр відповідає за обробку запиту, виконання замовленої послуги та надання актуального статусу виконання Дії

== Взаємодія Дії та Платформи Реєстрів

image::lowcode/diia-platform-integration-conceptual-design.svg[conceptual-design, 600,align=center]

* Взаємодія користувача з реєстром реалізується завдяки B2B інтеграції Дії та цільових реєстрів через ШБО Трембіта
* Кожен реєстр Платформи, який необхідно інтегрувати в Дію, повинен бути зареєстрованим у якості підсистеми - учасника обміну даними в ШБО Трембіта
* Взаємодія Дії та зареєстрованих підсистем реєстрів відбувається на підставі договору про інформаційний обмін
* Платформа Реєстрів забезпечує наявність стандартизованого API для реалізації сценаріїв взаємодії з реєстрами через ШБО Трембіта
* Дія забезпечує наявність стандартизованого API для відправки повідомлень про завершення виконання послуг реєстром через ШБО Трембіта
* API Платформи Реєстрів не передбачає зовнішнього доступу до даних які були передані у якості вхідних при формуванні запиту на отримання послуги до моменту його фактичного завершення

== Робота з даними

* Дія зберігає перелік доступних послуг інтегрованих реєстрів з мінімально необхідною інформацією для відображення користувачам
* Дія зберігає лише _не конфіденційні дані_, отримані від користувача в рамках формування запиту на отримання послуги для подальшого відображення статусу послуги у виконанні
* Дія не зберігає _конфіденційні дані_ та не дублює дані реєстрів
* Дія зберігає службовий ідентифікатор ініційованої послуги, статус та результат виконання послуги реєстру
