== Валідація даних UI-форм у кабінеті користувача

Low-code платформа надає можливості налаштування валідаційних правил через окремий адміністративний інтерфейс моделювання UI-форм. Наразі підтримуються наступні базові правила валідації на рівні окремих полів в залежності від їх типу:

- Обмеження за типом даних
- Відповідність введених даних заданому регулярному виразу
- Обов'язковість введення даних
- Мінімальна кількість символів
- Максимальна кількість символів
- Мінімальне значення
- Максимальне значення
- Обмеження за діапазоном дат
- Максимальний розмір завантаженого файлу
- тощо

NOTE: Додатково існує можливість налаштування складних правил валідації за допомогою скриптування.

=== Застосування валідаційних правил

На даній діаграмі зображено послідовність кроків обробки запиту на внесення даних користувачем через UI-форму кабінету користувача. Наразі, платформа реалізує валідацію вхідних даних на двох рівнях:

- _Клієнтська валідація_ - для покращення досвіду користування та зниження навантаження на систему
- _Серверна валідація_ - для надання гарантій цілістності та коректності внесення даних з ціллю подальшої обробки на рівні бізнес-процесу

[plantuml]
----
include::partial$lowcode/form-validation.puml[]
----

=== Клієнтська валідація

Валідація даних у кабінеті користувача реалізована за допомогою окремого Form.IO модуля _FormRenderer_, який надає можливість перевірки відповідності введених даних правилам, визначеним у JSON-схемі UI-форми.

.Приклад JSON-схеми опису UI-форми з налаштованими валідаційними правилами
[source, json]
----
{
  "components": [
    {
      "validate": {
        "required": true,
        "minLength": 1,
        "maxLength": 10
      },
      "type": "textfield",
      "customConditional": "<JavaScript validation rule>"
    },
    {
        "mask": false,
        "requireDecimal": false,
        "validate": {
            "max": 10
        },
        "type": "number"
    }
  ]
}
----

=== Серверна валідація

Серверна валідація реалізована завдяки інтеграції "Сервісу управління задачами користувачів" та NodeJS "Сервісу постачання UI-форм", який надає можливості перевірки JSON-документу з даними на відповідність JSON-схемі UI-форми та визначеним в ній правилам валідації. Серверна валідація є дублюючою по відношенню до клієнтської та використовує той самий набір правил, налаштований для цільової UI-форми.

==== API валідації даних "Сервісу постачання UI-форм"

[source]
----
POST /form/{id}/submission?dryrun=1

Content-Type: application/json

Payload:
{
    "data": {
        "name": "",
        "edrpou": ""
    }
}
----

.Коди відповідей
|===
|Код|Опис

a|[green]#200#
|Дані успішно пройшли валідацію
a|[red]#400#
|Виникла помилка валідації
|===

.Приклад відповіді у разі помилки валідації
[source, json]
----
{
  "name": "ValidationError",
  "details": [
    {
      "message": "Name is required",
      "level": "error",
      "path": [
        "name"
      ],
      "context": {
        "validator": "required",
        "setting": true,
        "key": "name",
        "label": "Name",
        "value": ""
      }
    },
    {
      "message": "Edrpou must have at least 2 characters.",
      "level": "error",
      "path": [
        "edrpou"
      ],
      "context": {
        "validator": "minLength",
        "setting": 2,
        "key": "edrpou",
        "label": "Edrpou",
        "value": "1"
      }
    }
  ]
}
----