= Управління налаштуваннями та секретами зовнішніх інтеграцій

[NOTE]
Розділ у процесі формування...

При створенні реєстру, адміністратор реєстру / платформи:

- Налаштовує SMTP сервер для використання / Вказує адресу та секрет зовнішнього SMTP
- Налаштовує Geo-сервер для використання / Вказує адресу...
- Налаштовує ШБО для використання / Вказує адресу та підсистему інформаційного обміну
- Налаштовує client: x-road-instance|member-class|member-code|subsystem-code
- Налаштовує підсистеми з якими буде взаємодіяти реєстр: service: x-road-instance|member-class|member-code|subsystem-code / вказує секрет
- Налаштовує Дія інтеграцію / адресу / секрет
- Налаштовує зовнішні системи з якими буде взаємодіяти реєстр: протокол / адресу / секрет

На рівні регламенту:

- Визначаються точки інтеграції с реєстрами через Трембіту: вказується реєстр (external system) та serviceCode
- Визначаються точки інтеграції з іншими системами: external system, resource path, http method

== Поточний дизайн

image::lowcode/registry-ext-systems-secrets-baseline.svg[registry-ext-systems-secrets-baseline,700]

В поточній реалізації є ряд недоліків:

- Визначення секретів на рівні регламенту
- Дублювання конфігурації та секретів до зовнішніх систем, які використовуються і в регламенті і системою (Дія)
- Неможливість промоції регламенту без внесення у нього змін між DEV-STAGE-PROD екземплярами реєстру
- Дублювання налаштувань реєстру як клієнта Трембіти
- Необхідність ручного створення секретів адміністратором реєстру

=== Налаштування зовнішніх інтеграцій на рівні регламенту

.bp-trembita/configuration.yml
[source, yaml]
----
trembita-exchange-gateway:
  registries:
    edr-registry:
      user-id: 'DDM'
      protocol-version: '4.0'
      trembita-url: 'trembita.url/mockEDRService'
      authorization-token: 'token'
      client:
        x-road-instance: 'SEVDEIR-TEST'
        member-class: 'GOV'
        member-code: '43395033'
        subsystem-code: 'IDGOV_TEST_01'
      service:
        x-road-instance: 'SEVDEIR-TEST'
        member-class: 'GOV'
        member-code: '00015622'
        subsystem-code: '2_MJU_EDR_prod'
external-systems:
  diia:
    url: http://api2.diia.gov.ua
    methods:
      get-damaged-property:
        path: /api/v1/public-service/damaged-property/filtered
        method: GET
    auth:
      type: PARTNER_TOKEN
      secret-name: diia-partner-token
      partner-token-auth-url: https://api2t.diia.gov.ua/api/v1/auth/partner
      token-json-path: $.token
  httpbin:
    url: http://httpbin.org/
    methods:
      get:
        path: /get
        method: GET
    auth:
      type: BASIC
      secret-name: httpbin-basic-authentication
----

== Цільовий дизайн

image::lowcode/registry-ext-systems-secrets.svg[registry-ext-systems-secrets,700]

=== Налаштування зовнішніх інтеграцій на рівні регламенту

.bp-trembita/configuration.yml
[source, yaml]
----
# reusing external system keys configured on registry level
external-systems:
  edr-registry:
    operations:
      search-subjects:
        service-code: "SearchSubjects"
      subject-detail:
        service-code: "SubjectDetail"
  dracs-registry:
    operations:
      get-cert-by-num-role-birthdate:
        service-code: "GetCertByNumRoleBirthDate"
      get-cert-by-num-role-names:
        service-code: "GetCertByNumRoleNames"
  diia:
    operations:
      get-damaged-property:
        resource-path: "/api/v1/public-service/damaged-property/filtered"
        method: "GET"
      create-distribution:
        resource-path: "/api/v1/notification/distribution/push"
        method: "POST"
  http-bin:
    service-name: "HttpBin"
    operations:
      get-operation:
        resource-path: "/get"
        method: "GET"
----

=== Налаштування зовнішніх інтеграцій на рівні реєстру

.ConfigMap: registry-trembita-client
[source,json]
----
{
  "trembita-consumer": {
    "user-id": "DDM",
    "protocol-version": "4.0",
    "client": {
      "x-road-instance": "SEVDEIR-TEST",
      "member-class": "GOV",
      "member-code": "43395033",
      "subsystem-code": "IDGOV_TEST_01"
    }
  }
}
----

// for all external systems we are creating ServiceEntries automatically
.ConfigMap: registry-external-systems
[source,json]
----
{
  "external-systems": {
    "edr-registry": {
      "url": "https://trembita.mdtu-ddm.projects.epam.com",
      "protocol": "SOAP/Trembita",
      "trembita": {
        "service": {
          "x-road-instance": "SEVDEIR-TEST",
          "member-class": "GOV",
          "member-code": "00015622",
          "subsystem-code": "2_MJU_EDR_prod"
        }
      },
      "auth": {
        "type": "AUTH_TOKEN",
        "secret (stored in Vault: 'secret/external-system/edr-registry')": {
          "token": "<authorization-token>"
        }
      }
    },
    "dracs-registry": {
      "url": "https://trembita.mdtu-ddm.projects.epam.com",
      "protocol": "SOAP/Trembita",
      "trembita": {
        "service": {
          "x-road-instance": "SEVDEIR-TEST",
          "member-class": "GOV",
          "member-code": "22956058",
          "subsystem-code": "TEST_DRAC"
        }
      }
    },
    "diia": {
      "url": "https://api2t.diia.gov.ua",
      "protocol": "REST",
      "auth": {
        "type": "AUTH_TOKEN+BEARER",
        "secret (stored in Vault: 'secret/external-system/diia')": {
          "token": "<authorization-token>"
        },
        "auth-uri": "/api/v1/auth/partner",
        "access-token-json-path": "$.token"
      }
    },
    "http-bin": {
      "url": "http://httpbin.org/",
      "protocol": "REST",
      "auth": {
        "type": "BASIC",
        "secret (stored in Vault: 'secret/external-system/http-bin')": {
          "username": "<username>",
          "password": "<password>"
        }
      }
    },
    "secured-service": {
      "url": "http://secured-service.org/",
      "protocol": "REST",
      "auth": {
        "type": "BEARER",
        "secret (stored in Vault: 'secret/external-system/secured-service')": {
          "token": "<authorization-token>"
        }
      }
    }
  }
}
----

=== Типи протоколів аутентифікації

* NO_AUTH
* AUTH_TOKEN+BEARER
* BASIC
* BEARER

=== Зберігання секретів у HashiCorp Vault

."BASIC" Vault Secret: registry/regulation/secret/<integration-point-name>
[source, json]
----
{
  "username": "",
  "password": ""
}
----

."BEARER" Vault Secret: registry/regulation/secret/<integration-point-name>
[source, json]
----
{
  "token": ""
}
----