= Загальний опис

== Вступ

Механізм робочих процесів Camunda (**Camunda BPMN Engine**) опрацьовує та виконує процеси, визначені в моделі бізнес-процесів і нотації (BPMN), глобальному стандарті моделювання процесів.

Побудова моделі бізнес-процесів є можливою завдяки додатку **Camunda Modeler** -- настільного додатка для редагування діаграм процесів BPMN, таблиць рішень DMN і форм.

TIP: Зверніться до офіційного джерела **Camunda** для отримання детальної інформації щодо моделювання та виконання бізнес-процесів і бізнес-правил (_див. xref:useful-links[Корисні посилання]_).

:sectnums:
:sectanchors:

== Аналіз бізнес-процесів «AS IS»

**Послуги**, що надаються фізичним і юридичним особам державними органами, **а також операції** (_запис_, _перегляд_, _редагування_, _видалення_), що відбуваються з даними в процесі виконання владних повноважень, **реалізуються на базі бізнес-процесів певного реєстру**.

TIP: _**Бізнес-Процес (БП)** -- це набір операцій та будь-яких дій, спрямованих на досягнення певного результату шляхом обробки даних._

Бізнес-процес складається з однієї або більше операцій.

TIP: _Результатом виконання бізнес-процесу є реалізація в реєстрах діяльності, спрямованої на виконання повноважень або послуги._

Необхідно обов'язково провести аналіз типових людських помилок введення-виведення інформації, щоб зрозуміти, якими бізнес-процесами їх закривати. Наприклад, була допущена помилка в назві Лабораторії -- як саме буде виправлятися помилка? Як виправлення торкнуться даних в інших таблицях, пов'язаних із назвою Лабораторії?

== Бізнес-процеси та типові операції в реєстрі

=== Загальний опис бізнес-процесів

В рамках Платформи, бізнес-процеси моделюються моделювальниками та розробниками бізнес-процесів інструментами візуального моделювання та управління low-code підсистеми через функціональність створення бізнес-процесів, форм, взаємодій з іншими реєстрами/системами, та компонентами.

Бізнес-процеси складаються з **послідовності операцій**. Операція являє собою одну одиницю роботи, яку неможливо або не можна розбити на глибший рівень деталізації бізнес-процесів. Операції відповідають сутності **Activity** із BPMN.

**Атомарна операція** -- це активність найнижчого рівня деталізації, що зображається в бізнес-процесі. Атомарні операції можуть бути згруповані в складені операції, такі як підпроцес, транзакція, інше (в залежності від можливостей BPMN Modeler) для подальшого перевикористання.

=== Типи атомарних операцій у реєстрах, підтримувані Платформою

Нижче подано список операцій (задач) для моделювання бізнес-процесів у розрізі BPMN activities.

.Список операцій для моделювання БП у розрізі BPMN activities

|===
| № | Тип | Опис

| 1
| Сервісна операція (**`Service Task`**)
| Операція для виклику сервісів (вебсервісів або автоматизованого додатка).

| 2
| Користувацька операція (**`User Task`**)
| Операція, що виконується користувачем в системі. Коли виконання бізнес-процесу приходить до такої операції, нова задача створюється у списку задач для користувача, що призначений для виконання цієї операції.

| 3
| Задача операція (**`Script Task`**)
| Автоматизована операція, що виконується, щойно бізнес-процес приходить до цієї операції.


| 4
| Операція з бізнес-правилами (**`Business Rule Task`**)
| Операція для виконання наперед визначеної логіки процесу.

|===

Також Платформа підтримує можливості моделювання з використанням атомарних операцій виклику (`Call Activity`) і таблиць прийняття рішень (`DMN`).

DMN-таблиці є нерозривно пов'язаними з операціями бізнес-правил (`Business Rule Task`).

=== Опис типових операцій в реєстрах

Нижче подано перелік типових операцій в реєстрі (групування за типом):

.**Сервісна операція (Service Task)**
* Прочитати/Взяти дані з цього реєстру

_Наприклад, створити точку інтеграції з фабрикою даних, вказавши параметри налаштування інтеграції та з набором полів до прочитання._

* Прочитати/Взяти дані з іншого реєстру

_Наприклад, створити точку інтеграції з «Трембітою» вказавши параметри налаштування інтеграції та необхідні поля._

* Записати первинні дані до цього реєстру

_Наприклад, створити точку інтеграції з фабрикою даних, вказавши параметри налаштування інтеграції та набір полів для запису, й відповідні значення для кожного поля._

* Записати нову версію даних до цього реєстру

_Наприклад, створити точку інтеграції з фабрикою даних, вказавши параметри налаштування інтеграції та набір полів для запису, й відповідні значення для кожного поля, ідентифікатор запису до якого вносяться зміни._

* Передати дані до іншого реєстру

_Наприклад, створити точку інтеграції для публікації до «Трембіти», вказавши параметри налаштування інтеграції та необхідні поля._

* Створити документ (включаючи збереження)

_Наприклад, створити витяг з реєстру, де будуть відображатись дані для одного запису, і зберегти до файлу._

* Ініціювати іншій бізнес-процес

_Наприклад, виклик процесу читання даних в іншому реєстрі в рамках запису даних до реєстру -- перевірка коду ЄДРПОУ._

.**Користувацька операція (User Task)**

* Підписати документ

_Наприклад, показати форму з можливістю завантаження файлу КЕП з дозволеними розширеннями від надавачів електронних довірчих послуг для відповідного вихідного документа._

* Підпис даних, введених на попередніх формах, за допомогою КЕП

_Наприклад, форма з можливістю завантаження файлу КЕП з дозволеними розширеннями від надавачів електронних довірчих послуг._

* Внести уточнення до даних, що не пройшли перевірку

_Наприклад, зобразити на формі (підсвітити) дані, що не пройшли перевірку, і дати можливість користувачу скорегувати їх перед переходом до наступного кроку._

* Завантажити документ (файл)

_Наприклад, форма з можливістю завантаження файлів з дозволеними розширеннями, дозволеного розміру з локального комп'ютера._

* Переглянути документ (файл)

_Наприклад, на формі переглянути завантажений файл для визначених форматів._

* Знайти дані в реєстрі за фільтром (форма пошуку за параметрами)

_Наприклад, вказати значення параметрів, за якими будуть відфільтровані дані в реєстрі та показані на формі._

* Переглянути дані з реєстру за одним записом

_Наприклад, обрати один запис зі знайдених в результаті фільтрування і переглянути без внесення змін._

* Розподіл задач між чиновниками

_Наприклад, форма для посадової особи, уповноваженої розподіляти задачі, де вона може встановити відповідність між задачею бізнес-процесу і посадовою особою, що має виконати цю задачу._

* Заповнити дані згідно з масками для кожного поля

_Наприклад, на формі заповнити прізвище, ім'я, по-батькові, використовуючи тільки літери української абетки і такі спеціальні символи, як дефіс (`-`), апостроф (`'`), пробіл._

.**Операція скриптування (Script Task)**

* Перевірка через скриптування

_Наприклад, створення операції скриптування перевірки даних зі складними механізмами, таких як контрольна цифра в РНОКПП._

* Розподіл задач між чиновниками

_Наприклад, створення операції скриптування для складного обчислення відповідність між задачею бізнес-процесу і посадовою особою, що має виконати цю задачу._

* Заповнити дані згідно з масками для кожного поля

_Наприклад, створення операції скриптування для складних масок введення._

* Скасування бізнес-процесу

_Наприклад, створення бізнес-правила, що скасовує бізнес-процес, якщо х днів не було дій з боку користувача._

* Зміна посадової особи для виконання задачі

_Наприклад, повернення задачі на розподіл, якщо х днів не було дій з боку посадової особи._

.**Операція з бізнес-правилами (Business Rule Task)**
* Валідація на основі таблиць прийняття рішень
* Розподіл задач між чиновниками

_Наприклад, створення бізнес-правила, що встановлює відповідність між задачею бізнес-процесу і чиновником -- хто має виконати цю задачу._

* Заповнити дані згідно з масками для кожного поля

_Наприклад, створення бізнес-правила, що перевіряє коректність введення._

* Скасування бізнес-процесу

_Наприклад, створення бізнес-правила, що скасовує бізнес-процес, якщо х днів не було дій з боку користувача._

[#useful-links]
== Корисні посилання

. https://docs.camunda.org/manual/latest/[Офіційне джерело Camunda].
. https://docs.camunda.org/manual/latest/modeler/bpmn/[Camunda Modeler BPMN].
. https://docs.camunda.org/manual/latest/modeler/dmn/[Camunda Modeler DMN].