:toc-title: On this page:
:toc: auto
:toclevels: 5
:experimental:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Setting global registry variables
//= Налаштування глобальних змінних реєстру

The regulations administrator can configure global variables for the registry. Global variables are part of the regulations and are stored in the *_global-vars/camunda-global-system-vars.yml_* file.
//Адміністратор регламенту може налаштовувати глобальні змінні для реєстру. Глобальні змінні є частиною регламенту та зберігаються у файлі *_global-vars/camunda-global-system-vars.yml_*.

Global variables can be used to: ::
//Глобальні змінні можна використовувати для: ::

//- налаштування шляху до фабрики даних (`dataFactoryBaseUrl`);
* Configure the email address of the support service (parameter `*supportEmail*`). The `supportEmail` variable is used in all critical error pages in the officer and citizen portals.
//* Налаштування поштової адреси служби підтримки (параметр `*supportEmail*`). Змінна `supportEmail` використовується на сторінках усіх критичних помилок у Кабінетах посадової особи та отримувача послуг.
* Set up the interface theme for the officer, citizen and registry regulations administrator portals (`*themeFile*` parameter).
//* Налаштування теми інтерфейсу кабінетів посадової особи, отримувача послуг та адміністратора регламентів реєстру (параметр `*themeFile*`).

[WARNING]
====
Only `*supportEmail*` and `*themeFile*` parameters are currently available for configuring. Adding any other variables to the file is prohibited. Also, comments are not allowed. If you want to remove an extra parameter, delete it.
//Зараз доступні для налаштування лише параметри `*supportEmail*` та `*themeFile*`. Внесення будь-яких інших змінних у файл є забороненим. Крім того, не допускається додавання коментарів. Якщо ви хочете прибрати зайвий параметр, просто видаліть його.
====

The variable configuration format is as follows: ::
//Формат конфігурації змінних наступний: ::
+
----
<variable name>: <variable value>
----
//<назва змінної>: <значення змінної>
You can configure the email address of the support service as follows: ::
//Налаштувати поштову адресу служби підтримки можна так: ::
+
----
supportEmail: help@support.com
----

You can customize the theme of the portal interface as follows: ::
//Налаштувати тему інтерфейсу кабінетів можна так: ::
+
----
themeFile: dark-theme.js
----
+
NOTE: By default, all portals use the light theme. Enter this parameter if you want to apply the dark theme.
//NOTE: За замовчуванням усі портали використовують світлу тему. Вкажіть цей параметр, якщо хочете застосувати темну.

Make changes to the master branch of the Gerrit repository, and wait for the `*Master-Build-registry-regulations*` Jenkins pipeline to apply the chosen configuration to your registry regulations.
//Внесіть зміни до майстер-гілки Gerrit-репозиторію, та зачекайте, доки Jenkins-пайплайн `*Master-Build-registry-regulations*` застосує обрану конфігурацію до регламенту вашого реєстру.

[TIP]
====
Use the convenient interface in the Regulations administrator portal for managing global registry settings.
//Використовуйте зручний інтерфейс Кабінету адміністратора регламентів для управління глобальними налаштуваннями реєстру.

For more details, visit xref:registry-develop:registry-admin/admin-portal/registry-modeling/registry-global-settings.adoc[].
//Детальніше -- на сторінці xref:registry-develop:registry-admin/admin-portal/registry-modeling/registry-global-settings.adoc[].
====