//= Моделювання бізнес-процесів і таблиць прийняття рішень
= Business process and decision tables modeling
:sectanchors:
:sectlinks:


Business Processes (BP) are the basis of all services provided by the Platform. They are based on BPMN -- as standardized notation for representing and modeling business processes that allow organizations to streamline operations, improve efficiency and communication between service providers and recipients. BP modelers use dedicated BPMN tools to create, edit, emulate, and execute Business Processes.

BP modeling is an extensive section that includes many topics. You can learn more about them on dedicated pages.

== Section overview

* [*] xref:bp-modeling/bp/what-is-bp.adoc[]
* [*] xref:bp-modeling/bp/bp-modeling-instruction.adoc[]
* [*] xref:bp-modeling/bp/element-templates/element-templates-overview.adoc[]
* [*] xref:bp-modeling/bp/bpmn/index.adoc[]
* [*] xref:bp-modeling/bp/modeling-facilitation/overview.adoc[]
* [*] xref:bp-modeling/bp/bp-alternative-branches.adoc[]
* [*] xref:bp-modeling/bp/access/roles-rbac-bp-modelling.adoc[Restricting access to Business Processes and tasks]
* [*] xref:bp-modeling/bp/excerpts/bp-modeling-excerpt-csv-docx.adoc[]
