= Управління каналами зв'язку користувача

== Загальний опис

Наразі користувач має можливість налаштовувати канали зв'язку для отримання повідомлень від системи:

* *email* - Відправка поштових повідомлень
* *diia* - Відправка _push_-нотифікацій у мобільний додаток _Дія_

[NOTE]
--
Особливістю _inbox_ каналу зв'язку є те, що він буде активований за замовчуванням, користувач не зможе редагувати, деактивувати або якимось іншим чином налаштовувати цей канал.

Іншими словами, робота з _inbox_ каналом не є предметом даної статті
--

== Функціональні сценарії

- Пошук налаштувать користувача за ідентифікатором користувача
- Пошук налаштувань користувача за ідентифікатором користувача, отриманим з токена доступу
- Активація каналу зв'язку шляхом введення / оновлення даних атрибутів каналу (наприклад: поштова адреса)
- Деактивація каналу зв'язку
- Валідація введених налаштувань користувача (за патерном email, відсутністю в blacklist тощо)

== Базові принципи

* Користувач має право змінювати лише власні налаштування
* Користувач може мати лише один канал кожного типу (_email_, _diia_)
* Отримувати налаштування користувача може користувач, якому належать ці налаштування, або система (для змоги надсилати повідомлення користувачам на обрані ними канали зв'язку)

== Технічний дизайн рішення

[NOTE]
При імплементації роботи з каналами зв'язку було змінено дизайн _Сервісу налаштувань_. Основна зміна полягає в тому, що сервіси _user-settings-service-api_ та _user-settings-service-persistence_ об'єднані в один сервіс _user-settings-service_.

image::architecture/registry/operational/user-settings/user-settings-service-design.svg[]

=== Компоненти системи та їх призначення в рамках дизайну рішення

У даному розділі наведено перелік компонент системи, які задіяні або потребують змін/створення в рамках реалізації функціональних вимог згідно технічного дизайну рішення.

|===
|Компонент|Службова назва|Призначення

|_Кабінет громадянина_
|*citizen-portal*
|Управління налаштуваннями користувача через сторінку "Профіль" кабінету

|_Сервіс управління налаштуваннями користувачів_
|*user-settings-service*
|Отримання та зміна налаштувань каналів зв'язку, обраних користувачем

|_Розподілена реляційна база даних Citus_
|*citus-master*
|Довготривале збереження налаштувань каналів зв'язку користувачів на цільовому оточенні реєстру

|_Розподілений брокер повідомлень Kafka_
|*kafka*
|Асинхронне відправлення аудит-повідомлень про зміни в каналах зв'язку

|_Сервіс управління Avro-схемами опису структур даних_
|*kafka-schema-registry*
|Збереження Avro-схеми опису структури даних значущих подій аудиту

|===

=== Налаштування політик міжсервісної взаємодії

Для коректної роботи сервісу налаштувань, мають бути налаштовані відповідні мережеві політики _NetworkPolicy_, які дозволяють взаємодію для наступних компонентів:

- *kong* -> *user-settings-service*
- *user-settings-service* -> *citus-master*
- *user-settings-service* -> *kafka*
- *user-settings-service* -> *kafka-schema-registry*

=== API управління налаштуваннями та каналами зв'язку

[WARNING]
Отримання доступу до API можливе лише в рамках виконання запиту автентифікованого користувача в системі

==== Отримання користувачем налаштувань, що йому належать

[NOTE]
Даний API-роут є публічним та має бути опублікованим для зовнішнього доступу через окремий _Kong Route_ для _Кабінету Громадянина_.

_GET /api/settings/me_

|===
|Параметр|Тип|Частина запиту|Опис

|*X-Access-Token*
|JWT
|HTTP заголовок
|Токен доступу користувача
|===

.Приклад відповіді:

[source, json]
----
{
  "settingsId":  "uuid",
  "channels": [
    {
        "channel": "email",
        "activated": "true",
        "address": "user@domain.com",
        "deactivationReason": "some reason"
    }
  ]
}
----

.Коди відповіді
|===
|Код|Опис

a|[green]#200#
|OK
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації (відсутній токен доступу)
a|[yellow]#404#
|Дані не знайдено
a|[red]#500#
|Серверна помилка обробки запиту
|===

==== Отримання налаштувань для користувача за ідентифікатором

_GET /api/settings/{userId}_

[NOTE]
Даний API-роут не є службовим та не має бути опублікованим для зовнішнього доступу через _Kong Route_.

|===
|Параметр|Тип|Частина запиту|Опис

|*X-Access-Token*
|JWT
|HTTP заголовок
|Токен доступу користувача

|*userId*
|Текстовий
|Параметр запиту
|Унікальний ідентифікатор користувача в системі
|===

.Приклад відповіді:
[source, json]
----
{
  "settingsId":  "uuid",
  "channels": [
    {
        "channel": "email",
        "activated": "true",
        "address": "user@domain.com",
        "deactivationReason": "some reason"
    }
  ]
}
----

.Коди відповіді
|===
|Код|Опис

a|[green]#200#
|OK
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації (відсутній токен доступу)
a|[yellow]#404#
|Дані не знайдено
a|[red]#500#
|Серверна помилка обробки запиту
|===

==== Валідація адреси для каналу зв'язку

Серверна валідація даних, внесених у якості адреси для каналу зв'язку. Набір правил залежить від типу каналу, для *channel = email*:

- Валідація поштової адреси за regexp
- Валідація поштової адреси на унікальність
- Валідація поштової адреси проти сконфігурованого _blacklist_-набору

[TIP]
Валідація для *channel = diia* не застосовується.

[NOTE]
Данний API-роут є публічним та має бути опублікованим для зовнішнього доступу через окремий _Kong Route_ для _Кабінету Громадянина_.

_POST /api/settings/me/channels/{channel}/validate_

|===
|Параметр|Тип|Частина запиту|Опис

|*X-Access-Token*
|JWT
|HTTP заголовок
|Токен доступу користувача

|*channel*
|Текстовий
|Параметр запиту
|Назва каналу [email, diia]
|===

.Приклад запита
[source, json]
----
{
    "address": "<email>"
}
----

.Приклад відповіді з помилкою валідації
[source,json]
----
{
    "traceId": "string",
    "code": "string",
    "message": "string",
    "localizedMessage": "string"
}
----

.Коди відповіді
|===
|Код|Опис
a|[green]#200#
|OK
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації (відсутній токен доступу)
a|[yellow]#422#
|Помилка валідації
a|[red]#500#
|Серверна помилка обробки запиту
|===

==== Активація каналу зв'язку користувача

Активація каналу зв'язку для користувача, створення налаштувань для каналу, якщо вони ще не існують.

[NOTE]
Данний API-роут є публічним та має бути опублікованим для зовнішнього доступу через окремий _Kong Route_ для _Кабінету Громадянина_.

_POST /api/settings/me/channels/{channel}/activate_

|===
|Параметр|Тип|Частина запиту|Опис

|*X-Access-Token*
|JWT
|HTTP заголовок
|Токен доступу користувача

|*channel*
|Текстовий
|Параметр запиту
|Назва каналу [email, diia]
|===

.Приклад тіла запиту для *channel = email*
[source, json]
----
{
    "address": "user@domain.com"
}
----

.Коди відповіді
|===
|Код|Опис

a|[green]#200#
|OK
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації (відсутній токен доступу)
a|[yellow]#409#
|Порушення обмежень бази даних
a|[red]#500#
|Серверна помилка обробки запиту
|===

==== Деактивація каналу зв'язку

_POST /api/settings/me/channels/{channel}/deactivate_

[NOTE]
Данний API-роут є публічним та має бути опублікованим для зовнішнього доступу через окремий _Kong Route_ для _Кабінету Громадянина_.

|===
|Параметр|Тип|Частина запиту|Опис

|*X-Access-Token*
|JWT
|HTTP заголовок
|Токен доступу користувача

|*channel*
|Текстовий
|Параметр запиту
|Назва каналу [email, diia]
|===

.Приклад тіла запиту
[source, json]
----
{
  "deactivationReason": "<deactivation reason enum: [USER_DEACTIVATED|SYSTEM_DEACTIVATED|BLACKLIST_DEACTIVATED]> + some message"
}
----

.Коди відповіді
|===
|Код|Опис
a|[green]#200#
|OK
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації (відсутній токен доступу)
a|[red]#500#
|Серверна помилка обробки запиту
|===

=== Взаємодія компонентів в рамках реалізації сценаріїв

[plantuml, settings_citizen, svg]
----
include::partial$architecture/registry/operational/user-settings/settings_sequence.puml[]
----

=== Фізична модель зберігання даних

В рамках реалізації функціональних вимог, необхідно створити окрему схему _SETTINGS_ та розширити фізичну модель додатковими таблицями:

- _SETTINGS_ - зберігання налаштувань користувача
- _NOTIFICATION_CHANNEL_ - зберігання налаштувань каналів зв'язку користувача

[NOTE]
У випадку необхідності введення статусу/ролі користувача таблиця "subject_settings" може бути розширена відповідними полями.

[plantuml]
----
@startuml
skinparam monochrome true
left to right direction

namespace registry {
object "Subject" as s  {
  id: uuid <<generated>>
  ...
}

object "subject_settings" as sp {
  id: uuid <<generated>>
  subject_id: uuid
  settings_id: uuid
}
}

namespace platform {

object "settings" as settings  {
  id: uuid <<generated>>
  keycloak_id: uuid
}

object "notification_channel" as channels  {
  id: uuid <<generated>>
  settings_id: uuid <<FK>>
  channel: enum
  address: text
  deactivation_reason: text
  is_activated: boolean
  created_at: timestamp
  updated_at: timestamp
}

}

s ||--|| sp
sp ||--|| settings
channels }|--|| settings

@enduml
----


==== Структура даних _SETTINGS_

|===
|Поле|Тип|Обмеження|Значення за замовчуванням|Опис

|*ID*
|UUID
|Primary Key
|_uuid_generate_v4()_
|Унікальний автоматично згенерований ідентифікатор запису

|*KEYCLOAK_ID*
|UUID
|Not Null
|-
|Зовнішній ідентифікатор користувача в keycloak
|===

==== Структура даних _NOTIFICATION_CHANNEL_

|===
|Поле|Тип|Обмеження|Значення за замовчуванням|Опис

|*ID*
|UUID
|Primary Key
|_uuid_generate_v4()_
|Унікальний автоматично згенерований ідентифікатор запису

|*SETTINGS_ID*
|UUID
|Foreign Key, Not Null, Unique Constraint with *CHANNEL*
|-
|Ідентифікатор запису в settings

|*CHANNEL*
|ENUM
|Not Null, Unique Constraint with *SETTINGS_ID* _[email,diia]_
|-
|Назва каналу зв'язку для використання шаблону повідомлення

|*ADDRESS*
|TEXT
|Unique
|-
|Адреса для відправлення повідомлень (опційна, в залежності від типу каналу зв'язку)

|*DEACTIVATION_REASON*
|TEXT
|-
|-
|Причина попередньої деактивації каналу

|*IS_ACTIVATED*
|BOOLEAN
|Not Null
|false
|Чи активований даний канал

|*CREATED_AT*
|TIMESTAMP
|Not Null
|_now()_
|Дата/Час створення запису

|*UPDATED_AT*
|TIMESTAMP
|Not Null
|_now()_
|Дата/Час оновлення запису


|===

[NOTE]
--
Роботи з забезпечення унікальності поштових адрес заплановані на 2023 рік.
До тих пір _Unique_ обмеження для поля _ADDRESS_ не є необхідним
--

=== Ролі/системні користувачі БД

Для обслуговування операцій взаємодії з БД, необхідно створити ролі/користувачів з визначеними правами доступу для використання відповідними компонентами системи:

|===
|Компонент системи|Роль/Користувач|Привілегії

|*user-settings-service*
|_settings_role_
|_GRANT SELECT, INSERT, UPDATE, DELETE ON SETTINGS_

_GRANT SELECT, INSERT, UPDATE, DELETE ON CHANNELS_
|===

=== Аудит та журналювання подій

Події активації/деактивації каналів зв'язку фіксуються у журналі аудиту з повним контекстом. Для реалізації вимоги необхідно розширити підсистему аудиту наступними службовими операціями:

** _USER_NOTIFICATION_CHANNEL_ACTIVATION_
** _USER_NOTIFICATION_CHANNEL_DEACTIVATION_

[NOTE]
Детальніше з дизайном підсистеми "_Журнал аудиту_" можна ознайомитися
xref:architecture/registry/operational/audit/audit.adoc[за посиланням]

==== Структура події аудиту

Нижче наведено xref:architecture/registry/operational/audit/audit.adoc#_події[структуру події аудиту] та її відповідність структурі та значенням отриманого через Kafka-топік повідомлення про необхідність відправки нотифікації користувачу.

===== Структура контексту події аудиту

.Подія активації каналу зв'язку користувача
[source, json]
----
{
  "channel": "email",
  "address": "email@email.com"
}
----

.Подія деактивації каналу зв'язку користувача
[source, json]
----
{
  "channel": "email",
  "address": "email@email.com",
  "deactivationReason": "deactivationReason"
}
----

=== Налаштування публікації подій аудиту
.Приклад налаштувань сервісу для публікації подій аудиту через Kafka-топік (на прикладі використання *ddm-starter-audit* бібліотеки)
[source, yaml]
----
audit:
  kafka:
    topic: audit-events
    schemaRegistryUrl: http://kafka-schema-registry:8081
----

== Редизайн системи

В рамках редизайну системи, необхідно виконати наступні кроки:

* Змінити ім'я сервіса налаштувань на _user-settings-service_
* В усіх місцях, де використовується стара адреса сервіса налаштувань, змінити її на нову (виклики з _Кабінету користувача_, _bpms_, _Сервісу відправки повідомлень_)
* Виправити назву сервіса налаштувань всюди, де вона використовується (для усіх мережевих політик, деплойментів, конфігурацій, секретів тощо)
* Декомісувати сервіс _user-settings-service-persistence_, усі пов'язані з ним деплойменти, секрети, конфігмапи тощо
* Видалити наступні kafka-топіки:
** _read-settings-inbound_
** _read-settings-outbound_
** _update-settings-inbound_
** _update-settings-outbound_
** _read-settings-by-keycloak-id-inbound_
** _read-settings-by-keycloak-id-outbound_
** .DLT топіки для усіх перерахованих _*-inbound_

== Міграція даних

Для збереження вже наявних поштових адрес користувачів, при оновленні фізичної моделі даних, необхідно виконати процедуру міграції

В рамках процедури міграції необхідно виконати наступні кроки:

* Створити таблицю _NOTIFICATION_CHANNEL_
* В рамках liquibase міграції БД для кожного наявного запису в таблиці _SETTINGS_ створити у таблиці _NOTIFICATION_CHANNEL_ відповідний запис з заповненими значеннями

|===
|Поле|Значення

|*SETTINGS_ID*
|Ідентифікатор запису з таблиці _SETTINGS_

|*CHANNEL*
|_email_

|*ADDRESS*
|Значення з колонки _email_

|*IS_ACTIVATED*
|true

|===

* Оновити структуру таблиці _SETTINGS_

== Міграція бізнес-процесів

[CAUTION]
--
В рамках переходу до реалізації концепції каналів зв'язку, необхідно забезпечити можливість їх управління виключно через профіль користувача.

Задля цього необхідно мігрувати бізнес-процеси он-бордингу користувачів існуючих реєстрів на нову версію, в якій відсутні кроки внесення поштової адреси.
--

Існують 2 делегати, що використовувались для роботи з налаштуваннями користувача:

- _userSettingsConnectorReadDelegate_
- _userSettingsConnectorUpdateDelegate_

Після змін у сервісі роботи з налаштуваннями користувача, для коректного продовження роботи _userSettingsConnectorReadDelegate_ необхідно:

* Перейти до використання нового ендпоінту отримання налаштувань
* Перетворити дані, отримані з сервіса, до старої структури, та не змінювати формат відповіді делегата

Делегат _userSettingsConnectorUpdateDelegate_ стає deprecated і підлягає подальшому видаленню у наступних оновленнях платформи
