@startuml
actor  "Користувач\n (Веб браузер)" as client  order 10
participant "Сервер Авторизації (KeyCloack)" as iam  order 20
participant "КЕП Сервіс" as digital_ops  order 30
collections "АЦСК" as ca  order 40
participant "id.gov.ua" as idgovua  order 50
skinparam responseMessageBelowArrow true

title Автентифікація з допомогою КЕП
autonumber
    activate client
        client -> iam: Запит на автентифікацію

    activate iam
        client <-- iam: Логін сторінка з одноразовим кодом (nonce)\n та віджетом для накладання ЕЦП
    deactivate iam
        client -> idgovua: Запит сторінки з віджетом для накладання підпису
        activate idgovua
        client <-- idgovua: Віджет для накладання підпису
        deactivate idgovua
        group Віджет для накладання підпису "id.gov.ua" (iFrame)

            client -> client: Зчитування особистого ключа та пошук і перевірка сертифікатів
            autonumber stop
            client -> ca: Запити на сертифікати та їх статус, мітку часу
            activate ca
            client <-- ca: Сертифікати та їх статус, мітка часу
            deactivate ca
            autonumber resume
            client -> client: Накладання КЕП на одноразовий код (nonce) з міткою часу
        end
        client -> iam: Запит на автентифікацію з підписаним одноразовим кодом (nonce)
        activate iam
        iam -> digital_ops: Запит на перевірку підпису
        activate digital_ops
        digital_ops -> digital_ops: Перевірка підпису \nта одноразового коду (nonce)
        autonumber stop
        digital_ops -> ca: Запити на сертифікати та їх статус
        activate ca
        digital_ops <-- ca: Сертифікати та їх статус
        deactivate ca
        autonumber resume
        iam <-- digital_ops: Статус перевірки та дані користувача\n за умови проходження перевірки
        deactivate digital_ops
        iam -> iam: Автентифікація користувача
        client <-- iam: Відповідь з перенаправленням на АПІ Шлюз з кодом авторизації


    deactivate iam
    deactivate client



@enduml