= Оновлення Платформи та реєстрів до версії 1.9.7: спеціальні кроки
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

CAUTION: Сторінка у процесі розробки. Завітайте пізніше.

== Мета інструкції

Метою цієї сторінки є відображення процесу оновлення та спеціальних кроків, необхідних для оновлення кластера Платформи та реєстрів з версії `1.9.6.34` до `1.9.7.42`.

[#update-platform]
== Оновлення Платформи

=== Запуск пайплайну platform-deploy

Запустіть пайплайн `platform-deploy` в Jenkins CICD2 з опціями оновлення та необхідною версією збірки, а саме `1.9.6.34`.

//TODO: QUESTION
Вкажіть необхідний режим розгортання (`deploymentMode`).

=== Оновлення cluster-mgmt

//TODO: HEREEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

Цей крок описує стандартний процес оновлення інфраструктурних компонентів Платформи за допомогою пайплайну `cluster-mgmt` в адміністративній панелі *Control Plane*.

TIP: Див. детальніше на сторінці xref:admin:update/update_cluster-mgmt.adoc[].

== Кроки після оновлення Платформи

=== aaaaaaaaaaa

=== bbbbbbbbbbb

=== ccccccccccc

== Оновлення реєстру

. Оновіть реєстр до нової версії відповідно до інструкції xref:admin:update/update-registry-components.adoc[]. При сторенні запита на оновлення, не підтверджуйте його.

. Перейдіть до міграції налаштувань, описаних нижче.

=== Оновлення наявних реєстрів

...

=== Оновлення реєстрів версії 1.9.6, що були створені після оновлення Платформи до 1.9.7

...

== Відомі проблеми

Проблема: ::
...

Тимчасове рішення: ::
...

== Виправлення помилки при відновленні центрального компонента `control-plane`

...
