= Управління схемами UI-форм реєстру
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

Розділ показує функціональність моделювання та управління схемами UI-форм до бізнес-процесів у Кабінеті адміністратора регламентів. Функціональність є розширеною адаптацією наявних розробок для управління формами з можливістю:

* Створення форм
* Редагування форм
* Пошуку форм за назвою
* Копіювання форм
* Завантаження форм
* xref:registry-admin/admin-portal/registry-modeling/ui-forms/sorting-paginating-forms.adoc[]
* Видалення форм
* Перегляду складових форми, а саме:

** керування загальною інформацією;
** xref:registry-admin/admin-portal/registry-modeling/ui-forms/json-code-view-edit.adoc[];
** моделювання форм у конструкторі;
** попередній перегляд;
** перегляд сформованих JSON-запитів до фабрики даних.

[WARNING]
====
Рекомендації для збереження та видалення об'єктів у Кабінеті адміністратора регламентів:

* Зверніть увагу, що у Кабінеті адміністратора регламентів немає попереджувальних вікон, тому будьте особливо уважні та обережні при роботі з об'єктами.
* Будьте особливо обережні та уважні при збереженні або видаленні об'єктів, таких як бізнес-процеси, форми тощо.
* Перед створенням або видаленням об'єкта, рекомендується перевірити його, щоб уникнути непередбачуваних наслідків.
* Врахуйте, що видалення або зміна об'єкта може призвести до втрати даних та порушення бізнес-процесів.
====