= System requirements for the Platform instance
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

This document provides the system requirements for the Platform instance. The main aspects of these requirements include:

. *_Requirements for the OKD cluster_*: The OKD cluster can be deployed in various environments, including public clouds like AWS or private solutions based on vSphere. Each environment requires its own approach and specifications.
. *_Requirements for the Platform's central services_*: These services include components common to all registries and ensure the overall functioning of the Platform.

Details of these aspects are discussed in the following sections of the document. Analyze the provided information to ensure the optimal selection of resources and configuration for your Platform instance.

== System requirements for the Platform deployment environment

=== System requirements for OKD in the public cloud environment AWS

Hosts in your OKD environment must meet the following technical specifications and system requirements.

TIP: See more details on https://docs.okd.io/latest/installing/installing_aws/preparing-to-install-on-aws.html[Requirements for Installing OKD Cluster in AWS Environment].

//TODO: Check all the figures, as they are partially for the OKD 3.11 version. Update to 4.11

Key components: ::

* *Master nodes*: Manage the cluster and resources, control application deployments, and have configuration storage.

* *Worker nodes*: These are the nodes where container applications are deployed.

* *Infrastructure nodes*: Deploy cluster support services such as routers, metrics, and logging.

Hardware requirements: ::

* *Master nodes*:
** CPU: 2 vCPU
** RAM: 16 GB RAM
** Disk Space: 40 GB

* *Worker nodes*:
** CPU: 2 vCPU
** RAM: 8 GB RAM
** Disk Space: 15 GB

* *Infrastructure nodes*:
** CPU: 2 vCPU
** RAM: 8 GB RAM
** Disk Space: 20 GB

Network requirements: ::

* *MTU*: The recommended MTU size for your network interfaces is 1500 bytes or more.
* *DNS*: All nodes in the cluster should be able to resolve the names of other nodes in the network.

Additional software requirements: ::

* *Docker*: Version 1.13.1 or newer for deploying containers.
* *Red Hat Enterprise Linux*: Version 8 or newer for nodes.

AWS requirements: ::
It is recommended to use EC2 instances optimized for EBS.
Ensure proper access to AWS resources such as VPC, EC2, S3, etc.
Consider using Elastic Load Balancers for load distribution.

=== System Requirements for OKD in the private cloud environment vSphere

Hosts in your OKD environment must meet the following technical specifications and system requirements.

//TODO: Check all the figures, as they are partially for the OKD 3.11 version. Update to 4.11

[minimal-okd-requirements]
==== Minimum requirements for installing OKD Cluster on VMware vSphere

TIP: See more details on https://docs.okd.io/4.11/installing/installing_vsphere/installing-vsphere-installer-provisioned.html[Requirements for Installing OKD Cluster in vSphere Environment].

Key components: ::

* *Master nodes*: Manage the cluster and resources, control application deployments, and have configuration storage.
* *Worker nodes*: These are the nodes where container applications are deployed.
* *Infrastructure nodes*: Deploy cluster support services such as routers, metrics, and logging.

Hardware requirements: ::
* *Master nodes*:
** CPU: 2 vCPU
** RAM: 16 GB RAM
** Disk Space: 40 GB

* *Worker nodes*:
** CPU: 1 vCPU
** RAM: 8 GB RAM
** Disk Space: 15 GB

* *Infrastructure nodes*:
** CPU: 2 vCPU
** RAM: 8 GB RAM
** Disk Space: 20 GB

Network requirements: ::
* *MTU*: Should be configured to support the largest packet size needed for your deployment.
* *DNS*: All nodes in the cluster should be able to resolve the names of other nodes in the network.

Additional software requirements: ::
* *Docker*: For deploying containers.
* *Red Hat Enterprise Linux*: Version 7.3 or newer for nodes.

vSphere requirements: ::
* *VM hardware*: Version 13 or newer
* *vSphere ESXi hosts*: 6.5 or newer
* *vCenter host*: 6.5 or newer
{empty}

Minimum supported version of vSphere for VMware components: ::
+
* *Hypervisor component*: Minimum supported version: vSphere 6.5 or newer, with HW version 13.
+
This is the minimum version supported by Fedora CoreOS (see more details on the official resource: https://access.redhat.com/documentation/ru-ru/red_hat_enterprise_linux/8/html/configuring_and_managing_virtualization/feature-support-and-limitations-in-rhel-8-virtualization_configuring-and-managing-virtualization[Red Hat Enterprise Linux 8 supported hypervisors list]).

* *Storage component with in-tree drivers*: Minimum supported version -- vSphere 6.5 or newer.
+
This plugin creates vSphere storage using the in-tree storage drivers for vSphere included in OKD.
(Optional) Networking Component (NSX-T): Minimum supported version -- vSphere 6.5U3 or vSphere 6.7U2 and newer.
+
OKD requires vSphere 6.5U3 or vSphere 6.7U2+. NSX container plugin (NCP) VMware is certified for OKD 4.6 and NSX-T 3.x.

== System Requirements for the Platform's Central Services

The Platform's central services system requirements outline the necessary resources for efficient operation. These resources are common to all registries. Among the primary services are:

Openshift (master and workers):: An automatic deployment, scaling, and management system for container applications

Ceph:: File storage distribution subsystem

Logging:: Event logging subsystem

Central Vault:: Platform secret management subsystem

Minio:: Platform backup storage

.Approximate system requirements for the Platform's central services
|===
|Service|Machine type|Number of machines|Machine disk type|Machine disk size, Gb

|Openshift master
|r5.2xlarge (8 CPU, 64 RAM)
|3
|gp2
|120

|Ceph
|r5.4xlarge (16 CPU, 128 RAM)
|3
|gp2
|1170

|Logging
|m5.2xlarge (8 CPU, 32 RAM)
|3
|gp2
|495

|Workers
|r5.2xlarge (8 CPU, 64 RAM)
|5
|gp2
|250

|Central Vault
|r5.2xlarge (8 CPU, 64 RAM)
|1
|gp2
|160

|Minio
|r5.2xlarge (8 CPU, 64 RAM)
|1
|gp2
|2080

|===

[infra-components-cost]
=== Calculation of the Platform's central services cost

The computational cost of the Platform's central services reflects the funds invested in resources that support the shared services. Since one such complex of services can serve numerous registries, its cost is distributed proportionally among them.

TIP: More details about what is included in the cost can be found in the electronic spreadsheet
xref:attachment$architecture/platform-system-requirements/registry-cost-calculator.xlsx[Registry cost calculation] on the _Cost Calculator_ page _>_ _Approximate calculation of common services cost_.

== Related Pages
* xref:arch:architecture/platform-system-requirements/registry-requirements.adoc[System requirements for the Registry instance]