= System requirements for the Registry instance
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== System requirements

Calculating the system requirements for a specific registry is a crucial aspect of planning its infrastructure and resources. Different registries may vary due to the volume of data, number of users, data structure, and other parameters that determine their specific system needs.

This page presents recommendations and parameters for various registry configurations. The parameter *`1 VM calculation reference`* defines the reference value for one virtual machine (VM). Based on this, we propose three main deployment template configurations:

Minimal::
This configuration is intended for registries with small data and users.
It is optimally suited for pilot projects, testing, or registries in the early implementation stages.
Although this configuration has limited resources, it still provides reliability and basic performance.

Recommended::
This configuration is recommended for most registries operating in medium and high load modes.
It is well balanced between resources, performance, and cost, making it suitable for registries serving an average number of users and having a moderate amount of data.

Large::
This configuration is for large registries with significant data and high workloads.
It is designed for registries that serve many users, have complex business processes, and require high performance.
This configuration provides maximum performance and flexibility but requires more resources and costs.

Each configuration has system characteristics, such as _machine type (CPU, RAM)_, _disk size_, _disk type_, file system storage size, expected traffic volume, etc.

.Approximate system requirements for a single registry instance
|===
|Template|Machine Type|Number of Machines|Machine Disk Type|Machine Disk Size, Gb|Ceph Disk Type|Ceph Storage Size, Gb|Expected Traffic Volume per Month, Gb

|1 VM calculation reference

|m5.2xlarge (8 CPU, 32 RAM)
|1
|gp3
|120
|gp3
|200
|550

|minimal
|m5.2xlarge (8 CPU, 32 RAM)
|2
|gp3
|120
|gp3
|200
|550

|recommended
|m5.2xlarge (8 CPU, 32 RAM)
|5
|gp3
|120
|gp3
|200
|550

|large
|m5.2xlarge (8 CPU, 32 RAM)
|10
|gp3
|120
|gp3
|200
|550
|===

== Registry cost calculation

The cost of computing resources for the registry consists of the cost of resources created exclusively for the registry and a portion of the cost of resources designed to support the operation of shared services.

One set of shared services can support dozens of registries, and its operating cost is distributed among these registries (_see more on page xref:arch:architecture/platform-system-requirements/platform-requirements.adoc[]_).

=== Typical configurations

When deploying a registry with standard templates, you can refer to the following cost of computing resources.

|===
|Template|Number of VMs|Total VM Operating Cost, $ per month|Total VM Disk Cost, $ per month|Total Cost of Distributed Storage, $ per month|Total Traffic Cost, $ per month|Cost of Shared Services, $ per month|Total Cost, $ per month

|Minimal|2|220.8|22.85|19.04|49.50|258.52|*570.71*
|Recommended|5|552.00|57.12|19.04|49.50|646.30|*1323.96*
|Large|10|1104.00|114.24|19.04|49.50|1292.61|*2579.39*
|===

NOTE: Prices are based on Amazon Web Services cloud computing platform rates as of the end of 2022, assuming 12 hours of operation per day during the working week.

TIP: More details about what is included in the cost can be found in the electronic table
xref:attachment$architecture/platform-system-requirements/registry-cost-calculator.xlsx[Registry Cost Calculation] on the _Cost Calculator_ page.

=== Cost calculator

To estimate the cost of resources necessary for the operation of a registry that meets the specified requirements, you can use the following calculator:

* xref:attachment$architecture/platform-system-requirements/registry-cost-calculator.xlsx[Registry cost calculation]

On the _Select registry size_ page, in the _Your registry_ row, you can see the calculation results and the registry parameter selection below.

==== Results

Number of VMs:: The calculated number of virtual machines required for the registry operation that meets the parameters specified below.

Cost:: The calculated monthly operating cost at Amazon Web Services cloud computing platform prices. It comprises the virtual machines required to operate the registry and the cost of using shared Platform services.

==== Input parameters
===== Basic parameters

High-availability mode:: Reserving additional instances of registry components and capacities for automatic horizontal scaling.
Operating mode:: The time when the registry is operational.

===== Registry volume
Number of business entities:: The number of tables in the registry's data model.
Maximum number of business entity instances (rows in the table):: The number of rows in the largest table of the registry.
Approximate volume of historical data in GB:: The volume of data uploaded to the registry before the start of commercial operation (initial upload).

===== Registry parameters
The following parameters are set separately for each of the three categories of users: _officials/service providers_, _citizens/service recipients_, _other systems_.

Number of users:: The number of registered users who can use the registry.
Number of services (business processes):: The number of services the registry can provide to different categories of users.
Average number of user tasks per service:: The average number of tasks requiring user input.
Average number of automated tasks per service:: The average number of tasks that do not require user input.
Number of reports:: The total number of modeled reports used by officials.
Number of extracts:: The total number of modeled extracts.
Number of services provided per month:: The total number of services offered monthly.

== Related pages

* xref:arch:architecture/platform-system-requirements/platform-requirements.adoc[]