:toc:
:toclevels:
:toc-title: ЗМІСТ
:sectnums:
:sectnumlevels:
:sectanchors:
:experimental:
:important-caption: ВИПРАВЛЕНО
:note-caption: ПОКРАЩЕНО
:tip-caption: РОЗРОБЛЕНО
:warning-caption: ДИЗАЙН
:caution-caption: ІНШЕ
:example-caption: Приклад
:last-update-label: 24.01.2023
:sectlinks:

= Примітки до релізу 1.9

== Зміни у версії 1.9.2

=== Використання JOIN з можливістю вказання додаткової умови OR
//https://jiraeu.epam.com/browse/MDTUDDM-20617

[TIP]
Розширено можливості використання операції `*JOIN*` для поєднання таблиць-представлень (Search Conditions) у БД додатковою умовою `*OR*`, окрім вже наявної `AND`. Тепер адміністратор регламенту зможе використовувати нову функціональність при роботі з моделлю даних реєстру.

=== Завантаження файлів формату p7s та asic на формі задачі
//https://jiraeu.epam.com/browse/MDTUDDM-21820

[TIP]
Можливість в рамках виконання бізнес-процесу завантажувати та дозавантажувати файл у форматах `p7s` та `asics` для збереження його до бази даних реєстру. Функціональність доступна для Кабінетів посадової особи та отримувача послуг.

=== Керування розкладом створення резервних копій центральних компонент та часом їх зберігання
//https://jiraeu.epam.com/browse/MDTUDDM-21045

[TIP]
====
Імплементовано можливість керувати розкладом створення резервних копій наступних центральних компонентів, а також часом зберігання таких резервних копій у сховищі бекапів:

* Бекапування центрального *Nexus* (сховище артефактів);
* Бекапування центрального *Control Plane* (панель керування Платформою та реєстрами);
* Бекапування центрального *user-management* (Керування користувачами);
* Бекапування центрального *monitoring* (моніторинг).

Значення зберігаються до конфігурації *_values.yaml_* у репозиторії  *_cluster-mgmt_*.

Відповідні параметри застосовуються завдяки Jenkins-пайплайну `Cluster-mgmt`.
====

=== Оновлення Kong до версії 3.0
//https://jiraeu.epam.com/browse/MDTUDDM-21381

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-21384
Оновлено Kong API-шлюз до нової версії 3.0.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-13029
Не працюють посилання до вебпорталів.

=== Управління бізнес-процесами реєстру 1.9.2
//https://jiraeu.epam.com/browse/MDTUDDM-21815

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-20368
Імплементовано валідацію бізнес-процесів за XSD-схемою.

Створено XSD-схему для валідації бізнес-процесів.
XSD імпортує схему Camunda та додатково валідує бізнес-назву процесу на наявність.

Створено кастомний валідатор бізнес-процесу через `spring-boot-starter-validation`.
====

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21522
Не відображається попередження на вкладці [.underline]#Загальна#: `"XML представлення містить помилки"`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21484
Шрифт відображення xml-представлення не відповідає очікуваному на вкладці [.underline]#Код# під час створення бізнес-процесу.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21523
XML-представлення бізнес-процесу відображається без форматування.

=== Централізоване розповсюдження типових розширень бізнес-процесів як частини Платформи
//https://jiraeu.epam.com/browse/MDTUDDM-22433

[TIP]
====
Імплементовано централізоване розповсюдження типових розширень бізнес-процесів як частини Платформи для використання в інтерфейсі моделювання БП з метою забезпечення сумісності версій.

У минулих версіях `admin-portal` зчитував розширення `business-process-modeler-extensions` з hardcoded-конфігурації.

Оновлений механізм передбачає зчитування із `business-process-modeler-element-templates.js`.

====

=== Інші впровадження 1.9.2

==== [ST1] Покращення 1.9.2
//https://jiraeu.epam.com/browse/MDTUDDM-21425

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-17487
Некоректно працює Search Condition endpoint.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-18573
Не відображаються обрані координати на мапі, які були передані з іншої форми.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-18556
Підвищено технічну якість компонента `Map`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-21080
Перероблено логування `form-submission-service` з використання DI.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-21672
Виправлено selector для сервісів `citus-master` i `citus-master-rep` у Crunchy PGO.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-21698
Винести загальні типи (`types`) у пакет `common`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21778
Не налаштоване за замовченням використання балансеру при горизонтальному масштабуванні баз даних.

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-22079
Перевірено всі Java-репозиторії, де не використовуються latest-версії плагінів.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22152
Перенесено компонент `Map` з експериментальних до оновлених компонентів.

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-22520
Відновлено перевірку на `typescript`-помилки.

==== [ST2][Sprint7] Допрацювання 1.9.2
//https://jiraeu.epam.com/browse/MDTUDDM-21426

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-8482
Рефакторинг роботи із системним підписом у делегаті генерації витягів.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13243
Розширено безпеку сервісу завантаження користувачів. Сервіс може використовувати лише користувач із правами `KeyCloak/Client Roles/realm-management -> manage-users`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-15480
Позначки розташування майна з'являються лише при великому зменшенні масштабу карти.

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-16577
Для `serv-gen-utility` додано суфікс до згенерованих моделей.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-17491
Розділено моделі для `create` та `update` для можливості виключення `primaryKey` з `dto`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-20960
Проведено рефакторинг `ddm-notification-service` після імплементації усіх каналів зв'язку.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-21738
Створено Redis healthcheck для BE-компонентів.

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-22009
Відкореговано помилки в Sonar для `service-generation-utility`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-22069
Перехід до використання токена системного користувача при видаленні файлів у bpms-сервісі.

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-22363
Додано можливість підпису файлів витягу mock-підписом.

==== [ST3][Sprint7] Покращення 1.9.2
//https://jiraeu.epam.com/browse/MDTUDDM-21429

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-16140
Додано валідацію полів `Назва версії` та `Опис зміни` при створенні нового запита на внесення змін до регламенту.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-19762
Cleanup-пайплайн тепер видаляє файли з persistence volume поди `registry-regulation-management`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21921
Не обробляється помилка для рейт-лімітів в `admin-portal`.

==== [PST] Покращення 1.9.2
//https://jiraeu.epam.com/browse/MDTUDDM-21430

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13757
Винесення реєстрового адміністративного `admin-portal`-ендпоінту під Kong Gateway.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-19279
Дозволити завантажувати кастомний файл `terraform.tfvars` при розгортанні/оновленні Платформи через автоматизацію CICD2-кластера та ручному варіанті оновлення/встановлення.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-21927
Налаштовано підтримку `https` у сервісі minio на цільових оточеннях.

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-22807
Прибрати CORS для dev-оточень `admin-portal`.

==== E-Shelter 1.9.2: Пошук та усунення несправностей при підтримці продукту
//https://jiraeu.epam.com/browse/MDTUDDM-21836

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-18849
[SUPPORT] Скориговано конфігурацію рівня деталізації для історичних подій бізнес-процесів на оточенні "e-shelter".

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-18850
[SUPPORT] Скориговано конфігурацію процесу видалення історичних подій бізнес-процесів на оточенні "e-shelter" та застосовано для наявних процесів.

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-18853
[SUPPORT] Підготовлено скрипти для термінового завершення застарілих бізнес-процесів, для яких не має ризику неконсистентності даних реєстру.

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-18859
[SUPPORT] Проведено видалення історичних подій бізнес-процесів та "вакуумізацію" Citus на оточенні "e-shelter".

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-19144
[SUPPORT] Тимчасова зміна часу життя токена доступу в Keycloak для проходження camunda-auth-cli застосування правил авторизації бізнес-процесу (MASTER-Build-registry-regulations) на оточенні "e-shelter".

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-21214
У секції "РЕСУРСИ РЕЄСТРУ" необхідно підвантажено значення Istio sidecar та  Container замовчуванням для обраного компонента.

//https://jiraeu.epam.com/browse/MDTUDDM-21462
// 4 задачі нижче стосуються цього тікета

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18866
Підготовано скрипти/утиліту для видалення документів із Ceph-бакетів для завершених бізнес-процесів на оточенні "e-shelter".

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19766
Розширено інтерфейс утиліти `CephGUI` можливістю отримання кількості документів у бакеті та його розміру.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20975
Таблиця `ACT_HI_ACTINST` у Camunda БД не вичищається при увімкненій `history-cleanup` конфігурації.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-19198
Оптимізовано видалення та створення авторизаційних прав у `camunda-auth-cli`, використовуючи ендпоінти `batch create/delete`.


==== [PST][1.9.2] Регресійні дефекти
//https://jiraeu.epam.com/browse/MDTUDDM-21404

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-23001
Не оновлюється `Group-Sync-Operator` автоматично до версії 0.0.23.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22322
Під час відновлення реєстру (пайплайн `Restore-registry`) томи Kafka досягають свого ліміту.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21924
При зміні `envVars` під час редагування ресурсів зберігаються обидва значення: старе (за замовчуванням) та нове.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21913
Після відновлення *Control Plane* з резервної копії, адміністратори Платформи втрачають свої права.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-16591
Не проходить cleanup-пайплайн реєстрів.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22198
При розгортанні оточення виникає помилка `BackoffLimitExceeded`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22197
При розгортанні оточення виникає помилка при виконанні pre-upgrade scripts зі `strimzi-kafka-operator`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-18900
Після проходження Cleanup-пайплайну не з'являється папка Registry Regulation.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-12757
Не відпрацьовує cleanup-пайплайн, якщо `codebases.v2.edp.epam.com` "registry-regulations" було вже видалено.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-18971
Неможливо провести cleanup, якщо екземпляр `redash-admin` вимкнено.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21912
При наявності свого (кастомного) URL для кабінету, Istio перевіряє `token issuer` за внутрішнім URL.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-12584
`CRD KeycloakRealmUser` не оновлюється.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-13217
Після видалення реєстру через Control Plane, залишаються мапери в `KeycloakRealmIdentityProvider`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-13223
Clean-up-пайплайн не видаляє компонент `registry-rest-api-deployment`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-16877
Перенести генерацію TLS-сертифікатів Vault/Minio з `user-data` до модуля `terraform`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19761
При оновленні реєстру пайплайн намагається видалити адміністраторів, які додані до іншого реєстру.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19987
Не додаються ролі адміністратора Платформи.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20948
Сесія в Redash не завершується після 3 діб.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21032
Некоректне формування MR при оновленні 1.8.2->1.8.3->1.8.4 (Envone).

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21406
pgAdmin реєстру містить декілька однакових серверів.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21433
Зникає маршрут до Swagger-сервісу.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21911
Перелік CIDR не переноситься на наступну сторінку.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22190
Не остання версія регламенту використовується під час розгортання реєстру на Envone.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22360
Kong продовжує шифрувати cookie сесії, попри використання Redis.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22854
Неможливо вносити зміни в оновленому до версії 1.9.1 реєстрі через зайвий файл у корні репозиторію реєстру.

==== [ST1][Sprint 5] Регресійні дефекти
//https://jiraeu.epam.com/browse/MDTUDDM-21413

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-18930
Script в оновленому компоненті *EditGrid* працює неправильно.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20602
Не виконується перевірка при заповненні обов'язкових полів на формі.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20894
Проблема при створенні search condition з одним вихідним параметром.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21519
Представлення `pg_stat_statements_info` та `pg_stat_statements` не повинні бути присутні у БД audit.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21559
Додано можливість при завантаженні користувачів через admin-portal додавати `Username`, `Last Name` та `First Name`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21910
У системного користувача відсутні атрибути `drfo` та `fullName`, що унеможливлює виконання операцій з фабрикою даних.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21922
При першому переході за посиланням у АП на сторінці Управління користувачами логи в Kibana відкривається без фільтрів.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21968
Додано в оновленому *EditGrid* `rowIndex`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22015
Проблеми з використанням formVariables в оновленому EditGrid

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22076
Latest-версія spring-boot-maven-plugin не працює на java11.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22179
Cleanup пайплайн не видаляє аналітичні екземпляри Crunchy, якщо підписка не видалилась.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22213
Додати екранування паролів у команди запуску Liquibase для `run-db-scripts-job`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22274
Помилка при використанні компонента *File* всередині компонента *Table*.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22286
Деякі запити (queries) не публікуються в `redash-viewer`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22325
Відсутня валідація поля `Максимальний сукупний об'єм завантажуваних файлів`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22659
Не валідувати поле `Minimum total size` для компонента *File*, якщо воно не заповнене.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22723
Помилка при використанні компонента *File* при розміщенні в *Edit Grid*.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22834
Редагування скриптів не працює в `admin-portal` на деяких нових версіях Chrome.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22998
Помилка відправки Kafka-повідомлень при масштабуванні BPMS.

==== [ST2][Sprint 6] Регресійні дефекти
//https://jiraeu.epam.com/browse/MDTUDDM-21415

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-15474
Неможливість редагування компонента *FieldSet* при наявності в ньому *Table* та інших компонентів.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-15799
Не працює збірка `registry-kafka-api`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19032
При старті `registry-kafka-api` зменшується та не вистачає CPU.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-18935
Не проходить автентифікація за допомогою електронного підпису id.gov.ua.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20171
Не відображається повна історія наданих послуг на порталі.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20949
NPE у сервісі `Digital-document-service` при спробі пошуку (search) файлу з відсутнім `filename` у `user metadata`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21740
*Citizen sign task* надає можливість підписати дані форми для параметра `ENTREPRENEUR` при значенні `disable`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22191
Делегат `UserSettingsConnectorUpdateDelegate` не працює у версії 1.9.

==== [ST3][Sprint 7] Регресійні дефекти
//https://jiraeu.epam.com/browse/MDTUDDM-21422

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20990
Завелика відстань між полем вводу даних та UI-елементом рядка цього поля в `admin-portal` на створенні версії кандидата.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21339
Якщо у версії-кандидаті багато змін, не відбувається прокрутка змін.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19795
Після запуску cleanup-пайплайну, в `admin-portal` видаляються версії-кандидати.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21466
Планувальник для списку таблиць відпрацьовує лише один раз при старті сервера.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22172
Не створюється бізнес-процес, якщо задавати бізнес-назву та службову назву у конструкторі.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22003
Не створюється форма із дозволеним символом в `admin-portal`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22006
Додати помилку до всіх TAB, якщо не валідний JSON на формах.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22272
Видалити з колонки "Правило" назву таблиці.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22273
Неправильно відображається історичність таблиць.

==== [ST1][SECURITY] Дефекти безпеки
//https://jiraeu.epam.com/browse/MDTUDDM-21817

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-14718
[Security] [Group] Vulnerabilities in `org.springframework.boot:spring-boot-starter-web`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19389
[FB][Security] [Group] Vulnerabilities in `org.springframework:spring-core`.

[#changes-1-9-1]
== Зміни у версії 1.9.1
//https://jiraeu.epam.com/browse/MDTUDDM-21187

=== Захист адміністративних ендпоінтів за допомогою Kong
//https://jiraeu.epam.com/browse/MDTUDDM-12954

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13732
Можливість мати доступ до реєстрових Jenkins та Gerrit через Kong API Gateway для адміністраторів Платформи.

'''

=== Оновлення Velero до 1.9.0 та безпечний запуск пайплайну Jenkins
//https://jiraeu.epam.com/browse/MDTUDDM-20265

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-12918
Автоматично не видаляється бекап, якщо статус бекапу - expired.

При завершенні TTL бекапу, бекап не видалявся. Ця поведінка повторювалась лише на промислових оточеннях, де под velero у статусі Running увесь час. Після примусового видалення поди velero, velero видаляє бекап.

Розв'язання проблеми -- оновлення версії Velero.
====

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-19110
Видалено резервне копіювання OBC, та оновлено скрипт зі створення із резервної копії.

Додати реплікацію OBC в AWS/S3 compatible storage.
====

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-21293
Виправлено процес відновлення реєстру з відновлення OBC з s3 compatible storage.
====

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-20266
Покращення бекапів: безпечний запуск пайплайну з відновлення.
====

'''

=== Автоматизація менеджменту Keycloak client, SAML
//https://jiraeu.epam.com/browse/MDTUDDM-20942

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18969
Змінили налаштування SAML-клієнта в Keycloak для Redash.

Для коректної роботи SSO-автентифікації у Redash -- щоб могли логуватися користувачі, які не мають встановленого Email у Keycloak, -- змінено налаштування SAML-клієнта у Keycloak для Redash з метою примусового використання поля `username` як ідентифікатора користувача (`NameID`).

Встановлено відповідні значення для конфігурації клієнтів `redash-viewer (officer realm)`, `redash-admin (admin realm)` у Keycloak:

* `Force Name ID Format` -> `ON`
* `Name ID Format` -> `username`

====

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-20908
Налаштовано оновлення Keycloak client при оновленні KeycloakClient CR.

Тепер при оновленні поля `.spec.webIUrl` в `KeycloakClient CR` вже на створеному Keycloak-клієнті зі `status = ok`, для клієнта оновлюється значення `Root URL`, `Valid Redirect URIs` , `Admin URL`, `Web Origins` на Keycloak-сервері.
====

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20946
Keycloak-оператор не змінює стан на сервері після зміни поля `KeycloakClient.spec.webURL`.

'''

=== Розробка скриптів upgrade-фреймворку
//https://jiraeu.epam.com/browse/MDTUDDM-11860

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-11862
Розроблені скрипти для оновлення jenkins job provisioner.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-11861
Розроблені скрипти для оновлення kafka-оператора.

'''

=== Оптимізація продуктивності для E-Shelter 1.9.1
//https://jiraeu.epam.com/browse/MDTUDDM-21748

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18957
Реалізовано можливість виділення ресурсів сервісам реєстру через конфігурацію у control-plane-console.

.Список компонентів:
=====
----
kong
bpms
digitalSignatureOps
userTaskManagement
userProcessManagement
digitalDocumentService
restApi
kafkaApi
soapApi
----
=====
====

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18836
Реалізовано можливість налаштування виділення ресурсів сервісам реєстру на рівні конфігурації через підтримку параметризації.

Додано можливість гранулярного налаштування ресурсів, які виділяються наступним сервісам реєстру:

.Список компонентів:
=====
----
* kong
* bpms
* digital-signature-ops
* user-task-management
* user-process-management
* form-management-provider (LEGACY)
* digital-document-service
* registry-rest-api
* registry-kafka-api
----
=====
====

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18837
Змінено налаштування виділення ресурсів сервісам реєстру на оточенні "e-shelter".

На рівні OpenShift Deployment змінено налаштування ресурсів, які виділяються сервісам реєстру.
====

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18904
Реалізовано можливість налаштування crunchy на рівні конфігурації через підтримку параметризації.

Додано можливість гранулярного налаштування ресурсів, які виділяються crunchy, а саме кількість підключень до бази даних.

Заповнено "recommended" шаблон конфігурації реєстру згідно з новою структурою для citus значеннями з поточної конфігурації ресурсів для розгортання.
====

'''

=== Розробка SOAP-інтеграційних розширень бізнес-процесів
//https://jiraeu.epam.com/browse/MDTUDDM-11387

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-7419
Зробили конфігурацію доступу до ШБО "Трембіта" частиною регламенту.
====

'''

=== Можливість попередньої валідації даних з csv-файлу до збереження даних в базу
//https://jiraeu.epam.com/browse/MDTUDDM-21228

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-20101
Можливість виконувати попередню перевірку даних з csv-файлу посадовою особою до збереження даних в базу.

'''

=== Обов'язковість поля Url в оновленому компоненті File
//https://jiraeu.epam.com/browse/MDTUDDM-21403

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-20816

В оновленому компоненті *File*, на вкладці *File* над полем `Url`, з'явилося поле -- *Storage*. Поле є обов'язковим до заповнення і реалізовано у вигляді випадного списку із двох значень:

* `Digital-document-service`;
* `Custom Url`.
====

'''

=== Перегляд переліку таблиць моделі даних реєстру та їх структур для Майстер-версії
//https://jiraeu.epam.com/browse/MDTUDDM-21540

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17574
Перегляд структури таблиць в Мастер версії. Перегляд списку таблиць.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19039
Перегляд індексів до таблиць. Це дозволяє бачити, як пов'язані таблиці.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21671
GET-запит на отримання інформації про таблицю не повертає індекси.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21792
Сортування за стовпчиком Правило на вкладці "Індекси" відпрацьовує лише один раз.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21803
Сортування за стовпчиком "Значення за замовчуванням" на вкладці "Колонки" працює у зворотному напрямку.

'''

=== Управління бізнес-процесами реєстру
//https://jiraeu.epam.com/browse/MDTUDDM-21541

//TODO: Documenting
[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-20179
Валідація обов'язкових полів при збереженні змін на всіх вкладках бізнес-процесу та Форм адміністратором регламенту. Це дозволить уникнути збереження невалідних даних.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19040
Створення бізнес-процесів із використанням функціональності вкладки "Код".

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-21208
Обробка статусу `сopied` у gerrit.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21486
Неможливість повного видалення xml-представлення на вкладці "Код" під час створення бізнес-процесу.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21764
Повідомлення з попередженням про помилку не показується на вкладці "Конструктор", коли xml-представлення порожнє.

'''

=== Регресійні дефекти 1.9.1
//https://jiraeu.epam.com/browse/MDTUDDM-20718

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20180
Після рестарту кластера не підіймається NEXUS.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-11545
Інсталер перестає розгортання при встановленні на API Openshift сертифікату.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-10710
Поди CephObjectStore плануються (schedule) на машинсеті за замовчуванням у кластері.


[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19956
Видалено жорстко закодованих секретних ключів у значеннях Redash (secretKey, cookieSecret і секретний пароль postgresqlPassword).

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-12717
Configmaps bp-webservice-gateway-trembita-business-processes та registry-environment-js перезаписуються при кожному розгортанні оточення.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-13119
Позначка статусу у конфігурації реєстру в control-plane-console є зеленою при не розгорнутому реєстрі.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-14561
[UAT] Не виконується запит на оновлення.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-18826
Redash не має з'єднання із БД через джерела даних (data sources).

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19036
При оновленні реєстру та cluster-mgmt job, видаляються налаштування для ШБО "Трембіта", адміністраторів та IP-адрес у _values.yaml_.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19037
Запити на оновлення на сторінці "Керування Платформою" сортувати за датою створення від найновіших.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19742
Пайплайн з видалення реєстрів не видаляє мапери у Keycloak.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19970
Не виконується розгортання регламенту registry-model-1.0.0 через префікс https://index.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20448
Не можна перейти до редагування реєстру у Control Plane після оновлення до версії 1.8.3.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20542
Помилки у Grafana через  оновлення 4.11 до k8s 1.24.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20611
При створенні запита на внесення змін, перенаправлення йде не на "Огляд версії", а на "UI-форми".

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20729
[EnvOne] Pull-ліміти при збірці компонентів регламенту.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20934
Виправлено видалення лямбдою правил та політик.


[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21103
Не виконується `Create-release-cluster-mgmt` job після розгортання кластера.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21171
Додано валідацію на внесення адміністраторів реєстру/платформи.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21450
Не працює кнопка видалення Переліку дозволених ключів.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21564
Control Plane має приймати пусті значення в ресурсах.

=== [ST1] [Sprint 4] Регресійні дефекти
//https://jiraeu.epam.com/browse/MDTUDDM-20627


[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-18407
Некоректне розташування іконки на сторінці "Звіти" кабінету посадової особи.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20899
При оновленні реєстру до журналу управління користувачами не додається колонка з кастомними атрибутами внесеними в csv-файл.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-18776
При натисканні на "Х" у компоненті *File*, викликається ендпоінт видалення файлу з digital-document-service.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19744
Невідповідність вказаної кількості ініційованих послуг до кількості послуг, ініційованих насправді.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19774
[BPMS][CAMUNDA] Неконсистентне відображення активних процесів та задач у кабінетах користувачів.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19966
При роботі з формою, у користувача перестають підтримуватись дані, ключі для яких не прописані в компонентах форми.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20212
Під значенням "0" у widgetHeight у Keycloak система повністю прибирає віджет зі сторінки аутентифікації.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20301
BPMS не може зрозуміти помилку FORBIDDEN_OPERATION з дата-фабрики.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20815
Як посадова особа, я хочу мати можливість сортувати послуги за статусом виконання і датою на вкладці "Послуги у виконанні" в особистому Кабінеті.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21294
pgAdmin не підключається до БД на кластері CICD2.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21451
Немає логів при переході за посилання після пакетного завантаження осіб на цільових кластерах.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21494
Redash не може оновлювати інформаційні панелі (дашборди) без розгортання оточення з нуля.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21542
Відсутній КАТОТТГ-mapper для клієнта redash-viewer у Keycloak.

=== [ST2][Sprint 5] Регресійні дефекти
//https://jiraeu.epam.com/browse/MDTUDDM-20643

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-9473
Горизонтальний скрол на формі додавання відомостей про кадровий склад.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19030
Зацикленість (повне припинення дій) пайплайнів у control plane jenkins після старту кластера.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-14505
Перезатирається configmap для bp-webservice-gateway-trembita-business-processes після оновлення реєстру.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-15241
Видалено оточення platform-ci.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-15481
Фіксація користувача, що запустив пайплайн, у повідомленні коміту, у CP Gerrit та CP Installer.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-17543
Неправильний розмір шрифту при відображенні помилки в admin-portal.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-14736
При винесенні умови за рамки визначення search condition, збірка проходить успішно, а search condition створюється некоректно.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-18581
Помилка при розгортанні реєстру через те, що порт для розгортання Gerrit вже зайнятий.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-18710
Некоректна робота компонента Button після внесення його до компонента Table. Button Component для Action "Navigation" неактивний, якщо його помістити до Table Component.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-18867
Розгортання інсталера не пройшло через platformVaultToken.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20040
Відсутнє обмеження поля компонента Content у білдері стилізованого Edit Grid.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20327
Відсутня валідація під час розгортання змін у заголовку, коли одне поле "title" чи "titleFull" залишилося порожнім.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20601
[PROD SUPPORT L3] Додано у валідатор регламенту перевірку на дублікат сутності у моделі даних.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-20630
Обробка помилок, що виникають при незбігу обмежень БД та даних, що вводяться на формі задачі.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20631
Немає можливості повернутись до процесу Онбордингу, якщо його не завершити та повторно увійти до кабінету отримувача послуг.


[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20772
Положення UI-елементів на стилізованому компоненті Upload, а саме положення хрестика видалення файлів, не збігається з дизайном.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20777
Файл з великою назвою виходить за кордони сторінки, якщо у налаштуваннях стилізованого File стоїть положення "Right".


[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20900
Користувач має можливість завантаження 2 файлів на UI у компонент "File" без активної функції Multiple Values.


[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21205
Рендерінг привітальної сторінки у розділі "Повідомлення" під час оновлення сторінки у браузері при наявності вже актуальних повідомлень у цьому розділі.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21210
Невірний код відповіді при модифікації повідомлення клієнтом яке йому не належить.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21267
Системні параметри не логуються в `audit_event`.


[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21380
Не валідується "Заголовок повідомлення" на обов'язковість у _notification.yml_.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21405
Не відображається повідомлення "Задача успішно виконана".


[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21447
Здійснюється спроба відправки повідомлення в inbox якщо воно було ініційовано не делегатом.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21448
Не виконується логування події в audit_event для inbox, якщо воно було забраковане.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22068
Критична помилка на формі с підписом КЕП у БП, де є компонент Text Area.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-22168
Обмеження підключень кранчів дорівнює 100 під час розгортання оточення.

=== [ST3][Sprint 6] Регресійні дефекти
//https://jiraeu.epam.com/browse/MDTUDDM-20644

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-12922
Неправильно формується запит через очищення поля форми.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-14714
Перехід системи на головну сторінку порталу під час оновлення сторінки в активному БП на citizen-portal.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19260
Помилка не відповідає мокапам при спробі створити форму із наявною службовою назвою.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19386
Немає обробки помилки при клоні репозиторію.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19945
Під час редагування форм Кабінеті адміністратора регламентів виникає помилка.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19950
Прибрали з customClass назву mdtuddm на вкладці "Код" при створенні нової форми.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19957
[UAT] В адміністратора у Кабінеті адміністратора регламентів відсутні два поля: `drfo` та `fullName`, через що не відправляється запит на searchCondition.


[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20170
Немає можливості налаштування часу життя кешу для дат.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20297
Отримання nullPointerException якщо файл має статус *renamed*.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20628
При додаванні відсутньої версії-кандидата в api, повертається статус-код 200 та помилка у вигляді рядка `registry not found`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21177
Поле "Власники/управителі обраного об'єкта" не підтягує дані.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21338
Некоректно відпрацьовує сортування у admin/officer/citizen portals.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21397
Не підтягуються templates у бізнес-процеси адмін порталу.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21398
Під час редагування наявного БП, підтягується не вірна службова назва.

=== [ST1][Sprint 4][SECURITY] Дефекти безпеки
//https://jiraeu.epam.com/browse/MDTUDDM-20965

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20358
[Security][Group] Vulnerabilities in `org.apache.commons:commons-text`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-8110
Прибрали інформацію про проксі-сервер із заголовків відповіді сервера.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-9820
Додали заголовки `content-security-policy` у Кабінетах посадової особи та отримувача послуг.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-10051
Generic API key in reports/auditor/queries/parameter-queries.json file detected.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-10052
Generic API key in reports/auditor/system-events.json file detected.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-10053 	Generic API key in reports/auditor/user-events.json file detected.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-11777 	[Redash] Оновлення версії PostgreSQL.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-14721
[Security] [Group] Vulnerabilities in `org.springframework.security:spring-security-core`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-15237
[Security][Group] Vulnerabilities in `org.apache.logging.log4j:log4j-core`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-18812
Додали заголовок `Strict-Transport-Security` до всіх відповідей платформи.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-18815
Додали заголовок відповіді `X-Frame-Options`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-18816
Додали заголовок відповіді `X-Content-Type-Options`.

'''

=== Інші впровадження

==== Впровадження 1.9.1 [ST1]
//[S22][TECH_DEBT][ST1] Технічний борг 1.9.1
// https://jiraeu.epam.com/browse/MDTUDDM-21343

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-21461
Додали value StorageClass та velero-анотації для бекапу crunchy postgres-кластерів.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-16631
Update citizen-portal / officer-portal according to "form-submission-validation" API redesign.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-20285
Fix збірки keycloak-сторінок, пов'язаний із widgetHeight.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-20391
Змінили налаштування видалення авторизацій, створених camunda-auth-cli. Видалили усі авторизації, які "contains" READ, CREATE_INSTANCE.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20906
Не локалізовані елементи в Redash 10.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-16630
Редизайн внутрішніх API для "form-submission-validation" з метою узгодження по всій системі.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-16571
Підвищили фактичний coverage в _common-web-app_ до 85%.

'''

==== Впровадження 1.9.1 [ST2]
// [S22][TECH_DEBT][ST2] Технічний борг 1.9.1
// https://jiraeu.epam.com/browse/MDTUDDM-21394

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-15341
Додали retrying при зверненні до зовнішніх систем (АЦСК) у сервісі по роботі з системним підписом.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-20446
Додати до registry-regulation-validator-cli перевірку назв таблиць/колонок на співпадіння з зарезервованими словами java.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-20959
Перенести валідацію шаблонів email/inbox до validator-cli.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-21396
Прибрали NullPointerException для digital-signature-ops /citizen/verify, якщо allowedSubjects не існує або subject відсутній у токені.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-21556
Внесення змін в делегат Get citizen users by attributes from keycloak.

'''

==== Впровадження 1.9.1 [ST3]
// [S22] [TECH_DEBT] [ST3] Технічний борг 1.9.1
// https://jiraeu.epam.com/browse/MDTUDDM-21543

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-21491
Збільшення максимальної кількості символів для бізнес- та службової назв бізнес-процесу. Моделювальник регламенту реєстру може задавати назву БП зі збільшеною довжиною та додатковими символами. Це дозволить правильно представляти суть БП у назві.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21920
При копіюванні Бізнес-процесу, з перегляду іншого бізнес-процесу зникає префікс `Copy_`.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-12692
Компонент File з `clearWhenHidden=true` не очищується після зникнення, якщо показана валідаційна помилка.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-14293
Додано autocompletion для input-полів форми.

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-16455
Підготовка тестів для Java-сервісу по роботи з конфігураційними файлами регламенту.

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-20507
Рефакторинг _registry-regulations-management_.

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-20779
Рефакторинг репозиторію _registry-regulations-management_ згідно з діаграмою модулів.

'''

==== Впровадження 1.9.1 [PST]
//[S22][TECH_DEBT][PST] Технічний борг 1.9.1
//https://jiraeu.epam.com/browse/MDTUDDM-21765

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-20307
Доставка business-processes-modeler-extension в web-common-app.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-11863
Розроблено скрипти для зміни розміру persistent volume для Kafka & Zookeeper.

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-18994
Зміни в RPZM Denovo Backport helm chart.

////
//reopened for further improvements in 1.9.2
[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-13223
Clean-up пайплайн не видаляє registry-rest-api-deployment.
////

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-19772
Оновлено інтерфейс створення та редагування реєстрів згідно з новим дизайном.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21399
Видаляється рядок `deploymentMode` у _values.yaml_.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21520
Cleanup-job не виконується та видає помилку на delete release пайплайнах -- `"fatal: project not found"`.

'''

==== Тимчасове сховище проміжних даних виконання бізнес-процесів 1.9.1
//https://jiraeu.epam.com/browse/MDTUDDM-21841

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-13396
Знайдено оптимальні значення Redis-конфігурації.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13401
Створено Grafana-дашборд для моніторингу Redis-кластера.

'''

==== Створення нового запита на внесення змін до регламенту реєстру 1.9.1
//https://jiraeu.epam.com/browse/MDTUDDM-22100

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-19600
Перевірка поля "Опис" при створенні версії змін на наявність подвійних лапок адміністратором регламенту. Це дозволить уникнути помилки при збереженні у Gerrit через невірну обробку лапок.
====

'''

==== Тестування

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-22161
Функціональне та регресійне тестування на кластері `master-for-install`.

'''

==== Розширення пам'яті для Nexus

[CAUTION]
//https://jiraeu.epam.com/browse/MDTUDDM-22308
Розширено volume для Nexus для розгортання 1.9.1.

[#changes-1-9-0]
== Зміни у версії 1.9.0
//https://jiraeu.epam.com/browse/MDTUDDM-21092

=== Підтвердження каналу зв'язку "Дія" (OTP)
//https://jiraeu.epam.com/browse/MDTUDDM-19205

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19206
Реалізовано готовий шаблон push-повідомлення з кодом для підтвердження каналу зв'язку "Дія". Шаблон стає доступний при розгортанні нового реєстру у структурі регламенту.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19210
Можливість отримувати push-повідомлення з OTP-кодом у застосунок "Дія".

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19212
Можливість вносити OTP-код і підтверджувати активацію каналу зв'язку "Дія" у профілі Кабінету отримувача послуг.

=== Повідомлення у застосунку "Дія"
//https://jiraeu.epam.com/browse/MDTUDDM-11460

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18303
Імплементовано можливість моделювати шаблон повідомлення для застосунку "Дія" адміністратором регламенту.

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-19473
Для завантаження сформованих або відкорегованих адміністратором шаблонів повідомлень розширено пайплайн публікації регламенту етапом `publish-notification-templates` з викликом утиліти `notification-template-publisher`.

Моделювальник бізнес-процесів може використовувати унікальну назву опублікованого шаблону push-повідомлення для застосунку "Дія" (Notification message template) при моделюванні бізнес-процесу з кроком відправки повідомлення користувачу.
====

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19201
Можливість отримувати повідомлення у застосунку "Дія" отримувачем послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19522
Можливість логувати у журналі аудиту відправлення push-повідомлень у застосунок "Дія" користувачам.

=== Повідомлення у Кабінеті отримувача послуг (inbox) у текстовому форматі
//https://jiraeu.epam.com/browse/MDTUDDM-12411

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-16634
Для завантаження сформованих або відкорегованих адміністратором шаблонів повідомлень розширено пайплайн публікації регламенту етапом `publish-notification-templates` з викликом утиліти `notification-template-publisher`.

Моделювальник бізнес-процесів може використовувати унікальну назву опублікованого шаблону in-app повідомлення (Notification message template) при моделюванні бізнес-процесу з кроком відправки.
====

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12532
Реалізовано готовий шаблон inbox-повідомлення для Кабінету отримувача послуг. Шаблон стає доступний при розгортанні нового реєстру у структурі регламенту.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12531
Можливість отримувати in-app повідомлення в Кабінеті отримувача послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12535
Можливість переглядати вхідні повідомлення у Кабінеті отримувача послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-16646
Можливість бачити прочитані та непрочитані повідомлення в Кабінеті отримувача послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-16647
Можливість застосовувати пагінацію на сторінці вхідних повідомлень в Кабінеті отримувача послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19523
Можливість логувати у журналі аудиту відправлення in-app повідомлень у Кабінеті отримувача послуг.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21209
Не валідується токен на час дійсності.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21210
Невірний код відповіді при модифікації повідомлення клієнтом яке йому не належить.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21380
Не валідується "Заголовок повідомлення" на обов'язковість.

=== Підтвердження каналу зв'язку email в Кабінеті отримувача послуг (лише email OTP)

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17316
Реалізовано готовий шаблон повідомлення з кодом для підтвердження адреси електронної пошти. Шаблон стає доступний при розгортанні нового реєстру у структурі регламенту.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12526
Можливість вносити Email у профілі Кабінету отримувача послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17561
Можливість змінювати адресу електронної пошти у профілі Кабінету отримувача послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12525
Можливість внести код OTP і підтвердити дані вказаної електронної адреси у профілі Кабінету отримувача послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12731
Можливість отримувати повідомлення з кодом на вказаний Email для підтвердження вказаної електронної адреси.

=== Автоматичне розподілення задач на виконавців

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17488
Розширено делегат *Get users by attributes from keycloak* пошуком користувачів за КАТОТТГ.

=== Механізм роботи з масивом даних (в рамках бізнес-процесів)

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17916
Можливість для посадових осіб та отримувачів послуг зберігати дані з бізнес-процесів, внесені на формі за допомогою компонента *Edit Grid*, масивом до фабрики даних.

[IMPORTANT]
Помилка `Internal Server Error` виникає для звіту "Кадрове забезпечення лабораторії".

=== Первинне завантаження та дозавантаження даних (завантаження CSV файлів в БП)

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19743
Можливість на формі у компоненті *File* налаштовувати попередню перевірку CSV-файлу.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-16561
Можливість для посадових осіб та отримувачів послуг в рамках БП завантажувати/дозавантажувати файл з даними для збереження їх до бази даних.

=== Вказання назви секрету, без вказання токена авторизації, при налаштуванні інтеграції з ЄДР

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19882
Можливість у файлі _configuration.yml`_ при налаштуванні інтеграції з ЄДР, вказувати назву секрету, без вказання токена авторизації.

=== Розширення функціональних можливостей виконанням задач бізнес-процесів підтримкою проміжного збереження даних в Кабінетах посадової особи та отримувача послуг

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-4039
Можливість проміжного збереження при внесенні даних через форми задач (для отримувача послуг).

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18876
Можливість повернутись до виконання ініційованого раніше бізнес-процесу, в якому було збережено внесені дані на формі задач (для отримувача послуг).

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-1151
Можливість проміжного збереження при внесенні даних через форми задач (для посадової особи).

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18877
Можливість повернутись до виконання ініційованого раніше бізнес-процесу, в якому було збережено внесені дані на формі задач (для посадової особи).

=== Розширення переліку та вдосконалення підтримуваних компонент для моделювання UI-форм

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13039
Можливість налаштовувати тип сортування для стовпців у компонентах, що використовуються для компонента *EditGrid*. Сортування виконується як для строкових даних, так і для числових.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13162
Можливість обмежувати введення пробілів на початку та в кінці у компоненті *Textfield*.

=== Пакетне завантаження посадових осіб реєстру

//TODO: Not yet ready
//[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12744
//Можливість вивантажити CSV-файл, що використовувався для імпорту користувачів в Keycloak (для адміністратора доступу).

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-16868
Перегляд у технічних логах лише інформації, яка стосується завантаження користувачів (для адміністратора доступу).

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-13265
Файл з іменем кирилицею не завантажується до сховища.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-14419
Помилки про невідповідність розміру кодування та типу файлу перестають змінюватися після другого виникнення.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-16434
Внести зміни на сторінках admin-portal, що пов'язані з автоматичним завантаженням користувачів до Keycloak.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-16564
Якщо user-publisher при запиті access token отримує код `401 UNAUTHORIZED`, він відмовляє з помилкою `StackOverflowError`.

=== Управління глобальними налаштуваннями реєстру

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17575
Можливість управляти глобальними налаштуваннями реєстру в рамках моделювання регламенту.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20637
Відсутність regexp та тексту помилки, якщо email входить до списку заборонених.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20638
Відсутність червоної зірочки на обов'язкових полях.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20639
Колір тексту не відповідає mockup.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20717
Некоректно відпрацьовує settings validation.

=== Перегляд переліку таблиць моделі даних реєстру та їх структур
//https://jiraeu.epam.com/browse/MDTUDDM-13321

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17568
Можливість переглядати список таблиць для Майстер-версії.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18909
Можливість переглядати структуру таблиці у майстер-версії (вкладка "Колонки").

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20580
На сторінці перегляду таблиць ширина стовпців не визначена відповідно до mockup.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20581
Відсутня пагінація на сторінці перегляду таблиці у майстер-версії.

=== Перевірка та фіксація наявності конфліктів запита на внесення змін та майстер-версії регламенту реєстру

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17562
Можливість бачити відображення в огляді версії-кандидата інформацію про конфліктні зміни.

[IMPORTANT]
====
Не додається форма при rebase у версію кандидата. При творенні двох запитів версії кандидата, якщо в одному запиті видалити, або додати форму, і злити її, то у другому запиті версії кандидата при rebase не з'являється ця форма.
====

=== Внесення змін до складових запита на внесення змін до регламенту

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13369
Можливість вносити зміни до складових запита на внесення змін до регламенту реєстру.

[IMPORTANT]
====
//https://jiraeu.epam.com/browse/MDTUDDM-17305
Користувач з будь-якого реалму Keycloak (`officer`/`citizen`/`admin`) може використовувати API registry-regulation-management.
====

[IMPORTANT]
====
//https://jiraeu.epam.com/browse/MDTUDDM-17502
При розгортанні нового реєстру сервіс не стартує.

В логах ми можемо побачити помилку. Помилка виникає, тому що при розгортанні спочатку створюються всі поди та тільки після цього, якщо вони встановилися успішно, створюється Gerrit-репозиторій, але сервіс не може запуститися без підключення до репозиторію.
====

=== Активація запита на внесення змін до регламенту реєстру адміністратором зі спадного меню

[TIP]
Реалізовано можливість активувати у спадному списку необхідний запит на внесення змін до реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-14016

=== Інтеграція запита на внесення змін до майстер-версії регламенту реєстру
//Epic link: https://jiraeu.epam.com/browse/MDTUDDM-13349

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19143
При створенні кандидат-версії, форми сортуються за колонкою, за якою були відсортовані у майстер-версії.

=== Базові функції та навігація кабінету адміністратора, відображення назви майстер-версії
//https://jiraeu.epam.com/browse/MDTUDDM-13370

[TIP]
//2 частини
//https://jiraeu.epam.com/browse/MDTUDDM-16860
//https://jiraeu.epam.com/browse/MDTUDDM-18891
Можливість бачити дату створення/редагування форм для майстер/кандидат версії.

[IMPORTANT]
====
//https://jiraeu.epam.com/browse/MDTUDDM-19035
Заборонити змінювати службову назву форми при редагуванні форми.

Зробити поле `Службова назва форми` -- `disabled` при редагуванні.
====

=== Управління бізнес-процесами реєстру
//https://jiraeu.epam.com/browse/MDTUDDM-13326

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19717
При пошуку БП/форм/звітів результат не відображається, якщо пошук виконувався з останньої сторінки таблиці.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19951
На сторінці "Створення бізнес-процесу" описи полів для введення не відповідають очікуваним відповідно до mockup.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19777
При створенні бізнес-процесу відсутня вкладка с трьома крапками (`...`).

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20293
На сторінці редагування бізнес-процесу (вкладка "Конструктор") при натисканні на Меню (три крапки) список можливих дій відображається за панеллю налаштувань Camunda Modeler.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20295
Під час клонування бізнес-процесу, на вкладці "Конструктор" виникає помилка.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21484
Шрифт відображення XML-представлення не відповідає очікуваному на вкладці "Код" під час створення бізнес-процесу.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21486
Неможливо повністю видалити xml-представлення на вкладці "Код" під час створення бізнес-процесу.

=== Тимчасове сховище проміжних даних виконання бізнес-процесів
//https://jiraeu.epam.com/browse/MDTUDDM-13044

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-13424
Не видаляються проміжні дані бізнес-процесу після його завершення.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-13509
`Excerpt-service-api` неправильно отримує bucket name.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-14580
Перевірити спроби сервісу rest-api під'єднатися до Redis.

=== Конфігурація DNS-імен для реєстрів та захист адміністративних ендпоінтів у Control Plane
//https://jiraeu.epam.com/browse/MDTUDDM-12978

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13157
Можливість обмежувати доступ до адміністративних та реєстрових ендпоінтів.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13158
Можливість задавати власне DNS-ім'я для кабінетів посадової особи та отримувача послуг.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-18653
Додати валідацію на введення короткого DNS.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-18654
Додати посилання на інструкції по налаштуванню зовнішньої конфігурації адміністратором.

=== Розробка Control Plane для адміністрування тенантів/реєстрів

[IMPORTANT]
Після відновлювання резервної копії  Control-plane неможливо увійти до Gerrit платформи.

[IMPORTANT]
Реєстри не розгортаються паралельно.

[IMPORTANT]
Не видаляються реєстри через адмін-консоль.

[IMPORTANT]
Переобрана роль `cp-registry-admin-{REGISRTY_ALIAS}`, що створюється під час розгортання реєстру, не набуває своєї дії.

[IMPORTANT]
Користувач з роллю `cp-registry-admin-{REGISRTY_ALIAS}` не має доступу до платформних Gerrit та Jenkins job свого реєстру.

[IMPORTANT]
Користувач з роллю `cp-registry-admin-{REGISRTY_ALIAS}` не має доступу до *Role Mappings* у реалмах свого реєстру.

[IMPORTANT]
Після видалення реєстру з адмін-консолі, залишається його група в OKD.

[IMPORTANT]
Не розгортається реєстр із шаблоном `template-registry-dev-recommended`.

[IMPORTANT]
Реєстри створюються з порожнім полем "Адміністратори".

[IMPORTANT]
Якщо видалити адміна при редагуванні реєстру, то відповідна роль `cp-registry-admin-namespace` не видаляється з *Assigned Roles*.

[IMPORTANT]
`Reg-Dev-Minimal` template: під час спроби запуску бізнес-процесу у Кабінеті посадової особи та отримувача послуг, виникає помилка `"Status Code: 500 Internal Server Error"`.

[IMPORTANT]
В Кабінеті посадової особи при підписі будь-якого бізнес-процесу, виникає помилка "Дані в тілі не відповідають підпису".

[IMPORTANT]
Після оновлення реєстру до вищої гілки під час спроби запуску бізнес-процесу у Кабінеті посадової особи та отримувача послуг, виникає помилка `"Status Code: 500 Internal Server Error"`.

[IMPORTANT]
Під час входу адміністратора реєстру до реєстрових Keycloak через Openshift SSO, виникає помилка.

[IMPORTANT]
Після видалення реєстру через Control Plane, іноді залишається його репозиторій у Gerrit.

[IMPORTANT]
Admin-portal повинен відкривати посилання до admin-portal, а замість цього веде до Camunda.

[IMPORTANT]
Custom-ресурс `GerritGroupMember` ламається після кожного перезапуску `cluster-mgmt` job.

[IMPORTANT]
Не правильне сортування реєстрів за часом у Control Plane.

[IMPORTANT]
У Select-запиті на оновлення реєстру немає нової, старшої гілки.

[IMPORTANT]
Конфліктують групи `cluster-admins` та `cp-registry-admin`, якщо вони встановлені в одного і того ж користувача.

[IMPORTANT]
Пайплайн `history-excerptor` не виконується, якщо Cleanup job запустити декілька разів.

[IMPORTANT]
Заборонити вводити назву реєстру довжиною понад 12 символів на цільових кластерах.

[IMPORTANT]
Після видалення (cleanup), гілки для `history-excerptor` не створюються.

[IMPORTANT]
Після перезапуску кластера не підіймаються поди (pods) в наявних реєстрах через помилку з Kafka.
[IMPORTANT]
Видаляється рядок `deploymentMode` у файлі _values.yaml_.

=== Інші впровадження

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-10889
Автоматичне горизонтальне масштабування нод обробки баз даних

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12954
Захист адміністративних ендпоінтів за допомогою Kong

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12955
====
Server-side сесії на Kong.

Збереження токенів на стороні сервера.
====

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-20416
Можливість виконувати запит на злиття змін із Control Plane.

[TIP]
Оновлено компонент `velero` до версії `1.9.0`. Безпечний запуск pipeline з відновлення.

[IMPORTANT]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18530
Backport for RPZM in Denovo.

Сервіс `digital-signature-ops` зависає при інтеграції з `Гряда-301` під час виконання запитів `hashSigh` та `develop`.
//https://jiraeu.epam.com/browse/MDTUDDM-18594
====







