= Примітки до релізу 1.8
:toc:
:toclevels:
:toc-title: ЗМІСТ
:sectnums:
:sectnumlevels: 
:sectanchors:
:experimental:
:important-caption: ВИПРАВЛЕНО
:note-caption: ПОКРАЩЕНО
:tip-caption: РОЗРОБЛЕНО
:warning-caption: ДИЗАЙН
:caution-caption: ІНШЕ

== Зміни у версії 1.8.1

=== Налаштування та контроль рейт-лімітів

[TIP]
Відображення сторінки з помилкою при перевищенні кількості запитів до сервера у кабінетах `admin-`/`citizen-`/`officer-portal`.
//https://jiraeu.epam.com/browse/MDTUDDM-12163

=== Пакетне завантаження посадових осіб реєстру

[TIP]
Шифрування CSV-файлу при збереженні в Ceph.
//https://jiraeu.epam.com/browse/MDTUDDM-12679

[IMPORTANT]
Файл із кириличним ім'ям не завантажується до CEPH-bucket.
//https://jiraeu.epam.com/browse/MDTUDDM-13265

=== Запити від СС та бізнесу

[TIP]
Можливість використовувати конектор до Єдиної інформаційної бази даних внутрішньо переміщених осіб у бізнес-процесах (конектор ЄІБДВПО).
//https://jiraeu.epam.com/browse/MDTUDDM-13295

=== Запити від СС та бізнесу 1.8

[TIP]
Формування унікального номера для створених у реєстрі сутностей (документів) за допомогою атрибута `ext:autoGenerate` у тегу `<column>`.
//https://jiraeu.epam.com/browse/MDTUDDM-16858

[TIP]
Можливість використовувати тип пошуку `notIn` (масив) для створення search conditions при моделюванні даних.
//https://jiraeu.epam.com/browse/MDTUDDM-12858

=== Розширення переліку підтримуваних компонентів для моделювання UI-форм

[NOTE]
Видалення функції `Redraw On` для стилізованих компонентів форм: `Radiobutton`, `Date/Time`, `File`, `CheckBox`.
//https://jiraeu.epam.com/browse/MDTUDDM-16432

[TIP]
Можливість для адміністратора регламенту обирати декілька значень параметра `Refresh option on` для оновлення значення в компоненті *Select*.
//https://jiraeu.epam.com/browse/MDTUDDM-13161


=== Управління схемами UI-форм реєстру

[WARNING]
Розробка дизайну Rest API для забезпечення роботи з формами.
//https://jiraeu.epam.com/browse/MDTUDDM-14230

=== Базові функції та навігація кабінету адміністратора, відображення назви майстер-версії

[WARNING]
Розробка дизайну Rest API для отримання інформації про відкритий запит.
//https://jiraeu.epam.com/browse/MDTUDDM-14227

[TIP]
Розробка Rest API endpoint для отримання переліку версій.
//https://jiraeu.epam.com/browse/MDTUDDM-14228

=== Створення нового запита на внесення змін до регламенту реєстру

[WARNING]
Розробка дизайн Rest API для створення нової версії-кандидата.
//https://jiraeu.epam.com/browse/MDTUDDM-14225

[TIP]
Імплементація Rest API endpoint для створення нової версії-кандидата.
//https://jiraeu.epam.com/browse/MDTUDDM-14226

=== Встановлення та конфігурація геосервера

[TIP]
Включення конфігурації геосервера до пайплайну розгортання регламенту реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-15494

[TIP]
Сервіс для конфігурації GeoServer через REST API.
//https://jiraeu.epam.com/browse/MDTUDDM-15493

//'''
//Додавання геотипів до фабрики даних ::
//TODO: Add RN for 1.8.2+

//'''
//Компонент Form.io для відображення геоданих ::
//TODO: Add RN for 1.8.2+

=== Розробка Control Plane для керування тенантами/реєстрами

[TIP]
Можливість задавати адміністраторів платформи через адмін-консоль.
//https://jiraeu.epam.com/browse/MDTUDDM-13043

[TIP]
Перегляд змін до реєстру адміністратором, що вносяться через МР до control-plane-console.
//https://jiraeu.epam.com/browse/MDTUDDM-12723

[TIP]
В адмін-консолі, у вікні реєстру додано посилання до сервісів `citizen-portal` та `officer-portal`.
//https://jiraeu.epam.com/browse/MDTUDDM-14026


=== Автоматизація та процедури розгортання системи управління реєстрами (control plane)

[IMPORTANT]
Процес збірки реєстру `MASTER-Build` не виконується після додавання адміністратора реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-18622

[IMPORTANT]
Процес збірки реєстру `MASTER-Build` викликається після створення МР (статус NEW) на додавання нового адміністратора реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-18618

[IMPORTANT]
Адміністратор реєстру не може додати нового адміністратора реєстру, немає прав на submit МР до центрального Gerrit.
//https://jiraeu.epam.com/browse/MDTUDDM-18617

=== Тимчасове сховище проміжних даних виконання бізнес-процесів

[TIP]
Імплементовано новий делегат _systemDigitalSignature.json_. +
Замінено підпроцес System Digital Signature на окремий делегат для підпису системним ключем.

[NOTE]
====
Скасовано підтримку застарілих делегатів для бізнес-процесів:

* _putContentToCeph.json_
* _readContentFromCeph.json_
* _putFormDataToCeph.json_
* _readFormDataFromCeph.json_
====

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13225
Створено репозиторій `ddm-file-storage`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13281
Оновлено `registry-rest-api` для використання `ddm-form-storage`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13280
Оновлено `excerpt-api-service` для використання `ddm-form-storage`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13205
Оновлено `digital-document-service` для використання `ddm-file-storage`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13196
Проведено рефакторинг коду для інтеграції з Ceph у модулі `ddm-file-storage`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13074
Змінено використання Ceph-сховища для делегатів підпису на Storage-сервіси.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13282
Підключено нові версії бібліотек `form-data-storage`, `message-payload-storage` та `file-storage` для bpms.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13062
Додано інтеграцію з Redis до `ddm-form-data-storage`.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13065
Додано імплементацію репозиторію із підтримкою redis.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13066
Реалізовано підтримку зберігання форм та повідомлень у JSON-форматі.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13062
Проведено рефакторинг інтеграції з Ceph.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13195
Додано інтеграцію з Redis до `ddm-message-payload-storage`.

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-13219
Проведено рефакторинг інтеграції з Ceph у модулі `ddm-message-payload`.

Створено репозиторій `ddm-message-payload` та переміщено до нього імплементацію використання Redis для тимчасового сховища для message-payload даних.
====

[IMPORTANT]
Excerpt-service-api неправильно отримує bucket name.
//https://jiraeu.epam.com/browse/MDTUDDM-13509

[IMPORTANT]
Не видаляються проміжні дані бізнес-процесу після його завершення.
//https://jiraeu.epam.com/browse/MDTUDDM-13424

=== Технічна якість платформи

[NOTE]
Повернення коду `500` (http status code) замість `200` при помилці отримання time stamp при спробі підпису системним ключем у сервісі по роботі з цифровим підписом.
//https://jiraeu.epam.com/browse/MDTUDDM-15340

=== Регресійне тестування

[IMPORTANT]
Завантаження шаблону витягів використовує лише файл _styles.css_. При завантаженні видаляються усі стилі й використовується _style.css_ без перевірки наявності такого файлу.
//https://jiraeu.epam.com/browse/MDTUDDM-14242

=== Розробка типових розширень моделювання бізнес-процесів

[CAUTION]
Підготовка синтетичної моделі бізнес-процесу для проведення тестування.
//https://jiraeu.epam.com/browse/MDTUDDM-13079

=== Penetration test

[IMPORTANT]
Cookie сеансу не має встановленого прапорця безпеки "Secure".
//https://jiraeu.epam.com/browse/MDTUDDM-8769

'''

== Зміни у версії 1.8.2

=== Активація запиту на внесення змін до регламенту реєстру адміністратором зі спадного меню

[TIP]
Реалізовано можливість обрати зі спадного списку необхідний запит на внесення змін до реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-14016

=== Базові функції та навігація кабінету адміністратора, відображення назви майстер-версії

[TIP]
Для майстер-версії показується перелік форм, і вони доступні лише для перегляду та завантаження.
//https://jiraeu.epam.com/browse/MDTUDDM-14135

[TIP]
Створено сторінку з відображенням форм майстер-версії.
//https://jiraeu.epam.com/browse/MDTUDDM-14289

[TIP]
====
Створено оновлене меню навігації, що розташовується у лівій частині сторінки. Передбачено наступну структуру секцій:

- Організаційна структура;
- Управління користувачами;
- Моделювання регламенту;
- UI форми;
- Шаблон звітів.
//https://jiraeu.epam.com/browse/MDTUDDM-14500
====

[TIP]
Реалізовано можливість перегляду налаштувань форм майстер-версії, без можливості внесення змін.
//https://jiraeu.epam.com/browse/MDTUDDM-16563

=== Внесення змін до складових запиту на внесення змін регламенту реєстру

[TIP]
Розроблено java-сервіси для роботи з конфігураційними файлами регламенту.
//https://jiraeu.epam.com/browse/MDTUDDM-14234
[TIP]
Забезпечено коректну роботу git/gerrit сервісів під час одночасного їх використання декількома користувачами.
//https://jiraeu.epam.com/browse/MDTUDDM-16227
[IMPORTANT]
Помилка при розгортанні нового реєстру, сервіс не може розпачати роботу без підключення до репозиторію.
//https://jiraeu.epam.com/browse/MDTUDDM-17502

=== Інтеграція Платформи Реєстрів iз зовнішніми системами

[NOTE]
Додано автоматичне розширення service entry в пайплайні публікації за всіма зовнішніми посиланнями, що вказані в реєстрі, щоб надати доступ до зовнішніх систем.
//https://jiraeu.epam.com/browse/MDTUDDM-13602

=== Пакетне завантаження посадових осіб реєстру

[NOTE]
Адаптовано функціональність імпорту посадових осіб через файл в оновленому Кабінеті адміністратора регламентів.
//https://jiraeu.epam.com/browse/MDTUDDM-14027

=== Перегляд метаданих відкритого запита на внесення змін до регламенту реєстру, можливості застосування та відізвання запита

[TIP]
Реалізовано відображення контексту обраного відкритого запиту на внесення змін та управління UI формами. При виборі відкритого запита у спадному списку, адміністратору показується сторінка зі списком змодельованих форм, на якій можливо відредагувати форму, копіювати, завантажити, видалити.
//https://jiraeu.epam.com/browse/MDTUDDM-14018

=== Регресійне тестування

[IMPORTANT]
При спробі увійти до Кабінету громадянина, користувач який не має роль "citizen" у KeyCloak, отримував помилка з пустою сторінкою. Після виправлення відображається сторінка з помилкою "403 Доступ заборонено".
//https://jiraeu.epam.com/browse/MDTUDDM-10980
[IMPORTANT]
Процес розгортання зависає на етапі excerpt-service-api, в логах виникає помилка та пода перебуває у статусі "Pending 1/2".
//https://jiraeu.epam.com/browse/MDTUDDM-13104
[IMPORTANT]
Некоректна робота, коли система дає можливість подальшого розгортання оточення, навіть якщо бізнес-процес не був доданий до оточення, системний WARN та помилку можливо відстежити тільки при падінні тестових етапів.
Після виправлення система не дає можливість подальшого розгортання оточення, якщо бізнес-процес не був доданий до оточення та пайплайн генерує помилку саме на цьому етапі.
//https://jiraeu.epam.com/browse/MDTUDDM-11885

=== Створення нового запита на внесення змін до регламенту реєстру

[TIP]
Реалізовано можливість створення нового запита на внесення змін до реєстру, натиснувши "+ Створити новий запит" з меню випадного списку версій.
//https://jiraeu.epam.com/browse/MDTUDDM-14017

=== Управління схемами UI-форм реєстру

[TIP]
Реалізовано можливість перегляду та редагування форм шляхом переходу міх вкладками. Коли адміністатор переходить в режим створення або редагування форми, то він бачить вкладки у наступному порядку: "загальна", "код", "конструктор", "перегляд", "запит", іконка трьох крапок "дії над формою".
//https://jiraeu.epam.com/browse/MDTUDDM-12734

=== Управління шаблонами звітів реєстру

[TIP]
Адаптовано функціональність перегляду доступних звітів з можливістю їх завантаження в оновленому Кабінеті адміністратора регламентів.
//https://jiraeu.epam.com/browse/MDTUDDM-14020

=== Додавання гео-типів до дата фабрики

[TIP]
Реалізовано можливість збереження об'єктів за типом лінія та полігон до дата фабрики.
//https://jiraeu.epam.com/browse/MDTUDDM-17383

=== Компонент Form.io для відображення геоданих

[TIP]
Реалізовано можливість повернення координат вибраного об'єкта на формі у бізнес-процесі.
//https://jiraeu.epam.com/browse/MDTUDDM-13445
[NOTE]
Для спрощення досвіду моделювальника змінено формат даних, які повертає компонент Form.io для відображення геоданих до вигляду який очікує дата фабрика.
//https://jiraeu.epam.com/browse/MDTUDDM-18313
[TIP]
====
Створено два режими роботи для компонента карти "Map":

- Select mode - дозволяє кліком на обʼєкт на карті вибрати його, повернути данні відповідного формату про обраний обʼєкт, приховує кнопки керування з можливістю внесення нових обʼєктів;
- Edit mode - відображає кнопки керування для внесення нових точок, можливо внести тільки один обʼєкт, при натисканні на існуючі обʼєкти інших слоїв відбувається відображення підказки але обʼєкт не стає вибраним,  вибраними можуть вважатись тільки обʼєкти які були створені на карті.
//https://jiraeu.epam.com/browse/MDTUDDM-18316
====

== Зміни у версії 1.8.3

===  Мінімальний шаблон для vSphere
//https://jiraeu.epam.com/browse/MDTUDDM-19445

[NOTE]
====
Внесено зміни до мінімальної конфігурації (мінімального шаблону) для середовища vSphere. +
Кількість ресурсів змінено на `8 CPU` і `32 Gb RAM`.
====

=== Коригування конфігурації рівня деталізації для історичних подій бізнес-процесів
//https://jiraeu.epam.com/browse/MDTUDDM-18840

[NOTE]
====
* Внесено зміни до рівня фіксації історичних подій бізнес-процесів на рівні конфігурації `bpms`:
+
----
camunda.bpm.history-level: AUDIT
camunda.bpm.database-history-level: ACTIVITY
----

* Внесено зміни до рівня фіксації історичних подій бізнес-процесів на рівні конфігурації business-process-administration-portal:
+
----
camunda.bpm.history-level: AUDIT
camunda.bpm.database-history-level: ACTIVITY
----

* Для міграції наявних реєстрів оновлено скрипт `init` контейнера bpms.
====


=== Увімкнено доступність метрик для моніторингу для Java-застосунків
//https://jiraeu.epam.com/browse/MDTUDDM-18803

[NOTE]
====

На рівні Openshift-кластера, у `ConfigMaps` > _application.yaml_ налаштовано exposure метрик для моніторингу Prometheus для Java-застосунків:

[source,yaml]
----
management.endpoints.web.exposure.include: 'health, prometheus'
----
====

=== Можливість вказувати кастомні атрибути у файлі для імпорту користувачів

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18705

Адміністратор доступу може додати у CSV-файлі додаткові заголовки й, опційно, значення для них у рядках.

За наявності значення у додаткових полях, створюється відповідний атрибут з таким самим іменем у Keycloak для цього користувача
====

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18823

Додано обробку кастомних атрибутів у `user-publisher`.
====

=== Доступ трафіку до czo.gov.ua із сервісу КЕП-операцій

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18648

Відкрито трафік до зовнішнього сервісу `czo.gov.ua` із сервісу `digital-signature-ops`.
====

=== Оновлення версії ІІТ-бібліотеки для сервісу КЕП-операцій

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18641

Оновлено версію ІІТ-бібліотеки для сервісу `digital-signature-ops` до `1.3.236`.

Додано нову версію ІІТ-бібліотеки у nexus releases:

----
<dependency>
    <groupId>com.iit.certificateAuthority</groupId>
    <artifactId>eu-sign</artifactId>
    <version>1.3.236</version>
</dependency>
----
====

=== Налаштування Istio для сервісу КЕП-операцій

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18632
Сконфігуровано Istio для сервісу `digital-signature-ops`. +
Доступ до АЦСК при перевірці підпису не проходив при включеному Istio.
====


=== Сервіс digital-signature-ops зависає при інтеграції з Гряда-301

[IMPORTANT]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18594
Сервіс `digital-signature-ops` зависає при інтеграції з Гряда-301 при виконанні запитів hashSigh та develop.
====

=== Конфігурація Istio для розділення внутрішньої та зовнішньої адреси Keycloak

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18561

У випадку додавання короткого імені для Keycloak, кожний ресурс `RequestAuthentication` повинен мати наступну конфігурацію:

* `issuer`: <коротке ім'я Keycloak>
* `jwksUri` -- за замовчуванням.

В інших випадках URL встановлюється за замовчуванням.
====

=== Конфігурація Redash для розділення внутрішньої та зовнішньої адреси Keycloak

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18560
Налаштовано сервіс Redash для розділення внутрішньої та зовнішньої адреси Keycloak.
====

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18981

Додано на UI елементи керування для додавання короткого DNS-імені для Redash.

Аналогічно до кабінетів користувачів, додано елементи керування на UI для збереження у файлі _values.yaml_ введених значень для коротких імен компонента Redash та Keycloak:

----
keycloak:
  customHost: short-example-dns-name.com
----
====

=== Оновлення Openshift-кластера до версії 4.11

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18536
Оновлено Openshift-кластер до версії 4.11.
====

=== Допрацювання взаємодії з id.gov.ua
//https://jiraeu.epam.com/browse/MDTUDDM-18531

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-18529
Полагоджено генерацію Keycloak логін-сторінок.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18546
Додано підтримку production-віджету підпису.

=== Управління шаблонами звітів реєстру
//Epic link: https://jiraeu.epam.com/browse/MDTUDDM-13331

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18165
Можливість здійснювати пошук звітів у переліку шаблонів звітів адміністратором регламенту. +
Це дозволяє швидко знайти потрібний шаблон звіту у Кабінеті адміністратора регламенту.

=== Управління схемами UI-форм реєстру
//https://jiraeu.epam.com/browse/MDTUDDM-13329

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18102?src=confmacro
Можливість здійснювати пошук адміністратором регламенту за назвою форми в переліку форм та бачити поточну сторінку у розділі _Моделювання регламенту_. +
Це дозволяє швидко знайти потрібну форму у Кабінеті адміністратора регламенту.

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-16648
Можливість переглядати параметри запита до бази даних на вкладці "Запит".

При моделюванні форми з комплексними компонентами виникає потреба бачити, які саме дані форма отримає із бази даних, який саме запит виходить із форми в рамках бізнес-процесу. +
Для більшої прозорості та пришвидшення процесу розробки регламенту додано секцію, яка показує SQL запити до бази даних від форми.
====

=== Інтеграція запита на внесення змін до майстер-версії регламенту реєстру
//Epic link: https://jiraeu.epam.com/browse/MDTUDDM-13349

[TIP]
Можливість інтегрувати запит на внесення змін до майстер-версії регламенту реєстру адміністратором. Це дозволяє бачити внесені зміни до майстер-версії в Кабінеті адміністратора регламенту.
//https://jiraeu.epam.com/browse/MDTUDDM-18090

[TIP]
Створено ендпоінт для submit версії.
//https://jiraeu.epam.com/browse/MDTUDDM-18096

[TIP]
Створено ендпоінт для відкликання версії кандидата.
//https://jiraeu.epam.com/browse/MDTUDDM-18389

[TIP]
Імплементовано обробку кнопки "Застосувати зміни до майстер-версії".
//https://jiraeu.epam.com/browse/MDTUDDM-18390

[TIP]
Імплементовано обробку кнопки "Відхилити".
//https://jiraeu.epam.com/browse/MDTUDDM-18391

[IMPORTANT]
У майстер-версії не відображаються форми, які були злиті до майстер-гілки із кандидат-версії.
//https://jiraeu.epam.com/browse/MDTUDDM-18708

=== Автоматичне оновлення та актуалізація стану відкритих запитів на внесення змін згідно з останньою майстер-версією регламенту реєстру
//https://jiraeu.epam.com/browse/MDTUDDM-13356

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17551
Можливість бачити актуальний стан відкритого запита на внесення змін згідно з останньою майстер-версією регламенту реєстру. +
Це забезпечує актуалізацію стану регламенту згідно з останніми внесеними змінами для послуги у процесі розробки.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18392
Розроблено scheduler для pull та fetch репозиторіїв на файловій системі.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18393
Імплементовано scheduler для видалення клонів для злитих та відкликаних версій кандидатів.

=== Створення нового запиту на внесення змін до регламенту реєстру

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-16228

Імплементовано маркування MR у Gerrit, які відповідають версіям-кандидатам. +
Реалізовано контракт з ідентифікації MR в Gerrit, які відповідають версіям-кандидатам в admin-portal.

Це дозволяє показувати лише MR, що мають відношення до admin-portal.

Це також дозволяє не допустити внесення змін у MR, що були створені розробниками реєстру через Gerrit.
====

=== Запити від СС та бізнесу 1.8
//https://jiraeu.epam.com/browse/MDTUDDM-13380

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-12853
Можливість використовувати тип пошуку `notEquals` для створення search conditions.
====

=== Впровадження безпеки

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-15265
[Security][Group] history-excerptor base image update (openjdk:11.0.7-jre-slim)

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-15223
[Security][Group] platform-gateway base image update (openjdk:11.0.13-jre-slim)

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-14727
[Security][Group] report-publisher base image update (openjdk:11.0.7-jre-slim)

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-14726
[Security][Group] user-publisher base image update (openjdk:11.0.7-jre-slim)

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-14587
[Security][Group] registry-regulation-management base image update (openjdk:11.0.13-jre-slim)

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-14586
[Security][Group] Base image update openjdk:11.0.13-jre-slim

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-14583
[Security][Group] Base image update openjdk:11.0.7-jre-slim

=== Інше

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-13217
Після видалення реєстрів через консоль Control Plane залишаються їх мапери в `KeycloakRealmIdentityProvider`.





////
=== Інше
TODO: RN 1.8.4

[IMPORTANT]
====
При додаванні DNS імені не проходить оновлення реєстру з конфігурацією DNS. +

Після підтвердження Merge Request, збірка MASTER-Build не проходить і завершується помилкою в helm install.
//https://jiraeu.epam.com/browse/MDTUDDM-18974
====

[IMPORTANT]
При додаванні додаткового DNS імені, воно застосовується до іншого порталу.
//https://jiraeu.epam.com/browse/MDTUDDM-14635

[IMPORTANT]
При додаванні додаткового DNS імені, _values.yaml_ -- не валідний.
////