= Примітки до релізу 1.8
:toc:
:toclevels:
:toc-title: ЗМІСТ
:sectnums:
:sectnumlevels: 
:sectanchors:
:experimental:
:important-caption: ВИПРАВЛЕНО
:note-caption: ПОКРАЩЕНО
:tip-caption: РОЗРОБЛЕНО
:warning-caption: ДИЗАЙН
:caution-caption: ІНШЕ

== Зміни у версії 1.8.1

=== Налаштування та контроль рейт-лімітів

[TIP]
Відображення сторінки з помилкою при перевищенні кількості запитів до сервера у кабінетах `admin-`/`citizen-`/`officer-portal`.
//https://jiraeu.epam.com/browse/MDTUDDM-12163

=== Пакетне завантаження посадових осіб реєстру

[TIP]
Шифрування CSV-файлу при збереженні в Ceph.
//https://jiraeu.epam.com/browse/MDTUDDM-12679

[IMPORTANT]
Файл із кириличним ім'ям не завантажується до CEPH-bucket.
//https://jiraeu.epam.com/browse/MDTUDDM-13265

=== Запити від СС та бізнесу

[TIP]
Можливість використовувати конектор до Єдиної інформаційної бази даних внутрішньо переміщених осіб у бізнес-процесах (конектор ЄІБДВПО).
//https://jiraeu.epam.com/browse/MDTUDDM-13295

=== Запити від СС та бізнесу 1.8

[TIP]
Формування унікального номера для створених у реєстрі сутностей (документів) за допомогою атрибута `ext:autoGenerate` у тегу `<column>`.
//https://jiraeu.epam.com/browse/MDTUDDM-16858

[TIP]
Можливість використовувати тип пошуку `notIn` (масив) для створення search conditions при моделюванні даних.
//https://jiraeu.epam.com/browse/MDTUDDM-12858

=== Розширення переліку підтримуваних компонентів для моделювання UI-форм

[NOTE]
Видалення функції `Redraw On` для стилізованих компонентів форм: `Radiobutton`, `Date/Time`, `File`, `CheckBox`.
//https://jiraeu.epam.com/browse/MDTUDDM-16432

[TIP]
Можливість для адміністратора регламенту обирати декілька значень параметра `Refresh option on` для оновлення значення в компоненті *Select*.
//https://jiraeu.epam.com/browse/MDTUDDM-13161


=== Управління схемами UI-форм реєстру

[WARNING]
Розробка дизайну Rest API для забезпечення роботи з формами.
//https://jiraeu.epam.com/browse/MDTUDDM-14230

=== Базові функції та навігація кабінету адміністратора, відображення назви майстер-версії

[WARNING]
Розробка дизайну Rest API для отримання інформації про відкритий запит.
//https://jiraeu.epam.com/browse/MDTUDDM-14227

[TIP]
Розробка Rest API endpoint для отримання переліку версій.
//https://jiraeu.epam.com/browse/MDTUDDM-14228

=== Створення нового запита на внесення змін до регламенту реєстру

[WARNING]
Розробка дизайн Rest API для створення нової версії-кандидата.
//https://jiraeu.epam.com/browse/MDTUDDM-14225

[TIP]
Імплементація Rest API endpoint для створення нової версії-кандидата.
//https://jiraeu.epam.com/browse/MDTUDDM-14226

=== Встановлення та конфігурація геосервера

[TIP]
Включення конфігурації геосервера до пайплайну розгортання регламенту реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-15494

[TIP]
Сервіс для конфігурації GeoServer через REST API.
//https://jiraeu.epam.com/browse/MDTUDDM-15493

//'''
//Додавання геотипів до фабрики даних ::
//TODO: Add RN for 1.8.2+

//'''
//Компонент Form.io для відображення геоданих ::
//TODO: Add RN for 1.8.2+

=== Розробка Control Plane для керування тенантами/реєстрами

[TIP]
Можливість задавати адміністраторів платформи через адмін-консоль.
//https://jiraeu.epam.com/browse/MDTUDDM-13043

[TIP]
Перегляд змін до реєстру адміністратором, що вносяться через МР до control-plane-console.
//https://jiraeu.epam.com/browse/MDTUDDM-12723

[TIP]
В адмін-консолі, у вікні реєстру додано посилання до сервісів `citizen-portal` та `officer-portal`.
//https://jiraeu.epam.com/browse/MDTUDDM-14026


=== Автоматизація та процедури розгортання системи управління реєстрами (control plane)

[IMPORTANT]
Процес збірки реєстру `MASTER-Build` не виконується після додавання адміністратора реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-18622

[IMPORTANT]
Процес збірки реєстру `MASTER-Build` викликається після створення МР (статус NEW) на додавання нового адміністратора реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-18618

[IMPORTANT]
Адміністратор реєстру не може додати нового адміністратора реєстру, немає прав на submit МР до центрального Gerrit.
//https://jiraeu.epam.com/browse/MDTUDDM-18617

=== Тимчасове сховище проміжних даних виконання бізнес-процесів

[IMPORTANT]
Excerpt-service-api неправильно отримує bucket name.
//https://jiraeu.epam.com/browse/MDTUDDM-13509

[IMPORTANT]
Не видаляються проміжні дані бізнес-процесу після його завершення.
//https://jiraeu.epam.com/browse/MDTUDDM-13424

=== Технічна якість платформи

[NOTE]
Повернення коду `500` (http status code) замість `200` при помилці отримання time stamp при спробі підпису системним ключем у сервісі по роботі з цифровим підписом.
//https://jiraeu.epam.com/browse/MDTUDDM-15340

=== Регресійне тестування

[IMPORTANT]
Завантаження шаблону витягів використовує лише файл _styles.css_. При завантаженні видаляються усі стилі й використовується _style.css_ без перевірки наявності такого файлу.
//https://jiraeu.epam.com/browse/MDTUDDM-14242

=== Розробка типових розширень моделювання бізнес-процесів

[CAUTION]
Підготовка синтетичної моделі бізнес-процесу для проведення тестування.
//https://jiraeu.epam.com/browse/MDTUDDM-13079

=== Penetration test

[IMPORTANT]
Cookie сеансу не має встановленого прапорця безпеки "Secure".
//https://jiraeu.epam.com/browse/MDTUDDM-8769

'''

<<<

== Зміни у версії 1.8.2

=== Активація запиту на внесення змін до регламенту реєстру адміністратором зі спадного меню

[TIP]
Реалізовано можливість обрати зі спадного списку необхідний запит на внесення змін до реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-14016

=== Базові функції та навігація кабінету адміністратора, відображення назви майстер-версії

[TIP]
Для майстер-версії показується перелік форм, і вони доступні лише для перегляду та завантаження.
//https://jiraeu.epam.com/browse/MDTUDDM-14135

[TIP]
Створено сторінку з відображенням форм майстер-версії.
//https://jiraeu.epam.com/browse/MDTUDDM-14289

[TIP]
====
Створено оновлене меню навігації, що розташовується у лівій частині сторінки. Передбачено наступну структуру секцій:

- Організаційна структура;
- Управління користувачами;
- Моделювання регламенту;
- UI форми;
- Шаблон звітів.
//https://jiraeu.epam.com/browse/MDTUDDM-14500
====

[TIP]
Реалізовано можливість перегляду налаштувань форм майстер-версії, без можливості внесення змін.
//https://jiraeu.epam.com/browse/MDTUDDM-16563

=== Внесення змін до складових запиту на внесення змін регламенту реєстру

[TIP]
Розроблено java-сервіси для роботи з конфігураційними файлами регламенту.
//https://jiraeu.epam.com/browse/MDTUDDM-14234
[TIP]
Забезпечено коректну роботу git/gerrit сервісів під час одночасного їх використання декількома користувачами.
//https://jiraeu.epam.com/browse/MDTUDDM-16227
[IMPORTANT]
Помилка при розгортанні нового реєстру, сервіс не може розпачати роботу без підключення до репозиторію.
//https://jiraeu.epam.com/browse/MDTUDDM-17502

=== Інтеграція Платформи Реєстрів iз зовнішніми системами

[NOTE]
Додано автоматичне розширення service entry в пайплайні публікації за всіма зовнішніми посиланнями, що вказані в реєстрі, щоб надати доступ до зовнішніх систем.
//https://jiraeu.epam.com/browse/MDTUDDM-13602

=== Пакетне завантаження посадових осіб реєстру

[NOTE]
Адаптовано функціональність імпорту посадових осіб через файл в оновленому Кабінеті адміністратора регламентів.
//https://jiraeu.epam.com/browse/MDTUDDM-14027

=== Перегляд метаданих відкритого запита на внесення змін до регламенту реєстру, можливості застосування та відізвання запита

[TIP]
Реалізовано відображення контексту обраного відкритого запиту на внесення змін та управління UI формами. При виборі відкритого запита у спадному списку, адміністратору показується сторінка зі списком змодельованих форм, на якій можливо відредагувати форму, копіювати, завантажити, видалити.
//https://jiraeu.epam.com/browse/MDTUDDM-14018

=== Регресійне тестування

[IMPORTANT]
При спробі увійти до Кабінету громадянина, користувач який не має роль "citizen" у KeyCloak, отримував помилка з пустою сторінкою. Після виправлення відображається сторінка з помилкою "403 Доступ заборонено".
//https://jiraeu.epam.com/browse/MDTUDDM-10980
[IMPORTANT]
Процес розгортання зависає на етапі excerpt-service-api, в логах виникає помилка та пода перебуває у статусі "Pending 1/2".
//https://jiraeu.epam.com/browse/MDTUDDM-13104
[IMPORTANT]
Некоректна робота, коли система дає можливість подальшого розгортання оточення, навіть якщо бізнес-процес не був доданий до оточення, системний WARN та помилку можливо відстежити тільки при падінні тестових етапів.
Після виправлення система не дає можливість подальшого розгортання оточення, якщо бізнес-процес не був доданий до оточення та пайплайн генерує помилку саме на цьому етапі.
//https://jiraeu.epam.com/browse/MDTUDDM-11885

=== Створення нового запита на внесення змін до регламенту реєстру

[TIP]
Реалізовано можливість створення нового запита на внесення змін до реєстру, натиснувши "+ Створити новий запит" з меню випадного списку версій.
//https://jiraeu.epam.com/browse/MDTUDDM-14017

=== Управління схемами UI-форм реєстру

[TIP]
Реалізовано можливість перегляду та редагування форм шляхом переходу міх вкладками. Коли адміністатор переходить в режим створення або редагування форми, то він бачить вкладки у наступному порядку: "загальна", "код", "конструктор", "перегляд", "запит", іконка трьох крапок "дії над формою".
//https://jiraeu.epam.com/browse/MDTUDDM-12734

=== Управління шаблонами звітів реєстру

[TIP]
Адаптовано функціональність перегляду доступних звітів з можливістю їх завантаження в оновленому Кабінеті адміністратора регламентів.
//https://jiraeu.epam.com/browse/MDTUDDM-14020

=== Додавання гео-типів до дата фабрики

[TIP]
Реалізовано можливість збереження об'єктів за типом лінія та полігон до дата фабрики.
//https://jiraeu.epam.com/browse/MDTUDDM-17383

=== Компонент Form.io для відображення геоданих

[TIP]
Реалізовано можливість повернення координат вибраного об'єкта на формі у бізнес-процесі.
//https://jiraeu.epam.com/browse/MDTUDDM-13445
[NOTE]
Для спрощення досвіду моделювальника змінено формат даних, які повертає компонент Form.io для відображення геоданих до вигляду який очікує дата фабрика.
//https://jiraeu.epam.com/browse/MDTUDDM-18313
[TIP]
====
Створено два режими роботи для компонента карти "Map":

- Select mode - дозволяє кліком на обʼєкт на карті вибрати його, повернути данні відповідного формату про обраний обʼєкт, приховує кнопки керування з можливістю внесення нових обʼєктів;
- Edit mode - відображає кнопки керування для внесення нових точок, можливо внести тільки один обʼєкт, при натисканні на існуючі обʼєкти інших слоїв відбувається відображення підказки але обʼєкт не стає вибраним,  вибраними можуть вважатись тільки обʼєкти які були створені на карті.
//https://jiraeu.epam.com/browse/MDTUDDM-18316
====






////
=== Інше
TODO: RN 1.8.4

[IMPORTANT]
====
При додаванні DNS імені не проходить оновлення реєстру з конфігурацією DNS. +

Після підтвердження Merge Request, збірка MASTER-Build не проходить і завершується помилкою в helm install.
//https://jiraeu.epam.com/browse/MDTUDDM-18974
====

[IMPORTANT]
При додаванні додаткового DNS імені, воно застосовується до іншого порталу.
//https://jiraeu.epam.com/browse/MDTUDDM-14635

[IMPORTANT]
При додаванні додаткового DNS імені, _values.yaml_ -- не валідний.
////