= Примітки до релізу 1.7
:toc:
:toclevels: 5
:toc-title: ЗМІСТ
:sectnums:
:sectnumlevels: 5
:sectanchors:
:experimental:
:important-caption: ВИПРАВЛЕНО
:note-caption: ПОКРАЩЕНО
:tip-caption: РОЗРОБЛЕНО
:warning-caption: ДИЗАЙН
:caution-caption: ІНШЕ

== Зміни у версії 1.7.0

Автоматична валідація змін до регламенту на етапі публікації

[NOTE]
Об'єднано валідацію регламенту бізнес-процесу та моделі даних у єдину утиліту "registry-regulations-validator-cli".

'''
Міжреєстрова взаємодія реєстрів на Платформі зі сторонньою єдиною інформаційною системою, якщо вони розгорнуті в межах одного ЦОД
(API без ШБО "Трембіта")

[TIP]
Для розробників регламенту реалізовано можливість викликати зовнішньою системою по REST API бізнес-процеси, які були розроблені на платформі.

'''
Міжреєстрова взаємодія реєстрів різних власників на одному екземплярі Платформи
(API без ШБО "Трембіта")

[TIP]
Створено service account в realm "external-systems" через Control plane реєстру та виконано збереження параметрів входу до центрального Vault. На сторінці реєстру додано нову секцію "Доступ для реєстрів платформи та зовнішніх систем. В цьому списку можна побачити список реєстрів та зовнішніх систем (їх назву, статус, тип),  для яких надано доступ до даних цього реєстру, а також можливо управляти цим доступом.


[TIP]
Для імплементації успішного виклику registry-rest-api іншого реєстру реалізовано фільтр в Platform Gateway, який забирає параметри логіну з Vault, аутентифікується з ними в external-system realm цільового реєстру (отримує токен) і перенаправляє запит з цим токеном до цільового реєстру.


[CAUTION]
Згенеровано istio virtualservice для точок інтеграції, які були опубліковані.


[TIP]
Розширено тег "exposeSearchCondition", додано обробку нових параметрів до тегу для комунікації реєстрів без ШБО "Трембіта.


[CAUTION]
Створено модель та опрацьовано тестові бізнес-процеси з метою тестування реалізованої розробки.


[TIP]
Створено автоматизовані тести в в репозиторії "user-cabinets-ui-tests", "data-integration-tests". Імплементація тестів для перевірки створення групи споріднених реєстрів дозволяє виконати перевірку правильно розгорнутої моделі даних і перевірку можливості запуску бізнес процесів в новій групі реєстрів.


[TIP]
Реалізовано відображення спливаючого тексту підказки (tooltip) з назвою кнопки чи описом статусу, при наведенні курсора на іконку кнопки чи іконку статусу без опису.


[CAUTION]
Розгорнута data-модель для тестового "Реєстру шкіл", для можливості здійснити перевірку функціональності на тестовому БП.


[CAUTION]
Розгорнута data-модель для тестового "Реєстру учнів" без даних, для можливості здійснити перевірку функціональності на тестовому БП.


[IMPORTANT]
Виправлено відображення tooltip у Control Plane на сторінках: "Інформація про реєстри", "Керування кластером".


[IMPORTANT]
Запит до іншого реєстру з увімкненим Istio більше не блокується.

'''
Розширення можливостей моделювання бізнес-процесів підтримкою альтернативних гілок

[WARNING]
Для користувача кабінету реалізована можливість повернутися до попередньої форми та виправити внесені дані, якщо в рамках бізнес-процесу є дві чи більше задач розподілених на нього в ряд, та коли процесс змодельований зі стартовою формою.


[NOTE]
Змінено транзієнтність даних ініціатора для бізнес-процесу. Це потрібно тому, що дані initiator() зберігаються тільки до виконання першої форми. Якщо ж перейти з форми назад – ці дані потрібні ще раз.


[NOTE]
Компонент Button розширено можливістю змоделювати перехід на альтернативні гілки. Додано кастомну опцію Navigation, завдяки якій є можливість додати Action code.


[CAUTION]
Виконана заміна initiator() на submission() для отримання access key.

'''
Формування витягів (наказів) у кабінеті чиновника у форматі DOCX та витягів-звітів у форматі CSV

[CAUTION]
Створено шаблон Проекту наказу у форматі docx (з вбудованими ресурсами) для прикладу.


[TIP]
Створено endpoint за типом Search condition для заповнення поля 'ПІБ співробітника' з підтримкою READ ALL.


[IMPORTANT]
Виправлена помилка з відображенням кнопки "Завантажити витяг" після валідної генерації документа на сервері, у меню "Надані послуги" в кабінеті чиновника.


[IMPORTANT]
Виправлено невідповідність контрактів надсилання даних у БД та отримання цих даних у стилізованому EditGrid через відправлення даних із Radio компонента.

'''
Пов'язані selects для звітів Redash

[NOTE]
Для адміністратора сервісу звітності реалізована можливість робити зв'язані селекти в фільтрації (Parameters) при моделюванні дашборду в Redash Admin.

'''
Запити від Competency Center та бізнесу для релізу 1.7

[TIP]
Реалізована можливість для моделювальників баз даних використовувати тип пошуку between для створення search conditions.


[WARNING]
Розроблено конектор до ЄІБДВПО (Єдина інформаційна база даних про внутрішньо переміщених осіб) через ШБО Трембіта. Необхідно для реалізації можливості використовувати конектор під час моделювання бізнес процесах

'''
Тимчасове сховище проміжних даних виконання бізнес-процесів

[WARNING]
Розроблено дизайн використання Redis у якості тимчасового сховища даних, внесених через UI-форми задач бізнес-процесу.

'''
Конфігурація DNS імен для реєстрів та захист адміністративних ендпоїнтів в control-plane

[WARNING]
Реалізовано можливість для адміністратора платформи задати IP-адреси з яких буде дозволений доступ до реєстрових компонентів. Адміністратор має можливість задавати список IP-адрес окремо для кабінету чиновника, кабінету громадянина та окремо для адміністративних компонентів.


[WARNING]
Реалізована можливість вказати список дозволених IP-адрес окремо для кластер-менеджменту та кожного реєстру в Controlplane.


[WARNING]
Розроблено дизайн налаштування кастомного DNS імені для кабінетів реєстру. Функціоналом передбачена можливість задати кастомне DNS ім'я для кабінету чиновника та громадянина через control-plane для відповідного реєстру.

'''
Підготування до релізу на залізо ДП УСС

[NOTE]
Застосовано конфігурацію промислового КЕП-віджета для аутентифікації та підпису даних користувачів.

'''
Розширення можливостей моделювання бізнес-процесів підтримкою відправки повідомлень

[WARNING]
Реалізована можливість моделювання відправку повідомлень у канали зв'язку користувача. У каталозі моделювальника бізнес-процесів додано типове розширення "Send User Notification".


[WARNING]
Реалізовано логування відправки повідомлень користувачам (факт вдалої та невдалої відправки повідомлення) в журналі аудиту.


[CAUTION]
Змодельовано та опрацьовано тестовий бізнес-процес з відправкою повідомлень одному користувачу, з метою тестування реалізованої розробки.


[CAUTION]
Змодельовано та опрацьовано тестовий бізнес-процес з відправкою повідомлень декільком користувачу, з метою тестування реалізованої розробки.

'''
Механізм завантаження масиву користувачів реєстру

[TIP]
Реалізовано автоматичне створення клієнта з сервіс екаунтом в officer реалмі KeyCloak при створенні реєстру, що необхідно для доступу процесу імпорту користувачів до API KeyCloak з метою створення масиву користувачів.


[TIP]
Розроблено модуль (Kubernetes job) для створення користувачів через KeyCloak REST API. Модуль виконує наступні задачі: зчитує файл, що містить дані користувачів; валідує дані; створює користувачів з відповідними атрибутами та ролями.


[TIP]
Для адміністратора доступу в адміністративний портал реалізована можливість завантажити файл з даними користувачів реєстру, для автоматичного створення користувачів (посадових осіб) у KeyCloack та надання їм прав доступу.


[TIP]
Запроваджено шифрування CSV файлу при збереженні в Ceph, оскільки файли для імпорту користувачів містять персональні дані, необхідно гарантувати їх конфіденційність при збереженні в Ceph, для цього перед записом їх в сховище здійснюється їх шифрування.

'''
Розширення переліку підтримуваних компонент для моделювання UI-форм, компонентами FieldSet, Columns, Table

[NOTE]
Реалізовано підтримку компонента Table форми задачі, він доступний для моделювання в переліку "Компоненти" та відповідає стайл-гайдам додатка "Дія".


[NOTE]
Реалізовано підтримку компонента Columns форми задачі, він доступний для моделювання в переліку "Компоненти" та відповідає стайл-гайдам додатка "Дія".


[NOTE]
Реалізовано підтримку компонента FieldSet форми задачі, він доступний для моделювання в переліку "Компоненти" та відповідає стайл-гайдам додатка "Дія".

'''
Налаштування та контроль рейт-лімітів (обмеження кількості запитів від одного користувача)

[NOTE]
Розширено функціональність плагіну Kong OIDC, з метою обмеження кількості запитів від автентифікованого користувача, додана можливість встановлення ним кастомних заголовків, що містять дані користувача з JWT токена, наприклад, ідентифікатор користувача.


[TIP]
Реалізовано доробку, згідно якої при спробі отримати доступ до сторінок кабінетів посадової особи, громадянина та адміністратора перевищено ліміт по дозволеній кількості запитів до серверів, то робота зі сторінкою блокується та відбувається перехід на сторінку з описом помилки та підказкою щодо подальших дій.


[NOTE]
З метою обмеження кількості запитів до API встановлено Rate Limiting розширення для Kong API Gateway. Також для налаштування лімітів адміністратором безпеки, [TIP] механізм конфігурування Rate-limiting та OIDC розширень для Kong.

'''
Інформування через електронну пошту

[TIP]
Реалізовано доробку, згідно якої, якщо у бізнес-процесі змодельована задача відправки повідомлення зареєстрованому користувачу реєстру, користувач отримує отримує лист за шаблоном, налаштованим для каналу зв'язку "Електронна пошта", з відповідного SMTP-сервера.


[TIP]
Реалізована можливість для адміністраторів бізнес-процесів моделювати шаблон повідомлення для email повідомлень.


[TIP]
Реалізована можливість вибирати SMTP-сервер для відправки email повідомлень при створенні реєстру адміністратором платформи.


[WARNING]
Розроблено дизайн configmap для SMTP-сервера.


[TIP]
Розроблено процедуру автоматичного розгортання SMTP-сервера,  як компонента user-management, через Helmfile.


[TIP]
Розроблено шаблон для email повідомлень, який відповідає загальній стилізації кабінету користувачів Платформи та стайл-гайдів додатку "Дія".


[CAUTION]
Для надання доступу ddm-notification-service додано до user-settings-service-policy.


[CAUTION]
Виконано налаштування поштового домену, а саме налаштовано DNS entries у відповідній хостед зоні (Route53 у випадку AWS).

'''
Конфігурація SMTP-серверу через Control Plane

[WARNING]
Для адміністратора Платформи в адміністративному інтерфейсі управління платформою реалізована можливість налаштувати канал відправлення електронних повідомлень, обравши одну з опцій: платформенний поштовий сервер (platform-mail-server), зовнішній поштовий сервер (external-mail-server).


[WARNING]
Для адміністратора реєстру в адміністративному інтерфейсі управління платформою реалізована можливість змінити налаштування поштового SMTP-серверу реєстру.


[TIP]
Реалізована можливість налаштування SMTP-серверу через інтерфейс control-plane console при створенні реєстру.

'''
Аналіз ГІС рішення/модуля

[WARNING]
Проаналізовані рішення для модуля ГІС (геоінформаційної системи).

'''
Server-side сесії на Kong API Gateway.

[WARNING]
Розроблено дизайн використання Redis як сховище сесій Kong API Gateway.

'''
Повідомлення в Кабінеті громадянина (inbox)

[WARNING]
В кабінеті користувача послуг реалізована можливість отримувати повідомлення.


[WARNING]
Для адміністратора бізнес-процесів реалізована можливість моделювати шаблон повідомлення в inbox кабінету громадянина.


[WARNING]
В кабінеті користувача послуг реалізована можливість перегляду повідомлень.

'''
Email в профілі отримувача послуг

[WARNING]
В профілі кабінету користувача реалізовано обов'язкове підтвердження email при його внесенні або редагуванні в профілі кабінету. У разі успішного проходження перевірки, канал зв'язку з користувачем підтверджується і йому надається статус "перевіреного", що означає для системи можливість використання цього каналу для зв'язку.


[WARNING]
Реалізовано відображення кнопки "Вказати електронну адресу" на сторінці Профіля в блоці "Налаштування", у разі пустого значення поля email.


[WARNING]
Реалізовано відправку email листа з кодом підтвердження. При внесенні або редагуванні email, на вказану електронну адресу відправляється лист з 6-ти символьним кодом підтвердження, який користувач зазначає для перевірки електронної адреси.

'''
API пакетного завантаження сирих даних

[WARNING]
Розроблено дизайн реалізації пакетного завантаження даних з файлів (збереження файлу або читання даних, процес підпису даних, replay - можливість відтворення даних з Kafka).


[TIP]
Реалізовано API (процедури) транзакційного мікропакетного (micro-batch) перенесення сирих даних (Kafka/Ceph) до операційної БД PostgreSQL з розширенням Citus.


[CAUTION]
Завантажено масиви даних.

'''