= Примітки до релізу 1.8
:toc:
:toclevels:
:toc-title: ЗМІСТ
:sectnums:
:sectnumlevels: 
:sectanchors:
:experimental:
:important-caption: ВИПРАВЛЕНО
:note-caption: ПОКРАЩЕНО
:tip-caption: РОЗРОБЛЕНО
:warning-caption: ДИЗАЙН
:caution-caption: ІНШЕ

== Зміни у версії 1.8.1

=== Налаштування та контроль рейт-лімітів

[TIP]
Відображення сторінки з помилкою при перевищенні кількості запитів до сервера у кабінетах `admin-`/`citizen-`/`officer-portal`.
//https://jiraeu.epam.com/browse/MDTUDDM-12163

=== Пакетне завантаження посадових осіб реєстру

[TIP]
Шифрування CSV-файлу при збереженні в Ceph.
//https://jiraeu.epam.com/browse/MDTUDDM-12679

[IMPORTANT]
Файл із кириличним ім'ям не завантажується до CEPH-bucket.
//https://jiraeu.epam.com/browse/MDTUDDM-13265

=== Запити від СС та бізнесу

[TIP]
Можливість використовувати конектор до Єдиної інформаційної бази даних внутрішньо переміщених осіб у бізнес-процесах (конектор ЄІБДВПО).
//https://jiraeu.epam.com/browse/MDTUDDM-13295

=== Запити від СС та бізнесу 1.8

[TIP]
Формування унікального номера для створених у реєстрі сутностей (документів) за допомогою атрибута `ext:autoGenerate` у тегу `<column>`.
//https://jiraeu.epam.com/browse/MDTUDDM-16858

[TIP]
Можливість використовувати тип пошуку `notIn` (масив) для створення search conditions при моделюванні даних.
//https://jiraeu.epam.com/browse/MDTUDDM-12858

=== Розширення переліку підтримуваних компонентів для моделювання UI-форм

[NOTE]
Видалення функції `Redraw On` для стилізованих компонентів форм: `Radiobutton`, `Date/Time`, `File`, `CheckBox`.
//https://jiraeu.epam.com/browse/MDTUDDM-16432

[TIP]
Можливість для адміністратора регламенту обирати декілька значень параметра `Refresh option on` для оновлення значення в компоненті *Select*.
//https://jiraeu.epam.com/browse/MDTUDDM-13161


=== Управління схемами UI-форм реєстру

[WARNING]
Розробка дизайну Rest API для забезпечення роботи з формами.
//https://jiraeu.epam.com/browse/MDTUDDM-14230

=== Базові функції та навігація кабінету адміністратора, відображення назви майстер-версії

[WARNING]
Розробка дизайну Rest API для отримання інформації про відкритий запит.
//https://jiraeu.epam.com/browse/MDTUDDM-14227

[TIP]
Розробка Rest API endpoint для отримання переліку версій.
//https://jiraeu.epam.com/browse/MDTUDDM-14228

=== Створення нового запита на внесення змін до регламенту реєстру

[WARNING]
Розробка дизайн Rest API для створення нової версії-кандидата.
//https://jiraeu.epam.com/browse/MDTUDDM-14225

[TIP]
Імплементація Rest API endpoint для створення нової версії-кандидата.
//https://jiraeu.epam.com/browse/MDTUDDM-14226

=== Встановлення та конфігурація геосервера

[TIP]
Включення конфігурації геосервера до пайплайну розгортання регламенту реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-15494

[TIP]
Сервіс для конфігурації GeoServer через REST API.
//https://jiraeu.epam.com/browse/MDTUDDM-15493

//'''
//Додавання геотипів до фабрики даних ::
//TODO: Add RN for 1.8.2+

//'''
//Компонент Form.io для відображення геоданих ::
//TODO: Add RN for 1.8.2+

=== Розробка Control Plane для керування тенантами/реєстрами

[TIP]
Можливість задавати адміністраторів платформи через адмін-консоль.
//https://jiraeu.epam.com/browse/MDTUDDM-13043

[TIP]
Перегляд змін до реєстру адміністратором, що вносяться через МР до control-plane-console.
//https://jiraeu.epam.com/browse/MDTUDDM-12723

[TIP]
В адмін-консолі, у вікні реєстру додано посилання до сервісів `citizen-portal` та `officer-portal`.
//https://jiraeu.epam.com/browse/MDTUDDM-14026


=== Автоматизація та процедури розгортання системи управління реєстрами (control plane)

[IMPORTANT]
Процес збірки реєстру `MASTER-Build` не виконується після додавання адміністратора реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-18622

[IMPORTANT]
Процес збірки реєстру `MASTER-Build` викликається після створення МР (статус NEW) на додавання нового адміністратора реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-18618

[IMPORTANT]
Адміністратор реєстру не може додати нового адміністратора реєстру, немає прав на submit МР до центрального Gerrit.
//https://jiraeu.epam.com/browse/MDTUDDM-18617

=== Тимчасове сховище проміжних даних виконання бізнес-процесів

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13225
Створено репозиторій `ddm-file-storage`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13281
Оновлено `registry-rest-api` для використання `ddm-form-storage`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13280
Оновлено `excerpt-api-service` для використання `ddm-form-storage`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13205
Оновлено `digital-document-service` для використання `ddm-file-storage`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13196
Проведено рефакторинг коду для інтеграції з Ceph у модулі `ddm-file-storage`.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13074
Змінено використання Ceph-сховища для делегатів підпису на Storage-сервіси.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13282
Підключено нові версії бібліотек `form-data-storage`, `message-payload-storage` та `file-storage` для bpms.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13062
Додано інтеграцію з Redis до `ddm-form-data-storage`.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13065
Додано імплементацію репозиторію із підтримкою redis.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13066
Реалізовано підтримку зберігання форм та повідомлень у JSON-форматі.

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-13062
Проведено рефакторинг інтеграції з Ceph.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13195
Додано інтеграцію з Redis до `ddm-message-payload-storage`.

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-13219
Проведено рефакторинг інтеграції з Ceph у модулі `ddm-message-payload`.

Створено репозиторій `ddm-message-payload` та переміщено до нього імплементацію використання Redis для тимчасового сховища для message-payload даних.
====

[IMPORTANT]
Excerpt-service-api неправильно отримує bucket name.
//https://jiraeu.epam.com/browse/MDTUDDM-13509

[IMPORTANT]
Не видаляються проміжні дані бізнес-процесу після його завершення.
//https://jiraeu.epam.com/browse/MDTUDDM-13424

=== Технічна якість платформи

[NOTE]
Повернення коду `500` (http status code) замість `200` при помилці отримання time stamp при спробі підпису системним ключем у сервісі по роботі з цифровим підписом.
//https://jiraeu.epam.com/browse/MDTUDDM-15340

=== Регресійне тестування

[IMPORTANT]
Завантаження шаблону витягів використовує лише файл _styles.css_. При завантаженні видаляються усі стилі й використовується _style.css_ без перевірки наявності такого файлу.
//https://jiraeu.epam.com/browse/MDTUDDM-14242

=== Розробка типових розширень моделювання бізнес-процесів

[CAUTION]
Підготовка синтетичної моделі бізнес-процесу для проведення тестування.
//https://jiraeu.epam.com/browse/MDTUDDM-13079

=== Penetration test

[IMPORTANT]
Cookie сеансу не має встановленого прапорця безпеки "Secure".
//https://jiraeu.epam.com/browse/MDTUDDM-8769

'''

== Зміни у версії 1.8.2

=== Активація запиту на внесення змін до регламенту реєстру адміністратором зі спадного меню

[TIP]
Реалізовано можливість обрати зі спадного списку необхідний запит на внесення змін до реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-14016

=== Базові функції та навігація кабінету адміністратора, відображення назви майстер-версії

[TIP]
Для майстер-версії показується перелік форм, і вони доступні лише для перегляду та завантаження.
//https://jiraeu.epam.com/browse/MDTUDDM-14135

[TIP]
Створено сторінку з відображенням форм майстер-версії.
//https://jiraeu.epam.com/browse/MDTUDDM-14289

[TIP]
====
Створено оновлене меню навігації, що розташовується у лівій частині сторінки. Передбачено наступну структуру секцій:

- Організаційна структура;
- Управління користувачами;
- Моделювання регламенту;
- UI форми;
- Шаблон звітів.
//https://jiraeu.epam.com/browse/MDTUDDM-14500
====

[TIP]
Реалізовано можливість перегляду налаштувань форм майстер-версії, без можливості внесення змін.
//https://jiraeu.epam.com/browse/MDTUDDM-16563

=== Внесення змін до складових запиту на внесення змін регламенту реєстру

[TIP]
Розроблено java-сервіси для роботи з конфігураційними файлами регламенту.
//https://jiraeu.epam.com/browse/MDTUDDM-14234
[TIP]
Забезпечено коректну роботу git/gerrit сервісів під час одночасного їх використання декількома користувачами.
//https://jiraeu.epam.com/browse/MDTUDDM-16227
[IMPORTANT]
Помилка при розгортанні нового реєстру, сервіс не може розпачати роботу без підключення до репозиторію.
//https://jiraeu.epam.com/browse/MDTUDDM-17502

=== Інтеграція Платформи Реєстрів iз зовнішніми системами

[NOTE]
Додано автоматичне розширення service entry в пайплайні публікації за всіма зовнішніми посиланнями, що вказані в реєстрі, щоб надати доступ до зовнішніх систем.
//https://jiraeu.epam.com/browse/MDTUDDM-13602

=== Пакетне завантаження посадових осіб реєстру

[NOTE]
Адаптовано функціональність імпорту посадових осіб через файл в оновленому Кабінеті адміністратора регламентів.
//https://jiraeu.epam.com/browse/MDTUDDM-14027

=== Перегляд метаданих відкритого запита на внесення змін до регламенту реєстру, можливості застосування та відізвання запита

[TIP]
Реалізовано відображення контексту обраного відкритого запиту на внесення змін та управління UI формами. При виборі відкритого запита у спадному списку, адміністратору показується сторінка зі списком змодельованих форм, на якій можливо відредагувати форму, копіювати, завантажити, видалити.
//https://jiraeu.epam.com/browse/MDTUDDM-14018

=== Регресійне тестування

[IMPORTANT]
При спробі увійти до Кабінету громадянина, користувач який не має роль "citizen" у KeyCloak, отримував помилка з пустою сторінкою. Після виправлення відображається сторінка з помилкою "403 Доступ заборонено".
//https://jiraeu.epam.com/browse/MDTUDDM-10980
[IMPORTANT]
Процес розгортання зависає на етапі excerpt-service-api, в логах виникає помилка та пода перебуває у статусі "Pending 1/2".
//https://jiraeu.epam.com/browse/MDTUDDM-13104
[IMPORTANT]
Некоректна робота, коли система дає можливість подальшого розгортання оточення, навіть якщо бізнес-процес не був доданий до оточення, системний WARN та помилку можливо відстежити тільки при падінні тестових етапів.
Після виправлення система не дає можливість подальшого розгортання оточення, якщо бізнес-процес не був доданий до оточення та пайплайн генерує помилку саме на цьому етапі.
//https://jiraeu.epam.com/browse/MDTUDDM-11885

=== Створення нового запита на внесення змін до регламенту реєстру

[TIP]
Реалізовано можливість створення нового запита на внесення змін до реєстру, натиснувши "+ Створити новий запит" з меню випадного списку версій.
//https://jiraeu.epam.com/browse/MDTUDDM-14017

=== Управління схемами UI-форм реєстру

[TIP]
Реалізовано можливість перегляду та редагування форм шляхом переходу міх вкладками. Коли адміністатор переходить в режим створення або редагування форми, то він бачить вкладки у наступному порядку: "загальна", "код", "конструктор", "перегляд", "запит", іконка трьох крапок "дії над формою".
//https://jiraeu.epam.com/browse/MDTUDDM-12734

=== Управління шаблонами звітів реєстру

[TIP]
Адаптовано функціональність перегляду доступних звітів з можливістю їх завантаження в оновленому Кабінеті адміністратора регламентів.
//https://jiraeu.epam.com/browse/MDTUDDM-14020

=== Додавання гео-типів до дата фабрики

[TIP]
Реалізовано можливість збереження об'єктів за типом лінія та полігон до дата фабрики.
//https://jiraeu.epam.com/browse/MDTUDDM-17383

=== Компонент Form.io для відображення геоданих

[TIP]
Реалізовано можливість повернення координат вибраного об'єкта на формі у бізнес-процесі.
//https://jiraeu.epam.com/browse/MDTUDDM-13445
[NOTE]
Для спрощення досвіду моделювальника змінено формат даних, які повертає компонент Form.io для відображення геоданих до вигляду який очікує дата фабрика.
//https://jiraeu.epam.com/browse/MDTUDDM-18313
[TIP]
====
Створено два режими роботи для компонента карти "Map":

- Select mode - дозволяє кліком на обʼєкт на карті вибрати його, повернути данні відповідного формату про обраний обʼєкт, приховує кнопки керування з можливістю внесення нових обʼєктів;
- Edit mode - відображає кнопки керування для внесення нових точок, можливо внести тільки один обʼєкт, при натисканні на існуючі обʼєкти інших слоїв відбувається відображення підказки але обʼєкт не стає вибраним,  вибраними можуть вважатись тільки обʼєкти які були створені на карті.
//https://jiraeu.epam.com/browse/MDTUDDM-18316
====

=== Тимчасове сховище проміжних даних виконання бізнес-процесів

[TIP]
Імплементовано новий делегат _systemDigitalSignature.json_. +
Замінено підпроцес System Digital Signature на окремий делегат для підпису системним ключем.

[NOTE]
====
Скасовано підтримку застарілих делегатів для бізнес-процесів:

* _putContentToCeph.json_
* _readContentFromCeph.json_
* _putFormDataToCeph.json_
* _readFormDataFromCeph.json_
====

== Зміни у версії 1.8.3

===  Мінімальний шаблон для vSphere
//https://jiraeu.epam.com/browse/MDTUDDM-19445

[NOTE]
====
Внесено зміни до мінімальної конфігурації (мінімального шаблону) для середовища vSphere. +
Кількість ресурсів змінено на `8 CPU` і `32 Gb RAM`.
====

=== Коригування конфігурації рівня деталізації для історичних подій бізнес-процесів
//https://jiraeu.epam.com/browse/MDTUDDM-18840

[NOTE]
====
* Внесено зміни до рівня фіксації історичних подій бізнес-процесів на рівні конфігурації `bpms`:
+
----
camunda.bpm.history-level: AUDIT
camunda.bpm.database-history-level: ACTIVITY
----

* Внесено зміни до рівня фіксації історичних подій бізнес-процесів на рівні конфігурації business-process-administration-portal:
+
----
camunda.bpm.history-level: AUDIT
camunda.bpm.database-history-level: ACTIVITY
----

* Для міграції наявних реєстрів оновлено скрипт `init` контейнера bpms.
====


=== Увімкнено доступність метрик для моніторингу для Java-застосунків
//https://jiraeu.epam.com/browse/MDTUDDM-18803

[NOTE]
====

На рівні Openshift-кластера, у `ConfigMaps` > _application.yaml_ налаштовано exposure метрик для моніторингу Prometheus для Java-застосунків:

[source,yaml]
----
management.endpoints.web.exposure.include: 'health, prometheus'
----
====

=== Можливість вказувати кастомні атрибути у файлі для імпорту користувачів

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18705

Адміністратор доступу може додати у CSV-файлі додаткові заголовки й, опційно, значення для них у рядках.

За наявності значення у додаткових полях, створюється відповідний атрибут з таким самим іменем у Keycloak для цього користувача
====

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18823

Додано обробку кастомних атрибутів у `user-publisher`.
====

=== Доступ трафіку до czo.gov.ua із сервісу КЕП-операцій

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18648

Відкрито трафік до зовнішнього сервісу `czo.gov.ua` із сервісу `digital-signature-ops`.
====

=== Оновлення версії ІІТ-бібліотеки для сервісу КЕП-операцій

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18641

Оновлено версію ІІТ-бібліотеки для сервісу `digital-signature-ops` до `1.3.236`.

Додано нову версію ІІТ-бібліотеки у nexus releases:

----
<dependency>
    <groupId>com.iit.certificateAuthority</groupId>
    <artifactId>eu-sign</artifactId>
    <version>1.3.236</version>
</dependency>
----
====

=== Налаштування Istio для сервісу КЕП-операцій

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18632
Сконфігуровано Istio для сервісу `digital-signature-ops`. +
Доступ до АЦСК при перевірці підпису не проходив при включеному Istio.
====


=== Сервіс digital-signature-ops зависає при інтеграції з Гряда-301

[IMPORTANT]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18594
Сервіс `digital-signature-ops` зависає при інтеграції з Гряда-301 при виконанні запитів hashSigh та develop.
====

=== Конфігурація Istio для розділення внутрішньої та зовнішньої адреси Keycloak

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18561

У випадку додавання короткого імені для Keycloak, кожний ресурс `RequestAuthentication` повинен мати наступну конфігурацію:

* `issuer`: <коротке ім'я Keycloak>
* `jwksUri` -- за замовчуванням.

В інших випадках URL встановлюється за замовчуванням.
====

=== Конфігурація Redash для розділення внутрішньої та зовнішньої адреси Keycloak

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18560
Налаштовано сервіс Redash для розділення внутрішньої та зовнішньої адреси Keycloak.
====

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18981

Додано на UI елементи керування для додавання короткого DNS-імені для Redash.

Аналогічно до кабінетів користувачів, додано елементи керування на UI для збереження у файлі _values.yaml_ введених значень для коротких імен компонента Redash та Keycloak:

----
keycloak:
  customHost: short-example-dns-name.com
----
====

=== Оновлення Openshift-кластера до версії 4.11

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18536
Оновлено Openshift-кластер до версії 4.11.
====

=== Допрацювання взаємодії з id.gov.ua
//https://jiraeu.epam.com/browse/MDTUDDM-18531

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-18529
Полагоджено генерацію Keycloak логін-сторінок.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18546
Додано підтримку production-віджету підпису.

=== Управління шаблонами звітів реєстру
//Epic link: https://jiraeu.epam.com/browse/MDTUDDM-13331

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18165
Можливість здійснювати пошук звітів у переліку шаблонів звітів адміністратором регламенту. +
Це дозволяє швидко знайти потрібний шаблон звіту у Кабінеті адміністратора регламенту.

=== Управління схемами UI-форм реєстру
//https://jiraeu.epam.com/browse/MDTUDDM-13329

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18102?src=confmacro
Можливість здійснювати пошук адміністратором регламенту за назвою форми в переліку форм та бачити поточну сторінку у розділі _Моделювання регламенту_. +
Це дозволяє швидко знайти потрібну форму у Кабінеті адміністратора регламенту.

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-16648
Можливість переглядати параметри запита до бази даних на вкладці "Запит".

При моделюванні форми з комплексними компонентами виникає потреба бачити, які саме дані форма отримає із бази даних, який саме запит виходить із форми в рамках бізнес-процесу. +
Для більшої прозорості та пришвидшення процесу розробки регламенту додано секцію, яка показує SQL запити до бази даних від форми.
====

=== Інтеграція запита на внесення змін до майстер-версії регламенту реєстру
//Epic link: https://jiraeu.epam.com/browse/MDTUDDM-13349

[TIP]
Можливість інтегрувати запит на внесення змін до майстер-версії регламенту реєстру адміністратором. Це дозволяє бачити внесені зміни до майстер-версії в Кабінеті адміністратора регламенту.
//https://jiraeu.epam.com/browse/MDTUDDM-18090

[TIP]
Створено ендпоінт для submit версії.
//https://jiraeu.epam.com/browse/MDTUDDM-18096

[TIP]
Створено ендпоінт для відкликання версії кандидата.
//https://jiraeu.epam.com/browse/MDTUDDM-18389

[TIP]
Імплементовано обробку кнопки "Застосувати зміни до майстер-версії".
//https://jiraeu.epam.com/browse/MDTUDDM-18390

[TIP]
Імплементовано обробку кнопки "Відхилити".
//https://jiraeu.epam.com/browse/MDTUDDM-18391

[IMPORTANT]
У майстер-версії не відображаються форми, які були злиті до майстер-гілки із кандидат-версії.
//https://jiraeu.epam.com/browse/MDTUDDM-18708

=== Автоматичне оновлення та актуалізація стану відкритих запитів на внесення змін згідно з останньою майстер-версією регламенту реєстру
//https://jiraeu.epam.com/browse/MDTUDDM-13356

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17551
Можливість бачити актуальний стан відкритого запита на внесення змін згідно з останньою майстер-версією регламенту реєстру. +
Це забезпечує актуалізацію стану регламенту згідно з останніми внесеними змінами для послуги у процесі розробки.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18392
Розроблено scheduler для pull та fetch репозиторіїв на файловій системі.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18393
Імплементовано scheduler для видалення клонів для злитих та відкликаних версій кандидатів.

=== Створення нового запиту на внесення змін до регламенту реєстру

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-16228

Імплементовано маркування MR у Gerrit, які відповідають версіям-кандидатам. +
Реалізовано контракт з ідентифікації MR в Gerrit, які відповідають версіям-кандидатам в admin-portal.

Це дозволяє показувати лише MR, що мають відношення до admin-portal.

Це також дозволяє не допустити внесення змін у MR, що були створені розробниками реєстру через Gerrit.
====

=== Запити від СС та бізнесу 1.8
//https://jiraeu.epam.com/browse/MDTUDDM-13380

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-12853
Можливість використовувати тип пошуку `notEquals` для створення search conditions.
====

=== Впровадження безпеки

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-15265
[Security][Group] history-excerptor base image update (openjdk:11.0.7-jre-slim)

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-15223
[Security][Group] platform-gateway base image update (openjdk:11.0.13-jre-slim)

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-14727
[Security][Group] report-publisher base image update (openjdk:11.0.7-jre-slim)

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-14726
[Security][Group] user-publisher base image update (openjdk:11.0.7-jre-slim)

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-14587
[Security][Group] registry-regulation-management base image update (openjdk:11.0.13-jre-slim)

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-14586
[Security][Group] Base image update openjdk:11.0.13-jre-slim

[NOTE]
//https://jiraeu.epam.com/browse/MDTUDDM-14583
[Security][Group] Base image update openjdk:11.0.7-jre-slim

=== Інше

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-13217
Після видалення реєстрів через консоль Control Plane залишаються їх мапери в `KeycloakRealmIdentityProvider`.

== Зміни у версії 1.8.4

=== Підтримка та поточна діяльність
[NOTE]
Додано етап видалення publish-users-job при оновлені компонента user-publisher.
//https://jiraeu.epam.com/browse/MDTUDDM-19707

=== Регресійне тестування
[IMPORTANT]
Неможливо виконати rebase при push --force до master не використовуючи портал адміністратора.
//https://jiraeu.epam.com/browse/MDTUDDM-19760

[IMPORTANT]
При розгортанні Redash 10 версії на consent-data система не передає ролі з report-publisher до Redash.
//https://jiraeu.epam.com/browse/MDTUDDM-18586

[CAUTION]
Проведено регресійне тестування у сервісі Redash (admin&viewer) 10 версії.
//https://jiraeu.epam.com/browse/MDTUDDM-18576

[IMPORTANT]
Не екрануються спец символи при імпорті користувачів.
//https://jiraeu.epam.com/browse/MDTUDDM-19592

=== Оптимізація продуктивності E-Shelter
[NOTE]
Виконано конфігурацію процесу видалення історичних подій бізнес-процесів. Відключено службовий процес видалення історії бізнес-процесів на рівні конфігурації bpms (ddm-bpm/src/main/resources/application.yml). Налаштовано службовий процес видалення історії бізнес-процесів на рівні конфігурації business-process-administration-portal (src/main/resources/application.yml).
//https://jiraeu.epam.com/browse/MDTUDDM-18841

[IMPORTANT]
Створення авторизацій бізнес-процесу через camunda-auth-cli пайплайну публікації регламенту займає занадто багато часу та не встигає завершитись до Access Token expiration. Помилка "401 Jwt is expired".
//https://jiraeu.epam.com/browse/MDTUDDM-18804

[CAUTION]
Створено зразок реєстру, що оптимізований під 1000 користувачів.
//https://jiraeu.epam.com/browse/MDTUDDM-13624

[IMPORTANT]
Адміністратор реєстру не може редагувати дані про ключ. Помилка "secrets is forbidden: User "name@mail.com" cannot create resource "secrets" in API group "" in the namespace "control-plane" unable to create secret".
//https://jiraeu.epam.com/browse/MDTUDDM-13515"

=== Обмеження вибірки даних у звіті на основі переданої контекстної інформації з токену
[TIP]
Реалізовано можливість обмежувати вибірку даних у звіті на підставі переданої контекстної інформації з токена (наприклад код ЄДРПОУ).
//https://jiraeu.epam.com/browse/MDTUDDM-15993

=== Автоматичне оновлення та актуалізація стану відкритих запитів на внесення змін
[TIP]
Імплементовано автоматичне оновлення та актуалізація стану відкритих запитів на внесення змін згідно з останньою майстер-версією регламенту.
//https://jiraeu.epam.com/browse/MDTUDDM-17551

===  Базові функції та навігація кабінету адміністратора, відображення назви майстер-версії
[TIP]
Імплементовано автоматичне оновлення та актуалізація стану відкритих запитів на внесення змін згідно з останньою майстер-версією регламенту. Виконується порівняння майстер-версії з усіма версіями кандидатами реєстру. Усі версії кандидати актуалізуються згідно з останньою майстер-версією регламенту.
//https://jiraeu.epam.com/browse/MDTUDDM-17387

=== Загальні сторінки кабінету користувача
[TIP]
Реалізовано можливість підтримувати сесію користувача в Кабінеті посадової особи чи Кабінеті отримувача послуг, навіть якщо користувач не здійснює дій пов'язаних з надсиланням запитів (переходи на інші сторінки, натискання кнопок, сортування тощо). У разі, якщо користувач виконую рух мишкою або натискання клавіші клавіатури, через 5 хвилин на сервер відправляється запит для підтримки сесії кабінету.
//https://jiraeu.epam.com/browse/MDTUDDM-18694

[TIP]
Реалізовано автоматичне завершення сеансу роботи у Кабінеті посадової особи чи Кабінеті отримувача послуг у випадку тривалої відсутності активних дій в кабінеті. При спробі переходу з інтерфейсу на іншу сторінку чи виконати будь-яку дію відбувається перехід на стартову сторінку, на якій показується повідомлення про завершення сесії та порада увійти до кабінету знов.
//https://jiraeu.epam.com/browse/MDTUDDM-1240

=== Запити від СС та бізнесу 1.7
[NOTE]
В загальному інтеграційному конекторі додано можливість обирати метод запиту до фабрики даних зі спадного списку. Для вибору методу в делегаті Connect to data factory використовується параметр "method" з можливими значеннями: POST, GET, PUT, PATCH.
//https://jiraeu.epam.com/browse/MDTUDDM-18698

=== Ієрархічно-рольова модель користувачів (короб. рішення) з урахуванням кодів КАТОТТГ
[NOTE]
В "Журналі управління користувачами" в Redash додано параметр "КАТОТТГ", що відображається для реєстрів які використовують такий атрибут.
//https://jiraeu.epam.com/browse/MDTUDDM-18325

[TIP]
Створено нову роль "Адміністратор-кадровик" в officer-realm. Передбачається, що ця роль призначена для керування користувачами через бізнес-процеси (спеціальні бізнес-процеси для створення або зміни користувачів та їх ролей).
//https://jiraeu.epam.com/browse/MDTUDDM-18301

[NOTE]
Розширено можливість завантаження користувачів файлом до Keycloak додатковим атрибутом коду "KATOTTG".
//https://jiraeu.epam.com/browse/MDTUDDM-13946

[TIP]
Як адміністратор безпеки я хочу в Редаш в Журналі управління користувачами в одній колонці бачити внесені в csv-файл довільні кастомні атрибути.
//https://jiraeu.epam.com/browse/MDTUDDM-19267

[TIP]
Як посадова особа я хочу в БП створювати тільки заявки з атрибутом KATOTTG, який відповідає моєму атрибуту KATOTTG в Keycloak або знаходиться нижче по ієрархії цього атрибута.
//https://jiraeu.epam.com/browse/MDTUDDM-19152

[NOTE]
Додати валідацію на допустимі символи в кастомних атрибутах.
//https://jiraeu.epam.com/browse/MDTUDDM-18931

[TIP]
Конфігурація правил ієрархії на рівні регламенту (дата моделі)
//https://jiraeu.epam.com/browse/MDTUDDM-18658

[TIP]
Як посадова особа я хочу в БП переглядати/редагувати тільки заявки з атрибутом КАТОТТГ, який відповідає моєму атрибуту KATOTTG в Keycloak або знаходиться нижче по ієрархії цього атрибута.
//https://jiraeu.epam.com/browse/MDTUDDM-18088

[TIP]
Як адміністратор доступу-кадровик, я хочу розширювати/обмежувати доступ до даних реєстру користувачам (посадовим особам), використовуючи коди територіальної прив'язки КАТОТТГ
//https://jiraeu.epam.com/browse/MDTUDDM-13952

=== Компонент Form.io для відображення гео даних
[TIP]
Реалізовано можливість пошуку географічних об'єктів на карті (геокодування).
//https://jiraeu.epam.com/browse/MDTUDDM-13443

=== Конфігурація DNS-імен для реєстрів та захист адміністративних ендпоїнтів в control-plane
[CAUTION]
Розроблено інструкцію щодо обмеження доступу до адміністративних та реєстрових ендпоінтів у Control Plane.
//https://jiraeu.epam.com/browse/MDTUDDM-17977

[CAUTION]
Розроблено інструкцію з налаштування користувацьких DNS-імен для кабінетів посадової особи та отримувача послуг в інтерфейсі Control Plane.
//https://jiraeu.epam.com/browse/MDTUDDM-17976

[TIP]
В control-plane реалізовано інтерфейс для можливості налаштування унікальних DNS-імен для Кабінету отримувача послуг та Кабінету посадової особи.
//https://jiraeu.epam.com/browse/MDTUDDM-13158

=== Пакетне завантаження посадових осіб реєстру
[NOTE]
Внесено ряд змін (формулювання тексту) на сторінках порталу адміністратора, пов'язаних з автоматичним завантаженням користувачів через файл до Keycloak.
//https://jiraeu.epam.com/browse/MDTUDDM-16434

[TIP]
Додано авторизацію для сервісу registry-regulation-management  для операції імпорту користувачів (/batch-loads/users). Автоматизовано створення ролі user-management в -admin-realm.
//https://jiraeu.epam.com/browse/MDTUDDM-15475

=== Перегляд мета-даних відкритого запиту на внесення змін до регламенту реєстру, можливості застосування та відізвання запита
[TIP]
Реалізовано відображення метаданих відкритого запиту на внесення змін до регламенту реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-17550

=== Перегляд переліку та статусів сутностей-складових запиту на внесення змін регламенту реєстру

[TIP]
Реалізовано показ переліку та статусів складових запиту на внесення змін до регламенту реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-17388

=== Пов'язані selects для звітів Redash
[IMPORTANT]
Довге очікування даних з помилкою "500" у другому select для зв'язаних selects у Redash-admin.
//https://jiraeu.epam.com/browse/MDTUDDM-19926

[IMPORTANT]
Користувачі, ролі яких було надано тегами grant або grant-all, не бачать аналітичних таблиць та представлень на UI у Redash 10.
//https://jiraeu.epam.com/browse/MDTUDDM-18558

[TIP]
Налаштовано локалізацію після міграції до Redash 10.
//https://jiraeu.epam.com/browse/MDTUDDM-18557

[TIP]
Виконано налаштування SSO через SAML відповідно до змін e Redash 10.
//https://jiraeu.epam.com/browse/MDTUDDM-14247

[TIP]
Розгорнуто Redash з початковою конфігурацією.
//https://jiraeu.epam.com/browse/MDTUDDM-13807

[TIP]
Реалізовано можливість робити зв'язані selects в фільтрації (Parameters) при моделюванні дашборду для адміністратора сервісу звітності.
//https://jiraeu.epam.com/browse/MDTUDDM-12980

=== Розробка Control Plane для адміністрування тенантами/реєстрами
[TIP]
В адміністративній консолі Control Plane у меню "Керування платформою" додано можливість редагувати дані про ключ в User Management, що зберігаються у секретах digital-signature-env-vars та digital-signature-data.
//https://jiraeu.epam.com/browse/MDTUDDM-13418

=== Розширення переліку підтримуваних компонент для моделювання UI-форм
[TIP]
Реалізовано можливість фільтрувати дані, що були отримані через search condition у стилізованому компоненті форми "Select".
//https://jiraeu.epam.com/browse/MDTUDDM-13163

=== Управління налаштуваннями каналів зв'язку користувача у профілі кабінету громадянина
[NOTE]
Виконано модифікацію фізичної моделі, створено таблицю NOTIFICATION_CHANNEL.
//https://jiraeu.epam.com/browse/MDTUDDM-18589

[TIP]
У Кабінеті отримувача послуг реалізовано можливість змінювати адресу електронної пошти та активувати канал повідомлень в профілі користувача.
//https://jiraeu.epam.com/browse/MDTUDDM-18446

[TIP]
У Кабінеті отримувача послуг реалізовано можливість деактивувати канал зв'язку "Електронна адреса" з внесеною адресою електронної пошти у профілі користувача.
//https://jiraeu.epam.com/browse/MDTUDDM-18444

[TIP]
Реалізовано клієнтську та серверну валідацію даних електронної адреси після її внесення або редагування користувачем.
//https://jiraeu.epam.com/browse/MDTUDDM-18426

[TIP]
У Кабінеті отримувача послуг реалізовано можливість деактивувати канал зв'язку "Дія" у профілі користувача.
//https://jiraeu.epam.com/browse/MDTUDDM-18424

[TIP]
У Кабінеті отримувача послуг реалізовано можливість активувати канал зв'язку "Електронна адреса" з внесеною адресою електронної пошти у профілі користувача.
//https://jiraeu.epam.com/browse/MDTUDDM-18423

[TIP]
У Кабінеті отримувача послуг реалізовано можливість вносити адресу електронної пошти з автоматичним активуванням цього каналу повідомлень в профілі користувача.
//https://jiraeu.epam.com/browse/MDTUDDM-18422

[TIP]
У Кабінеті отримувача послуг реалізовано можливість активувати канал зв'язку "Дія" у профілі користувача.
//https://jiraeu.epam.com/browse/MDTUDDM-18421

[TIP]
Реалізовано можливість для адміністратора регламенту заборонити користувачу Кабінету отримувача послуг вносити електронну адресу через бізнес-процес onboarding.
//https://jiraeu.epam.com/browse/MDTUDDM-17161

[TIP]
Реалізовано можливість отримувати налаштування користувача Кабінету отримувача послуг за його ідентифікатором. У каталозі моделювальника бізнес-процесів додано оновлені типові розширення "Read User Settings" та "Create or Update User Settings".
//https://jiraeu.epam.com/browse/MDTUDDM-9316

[TIP]
У Кабінеті отримувача послуг реалізовано можливість переглядати поточні налаштування каналів зв'язку у профілі користувача.
//https://jiraeu.epam.com/browse/MDTUDDM-681

===  Управління схемами UI-форм реєстру
[IMPORTANT]
Некоректне видалення форми в Кабінеті адміністратора регламентів. Після створення нової форми з такою ж назвою виникає помилка "Неунікальна службова назва форми".
//https://jiraeu.epam.com/browse/MDTUDDM-18731

[IMPORTANT]
Після видалення форми зі сторінки редагування форм користувача перенаправляє не на поточну версію змін.
//https://jiraeu.epam.com/browse/MDTUDDM-18436

[TIP]
При моделюванні форм бізнес-процесів, які мають інтеграцію з критеріями пошуку на фабриці даних, ендпоінти фабрики даних стали доступними, та можуть бути показані на цій формі. Перевірка інтеграції компонента select з search condition фабрики даних в Кабінеті адміністратора регламентів при моделюванні форм дає можливість швидко оцінити коректність критеріїв пошуку не розгортаючи зміни на оточені.
//https://jiraeu.epam.com/browse/MDTUDDM-12693

=== Зберігання схем UI-форм та валідація даних користувачів

[NOTE]
Видалено валідацію поля path для форм.
//https://jiraeu.epam.com/browse/MDTUDDM-18934

[NOTE]
Замінено виклики /form-management-provider на /api/forms.
//https://jiraeu.epam.com/browse/MDTUDDM-18701

[CAUTION]
Перенесено "digital-documents-service" до "ddm-form-validation-client" для перевірки файлів
//https://jiraeu.epam.com/browse/MDTUDDM-16620

[CAUTION]
Перенесено "user-process-management" до "ddm-form-validation-client" для перевірки форм.
//https://jiraeu.epam.com/browse/MDTUDDM-16619

[CAUTION]
Перенесено "user-task-management" до "ddm-form-validation-client" для перевірки форм
//https://jiraeu.epam.com/browse/MDTUDDM-16618

[CAUTION]
Імплементовано бібліотеку "ddm-form-validation-client" до "form-submission-validation".
//https://jiraeu.epam.com/browse/MDTUDDM-16617

[CAUTION]
Перенесено "ddm-form-provider-client" до "form-schema-provider".
//https://jiraeu.epam.com/browse/MDTUDDM-16616

[CAUTION]
Імплементовано "form-schema-provider" Java service Public & Internal API + cross-cutting concerns. Усі ендпоінти мають ті самі контракти, що й у "form-management-provider".
//https://jiraeu.epam.com/browse/MDTUDDM-16615

[CAUTION]
Імплементовано "form-submission-validation" NodeJS внутрішні сервіси API використовуючи бібліотеку formio.js.
//https://jiraeu.epam.com/browse/MDTUDDM-16614

=== Інші впровадження
[TIP]
Розроблено дашборд, на якому візуалізовано скільки місця займає той чи інший Bucket.
//https://jiraeu.epam.com/browse/MDTUDDM-19493

[TIP]
Створено скрипт для міграції форм.  Скрипт завантажує форми з node application, використовуючи REST API.
//https://jiraeu.epam.com/browse/MDTUDDM-19439

[IMPORTANT]
При додаванні DNS-імені, не проходить оновлення реєстру з конфігурацією DNS, MASTER-Build pipeline завершується з помилкою в helm install.
//https://jiraeu.epam.com/browse/MDTUDDM-18974

[IMPORTANT]
При додаванні додаткового DNS-імені, DNS-ім'я застосовується до іншого порталу.
//https://jiraeu.epam.com/browse/MDTUDDM-14635

[IMPORTANT]
При додаванні додаткового DNS-імені, values.yaml - не валідний.
//https://jiraeu.epam.com/browse/MDTUDDM-14634

[IMPORTANT]
Відсутня валідація SSL-сертифікату при додаванні додаткового DNS-імені.
//https://jiraeu.epam.com/browse/MDTUDDM-14633

[IMPORTANT]
Таблиці додані при оновлені регламенту не реплікуються. Данні з таблиць, які створені в першій версії є на репліці, данні таблиці доданої в другій версії відсутні на репліці.
//https://jiraeu.epam.com/browse/MDTUDDM-13258

[IMPORTANT]
Отримання nullPointerException якщо файл має статус renamed.
//https://jiraeu.epam.com/browse/MDTUDDM-20297









////
=== Інше
TODO: RN 1.8.4

[IMPORTANT]
====
При додаванні DNS імені не проходить оновлення реєстру з конфігурацією DNS. +

Після підтвердження Merge Request, збірка MASTER-Build не проходить і завершується помилкою в helm install.
//https://jiraeu.epam.com/browse/MDTUDDM-18974
====

[IMPORTANT]
При додаванні додаткового DNS імені, воно застосовується до іншого порталу.
//https://jiraeu.epam.com/browse/MDTUDDM-14635

[IMPORTANT]
При додаванні додаткового DNS імені, _values.yaml_ -- не валідний.
////