:toc:
:toclevels:
:toc-title: ЗМІСТ
:sectnums:
:sectnumlevels:
:sectanchors:
:experimental:
:important-caption: ВИПРАВЛЕНО
:note-caption: ПОКРАЩЕНО
:tip-caption: РОЗРОБЛЕНО
:warning-caption: ДИЗАЙН
:caution-caption: ІНШЕ

= Примітки до релізу 1.9

== Зміни у версії 1.9.0
//https://jiraeu.epam.com/browse/MDTUDDM-21092

=== Підтвердження каналу зв'язку "Дія" (OTP)
//https://jiraeu.epam.com/browse/MDTUDDM-19205

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19206
Реалізовано готовий шаблон push-повідомлення з кодом для підтвердження каналу зв'язку "Дія". Шаблон стає доступний при розгортанні нового реєстру у структурі регламенту.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19210
Можливість отримувати push-повідомлення з OTP-кодом у застосунок "Дія".

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19212
Можливість вносити OTP-код і підтверджувати активацію каналу зв'язку "Дія" у профілі Кабінету отримувача послуг.

=== Повідомлення у застосунку "Дія"
//https://jiraeu.epam.com/browse/MDTUDDM-11460

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18303
Імплементовано можливість моделювати шаблон повідомлення для застосунку "Дія" адміністратором регламенту.

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-19473
Для завантаження сформованих або відкорегованих адміністратором шаблонів повідомлень розширено пайплайн публікації регламенту етапом `publish-notification-templates` з викликом утиліти `notification-template-publisher`.

Моделювальник бізнес-процесів може використовувати унікальну назву опублікованого шаблону push-повідомлення для застосунку "Дія" (Notification message template) при моделюванні бізнес-процесу з кроком відправки повідомлення користувачу.
====

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19201
Можливість отримувати повідомлення у застосунку "Дія" отримувачем послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19522
Можливість логувати у журналі аудиту відправлення push-повідомлень у застосунок "Дія" користувачам.

=== Повідомлення у Кабінеті отримувача послуг (inbox) у текстовому форматі
//https://jiraeu.epam.com/browse/MDTUDDM-12411

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-16634
Для завантаження сформованих або відкорегованих адміністратором шаблонів повідомлень розширено пайплайн публікації регламенту етапом `publish-notification-templates` з викликом утиліти `notification-template-publisher`.

Моделювальник бізнес-процесів може використовувати унікальну назву опублікованого шаблону in-app повідомлення (Notification message template) при моделюванні бізнес-процесу з кроком відправки.
====

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12532
Реалізовано готовий шаблон inbox-повідомлення для Кабінету отримувача послуг. Шаблон стає доступний при розгортанні нового реєстру у структурі регламенту.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12531
Можливість отримувати in-app повідомлення в Кабінеті отримувача послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12535
Можливість переглядати вхідні повідомлення у Кабінеті отримувача послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-16646
Можливість бачити прочитані та непрочитані повідомлення в Кабінеті отримувача послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-16647
Можливість застосовувати пагінацію на сторінці вхідних повідомлень в Кабінеті отримувача послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19523
Можливість логувати у журналі аудиту відправлення in-app повідомлень у Кабінеті отримувача послуг.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21209
Не валідується токен на час дійсності.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21210
Невірний код відповіді при модифікації повідомлення клієнтом яке йому не належить.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21380
Не валідується "Заголовок повідомлення" на обов'язковість.

=== Підтвердження каналу зв'язку email в Кабінеті отримувача послуг (лише email OTP)

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17316
Реалізовано готовий шаблон повідомлення з кодом для підтвердження адреси електронної пошти. Шаблон стає доступний при розгортанні нового реєстру у структурі регламенту.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12526
Можливість вносити Email у профілі Кабінету отримувача послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17561
Можливість змінювати адресу електронної пошти у профілі Кабінету отримувача послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12525
Можливість внести код OTP і підтвердити дані вказаної електронної адреси у профілі Кабінету отримувача послуг.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12731
Можливість отримувати повідомлення з кодом на вказаний Email для підтвердження вказаної електронної адреси.

=== Автоматичне розподілення задач на виконавців

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17488
Розширено делегат *Get users by attributes from keycloak* пошуком користувачів за КАТОТТГ.

=== Механізм роботи з масивом даних (в рамках бізнес-процесів)

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17916
Можливість для посадових осіб та отримувачів послуг зберігати дані з бізнес-процесів, внесені на формі за допомогою компонента *Edit Grid*, масивом до фабрики даних.

[IMPORTANT]
Помилка `Internal Server Error` виникає для звіту "Кадрове забезпечення лабораторії".

=== Первинне завантаження та дозавантаження даних (завантаження CSV файлів в БП)

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19743
Можливість на формі у компоненті *File* налаштовувати попередню перевірку CSV-файлу.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-16561
Можливість для посадових осіб та отримувачів послуг в рамках БП завантажувати/дозавантажувати файл з даними для збереження їх до бази даних.

=== Вказання назви секрету, без вказання токена авторизації, при налаштуванні інтеграції з ЄДР

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-19882
Можливість у файлі _configuration.yml`_ при налаштуванні інтеграції з ЄДР, вказувати назву секрету, без вказання токена авторизації.

=== Розширення функціональних можливостей виконанням задач бізнес-процесів підтримкою проміжного збереження даних в Кабінетах посадової особи та отримувача послуг

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-4039
Можливість проміжного збереження при внесенні даних через форми задач (для отримувача послуг).

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18876
Можливість повернутись до виконання ініційованого раніше бізнес-процесу, в якому було збережено внесені дані на формі задач (для отримувача послуг).

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-1151
Можливість проміжного збереження при внесенні даних через форми задач (для посадової особи).

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18877
Можливість повернутись до виконання ініційованого раніше бізнес-процесу, в якому було збережено внесені дані на формі задач (для посадової особи).

=== Розширення переліку та вдосконалення підтримуваних компонент для моделювання UI-форм

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13039
Можливість налаштовувати тип сортування для стовпців у компонентах, що використовуються для компонента *EditGrid*. Сортування виконується як для строкових даних, так і для числових.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13162
Можливість обмежувати введення пробілів на початку та в кінці у компоненті *Textfield*.

=== Пакетне завантаження посадових осіб реєстру

//TODO: Not yet ready
//[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12744
//Можливість вивантажити CSV-файл, що використовувався для імпорту користувачів в Keycloak (для адміністратора доступу).

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-16868
Перегляд у технічних логах лише інформації, яка стосується завантаження користувачів (для адміністратора доступу).

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-13265
Файл з іменем кирилицею не завантажується до сховища.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-14419
Помилки про невідповідність розміру кодування та типу файлу перестають змінятися після другого виникнення.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-16434
Внести зміни на сторінках admin-portal, що пов'язані з автоматичним завантаженням користувачів до Keycloak.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-16564
Якщо user-publisher при запиті access token отримує код `401 UNAUTHORIZED`, він відмовляє з помилкою `StackOverflowError`.

=== Управління глобальними налаштуваннями реєстру

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17575
Можливість управляти глобальними налаштуваннями реєстру в рамках моделювання регламенту.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20637
Відсутність regexp та тексту помилки, якщо email входить до списку заборонених.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20638
Відсутність червоної зірочки на обов'язкових полях.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20639
Колір тексту не відповідає mockup.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20717
Некоректно відпрацьовує settings validation.

=== Перегляд переліку таблиць моделі даних реєстру та їх структур
//https://jiraeu.epam.com/browse/MDTUDDM-13321

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17568
Можливість переглядати список таблиць для Майстер-версії.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-18909
Можливість переглядати структуру таблиці у майстер-версії (вкладка "Колонки").

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20580
На сторінці перегляду таблиць ширина стовпців не визначена відповідно до mockup.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20581
Відсутня пагінація на сторінці перегляду таблиці у майстер-версії.

=== Перевірка та фіксація наявності конфліктів запита на внесення змін та майстер-версії регламенту реєстру

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-17562
Можливість бачити відображення в огляді версії-кандидата інформацію про конфліктні зміни.

[IMPORTANT]
====
Не додається форма при rebase у версію кандидата. При творенні двох запитів версії кандидата, якщо в одному запиті видалити, або додати форму, і злити її, то у другому запиті версії кандидата при rebase не з'являється ця форма.
====

=== Внесення змін до складових запита на внесення змін до регламенту

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13369
Можливість вносити зміни до складових запита на внесення змін до регламенту реєстру.

[IMPORTANT]
====
//https://jiraeu.epam.com/browse/MDTUDDM-17305
Користувач з будь-якого реалму Keycloak (`officer`/`citizen`/`admin`) може використовувати API registry-regulation-management.
====

[IMPORTANT]
====
//https://jiraeu.epam.com/browse/MDTUDDM-17502
При розгортанні нового реєстру сервіс не стартує.

В логах ми можемо побачити помилку. Помилка виникає, тому що при розгортанні спочатку створюються всі поди та тільки після цього, якщо вони встановилися успішно, створюється Gerrit-репозиторій, але сервіс не може запуститися без підключення до репозиторію.
====

=== Активація запита на внесення змін до регламенту реєстру адміністратором зі спадного меню

[TIP]
Реалізовано можливість активувати у спадному списку необхідний запит на внесення змін до реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-14016

=== Інтеграція запита на внесення змін до майстер-версії регламенту реєстру
//Epic link: https://jiraeu.epam.com/browse/MDTUDDM-13349

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19143
При створенні кандидат-версії, форми сортуються за колонкою, за якою були відсортовані у майстер-версії.

=== Базові функції та навігація кабінету адміністратора, відображення назви майстер-версії
//https://jiraeu.epam.com/browse/MDTUDDM-13370

[TIP]
//2 частини
//https://jiraeu.epam.com/browse/MDTUDDM-16860
//https://jiraeu.epam.com/browse/MDTUDDM-18891
Можливість бачити дату створення/редагування форм для майстер/кандидат версії.

[IMPORTANT]
====
//https://jiraeu.epam.com/browse/MDTUDDM-19035
Заборонити змінювати службову назву форми при редагуванні форми.

Зробити поле `Службова назва форми` -- `disabled` при редагуванні.
====

=== Управління бізнес-процесами реєстру
//https://jiraeu.epam.com/browse/MDTUDDM-13326

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19717
При пошуку БП/форм/звітів результат не відображається, якщо пошук виконувався з останньої сторінки таблиці.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19951
На сторінці "Створення бізнес-процесу" описи полів для введення не відповідають очікуваним відповідно до mockup.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-19777
При створенні бізнес-процесу відсутня вкладка с трьома крапками (`...`).

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20293
На сторінці редагування бізнес-процесу (вкладка "Конструктор") при натисканні на Меню (три крапки) список можливих дій відображається за панеллю налаштувань Camunda Modeler.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-20295
Під час клонування бізнес-процесу, на вкладці "Конструктор" виникає помилка.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21484
Шрифт відображення XML-представлення не відповідає очікуваному на вкладці "Код" під час створення бізнес-процесу.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-21486
Неможливо повністю видалити xml-представлення на вкладці "Код" під час створення бізнес-процесу.

=== Тимчасове сховище проміжних даних виконання бізнес-процесів
//https://jiraeu.epam.com/browse/MDTUDDM-13044

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-13424
Не видаляються проміжні дані бізнес-процесу після його завершення.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-13509
`Excerpt-service-api` неправильно отримує bucket name.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-14580
Перевірити спроби сервісу rest-api під'єднатися до Redis.

=== Конфігурація DNS-імен для реєстрів та захист адміністративних ендпоінтів у Control Plane
//https://jiraeu.epam.com/browse/MDTUDDM-12978

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13157
Можливість обмежувати доступ до адміністративних та реєстрових ендпоінтів.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-13158
Можливість задавати власне DNS-ім'я для кабінетів посадової особи та отримувача послуг.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-18653
Додати валідацію на введення короткого DNS.

[IMPORTANT]
//https://jiraeu.epam.com/browse/MDTUDDM-18654
Додати посилання на інструкції по налаштуванню зовнішньої конфігурації адміністратором.


=== Розробка Control Plane для адміністрування тенантів/реєстрів

[IMPORTANT]
Після відновлювання резервної копії  Control-plane неможливо увійти до Gerrit платформи.

[IMPORTANT]
Реєстри не розгортаються паралельно.

[IMPORTANT]
Не видаляються реєстри через адмін-консоль.

[IMPORTANT]
Переобрана роль `cp-registry-admin-{REGISRTY_ALIAS}`, що створюється під час розгортання реєстру, не набуває своєї дії.

[IMPORTANT]
Користувач з роллю `cp-registry-admin-{REGISRTY_ALIAS}` не має доступу до платформних Gerrit та Jenkins job свого реєстру.

[IMPORTANT]
Користувач з роллю `cp-registry-admin-{REGISRTY_ALIAS}` не має доступу до *Role Mappings* у реалмах свого реєстру.

[IMPORTANT]
Після видалення реєстру з адмін-консолі, залишається його група в OKD.

[IMPORTANT]
Не розгортається реєстр із шаблоном `template-registry-dev-recommended`.

[IMPORTANT]
Реєстри створюються з порожнім полем "Адміністратори".

[IMPORTANT]
Якщо видалити адміна при редагуванні реєстру, то відповідна роль `cp-registry-admin-namespace` не видаляється з *Assigned Roles*.

[IMPORTANT]
`Reg-Dev-Minimal` template: під час спроби запуску бізнес-процесу у Кабінеті посадової особи та отримувача послуг, виникає помилка `"Status Code: 500 Internal Server Error"`.

[IMPORTANT]
В Кабінеті посадової особи при підписі будь-якого бізнес-процесу, виникає помилка "Дані в тілі не відповідають підпису".

[IMPORTANT]
Після оновлення реєстру до вищої гілки під час спроби запуску бізнес-процесу у Кабінеті посадової особи та отримувача послуг, виникає помилка `"Status Code: 500 Internal Server Error"`.

[IMPORTANT]
Під час входу адміністратора реєстру до реєстрових Keycloak через Openshift SSO, виникає помилка.

[IMPORTANT]
Після видалення реєстру через Control Plane, іноді залишається його репозиторій у Gerrit.

[IMPORTANT]
Admin-portal повинен відкривати посилання до admin-portal, а замість цього веде до Camunda.

[IMPORTANT]
Custom-ресурс `GerritGroupMember` ламається після кожного перезапуску `cluster-mgmt` job.

[IMPORTANT]
Не правильне сортування реєстрів за часом у Control Plane.

[IMPORTANT]
У Select-запиті на оновлення реєстру немає нової, старшої гілки.

[IMPORTANT]
Конфліктують групи `cluster-admins` та `cp-registry-admin`, якщо вони встановлені в одного і того ж користувача.

[IMPORTANT]
Пайплайн `history-excerptor` не виконується, якщо Cleanup job запустити декілька разів.

[IMPORTANT]
Заборонити вводити назву реєстру довжиною понад 12 символів на цільових кластерах.

[IMPORTANT]
Після видалення (cleanup), гілки для `history-excerptor` не створюються.

[IMPORTANT]
Після перезапуску кластера не підіймаються поди (pods) в наявних реєстрах через помилку з Kafka.
[IMPORTANT]
Видаляється рядок `deploymentMode` у файлі _values.yaml_.

=== Інші впровадження

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-10889
Автоматичне горизонтальне масштабування нод обробки баз даних

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12954
Захист адміністративних ендпоінтів за допомогою Kong

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-12955
====
Server-side сесії на Kong.

Збереження токенів на стороні сервера.
====

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-20416
Можливість виконувати запит на злиття змін із Control Plane.

[TIP]
Оновлено компонент `velero` до версії `1.9.0`. Безпечний запуск pipeline з відновлення.

[IMPORTANT]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18530
Backport for RPZM in Denovo.

Сервіс `digital-signature-ops` зависає при інтеграції з `Гряда-301` під час виконання запитів `hashSigh` та `develop`.
//https://jiraeu.epam.com/browse/MDTUDDM-18594
====