= Примітки до релізу 1.7
:toc:
:toclevels: 5
:toc-title: ЗМІСТ
:sectnums:
:sectnumlevels: 
:sectanchors:
:experimental:
:important-caption: ВИПРАВЛЕНО
:note-caption: ПОКРАЩЕНО
:tip-caption: РОЗРОБЛЕНО
:warning-caption: ДИЗАЙН
:caution-caption: ІНШЕ

== Зміни у версії 1.7.0

'''

Автоматизація та процедури розгортання системи управління реєстрами (Control plane)
[IMPORTANT] 
Помилка оновлення репозиторію history-excerptor-chart на цільовому кластері.
[IMPORTANT] 
Помилка повторного розгортання Vault  під час оновлення кластера.
[IMPORTANT] 
Не працює пайплайн code-review для репозиторію реєстра у Control plane (відсутній code-review.groovy).
 
'''

Міжреєстрова взаємодія реєстрів на Платформі зі сторонньою інформаційною системою
[TIP] 
Для розробників регламенту реалізовано можливість викликати зовнішньою системою через REST API бізнес-процеси, які були розроблені на Платформі.
 
'''

Міжреєстрова взаємодія реєстрів, що розгорнуті на одному екземплярі Платформи
(API без ШБО "Трембіта")
[NOTE] 
Винесено створення external-system-api-kong-proxy до registry-configuration.
[IMPORTANT] 
Можливість обирати реєстр у "поганому" статусі підчас надання доступу до реєстру.
[IMPORTANT] 
Створюється дублікат запиту на доступ до реєстру або платформи.
[IMPORTANT] 
Змінюється тип системи для доступу зовнішня система під час запиту на видалення.
[IMPORTANT] 
Не оновлювати пароль зовнішнім системам, які були раніше створені під час надання доступу іншим системам
[IMPORTANT] 
Не створюється реєстр на Control plane.
[IMPORTANT] 
"Статус доступу" до реєстру або системи "Помилка".
[NOTE] 
Группування даних в таблиці "Запити на оновлення" в Control plain на сторінці "Реєстри".
[IMPORTANT] 
Неправильний статус коли доступ до реєстру заблоковано.
[IMPORTANT] 
Примітка для поля "Назва системи" не відповідає валідації поля.
[IMPORTANT] 
Не відображається пароль після натискання кнопки "Показати пароль".
[IMPORTANT] 
Некоректне сповіщення про дублікат ім'я системи до якої надається доступ.
[IMPORTANT] 
Внесено виправлення, завдяки якому запит до іншого реєстру з увімкненим Istio більше не блокується.
[TIP] 
Реалізована можливість створювати GerritMergeRequest з файлами для змін для користувачів EDP.
[IMPORTANT] 
Виправлено відображення tooltip у Control Plane на сторінках: "Інформація про реєстри", "Керування кластером".
[TIP] 
Адаптовано Control plane до розробки на CICD2.
[CAUTION] 
Розгорнута data-модель для тестового "Реєстру шкіл", для можливості здійснити перевірку функціональності на тестовому БП.
[CAUTION]
Розгорнута data-модель для тестового "Реєстру учнів" без даних, для можливості здійснити перевірку функціональності на тестовому БП.
[TIP] 
Додано передачу необхідних vault-параметрів до platform-gateway.
[TIP] 
Створено репозиторій для додатку, заведено сервіс під kong.
[CAUTION] 
Створено автоматизовані тести в репозиторії user-cabinets-ui-tests, data-integration-tests. Імплементація тестів для перевірки створення групи споріднених реєстрів дозволяє виконати перевірку правильно розгорнутої моделі даних і перевірку можливості запуску бізнес-процесів у новій групі реєстрів.
[CAUTION] 
Розроблено користувацьку документацію.
[CAUTION] 
Змодельовано та опрацьовано тестові бізнес-процеси з метою тестування реалізованої розробки.
[NOTE] 
Розширено тег exposeSearchCondition, додано обробку нових параметрів до тегу для комунікації реєстрів без ШБО "Трембіта".
[TIP] 
Згенеровано istio virtualservice для точок інтеграції, які були опубліковані.
[TIP] 
Для імплементації успішного виклику registry-rest-api іншого реєстру реалізовано фільтр в platform-gateway, який забирає параметри логіну з Vault, аутентифікується з ними в external-system realm цільового реєстру (отримує токен) і перенаправляє запит з цим токеном до цільового реєстру.
[NOTE] 
Розширено bp-gateway REST інтерфейсом.
[TIP] 
Інтегровано Platform Gateway з Vault. Реалізовано запит до центрального Vault, в якому додаток забирає параметри для логіну в keycloak, параметри для логіну зберігаються за конвенцією.
[TIP] 
Створено сервіс platform gateway для маршрутизації запитів, який на підставі вхідних параметрів перенаправляє запит в інший реєстр.
 
'''

Внесення змін до складових запиту на внесення змін регламенту реєстру
[WARNING] 
Створено прототип механізму інтеграції з Git та Gerrit для отримання стану HEAD/master-гілки репозиторію регламенту та управління MR-запитами на внесення змін, з метою виключення необхідності локального встановлення додаткового ПЗ та спрощення досвіду моделювання регламенту реєстру.

'''

Запити від СС та бізнесу 1.7
[NOTE] 
Реалізована можливість для моделювальників баз даних використовувати тип пошуку between для створення search conditions.
[NOTE] 
Заборонено прямі комміти до репозиторію регламенту реєстру.
[TIP] 
Розроблено загальний інтеграційний конектор для можливості задавання методів, параметрів та тіла запиту при інтеграції з фабрикою даних.

'''

Інтерфейс порівняння версій бізнес-процесів регламенту реєстру
[WARNING] 
Створено прототип екрана порівняння версій бізнес-процесів з використанням бібліотеки bpmn.io та її розширень. Реалізовано нове вкладення "Порівняння БП" на сторінці "Моделювання бізнес-процесів".
[WARNING] 
Створено прототип екрана порівняння версій та візуалізації змін UI-форми з використанням web-моделера на базі Form.IO.
 
'''

Інформування через електронну пошту
[IMPORTANT] 
Помилка при деплої реєстру немає автоматизіції конфігурування системного клієнта system-user.
[TIP] 
Налаштовано поштовий домен.
[NOTE] 
Для надання доступу ddm-notification-service додано до user-settings-service-policy.
[TIP] 
Розроблено шаблон повідомлення на email, який відповідає загальній стилізації кабінету користувачів Платформи та стайл-гайдів додатку "Дія".
[TIP] 
Розроблено автоматизацію розгортання SMTP-сервера,  як компонент user-management через Helmfile.
[WARNING] 
Розроблено дизайн configmap для SMTP-сервера.
[TIP] 
Реалізована можливість вибирати SMTP-сервер для відправки email повідомлень при створенні реєстру адміністратором платформи.
[TIP] 
Реалізована можливість для адміністраторів бізнес-процесів моделювати шаблон повідомлення на email.
[TIP] 
При моделюванні задачі відправки повідомлення  зареєстрованому користувачу реєстру в бізнес-процесі, користувач отримує отримує лист за шаблоном, налаштованим для каналу зв'язку "Електронна пошта" з відповідного SMTP-сервера.
 
'''

Конфігурація dns імен для реєстрів та захист адміністративних ендпоїнтів в control-plane
[WARNING] 
Розроблено дизайн налаштування кастомного DNS-імені для кабінетів реєстру. Функціональністю передбачена можливість задати кастомне DNS-ім'я для кабінету чиновника та громадянина через control-plane для відповідного реєстру.
[WARNING] 
Розроблено дизайн блокування адміністративних ендпоїнтів на рівні OpenShift Router.
 
'''

Перевірка цілісності запиту на внесення змін до регламенту реєстру
[WARNING] 
Створено прототип механізму використання "Robot Comments" через Gerrit API з метою публікації результатів виконання статичного аналізу, тестування та публікації регламенту.
[WARNING] 
Створено прототип механізму використання "Custom Labels" через Gerrit API з метою розширення переліку можливих етапів перевірок, через які проходить версія регламенту (Review Passed, Static Analysis Passed, Tests Passed, ін.).
[CAUTION] 
Досліджено можливості використання jGit для клонування репозиторію у пам'ять та виконання операцій отримання стану, внесення змін та публікації у Gerrit.
 
'''

Повідомлення в Кабінеті громадянина (inbox)
[WARNING] 
Реалізовано механізм перегляду повідомлень у Кабінеті громадянина.
 
'''

Регресійне тестування
[IMPORTANT] 
Некоректне розташування UI-елементів на сторінці білдера у admin-portal.
[IMPORTANT] 
Падіння Cleanup job через неіснуючу версію бібліотеки.
[IMPORTANT] 
Report publisher не опрацьовує помилки від Redash.
[IMPORTANT] 
Не відображається завантажувач під час відкриття та відалення форм у Admin portal.
[IMPORTANT] 
Помилка при створені таблиці де ім'я є зарезрвованим словом.
[IMPORTANT] 
Компоненти RadioButton та CheckBox на формах задач та у режимі попереднього перегляду в Admin portal мають невірне вирівнювання за лівим краєм.
[IMPORTANT] 
Помилка системи, не відображаються задачі або процеси при пагінації у більше ніж 100 записів.
[IMPORTANT] 
Випадний список відкритий на формі з компонентом EditGrid  має менший Z-index, ніж інші компоненти на формі.
[IMPORTANT] 
Компоненти RadioButton, CheckBox та Date/time у регламентних БП мають некоректне положення відносно інших компонентів на формі.
[IMPORTANT] 
Сервісна валідація не враховує різницю між часовими поясами КЕП-сервісу та оточення, де був виконаний цей підпис.
 
'''

Розробка Control Plane для адміністрування тенантами/реєстрами
[IMPORTANT] 
В select на оновлення реєстру немає нової старшої гілки.
[IMPORTANT] 
Після видалення реєстру через Control plane, не видляється його репозиторій в Gerrit.
[IMPORTANT] 
Під час логіну Адміністратора реєстра до реєстрових Keycloak через Openshift SSO виникає помилка.
 
'''

Розширення можливостей моделювання бізнес-процесів підтримкою альтернативних гілок
[CAUTION] 
Виконана заміна функції initiator() на submission() для отримання ключа доступу (access key).
[TIP] 
Компонент Button розширено можливістю змоделювати перехід на альтернативні гілки. Додано кастомну опцію Navigation, завдяки якій є можливість додати Action code.
[NOTE] 
Змінено транзієнтність даних ініціатора для бізнес-процесу. Це потрібно тому, що дані initiator() зберігаються тільки до виконання першої форми. Якщо ж перейти з форми назад – ці дані потрібні ще раз.
[TIP] 
Для користувача кабінету реалізована можливість повернутися до попередньої форми та виправити внесені дані, якщо в рамках бізнес-процесу є дві чи більше задач розподілених на нього в ряд, та коли процесс змодельований зі стартовою формою.
 
'''

Розширення можливостей моделювання БП підтримкою відправки повідомлень
[CAUTION] 
Змодельовано та опрацьовано тестовий бізнес-процес з відправкою повідомлень одному користувачу, з метою тестування реалізованої розробки.
[CAUTION] 
Змодельовано та опрацьовано тестовий бізнес-процес з відправкою повідомлень декільком користувачам, з метою тестування реалізованої розробки.
[TIP] 
Реалізовано логування відправки повідомлень користувачам (факт вдалої та невдалої відправки повідомлення) в журналі аудиту Redash.
[TIP] 
Реалізована можливість моделювання відправки повідомлень до каналів зв'язку з користувачем. У каталозі моделювальника бізнес-процесів додано типове розширення "Send User Notification".
 
'''

Розширення переліку підтримуваних компонент для моделювання UI-форм
[TIP] 
Реалізовано підтримку компонента "Table" форми задачі, він доступний для моделювання в переліку "Компоненти" та відповідає стайл-гайдам додатка "Дія".
[TIP] 
Реалізовано підтримку компонента "Columns" форми задачі, він доступний для моделювання в переліку "Компоненти" та відповідає стайл-гайдам додатка "Дія".
[TIP] 
Реалізовано підтримку компонента "FieldSet" форми задачі, він доступний для моделювання в переліку "Компоненти" та відповідає стайл-гайдам додатка "Дія".

'''

Cтилізація та кастомізація критичних компонент моделювання UI-форм згідно стайл-гайдів "Дії"
[IMPORTANT]
Некоректна клієнтська валідація на стилізованих компонентах під час першого розгортання елементів на формі БП.
[IMPORTANT]
Помилка даних з calculateValue, при відправленні на форму.
[IMPORTANT]
Повернуто CalculatedValue до Text Field/TextArea/Email/File компонента.
[IMPORTANT]
Некоректно працює валідація на обов'язковість заповнення для компонентів File та Number.
[IMPORTANT]
Некоректна генерація блакитної заливки поля елемента в ОС Windows при активній опції "autocomplete" = "on" у стилізованих компонентах Email, Number, Text Field.
[IMPORTANT]
Некоректна взаємодія елемента Checkbox з властивістю calculateValue.
[IMPORTANT]
Некоректне розташування компонента Radiobutton, якщо користувач встановив Options Label Position.
[IMPORTANT]
Видалено назви кастомних класів з json-файлів стилізованих компонентів.
[IMPORTANT]
Помилка під час ручного вводу некоректної дати, вона записувалась до компонента у режимі попередього перегляду.
[IMPORTANT]
Видалено чекбокс "Modal edit" з деяких компонентів в Admin portal.
[IMPORTANT]
Помилка відсутності та нелокалізоване попередження про однакові API names у всіх стилізованих компонентах.
[IMPORTANT]
Помилка Description тексту відображалася нижче повідомлення про помилку та з відступом у попередньому перегляді на формі у Admin portal.
[IMPORTANT]
Видалено функцію "Unique" з компонентiв TextFileld, Email та TextArea у Admin portal.

'''

Технічна якість Клієнтських додатків платформи
[NOTE] 
Створені необхідні CI/CD процеси в Jenkins для monorepo (common-web-app).
 
'''

Тимчасове сховище проміжних даних виконання бізнес-процесів
[CAUTION] 
Додано redis-клієнт до тестових бібліотек.
[WARNING] 
Розроблено дизайн використання Redis як тимчасове сховище даних, внесених через UI-форми задач бізнес-процесу.
 
'''

Управління бізнес-процесами реєстру
[WARNING] 
Розроблено прототип web-редактора коду для розробки BPMN моделей бізнес-процесів (формату XML) з підтримкою валідації та автодоповненням.
[CAUTION] 
Проведено дослідження можливостей кастомізації та стилізації web-моделера на базі бібліотеки bpmn.io (зміни кольорів, шрифтів, локалізація).
[WARNING] 
Створено прототип використання користувацьких розширень у web-моделері на базі бібліотеки bpmn.io у якості аналогів Element Templates в Camunda Modeler.
[WARNING] 
Створено прототип web-моделера на базі бібліотеки bpmn.io для створення бізнес-процесів. Реалізовано окрему сторінку "Моделювання бізнес-процесів", яка підтримує два режими перегляду та зміни бізнес-процесів "Код" або "Конструктор".
[CAUTION] 
Проведено дослідження та створено прототип web-редактора коду для розробки Groovy-скриптів у бізнес-процесах з підтримкою автоматичного доповнення синтаксичним аналізом та можливостями розширення. Аналіз утиліт VSCode та CodeMirror.
 
'''

Управління структурами таблиць моделі даних реєстру
[WARNING] 
Запрототиповано механізм перетворення моделі структури БД у вигляді Liquibase ChangeSet.
[WARNING] 
Розроблено прототип механізму створення файлу з описом структури БД відповідно до Liquibase changelog з метою візуального представленням поточного стану структури БД у вигляді ER-діаграми.
 
'''

Управління схемами UI-форм реєстру
[WARNING] 
Створено прототип web-редактора коду для розробки JSON UI-форм відповідно до схеми з підтримкою валідації та автодоповнення (утиліта CodeMirror).
 
'''

Формування витягів (наказів) у кабінеті чиновника у форматі DOCX та витягів-звітів у форматі CSV
[IMPORTANT] 
Невідповідність контрактів надсилання даних у БД та отримання цих даних у стилізованому компоненті EditGrid через відправлення даних із компонента Radio.
[IMPORTANT] 
Помилка відображення кнопки "Завантажити витяг" у меню "Надані послуги" в Кабінеті посадової особи після коректної генерації документа на сервері.
[TIP] 
Створено endpoint за типом Search condition для заповнення поля "ПІБ співробітника" з підтримкою READ ALL.
 
'''

Security Activities
[NOTE] 
Додано етапи безпеки до EDP-постачальників. Оновлено EDP-pipeline згідно з етапами безпеки.
[NOTE] 
Налаштовано SSO-автентифікацію для компонента безпеки DefectDojo.
 
'''

Single Logout
[IMPORTANT] 
Помилка "Internal Server Error" на BPMS,  якщо при зверненні до кешу не знайдено потрібної інформації.
 
'''


Technical debt
[NOTE]
Синхронізовано роботу гілок реєстру з темплейтом в компоненті cluster-mgmt (коли кількість гілок більше однієї, всі гілки після першої містять належні зміни).

'''

Technical improvements
[NOTE]
Оновлено сховище секретів Hashicorp Vault до версії 1.9.7.
[IMPORTANT]
Помилка мережевої політики, перевірено роботу deny all policy, та інших мережевих політик в окремому тестовому середовищі.

'''

Інші впровадження
[IMPORTANT] 
Реальний КЕП-віджет на задачах підписання в оточенні SIT при розгортанні з параметром CA_ISOLATION=true.
[IMPORTANT] 
Код для REST API компілюється із зайвим символом, якщо у search condition вказати ліміт більше 1000.
[NOTE] 
Додано до пайплайну cluster-<cluster name>-run-installer-validation-tests можливість запуску тестів на видалення реєстру.
[CAUTION] 
Виконано налаштування Kong OIDC-плагіна для кореневих шляхів усіх порталів.
[CAUTION] 
Переведення тестових оточень CICD2 на роботу з ПКМ "Гряда-301".
[IMPORTANT] 
Помилка "Internal Server Error" на BPMS,  якщо при зверненні до кешу не знайдено потрібної інформації.
 
'''

