= Примітки до релізу 1.8
:toc:
:toclevels:
:toc-title: ЗМІСТ
:sectnums:
:sectnumlevels: 
:sectanchors:
:experimental:
:important-caption: ВИПРАВЛЕНО
:note-caption: ПОКРАЩЕНО
:tip-caption: РОЗРОБЛЕНО
:warning-caption: ДИЗАЙН
:caution-caption: ІНШЕ

== Зміни у версії 1.8.1

=== Налаштування та контроль рейт-лімітів

[TIP]
Відображення сторінки з помилкою при перевищенні кількості запитів до сервера у кабінетах `admin-`/`citizen-`/`officer-portal`.
//https://jiraeu.epam.com/browse/MDTUDDM-12163

=== Пакетне завантаження посадових осіб реєстру

[TIP]
Шифрування CSV-файлу при збереженні в Ceph.
//https://jiraeu.epam.com/browse/MDTUDDM-12679

[IMPORTANT]
Файл із кириличним ім'ям не завантажується до CEPH-bucket.
//https://jiraeu.epam.com/browse/MDTUDDM-13265

=== Запити від СС та бізнесу

[TIP]
Можливість використовувати конектор до Єдиної інформаційної бази даних внутрішньо переміщених осіб у бізнес-процесах (конектор ЄІБДВПО).
//https://jiraeu.epam.com/browse/MDTUDDM-13295

=== Запити від СС та бізнесу 1.8

[TIP]
Формування унікального номера для створених у реєстрі сутностей (документів) за допомогою атрибута `ext:autoGenerate` у тегу `<column>`.
//https://jiraeu.epam.com/browse/MDTUDDM-16858

[TIP]
Можливість використовувати тип пошуку `notIn` (масив) для створення search conditions при моделюванні даних.
//https://jiraeu.epam.com/browse/MDTUDDM-12858

=== Розширення переліку підтримуваних компонентів для моделювання UI-форм

[NOTE]
Видалення функції `Redraw On` для стилізованих компонентів форм: `Radiobutton`, `Date/Time`, `File`, `CheckBox`.
//https://jiraeu.epam.com/browse/MDTUDDM-16432

[TIP]
Можливість для адміністратора регламенту обирати декілька значень параметра `Refresh option on` для оновлення значення в компоненті *Select*.
//https://jiraeu.epam.com/browse/MDTUDDM-13161


=== Управління схемами UI-форм реєстру

[WARNING]
Розробка дизайну Rest API для забезпечення роботи з формами.
//https://jiraeu.epam.com/browse/MDTUDDM-14230

=== Базові функції та навігація кабінету адміністратора, відображення назви майстер-версії

[WARNING]
Розробка дизайну Rest API для отримання інформації про відкритий запит.
//https://jiraeu.epam.com/browse/MDTUDDM-14227

[TIP]
Розробка Rest API endpoint для отримання переліку версій.
//https://jiraeu.epam.com/browse/MDTUDDM-14228

=== Створення нового запита на внесення змін до регламенту реєстру

[WARNING]
Розробка дизайн Rest API для створення нової версії-кандидата.
//https://jiraeu.epam.com/browse/MDTUDDM-14225

[TIP]
Імплементація Rest API endpoint для створення нової версії-кандидата.
//https://jiraeu.epam.com/browse/MDTUDDM-14226

=== Встановлення та конфігурація геосервера

[TIP]
Включення конфігурації геосервера до пайплайну розгортання регламенту реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-15494

[TIP]
Сервіс для конфігурації GeoServer через REST API.
//https://jiraeu.epam.com/browse/MDTUDDM-15493

//'''
//Додавання геотипів до фабрики даних ::
//TODO: Add RN for 1.8.2+

//'''
//Компонент Form.io для відображення геоданих ::
//TODO: Add RN for 1.8.2+

=== Розробка Control Plane для керування тенантами/реєстрами

[TIP]
Можливість задавати адміністраторів платформи через адмін-консоль.
//https://jiraeu.epam.com/browse/MDTUDDM-13043

[TIP]
Перегляд змін до реєстру адміністратором, що вносяться через МР до control-plane-console.
//https://jiraeu.epam.com/browse/MDTUDDM-12723

[TIP]
В адмін-консолі, у вікні реєстру додано посилання до сервісів `citizen-portal` та `officer-portal`.
//https://jiraeu.epam.com/browse/MDTUDDM-14026


=== Автоматизація та процедури розгортання системи управління реєстрами (control plane)

[IMPORTANT]
Процес збірки реєстру `MASTER-Build` не виконується після додавання адміністратора реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-18622

[IMPORTANT]
Процес збірки реєстру `MASTER-Build` викликається після створення МР (статус NEW) на додавання нового адміністратора реєстру.
//https://jiraeu.epam.com/browse/MDTUDDM-18618

[IMPORTANT]
Адміністратор реєстру не може додати нового адміністратора реєстру, немає прав на submit МР до центрального Gerrit.
//https://jiraeu.epam.com/browse/MDTUDDM-18617

=== Тимчасове сховище проміжних даних виконання бізнес-процесів

[IMPORTANT]
Excerpt-service-api неправильно отримує bucket name.
//https://jiraeu.epam.com/browse/MDTUDDM-13509

[IMPORTANT]
Не видаляються проміжні дані бізнес-процесу після його завершення.
//https://jiraeu.epam.com/browse/MDTUDDM-13424

=== Технічна якість платформи

[NOTE]
Повернення коду `500` (http status code) замість `200` при помилці отримання time stamp при спробі підпису системним ключем у сервісі по роботі з цифровим підписом.
//https://jiraeu.epam.com/browse/MDTUDDM-15340

=== Регресійне тестування

[IMPORTANT]
Завантаження шаблону витягів використовує лише файл _styles.css_. При завантаженні видаляються усі стилі й використовується _style.css_ без перевірки наявності такого файлу.
//https://jiraeu.epam.com/browse/MDTUDDM-14242

=== Розробка типових розширень моделювання бізнес-процесів

[CAUTION]
Підготовка синтетичної моделі бізнес-процесу для проведення тестування.
//https://jiraeu.epam.com/browse/MDTUDDM-13079

=== Penetration test

[IMPORTANT]
Cookie сеансу не має встановленого прапорця безпеки "Secure".
//https://jiraeu.epam.com/browse/MDTUDDM-8769

// == Зміни у версії 1.8.2

////
=== Інше
TODO: RN 1.8.4

[IMPORTANT]
====
При додаванні DNS імені не проходить оновлення реєстру з конфігурацією DNS. +

Після підтвердження Merge Request, збірка MASTER-Build не проходить і завершується помилкою в helm install.
//https://jiraeu.epam.com/browse/MDTUDDM-18974
====

[IMPORTANT]
При додаванні додаткового DNS імені, воно застосовується до іншого порталу.
//https://jiraeu.epam.com/browse/MDTUDDM-14635

[IMPORTANT]
При додаванні додаткового DNS імені, _values.yaml_ -- не валідний.
////