= Примітки до релізу 1.8
:toc:
:toclevels: 5
:toc-title: ЗМІСТ
:sectnums:
:sectnumlevels: 
:sectanchors:
:experimental:
:important-caption: ВИПРАВЛЕНО
:note-caption: ПОКРАЩЕНО
:tip-caption: РОЗРОБЛЕНО
:warning-caption: ДИЗАЙН
:caution-caption: ІНШЕ

== Зміни у версії 1.8.0

'''
Збереження масивів файлів, отриманих з БП, в дата фабриці
[TIP]
Реалізовано можливість відображення та збереження масиву файлів в реєстрі.

'''
Інтеграція Платформи Реєстрів із зовнішніми системами
[TIP]
Для моделювальника бізнес-процесів реалізована можливість інтеграції із зовнішніми сервісами за допомогою конектора REST.

'''
Пакетне завантаження посадових осіб реєстру
[TIP]
На сторінці завантаження файлів у Адміністратора платформи додано розділ з посиланнями на шаблон csv-файлу з даними про посадових осіб та на пояснення до його заповнення для створення користувачів у Keycloak.
[IMPORTANT]
Неможливо завантажити файл із назвою у кирилиці.
[TIP]
Створення користувачів у KeyCloack при імпорті через файл логується до журналу аудиту.
[TIP]
Для доступу процесу імпорту користувачів до API KeyCloak при створенні реєстру автоматично створюється клієнт з сервіс екаунтом в officer реалмі KeyCloak.
[TIP]
Шифрування CSV файлу при збереженні в Ceph.
[TIP]
Створено модуль (Kubernetes job) для створення користувачів через KeyCloak REST API.

'''
Встановлення та конфігурація геосервера
[CAUTION]
Сформовано інструкції для публікації необхідих структур БД.
[CAUTION]
Виконано ручну публікацію необхідих структур БД.
[TIP]
Реалізовано розгортання геосервера при інсталяції реєстру ПЗМ.

'''
Додавання гео типів до дата фабрики
[TIP]
Додано можливість збереження гео типів в БД через згенеровані сервіси.
[TIP]
Додано можливості створення таблиць з загальним типом geometry.

'''
Компонент Form.io для відображення гео даних
[TIP]
Додано новий компонент "мапа" для form.io
[TIP]
Реалізовані підказки з деталям об'єкта реєстра при їх виборі на карті.
[TIP]
Реалізовано можливість пошуку об'єктів реєстру на карті за ключем.
[TIP]
Додано можливость відобаржати слої з гео-сервера GeoJSON (компонент Form.io).
[TIP]
Виконано конфігурацію компонента мапи (додавання публічних tile server-ів).
