= Обмеження доступу до SOAP інтерфейсів з ШБО Трембіта

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

Як адміністратор реєстру, я хочу обмежувати доступ до SOAP API інтерфейсів, що використовуються ШБО Трембіта

== Загальний опис
Реєстрові компоненти _bp-webservice-gateway_ та _registry-soap-api_ не мають механізму аутентифікації та авторизації та
призначені для виклику тільки через ШБО Трембіта. Для безпечного використання SOAP API інтерфейсів, адміністратору
необхідно надати можливість дозволяти комунікацію тільки з обмеженого переліку IP-адрес.

=== Ролі користувачів
* Технічний адміністратор реєстру

== Функціональні сценарії
* Обмеження доступу до SOAP API реалізованих у двох сервісах _bp-webservice-gateway_ та _registry-soap-api_

== Загальні принципи та положення
* На інтерфейсі створення та редагування реєстру адмін-консолі є розділ "ШБО Трембіта"
* Присутня можливість вказати перелік IP-адрес ШБО Трембіта, з яких буде дозволений доступ до _bp-webservice-gateway_
та _registry-soap-api_
* Зі всіх інших IP-адрес доступ до роутів _bp-webservice-gateway_ та _registry-soap-api_ обмежений
* Дозволено введення тільки IP-адрес, а не підмереж (CIDR)
* Кількість IP-адрес обмежена 10
* Технічний адміністратор відповідальний за коректність налаштувань та що за внесеними адресами дійсно Трембіта

== Технічний дизайн рішення
.Верхньорівнева діаграма взаємодії на рівні підсистем
[plantuml, flow, svg]
image::architecture-workspace/platform-evolution/api-access-from-trembita/soap-api.svg[soap-api-restrictions]

Після внесення IP-адрес в інтерфейсі адмін-консолі, система додає їх в перелік _values.yaml_ в наступному вигляді:

[source,yaml]
----
trembita:
  ipList:
    - 8.8.8.8
    - 8.8.4.4
  registries:
    dracs-registry:
    .....
----

В результаті конфігурації компонентів підсистеми зовнішніх інтеграцій анотація

[source, yaml]
----
metadata:
  annotations:
    haproxy.router.openshift.io/ip_whitelist: 8.8.8.8/32 8.8.4.4/32
----

додається до OpenShift роутів компонентів _bp-webservice-gateway_ та _registry-soap-api_.

IMPORTANT: Анотація додається тільки до OpenShift роутів

.Верхньорівнева діаграма взаємодії на рівні розгортання конфігурації
[plantuml, flow, svg]
image::architecture-workspace/platform-evolution/api-access-from-trembita/soap-api-trembita.svg[soap-api-restrictions-2]

=== Орієнтовні макети дизайну адмін-консолі

=== Компоненти реєстру та їх призначення в рамках дизайну рішення
|===
|Компонент|Службова назва|Призначення / Суть змін
|API-шлюз для викликів БП зовнішніми системами|bp-webservice-gateway|Додання анотації
|API-шлюз для читання даних реєстру зовнішніми системами|registry-soap-api|Додання анотації
|Веб-інтерфейс управління Платформою та реєстрами|control-plane-console|Зміни в інтерфейсі користувача
|===

TIP: Registry-soap-api генерується в компоненті service-generation-utility

== План розробки
=== Технічні експертизи
* BE
* DevOps

=== План розробки
* Змінити інтерфейс користувача адмін-консолі відповідно до макетів
* Зберігати внесені IP-адреси в налаштуваннях _values.yaml_ реєстру
* Обробити внесені IP-адреси на рівні чартів компонентів

== Безпека