= Керування розкладом та часом зберігання резервних копій реєстру

== Загальний опис
В поточній версії Платформи реєстрів не передбачено процесу керування налаштуваннями підсистеми бекапування реєстрів.
Для впровадження такого функціоналу пропонується поліпшення інтерфейсу адмін-консолі, використовуючи яку адміністратор
реєстру може налаштовувати розклад та час зберігання резервних копій реєстру.

== Ролі користувачів
* Адміністратор реєстру

== Функциональні сценарії
* Введення розкладу резервного копіювання через адмін-консоль
* Налаштування часу зберігання резервних копій через адмін-консоль

== Загальні принципи та положення
* Введення розкладу резервного копіювання в unix-cron форматі задається адміністратором
* Налаштування часу зберігання резервних копій вказується в днях адміністратором та встановлюється в годинах для системи бекапування
* Налаштування розкладу резервного копіювання та часу зберігання резервних копій не є обовʼязковим при створенні реєстру
* При закінченні строку зберігання системи бекапування видаляє застарілі резервні копії
* Введений розклад повинен відповідати unix-cron формату та валідуватись адмін-консоллю
* Час зберігання резервних копій повинен бути більше або дорівнювати одиниці, бути цілим числом та не містити спеціальних символів
* Автоматичне створення резервних копій можна вимкнути або ввімнути за допомогою перемикача
* При введені розкладу резервного копіювання адмін-консоль повинна показати коли відбудуться наступні три запуски резервного копіювання
* При оновленні реєстру на нову версію, налаштування розкладу резервних копій та часу зберігання резервних копій повинно залишитись незмінним
* За замовчуванням налаштування автоматичних резервних копій вимкнено для нових реєстрів
* Система повина врахувати розклад та тривались збереження резервних копій та попередити повідомленням про те, що
наступний запуск створення резервної копії відбудеться пізніше, ніж завершиться дата зберігання останнього
* Адмін-консоль зчитує тайм-зону користувача з браузера.
* За замовчуванням тайм-зона `Europe/Kiev`

== Поточний технічний дизайн
В поточній версії платформи резервне копіювання реєстрів доступне тільки при ручному запуску відповідної джоби.
Налаштування часу зберігання резервних копій не передбачено.

== Технічний дизайн рішення
На даній діаграмі зображено залучені для реалізації вимог сервіси та взаємодію між ними.
Додатково зображено важливі особливості, які необхідно брати до уваги в рамках реалізації.

image::architecture-workspace/platform-evolution/backup-schedule/backup-schedule.svg[remote-file-transfer,700]

Розклад резервних копій та час зберігання резервних копій передаються в values.yaml
[source, yaml]
----
global:
  registryBackup:
    enabled: true
    timezone: Europe/Kiev
    schedule: "0 0 * * *"
    expiresInDays: 3
----
та в анотацію `registry-parameters/values` codebase ресурсу реєстру.
Оператор повинен зреагувати на зміну в codebase CR та тригернути job provisioner, який перестворить `Create-registry-backup`
джобу з новими параметрами. Приклад налаштування розкладу в Jenkins:
[source, bash]
----
TZ=Europe/Kiev
30 19 * * *
----

== Високорівневий план розробки
=== Технічні експертизи

* _BE / DevOps_

=== План розробки
* Розширення функционалу codebase оператора тригером jenkins job provisioner після оновлення codebase CR
* Розширення UI функціоналу адмін-консолі по введенню / збереженню налаштувань розкладу резервних копій та часу їх зберігання
* Розробка groovy-функцій в jenkins job provisioner по оновленню параметрів в `Create-registry-backup` job.

== Міграція даних при оновленні реєстру
* Під час оновлення реєстру на нову версію налаштування розкладу бекапів поточні налаштування повинні залишитись незмінними.
* Необхідно передбачити можливість вимкнення автоматичного бекапування реєстра.

== Глосарій та акроніми

[cols="3,6"]
|===
|Термін|Опис

|_СR_
|Custom Resource

|===
