:imagesdir: ..\..\..\images\

= Категоризація доступних послуг в кабінеті користувача

== Загальний опис
В кабінеті користувача доступні послуги відображаються єдиним списком. Таким списком незручно користуватись в реєстрах які мають велику кількість доступних послуг.

Для поліпшення досвіду користувача пропонується реалізувати можливість категоризації послуг за допомогою груп. 

== Актори та ролі користувачів
* Отримувачі послуг
* Посадові особи
* Розробник регламенту

== Загальні принципи та положення
* Група не є частиною ідентифікатора бізнес-процесу. Тобто не може бути двох бізнес-процесів з однаковим id в різних групах.
* Група не є обов'язковою. Бізнес-процеси не прив'язані до групи відображаються поза групою. При відсутності налаштувань груп вважається що жоден бізнес-процес не прив'язаний до групи.
* Групи в яких нема жодного бізнес-процесу доступного користувачу не відображаються в кабінеті користувача. В інтерфейсі адміністративного порталу відображаються всі групи.
* Реалізація інтернаціоналізації для назв груп поза межами цього документу.

== Функціональні сценарії
* Налаштування групування бізнес-процесів розробником регламенту через веб-інтерфейс адміністративного порталу.
* Валідація змін до налаштувань групування бізнес-процесів при публікації регламенту.
* Перегляд списку бізнес-процесів з розділенням на групи через веб-інтерфейс кабінету користувача.

== Дизайн управління налаштуваннями
image::architecture-workspace/platform-evolution/bp-groups/bp-groups-configuration.drawio.svg[registry-authenticator-settings,700]

Для збереження налаштувань групування створюється новий елемент регламенту реєстру - файл налаштувань _bp-grouping.yaml_, який зберігається у папці _bp-grouping_

Файл налаштувань має наступну структуру: 
|===
|Ім'я|Тип|Опис|Обов'язкове

|groups
|[]object
|Список груп
|Так

|groups[groupId]
|object
|ID групи
|Ні


|groups[groupId].name
|string
|Ім'я групи
|Так

|groups[groupId].processDefinitions
|[]string
|Бізнес процеси в групі
|Ні

|groups[groupId].processDefinitions[processDefinitionId]
|string
|processDefinitionId бізнес-процесу
|Так

|===

Адміністратор реєстру створює або редагує налаштування через веб-інтерфейс адміністративного порталу, або вручну міняє файл налаштувань. В результаті чого налаштування потрапляють в регламент реєстру.

При публікації регламенту реєстру, пайплайн публікації регламенту пропагує налаштування у сервіс управління бізнес-процесами користувача.

На основі налаштувань, сервіс управління бізнес-процесами користувача збагачує інформацію про послугу, у списку доступних послуг, назвою групи до якої належить послуга.

Користувач кабінету бачить послуги розділені на групи на сторінці доступних послуг.


=== Адміністративний портал

Сторінка _Моделі процесів_ веб-інтерфейсу адміністративного порталу має бути доповнена, відповідно з узгодженим макетом,  можливостями створювати, редагувати, видаляти групи та переглядати бізнес-процеси у групах, додавати їх у групу та видаляти із групи.

API сервісу надання конфігурації регламенту реєстру має бути доповнений методами які забезпечують функціональність веб-інтерфейсу.

* Створити групу
* Перейменувати групу
* Видалити групу
* Прив'язати бізнес-процес до групи
* Відв'язати бізнес-процес від групи

[IMPORTANT]
При видаленні групи видаляється тільки група. Бізнес-процеси, які були до неї прив'язані, відв'язуються.

Також у наявних методах повернення списку бізнес-процесів *GET /versions/master/business-processes* та *GET /versions/candidates/{versionCandidateId}/business-processes* розширити відповідь _BusinessProcessDetailsShort_ інформацією про groupId та [groupId].name до якої прив'язаний бізнес-процес. Якщо бізнес-процес не прив'язаний до групи ці елементи будуть пустими.

=== Кабінети користувача
Сторінка _Доступні послуги_ веб-інтерфейсу кабінетів користувача (officer та citizen portals) має бути доповнена, відповідно з узгодженим макетом,  можливістю переглядати бізнес-процеси у групах.

В API сервісу управління бізнес-процесами користувача, відповідь ендпоінту, що повертає список бізнес процесів - *GET /api/process-definition* має бути доповнена атрибутом _groupName_. Атрибут _groupName_ встановлюється відповідно до [groupId].name групи до якої прив'язаний бізнес-процес в  _bp-grouping.yaml_. Якщо бізнес-процес не прив'язаний до жодної групи то атрибут не встановлюється.

=== Компоненти системи та їх призначення в рамках дизайну рішення
У даному розділі наведено перелік компонент системи, які задіяні або потребують змін/створення в рамках реалізації функціональних вимог згідно з технічним дизайном рішення.

|===
|Компонент|Службова назва|Призначення / Суть змін

|Регламент реєстру
|registry-regulation
|Розширення регламенту налаштуванням _bp-grouping_

|Пайплайн публікації регламенту
|registry-jenkins
|Пропагування налаштувань _bp-grouping.yaml_ в сервіс user-process-management

|CLI-утиліта валідації цілісності регламенту
|registry-regulations-validator-cli
|Валідація bp-grouping.yaml

|Сервіс управління бізнес-процесами користувача
|user-process-management
|Збагачення списку бізнес-процесів інформацією про групи до якої вони належать

|Сервіс надання конфігурації регламенту реєстру
|registry-regulation-management
|Додавання методів для створення, редагування і видалення груп, а також методів для додавання бізнес-процесів у групи та видалення їх із груп

|Веб компоненти та портали
|common-web-app
|Додавання UI елементів для управління та перегляду груп

|===

== Моделювання регламенту реєстру
=== Структура регламенту налаштувань реєстру
В рамках задачі по розширенню налаштувань, необхідно розширити відповідну конфігурацію реєстру за замовчуванням у шаблоні репозиторію регламенту _empty_regulation_template_. За замовчанням налаштування групування _bp-grouping.yaml_ пусті.

.Структура регламенту реєстру
[plantuml, registry-settings-regulation-structure, svg]
----
@startsalt
{
{T
+ <&folder> registry-regulation
++ <&folder> <b>bp-grouping</b>
+++ <&file> <b>bp-grouping.yaml</b>
++ <&folder> bpmn
++ <&folder> dmn
++ ...
}
}
@endsalt
----

.Приклад конфігурації реєстру _bp-grouping/bp-grouping.yaml_
[source, yaml]
----
groups:
  - group1-id:
      name: Перша група
      processDefinitions:
        - bp-1-process_definition_id
        - bp-2-process_definition_id
  - group2-id:
      name: Друга група
      processDefinitions:
        - bp-3-process_definition_id
  - group3-id:
      name: Третя група
----

=== Валідація регламенту реєстру
В рамках реалізації рішення, необхідно розширити CLI-утиліту _registry-regulations-validator-cli_ валідації регламенту додатковими правилами:

* ID груп унікальні.
* Назви груп унікальні.
* Бізнес-процеси в масивах processDefinitions зустрічаються не більше одного разу. Тобто бізнес-процес не може бути прив'язаний до різних груп одночасно, чи більше чим один раз до однієї групи.
* Бізнес-процеси вказані в масивах processDefinitions існують в регламенті (папці bpmn).

=== Публікація змін до регламенту реєстру
Налаштування _bp-grouping.yaml_ монтується як ConfigMap до сервісу управління бізнес-процесами користувача (_user-process-management_). Пайплайн публікації регламенту повинен оновлювати вміст ConfigMap _bp-grouping.yaml_ відповідно до змісту регламенту реєстру що публікується. 

== Високорівневий план розробки
=== Технічні експертизи
* _BE_
* _FE_
* _DevOps_

=== План розробки
* Розширення конфігурацію реєстру за замовчуванням у шаблоні репозиторію регламенту.
* Розширення _Пайплайну Публікації Регламенту_ логікою пропагування налаштувань _bp-grouping.yaml_ в сервіс user-process-management.
* Створити _JSON_-схему валідації налаштувань групування  та валідацію згідно з правилами.
* Розширення API сервісу user-process-management.
* Розширення API сервісу registry-regulation-management.
* Розширення веб-інтерфейсу налаштування бізнес-процесів адміністративного порталу можливістю керувати групами.
* Розширення веб-інтерфейсу перегляду бізнес-процесів кабінету посадової особи можливістю перегляду бізнес-процесів у групах.
* Розробка інструкцій для розробника регламенту та референтних прикладів