= Розширення набору метрик для моніторингу _Підсистеми виконання бізнес-процесів_

== Загальний опис

...

== Ролі користувачів

* Технічний адміністратор реєстру
* Служба підтримки платформи (L2)

== Принципи та положення

* Для зменшення навантаження на сервіси операційної зони реєстру, метрики збираються через окремий екземпляр _Camunda_ (*business-process-administration-portal*) адміністративної зони
* Реєстрація змін метрик виконання бізнес-процесів є опційним та налаштовується на рівні конфігурації сервісу
* Інтервал збору метрик налаштовується на рівні службового процесу _Prometheus_

== Технічний дизайн рішення

image::architecture-workspace/platform-evolution/camunda-metrics/camunda-metrics.svg[camunda-metrics]

=== Компоненти та їх призначення

У даному розділі наведено перелік компонент системи, які задіяні або потребують змін/створення в рамках реалізації функціональних вимог згідно технічного дизайну рішення.

|===
|Компонент|Службова назва|Призначення

|_Веб-інтерфейс моніторингу Платформи_
|*grafana*
|Розробка та розгортання окремого дашборду для моніторингу метрик виконання бізнес-процесів

|_Сервіс збору та зберігання метрик моніторингу_
|*prometheus*
|Налаштування збирання додаткових метрик

|_Веб-інтерфейс управління виконанням бізнес-процесів_
|*business-process-administration-portal*
|Розробка збору та реєстрації додаткових метрик _Micrometer_ у разі відповідного налаштування на рівні сервісу
|===

=== Налаштування реєстрації змін метрик

.Налаштування експорту метрик у Prometheus-сумісному форматі через службовий роут `'/actuator/prometheus'` в `application.yml`
[source,yaml]
----
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    enable: # Disable built-in metrics
      all: false
----

.Налаштування реєстрації змін метрик виконання бізнес-процесів в `application.yml`
[source,yaml]
----
camunda:
  bpm:
    metrics:
      enabled: true # Налаштування для вмикання експорту метрик Camunda
----

=== Налаштування збору метрик

.Налаштування збирання метрик виконання бізнес-процесів в `prometheus.yml`
[source,yaml]
----
scrape_configs:
  - job_name: "camunda"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 60s # Інтервал збору метрик
    static_configs:
      - targets: ['HOST:PORT']
----

=== Реєстрація метрик для експорту

.Приклад реєстрації метрик
[source,java]
----
public class CamundaMetricsBinder implements MeterBinder {
    private ProcessEngine processEngine;

    @Override
    public void bindTo(MeterRegistry registry) {
        Gauge.builder("<metric.key.name>", processEngine.getHistoryService().createHistoricProcessInstanceQuery(), Query::count)
                .tag("<dimension.tag.one>", "<value>")
                .tag("<dimension.tag.two>", "<value>")
                .description("<metric description>")
                .register(registry);

        FunctionCounter.builder("<metric.key.name>", processEngine.getManagementService().createMetricsQuery().name(Metrics.ROOT_PROCESS_INSTANCE_START), MetricsQuery::sum)
                .tag("<dimension.tag.one>", "<value>")
                .tag("<dimension.tag.two>", "<value>")
                .description("<metric description>")
                .register(registry);
    }
}
----

== Метрики для моніторингу

[TIP]
--
Детальніше з типами метрик можна ознайомитись в офіційній документації https://micrometer.io/docs/concepts[Micrometer].
--

|===
|Категорія|Метрика|Тип|Опис

.3+|Загальні метрики _Process Engine_
|_camunda.user.count_
|`Gauge`
|

|_camunda.deployments_
|`Gauge`
|

|_camunda.active.process.definitions_
|`Gauge`
|

.5+|Загальні метрики бізнес-процесів
|_camunda.active.user.tasks_
|`Gauge`
|

|_camunda.completed.process.instances_
|`Gauge`
|

|_camunda.completed.process.instances_
|`Gauge`
|

|_camunda.active.process.instances_
|`Gauge`
|

|_camunda.process.instances.total_
|`Gauge`
|

.4+|Загальні метрики обміну повідомленнями в рамках бізнес-процесу
|_camunda.active.signal.event.subscriptions_
|`Gauge`
|

|_camunda.active.conditional.event.subscriptions_
|`Gauge`
|

|_camunda.active.compensate.event.subscriptions_
|`Gauge`
|

|_camunda.active.message.event.subscriptions_
|`Gauge`
|

.4+|Загальні метрики асинхронного виконання задач бізнес-процесу
|_camunda.message.jobs_
|`Gauge`
|

|_camunda.timer.jobs_
|`Gauge`
|

|_camunda.executable.timer.jobs_
|`Gauge`
|

|_camunda.executable.jobs_
|`Gauge`
|

.5+|Видалення історичних даних виконання бізнес-процесів
|_camunda.history.cleanup.removed.process.instances_
|`Gauge`
|

|_camunda.history.cleanup.removed.task.metrics_
|`Gauge`
|
|===