= Моніторинг загальних показників виконання бізнес-процесів

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Необхідно забезпечити можливості моніторингу загальних метрик виконання бізнес-процесів для спрощення діагностики та аналізу поведінки системи з ціллю своєчасного виконання корегуючих дій.

== Ролі користувачів

* Технічний адміністратор реєстру
* Служба підтримки платформи (L2)

== Принципи та положення

* Для зменшення навантаження на сервіси операційної зони реєстру, метрики мають збиратись через окремий екземпляр _Camunda_ (*business-process-administration-portal*) адміністративної зони
* Реєстрація змін метрик виконання бізнес-процесів є опційним та має налаштовуватись на рівні конфігурації сервісу (*business-process-administration-portal*)
* Інтервал збору метрик налаштовується на рівні службового процесу _Prometheus_
* Механізм автоматичних сповіщень не входить до скоупу цього документа

== Технічний дизайн рішення

image::architecture-workspace/platform-evolution/camunda-metrics/camunda-metrics.svg[camunda-metrics,400]

=== Компоненти та їх призначення

У даному розділі наведено перелік компонент системи, які задіяні або потребують змін/створення в рамках реалізації функціональних вимог згідно технічного дизайну рішення.

|===
|Компонент|Службова назва|Призначення

|_Веб-інтерфейс моніторингу Платформи_
|*grafana*
|Розробка та розгортання окремого дашборду для моніторингу метрик виконання бізнес-процесів

|_Сервіс збору та зберігання метрик моніторингу_
|*prometheus*
|Налаштування збирання додаткових метрик

|_Веб-інтерфейс управління виконанням бізнес-процесів_
|*business-process-administration-portal*
|Розробка збору та реєстрації додаткових метрик _Micrometer_ у разі відповідного налаштування на рівні сервісу
|===

=== Налаштування реєстрації змін метрик

.Налаштування експорту метрик у Prometheus-сумісному форматі через службовий роут `'/actuator/prometheus'` в `application.yml`
[source,yaml]
----
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    enable: # Disable built-in metrics
      all: false
----

.Налаштування реєстрації змін метрик виконання бізнес-процесів в `application.yml`
[source,yaml]
----
camunda:
  bpm:
    metrics:
      enabled: true # Налаштування для вмикання експорту метрик Camunda. Default: true
----

=== Налаштування збору метрик

.Налаштування збирання метрик виконання бізнес-процесів в `prometheus.yml`
[source,yaml]
----
scrape_configs:
  - job_name: "camunda"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 60s # Інтервал збору метрик
    static_configs:
      - targets: ['HOST:PORT']
----

=== Реєстрація метрик для експорту

[IMPORTANT]
--
* Необхідно визначити доцільність використання додаткових тегів для окремих метрик
* Необхідно розглянути альтернативну опцію гранулярного налаштування інтервалу для виконання запиту на отримання актуального значення метрики з ціллю зменшення сумарного навантаження за допомогою _Spring Task Scheduling_ та _@Scheduled(fixedRate = <?>)_.
--

.Приклад реєстрації метрик з оновленням за інтервалом, налаштованим на рівні _Prometheus_
[source,java]
----
class CamundaMetricsBinder implements MeterBinder {
    ProcessEngine processEngine;

    void bindTo(MeterRegistry registry) {
        Gauge.builder("<metric.key.name>", processEngine.getHistoryService().createHistoricProcessInstanceQuery(), Query::count)
                .tag("<dimension.tag.one>", "<value>")
                .tag("<dimension.tag.two>", "<value>")
                .description("<metric description>")
                .register(registry);

        FunctionCounter.builder("<metric.key.name>", processEngine.getManagementService().createMetricsQuery().name(Metrics.ROOT_PROCESS_INSTANCE_START), MetricsQuery::sum)
                .tag("<dimension.tag.one>", "<value>")
                .tag("<dimension.tag.two>", "<value>")
                .description("<metric description>")
                .register(registry);
    }
}
----

.Приклад реєстрації метрик з оновленням за інтервалом, налаштованим на рівні окремої метрики
[source,java]
----
class CamundaMetricsBinder implements MeterBinder {
    ProcessEngine processEngine;

    AtomicLong metricGaugeNumber;

    void bindTo(MeterRegistry registry) {
        this.metricGaugeNumber = registry.gauge("<metric.key.name>", new AtomicLong(0));
    }

    @Scheduled(fixedRate = 60000L)
    void updateMetricNumber(){
        metricGaugeNumber.set(processEngine.getHistoryService().createHistoricProcessInstanceQuery().count());
    }
}
----

== Метрики для моніторингу

[NOTE]
--
Перелік метрик у процесі наповнення...
--

[TIP]
--
Детальніше з типами метрик можна ознайомитись в офіційній документації https://micrometer.io/docs/concepts[Micrometer].
--

|===
|Категорія|Метрика|Тип|Опис

.4+|Загальні метрики _Process Engine_
|_camunda.user.count_
|`Gauge`
|

|_camunda.authorization.count_
|`Gauge`
|

|_camunda.deployments_
|`Gauge`
|

|_camunda.active.process.definitions_
|`Gauge`
|

.9+|Загальні метрики бізнес-процесів
|_camunda.active.user.tasks_
|`Gauge`
|

|_camunda.active.user.tasks.assigned_
|`Gauge`
|

|_camunda.active.user.tasks.unassigned_
|`Gauge`
|

|_camunda.completed.process.instances_
|`Gauge`
|

|_camunda.terminated.process.instances_
|`Gauge`
|

|_camunda.suspended.process.instances_
|`Gauge`
|

|_camunda.active.process.instances_
|`Gauge`
|

|_camunda.process.instances.total_
|`Gauge`
|

|_camunda.active.incidents_
|`Gauge`
|

.4+|Загальні метрики обміну повідомленнями в рамках бізнес-процесу
|_camunda.active.signal.event.subscriptions_
|`Gauge`
|

|_camunda.active.conditional.event.subscriptions_
|`Gauge`
|

|_camunda.active.compensate.event.subscriptions_
|`Gauge`
|

|_camunda.active.message.event.subscriptions_
|`Gauge`
|

.4+|Загальні метрики асинхронного виконання задач бізнес-процесу
|_camunda.message.jobs_
|`Gauge`
|

|_camunda.timer.jobs_
|`Gauge`
|

|_camunda.executable.timer.jobs_
|`Gauge`
|

|_camunda.executable.jobs_
|`Gauge`
|

.5+|Видалення історичних даних виконання бізнес-процесів
|_camunda.history.cleanup.removed.process.instances_
|`Gauge`
|

|_camunda.history.cleanup.removed.task.metrics_
|`Gauge`
|
|===

== Оновлення існуючих реєстрів

В рамках процедури оновлення, необхідно забезпечити:

* Реєстрація даних метрик увімкнена за замовченням
* Налаштування збору та зберігання метрик в _Promethes_
* Встановлення та налаштування _Grafana_-дашборди

== Високорівневий план розробки

=== Технічні експертизи

* _BE_
* _DevOps_

=== План розробки

* Автоматизація налаштування _Prometheus_ для збирання метрик з *business-process-administration-portal*
* Реалізація механізму реєстрації метрик виконання бізнес-процесів та налаштувань через _Micrometer_ в *business-process-administration-portal*
* Розробка _Grafana_-дашборди моніторингу метрик виконання бізнес-процесів
* Розробка процедури оновлення існуючих реєстрів з автоматичним встановленням _Grafana_-дашборди
* Створення інструкцій для адміністраторів по використанню дашборди моніторингу метрик виконання бізнес-процесів