= Аутентифікація посадових осіб через портал id.gov.ua

== Загальний опис
Надання можливості використовувати портал (id.gov.ua) для аутентифікації в кабінеті посадової особи як альтернативу використання ІІТ віджета.

== Ролі користувачів
* Посадова особа
* Адміністратора реєстру

== Загальні принципи та положення
* Користувач посадової особи має існувати в реалмі посадових осіб відповідного реєстру
* Наявність атрибутів (`drfo`, `edrpou`, `fullName` ) в ключі посадової особи є обовʼязковою
* Значення атрибутів посадової особи в порталі id.gov.ua та атрибути користувача мають співпадати

== Функціональні сценарії
* Посадова особа аутентифікується в кабінеті
* Адміністратор реєстру, вказує можливість для аутентифікації через id.gov.ua


== Технічний дизайн рішення
=== Загальна структура компонента
image::architecture/platform/operational/user-management/user-managment-components.svg[]

=== Діаграма розгортання

image::architecture/platform/operational/user-management/user-managment-deployment.svg[]

=== Схема розгортання
[plantuml, flow, svg]
----
autonumber
actor "Посадова особа" as officer
participant "Браузер" as browser
participant "API менеджер" as api
participant "Кабінет чиновника" as portal
participant "Підсистема управління \nкористувачами та ролями" as key
participant "Сховище користувацьких сессій" as storage
participant "Портал \n(id.gov.ua)" as idgov

officer -> browser: адреса портала
browser -> api
api -> portal
return стартова сторінка
api --> browser
browser --> officer: старторва сторінка

officer -> browser: "Увійти в систему"
browser -> key: запит на аутентифікацію

return посилання на сторінку для аудентифікації
browser -> idgov: перенаправлення на сторінку для аутентифікації
return форма аутентифікації
browser --> officer: логін форма id.gov.ua

officer -> browser: файл ключ та пароль
browser -> idgov

idgov --> key: результат аутентифікації\n(отримання access token)

key -> idgov: отримання інформації про користувача (/userInfo) в ідентіті провайдері
return данні теж ІП

key -> key: пошук та валідація користувача за данними з id.gov.ua (аутентифікатор)
key --> browser: аутентифікація успішна\nтокен та посилання на головну сторінку
browser -> portal: головна
portal -> key: перевірка токена
return токен валідний
portal --> browser
browser --> officer:
----


