= Конфігурація Custom URL для сервісу управління користувачами та ролями Keycloak

Надання можливості конфігурації DNS імен для сервісу управління користувачами та ролями Keycloak використовуючи інтерфейс
адмін-консолі.

== Загальний опис
xref:architecture/platform/administrative/config-management/custom-dns.adoc[Дизайн по конфігурації DNS імені]
(окремого від імені OpenShift кластера) для Кабінету посадової особи та Кабінету отримувача послуг не враховував потребу
в конфігурації також відповідного імені для сервісу управління користувачами та ролями (Keycloak) через адмін-консоль.

Якщо кластер OpenShift створений повністю у приватній мережі, то перевірка сертифікатів на рівні підсистеми
управління міжсервісною взаємодією та аутентифікація за допомогою Keycloak відбуваються не коректно з деякими компонентами реєстру.

В цьому дизайні пропонується рішення для розв'язання цих проблем.

=== Ролі користувачів
* Технічний адміністратор реєстру
* Технічний адміністратор Платформи

== Функціональні сценарії
* Конфігурація DNS імен компонента Keycloak через адмін-консоль на рівні Платформи
* Конфігурація DNS імен кабінетів користувачів через адмін-консоль на рівні реєстру
* Повернення кабінетів до кластерного DNS OpenShift кластера
* Видалення доданих DNS-імен до Keycloak
* Конфігурація Keycloak Frontend URL в відповідному xref:ROOT:platform-glossary.adoc[рілмі]

== Загальні принципи та положення
* Конфігурація Keycloak DNS-імен задається технічним адміністратором Платформи
* Разом з DNS-іменем, платформний адміністратор також має задати TLS-сертифікат для домена
* DNS-імена для реєстрових кабінетів користувачів конфігуруються реєстровим технічним адміністратором
* Реєстровий адміністратор може задавати тільки піддомен для доменів з переліку наявних в системі
* Перелік наявних в системі доменів формується із заданих DNS-імен платформного Keycloak
* За замовчуванням, вважаємо що сертифікат доданий на рівні Платформи є wildcard і відповідно використовуємо його для
створення кастомних роутів для кабінетів
*

== Дизайн існуючого рішення

=== Keycloak DNS

В поточній версії Платформи, конфігурація DNS імені Keycloak відбувається наступним чином:

** Вручну додати в `values.yaml` реєстру наступне налаштування:
+
[source,yaml]
----
keycloak:
  customHost: keycloak.example.com
----

** Вручну налаштувати Keycloak Frontend URL у відповідному рілмі на нове DNS імʼя

** Вручну створити OpenShift Route з доданим TLS сертифікатом

=== DNS-імена для адміністративних інтерфейсів користувачів
xref:architecture/platform/administrative/config-management/custom-dns.adoc[Дизайн по конфігурації DNS імені для кабінетів користувачів]

=== Недоліки поточної реалізації
* Налаштування DNS-імені центрального компонента Keycloak відбувається з конфігурації реєстрів
* Потребує багато ручних налаштувань (route, request auth, keycloak realm тощо)
* Технічний адміністратор Платформи не контролює DNS налаштування Keycloak

== Технічний дизайн рішення

** Перед початком конфігурації функціоналу кастомних DNS-імен для адміністративних інтерфейсів користувачів, потрібно
спочатку налаштувати такий DNS для Keycloak в налаштуваннях Платформи.
** При налаштованому Keycloak DNS-імені повинен зʼявитись дропдаун елемент в адміністративних інтерфейсах з пропозицією
обрати DNS для keycloak кластерний за замовчуванням, чи один з кастомних доданих на попередньому кроці з можливістю вказати
піддомен

.Верхньорівнева діаграма взаємодії на рівні підсистем
[plantuml, flow, svg]
image::architecture-workspace/platform-evolution/keycloak-dns/keycloak-url-subsystem-level.svg[keycloak-url-subsystem-level]

.Верхньорівнева діаграма взаємодії на рівні розгортання конфігурації
[plantuml, flow, svg]
image::architecture-workspace/platform-evolution/keycloak-dns/keycloak-url-configuration-level.svg[keycloak-url-configuration-level]

=== Макети дизайну адмін-консолі

== План розробки
=== Технічні експертизи
* BE
* DevOps

=== План розробки


=== Компоненти системи та їх призначення в рамках дизайну рішення
|===
|Компонент|Службова назва|Призначення / Суть змін
|===
== Безпека