= Конфігурація Custom URL для сервісу управління користувачами та ролями Keycloak

Надання можливості конфігурації DNS імені для сервісу управління користувачами та ролями Keycloak використовуючи інтерфейс
адмін-консолі.

== Загальний опис
=== Опис проблеми
Дизайн по конфігурації DNS імені (окремого від імені OpenShift кластера) для Кабінету посадової особи та Кабінету
отримувача послуг не враховував потребу в конфігурації також відповідного імені для сервісу управління користувачами та
ролями (Keycloak)

=== Ролі користувачів
* Технічний адміністратор реєстру

== Функціональні сценарії
* Конфігурація DNS імені компонента Keycloak через адмін-консоль
* Повернення до дефолтного DNS OpenShift кластера
* Конфігурація Keycloak Frontend URL в відповідному рілмі
* Конфігурація istio request authentication

== Дизайн існуючого рішення
В поточній версії Платформи, конфігурація DNS імені Keycloak відбувається наступним чином:

** Вручну вкомітити в `values.yaml` реєстру наступне налаштування:
+
[source,yaml]
----
keycloak:
  customHost: keycloak.example.com
----

** Вручну налаштувати Keycloak Frontend URL у відповідному рілмі на нове DNS імʼя

== Загальні принципи та положення

== Технічний дизайн рішення

** Перед початком налаштування функціоналу кастомних DNS для Кабінетів користувачів, налаштувати кастомний DNS для
Keycloak в налаштуваннях платформи.
** При налаштованому DNS Keycloak повинен зʼявитись дропдаун в кабінетах з пропозицією обрати ДНС для keycloak:
дефолтний чи кастомний

=== Діаграми послідовності

=== Макети дизайну адмін-консолі

== План розробки
=== Технічні експертизи
=== План розробки

== Безпека