= Розміщення сервіса публікування аналітичної звітності Redash за Kong

== Загальний опис

В поточній версії Платформи публічний доступ до Redash відбувається через OpenShift HAProxy. Це спричиняє дві проблеми:

* Потенційна вразливіть сервіса публікування Redash, коли він розміщений поза виокремленого API шлюзу для зовнішнього трафіку
* При налаштуванні власного xref:admin:registry-management/control-plane-custom-dns.adoc[DNS-імені для Кабінетів]
зʼявляється потреба в налаштуванні також і окремого імені для сервіса публікування аналітичної звітності Redash.

Внесення Redash за Kong вирішить ці проблеми.

== Ролі користувачів

* Посадова особа

== Загальні принципи та положення

* Винесення стосується тільки сервісу публікування аналітичної звітності Redash (redash-viewer)
* Трафік до Redash повинен йти через основний Kong, використовуючи роут кабінету чиновника зі шляхом `/reports`
* Конг повинен перевіряти наявніть JWT-токену та у випадку відсутності переадресовувати користувача на підсистему
управління користувачами та ролями (Keycloak) для авторизації

== Функціональні сценарії

.Потік мережевого трафіку до Redash
[plantuml, flow, svg]
image::architecture-workspace/platform-evolution/kong-redash/kong-redash.svg[remote-file-transfer,700]

.Діаграма розгортання
[plantuml, flow, svg]
image::architecture-workspace/platform-evolution/kong-redash/deployment-diagram-redash.svg[remote-file-transfer,350]

== Високорівневий план розробки

=== Технічні експертизи

* _BE_
* _Frontend_
* _DevOps_

=== План розробки

* Змінити контекстний шлях у Redash
* Внести Redash за Kong шляхом створення необхідних налаштувань в Kong ресурсах
* Змінити URI в кабінеті чиновника на новий
* Дозволити трафік з Kong на Redash Viewer
* Прибрати з адмін-консолі налаштування DNS для Redash

== Безпека

== Глосарій та акроніми

[cols="3,6"]
|===
|Термін|Опис

|_Kong_
|API шлюз для зовнішнього трафіку
|_URI_
|Уніфікований ідентифікатор ресурсів (англ. Uniform Resource Identifier, URI) — компактний рядок літер, який однозначно ідентифікує окремий ресурс в інтернеті.

|===
