= Управління стратегіями нечіткого порівняння імені користувача при автентифікації

== Загальний опис

Існує проблема, що атрибут _fullName_ в КЕП що містить ПІП особи є нестандартизованим і заповнюється працівниками АЦСК. Це призводить до того що при перевипуску КЕП або використанні КЕП виданого іншим АЦСК значення можуть не збігатися. Зокрема інший КЕП може містити кілька пробілів замість одного, містити або не містити спеціальні символи такі як апостроф або дефіс.

Такі зміни в атрибуті _fullName_ призводять до того, що користувач не може зайти в кабінет з новим ключем оскільки значення _fullName_ атрибута з КЕП не збігається зі значенням що збережене в БД KeyCloak. В свою чергу в KeyCloak зберігається значення атрибута _fullName_ з КЕП користувача який він використовував при першому логіні в реєєстр (атореєстрації).

[NOTE]
--
Поточна реалізація стратегії автентифікації ("_strictIgnoreCase_") не враховує дані особливості та працює за принципом приведення стрічки до нижнього регістру та видалення лише символів пробілу.
--

Для вирішення цієї проблеми необхідно замістити поточну реалізацію новою стратегією нечіткого порівняння стрічок, що не враховує спецсимволи.

== Актори та ролі користувачів

* Отримувачі послуг
* Посадові особи

== Функціональні сценарії

* Застосування правил нечіткого порівняння повного імені користувача отриманого з _КЕП_ або від зовнішнього _IdP_ зі значенням збереженим в _KeyCloak IAM_ при автентифікації

== Стратегія автентифікації користувачів

Автентифікація користувача в компоненті "_dso-*-authenticator_" відбувається згідно описаної нижче логіки.

Автентифікатор в якості вхідних даних отримує наступні атрибути користувача:

- _drfo_: ідентифікаційний номер або серія і номер паспорта особи
- _fullName_: ПІП особи
- _edrpou_: код організації до якої належить особа

В процесі автентифікації відбувається пошук користувача в БД за атрибутом _drfo_. Якщо користувача з відповідним атрибутом знайдено, то відбувається порівняння атрибутів _fullName_ та _edrpou_ (в разі наявності).

Якщо порівняння _drfo_ та _edrpou_ відбувається чітким співпадінням (equals) то для fullName необхідно реалізувати наступну логіку ("_alphanumericIgnoreCase_"):

- перед порівнянням стрічки приводяться до нижнього регістру
- видаляються всі символи окрім латинських та кириличних літер та цифр
- довжина стрічки після нормалізації не може бути менше 50% від оригінальної

=== Компоненти системи та їх призначення в рамках дизайну рішення

У даному розділі наведено перелік компонент системи, які задіяні або потребують змін/створення в рамках реалізації функціональних вимог згідно з технічним дизайном рішення.

|===
|Компонент|Службова назва|Призначення / Суть змін

|_Автентифікатор громадян_
|*keycloak-ds-citizen-authenticator*
|Застосування стратегії нечіткого порівняння повного імені особи при автентифікації

|_Автентифікатор посадових осіб_
|*keycloak-ds-officer-authenticator*
|Застосування стратегії нечіткого порівняння повного імені посадової особи при автентифікації

|===

== Високорівневий план розробки

=== Технічні експертизи

* _BE_

=== План розробки

* Розширення citizen та officer автентифікаторів логікою застосування стратегії нечіткого порівняння імені користувача
* Розробка інструкцій користувачів