= Повернення інформації про загальну кількість записів при пагінації критеріїв пошуку

== Загальний опис

Наявна функціональність пагінації не надає можливості через API отримати загальну кількість елементів по критерію пошуку, по якому був виконаний запит. Зовнішнім системам доводиться перебирати всі сторінки ресурсу до пустої відповіді. Це незручно в розробці, та ускладнює можливість надати зручний інтерфейс кінцевому користувачу. 

Для поліпшення досвіду користувача пропонується реалізувати можливість створення критеріїв пошуку з новим типом пагінації, які будуть додатково повертати інформацію про поточну сторінку, кількість елементів на сторінці, загальну кількість елементів та загальну кількість сторінок.

== Актори та ролі користувачів
* Розробник регламенту
* Зовнішні системи

== Загальні принципи та положення

* Поведінка і контракт існуючих критеріїв пошуку не змінюється. 
* Зберігається зворотня сумісність конфігурації критеріїв пошуку.    

== Функціональні сценарії

* Налаштування критеріїв пошуку
* Генерація сервісів критеріїв пошуку
* Синхронний виклик API критерію пошуку
* Асинхронний виклик API критерію пошуку
* Виклик API критерію пошуку із зовнішніх систем, з "Трембіта" і без

== Поточна реалізація

Поточна реалізація надає можливість передавати offset та limit при визові API критерію пошуку. Ця можливість включена за замовчанням для всіх критеріїв пошуку, ала може бути вимкнута за допомогою атрибута тега _createSearchCondition_ `pagination=false`.

Відповідь API, незалежно від того включена опція пагінації чи ні, містить тільки масив елементів по яким був здійснений пошук. Інформація про загальну кількість елементів чи сторінок у відповіді не передбачена. При цьому якщо були передані offset та limit то відповідь формується з їх урахуванням. 

== Цільовий дизайн
=== Схема та модуль розширення тегів Liquibase
В схемі розширених тегів тип атрибуту _pagination_ змінюється на enum, який складається з наступних значень  _offset_, _none_, _page_ та  _true_ і _false_ які є синонімами _offset_ та _none_ для зворотньої сумісності.

.Схема розширених тегів Liquibase
[source, xml]
----
	<xsd:simpleType name="paginationType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="offset"/>
			<xsd:enumeration value="page"/>
			<xsd:enumeration value="none"/>
      <!--Following is for the backward compatibility-->
			<xsd:enumeration value="true"/> <!--Synonym for "offset"-->
			<xsd:enumeration value="false"/> <!--Synonym for "none"-->     
		</xsd:restriction>
	</xsd:simpleType>
  ....
	<xsd:complexType name="selectSearchConditionType">
		....
		<xsd:attribute name="pagination" type="paginationType" use="optional" default="offset"/>
	</xsd:complexType>
----

В модуль розширення тегів Liquibase додається можливість запису значення атрибуту _pagination_ для нових типів пагінації в таблицю метаданих `ddm_liquibase_metadata`, при обробці тегу _createSearchCondition_. 

=== Сервіс генератор
IMPORTANT: Значення _offset_ і _none_ є заміною для _true_ і _false_. Якщо на критерій пошуку атрибут _pagination_ встановлено в _offset_ чи _none_, логіка генерації сервісів має бути такою як вона я є для _true_ і _false_ відповідно.

Якщо на критерій пошуку атрибут _pagination_ встановлено в _page_, має бути згенерований сервіс який додатково до фільтрів заданих в критерії пошуку приймає:

pageSize:: бажана кількість елементів на сторінці. За замовчанням 10
pageNo:: бажаний номер сторінки. За замовчанням 0

У відповіді мають міститися наступні атрибути

content:: масив елементів по яким відбувся пошук, обмежений номером сторінки та кількістю елементів на сторінці
totalElements:: загальна кількість елементів по запиту
totalPages:: загальна кількість сторінок по запиту
pageSize:: кількість елементів на сторінці
pageNo:: номер сторінки що повертається


.Наприклад
[source, json]
----
{
  "content": [
    {
      "col1": "ADMIN"
    },
    {
      "col1": "USER"
    }    
  ],
  "totalElements": 1,
  "totalPages": 1,
  "pageNo": 0,
  "pageSize": 20,
}
----

Для отримання _content_ сервіс виконує запит до БД, який генерується таким же чином як і в поточній реалізації обробки запиту з limit та offset. При цьому значення limit та offset беруться не напряму з запиту API, а вираховуються з отриманих pageSize і pageNo. Де *limit=pageSize*, а *offset=pageSize*pageNo*

Для отримання _totalElements_ сервіс виконує додатковий запит до БД, який генерується за наступним шаблоном

[source, sql]
----
SELECT COUNT(*)
  FROM <search_condition_view>
 WHERE <filtering conditions>
----

*totalPages* дорівнює *ceil(totalElements/pageSize)*

*pageNo* та *pageSize* ті які були застосовані у запиті - за вхідними параметрами чи за замовчанням.

.Приклад OpenAPI специфікації (xref:attachment$/architecture-workspace/platform-evolution/sc-pagination-count/swagger.yml[Завантажити])
[%collapsible]
====
swagger::{attachmentsdir}/architecture-workspace/platform-evolution/sc-pagination-count/swagger.yml[]
====

Також має бути згенерований еквівалентний Kafka API для асинхронної взаємодії і SOAP для взаємодії з зовнішніми системами, якщо відповідні опції включені в регламенті реєстру для критерію пошуку. 

TIP: Spring має стандартні засоби для реалізації пагінації цього типу. Приклад імплементації https://www.petrikainulainen.net/programming/jooq/using-jooq-with-spring-sorting-and-pagination/[Using jOOQ With Spring: Sorting and Pagination]


=== Компоненти системи та їх призначення в рамках дизайну рішення
У даному розділі наведено перелік компонент системи, які задіяні або потребують змін/створення в рамках реалізації функціональних вимог згідно з технічним дизайном рішення.

|===
|Компонент|Службова назва|Призначення / Суть змін

|Сервіс Генератор
|service-generation-utility 
|Генерація Java-проектів для сервісів

|Схема розширених тегів Liquibase
|liquibase-ext-schema
|Валідація схеми 

|Модуль розширення тегів Liquibase
|liquibase-ddm-ext
|Обробка розширених тегів на етапі розгортання регламенту

|===

== Моделювання регламенту реєстру
=== Моделювання критеріїв пошуку
Адміністратору регламенту надається можливість обирати тип пагінації _page_ при моделюванні критеріїв пошуку. 

.Структура регламенту реєстру
[plantuml, registry-sc-regulation-structure, svg]
----
@startsalt
{
{T
+ <&folder> registry-regulation
++ <&folder> bpmn
++ <&folder> dmn
++ <&folder> <b>data-model</b>
+++ <&file> <b>searchConditions.xml</b>
++ ...
}
}
@endsalt
----

.Приклад конфігурації 
[source, xml]
----
    <changeSet author="registry owner" id="create pageable SC factor_chemical_host_contains_name">
        <ext:createSearchCondition name="factor_chemical_host_contains_name_pageable"  pagination="page">
            <ext:table name="factor" alias="f">
                <ext:column name="factor_id"/>
                <ext:column name="name" sorting="asc" searchType="contains"/>
            </ext:table>
            <ext:where>
                <ext:condition tableAlias="f" columnName="factor_type" operator="eq" value="'Хімічний: ГОСТ'"/>
            </ext:where>
        </ext:createSearchCondition>
    </changeSet>
----

Для адміністратора регламенту також доступні опції _offset_ та _none_ в атрибуті _pagination_. 

_offset_ - дає той самий результат що і _true_ в поточній реалізації і є опцією за замовчанням.

_none_ - дає той самий результат що і _false_ в поточній реалізації.

Опції _true_ та _false_ стають застарілими і можуть бути видалені з часом. Але наразі, в наявних регламентах реєстрів вони продовжать працювати так само як і в поточній реалізації. 

=== Валідація регламенту реєстру
В рамках реалізації рішення, необхідно розширити xml схему розширених тегів liquibase по якій проходить валідація.  

== Високорівневий план розробки
=== Технічні експертизи
* _BE_

=== План розробки
* Розширення схеми розширених тегів Liquibase.
* Розширення модуля розширення тегів Liquibase.
* Розширення сервіс генератору.
* Розробка інструкцій для розробника регламенту та референтних прикладів.