= Моделювання UI-форм за допомогою веб-редактора

== Функціональні сценарії

[TIP]
Описати функціональні сценарії, які необхідно реалізувати в рамках дизайну рішення

- Створення нових схем UI-форм
- Внесення змін до існуючих схем UI-форм
- Перегляд схем UI-форм
- Перегляд _JSON_-коду представлення схем UI-форм

== Ключові вимоги

[TIP]
Описати основні вимоги, які необхідно врахувати в рамках обрання підходу для реалізації рішення

- Надання адміністратору єдиного веб-інтерфейсу моделювання UI-форм бізнес-процесів
- Веб-інтерфейс моделювання має підтримувати локалізацію
- Веб-інтерфейс моделювання має підтримувати темування та стилізацію задля цілісної інтеграції у інтерфейс _Системи адміністрування регламенту реєстру_
- Веб-інтерфейс моделювання має підтримувати усі існуючи типові розширення каталогу моделювання, розроблені у вигляді _Element Templates_
- Веб-інтерфейс моделювання має генерувати _JSON_-код представлення UI-форм сумісний з поточною версією _Form.IO_

== Out of Scope

[TIP]
Описати вимоги, які не було розглянуто детально у процесі аналізу та дизайну

== Технологічний стек

[TIP]
Описати технології, які обрано для реалізації рішення

|===
|Технологія / Бібліотека|Версія|Ліцензія|Документація|Опис

|https://...[ReactJS]
|...
|...
|...
|...

|https://...[TypeScript]
|...
|...
|...
|...

|https://...[formio.js]
|...
|...
|...
|...

|...
|...
|...
|...
|...

|...
|...
|...
|...
|...

|===

== Підтримка темування та стилізації

[TIP]
Описати механізм реалізації вимоги

== Підтримка локалізації

[TIP]
Описати механізм реалізації вимоги

== Інтерфейс моделювання

[TIP]
Додати екрани для візуалізації досвіду моделювання згідно функціональних сценаріїв