= Порівняння версій схем UI-форм регламенту реєстру

== Функціональні сценарії

[TIP]
Описати функціональні сценарії, які необхідно реалізувати в рамках дизайну рішення

- _Side-by-side_ порівняння версій UI-форм бізнес-процесів регламенту реєстру
- _Side-by-side_ порівняння _JSON_-коду представлень версій UI-форм бізнес-процесів
- Перегляд деталей змін на рівні властивостей окремих елементів _Components_ UI-форм

== Ключові вимоги

[TIP]
Описати основні вимоги, які необхідно врахувати в рамках обрання підходу для реалізації рішення

* Синхронність _Side-by-Side_ перегляду версій UI-форм
* Маркування кольорами відмінностей на рівні окремих елементів _Components_ UI-форм
** [green]#Додано#
** [yellow]#Змінено#
** [red]#Видалено#
* Перегляд змін властивостей при наведенні на елемент UI-форми
* Перегляд агрегованого переліку відмінностей між UI-формами

== Out of Scope

[TIP]
Описати вимоги, які не було розглянуто детально у процесі аналізу та дизайну

== Технологічний стек

[TIP]
Описати технології, які обрано для реалізації рішення

|===
|Технологія / Бібліотека|Версія|Ліцензія|Документація|Опис

|https://...[ReactJS]
|...
|...
|...
|...

|https://...[TypeScript]
|...
|...
|...
|...

|https://...[formio.js]
|...
|...
|...
|...

|...
|...
|...
|...
|...

|===

== Інтерфейс користувача

[TIP]
Додати екрани для візуалізації досвіду моделювання згідно функціональних сценаріїв