//= Модуль ГІС
= GIS module

//== Загальні вимоги
== General requirements

//* Відображення мап, супутникових знімків які підтримуються сторонніми системами в порталі посадових осіб або громадян, з можливістю їх перемикання між собою та зміни масштабу.
* Display maps and satellite images supported by third-party systems in citizen/officer portals, with the ability to switch between them, and change display scale.

//* Відображення об'єктів реєстру, які мають прив'язку до місцевості на мапі -- шари (layers).
* Display Registry objects that are bound to specific areas on the map -- layers.

//* Включення декількох шарів на мапі.
* Display multiple layers on the map.

//* Пошук об'єктів реєстру на мапі за атрибутами.
* Search for Registry objects by attributes on the map .

//* Можливість вибору координати точки, внесення ліній або полігонів шляхом нанесення їх на карту в бізнес-процесі.
* Ability to select point coordinates, plotting lines or polygons by drawing them on the map in a Business Process.

//* Геокодування -- пошук координати на мапі за публічною адресою або назвою об'єкта.
* Geocoding -- search for coordinates on the map by public address or object name.

//* Зворотне геокодування -- пошук адреси або назви об`єкту за координатами
* Reverse geocoding -- search for public address or object name on the map by coordinates.

//== Структура рішення
== Solution structure

image::architecture/registry/operational/geo/gis-context.svg[]


//== Компоненти
== Components

//=== Компонент Form.io (LeafletJs)
=== Form.io component (LeafletJs)
//В основі компонента Form.io лежить бібліотека `LeafletJs`, в якій інтегруються всі аспекти геомодуля.
Form.io component is based on the `LeafletJs` library, where all the GIS module aspects are integrated.

=== GeoServer

//Сервер з відкритим кодом, який дозволяє отримувати дані з БД у вигляді GeoJSON.
Open source server that allows for the receiving of data from DB in GeoJSON form.

//* *GeoJSON* -- формат даних, який може бути інтерпретований LeafletJS і відображений на карті +
* *GeoJSON* -- data format that can be interpreted by LeafletJS and displayed on the map +
//* *Feature* -- інформація про об'єкт точку +
* *Feature* -- інформація про об'єкт точку +
//* *Layer* -- растровий або векторний набір даних, представлений набором географічних об'єктів.
* *Layer* -- raster or vector data set, represented by a collection of geographical objects.

=== GeoServer Publisher
//Застосунок командного рядка який здійснює автоматичну конфігурацію GeoServer-а, шляхом виконання викликів до адміністративного API `GeoServer`-а.
Command line application that performs automatic configuration of the GeoServer by executing calls to the GeoServer administrative API.

=== Nominatim


////
[NOTE]
Робота запланована на реліз 1.8
////
[NOTE]
Planned for version 1.8 release


== Deployment

image:architecture/registry/operational/geo/gis-deployment.svg[]

//Гіс модуль є частиною окремого шаблону реєстру. У випадку розгортання реєстру з такого шаблону буде додатково встановлено GeoServer та Nominatim. +
GIS module is a part of a dedicated Registry template. In case of Registry deployment from such a template, GeoServer and Nominatim will be installed. +
//Конфігурація GeoServer та публікація шарів відбувається під час розгортання регламенту.
GeoServer configuration and layer publication is performed during regulations deployment.

//== Конфігурація
== Configuration

//Конфігурація геомодуля полягає в створенні підключення до БД та публікації структур, які містять тип "геометрія" (`geometry`) як шари у `GeoServer`-і. Конфігурація відбувається на етапі розгортання регламенту на кроці `publish-geoserver-configuration` основного pipeline `registry-regulations`.
The GIS module is configured via the creation of a connection to the DB, and the publication of structures that include `geometry` type as layers in the `GeoServer`. The configuration is performed on the regulations deployment stage, on the `publish-geoserver-configuration` step of the main `registry-regulations` pipeline.
