== Форми

=== Загальний опис

Модуль для організації роботи з формами що знаходяться у репозиторії регламенту `registry-regulations` за шляхом `/forms`.

.Надає наступний функціонал:
- Отримання списку всіх форм регламенту
- CRUD операції над формами регламенту

==== Отримання списку всіх форм регламенту

Повертає список всіх форм вказаної версії регламенту, їх назви, системні назви та дати створення та останнього оновлення форм.

.Діаграма послідовності отримання списку доступних форм у вказаній версії
[plantuml]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/forms/get-form-list.puml[]
----

==== Створення форми регламенту

Додає форму з переданим контентом у версії-кандидаті.

.Діаграма послідовності створення форми у вказаній версії-кандидаті
[plantuml]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/forms/create-form.puml[]
----

==== Читання форми регламенту

Повертає контент форми версії (майстер, чи кандидату).

.Діаграма послідовності читання форми з вказаної версії
[plantuml]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/forms/read-form.puml[]
----

==== Оновлення форми регламенту

Оновлює форму, або створює нову форму якщо та не існує, з переданим контентом у версії-кандидаті.

.Діаграма послідовності оновлення форми у вказаній версії-кандидаті
[plantuml]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/forms/update-form.puml[]
----

==== Видалення форми регламенту

Видаляє файл форми з версії-кандидата.

.Діаграма послідовності видалення форми з вказаної версії-кандидата
[plantuml]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/forms/delete-form.puml[]
----

=== Робота з датами створення та останнього оновлення форм

.Загальні положення:
- Дати створення та останнього оновлення повинні показувати реальну картину роботи з формою.
- Для форм що вже існують в майстер-версії дати повинні показуватися без міграції файлів форм.

.Зчитування дат форм
* Дати створення та останнього оновлення форми можуть знаходитися у JSON контенті форми:
** JSON path дати створення форми - `**__$.created__**`
** JSON path дати останнього оновлення форми - `**__$.modified__**`
* Якщо в контенті форми не представлена дата створення або останнього оновлення то вона зчитується з `**__git log__**`
** Дата створення форми - це дата першого комміту з `**__git log__**` по файлу цієї форми
** Дата останнього оновлення форми - це дата останнього комміту з `**__git log__**` по файлу цієї форми

[NOTE]
====
Формат дат створення та останнього оновлення - `**ISO 8601**`.
Всі дати в зоні `**UTC+0**`, тобто формат - `**yyyy-MM-dd\'T\'HH:mm:ss.SSS\'Z'**`.
Наприклад `**2022-09-20T15:26:13.136Z**`.
====

.Запис дат форм
* При створенні форми через REST-API:
** Обидві дати у контенті форми виставляються автоматично
** Обидві дати будуть дорівнювати поточній даті на момент створення форми
** Будь-які явно зазначені дати у контенті форми при створенні будуть ігноруватись.
* При оновленні форми через REST-API:
** Дата оновлення у контенті форми виставляються автоматично
** Дата оновлення буде дорівнювати поточній даті на момент оновлення форми
** Дата створення при оновленні форми #_також_# проставляється автоматично та зчитується з _неоновленого_ контенту форми або з `**__git log__**` файлу форми, якщо дата створення не представлена у контенті
** Будь-які явно зазначені дати у контенті форми при оновленні будуть ігноруватись.

.Приклад контенту форми з датами:
[source,json]
----
{
  "components": [
    ...
  ],
  "title": "Погодження заяви",
  "name": "add-appgood",
  "created": "2022-08-19T16:15:24.784Z",
  "modified": "2022-09-20T15:26:13.136Z"
}
----

.Високорівнева JSON схема форм
[source,json]
----
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$"
    },
    "title": {
      "type": "string",
      "minLength": 1
    },
    "created": {
      "type": "string",
      "format": "date-time"
    },
    "modified": {
      "type": "string",
      "format": "date-time"
    },
    "components": {
      "type": "array"
    }
  },
  "additionalProperties": true,
  "required": [
    "name",
    "title",
    "components"
  ]
}
----