= Розмежування доступу організацій до бізнес-процесів на рівні атрибутів користувачів
:toc:
:toc-title: ЗМІСТ
:toclevels: 5
:sectnums:
:sectnumlevels: 5
:sectanchors:

WARNING: Інструкція у процесі формування.

== Загальний опис

З метою підтримки функціональності розмежування доступу організацій до бізнес-процесів на рівні атрибутів користувачів, розроблено типове розширення до бізнес-процесів -- делегат `${getUsersByAttributesFromKeycloak}`, для якого імплементовано однойменний шаблон *Get users by attributes from keycloak*, представлений у вигляді JSON-файлу _getUsersByAttributesFromKeycloak.json_.

Делегат потрібний для того, щоб при виконанні бізнес-процесу отримувати список користувачів (посадових осіб) за певними атрибутами із сервісу керування ідентифікацією та доступом Keycloak.

Виконати пошук у Keycloak можливо за такими атрибутами: ::

* `edrpou`, тобто ідентифікаційним номером суб'єкта Єдиного державного реєстру підприємств і організацій (ЄДРПОУ);
* `drfo`, тобто ідентифікаційним номером фізичної особи у Державному реєстрі фізичних осіб -- платників податків (ДРФО).

Кожна посадова особа певної організації має такі атрибути у сервісі Keycloak. У результаті виконання запита, до бізнес-процесу повертається список імен користувачів -- мається на увазі НЕ повне ім'я користувача, а його `username`. Наприклад, `user1`.

Цей список імен можна надалі застосовувати при виконанні користувацької задачі бізнес-процесу у полі *Candidate users*.

*Candidate users* -- користувачі, уповноважені на виконання задачі. Тобто це параметр, який потрібен для того, щоб розмежувати доступ до конкретних задач бізнес-процесу між користувачами.

Список користувачів із Keycloak зберігається до результівної змінної (Result variable) у користувацькій задачі бізнес-процесу. Ця змінна надалі обробляється groovy-скриптом при виконанні задачі скриптування, в результаті чого список перетворюється на рядок, який можна використовувати у Candidate users.

TIP: Отже, ми із сервісу Keycloak за атрибутами `edrpou` та `drfo` отримуємо об'єкт _список_, за допомогою скрипту конвертуємо його в _рядок_, значення якого розділені комами і використовуються для надання доступу до конкретної задачі бізнес-процесу у параметрі `Candidate users`.

////
== Налаштування делегата у бізнес-процесі

== Налаштування доступу у Keycloak



