//= Нереляційне сховище даних
= Non-relational data storage
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

//== Загальний опис
== General overview

//_xref:arch:architecture/registry/operational/ext-api-management/overview.adoc[Підсистема управління зовнішнім трафіком операційної зони реєстру]_ використовує розподілену _in-memory_ базу даних xref:arch:architecture/platform-technologies.adoc#redis[Redis] з  xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc[_Підсистеми управління нереляційними базами даних_] для зберігання даних сесій користувачів (_JWT_-токенів).
_xref:arch:architecture/registry/operational/ext-api-management/overview.adoc[External traffic management subsystem of the registry operational zone]_ utilizes a distributed _in-memory_ xref:arch:architecture/platform-technologies.adoc#redis[Redis] database from xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc[_Non-relational database management subsystem_] to store user session data (_JWT tokens_).

[NOTE]
--
//Детальніше з технічним підходом можна ознайомитися xref:arch:architecture/registry/operational/ext-api-management/api-gateway/kong-oidc.adoc#_управління_сесіями_користувачів[за посиланням].
For a more detailed technical approach, you can refer to the xref:arch:architecture/registry/operational/ext-api-management/api-gateway/kong-oidc.adoc#_управління_сесіями_користувачів[link].
--

//== Структури даних
== Data structures

=== sessions

//Зберігання користувацьких _JWT_-токенів, ключ зберігається як стрічка в _HEX_-форматі.
Storage for user _JWT_ tokens, with the key stored as a string in _HEX_ format.

[NOTE]
--
//Детальніше можна ознайомитись в документації бібліотеки https://github.com/bungle/lua-resty-session[lua-resty-session].
For more information, you can refer to the documentation of the https://github.com/bungle/lua-resty-session[lua-resty-session].
--