@startuml
skinparam shadowing false
skinparam DatabaseBackgroundColor white
skinparam DatabaseBorderColor #2688d4
skinparam QueueBackgroundColor white
skinparam QueueBorderColor #2688d4
skinparam NoteBackgroundColor white
skinparam NoteBorderColor #2688d4
skinparam sequence {
    ArrowColor #2688d4
    ActorBorderColor #2688d4
    LifeLineBorderColor #2688d4
    ParticipantBorderColor #2688d4
    ParticipantBackgroundColor white
    BoxBorderColor #2688d4
    BoxBackgroundColor white
}

actor Громадянин as citizen
participant "Кабінет \nГромадянина" as citizen_portal
participant "Kong \nУправління API" as kong
participant "Сервіс управління \nналаштуваннями користувачів" as user_settings_service
database "Redis\nin-memory сховище \n(channel-verification-codes.*)" as redis
queue "'user-notifications'\n Kafka Topic" as user_notifications_topic
participant "Сервіс повідомлень користувачів" as user_notifications_service
database "Сховище налаштувань користувачів" as user_settings_database

citizen -> citizen_portal: Внесення адреси \nдля каналу зв'язку
activate citizen_portal
  citizen_portal -> citizen_portal: Клієнтська валідація адреси
  citizen_portal -> kong: **Запит на валідацію адреси каналу зв'язку** \nPOST /api/settings/me/{channel}/validate \n*Ідентифікатор сесії Kong
  note left
    {
        "address": "{email}"
    }
  end note
  activate kong
    kong -> user_settings_service: **Запит на валідацію адреси каналу зв'язку** \nPOST /api/settings/me/{channel}/validate \n*X-Access-Token
    activate user_settings_service
      user_settings_service -> user_settings_service: Валідація адреси \nзгідно правил каналу \n(regexp, blacklist, тощо.)
      user_settings_service --> kong: 200: Валідацію пройдено
    deactivate user_settings_service
    kong --> citizen_portal: 200: Валідацію пройдено
  deactivate kong
  citizen_portal -> kong: **Запит на верифікацію каналу зв'язку** \nPOST /api/settings/me/{channel}/verify \n*Ідентифікатор сесії Kong
  note left
    {
        "address": "${email}"
    }
  end note
  activate kong
    kong -> user_settings_service: **Запит на верифікацію каналу зв'язку** \nPOST /api/settings/me/{channel}/verify \n*X-Access-Token
    activate user_settings_service
      user_settings_service -> user_settings_service: Валідація адреси \nзгідно правил каналу \n(regexp, blacklist, тощо.)
      user_settings_service -> redis: Перевірки існування запису за ключем \n**channel-verification-codes:{userId}/{channel}***
      redis --> user_settings_service: Результат пошуку запису з email-адресою та згенерованим OTP-кодом
      alt Запис знайдено - спробу повторного запиту на верифікацію заблоковано, поки не вичерпається час, відведений на підтвердження попереднього запиту
        user_settings_service --> kong: 429 - Too Many Requests
        kong --> citizen_portal: 429 - Too Many Requests
        citizen_portal --> citizen: Спробу повторного запиту на верифікацію заблоковано, \nпоки не вичерпається час, \nвідведений на підтвердження попереднього запиту
      end
      user_settings_service -> user_settings_service: Генерація 6-значного OTP-коду **verificationCode**
      user_settings_service -> redis: Збереження запису з ключем \n**channel-verification-codes:{userId}/{channel}*** \nта встановленим TTL згідно конфігурації
      note left
        {
            "address": "{email}",
            "verificationCode": "{verificationCode}"
        }
      end note
      redis --> user_settings_service: OK
      user_settings_service -> user_notifications_topic: Публікація запиту на \nвідправлення повідомлення з OTP-кодом
      note left
       {
         "context": {
           "system": "Low-code Platform",
           "application": "user-settings-service",
         },
         "notification": {
           "templateName": "channel-confirmation",
           "ignoreChannelPreferences": true
         },
         "recipients": [
           {
              "id": "{userId}",
              "channels": [
                {
                  "channel": "email",
                  "email": "{email}"
                }
              ],
              "parameters": [
                {
                    "key": "verificationCode",
                    "value": "{verificationCode}"
                }
              ]
           }
         ]
       }
      end note
      user_notifications_topic --> user_settings_service: Запит опубліковано
      user_settings_service --> kong: 202 - Accepted
    deactivate user_settings_service
    kong --> citizen_portal: 202 - Accepted
    note right
      {
          "verificationCodeExpirationSec": "60"
      }
    end note
  deactivate kong
  citizen_portal --> citizen: Очікування на внесення \nOTP-коду з повідомлення
deactivate citizen_portal

user_notifications_service -> user_notifications_topic: Отримання запиту \nна відправлення повідомлення
activate user_notifications_service
  user_notifications_service -> user_notifications_service: Обробка запиту \nна відправлення повідомлення
  user_notifications_service --> citizen: Відправлення повідомлення з OTP-кодом
deactivate user_notifications_service

citizen -> citizen_portal: Активація адреси для каналу зв'язку \nз внесенням OTP-коду
activate citizen_portal
  citizen_portal -> citizen_portal: Клієнтська валідація OTP-коду та адреси
  citizen_portal -> kong: **Запит на активацію адреси каналу зв'язку** \nPOST /api/settings/me/{channel}/activate \n*Ідентифікатор сесії Kong
  note left
    {
        "address": "{email}",
        "verificationCode": "{verificationCode}"
    }
  end note
  activate kong
    kong -> user_settings_service: **Запит на активацію адреси каналу зв'язку** \nPOST /api/settings/me/{channel}/activate \n*X-Access-Token
    activate user_settings_service
      user_settings_service -> redis: Отримання запису за ключем \n**channel-verification-codes:{userId}/{channel}***
      redis --> user_settings_service: Запис з OTP-кодом
      user_settings_service -> user_settings_service: Перевірка співпадіння адреси та OTP-коду
      alt Адресу та OTP-код верифіковано успішно
        user_settings_service -> redis: Видалення запису з OTP-кодом за ключем\n**channel-verification-codes:{userId}/{channel}***
        redis --> user_settings_service: OK
        user_settings_service -> user_settings_database: Збереження адреси та активація каналу зв'язку
        user_settings_database --> user_settings_service
        user_settings_service --> kong: 200 - OK
      end
    deactivate user_settings_service
    kong --> citizen_portal: 200 - OK
  deactivate kong
  citizen_portal --> citizen: Канал успішно активовано \nз новою адресою
deactivate citizen_portal
@enduml