@startsalt
{
{T
+ <&folder> registry-regulation
++ ...
++ <&folder> notifications
+++ <&folder> email
++++ <&folder> <b>channel-confirmation</b>
+++++ <&folder> css
++++++ <&file> style.css
+++++ <&folder> images
++++++ <&file> image.jpg
++++++ <&file> ...
+++++ <&file> template.ftlh
+++++ <&file> notification.yml
+++ <&folder> diia
++++ <&folder> <b>channel-confirmation</b>
+++++ <&file> template.diia
+++++ <&file> notification.yml
}
}
@endsalt