@startsalt
{
{T
+ <&folder> registry-regulation
++ <&folder> bpmn
++ <&folder> dmn
++ ...
++ <&folder> global-vars
+++ <&file> camunda-global-system-vars.yml
++ <&folder> <b>settings</b>
+++ <&file> <b>settings.yml</b>
}
}
@endsalt