@startuml
actor "Чиновник" as officer order 10
participant "Кабінет чиновника" as officer_portal  order 20
participant "Зовнішній API\ngateway" as gateway  order 30
participant "User task mgmt" as user_task_management  order 40
participant "Сервіс перевірки\nцифрового підпису" as digital_sign_service  order 50
participant "Ceph" as ceph  order 60
participant "Camunda" as bmps_service  order 70
participant "Data Rest API" as data_rest  order 80
participant "Kafka" as kafka order 90
participant "Data Kafka API" as data_kafka_api order 100

title Збереження даних у дата фабрику

autonumber
skinparam maxMessageSize 220

group Підпис форми
  officer -> officer_portal: Підписує форму з даними
  activate officer_portal
    officer_portal -> officer_portal: Підпис форми з даними
    officer_portal -> gateway: Передача даних
    activate gateway
      gateway -> gateway: Перевірка авторизації (правильного JWT)
      gateway -> user_task_management: Проксування запиту
      activate user_task_management
        user_task_management -> digital_sign_service: Перевірка консистентності body, signed hash з сертифікатами, JWT
        activate digital_sign_service
        return валідність підпису
        user_task_management -> user_task_management: Формування об'єкту з: body, підпис, JWT
        user_task_management -> ceph: Збереження сформованного об'єкту
        activate ceph
        return  ключ
        user_task_management -> bmps_service: Завершення user task з ключем отриманнам з Ceph
        activate bmps_service
          bmps_service -> ceph: Читання об'єкту по ключу
          activate ceph
          return  об'єкт
          opt Трансформація даних форми до контакту Data API
            bmps_service -> bmps_service: Трансформація об'єкту
            bmps_service -> digital_sign_service: Передача нового об'єкту на підпис
            activate digital_sign_service
              digital_sign_service -> digital_sign_service: Підпис ключем адмінестратора (системним)
            return hash підпису
            bmps_service -> ceph: зберегти новий об'єкт з підписом
          activate ceph
          return  ключ
          end
          bmps_service -> bmps_service: Формування запиту до потрібного Data Rest APІ
          bmps_service -> data_rest: Виклик Rest API через Istio:  body та  хедери з посиланням на Ceph derived and original,  хедер JWT
          activate data_rest
            data_rest -> digital_sign_service: Перевірка консистентності body, signed hash, JWT
            activate digital_sign_service
            return
            data_rest -> data_rest: Валідація формату даних (у майбутньому)
            data_rest -> data_rest: Збереження виклику до аудиту (у майбутньому)
            data_rest -> kafka: Збереження даних (body, signed hash, jwt)
            activate kafka
            return
            kafka <- data_kafka_api: Вичитування даних
            activate data_kafka_api
              data_kafka_api -> data_kafka_api: Перевірка JWT на базі підгруженого сертифікату з KeyCloak (у майбутньому)
              data_kafka_api -> digital_sign_service: Перевірка консистентності body, signed hash, JWT
              activate digital_sign_service
              return  публічні сертифікати ЕЦП
              data_kafka_api -> data_kafka_api: Збереження даних
              kafka <-- data_kafka_api: Підтвердження про читання
            deactivate data_kafka_api
        return наступний wait state

      return
    return
   return
end
@enduml