= Схема бази даних notifications

[plantuml, notifications-schema, svg]
----
@startuml
hide circle
skinparam linetype ortho
skinparam monochrome true

entity "**inbox_notification**" {
  + ""id"": //uuid [PK]//
  --
  *""recipient_id"": //text //
  *""subject"": //text //
  *""message"": //text //
  *""is_acknowledged"": //boolean //
  *""created_at"": //timestamp with time zone //
  *""updated_at"": //timestamp with time zone //
}

entity "**notification_template**" {
  + ""id"": //uuid [PK]//
  --
  *""name"": //text //
  *""channel"": //text //
  *""content"": //text //
  *""checksum"": //text //
  *""created_at"": //timestamp with time zone //
  *""updated_at"": //timestamp with time zone //
  ""title"": //text //
  ""ext_template_id"": //text //
  ""ext_published_at"": //timestamp with time zone //
}

entity "**notification_template_attr**" {
  + ""id"": //uuid [PK]//
  --
  *""template_id"": //uuid [FK]//
  *""name"": //text //
  *""value"": //text //
}

"**notification_template_attr**"   }--  "**notification_template**"
@enduml
----
.Умовні позначення
[%collapsible]
====
include::partial$architecture-workspace/documentation-templates/component-design-template/db-schema-legend.adoc[]
====
== inbox_notification
In-app повідомлення користувачів для відображення у Кабінеті Громадянина

[options="header",cols="a"]
|======
|Ім'я колонки +
Опис
| `*id* _uuid_ *(PK)*` + 
Ідентифікатор рядка 
| `*recipient_id* _text_` + 
Ідентифікатор користувача, який має отримати повідомлення 
| `*subject* _text_` + 
Заголовок повідомлення 
| `*message* _text_` + 
Зміст повідомлення 
| `*is_acknowledged* _boolean_` + 
Статус повідомлення (прочитане/не прочитане) 
| `*created_at* _timestamp with time zone_` + 
Дата/Час створення повідомлення 
| `*updated_at* _timestamp with time zone_` + 
Дата/Час оновлення повідомлення 

|======

== notification_template
Дані шаблонів повідомлень

[options="header",cols="a"]
|======
|Ім'я колонки +
Опис
| `*id* _uuid_ *(PK)*` + 
Ідентифікатор рядка 
| `*name* _text_` + 
Службова назва шаблону повідомлення. Є унікальною в комбінації з `*channel*`
| `*channel* _text_` + 
Канал зв’язку для використання шаблону повідомлення. Є унікальним в комбінації з `*name*`

* inbox - Кабінеті Громадянина
* email - електронна пошта
* diia - застосунок Дія
| `*content* _text_` + 
Текстовий шаблон тіла повідомлення для подальшого заповнення даними 
| `*checksum* _text_` + 
SHA-256 чек-сума, згенерована на вміст поля CONTENT 
| `*created_at* _timestamp with time zone_` + 
Дата/Час створення/публікації шаблону 
| `*updated_at* _timestamp with time zone_` + 
Дата/Час останньої зміни в рамках публікації шаблону 
| `title _text_` + 
Текстовий заголовок повідомлення 
| `ext_template_id _text_` + 
Унікальний ідентифікатор запису у зовнішній системі.
| `ext_published_at _timestamp with time zone_` + 
Дата/Час останньої публікації запису у зовнішню системуBD 

|======
[options="header",cols="a"]
|======
|Обмеження унікальності
|`ext_template_id`
|`name,channel`
|======
== notification_template_attr
Додаткові атрибути шаблонів в залежності від вимог окремого каналу зв'язку

[options="header",cols="a"]
|======
|Ім'я колонки +
Опис
| `*id* _uuid_ *(PK)*` + 
Ідентифікатор рядка 
| `*template_id* _uuid_` (references <<_notification_template>>.id) + 
Ідентифікатор шаблону повідомлень 
| `*name* _text_` + 
Службова назва атрибуту 
| `*value* _text_` + 
Значення атрибуту 

|======
