= Підсистема управління зовнішнім трафіком адміністративної зони реєстру
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

Підсистема, призначенням якої є управління зовнішнім трафіком та контроль доступу до API сервісів адміністративної зони Реєстру.

== Функції підсистеми

* Аутентифікація та авторизація запитів
* Маршрутизація трафіку до API-сервісів підсистем адміністративної зони реєстру
* Налаштування та контроль рейт-лімітів
* Трансформація запитів та відповідей
* Логування вхідних запитів

== Технічний дизайн підсистеми

image::architecture/registry/administrative/ext-api-management/registry-admin-ext-traffic-subsystem.drawio.svg[width=600,float="center",align="center"]

== Складові підсистеми

|===
|Назва компоненти|Представлення в реєстрі|Походження|Репозиторій|Призначення

|_Зовнішній API-шлюз адміністративної зони_
|`kong-admintools-kong`
|3rd-party
|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/general/kong-admin-tools[gerrit:/mdtu-ddm/general/kong-admin-tools]
|Забезпечує керування трафіком, авторизацію, контроль доступу до API, балансування навантаження,
перетворення запитів/відповідей та аналітику/моніторинг.

|_ServiceMesh шлюз_
|`istio-ingressgateway`
|3rd-party
|https://github.com/istio/proxy[github:/istio/proxy]
|Мережевий шлюз що працює на межі istio service-mesh та отримує вхідні з'єднання HTTP/TCP.

|xref:arch:architecture/registry/administrative/ext-api-management/redis-storage.adoc#_sessions_admin_tools[__Операційне сховище сесій користувача__]
|`redis:sessions_admin_tools`
|3rd-party
|-
|Зберігання користувацьких JWT-токенів
|===

== Технологічний стек

При проектуванні та розробці підсистеми, були використані наступні технології:

* xref:arch:architecture/platform-technologies.adoc#kong[Kong]
* xref:arch:architecture/platform-technologies.adoc#kong-ingress-controller[Kong Ingress Controller]
* xref:arch:architecture/platform-technologies.adoc#redis[Redis]
* xref:arch:architecture/platform-technologies.adoc#istio[Istio ServiceMesh]

== Атрибути якості підсистеми
=== _Scalability_

Підсистема управління зовнішнім трафіком адміністративної зони реєстру підтримує як горизонтальне, так і вертикальне масштабування.
[TIP]
--
Детальніше з масштабуванням підсистем можна ознайомитись у розділі xref:architecture/container-platform/container-platform.adoc[]
--

=== _Observability_
Підсистема управління зовнішнім трафіком адміністративної зони реєстру підтримує журналювання вхідних запитів та збір метрик продуктивності для
подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--

=== _Portability_
Підсистема управління зовнішнім трафіком адміністративної зони реєстру може бути перенесена, розгорнута та керована однаково та надійно на різних
платформах оркестрації контейнерів що розгорнуті в різних хмарних середовищах або власній інфраструктурі в дата-центрі.

[TIP]
--
Детальніше можна ознайомитись у розділі xref:arch:architecture/container-platform/container-platform.adoc[Платформа оркестрації контейнерів]
--
