= Нереляційне сховище даних
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

_xref:arch:architecture/registry/administrative/ext-api-management/overview.adoc[Підсистема управління зовнішнім трафіком адміністративної зони реєстру]_ використовує розподілену _in-memory_ базу даних xref:arch:architecture/platform-technologies.adoc#redis[Redis] з  xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc[_Підсистеми управління нереляційними базами даних_] для зберігання даних сесій користувачів (_JWT_-токенів).

[NOTE]
--
Детальніше з технічним підходом можна ознайомитися
xref:arch:architecture/registry/operational/ext-api-management/api-gateway/kong-oidc.adoc#_управління_сесіями_користувачів[за посиланням].
--

== Структури даних

=== sessions_admin_tools

Зберігання користувацьких _JWT_-токенів, ключ зберігається як стрічка в _HEX_-форматі.

[NOTE]
--
Детальніше можна ознайомитись в документації бібліотеки https://github.com/bungle/lua-resty-session[lua-resty-session].
--