= Компонент Code
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Опис компонента

Компонент *Code* дозволяє вставляти довільний JavaScript код та запускати його за різними подіями(наприклад, клік по кнопці або завантаження сторінки).

CAUTION: Використовуйте *Code* з переліку _Оновлених_ компонентів.

== Основні функції

[tabs]
====
API ::
* Поле для вводу JavaScript.

TIP: У цій функції використовується JS вставка. xref:bp-modeling/forms/components/general/eval.adoc[Детальніше про JS вставки.]

* *`Allow code to run during component initialization`*: дозволити виконання коду під час ініціалізації компонента.

====

== Формат даних

.Submission
[source,typescript]
----
// Цей компонент не має даних
----

== Сценарії використання
=== Запит до API та встановлення нового значення для компоненту editgrid
В компонент _Code_ вносимо JavaScript код для запиту на сервер:

[source,javascript]
----
  // якщо data.editGrid пустий, не відображаємо editGrid
  getComponent('editGrid').visible = !!data.editGrid?.length; 
  if (!getComponent('textfield').pristine) { // робити запит тільки після змін в компоненті textfield
    fetch('/api/data-factory/sample-by-id' + queryParams)
      .then((response) => {
        return response.json();
      .then((res) => {
        // якщо data.editGrid не пустий, відображаємо editGrid
        getComponent('editGrid').visible = !!res.length;
        if (res.length) {
          // встановлюємо дані в editGrid
          setValue('editGrid', res);
        }
      });
    });
  }
----

В цьому прикладі ми робимо _GET_ запит на сервер передаючи query параметри, використовуючи _fetch_ функцію.

=== Клік по кнопці

В компоненті _Button_ обираємо _Custom Action_ та в поле _Button Custom Logic_ вносимо таке значення:
[source,javascript]
----
instance.root.getComponent('code').runCode()
----
При кліку буде викликатися JavaScript код який був внесений в компоненті _Code_.

=== Зміна значення в текстовому полі

В компоненті _Textfield_ в _Calculated Value_ вносимо таке значення:
[source,javascript]
----

instance.root.getComponent('code').runCode();

----
При зміні тексту буде викликатися JavaScript код який був внесений в компоненті _Code_.
