= Компонент Code
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Опис компонента

Компонент *Code* дозволяє вставляти довільний JavaScript код та запускати його за різними подіями(наприклад, клік по кнопці або завантаження сторінки).

CAUTION: Використовуйте *Code* з переліку _Оновлених_ компонентів.

== Основні функції

[tabs]
====
API ::
* Поле для вводу JavaScript.

TIP: У цій функції використовується JS вставка. xref:bp-modeling/forms/components/general/eval.adoc[Детальніше про JS вставки.]

====

== Формат даних

.Submission
[source,typescript]
----
// Цей компонент не має даних
----

== Сценарії використання
=== Запит до API та встановлення нового значення для компоненту
[source,javascript]
----
  fetch('/api/data-factory/sample-by-id' + queryParams)
    .then((response) => {
      return response.json();
    .then((data) => {
      setValue('editgrid', data);
    });
  });
----

В цьому прикладі ми робимо _GET_ запит на сервер передаючи query параметри, використовуючи _fetch_ функцію. Отримані дані встановлюємо в значення компоненту, використовуючи функцію _setValue_ (перший аргумент назва компоненту(Property Name з таби API), другий нове значення).

=== Клік по кнопці

В компоненті _Button_ обираємо _Custom Action_ та в поле _Button Custom Logic_ вносимо таке значення:
[source]
----
instance.root.getComponent('code').runCode()
----
При кліку буде викликатися JavaScript код який був внесений в компоненті _Code_.

=== Зміна значення в текстовому полі

В компоненті _Textfield_ в _Calculated Value_ вносимо таке значення:
[source]
----
if (value) {
    instance.root.getComponent('code').runCode();
}
----
При зміні тексту буде викликатися JavaScript код який був внесений в компоненті _Code_.

TIP: Обов'язково використовуйте перевірку на існування _value_, щоб запобігти нескінченного циклу.