= Компонент Columns
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Опис компонента

Компонент *Columns* є елементом інтерфейсу який можна використовувати для групування інших компонентів. Використовуйте стовпці, якщо ви хочете відобразити більше одного компонента в одному рядку або щоб заощадити вертикальний простір у формі.


CAUTION: Використовуйте *Columns* з переліку _Оновлених_ компонентів.

== Основні функції

Компонент *Columns* підтримує велику кількість опцій для застосування при взаємодії із формою процесу, які розподілені за вкладками.

[tabs]
====
Display ::
include::general/common-descriptions/display/label.adoc[]
* *`Column Properties`*: налаштування кількості стовпців, які відображатимуться у формі, і вказати параметри ширини, зміщення для кожного стовпця. Після налаштування ви можете легко змінювати порядок стовпців за допомогою функції перетягування без необхідності створювати все з нуля.
include::general/common-descriptions/display/hidden.adoc[]

API ::
* *`Property Name`*: ім'я цього поля для API-ендпоінту, не функціональне для цього компонента

Conditions ::
include::general/common-descriptions/conditional/index.adoc[]


====

== Формат даних

.Submission
[source,typescript]
----
// Цей компонент не має даних
----
TIP: Цей компонент може містити внутрішні компоненти, та це не буде впливати на дані цих компонентів. Зверніть увагу, що внутрішні компоненти повинні мати все рівно різні імена (вкладка _API_ поле _Property Name_).

== Сценарії використання
. Область, в якій розміщено елемент «Columns», ділиться на 12 частин.
. Ширина кожної колонки задається в цих частинах.
. Offset – відступ на початку колонки.
--
Приклад:
--
. Якщо ширину першої колонки задати 5, а другої 7, то перша колонка займе 5/12 ширини контейнера, а друга - 7/12 ширини контейнера.
. Якщо задати для другої колонки offset=1, а width=6, то між першою та другою колонками буде відступ в 1/12 контейнера.
--
Рекомендується задавати width и offset таким чином, щоб їх сума була рівна 12. Якщо сума буде більша, то колонки, які не вміщуються по ширині, будуть перенесені на наступний рядок.
--

