:toc-title: ЗМІСТ
:toc: auto
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Компонент DateTime

== Опис компонента

Компонент *DateTime* є елементом інтерфейсу для роботи з датою та часом.


CAUTION: Використовуйте DateTime з переліку _Оновлених_ компонентів.

== Основні функції

Компонент *DateTime* підтримує велику кількість опцій для застосування при взаємодії із формою процесу, які розподілені за вкладками.

[tabs]
====
Display ::
include::general/common-descriptions/display/label.adoc[]
include::general/common-descriptions/display/label-position.adoc[]
* *`Allow Manual Input`*: дозволяє користувачеві вручну вводити дату.
* *`Format`*: формат дати для відображення значення дати й часу. За замовчуванням _yyyy-MM-dd HH:mm_. Використовуйте формати, надані https://github.com/angular-ui/bootstrap/tree/master/src/dateparser/docs/#uibdateparsers-format-codes[DateParser Codes, window=_blank]
include::general/common-descriptions/display/placeholder.adoc[]
include::general/common-descriptions/display/description.adoc[]
include::general/common-descriptions/display/tooltip.adoc[]
include::general/common-descriptions/display/tabindex.adoc[]
include::general/common-descriptions/display/hidden.adoc[]
include::general/common-descriptions/display/disabled.adoc[]

Date ::
* *`Enable Date Input`*: дозволяє вводити дату для цього поля.
* *`Use calendar to set minDate`*: дозволяє використовувати календар для встановлення мінімальної дати.
* *`Use calendar to set maxDate`*: дозволяє використовувати календар для встановлення максимальної дати.
* *`Disable specific dates or dates by range`*: вимкнути певні дати або дати за діапазоном.
* *`Custom Disabled Dates`*: вимкнути певні дати або дати за діапазоном за допомогою функцій. Детальніше <<_custom_disabled_dates>> 
* *`Disable weekends`*: вимкнути вихідні дні
* *`Disable weekdays`*: вимкнути робочі дні

Time ::
* *`Enable Time Input`*: дозволяє вводити час для цього поля.
* *`Hour Step Size`*: кількість годин для збільшення в інструменті вибору часу, за замовчуванням 1.
* *`Minute Step Size`*: кількість годин для зменшення в інструменті вибору часу, за замовчуванням 1.
* *`12 Hour Time (AM/PM)`*: відображати час у 12-годинному форматі з AM/PM.

Data ::
include::general/common-descriptions/data/index.adoc[]
include::general/common-descriptions/data/allow-manual-override.adoc[]

Validation ::
include::general/common-descriptions/validation/index.adoc[]

API ::
include::general/common-descriptions/api/index.adoc[]

Conditions ::
include::general/common-descriptions/conditional/index.adoc[]

Table ::
include::general/common-descriptions/table/index.adoc[]

====

== Формат даних

.Submission
[source,typescript]
----
String
// Формат: YYYY-MM-DD | YYYY-MM-DDTHH:mm:ss.sss
// Приклад: '2021-02-16'
----
TIP: Не використовуйте об'єкт moment та Date як значення дати, на сервер ви завжди повинні відправити _String_ формат, як вказано в прикладі. Для moment завжди викликайте функцію format() яка повертає відформатовану дату типу _String_.

== Сценарії використання
У цих функціях використовується JS вставка. xref:bp-modeling/forms/components/general/eval.adoc[Див.]

=== Custom Disabled Dates
Вимкнути для вибору всі вихідні дні
[source,javascript]
date.getDay() === 0 || date.getDay() === 6

Вимкнути дати після сьогоднішньої (включаючи сьогоднішню). Тут ми використовуємо бібліотеку moment.js для аналізу, перевірки, обробки та форматування дат. Дивіться більше методів у https://momentjs.com/docs/#/query/[momentjs docs, window=_blank].
[source,javascript]
moment(date).isSameOrAfter(moment(), 'day')

=== Custom Validation
Ви повинні призначити змінну _valid_ як true, або як повідомлення про помилку(текст помилки можливо вказати в умові або в полі _Custom Error Message_), якщо перевірка не вдається.
Для того щоб проводити будь-які операції з датами, такі як порівняння, необхідно спочатку перетворити значення поля _input_ на об'єкт Date. 
[source,javascript]
----
// в цьому кейсі текст помилки буде братися з поля Custom Error Message
valid = new Date(input) > new Date(data.datetimeLatest)
// в цьому кейсі, якщо valid буде false, користувачу відобразиться помилка error message
valid = new Date(input) > new Date(data.datetimeLatest) ? 'error message'
----

=== Custom Default Value
Встановити дефолтним значення завтрашню дату
[source,javascript]
----
value = moment().add(1,'days').format();
----