:toc-title: ЗМІСТ
:toc: auto
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Компонент Field Set

== Опис компонента

Компонент *Field Set* є елементом інтерфейсу який можна використовувати для створення заголовка для області форми або групування компонентів. Це корисно розмістити всередині компонентів макета або між багатьма пов'язаними компонентами.

CAUTION: Використовуйте Field Set з переліку _Оновлених_ компонентів.

== Основні функції

Компонент *Field Set* підтримує велику кількість опцій для застосування при взаємодії із формою процесу, які розподілені за вкладками.

[tabs]
====
Display ::
* *`Legend`*: це заголовок, який відображається для набору полів.
include::general/common-descriptions/display/tooltip.adoc[]
include::general/common-descriptions/display/tabindex.adoc[]
include::general/common-descriptions/display/hidden.adoc[]
include::general/common-descriptions/display/disabled.adoc[]
* *`Collapsible`*: дає можливість згортати групу компонентів.
** *`Initially Collapsed`*: показати компонент в згорнутому вигляді.

API ::
* *`Property Name`*: ім'я цього поля для API-ендпоінту, не функціональне для цього компонента

Conditions ::
include::general/common-descriptions/conditional/index.adoc[]


====

== Формат даних

.Submission
[source,typescript]
----
// Цей компонент не має даних
----
TIP: Цей компонент може містити внутрішні компоненти, та це не буде впливати на дані цих компонентів. Зверніть увагу, що внутрішні компоненти повинні мати все рівно різні імена (вкладка _API_ поле _Property Name_).

