:toc-title: ЗМІСТ
:toc: auto
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Компонент Table

== Опис компонента

Компонент *Table* є елементом інтерфейсу який упорядковує дані в рядки та стовпці.


CAUTION: Використовуйте Table з переліку _Оновлених_ компонентів.

== Основні функції

Компонент *Table* підтримує велику кількість опцій для застосування при взаємодії із формою процесу, які розподілені за вкладками.

[tabs]
====
Display ::
include::general/common-descriptions/display/label.adoc[]
* *`Number of Rows`*: дозволяє ввести кількість рядків, які повинні відображатися в таблиці.
* *`Number of Columns`*: дозволяє ввести кількість колонок, які повинні відображатися в таблиці.
* *`Cell Alignment`*: горизонтальне вирівнювання клітинок таблиці.
include::general/common-descriptions/display/hidden.adoc[]

API ::
* *`Property Name`*: ім'я цього поля для API-ендпоінту, не функціональне для цього компонента

Conditions ::
include::general/common-descriptions/conditional/index.adoc[]


====

== Формат даних

.Submission
[source,typescript]
----
// Цей компонент не має даних
----
TIP: Цей компонент може містити внутрішні компоненти, та це не буде впливати на дані цих компонентів. Зверніть увагу, що внутрішні компоненти повинні мати все рівно різні імена (вкладка _API_ поле _Property Name_).

