= Примітки до релізу 1.9.7. Частина 5
//:toc:
:toc-title: ЗМІСТ
//:sectnums:
:sectlinks:
:sectanchors:
:note-caption: Покращено
:tip-caption: Розроблено
:caution-caption: Інше
:important-caption: Виправлено
:warning-caption: Покращення безпеки

== Обмеження доступу на рівні IP до SOAP-інтерфейсів ШБО "Трембіта"
//TODO: first.xlsx

[TIP]
====
* [*] Можливість обмежувати доступ до SOAP API-роутів, що використовуються ШБО "Трембіта".

* [*] Можливість задавати дозволені IP-адреси для налаштування вхідних інтеграцій через ШБО "Трембіта".

* [*] Додано логіку: не створювати `registry-soap-api` роут за відсутності адрес в `ipList`.

* [*] Реалізовано можливість додавати IP-адреси в анотацію роутів компонентів `bp-webservice-gateway-trembita` та `registry-soap-api`.

* [*] Змінено роут `bp-webservice-gateway-trembita` на `path`-based.

* [*] Додано валідацію IP-адреси на рівні Jenkins-пайплайну.

* [*] Внесено зміни до бібліотеки для тестів після додавання нового роуту `bp-webservice-gateway-trembita`.
====

////

== Управління керівником реєстру кадровиками та іншими посадовими особами

[TIP]
====
Управління кадровиками та посадовими особами у реєстрі: ::

* [*] Запроваджено референтний бізнес-процес для управління реєстром кадровиків та інших посадових осіб керівником реєстру.

* [*] Керівники реєстру тепер мають змогу переглядати інформацію про кадровиків та інших посадових осіб, а також виконувати дії з обраними записами таблиці через Кабінет.

Типові розширення для розробників регламенту: ::

* [*] *Create officer user*: дозволяє створювати посадових осіб з обов'язковим внесенням службових атрибутів та додаванням додаткових довільних атрибутів, з автоматичним призначенням системної ролі.

* [*] *Save officer user attributes*: дозволяє редагувати системні та додаткові атрибути посадових осіб з бізнес-процесу.

* [*] *Get roles*: дає змогу отримувати список доступних ролей заданого реалма із бізнес-процесу.

* [*] *Get user roles*: дозволяє отримувати перелік регламентних ролей користувача.

Делегати та шаблони element templates: ::

* [*] На рівні back-end розроблено делегати та element templates для вищезгаданих типових розширень, що значно спрощує процес інтеграції та розширення функціональності бізнес-процесів.
====

== Управління кадровиком посадовими особами

[TIP]
====
* [*] Створено референтний бізнес-процес для управління посадовими особами через кабінет кадровика. Тепер кадровики мають змогу переглядати інформацію про посадових осіб, а також виконувати дії з обраними записами у таблиці. Це поліпшує ефективність управління персоналом та спрощує процеси.
====

== Ієрархічна модель заявників (не лише в рамках однієї юрособи) -- референтний приклад

[TIP]
====
Управління повноваженнями та ієрархічна модель: ::

* [*] Створено ієрархічну модель заявників для управління повноваженнями отримувачів послуг на референтному бізнес-процесі. Це дозволяє керівникам ЮО/ФОП ефективно керувати дозволами діяти від імені їхньої організації.

Модель даних та повідомлення: ::

* [*] Реалізовано дата-модель та сформовано шаблони повідомлень для бізнес-процесу.

Моделювання форм та сценаріїв: ::

* [*] Здійснено моделювання форм та сценаріїв бізнес-процесу, що підвищує зручність роботи користувачів.

Скасування ліцензій та управління повноваженнями: ::

* [*] Також, уповноваженим особам-отримувачам послуг надано можливість створювати запити на скасування ліцензій від імені ЮО/ФОП через референтний бізнес-процес. Це забезпечує більшу гнучкість та контроль над управлінням повноваженнями.
====

== Створення елементів ієрархії (підрозділи…) із Кабінету посадової особи -- референтний приклад

[TIP]
====
Розробка бізнес-процесу та моделі даних: ::

* [*] Розроблено референтний бізнес-процес (БП) для перегляду та виконання дій з елементами ієрархії з кабінету посадової особи.

* [*] Створено модель даних для управління ієрархією та заповнено довідники початковими значеннями.

* [*] Розроблено бізнес-процес для управління ієрархічною структурою, включаючи розробку форм.

* [*] Розроблено форми для редагування та створення документів у рамках бізнес-процесів.

* [*] Розширено модель даних необхідними критеріями пошуку (Search Conditions).

Робота з атрибутами користувачів: ::

* [*] Додано підтримку автоматичного пропагування додаткових атрибутів користувачів в Access Token / ID Token / UserInfo через "JsonWebToken#otherClaims".

* [*] Розроблено компонент `oidc-usermodel-custom-attributes-mapper` в EDP для обробки кастомних атрибутів користувачів для протоколу OIDC.

* [*] Додано mapper для кастомних атрибутів у збірку Keycloak та налаштування для клієнтів "officer-portal" та "citizen-portal".

* [*] Додано можливість отримання значень додаткових атрибутів користувача через функції "initiator()" та "completer()" у JUEL-виразах БП за допомогою "UserDto#attributes".

* [*] Додано метод (getter) "attributes" у клас "UserDTO" для використання у функціях "initiator()" та "completer()" JUEL.

Налаштування та використання атрибутів: ::

* [*] Налаштовано атрибут "КАТОТТГ" як ознаку приналежності до ієрархії та доступність для використання в RLS (Row-Level Security) та звітах на рівні регламенту реєстру разом з іншими додатковими атрибутами.

* [*] Позначено protocol mapper "КАТОТТГ" як deprecated у helm-чартах.
Позначено відповідні java-класи та методи, які використовують "КАТОТТГ", як deprecated.

Робота з протоколами та компонентами: ::

* [*] Додано компонент "saml-user-custom-attributes-mapper" в EDP для обробки кастомних атрибутів користувачів для протоколу SAML.

* [*] Додано mapper для кастомних атрибутів у збірку Keycloak та налаштування для клієнтів "redash-viewer" та "redash-admin".

Розширення пошуку та швидкого пошуку: ::

* [*] Розроблено типове розширення "Search registry users by attributes" для пошуку користувачів з можливістю вказати атрибути, їх значення та тип пошуку.

* [*] Створено універсальний делегат для пошуку користувачів в Keycloak та розроблено відповідний елемент-шаблон.

* [*] Розширено Keycloak REST API extension новим методом для пошуку користувачів за атрибутами.

* [*] Додано можливість швидкого текстового пошуку в табличному компоненті для користувачів кабінету посадової особи/громадянина після SAML-автентифікації.

* [*] Додано компонент "Quick Search" для швидкого пошуку у компоненті "Edit Grid" для використання в "Officer-portal" та "Citizen-portal".

* [*] Додано можливість налаштування швидкого текстового пошуку у табличному компоненті за даними ("Quick Search").
====

== Декларативний підхід до налаштування емуляторів зовнішніх систем для спрощення тестування зовнішніх інтеграцій реєстру

[TIP]
====
Налаштування емуляторів для зовнішніх інтеграцій у Control Plane: ::

* [*] Розширено можливості control-plane-console для виконання налаштувань.

* [*] Оновлено Control Plane Jenkins-пайплайн для розгортання реєстру з урахуванням описаних змін.

* [*] Видалено роут для Wiremock.

* [*] Прибрано з примітки біля чек-боксу "для версій реєстру 1.9.4 та вище".

* [*] Змінено URL емулятора реєстру з `url = http://wiremock:<port>/` на `http://wiremock.{NAME_REGІSTRy}:<port>/`.

Додавання нових емуляторів для інтеграції зовнішніх систем: ::

* [*] Реалізовано можливість додавати нові емулятори для інтеграції зовнішніх систем.

* [*] Додано правила валідації регламенту.

* [*] Додано етап для імпорту mappings до пайплайну *registry-regulations*.

* [*] Додано `network-policy` для взаємодії з реєстровим WM-сервісом.
====

== Єдиний URL для Кабінету посадової особи та інструменту Redash

[TIP]
====
Єдиний URL для Redash: ::

* [*] Винесено Redash Viewer за основний KONG API-шлюз за шляхом `/reports`.

Налаштування Redash Viewer: ::

* [*] Налаштовано Redash Viewer використовувати Kong DNS.

* [*] Налаштування маршрутизації в React для видачі статики `/static` за context path-ом `REDASH_ROUTE_PREFIX`.

Налаштування Redash Admin: ::

* [*] Винесено реєстровий адміністративний ендпоінт Redash Admin під Kong API Gateway.
====

[NOTE]
====
* [*] Видалено функціональність по використанню власних DNS для Redash Viewer.

* [*] Видалено окреме налаштування DNS в control-plane-console для Redash.
====

== Зв'язок зі службою підтримки при виникненні некритичних помилок у Кабінетах користувачів

[TIP]
====
* [*] Додано можливість отримання ідентифікатора трасування (*Trace ID*) при виникненні некритичних помилок на інтерфейсах користувачів.

* [*] Додано можливість скопіювати Email та зв'язатися зі службою підтримки при виникненні некритичних помилок.

* [*] Створено попереджувальне вікно нотифікацій, яке відображає інформацію про помилку.

* [*] Додано відображення нотифікації у Кабінетах користувачів (посадової особи, отримувача послуг та адміністратора регламенту).
====

== Розгортання демо-реєстру із референтними прикладами

[TIP]
====
* [*] Реалізовано можливість розгорнути демо-реєстр із референтними прикладами моделювання регламенту, зокрема бізнес-процесів, UI-форм, схем моделі даних тощо.

* [*] Додано пакування _consent-data_ як додаткового репозиторію Gerrit в Інсталері.

* [*] Додано версіонування по гілці у _consent-data_.

* [*] Адаптовано пайплайн публікації для можливості використання внутрішніх посилань до `nexus` у liquibase-файлах моделі даних.

* [*] Змінено для розгортання Nexus `basePath` CICD2-кластера (узгоджено зі значенням для Envone-кластера).

* [*] Додано сервіс для nexus для використання порту 80 (назва сервісу -- `artifactory`).
====

[NOTE]
====
* [*] Переведено _consent-data_ на використання внутрішніх посилань до `nexus` у liquibase-файлах моделі даних.

* [*] Переведено `empty-registry-reg` template на використання внутрішніх посилань до nexus у liquibase-файлах моделі даних.

* [*] Оновлено структуру регламенту _consent-data_ для розділення на unit та complex референтні приклади.
====

== Кешування JWT-токенів при взаємодії з іншими системами

[TIP]
====
Кешування тимчасових авторизаційних JWT-токенів: ::

* [*] Кешування тимчасових авторизаційних JWT-токенів, отриманих в рамках взаємодії із зовнішніми системами, згідно з визначеним специфікацією терміном дії у клеймі "exp".

* [*] Кешування тимчасових авторизаційних JWT-токенів, отриманих в рамках взаємодії із зовнішніми системами через "Універсальний REST-конектор", згідно з визначеним специфікацією часом дії у клеймі "exp".

Кешування тимчасових авторизаційних JWT-токенів для відправки push-повідомлень: ::

* [*] Кешування тимчасових авторизаційних JWT-токенів, отриманих в рамках взаємодії з "Дією" при обміні push-повідомленнями, згідно з визначеним специфікацією терміном дії у клеймі "exp".

* [*] Винесено логіку по кешуванню токена доступу в окремий клас.
====

==  Управління обмеженнями на завантаження цифрових документів та можливість скриптування завантаження та вивантаження файлів

[TIP]
====
Завантаження цифрових документів: ::

* [*] Додано можливість скриптування завантаження цифрових документів, завантажених користувачами або отриманих із зовнішніх систем, у межах виконання бізнес-процесу.

* [*] Розроблено JUEL-функцію `load_digital_document()`.

Отримання метаданих: ::

* [*] Розроблено внутрішній ендпоінт для вивантажування файлів із сервісу цифрових документів.

* [*] Розроблено JUEL-функцію `get_digital_document_metadata()` для отримання метаданих цифрових документів у рамках бізнес-процесу.

* [*] Додано розроблену JUEL-функцію для вивантажування файлу в автопідказки Groovy в адміністративному порталі.

* [*] Розроблено референтний приклад з використанням двох JUEL-функцій для роботи з файлами.

Збереження файлів у сховище: ::

* [*] Додано службову JUEL-функцію `save_digital_document()` для скриптування збереження файлів, які були сформовані або вивантажені з зовнішніх систем, у сховище цифрових документів в рамках бізнес-процесу.

* [*] Розроблено внутрішній ендпоінт для збереження файлу до Сервісу цифрових документів.

* [*] Додано розроблену JUEL-функцію для збереження файлу в автопідказки Groovy в адміністративному порталі.

Налаштування обмежень розмірів файлів: ::

* [*] Додано можливість налаштовувати обмеження на розмір файлів цифрових документів, які завантажуються до реєстру.

* [*] Додано параметри до конфігурації сервісу для встановлення обмежень на розмір файлів.

* [*] Виконано валідацію розмірів файлів при завантаженні та редагуванні компонента на формі.

Застосування обмежень на завантаження файлів: ::

* [*] Додано обмеження на максимальний розмір файлів цифрових документів, завантажених користувачами через UI-форми, налаштовані на рівні конфігурації реєстру.

* [*] Замінено використання параметра `max-remote-file-size-mb` на `digitalDocuments.maxFileSize`.

* [*] Додано механізм перевірки розширення файлу, завантаженого за віддаленою адресою, на доступність.
====

== Керування розкладом реплікації об'єктів S3 через Control Plane

[TIP]
====
Керування розкладом реплікації об'єктів S3 через Control Plane: ::

* [*] Імплементовано керування розкладом реплікації (бекапування) об'єктів в S3.

* [*] Додано керування розкладом у Control Plane.

* [*] Налаштовано передачу до пайплайну створення резервних копій S3-бакетів значення з Vault.

Редагування внесених даних місця зберігання реплікації об'єктів в S3: ::

* [*] Імплементовано можливість редагувати внесені дані місця зберігання реплікації (бекапування) об'єктів в S3.
====

== Інструкція з ручного перенесення реєстру з одного інстансу на інший

[TIP]
====
* [*] Розроблено детальну покрокову інструкцію щодо правильного перенесення реєстру з одного екземпляра на інший.
====

////
