= Підсистема управління секретами та шифруванням

== Загальний опис

Підсистема безпечного зберігання чутливої інформації та контролю доступу до токенів, паролів, сертифікатів та ключів шифрування
Платформи та Реєстрів.

== Функції підсистеми

* Зберігання токенів, паролів, сертифікатів
* Надання підсистемі моделювання регламенту реєстру ключів шифрування
* Контроль доступу до чутливої інформації збереженої в підсистемі

== Технічний дизайн підсистеми

image::architecture/platform/operational/secret-management/secret-management.drawio.svg[width=600,float="center",align="center"]

_Підсистема управління секретами та шифруванням_ складається з сервісу управління секретами та шифруванням HashiCorp Vault.

[NOTE]
--
Коли сервер Vault запускається, він завжди знаходиться в запечатаному (sealed) стані та не може розшифрувати дані що зберігаються в ньому.
Перед виконанням будь-якої операції з Vault, його необхідно розпечатати (unseal) створивши основний ключ, необхідний для
розшифрування шифрувального ключа.
Детальніше https://developer.hashicorp.com/vault/docs/concepts/seal[Seal/Unseal].
--

В Платформі _HashiCorp Vault_ розпечатується автоматично та для виконання цієї операції використовує _Сервіс управління секретами Платформи_ підсистеми
обслуговування Платформи що виступає в ролі Transit Engine. Детальніше про операцію https://developer.hashicorp.com/vault/tutorials/auto-unseal/autounseal-transit[auto-unseal with transit engine].

== Складові підсистеми

|===
|Назва компоненти|Namespace|Deployment|Походження|Репозиторій|Призначення

|_Сервіс управління секретами та шифруванням_
|`user-management`
|`hashicorp-vault`
|3rd-party
|https://github.com/epam/edp-ddm-platform-vault[github:/epam/edp-ddm-platform-vault]
|Інструмент для безпечного управління секретами та захисту доступу до конфіденційної інформації в обчислювальних середовищах.

|_Сервіс управління сертифікатами_
|`cert-manager`
|`cert-manager`
|3rd-party
|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/infrastructure/service-mesh[gerrit:/mdtu-ddm/infrastructure/service-mesh]
|Інструмент керування сертифікатами та видавцями сертифікатів як типами ресурсів у кластерах Kubernetes та OKD. Використовується підсистемою трасування запитів.

|===

== Технологічний стек

При проектуванні та розробці підсистеми, були використані наступні технології:

* xref:arch:architecture/platform-technologies.adoc#vault[HashiCorp Vault]
* xref:arch:architecture/platform-technologies.adoc#cert-manager[cert-manager]

== Атрибути якості підсистеми

=== _Security_
Підсистема використовує стійкі алгоритми шифрування для зберігання чутливих даних та реалізує надійний контроль доступу для них.

=== _Scalability_
Підсистема розроблена з урахуванням горизонтального та вертикального масштабування, що дозволяє враховувати зростаючі
навантаження та реагувати на них. Підсистема підтримує масштабування що забезпечується Платформою оркестрації контейнерів.

[TIP]
--
Детальніше можна ознайомитись в розділі xref:arch:architecture/container-platform/container-platform.adoc[]
--

=== _Observability_
Підсистема записує детальну інформацію про спроби аутентифікації, отримання секретів та інші операції, що дозволяє
дотримуватися вимог відповідності.

Також, підсистема управління користувачами та ролями підтримує журналювання вхідних запитів та збір метрик продуктивності
для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--
