:toc-title: ЗМІСТ
:toc: auto
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Права доступу до аналітичних даних

== Загальний опис
Одним з елементів механізму розмежування прав доступу до даних аналітичної БД є визначення переліку представлень (**views**), доступних для кожної зі створених аналітичних ролей у базі даних.

Цей перелік визначається моделювальником даних через додатковий XML-шаблон для Liquibase (_детальніше -- див. розділ xref:#xml-templates[]_).

Після публікації звітності, моделювальник регламенту має визначити відповідно бізнес-логіки реєстру, які ролі й до яких звітів матимуть доступ (_детальніше -- див. розділ xref:#reports-rbac[]_).

== Передумови
Для видачі або відкликання прав запита даних із представлень для певної ролі, мають виконуватися наступні умови:

* Роль, для якої надається доступ, має існувати на рівні аналітичної бази даних.
* Представлення, доступ до якого надається, має існувати на рівні аналітичної бази даних.

Порушення цих передумов генеруватиме помилку.

[#xml-templates]
== Налаштування доступу до аналітичних представлень

=== Теги доступу до певних аналітичних представлень

Наступна конструкція надаватиме право запита даних із представлень `registry_data_v` та `registry_info_v` для ролі `analytics_officer_level_1`, а також заборонятиме доступ до цих самих представлень для ролі `analytics_officer_level_2`.

.XML-шаблон зміни прав доступу для аналітичних ролей
====
[source, xml]
----
<changeSet author="registry owner" id="grant/revoke analytics rights">
    <ext:grant>
        <ext:role name="analytics_officer_level_1">
            <ext:view name="registry_data"/>
            <ext:view name="registry_info"/>
        </ext:role>
    </ext:grant>
    <ext:revoke>
        <ext:role name="analytics_officer_level_2">
            <ext:view name="registry_data"/>
            <ext:view name="registry_info"/>
        </ext:role>
    </ext:revoke>
</changeSet>
----
====
Результатом виконання зазначеного шаблону Liquibase є згенерований нижче SQL-синтаксис, що містить DCL-оператори для визначення доступу до даних.

.Приклад згенерованого SQL-синтаксису для зміни прав доступу для аналітичних ролей
[source, xml]

[source, sql]
----
GRANT SELECT ON registry_data_v TO analytics_officer_level_1;
GRANT SELECT ON registry_info_v TO analytics_officer_level_1;

REVOKE SELECT ON registry_data_v FROM analytics_officer_level_2;
REVOKE SELECT ON registry_info_v FROM analytics_officer_level_2;
----

TIP: За детальною інформацією щодо створення моделі даних за допомогою шаблонів Liquibase зверніться до сторінки xref:data-modeling/data/physical-model/liquibase-ddm-ext.adoc[].

=== Теги доступу до усіх представлень

Якщо певна роль потребує доступу до всіх наявних аналітичних представлень, то за допомогою тегів *`grantAll`* та *`revokeAll`* є можливість надати та анулювати права на запит усіх даних, присутніх у представленнях репліки БД.

IMPORTANT: Ці теги вимагають застосування атрибута *`runAlways="true"*` на рівні changeset Liquibase. Якщо вказати значення *`false`*, то тег не працюватиме, і в результаті повернеться помилка. Якщо не встановити жодного значення для атрибута, то буде використане значення за замовчуванням, що також призведе до помилки.

.XML-шаблон для надання/видалення прав доступу до всіх аналітичних даних
====
[source, xml]
----
<changeSet author="registry owner" id="grant all" context="sub" runAlways="true">
    <ext:grantAll>
        <ext:role name="analytics_officer_level_1"/>
    </ext:grantAll>
    <ext:revokeAll>
        <ext:role name="analytics_officer_level_2"/>
    </ext:revokeAll>
</changeSet>
----
====

Така конструкція має виконати DCL-оператори надання прав запита даних по кожному з представлень, що існують в аналітичній БД, для ролі `analytics_officer_level_1` і анулювання таких прав для ролі `analytics_officer_level_2`.

[NOTE]
====
Усі набори змін (changesets) виконуються по черзі. Якщо додати нове аналітичне представлення після того, як всі попередні зміни виконалися, то воно створиться пізніше за інші, й, відповідно, не матиме потрібних прав.

Тому, щоб не було проблем із правами доступу до аналітичних даних, рекомендуємо завжди додавати зміни, що стосуються прав доступу, в кінець файлу, після створення усіх інших змін.

Іншими словами -- спочатку створіть усі Search Conditions, а вже потім надайте необхідні права доступу до них.
====

[#reports-rbac]
== Розмежування доступу до звітів на рівні регламенту

Для того, щоб налаштувати доступ до звітів Redash для кількох ролей, необхідно визначити окрему папку для кожної ролі в теці *_reports_* регламенту реєстру.

Дашборди та запити у кожній папці повинні мати _унікальні назви_, щоб уникнути перезаписування. Наприклад, можна додати префікс до назви дашборду, щоб відрізняти його від інших:

* `"name": "officer-level-1. Тестовий дашборд-1"`;
* `"name": "officer-level-2. Тестовий дашборд-1"`;

+
У цьому випадку показано 2 однакові (за `id`) дашборди, але з різними іменами (`name`) шляхом додавання префіксів.

Теки повинні відповідати ролям користувачів, для яких надається доступ до дашбордів (наприклад, `officer`, `officer-level-1`, `officer-level-2` тощо).

Важливо також впевнитися, що назви папок відповідають назвам ролей користувачів, які мають доступ до відповідних дашбордів. Ролі користувачів визначаються у сервісі Keycloak, у реалмі `*<назва-вашого-реєсру>-officer*`, тому рекомендується перевірити, що назви папок точно відповідають назвам ролей, які призначені для доступу до цих даних.

[TIP]
====
Детальніше про ролі користувачів -- див. на сторінці
xref:registry-admin/create-users/manual-user-creation.adoc[].
====

Якщо надати доступ декільком ролям до звітів з однаковими назвами звіту або запита, то в результаті одна з ролей переміститься до архіву і більше не буде показуватися в *`redash-viewer`*, а для іншої ролі звіт не показуватиметься.

Так відбувається саме через механізм оновлення звітів: ::

. Перед публікацією звіту знаходиться його попередня версія у базі за його назвою і архівується.

. Далі публікується оновлений звіт.

Пошук старого звіту проходить незалежно від ролі, для якої повинен бути опублікований новий звіт.

[TIP]
====
Припустимо, що для ролі `"officer_level_1"` додається новий звіт `"registry_data"`, хоча у ролі `"officer_level_2"` звіт з такою самою назвою вже існує. То для ролі `"officer_level_2"` звіт зникне (архівується, наче, це стара версія) і публікується новий звіт для ролі `"officer_level_1"`.
====

.Структура каталогу звітів reports з розмежуванням доступів до звітів за ролями представлено нижче.
====
[plantuml, structure, svg]
----
@startsalt
{
{T

++= <&folder> <b>reports</b>
+++ <&folder> officer-level-1
++++ <&folder> queries
++++++ <&file> queries.json
+++++ <&file> test1.json
+++++ <&file> test2.json

+++ <&folder> officer-level-2
++++ <&folder> queries
++++++ <&file> queries.json
+++++ <&file> test1.json
+++++ <&file> test2.json
+++++ <&file> test3.json

+++ <&folder> role-3
++++ <&folder> queries
++++++ <&file> queries.json
+++++ <&file> test4.json
+++++ <&file> test5.json
+++++ <&file> test6.json

++ <&folder> <b>roles</b>
+++ <&file> citizen.yaml
+++ <&file> officer.yaml
}
}
@endsalt
----
====

[TIP]
====
* *officer-level-1, officer-level-2, role-3* -- назва ролі, що зазначена в налаштуваннях файлів _roles/citizen.yaml_ або _roles/officer.yaml_;

* *test1.json, test2.json, test3.json* -- назва звітів Redash, де в налаштуваннях самого файлу параметр `name` містить назву звіту (тут -- `registry_data`) та назву запита в параметрі `query.name` (тут -- `View all report registry_data`).
+
.Зміст файлу зі звітом (дашбордом)
[%collapsible]
=====
[source, json]
----
{
  "id": 3,
  "name": "registry_data",
  "slug": "test",
  "created_at": "2022-07-07T10:57:27.718",
  "updated_at": "2022-07-07T10:57:54.956",
  "tags": [],
  "widgets": [
    {
      "text": "",
      "options": {
        "parameterMappings": {},
        "isHidden": false,
        "position": {
          "autoHeight": true,
          "sizeX": 3,
          "sizeY": 32,
          "maxSizeY": 1000,
          "maxSizeX": 6,
          "minSizeY": 1,
          "minSizeX": 2,
          "col": 0,
          "row": 0
        }
      },
      "width": 1,
      "dashboard_id": 3,
      "visualization_id": null,
      "visualization": {
        "query_id": null,
        "name": "Table",
        "type": "TABLE",
        "description": "",
        "options": {},
        "query": {
          "id": 9,
          "data_source_id": 1,
          "name": "View all report registry_data",
          "query": "select * from registry.report_koatuu_test1_v;",
          "description": null,
          "options": {
            "parameters": []
          },
          "draft": false
        }
      }
    }
  ],
  "options": null,
  "is_draft": false
}
----
=====

* *citizen.yaml, officer.yaml* -- файли з переліком ролей для користувачів реєстру.
====

[TIP]
====
Додаткову інформацію щодо доступу до даних та розмежування прав ви можете переглянути за посиланням:

* xref:registry-develop:data-modeling/data/physical-model/liquibase-ddm-ext.adoc#create-analytical-views[Керування аналітичними представленнями]
* xref:registry-develop:data-modeling/reports/data-analytical-reports-creation.adoc#_доступ_до_даних_та_розмежування_прав[Доступ до даних та розмежування прав]
====
