= Розширення функціональності Liquibase через зовнішній модуль Liquibase DDM Extension

== Вступ

Через складні вимоги до архітектури Платформи, використання стандартної функціональності Liquibase не покриває всі потреби при роботі зі структурою даних.

Функціональність Liquibase було розширено за допомогою зовнішнього модуля `**liquibase-ddm-ext**`.

До розширення функціональності додатку Liquibase відносяться модулі, які забезпечують роботу з додатковими тегами (в термінології Liquibase - _change types_) XML-шаблону Liquibase, що відповідають за:

- створення таблиць з підтримкою історичності даних;
- створення користувацьких типів даних;
- створення простого критерію пошуку (Simple Search Condition);
- створення критерію пошуку (Search Condition);
- створення типу зв'язку "багато до багатьох" (many-to-many).

:sectnums:

== Теги створення таблиць

Назва change type: `<createTable>` `<ext:historyFlag>`.

Цей тег надає можливість створити таблицю або дві таблиці:

- з історичними даними;
- із поточними даними.

CAUTION: В рамках процесу верифікації регламенту, флаг `historyFlag` зі значенням `true` вимагатиметься для всіх тегів `createTable`. Тому при створенні таблиці необхідно вказувати відповідне значення `historyFlag="true"`. Таким чином буде додатково згенерована історична таблиця, і для кожної з таблиць буде згенеровано свій специфічний набір службових полів.

TIP: За детальною інформацією щодо створення таблиць зверніться до секції xref:liquibase-changes-management-sys-ext.adoc#create-table-hst[Схема моделювання таблиць та функція підтримки історичності] відповідного документа.

== Тег створення користувацького типу даних Domain

Назва change type: `<createDomain>`.

Цей тег надає можливість створити користувацький тип даних з перевіркою на певні умови.

TIP: За детальною інформацією щодо створення типу даних `Domain` зверніться до секції xref:liquibase-changes-management-sys-ext.adoc#create-type-domain[Схема створення типу даних Domain] відповідного документа.

== Тег створення користувацьких типів даних ENUM та Composite

Назва change type: `<createType>`.

Цей тег надає можливість створити **два нових типи даних**:

1) перелічувальний тип даних (`ENUM`);

2) композитний тип даних (`Composite`).

TIP: За детальною інформацією щодо створення типу даних `ENUM` та `Composite` зверніться до секції xref:liquibase-changes-management-sys-ext.adoc#create-type-enum-composite[Cхема створення типів даних ENUM та Composite] відповідного документа.

== Створення простого критерію пошуку

Назва change type: `<createSimpleSearchCondition>`.

Цей тег надає можливість створити простий критерій пошуку, а саме створити для однієї таблиці відбиток даних (view) та індекс за вказаним полем пошуку.

WARNING: Якщо вказати створення індексу без вказання поля пошуку, то буде згенерована помилка.

TIP: За детальною інформацією щодо створення простого критерію пошуку зверніться до секції xref:liquibase-changes-management-sys-ext.adoc#create-sc-simple[XML-шаблон дизайну простого критерію пошуку (Сценарій 1)] відповідного документа.

== Створення критерію пошуку

Назва change type: `<createSearchCondition>`.

Цей тег надає можливість створити критерій пошуку, що виконує набір наступних функцій:

- створює відбиток даних (view) за декількома таблицями та зв'язками між ними;
- для кожного поля пошуку створює свій індекс.

WARNING: Якщо вказати створення індексу без вказання поля пошуку, то буде згенерована помилка.

WARNING: Перший тег `<ext:condition>` в умові `<ext:where>` не повинен містити атрибуту `logicOperator`, всі інші теги `<ext:condition>` — повинні;

WARNING: Перший тег `<ext:condition>`, як і всі інші, в умові `<ext:join>` повинен містити атрибут `logicOperator`;

WARNING: Атрибут `logicOperator` приймає значення _and_ і _or_.

WARNING: Якщо тег `<ext:condition>` вкладений в інший, то вони обгортаються дужками.

**Оператор приймає наступні значення:**

[options="header"]
|=======================================================================
|Значення| Пояснення                       |Символ (Unicode)| Коментар
|`eq`      |**eq**uals                       |=               |
|`ne`      |**n**ot **e**qual                |<>              |
|`gt`      |**g**reater **t**han             |>               |
|`ge`      |**g**reater than or **e**quals to|>=              |
|`lt`      |**l**ess **t**han                |<               |
|`le`      |**l**ess than or **e**quals to   |<=              |
|`in`      |                                 |                |
|`notIn`   |                                 |                |
|`isNull`  |is null                          |                |Якщо значення (value) = `true`, то перевірка колонки _is null_; якщо значення (value) = `false`, то перевірка колонки _is not null_.
|`similar` |similar                          |~               |
|=======================================================================

- Value - якщо потрібно передати текстове значення, то потрібно це значення обгорнути в одинарні лапки;
- `<ext:function>` — дозволяє використовувати агрегатні функції (`min()`, `max()`, `avg()`, `count()`, `sum()`), при цьому поля таблиці, які використовуються в цих функціях, вилучаються з виводу (`SELECT`). Всі інші поля включаються в групування (`GROUP BY`).

[TIP]
====
За детальною інформацією щодо сценаріїв використання критеріїв пошуку зверніться до наступних секцій відповідного документа:

- xref:liquibase-changes-management-sys-ext.adoc#create-sc-uc2[XML-шаблон дизайну критерію пошуку (Сценарій 2)];
- xref:liquibase-changes-management-sys-ext.adoc#create-sc-uc3[XML-шаблон дизайну критерію пошуку (Сценарій 3)];
- xref:liquibase-changes-management-sys-ext.adoc#create-sc-uc4[XML-шаблон дизайну критерію пошуку (Сценарій 4)];
- xref:liquibase-changes-management-sys-ext.adoc#delete-sc[XML-шаблон видалення критерію пошуку].
====
== Створення типу зв'язку "багато до багатьох"

Назва change type: `<createMany2Many>`.

Цей тег надає можливість створити особливий тип зв'язку "багато до багатьох", що виконує наступні функції:

- створює відбиток даних (view), розгортаючи масив у рядки;
- створює індекс.

TIP: За детальною інформацією щодо створення зв'язків між таблицями зверніться до розділу xref:liquibase-changes-management-sys-ext.adoc#create-many2many[Схема моделювання зв'язків між сутностями в БД] відповідного документа.