= Registry regulations structure
include::platform:ROOT:partial$templates/document-attributes/default-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

The system deployment relies on one or multiple regulations.

Configuring and deploying registry regulations involves changing a set of entities/elements within the regulations, which an administrator typically does.

CI/CD tools automate the deployment of the registry regulations. The *`MASTER-Build-registry-regulations`* Jenkins pipeline and other related pipelines are responsible for deploying the regulations.

The registry regulations directory has a well-defined structure. The following diagram shows a typical regulations structure.

._Typical registry regulations structure_
[%collapsible]
====
[plantuml]
----
@startsalt
{
{T
+ <&folder> registry-regulations

++ <&folder> bp-auth
+++ <&file> role.yml
+++ ...

++ <&folder> bp-trembita
+++ <&file> config.yml
+++ ...

++ <&folder> bpmn
+++ <&file> process.bpmn
+++ ...

++ <&folder>data-model
+++ <&folder> data-load
++++ <&file> dict.csv
++++ ...
+++ <&file> model.xml
+++ ...

++ <&folder> dmn
+++ <&file> rule.dmn

++ <&folder> excerpts
+++ <&file> index.html.ftl
+++ ...

++ <&folder> excerpts-csv
+++ <&file> excerpt.csv
+++ ...
++ <&folder> excerpts-docx
+++ <&file> excerpt.docx
+++ ...

++ <&folder> forms
+++ <&file> form.json
++++ ...

++ <&folder> global-vars
+++ <&file> global-vars.yml

++ <&folder> mock-integrations
+++ <&file> mock-1.json
+++ <&file> mock-2.json
+++ ...

++ <&folder> notifications
+++ <&folder> email
++++ <&folder> notification-template
+++++ <&file> notification.ftlh
+++++ <&file> notification.yml
++++ <&folder> channel-confirmation
+++++ <&file> notification.ftlh
+++++ <&file> notification.yml
+++ <&folder> inbox
++++ <&file> notification.ftl
++++ <&file> notification.yml

++ <&folder> reports
+++ <&file> report.json
+++ ...

++ <&folder> roles
+++ <&file> role.yml
+++ ...

++ <&folder> settings
+++ <&file> settings.yml

+ <&file> settings.yaml

}
}
@endsalt
----
====

[%collapsible]
._Regulations structure explained_
====


.Regulations structure explained
[width="100%",cols="19%,19%,62%",options="header"]
|===

| Regulations
| Directory/file
| Description

|_registry-regulations_
|
| A top-level directory containing nested directories with entities of the registry regulations.

|
| _bp-auth_
a| A directory houses YAML files used for authorizing users in business processes. The associated Keycloak realms are:

- `citizen`: represents the service recipient;
- `officer`: denotes the service provider;
- `external-system`: refers to an external system or registry.

|
| _bp-grouping_
| A directory containing the configuration file _bp-grouping.yaml_. This file's settings group the business processes of the registry.

|
| _bp-trembita_

a| A directory containing configuration files for interactions with external systems and services through SOAP and REST interfaces.

[NOTE,caption=UA-specific]
The _bp-trembita_ settings relate to the Ukrainian implementation in part of the SOAP connection. They may not apply or function as described in other contexts or regions.
Please consult the local guidelines or documentation if you are implementing this outside of Ukraine.

|
|_bpmn_
|A directory containing business process diagrams in ._bpmn_ format (a type of XML).

|
|_data-model_
|A directory containing data model diagrams for deploying the database and API representations. It also includes CSV datasets used to populate tables with reference data.

|
| _dmn_
|A directory containing decision rules modeled in ._dmn_ format (a type of XML).

|
|_excerpts_
|A directory containing templates for PDF excerpts.

|
|_excerpts-csv_
|A directory containing templates for CSV excerpts.

|
|_excerpts-docx_
|A directory containing templates for DOCX excerpts.

|
|_forms_
|A directory containing UI forms for business processes modeled in JSON format.

|
|_global-vars_
|A directory containing global variables for the registry business processes.

|
| _mock-integrations_
|A directory containing modeled templates for external API simulation in _.json_ format.

|
|_notifications_
|A directory containing message templates for `email` and `inbox` notifications.

|
|_reports_
|A directory containing generated analytical reports (queries and dashboards) in JSON format.

|
|_roles_
a|A directory containing configuration files for registry roles.

* _officer.yml_ defines officers of various ranks -- service providers.
* _citizen.yml_ defines citizens -- service recipients.

|
|_settings_
|A directory containing the registry's general settings such as full name, system name of the registry, and so on.

|
|_settings.yaml_
|A configuration file containing the system settings of the registry and several services.

|===
====

[TIP]
====
For details on the registry regulations and its deployment, see xref:arch:architecture/registry/administrative/regulation-management/registry-regulation/registry-regulation.adoc[].
====