openapi: 3.0.3
info:
  title: Excerpts management service
  description: This document describes REST API of 'Excerpts management service'
  version: "1.0"
tags:
- name: excerpts-service-api
  description: Excerpts management service Rest API
paths:
  /excerpts:
    post:
      tags:
      - excerpts-service-api
      summary: Create an excerpt generation record
      description: |-
        ### Endpoint purpose:
          Creates an excerpt generation record by sending required parameters as JSON data. Returns the UUID of the generated excerpt, which can be used to access the generated document.
         ### Authorization:
         This endpoint requires valid user authentication. To access this endpoint, the request must include a valid access token in the _X-Access-Token_ header, otherwise, the API will return a _401 Unauthorized_ status code
      operationId: generate
      parameters:
      - name: X-Access-Token
        in: header
        description: Token used for endpoint security
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExcerptEventDto'
            example:
              excerptType: subject-laboratories-accreditation-excerpt
              requiresSystemSignature: true
              excerptInputData:
                subjectId: <UUID>
        required: true
      responses:
        "200":
          description: OK. Excerpt ID successfully generated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExcerptEntityId'
              example:
                excerptIdentifier: <UUID>
        "400":
          description: Bad Request. Invalid excerpt type or incorrect request parameters.
          content:
            application/json: {}
        "401":
          description: Unauthorized. Missing or invalid access token or digital signature.
          content:
            application/json: {}
        "500":
          description: Internal Server Error. Error occurred during the excerpt generation
            process.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
  /excerpts/{id}:
    get:
      tags:
      - excerpts-service-api
      summary: Retrieve an excerpt file
      description: "### Endpoint purpose:\n This endpoint allows users to download\
        \ an excerpt file based on the provided excerpt ID. Returns the excerpt file\
        \ as a downloadable resource.\n ### Authorization:\n This endpoint requires\
        \ valid user authentication. To access this endpoint, the request must include\
        \ a valid access token in the _X-Access-Token_ header, otherwise, the API\
        \ will return a _401 Unauthorized_ status code. \n ### Validation: During\
        \ excerpt creation, the system performs validation of the digital signature\
        \ if enabled, and validation of the template associated with the excerpt type.\
        \ If these validations fail, an exception is thrown. If all input data is\
        \ correct, a new excerpt is created and its ID is returned in the response.\
        \ \n ### Validation: During excerpt creation, the system performs validation\
        \ of the digital signature if enabled, and validation of the template associated\
        \ with the excerpt type. If these validations fail, an exception is thrown.\
        \ If all input data is correct, a new excerpt is created and its ID is returned\
        \ in the response."
      operationId: retrieve
      parameters:
      - name: X-Access-Token
        in: header
        description: Token used for endpoint security
        required: true
        schema:
          type: string
      - name: excerptId
        in: path
        description: The UUID of the excerpt to retrieve
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: securityContext
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/SecurityContext'
      responses:
        "200":
          description: OK. Excerpt file successfully retrieved.
          content:
            application/octet-stream: {}
        "400":
          description: Bad Request. Invalid request parameters or data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
        "401":
          description: Unauthorized. Missing or invalid access token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
        "500":
          description: Internal Server Error. Error occurred while retrieving the
            excerpt.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
  /excerpts/{id}/status:
    get:
      tags:
      - excerpts-service-api
      summary: Get the status of an excerpt generation
      description: "### Endpoint purpose: \n This endpoint is used for getting the\
        \ status of an excerpt generation based on the provided excerpt ID. Returns\
        \ the status of the generation as a JSON object.\n ### Authorization:\n This\
        \ endpoint requires valid user authentication. To access this endpoint, the\
        \ request must include a valid access token in the _X-Access-Token_ header,\
        \ otherwise, the API will return a _401 Unauthorized_ status code"
      operationId: status
      parameters:
      - name: X-Access-Token
        in: header
        description: Token used for endpoint security
        required: true
        schema:
          type: string
      - name: excerptId
        in: path
        description: The UUID of the excerpt to retrieve
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK. Excerpt generation status successfully retrieved.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusDto'
              example:
                status: FAILED
                statusDetails: Technical description of the error
        "400":
          description: Bad Request. Invalid request parameters or data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
        "401":
          description: Unauthorized. Missing or invalid access token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
        "404":
          description: Not Found. No generation status found for the provided excerpt
            ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
        "500":
          description: Internal Server Error. Error occurred while retrieving the
            generation status.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedErrorResponse'
components:
  schemas:
    ExcerptEventDto:
      required:
      - excerptType
      type: object
      properties:
        recordId:
          type: string
          format: uuid
        excerptType:
          type: string
        excerptInputData:
          type: object
          additionalProperties:
            type: object
        requiresSystemSignature:
          type: boolean
    ExcerptEntityId:
      type: object
      properties:
        excerptIdentifier:
          type: string
          format: uuid
    DetailedErrorResponse:
      type: object
      properties:
        traceId:
          type: string
        code:
          type: string
        details:
          type: object
    SecurityContext:
      type: object
      properties:
        accessToken:
          type: string
        digitalSignature:
          type: string
        digitalSignatureDerived:
          type: string
    StatusDto:
      type: object
      properties:
        status:
          type: string
          enum:
          - IN_PROGRESS
          - FAILED
          - COMPLETED
        statusDetails:
          type: string
