== Версії регламенту

Модуль для організації роботи з версіями регламенту.

.Виділяються наступні версії регламенту:
- Майстер-версія регламенту - це поточна версія регламенту, що розгорнута на платформі
- Версія-кандидат регламенту - це версія яка є кандидатом на те, щоб стати майстер версією регламенту

.Надає наступний функціонал:
- Отримання інформації про майстер-версію регламенту
- Отримання списку всіх версій-кандидатів регламенту
- Отримання інформації про версію-кандидат регламенту
- Створення нової версії-кандидата
- Оновлення версії-кандидату змінами з майстер-версії
- Застосування версії-кандидату до майстер-версії
- Відхилення версії-кандидату

=== Отримання інформації про майстер-версію регламенту

Повертає інформацію про останню застосовану версію-кандидата. Якщо жодної версії-кандидата не було застосовано повертає пустий об'єкт.

.Діаграма послідовності отримання інформації про майстер-версію регламенту
[plantuml]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/versions/get-master-version.puml[]
----

=== Отримання списку всіх версій-кандидатів регламенту

Повертає список всіх версій-кандидатів регламенту: їх ідентифікатори, назви та опис.

.Діаграма послідовності отримання списку всіх версій-кандидатів регламенту
[plantuml]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/versions/get-version-candidates.puml[]
----

=== Отримання інформації про версію-кандидат регламенту

Повертає інформацію про версію-кандидата за ідентифікатором.

.Діаграма послідовності отримання інформації про версію-кандидат регламенту
[plantuml]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/versions/get-version-candidate.puml[]
----

=== Створення нової версії-кандидата

Створює нову версію-кандидат та ініціює клонування копії репозиторію для цієї версії-кандидата.

.Діаграма послідовності створення нової версії-кандидата
[plantuml]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/versions/create-version-candidate.puml[]
----

=== Оновлення версії-кандидату змінами з майстер-версії

Оновлює версію-кандидат змінами з майстер-версією якщо у версії-кандидаті не наявні зміни що конфліктують з майстер-версією, через що її не можна застосувати.

.Діаграма послідовності перевірки конфліктів у версії-кандидаті з майстер-версією
[plantuml]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/versions/rebase-version-candidate.puml[]
----

=== Застосування версії-кандидату до майстер-версії

Застосовує версію-кандидат до майстер-версії, після чого ця версія-кандидат стає майстер-версією.

.Діаграма послідовності застосування версії-кандидату до майстер-версії
[plantuml]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/versions/merge-version-candidate.puml[]
----

=== Відхилення версії-кандидату

Відхиляє версію-кандидат, після чого її не можна застосувати до майстер-версії та вона зникає зі списку всіх відкритих версій-кандидатів

.Діаграма послідовності відхилення версії-кандидату
[plantuml]
----
include::arch:partial$architecture/registry/administrative/regulation-management/services/registry-regulation-management/versions/merge-version-candidate.puml[]
----