= Аудит шаблонів витягів

|===
|Назва | Критичність

|<<_ex_01>> |Середня
|<<_ex_02>> |Середня

|===

[#_ex_01]
== EX-01. Набір даних для витягів
IMPORTANT: Критичність: середня

.Опис
В процесі тестування перевіряти витяги з різним набором даних і обсягом наближеним до промислового. В процесі розробки
можуть бути непокриті сценарії з перенесенням елементів шаблону на нову сторінку в залежності від обсягу даних.

.Вплив
* Деякі елементи шаблонів витягів можуть бути неправильно розміщені на сторінці в залежності від обсягу даних.
(наприклад, таблиці)

.Рекомендації
* Перевіряти витяги з різним набором даних і обсягом який призведе до перенесення елементів шаблону на нову сторінку.
* Виправити потенційні помилки і адаптувати шаблони з урахуванням можливого перенесення

[#_ex_02]
== EX-02. Обов'язкові параметри шаблонів витягів
IMPORTANT: Критичність: середня

.Опис
Враховувати обов'язковість за замовчуванням всіх вхідних параметрів для шаблонів витягів.

.Вплив
При запиті на генерацію витягу з бізнес-процесу не буле передавний обов'язковий параметр, то генерація витягу буде зупинена
з помилкою, яку потенційно буде складно ідентифікувати.

.Рекомендації
* Класифікувати вхідні параметри шаблонів витягів на обов'язкові та необов'язкові.
* Для обов'язкових параметрів додати додаткову перевірку в бізнес-процес перед викликом на генерацію витягу.
* Для необов'язкових параметрів врахувати можливість їх відсутності в шаблоні витягу та розглянути значення за
замовчуванням, наприклад, символ "-".
