= Аудит UI-форм бізнес-процесів

|===
|Назва | Критичність

|<<_fr_01>> |Висока
|<<_fr_02>> |Висока
|<<_fr_03>> |Висока
|<<_fr_04>> |Висока
|<<_fr_05>> |Висока
|<<_fr_06>> |Середня
|<<_fr_07>> |Висока
|<<_fr_08>> |Висока
|<<_fr_09>> |Середня
|<<_fr_10>> |Висока

|===

[#_fr_01]
== FR-01. Великі форми
IMPORTANT: Критичність: Висока

.Опис
Робити форми якомога простішими та короткими

.Вплив
* Зниження продуктивності при рендерінгу форми в браузері
* Ускладнення внесення змін до форми розробниками регламенту
* Погіршення користувацького досвіду при заповненні або перегляді форми
* Збільшення ймовірність виникнення системної помилки у користувача при роботі з формою (наприклад, втрата заповнених даних через закінчення сесії користувача)
* Ускладнення тестування форми. Велика кількість тест кейсів, які треба покрити

.Рекомендації
* При внесенні даних, розбивати форму на декілька окремих і робити збір даних поетапно
* При перегляді даних:
** Показувати обмежений набір даних за замовчуванням
** Для перегляду детальної інформації використовувати звіти чи витяги
* Уникати комплексної вкладеності компонентів зі складними зв'язками


NOTE: Детальніше про кращі практики по розробці WEB форм можна ознайомитись https://nngroup.com/articles/web-form-design/[за посиланням]

[#_fr_02]
== FR-02. Lazy load для компонента _Select_
IMPORTANT: Критичність: висока

.Опис
При наявності великої кількості компонентів _Select_ на формі, використовувати _lazy load_ для підвантаження даних по URL.
За замовчуванням компонент _Select_ заздалегідь дістає дані (_eager load_) по URL в наступних випадках:

* При первинному рендерінгу форми
* При зміні в пов'язаному компоненті
* При оновленні користувацького токена (системна поведінка, яка відбувається безумовно незалежно від дій користувача)

.Вплив
* Додаткове навантаження на сервери та мережу
* Збільшення часу рендерінгу форми

.Рекомендації
* Уникати створення великих форм (див. <<_fr_01>>)
* Використовувати _lazy load_ для компонентів _Select_ якщо їх кількість на формі достатньо велика (понад 5)
* Використовувати _eager load_ у випадках, коли це дійсно може покращити користувацький досвід. Наприклад, для першого
компоненту _Select_ на формі, щоб у користувача відразу після рендерінгу форми були необхідні дані для вибору

[#_fr_03]
== FR-03. _Javascript_ логіка в компонентах форми
IMPORTANT: Критичність: висока

.Опис
Конструктор форм дозволяє втілити значну кількість обробки даних та валідацій за допомогою вбудованих можливостей.
Додатково, існує можливість для певного переліку налаштувань (validation, conditional, custom default value)
реалізувати індивідуальну логіку на javascript. Це дозволяє з одного боку гнучко налаштовувати форму, однак, складна
та об'ємна логіка створює приховану складність, яка може призвести до проблем, що важко відлагоджуються або
непередбачуваної поведінки форми.

.Вплив
Підтримка та розвиток складної _javascript_ логіки на рівні моделювання форми стають крайно незручними. Це може призвести
до додаткового часу, витраченого на відлагодження, а також збільшити ймовірність помилок. Особливо це стає актуальним,
коли команда розробників змінюється або проєкт передається на підтримку.

.Рекомендації
* Контроль обсягу використання Javascript. Обмежувати складність _javascript_ логіки в формах. Намагатися зберігати логіку
якомога простішою та більш прямолінійною.
* Використовувати вбудовані можливості конструктора форм для валідації та обробки даних
* Уникати побічних ефектів в місцях використання. Кожна вставка _javascript_ логіки має єдину відповідальність (валідація,
умовне відображення, обробка даних тощо) та не має впливати на інші частини форми

[#_fr_04]
== FR-04. Зовнішні АПІ сервіси в компоненті _Select_
IMPORTANT: Критичність: висока

.Опис
Компонент _Select_ як джерело даних може використовувати зовнішні АПІ сервіси за довільним доменом, наприклад,
як довідник. Додатково існує можливість додавання кук (cookie) домену АПІ сервісу у виклик, який може містить куку
(cookie) для авторизації. Треба узгодити налаштування на такому АПІ сервісі (якщо є можливість впливати на ці
налаштування) та формою, яка виконує цей запит.

NOTE: Безпосередньо отримання авторизаційної кукі (cookie) поза скоупом рішення і не є предметом цього документу.

.Вплив
* Браузер заблокує виконання запиту до АПІ сервісу через CORS політики
* АПІ сервіс заблокує запит через відсутність необхідної Cookie

.Рекомендації
* Якщо АПІ сервіс відкритий і не потребує авторизації:
** В налаштуваннях компонента _Select_ виключити передачу авторизаційної інформації при запиті на АПІ сервіс (параметр
_Add authentication cookies for cross-site requests_ = false)
** Значення заголовка _Access-Control-Allow-Origin_ у відповіді АПІ сервісу повинно мати значення домену кабінету
користувача або вайлкард _*_
* Якщо АПІ сервіс потребує авторизації та рішення припускає наявність кукі (cookie) для авторизації на домен АПІ сервісу
в браузері необхідні наступні умови:
** В налаштуваннях компонента _Select_ додати передачу авторизаційної інформації при запиті на АПІ сервіс (параметр _Add
authentication cookies for cross-site requests_ = true)
** Значення заголовка _Access-Control-Allow-Origin_ у відповіді АПІ сервісу повинно мати значення домену кабінету
користувача (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials[вайлдард _*_
 не допускається])
* Додатково перед виходом в промислове середовище потрібно перевірити налаштування АПІ сервісу та форми та впевнитися, що
вони заздалегідь адаптовані до вимог CORS політик. Наприклад, домен користувача кабінету доданий в налаштування зовнішнього
АПІ сервісу

[#_fr_05]
== FR-05. Компонент карти. Нестандартні тайл-сервери
IMPORTANT: Критичність: висока

.Опис
При використанні нестандартних тайл-серверів для базового шару карти необхідно провести додаткові налаштування
на сервері для оновлення _Content-Security-Policy_ (CSP) заголовка відповіді.

NOTE: На момент написання документа стандартними тайл-серверами вважаються _tile.openstreetmap.org_ та _visicom.ua_.

.Вплив
Без додаткових налаштувань на сервері браузер буде блокувати запити на тайл-сервер і карта не буде працювати.

.Рекомендації
Заздалегідь провести налаштування на відповідному оточенні, якщо відомо, що будуть використовуватися нестандартні
тайл-сервери.

NOTE: На момент написання статті конфігурація _Content-Security-Policy_ (CSP) задається у файлі
_deploy-templates/templates/kong-response-transformer-plugin.yaml_ репозиторію _common-web-app_

[#_fr_06]
== FR-06. Експериментальні компоненти
Критичність: середня

.Опис
Компоненти в конструкторі форм в _Веб-інтерфейсі моделювання регламенту_ розділені по 3 категоріям:

* _Оновлені_: адаптовані компоненти під рішення та дизайн кабінетів. Розробка та тестування цих компонентів підтримується командою розробки платформи
* _Експериментальні_: стандартні компоненти _Form.io_. Не адаптовані під систему. Не підтримуються командою розробки платформи й не тестуються на відповідність вимогам системи
* _Компоненти_: застарілі адаптовані компоненти, які вже не підтримуються командою розробки платформи

При моделюванні форм рекомендується використовувати компоненти з категорії _Оновлені_

.Вплив
* Працездатність форми, яка містить компоненти з категорій _Експериментальні_ та _Компоненти_ не гарантується

.Рекомендації
* Використовувати компоненти з категорії _Оновлені_
* Якщо використання компонентів з інших категорій є обґрунтованим, врахувати всі можливі ризики й приділити тестування
таких форм більшу увагу
* Окремо слід зауважити, що використання компонентів з категорії _Експериментальні_ чи _Компоненти_ з подальшим ручним
виправленням коду і зміни типа на latest, що відповідає оновленому компоненту може призвести до непередбачуваних наслідків
і працездатність не гарантується в такому випадку

[#_fr_07]
== FR-07. Ліміти на критеріях пошуку для компонента _Select_
Критичність: висока

.Опис
При використанні компонента _Select_ з інтеграцію з довідниками через критерії пошуку дата моделі реєстру чи зовнішніми
сервісами завжди вказувати параметр _limit_ в налаштуваннях компонента. В промисловому середовищі кількість даних може
бути набагато більшої, чим у тестовому, тому використання параметра _limit_ дозволить уникнути проблем з продуктивністю.

.Вплив
Велика кількість даних, отримана в компоненті _Select_ з відсутнім параметром ліміту, може призвести до наступних
потенційних проблем:

* Додаткове непотрібне навантаження на реляційну базу даних
* Додаткове непотрібне навантаження на сервіс синхронного управління даними реєстру
* Збільшення часу рендерінгу форми

.Рекомендації
* Задавати параметр _limit_ для компонента _Select_ в мінімально необхідне значення для коректного функціонування форми
* Використання параметра _Disable limiting response_ повинно бути обґрунтоване й у більшості випадків не рекомендується

[#_fr_08]
== FR-08. Математичні обчислення
Критичність: висока

.Опис
Будь-які математичні обчислення (в особливості фінансові), результат виконання яких є достатньо критичним для
функціонування реєстру повинні виконуватися на сервері в рамках DMN таблиць чи бізнес-процесів.

.Вплив
* Результат математичних обчислень, що виконують на стороні клієнта можуть бути скомпрометовані й не можуть вважатися
правдивими
* Компонент _Number_ використовує _Javascript_ тип Number, який не є точним для фінансових обчислень і його використання
для великих чисел може бути небезпечним

.Рекомендації
* Використовувати DMN таблиці чи бізнес-процеси для виконання математичних обчислень
* Для покращення користувацького досвіду та швидшого розуміння результату обчислення користувачем, логіка може бути
продубльована на клієнті, але результат повинен ігноруватися на сервері

[#_fr_09]
== FR-09. Маска на текстовому полі
Критичність: середня

.Опис
Для спрощення вводу даних у компонент текстового поля можна використовувати маску. Маска визначає формат введення даних
у поле. Для коректного передзаповнення полів з маскою, дані повинні відповідати формату маски.

.Вплив
* Користувач не зможе підписати дані форми через помилку валідації на клієнті, якщо текстове поле з маскою не було
передзаповнено коректно і відповідно
бізнес-процес неможливо буде завершити
* Користувач не зможе виконати користувацьку задачу при наступних умовах:
** Текстове поле містить маску
** Текстове поле налаштоване як таке, що не можливо редагувати
** Дані для передзаповнення не відповідають формату маски для текстового поля

.Рекомендації
* На формах, де передбачається використання маски, перевіряти відповідні дані для передзаповнення полів в бізнес-процесі
* Особливу увагу приділяти даним, які були отримані зі сторонніх систем, і які з великою ймовірністю можуть не відповідати
масці
* Розглянути можливість відмови від використання масок. Іноді додаткові зусилля на підтримку масок для даних з різних
джерел можуть бути недоцільними. Також маску можна залишити для вводу даних, але не використовувати її для
передзаповнення

[#_fr_10]
== FR-10. Edit Grid
Критичність: висока

.Опис
При використанні компонента _Edit Grid_ слід враховувати, що наявність складної логіки вкладених компонентів може
суттєво впливати на продуктивність рендерінгу форми в поєднанні з великою кількістю рядків у таблиці. Це однаково
стосується як і режиму для читання, де дані для відображення готуються в бізнес-процесі, так і режиму редагування, де
користувач вносить дані в таблицю.

NOTE: В рамках цього пункту значення в тексті _Таблиця_ та _Edit Grid_ є синонімами.

.Вплив
* Збільшення часу рендерінгу форми через наступні причини:
** Виконання запитів на критерії пошуку для кожного рядка таблиці. Тобто, якщо в таблиці 100 рядків, з 3 селектами, то
буде виконано 300 запитів на критерії пошуку
** Виконання запиту на пошук файлів в _Сервіс цифрових документів_ для кожного рядка таблиці при наявності файлу. Слід
зауважити, що запит зі сторони клієнта виконується 1 раз для таблиці, проте час його виконання буде пропорційно
збільшуватися від кількості файлів через деталі внутрішньої реалізації (складність дорівнює _O(n)_)

.Рекомендації
* Використовувати параметр для оптимізації рендерінгу колонок _Edit Grid_ (Вкладка _Data_, чекбокс
_Optimize column render_). Цей параметр вимикає всі можливості по складній логіці вкладених компонентів (_javascript_ код,
який відповідає за валідацію, умовне відображення, обчислювальне значення, виклики критеріїв пошуку тощо). Тобто, таблиця
буде відображати тільки дані які підготовлені заздалегідь в бізнес-процесі, або додані користувачем. При цьому форма,
яка відповідає за додавання нового елементу в таблицю збереже відповідні можливості.
* Уникати використання файлів в _Edit Grid_ для відображення даних, які були підготовленні в БП. Для перегляду файлів
використовувати детальну картку для окремого запису на окремій формі.
* Використовувати мінімум даних для перегляду в таблиці:
** Зменшити кількість рядків до мінімального допустимого значення. За можливості, розглянути альтернативу у вигляді звітів,
якщо необхідно працювати з усіма даними відповідної таблиці
** Зменшити кількість колонок до мінімально необхідного значення. Як і в рекомендації з файлами, використовувати окрему
форму для перегляду детальної інформації про рядок