= Підсистема журналювання подій аудиту

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Підсистема, призначенням якої є отримання та обробка повідомлень про виникнення значущих подій в системі з їх послідуючою гарантованою фіксацією в журналі аудиту для довготривалого зберігання та аналізу.

== Функції підсистеми

* Фіксація подій операцій над даними реєстру, ініційованих користувачем в рамках виконання бізнес-процесу
* Фіксація подій, важливих для забезпечення захисту системи
* Фіксація загальних подій рівня системи

== Технічний дизайн підсистеми

image::architecture/registry/operational/audit/audit-overview.svg[float="center",align="center",width=600]

Аудитом в системі вважається фіксування аудито-важливих подій в момент їх настання в сервісах які підлягають аудиту.

Для додавання аудиту до сервісу необхідно додати `бібліотеку інструментації коду` до переліку залежностей сервісу і проанотувати місця де відбуваються аудито-важливі події. +
`Бібліотека інструментації коду` - відповідальна за створення і обробку подій сервісу та створення і відправку повідомлень до `брокера повідомлень`. +
Події сервісу створюються як асинхронні події (`Applicaton Events`) і таким чином не вносять значний вплив на швидкодію сценаріїв в середині сервісів. +
На основі кожної аудит події відправляється окреме повідомлення до `брокера повідомлень` згідно схеми яка зберігається в `сервісі збереження схем повідомлень подій аудиту`. +
Збереження таких подій відбувається за допомогою `сервісу збереження подій аудиту` який побудований на основі https://kafka.apache.org/documentation.html#connect[Kafka Connect API], що забезпечує оброку повідомлень рівно один раз `exactly one`. +
Всі повідомлення зберігаються до `операційної БД подій аудиту` та можуть бути переглянуті за допомогою `системних представлення для перегляду подій` через `сервіс перегляду звітів` які створюються під час розгортання реєстру підсистемою xref:arch:architecture/platform/administrative/overview.adoc[розгортання та налаштування Платформи та реєстрів]

.Перелік сервісів які підлягають аудиту
|===
|Назва|Представлення сервісу в платформі |Події аудиту

|_Сервіс синхронного управління даними реєстру_
|*registry-rest-api*
|//TODO посилання на опис подій аудиту сервісу

|_Сервіс асинхронного управління даними реєстру_
|*registry-kafka-api*
|//TODO посилання на опис подій аудиту сервісу

|_Сервіс управління налаштуваннями користувачів_
|*user-settings*
|//TODO посилання на опис подій аудиту сервісу

|_Сервіс нотифікацій користувачів_
|*ddm-notification-service*
|//TODO посилання на опис подій аудиту сервісу

|_Сервіс доступу до історичних даних БП_
|*process-history-service-api*
|//TODO посилання на опис подій аудиту сервісу

|_Сервіс фіксації історичних подій БП_
|*process-history-service-persistence*
|//TODO посилання на опис подій аудиту сервісу
|===


== Складові підсистеми

|===
|Назва компоненти|Представлення в реєстрі|Походження|Призначення

|_Сервіс збереження схем повідомлень подій аудиту_
|`kafka-schema-registry`
|3rd-party
|Перевірка відповідності структури повідомлення поточній схемі

|_Сервіс збереження подій аудиту_
|`kafka-connect-cluster-connect`
|3rd-party
|Збереження повідомлень в базу даних

|_Операційна БД подій аудиту_
|`operational:audit`
|3rd-party
|Відокремлена БД для збереження аудиту подій

|===

== Технологічний стек

* xref:arch:architecture/platform-technologies.adoc#kafka[Kafka]
* xref:arch:architecture/platform-technologies.adoc#kafka-schema-registry[Kafka Schema Registry]

== Атрибути якості

=== Security
Використання автентифікації за допомогою TLS для підключення до брокера повідомлень з боку додатка, унеможливлює здійснення атак типу `людина посередині` (`Man in the middle`).
Всі дані в русі також шифруються за допомогою TLS.

=== Reliability
Загальна надійність системи забезпечується переліком механізмів реалізованих в компонентах які використовуються підсистемою. +

* Kafka (`Replication`, `Fault Tolerance`, `Message Persistence`, `Message immutabiliuty`, `Acknowledgment Mechanism`)
* Crunchy PostgreSQL (`Replication and Failover`, `High Availability`)

=== Scalability
Можливість паралельної обробки повідомлень та відсутність зберігання стану в додатку забезпечує горизонтальне масштабування.