@startsalt
{
{T
+ <&folder> registry-regulation
++ ...
++ <&folder> notifications
+++ <&folder> email
++++ <&folder> <b><template-directory></b>
+++++ <&folder> css
++++++ <&file> style.css
+++++ <&folder> images
++++++ <&file> image.jpg
++++++ <&file> ...
+++++ <&file> template.ftlh
+++++ <&file> notification.yml
++++ ...
}
}
@endsalt