= Registries update
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

//- Оновлення не має потребувати внесення змін до регламенту реєстру та бути _backward-compatible_
- The update should not require amendments to the registry regulations and should remain _backward-compatible_
//- Платформа має підтримувати обробку шаблонів поштових повідомлень старого зразку
- The Platform should support processing legacy template email messages
//- Платформа має підтримувати визначення заголовку _title_ повідомлення на рівні бізнес-процесу для шаблонів старого зразку
- The Platform should support the definition of message header _title_ at the business process level for legacy template


//В рамках процедури оновлення реєстру до нової версії, у разі, якщо реєстр використовує функціональні можливості відправлення повідомлень, змодельовані шаблони поштових повідомлень, необхідно привести до структури, задокументованої xref:architecture/registry/operational/notifications/notifications-modelling.adoc#_структура_шаблону_поштового_повідомлення[за посиланням], а саме:
As part of the procedure for updating the registry to the new version, if the registry utilizes functional capabilities of sending messages, modeled template email messages need to be brought in line with the structure documented at the xref:architecture/registry/operational/notifications/notifications-modelling.adoc#_структура_шаблону_поштового_повідомлення[link], and namely:

//- Створити службовий файл мета-даних __notification.yml__ для кожного з шаблонів, вказати заголовок повідомлення (_title_)
- Create a service metadata file, _notification.yml_, for each of the templates, specifying the message header (_title_)
//- Опублікувати зміни до регламенту
- Publish changes to the regulations

[IMPORTANT]
--
//- Перед проведенням оновлення необхідно забезпечити відсутність невідправлених повідомлень користувачам у відповідних _Kafka_-топіках.
- Prior to conducting the update, ensure the absence of unsent messages to users in the corresponding _Kafka_ topics.
//- Нова версія Платформи має бути _backward-compatible_ та не потребувати змін до регламенту для виконання оновлення
- The new version of the Platform should be _backward-compatible_ and not necessitate changes to the regulations for update implementation.
--