== Помилки

=== 400 - Помилки клієнта
|===
||

a| 
[plantuml]
----
 @startuml

skinparam monochrome true

box "Low-Code" 
    participant "Business service" as low
end box

box "Data Factory"
    participant "REST API" as rest
end box

box "Platform"
    database "Ceph" as ceph
end box

low -> rest : request
alt request
rest -X rest: не відповідає контракту
else
rest -X rest: нема заголовка підпису
else
rest -> ceph: отримання підпису
ceph --X rest: не знайдено
end
rest -> low : 400
@enduml
----

a| 
Помилка з ControllerAdvice +

Внутрішній код:

* CLIENT_ERROR - загальний випадок
* HEADERS_ARE_MISSING - відсутній обов'язковий заголовок
* INVALID_HEADER_VALUE - значення заголовка недопустиме (в Cehp відсутнє значення для такого ключа)
|===

=== 401 - Аутентифікації 
|===
||

a| 
[plantuml]
----
 @startuml

skinparam monochrome true

box "Low-Code" 
    participant "Business service" as low
end box

box "Data Factory"
    participant "REST API" as rest
end box

low -> rest : request
rest -X rest: відсутній токен 
rest -> low : 401
@enduml
----

a| 
Відсутній токен

Внутрішній код:

* AUTHENTICATION_FAILED - загальний випадок
|===

=== 403 - Вийшов термін дії JWT 
|===
||

a| 
[plantuml]
----
 @startuml

skinparam monochrome true

box "Low-Code" 
    participant "Business service" as low
end box

box "Data Factory"
    participant "REST API" as rest
    queue "Kafka" as kafka
    participant "Kafka API" as kapi
end box


low -> rest : request
rest -> kafka : request
kapi -> kafka : read message

kapi -x kapi: JWT термін дії пройшов

kapi --> kafka : message with error code
rest --> kafka : read response
rest --> low : 403
@enduml
----

a| 
В REST API це перевіряє Istio, а в Kafka API це відбувається в сервісі.

Внутрішній код:

* JWT_EXPIRED - загальний випадок
|===

=== 409 - Порушення одного з обмежень на рівні БД
|===
||
a| 
[plantuml]
----
@startuml
skinparam monochrome true

box "Low-Code" 
    participant "Business service" as low
end box

box "Data Factory"
    participant "REST API" as rest
    queue "Kafka" as kafka
    participant "Kafka API" as kapi
    database "DB" as db
end box

low -> rest: request
rest -> kafka: request
kapi -> kafka: read
alt DB error
kapi -> db: call procedure
return error code
end
kapi --> kafka: response 
rest --> kafka: read
rest --> low: 500
@enduml
----
a| 
Процедура повертає поле яке порушено

Внутрішній код: 

* CONSTRAINT_ERROR - загальна помилка

Можливі кроки для усунення: Перенесення перевірки на рівень бізнес процесів\клієнта
|===

==== Приклад відповіді
[source, json]
----
{
    "traceId": "traceId from MDC",
    "code": "CONSTRAINT_ERROR",
    "details": {
        "constraint": "unique/fk"
    }
}
----

=== 412 - Данні не відповідають підпису

|===
||

a|
[plantuml]
----
@startuml
skinparam monochrome true

box "Low-Code" 
participant "Business service" as low
end box

box "Data Factory"
    participant "REST API" as rest
end box

box "Platform"
participant "КЕП Сервіс" as kep
end box

low -> rest: request
rest -> kep: запит валідації
kep --X rest: данні не відповідають підпису
rest --> low : 412
@enduml
----

a|
Данні в тілі не відповідають підпису 

Внутрішній код:

* SIGNATURE_VIOLATION - загальна помилка
|===

=== 422 - Помилка валідації доменів
|===
||

a| 
[plantuml]
----
@startuml
skinparam monochrome true

box "Low-Code" 
participant "Business service" as low
end box

box "Data Factory"
    participant "REST API" as rest
end box

low -> rest: request
rest -x rest: помилка валідації на рівні API
rest --> low: 422
@enduml
----

a|
Значення змінної не відповідає правилам вказаним в домені.
Внутрішній код:

* VALIDATION_ERROR - загальна помилка

Можливі кроки для усунення: Додати перевірки на рівні клієнта
|===

==== Приклад відповіді
[source, json]
----
{
    "traceId": "traceId from MDC",
    "code": "VALIDATION_ERROR",
    "details": {
        "errors": [
            {
                "value": "-42",
                "field": "age",
                "message": "doesn't match pattern"
            },
            {
                "value": "",
                "field": "name",
                "message": "shouldn't be blank"
            }
        ]
    }
}
----

=== 500 - Загальні помилки
|===
||

a|
[plantuml]
----
@startuml

skinparam monochrome true

box "Low-Code" 
    participant "Business service" as low
end box

box "Data Factory"
    participant "REST API" as rest
end box


low -> rest : request
rest -X rest : runtime error
rest --> low: 500 Generic
@enduml
----

a| 
Щось пішло не так

Внутрішній код:

* RUNTIME_ERROR  - загальна помилка

a| 
[plantuml]
----
 @startuml

skinparam monochrome true

box "Low-Code" 
    participant "Business service" as low
end box

box "Data Factory"
    participant "REST API" as rest
    queue "Kafka" as kafka
    participant "Kafka API" as kapi
end box

box "Platform"
    database "Ceph" as ceph
end box

low -> rest : request
rest -> kafka : request
kapi -> kafka : read message
alt request
kapi -X kapi: JWT parsing error 
else
kapi -X kapi: no signature header
else
kapi -> ceph: get signature
ceph --X kapi: Not found
end
kapi --> kafka : message with error code
rest --> kafka : read response
rest --> low : 500
@enduml
----

a| 
Помилка в контракті між Rest API та Kafka API відправляються клієнту як внутрішні помилки системи

Внутрішній код:

* INTERNAL_CONTRACT_VIOLATION  - Порушення внутрішнього контракту

Можливі причини виникнення: 
Скоріше за все "баг" дата фабрики або атака через Kafka

a|
[plantuml]
----
@startuml
skinparam monochrome true

box "Low-Code" 
    participant "Business service" as low
end box

box "Data Factory"
    participant "REST API" as rest
    queue "Kafka" as kafka
    participant "Kafka API" as kapi
    database "DB" as db
end box

low -> rest: request
rest -> kafka: request
kapi -> kafka: read
alt DB error
kapi -x db: call procedure
else
kapi -x kapi: result set processing
end
kapi --> kafka: response 
rest --> kafka: read
rest --> low: 500
@enduml
----

a|
Помилка виклику процедуру або обробки її відповіді
Внутрішній код:

* PROCEDURE_ERROR - Помилки пов'язані з БД

Можливі причини виникнення: 
Не узгодженість версій процедури і коду або баг" дата фабрики

a|
[plantuml]
----
@startuml

skinparam monochrome true

box "Low-Code" 
    participant "Business service" as low
end box

box "Data Factory"
    participant "REST API" as rest
    queue "Kafka" as kafka
end box

low -> rest : request
rest -> kafka : send message
rest --> kafka: no response
rest --> low: 500 Generic
@enduml
----

a| 
Відсутня відповідь від Kafka API. Неправильна конфігурація, Kafka API сервіс недоступний, або виконання зайняло занадто багато часу.

Внутрішній код:

* TIMEOUT_ERROR - Таймаут відповіді

Можливі причини виникнення: 
Помилка конфігурації в даба фабриці, "бага" дата фабрики, запит оброблявся занадто довго

a|
[plantuml]
----
@startuml
skinparam monochrome true

box "Low-Code" 
participant "Business service" as low
end box

box "Data Factory"
    participant "REST API" as rest
end box

box "Platform"
participant "КЕП Сервіс" as kep
end box

low -> rest: request

rest -X kep: помилка виклику КЕП
rest --> low : 500
@enduml
----

[plantuml]
----
@startuml
skinparam monochrome true

box "Low-Code" 
participant "Business service" as low
end box

box "Data Factory"
    participant "REST API" as rest
    queue "Kafka" as kafka
    participant "Kafka API" as kapi
end box

box "Platform"

participant "КЕП Сервіс" as kep
end box

low -> rest: request
rest -> kafka: request
kapi -> kafka: read

kapi -X kep: unavailable \n error

kapi --> kafka: response with error code
rest --> kafka: read response
rest --> low: 401 
@enduml
----

a|
Одна з сторонніх систем не доступна.

Внутрішній код:

* THIRD_PARTY_SERVICE_UNAVAILABLE - зовнішня система не доступна

a| 
[plantuml]
----
@startuml
skinparam monochrome true

box "Low-Code" 
participant "Business service" as low
end box

box "Data Factory"
    participant "REST API" as rest
    queue "Kafka" as kafka
    participant "Kafka API" as kapi
end box

box "Platform"

participant "КЕП Сервіс" as kep
end box

low -> rest: request
rest -> kafka: request
kapi -> kafka: read

kapi -> kep: validate
kep --X kapi: invalid

kapi --> kafka: response with error code
rest --> kafka: read response
rest --> low: 500 
@enduml
----

a|
Внутрішній підпис не відповідає даним що були підписані

Внутрішній код:

* RUNTIME_ERROR - загальна помилка

Можливі причини виникнення: 
"бага" дата фабрики, атака через Kafka
|===