@startuml

autoactivate on

skinparam shadowing false
skinparam DatabaseBackgroundColor white
skinparam DatabaseBorderColor #2688d4
skinparam QueueBackgroundColor white
skinparam QueueBorderColor #2688d4
skinparam NoteBackgroundColor white
skinparam NoteBorderColor #2688d4
skinparam sequence {
    ArrowColor #2688d4
    ActorBorderColor #2688d4
    LifeLineBorderColor #2688d4
    ParticipantBorderColor #2688d4
    ParticipantBackgroundColor white
    BoxBorderColor #2688d4
    BoxBackgroundColor white
}

skinparam responseMessageBelowArrow true

actor "Розробник\n регламенту" as Dev

box "Registry Regulations Management"
  participant "DataModel Manager" as TablesManager
  participant "DataModelSnapshot\nManager" as SnapshotManager
  participant "DBSchema\nManager" as DBSchemaManager
end box

'Create version candidate flow
Dev -> TablesManager: Оновлює перелік таблиць
  TablesManager -> DBSchemaManager: Створює (rewrite) тимчасову БД
  DBSchemaManager --> TablesManager: result

  TablesManager -> DBSchemaManager: Розгортання тимчасової БД моделлю даних регламенту реєстру
  DBSchemaManager --> TablesManager: result

  TablesManager -> SnapshotManager: Зчитування структури БД
  SnapshotManager --> TablesManager: result

TablesManager --> Dev: result

Dev -> TablesManager: Отримує перелік таблиць моделі даних
  TablesManager -> SnapshotManager: Зчитування переліку файлів DataModelSnapshot tables
  SnapshotManager --> TablesManager: result
TablesManager --> Dev: Перелік таблиць версії-кандидату

@enduml