@startsalt
{
{T
+ <&folder> repositories/data-model-snapshots
++ <&folder> master
+++ <&file> table1.json
+++ <&file> table2.json
+++ ...
+++ <&file> tableN.json
++ <&folder> 1
+++ <&file> table1.json
+++ <&file> table2.json
+++ ...
+++ <&file> tableN.json
++ <&folder> 2
+++ <&file> table1.json
+++ <&file> table2.json
+++ ...
+++ <&file> tableN.json
++ ...
++ <&folder> N
+++ <&file> table1.json
+++ <&file> table2.json
+++ ...
+++ <&file> tableN.json
}
}
@endsalt