@startuml

autoactivate on

skinparam shadowing false
skinparam DatabaseBackgroundColor white
skinparam DatabaseBorderColor #2688d4
skinparam QueueBackgroundColor white
skinparam QueueBorderColor #2688d4
skinparam NoteBackgroundColor white
skinparam NoteBorderColor #2688d4
skinparam sequence {
    ArrowColor #2688d4
    ActorBorderColor #2688d4
    LifeLineBorderColor #2688d4
    ParticipantBorderColor #2688d4
    ParticipantBackgroundColor white
    BoxBorderColor #2688d4
    BoxBackgroundColor white
}

skinparam responseMessageBelowArrow true

actor "Розробник\n регламенту" as Dev

participant "Registry Regulation\nManagement" as rrm
participant "Gerrit" as gerrit
participant "Jenkins" as jenkins
database "Template\nDB Schema" as TemplateDB
database "Registry dev VC\nDB Schema" as VCTemplateDB
participant "run-db-scripts" as OkdJob

OkdJob -> TemplateDB ** : Створює та розгортає

Dev -> rrm: Створює версію-кандидат
  rrm -> gerrit: Створює MR
  gerrit --> rrm: result
rrm --> Dev: версія-кандидат

gerrit -> jenkins: запуск пайплайну перевірки регламенту

  group "Створення тимчасової БД"
    jenkins -> TemplateDB: отримує еталонну БДc
    jenkins <-- TemplateDB: result
    jenkins -> VCTemplateDB ** : Створює тимчасову схему БД
    jenkins <-- VCTemplateDB: result
  end group

  group "Розгортання тимчасової БД моделлю даних регламенту реєстру"
    jenkins -> VCTemplateDB: Розгортання моделі даних по liquibase changelog's майстер версії
    jenkins <-- VCTemplateDB: result
    jenkins -> VCTemplateDB: Розгортання моделі даних по liquibase changelog's версії-кандидату
    jenkins <-- VCTemplateDB: result
  end group

jenkins --> gerrit: публікація результату розгортання (Verified +1)

Dev -> rrm: Отримує перелік таблиць моделі даних
  rrm -> gerrit: зчитує стан розгортання регламенту
  rrm <-- gerrit: result

  rrm -> VCTemplateDB: Зчитування структури\nтимчасової БД
  VCTemplateDB --> rrm: result
rrm --> Dev: перелік таблиць

@enduml