:sectlinks:
= Modeling elements

include::platform:ROOT:partial$admonitions/language-en.adoc[]

This section introduces the fundamental elements necessary for creating and optimizing business processes. You will learn about:

* [*] *Tasks:* The fundamental actions performed within a process.
* [*] *Gateways:* Direct the process flow based on predefined conditions.
* [*] *Events:* Play a crucial role in initiating, terminating, and responding to changes in the process.
* [*] *Subprocesses:* Allow for structuring complex processes for better management.
* [*] *Execution listeners:* Provide feedback and control over the process.

This guide is designed to help you efficiently manage your business processes, ensuring productivity and flexibility in your operations.

== Section overview

* xref:bp-modeling/bp/bpmn/tasks/overview.adoc[]
* xref:bp-modeling/bp/bpmn/gateways/event-based-gateway.adoc[Gateways]
* xref:bp-modeling/bp/bpmn/events/events-overview.adoc[]
* xref:bp-modeling/bp/bpmn/subprocesses/subprocess-overview.adoc[]
* xref:bp-modeling/bp/bpmn/execution-listeners.adoc[]