= Перегляд історичності даних

include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис
*Перегляд історичності даних* - механізм для перегляду еволюції даних та їх походження, що також може слугувати для виявлення помилок або втручань в цілісність даних.

== Загальний хід виконання

image::architecture/registry/operational/excerpts/history-pipeline.svg[]

== Кроки для K8s Job
[plantuml, job_flow, svg]
----
@startuml
skinparam monochrome true
participant "Jenkins" as jenkins
control "Job" as job
database "Аналітична БД" as db
participant "КЕП" as sign
participant "Ceph" as ceph
participant "Сервіс витягів" as service
== Отримання даних ==
jenkins -> job: назва таблиці \nта ідентифікатор запису
job -> db: запит до історичної таблиці
return історичні дані
== Збагачення даних ==
loop для кожного запису
    job -> ceph:  отримання цифрового підпису \nдля запису
    return цифровий підпис
    job -> sign: отримання інформації про підпис
    return ДРФО, П.І.Б
end
== Запит витягу ==
job -> job: формування запиту \nна формування витягу
job -> sign: накладання цифрового підпису
return
job -> service: запит на створення витягу
return ідентифікатор витягу
== Очікування зміни статусу ==
job -> job: побудова запиту на статус витягу
loop
job -> service: перевірка статусу
return статус запиту
end
== Оновлення ресурсу ==
job -> job: додавання анотації до ресурсу Job
@enduml
----

== Процес збирання даних

* Історичні дані можливо отримати в рамках однієї таблиці для конкретного первинного ідентифікатора.
* Запити виконуються під окремим користувачем аналітичної бази даних
* Пошук відбувається в рамках тільки поточної версії регламенту

== Шаблон

Шаблон завантажується разом з регламентом, рекомендований шаблон `ddm-history-excerpt` може бути стилізований та доповнений моделювальником