= API відправки push-нотифікацій у мобільний додаток "Дія"
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

Платформа "_Дія_" надає авторизованим партнерам окремий _REST API_ для відправки _push_-нотифікацій користувачам у мобільний застосунок. Наразі підтримуються наступні сценарії:

- Створення шаблону _push_-нотифікації
- Реєстрація розсилки _push_-нотифікацій на базі шаблону
- Перевірка статусу розсилки _push_-нотифікацій
- Отримання результату розсилки _push_-нотифікацій
- Зупинка розсилки замовленої _push_-нотифікації

Для використання даних можливостей, необхідно:

- Зареєструватись у якості авторизованого партнера та отримати _Partner Token_
- Отримати дозвіл для авторизованого партнера на використання методів "_Сервісу розсилки push-нотифікацій_"

== Взаємодія з сервісом розсилки _push_-нотифікацій "Дія"

[plantuml, diia-push-notification-flow, svg]
----
include::partial$architecture/registry/operational/notifications/diia/diia-general-push-notification-flow.puml[]
----

== Аутентифікація авторизованого партнера

[NOTE]
Сценарій доступний лише для авторизованого партнера за наявності _Partner Token_.

_GET /api/v1/auth/partner/{partnerToken}_

.Параметри запиту
|===
|Параметр|Тип|Частина запиту|Опис

|*partnerToken*
|string
|Параметр запиту
|Токен авторизованого партнера
|===

.Структура відповіді на запит
|===
|Json Path|Тип|Опис

|*$.token*
|string
|_Bearer_-токен доступу для авторизованого партнера. Час життя токену - 2 години
|===

.Приклад відповіді
[source, json]
----
{
  "token": "<authorization token>"
}
----

== Створення шаблону нотифікації

[NOTE]
Отримання доступу до API можливе лише за умови проходження попередньої аутентифікації партнера та отримання _Bearer_-токену для подальшого використання при формуванні запитів.

_POST /api/v1/notification/template_

|===
|Параметр|Тип|Частина запиту|Опційність|Опис

|*Authorization*
|string
|Заголовок
|mandatory
|Bearer-токен для проходження авторизації: "Bearer <bearer-token>"

|*$.actionType*
|string
|Тіло запиту
|mandatory
|Тип спеціальної дії, котра має біти ініційована у застосунку по факту натискання з боку користувача на push-сповіщення або на повідомлення у відповідній вкладці застосунку.
Для нотифікації стосовно відкриття нового кредиту на користувача, пропонуються до використання тип спеціальної дії newCredOpen

|*$.templateType*
|string
|Тіло запиту
|mandatory
|Тип шаблону повідомлення. Обирається з довідника.
В залежності від визначеного типу, повідомлення за створюваним шаблоном нотифікації буде відображено у застосунку із тип чи іншим ключовим заголовком.
Для нотифікації стосовно відкриття нового кредиту на користувача, пропонуються до використання тип повідомлення attention ( Зверніть увагу)

|*$.timeToLiveInSec*
|number
|Тіло запиту
|optional
|Час життя нотифікації.
За замовчуванням, визначається рівним 14 діб.

|*$.removePrevious*
|boolean
|Тіло запиту
|optional
|Ознака, що вказує на потребу видалення попередньої нотифікації, що була доправлена користувачеві за даним шаблоном із визначеним ідентифікатором ресурсу (екземпляру).
За замовчуванням, визначається рівним true

|*$.needAuth*
|boolean
|Тіло запиту
|optional
|Ознака, що вказує на потребу авторизації користувача для прочитання змісту повідомлення, котре буде
доправлятися йому за даним шаблоном.

|*$.title*
|string
|Тіло запиту
|mandatory
|Заголовок нотифікації.
Відображається у якості заголовку push-сповіщення. Рекомендована довжина до 60 символів.

|*$.shortText*
|string
|Тіло запиту
|mandatory
|Короткий текст.
Відображається у якості тексту push-сповіщення та короткого змісту повідомлення у відповідній вкладці застосунку, та заголовку повного тексту повідомлення.
Рекомендована довжина до 200 символів.

|*$.fullText*
|string
|Тіло запиту
|mandatory
|Повний текст.
Відображається у якості повного тексту повідомлення у відповідній вкладці застосунку.
Рекомендована довжина 2048 символів.

|===

.Приклад тіла запиту
[source, json]
----
{
  "actionType": "message",
  "templateType": "attention",
  "title" : "Українське бюро кредитних історій",
  "shortText" : "Новий кредитний договір у кредитній історії",
  "fullText" : "У кредитну історію надійшла інформація про новий кредитний договір:\n\nдата відкриття - {dateCredOpen},\nкредитор - {creditor}.\n\n\n📥 Отримати кредитну історію можна на сайті Українського бюро кредитних історій - ubki.ua. \n\n⛔️ У разі виявлення шахрайських дій щодо вас або помилки кредитора - оскаржіть дані у кредитній історії."
}
----

.Структура відповіді на запит
|===
|Json Path|Тип|Опис

|*$.templateId*
|string
|Ідентифікатор створеного шаблона нотифікації
|===

.Приклад відповіді на запит
[source, json]
----
{
  "templateId": "6132008a2db328003c5d1d43"
}
----

.Приклад відповіді у разі помилки
[source, json]
----
{
  "name": "Error",
  "message": "\"Create Template\" scope required",
  "code": 403,
  "data": {}
}
----

.Коди відповідей
|===
|Код|Опис

a|[green]#201#
|Шаблон створено успішно

a|[red]#403#
|Помилка авторизації запиту
|===

== Реєстрація розсилки push-нотифікацій за заданим шаблоном

[NOTE]
Отримання доступу до API можливе лише за умови проходження попередньої аутентифікації партнера та отримання _Bearer_-токену для подальшого використання при формуванні запитів.

_POST /api/v1/notification/distribution/push_

[WARNING]
Максимальна кількість отримувачів push-нотифікації = 10 000

|===
|Параметр|Тип|Частина запиту|Опційність|Опис

|*Authorization*
|string
|Заголовок
|mandatory
|Bearer-токен для проходження авторизації: "Bearer <bearer-token>"

|*$.templateId*
|string
|Тіло запиту
|mandatory
|Ідентифікатор шаблону, за котрим має бути виконано розсилку на визначених отримувачів.
Отримується у відповідь на запит на створення шаблону розсилки, у разі успішної реєстрації шаблону.

|*$.recipients*
|array
|Тіло запиту
|mandatory
|Масив отримувачів, на котрих має бути виконано розсилку у визначеному шаблоні.
Максимальний розмір, що приймається системою - до 10 000 отримувачів за запит.

|*$.recipients[].rnokpp*
|string
|Тіло запиту
|mandatory
|РНОКПП отримувача - ідентифікатор за котрим система визначить отримувача повідомлення.

|*$.recipients[].id*
|string
|Тіло запиту
|mandatory
|Ідентифікатор користувача в 3rd-party системі партнера

|*$.recipients[].resourceId*
|string
|Тіло запиту
|optional
|Ідентифікатор сутності, щодо котрої надсилається нотифікація для визначеного отримувача. Якщо даний параметр не визначено - при натисканні користувача на push-сповідення або відповідне повідомлення, йому буде відображено повідомлення з повним змістом fullText.

|*$.recipients[].parameters*
|array
|Тіло запиту
|optional
|Масив об'єктів, що визначають значення параметрів, що можуть бути визначеними у шаблоні заданої нотифікації.
Якщо параметр в шаблоні присутній, проте у запиті на реєстрацію розсилки його не визначено (такого ключа для користувача не задано) - статус розсилки по даному користувачеві буде встановлено, як notification-generation-error

|*$.recipients[].parameters[].key*
|string
|Тіло запиту
|mandatory
|Назва параметра шаблону нотифкації. Використовується у тексті нотифікації _{key}_

|*$.recipients[].parameters[].value*
|string
|Тіло запиту
|mandatory
|Значення параметра шаблону нотифікації, визначене для конкретного адресата.

|===

.Приклад тіла запиту
[source, json]
----
{
    "templateId": "string",
    "recipients": [
        {
            "rnokpp": "string",
            "id": "string",
            "resourceId?": "string",
            "parameters?": [
                {
                    "key": "string",
                    "value": "string"
                }
            ]
        }
    ]
}
----

.Структура відповіді на запит
|===
|Json Path|Тип|Опис

|*$.distributionId*
|string
|Ідентифікатор створеної розсилки нотифікацій
|===

.Приклад відповіді на запит
[source, json]
----
{
  "distributionId": "12345678901"
}
----

== Отримання статусу розсилки _push_-нотифікацій

[NOTE]
Отримання доступу до API можливе лише за умови проходження попередньої аутентифікації партнера та отримання _Bearer_-токену для подальшого використання при формуванні запитів.

_GET /api/v1/notification/distribution/push/{distributionId}/status_

|===
|Параметр|Тип|Частина запиту|Опційність|Опис

|*Authorization*
|string
|Заголовок
|mandatory
|Bearer-токен для проходження авторизації: "Bearer <bearer-token>"

|*distributionId*
|string
|Параметр запиту
|mandatory
|Ідентифікатор розсилки _push_-нотифікацій
|===

.Структура відповіді на запит
|===
|Json Path|Тип|Опис

|*$.status*
|string
|Статус виконання розсилки _push_-нотифікацій:

['pending', 'in-progress', 'sent', 'closed']

|===

.Приклад відповіді на запит
[source, json]
----
{
  "status": "enum ['pending', 'in-progress', 'sent', 'closed']"
}
----

== Отримання результату розсилки _push_-нотифікацій

[NOTE]
Отримання доступу до API можливе лише за умови проходження попередньої аутентифікації партнера та отримання _Bearer_-токену для подальшого використання при формуванні запитів.

_GET /api/v1/notification/distribution/push/{distributionId}_

|===
|Параметр|Тип|Частина запиту|Опційність|Опис

|*Authorization*
|string
|Заголовок
|mandatory
|Bearer-токен для проходження авторизації: "Bearer <bearer-token>"

|*distributionId*
|string
|Параметр запиту
|mandatory
|Ідентифікатор розсилки _push_-нотифікацій
|===

.Структура відповіді на запит
|===
|Json Path|Тип|Опис

|*$.recipients*
|array
|Перелік отримувачів розсилки

|*$.recipients[].id*
|string
|Ідентифікатор користувача в 3rd-party системі партнера

|*$.recipients[].rnokpp*
|string
|РНОКПП отримувача - ідентифікатор за котрим система визначить отримувача повідомлення.

|*$.recipients[].status*
|string
|Статус виконання розсилки _push_-нотифікацій користувачу:

['pending', 'in-progress', 'sent', 'closed']

|===

.Приклад відповіді на запит
[source, json]
----
{
  "recipients": [
    {
      "id": "string",
      "rnokpp": "string",
      "status": "enum ['not-found', 'sent', 'read', 'error']"
    }
  ]
}
----

== Зупинка розсилки _push_-нотифікацій

[NOTE]
Отримання доступу до API можливе лише за умови проходження попередньої аутентифікації партнера та отримання _Bearer_-токену для подальшого використання при формуванні запитів.

_DELETE /api/v1/notification/distribution/push/{distributionId}_

|===
|Параметр|Тип|Частина запиту|Опційність|Опис

|*Authorization*
|string
|Заголовок
|mandatory
|Bearer-токен для проходження авторизації: "Bearer <bearer-token>"

|*distributionId*
|string
|Параметр запиту
|mandatory
|Ідентифікатор розсилки _push_-нотифікацій
|===

.Коди відповідей
|===
|Код|Опис

a|[green]#204#
|Якщо розсилку не було запущено - її буде видалено без запуску. Якщо розсилка перебуває у процесі виконання - її буде зупинено.
|===

== Шаблонізація повідомлень у Дії

Відправка нотифікацій включає етап генерації фінального тексту нотифікації на базі створеного шаблона _fullText_ та моделі даних із запиту, шляхом заміщення змінних вигляду _{key}_ на відповідне значення поля моделі даних.

.Приклад шаблону текстового повідомлення _fullText_
[source, text]
----
"У кредитну історію надійшла інформація про новий кредитний договір:\n
дата відкриття - {dateCredOpen},\nкредитор - {creditor}.\n
📥 Отримати кредитну історію можна на сайті Українського бюро кредитних історій - ubki.ua.\n
⛔️ У разі виявлення шахрайських дій щодо вас або помилки кредитора - оскаржіть дані у кредитній історії."
----

.Приклад запиту на створення розсилки згідно шаблону та моделі даних для формування повідомлення
[source, json]
----
{
  "templateId": "<Ідентифікатор шаблона>",
  "recipients": [
    {
      "id": "<Ідентифікатор користувача у 3rd-party системі>",
      "rnokpp": "<ІПН користувача>",
      "parameters": [
        {
            "key": "dateCredOpen",
            "value": "01.08.2021"
        },
        {
            "key": "creditor",
            "value": "ПриватБанк"
        }
      ]
    }
  ]
}
----
