= Технічний дизайн рішення
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Контейнерна діаграма

На даній діаграмі зображено залучені для реалізації вимог сервіси платформи та взаємодію між ними.

image::architecture/registry/operational/notifications/notifications-design.svg[notifications-design,700]

== Задіяні сервіси та їх призначення в рамках дизайну рішення

У даному розділі наведено перелік компонент системи, які задіяні або потребують змін/створення в рамках реалізації функціональних вимог згідно технічного дизайну рішення.

|===
|Компонент|Службова назва|Призначення

|_Регламент реєстру_
|*registry-regulation*
|Налаштування шаблонів для відправки повідомлень за каналами зв'язку

|_Пайплайн публікації регламенту_
|*jenkins*
|Публікація змін до шаблонів повідомлень до цільового оточення реєстру

|_Утиліта публікації шаблонів_
|*notification-template-publisher*
|Підготовка та завантаження шаблонів повідомлень з репозиторію регламенту в окреме сховище шаблонів для використання в рамках виконання сценаріїв

|_Інтерфейс адміністрування платформи_
|*control-plane-console*
|Внесення налаштувань доступних каналів зв'язку для цільового оточення реєстру

|_Пайплайн створення реєстру_
|*control-plane-jenkins*
|Застосування налаштувань каналів зв'язку до цільового оточення реєстру

|_Сервіс управління користувачами та доступом_
|*keycloak*
|Отримання атрибутів користувачів за ідентифікатором (РНОКПП)

|_Кабінет громадянина_
|*citizen-portal*
|Перегляд in-app повідомлень в inbox Кабінету Громадянина

|_Сервіс виконання бізнес-процесів_
|*bpms*
|Формування та публікація події про необхідність відправки повідомлення користувачам у процесі виконання бізнес-процесу

|_Сервіс нотифікацій користувачів_
|*notification-service*
|Реагування на події про необхідність відправки повідомлення користувачам шляхом генерації повідомлення на базі вказаного шаблону та вхідних даних з послідуючою відправкою в залежності від вказаного та попередньо налаштованого каналу зв'язку. Управління шаблонами повідомлень.

|_Сервіс управління налаштуваннями користувачів_
|*user-settings-service-api*
|Отримання налаштувань каналів зв'язку обраних користувачами для отримання повідомлень

|_Платформенний поштовий сервер_
|*platform-mail-server*
|Поштовий сервер, який розповсюджується разом з платформою для сумісного використання реєстрами у якості опції за замовчуванням

|_Зовнішній поштовий сервер_
|*external-mail-server*
|Поштовий сервер за вибором адміністратора реєстру у разі особливих вимог до відправки поштових повідомлень

|_Сервіс нотифікацій Дія_
|*diia-notification-service*
|Відправки push-нотифікацій користувачам мобільного додатку Дія

|_Розподілена реляційна база даних Citus_
|*citus-master*
|Довготривале збереження шаблонів повідомлень на цільовому оточенні реєстру. Збереження in-app повідомлень користувачів.

|_Розподілений брокер повідомлень Kafka_
|*kafka*
|Обмін повідомленнями між компонентами системи управління реєстром

|===

== Налаштування політик міжсервісної взаємодії

Для коректної роботи підсистеми нотифікацій, мають бути налаштовані відповідні мережеві політики _NetworkPolicy_, які дозволяють взаємодію для наступних компонентів:

- *kong* -> *notification-service*
- *bpms* -> *kafka*
- *notification-service* -> *kafka*
- *notification-service* -> *keycloak*
- *notification-service* -> *user-settings-service-api*
- *notification-service* -> *citus-master*
- *notification-service* -> *kafka-schema-registry*
- *notification-service* -> *platform-mail-server*

В залежності від обраної конфігурації на етапі створення/редагування налаштувань реєстру, буде автоматично створено _ServiceEntry_ для налаштування доступу до зовнішніх сервісів на рівні _Istio Service Mesh_:

- *notification-service* -> *external-mail-server*
- *notification-service* -> *diia-notification-service*

== Kafka-топіки запитів на відправку повідомлень користувачам

Наразі, за обслуговування запитів на відправлення повідомлень користувачам відповідають наступні _Kafka_-топіки, сегреговані за призначенням, вимогами до масштабування та контролю навантаження на _downstream_-сервіси:

|===
|Службова назва|Опис
|_user-notifications_
|Публікація та обробка системних запитів на відправлення повідомлень користувачам. Реалізує асинхронну взаємодію між сервісами реєстру та _Сервісом відправки повідомлень користувачам_

|_user-notifications.DLT_
|Публікація запитів на відправлення повідомлень користувачам, які не вдалося опрацювати _Сервісом відправки повідомлень користувачам_

|_email-notifications_
|Публікація та обробка запитів на відправлення поштових повідомлень користувачам через платформенний або зовнішній SMTP-сервер

|_email-notifications.DLT_
|Публікація запитів на відправлення поштових повідомлень користувачам, які не вдалося опрацювати

|_diia-notifications_
|Публікація та обробка запитів на відправлення _push_-повідомлень користувачам у мобільний застосунок Дія

|_diia-notifications.DLT_
|Публікація запитів на відправлення _push_-повідомлень користувачам у мобільний застосунок Дія, які не вдалося опрацювати

|_inbox-notifications_
|Публікація та обробка запитів на відправлення повідомлень користувачам у _Кабінет Громадянина_

|_inbox-notifications.DLT_
|Публікація запитів на відправлення повідомлень користувачам у _Кабінет Громадянина_, які не вдалося опрацювати
|===

=== Публікація та обробка системних запитів на відправлення повідомлень

Перелік _Kafka_-топіків:

- _user-notifications_
- _user-notifications.DLT_

.Канонічний вигляд структури повідомлення
[source,json]
----
{
  "context": {
    "system": "Low-code Platform",
    "application": "<bpms.app.name>",
    "businessProcess": "<optional>",
    "businessProcessDefinitionId": "<optional>",
    "businessProcessInstanceId": "<optional>",
    "businessActivity": "<optional>",
    "businessActivityInstanceId": "<optional>"
  },
  "notification": {
    "templateName": "<notification template unique name>",
    "ignoreChannelPreferences": "<true|false (default: false) - ignore whether channel is active or not - used for OTP verification, etc. >"
  },
  "recipients": [
    {
      "id": "<Ідентифікатор користувача>",
      "channels": [
        {
          "channel": "diia",
          "rnokpp": "<ІПН користувача>"
        },
        {
          "channel": "email",
          "email": "<Email користувача>"
        }
      ],
      "parameters": [
        {
            "key": "<key>",
            "value": "<value>"
        }
      ]
    }
  ]
}
----

=== Публікація та обробка запитів на відправлення повідомлень користувачам у _Кабінет Громадянина_

Перелік _Kafka_-топіків:

- _inbox-notifications_
- _inbox-notifications.DLT_

.Канонічний вигляд структури повідомлення
[source,json]
----
{
  "context": {
    "system": "Low-code Platform",
    "application": "<bpms.app.name>",
    "businessProcess": "<optional>",
    "businessProcessDefinitionId": "<optional>",
    "businessProcessInstanceId": "<optional>",
    "businessActivity": "<optional>",
    "businessActivityInstanceId": "<optional>"
  },
  "notification": {
    "subject": "<notification subject>",
    "message": "<notification message>"
  },
  "recipient": {
    "id": "<Ідентифікатор користувача>"
  }
}
----

=== Публікація та обробка запитів на відправлення поштових повідомлень

Перелік _Kafka_-топіків:

- _email-notifications_
- _email-notifications.DLT_

.Канонічний вигляд структури повідомлення
[source,json]
----
{
  "context": {
    "system": "Low-code Platform",
    "application": "<bpms.app.name>",
    "businessProcess": "<optional>",
    "businessProcessDefinitionId": "<optional>",
    "businessProcessInstanceId": "<optional>",
    "businessActivity": "<optional>",
    "businessActivityInstanceId": "<optional>"
  },
  "notification": {
    "subject": "<notification subject>",
    "message": "<notification message>"
  },
  "recipient": {
    "id": "<Ідентифікатор користувача - optional>",
    "email": "<Email користувача>"
  }
}
----

=== Публікація та обробка запитів на відправлення _push_-повідомлень у мобільний застосунок Дія

Перелік _Kafka_-топіків:

- _diia-notifications_
- _diia-notifications.DLT_

.Канонічний вигляд структури повідомлення
[source,json]
----
{
  "context": {
    "system": "Low-code Platform",
    "application": "<bpms.app.name>",
    "businessProcess": "<optional>",
    "businessProcessDefinitionId": "<optional>",
    "businessProcessInstanceId": "<optional>",
    "businessActivity": "<optional>",
    "businessActivityInstanceId": "<optional>"
  },
  "notification": {
    "templateName": "<template name>",
    "externalTemplateId": "<external template id>"
  },
  "recipient": {
    "id": "<Ідентифікатор користувача - optional>",
    "rnokpp": "<ІПН користувача>",
    "parameters": [
      {
        "key": "<key>",
        "value": "<value>"
      }
    ]
  }
}
----

=== Загальні налаштування Kafka-топіків підсистеми нотифікацій

==== Налаштування цільових топіків запитів на відправку повідомлень

|===
|Властивість|Значення|Опис

|*num-partitions*
|_1_
|Кількість розділів в рамках топіку для збереження повідомлень

|*replication-factor*
|_1_
|Кількість реплік цільового топіка

|*retention-policy-in-days*
|_7_
|Кількість днів збереження повідомлення в Kafka
|===

==== Налаштування _Dead-Letter-Queue_ топіків запитів на відправку повідомлень, які не вдалося опрацювати

Службовий топік, який використовується для публікації та тимчасового збереження подій-запитів на відправку повідомлень користувачам, які не вдалося обробити з ціллю їх подальшого повторного опрацювання.

|===
|Властивість|Значення|Опис

|*num-partitions*
|_1_
|Кількість розділів в рамках топіку для збереження повідомлень

|*replication-factor*
|_1_
|Кількість реплік цільового топіка

|*retention-policy-in-days*
|_7_
|Кількість днів збереження повідомлення в Kafka
|===

[NOTE]
Перегляд та моніторинг подій, які не вдалося опрацювати, можливий через окремий веб-інтерфейс *kafka-ui*.

TIP: У разі необхідності відправлення подій адміністратором на повторне опрацювання, розглядається опція побудови окремого службового процесу на базі _Kafka Connect_, який буде переносити події з _Dead-Letter-Queue_ у цільовий топік.

