= Оновлення реєстрів
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

- Оновлення не має потребувати внесення змін до регламенту реєстру та бути _backward-compatible_
- Платформа має підтримувати обробку шаблонів поштових повідомлень старого зразку
- Платформа має підтримувати визначення заголовку _title_ повідомлення на рівні бізнес-процесу для шаблонів старого зразку


В рамках процедури оновлення реєстру до нової версії, у разі, якщо реєстр використовує функціональні можливості відправлення повідомлень, змодельовані шаблони поштових повідомлень, необхідно привести до структури, задокументованої xref:architecture/registry/operational/notifications/notifications-modelling.adoc#_структура_шаблону_поштового_повідомлення[за посиланням], а саме:

- Створити службовий файл мета-даних __notification.yml__ для кожного з шаблонів, вказати заголовок повідомлення (_title_)
- Опублікувати зміни до регламенту

[IMPORTANT]
--
- Перед проведенням оновлення необхідно забезпечити відсутність невідправлених повідомлень користувачам у відповідних _Kafka_-топіках.
- Нова версія Платформи має бути _backward-compatible_ та не потребувати змін до регламенту для виконання оновлення
--