= Аудит та журналювання подій

include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис підходу

Усі події відправки повідомлень користувачам системою фіксуються у журналі аудиту з повним контекстом. Для реалізації вимоги необхідно розширити підсистему аудиту наступним чином:

* Ввести окрему категорію подій аудиту для фіксації службових операцій:
** *EVENT_TYPE* = _SYSTEM_EVENT_
* Розширити перелік службових операцій:
** _SEND_USER_NOTIFICATION_

[NOTE]
Детальніше з дизайном підсистеми "_Журнал аудиту_" можна ознайомитися
xref:architecture/registry/operational/audit/audit.adoc[за посиланням]

.Приклад налаштувань для публікації подій аудиту через Kafka-топік (на прикладі використання *ddm-starter-audit* бібліотеки)
[source, yaml]
----
audit:
  kafka:
    topic: audit-events
    schemaRegistryUrl: http://kafka-schema-registry:8081
----

== Структура події аудиту

Нижче наведено xref:architecture/registry/operational/audit/audit.adoc#_події[структуру події аудиту] та її відповідність структурі та значенням отриманого через Kafka-топік повідомлення про необхідність відправки нотифікації користувачу.

|===
|Атрибут|Значення

|*timestamp*
|_now()_

|*application_name*
|"_notification-service_"

|*name*
|"_SEND_USER_NOTIFICATION_"

|*type*
|"_SYSTEM_EVENT_"

|*request_id*
|_<MDC.traceId>_

|*source_system*
|_<context.system>_

|*source_application*
|_<context.application>_

|*source_business_process*
|_<context.businessProcess>_

|*source_business_process_definition_id*
|_<context.businessProcessDefinitionId>_

|*source_business_process_instance_id*
|_<context.businessProcessInstanceId>_

|*source_business_activity*
|_<context.businessActivity>_

|*source_business_activity_id*
|_<context.businessActivityInstanceId>_

|*context*
|_<JSON-представлення деталей операції та результату її виконання>_

|===

=== Структура контексту події аудиту для каналів зв'язку

.JSON-представлення деталей події для фіксації відправки поштового повідомлення
[source, json]
----
{
  "notification": {
    "channel:": "email",
    "subject": "<Заголовок повідомлення>",
    "message": "<Повідомлення>",
    "recipient": {
      "id": "<Ідентифікатор користувача - optional>",
      "email": "<Поштова адреса користувача>"
    }
  }
}
----

.JSON-представлення деталей події для фіксації відправки повідомлення в inbox кабінету
[source, json]
----
{
  "notification": {
    "channel:": "inbox",
    "subject": "<Заголовок повідомлення>",
    "message": "<Повідомлення>",
    "recipient": {
      "id": "<Ідентифікатор користувача>"
    }
  }
}
----

.JSON-представлення деталей події для фіксації відправки повідомлення в мобільний додаток Дія
[source, json]
----
{
  "notification": {
    "channel:": "diia",
    "externalTemplateId": "<Ідентифікатор шаблону>",
    "templateName": "<Службова назва шаблону>",
    "distributionId": "<Ідентифікатор розсилки>",
    "recipient": {
      "id": "<Ідентифікатор користувача>",
      "rnokpp": "<ІПН користувача>",
      "parameters": [
        {
          "key": "<key>",
          "value": "<value>"
        }
      ]
    }
  }
}
----