= Підсистема нотифікацій користувачів

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Підсистема, призначенням якої є отримання та обробка запитів на відправлення нотифікацій користувачам згідно персональних налаштувань та каналів зв'язку, які підтримуються реєстром.

== Функції підсистеми

* Формування на базі налаштованого шаблону та відправлення поштових нотифікацій з використанням платформного або зовнішнього _SMTP_-сервера
* Формування на базі налаштованого шаблону та відправлення push-нотифікацій в мобільний додаток _Дія_
* Формування на базі налаштованого шаблону та створення _in-app_-нотифікацій в _Inbox_ кабінету користувача
* Перегляд переліку та підтвердження перегляду in-app повідомлень користувачем

== Технічний дизайн підсистеми

На даній діаграмі зображено компоненти, які входять в _Підсистема нотифікацій користувачів_ та їх взаємодію з іншими підсистемами в рамках реалізації функціональних сценаріїв.

image::architecture/registry/operational/notifications/notifications-subsystem-design.svg[width=600,float="center",align="center"]

=== Аудит та журналювання подій

Події відправки повідомлень користувачам системою фіксуються у журналі аудиту з повним контекстом. Використовуються наступні назви подій:

* _SEND_USER_NOTIFICATION_: Спроба відправки повідомлення з результатом операції

[NOTE]
Детальніше з дизайном _Підсистеми журналювання подій аудиту_ можна ознайомитися
xref:arch:architecture/registry/operational/audit/overview.adoc[за посиланням]

== Складові підсистеми

|===
|Назва компоненти|Представлення в реєстрі|Походження|Репозиторій|Призначення

|_Сервіс нотифікацій користувачів_
|`ddm-notification-service`
|origin
|https://github.com/epam/edp-ddm-notification-service[github.com/epam/edp-ddm-notification-service]
|Обробка запитів на відправку повідомлень користувачам згідно налаштувань каналів зв'язку

|_Операційна БД нотифікацій_
|`operational:notifications`
|origin
|https://github.com/epam/edp-ddm-registry-postgres/tree/main/platform-db/changesets/notifications[github.com/epam/edp-ddm-registry-postgres/tree/main/platform-db/changesets/notifications]
|Зберігання шаблонів повідомлень та inbox-нотифікацій користувачів
|===

== Технологічний стек

* xref:arch:architecture/platform-technologies.adoc#java[Java]
* xref:arch:architecture/platform-technologies.adoc#spring[Spring]
* xref:arch:architecture/platform-technologies.adoc#spring-boot[Spring Boot]
* xref:arch:architecture/platform-technologies.adoc#spring-cloud[Spring Cloud]
* xref:arch:architecture/platform-technologies.adoc#postgresql[PostgreSQL]
* xref:arch:architecture/platform-technologies.adoc#kafka[Kafka]

== Атрибути якості підсистеми

=== _Observability_

_Підсистема нотифікацій користувачів_ підтримує журналювання та збір метрик продуктивності для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--

=== Auditability

_Підсистема нотифікацій користувачів_ фіксує значимі технічні та бізнес події, пов'язані з експлуатацією системи кінцевими користувачами використовуючи xref:arch:architecture/registry/operational/audit/overview.adoc[підсистему журналювання подій аудиту].