= Підсистема нотифікацій користувачів

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Підсистема, призначенням якої є отримання та обробка запитів на відправлення нотифікацій користувачам згідно персональних налаштувань та каналів зв'язку, які підтримуються реєстром.

== Функції підсистеми

* Формування на базі налаштованого шаблону та відправлення поштових нотифікацій з використанням платформного або зовнішнього _SMTP_-сервера
* Формування на базі налаштованого шаблону та відправлення push-нотифікацій в мобільний додаток _Дія_
* Формування на базі налаштованого шаблону та відправлення _in-app_-нотифікацій в _Inbox_ кабінету користувача

== Технічний дизайн підсистеми

image::architecture/registry/operational/notifications/notifications-subsystem-design.svg[width=600,float="center",align="center"]

== Складові підсистеми

|===
|Назва компоненти|Представлення в реєстрі|Походження|Репозиторій|Призначення

|_Сервіс нотифікацій користувачів_
|`ddm-notification-service`
|origin
|https://github.com/epam/edp-ddm-notification-service[github.com/epam/edp-ddm-notification-service]
|Обробка запитів на відправку повідомлень користувачам згідно налаштувань каналів зв'язку

|_Операційна БД нотифікацій_
|`operational:notifications`
|origin
|https://github.com/epam/edp-ddm-registry-postgres/tree/main/platform-db/changesets/notifications[github.com/epam/edp-ddm-registry-postgres/tree/main/platform-db/changesets/notifications]
|Зберігання шаблонів повідомлень та inbox-нотифікацій користувачів
|===