= Мінімізація кількості шаблонів розгортання реєстру

== Загальний опис

У цій статті буде розглянута реалізація можливості створення реєстрів через адмін-консоль через гнучкі параметри налаштування
ресурсів реєстрів замість чітко визначених шаблонів.

== Актори та ролі користувачів
* Службові адміністратори

== Функціональні сценарії
* Створення реєстрів через адмін-консоль
* Редагування реєстрів через адмін-консоль

== Поточна реалізація

При розробці поточного функціонала по створенню реєстрів через адмін-консоль, було зроблено помилкове припущення що всі
реєстри можна категоризувати по чітко визначеним групам, тому при створенні реєстру через адмін-консоль,
службовий адміністратор Платформи має обирати з переліку один з присутніх шаблонів:

* registry-tenant-template-minimal
* registry-tenant-template-recommended
* registry-tenant-template-geo-server-minimal

що виявилось недостатньо гнучким підходом. Шаблони у своїй більшості ідентичні та відрізняються один від одного лише параметрами, які задають певну конфігурацію. В цій
реалізації є кілька недоліків:

* Дублювання коду шаблонів
* Неможливість гнучко змінити налаштування реєстрів через адмін-консоль без ручного втручання в код шаблону
* Складність вибору початкового шаблону реєстру для адміністратора та неможливість змінити його за бажанням адміністратора після створення
* Неможливість повноцінно категоризувати потреби в ресурсах кожного реєстру в чітко сформованих декількох шаблонах.

== Загальні принципи та положення

* Замість декількох шаблонів реєстрів, в `control-plane-gerrit` залишається один параметризований.
* Параметри реєстру для єдиного шаблону адміністратор має можливість задавати на окремій табі під час процесу створення реєстру.
* Параметри реєстру для винесення на адмін-консоль перелічені в таблиці 1-4.
* Адмін-консоль має розпізнавати тип інфраструктури на якій розгорнутий кластер OpenShift (AWS, vSphere тощо) і в залежності
від цього показувати або приховувати певні параметри специфічні для конкретного типу інфраструктури.
* Таба "Шаблон реєстру" змінює свою назву на "Параметри реєстру" та містить в собі винесені параметри шаблонів для редагування.
* Адмін-консоль має вносити задані адміністратором значенням (або задані за замовчуванням) у відповідні `values.yaml` (див. таблицю) та далі вони передаються у відповідні чарти та `helmfiles.yaml` для подалішого використання при розгортанні ресурсів реєстрів.
* На табі "Параметри реєстру" залишається випадаючий елемент з гілками шаблону та дозволяє обирати версію шаблону.
* На параметрах що вводяться в текстові поля повинна бути валідація на коректність введеної інформації як на рівні адмін-консолі, так і на рівні jenkins пайплайну (у разі редагування напряму через Gerrit).
* При редагуванні винесених параметрів повинен створюватись MR.
* В скрипті `add_template_repositories.sh` повинен пакуватись тільки один основний темплейт реєстрів.
* Параметр `griada.url` не виноситься на рівень адмін-консолі за відсутністю кейсів використання, а залишається доступним
для зміни через комміт в Gerrit. При цьому, Griada ServiceEntry не повинен створюватись, якщо `url` не заданий явно.
* Редагування deploymentMode дозволяється тільки з `development` в `production`, навпаки заборонено.

== Цільовий дизайн

1. Адмін-консоль має розпізнавати тип інфраструктури на якій розгорнутий кластер OpenShift (AWS, vSphere тощо). Це можна зробити через ресурс:
+
----
oc get infrastructure cluster -o jsonpath='{.status.platformStatus.type}'
----
+
На основі визначеного типу інфраструктури мають відображатись відповідні параметри для налаштування віртуальних машин реєстру.

2. Адмін-консоль зберігає вказані параметри до файлу налаштувань реєстру `values.yaml` наступним чином:
+
.Приклад yaml конфігурації в values.yaml
----
....
griada:
  enabled: true
  ip: "10.0.0.23"
  port: 3080
global:
  geoServer: true
  deploymentMode: "development"
  computeResources:
    instanceCount: 3
    awsInstanceType: "r5.2xlarge"
    awsSpotInstance: false
    awsInstanceVolumeType: "gp3"
    awsInstanceVolumeSize: 80
  excludePortals: "[]"
...
----

3. Для релізу `geoServer` в основному `helmfile.yaml` має бути встановлен параметер `installed` в який передаватись значення з `values.yaml`:
+
----
- name: geo-server
  namespace: '{{ env "NAMESPACE" }}'
  labels:
    type: remote
    update_scc: true
    repoURL: ssh://jenkins@gerrit.mdtu-ddm-edp-cicd:32114/mdtu-ddm/devops/geo-server.git
    path: components/registry/
  chart: /opt/repositories/geo-server/deploy-templates
  version: 1.0.0-SNAPSHOT.28
  values:
  - values.yaml
  - values.gotmpl
  installed: '{{ .Values.global.geoServer }}'
  missingFileHandler: Warn
  needs:
  - '{{ env "NAMESPACE" }}/registry-postgres'
----
+
TIP: Для передачі значення параметра `installed` можна використати або задання його на рівні пайплайну як змінну оточення або
або прочитати з `values.yaml` через https://helmfile.readthedocs.io/en/latest/#environment-values[helmfile environment values]

3.

=== Цільові кластери

=== Оточення для розробки CICD2

Для підтримки працездатності механізму розгортання персональних оточень на CICD2 кластері пропонується поступовий перехід на новий підхід з
єдиним шаблоном:

1. Перший етап — це збереження поточного процесу шляхом переносу CICD2 шаблонів в окремий від `control-plane-gerrit` суто
технічний репозиторій та зміна в стейджі `checkout-registry-tenant` посилання з `control-plane-gerrit` на новий репозиторій.
Це забезпечить швидкий та простий перехід для оточення розробки зі збереженням всіх автоматизованих операцій для розгортання реєстрів.
Але цей спосіб несе ризики з тим, що процеси створення реєстрів на розробницьких та промислових оточеннях будуть відрізнятись.
Для запобігання цьому розглянемо другий пункт.

2. Розширити Jenkins CD pipeline можливістю:
* задавати параметри для `helmfile` шаблону з сторінки запуску джоби
* завантаженням власного `values.yaml` на стейджі підготовки до розгортання оточення.

=== Перелік параметрів для винесення на рівень адмін-консолі

WARNING: Наступний перелік параметрів не вичерпний, а мінімально необхідний для зменшення кількості темплейтів до одного і може розширюватись за потребою.

[cols="5*",options="header"]
.spec parameters
|===
|Поле|Тип|Значення за замовчуванням|Приналежність|Призначення

|`griada`
|<<griada,griada>>
|-
|Registry values.yaml
|Налаштування програмно-апаратного криптомодуля "Гряда"

|`global`
|<<global,global>>
|-
|Registry values.yaml

Cluster values.yaml
|Глобальні параметри налаштувань реєстрів або Платформи

|===

[[griada]]
[cols="4*",options="header"]
.griada object
|===
|Поле|Тип|Значення за замовчуванням|Призначення

|`enabled`
|string
|Пусте значення. Встановлюється в залежності від попередньо заданого типу носія ключа на табі "Дані про ключ". Файловий носій
— `false`, апаратний — `true`.
|Поле для вказання, чи використовується апаратний ключ для реєстру.

|`ip`
|string
|Пусте значення. Задається з поля `Хост ключа` на табі "Дані про ключ" при вибраному апаратному носію ключа.
|Поле для вказання ip-адреси програмно-апаратного криптомодуля "Гряда".

|`port`
|string
|Пусте значення. Задається з поля `Порт ключа` на табі "Дані про ключ" при вибраному апаратному носію ключа.
|Поле для вказання порту програмно-апаратного криптомодуля "Гряда".

|===

WARNING: Параметр `griada.url` не виноситься на рівень адмін-консолі за відсутністю кейсів використання, а залишається доступним для зміни через комміт в Gerrit.
При цьому, Griada ServiceEntry не повинен створюватись, якщо url не заданий явно.

[[global]]
[cols="5*",options="header"]
.global object
|===
|Поле|Тип|Значення за замовчуванням|Приналежність|Призначення

|`geoServer`
|bool
|`false`
|Registry helmfile.yaml
|Поле для вказання, чи має бути розгорнута _підсистема управління геоданими_.

|`deploymentMode`
|string
|`development`
|Registry values.yaml

Cluster values.yaml
|Поле для вказання режиму розгортання реєстру. Дозволені значення `development` або `production`.

|`excludePortals`
|list
|Пусте значення.
|Registry values.yaml
|Поле для вказання, які портали не мають бути розгорнуті. За замовчуванням розгортаються всі. Дозволені значення в листі `citizen-portal`, `officer-portal`, `admin-portal`.

|`computeResources`
|<<computeResources,computeResources>>
|Пусте значення.
|Registry values.yaml
|Поле для вказання, які портали не мають бути розгорнуті. За замовчуванням розгортаються всі.

|===

WARNING: Переведення deploymentMode дозволяється тільки з `development` в `production`, навпаки заборонено.

[[computeResources]]
[cols="4*",options="header"]
.computeResources object
|===
|Поле|Тип|Значення за замовчуванням|Призначення

|`instanceCount`
|integer
|`2`
|Поле для вказання кількості віртуальних машин для розгортання реєстру з типом інфраструктури `AWS` або `vSphere`.

|`awsInstanceType`
|string
|`r5.2xlarge`
|Поле для вказання типу AWS EC2-інстансу для розгортання реєстру з типом інфраструктури `AWS`.

|`awsSpotInstance`
|bool
|`false`
|Поле для вказання spot типу для AWS EC2-інстансу реєстру

|`awsSpotInstanceMaxPrice`
|string
|Пусте значення
|Поле для вказання spot типу для AWS EC2-інстансу реєстру

|`awsInstanceVolumeType`
|string
|`gp3`
|Поле для вказання типу системного диска AWS EC2-інстансу для розгортання реєстру з типом інфраструктури `AWS`.

|`instanceVolumeSize`
|integer
|`80`
|Поле для вказання розміру системного диска віртуальної машини реєстру з типом інфраструктури `AWS` або `vSphere`.

|`vSphereInstanceCPUCount`
|integer
|`8`
|Поле для вказання кількості vCPU віртуальної машини реєстру з типом інфраструктури `vSphere`.

|`vSphereInstanceCoresPerCPUCount`
|integer
|`1`
|Поле для вказання кількості ядер у кожного vCPU віртуальної машини реєстру з типом інфраструктури `vSphere`.

|`vSphereInstanceRAMSize`
|integer
|`32768`
|Поле для вказання кількості RAM віртуальної машини реєстру з типом інфраструктури `vSphere`.

|===

=== Компоненти системи та їх призначення в рамках дизайну рішення

[cols="3*",options="header"]
.Компоненти підсистеми
|===
|Компонент|Службова назва|Призначення / Суть змін

|-
|control-plane-gerrit
|-

|-
|edp-library-pipelines(stages)-fork
|-

|-
|control-plane-console
|-

|===

== Високорівневий план розробки
=== Технічні експертизи
* _DevOps_
* _FE_

=== План розробки
