:toc-title: ЗМІСТ
:toc: auto
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
//:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:
= Платформа для розгортання та супроводження державних електронних реєстрів

== Що таке Платформа?

_Платформа_ -- це інструмент (інформаційна система) для швидкого створення, моделювання, розгортання та керування державними реєстрами для ефективного надання державних послуг в режимі онлайн. Платформа дозволяє досягати оптимального балансу між вимогами безпеки даних, швидкістю розгортання, вартістю володіння реєстрами та обміном даними з іншими реєстрами.

.Контекстна діаграма Платформи
image::arch:architecture/ddm-platform-context.svg[]

== Проблематика

=== Поточна ситуація з реєстрами в Україні

В Україні існує понад 350 державних реєстрів, які належать різним власникам. Кожен реєстр створюється та підтримується за допомогою окремої команди та експлуатується у власній інфраструктурі (апаратне забезпечення чи хмарна).

Поточну ситуацію можна класифікувати як [.underline]#децентралізовану# та [.underline]#нерегульовану#: ::

Під [.underline]#децентралізованою# слід розуміти зберігання даних в окремих власників на окремій інфраструктурі, що є дуже важливим моментом з огляду несення відповідальності за збір, збереження та використання даних.
+
Під [.underline]#нерегульованою# слід розуміти, що не існує можливості гарантувати коректну взаємодію між реєстрами через захищені з'єднання, виконання вимог щодо збереження даних, повторне використання підходів та заощадження ресурсів.

=== Концепція платформи для розгортання реєстрів в Україні та розв'язання проблеми

З огляду на поточну ситуацію та можливі ризики з визначенням відповідальності за збереження даних, Платформа дозволяє перейти до [.underline]#децентралізованого# та [.underline]#регульованого# підходу.

Такий підхід гарантує збереження визначеного власника даних, і, своєю чергою, збереження відповідальності за дані. З іншого боку -- це активує можливість розробки та модернізації платформи для створення реєстрів як комплексу програмно-апаратних засобів для імплементації вимог, що сформовані та регульовані Міністерством цифрової трансформації України.

== З чого почати?

Цей сайт є базою знань, яка допоможе вам краще зрозуміти продукт.

Меню навігації містить такі основні розділи за призначенням: ::

* Хочете дізнатися про нові розробки та поліпшення, переходьте до секції xref:release-notes:overview.adoc[].

* Якщо ви адміністратор інфраструктури платформи, адміністратор безпеки, або доступу, зверніться до розділу xref:admin:admin-overview.adoc[].

* Якщо ви з команди розробки та супроводу реєстрів, які розгортаються на базі платформи, зверніться до розділу xref:registry-develop:overview.adoc[].

* Якщо ви адміністратор реєстру, або адміністратор регламенту, зверніться до розділу xref:registry-develop:registry-admin/index.adoc[].

* Якщо ви моделювальник даних, працюєте зі структурами операційних даних та декларативним описом моделі, формуєте аналітичну звітність, зверніться до розділу xref:registry-develop:data-modeling/index.adoc[].

* Якщо ви моделювальник бізнес-процесів, UI-форм для бізнес-процесів, працюєте з BPMN, DMN та JSON-структурами, зверніться до розділу xref:registry-develop:bp-modeling/index.adoc[].

* Для поглиблення знань щодо роботи зі структурами регламенту, для вас розроблено спеціальний xref:registry-develop:study-project/index.adoc[]. Він містить перелік навчальних та контрольних завдань для розвитку практичних навичок моделювання регламенту.

* Якщо ви посадова особа, або отримувач послуг реєстру, працюєте з особистим кабінетом у рамках бізнес-процесів, зверніться до розділу xref:user:overview.adoc[].

* Якщо ви розробник, архітектор, або просто технічний гуру, зверніться до секції xref:arch:architecture/overview.adoc[].

* Цікавлять готові відповіді на часті запитання? Зверніться до розділу xref:faq:faq.adoc[].

// INTRODUCTION SECTION

////

METAINFO

Документація
Цей документ є адаптацією Epam SAD 2.6 і містить технічний опис системи розгортання електронних реєстрів.

=== Структура документа

Документація розділена на два типи:

- Документація яка обмежена описом одного конкретного компонента системи (секція *Компоненти* цього документу) - така документація має лежати в тому ж репозиторії, що і код, і підтримуватись всіма членами команди та контребьютерами в данний репозиторій

- Документація що описує міжкомпонентну взаємодію, загальні характеристи платформи які стосуються кожного компонента або не належать жодному - така документація зберігається як код в окремому https://gitbud.epam.com/mdtu-ddm/general/ddm-architecture[репозиторії]
////
