[glossary]
= Глосарій та Акроніми Платформи

[glossary]
API Платформи реєстрів:: <<API-Фабрики-даних>>
[[API-Фабрики-даних]]API Фабрики даних:: Програмний інтерфейс фабрики даних, доступний для інших компонентів Платформи, який надає набір функцій для взаємодії з даними реєстру.

BPMN (Business Process Model and Notation):: Нотація і модель бізнес-процесів -- система умовних позначень для моделювання бізнес-процесів.

CC (Competency Center):: Команда, яка відповідає за консультації команд розробки реєстрів і агрегацію запитів щодо нової функціональності та наявним помилкам (bugs).

СR (Custom Resource):: Ресурс для розширення OpenShift API, який не обов'язково доступний із коробки при встановленні OpenShift, а представляє собою налаштування конкретного OpenShift-екземпляра.

[[Control-Plane]]Control Plane:: Сукупність компонентів Платформи, що забезпечує спрощення керування центральними компонентами Платформи, дозволяє керувати реєстрами та агрегує посилання до усіх WEB API центральних компонентів.

DMN (Decision Model and Notation):: Нотація для моделювання бізнес-правил за допомогою таблиць прийняття рішень.

DNS (Domain Name System):: Розподілена система доменних імен, що перетворює ім'я будь-якого мережевого ресурсу на IP-адресу.

GitOps-підхід:: Спосіб реалізації безперервного розгортання для нативних хмарних додатків. Основна ідея GitOps полягає в тому, що будь-які зміни до конфігурації кластера OpenShift, компонентів кластера та компонентів Платформи відбуваються через внесення змін до конфігурації відповідних компонентів у Git-гілках цих компонентів.

Kong:: Компонент підсистеми управління зовнішнім трафіком та API шлюз.

[#kubernetes]
Kubernetes::
Kubernetes, часто скорочується як *K8s*, -- це відкрита платформа для автоматизації розгортання, масштабування та управління контейнеризованими застосунками.

Low-code:: Підхід до створення, налаштування та модифікації системи та додатків, який практично не вимагає написання програмного коду. У контексті Платформи -- це компоненти, за допомогою яких цей підхід реалізується.

OpenShift:: Система автоматичного розгортання, масштабування та управління застосунками у контейнерах, оркестрована та керована Kubernetes.

RBAC (Role Based Access Control):: Керування доступом на основі ролей. Привілеї не призначаються користувачам безпосередньо, а отримуються ними лише через свою роль (або ролі). Управління індивідуальними правами користувача, по суті, зводиться до призначення йому ролей.

Рілм/Реалм (Realm):: Сутність сервісу управління користувачами та ролями Keycloak. Realm керує набором користувачів, облікових даних, ролей і груп.

[[UI-форма]]UI-форма:: Форма задачі користувача Кабінету для внесення та перегляду даних у рамках виконання бізнес-процесу.

URI (Uniform Resource Identifier):: Уніфікований ідентифікатор ресурсів. Компактний рядок літер, який однозначно ідентифікує окремий ресурс в інтернеті.

Автентифікація:: Перевірка правдивості пред'явленого користувачем ідентифікатора.

Авторизація:: Надання і перевірка прав на здійснення будь-яких операцій в системі.

Адмін-портал:: <<Кабінет-адміністратора-регламентів>>

Адміністративна послуга:: Те саме, що й xref:#information-service[Інформаційна послуга]. Передбачає зміну певного статусу чи інших даних в реєстрі. На Платформі це бізнес-процес, реалізований на рівні окремого реєстру, результатом якого є внесення змін до даних реєстру.

Аналітична БД:: База даних, яка обслуговує аналітичні інструменти, зокрема Redash. Отримує дані реєстру через логічну реплікацію з операційної бази даних. Доступна лише на читання.

[[Аналітичний-звіт]]Аналітичні звіти:: Попередньо налаштовані загальні статистичні дані за реєстром. Побудовані за допомогою сервісу аналітичної звітності Redash. Можуть містити графіки, таблиці, картки показників та примітки щодо ефективності робочого процесу.

Бізнес-процес:: Набір операцій, спрямованих на досягнення певного результату шляхом обробки даних. BPMN-моделі бізнес-процесів є частиною регламенту реєстру.

Версія-кандидат регламенту реєстру::
Версія змін, відгалужена від майстер-версії регламенту, для створення та редагування сутностей, таких як модель даних, процеси, форми тощо. Зміни вносяться через Адміністративний портал до репозиторію registry-regulations. Після перевірки та затвердження, розробники можуть застосувати зміни до майстер-версії, що схоже на об'єднання (merge) гілок у Git.

Витяг:: Документ згенерований в рамках надання інформаційних послуг через бізнес-процеси, який може бути завантажений користувачем, який замовив інформаційну послугу. Представлений окремим шаблоном на рівні регламенту реєстру.

Відкриті дані:: Публічна інформація у форматі, що дозволяє її автоматизоване оброблення електронними засобами, вільний та безоплатний доступ до неї, а також її подальше використання.

Група реєстрів:: Реєстри що належать одному власнику та є спорідненими.

Дані реєстру:: Інформація, що зберігається в базі даних реєстру.

Дашборд:: <<Аналітичний-звіт>>

ДРФО:: Державний реєстр фізичних осіб - платників податків. Використовується у сенсі "код ДРФО" див. <<РНОКПП,РНОКПП>>

Електронний підпис:: В рамках цього документу це КЕП, УЕП, ЕЦП фізичної чи юридичної особи або електронна печатка юридичної особи. Використання КЕП, УЕП, з огляду на ситуацію, залежить від чинних вимог законодавства.

[#endpoint]
Ендпоінт::
Кінцева точка інтеграційної взаємодії, яка дозволяє двом програмам або системам обмінюватися даними. Вона слугує мостом для отримання, відправлення та оновлення інформації між різними компонентами системи або різними системами.

ЕЦП (Електронний цифровий підпис)::  Дані в електронній формі, отримані за результатами криптографічного перетворення, які додаються до інших даних або документів і забезпечують їх цілісність та ідентифікацію автора.

ЄДР:: Єдиний державний реєстр юридичних осіб, фізичних осіб-підприємців та громадських формувань.

ЄДРПОУ:: Код ЄДРПОУ (Єдиного державного реєстру підприємств та організацій України) — унікальний ідентифікаційний номер юридичної особи в Єдиному державному реєстрі підприємств та організацій України.

Запит на внесення змін:: Логічне представлення сукупності змін відносно поточної _майстер-версії_ регламенту, до якого застосовуються перевірки цілісності, якості та інспекції перед безпосереднім застосуванням до _майстер-версії_.

Інсталер ::
Архів програмного забезпечення зі скриптами та Docker-образами для інсталяції, який дозволяє автоматично розгорнути Платформу певної версії на цільовому оточенні (хмарне оточення, або ЦОД), а також оновити Платформу до певної версії (наприклад, `1.9.0` тощо).

Інтерфейс адмін-консолі/ Адмін-консоль:: <<Control-Plane>>

Інформаційна панель:: <<Аналітичний-звіт>>

[#information-service]
Інформаційна послуга::  Бізнес-процес, реалізований на рівні окремого реєстру, результатом якого є отримання даних реєстру у визначеній формі. Передбачає підтвердження того чи іншого статусу у реєстрі. Результатом "Послуги" буде витяг, або підтвердження прав.

[[Кабінет-адміністратора-регламентів]]
Кабінет адміністратора регламентів:: Клієнтський вебдодаток для адміністрування регламенту реєстрів. Інтерфейс дозволяє виконувати необхідну конфігурацію регламенту без володіння глибокими навичками програмування.

Кабінет користувача:: Загальна назва для кабінету отримувача послуг і кабінету посадової особи.
Кабінет отримувача послуг:: Вебінтерфейс для взаємодії з реєстром у вигляді клієнтського додатка кабінету орієнтований на обслуговування громадян.
Кабінет посадової особи:: Веб-інтерфейс для взаємодії з реєстром у вигляді клієнтського додатку кабінету орієнтований на обробку задач посадовою особою.
КЕП (Кваліфікований електронний підпис):: Електронний підпис користувача, що використовується для аутентифікації та підпису внесених ним даних.
Керування кластером (Платформою):: Абстракція в рамках Control Plane, що дозволяє керувати центральними компонентами системи
Компоненти реєстру:: Компоненти Платформи, що встановлюється окремо для кожного реєстру.
Конфігурація реєстру:: Налаштування компонентів реєстру доступне в control plane та репозиторії реєстру відповідно до GitOps-підходу.
Конфіденційні дані:: Дані для доступу до яких потрібна авторизація.
КСЗІ (Комплексна система захисту інформації):: Сукупність організаційних та інженерних заходів та програмно-апаратних засобів, що забезпечують захист інформації в системі.
Майстер-версія регламенту:: <<Мастер-версія-регламенту>>
[[Мастер-версія-регламенту]]Мастер-версія регламенту:: Поточна версія регламенту, розгорнута на екземплярі реєстру.
Модель даних:: Описи змісту, структури та обмежень цілісності, які використовуються для створення та підтримки бази даних реєстру. Представлена визначенням у liquibase форматі на рівні регламенту реєстру.
Об'єкти (Приналежність даних)::  Будь-яка сутність, якою володіє суб'єкт.
Онбординг громадян (отримувачів послуг):: Процес орієнтований на створення всіх необхідних записів у БД для взаємодії користувача з реєстром (профіль користувача, налаштування, призначення ролі користувача)
Операційна БД:: База даних яка обслуговує додатки та сервіси реєстру та зберігає дані реєстру, налаштування, дані бізнес-процесів та інші операційні дані.
Операційне сховище бізнес-процесів:: Реляційне сховище, в якому зберігаються розгорнуті моделі бізнес-процесів, поточний стан виконання екземплярів процесів та породжені ними дані, налаштування авторизацій та загальні налаштування.
Отримувач послуг:: Користувач який взаємодіє з реєстром з метою отримання адміністративних та інформаційних послуг. Ця роль може призначатися фізичній особі, представнику ФОП або юридичної особи. Системна роль.
Пакетне завантаження (імпорт користувачив):: Процес створення великої кількості користувачів-посадових осіб в реєстрі шляхом імпорту з CSV файлу.
Первинна автентифікація / автореєстрація громадян (отримувачів послуг):: Процес створення користувача - отримувача послуг реєстру та встановлення профілю взаємодії з кабінетом отримувача послуг на основі даних отриманих з особистого ключа КЕП та даних, отриманих у результаті інтеграції з ЄДР.
[[Персональні-дані]]Персональні дані:: Відомості чи сукупність відомостей про фізичну особу, яка ідентифікована або може бути конкретно ідентифікована. Класифікація даних як персональних відбувається на рівні створення моделі даних реєстру, що застосовує відповідні механізми обробки і доступу.
Платформа (IC «Платформа»):: Розгорнута інформаційна система реєстру, яка надає органам влади можливість створювати та в рамках повноважень вести реєстри за моделлю SaaS “Реєстр як сервіс”. Передбачається розгортання Платформи як в хмарі, так і на базі власного ЦОД, а також розгортання Платформи як для одного реєстру, так і для групи реєстрів.
Платформа ведення реєстрів:: OpenShift кластер зі встановленими компонентами необхідні для створення та ведення реєстрів.
Платформа даних:: <<Фабрика-даних>> (Дата-фабрика)
Платформні ключі цифрового підпису:: Ключі що використовуються для інтеграції з id.gov.ua.
Платформні компоненти:: <<Центральні-компоненти>>
Посадова особа:: Представник державного органу, що взаємодіє із реєстром у рамках виконання своїх службових обов'язків. Системна роль.
Послуга:: Один або декілька бізнес-процесів в реєстрі спрямовані на опрацювання запиту особи.
Публічно доступні дані:: Дані для доступу до яких не потрібна авторизація
Регламент/правила реєстру::  Набір моделей даних, бізнес-процесів, налаштувань, за якими реєстр буде реалізовувати свої функції.
Реєстр:: Спеціалізований інформаційний ресурс, призначений для зберігання та обробки юридично важливої інформації про людей, їх права та обов'язки, а також майно та ресурси.
Реєстровий пайплайн:: Процес що виконує застосування конфігурації реєстру.
Реєстрові  ключі цифрового підпису:: Ключі що використовуються для підписання трансформованих даних бізнес форм і підписування витягів.
Рейт-ліміти:: Обмеження кількості запитів від одного користувача.

Ресурс::
xref:#endpoint[Ендпоінт]

[[РНОКПП]]РНОКПП (Реєстраційний номер облікової картки платника податків):: Елемент Державного реєстру фізичних осіб України (ДРФО) , який надається фізичним особам-платникам податків та інших обов'язкових платежів та зберігається за ними протягом усього їхнього життя.
Розгортання регламенту реєстру:: Процедура створення або оновлення сервісів реєстру, бізнес-процесів та структури бази даних реєстру згідно з регламентом реєстру. 
Ролі регламенту:: Ролі які створюються під час розгортання регламенту реєстру та налаштовуються в регламенті реєстру.
Роль користувача:: Системні ролі та ролі регламенту, які призначені користувачу. 
СЕВДЕІР / Трембіта:: Система електронної взаємодії державних електронних інформаційних ресурсів.
Системні ролі:: Ролі які створюються Платформою під час розгортання реєстру або встановлення Платформи.
Суб’єкти (Приналежність даних):: будь-яка фізична або юридична особа, що має право власності над об'єктом.
Схема UI-форми:: Формальний опис структури, полів та валідаційних правил UI-форми. Представлена як файл на рівні регламенту реєстру.
Сховище історичних даних бізнес-процесів:: База даних в якій зберігаються значущі історичні події виконання бізнес-процесів (історія ініційованих користувачем та завершених бізнес-процесів та виконаних задач користувача).
Сховище проміжних даних бізнес-процесів:: Розподілене сховище пар ключ-значення, в якому тимчасово зберігаються дані, внесені користувачами через UI-форми задач бізнес-процесів.
[[Фабрика-даних]]Фабрика даних (Дата-фабрика):: Підсистема Платформи відповідальна за збереження даних та надання доступу до них.
Форма:: <<UI-форма>>
[[Центральні-компоненти]]Центральні компоненти::
Компоненти системи, що спільно використовуються усіма реєстрами та існують в єдиному екземплярі на кластері.
Цифрові документи:: Файли вкладення які можуть бути завантажені, вивантажені та переглянуті користувачами через UI-форми задач бізнес-процесів. Зберігаються в об'єктному сховищі реєстру. Зміст цифрових документів не є об'єктом виконання операцій на рівні бізнес-процесів.
ЦОД:: Центр обробки даних (Data center).
ШБО "Трембіта":: Шлюз Безпечного Обміну — захищений інтерфейс для електронної взаємодії між державними системами, який розгортається в межах Платформи реєстрів як сервіс і дозволяє використовувати власні ресурси для отримання інформації із зовнішніх систем.
