@startuml

title Діаграма взаємодії компонентів платформи

package "DDM platform Install" as ddm_platform_install{
  [OKD Install] as denovo_okd_install
  [DDM Core Install] as ddm_core_install
}
ddm_core_install -down-> infra_components: розгортає Nexus, Ceph та Platform Keycloak

ddm_core_install -down-> ddm_cp_install: розгортає компоненти Control Plane

package "Infra Components" as infra_components {
    [catalog-source]
    [monitoring ]
    [storage ]
    [logging ]
    [service-mesh ]
    [backup-management ]
    package "user-management" as user-management_infra {
        [groupsync-operator]
        [keycloak-operator]
        [digital-signature-ops]
        [keycloak]
        [hashicorp-vault]
    }
    [control-plane-nexus]
    [external-integration-mocks]
    package "Поза Openshift" #DDDDDD {
      [platform-vault]
      [platform-minio]
    }
}

package "DDM Control Plane (CP)" as ddm_cp_install {
  [keycloak-operator ]
  [codebase-operator ]
  [control-plane-console ]
  [control-plane-gerrit] as ddm_gerrit
  [control-plane-jenkins]
  [infrastructure-jenkins-agent]
}

denovo_okd_install -[hidden]down-> infra_components
ddm_gerrit -down-> infra_components : містить в собі композитний репозиторій """cluster-mgmt""", який визначає конкретні версії інфраструктурних компонентів
ddm_gerrit -[hidden]down-> infra_components
ddm_gerrit -down-> registry_components : містить в собі шаблони реєстрів """registry-tenant-template-*""", які визначають конкретні версії компонентів реєстру

package "Registry Regulations" as registry_regulations {
  [registry-regulation-template-minimal]
  [registry-regulation-template-recommended]
}

package "Registry Components" as registry_components {
  [bpms]
  [officer-portal]
  [jenkins-operator]
  [dataplatform-jenkins-agent]
  [gerrit-operator]
  [codebase-operator]
  [user-process-management]
  [bp-admin-portal]
  [user-task-management]
  [digital-signature-ops]
  [kong]
  [form-management]
  [admin-portal]
  [redash-chart]
  [pg-exporter-chart]
  [citus]
  [strimzi-kafka-operator]
  [nexus]
  [keycloak-operator]
  [kafka-schema-registry]
  [citizen-portal]
  [user-settings-service-persistence]
  [user-settings-service-api]
  [bp-webservice-gateway]
  [digital-document-service]
  [hashicorp-vault]
  [excerpt-service-api]
  [excerpt-worker]
  [report-exporter]
  [registry-configuration]
  [process-history-service-api]
}

ddm_gerrit -down-> registry_regulations : створює репозиторій """registry-regulations-template"""

legend
 Кожен компонент є окремим git резозиторієм
end legend

@enduml