@startuml
actor "Розробник платформи" as devops order 10
participant "gitserver" as gitserver  order 30
box "Тестовий кластер"
    participant "control-plane-gerrit" as control_plane_gerrit  order 35
    participant "control-plane-jenkins" as control_plane_jenkins  order 40
    participant "OKD cluster" as test_cluster  order 50
end box
box "CICD Кластер" #LightBlue
  participant "CICD Jenkins" as cicd_jenkins  order 60
  participant "CICD Docker Registry" as cicd_docker_registry  order 70
  participant "CICD Nexus" as cicd_nexus  order 80
end box

autonumber

title Діаграма послідовностей по розробці централізованих компонентів платформи та пакету для інсталяції

group Розробка інфра компоненту
  hnote over gitserver: e.g. logging
  devops -> control_plane_gerrit: "Commit в репозиторій gerrit компонента на тестовому кластері"
  activate control_plane_gerrit
    control_plane_gerrit -> control_plane_jenkins: "Запуск CD джоби cluster-mgmt для тестування та\n застосування зміни"
  deactivate control_plane_gerrit
  activate control_plane_jenkins
    control_plane_jenkins -> test_cluster: "Застосування змін"
  deactivate control_plane_jenkins
  devops -> test_cluster: "Тестування"
  devops <-- test_cluster: "Розуміння, що зміни можна переносити у master гілку основного gitserver"
  devops -> gitserver: "Merge змін в master гілку основного gitserver"
end

group Збірка інсталяції для цільового кластеру
  devops -> cicd_jenkins: Запуск control-plane-versioner і вибір Stage CR з потрібними версіями компонентів
  devops -> gitserver: Commit мерж реквесту в control_plane_gerrit репозиторій, створеного control-plane-versioner
  activate gitserver
    gitserver -> cicd_jenkins: Запуск CI джоби для control_plane_gerrit
    activate cicd_jenkins
        cicd_jenkins -> cicd_docker_registry: "Публікація control_plane_gerrit docker image"
        gitserver <-- cicd_jenkins: "Тегування коміту згідно EDP версіонування"
    deactivate cicd_jenkins
  deactivate gitserver
  devops -> gitserver: Commit мерж реквесту в control-plane-installer репозиторій, створеного control-plane-versioner
  devops -> gitserver: Оновлення версії control_plane_gerrit в репозиторії control-plane-installer
  activate gitserver
    gitserver -> cicd_jenkins: Запуск CI джоби для control-plane-installer
    activate cicd_jenkins
      cicd_jenkins -> cicd_nexus: "Публікація control-plane-installer zip архіву"
      gitserver <-- cicd_jenkins: "Тегування коміту згідно EDP версіонування"
    deactivate cicd_jenkins
    devops <-- gitserver: "Версія інсталяційного пакету, що можна скачати у Nexus"
  deactivate gitserver
end


@enduml