= Обмеження доступу до SOAP інтерфейсів з ШБО Трембіта

Як адміністратор реєстру, я хочу обмежувати доступ до SOAP API інтерфейсів, що використовуються ШБО Трембіта

== Загальний опис
Реєстрові компоненти _bp-webservice-gateway_ та _registry-soap-api_ не мають механізму аутентифікації та авторизації та
призначені для виклику тільки через ШБО Трембіта. Для безпечного використання SOAP API інтерфейсів, адміністратору
необхідно надати можливість дозволяти комунікацію тільки з обмеженого переліку IP-адрес.

=== Ролі користувачів
* Технічний адміністратор реєстру

== Функціональні сценарії
* Обмеження доступу до SOAP API реалізованих у двох сервісах _bp-webservice-gateway_ та _registry-soap-api_

== Загальні принципи та положення
* На інтерфейсі створення та редагування реєстру адмін-консолі є розділ "ШБО Трембіта"
* Присутня можливість вказати перелік IP-адрес ШБО Трембіта, з яких буде дозволений доступ до _bp-webservice-gateway_
та _registry-soap-api_
* Зі всіх інших IP-адрес доступ до роутів _bp-webservice-gateway_ та _registry-soap-api_ обмежений
* Дозволено введення тільки IP-адрес, а не підмереж (CIDR)
* Кількість IP-адрес обмежена 10
* Внесені IP-адреси повинні перевірятись на що це дійсно валідна IP-адреса без маски підмережі на рівні адмін-консолі та
Jenkins-пайплайна
* Технічний адміністратор відповідальний за коректність налаштувань та що за внесеними адресами дійсно Трембіта
* Якщо перелік `ipList` не містить жодної IP-адреси, то доступу до SOAP API немає взагалі (роут не створюється)

== Поточне рішення
Комунікація наразі відбувається наступним чином

image::architecture/registry/operational/external-integrations/api-access-from-trembita/trembita-access.svg[trembita-access-restrictions]

При налаштуванні інтеграції з зовнішніми системами, Платформа не знає з яких IP-адрес буде заходити трафік, тому роут `bp-webservice-gateway`
має бути відкритий для всіх. З іншої сторони, ШБО не вміє аутентифікуватись на `bp-webservice-gateway`, тому роут
повинен бути обмежений, так як для SOAP трафіку аутентифікації немає.

== Технічний дизайн рішення
.Верхньорівнева діаграма взаємодії на рівні підсистем
[plantuml, flow, svg]
image::architecture/registry/operational/external-integrations/api-access-from-trembita/soap-api.svg[soap-api-restrictions]

Після внесення IP-адрес в інтерфейсі адмін-консолі, система додає їх в перелік _values.yaml_ в наступному вигляді:

[source,yaml]
----
trembita:
  ipList:
    - 8.8.8.8
    - 8.8.4.4
  registries:
    dracs-registry:
    .....
----

В результаті конфігурації компонентів підсистеми зовнішніх інтеграцій анотація

[source, yaml]
----
metadata:
  annotations:
    haproxy.router.openshift.io/ip_whitelist: 8.8.8.8/32 8.8.4.4/32
----

додається до OpenShift роутів компонентів _bp-webservice-gateway_ та _registry-soap-api_.

IMPORTANT: Анотація додається тільки до OpenShift роутів

.Верхньорівнева діаграма взаємодії на рівні розгортання конфігурації
[plantuml, flow, svg]
image::architecture/registry/operational/external-integrations/api-access-from-trembita/soap-api-trembita.svg[soap-api-restrictions-2]

Додатково OpenShift роут до _bp-webservice-gateway_ стають "path-based" та має наступну конфігурацію:

|===
|Компонент|Хост|Шлях|Сервіс
|bp-webservice-gateway|bp-webservice-gateway-<registry-name>.<dns-wildcard>|/ws|bp-webservice-gateway
|===

.Послідовність конфігурації
[plantuml, config, svg]
----
@startuml
actor "Технічний адміністратор реєстру" as admin
participant "Інтерфейс адмін-консолі" as cp
participant "Система контролю версій\nGerrit" as vcs
participant "Сервіс розгортання\nконфігурацій Jenkins" as jenkins
participant "bp-webservice-gateway" as gateway
participant "registry-soap-api" as soap
admin -> cp: * ввімкнення доступу до API\n*перелік IP-адрес
cp -> cp: валідація IP-адрес
cp --> admin: валідаційне повідомлення
cp -> vcs: оновлення values.yaml
return запит створено та інтегровано
vcs -> jenkins: *перелік IP-адрес
jenkins -> jenkins: валідація IP-адрес
jenkins --> admin: валідаційне повідомлення
jenkins -> gateway: *розгортання конфігурації
jenkins -> soap: *розгортання конфігурації
jenkins --> admin: статус розгортання конфігурації
@enduml
----

Цільовий дизайн має наступний вигляд:

image::architecture/registry/operational/external-integrations/api-access-from-trembita/trembita-access-to-be.svg[soap-api-restrictions]

=== Орієнтовні макети дизайну адмін-консолі

Актуальні макети можна знайти за https://www.figma.com/file/mWTVRcPrvFwsek4o4eJlFp/05-Admin-Console?node-id=3386%3A38221&t=h902L3o4H6xHSaxT-0[посиланням]

=== Компоненти реєстру та їх призначення в рамках дизайну рішення
|===
|Компонент|Службова назва|Призначення / Суть змін
|API-шлюз для викликів БП зовнішніми системами|bp-webservice-gateway|Додання анотації / шляху
|API-шлюз для читання даних реєстру зовнішніми системами|registry-soap-api|Додання анотації
|Веб-інтерфейс управління Платформою та реєстрами|control-plane-console|Зміни в інтерфейсі користувача
|===

TIP: Registry-soap-api генерується в компоненті service-generation-utility

== План розробки
=== Технічні експертизи
* BE
* DevOps

=== План розробки
* Змінити інтерфейс користувача адмін-консолі відповідно до макетів
* Зберігати внесені IP-адреси в налаштуваннях _values.yaml_ реєстру
* Обробити внесені IP-адреси на рівні чартів компонентів

== Міграція даних
Перед оновленням реєстри які вже використовують ШБО Трембіта, треба в `values.yaml` налаштуваннях прописати IP-адреси Трембіти.
Зробити інструкцію по оновленню URL для `bp-webservice-gateway` в ШБО
== Безпека

=== Бізнес Дані
|===
|Категорія Даних|Опис|Конфіденційність|Цілісність|Доступність
|Технічні дані що містять інформацію з обмеженим доступом | Налаштування системи, конфіги, параметри що містять інформацію з обмеженим доступом зміна яких може негативно вплинути на атрибути системи |Середня|Висока|Висока
|===

=== Механізми протидії ризикам безпеки та відповідність вимогам безпеки
|===
Усі ризики було усунено в архітектурному дизайні
|===
