= Атрибут _searchType_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

Атрибут `*searchType*` в елементі `*<ext:column>*` вказує на тип операції, яку необхідно виконати для певної колонки при пошуку в таблиці.

_Атрибут приймає наступні значення:_

* `equal`
* `startsWith`
* `contains`
* `in`
* `notIn`
* `between`

[#equal]
== `equal`
`equal` (рівність) повертає значення, що мають точну відповідність (дорівнюють) заданим.

.XML-схема
[source, xml]
----
<ext:createSearchCondition name="search_condition">
        <ext:table name="table_one">
            <ext:column name="name" alias="to_name" searchType="equal"/>
            <ext:column name="type"/>
            <ext:function name="count" alias="cnt" columnName="uuid"/>
        </ext:table>
</ext:createSearchCondition>
----

.Опис таблиці `table_one`
--
* `name` -- назва поля
* `type` -- тип поля
* `uuid` -- унікальний ідентифікатор
--

[NOTE]
====
[%collapsible]
.Для чого потрібна функція `count`?
=====
Елемент `<ext:function>` в XML-схемі не виконує функцію пошуку чи фільтрації даних.

Функція `count` в SQL використовується для підрахунку кількості рядків у вибірці, яку ви отримуєте із запита. У нашому прикладі `<ext:function name="count" alias="cnt" columnName="uuid"/>`, функція `count` функція `count` підраховує кількість записів у стовпці `uuid` і повертає це число під псевдонімом `cnt`.

Ось як вона працює:

* `name="count"` вказує на те, що ви використовуєте функцію `count`.
* `alias="cnt"` вказує псевдонім для результату обчислення, який можна буде використовувати для подальших посилань на цей результат.
* `columnName="uuid"` вказує стовпець, у якому ви хочете підрахувати кількість записів.

Наприклад, якщо у стовпці `uuid` має бути 10 записів, то результатом цієї функції буде число 10, яке можна використовувати в подальших операціях чи виводити як результат запита.
=====
====

.SQL-скрипт (_пошуковий запит_)
[source,sql]
----
SELECT name, type FROM table_one
WHERE name = 'значення_пошуку'
-- Пошук за точною відповідністю у полі "name" таблиці "table_one".
----


.HTTP-запит із параметром пошуку для операції `equal`
[source,bash]
----
GET https://.../search-condition?name=значення_пошуку&type=...
----

Цей HTTP-запит виконує пошук у ресурсі `https://.../search-condition` за точною відповідністю назви (поля `name`) та типу (поля `type`) заданим значенням. Кожен параметр пошуку вказується як окремий параметр запита, що робить його більш інформативним та зрозумілим.


.HTTP-запит із референтними значеннями
[source,bash]
----
GET https://api.example.com/search-condition?name=John&type=Employee
----

У цьому прикладі:

* `https://api.example.com/search-condition` -- базовий URL та ресурсу та ендпоінт, де виконується пошук.
* `name=John` -- параметр пошуку за назвою, де шукається значення `John` у полі `name`.
* `type=Employee` -- параметр пошуку за типом, де шукається значення `Employee` у полі `type`.

[#starts-with]
== `startsWith`

`*startsWith*` повертає значення зі вказаним префіксом, тобто значення, які "починаються із" заданої умови.

._XML-схема_
[source, xml]
----
<ext:createSearchCondition name="subject_name_starts_with">
    <ext:table name="consent_table">
        <ext:column name="consent_id" fetchType="entity" />
        <ext:column name="document_copy" />
        <ext:column name="legal_entity_name" sorting="asc" searchType="startsWith" />
        <ext:column name="subject_id"/>
    </ext:table>
</ext:createSearchCondition>
----

{empty}

.Опис таблиці `consent_table`
--
* `consent_id` -- ідентифікатор згоди, який забезпечує зв'язок з іншою таблицею (_тип вибірки:_ `entity`).
+
TIP: Детальніше про атрибут `fetchType` та сценарії його застосування див. у розділі xref:registry-develop:data-modeling/data/physical-model/liquibase-ddm-ext.adoc#nested-structures[Використання вкладених структур в таблицях БД реєстру за вказаним параметром].
* `document_copy` -- сканована копія документа.
* `legal_entity_name` -- назва юридичної особи, яка може бути використана для пошуку за типом "починається з".
* `subject_id` -- ідентифікатор суб'єкта.
--


.SQL-скрипт (_пошуковий запит_)
[source,sql]
----
SELECT legal_entity_name FROM consent_table
WHERE legal_entity_name LIKE 'значення_пошуку%'
ORDER BY legal_entity_name ASC;
----

--
У цьому запиті:

* Вибрано назви юридичних осіб (`legal_entity_name`) з таблиці `consent_table`.
* Пошук виконується за принципом "починається з" для значення `'значення_пошуку'`.
* Результати відсортовано за назвою юридичної особи в алфавітному порядку (за зростанням).
--

.HTTP-запит із параметром пошуку для операції `startsWith`
[source,bash]
----
GET https://.../subject-name-starts-with?legalEntityName=значення_пошуку
----

Цей HTTP-запит використовує метод GET для запиту до сервера з метою отримання результатів, які відповідають критерію пошуку "починається з" для поля `legal_entity_name`.


.HTTP-запит із референтними значеннями
[source,bash]
----
GET https://api.example.com/subject-name-starts-with?legalEntityName=Corp
----

У цьому прикладі:

* `https://api.example.com/subject-name-starts-with` -- це базовий URL ресурсу, де відбувається пошук.
* `legalEntityName=Corp` -- параметр запита, який вказує на пошук юридичних осіб, чиї назви починаються з `Corp`.

[#contains]
== `contains`

`*contains*` повертає значення, які мають збіги із вказаним значенням умови у будь-якому місці рядка (на початку, в середині, в кінці тощо).

.XML-схема
[source, xml]
----
<ext:createSearchCondition name="search_condition" limit="1">
    <ext:table name="table_two" alias="tt">
        <ext:column name="name" alias="tt_name"/>
        <ext:column name="code" searchType="contains"/>
        <ext:function name="sum" alias="sm" columnName="code"/>
    </ext:table>
</ext:createSearchCondition>
----

TIP: Детальніше про атрибут ліміт ви можете дізнатися у секції xref:registry-develop:data-modeling/data/physical-model/liquibase-ddm-ext.adoc#limit-attribute-values[Атрибут _limit_].

.Опис таблиці `table_two`
--
* `name` (alias `tt_name`) -- назва елементу.
* `code` -- код елемента, який може бути використаний для пошуку за типом "містить".
* `sum` -- функція, яка підраховує суму значень у стовпці `code` і повертає це число під псевдонімом `sm`.

[NOTE]
====
[%collapsible]
.Для чого потрібна функція `sum`?
=====
Елемент `<ext:function>` в XML-схемі не виконує функцію пошуку чи фільтрації даних.

Функція `sum` в SQL використовується для підрахунку загальної суми значень у вказаному стовпці вибірці. У нашому прикладі `<ext:function name="sum" alias="sm" columnName="code"/>`, функція `sum` підраховує загальну суму значень у стовпці `code` і повертає цю суму під псевдонімом `sm`.

Ось як вона працює:

* `name="sum"` вказує на те, що ви використовуєте функцію `sum`.
* `alias="sm"` вказує псевдонім для результату обчислення, який можна буде використовувати для подальших посилань на цей результат.
* `columnName="code"` вказує стовпець, у якому ви хочете підрахувати загальну суму значень.

Наприклад, якщо у стовпці `code` є записи зі значеннями 10, 20 та 30, то результатом цієї функції буде число 60, яке можна використовувати в подальших операціях чи виводити як результат запита.
=====
====
--

.SQL-скрипт (_пошуковий запит_)
[source,sql]
----
SELECT name, code FROM table_two
WHERE code LIKE '%значення_пошуку%'
----

--
У цьому запиті:

* Вибрано назви (`name`) та коди (`code`) з таблиці `table_two`.
* Пошук виконується за типом "містить" для значення `'значення_пошуку'`, що може знаходитися в будь-якому місці рядка.
--

.HTTP-запит із параметром пошуку для операції `contains`
[source,bash]
----
GET https://.../search-condition?code=значення_пошуку
----

Цей HTTP-запит використовує метод GET для запита до сервера з метою отримання результатів, які відповідають критерію пошуку "містить" для поля `code`.

.HTTP-запит із референтними значеннями
[source,bash]
----
GET https://api.example.com/search-condition?code=1234AB
----

У цьому прикладі:

* `https://api.example.com/search-condition` -- це базовий URL ресурсу та ендпоінт, де відбувається пошук.
* `code=1234AB` -- параметр запита, який вказує на пошук кодів, які містять `1234AB`.

[#in-not-in]
== `in` | `notIn`

Оператор `*in*` повертає значення, що мають точну відповідність (дорівнюють) заданим значенням у масиві. Подібний до `equal`, але множинний.

Оператор `*notIn*` повертає значення, що _НЕ_ дорівнюють жодному із заданих значень у масиві. Він є протилежним до значення `in` атрибута `searchType`.

=== Проблематика

У контексті обробки `GET`-запитів може виникати проблема, яка полягає в некоректній обробці параметрів, особливо при використанні типів пошуку `in` та `notIn`. Ця проблема впливає не лише на поточну реалізацію, але й може виникати в інших сценаріях використання `GET`-метода.

Основна причина криється в обмеженнях, що існують у способі обробки параметрів у `GET`-запитах. Зокрема, коли значення параметрів містять спецсимволи або використовуються як роздільники, це може призвести до втрати важливої інформації або до некоректної інтерпретації даних запита.

==== Випадки використання

Ця секція надає детальний опис різних сценаріїв, які були виявлені під час тестування, і як кожен з них впливає на обробку запитів.

.Сценарій 1
====
* Запит: `GET /findXXXInYYY?yyy=1,2,3`
* Результат: `List.of("1", "2", "3")`
* Проблема: Коли значення передається через кому, воно розглядається як множина окремих елементів.
====

.Сценарій 2
====
* Запит: `GET /findXXXInYYY?yyy=1&yyy=2&yyy=3`
* Результат: `List.of("1", "2", "3")`
* Проблема: Не виникає, оскільки кожен параметр обробляється окремо.
====

.Сценарій 3
====
* Запит: `GET /findXXXInYYY?yyy=1,2&yyy=2,3&yyy=4,5`
* Результат: `List.of("1,2", "2,3", "4,5")`
* Проблема: Кома в цьому випадку не розглядається як роздільник, а входить до складу значення.
====

==== Рішення та рекомендації

Платформа підтримує вдосконалений механізм обробки запитів. Тепер система генерує два типи ендпоінтів на кожний створений критерій пошуку:

* `GET`
* `POST`

{empty}

.Випадки використання методів `GET` та `POST`
[cols="3,1,5", options="header"]
|===
| Сценарій | Метод | Рекомендації

.2+| Виклик API зовнішніми системами
| `POST`
| Використовуйте для складних пошукових умов, зокрема у випадках з `in`/`notIn` тощо.
| `GET`
| Використовуйте для простих пошукових умов.

.2+| Виклик публічних API реєстру
| `POST`
| Використовуйте для складних пошукових умов, зокрема у випадках з `in`/`notIn` тощо.
| `GET`
| Використовуйте для простих пошукових умов.

| Виклик Фабрики даних із делегатів бізнес-процесу
| `POST`
| Використовуються _за замовчуванням_. На цю поведінку вплинути неможливо.

| Виклик Фабрики даних із форм бізнес-процесу
| `GET`
| Використовуються _за замовчуванням_. На цю поведінку вплинути неможливо.
|===


=== Приклади запитів

==== Сценарій 1: простий пошук за віком

.XML-схема
====
[source, xml]
----
<ext:createSearchCondition name="simple_age_search">
    <ext:table name="users">
        <ext:column name="first_name" returning="true"/>
        <ext:column name="last_name" returning="true"/>
        <ext:column name="user_age" searchType="in"/>
    </ext:table>
</ext:createSearchCondition>
----
====

Ця XML-схема визначає структуру пошукової умови для таблиці `users`, де поля `first_name`, `last_name` та `user_age` використовуються для визначення результатів пошуку.

.Опис таблиці `users`
[cols="2,5", options="header"]
|===
| Стовпець | Опис

| `first_name`
| Ім'я користувача, яке повертається як результат.

| `last_name`
| Прізвище користувача, яке також повертається як результат.

| `user_age`
| Вік користувача, який може бути використаний для множинного пошуку за допомогою оператора `in`.
|===

TIP: Детальніше про атрибут `returning` ви можете дізнатися у секції xref:registry-develop:data-modeling/data/physical-model/liquibase-ddm-ext.adoc#returning-attribute-values[Атрибут _returning_].
--

.SQL-скрипт (_пошуковий запит_)
====
[source,sql]
----
SELECT first_name, last_name FROM users
WHERE user_age IN (25, 30, 35)
----
====

Цей SQL-скрипт демонструє, як виконується пошук за віком в базі даних.

--
У цьому запиті: ::

* Вибрані імена (`first_name`) та прізвища (`last_name`) користувачів з таблиці `users`.
* Пошук виконується за віком (`user_age`), який повинен бути одним зі значень, вказаних у множині `(25, 30, 35)`.
--

.HTTP GET-запит із використанням оператора `in`
[tabs]
====

HTTP::
+
[source,http]
----
GET /simple-age-search?userAge=25,30,35 HTTP/1.1
Host: api.example.com
----
+
Цей HTTP-запит використовує метод `GET` для запита до сервера з метою отримання результатів, які відповідають критерію пошуку "знаходяться у списку" для поля `user_age`.
+
У цьому HTTP-запиті:

* `GET` -- метод запита, використаний для отримання даних.
* `/simple-age-search?userAge=25,30,35` -- шлях до ресурсу на сервері, включаючи параметр запита `userAge` зі значеннями `25, 30, 35`, який вказує на пошук користувачів з віком 25, 30 або 35 років.
* `HTTP/1.1` -- версія протоколу HTTP.
* `Host: api.example.com` -- заголовок, що вказує хост або домен, де знаходиться ресурс.

cURL::
+
[source,curl]
----
curl -X GET "https://api.example.com/simple-age-search?userAge=25,30,35"
----
+
Ця команда використовує *cURL*, утиліту командного рядка для відправки HTTP-запитів, з методом `GET` для запита даних із сервера. Вона запитує інформацію за вказаним URL, де `userAge=25,30,35` визначає параметри запита.
+
У цьому HTTP-запиті:

* `GET` -- метод запита, використаний для отримання даних.
* `https://api.example.com` -- це базовий URL ресурсу, де відбувається пошук.
* `/simple-age-search` -- шлях до ресурсу на сервері (ендпоінт).
* `?userAge=25,30,35` -- параметр запита `userAge` зі значеннями `25, 30, 35`, який вказує на пошук користувачів за віком 25, 30 або 35 років.
====


.HTTP POST-запит із використанням оператора `in`
[tabs]
====

HTTP::
+
[source,http]
----
POST /simple-age-search HTTP/1.1
Host: api.example.com
Content-Type: application/json

{
  "userAge": [25, 30, 35]
}
----
+
Цей HTTP-запит використовує метод `POST` для відправки даних до сервера з метою отримання результатів, які відповідають критерію пошуку "знаходяться у списку" для поля `user_age`.
+
У цьому HTTP запиті:

* `POST` -- метод запита, використаний для відправки даних на сервер.
* `/simple-age-search` -- шлях до ресурсу на сервері (ендпоінт).
* `HTTP/1.1` -- версія протоколу HTTP.
* `Host: api.example.com` -- заголовок, що вказує домен, де знаходиться ресурс.
* `Content-Type: application/json` -- заголовок, що вказує на тип контенту, який передається у тілі запита.
* Тіло запита містить JSON-об'єкт із масивом значень: `{"userAge": [25, 30, 35]}`. Параметри вказують на пошук користувачів з віком 25, 30 або 35 років. Такий формат дозволяє точніше визначити умови пошуку та уникнути проблем з інтерпретацією складних параметрів, на відміну від методу `GET`.

cURL::
+
[source,curl]
----
curl -X POST "https://api.example.com/simple-age-search" \
     -H "Content-Type: application/json" \
     -d '{"userAge": [25, 30, 35]}'
----
+
Ця команда використовує *cURL*, утиліту командного рядка для відправки HTTP-запитів, з методом `POST` для запита даних із сервера.
+
У цій cURL-команді:

* `-X POST` вказує на використання метода `POST`.
* `https://api.example.com` -- це базовий URL ресурсу, де відбувається пошук.
* `/simple-age-search"` -- шлях до ресурсу на сервері (ендпоінт).
* `-H "Content-Type: application/json"` додає заголовок, який вказує, що тіло запиту містить JSON.
* `-d '{"userAge": [25, 30, 35]}'` встановлює дані, які будуть відправлені у тілі запита. У цьому випадку -- це JSON-об'єкт із масивом значень для `userAge`, що вказує на пошук користувачів з віком 25, 30 або 35 років.
====
--

==== Сценарій 2: складніший пошук

.XML-схема
====
[source, xml]
----
<ext:createSearchCondition name="advanced_search">
    <ext:table name="users">
        <ext:column name="first_name" returning="true"/>
        <ext:column name="last_name" returning="true"/>
        <ext:column name="user_age" searchType="in"/>
        <ext:column name="location" searchType="equal"/>
        <ext:column name="is_active" searchType="equal"/>
    </ext:table>
</ext:createSearchCondition>
----
====

.Опис таблиці `users`
[cols="2,5", options="header"]
|===
| Стовпець   | Опис

| `first_name`
| Ім'я користувача, яке повертається як результат.

| `last_name`
| Прізвище користувача, яке також повертається як результат.

| `user_age`
| Вік користувача, який може бути використаний для множинного пошуку за допомогою оператора `in`.

| `location`
| Місцеперебування користувача, яке використовується для точного пошуку.

| `is_active`
| Статус активності користувача, який використовується для точного пошуку.
|===

TIP: Детальніше про атрибут `returning` ви можете дізнатися у секції xref:registry-develop:data-modeling/data/physical-model/liquibase-ddm-ext.adoc#returning-attribute-values[Атрибут _returning_].
--

.SQL-скрипт (_пошуковий запит_)
====
[source,sql]
----
SELECT first_name, last_name FROM users
WHERE user_age IN (25, 30, 35) AND location = 'Kyiv' AND is_active = true
----
====

Ця XML-схема визначає структуру пошукової умови для таблиці users, включаючи поля для віку, місцеперебування та статусу активності.

--
У цьому запиті: ::

* Вибрані імена (`first_name`) та прізвища (`last_name`) користувачів з таблиці `users`.
* Пошук виконується за кількома параметрами: віком (`user_age`), який повинен бути одним зі значень у множині `(25, 30, 35)`, місцеперебування (`location`) та статусом активності (`is_active`).
--

.HTTP GET-запит із використанням операторів `in` та `equal`
[tabs]
====

HTTP::
+
[source,http]
----
GET /advanced-search?userAge=25,30,35&location=Kyiv&isActive=true HTTP/1.1
Host: api.example.com
----
+
Цей HTTP-запит використовує метод `GET` для запита до сервера з метою отримання результатів, які відповідають критеріям пошуку за декількома умовами: віком (`user_age`), місцеперебуванням (`location`) та статусом активності (`is_active`).
+
У цьому прикладі:

* `GET` -- метод запита, використаний для отримання даних.
* `/advanced-search` -- шлях до ресурсу на сервері (ендпоінт).
* `?userAge=25,30,35&location=Kyiv&isActive=true` -- параметри запита, розділені амперсандом (`&`).
* `HTTP/1.1` -- версія протоколу HTTP.
* `Host: api.example.com` -- заголовок, що вказує домен, де знаходиться ресурс.

cURL::
+
[source,curl]
----
curl -X GET "https://api.example.com/advanced-search?userAge=25,30,35&location=Kyiv&isActive=true"
----
+
Ця команда *cURL* використовує `-X GET` для вказівки на метод запита `GET` і включає повний URL з параметрами запита.
+
У цій cURL-команді:

* `-X GET` вказує на використання метода `GET`.
* `api.example.com` --  це базовий URL ресурсу, де відбувається пошук.
* `/advanced-search` -- шлях до ресурсу на сервері (ендпоінт).
* `?userAge=25,30,35&location=Kyiv&isActive=true` -- параметри запита, розділені амперсандом (`&`).
====

.HTTP POST-запит із використанням операторів `in` та `equal`
[tabs]
====

HTTP::
+
[source,http]
----
POST /advanced-search HTTP/1.1
Host: api.example.com
Content-Type: application/json

{
  "userAge": [25, 30, 35],
  "location": "Kyiv",
  "isActive": true
}
----
+
Цей HTTP-запит використовує метод `POST` для відправки даних до сервера з метою отримання результатів, які відповідають критеріям пошуку за декількома умовами: віком (`user_age`), місцеперебуванням (`location`) та статусом активності (`is_active`).
+
У цьому прикладі:

* `POST` -- метод запита, використаний для відправки даних на сервер.
* `/advanced-search` -- шлях до ресурсу на сервері (ендпоінт).
* `HTTP/1.1` -- версія протоколу HTTP.
* `Host: api.example.com` -- заголовок, що вказує домен, де знаходиться ресурс.
* `Content-Type: application/json` -- заголовок, що вказує на тип контенту в тілі запита.
* Тіло запита містить JSON-об'єкт із параметрами `userAge`, `location` та `isActive`.

cURL::
+
[source,curl]
----
curl -X POST "https://api.example.com/advanced-search" \
     -H "Content-Type: application/json" \
     -d '{"userAge": [25, 30, 35], "location": "Kyiv", "isActive": true}'
----
+
Ця команда *cURL* використовує `-X POST` для вказівки на метод запита `POST` і включає тіло запита у форматі JSON.
+
У цій cURL-команді:

* `-X POST` вказує на використання метода `POST`.
* `https://api.example.com` -- базовий URL ресурсу, де відбувається пошук.
* `-H "Content-Type: application/json"` додає заголовок, що вказує на тип контенту в тілі запита.
* `-d '{"userAge": [25, 30, 35], "location": "Kyiv", "isActive": true}'` встановлює дані, які будуть відправлені у тілі запита. У цьому випадку -- це JSON-об'єкт із масивом значень для `userAge` та додатковими полями `location` та `isActive`.
====
--

==== Сценарій 3: складний пошук із використанням спецсимволів та коми

.XML-схема
====
[source, xml]
----
<ext:createSearchCondition name="special_chars_in_search">
    <ext:table name="users">
        <ext:column name="name" searchType="in"/>
        <ext:column name="location" searchType="in"/>
    </ext:table>
</ext:createSearchCondition>
----
====

.Опис таблиці `users`
[cols="2,5", options="header"]
|===
| Стовпець   | Опис

| `name`
| Ім'я користувача, яке може містити спецсимволи (наприклад, апостроф) і коми, і повертається як результат. Пошук виконується за методом `in`.

| `location`
| Місцеперебування користувача, яке використовується для точного пошуку. Пошук виконується за методом `in`.
|===

TIP: Цей сценарій показує як обробляються спецсимволи та коми при використанні `in/notIn`.
--

.SQL-скрипт (_пошуковий запит_)
====
[source,sql]
----
SELECT name, location FROM users
WHERE name IN ('O''Reilly, Jr.', 'Smith, Sr.') AND location IN ('New York, NY', 'Los Angeles, CA')
----
====

--
У цьому запиті: ::
Вибираються записи, де ім'я (`name`) відповідає значенням із комами та апострофами, а місцеперебування (`location`) включає коми.
--

.HTTP POST-запит із використанням оператора `in` для спецсимволів і ком
[tabs]
====

HTTP::
+
[source,http]
----
POST /special-chars-in-search HTTP/1.1
Host: api.example.com
Content-Type: application/json

{
  "name": ["O'Reilly, Jr.", "Smith, Sr."],
  "location": ["New York, NY", "Los Angeles, CA"]
}
----
+
Цей HTTP-запит використовує метод `POST` для відправки даних до сервера з метою отримання результатів, які відповідають критерію пошуку `in` зі спецсимволами та комами в полях `name` та `location`.
+
У цьому прикладі:

* `POST` -- метод запита, використаний для відправки даних на сервер.
* `/special-chars-in-search` -- шлях до ресурсу на сервері (ендпоінт).
* `HTTP/1.1` -- версія протоколу HTTP.
* `Host: api.example.com` -- заголовок, що вказує домен, де знаходиться ресурс.
* `Content-Type: application/json` -- заголовок, що вказує на тип контенту в тілі запита.
* Тіло запита містить JSON-об'єкт із параметрами `name` та `location`, які включають спецсимволи та коми.

cURL::
+
[source,curl]
----
curl -X POST "https://api.example.com/special-chars-in-search" \
     -H "Content-Type: application/json" \
     -d '{"name": ["O'Reilly, Jr.", "Smith, Sr."], "location": ["New York, NY", "Los Angeles, CA"]}'
----
+
Ця команда *cURL* використовує `-X POST` для вказівки на метод запита `POST` і включає тіло запиту у форматі JSON.
+
У цій cURL-команді:

* `-X POST` вказує на використання метода `POST`.
* `https://api.example.com` -- базовий URL ресурсу, де відбувається пошук.
* `-H "Content-Type: application/json"` додає заголовок, що вказує на тип контенту в тілі запита.
* `-d '{"name": ["O'Reilly, Jr.", "Smith, Sr."], "location": ["New York, NY", "Los Angeles, CA"]}'` встановлює дані, які будуть відправлені у тілі запита. У цьому випадку -- це JSON-об'єкт із масивом значень для `name` та `location`.
====

WARNING: Для складних випадків обробки, як-от цей, використовуйте `POST`-запити, інакше ви отримаєте некоректний результат.

[IMPORTANT,caption=приклад невалідного випадку використання GET]
====
.HTTP GET-запит із використанням оператора `in` для спецсимволів і ком
[tabs]
=====

HTTP::
+
[source,http]
----
GET /special-chars-in-search?name=O'Reilly,%20Jr.,Smith,%20Sr.&location=New%20York,%20NY,Los%20Angeles,%20CA HTTP/1.1
Host: api.example.com
----
+
Цей HTTP-запит використовує метод `GET` для запита до сервера з метою отримання результатів, які відповідають критерію пошуку `in` зі спецсимволами та комами в полях `name` та `location`.
+
У цьому прикладі:

* `GET` -- метод запита, використаний для отримання даних.
* `/special-chars-in-search` -- шлях до ресурсу на сервері (ендпоінт).
* `?name=O'Reilly,%20Jr.,Smith,%20Sr.&location=New%20York,%20NY,Los%20Angeles,%20CA` -- параметри запита, де `%20` використовується для кодування пробілів.
* `HTTP/1.1` -- версія протоколу HTTP.
* `Host: api.example.com` -- заголовок, що вказує домен, де знаходиться ресурс.

cURL::
+
[source,curl]
----
curl -X GET "https://api.example.com/special-chars-in-search?name=O'Reilly,%20Jr.,Smith,%20Sr.&location=New%20York,%20NY,Los%20Angeles,%20CA"
----
+
Ця команда *cURL* використовує `-X GET` для вказівки на метод запита `GET` і включає повний URL з параметрами запита.
+
У цій cURL-команді:

* `-X GET` вказує на використання метода `GET`.
* `https://api.example.com` -- базовий URL ресурсу, де відбувається пошук.
* `/special-chars-in-search` -- шлях до ресурсу на сервері (ендпоінт).
* `?name=O'Reilly,%20Jr.,Smith,%20Sr.&location=New%20York,%20NY,Los%20Angeles,%20CA` -- параметри запита з кодуванням пробілів та включенням спецсимволів та ком.
=====
====
--

== `between`

`*between*` повертає значення, що належать до заданого діапазону значень (включно "від" та "до").

.XML-схема
[source, xml]
----
<ext:createSearchCondition name="find_between_age">
    <ext:table name="users">
        <ext:column name="first_name" returning="true"/>
        <ext:column name="last_name" returning="true"/>
        <ext:column name="user_age" searchType="between"/>
    </ext:table>
</ext:createSearchCondition>
----

.Опис таблиці `users`
--
* `first_name` -- ім'я користувача, яке повертається як результат.
* `last_name` -- прізвище користувача, яке також повертається як результат.
* `user_age` -- вік користувача, який може бути використаний для пошуку в межах заданого діапазону (включно) за допомогою оператора `between`.

TIP: Детальніше про атрибут `returning` ви можете дізнатися у секції xref:registry-develop:data-modeling/data/physical-model/liquibase-ddm-ext.adoc#returning-attribute-values[Атрибут _returning_].
--

.SQL-скрипт (_пошуковий запит_)
[source,sql]
----
SELECT first_name, last_name FROM users
WHERE user_age BETWEEN значення_від AND значення_до
----

--
У цьому запиті:

* Вибрані імена (`first_name`) та прізвища (`last_name`) користувачів з таблиці `users`.
* Пошук виконується за віком (`user_age`), який повинен належати діапазону від `значення_від` до `значення_до` (включно).
--

.HTTP-запит із використанням оператора `between`
[source,bash]
----
GET https://.../find-between-age?user_age_from=значення_від&user_age_to=значення_до
----

Цей HTTP-запит використовує метод GET для запита до сервера з метою отримання результатів, які відповідають критерію пошуку "між" для поля `user_age`.

.HTTP-запит із референтними значеннями
[source,bash]
----
GET https://api.example.com/find-between-age?userAgeFrom=20&userAgeTo=30
----

У цьому прикладі:

* `https://api.example.com/find-between-age` -- це базовий URL ресурсу та ендпоінт, де відбувається пошук.
* `userAgeFrom=20&userAgeTo=30` -- параметри запита, які вказують на пошук користувачів з віком від 20 до 30 років (включно).