= Аналіз WYSIWYG-редакторів на відповідність ключовим вимогам

== Функціональні сценарії

[TIP]
Описати функціональні сценарії, які необхідно реалізувати в рамках дизайну рішення

- Створення _Freemarker_ HTML-шаблонів для генерації витягів з реєстру
- Створення _Freemarker_ HTML-шаблонів для генерації поштових повідомлень
- ...

== Ключові вимоги до візуального редактора

[TIP]
Описати основні вимоги, які необхідно врахувати в рамках обрання підходу для реалізації рішення

- Підтримка темування
- Підтримка таблиць
- Підтримка _Freemarker_-директив
- ...

== Out of Scope

[TIP]
Описати вимоги, які не було розглянуто детально у процесі аналізу та дизайну

== Розглянуті рішення

[TIP]
Додати перелік рішень та технологій, які було розглянуто у процесі підготовки дизайну

- TinyMCE
- CKEditor
- ...

== Аналіз на відповідність вимогам

[TIP]
Додати результати аналізу _pros/cons_ розглянутих рішень та технологій

|===
|Критерій / Функціональність|TinyMCE|CKEditor|...

|...
|...
|...
|...

|===

== Рішення за результатами аналізу

[TIP]
Додати резолюцію за результатами проведеного аналізу

== Підтримка темування та стилізації

[TIP]
Описати механізм реалізації вимоги

== Підтримка локалізації

[TIP]
Описати механізм реалізації вимоги

== Інтерфейс веб-редактора

[TIP]
Додати екрани для візуалізації досвіду моделювання згідно функціональних сценаріїв
