== Технічний дизайн рішення

[IMPORTANT]
--
* Типовий екземпляр реєстру складається операційної та адміністративної зон
* В залежності від визначеної ролі, існує декілька варіацій функціонування екземпляра реєстру:
** Екземпляр реєстру з відсутнім інтерфейсом користувача для адміністративної зони
** Екземпляр реєстру з read-only інтерфейсом користувача для адміністративної зони
** Екзмепляр реєстру, який складається з операційної зони мастер-тенанта, адміністративної зони та _0..N_ ефемерних кандидат-тенантів реєстру, які складаютсья лише з операціїної зони
* Ефемерний кандидат-тенант реєстру складається з ідентичної мастер-тенанту копії операційної зони, яка має мінімальні вимоги до ресурсів
* При внесенні змін до дата моделі версії-кандидату регламенту, сховище ефемерного тенанта реєстру перестворюється з використанням стану сховища мастер-тенанту у якості базового, з послідуючим застосуванням змін
--

== Дизайн співіснування мастер та RC тенантів реєстру

image::architecture/registry/administrative/regulation-management/admin-portal/general/logical-design.svg[logical-design]

== Система Адміністрування Регламенту Реєстру

image::architecture/registry/administrative/regulation-management/admin-portal/general/admin-portal.svg[admin-portal-design]

== Регламент реєстру

На даній структурній діаграмі представлено складові частини _регламенту реєстру_, можливості управління якими надає інтерфейс користувача _Системи Адміністрування Регламенту Реєстру_.

image::architecture/registry/administrative/regulation-management/admin-portal/general/registry-regulation.svg[registry-regulation,500]

== CI/CD регламенту реєстру

У даному розділі представлено підходи до побудови CI/CD пайплайну для випуску оновлень регламенту реєстру з акцентом на наступних аспектах:

- Розробка нових послуг
- Виправлення дефектів
- Тестування змін
- Промоція оновлення
- _Blue/Green_ підхід до оновлення промислового екземпляра реєстру

=== Тактичний підхід

Для побудови CI/CD регламенту використовуються наступні визначення ролей для екземплярів реєстру:

* _Development_:
** Розробка нових послуг відбувається за допомогою _запитів на внесення змін_ та формування _версій-кандидатів_ реєстру
** Портування виправлень до регламенту, який розгорнуто на _Staging_ та _Production_ оточеннях відбувається за допомогою створення _запитів на внесення змін_ та формування _версій-кандидатів_ реєстру
** Тестування нових послуг та портованих виправлень до регламенту відбувається на окремих _кандидат-тенантах_ реєстру, які автоматично створюються для _версій-кандидатів_ на базі _запитів на внесення змін_
** Усі зміни, які вносяться у _мастер-версію_ регламенту реєстру мають відповідати критеріям сумісності з розгорнутими змінами на _Staging_ та _Production_ оточеннях
** _Мастер-версія_ регламенту реєстру має відповідати критеріям стабільності та якості для проведення тестування _версії-кандидата_ на _мастер-тенанті_ реєстру

* _Staging_:
** Внесення виправлень до регламенту відбувається за допомогою _запитів на внесення змін_ та формування _версій-кандидатів_ реєстру
** Тестування виправлень до регламенту відбувається на окремих _кандидат-тенантах_ реєстру, які автоматично створюються для _версій-кандидатів_ на базі _запитів на внесення змін_
** Усі зміни, які вносяться у _мастер-версію_ регламенту реєстру мають відповідати критеріям сумісності з розгорнутими змінами на _Production_ оточенні
** Усі виправлення, які вносяться у _мастер-версію_ регламенту мають бути портовані на _мастер-версію_ _Development_ екземпляра реєстру
** _Мастер-версія_ регламенту реєстру має відповідати критеріям стабільності та якості для проведення тестування _версії-кандидата_ на _мастер-тенанті_ реєстру

* _Production_:
** _Headless_ Адміністративні сервіси реєстру без інтерфейсу користувача
** При оновленні версії регламенту реєстру, автоматично створюється копія реєстру для забезпечення _Blue/Green_ підходу до встановлення

[WARNING]
--
Суттєвим недоліком підходу є відсутність можливості проводити тестування нової версії регламенту на _Staging_ оточенні та вносити виправлення / оновлювати _Production_ реєстр.
--

image::architecture/registry/administrative/regulation-management/admin-portal/general/regulation-cicd-tactical.svg[regulation-cicd,700]

=== Стратегічний підхід

Для побудови CI/CD регламенту використовуються наступні визначення ролей для екземплярів реєстру:

* _Development_:
** ...
* _Staging_:
** ...
* _Production_:
** ...

image::architecture/registry/administrative/regulation-management/admin-portal/general/regulation-cicd-strategic.svg[regulation-cicd,700]

== Логічна структура екземпляра реєстру

=== Екземпляр розробки та тестування реєстру

image::architecture/registry/administrative/regulation-management/admin-portal/general/development-registry-platform.svg[700]

=== Екземпляр промислового оточення реєстру

image::architecture/registry/administrative/regulation-management/admin-portal/general/production-registry-platform.svg[700]

== Варіанти побудови CI/CD регламенту реєстру на Платформі

=== Єдиний екземпляр Платформи Реєстрів

image::architecture/registry/administrative/regulation-management/admin-portal/general/single-registry-platform-deployment.svg[700]

=== Окремі екземпляри Платформи для розробки регламенту та промислового оточення

image::architecture/registry/administrative/regulation-management/admin-portal/general/separate-registry-platforms-deployment.svg[700]

== Опис API