= [DRAFT] Генерація і підтримка REST API документації сервісів системи

== Загальні положення

- _REST API документація_ ведеться в форматі _OpenAPI Specification_
- Для _Java_ застосунків _REST API документація_ будується автоматично на базі відповідних _Swagger_ анотації в коді
- Для застосунків які не генерують автоматичну _REST API документація_, документація формується вручну і зберігається у
Git репозиторії сервісу
- При побудові master/main версії сервісу, формується _REST API документація_ та автоматично вносяться зміни в загальну
документацію проєкту (Antora документація)
- Опис методів, параметрів та відповідей повинен містити розширену інформацію про їх використання
- Всі методи повинні мати приклади відповідей які будуть максимально наближені до реальних
- Правила авторизації описуються тільки ті, що реалізовані безпосередньо в сервісі
- Додатково до правил авторизації сервісу повинно бути посилання на документацію
xref:architecture/registry/operational/ext-api-management/overview.adoc[_Зовнішнього API-шлюзу операційної зони_] та
xref:architecture/platform/operational/service-mesh/overview.adoc[_Підсистеми управління міжсервісною взаємодією_] з описом перевірок прав доступу на всіх рівнях
- В сервісах з автоматичною генерацією _REST API документація_ розгортається додатково з самим сервісом

NOTE: З переліком сервісів та їх _REST API документацією_ можна ознайомитись на сторінці xref:architecture/platform-api/overview.adoc[]

== Автоматичне оновлення документації

.Компонентна діаграма автоматичної публікації РЕСТ АПІ документації
image::architecture-workspace/platform-evolution/rest-api/rest-api.drawio.svg[]

- Файл з Опен АПІ специфікацією може генеруватися автоматично в пайплайні сервісу чи зберігатися розробником в репозиторії сервісу
- Файл зберігається в репозиторії сервісу за шляхом docs/<service-name>-swagger.yml, де <service-name> - назва сервісу
- Для автоматичної генерації файлу використовуються maven plugin в build пайплайні сервісу

NOTE: Деталі по вибору плагіну та параметрів його налаштування поза скоупом цього документу

- Build пайплайн відповідальний за те щоб файл з Опен АПІ специфікацією був опублікований в репозиторій документації
проекту
- Файл публікується в репозиторій документації проекту за шляхом
docs/ua/modules/arch/attachments/architecture/platform-api/services/<service-name>-swagger.yml, де <service-name> -
назва сервісу
- Генерація файлу та його публікація відбувається тільки при побудові master/main версії сервісу
- Підключення конкретного файлу з опен апі специфікацією для відображення на сторінці документації відбувається вручну 1 раз для кожного сервісу


== Обсяг робіт

=== MVP
- Створення свагер документації для сервісів, що мають автогенерації
- Ручна публікація свагер документації сервісів в загальну документацію проекту


=== Full scope
- Публікація свагер документації сервісів в загальну документацію проекту автоматично при зміні в master/main гілці
- Для автогенерованої документації вихідний файл зі специфікацією генерується в build пайплайні сервісу
- Для документації, що ведеться вручну, файл зі специфікацією зберігається в репозиторії сервісу
- Розширений опис методів, параметрів та відповідей
- Збагачення РЕСТ АПІ документації прикладами відповідей
- Розширений опис правил авторизації включно з посиланнями на відповідні сторінки Конг АПІ гатевея та сервіс меша


== Поза скоупом
- Тестове оточення для викликів сервісів з документації
- Загальний опис сервісу формується окремо від РЕСТ АПІ специфікації
- Вказання ліцензії сервісу (в загальний опис сервісу)


