= Генерація і підтримка REST API документації сервісів системи

== Загальні положення

- _REST API документація_ ведеться в форматі _OpenAPI Specification_
- Для _Java_ застосунків _REST API документація_ будується автоматично на базі відповідних _Swagger_ анотації в коді
- Для застосунків які не генерують автоматичну _REST API документація_, документація формується вручну і зберігається у
Git репозиторії сервісу
- При побудові master/main версії сервісу, формується _REST API документація_ та автоматично вносяться зміни в загальну
документацію проєкту (Antora документація)
- Опис методів, параметрів та відповідей повинен містити розширену інформацію про їх використання
- Всі методи повинні мати приклади відповідей які будуть максимально наближені до реальних
- Правила авторизації описуються тільки ті, що реалізовані безпосередньо в сервісі
- Додатково до правил авторизації сервісу повинно бути посилання на документацію
xref:architecture/registry/operational/ext-api-management/overview.adoc[_Зовнішнього API-шлюзу операційної зони_] та
xref:architecture/platform/operational/service-mesh/overview.adoc[_Підсистеми управління міжсервісною взаємодією_] з описом перевірок прав доступу на всіх рівнях
- В сервісах з автоматичною генерацією _REST API документація_ розгортається додатково з самим сервісом

NOTE: З переліком сервісів та їх _REST API документацією_ можна ознайомитись на сторінці xref:architecture/platform-api/overview.adoc[]

== Автоматичне оновлення документації

.Компонентна діаграма автоматичної публікації _REST API документації_
image::architecture-workspace/platform-evolution/rest-api/rest-api.drawio.svg[]

- Файл з _REST API документацією_ може генеруватися автоматично в _build пайплайні_ сервісу чи зберігатися розробником в репозиторії сервісу
- Файл зберігається в репозиторії сервісу за шляхом _docs/<service-name>-swagger.yml_, де _<service-name>_ - назва сервісу
- Для автоматичної генерації файлу використовуються maven plugin в _build пайплайні_ сервісу

NOTE: Деталі по вибору плагіну та параметрів його налаштування поза скоупом цього документу

- _Build пайплайн_ відповідальний за те щоб файл з _REST API документацією_ був опублікований в репозиторій загальної
документації проєкту (Antora документація)
- Файл публікується репозиторій загальної документації проєкту за шляхом
_docs/ua/modules/arch/attachments/architecture/platform-api/services/<service-name>-swagger.yml_, де _<service-name>_ -
назва сервісу
- Генерація файлу та його публікація відбувається тільки при побудові master/main версії сервісу
- Підключення конкретного файлу з _REST API документацією_ для візуалізації на сторінці документації відбувається вручну
1 раз для кожного сервісу

== Обсяг робіт

=== MVP
- Створення _REST API документації_ для сервісів, що не мають автогенерації
- Ручна публікація _REST API документації_ сервісів в загальну документацію проєкту

=== Full scope
- Публікація _REST API документації_ сервісів в загальну документацію проєкту автоматично при зміні в master/main гілці
- Для сервісів, документація яких ведеться вручну, додати файл з _REST API документацією_ в репозиторії сервісу
- Розширений опис методів, параметрів та відповідей
- Збагачення _REST API документації_ прикладами відповідей
- Розширений опис правил авторизації включно з посиланнями на відповідні сторінки xref:architecture/registry/operational/ext-api-management/overview.adoc[_Зовнішнього API-шлюзу операційної зони_] та
xref:architecture/platform/operational/service-mesh/overview.adoc[_Підсистеми управління міжсервісною взаємодією_]

== Поза скоупом
- Тестове оточення для викликів сервісів з документації
- Загальний опис сервісу формується окремо від _REST API документації_
- Вказання ліцензії сервісу (в загальний опис сервісу)


