openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  /api/start-bp:
    post:
      tags:
        - start-bp-controller
      summary: Start process instance
      description: Returns result variable of business process
      operationId: startBp
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StartBpRestRequest'
        required: true
      responses:
        '200':
          description: Returns result variable of business process
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/StartBpResponse'
        '422':
          description: Business process definition cannot be started or missing required start variable for the business process
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SystemErrorDto'
        '500':
          description: Internal server error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SystemErrorDto'
components:
  schemas:
    StartBpRestRequest:
      type: object
      properties:
        businessProcessDefinitionKey:
          type: string
        startVariables:
          type: object
          additionalProperties:
            type: object
    SystemErrorDto:
      type: object
      properties:
        traceId:
          type: string
        code:
          type: string
        message:
          type: string
        localizedMessage:
          type: string
    StartBpResponse:
      required:
        - resultVariables
      type: object
      properties:
        resultVariables:
          type: object
          additionalProperties:
            type: object