openapi: 3.0.1
info:
  title: bpms API
  version: v1
paths:
  /extended/authorizations/process-instance/create:
    post:
      summary: Create authorizations for process instances.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DdmCountResultDto'
      tags:
        - Extended Authorizations

  /extended/authorizations/process-definition/create:
    post:
      summary: Create authorizations for process definitions.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DdmProcessDefinitionAuthDto'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DdmCountResultDto'
      tags:
        - Extended Authorizations

  /extended/authorizations/delete:
    delete:
      summary: Delete authorizations for process instances and process definitions.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DdmCountResultDto'
      tags:
        - Extended Authorizations

  /extended/process-definition/key/{key}:
    get:
      summary: Get process definition by key.
      parameters:
        - in: path
          name: key
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DdmProcessDefinitionDto'
      tags:
        - Extended Process Definition

  /extended/process-definition:
    post:
      summary: Get process definitions by params.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessDefinitionQueryDto'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DdmProcessDefinitionDto'
      tags:
        - Extended Process Definition

  /extended/process-instance:
    post:
      summary: Get list of historical process-instances by provided query params
      parameters:
        - in: query
          name: firstResult
          required: false
          schema:
            type: integer
        - in: query
          name: maxResults
          required: false
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProcessInstanceExtendedQueryDto'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DdmProcessInstanceDto'
      tags:
        - Extended Process Instance

  /extended/task:
    post:
      summary: Get list of user tasks by provided query params
      parameters:
        - in: query
          name: firstResult
          required: false
          schema:
            type: integer
        - in: query
          name: maxResults
          required: false
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskQueryDto'
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DdmTaskDto'
      tags:
        - Extended Task

  /extended/task/lightweight:
    post:
      summary: Method for getting list of lightweight camunda user tasks
      parameters:
        - in: query
          name: firstResult
          required: false
          schema:
            type: integer
        - in: query
          name: maxResults
          required: false
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskQueryDto'
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DdmLightweightTaskDto'
      tags:
        - Extended Task

  /extended/task/{id}:
    get:
      summary: Method for getting extended camunda user task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DdmSignableTaskDto'
      tags:
        - Extended Task

  /extended/task/{id}/complete:
    post:
      summary: Complete user task by ID
      operationId: completeTaskById
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DdmCompleteTaskDto'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DdmCompletedTaskDto'
        '422':
          description: Client validation exception
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientValidationException'
      tags:
        - Extended Task

components:
  schemas:
    DdmProcessDefinitionDto:
      type: object
      properties:
        id:
          type: string
        key:
          type: string
        name:
          type: string
        suspended:
          type: boolean
        formKey:
          type: string

    DdmProcessDefinitionAuthDto:
      type: object
      properties:
        groupId:
          type: string
        processDefinitionId:
          type: string

    DdmCountResultDto:
      type: object
      properties:
        count:
          type: integer

    ProcessDefinitionQueryDto:
      type: object
      properties:
        latestVersion:
          type: boolean
        sortBy:
          type: string
        sortOrder:
          type: string
        processDefinitionId:
          type: string
        processDefinitionIdIn:
          type: array
          items:
            type: string
        suspended:
          type: boolean
        active:
          type: boolean

    DdmProcessInstanceDto:
      type: object
      properties:
        id:
          type: string
        processDefinitionId:
          type: string
        processDefinitionName:
          type: string
        startTime:
          type: string
          format: date-time
        state:
          type: string
          enum: [ACTIVE, PENDING, SUSPENDED]

    ProcessInstanceExtendedQueryDto:
      type: object
      properties:
        deploymentId:
          type: string
        processDefinitionKey:
          type: string
        processDefinitionKeys:
          type: array
          items:
            type: string
        processDefinitionKeyNotIn:
          type: array
          items:
            type: string
        businessKey:
          type: string
        businessKeyLike:
          type: string
        caseInstanceId:
          type: string
        processDefinitionId:
          type: string
        superProcessInstance:
          type: string
        subProcessInstance:
          type: string
        superCaseInstance:
          type: string
        subCaseInstance:
          type: string
        active:
          type: boolean
        suspended:
          type: boolean
        processInstanceIds:
          type: array
          items:
            type: string
        withIncident:
          type: boolean
        incidentId:
          type: string
        incidentType:
          type: string
        incidentMessage:
          type: string
        incidentMessageLike:
          type: string
        tenantIds:
          type: array
          items:
            type: string
        withoutTenantId:
          type: boolean
        activityIds:
          type: array
          items:
            type: string
        rootProcessInstances:
          type: boolean
        leafProcessInstances:
          type: boolean
        isProcessDefinitionWithoutTenantId:
          type: boolean
        variableNamesIgnoreCase:
          type: boolean
        variableValuesIgnoreCase:
          type: boolean
        variables:
          type: array
          items:
            type: object
        orQueries:
          type: array
          items:
            type: object

    DdmTaskDto:
      type: object
      properties:
        id:
          type: string
        taskDefinitionKey:
          type: string
        name:
          type: string
        assignee:
          type: string
        created:
          type: string
          format: date-time
        description:
          type: string
        processDefinitionName:
          type: string
        processInstanceId:
          type: string
        processDefinitionId:
          type: string
        formKey:
          type: string
        suspended:
          type: boolean
        businessKey:
          type: string

    TaskQueryDto:
      type: object
      properties:
        taskId:
          type: string
        assignee:
          type: string
        unassigned:
          type: boolean
        processInstanceId:
          type: string
        rootProcessInstanceId:
          type: string
        orQueries:
          type: array
          items:
            $ref: '#/components/schemas/TaskQueryDto'
        processInstanceIdIn:
          type: array
          items:
            type: string
        sorting:
          type: array
          items:
            $ref: '#/components/schemas/SortingDto'

    SortingDto:
      type: object
      properties:
        sortBy:
          type: string
        sortOrder:
          type: string

    DdmLightweightTaskDto:
      type: object
      properties:
        id:
          type: string
        assignee:
          type: string

    DdmSignableTaskDto:
      type: object
      properties:
        id:
          type: string
        taskDefinitionKey:
          type: string
        name:
          type: string
        assignee:
          type: string
        created:
          type: string
          format: date-time
        description:
          type: string
        processDefinitionName:
          type: string
        processInstanceId:
          type: string
        rootProcessInstanceId:
          type: string
        processDefinitionId:
          type: string
        formKey:
          type: string
        suspended:
          type: boolean
        eSign:
          type: boolean
        signatureValidationPack:
          type: array
          items:
            type: string
            enum: [INDIVIDUAL, ENTREPRENEUR, LEGAL]
        formVariables:
          type: object

    DdmCompleteTaskDto:
      type: object
      properties:
        variables:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/DdmVariableValueDto'
        withVariablesInReturn:
          type: boolean

    DdmCompletedTaskDto:
      type: object
      properties:
        id:
          type: string
        processInstanceId:
          type: string
        rootProcessInstanceId:
          type: string
        rootProcessInstanceEnded:
          type: boolean
        variables:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/DdmVariableValueDto'

    DdmVariableValueDto:
      type: object
      properties:
        type:
          type: string
        value:
          type: object
        valueInfo:
          type: object

    ClientValidationException:
      type: object
      properties:
        traceId:
          type: string
        code:
          type: string
        details:
          $ref: '#/components/schemas/ErrorsListDto'

    ErrorsListDto:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetailDto'

    ErrorDetailDto:
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        value:
          type: string
