openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  /api/notifications/templates/{channel}:{name}:
    put:
      tags:
        - notification-template-controller
      summary: змінити ресурс
      description: Використовується для зміни вже існуючого ресурсу з вказанням id
      operationId: saveTemplate
      parameters:
        - name: channel
          in: path
          required: true
          schema:
            type: string
        - name: name
          in: path
          required: true
          schema:
            type: string
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveNotificationTemplateInputDto'
        required: true
      responses:
        '200':
          description: OK з результатом
  /api/notifications/inbox/{id}/ack:
    post:
      tags:
        - inbox-notification-controller
      summary: створити ресурс
      description: Використовується для створення ресурсу.
      operationId: acknowledgeNotification
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: X-Access-Token
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK з результатом
  /api/notifications/inbox:
    get:
      tags:
        - inbox-notification-controller
      summary: отримати список ресурсів
      description: Використовується для отримання об’єктів. Не змінює стан ресурсу
      operationId: getInboxNotifications
      parameters:
        - name: X-Access-Token
          in: header
          required: true
          schema:
            type: string
        - name: request
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/InboxOffsetBasedPageRequest'
      responses:
        '200':
          description: OK з результатом
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/InboxNotificationResponseDto'
        '401':
          description: Помилка аутентифікації (відсутній токен або цифровий підпис)
        '403':
          description: Недостатньо прав для виконання операції (роль користувача не передбачає доступу до даного ресурсу)
        '500':
          description: Внутрішня помилка сервера
        '501':
          description: Не імплементовано (використовується для заглушок)
components:
  schemas:
    NotificationTemplateAttributeDto:
      type: object
      properties:
        name:
          type: string
        value:
          type: string
    SaveNotificationTemplateInputDto:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/NotificationTemplateAttributeDto'
    InboxOffsetBasedPageRequest:
      type: object
      properties:
        offset:
          type: integer
          format: int64
        sort:
          $ref: '#/components/schemas/Sort'
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        paged:
          type: boolean
        unpaged:
          type: boolean
    Sort:
      type: object
      properties:
        unsorted:
          type: boolean
        sorted:
          type: boolean
        empty:
          type: boolean
    InboxNotificationResponseDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        subject:
          type: string
        message:
          type: string
        createdAt:
          type: string
          format: date-time
        isAcknowledged:
          type: boolean
