openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  /excerpts:
    post:
      tags:
        - excerpt-controller
      summary: створити ресурс
      description: Використовується для створення ресурсу.
      operationId: generate
      parameters:
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
        - name: X-Digital-Signature
          in: header
          required: false
          schema:
            type: string
        - name: X-Digital-Signature-Derived
          in: header
          required: false
          schema:
            type: string
        - name: X-Source-System
          in: header
          required: false
          schema:
            type: string
        - name: X-Source-Application
          in: header
          required: false
          schema:
            type: string
        - name: X-Source-Business-Process
          in: header
          required: false
          schema:
            type: string
        - name: X-Source-Business-Activity
          in: header
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExcerptEventDto'
        required: true
      responses:
        '200':
          description: OK з результатом
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExcerptEntityId'
        '400':
          description: Некоректні вхідні дані (наприклад, неправильний тип поля)
        '401':
          description: Помилка аутентифікації (відсутній токен або цифровий підпис)
        '403':
          description: Недостатньо прав для виконання операції (роль користувача не передбачає доступу до даного ресурсу)
        '422':
          description: Помилка валідації, запит містить дані, що не відповідають правилам вказаним в домені
        '500':
          description: Внутрішня помилка сервера
        '501':
          description: Не імплементовано (використовується для заглушок)
  /excerpts/{id}:
    get:
      tags:
        - excerpt-controller
      summary: отримати ресурс по ідентифікатору
      description: Використовується для отримання об’єктів. Не змінює стан ресурсу
      operationId: retrieve
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
        - name: X-Digital-Signature
          in: header
          required: false
          schema:
            type: string
        - name: X-Digital-Signature-Derived
          in: header
          required: false
          schema:
            type: string
        - name: X-Source-System
          in: header
          required: false
          schema:
            type: string
        - name: X-Source-Application
          in: header
          required: false
          schema:
            type: string
        - name: X-Source-Business-Process
          in: header
          required: false
          schema:
            type: string
        - name: X-Source-Business-Activity
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK з результатом
          content:
            '*/*':
              schema:
                type: string
                format: binary
        '401':
          description: Помилка аутентифікації (відсутній токен або цифровий підпис)
        '403':
          description: Недостатньо прав для виконання операції (роль користувача не передбачає доступу до даного ресурсу)
        '500':
          description: Внутрішня помилка сервера
        '501':
          description: Не імплементовано (використовується для заглушок)
  /excerpts/{id}/status:
    get:
      tags:
        - excerpt-controller
      summary: отримати ресурс по ідентифікатору
      description: Використовується для отримання об’єктів. Не змінює стан ресурсу
      operationId: status
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
        - name: X-Digital-Signature
          in: header
          required: false
          schema:
            type: string
        - name: X-Digital-Signature-Derived
          in: header
          required: false
          schema:
            type: string
        - name: X-Source-System
          in: header
          required: false
          schema:
            type: string
        - name: X-Source-Application
          in: header
          required: false
          schema:
            type: string
        - name: X-Source-Business-Process
          in: header
          required: false
          schema:
            type: string
        - name: X-Source-Business-Activity
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK з результатом
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/StatusDto'
        '401':
          description: Помилка аутентифікації (відсутній токен або цифровий підпис)
        '403':
          description: Недостатньо прав для виконання операції (роль користувача не передбачає доступу до даного ресурсу)
        '500':
          description: Внутрішня помилка сервера
        '501':
          description: Не імплементовано (використовується для заглушок)
components:
  schemas:
    ExcerptEventDto:
      required:
        - excerptType
      type: object
      properties:
        recordId:
          type: string
          format: uuid
        excerptType:
          type: string
        excerptInputData:
          type: object
          additionalProperties:
            type: object
        requiresSystemSignature:
          type: boolean
    ExcerptEntityId:
      type: object
      properties:
        excerptIdentifier:
          type: string
          format: uuid
    StatusDto:
      type: object
      properties:
        status:
          type: string
          enum:
            - IN_PROGRESS
            - FAILED
            - COMPLETED
        statusDetails:
          type: string
