openapi: 3.0.1
info:
  title: Keycloak rest api extension
  version: v1
paths:
  /admin/search/{realm}:
    post:
      summary: Search users by attributes
      operationId: searchUsersByAttribute
      parameters:
        - in: path
          name: realm
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchUserRequestDto'

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRepresentation'
      security:
        - bearerAuth: []

  /admin/search-by-attributes/{realm}:
    post:
      summary: Search users by attributes
      operationId: searchUsersByAttributesDeprecated
      parameters:
        - in: path
          name: realm
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchUsersByEqualsAndStartsWithAttributesRequestDto'
      deprecated: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRepresentation'
      security:
        - bearerAuth: []

  /admin/v2/search-by-attributes/{realm}:
    post:
      summary: Search users by attributes (v2)
      operationId: searchUsersByAttributesV2
      parameters:
        - in: path
          name: realm
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchUsersByAttributesRequestDto'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchUsersByAttributesResponseDto'

      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    SearchUserRequestDto:
      type: object
      properties:
        attributes:
          type: object
          additionalProperties:
            type: string

    SearchUsersByEqualsAndStartsWithAttributesRequestDto:
      type: object
      properties:
        attributesEquals:
          type: object
          additionalProperties:
            type: string
        attributesStartsWith:
          type: object
          additionalProperties:
            type: array
            items:
              type: string

    SearchUsersByAttributesRequestDto:
      type: object
      properties:
        attributesEquals:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        attributesStartsWith:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        attributesThatAreStartFor:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        pagination:
          type: object
          properties:
            limit:
              type: integer
            continueToken:
              type: integer

    SearchUsersByAttributesResponseDto:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/UserRepresentation'
        pagination:
          type: object
          properties:
            limit:
              type: integer
            continueToken:
              type: integer

    UserRepresentation:
      type: object
      properties:
        self:
          type: string
        id:
          type: string
        createdTimestamp:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        username:
          type: string
        enabled:
          type: boolean
        totp:
          type: boolean
        emailVerified:
          type: boolean
        attributes:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        credentials:
          type: array
          items:
            type: object
        requiredActions:
          type: array
          items:
            type: string
        federatedIdentities:
          type: array
          items:
            type: object
        socialLinks:
          type: array
          items:
            type: object
        realmRoles:
          type: array
          items:
            type: string
        clientRoles:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        clientConsents:
          type: array
          items:
            type: object
        notBefore:
          type: integer
        applicationRoles:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
        federationLink:
          type: string
        serviceAccountClientId:
          type: string
        groups:
          type: array
          items:
            type: string
        origin:
          type: string
        disableableCredentialTypes:
          type: array
          items:
            type: string
        access:
          type: object
          additionalProperties:
            type: boolean