openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  /api/runtime/process-instances:
    get:
      tags:
        - process-runtime-controller
      summary: отримати список ресурсів
      description: Використовується для отримання об’єктів. Не змінює стан ресурсу
      operationId: getProcesses
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 10
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: sort
          in: query
          required: false
          schema:
            type: string
            default: desc(endTime)
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK з результатом
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessResponse'
        '401':
          description: Помилка аутентифікації (відсутній токен або цифровий підпис)
        '403':
          description: Недостатньо прав для виконання операції (роль користувача не передбачає доступу до даного ресурсу)
        '500':
          description: Внутрішня помилка сервера
        '501':
          description: Не імплементовано (використовується для заглушок)
  /api/runtime/process-instances/count:
    get:
      tags:
        - process-runtime-controller
      summary: отримати ресурс по ідентифікатору
      description: Використовується для отримання об’єктів. Не змінює стан ресурсу
      operationId: count
      parameters:
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK з результатом
  /api/history/tasks:
    get:
      tags:
        - process-history-controller
      summary: отримати список ресурсів
      description: Використовується для отримання об’єктів. Не змінює стан ресурсу
      operationId: getTasks
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 10
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: sort
          in: query
          required: false
          schema:
            type: string
            default: desc(endTime)
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK з результатом
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HistoryTaskResponse'
        '401':
          description: Помилка аутентифікації (відсутній токен або цифровий підпис)
        '403':
          description: Недостатньо прав для виконання операції (роль користувача не передбачає доступу до даного ресурсу)
        '500':
          description: Внутрішня помилка сервера
        '501':
          description: Не імплементовано (використовується для заглушок)
  /api/history/process-instances:
    get:
      tags:
        - process-history-controller
      summary: отримати список ресурсів
      description: Використовується для отримання об’єктів. Не змінює стан ресурсу
      operationId: getProcesses_1
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 10
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            format: int32
            default: 0
        - name: sort
          in: query
          required: false
          schema:
            type: string
            default: desc(endTime)
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK з результатом
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HistoryProcessResponse'
        '401':
          description: Помилка аутентифікації (відсутній токен або цифровий підпис)
        '403':
          description: Недостатньо прав для виконання операції (роль користувача не передбачає доступу до даного ресурсу)
        '500':
          description: Внутрішня помилка сервера
        '501':
          description: Не імплементовано (використовується для заглушок)
components:
  schemas:
    ProcessResponse:
      type: object
      properties:
        processInstanceId:
          type: string
        superProcessInstanceId:
          type: string
        processDefinitionId:
          type: string
        processDefinitionKey:
          type: string
        processDefinitionName:
          type: string
        businessKey:
          type: string
        startTime:
          type: string
          format: date-time
        startUserId:
          type: string
        status:
          $ref: '#/components/schemas/StatusModel'
    StatusModel:
      type: object
      properties:
        code:
          type: string
          enum:
            - ACTIVE
            - PENDING
            - SUSPENDED
            - COMPLETED
            - EXTERNALLY_TERMINATED
        title:
          type: string
    HistoryTaskResponse:
      type: object
      properties:
        activityInstanceId:
          type: string
        taskDefinitionKey:
          type: string
        taskDefinitionName:
          type: string
        processInstanceId:
          type: string
        processDefinitionId:
          type: string
        processDefinitionKey:
          type: string
        processDefinitionName:
          type: string
        rootProcessInstanceId:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        assignee:
          type: string
        businessKey:
          type: string
    HistoryProcessResponse:
      type: object
      properties:
        processInstanceId:
          type: string
        superProcessInstanceId:
          type: string
        processDefinitionId:
          type: string
        processDefinitionKey:
          type: string
        processDefinitionName:
          type: string
        businessKey:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        startUserId:
          type: string
        excerptId:
          type: string
        status:
          $ref: '#/components/schemas/StatusModel'
