= Видалення документів з S3 Ceph-бакетів і Redis
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Огляд
Цей документ описує процедуру видалення документів, пов'язаних із завершеними бізнес-процесами, з S3 Ceph-бакетів і Redis. Процес включає генерацію списку активних бізнес-процесів, роботу з утилітою для видалення та налаштування параметрів для її запуску.

== Кроки для видалення документів

. *Генерація CSV-файлу з активними бізнес-процесами*.
+
У поді `operational-instance` реєстру увійдіть до бази даних `camunda` і виконайте SQL-скрипт, що згенерує CSV-файл з ID та `start-form-document-key` активних інстансів бізнес-процесів. Ці ключі *_НЕ_* повинні бути видалені.
+
[source,sql]
----
psql
\c camunda

COPY (select ae.id_ "process-instance-id", arv.text_ "start-form-document-key" from act_ru_execution ae left join act_ru_variable arv on ae.id_ = arv.proc_inst_id_ and arv.name_ in ('start_form_ceph_key', 'start_message_payload_storage_key') where ae.parent_id_ is null) TO '/var/tmp/process_instance_ids.csv' csv header;
----

. *Копіювання згенерованого CSV-файлу на локальну машину*.
+
Після генерації файлу _/tmp/process_instance_ids.csv_, скопіюйте його на локальну машину за допомогою наступної команди:
+
[source,kubectl]
----
oc cp --retries=-1 operational-instance-pod:/tmp/process_instance_ids.csv ./process_instance_ids.csv
----

. *(_Опціонально_) Встановлення https://openjdk.org/[OpenJDK]*.
+
Якщо у вас ще не встановлений *OpenJDK*, це можна зробити на цьому етапі.

. *Завантаження утиліти для очищення сховищ*.
+
Завантажте останню версію утиліти:
`xref:attachment$registry-admin/delete-docs-s3-redis/storage-cleanup-cli-1.4.0-20240920.130342-1.jar[storage-cleanup-cli-1.4.0-20240920.130342-1.jar]`.

. *Режими роботи утиліти*.
+
Утиліта підтримує *три* основні режими роботи:

* *`dry-run`*: зчитує CSV-файл з активними екземплярами процесів та ідентифікує ключі, які потрібно видалити, але не здійснює фактичного видалення. Ідентифіковані ключі записуються у CSV-файли для Ceph і Redis.

* *`remove-only`*: використовується для видалення ключів, які визначено на етапі `dry-run`. Не потребує повторної ідентифікації ключів.

* *`full-run`*: зчитує CSV-файл з активними екземплярами процесів, ідентифікує та видаляє непотрібні ключі. Результати записуються у ті ж CSV-файли, що й при `dry-run`.

. *Запуск утиліти*.
+
Запустіть утиліту з наступними параметрами:
+
[source,bash]
----
java -jar storage-cleanup-cli.jar
         --execute-mode=<arg>
         --running-processes-csv-file=<arg>
         --s3-ceph-url=<arg>
         --lowcode-file-storage-secret-key=<arg>
         --lowcode-file-storage-access-key=<arg>
         --lowcode-form-data-storage-secret-key=<arg>
         --lowcode-form-data-storage-access-key=<arg>
         --ceph-removal-output-csv-file=<arg>
         --redis-url=<arg>
         --redis-secret=<arg>
         --redis-removal-output-csv-file=<arg>
         --removal-batch-size=<arg>
         --log-output=<arg>
----

== Опис параметрів утиліти

Утиліта `storage-cleanup-cli` підтримує наступні параметри конфігурації:

* `--execute-mode=<режим>`: виберіть режим роботи утиліти (*`dry-run`*, *`remove-only`* або *`full-run`*).

* `--running-processes-csv-file=<шлях>`: шлях до CSV-файлу з активними екземплярами процесів.

* `--s3-ceph-url=<URL>`: URL для Ceph сховища. Якщо не вказано, документи з Ceph не будуть видалені.
+
TIP: Необов'язково, якщо надано Redis URL.

* `--lowcode-file-storage-secret-key=<ключ>`: секретний ключ для кошика `lowcode-file-storage`.
+
TIP: Необов'язково.

* `--lowcode-file-storage-access-key=<ключ>`: ключ доступу для кошика `lowcode-file-storage`.
+
TIP: Необов'язково.

* `--lowcode-form-data-storage-secret-key=<ключ>`: секретний ключ для кошика `lowcode-form-data-storage`.
+
TIP: Необов'язково.

* `--lowcode-form-data-storage-access-key=<ключ>`: ключ доступу для кошика `lowcode-form-data-storage`.
+
TIP: Необов'язково.

* `--ceph-removal-output-csv-file=<шлях>`: шлях до CSV-файлу для зберігання ключів Ceph, що підлягають видаленню.

* `--redis-url=<URL>`: URL для Redis сховища. Якщо не вказано, документи з Redis не будуть видалені.
+
TIP: Необов'язково, якщо надано Ceph URL.

* `--redis-secret=<секрет>`: пароль для Redis.

* `--redis-removal-output-csv-file=<шлях>`: шлях до CSV-файлу для зберігання ключів Redis, що підлягають видаленню.

* `--removal-batch-size=<значення>`: розмір пакета для операцій видалення. _За замовчуванням: 1000_.

* `--log-output=<шлях>`: шлях до файлу з логами, що створюється після виконання утиліти. За замовчуванням: `s3-storage-cleanup-cli.log`.

== Додаткові інструкції

* Для переадресації портів для поду Redis виконайте кроки з інструкції xref:registry-admin/abandoned-processes/port-forward-redis.adoc[].
* Для визначення розміру бакетів у Ceph використовуйте *Ceph Dashboard*: xref:registry-admin/abandoned-processes/define-ceph-buckets-space.adoc[].

== Пов'язані сторінки

* xref:registry-admin/abandoned-processes/delete-abandoned-processes.adoc[]
* xref:registry-admin/abandoned-processes/port-forward-redis.adoc[]
* xref:registry-admin/abandoned-processes/define-ceph-buckets-space.adoc[]