= Налаштування переадресації портів для доступу до Redis
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Огляд

Цей документ описує кроки для налаштування переадресації портів, що дозволяє безпечний доступ до інстансу Redis з локальної машини. Переадресація портів необхідна для тимчасового доступу до ресурсів кластера для розробки або тестування.

== Налаштування

Встановіть з'єднання з `redis` із локальної машини, на якій запускатиметься *_.jar_*:

. Отримайте пароль у середовищі, в секреті `redis-auth` реєстру.

. Визначте `redis master`. Для цього відкрийте логи будь-якого поду `rfS-redis-sentinel` і перегляньте останні логи з `set master`. IP-адреса, яка там вказана, є IP для `master`.

. Перегляньте Pod IP поду `rfR-redis-sentinel`. IP, який збігається з IP з попереднього пункту, є `master`.

. Виконайте переадресацію портів:
+
----
oc port-forward rfr-redis-sentinel-0 6379:6379 (або rfr-redis-sentinel-1)
----

. Перейдіть до Redis через `localhost:6379`.

== Пов'язані сторінки

* xref:registry-admin/abandoned-processes/delete-abandoned-processes.adoc[]
* xref:registry-admin/abandoned-processes/delete-docs-s3-ceph-redis-buckets.adoc[]
* xref:registry-admin/abandoned-processes/define-ceph-buckets-space.adoc[]