== Опис проблеми
Частиною процесу створення/редагування регламенту реєстру є опис моделі даних реєстру. Поточний підхід передбачає використання лише файлів конфігурації для створення моделі даних реєстру.
Користувач повинен використовувати liquibase changelog формат опису моделі даних, що де-факто є описом структури БД.

Частиною web-based адмін порталу редагування версії регламенту реєстру є редагування структури БД.
 Необхідно розробити технічний дизайн підсистеми створення моделі даних реєстру.

=== Ключові пункти проблеми
- Одночасна робота декількох користувачів з однією версією-кандидатом регламенту
- Збереження механізму забезпечення існуючого життєвого циклу регламенту версій (gerrit, jenkins)
- Збереження технічного інструменту відтворення структури БД (liquibase)
- Збереження механізму зміни регламенту шляхом зміни конфігураційних файлів в git
- Забезпечення синхронізації між змінами з адмін порталу і змінами внесеними через Gerrit
- Створення GUI based механізму зміни регламенту реєстру