== Розгортання Платформи реєстрів у продакшені без використання інструментів та роутів для розробки реєстру

Даний документ містить інформацію про загальні положення та технічний дизайн при розгортанні Платформи реєстрів.

=== Загальні положення

* Компоненти, які задіяні у процесах розробки реєстрів не повинні розгортатись разом із продакшн версіями Платформи реєстрів.
* Публічні роути компонентів, які задіяні у процесах розробки реєстрів, не повинні створюватись разом із продакшн версіями Платформи реєстрів.
* Темплейт реєстру повиннен містити змінну для вказання поточного режиму деплоя Платформи реєстрів.
* Підтримується два режими деплоя: `production` та `development`.

=== Верхньорівневий технічний дизайн

|===
|Компонент|Production|Route

|redash-admin
|Ні
|Ні

|redash-admin-adhocworker
|Ні
|Ні

|redash-admin-scheduledworker
|Ні
|Ні

|redash-admin-exporter
|Ні
|Ні

|form-management-modeler
|Ні
|Ні

|pgAdmin
|Ні
|Ні

|registry vault
|Так
|Ні

|external-integration-mocks
|Ні
|Ні

|registry-rest-api
|Так
|Ні
|===

=== Компоненти системи та їх призначення в рамках дизайну рішення

У даному розділі наведено перелік компонент системи, які задіяні або потребують змін/створення в рамках реалізації функціональних вимог згідно технічного дизайну рішення.
