== Розгортання Платформи реєстрів у продакшені без використання інструментів та роутів для розробки реєстру

Даний документ містить інформацію про загальні положення та технічний дизайн при розгортанні Платформи реєстрів.

=== Загальні положення

* Компоненти, які задіяні у процесах розробки реєстрів не повинні розгортатись разом із продакшн версіями Платформи реєстрів.
* Публічні роути компонентів, які задіяні у процесах розробки реєстрів, не повинні створюватись разом із продакшн версіями Платформи реєстрів.
* Темплейт реєстру повиннен містити змінну для вказання поточного режиму деплоя Платформи реєстрів.
* Підтримується два режими деплоя: `production` та `development`.

=== Верхньорівневий технічний дизайн
В таблиці нижче зазначені компоненті та їх роути які задіяні або потребують змін/створення в рамках реалізації функціональних вимог згідно технічного дизайну рішення.

|===
|Компонент|Production|Route

|admin-portal
|Ні
|Ні

|registry-regulation-management
|Ні
|Ні

|[green]#kafka-ui#
|Ні
|Ні

|redash-admin
|Ні
|Ні

|redash-admin-adhocworker
|Ні
|Ні

|redash-admin-scheduledworker
|Ні
|Ні

|redash-admin-exporter
|Ні
|Ні

|[green]#form-management-modeler (legacy)#
|Ні
|Ні

|[green]#pgAdmin#
|Ні
|Ні

|[green]#registry-vault#
|Так
|Ні

|[green]#external-integration-mocks#
|Ні
|Ні

|[green]#registry-rest-api#
|Так
|Ні
|===

Для налаштування відповідних режимів для темплейтів потрібно вказати потрібний режим наступним чином:
----
global:
  deploymentMode: development
----

В шаблоні для деплоя екземпляру реєстра без порталу громадянина необхідно встановити параметр `availablePortals`
----
global:
  availablePortals: ['officer', 'admin']
----

IMPORTANT: За замовчуванням змінна `availablePortals` відсутня, що означає розгортання всіх порталів.