:toc-title: On this page:
:toc: auto
:toclevels: 5
:experimental:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Object data storage

NOTE: 🌐 This document is available in both English and Ukrainian. Use the language toggle in the top right corner to switch between versions.

== General description

The _xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Registry regulations modeling subsystem]_ uses the xref:arch:architecture/platform-technologies.adoc#ceph[Ceph] object storage of the xref:arch:architecture/platform/operational/distributed-data-storage/overview.adoc[_Distributed data storage subsystem_] for saving CSV files containing a list of officers scheduled for importing or already imported to the register.
//_xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Підсистема моделювання регламенту реєстру]_ використовує об'єктне сховище xref:arch:architecture/platform-technologies.adoc#ceph[Ceph] з  xref:arch:architecture/platform/operational/distributed-data-storage/overview.adoc[_Підсистеми розподіленого зберігання даних_] для зберігання CSV-файлів з переліком посадових осіб запланованих для імпорту або вже імпортованих в реєстр.

== Data structures
//== Структури даних

=== user-import

The bucket for storing CSV files with a list of officers for importing to the registry.
//Бакет для зберігання CSV-файлів з переліком посадових осіб для імпорту в реєстр

[NOTE]
--
Read this xref:registry-develop:registry-admin/import-users-officer-description-file-csv.adoc[article] to learn about the CSV file structure.
//Зі структурою CSV-файлу можна ознайомитись в xref:registry-develop:registry-admin/import-users-officer-description-file-csv.adoc[статті]
--

.Description of object meta-data attributes
//.Опис атрибутів мета-даних об'єкту
|===
|Attribute|Data type|Description
//|Атрибут|Тип даних|Опис

|`name`
|_String (Base64)_
|The name of the file containing users for downloading
//|Назва файлу з якого відбувається завантаження користувачів
|===

.Description of the stored document structure
//.Опис структури документу для зберігання
|===
|Attribute|Data type|Description
//|Атрибут|Тип даних|Опис

|`vault:v1:`
|_String_
|Encrypted content of the file containing users for downloading
//|Зашифрований вміст файлу з якого відбувається завантаження користувачів
|===

.Example of a stored document
//.Приклад документу для зберігання
[source,text]
----
vault:v1:q5Rd32QX1bg4CZAmCqeZtliQBZUVfmnqS4wMIXCi9lAp95FRf0Tzx0a7tyFom87ebEbPzR91Yoe2lbAaWbf+Gi547r7MI+YEiFEYXPNeWorO2XReVXJ8pMRdUOz8AxOPkmfOG2/gbDN2cYuWWOpqpXGHrz/QHmKSt7PdT66E7Dc49u3hDxbkiMVwfd0bYxph8ysV7XEkbmxZMK7OEPv07CKx93ePfdGVyQuvNOLNpmocDf
----

=== user-import-archive

The bucket for storing files with a list of officers imported to the registry. Documents have the same structure and meta-data as in the `user-import' bucket.
//Бакет для зберігання файлів з переліком посадових осіб, які було імпортовано в реєстр. Документи мають аналогічно структуру та мета-дані, що і в бакеті `user-import`.