= Відновлення кластера після зміни IP-адрес master-нод

== Опис проблеми

Може виникнути ситуація, коли у всіх мастер-нод Openshift кластера зміниться IP-адреса.
Така ситуація можлива в випадку, коли DHCP сервер по певній причині змінить ІР адреса,
зарезервовані для мастер-нод. Статична ІР адреса є критичною для etcd компонента Openshift
кластера. Після перезавантаження мастер-нод з новими IP адресами система не зможе
завантажитись тому як поди etcd компонента будуть очікувати на отримання саме зарезервованих
ІР адреси, виданих мастер нодам при інсталюванні кластеру Openshift.

== Опис вирішення проблеми

Дана проблема може бути вирішена двома способами. Першим способом являється статична зміна
IP адрес для мастер нод. Після перезавантаження система відновить своє функціонування. Другий
спосіб є продовженням першого за вийнятком того, що в результаті виконання послідовності дій
мастер нодам будуть повернена функція отримання динамічних ІР адрес, зарезервованих DHCP
сервером.

== Опис необхідних інструментів та доступів для вирішення проблеми

Для вирішення проблеми із зміною ІР адрес мастер-нод необхідний доступ по ssh на мастер-ноди
та DHCP сервер.

== Процедура відновлення мастер-нод
=== Спосіб перший
Покрокова процедура відновлення мастер-нод є наступною:

. Залогінитись по ssh на DHCP інстанс.
. Зупинити DHCP сервер командою systemctl stop isc-dhcp-server.
. Зробити резервну копію файлу /var/lib/dhcp/dhcp.lease
. Залогінитись по ssh на одну із мастер-нод кластеру.
. Знайти потрібний мережевий інтерфейс за допомогою команди

    # nmcli device|grep ovs-interface
    br-ex ovs-interface *connected* ovs-if-br-ex

. Перевірити, що це потрібний мережевий інтерфейс. Його ІР адреса повинна відповідати поточним
налаштуванням мережі, відмінним повинен бути тільки *_IP4.ADDRESS[1]_*

    # nmcli device show *br-ex*
    IP4.ADDRESS[1]:                         10.9.1.235/24

. Змінити ІР адресу інстанса на статичну адресу командою, де замість *_<IP ADDRESS>_* необхідно
вказати потрібну ІР адресу кластера.

    # nmcli connection modify br-ex ipv4.addresses <IP ADDRESS>/24


. Перевірити що, мережа працює, виконавши будь яку мережеву команду, наприклад провірити доступність
шлюза за допомогою команди ping:

    # ping 10.9.1.1

. Перезагрузити мастер-ноду.
. Після перезавантаження переконатись, що мастер-нода працює, використовуючи потрібну ІР-адресу.
. Перевірити, що на даній ноді піднялись усі сервісні поди Openshift. Для цього необхідно виконати команду:

    # crictl ps

. Перевірити, що після виконання наведених вище крокі стала доступною API Openshift кластера.
. Для повноцінного відновлення кластеру необхідно повторити процедуру для решти мастер-нод інстансів.

=== Спосіб другий
. Спосіб другий включає в себе кроки 1-12 із <<_спосіб_перший, _першого способу_>>.
. Запустити DHCP сервер командою:

    # systemctl start isc-dhcp-server.

. Виконати процедуру по заміні etcd member (мастер-ноди) згідно _https://docs.okd.io/latest/backup_and_restore/control_plane_backup_and_restore/replacing-unhealthy-etcd-member.html[документації]_ в наступному порядку:
. Послідновно замінити два наступних непрацюючих etcd member (мастер-ноди).
. Перевірити, що всі три мастер-ноди працюють і штатному режимі командою:

    $ oc get nodes
    NAME                         STATUS   ROLES    AGE   VERSION
    mdtuddm-2n5bl-master-0       Ready    master   25h   v1.20.0+87cc9a4-1079
    mdtuddm-2n5bl-master-1       Ready    master   25h   v1.20.0+87cc9a4-1079
    mdtuddm-2n5bl-master-2       Ready    master   25h   v1.20.0+87cc9a4-1079

. Виключити мастер-ноду зі статичною адресою. Після того, як вона перейде в *Not Ready* стан, виконати заміну даного etcd member (мастер-ноди) згідно документації.
. Перевірити, що всі три мастер-ноди працюють в штатному режимі. Видалити виключену мастер-ноду із статичною ІР адресою.


