:toc-title: ЗМІСТ
:toc: auto
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Категоризація доступних послуг у кабінетах користувачів

[CAUTION]
Документ у процесі розробки.

== Проблематика

У Кабінетах користувачів усі доступні послуги представлені в єдиному списку, що є незручним для користувачів реєстрів із великою кількістю таких послуг.

Щоб поліпшити досвід користувачів, реалізовано можливість категоризації послуг за допомогою груп та можливість управління порядком їх відображення. Це дозволяє більш ефективно відображати та знаходити необхідні послуги у реєстрах.

== Загальні принципи та положення

Розробник регламенту може групувати та сортувати бізнес-процеси через вебінтерфейс адміністративного порталу. Зміни до налаштувань групування та сортування валідуються на етапі публікації регламенту реєстру та розгортаються на відповідному середовищі.

Надалі користувачі Кабінетів посадової особи та отримувача послуг зможуть переглядати список бізнес-процесів із розділенням на групи та впорядкованих згідно з налаштуваннями регламенту.

[NOTE]
====
Бізнес-процес не може бути прив'язаний до двох чи більше груп одночасно. Група не є обов'язковою, і якщо бізнес-процес не прив'язаний до групи, він відображається поза групою. Якщо відсутні налаштування груп, це означає, що жоден бізнес-процес не прив'язаний до групи.

Групи, в яких немає жодного бізнес-процесу, доступного користувачу, не відображаються в Кабінетах користувачів, але вони відображаються в інтерфейсі Кабінету адміністратора регламентів. Вкладеність груп не підтримується.
====

== Налаштування груп бізнес-процесів у Кабінеті адміністратора регламентів

Налаштувати категоризацію бізнес-процесів за допомогою груп можна наступним чином:

. Увійдіть до [.underline]#Кабінету адміністратора регламентів# у своєму реєстрі.

. Відкрийте, або створіть нову версію-кандидат на внесення змін.

. Відкрийте розділ [.underline]#Моделі процесів#.

//TODO: HERE