= Аудит регламенту реєстру. Загальні рекомендації

Документ містить перелік рекомендацій, які дозволяють оцінити якість регламенту реєстру та виявити можливі проблеми,
які можуть виникнути при його використанні. Рекомендації згруповані відповідно до структури
xref:arch:architecture/registry/administrative/regulation-management/registry-regulation/registry-regulation.adoc[Цифрового
 регламенту реєстру].

Перед впровадженням регламенту в промислову експлуатацію рекомендується провести повний аудит регламенту реєстру відповідно
до пунктів описаних в розділах:

* xref:registry-develop:registry-audit-instruction/modules/bp-audit.adoc[Аудит бізнес-процесів]
* xref:registry-develop:registry-audit-instruction/modules/dm-audit.adoc[Аудит моделі даних]
* xref:registry-develop:registry-audit-instruction/modules/form-audit.adoc[Аудит UI-форм бізнес-процесів]
* xref:registry-develop:registry-audit-instruction/modules/sec-audit.adoc[Аудит безпеки]
* xref:registry-develop:registry-audit-instruction/modules/excerpt-audit.adoc[Аудит шаблонів витягів]
* xref:registry-develop:registry-audit-instruction/modules/report-audit.adoc[Аудит шаблонів аналітичних звітів]
* xref:registry-develop:registry-audit-instruction/modules/integration-audit.adoc[Аудит зовнішніх інтеграцій]

Процес проведення аудиту є поза областю цього документу, але може бути використаний один з наступних підходів:

* Self-review команди розробки
* Проведення аудиту зовнішньою командою аудиторів
* Проведення аудиту зовнішньою командою аудиторів з активним залученням команди розробки. Цей підхід може містить
проведення воркшопів з опитуванням команди розробки за пунктами аудиту і подальший незалежний аналіз кодової бази.

Застосування пунктів оцінки якості рекомендується, але не обмежується проведенням аудиту перед виходом в промислову
експлуатацію і повинно проводитися постійно в процесі розробки регламенту реєстру. Ознайомлення з рекомендаціями повинно
бути обов'язковим для всіх учасників процесу розробки регламенту реєстру перед початком роботи над регламентом.