= Архітектурний робочий розділ

== План робіт по технічній документації

* [ ] Створити архітектурні діаграми для розділів підсистем Платформи
* [ ] Визначити актуальність залишку технічних статей у розділі "Архів технічної документації" та рознести по відповідним розділам або видалити
* [ ] Створити референтний приклад документування низькорівневого дизайну сервісу
* [ ] Фіналізувати структуру документування низькорівневого дизайну сервісу
* [ ] Задокументувати структуру регламенту реєстру
* [ ] Задокументувати структуру конфігурації реєстру
* [ ] Створити діаграму логічної архітектури Платформи
* [ ] Створити діаграму розгортання Платформи
* [ ] Створити набір типових візуальних діаграм у якості прикладу для уніфікації підходу до опису дизайну Платформи
* [ ] Створити референтний приклад документування низькорівневого дизайну бібліотек Платформи
* [ ] Задокументувати шаблон та структуру документування низькорівневого дизайну бібліотек
* [ ] Виявити статті розділу "Архітектурна документація", які продубльовано в інструкціях користувачів та видалити дублікати