= Принципи розробки архітектурної документації

_Платформа Реєстрів_ представляє собою розподілену систему з мікросервісною архітектурою, яка складається з 36+ підсистем різного призначення.

З ціллю спрощення процесу ознайомлення з високорівневим дизайном рішення, архітектурна документація структурована за top-down принципом з застосуванням технік логічної декомпозиції Платформи Рєестрів на окремі складові різних рівнів:

* Рівень Платформи
* Рівень групування підсистем за призначенням в операційну та адміністративну зони
* Рівень підсистеми
* Рівень сервісів підсистеми

Загальні функціональні та нефункціональні вимоги відображені на рівні Платформи та на рівні окремих підсистем, які їх реалізують з ціллю забезпечення відповідності вимог до технічного дизайну рішень.

При розробці та підтримці технічної документації, необхідно слідувати наступним принципам:

* Цілісне відображення актуального стану архітектури рішення для обраної версії
* Відсутність дублювання інформації як у межах _Antora_ документації та і з іншими базами знань (_Confluence_)
* Узгоджене використання єдиної термінології, визначеної у глосарії
* Єдиний підхід до структурування документації за принципом _top-down_ для рішення в цілому, підсистем та окремих компонент
* Єдиний підхід до структурування статей розділу дизайну підсистем та окремих компонентів
* Єдиний підхід до створення архітектурних діаграм (стиль, гамма, легенда, іменування, тощо.)
* Єдиний підхід до формування та структурування контенту статей опису "transition"-дизайну