= Управління ресурсами сервісів реєстру

== Управління налаштуваннями та ресурсами Java-додатків

* Підібрати оптимальну версію _GC_ згідно профіля додатку та доступних для нього ресурсів
* Явним чином вказати версію _GC_ для використання _JVM_ за допомогою службової опції задля забезпечення прогнозованості поведінки у разі оновлення версії _Java_ (_-XX:+UseG1GC_)
* Явним чином визначити мінімальний / максимальний об'єм пам'яті, який виділено під _Heap_ згідно до результатів тестування навантаження:
** _-Xms_ / _-Xmx_
** _-XX:InitialHeapSize_ / _-XX:MaxHeapSize_
* Встановити _-Xms_ = _-Xmx_ для запобігання втрати часу на виділення пам'яті при експлуатації додатку
* Розглянути доцільність використання опції _-XX:+ExplicitGCInvokesConcurrent_ у разі використання _G1_ для мітігування _Stop-The-World_ поведінки _GC_ при явних викликах _System.gc()_
* Розглянути доцільність використання опції _-XX:+AlwaysPreTouch_ для зменшення втрат часу _JVM_ у процесі експлуатації на виділення фізичних ресурсів на відміну від резервування віртуальних
* Розглянути використання опцій _-Dfile.encoding=UTF-8_ та _-Duser.timezone=UTC_

[NOTE]
--
Детальніше можна ознайомитись за посиланням xref:attachment$/architecture-workspace/registry-resources.xlsx[Управління ресурсами реєстру].
--