= Developing and maintaining technical product documentation
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

== Description of tools

The development of documentation is conducted using the following tools:

* https://asciidoc.org/[AsciiDoc] -- a markup language supporting structural and semantic elements for creating text documents.
* https://plantuml.com/[PlantUml] -- an open-source tool for describing UML diagrams and visualizing `JSON` and `YAML` in text form.
* https://draw.io/[Draw.IO] -- an online tool for creating various types of diagrams, with the ability to save in `SVG` format.

For structuring text `AsciiDoc` documents and creating a unified static HTML site, https://antora.org/[Antora] is used, based on _.yml_ playbook configurations.

=== Official documentation of tools

* https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc Documentation]
* https://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Technical Writer's Guide]
* https://docs.antora.org/antora/2.0/[Antora Documentation]

=== Local environment for developing technical documentation

Necessary tools for development:

- https://www.jetbrains.com/[IntelliJ IDEA / JetBrains WebStorm]: An integrated development environment.
- https://plugins.jetbrains.com/plugin/7391-asciidoc[AsciiDoc JetBrains Plugin]: A plugin for `AsciiDoc` syntax support.
- https://plugins.jetbrains.com/plugin/7017-plantuml-integration[PlantUML Integration]: For developing diagrams with `PlantUML` syntax.
- https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia[Asciidoctor.js Live Preview]: A *Chrome* extension for viewing `AsciiDoc` documents through a web browser.

== Viewing technical documentation through IntelliJ IDEA

IntelliJ IDEA provides several ways for local viewing of technical documentation. Here's how you can utilize these options:

=== Using the built-in AsciiDoc toolbar

You can use the built-in toolbar above the documentation development window in an open AsciiDoc (`.adoc`) file. Here, you will find options for real-time documentation preview mode:

. *Show Editor and Preview*:

** This option lets you see both the code editor and the preview window simultaneously.
** You can edit the documentation in the editor and immediately see the results of these changes in the preview window.
** This is useful for quickly verifying changes, ensuring an efficient editing process.
. *Show Preview Only*:

** This mode provides only the preview window without the code editor.
** It's ideal for focusing on the final appearance of the documentation, especially when you need to check the overall format and layout of elements.
** You can easily switch to *Show Editor and Preview* mode if you need to make changes.

=== Viewing options in the top right corner of the development window

You can also use the viewing options located in the top right corner of the development window:

. *Built-In Preview*:

** Opens the built-in preview window directly in the IntelliJ IDEA development environment.
** This is convenient for quick viewing and editing.
. *View in external browser*:

** *Chrome*: If Chrome is installed, select this option to open a tab with the documentation in the browser.
** *Firefox*: Similarly, select Firefox for viewing in this browser.
** *Edge*: If you use Edge, choose this option.

TIP: 💡 You can also open the desired viewing option by pressing the key combination `Alt+F2` &gt; `Preview File in...`.

These IntelliJ IDEA features allow flexible work with technical documentation, providing various viewing options to meet the needs of developers and technical writers.

== Building Antora in a local environment

You can build the overall structure of the documentation using Antora in a local environment.

=== Installing Antora

NOTE: 📝 Complete installation instructions for Antora can be found at https://docs.antora.org/antora/latest/install/install-antora/[this link].

. Check if Antora is installed:
+
[source,bash]
----
antora -v
----

. Install *Node*.
+
To check if *Node* is installed and its version, execute the following command:
+
[source,bash]
----
node --version
----

==== Installing Node on Linux

* Install Node on Linux using the command:
+
[source,bash]
----
nvm install --lts
----

* See detailed instructions https://docs.antora.org/antora/latest/install/linux-requirements/[at this link].

TIP: 💡 Linux users are invited to share their comments and supplement important information missing in this brief guide or the complete documentation.

==== Installing Node on macOS

* Install Node on macOS using the command:
+
[source,bash]
----
nvm install --lts
----

* View detailed instructions https://docs.antora.org/antora/latest/install/macos-requirements/[at this link].

TIP: 💡 macOS users are invited to share their comments and supplement important information missing in this brief guide or the complete documentation.

==== Installing Node on Windows

For installing Node on Windows, follow these steps:

. *Install https://chocolatey.org/[Chocolatey]:*

.. Open *PowerShell* as an administrator.
.. Execute the command:
+
[source,powershell]
----
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
----

. *Install nvm:*

.. Use the same *PowerShell* window as an administrator.
.. Execute the command:
+
[source,powershell]
----
choco install -y nvm
----

. *Install Node:*

.. Open a new *PowerShell* window.
.. Execute the command:
+
[source,powershell]
----
nvm install 16.20.2
----

[IMPORTANT]
====
🔑 Specify the exact version of Node for Windows (e.g., `16.20.2`) if you encounter an issue https://github.com/coreybutler/nvm-windows/issues/214[nvm-windows#214].
====

[NOTE]
====
📝 If Node is not installed after running the `nvm install` command, try installing Node through *Chocolatey* using the command:


[source,powershell]
----
choco install nodejs-lts
----

or

[source,powershell]
----
choco install nodejs
----

TIP: 💡 Detailed instructions can be found https://docs.antora.org/antora/latest/install/windows-requirements/[at this link].

Windows users are invited to share their comments and supplement important information missing in this brief guide or the complete documentation.
====

==== Installing Antora globally using `npm`

. You can install Antora globally so that the `antora` command is available on your `PATH`. To install Antora globally, pass the `-g` option to `npm i`.
+
[source,bash]
----
npm i -g @antora/cli@3.1 @antora/site-generator@3.1
----

. Verify the antora command is available on your `PATH` by running:
+
[source,bash]
----
antora -v
----

. If the installation was successful, the command should report the version of the Antora CLI and site generator.
+
[source,bash]
----
antora -v
@antora/cli: 3.1.5
@antora/site-generator: 3.1.5
----

TIP: 💡 See also: https://docs.antora.org/antora/latest/install/install-antora/#install-dir[Installing Antora Locally].

=== Granting access for Antora to remote Git repositories

NOTE: 📝 Complete instructions for accessing private repositories can be found https://docs.antora.org/antora/latest/playbook/private-repository-auth/[at this link].

==== Populating the credential store interactively

To grant Antora access to your source repositories, follow these steps:

. Open a terminal and execute the command to configure Git:
+
[source,bash]
----
git config --global credential.helper store && \
echo -n 'Repository URL: ' && read REPLY && \
git ls-remote -h $REPLY > /dev/null
----
+
NOTE: 📝 For `'Repository URL: '`, enter the URL of the Git repository to which you need to grant access.

. Repeat these steps for each repository from your Antora playbook. In our example, it's the _site.yml_ file.)

==== Populating the credential store directly (GitLab example)

Use personal access tokens to grant access to repositories:

. In your GitLab account, open https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html[GitLab personal access token] and create a token with `read_repository` scope.

. To grant access to repositories, use one of the following methods:

** *Through the `GIT_CREDENTIALS` environment variable:*
Set the environment variable with the value of the personal access token. For example:
+
[source,bash]
----
export GIT_CREDENTIALS='https://<FirstName_LastName>:<personalAccessToken>@gitlab.example.com'
----
+
Antora will use this token for all repositories in `gitlab.example.com`.

** *Through the _$HOME/.git_credentials_ file:*
Create or modify the `.git_credentials` file. Add lines with the necessary repositories in the following format:
+
[source,bash]
----
https://<personalAccessToken>:@gitlab.example.com/<repository_path>
# or
https://<FirstName_LastName>:<personalAccessToken>@gitlab.example.com/<repository_path>
# or use a single token for all repositories
https://<FirstName_LastName>:<personalAccessToken>gitlab.example.com/
----

=== Generating technical documentation

* Generate a static HTML site from the documentation using the command:
+
[source,bash]
----
antora site.yml
----

* Generate a static _LOCAL_ HTML site from the documentation using the command:
+
[source,bash]
----
antora site-local.yml
----

The generated site can be viewed locally through the default browser. The output of this site will be available at the path defined in your site.yml playbook:

----
output:
  dir: ./output/ua
----

=== Setting up quick launch for a documentation generation process in IntelliJ IDEA

To automate the documentation generation step, you can set up a *Shell Script* run configuration in IntelliJ IDEA:

. From the main menu, select: _Run &gt; Edit Configurations &gt; Add New Configuration_.
. Choose the *Shell Script* run configuration type.
. Specify the name *Name: antora-site*.
. Specify the script type *Execute: Shell Script*.
. Specify the script *Script text: _antora site-local.yml_*.

After setting up, IntelliJ IDEA will have an additional run configuration *antora-site* for generating technical documentation through Antora, which can be used for the quick launch of the process.