= Формування технічної документації

== Опис інструментів для розробки технічної документації проекту

.Розробка документації ведеться:
- на мові https://asciidoc.org/[AsciiDoc] (мова розмітки з підтримкою структурних та семантичних елементів, яка використовується для формування текстових документів)
- за допомогою https://plantuml.com/[PlantUml] (інструмент з відкритим кодом, який дозволяє описувати UML діаграми, візуалізувати JSON та YAML у текстовому вигляді за допомогою власного доменного синтаксису)
- та за допомогою https://draw.io/[Draw.IO] (онлайн інструмент створення діаграм різних типів з можливостями збереження у SVG форматі с підтримкою подальшого редагування, можна використовувати будь-який інший svg-редактор)

Для структурування текстових AsciiDoc документів за розділами та формування єдиного статичного HTML сайту з технічною документацією на базі _.yml_ плейбука конфігурації використовується https://antora.org/[Antora]

=== Офіційна документація інструментів

- https://docs.asciidoctor.org/asciidoc/latest/[Документація AsciiDoc]
- https://asciidoctor.org/docs/asciidoc-writers-guide/[Гайд техрайтера AsciiDoc]
- https://docs.antora.org/antora/2.0/[Документація Antora]

=== Локальне оточення для розробки технічної документації

.Для ведення розробки документації, необхідно встановити:
- https://www.jetbrains.com/[IntelliJ IDEA / JetBrains WebStorm] -- інтегроване середовище розробки
- https://plugins.jetbrains.com/plugin/7391-asciidoc[AsciiDoc JetBrains плагін] -- підтримка синтаксису AsciiDoc та попереднього перегляду в IntelliJ IDEA та WebStorm
- https://plugins.jetbrains.com/plugin/7017-plantuml-integration[PlantUML Integration IntelliJ IDEA плагін] -- плагін для розробки діаграм у текстовому вигляді з використанням PlantUML синтаксису та їх попереднього перегляду
- (опційно) https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia[Asciidoctor.js Live Preview] -- розширення до браузера Chrome для перегляду AsciiDoc документів (файли з розширенням _.adoc_)

== Перегляд технічної документації через вбудовані можливості перегляду IntelliJ IDEA

Для перегляду згенерованої документації на локальному оточенні можна використовувати вбудовані можливості перегляду IntelliJ IDEA (_File > Open In > Browser > Built-in Preview_)

== Локальне будування Antora

Також можна збудувати загальну структуру документації https://gitbud.epam.com/mdtu-ddm/general/ddm-architecture[ddm-architecture] за допомогою Antora у локальному оточенні та відкрити збудований файл _index.html_ браузером, встановленим за замовчуванням

=== Встановлення Antora

[NOTE]
Повна інструкція встановлення Antora https://docs.antora.org/antora/2.3/install/install-antora/[тут]

Щоб перевірити чи встановлена Antora можна виконати

[source,bash]
----
antora -v
----

Для встановлення Antora потрібно для початку встановити Node або yarn

Щоб перевірити чи Node встановлений та якої версії можна виконати

[source,bash]
----
node --version
----

==== Встановлення Node на Linux

Для встановлення Node на Linux треба виконати

[source,bash]
----
nvm install --lts
----

[NOTE]
--
Якщо у вас нема встановленого nvm, то його можна встановити https://github.com/nvm-sh/nvm#installing-and-updating[за інструкцією]

Повна інструкція по встановленню Node на Linux https://docs.antora.org/antora/2.3/install/linux-requirements/[тут]

Користувачі Linux ласкаво просимо додати важливих деталей які не вказані в цій або повній інструкції
--

==== Встановлення Node на macOS

Для встановлення Node на macOS треба виконати

[source,bash]
----
nvm install --lts
----

[NOTE]
--
Якщо у вас нема встановленого nvm, то його можна встановити https://github.com/nvm-sh/nvm#installing-and-updating[за інструкцією]

Повна інструкція по встановленню Node на macOS https://docs.antora.org/antora/2.3/install/macos-requirements/[тут]

Користувачі macOS ласкаво просимо додати важливих деталей які не вказані в цій або повній інструкції
--

==== Встановлення Node на Windows

Для встановлення Node на Windows треба:

* Встановити https://chocolatey.org/[Chocolatey]
** Відкрити PowerShell від імені адміністратора
** Виконати:

[source,powershell]
----
Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
----

* Встановити nvm:
** Відкрити PowerShell від імені адміністратора (можна в тому ж вікні що й для встановлення Chocolatey)
** Виконати:

[source,powershell]
----
choco install -y nvm
----

* Встановити node:
** Відкрити нове вікно PowerShell
** Виконати:

[source,powershell]
----
nvm install 16.1.0
----

[IMPORTANT]
Для Windows треба вказувати точну версію Node (приклад - 16.0.1) доки не вирішено https://github.com/coreybutler/nvm-windows/issues/214[nvm-windows#214]

[NOTE]
--
Якщо після `nvm install` у вас нема встановленого Node, то можна спробувати встановити Node через Chocolatey `choco install nodejs-lts` або `choco install nodejs`

Повна інструкція по встановленню Node на Windows https://docs.antora.org/antora/2.3/install/windows-requirements/[тут]

Користувачі Windows ласкаво просимо додати важливих деталей які не вказані в цій або повній інструкції
--

==== Встановлення Antora за допомогою npm

Щоб встановити Antora за допомогою npm треба виконати:

[source,bash]
----
npm i -g @antora/cli@2.3 @antora/site-generator-default@2.3
----

==== Встановлення Antora за допомогою yarn

Щоб встановити Antora за допомогою yarn треба виконати:

[source,bash]
----
yarn global add @antora/cli@2.3

yarn global add @antora/site-generator-default@2.3
----

=== Надання Antora доступу у віддалені Git репозиторії

.Щоб надати доступ Antora до репозиторіів треба:
* Виконати:

[source,bash]
----
git config --global credential.helper store && \
  echo -n 'Repository URL: ' && read REPLY && \
  git ls-remote -h $REPLY > /dev/null
----

* Вписати URL Git репозиторію до якого треба надати доступ (та повторити для кожного репозиторію із site.yml)

.Також можна використати токени особистого доступу:
* Зайти до https://gitbud.epam.com/-/profile/personal_access_tokens[GitLab personal access token]
* Створити токен зі скоупом `read_repository`
* Та надати доступ до репозиторіїв:
** Через змінну оточення `GIT_CREDENTIALS` зі значенням `https://<FirstName_LastName>:<personalAccessToken>@gitbud.epam.com` (Antora буде використовувати цей токен для всіх репозиторіїв у https://gitbud.epam.com)
** Через файл `.git_credentials` на базі файлу шаблону _.git-credentials.local_ шляхом копіювання та видалення суфіксу _.local_ та додання необхідних репозиторіїв у вигляді:

[source,bash]
----
https://<personalAccessToken>:@gitbud.epam.com/<repository_path>
# aбо
https://<FirstName_LastName>:<personalAccessToken>@gitbud.epam.com/<repository_path>
# aбо один токен на всі репозиторії
https://<FirstName_LastName>:<personalAccessToken>@gitbud.epam.com/
----

[NOTE]
Повна інструкція надання доступу до приватних репозиторіїв знаходиться https://docs.antora.org/antora/2.3/playbook/private-repository-auth/[тут]

=== Генерація технічної документації

Для генерації статичного HTML сайту документації з використанням останніх версій розділів з відповідних репозиторіїв треба виконати:

[source,bash]
----
antora site.yml
----

Для генерації статичного HTML сайту документації з використанням локальних копій розділів документації (необхідно створити з файлу _site-template.yml_ файл _site-local.yml_ та відкорегувати шляхи до локальних директорій. _site-local.yml_ знаходиться у _.gitignore_):

[source,bash]
----
antora site-local.yml
----

В обох випадках, сайт технічної документації буде згенеровано у директорію, налаштовану у _.yml_ плейбуці:

[source,yaml]
----
output:
  dir: ./build/site
----

Проглянути збудований сайт можна через браузер, встановлений за замовчуванням, шляхом відкриття файлу _./build/site/index.html_ в IntelliJ IDEA (_File > Open In > Browser > Default_)

=== Налаштування швидкого запуску процесу генерації документації в IntelliJ IDEA

.Для автоматизації кроку генерації документації, в IntelliJ IDEA можно налаштувати конфігурацію запуску **Shell Script**:
- Викликати з головного меню: _Run > Edit Configurations > Add New Configuration_
- Вибрати тип конфігурації запуску **Shell Script**
- Вказати ім'я **Name: antora-site**
- Вказати тип скрипта **Execute: Shell Script**
- Вказати скрипт **Script text: antora site-local.yml**

Як результат, в IntelliJ IDEA з'явиться додаткова конфігурація запуску для генерації технічної документації через Antora **antora-site**, яку можна використовувати у якості швидкого виклику.