= Adding POST methods generation for data retrieval
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== General overview

In the current implementation, issues have arisen with searching data using GET requests, specifically related to the _IN/NOT_IN_ type of search.

These problems are associated with the inability to correctly handle cases where a request of the form _GET /search?inParam=value1,value2_ is received, where the parameter `inParam` is a single value _value1,value2_, rather than an array of values _["value1", "value2"]_. Spring Web framework parses such structures in the request as an array _[value1, value2]_.

As a workaround, it became possible to format the request as _GET /search?inParam=value1,value2&inParam=_. In this case, Spring constructs the parameters as an array _["value1,value2", ""]_, which is valid for searching with the IN/NOT_IN type.

However, the use of such a workaround is only feasible for cases where the client can explicitly configure the HTTP request with the necessary search parameters in the correct format.

These scenarios include:

* Integration through UI forms
* xref:arch:architecture/registry/operational/registry-management/platform-evolution/public-api/public-api.adoc[Public API]
* xref:arch:architecture/registry/operational/external-integrations/cross-registry.adoc#_інтеграція_з_сторонніми_системами[Integration with external systems]

However, for scenarios where data search requests are generated programmatically within microservices of the system, such as:

include::ROOT:partial$admonitions/ua-specific.adoc[]

* Setting up data search endpoints through Trembita (UA-specific) secure exchange gateway (via _soap-api_)
* Using data search endpoints through delegates in business processes (via _bpms_)

The existing workaround cannot be applied, or it will create significant issues for the development and maintenance of such a solution, potentially leading to blocking problems within development teams.

To address such issues, it was decided that in addition to generating a GET interface for data search, a POST interface should also be generated. When using the POST interface, the required search parameters will be formatted in the request body in _JSON_ format, which allows for a proper differentiation between individual values and arrays.

== General principles and provisions

* GET and POST endpoints should be generated together
* For internal integrations within the system, transition to using POST is recommended
* The use of GET methods remains for backward compatibility when used by clients in scenarios such as _Search with UI forms_, _Public API_, and _Integration with external systems_.
* The use of POST methods for scenarios involving _Public API_ and __Integration with external system__s will become possible.
* The use of POST requests for retrieving the data does not affect scenarios involving data modification, where the POST method is also used (all Network Policies remain valid, and HTTP header checks during data saving remain applicable).
* Transitioning UI forms to use the POST method is currently not required and is beyond the scope

== High-level development plan

=== Example

.Search condition
[source, xml]
----
<changeSet author="registry owner" id="create SC registration_equal_laboratory_id_solution">
    <ext:createSearchCondition name="some_sc">
        <ext:table name="some_table" alias="r">
            <ext:column name="some_id" />
            <ext:column name="some_equal_column" searchType="equal"/>
            <ext:column name="some_in_column" searchType="in"/>
        </ext:table>
    </ext:createSearchCondition>
</changeSet>
----

Together with the existing GET endpoint, a POST should be generated:

.New API
[%collapsible]
====
swagger::{attachmentsdir}/architecture/registry/operational/registry-management/sc-post-migration/swagger.yml[]
====

=== Technical expertise

* BE

=== Development plan

[cols="3,5,5"]
|===
| Component | Required extension | Goal
| service-generation-utility | Add generation of POST endpoints for data search | Invoke new endpoints with _soap-api_ and _bpms_
| service-generation-utility | Change generation of soap-api code to send requests to rest-api, transition to POST | Avoid issues with setting up SC for IN/NOT_IN search through Trembita
| service-generation-utility | Modify AuthPolicy for external integrations with rest-api-ext, allow handling of POST for data search endpoints (should not affect data modification endpoints) | Enable calling POST endpoint for _Data search without Trembita_ scenario.
| rest-api-core-base-image | Remove validation of specific headers (_X-Digital-Signature_, _X-Source-Business-Process_ etc.) | In the current implementation, header validation is set based on the HTTP method, not the invoked endpoint. With the new approach, this logic needs to be changed
| bpms | Modify search delegates (_DataFactoryConnectorSearchDelegate_, _RegistryDataFactoryConnectorSearchDelegate_), adding possibility to accept _Map<String, Object>_ as a search parameter (now - _Map<String, String>_) | For proper _IN type_ search in POST request, a list of valid values will need to be passed. These will be sent from bpms as a string key - list value. There should be no compatibility issues, as Map<String, Object> is broader than the current Map<String, String>.
| ddm-data-factory-client | Update Feign clients used by delegates to use POST method | Use in bpms client
| platform-gateway | Add handling of POST search requests instead of GET | As the Trembita-less search scenario switches to POST, the proxy service platform-gateway also needs to switch to handling requests of this method
|===

It is also important to document the functionality:

* Document the specifics of using GET methods for IN/NOT_IN search
* Document recommendations for forming the body of a POST request (especially for IN/NOT_IN search)