= Типові розширення для інтеграції з іншими реєстрами на Платформі
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:sectanchors:
:sectlinks:

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

В рамках REST-взаємодії з іншими реєстрами на Платформі та бізнес-процесами, що змодельовані всередині регламентів таких реєстрів, імплементовано додаткові розширення-конектори (делегати) для передачі або отримання даних до/з цих реєстрів.

На сьогодні Платформа підтримує 2 таких делегати: ::

* *Start business process in another registry* -- делегат для ініціювання бізнес-процесу, що змодельований в рамках регламенту іншого реєстру на Платформі.

* *Search for entities in another registry data factory* -- делегат для отримання даних сутностей (таблиць) у базі даних іншого реєстру, що розгорнутий на Платформі.

[CAUTION]
====
Для того, щоб взаємодіяти з цільовим реєстром на Платформі, а також бізнес-процесами, що у ньому розгорнуті, недостатньо просто використовувати інтеграційні конектори.

Необхідно попередньо: ::

* Відкрити доступ до такого реєстру в адмін-консолі для керування реєстрами Control Plane (_детальну інструкцію ви можете переглянути на сторінці xref:admin:registry-management/control-plane-registry-grant-access.adoc[]_).

* Надати доступ до відповідних представлень та REST API реєстру на рівні моделі даних (_детальну інструкцію ви можете переглянути на сторінці xref:data-modeling/data/physical-model/rest-api-view-access-to-registry.adoc[]_).
====

== Огляд секції

* xref:registry-develop:bp-modeling/bp/element-templates/rest-integration-registries/start-bp-another-registry.adoc[]

* xref:registry-develop:bp-modeling/bp/element-templates/rest-integration-registries/search-for-entities-another-registry.adoc[]