@startuml
skinparam shadowing false
skinparam DatabaseBackgroundColor white
skinparam DatabaseBorderColor #2688d4
skinparam QueueBackgroundColor white
skinparam QueueBorderColor #2688d4
skinparam NoteBackgroundColor white
skinparam NoteBorderColor #2688d4
skinparam sequence {
    ArrowColor #2688d4
    ActorBorderColor #2688d4
    LifeLineBorderColor #2688d4
    ParticipantBorderColor #2688d4
    ParticipantBackgroundColor white
    BoxBorderColor #2688d4
    BoxBackgroundColor white
}

box "Upstream Service"
    participant "Upstream \nService" as upstream_service
    participant "Notification \nFacade" as notification_facade
    participant "Notification \nEvent Publisher" as notification_kafka_publisher
end box

queue "'user-notifications'\n Kafka Topic" as user_notifications_kafka_topic

== Sending a notification to the user by the specified communication channel==

activate upstream_service
  upstream_service -> notification_facade: Request to send a message \nby the specified communication channel
  note left
   {
     "context": {
       "system": "Low-code Platform",
       "application": "<upstream-service>",
     },
     "notification": {
       "templateName": "{notificationTemplate}"
     },
     "recipients": [
       {
          "id": "<user id - optional>",
          "channels": [
            {
              "channel": "email",
              "email": "<Email of the user>"
            }
          ],
          "parameters": [
            {
                "key": "<key>",
                "value": "<value>"
            }
          ]
       }
     ]
   }
  end note
  activate notification_facade
    notification_facade -> notification_kafka_publisher: Sending \nnotification
    activate notification_kafka_publisher
      notification_kafka_publisher -> user_notifications_kafka_topic: Publication of a request for \nsending a notification
      user_notifications_kafka_topic --> notification_kafka_publisher
      notification_kafka_publisher --> notification_facade
    deactivate notification_kafka_publisher
    notification_facade --> upstream_service
  deactivate notification_facade
deactivate upstream_service
@enduml