== Аудит

=== Компоненти аудиту

image::datafactory/high-level-audit.svg[]


Всі аудито-важливі події фіксуються як події додатку (Application Events), за опрацювання цих подій відповідальна audit-lib бібліотека. 

Всі події опрацьовуються асинхронно і не вносять значний вплив на швидкодію основних сценаріїв додатків.

Запис в БД відбувається за допомогою Kafka https://kafka.apache.org/documentation.html#connect[connect-api], що дозволяє виділити опрацювання повідомлень подій в окремий додаток, який використовує вбудований інструментарій Kafka.
Використовується https://docs.confluent.io/kafka-connect-jdbc/current/sink-connector/index.html[Confluent JDBC Sink]

== Події
=== Структура події
[plantuml, event, svg]
----
@startjson
{
    "requestId": "ідентифікатор запита з MDC",
    "application": "ім'я додатка",
    "name": "назва події",
    "source_business_id": "ідентифікатор конкретного бізнес процесу",
    "source_business_process": "назва бізнес процесу",
    "source_system": "назва системи що викликає",
    "type": "тип події SECURITY_EVENT/USER_ACTION",
    "timestamp": "час коли сталась подія",
    "user": "користувач з яким асоціована подія",
    "context": {
        "": "додаткові важливі параметри специфічні для кожної окремої події",
        "": "наприклад:",
        "action": "",
        "step": "...",
        "": "..."
    }
}
@endjson
----

=== Структура таблиці для збереження 

[plantuml, table, svg]
----
@startjson
{
    "id": "ідентифікатор події в БД",
    "request_id": "(varchar) відповідне поле події",
    "application": "(varchar) відповідне поле події",
    "name": "(varchar) відповідне поле події",
    "type": "(varchar) відповідне поле події",
    "timestamp": "(varchar) відповідне поле події",
    "user_id": "(varchar) відповідне поле події",
    "user_name": "(varchar) відповідне поле події",
    "source_business_id": "(varchar) відповідне поле події",
    "source_business_process": "(varchar) відповідне поле події",
    "source_system": "(varchar) відповідне поле події",
    "context": "(varchar) JSON представлення деталей події",
    "received": "(timestamp default now()) час коли повідомлення було записано в БД"
}
@endjson
----

=== Основні події

Аудиту підлягають операції користувача в системі та окремі події системи.
Операції користувача фіксуються на початку операції на етапі звернення до сторонніх ресурсів системи (БД, Ceph) та в кінці операції.
Події системи фіксуються лише раз - в момент і в місці виникнення події. 

==== Операції користувача
* Спроба\Створення нового запису в БД
* Спроба\Зміна запису в БД
* Спроба\Видалення запису в БД
* Запит даних які носять конфіденційний характер

===== Структура контексту для операцій користувачів

[plantuml, context_create_delete, svg]
----
@startjson
{
    "action": "INSERT / DELETE",
    "step": "...",
    "tablename": "...",
    "row_id": "..."
}
@endjson
----

[plantuml, context_select_update, svg]
----
@startjson
{
    "action": "READ / UPDATE",
    "step": "...",
    "tablename": "...",
    "row_id": "...",
    "fields": "[...]"
}
@endjson
----

==== Події системи
* Отримані дані не відповідають підпису
* Відсутній JWT токен 

===== Структура контексту для подій системи
[plantuml, context_system, svg]
----
@startjson
{
    "action": "SIGN_BREACH / NO_JWT",
    "step": "..."
}
@endjson
----


=== Візуалізація

Для візуалізації аудит логів використовується Redash.

[NOTE]
 Забеспечення пошуку по контексту подій та візуалізації поля контекст відбувається в окремих звітах в залежності від типу подій (структура контексту).
 Трансформація поля контекст відбувається за допомогою PostgreSQL.

== POC
https://gitbud.epam.com/mdtu-ddm/data-architecture/poc/audit[GitBud Repo]