= Персональні та чутливі дані

== Контекстна діаграма

image::datafactory/personal-data.drawio.svg[]

*Mediator/Facade* - для спрощення процесу генерації витягів, оркестрація цим процесом виділена в окремий сервіс
*Personal data requests DB* - база даних яка містить події факту запиту до персональних даних та даних які були позначені як чутливі. +
*Personal data service* - додаток що надає доступ для читання подій факту запиту персональних даних і повертає їх в форматі JSON +
*Report Service* - сервіс який зберігає шаблони витягів та генерує PDF витяги на підставі назви шаблону витягу та даних які відповідають шаблону.

== Вимоги до моделювання
=== Загальний опис
Для забезпечення прав власника персональних даних, при моделюванні реєстру всі персональні дані мають знаходитись в таблицях які позначені як об'єкти `ext:isObject="true"`.

[source, xml]
----
<changeSet id="table laboratory" author="registry owner">
    <createTable tableName="laboratory" ext:historyFlag="true" ext:isObject="true" remarks="Лабораторії що атестуються">
        <column name="laboratory_id" type="UUID" defaultValueComputed="uuid_generate_v4()">
            <constraints nullable="false" primaryKey="true" primaryKeyName="pk_laboratory_id"/>
        </column>
        <column name="name" type="TEXT">
            <constraints nullable="false"/>
        </column>
        <column name="address" type="TEXT">
            <constraints nullable="false"/>
        </column>
    </createTable>
</changeSet>
----

=== Розширення сутності для запиту персональних даних
Для спрощення моделювання передбачено окремий тег який дозволяє доєднувати інші таблиці через зовнішні ключі БД.
Звернення до таких точок інтеграції відбувається по ідентифікатору основної таблиці та передбачено повернення тільки однієї сутності.

=== Доступ до чутливих даних реєстру
Фіксація факту доступу через аудит події відбувається автоматично, для всіх таблиць де є поля, що позначені як приватні дані. У разі якщо необхідно додати фіксацію факту запиту до інших таблиць використовується розширення `accessAudit` де можуть бути перелічені такі таблиці.
Видалення такого аудиту можливе тільки для додаткових таблиць які були додані моделювальником.

.Приклад операцій додавання та видалення таблиць з аудиту.
[source, xml]
----
<databaseChangeLog>

    <changeSet id="add table to audit">
        <accessAudit>
          <addTables>
            <table name="address"/>
          </addTables>
        </accessAudit>
    </changeSet>

    <changeSet id="change audit tables">
        <accessAudit>
          <addTables>
            <table name="laboratory"/>
          </addTables>
          <removeTable>
            <table name="address"/>
          </removeTable>
        </accessAudit>
    </changeSet>

</databaseChangeLog>
----

=== Обмеження регламенту
До даних які були класифіковані як персональні запити можуть відбуватись тільки по унікальному ідентифікатору. Таким чином жодне поле персональних даних не може повертатись в рамках searchConditions, хоча може бути використано як поле для пошуку.

В структурах які містять персональні дані обов'язково має бути поле яке посилається на суб'єкт який є власником персональних даних

== Структура події

[plantuml]
----
@startuml

map PersonalDataAudit {
    subject_id => ідентифікатор власника персональних даних
    system => система з якої надійшов запит
    business_process => процес в рамках якого зроблено виклик
    request_name => назва запиту
    keycloak_id => ідентифікатор користувача службовця
    first_name => ім'я держ. службовця
    last_name => прізвище держ. службовця
    request_date => дата запиту
} 
@enduml
----