== POC можливості використання ETag хедерів для запобігання колізій під час паралельних змін декількома користувачами

Будо проведено link:https://jiraeu.epam.com/browse/MDTUDDM-22151[POC] з додавання підтримки
_optimistic locking_ для VersionCandidateFormController для усіх CRUD операцій контролера.

_Optimistic locks_ використовуються для запобігання одночасного змінювання ресурсу з
перезаписуванням обох користувачів. Якщо ресурс по даному URL змінюється, то має бути
згенерований новий ETag. Їх порівняння допомагає визначити, чи мають користувачі актуальні дані.

== Реалізація
Функціонал валідації ETag реалізований для VersionCandidateFormController за допомогою
AbstractETagHeaderInterceptor, який наслідується від HandlerInterceptor.

Перевірка ETag виконується у методі #preHandle(), де в якості ETag використовується хеш-код контенту
форми. Якщо метод після виконання повертає true, тоді зміна виконується, інакше ланцюг інтерцепторів
переривається.

Значення ETag передається до контролера у хедері реквесту "If-Match" та повертається користувачу
разом з респонсом у хедері "ETag". Цей хедер додається до респонсу в методі
[source,java]
--
AbstractETagHeaderInterceptor#postHandle()
--
Якщо користувач передає невалідний ETag, тоді повертається респонс зі статусом
412 Precondition Failed,
який також визначається в цьому методі.

Логіка, яка є спільною для усіх інтерцепторів, була винесена до окремого класу
AbstractETagHeaderInterceptor та інші інтерцептори мають розширювати.

== Реєстрація інтерцепторів
Створений FormETagHeaderInterceptor зареєстрований у класі WebConfig з pathPattern
[source,java]
--
/versions/candidates/**/forms/**
--
для того, щоб логіка, реалізована в FormETagHeaderInterceptor виконувалася лише під час запитів до
VersionCandidateFormController з будь-яким значенням versionCandidateId та formName.

== Основні положення відносно ETag
- Значення ETag перевіряється для PUT та DELETE методів.
- Значення ETag повертається з усіх методів окрім DELETE.
- У випадку, якщо ETag дорівнює null, тоді дія все одно виконується.
- Якщо ETag дорівнює "*", тоді вважається, що це може бути будь-яке значення та дія все одно виконується.
- Якщо користувач передає невалідний ETag, тоді вважається, що користувач має застарілі дані та дія
не буде виконана.

== Strong & Weak валідація ETag
Поточна реалізація валідації ETag використовує значення хеш-коду контенту
форми, що означає, що _Strong_ валідація більш застосовна в цьому випадку,
оскільки виконується порівняння кожного символу ETag. У випадку
необхідності реалізувати порівняння форм ігноруючи час останньої зміни,
тоді _Weak_ валідація буде більш застосовна таким чином, щоб форми
порівнювалися семантично, тобто за основним значенням форми, а не по
кожному символу. If-Match хедер підтримує лише _Strong_ валідацію, _Weak_ ETag будуть
ігноруватися.