== POC розгортання моделі бази данних реєстру для версії-кандидату
Було проведено link:https://jiraeu.epam.com/browse/MDTUDDM-21965[_POC_] для дослідження можливості розгортання моделі бази данних реєстру для версії-кандидату


=== Загальний опис
.Весь процес розгортання бази даних реєстру для версії кандидату складається з наступних етапів:
- Створення _template_ БД на основі новоствореної БД _registry_
- Створення БД для версії кандидату з _template_
- Запуск _liquibase_ скриптів на БД версії кандидату

=== Створення _template_ БД на основі новоствореної БД registry
Створення _template_ БД відбувається у відповідному _pipeline_.


=== Створення БД для версії кандидату з _template_
Реалізується за допомогою _java_ коду, в основі якого, покладено _SQL_ скрипт:
[source,sql]
----
CREATE DATABASE {databaseName} TEMPLATE {templateName};
----


=== Запуск liquibase скриптів на БД версії кандидату
Для забезпечення оновлення структури БД версії кандидату використовується _liquibase_.
Запуск _liquibase_ скриптів здійснюється за допомогою _java_ коду, попередньо визначивши _DataSource_ відповідної
бази даних та додаткові параметри.

_CurrentSchema_ параметр визначити як _public,registry_ в _dataSource url_.
[source,java]
----
"jdbc:postgresql://localhost:5432/" + dbName + "?currentSchema=public,registry"
----

Параметри _Database_
[source,java]
----
database.setDefaultSchemaName("registry");
database.setDatabaseChangeLogTableName("ddm_db_changelog");
database.setDatabaseChangeLogLockTableName("ddm_db_changelog_lock");
database.setLiquibaseSchemaName("public");
----



