@startsalt
{
{T
+ <&folder> registry-regulation
++ ...
++ <&folder> notifications
+++ <&folder> inbox
++++ <&folder> <b><template-directory></b>
+++++ <&file> template.ftl
+++++ <&file> notification.yml
}
}
@endsalt