= Управління профілем користувача

Профіль користувача системи містить набір атрибутів, які ідентифікують людину чи чиновника в процесі
автентифікації та спрощують користування в системі завдяки розширенню контексту виконання операцій.

== Структура профілю

Профіль користувача кабінету людини чи чиновника складається з наступних атрибутів:

* *ПІБ*
* *РНОКПП*
* *ЄДРПОУ*
* *Ознака представника юридичної особи* (тільки для людин)
* *Тип суб'єкта* (тільки для людин)
[NOTE]
 Профіль користувача кабінету чиновника створюється заздалегідь адміністратором доступу перед першим
входом в систему. Профіль користувачу кабінету людини автоматично заповнюється при першому вході
згідно з інформацією з КЕП. Деталі дивіться xref:architecture/platform/operational/user-management/citizen-authentication.adoc[за посиланням].

=== Атрибути профілю у Keycloak
Атрибути профілю користувача налаштовуються у Keycloak реалмі у секції *Attributes* відповідного
користувача і мають наступні значення:

* *fullName* для *ПІБ*
* *drfo* для *РНОКПП*
* *edrpou* для *ЄДРПОУ*
* *representative* для ознаки представника юридичної особи (для людин)
* *subjectType* для типу суб'єкта (для людин)
** individual - фізична особа
** entrepreneur - ФОП
** legal - юридична особа

Для показу імені поточного користувача в кабінеті використовуються вбудовані властивості в профілю
Keycloak для імені та прізвища. Ці атрибути повинні бути додані при ручному створенні користувача
чиновника. Для людини вони створюються автоматично на базі атрибуту ПІБ.

* *given_name* - Ім'я користувача
* *family_name* - Прізвище користувача

[NOTE]
 Наразі атрибути профілю зберігаються у Keycloak без шифрування, котре буде додано в наступних реалізаціях Платформи.

==== Keycloak Protocol Mappers
Для того щоб атрибути користувача були доступні при формуванні токену чи відповіді на метод */userinfo*
налаштовуються відповідні маппери у клієнтах *officer-portal* та *citizen-portal* на кожен атрибут профілю.
Таблиця з мапперами надана нижче:

|===
|Назва мапперу |Тип мапперу |Назва атрибуту |Назва поля |Додати до Access Token |Додати до Userinfo |Профіль чиновника |Профіль людини

|edrpou
|User Attribute
|edrpou
|edrpou
|так
|так
|так
|так

|drfo
|User Attribute
|drfo
|drfo
|так
|так
|так
|так

|fullName
|User Attribute
|fullName
|fullName
|так
|так
|так
|так

|representative
|User Attribute
|representative
|representative
|так
|так
|ні
|так

|subjectType
|User Attribute
|subjectType
|subjectType
|так
|так
|ні
|так

|family name
|User Property
|lastName
|family_name
|так
|так
|так
|так

|given name
|User Property
|firstName
|given_name
|так
|так
|так
|так

|===

Маппері налаштовуютсья автоматично при розгортанні системи з використанням https://github.com/epam/edp-keycloak-operator/tree/master#keycloak-operator[Keycloak Operator API], а
саме створення відповідного KeycloakClient CR.


==== Атрибути профілю в Access Token
Атрибути профілю користувача додаються до Access Token в процесі автентифікації та мають наступну
структуру:

[source, json]
.Поля атрибутів в Access Token
----
{
  "edrpou": "1110011000",
  "drfo": "220011000",
  "fullName": "Гупало Василь Миколайович",
  "representative": true,
  "subjectType": "individual"
}
----
[NOTE]
Структура токена у схемі спрощена та відображує лише атрибути профілю

=== API для отримання профілю користувача
Інформація про профіль користувача доступна за методом на Kong API Gateway. Всі операції вимагають
аутентифікацію. Отримання налаштувань можливе лише для поточного користувача.

*GET /userinfo*

Приклад відповіді:
[source, json]
----
{
    "sub": "e9972cc8-53c5-4d50-ab5e-cd7d617d9180",
    "email_verified": true,
    "edrpou": "1110011000",
    "roles": [
        "officer"
    ],
    "drfo": "220011000",
    "name": "Василь Гупало",
    "fullName": "Гупало Василь Миколайович",
    "preferred_username": "vasyl_gypalo",
    "given_name": "Василь",
    "family_name": "Гупало",
    "email": "vasyl_gypalo@gov.ua",
    "representative": true,
    "subjectType": "individual"
}
----

Цей метод використовується для відображення профілю користувача у кабінеті чиновника. Змінити
профіль має можливість лише адміністратор доступу.

[plantuml]
----
@startuml

actor "Людина/Чиновник" as person
participant "Кабінет людини/чиновника" as ui
participant "Kong API Gateway" as kong
participant "Keycloak" as keycloak

person -> ui: Запит сторінки з профілем
ui -> kong: Запит /userinfo\n(ідентифікатор сесії Kong)
kong -> keycloak: Запит /userinfo\n(Access Token)
keycloak --> kong: Профіль користувача
kong --> ui: Профіль користувача
ui --> person: Сторінка з профілем

@enduml
----