@startuml

autonumber
skinparam responseMessageBelowArrow true

actor "Regulations\n developer" as Client

participant "Monaco Editor" as Monaco
participant "Frontend Websocket" as FEWebsocket
participant "Language servers\n orchestrator" as ServiceOrchestrator
participant "Backend Websocket" as BEWebsocket
participant "Language server" as LanguageServer

activate Client

Client -> Monaco: open and edit document
activate Monaco
Monaco -> ServiceOrchestrator: WSS GET /groovy
activate ServiceOrchestrator

ServiceOrchestrator -> BEWebsocket ** : create
activate BEWebsocket
ServiceOrchestrator -> LanguageServer ** : create
activate LanguageServer

Monaco <-- ServiceOrchestrator: websocket
deactivate ServiceOrchestrator

Monaco -> FEWebsocket ** : create
activate FEWebsocket

Client -> Monaco: Focus on variable using mouse pointer

Monaco -> FEWebsocket: [LSP] textDocument/hoover

FEWebsocket -> BEWebsocket: [WSS] textDocument/hoover

BEWebsocket -> LanguageServer: textDocument/hover
LanguageServer -> LanguageServer: process hover action
LanguageServer --> BEWebsocket: [LSP] hover result
BEWebsocket --> FEWebsocket: [WSS] hover result
FEWebsocket --> Monaco: [LSP] hover result

Monaco --> Client: Hover popup

BEWebsocket -> LanguageServer: textDocument/hover
BEWebsocket <-- LanguageServer: Hoover information

Client -> Monaco: close document

Monaco -> FEWebsocket: close
deactivate Monaco
FEWebsocket --> BEWebsocket: close
deactivate FEWebsocket

BEWebsocket -> LanguageServer: close stream

deactivate LanguageServer

deactivate Client


@enduml