= Функція _get_trembita_auth_token()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

Функція *`get_trembita_auth_token(String registryName): String`* дозволяє отримати токен авторизації для доступу до сервісів СЕВ ДЕІР "Трембіта", з якими попередньо налаштовано взаємодію. Така взаємодія конфігурується в інтерфейсі адміністративної панелі Control Plane (_див. детальніше -- xref:registry-admin/external-integration/cp-integrate-trembita.adoc[]_).

== Параметри

.Параметри функції
|===
|*Аргумент*       | *Опис*
| `registryName`  | Назва системи або сервісу, до якого необхідно виконати запит.
|===

== Що повертає

Функція повертає токен авторизації у вигляді рядка (`String`).

== Алгоритм роботи

Функція працює за таким алгоритмом:

. Функція `get_trembita_auth_token()` приймає назву системи або сервісу як вхідний параметр.
. Виконується пошук конфігурації для вказаного сервісу у властивостях підключення Trembita.
. Якщо конфігурація знайдена, повертається токен авторизації.
. Якщо конфігурація не знайдена, виникає помилка конфігурації Trembita.

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

== Приклади використання

Цей розділ демонструє приклади використання JUEL-функції у Groovy-скриптах бізнес-процесу.

.Використання get_trembita_auth_token() у скрипті
[source,groovy]
----
def registryAuthSecretValue = get_trembita_auth_token('trembita-registry-test')
----
* `trembita-registry-test` -- назва системи у СЕВ ДЕІР "Трембіта".

[TIP]
====
Детальніше про роботу функції та її використання у бізнес-процесах ви можете переглянути у статті xref:registry-develop:bp-modeling/bp/element-templates/soap-integration/universal-connectors/trembita-soap-connector-delegate.adoc[].
====

== Пов'язані сторінки

* xref:registry-develop:bp-modeling/bp/element-templates/soap-integration/universal-connectors/trembita-soap-connector-delegate.adoc[]


