= Підсистема управління міжсервісною взаємодією

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Підсистема управління міжсервісною взаємодією допомагає розробникам та адміністраторам реєстрів підключати, захищати та
моніторити сервіси Платформи та реєстрів, надаючи багатий набір інструментів та сервісів для керування трафіком,
застосування політик, телеметрії та безпеки.

Крім того, підсистема надає функції управління зовнішнім/внутрішнім трафіком, такі як балансування навантаження, маршрутизація трафіку,
шифрування та контроль за вхідним та вихідним трафіком.

== Функції підсистеми

* Аутентифікація та авторизація запитів
* Реалізація політик міжсервісної взаємодії
* Шифрування трафіку при міжсервісній взаємодії
* Управління внутрішнім трафіком

Управління трафіком: Istio дозволяє контролювати, як трафік переходить між сервісами, зокрема, визначає маршрутизацію та балансування навантаження.

Забезпечення безпеки: Istio надає механізми для захисту сервісів від атак та зловмисних дій, зокрема, автентифікацію, авторизацію, шифрування та контроль доступу.

Політики: Istio дозволяє налаштувати різноманітні політики для керування поведінкою сервісів, зокрема, для контролю доступу, мережевого взаємодії та безпеки.

Телеметрія: Istio забезпечує збір та відображення різноманітних метрик та журналів, що дозволяє операторам моніторити та аналізувати роботу сервісів, зокрема, рівень доступності та продуктивності.

Розробка: Istio дозволяє зосередитись на написанні бізнес-логіки, забезпечуючи інфраструктурну підтримку для сервісів, зокрема, маршрутизацію, взаємодію між сервісами та забезпечення безпеки.

== Дизайн підсистеми

image::architecture/platform/operational/service-mesh/service-mesh-subsystem.svg[width=600,float="center",align="center"]

== Складові підсистеми

|===
|Назва компоненти|Namespace|Deployment|Походження|Призначення

|-
|`istio-system`
|`istiod`
|
|-

|_Istio оператор_
|`istio-operator`
|`istio-operator`
|
|-

|_Веб-інтерфейс управління та моніторингу Service Mesh_
|`istio-system`
|`kiali`
|3rd-party
|Компонент, що дозволяє конфігурувати, перевіряти та аналізувати service-mesh Платформи, а також візуалізувати трафік
всередині Платформи.

|_Kiali оператор_
|`istio-system`
|`kiali-operator`
|3rd-party
|Допоміжне програмне забезпечення, яке виконує функції розгортання, налаштування та відновлення Kiali, як
компонента підсистеми.
|===

== Атрибути якості
