= Підсистема управління міжсервісною взаємодією

== Загальний опис

_Підсистема управління міжсервісною взаємодією_ реалізовуючи мережевий паттерн _Service Mesh_ допомагає розробникам та
адміністраторам реєстрів безпечно підключати зовнішні системи до Платформи реєстрів та навпаки, захищає та моніторить
компоненти Платформи та реєстрів, надає набір компонентів для керування зовнішнім/внутрішнім трафіком, мережевими
політиками, телеметрією та безпекою, забезпечує балансування навантаження, маршрутизацію трафіку та шифрування.

[TIP]
--
Детальніше з переліком сервісів, що входять у _Service Mesh_ можна ознайомитись у розділі xref:arch:architecture/platform/operational/service-mesh/service-mesh-components.adoc[]
--

== Функції підсистеми

* Підсистема надає механізми для захисту сервісів від атак та зловмисних дій, зокрема, автентифікацію, авторизацію,
шифрування та контроль доступу.
* Підсистема дозволяє контролювати, як трафік переходить між сервісами, зокрема, визначає маршрутизацію та балансування навантаження.
* Підсистема забезпечує збір та відображення різноманітних метрик, що дозволяє адміністраторам Платформи переглядати
та аналізувати роботу компонентів реєстрів та Платформи, зокрема, рівень доступності та продуктивності.
* Створення та керування політиками безпеки та обмеження доступу до компонентів Платформи та реєстрів.

== Технічний дизайн підсистеми

image::architecture/platform/operational/service-mesh/service-mesh-subsystem.svg[width=600,float="center",align="center"]

== Компоненти підсистеми

|===
|Назва компоненти|Namespace|Deployment|Походження|Репозиторій|Призначення

|Istio control plane
|`istio-system`
|`istiod`
|3rd-party
.4+|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/infrastructure/service-mesh[gerrit:/mdtu-ddm/infrastructure/service-mesh]
a|Istiod - це головний компонент підсистеми, який забезпечує основні функції service mesh, такі як маршрутизація трафіку,
керування трафіком та забезпечення безпеки. Istiod складається з декількох компонентів, а саме:

* Pilot - керує маршрутизацією трафіку та забезпечує балансування навантаження між сервісами.
* Citadel - відповідає за безпеку трафіку, шифрування, автентифікацію та авторизацію. Citadel створює та розповсюджує сертифікати для кожного сервісу в мережі.
* Galley - використовується для обробки та перевірки конфігураційних даних Istio Envoy.
* Sidecar Injector - автоматично додає Envoy контейнери до потрібних подів компонент Платформи та реєстрів.

|_Istio оператор_
|`istio-operator`
|`istio-operator`
|3rd-party
|Istio оператор дозволяє встановлювати, налаштовувати та керувати різними компонентами `istiod`. Це спрощує налаштування
та розгортання `istio` як компонента Платформи

|_Prometheus_
|`istio-system`
|`prometheus`
|3rd-party
|Prometheus - це компонент моніторингу та аналізу метрик продуктивності, що використовується разом з Istio для збору,
аналізу та візуалізації метрик компонентів Платформи та реєстрів.

|_Веб-інтерфейс управління та моніторингу Service Mesh_
|`istio-system`
|`kiali`
|3rd-party
|Компонент, що забезпечує адміністраторів Платформи та реєстрів можливістю налаштовувати та аналізувати стан
компонентів service-mesh Платформи та реєстрів, здійснювати моніторинг компонентів що входять в service-mesh в реальному
часі та швидко виявляти проблеми в мережі.

|_Kiali оператор_
|`istio-system`
|`kiali-operator`
|3rd-party
|Допоміжне програмне забезпечення, яке виконує функції розгортання, налаштування та відновлення Kiali, як
компонента підсистеми Платформи.
|===

== Технологічний стек

* xref:arch:architecture/platform-technologies.adoc#istio[Istio]
* xref:arch:architecture/platform-technologies.adoc#kiali[Kiali]
* xref:arch:architecture/platform-technologies.adoc#prometheus[Prometheus]
* xref:arch:architecture/platform-technologies.adoc#istio-operator[Istio Operator]
* xref:arch:architecture/platform-technologies.adoc#kiali-operator[Kiali Operator]

== Атрибути якості підсистеми

=== _Observability_
Підсистема надає можливість спостерігати за Платформою та реєстрами та забезпечує збір метрик, що допомагає
адміністраторам розуміти поведінку та продуктивність компонентів Платформи та реєстрів для виявлення проблем та поліпшення їх продуктивності.

=== _Security_
Підсистема забезпечує захист компонентів Платформи та реєстрів від зовнішніх атак та внутрішніх загроз шляхом автентифікації,
авторизації, обмеження мережевої взаємодії, перевірки _JWT_-токенів, шифруванням трафіку між сервісами (_mTLS_) що повністю відповідає підходу Zero-trust.

Присутній механізм обмеження доступу до інтерфейсу який в свою чергу мінімізує поверхню атаки підсистеми ззовні. 

Підсистема відповідє вимогам криптостійкості використовуючі надійні шифри та TLS 1.2 або вище. Сертифікати згенеровані підсистемою зберігаються в безпечному, зашифрованому сховищі доступ до яких контролюється. 

Вся комунікація між компонентами підсистеми відбувається по захищеному каналу звязку з обовязковою ідентифікацією та автентифікацією.

=== _Reliability_
Підсистема забезпечує стійкість компонентів Платформи та реєстрів до відмов шляхом автоматичного перенаправлення
трафіку, виконання повторних спроб запитів,

=== _Performance_
Підсистема забезпечує балансування навантаження між компонентами Платформи та реєстрів та надає можливість використання
різних стратегій балансування, що дозволяє підвищити продуктивність додатків та керувати їх версіями.
