= Пагінація та сортування послуг у Кабінеті отримувача послуг

:sectanchors:

З метою розширення можливостей інтерфейсу Кабінету отримувача послуг, а також сприянню використовності, розроблено підтримку функціональності сортування та пагінаціїfootnote:[Пагінація -- це розбивка величезного масиву даних (зазвичай однотипного) на невеликі за обсягом сторінки, із відображенням нумерованої навігації.] послуг.

Функціональність надає можливість: ::

* розбивати на сторінки перелік бізнес-процесів у виконанні;
* розбивати на сторінки перелік завершених бізнес-процесів;
* сортувати бізнес-процеси у виконанні за датою і часом їх старту;
* сортувати завершені бізнес-процеси за датою і часом їх старту та датою завершення.

Механізм функціонування пагінації та сортування елементів вебсторінок Кабінетів користувача, як то пагінація та сортування задач, або послуг, ідентичний. Тому з погляду кінцевих користувачів, як то посадових осіб та отримувачів послуг реєстру, налаштування таких функцій інтерфейсу є однаковим.

TIP: Детальний опис функціональності представлений у розділі xref:user:officer/sorting-pagination/officer-portal-bp-sorting-pagination.adoc[].