= Integrating extensions
:sectanchors:
:sectlinks:

include::platform:ROOT:partial$admonitions/language-en.adoc[]

Additional extensions, or delegates, are implemented to transfer and receive data as part of the REST interaction between the different registries on the Platform and the business process modeled within their regulations.

The Platform supports the following delegates: ::

* *Start business process in another registry*: A delegate for initiating a business process modeled in the regulations of another registry on the Platform.
* *Search for entities in another registry data factory*: A delegate for obtaining data from entities (tables) in the database of another registry deployed on the Platform.

[CAUTION]
====
Using integration connectors is not enough to interact with a target registry on the Platform, as well as its business processes.

You also need to: ::

* Grant access to the target registry using the Control Plane admin console. For details, see xref:admin:registry-management/control-plane-registry-grant-access.adoc[].
* Grant access to the relevant views and registry's REST API at the data model level. For details, see xref:data-modeling/data/physical-model/rest-api-view-access-to-registry.adoc[].
====

== Section overview

* xref:registry-develop:bp-modeling/bp/element-templates/rest-integration-registries/start-bp-another-registry.adoc[Start business process in another registry]

* xref:registry-develop:bp-modeling/bp/element-templates/rest-integration-registries/search-for-entities-another-registry.adoc[Search for entities in another registry data factory]