= JUEL-функції у бізнес-процесах
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

CAUTION: Документ застарів і буде видалений у майбутніх релізах. Використовуйте новий формат у розділі xref:bp-modeling/bp/juel-functions/juel-functions-overview.adoc[].

== Загальний опис

У https://camunda.com/products/camunda-platform/modeler/[Camunda] ви можете використовувати скрипти в різних місцях xref:registry-develop:bp-modeling/bp/bp-modeling-instruction.adoc[бізнес-процесу]. Наприклад, при роботі зі https://docs.camunda.org/manual/7.4/reference/bpmn20/tasks/script-task/[Script Task]. Camunda Engine підтримує скриптування мовами JavaScript, Groovy або JUEL тощо.

У розрізі Платформи реєстрів реалізовано підтримку скриптування за допомогою Groovy та http://juel.sourceforge.net/[JUEL (Java Unified Expression Language)] -- уніфікованої скриптової мови виразів Java -- з використанням спеціальних розроблених JUEL-функцій.

Використовуйте платформні JUEL-функції для спрощення моделювання бізнес-процесів. Наразі імплементовано такі функції та їх автодоповнення у візуальному редакторі коду:

* xref:#fn-intiator[*`initiator()`*]
* xref:#fn-completer[*`completer()`*]
* xref:#submission-fn[*`submission()`*]
* xref:#fn-sign-submission[*`sign_submission()`*]
* xref:#fn-system-user[*`system_user()`*]
* *`get_variable()`*
* *`set_variable()`*
* *`set_transient_variable()`*
* *`process_caller()`*
* *`message_payload()`*
* xref:#load-digital-document[*`load-digital-document()`*]
* xref:#get-digital-document-metadata[*`get-digital-document-metadata()`*]
* xref:#save-digital-document[*`save-digital-document()`*]
* xref:#fn-save-digital-document-from-url[*`save_digital_document_from_url()`*]
* xref:#fn-get-trembita-auth-token[*`get_trembita_auth_token()`*].

[TIP]
====
Детальніше про використання редактор коду ви можете переглянути на сторінці xref:registry-admin/admin-portal/registry-modeling/process-models/components/edit-groovy-scripts.adoc[].
====

[#fn-intiator]
== Функція initiator()

Функція `initiator()` призначена для отримання та подальшого використання xref:registry-develop:bp-modeling/bp/bp-modeling-instruction.adoc#initial-event[ініціатора] (`initiator`) в процесі. +
Повертає клас `UserDto`.

TIP: `UserDto` -- клас, що є обгорткою даних користувача (тут -- ініціатора).
Завжди містить у собі `userName`, токен і `JwtClaimsDto` (дані для авторизації) до першої задачі користувача.

[initiator-methods]
=== Методи взаємодії

Функція надає наступні методи:

* `getUserName()` -- повертає ім'я користувача, що можна використовувати в полях `Assignee` та `Candidate Users` задач користувача.
* `getAccessToken()` -- повертає токен користувача, що можна використовувати в інтеграційних конекторах для інтеграції від імені користувача.
* `getDrfo()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `drfo` користувача.
* `getEdrpou()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `edrpou` користувача.
* `getFullName()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `fullName` користувача.

NOTE: Токен ініціатора, а разом з ним і всі атрибути Keycloak, будуть доступні тільки до першої користувацької задачі (**User Task**) у бізнес-процесі.

[#fn-completer]
== Функція completer()

Функція `completer(<task_id>)` дозволяє отримати виконавця користувацької задачі для подальшого використання у процесі. +
Повертає клас `UserDto`.

TIP: `UserDto` -- клас, що є обгорткою даних користувача (тут -- ініціатора).
Завжди містить у собі `userName`, токен і `JwtClaimsDto` (дані для авторизації).

[completer-methods]
=== Методи взаємодії

Функція надає наступні методи:

* `getUserName()` -- повертає ім'я користувача, що можна використовувати в полях `Assignee` та `Candidate Users` задач користувача.
* `getAccessToken()` -- повертає токен користувача, що можна використовувати в інтеграційних конекторах для інтеграції від імені користувача.
* `getDrfo()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `drfo` користувача.
* `getEdrpou()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `edrpou` користувача.
* `getFullName()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `fullName` користувача.

NOTE: Функція `completer(<task_id>)` доступна для використання після успішного завершення користувацької задачі.

[#submission-fn]
== Функція submission()

Функція `submission(<activity_id|event_id>)` дозволяє отримати дані форми користувацької задачі та повертає клас `UserFormDataDto`.

TIP: `UserFormDataDto` -- _клас, що є обгорткою даних форми користувача._

NOTE: Функція `submission(<activity_id|event_id>)` доступна для використання після успішного завершення користувацької задачі або стартової форми.

[#fn-sign-submission]
== Функція sign_submission()

Функція `sign_submission(<activity_id|event_id>)` використовується для отримання підпису та даних форми користувацьких задач. +
Повертає клас `SignUserFormDataDto`.

TIP: `SignUserFormDataDto` -- _клас, що є обгорткою для даних форми користувача, підпису та ключа CEPH-документа, де зберігається підпис._

NOTE: _Функція `sign_submission(<activity_id|event_id>)` доступна для використання після успішного завершення задачі, що потребує валідації підписом користувача, або стартової форми._

[#fn-system-user]
== Функція system_user()

Функція `system_user()` необхідна для отримання системного користувача з Keyclock. +
Повертає клас `UserDto`.

TIP: `UserDto` -- _клас, що є обгорткою даних користувача (тут -- ініціатора).
Завжди містить у собі `userName`, токен і `JwtClaimsDto`._

[system-user-methods]
=== Методи взаємодії

Функція надає наступні методи:

* `getUserName()` -- повертає ім'я користувача, що можна використовувати в полях `Assignee` та `Candidate Users` задач користувача.
* `getAccessToken()` -- повертає токен користувача, що можна використовувати в інтеграційних конекторах для інтеграції від імені користувача.
* `getDrfo()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `drfo` користувача.
* `getEdrpou()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `edrpou` користувача.
* `getFullName()` -- делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `fullName` користувача.

[#fn-get-trembita-auth-token]
== Функція get_trembita_auth_token()

Функція *`get_trembita_auth_token()`* дозволяє отримати токен авторизації для доступу до сервісів СЕВ ДЕІР "Трембіта", з якими попередньо налаштовано взаємодію. Така взаємодія конфігурується в інтерфейсі адміністративної панелі Control Plane (_див. детальніше -- xref:registry-admin/external-integration/cp-integrate-trembita.adoc[]_).

Функція застосовується у скрипт-задачах (*Script Task*) бізнес-процесів і приймає один параметр (*`String`*) -- назву системи/сервісу, до якої необхідно виконати запит. Наприклад:

.Використання get_trembita_auth_token() у скрипті
====
[source,groovy]
----
def registryAuthSecretValue = get_trembita_auth_token('trembita-registry-test')
----

* `trembita-registry-test` -- назва системи у СЕВ ДЕІР "Трембіта".
====

[TIP]
====
Детальніше про роботу функції та її використання у бізнес-процесах ви можете переглянути у статті xref:registry-develop:bp-modeling/external-integration/api-call/connectors-external-registry.adoc#trembita-connector[Загальний Trembita SOAP-конектор].
====

== Робота з цифровими документами

[#load-digital-document]
=== Функція load_digital_document()

JUEL-функція *`load_digital_document(String documentId): byte[]`* призначена для завантаження цифрових документів. Ця функція використовує ідентифікатор документа (`documentId`), який передається як вхідний параметр для отримання відповідного документа через внутрішній API сервісу цифрових документів.

.Службовий API сервісу цифрових документів
[source,http]
----
GET /internal-api/documents/{processInstanceId}/{id} (binary response)
----

Функція повертає документ у форматі байтів -- `byte[]`, що дозволяє працювати з даними документа на низькому рівні. Ця функція може бути корисна для розробників, яким потрібно працювати з цифровими документами, використовуючи скриптування Groovy.

TIP: Застосування функції `load_digital_document()` детально представлено у референтному прикладі на сторінці xref:best-practices/bp-upload-edit-file.adoc[].

[#get-digital-document-metadata]
=== Функція get_digital_document_metadata()

JUEL-функція *`get_digital_document_metadata(String documentId): DocumentMetadata`* використовується для отримання метаданих документа, які зберігаються в сервісі цифрових документів.

.Службовий API сервісу цифрових документів
[source,http]
----
GET /internal-api/documents/{processInstanceId}/{id}/metadata (DocumentMetadata)

class DocumentMetadata {
  String id
  String name
  String type
  String checksum
  Long size
}
----

Ця функція приймає на вхід ідентифікатор документа (`documentId`) і повертає об'єкт типу `DocumentMetadata`, що містить наступну інформацію:

* `id`: ідентифікатор документа.
* `name`: ім'я документа.
* `type`: тип документа.
* `checksum`: контрольна сума документа. Використовується для перевірки цілісності документа після його передачі або збереження.
* `size`: розмір документа.

Ця функція може бути корисною, коли вам потрібно отримати метадані документа в рамках вашого бізнес-процесу. Вона дозволяє вам працювати з документами в сервісі цифрових документів, не здійснюючи прямі запити до API цього сервісу. Замість цього, ви можете використовувати цю JUEL-функцію безпосередньо в Groovy-редакторі.

TIP: Застосування функції `get_digital_document_metadata()` детально представлено у референтному прикладі на сторінці xref:best-practices/bp-upload-edit-file.adoc[].

[#save-digital-document]
=== Функція save_digital_document()

JUEL-функція *`save_digital_document(byte[] content, String targetFileName): DocumentMetadata`* використовується для збереження документа в сервісі цифрових документів.

Ця функція приймає два аргументи:

* `content`: це байтовий масив, що представляє вміст документа, який потрібно зберегти.
* `targetFileName`: це ім'я файлу, під яким буде збережено документ.

.Службовий API сервісу цифрових документів
[source,http]
----
POST /internal-api/documents/{processInstanceId} (multipart file + filename) : DocumentMetadata

class DocumentMetadata {
  String id
  String name
  String type
  String checksum
  Long size
}
----

Після виконання, ця функція повертає об'єкт типу `DocumentMetadata`, що містить метадані новозбереженого документа. Ці метадані включають:

* `id`: ідентифікатор нового документа.
* `name`: ім'я нового документа (це буде те саме ім'я, що було передано як `targetFileName`).
* `type`: тип нового документа.
* `checksum`: контрольна сума нового документа, що використовується для перевірки його цілісності.
* `size`: розмір нового документа в байтах.

Ця функція дуже корисна, коли вам потрібно зберегти документ в рамках ваших бізнес-процесів. Замість того, щоб робити прямі запити до API сервісу цифрових документів, ви можете використовувати цю JUEL-функцію прямо в Groovy-редакторі.

TIP: Застосування функції `save_digital_document()` детально представлено у референтному прикладі на сторінці xref:best-practices/bp-upload-edit-file.adoc[].

[#fn-save-digital-document-from-url]
=== Функція save_digital_document_from_url()

Функція `*save_digital_document_from_url()*` дозволяє отримувати цифрові файли/документи за віддаленою адресою від публічних API, тобто таких, що не потребують автентифікації. ЇЇ можна використовувати для спрощення моделювання бізнес-процесів у скриптах.

Функція може приймати 2 вхідні параметри: ::

* URL цифрового документа
* Назва файлу
+
NOTE: Можливо отримати лише один документ за один запит до зовнішнього джерела.
+
Обидва параметри є рядком (`String`), тому моделювальник може передати функції фактично будь-який аргумент:
+
.Шаблон функції
====
----
save_digital_document_from_url(String remoteFileUrl, String targetFileName)
----
====

[TIP]
====
Детальніше про роботу функції та її використання у бізнес-процесах ви можете переглянути на сторінці xref:bp-modeling/bp/save-digital-doc-remote-url.adoc[].
====