= User task templates
include::platform:ROOT:partial$admonitions/language-en.adoc[]

== Section overview

* xref:bp-modeling/bp/element-templates/user-task-templates/citizen-sign-task.adoc[]
* xref:bp-modeling/bp/element-templates/user-task-templates/officer-sign-task.adoc[]
* xref:bp-modeling/bp/element-templates/user-task-templates/user-form.adoc[]



////
[#business-process-modeler-extensions-configuration]
== Налаштування типових розширень до бізнес-процесів

Цей розділ описує налаштування типових розширень для бізнес-процесів -- **Element Templates**.

Типи задач для застосування розширень ::

Типові розширення **Element Templates** можуть бути застосовані до різних типів задач, наприклад:

* xref:#element-temp-user-task[]
* xref:#element-temp-service-task[]
* xref:#element-temp-call-activity[]
* xref:#element-temp-send-task[]
* xref:#extensions-integrate-bp-another-registries[]

[CAUTION]
====
Налаштування типових розширень-конекторів відбувається у застосунку *Camunda Modeler*.

Перед початком роботи переконайтеся, що виконано всі передумови, описані у розділі xref:business-process-modeler-extensions-installation[Встановлення каталогу типових розширень до бізнес-процесів].
====
////

