@startsalt
{
{T
+ <&folder> registry-regulation
++ ...
++ <&folder> notifications
+++ <&folder> diia
++++ <&folder> <b><template-directory></b>
+++++ <&file> template.diia
+++++ <&file> notification.yml
}
}
@endsalt