= Примітки до релізу 1.9.7. Частина 4
:toc:
:toc-title: ЗМІСТ
:sectnums:
:sectlinks:
:sectanchors:
:note-caption: Покращено
:tip-caption: Розроблено
:caution-caption: Інше
:important-caption: Виправлено
:warning-caption: Покращення безпеки

== Конфігурація перевірки в ЄДР при логіні юридичних осіб до Кабінету отримувача послуг
//MDTUDDM-22846
//TODO: first.xlsx

[TIP]
====
* [*] Можливість налаштовування перевірки в ЄДР для користувачів, що обрали вхід "Для бізнесу" на сторінці автентифікації для технічного адміністратора реєстру.

* [*] Забезпечено можливість автентифікації для отримувачів послуг-ФОП, представників ФОП або ЮО, обираючи режим "Для бізнесу" та використовуючи КЕП без відповіді ЄДР.
====

== Впровадження універсального SOAP-конектора для взаємодії з "Трембіта"
//MDTUDDM-20426
//TODO: first.xlsx

[TIP]
====
* [*] Додано автодоповнення для JUEL-функції `get_trembita_auth_token()` у візуальному редакторі коду для версії-кандидат.

* [*] Розробникам регламенту надана можливість виклику із БП довільного реєстру-учасника ШБО "Трембіта", використовуючи універсальний SOAP-конектор.

* [*] Адміністраторам реєстру надана можливість налаштувати інтеграцію із довільною зовнішньою системою-учасником ШБО Трембіта через SOAP протокол в інтерфейсі Control Plane.
====

== Інструкція з розгортання Платформи у публічному хмарному середовищі AWS
//MDTUDDM-22057
//TODO: first.xlsx

[TIP]
====
* [*] Впроваджено детальне покрокове керівництво для адміністратора Платформи щодо розгортання системи на цільовому публічному хмарному оточенні AWS.
====

////

== Оптимізація збирання логів для спрощення їх аналізу у виробничому середовищі

[NOTE]
====
* [*] Налаштовано логування Kong у форматі JSON.

* [*] Додано контекстну інформацію до логів form-schema-provider.

* [*] Додано логування responseCode до registry-rest-api.

* [*] Покращено логування для Keycloak.

* [*] Зменшено рівень логування для kafka-кластера у виробничому режимі.

* [*] Зменшено рівень логування в Jenkins.

* [*] Змінено рівень логування Ceph (rgw, mon).

* [*] Вирівняно структуру логів для сервісів реєстру.

* [*] Прибрано логи Crawling result set у registry-regulation-mng.

* [*] Додано логування до сервісу DSO для деталізації помилок ініціалізації контексту.

* [*] Перевірено та вимкнено логування cookie header в усіх BE-сервісах.
====

== Категоризація доступних послуг у Кабінетах користувачів

[TIP]
====
* [*] Можливість використання конфігурації репозиторію регламенту для налаштування групування послуг в Кабінеті посадової особи.

* [*] Створення нових груп доступних послуг для відображення в кабінетах користувачів через інтерфейс Адмін порталу.

* [*] Додавання не згрупованих бізнес-процесів до наявних та нових груп для відображення у Кабінетах користувачів через інтерфейс адміністративного порталу.

* [*] Сортування груп, бізнес-процесів в групах та поза групами для відображення в кабінетах користувачів через інтерфейс адміністративного порталу у версії-кандидат.

* [*] Зміна назви та видалення груп доступних послуг через інтерфейс Адмін порталу.

* [*] Збереження змін на вкладці "Відображення в кабінетах" у поточній версії-кандидат через інтерфейс Адмін порталу.

* [*] Виключення бізнес-процесів з груп через інтерфейс Адмін порталу.

* [*] Перегляд доступних груп, послуг в них та поза групами у версії-кандидат та Мастер версії через інтерфейс адмін-порталу.

* [*] Відображення груп доступних послуг за категоріями для користувачів Кабінету посадової особи/отримувача послуг.

* [*] Відображення збережених змін на вкладці "Відображення в кабінетах" в розділі "Огляд версії" інтерфейсу адмін-порталу.

* [*] Видалення process definition із груп при виклику ендпоінта видалення бізнес-процесу.

* [*] Міграція груп для наявних реєстрів.
====

[NOTE]
====
* [*] Оптимізовано рендеринг сторінки "Відображення в кабінетах".
====

== Підтвердження при залишенні форми задачі або стартової форми із незбереженими даними

[TIP]
====
* [*] У цьому оновленні ми зосередилися на підвищенні користувацького досвіду та запобіганні втраті внесених даних. Тепер наша система оснащена новою можливістю: коли користувач працює з формою задачі або стартовою формою, він буде отримувати попередження перед тим, як залишити сторінку.
+
Ця зміна має велике значення для підвищення ефективності взаємодії з системою. Вона дозволяє користувачам отримати повідомлення про можливість зберегти важливі дані, які вони ввели, перед тим, як залишити сторінку. Таким чином, користувачі можуть уникнути ненавмисного втрачання цінної інформації та забезпечити більш безперервний робочий процес.
====

== Можливість задавати DNS-ім'я для аутентифікації користувачів для конкретного реєстру

[TIP]
====
Розширене управління DNS-іменами в Keycloak для адміністраторів ::

* [*] В останньому оновленні ми значно покращили можливості управління DNS-іменами в компоненті Keycloak, що дозволяє більш гнучке налаштування аутентифікації користувачів для різних реєстрів.

Для адміністраторів Платформи ::

* [*] Ви тепер можете додавати та редагувати додаткові DNS-імена для компонента Keycloak через адміністративну консоль Control Plane. Це дозволяє вам налаштовувати імена за замовчуванням, що підвищує безпеку та ефективність управління ідентифікацією користувачів.
* [*] Можливість редагування внесених додаткових DNS через адмін-консоль на рівні Платформи.
* [*] Оптимізовано інтерфейс налаштувань Платформи, розділивши їх на окремі вкладки для зручності та кращої організації.

Для адміністраторів реєстрів ::

* [*] Тепер ви можете використовувати DNS-імена компонента Keycloak, налаштовані адміністратором Платформи. Це спрощує процес аутентифікації користувачів та забезпечує більшу консистентність в налаштуваннях безпеки між різними реєстрами.
====

== Видалення попередньої версії автогенерованого коду при розгортанні регламенту

[TIP]
====

* [*] Впроваджено автоматичну заміну коду новою версією у Gerrit реєстру в репозиторії для технічного адміністратора реєстру.

* [*] Забезпечено автоматичне оновлення версій Docker images в Nexus реєстру останньою версією для технічного адміністратора реєстру.

* [*] У Kafka реєстру тепер відображаються тільки топіки для сервісів API, що використовуються в останній версії реєстру, для технічного адміністратора реєстру.

* [*] Відмова від необхідності змінювати версію регламенту в структурі регламенту після кожної зміни для розробників та моделювальників регламенту.
====

== Швидкі посилання до сервісів у Control Plane

[TIP]
====
* [*] Додано посилання на Openshift, pgAdmin, Kibana, Swagger, Redash та інші адміністративні ендпоінти в інтерфейсі Control Plane для зручності адміністратора реєстру.
====

== Можливість пагінації пошукових запитів

[TIP]
====
* [*] Можливість налаштування отримання інформації про загальну кількість знайдених елементів при створенні критеріїв пошуку (SC) для коректного налаштування пагінації користувачів.
====

== Внесення змін до файлу описів структур таблиць моделі даних реєстру через вебредактор коду

[TIP]
====
* [*] Підтвердження змін у файлі описів структур таблиць моделі даних реєстру через вебредактор коду у версії-Кандидаті.

* [*] Перегляд файлу описів структур таблиць моделі даних реєстру через вебредактор коду для версії-кандидата та Майстер-версії.

* [*] Відображення статусу оновлення структур таблиць моделі даних, здійснених через вебредактор коду.

* [*] Редагування файлу опису структур таблиць моделі даних реєстру для Версії Кандидата, використовуючи автопідказки, автодоповнення та аналіз коду згідно з liquibase та DDM xsd.

* [*] Відображення сторінок помилок при перегляді переліку таблиць при відсутності файлу опису моделі даних та неуспішному запиті файлу у майстер-версії.
====

== Моніторинг показників виконання бізнес-процесів

[TIP]
====
* [*] Додано можливість для технічного адміністратора реєстру моніторити показники виконання бізнес-процесів через дашборд.
====

== Додавання або видалення API по роботі з масивами даних для наявних таблиць

[TIP]
====
* [*] Додано можливість зміни налаштувань на рівні створення таблиць для розробників регламенту, що впливає на поведінку згенерованого коду API.
====

== Відображення масивів даних у вигляді таблиць на формах БП з можливістю виклику інших БП для певного рядка

[TIP]
====
* [*] Додано можливість налаштовувати компонент EditGrid для роботи в режимі "тільки для перегляду" для розробників регламенту.

* [*] Користувачі Кабінету посадової особи та отримувачі послуг можуть переглядати даних UI-форми в режимі "read only" та виконувати дії стосовно обраного запису таблиці.

* [*] Розробникам регламенту додано можливість налаштовувати набір дій, які можна виконати стосовно окремих записів таблиці.

* [*] Моделювальникам реєстру надано можливість відображати масиви даних у вигляді таблиць на формах БП з можливістю виклику інших БП для певного рядка.

* [*] Розроблено референтний БП для функціональності вибору одного рядка в таблиці та запуску для нього БП.
====

== Можливість обирати декілька рядків у таблиці та запускати для них БП

[TIP]
====
Моделювальникам реєстру додано можливість обирати декілька рядків в таблиці та запускати для них бізнес-процеси.

* [*] Розробникам регламенту надано можливість налаштовувати активацію обрання декількох записів з таблиці для виконання стосовно них дій.

* [*] Користувачі Кабінету посадової особи та отримувачам послуг можуть ініціювати виконання бізнес-процесів з даними декількох обраних рядків з таблиці.

* [*] Розробникам регламенту додано можливість налаштовувати ширину полів компонентів для відображення в таблиці EditGrid.

* [*] Розроблено референтний бізнес-процес для функціональності вибору одного або декількох рядків в таблиці та запуску для них бізнес-процесів.
====

[NOTE]
====
* [*] Оптимізовано рендеринг таблиці для забезпечення кращої продуктивності.
====

== Автореєстрація для посадових осіб з ручним або автоматичним модеруванням

[TIP]
====
* [*] Додано можливість для моделювальників реєстру дати можливість посадовим особам проходити самореєстрацію з ручним або автоматичним модеруванням.

* [*] Адміністраторам реєстру надано можливість налаштовувати самореєстрацію посадових осіб.

* [*] Розроблено референтні приклади бізнес-процесів автореєстрації посадової особи з автоматичною та ручною модерацією для моделювальників реєстру.

* [*] Посадові особи можуть після автентифікації в кабінеті автоматично почати процес самореєстрації, якщо він змодельований в реєстрі та налаштована автореєстрація.

* [*] Розробникам регламенту надано окреме типове розширення *Save user roles* для внесення змін до переліку регламентних ролей користувача.
====

== Запуск бізнес-процесу за таймером

[TIP]
====
* [*] Додано референтний приклад бізнес-процесу для розробників та моделювальників регламенту, що демонструє запуск бізнес-процесу за встановленим розкладом у події "Таймер".
====

== Зміна логіки роботи Cleanup-процесу видалення регламенту

[TIP]
====
* [*] Змінено логіку роботи Cleanup-процесу видалення регламенту.
* [*] Додано можливість виконати cleanup зі збереженням поточного регламенту, регулюючи процес вхідним параметром *`DELETE_REGISTRY_REGULATIONS_GERRIT_REPOSITORY`*.
====

////

