= Test 1
include::platform:ROOT:partial$templates/document-attributes/default-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== Objectives


This test aims to give you in-depth practical knowledge of creating business processes on the Platform.

== Tasks

. Create a data model based on the following table.

+
.Fields and descriptions
|====

|No. |Field name on the form and in the logical data model |Field name in the physical data model |Format |Reference used |Required field

6+^|*edu_organization* entity
|1|EDEBO ID|edu_organization_id_external|Number||+
|2|EDRPOU code|edrpou|dn_edrpou||+
|3|Full name|full_name|Text||+
|4|Short name|short_name|Text||+

|5|Institution status (Institution status ID)|edu_status_id|UUID|Institution status (edu_status)|+

|6|Ownership type (Ownership type ID)|ownership_id|UUID|Ownership type (ownership)|+
|7|Town|settlement|Text||+
|8|Address|address|Text||+
|9|Phone|phone_number|Text||+
|10|Email|email|Text||+
|11|Website|website|Text||-
|12|Institution head|head_name|Text||+
|13|Accreditation status|accreditation_flag|Boolean||+
|14|Accreditation date|date_of_accreditation|Date||-
|====
+

. Create a search condition endpoint to fill the *Institution status* field with `READ ALL` access support.
+
.Input parameters:
[source, sql]
----
SELECT edu_status_id, name, constant_code FROM edu_status ORDER BY name ASC;
Parameters: none
Constants:  none
----
+
.Output parameters:
[source, sql]
----
UUID, working, WORKING
UUID, suspended, SUSPENDED
UUID, reorganized, REORGANIZED
UUID, liquidated, LIQUIDATED
----
+

. Create a search condition endpoint to fill out the *Ownership type* field with `LIKE` and `READ ALL` support.
+
.Input parameters:
[source, sql]
----
SELECT ownership_id, name FROM ownership ORDER BY name ASC;
Parameters: none
Constants:  none
----
+
.Output parameters:
[source, sql]
----
UUID, State
UUID, Private
UUID, Municipal
UUID, Corporate
----
+
SEARCH BY LIKE::
+
.Input parameters:
[source, sql]
----
Input: SELECT ownership_id, name FROM ownership  WHERE name LIKE '%держ%' ORDER BY name ASC ;
Parameters: name
Constants: none
----
+
.Output parameters:
[source, sql]
----
l.UUID, State
----
+

. Create a form for adding information about schools and a form for signing data. Use the previously created search conditions in the Select components.
+

. Develop a business process for adding schools using the following businessKey: `EDEBO ID`, `Short name`, `EDRPOU code`.

== Expected result

After completing this test, you should have the following:

* A business process for adding schools to a test registry.
* Your business process must be available as a service in the user portal.