= Розгортання

== Діаграма розгортання

image:arch:architecture/registry/operational/portals/services/citizen-portal/citizen-portal-deploy.svg[]

=== Розгортання додатку

- Громадяни використовують браузер для доступу до веб-додатку
- *React* з *Redux* є основними бібліотеками для розробки веб додатку
- Після збірки додаток представляє собою набір файлів серед яких тільки один *html* файл, та деяка кількість *js*, *css* та інших необхідних статичних файлів
- Веб додаток громадянина відображає контент використовуючи *Nginx* як вебсервер для статичного контенту. Єдиний *html* файл віддається на усіх веб-шляхах додатка.
- Конфігурація веб додатку відбувається через конфіг мапи *citizen-portal-environment-js* та *citizen-portal-nginx-config*

=== Зовнішні сервіси

- Користувацькі форми веб додатку отримують данні реєстру з *API Дата фабрики*
- Авторизація користувачів веб додатку та отримання інформації про користувача відбувається за рахунок сервісу *Управління користувачами та ролями*
- JSON метадані форм веб додаток отримує з *Сервісу постачання мета-даних форм*
- *Сервіс управління задачами* надає веб додатку інформацію про задачі користувача
- *Сервіс управління процесами користувача* надає веб додатку данні щодо доступних та ініційованих громадянином послуг
- Веб додаток для взаємодії з усіма сервісами використовує сервіс *Управління API системи* 
