= Додавання генерації POST-методів для пошуку даних

== Загальний опис

При поточній реалізації з виконанням GET-запитів для пошуку даних, виникли проблеми з пошуком по типу _IN_/_NOT_IN_)

Для сценаріїв інтеграції через UI-форми, xref:arch:architecture/registry/operational/registry-management/platform-evolution/public-api/public-api.adoc[Публічний API] або xref:arch:architecture/registry/operational/external-integrations/cross-registry.adoc#_інтеграція_з_сторонніми_системами[Інтеграція з зовнішніми системами], можливим є використання воркераундів з використанням існуючого GET-методу.

Проте для сценаріїв з виставлення ендпоінтів пошуку даних через Трембіту та використання їх через бізнес-процеси, наявні воркераунди не допомагають, що в майбутньому може призвести до блокуючих проблем у команд розробки.

Як вирішення таких проблем було вирішено додатково до генерації GET-інтерфейсу для пошуку даних також генерувати і POST-інтерфейс

== Загальні принципи та положення

* GET і POST ендпоінти мають генеруватись разом
* Для внутрішніх інтеграцій всередині системи перейти на використання POST
* Використання GET методів залишається для зворотньої сумісності при використанні клієнтами сценаріїв _Пошук з UI-форм_, _Публічний API_ та _Інтеграція з зовнішніми системами_
* Використання POST-методів для сценаріїв _Публічний API_ та _Інтеграція з зовнішніми системами_ стане можливим

== Високорівневий план розmробки

=== Технічні експертизи

* BE

=== План розробки

* Розширити _service-generation-utility_, додавши генерації POST ендпоінтів пошуку даних
* Розширити _service-generation-utility_, змінити генерацію коду soap-api на відправку запитів до rest-api, перейти на POST
* Розширити _service-generation-utility_, змінити AuthPolicy для зовнішніх інтеграцій з rest-api, дозволити обробку POST
* Розширити _rest-api-core-base-image_, наразі для POST-запитів налаштовані фільтри, що очікують певний набір HTTP-заголовків (_X-Digital-Signature_, _X-Source-Business-Process_ etc.)
* Розширити BPMS делегати пошуку (_DataFactoryConnectorSearchDelegate_, _RegistryDataFactoryConnectorSearchDelegate_) можливістю передати _Map<String, Object>_ у якості пошукового параметра (зараз - _Map<String, String>_)
* Оновити Feign-клієнти, які використовуються делегатами, на POST метод
* Оновити platform-gateway, додавши обробку POST-запитів пошуку замість GET
* Задокументувати особливості використання GET-методів при пошуку з IN/NOT_IN
* Задокументувати рекомендації щодо формування тіла POST запиту (особливо при пошуку IN/NOT_IN)