= Додавання генерації POST-методів для пошуку даних

include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

При поточній реалізації з виконанням GET-запитів для пошуку даних, виникли проблеми з пошуком по типу _IN_/_NOT_IN_.

Вони пов'язані з неможливістю коректно обробити випадок, коли приходить запит типу _GET /search?inParam=value1,value2_ , де параметр inParam є єдиним значенням _value1,value2_, а не масивом значень _["value1", "value2"]_. Подібні структури в запиті Spring Web фреймворк парсить саме як масив _[value1, value2]_.

В якості воркераунду можливим виявилось формувати запит у форматі _GET /search?inParam=value1,value2&inParam=_. В такому випадку Spring формує параметри у масив _["value1,value2", ""]_, що є коректним для пошуку за типом IN/NOT_IN.

Проте використання подібного воркераунду є можливим тільки для випадків, де клієнт може явно сконфігурувати запит HTTP-запит з необхідними пошуковими параметрами у правильному форматі.

Такими сценаріями є:

* Інтеграція через UI-форми
* xref:arch:architecture/registry/operational/registry-management/platform-evolution/public-api/public-api.adoc[Публічний API]
* xref:arch:architecture/registry/operational/external-integrations/cross-registry.adoc#_інтеграція_з_сторонніми_системами[Інтеграція з зовнішніми системами]

Проте для сценаріїв, де запити пошуку даних формуються програмно всередині мікросервісів системи, таких як:

* виставлення ендпоінтів пошуку даних через Трембіту (через _soap-api_)
* використання ендпоінтів пошуку даних через делегати у бізнес-процесах (через _bpms_)

наявний воркераунд використати неможливо або це створить суттєві проблеми для розробки та підтримки такого рішення, що в майбутньому може призвести до блокуючих проблем у команд розробки.

Як вирішення таких проблем було вирішено додатково до генерації GET-інтерфейсу для пошуку даних також генерувати і POST-інтерфейс, при використанні якого необхідні пошукові параметри будуть формуватись у тілі запиту формату _JSON_, який дозволяє коректно відрізняти окремі одиночні значення від масивів.

== Загальні принципи та положення

* GET і POST ендпоінти мають генеруватись разом
* Для внутрішніх інтеграцій всередині системи перейти на використання POST
* Використання GET методів залишається для зворотньої сумісності при використанні клієнтами сценаріїв _Пошук з UI-форм_, _Публічний API_ та _Інтеграція з зовнішніми системами_
* Використання POST-методів для сценаріїв _Публічний API_ та _Інтеграція з зовнішніми системами_ стане можливим
* Використання POST-запитів для пошуку даних не впливає на сценарії модифікації даних, де також використовується метод POST (залишаються актуальними усі Network Policy, а також перевірка HTTP-заголовків при збереженні даних)
* Перехід UI-форм на використання POST методу наразі не потребується та є поза скоупом

== Високорівневий план розробки

=== Приклад

Для критерію пошуку

[source, xml]

<changeSet author="registry owner" id="create SC registration_equal_laboratory_id_solution">
    <ext:createSearchCondition name="some_sc">
        <ext:table name="some_table" alias="r">
            <ext:column name="some_id" />
            <ext:column name="some_equal_column" searchType="equal"/>
            <ext:column name="some_in_column" searchType="in"/>
        </ext:table>
    </ext:createSearchCondition>
</changeSet>

---

разом з існуючим GET-ендпоінтом повинен згенеруватись POST

.Новий API
[%collapsible]
====
swagger::{attachmentsdir}/architecture/registry/operational/registry-management/sc-post-migration/swagger.yml[]
====

=== Технічні експертизи

* BE

=== План розробки

[cols="3,5,5"]
|===
| Компонент | Необхідне розширення | Мета
| service-generation-utility | додати генерацію POST ендпоінтів пошуку даних | виклик нових ендпоінтів з _soap-api_ та _bpms_
| service-generation-utility | змінити генерацію коду soap-api на відправку запитів до rest-api, перейти на POST | уникнути проблем з виставленням SC з пошуком через IN/NOT_IN через Трембіту
| service-generation-utility | змінити AuthPolicy для зовнішніх інтеграцій з rest-api-ext, дозволити обробку POST для ендпоінтів пошуку даних (не має впливати на ендпоінти модифікації даних) | можливість викликати POST ендпоінт для сценарію _Пошук даних без Трембіта_
| rest-api-core-base-image | для пошукових POST запитів прибрати валідацію специфічних заголовків (_X-Digital-Signature_, _X-Source-Business-Process_ etc.) | у поточній реалізації валідація заголовків налаштована за HTTP-методом, а не за викликаним ендпоінтом, внаслідок чого всі POST-запити валідуються. З новим підходом цю логіку необхідно змінити
| bpms | змінити делегати пошуку (_DataFactoryConnectorSearchDelegate_, _RegistryDataFactoryConnectorSearchDelegate_), додавши можливість приймати як параметр пошуку _Map<String, Object>_ (зараз - _Map<String, String>_) | для коректного пошуку за типом IN у POST запиті необхідно буде передати список допустимих значень, вони відправляться з bpms як string ключ - list значення. Не має виникнути проблем зі зворотньою сумісністю, оскільки Map<String, Object> є ширшим, ніж поточне Map<String, String>
| ddm-data-factory-client | оновити Feign-клієнти, які використовуються делегатами, на POST метод | використання в bpms клієнту
| platform-gateway | додати обробку POST-запитів пошуку замість GET | оскільки сценарій пошуку без Трембіти перемикається на POST метод, у проксі-сервісі platform-gateway теж необхідно перемкнутись на обробку запитів саме цього методу
|===

Також важливим є документування функціональності:

* Задокументувати особливості використання GET-методів при пошуку з IN/NOT_IN
* Задокументувати рекомендації щодо формування тіла POST запиту (особливо при пошуку IN/NOT_IN)