= Компонент Edit Grid
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Опис компонента

Компонент *Edit Grid* є потужним інструментом для роботи з таблицями у формах і дозволяє динамічно додавати, редагувати та видаляти рядки з таблиці. Це поле відображається у формі як таблиця, яка містить дані, які користувачі можуть редагувати. Компонент дозволяє вам налаштувати відображення, валідацію та інші опції для кожного рядка.

Розширення стандартного компонента *Edit Grid* включає додавання додаткових опцій, які спрощують моделювання. Це дозволяє розробникам та моделювальникам регламенту використовувати цей компонент більш гнучко та підлаштувати його під специфічні потреби різноманітних бізнес-сценаріїв.

CAUTION: Використовуйте *Edit Grid* з переліку *_Оновлених_* компонентів.

== Основні функції

Компонент *Edit Grid* підтримує велику кількість опцій для застосування при взаємодії із формою процесу, які розподілені за вкладками.

[tabs]
====
Display ::

* *`Label`*: назва компонента, яка відображається поряд з ним.
* *`Label Position`*: визначає положення мітки відносно компонента (верх, праворуч, зліва, або внизу).
* *`Description`*: опис компонента, який може допомогти користувачам зрозуміти його призначення.
* *`Tooltip`*: текст, який відображається при наведенні курсора на компонент.
* *`Quick Search`*: дозволяє користувачам швидко знаходити записи в таблиці, використовуючи простий пошуковий фільтр.
* *`Hidden`*: поля, які приховані від користувача, але все ще є частинами форми й будуть передані при відправленні форми.
* *`Multiple-record selection`*: дозволяє користувачам вибирати кілька записів в таблиці одночасно.
* *`Read Only`*: показує дані через окремий елемент управління в контекстному меню (три вертикальних крапки), який дозволяє переглядати дані без можливості редагування.

Data ::

* *`Redraw On`*: перемальовує компонент, якщо інший компонент змінюється.
* *`Clear value when hidden`*: коли значення приховане, очищує значення.

Validation ::

* *`Validate On`*: визначає, коли цей компонент повинен активувати валідацію на клієнті (опції Зміна або Розмиття).
* *`Required`*: поле обов'язкове для заповнення перед відправленням форми.
* *`Minimum length`*: Вказує мінімальну кількість рядків (записів), які потрібно ввести. Це забезпечує, що користувачі додають необхідний мінімум інформації до компонента.
* *`Maximum length`*: Встановлює максимальну кількість рядків (записів), які можна ввести. Ліміт становить 50 рядків. *Важливо:* це максимальне значення можна коригувати лише на менше.
* *`Custom error message`*: спеціальне повідомлення про помилку, яке відображається, коли дані не проходять валідацію.
* *`Custom validation`*: власна валідація, яка дозволяє вам створити специфічні для ваших потреб перевірки на валідність.

API ::

* *`Property name`*: ім'я цього поля для API-ендпоінту, яке відповідає назві таблиці у базі даних реєстру. Наприклад, *`licences`*.

Logic ::

include::registry-develop:bp-modeling/forms/components/general/common-descriptions/logic/index.adoc[]
* *`Record Actions`*: дії, які можна виконати із записами в таблиці (максимальна кількість дій -- 5). Наприклад, можна змінити дату терміну дії ліцензії (`Action: _action_update`) або анулювати ліцензію (`Action: _action_cancel`) тощо.

====

== Формат даних

Компонент приймає масив об'єктів. Кожен об'єкт у масиві може містити різні поля та їх значення. У прикладі нижче наведено один об'єкт з полем "textfield" та значенням 'test'.

.Submission
[source,typescript]
----
Array<Object>
// Приклад: [ { textfield: 'test' } ]
----