= Схема бази даних excerpt

[plantuml, excerpt-schema, svg]
----
@startuml
hide circle
skinparam linetype ortho

entity "**excerpt_record**" {
  + ""id"": //uuid [PK]//
  --
  ""status"": //text //
  ""status_details"": //text //
  ""keycloak_id"": //text //
  ""checksum"": //text //
  ""excerpt_key"": //text //
  *""created_at"": //timestamp with time zone //
  *""updated_at"": //timestamp with time zone //
  ""signature_required"": //boolean //
  ""x_source_system"": //text //
  ""x_source_application"": //text //
  ""x_source_business_process"": //text //
  ""x_source_business_activity"": //text //
  ""x_digital_signature"": //text //
  ""x_digital_signature_derived"": //text //
  *""excerpt_type"": //text //
}

entity "**excerpt_template**" {
  + ""id"": //uuid [PK]//
  --
  *""template_name"": //text //
  *""template"": //text //
  *""created_at"": //timestamp with time zone //
  *""updated_at"": //timestamp with time zone //
  *""checksum"": //text //
  *""template_type"": //text //
}
@enduml



----
=== excerpt_record
Записи генерації витягів та статусу

[options="header",cols="a"]
|======
|Ім'я колонки +
Опис
| `*id* _uuid_ *(PK)*` + 
Ідентифікатор рядка 
| `status _text_` + 
Статус генерації витягу

* 0 - Виконується
* 1 - Помилка
* 2 - Завершено
| `status_details _text_` + 
Деталі у разі помилки 
| `keycloak_id _text_` + 
Ідентифікатор користувача який ініціював витяг
| `checksum _text_` + 
Контрольна сума витягу
| `excerpt_key _text_` + 
Ключ документу витягу у CEPH
| `*created_at* _timestamp with time zone_` + 
Час створення запиту
| `*updated_at* _timestamp with time zone_` + 
Час оновлення запиту
| `signature_required _boolean_` + 
Необхідність накладання системного підпису для заданого типу звіту 
| `x_source_system _text_` + 
Назви підсистеми, яка виконує запит 
| `x_source_application _text_` + 
Назва компоненти підсистеми, яка ініціює запит 
| `x_source_business_process _text_` + 
Назва бізнес-процесу, яку визначив адміністратор регламенту при моделюванні 
| `x_source_business_activity _text_` + 
Назва сервісної задачі, яку визначив адміністратор регламенту при моделюванні  
| `x_digital_signature _text_` + 
Посилання на Ceph документ, в якому збережено оригінальний запит користувача та підпис 
| `x_digital_signature_derived _text_` + 
Посилання на Ceph документ в якому зберігається системний підпис, який автоматично накладено на тіло запиту 
| `*excerpt_type* _text_` + 
Тип витягу, який необхідно згенерувати в рамках бізнес-процесу

* csv
* pdf
* docx

|======

=== excerpt_template
Шаблони витягів. Таблиця заповнюється на етапі розгортання регламенту, у разі співпадіння імен та не співпадіння контрольної суми оновлюється тіло шаблону.

[options="header",cols="a"]
|======
|Ім'я колонки +
Опис
| `*id* _uuid_ *(PK)*` + 
Ідентифікатор рядка 
| `*template_name* _text_` + 
Ім'я шаблону. Є унікальним.
| `*template* _text_` + 
Зміст шаблону
| `*created_at* _timestamp with time zone_` + 
Час створення шаблону
| `*updated_at* _timestamp with time zone_` + 
Час оновлення шаблону
| `*checksum* _text_` + 
Контрольна сума шаблону 
| `*template_type* _text_` + 
Формат витягу

* csv
* pdf
* docx

|======
[options="header",cols="a"]
|======
|Обмеження унікальності
|`template_name`
|======