name: ddm-architecture
namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: apps.cicd.mdtu-ddm.projects.epam.com

image:
  name: ddm-architecture
  version: latest

ingress:
  site: ddm-architecture
  path: /