= Функція _get_digital_document_metadata()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`get_digital_document_metadata(String documentId): DocumentMetadata`* використовується для отримання метаданих документа, які зберігаються в сервісі цифрових документів.

== Параметри

.Параметри функції
|===
|*Аргумент*    | *Опис*
| `documentId` | Ідентифікатор документа, метадані якого потрібно отримати.
|===

== Що повертає

Ця функція повертає об'єкт типу `DocumentMetadata`, що містить метадані документа.

.Службовий API сервісу цифрових документів
[source,http]
----
GET /internal-api/documents/{processInstanceId}/{id}/metadata (DocumentMetadata)
----

.DocumentMetadata
|===
|*Поле*            | *Тип*  | *Опис*
| `id`             | UUID   | Унікальний ідентифікатор цифрового документа, сформований з використанням генератора псевдовипадкових чисел.
| `name`           | Текстовий | Оригінальна назва файлу.
| `type`           | Текстовий | Тип контенту файлу (`application/pdf`, `image/png`, `image/jpeg`, etc.)
| `checksum`       | Текстовий | Автоматично згенерований геш, що накладається на контент файлу з використанням алгоритму `SHA256`.
| `size`           | Числовий  | Розмір файлу.
|===

.Приклад тіла відповіді
[source, json]
----
{
  "id": "{UUID}",
  "name": "{fileName}",
  "type": "{contentType}",
  "checksum": "{sha256}",
  "size": 0
}
----

== Алгоритм роботи

Функція працює за таким алгоритмом:

. Функція `get_digital_document_metadata()` приймає ідентифікатор документа як вхідний параметр.
. Виконується запит до внутрішнього API сервісу цифрових документів для отримання метаданих документа.
. Отримані метадані документа повертаються у вигляді об'єкта `DocumentMetadata`, що містить інформацію про документ.

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

== Приклади використання

Цей розділ демонструє приклади використання JUEL-функції у Groovy-скриптах бізнес-процесу.

TIP: Застосування функції `get_digital_document_metadata()` детально представлено у референтному прикладі на сторінці xref:best-practices/bp-upload-edit-file.adoc[].

== Пов'язані сторінки

* xref:bp-modeling/bp/juel-functions/digital-documents/save-digital-document.adoc[]
* xref:bp-modeling/bp/juel-functions/digital-documents/save-digital-document-from-url.adoc[]
* xref:bp-modeling/bp/juel-functions/digital-documents/load-digital-document.adoc[]
* xref:best-practices/bp-upload-edit-file.adoc[]
* xref:bp-modeling/bp/save-digital-doc-remote-url.adoc[]
