= Функція _load_digital_document()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`load_digital_document(String documentId): byte[]`* призначена для вивантаження цифрових документів. Ця функція використовує ідентифікатор документа (`documentId`), який передається як вхідний параметр для отримання відповідного документа через внутрішній API сервісу цифрових документів.

== Параметри

.Параметри функції
|===
|*Аргумент*    | *Опис*
| `documentId` | Ідентифікатор документа, який потрібно вивантажити.
|===

== Що повертає

Функція повертає документ у форматі байтів (`byte[]`), що дозволяє працювати з даними документа на низькому рівні.

.Службовий API сервісу цифрових документів
[source,http]
----
GET /internal-api/documents/{processInstanceId}/{id} (binary response)
----

== Алгоритм роботи

Функція працює за таким алгоритмом:

. Функція `load_digital_document()` приймає ідентифікатор документа як вхідний параметр.
. Виконується запит до внутрішнього API сервісу цифрових документів для вивантаження документа.
. Отриманий документ повертається у форматі масиву байтів (`byte[]`), що дозволяє розробникам працювати з даними документа на низькому рівні.

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

== Приклади використання

Цей розділ демонструє приклади використання JUEL-функції у Groovy-скриптах бізнес-процесу.

TIP: Застосування функції `load_digital_document()` детально представлено у референтному прикладі на сторінці xref:best-practices/bp-upload-edit-file.adoc[].

== Пов'язані сторінки

* xref:bp-modeling/bp/juel-functions/digital-documents/save-digital-document.adoc[]
* xref:bp-modeling/bp/juel-functions/digital-documents/save-digital-document-from-url.adoc[]
* xref:bp-modeling/bp/juel-functions/digital-documents/get-digital-document-metadata.adoc[]
* xref:best-practices/bp-upload-edit-file.adoc[]
* xref:bp-modeling/bp/save-digital-doc-remote-url.adoc[]