= Функція _save_digital_document_from_url()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`save_digital_document_from_url(String remoteFileUrl, String targetFileName): DocumentMetadata`* дозволяє отримувати цифрові файли/документи за віддаленою адресою від публічних API, тобто таких, що не потребують автентифікації. ЇЇ можна використовувати для спрощення моделювання бізнес-процесів у скриптах.

== Параметри

.Параметри функції
|===
|*Аргумент*        | *Опис*
| `remoteFileUrl`  | URL цифрового документа.
| `targetFileName` | Назва файлу.
|===

== Що повертає

Ця функція повертає об'єкт типу `DocumentMetadata`, що містить метадані збереженого документа.

.DocumentMetadata
|===
|*Поле*            | *Тип*  | *Опис*
| `id`             | UUID   | Унікальний ідентифікатор цифрового документа, сформований з використанням генератора псевдовипадкових чисел.
| `name`           | Текстовий | Оригінальна назва файлу.
| `type`           | Текстовий | Тип контенту файлу (`application/pdf`, `image/png`, `image/jpeg`, etc.)
| `checksum`       | Текстовий | Автоматично згенерований геш, що накладається на контент файлу з використанням алгоритму `SHA256`.
| `size`           | Числовий  | Розмір файлу.
|===

.Приклад тіла відповіді
[source, json]
----
{
  "id": "{UUID}",
  "name": "{fileName}",
  "type": "{contentType}",
  "checksum": "{sha256}",
  "size": 0
}
----

== Алгоритм роботи та обмеження


Функція працює за таким алгоритмом:

. Функція `save_digital_document_from_url()` виконує запит до відкритого ресурсу за вказаним посиланням та отримує цифровий документ (наприклад, зображення у форматі `.jpeg`).
. Далі передає файл _Сервісу цифрових документів_ (`digital-document-service`).
. Сервіс зберігає файл у зашифрованому вигляді до _Об'єктного сховища проміжних даних БП_ (`lowcode-file-storage`) та у відповідь отримує метадані, зокрема *`id`*, *`name`*, *`type`*, *`checksum`* та *`size`* документа, які передаються до бізнес-процесу.

Ці метадані можна використати у бізнес-процесі для подальшого оброблення та збереження документа.

//File upload restrictions
include::registry-develop:partial$snippets/juel/file-upload-restrictions.adoc[]

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

== Приклади використання

Цей розділ демонструє приклади використання JUEL-функції у завданнях бізнес-процесу.

TIP: Застосування функції `save_digital_document_from_url()` детально представлено у прикладі на сторінці xref:bp-modeling/bp/save-digital-doc-remote-url.adoc[].

== Пов'язані сторінки

* xref:bp-modeling/bp/juel-functions/digital-documents/save-digital-document.adoc[]
* xref:bp-modeling/bp/juel-functions/digital-documents/load-digital-document.adoc[]
* xref:bp-modeling/bp/juel-functions/digital-documents/get-digital-document-metadata.adoc[]
* xref:best-practices/bp-upload-edit-file.adoc[]
* xref:bp-modeling/bp/save-digital-doc-remote-url.adoc[]