= Registry administrative zone
include::ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::ROOT:partial$admonitions/language-en.adoc[]

== General description

_The Registry administrative zone_ is a collection of subsystems that provide functions for developing and deploying the digital registry regulations using the _GitOps_ approach by making changes to the corresponding version control repository and automatically applying them.

_The Registry regulations modeling subsystem_ of the administrative zone provides web interfaces for administrators, through which they can create data models, business processes for information and administrative services, define organizational structure and access rights, configure external integrations, generate analytical reports and extracts, and more.

[TIP]
--
For more details on the roles of system administrators see xref:arch:architecture/platform/operational/user-management/platform-actors-roles.adoc#system-administrators[Platform actors and roles] section.
--

== Technical design

This diagram depicts the subsystems comprising the _Registry administrative zone_ and their interactions with other subsystems within the scope of implementation of functional scenarios.

image::architecture/registry/administrative/administrative-zone-subsystems.svg[]

== Registry administrative zone subsystems

|===
|Subsystem name|Service name

|xref:architecture/registry/administrative/ext-api-management/overview.adoc[]
|_ext-api-management_

|xref:architecture/registry/administrative/regulation-management/overview.adoc[]
|_regulation-management_

|xref:architecture/registry/administrative/regulation-publication/overview.adoc[]
|_regulation-publication_

|xref:architecture/registry/administrative/operational-maintenance/overview.adoc[]
|_operational-maintenance_
|===