== Підпис даних UI-форм з файловими вкладеннями та подальше збереження у Дата Фабриці через кабінет користувача

=== Взаємодія компонентів системи
На даній діаграмі зображено сценарій підпису даних з файловими вкладеннями в рамках виконання задачі користувачем, обробка даних в рамках бізнес-процесу та їх збереження в Дата Фабрику.

[plantuml, file_signing, svg]
----
include::partial$lowcode/file-signing.puml[]
----

=== Формування запиту на збереження підписаних даних форми через серверний додаток

При формуванні запиту на збереження підписаних даних UI-форми у серверному додатку, на стороні клієнта необхідно провести трансформацію значень полів типу _File_ JSON-документа, результатом якої стане JSON-документ, який відповідає заданій канонічній формі (<<_взаємодія_компонентів_системи, Діаграма взаємодії:6>>):

[source, json]
----
{
  "data": {
      "<file_property_name>": [
        {
          "name": "<original file name with extension>",
          "type": "<mime type>",
          "size": 1,
          "content": "<base64 content>"
        }
      ]
  },
  "signature": "<e-signature>"
}
----

.Приклад запиту на збереження підписаних даних UI-форми через сервіс "Управління задачами користувача" (<<_взаємодія_компонентів_системи, Діаграма взаємодії:6>>)
[source, json]
----
{
  "data": {
      "passport_scans": [
        {
          "name": "passport.png",
          "type": "image/png",
          "size": 324801,
          "content": "/9j/4AAQSkZJRgABAQA0e0vuj/8ALAP/2Q=="
        }
      ]
  },
  "signature": "JRgABAQA0e0vuj"
}
----

== Опис формату збереження документів з підписом в Ceph
.Приклад Ceph-документу з підписаними даними UI-форми, отриманої з клієнтського додатку, за умови наявності полів типу "File" (<<_взаємодія_компонентів_системи, Діаграма взаємодії:18>>)
[source, json]
----
{
  "data": {
      "passport_scans": [
        {
          "name": "passport.png",
          "type": "image/png",
          "size": 324801,
          "content": "/9j/4AAQSkZJRgABAQA0e0vuj/8ALAP/2Q=="
        }
      ]
  },
  "x-access-token": "<access token>",
  "signature": "<e-signature>"
}
----

.Приклад Ceph-документу з даними трансформованої UI-форми з посиланнями на Ceph-документи (<<_взаємодія_компонентів_системи, Діаграма взаємодії:32>>)
[source, json]
----
{
  "data": {
      "passport_scans": [
        {
          "id": "<Ceph reference UUID>",
        }
      ]
  },
  "x-access-token": "<access token>"
}
----

== Опис контракту взаємодії з Дата Фабрикою при збереженні сутностей з файловими вкладеннями

- Збереження файлових вкладень реалізується за рахунок обміну посиланнями на попередньо збережені Ceph-документи у бакеті "_backend-ceph-bucket_"
- Для полів типу _File_ сутності, _завжди_ використовується масив структур у якості значення, де кожна структура містить мета-дані файлу та UUID-посилання на Ceph-документ з контентом файлу
- Перед формуванням запиту на збереження сутності з файловими вкладеннями у вигляді посилань на Ceph-документи, оригінальні файли повинні бути збережені у окремому бакети з відповідними UUID документів

NOTE: Підтримка роботи з файлами на Дата Фабриці запланована в два етапи: 1 файл у якості значення поля типу "_File_", а в подальшому - підтримка N файлів.

.Приклад тіла запиту на збереження даних сутності з файловими вкладеннями (<<_взаємодія_компонентів_системи, Діаграма взаємодії:42>>)
[source,json]
----
{
  "passport_scans": [
    {
      "id": "<Ceph document UUID>"
    }
  ]
}
----