== Вивантаження файлових вкладень через UI-форми у кабінеті користувача

=== Взаємодія компонентів системи
На даній діаграмі зображено сценарій отримання сутності з файловими вкладеннями, яка була попередньо збережена у Дата Фабриці та послідуюча її підготовка для відображення на UI-формі задачі користувача.

[plantuml, file_download, svg]
----
include::partial$lowcode/file-download.puml[]
----

=== Опис контракту взаємодії з Дата Фабрикою при отриманні сутностей з файловими вкладеннями

- Отримання файлових вкладень реалізується за рахунок обміну посиланнями на попередньо збережені Ceph-документи у бакеті "_backend-ceph-bucket_"
- При отриманні даних сутності, яка містить файлові вкладення у вигляді посилань на Ceph-документи, Дата Фабрика попередньо зберігає контент відповідних файлів в бакеті "_backend-ceph-bucket_"
- Для полів типу _File_ сутності, _завжди_ використовується масив структур у якості значення, де кожна структура містить мета-дані файлу та UUID-посилання на Ceph-документ з контентом файлу
- Доступ до файлів, завантажених як вкладення до сутності, можливий лише через отримання даних цієї сутності та послідуюче читання контенту за посиланням на Ceph-документ з бакету "_backend-ceph-bucket_"

NOTE: Підтримка роботи з файлами на Дата Фабриці запланована в два етапи: 1 файл у якості значення поля типу "_File_", а в подальшому - підтримка N файлів.

.Канонічний вигляд відповіді на запит отримання даних сутності з файловими вкладеннями (<<_взаємодія_компонентів_системи, Діаграма взаємодії:5>>)
[source,json]
----
{
  "<file_property_name>": [
    {
      "id": "<Ceph document UUID>",
      "checksum": "<checksum>"
    }
  ]
}
----

=== Опис формату збереження документів в Ceph

.Приклад Ceph-документу з даними, підготовленими для передзаповнення UI-форми в БП на базі даних сутності, отриманої з Дата Фабрики, за умови наявності полів типу "File" (<<_взаємодія_компонентів_системи, Діаграма взаємодії:7>>)
[source, json]
----
{
  "data": {
      "passport_scans": [
        {
          "id": "<Ceph document UUID>"
        }
      ]
  }
}
----