== Робота з файловими вкладеннями у кабінеті користувача

Для забезпечення вимог по роботі з файлами через кабінет, реалізована підтримка окремої компоненти "_File_" для використання при моделюванні UI-форм задач користувачів через адміністративний інтерфейс. Цей компонент надає можливості завантаження, вивантаження та попереднього перегляду файлів та підтримує режими роботи з одним або декількома файлами водночас в залежності від поточної конфігурації, визначеної адміністратором регламенту. Наразі підтримуються наступні типи файлів:

- _application/pdf_
- _image/jpeg_
- _image/png_

В залежності від бізнес-процесу, файли, завантажені в рамках виконання задачі користувача, можуть бути доступні для перегляду та вивантаження іншими користувачами в рамках їхніх задач екземпляру цього бізнес-процесу або збережені у Дата Фабриці.

=== Базові принципи

- UI-компонента "_File_" налаштована на роботу в режимі збереження та відображення файлів на клієнтському додатку у _Base64_ форматі
- Контент файлів передається між клієнтським та серверним додатками у _Base64_ форматі разом з даними форми у єдиному JSON документі
- При підписанні особистим ключем даних форми, в якій використовується компонента "_File_", підпис генерується на увесь JSON документ разом з _Base64_ контентом файлів у якості значень полів UI-форми
- Підписаний користувачем оригінальний JSON документ даних форми з _Base64_ контентом файлів зберігається в Ceph для подальшого використання у якості джерела для формування _X-Digital-Signature_
- В рамках обробки даних форми користувача в якій присутні файли, система відокремлює контент файлів та зберігає в об'єктному сховищі Ceph, а на базі оригінального JSON документу створюється новий документ аналогічної структури, в якому _Base64_ контент заміщений посиланнями на попередньо збережені Ceph-документи файлів
- Контент файлів зберігається у проміжному об'єктному сховищі Ceph для подальшого використання в рамках задач користувачів за посиланням на Ceph-документ та збереження у Дата Фабрику
- При взаємодії з Дата Фабрикою для обміну файлами використовується принцип обміну посиланнями на Ceph-документи, які попереднью збережені в окремий бакет Low-code платформи

===  Низькорівневий дизайн

image::lowcode/file-management.svg[]

===  Обмін файлами / посиланнями при взаємодії Low-code та Дата Фабрики
[plantuml,file_exchange,svg]
----
@startuml
skinparam monochrome true

participant "Клієнтський додаток\n кабінету користувача" as cabinet
participant "Сервіс управління \nзадачами користувача" as user_task_mngmnt
participant "Сервіс виконання \nбізнес-процесів" as bpms
participant "Дата Фабрика" as data_factory
participant "Ceph бакет \nLow-code" as lowcode_ceph_bucket
participant "Ceph бакет \nДата Фабрики" as data_ceph_bucket
participant "Сховище даних \nДата Фабрики" as citus
skinparam responseMessageBelowArrow true

title Обмін файлами при взаємодії Low-code та Дата Фабрики

activate cabinet
  cabinet -> user_task_mngmnt: Виконання підпису даних форми та файлових вкладень у вигляді єдиного документа
  activate user_task_mngmnt
    user_task_mngmnt -> lowcode_ceph_bucket: Зберегти оригінальний документ даних форми та Base64 файлових вкладень з єдиним підписом (документ підпису)
    user_task_mngmnt -> lowcode_ceph_bucket: Зберегти декодовані файлові вкладення у вигляді окремих Ceph-документів
    user_task_mngmnt -> lowcode_ceph_bucket: Зберегти документ даних форми з Ceph-посиланнями на файлові вкладення
    user_task_mngmnt -> bpms: Завершення виконання задачі
    activate bpms
      bpms -> lowcode_ceph_bucket: Зчитати документ даних форми
      lowcode_ceph_bucket --> bpms: Дані форми з Ceph-посиланнями на файлові вкладення
      note over bpms, data_factory: X-Digital-Signature - оригінальний документ з підписом користувача
      bpms -> data_factory: Запит на збереження документа даних форми з Ceph-посиланнями на файлові вкладення
      activate data_factory
        data_factory -> lowcode_ceph_bucket: Отримання Ceph-документів за посиланнями (UUID)
        lowcode_ceph_bucket --> data_factory: Ceph-документи з декодованим контентом та мета-атрибутами
        data_factory -> data_ceph_bucket: Збереження Ceph-документів за ідентичними ключами UUID
        data_factory -> citus: Збереження даних сутності з Ceph-посиланнями (UUID)
        data_factory -> bpms: 200 OK, Дані збережено
      deactivate data_factory

      bpms -> data_factory: Отримання даних сутності
      activate data_factory
        data_factory -> citus: Отримання даних сутності з Ceph-посиланнями (UUID)
        citus --> data_factory: Дані сутності з UUID Ceph-документів
        data_factory -> data_ceph_bucket: Отримання Ceph-документів за посиланнями (UUID)
        data_ceph_bucket --> data_factory: Ceph-документи з декодованим контентом та мета-атрибутами
        data_factory -> lowcode_ceph_bucket: Збереження Ceph-документів за ідентичними ключами (UUID)
        data_factory --> bpms: 200 OK, Дані сутності з Ceph-посиланнями
      deactivate data_factory
      bpms --> cabinet: Повернення управління
    deactivate bpms
  deactivate user_task_mngmnt
deactivate cabinet

@enduml
----

=== Відкриті питання, обмеження та альтернативні підходи

* Необхідно визначити максимально допустимий розмір (_hard limit_), при якому дозволено завантажувати файли через кабінет користувача (_soft limit_ вказується адміністратором при моделюванні UI-форми)
* Необхідно визначити максимально допустимий розмір контенту, який підтримується ІІТ бібліотекою для генерації та валідації підпису
** _Prozorro_ та _Дія_ використовують _49МБ_ та _50МБ_ у якості максимального розміру документу / пакету документів для завантаження та підпису
* Використання підходу збереження контенту файлових вкладень на клієнті накладає обмеження на максимальний сумарний розмір завантажених файлів для однієї UI-форми
** Альтернативою є реалізація підтримки File Storage = URL для Form.IO компоненти "_File_" при якому завантаження контенту виконується напряму на сервер, що автоматично ускладнює процес підпису контенту (необхідність отримання геша даних файлу та його підписування)
* Використання підходу підпису даних форми разом з Base64 контентов завантажених файлів накладає обмеження на кількість файлів в залежності від їх розміру
** Альтернативою є відокремлення накладання підпису даних форми та завантажених файлів (1 + N згенерованих підписів). У цьому разі, підписи, згенеровані на контент файлів можуть бути збережені у вигляді окремих користувачьких атрибутів на рівні Ceph-документів файлових вкладень
** Визначити необхідність накладання підпису на дані форми разом з контентом файлових вкладень для забезпечення цілістності. Альтернативою є накладання підпису на дані форми з включенням контрольних сум / метаданих файлових вкладень замість фактичного контенту та генерація та збереження підписів на файли окремо
* Необхідність повторного накладання підпису для файлових вкладень документів, які вже є "підписаними" користувачем / включають цифровий підпис. Підтримка розпізнавання таких документів?