== Робота з файловими вкладеннями у кабінеті користувача

Для забезпечення вимог по роботі з файлами через кабінет, реалізована підтримка окремої компоненти "_File_" для використання при моделюванні UI-форм задач користувачів через адміністративний інтерфейс. Цей компонент надає можливості завантаження, вивантаження та попереднього перегляду файлів та підтримує режими роботи з одним або декількома файлами водночас в залежності від поточної конфігурації, визначеної адміністратором регламенту. Наразі підтримуються наступні типи файлів:

- _application/pdf_
- _image/jpeg_
- _image/png_

В залежності від бізнес-процесу, файли, завантажені в рамках виконання задачі користувача, можуть бути доступні для перегляду та вивантаження іншими користувачами в рамках їхніх задач екземпляру цього бізнес-процесу або збережені у Дата Фабриці.

=== Базові принципи
- UI-компонента "_File_" налаштована на роботу в режимі збереження та відображення файлів на клієнтському додатку у _Base64_ форматі
- Контент файлів передається між клієнтським та серверним додатками у _Base64_ форматі разом з даними форми у єдиному JSON документі
- При підписанні особистим ключем даних форми, в якій використовується компонента "_File_", підпис генерується на увесь JSON документ разом з _Base64_ контентом файлів у якості значень полів UI-форми
- Підписаний користувачем оригінальний JSON документ даних форми з _Base64_ контентом файлів зберігається в Ceph для подальшого використання у якості джерела для формування _X-Digital-Signature_
- В рамках обробки даних форми користувача в якій присутні файли, система відокремлює контент файлів та зберігає в об'єктному сховищі Ceph, а на базі оригінального JSON документу створюється новий документ аналогічної структури, в якому _Base64_ контент заміщений посиланнями на попередньо збережені Ceph-документи файлів
- Контент файлів зберігається у проміжному об'єктному сховищі Ceph для подальшого використання в рамках задач користувачів за посиланням на Ceph-документ та збереження у Дата Фабрику
- При взаємодії з Дата Фабрикою для обміну файлами використовується принцип обміну посиланнями на Ceph-документи, які попереднью збережені в окремий бакет Low-code платформи

===  Низькорівневий дизайн

image::lowcode/file-management.svg[]