== Завантаження файлових вкладень через UI-форми у кабінеті користувача

=== Взаємодія компонентів системи
На даній діаграмі зображено сценарій внесення даних з файловими вкладеннями в рамках виконання задачі користувачем, обробка даних в рамках бізнес-процесу та використання їх для попереднього заповнення наступної задачі користувача з можливостями перегляду та вивантаження файлів.

[plantuml]
----
include::partial$lowcode/file-upload.puml[]
----

=== Збереження даних файлових вкладень у клієнтському додатку
Для збереження контенту файлів як невід'ємної частини JSON-документа даних форми, прийнято підхід використання схеми *data:[<тип даних>][;base64],<дані у Base64>*.

.Канонічний вигляд структури даних форми з полем типу "File" у клієнтському додатку (<<_взаємодія_компонентів_системи, Діаграма взаємодії:4>>)
[source, json]
----
{
    "data": {
      "<file_property_name>": [
        {
            "storage": "base64",
            "name": "<original file name>-<UUID>.<original file extension>",
            "url": "[data:]<mime type>[;base64,]<base64 content>",
            "size": 0,
            "type": "<mime type>",
            "originalName": "<original file name with extension>"
        }
      ]
    }
}
----

.Приклад структури даних форми з полем типу "File" у клієнтському додатку
[source, json]
----
{
    "data": {
      "passport_scans": [
        {
            "storage": "base64",
            "name": "passport-b7dc6f8b-8247-471f-8145-7db4b7e7180e.png",
            "url": "data:image/png;base64,/9j/4AAQSkZJRgABAQA0e0vuj/8ALAP/2Q==",
            "size": 324801,
            "type": "image/png",
            "originalName": "passport.png"
        }
      ]
    }
}
----

=== Формування запиту на збереження даних форми через серверний додаток

При формуванні запиту на збереження даних UI-форми у серверному додатку, на стороні клієнта необхідно провести трансформацію значень полів типу _File_ JSON-документа, результатом якої стане JSON-документ, який відповідає заданій канонічній формі:

[source, json]
----
{
  "data": {
      "<file_property_name>": [
        {
          "name": "<original file name with extension>",
          "type": "<mime type>",
          "size": 0,
          "content": "<base64 content>"
        }
      ]
  }
}
----

.Приклад запиту на збереження даних UI-форми через сервіс "Управління задачами користувача" (<<_взаємодія_компонентів_системи, Діаграма взаємодії:8>>)
[source, json]
----
{
  "data": {
      "passport_scans": [
        {
          "name": "passport.png",
          "type": "image/png",
          "size": 324801,
          "content": "/9j/4AAQSkZJRgABAQA0e0vuj/8ALAP/2Q=="
        }
      ]
  }
}
----

=== Опис формату збереження документів в Ceph у процесі обробки запиту на виконання задачі

.Приклад Ceph-документу даних UI-форми з полем типу "File" після трансформації та відокремлення контенту та метаданих файлів у вигляді окремих Ceph-документів (<<_взаємодія_компонентів_системи, Діаграма взаємодії:28>>)
[source, json]
----
{
  "data": {
      "<file_property_name>": [
        {
          "id": "<Ceph document UUID>"
        }
      ]
  },
  "x-access-token": "<access token>"
}
----

.Структура Ceph-документа файлового вкладення (<<_взаємодія_компонентів_системи, Діаграма взаємодії:24>>)
|===
|Назва атрибуту|Атрибут JSON-документа|Атрибут Ceph об'єкта|Значення

|Ключ документа
|
|key
|<Автоматично згенерований UUID>

|Назва файлу
|name
|UserMetaData.name
|<Назва файлу>

|Тип контента
|type
|Content-Type (UserMetaData.type)
|application/pdf, image/png, image/jpeg

|Розмір
|size
|Content-Length (UserMetaData.size)
|<Розмір файлу>

|Контент документа
|content
|input
|<Декодований з Base64 бінарний контент файла>
|===