= Інтеграція із зовнішніми системами: _Connect to external system v2_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

.Короткі відомості про делегат
|===
|Назва |Пояснення

|Бізнес-назва інтеграційного розширення
|*Connect to external system v2*

|Службова назва інтеграційного розширення
|*`${externalSystemConnectorDelegateV2}`*

|Назва файлу у бібліотеці розширень
|*_externalSystemConnectorDelegateV2.json_*
|===

Загальне інтеграційне розширення-делегат, також відоме як *REST Connector*, надає можливість взаємодіяти із зовнішніми системами через REST API й налаштовується у сервісних задачах (*Service Task*) бізнес-процесу за допомогою шаблону *Connect to external system v2*.

NOTE: При налаштуванні делегата у додатку Camunda Modeler, переконайтеся, що папка із застосунком *_resources > element-templates_* містить файл *_externalSystemConnectorDelegateV2.json_*.

TIP: Детальніше про застосування REST-конектора у бізнес-процесах ви можете переглянути на сторінці xref:registry-develop:bp-modeling/bp/rest-connector.adoc[].