= Розгортання Платформи без інструментів та роутів для розробки реєстру

include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

Цей документ містить інформацію про загальні положення та технічний дизайн при розгортанні Платформи реєстрів.

== Загальні положення

* Компоненти, які залучені у процесах розробки реєстрів, не повинні розгортатись разом із prod-версіями Платформи реєстрів.
* Публічні роути компонентів, які залучені у процесах розробки реєстрів, не повинні створюватись разом із prod-версіями Платформи реєстрів.
* Шаблон реєстру повинен містити змінну для вказання поточного режиму розгортання Платформи реєстрів.
* Підтримується два режими розгортання: `production` та `development`.

== Верхньорівневий технічний дизайн
В таблиці нижче зазначені компоненти та їх роути які залучені або потребують змін/створення в рамках реалізації функціональних вимог згідно з технічним дизайном рішення.

include::platform:ROOT:partial$templates/snippets/dev-prod-mode-ua.adoc[]

Для налаштування відповідних режимів для темплейтів потрібно вказати потрібний режим наступним чином:
----
global:
  deploymentMode: development
----

У випадку необхідності розгортання реєстру без конкретного порталу, наприклад, порталу отримувача послуг, необхідно додати наступний параметр:
----
global:
  excludePortals: ['citizen']
----

IMPORTANT: За замовчуванням змінна `excludePortals` відсутня, що означає розгортання всіх порталів.

При виключенні порталу отримувача послуг із процесу розгортання, наступні сервіси також не повинні розгортатись:

* citizen-portal
* ddm-notification-service
* user-service-api
* user-service-persistence
