= Підсистема розгортання та налаштування Платформи та реєстрів

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Підсистема розгортання та налаштування Платформи та реєстрів - це комплекс різноманітних інструментів і процесів, які
дозволяють забезпечити ефективне та безперервне функціонування Платформи та Реєстрів відповідно до потреб користувачів Платформи.

Підсистема забезпечує такі функції як розгортання, налаштування, оновлення, зберігання компонентів та контроль версій
компонентів Платформи та Реєстрів і їх конфігурацій.

Підсистема реалізована з використанням GitOps-практик, що означає стан Платформи та реєстрів зберігається в репозиторії
системи контроля версій Git (Gerrit). Інші компоненти підсистеми, такі як оператори та інструменти CI/CD (Jenkins), контролюють
стан Платформи та реєстрів та приводять її до тієї, що збережена в репозиторії.

== Функції підсистеми

* Розгортання, конфігурування та оновлення компонентів Платформи та реєстрів
* Зберігання компонентів Платформи та Реєстрів
* Версіонування конфігурації Платформи та Реєстрів

== Технічний дизайн підсистеми

.Діаграма компонентів підсистеми та їх взаємодії
image::architecture/platform/administrative/config-management/config-mgmt.svg[]

== Структура конфігурації реєстру

.Складові конфігурації реєстрів
image::architecture/platform/administrative/config-management/registry-configuration-structure.svg[]

== Складові підсистеми

|===
|Назва компоненти|Namespace|Deployment|Походження|Призначення

|_Сервіс інспекції та зберігання змін конфігурації_
|`control-plane`
|`gerrit`
|3rd-party
|Програмний інструмент, що дозволяє керувати версіями компонентів та конфігурацій. Тісно інтегрований з розподіленою
системою контроля версій Git та з допомогою цього інструменту адміністратори Платформи мають можливість переглядати всі
модифікації коду та конфігурацій за допомогою веб-браузера і затверджувати або відхиляти ці зміни.

|_Сервіс розгортання конфігурації_
|`control-plane`
|`jenkins`
|3rd-party
|Програмний комплекс, що забезпечує автоматизацію в життєвому циклі Платформи та Реєстрів. Виконує фактичне розгортання Реєстру, конфігурування, оновлення та безліч інших автоматизованих задач в Платформі.

|_Сховище артефактів Платформи_
|`control-plane-nexus`
|`nexus`
|3rd-party
|Центральне сховище артефактів, компонентів та їх залежностей з яких складається кожна окрема підсистема та Платформа в цілому.
Збереження артефактів платформи

|_Jenkins оператор_
|`control-plane`
|`jenkins-operator`
|epam-origin
|Допоміжне програмне забезпечення, яке виконує функції розгортання, налаштування та відновлення програмного комплексу Jenkins, як
компонента підсистеми.

|_Gerrit оператор_
|`control-plane`
|`gerrit-operator`
|epam-origin
|Допоміжне програмне забезпечення, яке виконує функції розгортання, налаштування та відновлення Gerrit, як
компонента підсистеми.

|_Codebase оператор_
|`control-plane`
|`codebase-operator`
|epam-origin
|Codebase оператор - це допоміжне програмне забезпечення, яке виконує функцію реєстрації нового Реєстру як компонента
Платформи та виконує первісну конфігурацію.

|_Nexus оператор_
|`control-plane-nexus`
|`nexus-operator`
|epam-origin
|Допоміжне програмне забезпечення, яке виконує функції розгортання, налаштування та відновлення Nexus Repository Manager, як
компонента підсистеми.

|===

== Атрибути якості підсистеми

=== _Portability_
Контейнери з компонентами підсистеми можуть бути розгорнуті або перенесені на різні хмарні середовища, на власну
локальну інфраструктуру або між іншими екземплярами Платформи реєстрів.

=== _Observability_
Підсистема управління Платформою та Реєстрами підтримує журналювання вхідних запитів, логування подій та збір метрик
продуктивності для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--

=== _Maintainability_

Підсистема розроблена з використанням підходу Gitops, що забезпечує опис конфігурації Платформи та реєстрів у вигляді
коду, що спрощує підтримку та розгортання. Це також дозволяє автоматизувати процес розгортання, зменшуючи ризик людської
помилки. Також, це дозволяє відстежувати зміни та забезпечує стабільність при розгортанні та технічним адміністраторам
легко вносити оновлення в Платформу та реєстри, відкочовувати зміни за потреби та підтримувати історію всіх внесених змін.
