= Референтний перелік питань до _transition_-дизайну

[TIP]
--
Даний перелік питань є підказкою / чек-листом для спрощення проведення аналізу вимог та підготовки технічного дизайну для подальшої реалізації технічного / бізнес епіку.

Він може змінюватись в залежності від рівня складності, задіяних експертиз, кількості підсистем та компонент, тощо.
--

* [x] До якого технічного / функціонального епіка відноситься технічний дизайн?
* [x] Яку проблему адресує / в якому контексті?
* [x] На яких функціях системи / функціональних сценаріях фокусується? Які є _out-of-scope_?
* [x] Які бізнес-актори / категорії користувачів задіяні?
* [x] Чи є необхідність розширення глосарію Платформи новими термінами / визначеннями / акронімами для спрощення розуміння?
* [x] Які гіпотези / обмеження / принципи закладені у технічний дизайн рішення?
* [x] В які підсистеми / сервіси / компоненти вносяться зміни? Чи є необхідність введення нових сервісів та яке їх призначення?
* [x] Чи є необхідність маркування сервісів / компонентів як застарілих для подальшого видалення?
* [x] Яка візуальна схема цільового дизайну системи?
* [x] Чи є необхідність змінювати політики міжсервісної взаємодії? Яким чином?
* [x] Чи змінюються зовнішні та внутрішні інтерфейси сервісів? Які контракти для взаємодії?
* [x] Яким чином реалізується аутентифікація / авторизація запитів?
* [x] Чи є взаємодія з зовнішніми системами, яким чином / на якому етапі налаштовується?
* [x] Як взаємодіють сервіси в рамках реалізації ключових сценаріїв?
* [x] Як реалізована робота з помилками на прикладі негативних сценаріїв?
* [x] Чи змінюються налаштування сервісів? На якому рівні контролюються (_система/реєстр/регламент_) та в рамках якого процесу застосовується?
* [x] Чи є зміни до процесів розгортання сервісів / системи? Які саме?
* [x] Чи є необхідність фіксації подій у бізнес-аудит? Які типи / структури подій?
* [x] Чи мають бути адресовані вимоги по інтернаціоналізації / локалізації? Яким чином?
* [x] Чи є необхідність тимчасового або постійного зберігання даних? В яких сховищах?
* [x] Які зміни вносяться до фізичної моделі? ERD / опис структур?
* [x] Чи є необхідність створення окремих ролей з привілегіями для взаємодії з БД?
* [x] Чи є зміни у досвіді моделювання регламенту? Яких складових та за допомогою яких розширень? Приклади моделювання?
* [x] Чи є необхідність розширення правил валідації цілісності регламенту?
* [x] Чи вносяться зміни до етапів процесу публікації регламенту?
* [x] Чи є зміни у досвіді адміністрування реєстру / платформи? Структура конфігурації / як застосовується?
* [x] Чи є особливості, які необхідно врахувати при реалізації на рівні низькорівневого дизайну?
* [x] Чи є необхідність створення додаткових дашбордів моніторингу?
* [x] Чи є додаткові вимоги до бекапування/відновлення даних?
* [x] Чи є додаткові вимоги до шифрування даних?
* [x] Чи потребує міграції даних / регламенту оновлення існуючих реєстрів?
* [x] Які експертизи знадобляться для реалізації технічного дизайну?
* [x] З яких ключових етапів / задач буде складатися розробка?