= Організація роботи з git репозиторіями під час роботи з декількома версіями регламенту реєстру

== Базові принципи
- Backend admin-portal service використовує в якості сховища даних: gerrit (git) та файлову систему (persistent volume)
- Файлова система зберігає окрему копію git clone для кожної версії-кандидату
- Файлова система зберігає окрему копію git clone для створення копій git clone для версій-кандидатів шляхом копіювання файлів на файловій системі.
- Існує окрема частина коду (scheduled job), що відповідає за оновлення (git rebase)  папок з кодом версій-кандидатів на файловій системі
- Під час запуску сервісу перевіряється сумісність коду на файловій системі с переліком версій-кандидатів в gerrit.
- Синхронізація дій користувачів в межах однієї версії-кандидату відбувається на боці "git client". Дана синхронізація є частиною git контракту та не потребує додаткової розробки даного функціоналу на боці користувача.

== Факти, необхідні під час роботи з gerrit/git
- Інформація про зміни
- Статус виконання тестів
- Інформація про конфлікти змін
- Історія змін
- Labels з MR, коментарії

== Типи сховищ даних та їх відповідальність фактам

Адмін-портал використовую в якості сховищ даних два типи:

- Gerrit
- Файлову систему (docker persistent volume).

На файловій системі знаходяться локальні копії (git clone) репозиторію регламенту реєстру.

Відповідність типів сховищ фактам

image::lowcode/admin-portal/regulation-repository/gitflow-facts.svg[gitflow-facts]

== Робота з локальними та віддаленими репозиторіями git

=== Опис структури файлів на файловій системі
Структура файлів на файловій системі:

- мастер версія репозиторію знаходиться в каталозі master
- версія-кандидат має одну, відповідну їй, директорію, що має назву reglamant-<gerrit-mr-number>. (Наприклад: reglament-127)

[listing]
checkout-dir
|- master
|- registry-<gerrit-mr-number>
|        ...
|- registry-<gerrit-mr-number>

=== Життєвий цикл файлів на файловій системі

image::lowcode/admin-portal/regulation-repository/git-directory-flow.svg[git-directory-flow]

=== Одночасна робота декількох користувачів над декількома версіями регламенту

image::lowcode/admin-portal/regulation-repository/gitflow-concurrent-work.svg[gitflow-concurrent-work]

Кожна версія-кандидат регламенту реєстру має відповідну їй "git clone" директорію на файловій системі. Всі операції над регламентом реєстру проводяться відносно цієї директорії (зміни в конфігурації регламенту шляхом зміни файлів на файловій системі).

Синхронізація змін відносно файлів на файловій системі відбуваються з використанням git клієнту. Кожна зміна від клієнта відбувається з використанням `git commit --amend`.

[CAUTION]
Під час одночасної роботи (виконання _git_ команд) декількох користувачів над однією версією, _Git_ блокує частину репозиторію шляхом створення _lock_ файлів. В такому випадку, задача, яка виконується після створення _lock_ файлу, буде чекати розблокування репозиторію або проінформує користувача про необхідність проведення операції пізніше (використовується _retry_ механізм для очікування завершення одночасних дій з репозиторієм на рівні _jGit_ java сервісу).

[WARNING]
Даний механізм використання _git lock_ файлів працює тільки з git клієнтом і не гарантує постійну консистентність даних на файловій системі під час виконання git операцій. xref:lowcode/admin-portal/regulation-repository/gitflow/git-repositories-management.adoc[Дивись документ.]




