= Системні вимоги до екземпляра Платформи
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

CAUTION: Сторінка у процесі розробки...

У цьому документі наведено системні вимоги до екземпляра Платформи. Основні аспекти цих вимог включають:

. _Вимоги до OKD-кластера_: OKD-кластер може бути розгорнутим у різних середовищах, включаючи публічні хмари як AWS або приватні рішення на базі vSphere. Кожне середовище вимагає свого підходу та специфікацій.

. _Вимоги до центральних сервісів Платформи_: Ці сервіси включають компоненти, які є спільними для всіх реєстрів і забезпечують загальне функціонування Платформи.

Деталі кожного з цих аспектів розглядаються в наступних розділах документа.
Проаналізуйте подану інформацію, щоб забезпечити оптимальний вибір ресурсів та конфігурацію для вашого екземпляра Платформи.

== Системні вимоги до середовища розгортання Платформи

=== Системні вимоги до OKD у публічному хмарному середовищі _AWS_

CAUTION: Розділ у процесі розробки...

Хости у вашому середовищі OKD повинні відповідати наступним технічним характеристикам та системним вимогам.

=== Системні вимоги до OKD 3.11 у хмарному середовищі AWS

TIP: Див. детальніше https://docs.okd.io/latest/installing/installing_aws/preparing-to-install-on-aws.html[Вимоги до встановлення OKD-кластера у середовищі AWS].

//TODO: Check all the figures as they are partially for OKD 3.11 version. Update to 4.11

Основні компоненти: ::
* _Мастер-вузли (*master nodes*)_: Керують кластером та ресурсами, контролюють розгортання застосунків, мають сховища конфігурацій.
* _Робочі вузли (*worker nodes*)_: Це вузли, де розгортаються контейнерні застосунки.
* _Інфраструктурні вузли (*infrastructure nodes*)_: Розгортають служби підтримки кластера, такі як маршрутизатори, метрика та журналювання.

Апаратні вимоги: ::
* _Мастер-вузли (*master nodes*)_:
** CPU: 2 vCPU
** ОЗУ: 16 GB RAM
** Дисковий простір: 40 GB
* _Робочі вузли (*worker nodes*)_:
** CPU: 2 vCPU
** ОЗУ: 8 GB RAM
** Дисковий простір: 15 GB
* _Інфраструктурні вузли (*infrastructure nodes*)_ (якщо вони використовуються):
** CPU: 2 vCPU
** ОЗУ: 8 GB RAM
** Дисковий простір: 20 GB

Мережеві вимоги: ::
* *MTU*: Рекомендований розмір MTU для ваших мережевих інтерфейсів -- 1500 байтів або більше.
* *DNS*: Усі вузли в кластері повинні мати можливість розв'язувати імена інших вузлів у мережі.

Вимоги до додаткового програмного забезпечення: ::
* *Docker*: Версія 1.13.1 або новіша для розгортання контейнерів.
* *Red Hat Enterprise Linux*: Версія 8 або новіша для вузлів.

Вимоги до AWS: ::
* Рекомендовано використовувати оптимізовані для роботи з EBS екземпляри EC2.
* Забезпечте належний доступ до ресурсів AWS, таких як VPC, EC2, S3 тощо.
* Розгляньте використання Elastic Load Balancers для розподілу навантаження.

=== Системні вимоги до OKD у приватному хмарному середовищі _vSphere_

CAUTION: Розділ у процесі розробки...

Хости у вашому середовищі OKD повинні відповідати наступним технічним характеристикам та системним вимогам.

//TODO: Check all the figures as they are partially for OKD 3.11 version. Update to 4.11
[minimal-okd-requirements]
==== Мінімальні вимоги встановлення кластера версії OKD 4.11 на vSphere VMware

TIP: Див. детальніше https://docs.okd.io/4.11/installing/installing_vsphere/installing-vsphere-installer-provisioned.html[Вимоги до встановлення OKD-кластера у середовищі vSphere].

Основні компоненти: ::
* _Мастер-вузли (*master nodes*)_: Керують кластером та ресурсами, контролюють розгортання застосунків, мають сховища конфігурацій.
* _Робочі вузли (*worker nodes*)_: Це вузли, де розгортаються контейнерні застосунки.
* _Інфраструктурні вузли (*infrastructure nodes*)_: Розгортають служби підтримки кластера, такі як маршрутизатори, метрика та журналювання.

Апаратні вимоги: ::
* _Мастер-вузли (*master nodes*)_:
** CPU: 2 vCPU
** ОЗУ: 16 GB RAM
** Дисковий простір: 40 GB
* _Робочі вузли (*worker nodes*)_:
** CPU: 1 vCPU
** ОЗУ: 8 GB RAM
** Дисковий простір: 15 GB
* _Інфраструктурні вузли (*infrastructure nodes*)_:
** CPU: 2 vCPU
** ОЗУ: 8 GB RAM
** Дисковий простір: 20 GB

Мережеві вимоги: ::
* *MTU*: Повинен бути налаштований так, щоб підтримувати найбільший розмір пакета, який потрібен для вашого розгортання.
* *DNS*: Всі вузли в кластері повинні мати можливість розв'язувати імена інших вузлів в мережі.

Вимоги до додаткового програмного забезпечення: ::
* *Docker*: Для розгортання контейнерів.
* *Red Hat Enterprise Linux*: Версія 7.3 або новіша для вузлів.

Вимоги до vSphere: ::
* *VM hardware*: 13 або новіша версія
* *vSphere ESXi hosts*: 6.5 або новіша
* *vCenter host*: 6.5 або новіша

{empty}

Мінімальна підтримувана версія vSphere для компонентів VMware: ::
+
* *Компонент Hypervisor:* Мінімально підтримувана версія: vSphere 6.5 або новіша, з HW-версією 13.
+
Це мінімальна версія, яку підтримує Fedora CoreOS (_див. детальніше на офіційному ресурсі: https://access.redhat.com/documentation/ru-ru/red_hat_enterprise_linux/8/html/configuring_and_managing_virtualization/feature-support-and-limitations-in-rhel-8-virtualization_configuring-and-managing-virtualization[Red Hat Enterprise Linux 8 supported hypervisors list]_).

* *Компонент Storage with in-tree drivers*: Мінімально підтримувана версія -- vSphere 6.5 або новіша.
+
Цей плагін створює сховище vSphere за допомогою драйверів сховища в ієрархії для vSphere, які входять до OKD.

* (_Опціонально_) Компонент *Networking (NSX-T)*: Мінімально підтримувана версія -- vSphere 6.5U3 або vSphere 6.7U2 та новіша.
+
OKD вимагає vSphere 6.5U3 або vSphere 6.7U2+. NSX Container Plug-in (NCP) VMware сертифіковано для OKD 4.6 і NSX-T 3.x.

== Системні вимоги до центральних сервісів Платформи

CAUTION: Розділ у процесі розробки...

Системні вимоги до центральних сервісів Платформи окреслюють необхідні ресурси для їх ефективної роботи. Ці ресурси є спільними для всіх реєстрів. Серед основних сервісів можна виділити:

Openshift (master та workers)::
Система автоматичного розгортання, масштабування та управління застосунками у контейнерах

Ceph::
Підсистема розподіленого зберігання файлів

Logging::
Підсистема журналювання подій

Central Vault::
Підсистема управління секретами Платформи

Minio::
Сховище резервних копій Платформи

Trembita::
Шлюз безпечного обміну (ШБО)

.Орієнтовні системні вимоги до центральних сервісів Платформи
|===
|Сервіс|Тип машин|Кількість машин|Тип диска машини|Розмір диска машини, Gb

|Openshift master
|r5.2xlarge (8 CPU, 64 RAM)
|3
|gp2
|120

|Ceph
|r5.4xlarge (16 CPU, 128 RAM)
|3
|gp2
|1170

|Logging
|m5.2xlarge (8 CPU, 32 RAM)
|3
|gp2
|495

|Workers
|r5.2xlarge (8 CPU, 64 RAM)
|5
|gp2
|250

|Central Vault
|r5.2xlarge (8 CPU, 64 RAM)
|1
|gp2
|160

|Minio
|r5.2xlarge (8 CPU, 64 RAM)
|1
|gp2
|2080

|Trembita
|r5.2xlarge (8 CPU, 64 RAM)
|1
|gp2
|160
|===

[infra-components-cost]
=== Розрахунок вартості центральних сервісів Платформи

Обчислювальна вартість центральних сервісів Платформи відображає кошти, вкладені у ресурси, що підтримують спільні сервіси. Оскільки один такий комплекс сервісів може обслуговувати численні реєстри, його вартість розподіляється пропорційно між ними.

TIP: Більше деталей про те, що входить у вартість, можна знайти в електронній таблиці
xref:attachment$architecture/platform-system-requirements/registry-cost-calculator.xlsx[Розрахунок вартості реєстру] на сторінці _Калькулятор вартості_ _>_ _Орієнтовний розрахунок вартості спільних сервісів_.

== Пов'язані сторінки

* xref:arch:architecture/platform-system-requirements/registry-requirements.adoc[]
