include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

= Розрахунок вартості реєстру

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

Вартість обчислювальних ресурсів реєстру складається з вартості ресурсів які створюються ексклюзивно для реєстру, та частини вартості ресурсів які створені для забезпечення функціонування спільних сервісів.

Один набір спільних сервісів може обслуговувати десятки реєстрів і вартість його роботи розподіляється між цими реєстрами. В категорію спільних сервісів зокрема входять:

* Система автоматичного розгортання, масштабування та управління застосунками у контейнерах Openshift (master and workers)
* Підсистема розподіленого зберігання файлів Ceph
* Підсистема журналювання подій Logging
* Підсистема управління секретами платформи Central Vault
* Сховище резервних копій платформи Minio
* Шлюз безпечного обміну Trembita


== Типові конфігурації

При розгортанні реєстру за типовими шаблонами можна орієнтуватися на наступну вартість обчислювальних ресурсів.

|===
|Шаблон|Кількість ВМ|Сумарна вартість роботи ВМ, $ в міс.|Сумарна вартість диску ВМ, $ в міс.|Сумарна вартість розподіленого сховища, $ в міс.|Сумарна вартість трафіку, $ в міс.|Вартість спільних сервісів, $ в міс.|Підсумкова вартість, $ в міс.

|Мінімальний|2|220.8|22.85|19.04|49.50|258.52|*570.71*
|Рекомендований|5|552.00|57.12|19.04|49.50|646.30|*1323.96*
|Великий|10|1104.00|114.24|19.04|49.50|1292.61|*2579.39*
|===

Ціни дані за тарифами платформи хмарних обчислень Amazon Web Services на кінець 2022 р., за умови режиму роботи 12 годин на добу протягом робочого тижня.

Більше деталей про те що входить у вартість можна знайти в електронній таблиці xref:attachment$/architecture/registry_cost_calculator.xlsx[розрахунок вартості реєстру] на сторінці _Калькулятор вартості_. 

== Калькулятор вартості

Для оцінки вартості ресурсів необхідних для роботи реєстру, який відповідає заданим вимогам, можна скористатися наступним калькулятором:

xref:attachment$/architecture/platform-system-requirements/registry_cost_calculator.xlsx[Розрахунок вартості реєстру - Excel]

На сторінці _Вибір розміру реєстру_ в рядку _Ваш реєстр_ можна побачити результати розрахунку, а нижче, під результатом, вибір параметрів реєстру. 

=== Результати

Кількість ВМ:: Розрахована кількість віртуальних машин необхідна для роботи реєстру який відповідає заданим нижче параметрам.
Вартість:: Розрахована місячна вартість роботи за цінами платформи хмарних обчислень Amazon Web Services. Складається з вартості віртуальних машин необхідних для роботи реєстру та вартості користування спільними сервісами платформи реєстрів.

=== Вхідні параметри
==== Базові параметри

Режим високої доступності:: Резервування додаткових екземплярів компонентів реєстру та потужностей для автоматичного горизонтального масштабування. 
Режим роботи:: Час коли реєстр працює.

==== Об'єм реєстру
Кількість бізнес сутностей:: Кількість таблиць в моделі даних реєстру
Максимальна кількість екземплярів бізнес сутностей (рядків в таблиці):: Кількість рядків у найбільшій таблиці реєстру.
Приблизний об'єм історичних даних в GB:: Об'єм даних що завантажуються в реєстр перед початком промислової експлуатації (первинне завантаження). 

==== Параметри реєстру
Наступні параметри задаються окремо для кожної з трьох категорій користувачів - посадові особи, громадяни, інші системи.

Кількість користувачів:: Кількість зареєстрованих користувачів які можуть користуватися реєстром.
Кількість послуг (бізнес-процесів):: Кількість послуг які може надавати реєстр різним категоріям користувачів.
Середня кількість задач для користувачів на послугу:: Середня кількість задач які потребують введення від користувача. 
Середня кількість автоматизованих задач на послугу:: Середня кількість задач які не потребують введення від користувача.
Кількість звітів:: Загальна кількість змодельованих звітів, що використовуються посадовими особами.
Кількість витягів:: Загальна кількість змодельованих витягів.
Кількість надаваних послуг в місяць:: Загальна кількість всіх типів послуг надаваних протягом місяця.
