= Системні вимоги до екземпляра реєстру
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Системні вимоги

Розрахунок системних вимог до конкретного реєстру є ключовим аспектом планування його інфраструктури та ресурсів. Різні реєстри можуть мати відмінності через обсяг даних, кількість користувачів, структуру даних та інші параметри, що зумовлюють їхні специфічні системні потреби.

На цій сторінці представлені рекомендації та параметри для різних конфігурацій реєстру. Параметр *`1 VM calculation reference`* визначає референтне значення для однієї віртуальної машини (ВМ). За його основою ми пропонуємо три основні конфігурації шаблонів розгортання:

minimal ::
Ця конфігурація призначена для реєстрів із невеликим обсягом даних та користувачів.
Вона оптимально підходить для пілотних проєктів, тестування або реєстрів, які знаходяться на ранніх стадіях впровадження.
Хоча така конфігурація має обмежені ресурси, вона все ще забезпечує надійність і базову продуктивність.

recommended ::
Ця конфігурація рекомендована для більшості реєстрів, які функціонують у середньому та високому режимах навантаження.
Вона добре збалансована між ресурсами, продуктивністю та вартістю, тому підходить для реєстрів, які обслуговують середню кількість користувачів та мають помірний обсяг даних.

large::
Конфігурація для великих реєстрів зі значним обсягом даних та високим навантаженням.
Вона призначена для реєстрів, які обслуговують велику кількість користувачів, мають багато складних бізнес-процесів та вимагають високої продуктивності.
Ця конфігурація забезпечує максимальну продуктивність та гнучкість, але вимагає більше ресурсів і коштів.

Кожна з таких конфігурацій має свої системні характеристики, такі як _тип машини (CPU, RAM)_, _розмір диска_, _тип диска_, розмір сховища файлової системи, очікуваний об'єм трафіку тощо.

.Орієнтовні системні вимоги до одного екземпляра реєстру
|===
|Шаблон|Тип машин|Кількість машин|Тип диску машини|Розмір диска машини, Gb|Тип диска Ceph|Розмір сховища в Ceph, Gb|Очікуваний об'єм трафіку в місяць, Gb

|1 VM calculation reference

|m5.2xlarge (8 CPU, 32 RAM)
|1
|gp3
|120
|gp3
|200
|550

|minimal
|m5.2xlarge (8 CPU, 32 RAM)
|2
|gp3
|120
|gp3
|200
|550

|recommended
|m5.2xlarge (8 CPU, 32 RAM)
|5
|gp3
|120
|gp3
|200
|550

|large
|m5.2xlarge (8 CPU, 32 RAM)
|10
|gp3
|120
|gp3
|200
|550
|===

== Розрахунок вартості реєстру

Вартість обчислювальних ресурсів реєстру складається з вартості ресурсів які створюються ексклюзивно для реєстру, та частини вартості ресурсів які створені для забезпечення функціонування спільних сервісів.

Один набір спільних сервісів може обслуговувати десятки реєстрів і вартість його роботи розподіляється між цими реєстрами (_див. детальніше на сторінці xref:arch:architecture/platform-system-requirements/platform-requirements.adoc[]_).

=== Типові конфігурації

При розгортанні реєстру за типовими шаблонами можна орієнтуватися на наступну вартість обчислювальних ресурсів.

|===
|Шаблон|Кількість ВМ|Сумарна вартість роботи ВМ, $ в міс.|Сумарна вартість диску ВМ, $ в міс.|Сумарна вартість розподіленого сховища, $ в міс.|Сумарна вартість трафіку, $ в міс.|Вартість спільних сервісів, $ в міс.|Підсумкова вартість, $ в міс.

|Мінімальний|2|220.8|22.85|19.04|49.50|258.52|*570.71*
|Рекомендований|5|552.00|57.12|19.04|49.50|646.30|*1323.96*
|Великий|10|1104.00|114.24|19.04|49.50|1292.61|*2579.39*
|===

NOTE: Ціни подано за тарифами платформи хмарних обчислень Amazon Web Services на кінець 2022 р., за умови режиму роботи 12 годин на добу протягом робочого тижня.

TIP: Більше деталей про те, що входить у вартість, можна знайти в електронній таблиці
xref:attachment$architecture/platform-system-requirements/registry-cost-calculator.xlsx[Розрахунок вартості реєстру] на сторінці _Калькулятор вартості_.

=== Калькулятор вартості

Для оцінки вартості ресурсів необхідних для роботи реєстру, який відповідає заданим вимогам, можна скористатися наступним калькулятором:

* xref:attachment$architecture/platform-system-requirements/registry-cost-calculator.xlsx[Розрахунок вартості реєстру]

На сторінці _Вибір розміру реєстру_ в рядку _Ваш реєстр_ можна побачити результати розрахунку, а нижче, під результатом, вибір параметрів реєстру. 

==== Результати

Кількість ВМ:: Розрахована кількість віртуальних машин, необхідна для роботи реєстру, який відповідає заданим нижче параметрам.
Вартість:: Розрахована місячна вартість роботи за цінами платформи хмарних обчислень Amazon Web Services. Складається з вартості віртуальних машин необхідних для роботи реєстру та вартості користування спільними сервісами Платформи реєстрів.

==== Вхідні параметри
===== Базові параметри

Режим високої доступності:: Резервування додаткових екземплярів компонентів реєстру та потужностей для автоматичного горизонтального масштабування. 
Режим роботи:: Час, коли реєстр працює.

===== Об'єм реєстру
Кількість бізнес сутностей:: Кількість таблиць в моделі даних реєстру
Максимальна кількість екземплярів бізнес сутностей (рядків в таблиці):: Кількість рядків у найбільшій таблиці реєстру.
Приблизний об'єм історичних даних в GB:: Об'єм даних що завантажуються в реєстр перед початком промислової експлуатації (первинне завантаження). 

===== Параметри реєстру
Наступні параметри задаються окремо для кожної з трьох категорій користувачів: _посадові особи/надавачі послуг_, _громадяни/отримувачі послуг_, _інші системи_.

Кількість користувачів:: Кількість зареєстрованих користувачів, які можуть користуватися реєстром.
Кількість послуг (бізнес-процесів):: Кількість послуг, які може надавати реєстр різним категоріям користувачів.
Середня кількість задач для користувачів на послугу:: Середня кількість задач, які потребують введення від користувача.
Середня кількість автоматизованих задач на послугу:: Середня кількість задач, які не потребують введення від користувача.
Кількість звітів:: Загальна кількість змодельованих звітів, що використовуються посадовими особами.
Кількість витягів:: Загальна кількість змодельованих витягів.
Кількість надаваних послуг в місяць:: Загальна кількість всіх типів послуг надаваних протягом місяця.

== Пов'язані сторінки

Ознайомтеся з цими ресурсами для отримання додаткової інформації та поглиблення вашого розуміння:

* xref:arch:architecture/platform-system-requirements/platform-requirements.adoc[]
* xref:admin:registry-management/control-plane-create-registry.adoc#vm-params[Розгортання реєстру: параметри віртуальних машин]
* xref:admin:registry-management/control-plane-registry-resources.adoc[]



