:toc-title: ЗМІСТ
:toc: auto
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Пояснення до заповнення файлу «Users_Upload»

*Для автоматичного завантаження користувачів до системи управління користувачами:*

. Завантажте шаблон CSV-файлу Users_Upload.csv за посиланням на екрані.
. Відкрийте завантажений файл та заповніть колонки шаблону своїми значеннями згідно з поясненнями, поданими нижче. Заповнені поля не повинні мати додаткових пробілів на початку та в кінці значення. CSV-роздільник між колонками – крапка з комою.
. Завантажте заповнений файл на сторінку Кабінету адміністратора регламентів та натисніть кнопку підтвердження. Зачекайте декілька хвилин до повного завантаження користувачів реєстру. Результат можна переглянути в технічних логах за посиланням на екрані.

*Пояснення до заповнення файлу "Users_Upload", для мінімізації помилок:*

[WARNING]
====
При заповненні колонок drfo, edrpou і fullName потрібно обов'язково використовувати дані, що вказані в кваліфікаційному електронному підписі (КЕП) юридичної особи, яку представлятиме посадова особа.
====

.	`*drfo*` – особистий реєстраційний номер облікової картки платника податків (РНОКПП). Код РНОКПП містить 10 цифр. Якщо через релігійні переконання особа не отримувала РНОКПП, необхідно вказати серію та номер паспорта або номер ID-картки. При внесенні серії та номера паспорта необхідно звернути увагу, як саме ці дані записані у КЕП з точністю до символу (з пробілом чи без). *Поле обов'язкове до заповнення.*
+
Для перевірки даних у КЕП можна скористатися порталом Дія: https://id.diia.gov.ua/. Виконайте вхід та оберіть спосіб авторизації _Файловий ключ_ або _Апаратний ключ_, залежно від вашого носія. У правому верхньому куті сторінки відкрийте меню *«Мій профіль»*. У блоці *«Персональні дані»* ви побачите інформацію про свій КЕП.

.	`*edrpou*` – унікальний ідентифікаційний номер юридичної особи в Єдиному державному реєстрі підприємств та організацій України. Ідентифікаційні коди ЄДРПОУ містять 8 цифр. Якщо перша цифра в ЄДРПОУ – нуль, то спочатку обов'язково потрібно змінити формат клітинки на *_Текстовий_* (натисність правою клавішею на поле та оберіть *_«Формат клітинок»_*) і після цього ввести значення. *Поле обов'язкове до заповнення.*

. `*fullName*` – прізвище, ім'я, по батькові (за наявності). Має містити більше 3-х, але не менше 2-х слів. ПІБ повинне мати 100% співпадіння із даними у КЕП з точністю до символу. *Поле обов'язкове до заповнення.*
+
[CAUTION]
====
У разі невідповідності значень атрибутів до значень, вказаних у КЕП, користувач не матиме можливості увійти до Кабінету посадової особи та підписувати задачі КЕП.
====
<<<
+
. `*Realm Roles*` – перелік системних та регламентних (за наявності) ролей користувача. *Для Кабінету посадової особи обов'язквою є одна системна роль  –* `*officer*`. Якщо посадова особа має додатково визначені регламентні ролі, вони вносяться через кому після значення `*officer*`. Управління регламентними ролями здійснює Адміністратор реєстру, інформацію про те, чи передбачені у конкретному реєстрі регламентні ролі, і які саме, можна дізнатися у нього.
+
[WARNING]
====
За відсутності системної ролі, користувач не матиме доступу до Кабінету посадової особи.

* Системна роль *`officer`* створюється Платформою під час розгортання реєстру або встановлення Платформи.
* Регламентні ролі створюються під час розгортання реєстру та налаштовуються у регламенті реєстру → директорія _roles_ → у відповідному конфігураційному файлі _*.yml_.
====

+
.	`*KATOTTG*` – перелік кодів з Кодифікатора адміністративно-територіальних одиниць та територій територіальних громад.
+
[NOTE]
====
Поле обов'язкове для реєстрів, які використовують рольову модель за територіальною ознакою, для інших реєстрів необов'язкове.
====
+
Значення складається із літер «UA», за якими слідують 17 цифр. Якщо користувач матиме доступ до декількох територіальних одиниць, їх коди вносяться через кому. Максимально можлива кількість значень для одного користувача – 16. Користувач Кабінету посадової особи матиме доступ до записів саме тієї області/району/територіальної громади тощо, код якої буде вказано.
+
У випадку надання користувачу доступу до записів всієї України в значенні KATOTTG потрібно вказати тільки два символи – *UA*.
+
Для визначення коду KATOTTG потрібно скористатись найактуальнішим файлом «Кодифікатор» за link:https://www.minregion.gov.ua/napryamki-diyalnosti/rozvytok-mistsevoho-samovryaduvannya/administratyvno/kodyfikator-administratyvno-terytorialnyh-odynycz-ta-terytorij-terytorialnyh-gromad/[посиланням].  Код адміністративно-територіальної одиниці слід обирати з тієї колонки файлу, на рівні якої посадовій особі буде надано права доступу.
+
Перелік можливих значень в колонці «Категорія об'єкта» файлу Кодифікатор:
+
|===
|*_Рівень_*|*_Значення_*
|Перший рівень|«O» – Автономна Республіка Крим, області

«K» – міста, що мають спеціальний статус
|Другий рівень|«P» – райони в областях та Автономній Республіці Крим
|Третій рівень|«H» – території територіальних громад (назви територіальних громад) в областях, територіальні громади Автономної Республіки Крим
|Четвертий рівень|«M» – міста

«T» – селища міського типу

«C» – села

«X» – селища
|Додатковий рівень|«B» – райони в містах
|===
+
ПРИКЛАД 1: ::
Вам необхідно надати доступ користувачу до Кабінету посадової особи на рівні Миргородської територіальної громади (Третій рівень) Полтавської області. Для цього:
•	в колонці «Категорія об'єкта» виберіть значення «Н»;
•	в колонці «Назва об'єкта» введіть в пошуку назву територіальної громади «Миргородська»;
•	скопіюйте з колонки «Третій рівень» код значення територіальної одиниці (UA53060230000098362).
+
У деяких випадках пошук з Прикладу 1 видасть вам декілька однакових значень (якщо на території України існує більше, ніж одна територіальна одиниця на одному рівні з тією самою назвою). В цьому разі використовуйте пошук, описаний у Прикладі 2.

+
ПРИКЛАД 2: ::
Вам необхідно надати доступ користувачу до Кабінету посадової особи на рівні Шевченківського району м.Полтава (Додатковий рівень). Для цього:
• спочатку в колонці «Категорія об'єкта» виберіть значення «О»;
• в колонці «Назва об'єкта» введіть в пошуку назву області «Полтавська»;
• скопіюйте з колонки «Перший рівень» код значення області (UA53000000000028050);
• за допомогою фільтра залиште лише ті значення, які в колонці  «Перший рівень» містять значення UA53000000000028050;
• в колонці «Категорія об'єкта» виберіть значення «В»;
• в колонці «Назва об'єкта» введіть в пошуку назву району «Шевченківський»;
• скопіюйте з колонки «Додатковий рівень» код значення територіальної одиниці (UA53080370010339303).

<<<

Приклад заповнення файлу: ::
|===
|*drfo*|*edrpou*|*fullName*|*Realm Roles*|*KATOTTG*
|1010101018|34554362|Сидоренко Василь Леонідович|officer|UA32000000000030281
|3030303033|33333333|Степанченко Степан Степанович|officer|UA32020000000057002
|СО 522654|20559371|Алмаз-заде Гайяне Мухамедівна|officer, head-officer `*`|UA32020050000062595, UA32020170000020698
|2354689712|20553149|Петру Іон|officer|UA32020050040035161
|===

`*`- приклад регламентної ролі, яка може бути створена в реєстрі додатково до основної системної ролі officer. У кожному реєстрі перелік регламентних ролей налаштовується індивідуально і може відрізнятися.

{empty} +
{empty} +

[TIP]
====
За необхідності після колонки KATOTTG ви можете додати до файлу *`довільні колонки`*. Вони будуть збережені в атрибути користувачів з тією ж назвою та значеннями, з якими ви внесете їх в файл. Наприклад, в csv-файлі ви створили додаткову колонку з назвою *_city_* і заповнили це значення в кожному рядку. В результаті у кожного користувача з'явиться в системі атрибут з назвою *`city`* і значеннями з csv-файлу.

Заборонено включати до значення спеціальні символи ([, ], {, }, \, "), а також значення, які містять понад 200 символів.
Назва кожного додаткового атрибута обов'язково повинна бути однаковою для всіх користувачів реєстру і мати унікальну назву серед інших параметрів.

Приклад заповнення файлу з довільною колонкою `city`: ::
|===
|*drfo*|*edrpou*|*fullName*|*Realm Roles*|*KATOTTG*|*city*
|1010101018|34554362|Сидоренко Василь Леонідович|officer|UA32000000000030281|Київ
|2354689712|20553149|Петру Іон|officer|UA32020050040035161|Дніпро
|===

====