== Опис проблеми
Частиною процесу створення/редагування регламенту реєстру є опис моделі данних реєстру. Поточний підхід передбачає використання лише файлів конфігурації для створення моделі данних реєстру.
Користувач повинен використовувати liquibase changelog формат опису моделі данних, що дефакто є описом структури БД.

Частиною web-based адмін порталу редагування версії регламенту реєстру є редагування структури БД.
 Необхідно розробити технічний дизайн підсистеми створення моделі данних реєстру.

=== Ключові пункти проблеми
- Одночасна робота декількох користувачів з однією версією-кандидатом регламенту
- Збереження механізму забезпечення існуючого жіттєвого циклу регламенту версій (gerrit, jenkins)
- Збереження технічного інструменту відтворення структури БД (liquibase)
- Збереження механізму зміни регламенту шляхом зміни конфігураційних файлів в git
- Забезпечення синхронізації між змінами з адмінпорталу і змінами внесеними через Gerrit
- Створення GUI based механізму зміни регламенту реєстру