== Загальні принципи реалізації
- Механізм дозволяє проводити CRUD операції відносно об'єктів доменної моделі
- Одночасне редагування регламенту реєстру як з використанням адмін порталу так і шляхом зміни конфігураційних файлів в репозиторії регламенту
- Стан структури БД і метаданних повністю відображений DataModelSnapshot документом
- DataModelSnapshot json структура описана за допомогою JSONSchema
- DataModelSnapshot document (з JSONSchema) має бути використаний як структура обміну даними на рвіні RestAPI між Front-End додатком та Backend сервісами
- Вирішення конфліктів при редагуванні регламенту реєстру з використанням адмінпорталу необхідний лише на рівні DataModelSnapshot документу
- Підтримання консистентними DataModelSnapshot та liquibase changelog
- Процес синхронізації DataModelSnapshot по liquibase changelog є ідемпотентним
- Зміни внесені через адмінністративний портал знаходяться в окремому liquibase changeset. Ідентифікатор версії-кандидату є частиною liquibase changeset id атрибуту.

