= Управління структурами таблиць моделі даних реєстру

include::admin-portal-data-model-problem-description.adoc[]

include::admin-portal-data-model-scenarious.adoc[]

== Out of scope
- Робота з типами данних
- Робота з аналітичними представленнями
- Вирішення конфліктів з використанням адмінінстративного порталу менеджменту регламенту реєстру

== Принципи роботи зі змінами в БД

== Існуючий механізм роботи зі змінами в БД

Існуючий механізм роботи зі змінами в БД базуєтсья на двух принципах:

- Cтворення liquibase changeset
- Збереження liquibase changeset в git

image::lowcode/admin-portal/data-model/tables-management-luqibase-current-flow.svg[]

== Розширений механізм роботи зі змінами в БД
Пропонується розширити існуючий механізм роботи зі змінами БД шляхом додавання DataModelSnapshot документу в git репозиторій, котрий буде відображати стан моделі данних.

image::lowcode/admin-portal/data-model/tables-management-luqibase-extended-flow.svg[]

== Основні концепції
- DataModelSnapshot Document - документ, що відображає стан моделі данних регламенту реєстру
- Diff Document - документ, що відображає різницю між двома станами моделі данних регламенту реєстру
- History Document - документ, що відображає історію змін мастер версії або версії- кандидату регламенту реєстру

== Описання структури DataModelSnapshot
[NOTE]
Дана модель данних була отримана в результаті аналізу існуючого стану lqiuibase changelogs (включно з аналізом функціональності custom liquibase тегів)

[plantuml, db-tables-management-er, svg]
----
include::partial$lowcode/admin-portal/db-tables-management-er.puml[]
----

=== Опис DataModelSnapshot формату даних
В якості технічного інструменту опису структури даних DataModelSnapshot використовується Json формат. В якості опису контракту документу використовується https://json-schema.org/[JsonSchema]

xref:lowcode/admin-portal/data-model/admin-portal-data-model-json-schema-description.adoc[DataModelSnapshotSchema]

include::domain-model-description.adoc[]
include::domain-attributes-description.adoc[]

include::admin-portal-data-model-principles.adoc[]

== Опис технічного рішення
//=== System context
//image::lowcode/admin-portal/data-model/tables-management-c4-context.svg[]

=== Container
image::lowcode/admin-portal/data-model/tables-management-c4-container.svg[]

=== Admin portal API container
image::lowcode/admin-portal/data-model/tables-management-c4-apiContainer.svg[]

=== CICD container
image::lowcode/admin-portal/data-model/tables-management-c4-cicd-container.svg[]

== Сценарій взаємодії компонентів сістеми під час редагування структури таблиць регламенту реєстру
[plantuml, db-tables-management-sequence, svg]
----
include::partial$lowcode/admin-portal/db-tables-management-sequence.puml[]
----

== Загальна діаграма взаємодії компонентів системи під час редагування моделі даних регламенту реєстру

image::lowcode/admin-portal/data-model/tables-management-component-structure.svg[]
