== Допустимі операції з об'єктами доменної моделі
:hide-uri-scheme:


[]
NOTE: Ніжче наведена інформація базується на існуючому контракті по роботі з моделлю данних регламенту реєстру. В контексті даної проблеми цей контракт є джерелом функціональних можливостей, що мають бути взяті до уваги при розробці технічного дизайну.

Допустимі операції відносно моделі даних реглменту реєстру діляться на 2 групи:

- Обмежена можливість змін моделі данних
- Повна можливість змін моделі данних

IMPORTANT: Об'єкти моделі даних, що не були інтегровані в мастер-версію регламенту реєстру, можуть бути змінені будь-яким чином не зважаючи на нижче вказані обмеження.

Об'єкти моделі даних, що ввійшли в ReleaseSnapshot мають обмежені можливості для редагування. Таблиці, що були створені в CandidateSnapshot не мають ніяких обмежень відносно можливостей редагування.

=== Допустимі операції з об'єктами доменної моделі, що ввійшли в попередній реліз

|===
|Назва entity|Create| Update| Delete

|Table|Y|Y|N
|Column|Y|Y|N
|Index|Y|Y|Y
|Constraint|Y|Y|Y
|ForeignKey|Y|Y|Y
|AccessRule|Y|Y|Y|
|===
