@startuml
participant "Web Клієнт" as client  order 10
participant "Сервіс управління задачами" as service  order 20
participant "Cервіс виконання бізнес-процесів" as bpms order 30
participant "Ceph сховище" as ceph order 40
skinparam responseMessageBelowArrow true

title Виконати задачу користувача
  client -> service: Виконати задачу за ідентифікатором задачі,\nз даними форми, та JWT токеном
  activate service
  service -> bpms: Отримати задачу користувача за ідентифікатором
  activate bpms
  bpms -> service: Задача користувача, 200 OK
  deactivate bpms
  service -> service: Отримати username користувача з токену
  service -> service: Порівняти assignee задачі та username з токену
  alt Користувач не призначений\n на виконання задачі
    service -> client: Помилка клієнта, 400 Bad Request
  end
  service -> service: Зформувати ceph ключ на базі id задачі та id бізнес процесу
  service -> ceph: Зберегти дані форми користувача за ключем
  activate ceph
  ceph -> service: Дані форми користувача збережені, 200 OK
  deactivate ceph
   service -> bpms: Виконати задачу за ідентифікатором
  activate bpms
    bpms -> bpms: Виконання логіки регламента
    bpms -> service: Задача виконана, 204 No content
  deactivate bpms
  service -> client: Задача виконана, 204 No content
  deactivate service
@enduml