@startuml
participant "Web Клієнт" as client  order 10
participant "Сервіс управління задачами" as service  order 20
participant "КЕП сервіс" as digital_ops  order 30
participant "Cервіс виконання бізнес-процесів" as bpms order 40
participant "Ceph сховище" as ceph order 50
skinparam responseMessageBelowArrow true

title Виконати задачу людини
    client -> service: Виконати задачу за ідентифікатором задачі,\nпідписом, даними форми, та JWT токеном
    activate service
      group Отримати пакет валідації КЕП із властивостей розширення
        service -> bpms : Отримати властивості розширення користувацької задачі
        activate bpms
          service <-- bpms : Властивості розширення
          deactivate bpms
        service -> service : Отримати пакет валідації КЕП із властивостей розширення
        note left
          Якщо у властивостях розширення немає визначеного пакету валідації -
          використовувати пакет для **фізичних осіб** за замовчуванням
        end note
      end
      service -> digital_ops: Перевірити підпис:\nдані форми, підпис, JWT токен
      activate digital_ops
        digital_ops -> digital_ops: Перевірка цифрового підпису\nкористувача системи та даних
        alt Помилка валідації
            service <-- digital_ops: Дані не валідні, 400 Bad request
            client <-- service: Помилка валідації, 422 Unprocessable Entity
        end
        digital_ops -> service: Валідація успішна, 200 OK
      deactivate digital_ops
      service -> bpms: Отримати задачу користувача за ідентифікатором
      activate bpms
        bpms -> service: Задача користувача, 200 OK
      deactivate bpms
      service -> service: Отримати username користувача з токену
      service -> service: Порівняти assignee задачі та username з токену
      alt Користувач не призначений\n на виконання задачі
        service -> client: Помилка авторизації, 403 Forbidden
      end
      service -> service: Зформувати ceph ключ на базі id задачі та id бізнес процесу
      service -> ceph: Зберегти дані форми користувача за ключем
      activate ceph
        ceph -> service: Дані форми користувача збережені, 200 OK
      deactivate ceph
      service -> bpms: Виконати задачу за ідентифікатором
      activate bpms
        bpms -> bpms: Виконання логіки регламента
        bpms -> service: Задача виконана, 204 OK
      deactivate bpms
      service -> client: Задача виконана, 204 OK
    deactivate service
@enduml