= Pessimistic locks

Даний підхід передбачає заборону (отримання _lock_) на зміну файлів в окремій директорії, якщо наразі інший користувач редагує будь-яку сутність в даній директорії.

image::architecture-workspace/research/admin-portal/gitflow/git-pessimistic-lock.svg[]

[NOTE]
Адміністратори реєстру не взаємодіють з файловою системою як такою. Всі зміни відбуваються шляхом взаємодії з `admin-portal backend service` через RestAPI.

[NOTE]
Технічна реалізація lock для файлів на файловій системі не розглядається в рамках даного документу


Користувач, що намагається провести редагування файлу, що знаходиться в області дії _lock_, буде отримувати помилку відповідне повідомлення від _backend_ сервісу і має чекати доки попередній користувач закінчить роботу за файлами в області дії _lock_.

[TIP]
Область lock може бути технічно зменшена до окремих файлів на файловій системі.

== Pros
- Не потребує кардинальної зміни існуючого механізму взаємодії з _git repositories_

== Cons
- Потребує інтеграції з додатковим компонентом для збереження інформації про _locks_ або розробки окремого контракту та механізму як зберігати дану інформацію на файловій системі (use transaction manager over Filesystem)
- Потребує розробки механізму єдиного `lock registry` для декількох екземплярів `admin-portal backend service`