:toc-title: On this page:
:toc: auto
:toclevels: 5
:experimental:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

//= Керування розкладом та часом зберігання резервних копій реєстру
= Manage the schedule and storage time of registry backups

//== Загальний опис
== General description
////
В поточній версії Платформи реєстрів не передбачено процесу керування налаштуваннями підсистеми бекапування реєстрів.
Для впровадження такої функціональності пропонується поліпшення інтерфейсу адмін-консолі, використовуючи яку адміністратор
реєстру може налаштовувати розклад та час зберігання резервних копій реєстру.
////
In the current version of the Registry Platform, there is no process for managing the settings of the registry backup subsystem.
To implement such functionality, it is proposed to improve the admin console interface, which the administrator uses
the registry can configure the schedule and time to store registry backups.

//== Ролі користувачів
== User roles

//* Технічний адміністратор реєстру
* Registry administrator
////
== Функціональні сценарії
* Введення розкладу резервного копіювання через адмін-консоль
* Налаштування часу зберігання резервних копій через адмін-консоль
////

== Functional scenarios
* Entering the backup schedule through the admin console
* Setting the storage time of backup copies through the admin console

////
== Загальні принципи та положення
* Введення розкладу резервного копіювання в unix-cron форматі задається адміністратором
* Налаштування часу зберігання резервних копій вказується в днях адміністратором та встановлюється в годинах для системи бекапування
* Налаштування розкладу резервного копіювання та часу зберігання резервних копій не є обовʼязковим при створенні реєстру
* При закінченні строку зберігання система бекапування видаляє застарілі резервні копії
* Введений розклад повинен відповідати unix-cron формату та валідуватись адмін-консоллю
* Час зберігання резервних копій повинен бути більше або дорівнювати одиниці, бути цілим числом та не містити спеціальних символів
* Автоматичне створення резервних копій можна вимкнути або ввімнути за допомогою перемикача
* При введені розкладу резервного копіювання адмін-консоль повинна показати коли відбудуться наступні три запуски резервного копіювання
* При оновленні реєстру на нову версію, налаштування розкладу резервних копій та часу зберігання резервних копій повинно залишитись незмінним
* За замовчуванням налаштування автоматичних резервних копій вимкнено для нових реєстрів
* Адмін-консоль повинна показувати дату останньої успішної резервної копії та термін її видалення
* За замовчуванням тайм-зона `Europe/Kiev` встановлюється у `values.yaml` та на рівні поди з Jenkins, як змінна середовища
* При вимкнені резервного копіювання існуючі резервні копії не видаляються
* Адмін-консоль повинна відображати заданий часовий пояс в `values.yaml` при налаштуванні розкладу резервного копіювання.
////

== General principles and provisions
* Entry of the backup schedule in unix-cron format is set by the administrator
* Backup storage time settings are specified in days by the administrator and set in hours for the backup system
* Setting the backup schedule and backup storage time is optional when creating the registry
* When the storage period expires, the backup system deletes outdated backup copies
* The entered schedule must correspond to the unix-cron format and be validated by the admin console
* Backup storage time must be greater than or equal to one, be an integer, and contain no special characters
* Automatic backups can be turned off or on with a switch
* When entering a backup schedule, the admin console should show when the next three backup runs will take place
* When updating the registry to a new version, the backup schedule and backup storage time settings should remain unchanged
* By default, the automatic backups setting is disabled for new registries
* The admin console should show the date of the last successful backup and the date of its deletion
* By default, the time zone `Europe/Kiev` is set in `values.yaml` and at the pod level with Jenkins, as an environment variable
* When backup is disabled, existing backups are not deleted
* The admin console should reflect the specified time zone in `values.yaml` when configuring the backup schedule.

////
== Поточний технічний дизайн
В поточній версії платформи резервне копіювання реєстрів доступне тільки при ручному запуску відповідної джоби.
Налаштування часу зберігання резервних копій не передбачено.
////

== Current technical design
In the current version of the platform, registry backup is available only when the corresponding job is manually launched.
Setting the storage time of backup copies is not provided.

////
== Технічний дизайн рішення
На даній діаграмі зображено залучені для реалізації вимог сервіси та взаємодію між ними.
Додатково зображено важливі особливості, які необхідно брати до уваги в рамках реалізації.
////

== Technical solution design
This diagram shows the services involved in fulfilling the requirements and the interaction between them.
In addition, important features that must be taken into account in the framework of implementation are depicted.

image::architecture/platform/administrative/control-plane/backup-schedule/backup-schedule.svg[remote-file-transfer,700]

//Розклад резервних копій та час зберігання резервних копій передаються в values.yaml
The backup schedule and backup retention time are passed in values.yaml
[source, yaml]
----
global:
  timeZone: Europe/Kiev
  .....
  registryBackup:
    enabled: true
    schedule: "30 19 * * *"
    expiresInDays: 3
----
////
та в анотацію `registry-parameters/values` codebase ресурсу реєстру.
Оператор повинен зреагувати на зміну в codebase CR та тригернути job provisioner, який перестворить `Create-registry-backup`
джобу з новими параметрами. Приклад налаштування розкладу в Jenkins:
[source, bash]
////
and in the `registry-parameters/values` codebase annotation of the registry resource.
The operator must react to the change in the CR codebase and trigger the job provisioner, which will recreate `Create-registry-backup`
job with new parameters. An example of configuring a schedule in Jenkins:
[source, bash]
----
30 19 * * *
----

//== Інтерфейс керування
== Management interface

//An example of filling in backup parameters. If the schedule is filled out correctly, then we show the next execution dates.

image::architecture/platform/administrative/control-plane/backup-schedule/schedule-2.svg[]

//.Розгорніть, щоб побачити більше мокапів
.Expand to see more mockups
[%collapsible%]
====
//* Початковий стан. Резервне копіювання вимкнено:
* Initial state. Backup is disabled:
+
image::architecture/platform/administrative/control-plane/backup-schedule/schedule-1.svg[]

//* Попередні резервні копії існують в системі. Виводимо дату створення копії та кількість днів до її видалення:
* Previous backups exist in the system. We output the date of creation of the copy and the number of days until its deletion:
+
image::architecture/platform/administrative/control-plane/backup-schedule/schedule-3.svg[]

====

//== Високорівневий план розробки
== High-level development plan

//=== Технічні експертизи
=== Technical examinations

* _BE / DevOps_

////
=== План розробки
* Розширення функционалу codebase оператора тригером jenkins job provisioner після оновлення codebase CR
* Розширення UI функціоналу адмін-консолі по введенню / збереженню налаштувань розкладу резервних копій та часу їх зберігання
* Розробка groovy-функцій в jenkins job provisioner по оновленню параметрів в `Create-registry-backup` job.
////

=== Development plan
* Extending the functionality of the codebase operator with a jenkins job provisioner trigger after updating the CR codebase
* Extension of the UI functionality of the admin console for entering / saving backup schedule settings and their storage time
* Development of groovy functions in jenkins job provisioner for updating parameters in `Create-registry-backup` job.

////
== Міграція даних при оновленні реєстру
* Під час оновлення реєстру на нову версію налаштування розкладу бекапів поточні налаштування повинні залишитись незмінними.
* Необхідно передбачити можливість вимкнення автоматичного бекапування реєстра.
////

== Data migration when updating the registry
* When updating the registry to a new version of the backup schedule settings, the current settings should remain unchanged.
* It is necessary to provide for the possibility of disabling automatic backup of the registry.

//== Безпека
== Security

//=== Бізнес Дані
=== Business Data
////
|===
|Категорія Даних|Опис|Конфіденційність|Цілісність|Доступність
|Технічні дані що містять відкриту інформацію | Налаштування системи, конфіги, параметри з не конфіденційними значеннями але зміна яких може негативно вплинути на атрибути системи |Відсутня|Висока|Висока
|===
////
|===
|Data category|Description|Privacy|Integrity|Accessibility
|Technical data containing open information | System settings, configs, parameters with non-confidential values, but changing which can negatively affect system attributes |Absent|High|High
|===

=== Спрощена модель загроз

image::architecture/platform/administrative/control-plane/backup-schedule/schedule_TM.svg[]

//=== Механізми протидії ризикам безпеки та відповідність вимогам безпеки
=== Security risk mitigation mechanisms and security compliance

////

|===
| Ризик | Засоби контролю безпеки | Реалізація | Пріорітет 
| Віддалене виконання команди (RCE). Значення expiresInDays без санітізації комітається в геріт з інтерфейсу адмін консолі. Під час запуску процедури резервного копіювання значення передається в скрипт backup-registry.sh як аргумент знову без санітізації що дає змогу виконати будь-яку системну команду на провіженері
a|
- Реалізувати механізм позитивної валідації для форми "Розклад" на фронтенді
- Реалізувати механізм позитивної валідації для даних з форми "Розклад" на бекенді
- Реалізувати механзм строгої типізації та валідації для даних expiresInDays на фронтенді
- Реалізувати механзм строгої типізації та валідації для даних з форми expiresInDays на бекенді
- Реалізувати механізм санітізації аргументів в скрипті backup-registry.sh
| Частково враховано в початковому дизайні. Залишилось реалізувати механізм санітізації аргументів в скрипті backup-registry.sh | Критичний

| Відмова в обслуговуванні через вичерпання обчислювальних ресурсів (DOS) шляхом задання розкладу виконання резервного копіювання кожну хвилину
a|
- Розробити обмеження для розкладу виконання резервного копіювання як мінімум один раз на годину.
| Не враховано в початковому дизайні | Високий

| Ризик втрати даних при занадто малому терміну зберігання резервних копій
a|
- Розробити мінімальний ліміт для терміну зберігання резервних копій рівний 7 дням.
| Не враховано в початковому дизайні | Високий

| Ризик втрати даних при відсутності увімкненого резервного копіювання за замовчуванням. (Secure by default)
a|
- Розробити розклад виконання резервного копіювання та терміну зберігання за замовчуванням та використовувати його для нових реєстрів.
| Не враховано в початковому дизайні | Високий

| Відмова від авторства. Відсутність аудит логу і інформації хто займався конфігурацією резервного копіювання.
a|
- Цільовий сервіс має логувати усі запити та надсилати їх до централізованої системи логування та моніторингу.
- Переконатись що усі неуспішні запити та помилки при виконанні операцій будуть залоговані.
- Система логування має використовувати уніфікований час та часову зону.
- Логи мають бути у уніфікованому форматі та містити усю необхідну інформацію для розслідування інцидентів безпеки.
- Логи не мають містити чутливої інформації або вона повинна бути заплутана (obfuscated) відповідним чином
| Не враховано в початковому дизайні | Середній

| Ризик витоку даних при використання зовнішнього простору домених імен
a|
- Перевести всю внутрішню міжсервісну комунікацю на приватні домені імена.
| Частково враховано в початковому дизайні. Деякі сервіси можуть використовувати зовнішні адреси. Потрібно перевести усі сервіси на комунікацію всередині приватної мережі | Середній

| Вимоги з безпеки: Налаштування мережевих політик безпеки
a|
- Налаштувати мережеві політики таким чином щоб вони відповідали принципу найменших прівілеїв.
| Враховано в початковому дизайні  | Середній

////

|===
| Risk | Security controls | Realization | Priority
| Remote command execution (RCE). The expiresInDays value without sanitization is committed to herit from the admin console interface. When starting the backup procedure, the value is passed to the backup-registry.sh script as an argument, again without sanitization, which allows you to execute any system command on the provisioner
a|
- Implement a positive validation mechanism for the "Schedule" form on the frontend
- Implement a positive validation mechanism for data from the "Schedule" form on the backend
- Implement a strict typing and validation mechanism for expiresInDays data on the frontend
- Implement a mechanism of strict typing and validation for data from the expiresInDays form on the backend
- Implement the argument sanitization mechanism in the backup-registry.sh script
| Partially considered in the initial design. It remains to implement the argument sanitization mechanism in the backup-registry.sh script | Critical

| Refusal of Service (DOS) by scheduling backups to run every minute
a|
- Design a limit for the backup schedule to run at least once an hour.
| Not considered in the initial design | High

|Risk of data loss if the storage period for backup copies is too short
a|
- Develop a minimum limit for the storage period of backup copies equal to 7 days.
| Not considered in the initial design | High

| Risk of data loss if backup is not enabled by default. (Secure by default)
a|
- Develop a default backup and retention schedule and use it for new registries.
| Not considered in the initial design | High

| Disclaimer of authorship. Lack of audit log and information about who was involved in the backup configuration.
a|
- The target service should log all requests and send them to a centralized logging and monitoring system.
- Make sure that all unsuccessful requests and errors during operations will be logged.
- The logging system must use a unified time and time zone.
- Logs must be in a unified format and contain all the necessary information for the investigation of security incidents.
- Logs should not contain sensitive information or it should be obfuscated accordingly
| Not considered in the initial design | Average

| Risk of data leakage when using external domain name space
a|
- Transfer all internal interservice communication to private domain names.
| Partially considered in the initial design. Some services may use external addresses. It is necessary to transfer all services to communication within a private network | Average

| Security requirements: Configuring network security policies
a|
- Configure network policies to conform to the principle of least privilege.
| Considered in the initial design | Average


|===
//== Глосарій та акроніми
== Glossary and acronyms

[cols="3,6"]
|===
|Term|Description

|_СR_
|Custom Resource

|===
