= Business process modelers

include::platform:ROOT:partial$templates/document-attributes/default-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

Business Process (BP) modelers create the "lifeblood" of the _Registry Platform_ -- Business Processes. They are the basis for all the services that the Platform offers to the users. To create Business Processes, BP modelers use visual modelling and managing instruments (**Camunda Modeler**) of a low-code-subsystem via the functionality for the creation of Business Processes, UI-forms, and interactions with other Registries/systems and components. In addition, modeling BP involves using Groovy-scripts and JSON-structures for more complex models. In order to configure integrations with external systems or other Registries within the same Platform instance, API/SOAP-based connectors are used.

You can find more information on BP modeling on the section pages.

== Section Overview

* [*] xref:bp-modeling/bp/index.adoc[]
* [*] xref:bp-modeling/bp/bpmn/index.adoc[]
* [*] xref:bp-modeling/forms/bp-modeling-forms-general-description.adoc[]
* [*] xref:bp-modeling/bp/rest-connector.adoc[]
* [*] xref:bp-modeling/external-integration/api-call/connectors-external-registry.adoc[]

