@startuml
autonumber
skinparam ParticipantPadding 20
title "API Rate Limiting - Authenticated User"

'This is a single line comment

/'
This is a multi-
line comment
'/

actor "Користувач" as User
box "Kong API Gateway"
entity "OIDC plug-in" as oidc
entity "Rate Limiting plug-in" as ratel
end box
participant "Upstream Service" as service

note over User: Cookie: session=xxx
User -> oidc : Запит з ідентифікатором сесії

oidc -> oidc : Перевірка сесії користувача та додавання заголовків

note over oidc
X-Access-Token: aaa
X-ID-Token: bbb
X-Userinfo: ccc  
token-claim: 123
end note

oidc -> ratel : Передача запиту для обробки в наступний плагін
ratel -> ratel : Перевірка ліміту запитів для клієнта \n по ІР адресі або "token-claim" заголовку
alt Ліміту по кількості запитів не досягнуто
ratel -> service: Перенаправлення запиту до upstream сервісу
service --> User : Відповідь сервіса
else Ліміт по кількості запитів вичерпано
ratel --> User: HTTP 429: { "message": "API rate limit exceeded" }
end

@enduml
