= Platform for state registries: requirements for OKD clusters
include::platform:ROOT:partial$templates/document-attributes/default-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

*_OKD_* refers to the Kubernetes community distribution developed under Red Hat's guidance. It's an open project that provides a platform for deploying, managing, and scaling containerized applications. More information can be found on the official website https://www.okd.io/[OKD] and in the https://www.okd.io/docs/[documentation].

Deploying the Platform for state registries into production requires officially supported virtual infrastructures. At present, these infrastructures include recognized cloud services like https://aws.amazon.com/[Amazon Web Services (AWS)], https://azure.microsoft.com/[Microsoft Azure (Azure)], https://cloud.google.com/[Google Cloud Platform (GCP)], and https://www.vmware.com/products/vsphere.html[VMWare vSphere].

These infrastructures should have an OKD cluster installed to ensure optimal compatibility and functionality. The version of this cluster needs to align with the Platform's specific requirements, as outlined below.

.Platform for state registries: requirements for OKD clusters
[options="header"]
|===
| *Platform version* | *Supported OKD versions*
| `1.9.2` | `4.11`
| `1.9.3` | `4.11`
| `1.9.4` | `4.11`
| `1.9.5` | `4.11`
| `1.9.6` | `4.11`
|===

Follow the official Platform documentation guidelines to carry out the installation and configuration process:

* xref:admin:installation/platform-deployment/platform-deployment-overview.adoc[]
