:toc-title: ЗМІСТ
:toc: auto
:toclevels: 5
:experimental:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Platform for state registries: requirements for OKD clusters

Deploying the Platform for state registries into production requires the use of officially supported virtual infrastructures. At present, these infrastructures include recognized cloud services like https://aws.amazon.com/[Amazon Web Services (AWS)] and https://www.vmware.com/products/vsphere.html[VMWare vSphere].

To ensure optimal compatibility and functionality, these infrastructures should have an OKD cluster installed. The version of this cluster needs to align with the Platform's specific requirements as outlined below.

.Platform for state registries: requirements for OKD clusters
[options="header"]
|===
| *Platform Version* | *Supported OKD Versions*
| `1.9.2` | `4.11`
| `1.9.3` | `4.11`
| `1.9.4` | `4.11`
| `1.9.5` | `4.11`, `4.12`
|===

Follow the guidelines in the official Platform documentation to carry out the process of installation and configuration:

* xref:admin:installation/platform-deployment/platform-deployment-overview.adoc[]
