:sectanchors:
:sectlinks:
= Installing and configuring

include::platform:ROOT:partial$admonitions/language-en.adoc[]

This section covers all the aspects related to the Platform deployment.

In the _Platform for state registries: requirements for OKD clusters_ subsection you can find the description of the supported virtual infrastructures and requirements to the installed OKD cluster depending on the Platform version.

The _Deploying the Platform on target environments_ subsection provides the step-by-step instructions for the Platform deployment in four cloud environments.

The _Configuring internal SMTP server_ subsection gives the required information for configuring the `smtp-server` component used for sending notifications to the Platform users.

In the _Changing the network provider of the OKD 4.x cluster_ subsection, you can learn about the available options for changing the network provider.

== Section overview

* xref:admin:installation/okd-requirements.adoc[Platform for state registries: requirements for OKD clusters]
* xref:admin:installation/platform-deployment/platform-deployment-overview.adoc[Deploying the Platform on target environments]
//** xref:admin:installation/platform-deployment/platform-aws-deployment.adoc[]
//** xref:admin:installation/platform-deployment/platform-vsphere-deployment.adoc[]
* xref:admin:installation/internal-smtp-server-setup.adoc[Configuring internal SMTP server]
* xref:admin:installation/changing-network-provider.adoc[Changing the network provider of the OKD 4.x cluster]