= Інтеграційні розширення до бізнес-процесів
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:sectanchors:
:sectlinks:

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

Цей розділ надає вам інформацію про *Element Templates*, інструменти, які роблять моделювання бізнес-процесів простішим і більш інтуїтивним. Використовуючи ці шаблони, ви легко налаштуєте взаємодію між вашими процесами та API, що забезпечує ефективність у вашій роботі.

== Як це працює

*Element Templates* -- це готові до використання шаблони типових розширень (делегатів), які можна легко впровадити на будь-якій стадії бізнес-процесу. Вони доступні для застосування прямо з xref:registry-admin/admin-portal/overview.adoc[Кабінету адміністратора регламентів], дозволяючи вам швидко налаштувати процеси під конкретні задачі, такі як *User Task* чи *Service Task* тощо.

Кожен шаблон створений так, що містить лише необхідні налаштування для виконання задачі, що забезпечує точність і зручність у використанні.

== Інтеграція та розширення

Шаблони *Element Templates* зберігаються у спеціальній бібліотеці https://github.com/epam/edp-ddm-business-process-modeler-extensions[business-process-modeler-extensions]. Якщо ви користуєтесь сторонніми інструментами для моделювання, такими як Camunda Modeler, ви можете завантажити ці шаблони з нашого відкритого репозиторію та додати їх до вашого проєкту. Повна інструкція доступна на сторінці xref:registry-develop:bp-modeling/bp/element-templates/element-templates-install.adoc[Встановлення типових розширень].

== Переваги використання

*Element Templates* пропонують наступні переваги: ::

* [*] *Ефективність і точність*: вони спрощують інтеграцію з API, одночасно забезпечуючи високу точність у налаштуваннях задач.
* [*] *Стандартизація*: шаблони допомагають у стандартизації процесів створення та виконання бізнес-завдань.
* [*] *Гнучкість та адаптація*: ви можете налаштувати процеси відповідно до ваших унікальних потреб і цілей.


== Огляд секції

[%collapsible]
.*Встановлення типових розширень*
====
* [*] xref:registry-develop:bp-modeling/bp/element-templates/element-templates-install.adoc[]
====

[%collapsible]
.*Каталог типових розширень*
====
* [*] xref:registry-develop:bp-modeling/bp/element-templates/user-task-templates/user-task-overview.adoc[Типові розширення для користувацьких задач (User task templates)]
* [*] xref:bp-modeling/bp/element-templates/service-task-templates/service-task-overview.adoc[Типові розширення для сервісних задач (Service task templates)]
* [*] xref:bp-modeling/bp/element-templates/call-activities/call-activities-overview.adoc[]
* [*] xref:bp-modeling/bp/element-templates/rest-integration-registries/rest-integration-registries-overview.adoc[Типові розширення для інтеграції з іншими реєстрами на Платформі]
====

[%collapsible]
.*Валідація шаблонів типових розширень*
====
* [*] xref:bp-modeling/bp/element-templates/element-templates-validate.adoc[]
====


