= Автоматичне застосування видалення складових регламенту до реєстру

Для більшої частини компонентів регламенту реєстру діє правило що при видаленні елемента із регламенту він видаляється з реєстру при розгортанні регламенту. На даний час ця функціональність не реалізована для шаблонів витягів, форм, бізнес-процесів та бізнес-правил. В цьому документі описано підхід до реалізації функціональності видалення цих складових при розгортанні регламенту.

== Функціональні сценарії
* Розгортання регламенту реєстру

== Ролі користувачів
* Моделювальник
* Адміністратор реєстру

== Загальні положення
* Компоненти регламенту реєстру, які були видалені з регламенту, видаляються з реєстру при розгортанні регламенту.
* Дані породжені цими компонентами, такі як історія виконання бізнес-процесів, згенеровані витяги та ін., зберігаються в системі.

== Технічне рішення

=== Шаблони витягів
При розгортанні регламенту утилітою `report-publisher` додатково повинні виконуватися наступні дії:

* При виклику з аргументом `--excerpts`:
** Видаляти із БД `excerpt` ті шаблони для яких нема відповідних директорій в папці `excerpt` регламенту. 
* При виклику з аргументом `--excerpts-docx` або `-- excerpts-csv`:
** Видаляти із БД `excerpt` ті шаблони для яких нема відповідних файлів в папці `excerpts-docx` чи `excerpts-csv` регламенту. 
** Видаляти із бакету `excerpt-templates` файли шаблонів яких не існує в папці `excerpts-docx` чи `excerpts-csv` регламенту

Інформація про видалення шаблонів повинна журналюватися, тобто потрапляти в лог, і бути доступною до перегляду в jenkins. 

IMPORTANT: Записи генерації витягів та статусу (*excerpt_record*) видаляти не потрібно.

IMPORTANT: Перевірка відсутності залежностей бізнес процесів від видалених шаблонів повинна відбуватися при xref:arch:architecture/registry/administrative/regulation-management/platform-evolution/regulations-integrity/regulations-integrity.adoc[валідації регламенту перед розгортанням].

=== Форми

При розгортанні регламенту, на кроці створення та оновлення форм, із сховища сервісу постачання UI-форм потрібно видаляти форми яких нема в регламенті. 

Для реалізації цього функціоналу має буде створений новий метод API сервісу постачання UI-форм, який буде повертати список ідентифікаторів всіх форм що зберігаються у сховищі сервісу постачання UI-форм.

.OpenAPI Specification (xref:attachment$architecture-workspace/platform-evolution/auto-remove-on-deploy/fsp-getList-swagger.yml[Завантажити])
[%collapsible]
====
swagger::{attachmentsdir}/architecture-workspace/platform-evolution/auto-remove-on-deploy/fsp-getList-swagger.yml[]
====

Використовуючи цей новий API, отримати список форм що встановлені у сервісі та порівняти його із списком в регламенті. Ті форми яких нема в регламенті мають бути видалені за допомогою методу `DELETE /api/forms/{key}` сервісу постачання UI-форм.

Інформація про видалення форм повинна журналюватися, тобто потрапляти в лог, і бути доступною до перегляду в jenkins. 

Згідно з принципом найменших привілеїв, політики авторизації для цього методу мають дозволяти його виклик тільки користувачам admin реалму, зокрема користувачу `jenkins-deployer`.

TIP: Інші методи API цього сервісу, які використовуються тільки підсистемою розгортання регламенту, можуть бути обмежені такою самою політикою. Користувачам citizen та officer реалмів доступним має залишитись тільки метод `GET /api/forms/{key}`, який використовує bpms для отримання форм.

IMPORTANT: Перевірка відсутності залежностей бізнес процесів від видалених форм повинна відбуватися при xref:arch:architecture/registry/administrative/regulation-management/platform-evolution/regulations-integrity/regulations-integrity.adoc[валідації регламенту перед розгортанням].

=== Бізнес-процеси та правила

TBD after POC

// delete process definition with no versions
// delete process definition with many versions
// delete process definition with running instances
// delete process definition with not finished instances

// deactivate process definition with no versions
// deactivate process definition with many versions
// deactivate process definition with running instances
// deactivate process definition with not finished instances

// create process definition with the same name as previously deleted PD

// what happens with
// - instances
// - history 
// - tasks
// - officer portal

// delete rule
// -?

// https://camunda.com/blog/2022/03/qa-the-one-where-you-completely-delete-a-process-definition/

Інформація про видалення бізнес-процесів та правил повинна журналюватися, тобто потрапляти в лог, і бути доступною до перегляду в jenkins. 

IMPORTANT: Перевірка відсутності залежностей бізнес-процесів від видалених бізнес-процесів та правил повинна відбуватися при xref:arch:architecture/registry/administrative/regulation-management/platform-evolution/regulations-integrity/regulations-integrity.adoc[валідації регламенту перед розгортанням].

== Міграція

Впровадження автоматичного видалення компонентів регламенту, які не видалялись раніше, несе певні ризики при постачанні цього функціоналу на промислові оточення. Наприклад:

* При реалізації функціоналу можуть бути не враховані особливості цільового оточення які виникли в результаті ручних змін або інші специфічні властивості реєстру.
* Є шанс що  реєстр в своїй роботі покладається на якісь компоненти які були видалені з регламенту, помилково чи ні, але залишаються встановленими.

Для пом'якшення цих ризиків рекомендується при оновленні реєстру запустити процедуру розгортання регламенту, таким чином щоб спрацювали кроки розгортання форм, витягів, бізнес процесів та правил, та в рамках smoke тесту впевнитися в працездатності реєстру.

== Компоненти системи та їх призначення в рамках дизайну рішення
У даному розділі наведено перелік компонент системи, які задіяні або потребують змін в рамках реалізації дизайну.

|===
|Підсистема|Компонент|Опис змін

.2+|Підсистема розгортання регламенту реєстру
|*registry-regulations-publications-pipelines*
|Видалення моделей бізнес-процесів (_BPMN_), бізнес-правил (_DMN_) та моделей форм реєстру.

|*report-publisher*
|Видалення шаблонів витягів

.2+|Підсистема виконання бізнес-процесів
|*form-schema-provider*
|API отримання списку встановлених форм.

// |*bpms*
// |Видалення моделей бізнес-процесів (_BPMN_) та бізнес-правил (_DMN_) реєстру.
|===

== Високорівневий план розробки
=== Технічні експертизи
* _DevOps_
* _BE_

=== Попередній план розробки
* Додавання логіки видалення шаблонів витягів у report-publisher
* Додавання API отримання списку встановлених форм у form-schema-provider
* Додавання логіки видалення форм у registry-regulations-publications-pipelines
* Додавання логіки видалення моделей бізнес процесів та бізнес-правил в registry-regulations-publications-pipelines

== Поза скоупом

* Валідація цілісності регламенту
