= Використання Redash аналітичної бази даних реєстру

[IMPORTANT]
--
Сторінка технічної документації є баченням майбутньої реалізації, актуальність якого може бути застарілою.
--

== Загальний опис

В цьому перехідному дизайні розглядається налаштування Redash таким чином, щоб він використовував вже наявний в реєстрі
аналітичний Postgres.

== Актори та ролі користувачів
* Технічний адміністратор Платформи
* Технічний адміністратор реєстру

== Функціональні сценарії
Нові функціональні сценарії не додаються.

== Поточна реалізація

Кожен екземпляр сервісу аналітичної звітності реєстру Redash (viewer та admin) створюють собі окремі екземпляри Postgres.
Така поточна реалізація

. Споживає додаткові ресурси віртуальних машин реєстру.
. Несе додаткові витрати з точки зору операційного обслуговування. Для кожного потрібен моніторинг, оновлення, резервне копіювання тощо.
. Наразі ні моніторингу, ні резервного копіювання для цих екземплярів postgres немає, а оновлення якщо й проводяться, то
зі значним запізненням у порівнянні з реєстром аналітичним екземпляром postgres.

Ознайомитись з поточною реалізацією можна на сторінці xref:arch:architecture/registry/operational/reporting/overview.adoc[Підсистема аналітичної звітності реєстру]

== Загальні принципи та положення

* Окремі бази під кожний екземпляр Redash не створюються
* Кожний екземпляр Redash використовує свою відповідну базу в аналітичному екземплярі Postgres реєстру

== Цільовий дизайн

image::architecture-workspace/platform-evolution/reporting.drawio.svg[float="center",align="center"]

== Високорівневий план розробки
=== Технічні експертизи
* _DevOps_

=== Попередній план розробки
. Додати функціонал по створенню баз `redash-viewer` і `redash-admin` в аналітичному екземплярі registry postgres.
. Додати liquibase функціонал по створенню користувача `redash` в аналітичному екземплярі registry postgres.
. У значеннях `redash-chart` ввімкнути зовнішній postgres та задати відповідну URL бази.
. Helm chart Redash підтримує налаштування `externalPostgreSQL`. Ввімкнення `externalPostgreSQL` також вимикає створення окремого екземпляру Postgres для кожного з Redash.
. Перевикористати міграційний скрипт, що був створений для міграції бази даних з Postgres 9.5 на 14, щоб виконати міграцію під час оновлення реєстру.
. Оновити відповідні архітектурні діаграми для відображення нової взаємодії.

=== Підтримка зворотної сумісності
В екземплярах `redash-viewer` і `redash-admin` можуть бути присутні особові налаштування користувачів, тому для підтримки працездатності
необхідно провести міграцію бази вже існуючим скриптом при оновленні реєстру.
