= Підсистема кабінетів користувачів

include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

Підсистема, яка реалізує веб-інтерфейси кабінетів користувачів для отримання та надання адміністративних та інформаційних послуг реєстру, відслідковування статусу їх виконання та отримання інформаційних повідомлень.

== Функції підсистеми

* Логін / Логаут користувача
* Перегляд профілю користувача
* Управління персональними налаштуваннями
* Перегляд доступних послуг
* Ініціювання бізнес-процесів надання або отримання послуги
* Внесення та накладання електронного підпису на дані через UI-форми задач бізнес-процесів
* Перегляд даних реєстру
* Перегляд задач для виконання у черзі
* Перегляд статусу виконання бізнес-процесу послуги
* Перегляд виконаних задач
* Перегляд завершених бізнес-процесів послуг
* Завантаження витягів з реєстру
* Перегляд inbox-повідомлень
* Перехід до веб-інтерфейсу перегляду інформаційних панелей (дашбордів)

== Технічний дизайн підсистеми

На даній діаграмі зображено компоненти, які входять в _Підсистема кабінетів користувачів_ та їх взаємодію з іншими підсистемами в рамках реалізації функціональних сценаріїв.

image::architecture/registry/operational/portals/portals-subsystem-design.svg[float="center",align="center"]

_Підсистема кабінетів користувачів_ складається з двох веб-додатків, побудованих на базі _SPA_-архітектури (_Single-Page-Application_), які взаємодіють з бекенд-сервісами за допомогою _REST API_ через _Підсистему управління зовнішнім трафіком_, що унеможливлює неавторизований доступ до даних реєстру.

У якості веб-сервера для обслуговування клієнтських запитів на отримання статичного контенту використовується _Nginx_.

== Складові підсистеми

|===
|Назва компоненти|Представлення в реєстрі|Походження|Репозиторій|Призначення

|_Кабінет надавача послуг_
|`officer-portal`
|origin
.2+|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/low-code-platform/platform/frontend/applications/common-web-app[gerrit:/mdtu-ddm/low-code-platform/platform/frontend/applications/common-web-app]
|Клієнтський веб-додаток для надання адміністративних та інформаційних послуг посадовою особою

|_Кабінет отримувача послуг_
|`citizen-portal`
|origin
|Клієнтський веб-додаток для отримання адміністративних та інформаційних послуг громадянами
|===

== Технологічний стек

При проектуванні та розробці підсистеми, були використані наступні технології:

* xref:arch:architecture/platform-technologies.adoc#javascript[JavaScript]
* xref:arch:architecture/platform-technologies.adoc#typescript[TypeScript]
* xref:arch:architecture/platform-technologies.adoc#reactjs[ReactJS]
* xref:arch:architecture/platform-technologies.adoc#redux[Redux]
* xref:arch:architecture/platform-technologies.adoc#material-ui[Material UI]
* xref:arch:architecture/platform-technologies.adoc#leaflet[Leaflet]
* xref:arch:architecture/platform-technologies.adoc#formio[Form.IO SDK]
* xref:arch:architecture/platform-technologies.adoc#i18next[i18next]
* xref:arch:architecture/platform-technologies.adoc#nginx[Nginx]

== Атрибути якості підсистеми

=== _Security_

Необхідний рівень безпеки досягається завдяки захисту від основних векторів атаки: санитизація input/output користувачів, використання СORS-токену, автоматизація перевірки бібліотек на вразливість, тощо.

Доступ до внутрішніх сторінок кабінетів дозволено лише для автентифікованих користувачів згідно їх прав доступу. За контроль та розмежування доступу відповідають _Підсистема управління зовнішнім трафіком_ та _Підсистема управління користувачами та ролями_.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/operational/ext-api-management/overview.adoc[]
* xref:arch:architecture/platform/operational/user-management/overview.adoc[]
--

=== _Accessibility_

Правильне використання сторінок кабінету screen-reader-ом забезпечується через автоматичну перевірку (lint) необхідних html-атрибутів на етапі збирання кабінетів.

=== _Adaptability_

Кабінети користувачів адаптуються до розмірів екрана браузера починаючи від *1280px* та за умови використання персонального комп'ютера. Менші розміри екрану та портативні пристрої з сенсорним екраном не підтримуються.

Браузери що підтримуються: Google Chrome @latest

=== _Usability_

Інтерфейси користувачів розроблялись з урахуванням рекомендацій та гайдлайнів до державних сайтів України. Індивідуальні компоненти вводу даних використовують загальний підхід xref:https://m3.material.io/[Material Design] від компанії Google.
