= Процес первинної автентифікації / автореєстрації громадян

Наразі, система надає вебінтерфейс для взаємодії з реєстром у вигляді клієнтського додатка кабінету та орієнтована на обслуговування наступних категорій громадян України:

- Фізичні особи
- Фізичні особи-підприємці та їх представники
- Юридичні особи та їх представники

=== Доступні способи автентифікації

Для автентифікації користувачів кабінету використовується Інтегрована Система Електронної Ідентифікації https://id.gov.ua/[ID.GOV.UA] (ІСЕІ) у якості зовнішнього Identity Provider в Keycloak, який налаштований на рівні окремого Realm для громадян. Завдяки використанню ІСЕІ, кабінет надає можливість пройти e-ідентифікацію за допомогою електронних підписів (на файловому, хмарному чи інших захищених носіях, за допомогою MobileID) та BankID НБУ.

[NOTE]
У разі недоступності ІСЕІ, система надає альтернативну (вбудовану у платформу) опцію для автентифікації користувачів з використанням виключно електронних підписів на файловому або захищеному носії.

=== Профілі взаємодії з реєстром

Кабінет громадянина підтримує окремі профілі роботи з реєстром в залежності від особистого ключа КЕП, який було використано для автентифікації:

- *Фізична особа* - особистий ключ, виданий на фізичну особу з вказанням РНОКПП та відсутнім ЄДРПОУ
- *Фізична особа-підприємець* - особистий ключ виданий ФОП з вказанням РНОКПП та ЄДРПОУ
- *Представник фізичної особи-підприємця* - особистий ключ виданий ФОП з вказанним РНОКПП представника та ЄДРПОУ ФОП
- *Представник юридичної особи* - особистий ключ виданий юридичною особою з вказанним РНОКПП представника та ЄДРПОУ юридичної особи

[NOTE]
З огляду на те, що наразі для взаємодії з державними реєстрами від імені ФОП допускається використання особистого ключа фізичної особи на яку зареєстровано ФОП, системи підтримує цей сценарій взаємодії та надає користувачам моливість обрати той чи інший профіль роботи з кабінетом у процесі автентифікації у разі, якщо для фізичної особи було знайдено запис про реєстрацію ФОП в ЄДР.

=== Принципи автентифікації з автоматичною реєстрацією користувачів

Автентифікація користувачів кабінету реалізована за принципом автоматичної реєстрації громадянина в окремому Keycloak Realm системи у разі використання дійсного особистого ключа КЕП. Для формування данних / атрибутів зареєстрованого користувача використовується інформація, отримана з електронного підпису та дані, отримані у результаті інтеграції з ЄДР, зокрема:

- Перевірка наявності зареєстрованого ФОП при використанні особистого ключа фізичної особи
- Перевірка стану актуальності ФОП та юридичної особи
- Дані для заповнення атрибутів користувача (ЄДРПОУ, тощо.)

[NOTE]
Актуальний перелік даних, які необхідно отримати з ЄДР для формування запису про користувача, доступний за https://kb.epam.com/pages/viewpage.action?pageId=1389980089[посиланням].

Кожен профіль взаємодії з кабінетом в залежності від типу використаного особистого ключа призводить до створення окремого запису громадянина в Keycloak Realm.

Для прикладу розглянемо сценарій, у якому Олександр має зареєстрований ФОП та займається наданням бухгалтерських послуг. З огляду на важливість реєстру, Олександр використовує кабінет:

- у якості фізичної особи з використанням особистого ключа
- у якості директора ФОП, зареєстрованого на його ім'я (та має особистий ключ КЕП ФОП)
- у якості представника-бухгалтера ФОП, зареєстрованого на іншу особу (та має особистий ключ представника ФОП)
- у якості представника-бухгалтера юридичної особи (та має особистий ключ представника)

У результаті проходження автентифікації у кабінеті громадянина з кожним з цих особистих ключів, в системі буде створено 4 записи (по одній на профіль взаємодії).

=== Процес первинної автентифікації / авто-реєстрації користувачів з підтримкою профілів взаємодії з реєстром

На блок-схемі зображено процес автентифікації для кожного з типів суб'єктів, які обслуговуються системою разом з результатами успішного проходження e-ідентифікації у вигляді створення запису про користувача, який містить всю необхідну інформацію:

- *РНОКПП*
- *ЄДРПОУ*
- *REPRESENTATIVE* - Ознака представника юридичної особи чи ФОП, зареєстрованого на іншу особу
- *SUBJECT_TYPE* - Тип суб'єкта (фізична особа, ФОП або представник, представник юридичної особи)

image::architecture/platform/operational/user-management/citizen-authentication-flow.svg[]

В залежності від обраного особистого ключа та профіля взаємодії з системою, користувачу буде призначена одна з системних ролей:

- *UNREGISTERED_INDIVIDUAL* (фізична особа)
- *UNREGISTERED_ENTREPRENEUR* (ФОП або представник)
- *UNREGISTERED_LEGAL* (представник юридичної особи)

Префікс #UNREGISTERED_# означає, що користувач не завершив процес xref:architecture/platform/operational/user-management/citizen-onboarding.adoc[реєстрації / онбордингу] в цільовому реєстрі та зможе завершити його створенням суб'єкту через змодельований бізнес-процес, доступний у кабінеті громадянина.
