= Підсистема резервного копіювання та відновлення

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Підсистема, що забезпечує безпечне резервне копіювання та відновлення реєстрових та центральних компонентів Платформи,
виконання аварійного відновлення Реєстру.

== Функції підсистеми

* Безпечне резервне копіювання та відновлення центральних і реєстрових компонентів Платформи реєстрів
* Безпечне резервне копіювання та відновлення даних реєстрів
* Відновлення центральних та реєстрових компонентів Платформи реєстрів
* Виконання аварійного відновлення функціонування Платформи реєстрів
* Міграція ресурсів реєстру на інший екземпляр Платформи реєстрів

== Технічний дизайн підсистеми

На даній діаграмі зображено компоненти, які входять в _Підсистему резервного копіювання та відновлення_ та їх взаємодію з іншими підсистемами.

image::architecture/platform/operational/backup-recovery/backup-subsystem.drawio.svg[width=800,float="center",align="center"]

== Складові підсистеми

|===
|Назва компоненти|Namespace|Deployment|Походження|Репозиторій|Призначення

|_Сервіс резервного копіювання та відновлення_
|`velero`
|`velero`
|3rd-party
|https://github.com/epam/edp-ddm-backup-management[github:/epam/edp-ddm-backup-management]
|Компонент резервного копіювання та відновлення ресурсів у кластері

|_Служба відновлення обʼєктів S3_
|`velero`
|`restore-job`
|origin
|https://github.com/epam/edp-ddm-backup-management[github:/epam/edp-ddm-backup-management]
|Служба відновлення обʼєктів S3 реєстру

|_Служба реплікації обʼєктів S3_
|`velero`
|`replication-job`
|origin
|https://github.com/epam/edp-ddm-backup-management[github:/epam/edp-ddm-backup-management]
|Служба резервної реплікації обʼєктів S3 реєстру
|===

== Технологічний стек
* xref:arch:architecture/platform-technologies.adoc#velero[Velero]
* xref:arch:architecture/platform-technologies.adoc#okd[OKD]
* xref:arch:architecture/platform-technologies.adoc#bash[bash]

== Атрибути якості підсистеми

=== _Reliability_
Підсистема резервного копіювання та відновлення розроблена із забезпеченням надійності збереження резервних копій та
надає можливість виконання резервного копіювання та відновлювальних операцій систематично та за потребою.

=== _Scalability_
Підсистема резервного копіювання та відновлення має можливість працювати з великими обсягами даних реєстрів та Платформи
та постійно зростаючими обʼємами даних.

=== _Recoverability_
Підсистема резервного копіювання та відновлення надає Платформі реєстрів можливість аварійно відновити дані реєстру та
Платформи у випадку відмови або при виникненні нештатної ситуації.
