@startuml
participant "Web клієнт" as client order 1
participant "Модуль роботи з формами" as formModule order 2
participant "Модуль роботи з файлами" as fileModule order 3
participant "Файловий\nсервіс" as fileService order 4

skinparam responseMessageBelowArrow true

title Створення форми регламенту у вказаній версії

client -> formModule: створити форму
activate formModule

  formModule -> fileModule: отримати файловий\nсервіс для вказаної версії
  activate fileModule
    create fileService
    fileModule -> fileService: ініціалізувати
    alt вказана версія не існує
      fileModule <-- fileService: помилка ініціалізації
      formModule <-- fileModule: помилка ініціалізації\nфайлового сервісу
      client <-- formModule: помилка зі статусом\n404 Not Found
    end
    fileModule <-- fileService
    return файловий сервіс
  deactivate fileModule

  formModule -> formModule: провалідувати інпут форми
  alt форма не валідна
  client <-- formModule: помилка зі статусом\n422 Unprocessable entity
  end


  formModule -> fileService: перевірити чи вже існує форма з вказаним ім'ям
  activate fileService
    return ознака існування
  deactivate fileService
  alt форма з таким ім'ям вже існує
  client <-- formModule: помилка зі статусом\n409 Conflict
  end

  formModule -> formModule: визначити дати створення\nта останнього оновлення\nяк поточну дату та час

  formModule -> formModule: додати дати створення та\nостаннього оновлення до контенту
  note right
    Дата створення - **//$.created//**
    Дата останнього оновлення - **//$.modified//**
  end note

  formModule -> fileService: створити файл форми
  activate fileService
  return
  deactivate fileService

  client <-- formModule: контент форми з датами\nстворення та останнього\nоновлення

deactivate formModule
@enduml