//:toc: auto
:toclevels:
:toc-title: ЗМІСТ
:sectnums:
:sectnumlevels:
:sectanchors:
:experimental:
:important-caption: ВАЖЛИВО
:note-caption: ПОКРАЩЕНО
:tip-caption: РОЗРОБЛЕНО
:warning-caption: ЗВОРОТНО НЕСУМІСНІ ЗМІНИ
:caution-caption: ІНШЕ
:example-caption: Приклад
//:last-update-label: 24.01.2023
:sectlinks:

= Зворотно несумісні зміни 1.9.4

== Швидкі посилання до сервісів реєстру

[WARNING]
====
Після оновлення Платформи, навіть без оновлення реєстру, посилання до компонентів реєстру переміщаються на вкладку +++<b style="font-weight: 700"> Швидкі посилання </b> +++ у *Control Plane*.

Детальніше ви можете ознайомитися з функціональністю на сторінці xref:admin:registry-management/control-plane-quick-links.adoc[].
====

== Зміна логіки роботи Cleanup-процесу видалення регламенту

[WARNING]
====
З'явилася можливість виконати cleanup реєстру зі збереженням поточного регламенту, регулюючи процес вхідним параметром `*DELETE_REGISTRY_REGULATIONS_GERRIT_REPOSITORY*`.

Детальніше ви можете ознайомитися зі змінами на сторінці xref:registry-develop:registry-admin/regulations-deploy/cleanup-job.adoc[].
====