//:toc: auto
:toclevels:
:toc-title: ЗМІСТ
:sectnums:
:sectnumlevels:
:sectanchors:
:experimental:
:important-caption: ВАЖЛИВО
:note-caption: ПОКРАЩЕНО
:tip-caption: РОЗРОБЛЕНО
:warning-caption: ЗВОРОТНО НЕСУМІСНІ ЗМІНИ
:caution-caption: ІНШЕ
:example-caption: Приклад
//:last-update-label: 24.01.2023
:sectlinks:

= Зворотно несумісні зміни 1.9.5

== Міграція доступів до SOAP-роутів ШБО "Трембіта"

[WARNING]
====
Після оновлення реєстру до нової версії, видаляться наявні SOAP API-роути. Тому, щоб їх зберегти, перед оновленням необхідно вручну додати IP-адреси ШБО "Трембіта" до конфігурації файлу _deploy-templates/values.yaml_ та виконати commit до `master`-гілки репозиторію https://gerrit-control-plane.<dns-wildcard>[] (центральний компонент Gerrit Платформи).

TIP: Детальніше про це дивіться на сторінці xref:admin:registry-management/control-plane-soap-api-access-trembita.adoc#configuration-scenarios[Обмеження доступу на рівні IP до SOAP-роутів ШБО "Трембіта"].

Надалі можна виконувати оновлення реєстру у штатному режимі.
====

== Винесення сервісів для роботи з аналітичною звітністю за Kong API

[WARNING]
====
Змінено посилання до сервісів для побудови та перегляду аналітичної звітності реєстру -- *`redash-admin`* та *`redash-viewer`*. Тепер компоненти винесені за KONG API-шлюз та доступні за ендпоінтом *`/reports`*.

Нові посилання до сервісів виглядають наступним чином:

* *`redash-admin`*: https://admin-tools-<назва-реєстру>.dnsWildcard/reports.

* *`redash-viewer`*: https://officer-portal-<назва-реєстру>.dnsWildcard/reports.
====