:toc-title: ЗМІСТ
:toc: auto
:toclevels: 1
:experimental:
:important-caption:     ВИПРАВЛЕНО
:note-caption:          ПОКРАЩЕНО
:tip-caption:           РОЗРОБЛЕНО
:caution-caption:       ІНШЕ
:warning-caption:       ПОКРАЩЕННЯ БЕЗПЕКИ
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
//:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Примітки до релізу 1.9.4

Пропонуємо ознайомитися з останніми примітками до релізу нашого програмного продукту. У цьому розділі ми надаємо інформацію про нові функції, оновлення компонентів, виправлення помилок, оптимізацію продуктивності та покращення безпеки.

== Розробка

=== Категоризація доступних послуг у Кабінетах користувачів

[TIP]
Можливість використання конфігурації репозиторію регламенту для налаштування групування послуг в Кабінеті посадової особи.

[TIP]
Створення нових груп доступних послуг для відображення в кабінетах користувачів через інтерфейс Адмін порталу.

[TIP]
Додавання не згрупованих бізнес-процесів до наявних та нових груп для відображення у Кабінетах користувачів через інтерфейс адміністративного порталу.

[TIP]
Сортування груп, бізнес-процесів в групах та поза групами для відображення в кабінетах користувачів через інтерфейс адміністративного порталу у версії-кандидат.

[TIP]
Зміна назви та видалення груп доступних послуг через інтерфейс Адмін порталу.

[TIP]
Збереження змін на вкладці "Відображення в кабінетах" у поточній версії-кандидат через інтерфейс Адмін порталу.

[TIP]
Виключення бізнес-процесів з груп через інтерфейс Адмін порталу.

[TIP]
Перегляд доступних груп, послуг в них та поза групами у версії-кандидат та Мастер версії через інтерфейс адмін-порталу.

[TIP]
Відображення груп доступних послуг за категоріями для користувачів Кабінету посадової особи/отримувача послуг.

[TIP]
Відображення збережених змін на вкладці "Відображення в кабінетах" в розділі "Огляд версії" інтерфейсу адмін-порталу.

[TIP]
Видалення process definition із груп при виклику ендпоінта видалення бізнес-процесу.

[TIP]
Міграція груп для наявних реєстрів.

[NOTE]
Оптимізовано рендеринг сторінки "Відображення в кабінетах".

=== Внесення змін до файлу описів структур таблиць моделі даних реєстру через вебредактор коду

[TIP]
Підтвердження змін у файлі описів структур таблиць моделі даних реєстру через вебредактор коду у версії-Кандидаті.

[TIP]
Перегляд файлу описів структур таблиць моделі даних реєстру через вебредактор коду для версії-кандидата та Майстер-версії.

[TIP]
Відображення статусу оновлення структур таблиць моделі даних, здійснених через вебредактор коду.

[TIP]
Редагування файлу опису структур таблиць моделі даних реєстру для Версії Кандидата, використовуючи автопідказки, автодоповнення та аналіз коду згідно з liquibase та DDM xsd.

[TIP]
Відображення сторінок помилок при перегляді переліку таблиць при відсутності файлу опису моделі даних та неуспішному запиті файлу у майстер-версії.

=== Можливість пагінації пошукових запитів

[TIP]
Можливість налаштування отримання інформації про загальну кількість знайдених елементів при створенні критеріїв пошуку (SC) для коректного налаштування пагінації користувачів.

=== Впровадження загального SOAP-конектора для взаємодії з "Трембіта"

[TIP]
Додано автодоповнення для JUEL функції get_trembita_auth_token() у візуальному редакторі коду для Версії Кандидат.

[TIP]
Розробникам регламенту надана можливість виклику із БП довільного реєстру-учасника ШБО "Трембіта", використовуючи універсальний SOAP-конектор.

[TIP]
Адміністраторам реєстру надана можливість налаштувати інтеграцію із довільною зовнішньою системою-учасником ШБО Трембіта через SOAP протокол в інтерфейсі Control plane.

=== Швидкі посилання до сервісів у Control Plane

[TIP]
Додано посилання на Openshift, pgAdmin, Kibana, Swagger, Redash та інші адміністративні ендпоінти в інтерфейсі Control Plane для зручності адміністратора реєстру.

=== Конфігурація перевірки в ЄДР при логіні юридичних осіб до Кабінету отримувача послуг

[TIP]
Можливість налаштовування перевірки в ЄДР для користувачів, що обрали вхід "Для бізнесу" на сторінці автентифікації для технічного адміністратора реєстру.

[TIP]
Забезпечено можливість автентифікації для отримувачів послуг-ФОП, представників ФОП або ЮО, обираючи режим "Для бізнесу" та використовуючи КЕП без відповіді ЄДР.

=== Видалення попередньої версії автогенерованого коду при розгортанні регламенту

[TIP]
Впроваджено автоматичну заміну коду новою версією у Gerrit реєстру в репозиторії для технічного адміністратора реєстру.

[TIP]
Забезпечено автоматичне оновлення версій Docker images в Nexus реєстру останньою версією для технічного адміністратора реєстру.

[TIP]
У Kafka реєстру тепер відображаються тільки топіки для сервісів API, що використовуються в останній версії реєстру, для технічного адміністратора реєстру.

[TIP]
Відмова від необхідності змінювати версію регламенту в структурі регламенту після кожної зміни для розробників та моделювальників регламенту.

=== Видалення API по роботі з масивами даних для наявних таблиць

[TIP]
Додано можливість зміни налаштувань на рівні створення таблиць для розробників регламенту, що впливає на поведінку згенерованого коду API.

=== Запуск бізнес-процесу за розкладом

[TIP]
Додано референтний приклад бізнес-процесу для розробників та моделювальників регламенту, що демонструє запуск бізнес-процесу за таймером.

=== Відображення масивів даних у вигляді таблиць на формах БП з можливістю виклику інших БП для певного рядка

[TIP]
Додано можливість налаштовувати компонент EditGrid для роботи в режимі "тільки для перегляду" для розробників регламенту.

[TIP]
Користувачі Кабінету посадової особи та отримувачі послуг можуть переглядати даних UI-форми в режимі "read only" та виконувати дії стосовно обраного запису таблиці.

[TIP]
Розробникам регламенту додано можливість налаштовувати набір дій, які можна виконати стосовно окремих записів таблиці.

[TIP]
Моделювальникам реєстру надано можливість відображати масиви даних у вигляді таблиць на формах БП з можливістю виклику інших БП для певного рядка.

[TIP]
Розроблено тестовий БП для функціональності вибору одного рядка в таблиці та запуску для нього БП.

=== Можливість обирати декілька рядків в таблиці та запускати для них БП

[TIP]
Моделювальникам реєстру додано можливість обирати декілька рядків в таблиці та запускати для них бізнес-процеси.

[TIP]
Розробникам регламенту надано можливість налаштовувати активацію обрання декількох записів з таблиці для виконання стосовно них дій.

[TIP]
Користувачі Кабінету посадової особи та отримувачам послуг можуть ініціювати виконання бізнес-процесів з даними декількох обраних рядків з таблиці.

[TIP]
Розробникам регламенту додано можливість налаштовувати ширину полів компонентів для відображення в таблиці EditGrid.

[TIP]
Розроблено тестовий бізнес-процес для функціональності вибору одного або декількох рядків в таблиці та запуску для них бізнес-процесів.

[NOTE]
Оптимізовано рендеринг таблиці для забезпечення кращої продуктивності.

=== Автореєстрація для посадових осіб

[TIP]
Додано можливість для моделювальників реєстру дати можливість посадовим особам проходити самореєстрацію з ручним або автоматичним модеруванням.

[TIP]
Адміністраторам реєстру надано можливість налаштовувати самореєстрацію посадових осіб.

[TIP]
Розроблено референтні приклади бізнес-процесів автореєстрації посадової особи з автоматичною та ручною модерацією для моделювальників реєстру.

[TIP]
Посадові особи можуть після автентифікації в кабінеті автоматично почати процес самореєстрації, якщо він змодельований в реєстрі та налаштована автореєстрація.

[TIP]
Розробникам регламенту надано окреме типове розширення *Save user roles* для внесення змін до переліку регламентних ролей користувача.

=== Зміна логіки роботи Cleanup-процесу видалення регламенту

[TIP]
Додано можливість виконати cleanup зі збереженням поточного регламенту, регулюючи процес вхідним параметром *`DELETE_REGISTRY_REGULATIONS_GERRIT_REPOSITORY`*.

[NOTE]
Розроблено механізм очищення артефактів Docker у Nexus до Cleanup для запобігання переповненню пам'яті.

=== Моніторинг показників виконання бізнес-процесів

[TIP]
Додано можливість для технічного адміністратора реєстру моніторити показники виконання бізнес-процесів через дашборд.

=== Оптимізація збирання логів для спрощення їх аналізу у виробничому середовищі

[NOTE]
Налаштовано логування Kong у форматі JSON.

[NOTE]
Додано контекстну інформацію до логів form-schema-provider.

[NOTE]
Додано логування responseCode до registry-rest-api.

[NOTE]
Покращено логування для Keycloak.

[NOTE]
Зменшено рівень логування для kafka-кластера у виробничому режимі.

[NOTE]
Зменшено рівень логування в Jenkins.

[NOTE]
Змінено рівень логування Ceph (rgw, mon).

[NOTE]
Вирівняно структуру логів для сервісів реєстру.

[NOTE]
Прибрано логи Crawling result set у registry-regulation-mng.

[NOTE]
Додано логування до сервісу DSO для деталізації помилок ініціалізації контексту.

[NOTE]
Перевірено та вимкнено логування cookie header в усіх BE-сервісах.

=== Технічна підтримка, регулярні активності, покращення

[NOTE]
Додано rebase для security-header гілки до master у proxy-mode pipeline.

[NOTE]
Змінено значення за замовчуванням для параметра CP_GERRIT_BRANCH на security-header в ci-proxy pipeline.

[NOTE]
Додано крок збірки npm до control-plane-console.

[NOTE]
Оновлено ReportPortal до версії 5.7.4.

[NOTE]
Створено автотести для налаштувань зовнішніх систем.

[CAUTION]
Видалено етапи безпеки зі спеціальних гілок розробки.

[CAUTION]
Створено pipeline для публікації обраної версії installer в S3 bucket.

[CAUTION]
Змінено час розкладу старту/стопу кластерів згідно з переходом на літній час.

== Інші впровадження

[TIP]
Створено автотест для getUsersByRoleFromKeycloak делегату.

[TIP]
Створено автотести для JUEL функцій: initiator(), completer(), system_user().

[TIP]
Можливість викликати SOAP-ендпоінти з бізнес-процесу.

[TIP]
Додано автотест до officer та citizen порталів, який перевіряє валідаційну помилку (422 статус код) при додаванні файлу з некоректним розширенням у стилізований компонент "File" на формах БП.

[TIP]
Додано можливість застосовувати зміни до мастер версії без проходження пайплайну розгортання та перевірки на версії-кандидаті в адмін-порталі.

[NOTE]
Оновлено реєстровий gerrit-operator до останньої EDP-версії.

[NOTE]
Адаптовано onboarding-автотести у consent test suite для перевірки addRoleToKeycloakUser та removeRoleFromKeycloakUser делегату.

[NOTE]
Автоматизовано налаштування підтримки https у minio та vault на цільових оточеннях в AWS.

[NOTE]
Стабілізовано checkSortingOnTablePageInMasterVersion.

[NOTE]
Підготовлено до виводу з використання low-code-form-data-storage Ceph bucket.

[NOTE]
Дослідження та оновлення нестабільного тесту AheadCandidateVersionOverviewTest.

[NOTE]
Змінено обмеження за кількістю записів у csv-файлі із 50 до 600.

[NOTE]
Автоматизовано оновлення CRD для jenkins-operator, gerrit-operator, keycloak-operator та edp-component-operator.

[NOTE]
Автоматизовано застосування crunchy-postgres-operator.

[NOTE]
Додано UI-автотести для перевірки сторінок "Загальні" у БП в розділі "Моделі процесів" для адмін-портал у майстер- та кандидат-версії.

[NOTE]
Додано заборону для користувача підтверджувати нові запити на оновлення, доки master-build пайплайн не відпрацює попередній запит.

[CAUTION]
Створення дефолтних користувачів Сидоренко для officer та citizen порталу під час автоналаштування.

[CAUTION]
Оновлено Crunchy PGO до версії 5.3.0.

[CAUTION]
Оновлено kubectl/oc на gitops-агенті.

[CAUTION]
Оновлення версії моделі даних у репозиторії consent-data.

[CAUTION]
Видалено з репозиторію citus скрипти оновлення, які були призначені для міграції з citus на crunchy. Перейменовано репозиторій.

[CAUTION]
Обмеження використання [email protected].

[CAUTION]
Замінено назву параметра methodName у bpms ExternalSystemConnectorDelegate.

[CAUTION]
Оновлено camunda-auth-cli утиліту.

[CAUTION]
Відключено авто-rebase для RRM-сервісу на оточенні CICD2.

[CAUTION]
Створено новий репозиторій для автотестів _platform-qa-tests_.

[CAUTION]
Переміщення тестів компонента template-rest-api до основної бібліотеки -- core lib.

== Регресійні дефекти

[IMPORTANT]
====
._Список регресійних дефектів. Натисніть, що розгорнути або згорнути блок_.
[%collapsible]
=====
[IMPORTANT]
Пайплайн із реплікації бакета rook-to-s3-lowcode-file-storage падає через битий файл у бакеті.

[IMPORTANT]
Пайплайн із по реплікації бакета rook-to-s3-datafactory-ceph-bucket падає через кількість директорій.

[IMPORTANT]
Перевірити механізм міграції з використання CEPH бакетів на Redis та видалити lowcode-form-data-storage bucket з усіх реєстрів.

[IMPORTANT]
Дослідження роботи Redash-viewer та Redash-admin автентифікації та встановлення скриптів, які потенційно породжують велику кількість запитів до keycloak системи, через що падає пода.

[IMPORTANT]
Параметризація використання maxmemory для компонента redis-sentinel.

[IMPORTANT]
Помилка error="no KongPlugin or KongClusterPlugin was found" в логах Kong поди

[IMPORTANT]
Видалення попередньої версії автогенерованого коду при розгортанні регламенту. Розгортання registry-rest-api і registry-kafka-api не залежить від версії.

[IMPORTANT]
Зміна іконки статусу інтеграції на зелену після натискання кнопки "Підтвердити/Додати".

[IMPORTANT]
Неправильне модальне вікно при додаванні нового запиту на оновлення якщо існує необроблений запит.

[IMPORTANT]
При редагуванні зовнішньої інтеграції із типом автентифікації Basic не відображається значення логіну.

[IMPORTANT]
Блокується можливість надати доступ до реєстру, якщо вже був доданий доступ до Зовнішньої системи з ім'ям наявного реєстру.

[IMPORTANT]
Після бекапу та відновлення реєстру при подальших змінах в реєстрі падає master-build job-а.

[IMPORTANT]
[EnvOne] Після відновлення реєстру під час підпису будь-якого процесу, отримуємо 500 помилку.

[IMPORTANT]
[vSphere] Не формується бекап PV grafana у НС grafana-monitoring.

[IMPORTANT]
[FE]Неправильна робота під час надання/видалення/заблокування доступу до платформи або системи якщо у системи й платформи однакові імена.

[IMPORTANT]
Видалено Shortcut-функціональність зі стилізованого Radio-компонента.

[IMPORTANT]
[FE] Дублювання компонентів у білдері стилізованого Edit Grid при активній опції "Custom Default Value" чи "Calculated Value".

[IMPORTANT]
Cleanup процес перестворює registry-regulation із порожнього шаблону, коли НЕ обрано чекбокс RECREATE_EMPTY.

[IMPORTANT]
[FE] Пошкодження форми, що створюється в білдері, через маніпуляції з однаковими API іменами в стилізованих компонентах Date/Time, Select, Edit Grid.

[IMPORTANT]
Після cleanup-процесу і розгортання регламенту, не створився build registry-kafka-api.

[IMPORTANT]
Збирач (Builder) адмін-порталу ховає попередження для будь-якої вбудованої помилки, якщо адмін переходить на Preview mode, а потім повертається до Builder форми.

[IMPORTANT]
[S23][REGRESSION][ST1] Регресійні дефекти 1.9.4	[PROD SUPPORT L3] Помилка liquibase після видалення регламенту з Cleanup-процесом.

[IMPORTANT]
Некоректна сторінка відповіді під час 403 помилки на citizen-portal при аутентифікації у кабінет (валідно для consent-data registry).

[IMPORTANT]
Виправити посилання на центральний Gerrit на сторінці перегляду реєстру.

[IMPORTANT]
Герб на історичному витягу занадто великий.

[IMPORTANT]
Пов'язані Select-запити не заповнюються даними.

[IMPORTANT]
Невірно генерується клас у registry-model для типу TEXT.

[IMPORTANT]
Додати додаткові умови при внесенні назви реєстру в settings.yml.

[IMPORTANT]
Не відображається іконка статусу у конфігурації реєстру в control-plane-console.

[IMPORTANT]
Не відображається номер збірки на сторінці "Інформація про реєстр" у блоці Конфігурація.

[IMPORTANT]
Видалити кнопку "Kebab-menu" з мастер версії з навігаційного меню в розгорнутих БП у розділі "Моделі процесів" у admin-tools.

[IMPORTANT]
Кожен новий CIDR стартує с нового рядка.

[IMPORTANT]
Властивість "Description" не працює в оновленому компоненті "Map" в admin-tools.

[IMPORTANT]
Створювати окремі кластерні ролі для розгортань Kong у кожному реєстрі.

[IMPORTANT]
Після створення нової версії кандидату та переходу до сторінки Таблиці (тимчасова БД ще не розгорнулась) після 30 сек очікування користувач бачить некритичну помилку "Щось пішло не так" в адмін-порталі.

[IMPORTANT]
Некоректні помилки в admin-tools під час 404 та 500 статус кодів у розділі "Таблиці" на вкладці "Перелік таблиць".

[IMPORTANT]
Дослідження проблеми працездатності keycloak системи.

[IMPORTANT]
Неуспішний пайплайн перевірки коду у випадку, коли створюється версія-кандидат при порожньому регламенті (відсутня модель даних).

[IMPORTANT]
Автоматичний pull майстер-версії не відбувається через відключення авто-rebase на cicd2.

[IMPORTANT]
Зайві записи налаштувань авторизації camunda для Historic Task.

[IMPORTANT]
Не можливо робити оновлення у базі даних системним користувачем.

[IMPORTANT]
При редагуванні groovy скриптів в Адмін Порталі не автодоповнюється функція save_digital_document_from_url().

[IMPORTANT]
Некоректний колір елемента кнопки "Додати" вимкненого "Edit Grid" на UI формах.

[IMPORTANT]
Через велику кількість відкритих версій-кандидатів (понад 30) система адмін-порталу починає гальмувати, й починаються зависання на стороні BE.

[IMPORTANT]
Дослідження проблеми із використанням параметра з \n символом у SC-запиті.

[IMPORTANT]
Автоматичний запуск крон job підчистки кешу (кожні 5 хв) може видалити щойно створені дані версії-кандидата.

[IMPORTANT]
Помилка 413 payload too large на запит http://form-submission-validation:8080/api/form-submissions/change-status-bp-change-status/validate, якщо оновлюється сутність великого обсягу даних.

[IMPORTANT]
Значно зросло зайняте аудит-логами місце на одному з kafka-брокерів реєстру PZM кластера Denovo.

[IMPORTANT]
Прибрати хард-код на кластері розробки у trembita-mock в репозиторії _mdtu-ddm/general/registry-configuration/-/blob/main/deploy-templates/values.yaml_.

[IMPORTANT]
Operational БД перестає коректно працювати через помилку з invalid permissions.

[IMPORTANT]
Через імпорт json-плагіну до Kong, при роботі з кабінетами логуються авторизаційні токени користувача.

[IMPORTANT]
Eндпоінт minio після оновлення кластера не оновився.

[IMPORTANT]
Прибрати з налаштування кількості з'єднань у PgPool (operational-pool-config) hardcoded-значення.

[IMPORTANT]
Не працює створення налаштувань бекапу компонентів реєстру у Control Plane.

[IMPORTANT]
Змінити налаштування видалення авторизацій, створених camunda-auth-cli, та видаляти усі авторизації які "contains" READ, CREATE_INSTANCE.

[IMPORTANT]
Додати можливість виконувати REST запити для пошуку даних, у яких присутній спецсимвол кома.

[IMPORTANT]
Користувач має бачити тільки ті версії реєстрів котрі відповідають версії адмін консолі.

[IMPORTANT]
Помилка зберігання даних під час оновлення на нову версію при зміні назви згенерованого об'єкта.

[IMPORTANT]
Додати рестарт поди process-history-service-persistence-deployment при невдалому з'єднанні з Kafka.

[IMPORTANT]
Падає розгортання оточень на redash-chart із помилкою ImportError: cannot import name 'DEPRECATED_SERVICE_NAMES' from 'botocore.docs'.

[IMPORTANT]
SOAP-ендпоінт дата фабрики не дає можливості використовувати read all запит на search condition.

[IMPORTANT]
Помилка NullPointerException при незбігу назви системи та метода у configuration.yml та в делегаті.

[IMPORTANT]
Відсутній toggle button "Edr check" у ds-citizen-authenticator-configuration у KeyCloak при оновленні реєстру на нову версію.

[IMPORTANT]
Додати можливість прокручувати вправо-вліво значення у Select-компоненті, якщо воно виходить за рамки компонента.

[IMPORTANT]
Відсутній service account istio-gateway у SCC anyuid.

[IMPORTANT]
Система не дає можливість створювати реєстри на версії 1.9.3 на оновленій платформі 1.9.4 в одній консолі control-plane.

[IMPORTANT]
Валідатор повинен пропускати групу із порожнім масивом processDefinition.

[IMPORTANT]
Group Sync operator версії 0.0.25 не підтримує Keycloak нижче 17 версії.

[IMPORTANT]
Додати можливість виключати initial load із розгортання з code-review пайплайну.

[IMPORTANT]
Не підтягуються дані з зовнішнього ресурсу на оновленому компоненті Select.

[IMPORTANT]
Не проходить реплікація екземплярів PostgreSQL.

[IMPORTANT]
Запуск пайплайну cleanup-of-version-candidate-db на реєстрі видаляє усі тимчасові БД.

[IMPORTANT]
Не працює відновлення реєстру із резервної копії.

[IMPORTANT]
Під час розгортання платформи з 0 система використовує некоректні сертифікати для DSO у секреті "digital-signature-data" у user-management сервісі.

[IMPORTANT]
Під час розгортання платформи з нуля пайплайн падає через помилку GroupSync.

[IMPORTANT]
Control-plane-nexus перезапускається під час кожного розгортання на cluster-mgmt.

[IMPORTANT]
При розгортанні платформи з нуля, cluster-mgmt процес падає з помилкою kong-global-resources.

[IMPORTANT]
При розгортанні платформи з нуля, cluster-mgmt процес падає з помилкою smtp-server.

[IMPORTANT]
Поле "Посилання" та розмір віджета тепер мають значення за замовченням при оновленні версії платформи.

[IMPORTANT]
Усунено неінформативність помилок в Kafka API при помилці виклику процедури.

[IMPORTANT]
При очищенні регламенту з cleanup-job, тепер видаляються дані з бази аудиту.

[IMPORTANT]
Усунено нестабільність розгортання e-shelter після проходження cleanup-процесу.

[IMPORTANT]
Виправлено проблеми зависання процесу *`cleanup-job`* та створення *`registry-regulations`* після cleanup-job.

[IMPORTANT]
Виправлено крок компіляції у компоненті common-web-app.

[IMPORTANT]
Полагоджено compile step на Code Review pipe.

[IMPORTANT]
Виправлено проблему, коли при створенні середовища з нуля, у пайплайн підтягується неправильний gerrit-користувач.

[IMPORTANT]
Не підтягуються дані із зовнішнього ресурсу на оновленому компоненті Select.

[IMPORTANT]
Користувач, створений у admin/openshift реалмі keycloak системи та з відсутньою роллю cp-registry-admin-{registryName}, може увійти до кабінету адміністратора регламенту.

[IMPORTANT]
Помилка error invoking function 'system_user' на e-shelter-prod.
=====
====

== Безпека

[WARNING]
====
.Покращення безпеки інфраструктури Платформи
[%collapsible]
=====
[S23][PST][SECURITY] Дефекти з безпеки 1.9.4	Build Process: Missing User Instruction
=====
====

[WARNING]
====
.Покращення безпеки бібліотек Spring-фреймворку
[%collapsible]
=====
* [S23][ST2][SECURITY] Дефекти з безпеки 1.9.4	[Security] [Group] 1.9.4 Vulnerabilities in org.springframework.boot:spring-boot

* [S23][ST2][SECURITY] Дефекти з безпеки 1.9.4	[Security] [Group] 1.9.4 Vulnerabilities in org.springframework:spring-beans

* [S23][ST2][SECURITY] Дефекти з безпеки 1.9.4	[Security] [Group] 1.9.4 Vulnerabilities in org.springframework:spring-webmvc
=====
====

[WARNING]
====
.Покращення бібліотек Postgresql
[%collapsible]
=====
[S23][ST1][SECURITY] Дефекти з безпеки 1.9.4	[Security][Group] 1.9.4 Postgresql vulnerability mitigation
//https://jiraeu.epam.com/browse/MDTUDDM-14725
=====
====
