@startuml
participant "Platform service" as client  order 10
participant "QES service" as digital_ops  order 20
participant "AKCC" as ca  order 30
skinparam responseMessageBelowArrow true

title Putting system signature
  client -> digital_ops: Data
    activate digital_ops
    digital_ops -> digital_ops: Data hash calculation
     digital_ops -> ca: Rwequest timestamp
     activate ca
     digital_ops <-- ca: timestamp
     digital_ops -> ca: Request revoked certificate list
     digital_ops <-- ca: List of revoked certificates
     deactivate ca
    digital_ops -> digital_ops: Put the electronic seal on a hash
    digital_ops -> client: Signature
    deactivate digital_ops

@enduml