@startuml
participant "Сервіс платформи" as client  order 10
participant "КЕП сервіс" as digital_ops  order 20
participant "Ceph" as ceph  order 30
skinparam responseMessageBelowArrow true

title Накладання системного підпису на файл
  client -> digital_ops: Ключ розташування файлу
  activate digital_ops
    digital_ops -> ceph: Пошук файлу
    activate ceph
    ceph -> digital_ops: Файл для підпису
    deactivate ceph
    digital_ops -> digital_ops : Накладання підпису на файл
    digital_ops -> ceph: Оновлення файлу в бакеті
    activate ceph
    deactivate ceph
  digital_ops -> client: Відповідь
  deactivate digital_ops
@enduml