= Підсистема трасування запитів

include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

_Підсистема трасування запитів_ допомагає адміністраторам та розробникам реєстрів відстежувати, профілювати та усувати неполадки в
мікросервіс-орієнтованих розподілених системах таких як Платформа реєстрів. Вона надає можливість прослідковувати запити
під час їх передачі через складну архітектуру, що дозволяє адміністраторам та розробникам розуміти, як різні сервіси
Платформи взаємодіють між собою та де можуть бути проблеми з продуктивністю.

_Підсистема трасування запитів_ складається з кількох компонентів, включаючи агентів, колекторів, сховище для зберігання трейсів
та сервіс запитів. Агенти відповідають за збір даних з мікросервісів та їх передачу колекторам. Колектори зберігають та індексують дані, а
сервіс запитів дозволяє шукати та візуалізувати дані у зручний спосіб.

Підсистема дозволяє прослідковувати окремі запити через кілька сервісів Платформи та переглядати детальну інформацію про
кожен запит, таку як час відповіді, частоту помилок та залежності сервісів.
Ця інформація може бути використана для ідентифікації проблем продуктивності, оптимізації комунікації сервісів та
покращення загальної надійності системи.

== Функції підсистеми

* Візуалізація та аналіз трейсингових даних, що дозволяє розробникам швидко ідентифікувати проблеми та оптимізувати свої системи.
* Відображення часу виконання ланцюгів та ланок запитів
* Підсистема надає детальні метрики для трейсингових даних, такі як кількість зібраних спанів (span), кількість дискретних трейсів (trace) та кількість помилок, що виникли.
* Пошук ланцюгів запитів на підставі ідентифікаторів запитів (`trace_id`).
* Підсистема має зручний веб-інтерфейс для візуалізації та аналізу трейсингових даних, що дозволяє швидко ідентифікувати проблеми в Платформі.

[NOTE]
====
Span являє собою фрагмент коду, що вимірює час виконання операції та збирає інформацію про неї, таку як
ідентифікатор, час початку і закінчення операції, а також теги, які описують контекст операції.

Trace - це послідовність span-ів, які утворюють структуру запиту. Кожен span має унікальний ідентифікатор,
таким чином можна скласти дерево span-ів, що показує послідовність операцій та їх залежності в процесі виконання запиту.
====

== Технічний дизайн підсистеми

image::architecture/platform/operational/distributed-tracing/distributed-tracing-subsystem.drawio.svg[width=600,float="center",align="center"]

== Компоненти підсистеми

|===
|Назва компоненти|Namespace|Deployment|Походження|Репозиторій|Призначення

|_Jaeger оператор_
|`istio-system`
|`jaeger-operator`
|3rd-party
.3+|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/infrastructure/service-mesh[gerrit:/mdtu-ddm/infrastructure/service-mesh]
|Допоміжне програмне забезпечення, яке виконує функції розгортання, налаштування та відновлення Jaeger, як
компонента підсистеми.

|_Jaeger колектор_
|`istio-system`
|`jaeger-collector`
|3rd-party
|Компонент призначений для збору, обробки та фільтрації трейсингових даних з різних джерел. Агрегує дані та забезпечує їхнє надійне збереження у потрібному форматі для подальшого аналізу та візуалізації.

|_Сервіс запитів та веб-інтерфейс_
|`istio-system`
|`jaeger-query`
|3rd-party
|Компонент, що надає веб-інтерфейс для пошуку та фільтрації трейсів, а також їх візуалізації та аналізу.

|_Сховище Elasticsearch_
|`istio-system`
|`elasticsearch`
|3rd-party
|Компонент для зберігання та індексування трейсів що були зібрані колектором.

|===

== Технологічний стек

При проєктуванні та розробці підсистеми, були використані наступні технології:

* xref:arch:architecture/platform-technologies.adoc#jaeger[Jaeger]
* xref:arch:architecture/platform-technologies.adoc#elasticsearch[ElasticSearch]
* xref:arch:architecture/platform-technologies.adoc#jaeger-operator[Jaeger Operator]

== Атрибути якості підсистеми

=== _Observability_
_Підсистема трасування запитів_ забезпечує всебічний огляд поведінки Платформи, що дозволяє адміністраторам та розробникам
реєстрів спостерігати продуктивність, виявляти аномалії та ідентифікувати можливі проблеми при експлуатації Платформи.

=== _Performance_
_Підсистема трасування запитів_ надає низькопомітну інструментальну підтримку трейсингу та ефективне зберігання та
індексування даних, що дозволяє проводити високопродуктивний моніторинг запитів в Платформі не витрачаючи зайві
обчислювальні ресурси.

=== _Scalability_
_Підсистема трасування запитів_ розроблена з урахуванням великих обсягів даних трейсингу, з підтримкою горизонтальної
масштабованості та розподіленого зберігання даних.

=== _Security_

Користувацький інтерфейс захищений додатковим проксі компонентом який разом з централізованою xref:architecture/platform/operational/user-management/overview.adoc[підсистемою управління користувачами та ролями] 
відповідає за надання доступу та розмежування прав. За замовчуванням користувачу надаються мінімальні права необхідні для виконання поставлених завдань.

Присутній механізм обмеження доступу до інтерфейсу який своєю чергою мінімізує поверхню атаки підсистеми ззовні.

Усі події всередині підсистеми логуються та доступні для подальшого аналізу при потребі xref:arch:architecture/platform/operational/logging/overview.adoc[підсистемою журналювання подій].

Підсистема не має доступу до чутливих даних та не зберігає їх.
