Camunda-auth-cli інструмент командного рядка
-------------------------------------------

== Загальний опис

Інструмент командного рядка, який на базі вхідних параметрів створює права доступу до окремих бізнес-процесів
для вказаних системних ролей.

== Загальні принципи

- Видалення всіх прав доступу до регламентів.
- Створення прав доступу до окремих *бізнес-процесів* для *вказаних ролей* у файлах конфігурацій.

Наступні права доступу повинні бути створені для кожної ролі в конфігураційному файлі:

|====
| Ресурс | Доступ

| PROCESS-DEFINITION (бізнес-процеси)
| READ (доступ до списку процесів регламенту), CREATE-INSTANCE (старт бізнес процесу)

| PROCESS-INSTANCE (екземпляр бізнес-процесу)
| CREATE (створення екземпляру для старту бізнес-процесу)

|====

== Взаємодія з сервісами платформи

image::arch:architecture/registry/administrative/regulation-publication/services/camunda-auth-cli/camunda-auth-cli.svg[]

.Критичні залежності:
* *Cервіс виконання бізнес-процесів (bpms)* - впливає на весь функціонал інструменту.

== Необхідні вхідні параметри

Вхідні параметри, які повинні бути вказані для коректної роботи інструменту.

|===
|Параметр |Тип |Опис

|BPMS_URL
|string
|Адреса до сервісу виконання бізнес-процесів (bpms)

|BPMS_TOKEN
|string
|Шлях до файлу з токеном. Токен *повинен мати camunda-admin роль*.

|AUTH_FILES
|string
|Список конфігураційних файлів через кому.
|===

== Приклад використання

[source,bash]
----
java -jar camunda-auth-cli.jar --BPMS_URL=http://localhost:8080 --BPMS_TOKEN=C:/token.txt --AUTH_FILES=C:/officer.yml,C:/citizen.yml
----

== Приклад конфігураційного файлу для створення доступу до бізнес-процесів

officer.yml:

[source, yaml]
----
authorization:
  realm: 'officer' # Реалм до якого застосовується конфігурація
  process_definitions:
    - process_definition_id: 'add-lab' # Унікальний ідентифікатор бізнес-процесу
      process_name: 'Створення лабораторії' # Назва бізнес-процесу для зручності читання файлу
      process_description: 'Регламент для створення лабораторій' # Опис бізнес-процесу для зручності читання файлу
      roles:
        - officer-first-rank # Унікальне ім'я ролі регламенту
    - process_definition_id: 'update-lab'
      process_name: 'Оновлення даних про лабораторію'
      process_description: 'Регламент для оновлення даних про лабораторію'
      roles:
        - officer-first-rank
        - officer-second-rank
----
[IMPORTANT]
Обов'язкові поля: *process_definition_id*, *roles*


