= Підсистема управління секретами та шифруванням

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Підсистема що обслуговує процеси шифрування чутливих даних Реєстру та синхронізацію секретів у цільові сервіси Реєстрів.

== Функції підсистеми

* Шифрування / дешифрування даних
* Синхронізація та оновлення секретів між сховищем та Платформою оркестрації контейнерів

== Технічний дизайн підсистеми

image::architecture/registry/operational/secret-management/secret-and-cipher-management.drawio.svg[width=600,float="center",align="center"]

== Складові підсистеми

|===
|Назва компоненти|Представлення в реєстрі|Походження|Призначення

|_Сервіс управління секретами та шифруванням_
|`hashicorp-vault`
|3rd-party
|Безпечне зберігання ключів шифрування

|_Сервіс синхронізації секретів із платформної підсистеми управління секретами в OpenShift_
|`external-secrets-operator`
|3rd-party
|Автоматизує процес безпечного отримання та синхронізації конфіденційних даних з HashiCorp Vault, в OKD Secrets.

|_Сервіс оновлення секретів в цільових сервісах реєстру_
|`reloader`
|3rd-party
|Cпостереження за змінами в ConfigMaps та Secrets та їх оновлення на подах компонентів реєстру

|===

== Технологічний стек

* xref:arch:architecture/platform-technologies.adoc#vault[HashiCorp Vault]

== Атрибути якості підсистеми

=== _Security_
Підсистема використовує стійкі алгоритми шифрування для зберігання чутливих даних та реалізує надійний контроль доступу для них.

=== _Observability_
Підсистема записує детальну інформацію про спроби аутентифікації, отримання секретів та інші операції, що дозволяє
дотримуватися вимог відповідності.

Також, підсистема управління користувачами та ролями підтримує журналювання вхідних запитів та збір метрик продуктивності
для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--
