= Управління структурами таблиць моделі даних реєстру
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

include::admin-portal-data-model-problem-description.adoc[]

include::admin-portal-data-model-scenarious.adoc[]

== Out of scope
- Робота з типами даних
- Робота з аналітичними представленнями
- Вирішення конфліктів з використанням адмінпорталу менеджменту регламенту реєстру

== Принципи роботи зі змінами в БД

=== Існуючий механізм роботи зі змінами в БД

Існуючий механізм роботи зі змінами в БД базуєтсья на двух принципах:

- Cтворення liquibase changeset
- Збереження liquibase changeset в git

image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-luqibase-current-flow.svg[]

=== Розширений механізм роботи зі змінами в БД
Пропонується розширити існуючий механізм роботи зі змінами БД шляхом додавання DataModelSnapshot документу в git репозиторій, котрий буде відображати стан моделі даних.

image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-luqibase-extended-flow.svg[]

=== Основні концепції
- DataModelSnapshot model - JSON документи, що відображають стан моделі даних регламенту реєстру
- Diff Document - документ, що відображає різницю між двома станами моделі даних регламенту реєстру
- History Document - документ, що відображає історію змін мастер версії або версії- кандидату регламенту реєстру

=== Описання структури DataModelSnapshot
[NOTE]
Вищенаведена модель даних була отримана в результаті аналізу існуючого стану lqiuibase changelogs (включно з аналізом функціональності custom liquibase тегів)

[plantuml, db-tables-management-er, svg]
----
include::partial$architecture/registry/administrative/regulation-management/admin-portal/db-tables-management-er.puml[]
----


=== Опис структури файлів на файловій системі

DataModelSnapshot model має наступну структуру файлів на файловій системі

image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-datamodel-filestructure.svg[]

- Перелік таблиць визначається переліком файлів на файловій системі
- Ім'я файлу таблиць відповідає назві таблиці та має наступний вигляд: `<table-name>.json`
- Ім'я файлу role permission відповідає назві id role permission та має наступний вигляд: `<role-id>.json`

==== Тимчасова структура файлів на файловій системі (first iteration)

image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-datamodel-filestructure-simple.svg[]

=== Опис DataModelSnapshot формату даних
В якості технічного інструменту опису структури даних DataModelSnapshot використовується Json формат. В якості опису контракту документу використовується https://json-schema.org/[JsonSchema]

xref:arch:architecture/registry/administrative/regulation-management/admin-portal/data-model/admin-portal-data-model-json-schema-description.adoc[DataModelSnapshotSchema]

include::domain-model-description.adoc[]
include::domain-attributes-description.adoc[]

include::admin-portal-data-model-principles.adoc[]

== Опис технічного рішення

=== Container
image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-c4-container.svg[]

=== Admin portal API container
image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-c4-apiContainer.svg[]

=== CICD container
image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-c4-cicd-container.svg[]

== Сценарій взаємодії компонентів системи під час редагування структури таблиць регламенту реєстру
[plantuml, db-tables-management-sequence, svg]
----
include::partial$architecture/registry/administrative/regulation-management/admin-portal/db-tables-management-sequence.puml[]
----

== Загальна діаграма взаємодії компонентів системи під час редагування моделі даних регламенту реєстру

image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-component-structure.svg[]
