== Описання атрибутів доменної моделі

=== Table
|===
|Назва |Тип |Read only| Описання

|Name| string| true| |
HistoricalFlag| boolean|true||
ObjectReference||true||
Description| String|false||
|===

=== Column
|===
|Назва |Тип |Read only|Описання
|Name| string|true||
Description| string|false||
Type| enum[clarify types]|true||
DefaultValue| object|false||
NotNull| boolean|true||
Unique| boolean|true||
PrimaryKey| boolean|true|
|===

=== Index
|===
|Назва |Тип |Read only|Описання
|Name| string|true||
Columns| [{
name string
sorting: enum[ASC, DESC, NONE]
}]|false|
|===

=== Constraint
|===
|Назва |Тип |Read only|Описання
|Name| string|true||
Columns| array[columnName]|true|
|===

=== ForeignKey
|===
|Назва |Тип |Read only|Описання
|Name| string|true||
SourceColumnName| string|true||
TargetTable| string|true||
TargetColumnName| string|true||
|===

=== AccessRule
|===
|Назва |Тип |Read only|Описання
|ColumnName| string|true||
Actions| enum[CREATE, READ, UPDATE, DELETE]|false||
RoleNames| [roleName: string]|false||
|===