@startuml


autonumber
skinparam responseMessageBelowArrow true

actor "Client 1" as Client1
participant "Admin portal RestAPI" as Service
actor "Client 2" as Client2

Client1 -> Service: GET /versions/1/forms/form1 HTTP/1.1
Client1 <- Service: HTTP/1.1 200 OK; Etag: "abcde1"
activate Client1
Client2 -> Service: GET /versions/1/forms/form1 HTTP/1.1
Client2 <- Service: HTTP/1.1 200 OK; Etag: "abcde1"
activate Client2

Client1->Service: PUT /versions/1/forms/form1 HTTP/1.1; If-Match: "abcde1"
Client1<-Service: HTTP/1.1 200 OK; Etag: "abcde2"
deactivate Client1

Client2->Service: PUT /versions/1/forms/form1 HTTP/1.1; If-Match: "abcde1"
Client2<-Service: HTTP/1.1 412 Precondition Failed;
deactivate Client1

@enduml