= Підсистема управління зовнішнім трафіком операційної зони реєстру

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Підсистема, призначенням якої є управління зовнішнім трафіком та контроль доступу до API-сервісів операційної зони Реєстру.

== Функції підсистеми

* Аутентифікація та авторизація запитів
* Маршрутизація трафіку до API-сервісів підсистем операційної зони реєстру
* Налаштування та контроль рейт-лімітів
* Трансформація запитів та відповідей
* Логування вхідних запитів

== Технічний дизайн підсистеми

image::architecture/registry/operational/ext-api-management/registry-ext-traffic-subsystem.drawio.svg[width=600,float="center",align="center"]

== Складові підсистеми

|===
|Назва компоненти|Представлення в реєстрі|Походження|Призначення

|_Зовнішній API-шлюз операційної зони_
|`kong-kong`
|3rd-party
|Забезпечує керування трафіком, авторизацію, контроль доступу до API, балансування навантаження,
перетворення запитів/відповідей та аналітику/моніторинг.

|_ServiceMesh шлюз_
|`istio-ingressgateway`
|3rd-party
|Мережевий шлюз що працює на межі istio service-mesh та отримує вхідні з'єднання HTTP/TCP.

|_Операційне сховище сесій користувача_
|`redis:sessions`
|3rd-party
|Зберігання користувацьких JWT-токенів
|===

== Технологічний стек
* xref:arch:architecture/platform-technologies.adoc#kong[Kong]
* xref:arch:architecture/platform-technologies.adoc#kong-ingress-controller[Kong Ingress Controller]
* xref:arch:architecture/platform-technologies.adoc#redis[Redis]
* xref:arch:architecture/platform-technologies.adoc#istio[Istio ServiceMesh]

== Атрибути якості підсистеми
=== _Scalability_

Підсистема управління зовнішнім трафіком операційної зони реєстру підтримує як горизонтальне, так і вертикальне масштабування.
[TIP]
--
Детальніше з масштабуванням підсистем можна ознайомитись у розділі xref:architecture/container-platform/container-platform.adoc[]
--

=== _Observability_
Підсистема управління зовнішнім трафіком операційної зони реєстру підтримує журналювання вхідних запитів та збір метрик продуктивності для
подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--

=== _Portability_
Підсистема управління зовнішнім трафіком операційної зони реєстру може бути перенесена, розгорнута та керована однаково та надійно на різних
платформах оркестрації контейнерів що розгорнуті в різних хмарних середовищах або власній інфраструктурі в дата-центрі.

[TIP]
--
Детальніше можна ознайомитись у розділі xref:arch:architecture/container-platform/container-platform.adoc[Платформа оркестрації контейнерів]
--
