:toc-title: On this page:
:toc: auto
:toclevels: 5
:experimental:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Configuring custom DNS name for registry portals in OpenShift 4.x

NOTE: 🌐 This document is available in both English and Ukrainian. Use the language toggle in the top right corner to switch between versions.

//Функціонал для налаштування власного DNS імені для роутів кабінетів реєстрів в OpenShift 4.x кластері та забезпечення їх безпечного використання.
The functionality for custom DNS name configuration for *Platform for state registries* routes in OpenShift 4.x cluster, and provision of their safe usage.

//NOTE: Система доменних імен (англ. Domain Name System, DNS) — ієрархічна розподілена система перетворення імені будь-якого мережевого пристрою в IP-адресу.
NOTE: **Domain Name System, DNS** -- a hierarchical system for transforming the name of any network device into an IP-address.

//Зовнішній доступ до ресурсів кластера відбувається за допомогою роутів.
External access to cluster resources is performed via routes.

//NOTE: Роут (_англ. **Route**_) -- абстракція в конфігурації OpenShift, яка дозволяє розміщувати веб-додатки за загальнодоступною URL-адресою.
NOTE: **Route** -- an abstraction in OpenShift configuration, which allows for the deployment of web-applications at generally available URL.

include::custom-dns/custom-dns-technical-design.adoc[]

include::custom-dns/custom-dns-overview.adoc[]

include::custom-dns/custom-dns-external-configuration.adoc[]
