include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

= Deploying the Platform to production without registry development tools

include::platform:ROOT:partial$admonitions/language-en.adoc[]

//Цей документ містить інформацію про загальні положення та технічний дизайн при розгортанні Платформи реєстрів.
This document provides information on the general points and technical design during Platform deployment.

== General provisions

//* Компоненти, які задіяні у процесах розробки реєстрів не повинні розгортатись разом із продакшн версіями Платформи реєстрів.
* Components involved in the processes of registry development must not be deployed together with a production version of the Platform for state registries.
//* Публічні роути компонентів, які задіяні у процесах розробки реєстрів, не повинні створюватись разом із продакшн версіями Платформи реєстрів.
* Public routes of components involved in the processes of registry development must not be created together with a production version of the Platform for state registries.
* Registry template must include a variable to set the current Platform deployment mode.
//* Підтримується два режими деплоя: `production` та `development`.
* Two deployment modes are supported: `production` and `development`.

//=== Верхньорівневий технічний дизайн
== High-level technical design

The following table lists the components and their routes, which are involved, or need to be changed/created within the realization of functional requirements according to the technical solution design.

include::platform:ROOT:partial$templates/snippets/dev-prod-mode-en.adoc[]

//Для налаштування відповідних режимів для темплейтів потрібно вказати потрібний режим наступним чином:
To configure the corresponding modes for the templates, set the mode the following way:
----
global:
  deploymentMode: development
----

//У випадку необхідності розгортання реєстру без конкретного порталу (наприклад портала Громадянина), необхідно додати наступний параметр:
In case you need to deploy a registry without a defined Portal (Citizen Portal, for example), add the following parameter:
----
global:
  excludePortals: ['citizen']
----

//IMPORTANT: За замовчуванням змінна `excludePortals` відсутня, що означає розгортання всіх порталів.
IMPORTANT: By default, `excludePortals` variable is absent, which means the deployment of all Portals.

//При виключенні порталу громадянина з процессу розгортання, наступні сервіси також не повинні розгортатись:
Excluding Citizen Portal from deployment process means the following services must also not be deployed:

* citizen-portal
* ddm-notification-service
* user-service-api
* user-service-persistence
