:toc-title: On this page:
:toc: auto
:toclevels: 5
:experimental:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Secure resource publishing in OpenShift 4.x cluster

NOTE: 🌐 This document is available in both English and Ukrainian. Use the language toggle in the top right corner to switch between versions.

//Функціонал для безпечного публікування роутів в OpenShift 4.x кластері та механізму контролю доступу до ресурсів.
The functionality for secure route publishing in OpenShift 4.x cluster, and resource access control mechanism.

//Зовнішній доступ до ресурсів кластера відбувається за допомогою роутів.
External access to the resources is performed via routes.

//NOTE: Роут (_англ. **Route**_) -- абстракція в конфігурації OpenShift, яка дозволяє розміщувати веб-додатки за загальнодоступною URL-адресою.
NOTE: **Route** -- an abstraction in OpenShift configuration, which allows for the deployment of web-applications at generally available URL.

include::secure-endpoints/secure-endpoints-tech-design.adoc[]

include::secure-endpoints/secure-endpoints-overview.adoc[]

include::secure-endpoints/secure-endpoints-components.adoc[]

//Таким чином, запити з IP-адрес, яких немає в доданих анотаціях будуть відхилятись.
Consequently, requests from IP-addresses not listed in added annotations will be rejected.