:imagesdir: ../../../../../images
= Підсистема управління реляційними базами даних

== Загальний опис підсистеми

Підсистема керування реляційними базами даних надає надійне та масштабоване зберігання даних для сервісів реєстру. Підсистема використовує Crunchy PGO для управління кластерами PostgreSQL.

Підсистема забезпечує управління користувачами та схемами, за підтримки Liquibase для контролю версій схем баз даних. Крім того, підсистема підтримує географічні об'єкти та геолокаційні запити з використанням PostGIS, що дозволяє аналізувати та візуалізувати геопросторові дані.

Підсистема розроблена з масштабуванням на увазі, дозволяючи горизонтально масштабувати кластери PostgreSQL, щоб задовольнити змінні потреби. На випадок втрати даних або їх пошкодження, підсистема включає потужні функції резервного копіювання та відновлення, з автоматичними графіками резервного копіювання та можливістю відновлення на певний момент у часі.

Для забезпечення надійності та продуктивності підсистеми вона має вбудовані можливості моніторингу та логування, з метриками в реальному часі через Prometheus та Grafana. 

Сервіси реєстру використовують дану підсистему для зберігання своїх службових даних та даних реєстру.

== Функції підсистеми

* Зберігання даних реєстру
** Зберігання бізнес-даних
** Зберігання історії змін бізнес-даних
** Зберігання журналу подій аудиту
** Зберігання глобальних налаштувань
** Зберігання персональних налаштувань користувачів
** Зберігання стану виконання бізнес-процесів
* Контроль цілісності даних
* Підтримка географічних об'єктів та геолокаційних запитів
* Забезпечення механізмів контролю доступу до даних, автентифікації та авторизації
* Резервне копіювання та відновлення, в тому числі відновлення на момент часу (PITR)
* Підтримка горизонтального масштабування
* Підтримка комплексної аналітики та звітності

== Технічний дизайн підсистеми

image::architecture/registry/operational/relational-data-storage/registry-rdbms.svg[float="center",align="center"]

Підсистема керування реляційними базами даних складається з двох екземплярів СКРБД _(Систем керування реляційними базами даних)_, а саме операційного та аналітичного. Операційний екземпляр містить БД сервісів і БД реєстру, тоді як аналітичний екземпляр містить аналітичну БД реєстру яка наповнюється за допомогою реплікації з БД реєстру операційного екземпляру. Процес реплікації реалізовано за допомогою логічної реплікації Postgres, яка керується та налаштовується підсистемою розгортання реєстру. Нарешті, аналітичний екземпляр в основному використовується підсистемою аналітичної звітності реєстру для комплексної аналітики та звітності щодо даних, що зберігаються в БД реєстру.

Кожен екземпляр складається з компонентів представлених на наступній діаграмі:

image::architecture/registry/operational/relational-data-storage/rdbms-component-architecture.svg[float="center",align="center"]

PgPool II та Replica поди необов'язкові та розгортаються в залежності від потреб. На аналітичному екземплярі не розгортається PgPool II, оскільки розділення читання/запису на ньому не потрібно. А при роботі в режимі "без масштабування" не розгортаються Replica поди на обох екземплярах.

== Компоненти підсистеми
[options="header",cols="a,a,a,a"]
|===
|Назва компоненти|Представлення в платформі|Походження|Призначення

|_Операційний екземпляр СКБД_
|`operational` +
`operational-pool`
|3rd-party
|Екземпляр СКБД що обробляє операційні запити сервісів. Містить операційні бази сервісів та операційну базу реєстру.

|_Аналітичний екземпляр СКБД_
|`analytical`
|3rd-party
|Екземпляр СКБД що обробляє аналітичні запити підсистеми аналітичної звітності. Містить аналітичну базу реєстру.

|_Задача керування об'єктами БД_
|`run-db-scripts-job`
|1st-party
|Відповідальна за створення та оновлення баз даних, користувачів та службових схем БД 

|_Crunchy Postgres Оператор_
|`pgo` +
`pgo-upgrade`
|3rd-party
|Відповідальний за розгортання та конфігурацію екземплярів кластерів PostgreSQL
|===

== Атрибути якості підсистеми

=== _Scalability_

_Підсистема керування реляційними базами даних_ підтримує вертикальне та горизонтальне масштабування у разі збільшення навантаження шляхом виділення додаткових ресурсів для подів підсистеми або використання механізмів описаних у розділі xref:arch:architecture/registry/operational/relational-data-storage/rdbms-horizontal-scaling.adoc[Горизонтальне масштабування].

=== _Security_

_Підсистема керування реляційними базами даних_ забезпечує захист каналу інформаційної взаємодії між сервісами підсистеми за допомогою _SSL/TLS_ шифрування трафіку. Також вона надає можливість _SSL/TLS_ шифрування трафіку при взаємодії з іншими підсистемами.

Для підсистеми налаштовані мережеві політики які дозволяють мережеву взаємодію тільки з сервісами внесеними у білий список.

Для кожного сервісу створені окремі користувачі БД. Їм видані мінімальні привілеями необхідні для роботи.

Дані зберігаються у _Підсистемі розподіленого зберігання файлів_ та використовують її можливості забезпечення безпеки.

=== _Performance_

Висока продуктивність _Підсистеми керування реляційними базами даних_ досягається завдяки:

* Використання найкращих практик при моделюванні БД.
* Відокремленню бази даних для аналітичних робочих навантажень.
* Використанню механізму xref:arch:architecture/registry/operational/relational-data-storage/rdbms-horizontal-scaling.adoc[горизонтального масштабування].

=== _Observability_

_Підсистема керування реляційними базами даних_ підтримує журналювання вхідних запитів та збір xref:arch:architecture/registry/operational/relational-data-storage/rdbms-monitoring.adoc[метрик продуктивності] для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--

===  _Reliability_
Надійність _Підсистеми керування реляційними базами даних_ забезпечується вбудованими функціями xref:arch:architecture/registry/operational/relational-data-storage/rdbms-backup-recovery.adoc[резервного копіювання та відновлення], з автоматичними графіками резервного копіювання та можливістю відновлення на певний момент у часі.

Додатково до внутрішніх механізмів резервного копіювання, 
xref:architecture/platform/operational/backup-recovery/overview.adoc[підсистема резервного копіювання та відновлення] включає у себе резервне копіювання файлових систем БД.