//:imagesdir: ../../../../../../images
= Підсистема управління реляційними базами даних

== Загальний опис підсистеми

Підсистема керування реляційними базами даних надає надійне та масштабоване зберігання даних для сервісів реєстру. Підсистема використовує Crunchy PGO для управління кластерами PostgreSQL.

Підсистема забезпечує управління користувачами та схемами, за підтримки Liquibase для контролю версій схем баз даних. Крім того, підсистема підтримує географічні об'єкти та геолокаційні запити з використанням PostGIS, що дозволяє аналізувати та візуалізувати геопросторові дані.

Підсистема розроблена з масштабуванням на увазі, дозволяючи горизонтально масштабувати кластери PostgreSQL, щоб задовольнити змінні потреби. На випадок втрати даних або їх пошкодження, підсистема включає потужні функції резервного копіювання та відновлення, з автоматичними графіками резервного копіювання та можливістю відновлення на певний момент у часі.

Для забезпечення надійності та продуктивності підсистеми вона має вбудовані можливості моніторингу та логування, з метриками в реальному часі через Prometheus та Grafana. 

Сервіси реєстру використовують дану підсистему для зберігання своїх службових даних та даних реєстру.

== Функції підсистеми

* Зберігання даних реєстру
** Зберігання бізнес-даних
** Зберігання історії змін бізнес-даних
** Зберігання журналу подій аудиту
** Зберігання глобальних налаштувань
** Зберігання персональних налаштувань користувачів
** Зберігання стану виконання бізнес-процесів
* Контроль цілісності даних
* Підтримка географічних об'єктів та геолокаційних запитів
* Забезпечення механізмів контролю доступу до даних, автентифікації та авторизації
* Резервне копіювання та відновлення, в тому числі відновлення на момент часу (PITR)
* Підтримка горизонтального масштабування
* Підтримка комплексної аналітики та звітності

== Технічний дизайн підсистеми
=== Високорівневий огляд

image::architecture/registry/operational/relational-data-storage/registry-rdbms.svg[float="center",align="center"]

Підсистема керування реляційними базами даних складається з двох екземплярів СКРБД _(Систем керування реляційними базами даних)_, а саме операційного та аналітичного. Операційний екземпляр містить БД сервісів і БД реєстру, тоді як аналітичний екземпляр містить аналітичну БД реєстру яка наповнюється за допомогою реплікації з БД реєстру операційного екземпляру. Процес реплікації реалізовано за допомогою логічної реплікації Postgres, яка керується та налаштовується підсистемою розгортання реєстру. Нарешті, аналітичний екземпляр в основному використовується підсистемою аналітичної звітності реєстру для комплексної аналітики та звітності щодо даних, що зберігаються в БД реєстру.

Кожен екземпляр складається з компонентів представлених на наступній діаграмі:

image::architecture/registry/operational/relational-data-storage/rdbms-component-architecture.svg[float="center",align="center"]

PgPool II та Replica поди необов'язкові та розгортаються в залежності від потреб. На аналітичному екземплярі не розгортається PgPool II, оскільки розділення читання/запису на ньому не потрібно. А при роботі в режимі "без масштабування" не розгортаються Replica поди на обох екземплярах.


=== Географічні об'єкти та геолокаційні запити
Підтримка географічних об'єктів та геолокаційних запитів реалізована за допомогою розширення PostGIS

PostGIS - це відкрите програмне забезпечення, розширення системи управління базами даних PostgreSQL. Воно дозволяє зберігати, обробляти та аналізувати географічні дані, такі як точки, лінії та полігони. PostGIS надає широкий спектр функцій та операторів для роботи з просторовими даними, включаючи розрахунки відстаней, обчислення площі та просторові з'єднання. 

Ця функціональність зокрема використовується xref:arch:architecture/registry/operational/geo/overview.adoc[підсистемою управління гео-даними] для збереження, пошуку і візуалізації даних про географічні об'єкти. 

=== Горизонтальне масштабування

Реалізована горизонтально масштабована архітектура для бази даних PostgreSQL, призначена для динамічного додавання та видалення вузлів та дозволяє збільшувати продуктивність системи за потребою та економити ресурси, коли навантаження зменшується.

У цій архітектурі використовується Crunchy PGO для управління PostgreSQL та керування репліками "лише для читання", додаючи або видаляючи їх згідно з налаштуваннями.

Додатково використовується PgPool-II для маршрутизації всіх запитів до бази даних на відповідні вузли. PgPool-II є потужним проміжним програмним забезпеченням, яке діє як проксі між клієнтами та вузлами бази даних PostgreSQL.

Всі запити на запис PgPool-II відправляє до primary вузла, який відповідає за управління головною копією бази даних. У режимі синхронної реплікації всі репліки отримують запити та реплікують дані з первинного вузла. Це забезпечує, те що всі вузли мають однакові дані, і будь-які зміни, внесені в первинний вузол, з'являються на репліках в режимі реального часу.

Для запитів, які не передбачають запис, PgPool-II балансує навантаження між всіма вузлами. Це допомагає розподілити роботу між усіма вузлами та покращити загальну продуктивність та час відгуку системи.

[TIP]
--
З деталями можна ознайомитись у статті xref:arch:architecture/registry/operational/relational-data-storage/db-scaling.adoc[]
--

=== Резервне копіювання та відновлення
Postgres Operator від Crunchy Data (PGO), який використовується для управління БД реєстру,включає в себе pgBackRest - рішення для резервного копіювання та відновлення з відкритим кодом. PGO та pgBackRest роблять зручним виконання багатьох поширених дій, необхідних протягом життєвого циклу бази даних, зокрема:

* Налаштування розкладів автоматичного резервного копіювання та політик збереження
* Резервне копіювання даних у декілька місць
**  Підтримка резервного сховища в Kubernetes, AWS S3 (або S3-сумісних системах, таких як MinIO), Google Cloud Storage (GCS) і Azure Blob Storage
* Одноразове створення резервних копій
* Виконання «відновлення на певний момент часу» (PITR)
* Клонування даних у новий екземпляр БД

За замовчанням налаштоване автоматичне резервне копіювання в _сховище резервних копій платформи_.

[TIP]
--
З деталями можна ознайомитись у статті xref:admin:backup-restore/postgres-backup-restore.adoc[]
--

=== Моніторинг

Архітектура включає в себе використання Postgres exporter та xref:arch:architecture/platform/operational/monitoring/overview.adoc[підсистеми моніторингу подій та сповіщення] для моніторингу та візуалізації метрик з баз даних PostgreSQL.

Postgres exporter - це інструмент, який збирає метрики з сервера PostgreSQL та викладає їх у форматі, який може бути зібраний сервісом Prometheus _підсистеми моніторингу подій та сповіщення_.

Postgres exporter встановлено на сервері PostgreSQL та налаштовано для збору необхідних метрик з бази даних. А в  _підсистемі моніторингу подій та сповіщення_ встановлено інформаційні панелі які візуалізують ці метрики.

До набору встановлених інформаційних панелей входять:

* *Overview* - надає огляд усіх кластерів PostgreSQL розгорнутих на платформі.
* *PostgreSQL Details* - надає більше інформації про конкретний кластер PostgreSQL. Включає багато ключових, специфічних для PostgreSQL, метрик.
* *Pod details* - надає інформацію про  використання ресурсів конкретними подами, які використовуються кластером PostgreSQL.
* *Backup details* - надає інформацію про загальний стан резервних копій pgBackRest.
* *Service Health* - містить інформацію про служби Kubernetes, які розташовані перед PostgreSQL Pods. Це надає інформацію про стан мережі.
* *Query Statistics* - надає інформацію про загальну продуктивність запитів.

Цей набір дозволяє адміністраторам відстежувати продуктивність бази даних протягом часу та виявляти потенційні проблеми до того, як вони стануть критичними. 

=== Обробка аналітичних запитів

Для обробки аналітичних запитів до БД реєстру архітектура передбачає окремий, аналітичний, екземпляр СКРБД. 

Для передачі даних з операційної бази даних реєстру до аналітичної використовується логічна реплікація PostgreSQL. Вона підтримує синхронізацію даних в реальному часі з мінімальною затримкою, вибіркову реплікацію, гнучкість схеми аналітичної бази та має мінімальний вплив на продуктивність операційної бази даних.

Відокремлення бази даних для аналітичних робочих навантажень надає наступні можливості та переваги:

* Швидкість виконання запитів: Аналітичні робочі навантаження зазвичай включають складні запити та обробку великих наборів даних. З відокремленою базою даних, оптимізованою для аналітики, дані можуть бути структуровані та індексовані таким чином, що збільшують швидкість виконання запитів.

* Покращена масштабованість: Відокремлення аналітичного навантаження від операційного покращує масштабованість. Оскільки аналітичні запити зазвичай вимагають багато ресурсів, вони можуть сповільнювати інші процеси, які залежать від тієї ж бази даних. Шляхом відокремлення аналітичного навантаження, можливо масштабувати кожне навантаження незалежно, щоб задовольнити змінні вимоги.

* Зменшення ризику: Відокремлення аналітичного та операційного навантажень зменшує ризик відмови операційного екземпляру БД через помилки або проблеми з продуктивністю, пов'язані з аналітичними запитами.

* Краще управління даними: Відокремлена аналітична база забезпечує чітке розмежування між операційними даними та аналітичними даними. Це полегшує забезпечення дотримання політик, пов'язаних із доступом до даних, безпекою та відповідністю.

=== Керування користувачами та схемами БД

Облікові дані авторизації користувачів баз даних зберігаються у секретах Kubernetes.

Для керування змінами схеми використовується журнал змін Liquibase, який є повним списком усіх змін, внесених до схем баз даних. Цей журнал змін також містить інформацію про користувачів та привілеї, і використовує дані авторизації з секретів Kubernetes для створення та зміни користувачів баз даних.

Усі журнали змін пакуються разом як задача _run-db-scripts_ під час релізу. Задача _run-db-scripts_ використовує Liquibase для застосування журналів змін до бази даних.  Ця задача інтегрується в процес розгортання реєстру та виконується при кожному встановленні або оновленні реєстру. Це забезпечує однакове та автоматичне застосування будь-яких змін до схем баз даних чи привілеїв користувачів.

В цілому, це рішення дозволяє ефективно та безпечно керувати користувачами та схемою бази даних, ведучи детальний журнал змін та автоматично виконуючи їх під час процесу розгортання.

[TIP]
--
Із списком користувачів БД можна ознайомитися у розділі xref:arch:architecture/registry/operational/relational-data-storage/db-roles.adoc[Користувачі бази даних реєстру та їх привілеї].
Схеми баз даних описани у розділах відповідних підсистем які їх використовують.
--

== Компоненти підсистеми
[options="header",cols="a,a,a,a"]
|===
|Назва компоненти|Представлення в платформі|Походження|Призначення

|_Операційний екземпляр СКБД_
|`operational` +
`operational-pool`
|3rd-party
|Екземпляр СКБД що обробляє операційні запити сервісів. Містить операційні бази сервісів та операційну базу реєстру.

|_Аналітичний екземпляр СКБД_
|`analytical`
|3rd-party
|Екземпляр СКБД що обробляє аналітичні запити підсистеми аналітичної звітності. Містить аналітичну базу реєстру.

|_Задача керування об'єктами БД_
|`run-db-scripts-job`
|1st-party
|Відповідальна за створення та оновлення баз даних, користувачів та службових схем БД 

|_Crunchy Postgres Оператор_
|`pgo` +
`pgo-upgrade`
|3rd-party
|Відповідальний за розгортання та конфігурацію екземплярів кластерів PostgreSQL
|===

== Атрибути якості підсистеми

=== _Scalability_

_Підсистема керування реляційними базами даних_ підтримує вертикальне та горизонтальне масштабування у разі збільшення навантаження шляхом виділення додаткових ресурсів для подів підсистеми або використання механізмів описаних у розділі <<_горизонтальне_масштабування>>.

=== _Security_

_Підсистема керування реляційними базами даних_ забезпечує захист каналу інформаційної взаємодії між сервісами підсистеми за допомогою _SSL/TLS_ шифрування трафіку. Також вона надає можливість _SSL/TLS_ шифрування трафіку при взаємодії з іншими підсистемами.

Для підсистеми налаштовані мережеві політики які дозволяють мережеву взаємодію тільки з сервісами внесеними у білий список.

Для кожного сервісу створені окремі користувачі БД. Їм видані мінімальні привілеями необхідні для роботи.

Дані зберігаються у _Підсистемі розподіленого зберігання файлів_ та використовують її можливості забезпечення безпеки.

=== _Performance_

Висока продуктивність _Підсистеми керування реляційними базами даних_ досягається завдяки:

* Використання найкращих практик при моделюванні БД.
* Відокремленню бази даних для аналітичних робочих навантажень.
* Використанню механізму <<_горизонтальне_масштабування,горизонтального масштабування>>.

=== _Observability_

_Підсистема керування реляційними базами даних_ підтримує журналювання вхідних запитів та збір <<_моніторинг,метрик продуктивності>> для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--

===  _Reliability_
Надійність _Підсистеми керування реляційними базами даних_ забезпечується вбудованими функціями <<_резервне_копіювання_та_відновлення,резервного копіювання>> та відновлення, з автоматичними графіками резервного копіювання та можливістю відновлення на певний момент у часі.

Додатково до внутрішніх механізмів резервного копіювання, 
xref:architecture/platform/operational/backup-recovery/overview.adoc[підсистема резервного копіювання та відновлення] включає у себе резервне копіювання файлових систем БД.