:imagesdir: ../../../../../images
= Підсистема управління реляційними базами даних

== Загальний опис підсистеми

_Підсистема управління реляційними базами_ даних надає надійне та масштабоване зберігання даних для сервісів реєстру. Підсистема використовує _Crunchy PGO_ для управління кластерами _PostgreSQL_.

Підсистема забезпечує управління користувачами та схемами, за підтримки _Liquibase_ для контролю версій схем баз даних. Крім того, підсистема підтримує географічні об'єкти та геолокаційні запити з використанням _PostGIS_, що дозволяє аналізувати та візуалізувати геопросторові дані.

Підсистема розроблена з врахуванням вимог до масштабування, дозволяючи горизонтально масштабувати кластери _PostgreSQL_, щоб задовольнити змінні потреби. На випадок втрати даних або їх пошкодження, підсистема включає потужні функції резервного копіювання та відновлення, з автоматичними графіками резервного копіювання та можливістю відновлення на певний момент у часі.

Для забезпечення надійності та продуктивності підсистеми вона має вбудовані можливості моніторингу та логування, з метриками в реальному часі через _Prometheus_ та _Grafana_.

Сервіси реєстру використовують дану підсистему для зберігання своїх службових даних та даних реєстру.

== Функції підсистеми

* Зберігання даних реєстру
** Зберігання бізнес-даних
** Зберігання історії змін бізнес-даних
** Зберігання журналу подій аудиту
** Зберігання глобальних налаштувань
** Зберігання персональних налаштувань користувачів
** Зберігання стану виконання бізнес-процесів
* Контроль цілісності даних
* Підтримка географічних об'єктів та геолокаційних запитів
* Забезпечення механізмів контролю доступу до даних, автентифікації та авторизації
* Резервне копіювання та відновлення, в тому числі відновлення на момент часу (PITR)
* Підтримка горизонтального масштабування
* Підтримка комплексної аналітики та звітності

== Технічний дизайн підсистеми

image::architecture/registry/operational/relational-data-storage/registry-rdbms.svg[float="center",align="center",width=500]

_Підсистема управління реляційними базами даних_ складається з двох екземплярів СКБД _(Систем керування базами даних)_, а саме операційного (_Operational Instance_) та аналітичного (_Analytical Instance_). Операційний екземпляр містить БД сервісів і БД реєстру, тоді як аналітичний екземпляр містить аналітичну БД реєстру яка наповнюється за допомогою реплікації з БД реєстру операційного екземпляру.

Процес реплікації реалізовано за допомогою логічної реплікації _Postgres_, яка керується та налаштовується підсистемою розгортання реєстру.

Нарешті, аналітичний екземпляр в основному використовується підсистемою аналітичної звітності реєстру для комплексної аналітики та звітності щодо даних, що зберігаються в БД реєстру.

Кожен екземпляр складається з компонентів представлених на наступній діаграмі:

image::architecture/registry/operational/relational-data-storage/rdbms-component-architecture.svg[float="center",align="center",width=700]

* Компонент _PostgresCluster_ instance представляє собою кластер _PostgreSQL_, який керується _Crunchy Postgres_ оператором. Цей оператор відповідає за керування такими ресурсами:
** _PostgreSQL Primary_ под: Основний (primary) под бази даних _PostgreSQL_, який використовується для запису даних та виконання транзакцій.
** _PostgreSQL Replica_ поди: Додаткові (replica), доступні лише на читання, поди бази даних _PostgreSQL_, які створюються лише у випадку, коли налаштовано масштабування на 2 або більше поди.
** Сервіси екземпляру _PostgresCluster_: Сервіси _Kubernetes_ що забезпечують балансування навантаження та надання стабільної IP-адреси та доменного імені.
** Налаштування резервного копіювання: Конфігураційні параметри, які визначають політику резервного копіювання та зберігання резервних копій бази даних.
** Налаштування експорту метрик для моніторингу: Конфігураційні параметри, які визначають, які метрики бази даних експортуються для моніторингу та аналізу.

* Компонент _PgPool II_ виконує роль проміжного рівня між додатками та кластером _PostgreSQL_. Він забезпечує прозоре та автоматичне розділення запитів на читання та запис з перенаправленням їх на відповідні сервіси екземпляру _PostgresCluster_. Цей компонент і його сервіс керуються безпосередньо, без допомоги оператора.


NOTE: Для економії ресурсів под _PgPool II_ та сервіс _pool_ не створюються на _аналітичному екземплярі СКБД_, оскільки жоден сервіс що працює з ним не потребує автоматичного розділення запитів на читання та запитів на запис

Доступ до екземпляру СКБД надається через 4 сервіси які виконують наступні функції:

* _Primary_ - направляє запити на primary под, який дає можливість читання та запису БД. Використовується для підключення до БД службовими додатками які вносять зміни у БД але не потребують балансування навантаження, наприклад _Задачею керування об’єктами БД_
* _Replica_ - балансує запити між replica подами, які дають тільки можливість читання БД. Наразі використовується тільки PgPool II для автоматичного перенаправлення запитів на читання
* _Pods_ - балансує запити між всіма подами, primary і replica. Використовується додатками які здійснюють тільки читання БД, наприклад _Підсистемою аналітичної звітності реєстру_
* _Pool_ - направляє запити на PgPool II, який автоматично балансує запити на читання між всіма подами, а запити на запис направляє на primary под. Використовується додатками які здійснюють як читання так і запис БД та потребують балансування навантаження, тобто переважною більшістю додатків реєстру.

NOTE: На розгорнутому оточенні імена ресурсів доповнюються префіксом з іменем екземпляра СКБД. Наприклад `operational-pool` чи `analytical-pods`.

== Компоненти підсистеми
[options="header",cols="a,a,a,a,a"]
|===
|Назва компоненти|Представлення в платформі|Походження|Репозиторій|Призначення

|_Операційний екземпляр СКБД_
|`operational` +
`operational-pool`
|3rd-party
.4+|https://github.com/epam/edp-ddm-registry-postgres[github:/epam/edp-ddm-registry-postgres]
|Екземпляр СКБД що обробляє операційні запити сервісів. Містить операційні бази сервісів та операційну базу реєстру.

|_Аналітичний екземпляр СКБД_
|`analytical`
|3rd-party
|Екземпляр СКБД що обробляє аналітичні запити підсистеми аналітичної звітності. Містить аналітичну базу реєстру.

|_Задача керування об'єктами БД_
|`run-db-scripts-job`
|origin
|Відповідальна за створення та оновлення баз даних, користувачів та службових схем БД

|_Crunchy Postgres Оператор_
|`pgo` +
`pgo-upgrade`
|3rd-party
|Відповідальний за розгортання та конфігурацію екземплярів кластерів _PostgreSQL_
|===

== Технологічний стек

При проектуванні та розробці підсистеми, були використані наступні технології:

* xref:arch:architecture/platform-technologies.adoc#postgresql[PostgreSQL]
* xref:arch:architecture/platform-technologies.adoc#crunchy-operator[CrunchyData Postgres Operator]
* xref:arch:architecture/platform-technologies.adoc#pgpool[Pgpool]
* xref:arch:architecture/platform-technologies.adoc#postgis[PostGIS]
* xref:arch:architecture/platform-technologies.adoc#pgbackrest[pgBackRest]

== Атрибути якості підсистеми

=== _Scalability_

_Підсистема управління реляційними базами даних_ підтримує вертикальне та горизонтальне масштабування у разі збільшення навантаження шляхом виділення додаткових ресурсів для подів підсистеми або використання механізмів описаних у розділі xref:arch:architecture/registry/operational/relational-data-storage/rdbms-horizontal-scaling.adoc[Горизонтальне масштабування].

=== _Security_

_Підсистема управління реляційними базами даних_ забезпечує захист каналу інформаційної взаємодії між сервісами підсистеми за допомогою _SSL/TLS_ шифрування трафіку. Також вона надає можливість _SSL/TLS_ шифрування трафіку при взаємодії з іншими підсистемами.

Для підсистеми налаштовані мережеві політики які дозволяють мережеву взаємодію тільки з сервісами внесеними у білий список.

Для кожного сервісу створені окремі користувачі БД. Їм видані мінімальні привілеями необхідні для роботи.

Дані зберігаються у _Підсистемі розподіленого зберігання файлів_ та використовують її можливості забезпечення безпеки.

=== _Performance_

Висока продуктивність _Підсистеми управління реляційними базами даних_ досягається завдяки:

* Використання найкращих практик при моделюванні БД.
* Відокремленню бази даних для аналітичних робочих навантажень.
* Використанню механізму xref:arch:architecture/registry/operational/relational-data-storage/rdbms-horizontal-scaling.adoc[горизонтального масштабування].

=== _Observability_

_Підсистема управління реляційними базами даних_ підтримує журналювання вхідних запитів та збір xref:architecture/platform/operational/monitoring/rdbms-monitoring.adoc[метрик продуктивності] для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--

===  _Reliability_
Надійність _Підсистеми управління реляційними базами даних_ забезпечується вбудованими функціями xref:arch:architecture/registry/operational/relational-data-storage/rdbms-backup-recovery.adoc[резервного копіювання та відновлення], з автоматичними графіками резервного копіювання та можливістю відновлення на певний момент у часі.

Додатково до внутрішніх механізмів резервного копіювання, 
xref:architecture/platform/operational/backup-recovery/overview.adoc[підсистема резервного копіювання та відновлення] включає у себе резервне копіювання файлових систем БД.
