= Горизонтальне масштабування

Реалізована горизонтально масштабована архітектура для бази даних _PostgreSQL_, призначена для динамічного додавання та видалення вузлів та дозволяє збільшувати продуктивність системи за потребою та економити ресурси, коли навантаження зменшується.

У цій архітектурі використовується _Crunchy PGO_ для управління _PostgreSQL_ та керування репліками "лише для читання", додаючи або видаляючи їх згідно з налаштуваннями.

Додатково використовується _PgPool-II_ для маршрутизації всіх запитів до бази даних на відповідні вузли. _PgPool-II_ є потужним проміжним програмним забезпеченням, яке діє як проксі між клієнтами та вузлами бази даних _PostgreSQL_.

Всі запити на запис _PgPool-II_ відправляє до primary вузла, який відповідає за управління головною копією бази даних. У режимі синхронної реплікації всі репліки отримують запити та реплікують дані з первинного вузла. Це забезпечує, те що всі вузли мають однакові дані, і будь-які зміни, внесені в первинний вузол, з'являються на репліках в режимі реального часу.

Для запитів, які не передбачають запис, _PgPool-II_ балансує навантаження між всіма вузлами. Це допомагає розподілити роботу між усіма вузлами та покращити загальну продуктивність та час відгуку системи.