= Резервне копіювання та відновлення
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

_Postgres Operator_ від _Crunchy Data (PGO)_, який використовується для управління БД реєстру, включає в себе _pgBackRest_ - рішення для резервного копіювання та відновлення з відкритим кодом. PGO та pgBackRest роблять зручним виконання багатьох поширених дій, необхідних протягом життєвого циклу бази даних, зокрема:

* Налаштування розкладів автоматичного резервного копіювання та політик збереження
* Резервне копіювання даних у декілька місць
**  Підтримка резервного сховища в _Kubernetes_, _AWS S3_ (або _S3_-сумісних системах, таких як _MinIO_), _Google Cloud Storage (GCS)_ і _Azure Blob Storage_
* Одноразове створення резервних копій
* Виконання «відновлення на певний момент часу» (PITR)
* Клонування даних у новий екземпляр БД

За замовчанням налаштоване автоматичне резервне копіювання в _сховище резервних копій платформи_.

[TIP]
--
З деталями можна ознайомитись у статті xref:admin:backup-restore/postgres-backup-restore.adoc[]
--