= Керування користувачами та схемами БД

Облікові дані авторизації користувачів баз даних зберігаються у секретах Kubernetes.

Для керування змінами схеми використовується журнал змін Liquibase, який є повним списком усіх змін, внесених до схем баз даних. Цей журнал змін також містить інформацію про користувачів та привілеї, і використовує дані авторизації з секретів Kubernetes для створення та зміни користувачів баз даних.

Усі журнали змін пакуються разом як задача _run-db-scripts_ під час релізу. Задача _run-db-scripts_ використовує Liquibase для застосування журналів змін до бази даних.  Ця задача інтегрується в процес розгортання реєстру та виконується при кожному встановленні або оновленні реєстру. Це забезпечує однакове та автоматичне застосування будь-яких змін до схем баз даних чи привілеїв користувачів.

В цілому, це рішення дозволяє ефективно та безпечно керувати користувачами та схемою бази даних, ведучи детальний журнал змін та автоматично виконуючи їх під час процесу розгортання.

[TIP]
--
Із списком користувачів БД можна ознайомитися у розділі xref:arch:architecture/registry/operational/relational-data-storage/db-roles.adoc[Користувачі бази даних реєстру та їх привілеї].

Із списком баз даних можна ознайомитися у розділі xref:arch:architecture/registry/operational/relational-data-storage/databases.adoc[Бази даних]

Опис та схеми баз даних представлені у розділах відповідних підсистем яким належить БД.
--