= Моніторинг

Архітектура включає в себе використання Postgres exporter та xref:arch:architecture/platform/operational/monitoring/overview.adoc[підсистеми моніторингу подій та сповіщення] для моніторингу та візуалізації метрик з баз даних PostgreSQL.

Postgres exporter - це інструмент, який збирає метрики з сервера PostgreSQL та викладає їх у форматі, який може бути зібраний сервісом Prometheus _підсистеми моніторингу подій та сповіщення_.

Postgres exporter встановлено на сервері PostgreSQL та налаштовано для збору необхідних метрик з бази даних. А в  _підсистемі моніторингу подій та сповіщення_ встановлено інформаційні панелі які візуалізують ці метрики.

До набору встановлених інформаційних панелей входять:

* *Overview* - надає огляд усіх кластерів PostgreSQL розгорнутих на платформі.
* *PostgreSQL Details* - надає більше інформації про конкретний кластер PostgreSQL. Включає багато ключових, специфічних для PostgreSQL, метрик.
* *Pod details* - надає інформацію про  використання ресурсів конкретними подами, які використовуються кластером PostgreSQL.
* *Backup details* - надає інформацію про загальний стан резервних копій pgBackRest.
* *Service Health* - містить інформацію про служби Kubernetes, які розташовані перед PostgreSQL Pods. Це надає інформацію про стан мережі.
* *Query Statistics* - надає інформацію про загальну продуктивність запитів.

Цей набір дозволяє адміністраторам відстежувати продуктивність бази даних протягом часу та виявляти потенційні проблеми до того, як вони стануть критичними. 