= Обробка аналітичних запитів

include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

Для обробки аналітичних запитів до БД реєстру архітектура передбачає окремий, аналітичний, екземпляр СКРБД. 

Для передачі даних з операційної бази даних реєстру до аналітичної використовується логічна реплікація _PostgreSQL_. Вона підтримує синхронізацію даних в реальному часі з мінімальною затримкою, вибіркову реплікацію, гнучкість схеми аналітичної бази та має мінімальний вплив на продуктивність операційної бази даних.

Відокремлення бази даних для аналітичних робочих навантажень надає наступні можливості та переваги:

* Швидкість виконання запитів: Аналітичні робочі навантаження зазвичай включають складні запити та обробку великих наборів даних. З відокремленою базою даних, оптимізованою для аналітики, дані можуть бути структуровані та індексовані таким чином, що збільшують швидкість виконання запитів.

* Покращена масштабованість: Відокремлення аналітичного навантаження від операційного покращує масштабованість. Оскільки аналітичні запити зазвичай вимагають багато ресурсів, вони можуть сповільнювати інші процеси, які залежать від тієї ж бази даних. Шляхом відокремлення аналітичного навантаження, можливо масштабувати кожне навантаження незалежно, щоб задовольнити змінні вимоги.

* Зменшення ризику: Відокремлення аналітичного та операційного навантажень зменшує ризик відмови операційного екземпляру БД через помилки або проблеми з продуктивністю, пов'язані з аналітичними запитами.

* Краще управління даними: Відокремлена аналітична база забезпечує чітке розмежування між операційними даними та аналітичними даними. Це полегшує забезпечення дотримання політик, пов'язаних із доступом до даних, безпекою та відповідністю.