= Збереження даних

include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

Опис збереження даних на платформі є важливою складовою інформаційної безпеки та прозорої роботи з даними. У цьому документі описуються ключові аспекти політики та стратегії збору, зберігання та видалення даних з платформи реєстрів.

== Збір та Завантаження Даних

Платформа збирає дані від користувачів через різноманітні інтеракції, такі як реєстрація, використання сервісів та комунікація через кабінети користувача. При використанні розробником регламенту інтеграцій з зовнішніми системами бізнес процеси можуть отримувати необхідні дані від інших реєстрів.

Дані вводяться та передаються через зашифроване з'єднання для забезпечення конфіденційності.

|===
| Види даних | Підсистеми які збирають дані | Місце збереження

| Дані завантажені користувачем 
| xref:arch:architecture/registry/operational/portals/overview.adoc[Підсистема кабінетів користувачів]
a| 
- xref:arch:architecture/registry/operational/relational-data-storage/overview.adoc[Операційна БД Підсистеми управління реляційними базами даних]
- xref:arch:architecture/platform/operational/distributed-data-storage/overview.adoc[Підсистема розподіленого зберігання даних] 


| Дані завантажені при міжреєстровій взаємодії 
| xref:arch:architecture/registry/operational/external-integrations/overview.adoc[Підсистема зовнішніх інтеграцій]
a|
- xref:arch:architecture/registry/operational/relational-data-storage/overview.adoc[Операційна БД Підсистеми управління реляційними базами даних]
- xref:arch:architecture/platform/operational/distributed-data-storage/overview.adoc[Підсистема розподіленого зберігання даних] 

| Тимчасові дані бізнес процесів
| xref:arch:architecture/registry/operational/bpms/overview.adoc[Підсистема виконання бізнес-процесів]
a|
- xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc[Підсистема управління нереляційними базами даних]


| Аналітичні дані 
| xref:arch:architecture/registry/operational/reporting/overview.adoc[Підсистема аналітичної звітності реєстру]
a| 
- xref:arch:architecture/registry/operational/relational-data-storage/overview.adoc[Аналітична БД Підсистеми управління реляційними базами даних] 

| Історичні дані 
| xref:arch:architecture/registry/operational/registry-management/overview.adoc[Підсистема управління даними реєстру]
a| 
- xref:arch:architecture/registry/operational/relational-data-storage/overview.adoc[Операційна БД Підсистеми управління реляційними базами даних]

| Резервні копії даних
| xref:arch:architecture/platform/operational/backup-recovery/overview.adoc[Підсистема резервного копіювання та відновлення]
a| 
- xref:arch:architecture/platform-backup-storage/overview.adoc[Сховище резервних копій Платформи]

|===

== Зберігання Даних

=== Терміни зберігання

Для забезпечення належного функціонування платформи та відповідності державним правовим вимогам, дані не видаляються за замовчуванням після їх збору. Тривалість зберігання визначається з урахуванням типу даних та їх призначення, з метою забезпечення можливості використання та аналізу відповідно до цілей платформи. Тимчасові дані бізнес процесів зберігаються до кінця виконання бізнес-процесу.

=== Правила видалення

Зберігання даних на платформі здійснюється з урахуванням їхньої цінності та потреб користувачів. Для забезпечення прозорого та відповідального підходу до видалення даних пропонується використовувати наступний процес:

   - Користувачі мають можливість подати заяву на видалення своїх особистих даних з платформи. Заява повинна містити обґрунтування та пояснення причин видалення.

   - Отримані заяви на видалення даних мають розглядатися організацією (власником платформи) яка здійсенює аналіз та оцінку можливих наслідків видалення даних для користувача та платформи.

   - Після належного розгляду та затвердження заяви на видалення, організація (власник платформи) ініціює процес безпечного та надійного видалення даних з реєстрів. Цей процес здійснюється з урахуванням технічних та безпекових аспектів адміністратором реєстру.

   - Після видалення даних користувач буде оповіщений про завершення цього процесу. Організація (власник платформи) також має забезпечити що видалені дані більше не були доступні для відновлення або використання.

   - Цей підхід допомагає забезпечити, що видалення даних здійснюється відповідально та відповідно до вимог користувачів, забезпечуючи їхню приватність та безпеку в реєстрі.

Попри все згадка про дані користувача має залишитись в історичних даних реєстру як доказ "незаперечності дій" користувача виконаних ним на платформі.


=== Архівування та резервне копіювання

Тривалість зберігання даних на платформі можливо налаштувати тільки для резервних копій. Опис підходу та налаштування доступний у статті xref:admin:backup-restore/backup-schedule-cluster-mgmt.adoc[Керування розкладом створення резервних копій центральних компонентів та часом їх зберігання]

=== Передача та Обмін Даними

Підтримка міжреєстрової передачі даних відключена за замовченням на платформі реєстрів. Права на підключення зазначеної функціональності надаються тільки адміністратору платформи. Права ж на використання взаємодії з зовнішніми системами доступні розробнику регламенту який в свою чергу відповідає за обгрунтовання обміну даними. 

Більше інформації доступно у статті xref:arch:architecture/registry/operational/external-integrations/overview.adoc[Підсистема зовнішніх інтеграцій]
