= Шифрування даних у русі

include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

_Шифрування у русі_ - це процес перетворення інформації таким чином, щоб вона стала незрозумілою для несанкціонованих осіб, які не мають відповідних ключів для розшифрування. Цей процес використовується для забезпечення конфіденційності та безпеки даних під час передачі.

Основні ідеї шифрування у русі:

* _Конфіденційність_: Одна з основних цілей шифрування полягає у забезпеченні конфіденційності даних. Шифрування дозволяє зробити інформацію незрозумілою для сторонніх осіб, які намагаються перехопити або переглянути дані під час їх передачі чи збереження.
* _Захист від несанкціонованого доступу_: Шифрування забезпечує захист від несанкціонованого доступу до інформації, оскільки лише особи або системи з правильними ключами можуть розшифрувати зашифровані дані.
* _Інтегрітет даних_: Додаткова важливість шифрування полягає у забезпеченні інтегрітету даних. Під час передачі даних в мережі вони можуть піддаватися небажаним змінам. Застосування шифрування допомагає впевнитися, що дані не були змінені під час транзиту.
* _Дотримання регуляторних вимог_: Шифрування у русі є однією з основних вимог безпеки профільних стандартів.

=== Шифрування трафіку між користувачами та платформою

Для забезпечення безпечного каналу звязку та обміну даними між користувачем та платформою використовується криптографічний протокол TLS 1.2.

Весь зовнішній трафік спочатку проходе через зовнішній балансувальник навантаження але операція дешифрування (SSL Offload) відбувається вже всередині платформи головним мережевим компонентом Haproxy (роутер). За допомогою підходу SSL Offload, обробка криптографічних операцій відбувається на платформенному роутері підсистеми управління зовнішнім трафіком, що дозволяє звільнити внутрішні сервіси від цього навантаження і підвищити продуктивність. Це сприяє поліпшенню швидкодії, масштабованості та безпеки інфраструктури.

[TIP]
--
Детальніше можна ознайомитись у розділі xref:arch:architecture/platform/operational/external-traffic-management/overview.adoc[Підсистема управління зовнішнім трафіком]
--

У якості надавача довірених сертифікатів використовується центр сертифікації LetsEncrypt (https://letsencrypt.org/). Цей підхід дозволяє налаштовувати безкоштовні довірені сертифікати для шифрування трафіку на цільовому оточенні при розгортанні платформи.

[TIP]
--
Детальніше можна ознайомитись у розділі xref:admin:installation/platform-deployment/platform-aws-deployment.adoc#_заміна_самопідписаних_сертифікатів_на_довірені_сертифікати[Заміна самопідписаних сертифікатів на довірені сертифікати]
--

=== Шифрування трафіку всередині платформи

Платформа реєстрів а саме _Підсистема управління міжсервісною взаємодією_ використовує мережевий паттерн _Service Mesh_ однією з цілей якого є шифрування трафіку між сервісами. За динамічну генерацію, розповсюдження та підтвердження виданих сертифікатів відповідає окремий компонент Citadel.

[TIP]
--
Детальніше з компонентами _Service Mesh_ можна ознайомитись у розділі xref:arch:architecture/platform/operational/service-mesh/service-mesh-components.adoc[Service Mesh та компоненти Платформи]
--

Комунікація решти внутрішніх сервісів відбувається по відкритому каналу звязку в приватній мережі використовуючи приватні доменні імена.

Для взаємодії з зовнішніми системами такими як _Сервіс цифрової ідентифікації (id.gov.ua)_ або _Сервіси Дії (diia.gov.ua)_ та _Акредитованим центр сертифікації ключів (АЦСК)_ використовується виключно безпечний канал передачі даних.

З метою забезпечення захищеного інформаційного обміну даними державних реєстрів та інших інформаційних систем використовується _Система Електронної Взаємодії Державних Електронних Інформаційних Ресурсів (СЕВДЕІР) "Трембіта"_.  Всі повідомлення, що нею передають, зашифровуються відповідно до національних криптографічних стандартів.

[TIP]
--
Детальніше з дизайном підсистем, в яких залучена інтеграція, можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/user-management/overview.adoc[]
* xref:arch:architecture/registry/operational/bpms/overview.adoc[]
* xref:arch:architecture/registry/operational/external-integrations/overview.adoc[]
* xref:arch:architecture/data-exchange/overview.adoc[]
--
