= Цілісність даних
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

Цілі цілісності даних в контексті інформаційної безпеки - це запобігання несанкціонованим змінам, пошкодженню та забезпечення точності та надійності даних.

Об'єкти цілісності даних - це самі дані, дані в русі, ідентифікатори і ключі, метадані та журнали подій, які повинні бути захищені від несанкціонованого доступу, змін та пошкоджень.

== Класифікація та ідентифікація даних

Ідентифікація та класифікація даних на Платформі доступна на сторінці xref:arch:architecture/security/data-classification.adoc[].

== Заходи інформаційної безпеки

Оцінка ступеня цілісності даних є важливою складовою інформаційної безпеки. Для різних типів даних ступінь цілісності може бути різною. Наприклад структуровані дані, які зазвичай зберігаються в базах даних, мають високий рівень цілісності, оскільки їх формат та розташування можна легко перевірити та контролювати. Проте, для забезпечення їх цілісності, необхідно використовувати захист від несанкціонованого доступу, який може призвести до витоку даних та можливих зловживань. В свою чергу неструктуровані дані, які зазвичай зберігаються в документах та зображеннях, мають менший рівень цілісності, оскільки їхній інтегритет важко перевірити, відстежити та контролювати. Для забезпечення їх цілісності необхідно мати доступ до механізмів отримання системного журналу та аудиту, який може включати інформацію про зміни документів. Історичні та архівні документи мають високий рівень цілісності, оскільки вони зберігаються в незмінному та захищеному від змінного середовищі. Ці документи можуть включати підписи та печатки, які доводять їх автентичність.

Врешті решт, згідно класифікації даних та вимог безпеки щоб досягнути необхідний рівень цілісності для кожного типу даних необхідно інтегрувани відповідну кількість контролів безпеки.

|===
| Категорія даних | Опис | Цілісність згідно класу | Контролі у русі | Контролі при зберіганні | Інші контролі безпеки

| Автентифікаційні дані
| Будь-які дані користувача які приймають участь в процедурі автентифікації
| Висока
a|
- Шифрування каналу звязку від клієнта до платформи
- Шифрування каналу звязку між певними компонентами підсистем реєстру за допомогою mTLS.
- Шифрування каналу звязку між певними компонентами підсистем платформи за допомогою TLS.
- xref:arch:architecture/security/data-encryption-in-transit.adoc[]
a|
- Зберігання облікових даних в KeyCloak
- Шифрування дисків з даними
- Встановлено захист для сесій від несанкціонованого доступу клієнтськими скриптами
- Налаштований захист для сесій від CSRF-атак, що забезпечує, що кукі використовується лише на цільовому веб-сайті.
a|
- Інтерфейс керування додатково захищено мережевим контролем доступу
- Використовується надійний механізм автентифікації та система розмежування прав основана на ролях
- Резервне копіювання
- Журналювання


| Сервісні автентифікаційні дані
| Будь-які дані технічних користувачів які приймають участь в процедурі внутрішньої автентифікації
| Висока
a|
- Шифрування каналу звязку між певними компонентами підсистем реєстру за допомогою mTLS.
- Шифрування каналу звязку між певними компонентами підсистем платформи за допомогою TLS.
- xref:arch:architecture/security/data-encryption-in-transit.adoc[]
a|
- Шифрування сховища секретів підсистеми оркестрації контейнерів
- Автоматичний механізм ротації криптографічного матеріалу
a|
- Автентифікація
- Авторизація
- Резервне копіювання
- Журналювання


a| 
- Дані реєстру
- Метадані бізнес процесів
| Вибірка даних з реєстру яка софрмована в результаті виконання певних операцій та циркулює системою. Усі дані які належать користувачу і які оброблюються Платформою
| Висока
a|
- Шифрування каналу звязку від клієнта до платформи
- Шифрування каналу звязку між певними компонентами підсистем реєстру за допомогою mTLS
- Маршрутизація трафіку
- Рейт ліміти
- xref:arch:architecture/security/data-encryption-in-transit.adoc[]
a|
- Забезпечення цілісності за допомогою xref:arch:architecture/registry/operational/digital-signatures/overview.adoc[]
- Контроль цілісності даних за допомогою xref:arch:architecture/registry/operational/relational-data-storage/overview.adoc[]
- xref:arch:architecture/security/data-encryption-at-rest.adoc[]
- Шифрування дисків з даними
a|
- Автентифікація
- Авторизація
- Журналювання
- Аудит


| Технічні дані реєстру
| Дані про реалізацію, налаштування та функціонування Платформи
| Висока
a|
- xref:arch:architecture/security/data-encryption-in-transit.adoc[]
a|
- Шифрування дисків з даними
a|
- Автентифікація
- Авторизація
- Журналювання


| Історичні дані
| Дані про зміни в компонентах та процесах Платформи
| Висока
a|
- xref:arch:architecture/security/data-encryption-in-transit.adoc[]
a|
- xref:arch:architecture/security/data-encryption-at-rest.adoc[]
- Контроль цілісності даних за допомогою xref:arch:architecture/registry/operational/relational-data-storage/overview.adoc[]
- Шифрування дисків з даними
a|
- Дані доступні тільки для читання
- Автентифікація
- Авторизація
- Журналювання
- Аудит


| Публічна документація Платформи
| Документація про Платформу яка публікується публічно
| Середня
a|
- xref:arch:architecture/security/data-encryption-in-transit.adoc[]
a|
- -
a|
- Дані доступні тільки для читання



| Дані працездатності системи
| Дані моніторингу, трейсингу та журналювання
| Висока
a|
- Шифрування каналу звязку між клієнтом та відповідним веб-інтерфейсом
- xref:arch:architecture/security/data-encryption-in-transit.adoc[]
a|
- - 
a|
- Автентифікація
- Авторизація
- Журналювання
- Інтерфейс керування додатково захищено мережевим контролем доступу


| Криптографічні дані
| Дані які мають відношення то криптографічних операцій
| Висока
a|
- Шифрування каналу звязку та надійні алгоритми обміну ключами
- Шифрування каналу звязку між певними компонентами підсистем реєстру за допомогою mTLS
- xref:arch:architecture/security/data-encryption-in-transit.adoc[]
a|
- Шифрування сховища секретів підсистеми оркестрації контейнерів
- Автоматичний механізм ротації криптографічного матеріалу
a|
- Інтерфейс керування додатково захищено мережевим контролем доступу
- Автентифікація
- Авторизація
- Резервне копіювання

| Цифрові підписи
| Дані які відносять до процесу підпису або перевірки підпису даних на Платформі
| Висока
a|
- Шифрування каналу звязку між платформою та зовнішніми системами
- Шифрування каналу звязку сеансовим ключем між бібліотекою та HSM
a|
- Зберігання даних у програмно-апаратному захищеному модулі (HSM)
a|
- Механізм додаткової ідентифікації
- Механізм спеціальної автентифікації
- Механізми обмеження доступу

| Чутливі налаштування
| Налаштування які впливають на працездатність Платформи та може містити чутливу інформацію
| Висока
a|
- Шифрування каналу звязку
a|
- Шифрування сховища секретів реєстрів на платформи
a|
- Автентифікація на базі токенів та інтегрована з підсистемою оркестрації контейнерів
- Відсутність доступу до сховища у будь-якого користувача платформи
- Механізм транзитивного безключевого шифрування платформенного та реєстрових волтів центральним для підвищення безпеки даних та зниження ризика компрометації ключів.
- Механізм делегування розшифрування центрального волта хмарному сервісу керування секретами задля підвищення безпеки, зменшення ризику витоку ключів та підвищення надійності системи
- Реалізація розмежування прав на базі політик доступу
- Резервне копіювання

|===

== Журналювання та аудит

На Платформі Реєстрів існують відповідні підсистеми - журналювання подій та журналювання подій аудиту. Потрібно зауважити що платформа надає лише базовий функціонал по збору та відображенню журналів системи та аудиту. Для побудови повноцінної системи моніторингу подій безпеки у режими реальноого часу організація (власник платформи) має інтегрувати платформу з відповідною SIEM системою. 

Підсистема журналювання подій аудиту - це підсистема, що забезпечує збір, зберігання та аналіз інформації про дії користувачів, які мають доступ до даних. Підсистема збирає повну інформація про всі дії користувача, включаючи доступ, зміну та видалення даних. Детальніше про покриття компонентів платформи підсистемою аудиту можна ознайомитись за xref:arch:architecture/registry/operational/audit/overview.adoc[посиланням].

Детальніше з форматом даних у підсистемі аудиту можна ознайомитись за xref:arch:architecture/registry/operational/audit/audit.adoc[посиланням].

Підсистема аудиту надає адміністраторам доступ до даних через веб-інтерфейс Підсистеми аналітичної звітності у вигляді набору службових дашбордів, які створюються під час розгортання реєстру. Детальніше з підсистемою аналітічної звітності можна ознайомитись за xref:arch:architecture/registry/operational/reporting/overview.adoc[посиланням].

Також на платформі присутня підсистема журналювання подій. Вона базується на стеку ElasticSearch, Fluentd та Kibana та дозволяє збирати, аналізувати та візуалізувати журнали подій безпеки на платформі. Система журналювання подій забезпечує доступ до детального журналювання подій безпеки на різних рівнях основних технологій. Підсистема забезпечує підвищену безпеку, широкі можливості журналювання та аналізу журналів, відслідковування проблем в реальному часі та зручний веб-інтерфейс управління журналами подій.

Детальніше з підсистемою можна ознайомитись за за xref:arch:architecture/platform/operational/logging/overview.adoc[посиланням].

== Заходи в разі порушення цілісності даних

=== Реагування на інциденти цілісності даних

Реагування на інциденти цілісності даних - це процес виявлення, оцінки та виправлення порушень безпеки даних, який має на меті захистити цілісність даних та запобігти потенційним загрозам. Цей процес включає виявлення інциденту, оцінку його наслідків та відновлення нормального функціонування системи. Відповідальність за побудову процесу реагуванян на інциденти цілісності платформи та реєстрів лежить повністю на організації (власнику платформи).

Взагалі процес складається з основних чотирьох дій, а саме:

1. Виявлення інциденту. Для цього власник платформи повинен мати систему моніторингу, яка дозволить вчасно виявити будь-яке порушення цілісності даних. Платформа надає інструменти для збору та аналізу журналів подій та аудиту.

2. Оцінка ризиків. Після виявлення інциденту власник платформи повинен провести оцінку ризиків, що виникають з цього порушення цілісності даних.

3. Відновлення даних. Власник платформи повинен відновити пошкоджені дані або втрачені дані з резервних копій.

4. Запобігання виникненню інцидентів в майбутньому. Власник платформи повинен зробити висновки з інциденту та внести необхідні зміни у систему безпеки платформи заради запобігання виникненню подібних інцидентів в майбутньому.

=== Відновлення даних після порушення цілісності

Відновлення даних після порушення цілісності має бути проведене з урахуванням збереження оригінальної якості й цілісності даних. Для цього платформа надає функціонал по створенню резервних копій інформації, які зберігаються в надійному та безпечному місці.

* Центральні компоненти
** xref:admin:backup-restore/control-plane-components-backup-restore.adoc[]
** xref:admin:backup-restore/backup-schedule-cluster-mgmt.adoc[]

* Середовище реєстру
** xref:admin:backup-restore/control-plane-backup-restore.adoc[]
** xref:admin:backup-restore/backup-schedule-registry-components.adoc[]

* xref:admin:backup-restore/postgres-backup-restore.adoc[]
* xref:admin:backup-restore/master_ip_repair.adoc[]


== Завдання та відповідальність

Відповідальності за цілісність даних несуть керівництво компанії, співробітники, адміністратори баз даних та інших систем, а також користувачі, які мають доступ до даних. Ролі та відповідальності з питань цілісності даних можуть відрізнятися в залежності від розміру та складності організації але безпосередньо визначення ролей та зобовязань повністю лежить на плечах організації (власнику платформи).

Власник платформи:

- Виділення фінансування та ресурсів для забезпечення безпеки даних

Інформаційний відділ:

- Розробка стратегії з питань захисту інформації.
- Моніторинг систем безпеки та виявлення проблем операційних систем та програмного забезпечення.
- Аналіз ризиків, пов'язаних зі ступенем доступу до інформації та подальший розвиток планів на основі цих аналізів.
- Вдосконалення систем зберігання та обробки інформації у відповідності з міжнародними нормами та стандартами щодо безпеки даних.

Адміністратори платформи:

- Безпечне налаштування платформи згідно наданих рекомендацій
- Налаштування зовнішніх інтеграцій
- Регламентоване надання доступу до платформи та реєстрів
- Обмеження мережевого доступу до адміністративних інтерфейсів
- Налаштування інформаційних дашбордів

Розробники регламенту:

- Розробка регламенту реєстру таким чином щоб цілісність даних не була порушена неавторизованими особами
- Відповідають за цілісність регламенту

Персонал із забезпечення інформаційної безпеки:
- Навчання користувачів організації(власник платформи) щодо стандартів безпеки даних та заходів захисту інформації.

