= Архітектура безпеки Платформи

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Безпека — це показник здатності системи захищати дані та інформацію від несанкціонованого доступу, забезпечуючи при цьому доступ авторизованим користувачам і системам.

Архітектура безпеки платформи реєстрів відповідає за три загальноприйняті характеристики:

* Конфіденційність – властивість захисту даних або сервісів від несанкціонованого доступу.
* Цілісність – властивість того, що дані або послуги не піддаються несанкціонованим маніпуляціям.
* Доступність - властивість, що система буде доступна для цільового використання.

Архітектура безпеки покриває наступні частини:

* Розроблені компоненти з яких складається платформа.
* Вбудовані компоненти
* Сторонні сервіси які використовуються системою
* Архітектура програмного забезпечення
* Інфраструктурні компоненти на яких побудована платформа
* Процес безпечної розробки програмного забезпечення
* Вимоги до безпеки

== Розділи технічній документації

* xref:arch:architecture/security/data-classification.adoc[] - визначення та встановлення рівня конфіденційності, цілісності та доступності даних залежно від їх важливості, чутливості та потенційного впливу на організацію або платформу.
* xref:arch:architecture/security/data-encryption-at-rest.adoc[] - опис криптографічних механізмів платформи перетворення даних в незрозумілий для несанкціонованого доступу формат з метою захисту конфіденційності та запобігання несанкціонованому доступу до цих даних під час їх зберігання.
* Шифрування у русі - опис криптографічних механізмів платформи перетворення даних в незрозумілу форму з метою забезпечення їх конфіденційності та захисту від несанкціонованого доступу під час передачі по мережі.
* Збереження даних (Data retention) - опис процедур та технічних заходів, що регулюють тривалість зберігання даних на платформі з метою забезпечення вимог законодавства, внутрішніх правил або бізнес-потреб.
* Збереження секретів та ключів доступу (HCP Vault) - опис криптографічних механізмів, політик, розмежування прав, ротації та зберігання платформенних ключів доступу в HashiCorp Vault.
* Обіг та використання ключів доступу - документація стосовно використання, обігу та гарантування безпеки ключів доступу всередині платформи.
* Управління доступом - механізми контролю та регулювання доступу до ресурсів, систем, даних та інших активів платформи з метою забезпечення конфіденційності, цілісності та доступності інформації а також механізми контролю життєвого циклу користувачів та сутностей.
* Цілісність даних - опис процесу забезпечення правдивості, недоступності змін та цілісності даних, систем, процесів платформи.