= Архітектура безпеки Платформи

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Безпека — це показник здатності системи захищати дані та інформацію від несанкціонованого доступу, забезпечуючи при цьому доступ авторизованим користувачам і системам.

Архітектура безпеки платформи реєстрів відповідає за три загальноприйняті характеристики:

* Конфіденційність – властивість захисту даних або сервісів від несанкціонованого доступу.
* Цілісність – властивість того, що дані або послуги не піддаються несанкціонованим маніпуляціям.
* Доступність - властивість, що система буде доступна для цільового використання.

Архітектура безпеки покриває наступні частини:

* Розроблені компоненти з яких складається платформа.
* Вбудовані компоненти
* Сторонні сервіси які використовуються системою
* Архітектура програмного забезпечення
* Інфраструктурні компоненти на яких побудована платформа
* Процес безпечної розробки програмного забезпечення
* Вимоги до безпеки

== Розділи технічній документації

* xref:arch:architecture/security/data-classification.adoc[] - ...
* Encryption at rest - ...
* Encryption in transit - ...
* Data retention - ...
* Vaults - ...
* Secrets usage - ...
* Access management - ...
* Integrity - ...