:sectlinks:
= Адміністраторам Платформи

Розділ _Адміністраторам Платформи_ надає докладні інструкції для технічних адміністраторів Платформи, що покриває усі аспекти їх діяльності, від встановлення до інтеграції із зовнішніми системами.

Тут ви знайдете покрокові інструкції зі встановлення та налаштування, вимоги до OKD кластерів, а також деталі розгортання Платформи на цільових середовищах. Розділ також розглядає управління Платформою та реєстрами через адміністративну панель Control Plane, керування ресурсами реєстру, масштабування, конфігурацію цифрових підписів та сертифікатів, налаштування DNS, технічне обслуговування підсистем логування, моніторингу подій, а також роботу із розподіленою файловою системою.

Для тих, хто хоче більш детально ознайомитися із роллю технічного адміністратора Платформи, пропонується детальна посадова інструкція зі стеком технологій, обов'язків та вимог до адміністратора. Окремо описані деякі налаштування інтеграції із зовнішніми системами, що підкреслює важливість забезпечення сумісності та гнучкості нашої Платформи.

Цей розділ -- незамінний ресурс для технічних спеціалістів, які хочуть повністю розуміти та ефективно управляти нашою Платформою.

== Огляд секції

* xref:admin:installation/overview.adoc[Встановлення та налаштування]
* xref:admin:registry-management/overview.adoc[Керування Платформою та реєстрами в Control Plane]
* xref:admin:migration/migration-overview.adoc[Міграція]
* xref:admin:update/overview.adoc[Оновлення]
* xref:admin:backup-restore/overview.adoc[Резервне копіювання та відновлення]
* xref:admin:scaling/overview.adoc[Масштабування]
* xref:admin:logging/elastic-search.adoc[Технічне обслуговування підсистеми логування (EFK)]
* xref:admin:file-system/ceph-space.adoc[Керування розподіленою файловою системою]
* xref:platform:registry-develop:bp-modeling/bp/rest-connector.adoc#create-service-entry[Інтеграція із зовнішніми системами]
* xref:admin:admin-study/admin-profile.adoc[Посадова інструкція для технічного адміністратора Платформи]
* xref:admin:admin-study/platform-admin-tools.adoc[Інструменти адміністратора Платформи]