= Функція _process_caller()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`process_caller(): ProcessCallerDto`* використовується для отримання даних про викликаючий процес.

== Параметри

NOTE: Ця функція не приймає аргументів.

== Що повертає

Функція повертає об'єкт типу `ProcessCallerDto`, що містить дані про викликаючий процес.

.ProcessCallerDto
|===
|*Поле*            | *Опис*
| `id`             | Ідентифікатор викликаючого процесу
|===

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

== Приклади використання

Цей розділ демонструє приклади використання JUEL-функції у Groovy-скриптах бізнес-процесу.

[TIP]
====
[%collapsible]
.Де можна знайти приклад бізнес-процесу?
=====
include::partial$snippets/demo-reg-reference-examples-ua.adoc[]

Застосування функції `process_caller()` представлено у багатьох бізнес-процесах.

Ви можете використати один із прикладів процесів за пошуком по ключовим словам — *_feature-start-process-by-end-message-event_*.

У Кабінеті користувача бізнес-процес буде доступний у розділі *Доступні послуги*.
=====
====

Нижче наведено приклад використання функції `process_caller()` який демонструє, як зібрати дані про процес, що викликав поточний процес, і використовувати ці дані разом з повідомленнями для подальшої обробки.

[source,groovy]
----
var cephData = [:]

cephData['callerProcess'] = process_caller().id

message_payload('startEvent2').data.keySet().each {
    cephData[it] = message_payload('startEvent2').data.get(it)
}

set_transient_variable('payload', S(cephData, 'application/json'))
----

Пояснення ::

. *`cephData['callerProcess'] = process_caller().id`* -- отримує ідентифікатор процесу, що викликав поточний, і зберігає його в об'єкті `cephData`.
. *`message_payload('startEvent2')`* -- отримує дані повідомлення, пов'язаного з подією або завданням під ідентифікатором `'startEvent2'` (див. детальніше -- xref:bp-modeling/bp/juel-functions/messages/message-payload.adoc[]).
. *`.data.keySet()`* -- отримує всі ключі з даних повідомлення.
. *`.data.get(it)`* -- отримує значення для кожного ключа і зберігає його в об'єкті `cephData`.
. *`set_transient_variable()`* -- зберігає зібрані дані у форматі JSON як тимчасову змінну для подальшого використання в процесі (див. детальніше -- xref:bp-modeling/bp/juel-functions/variables/set-transient-variable.adoc[]).

== Пов'язані сторінки

* xref:bp-modeling/bp/juel-functions/messages/message-payload.adoc[]
* xref:bp-modeling/bp/juel-functions/variables/set-transient-variable.adoc[]
* xref:bp-modeling/bp/bpmn/events/message-event.adoc[]