:toc-title: On this page:
:toc: auto
:toclevels: 5
:experimental:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:
= Organization of work with git repositories when working with several versions of registry regulations
//= Організація роботи з git репозиторіями під час роботи з декількома версіями регламенту реєстру
NOTE: 🌐 This document is available in both English and Ukrainian. Use the language toggle in the top right corner to switch between versions.

== Basic principles
//== Базові принципи
- Backend admin-portal service uses gerrit (git) and the file system (persistent volume) as a data store.
//- Backend admin-portal service використовує в якості сховища даних: gerrit (git) та файлову систему (persistent volume)
- The file system keeps a separate copy (git clone) for each candidate version.
//- Файлова система зберігає окрему копію git clone для кожної версії-кандидату
- The file system stores a separate copy (git clone) to create copies of git clone for candidate versions by copying files in the file system.
//- Файлова система зберігає окрему копію git clone для створення копій git clone для версій-кандидатів шляхом копіювання файлів на файловій системі.
- There is a separate part of the code (scheduled job), responsible for updating (git rebase) folders with the code of the candidate versions in the file system.
//- Існує окрема частина коду (scheduled job), що відповідає за оновлення (git rebase)  папок з кодом версій-кандидатів на файловій системі
- When starting a service, the compatibility of the code in the file system with the list of candidate versions in gerrit is verified.
//- Під час запуску сервісу перевіряється сумісність коду на файловій системі с переліком версій-кандидатів в gerrit.
- Synchronization of user actions within the same candidate version occurs on the "git client" side. This synchronization is part of the git contract and does not require additional development of this functionality on the user side.
//- Синхронізація дій користувачів в межах однієї версії-кандидату відбувається на боці "git client". Дана синхронізація є частиною git контракту та не потребує додаткової розробки даного функціоналу на боці користувача.

== Facts required when working with gerrit/git
//== Факти, необхідні під час роботи з gerrit/git
- Information about changes
//- Інформація про зміни
- Test execution status
//- Статус виконання тестів
- Change conflict information
//- Інформація про конфлікти змін
- History of changes
//- Історія змін
- Labels with MR, comments
//- Labels з MR, коментарії

== Data warehouse types and their compliance with facts
//== Типи сховищ даних та їх відповідальність фактам

The admin portal uses two types of data stores:
//Адмін-портал використовую в якості сховищ даних два типи:

- Gerrit
- File system (docker persistent volume).
//- Файлову систему (docker persistent volume).

The file system contains local copies (git clone) of the registry regulations repository.
//На файловій системі знаходяться локальні копії (git clone) репозиторію регламенту реєстру.

Compliance of the storage types with facts
//Відповідність типів сховищ фактам

image::architecture/registry/administrative/regulation-management/admin-portal/regulation-repository/gitflow-facts.svg[gitflow-facts]

== Working with local and remote git repositories
//== Робота з локальними та віддаленими репозиторіями git

=== Description of the file structure in the file system
//=== Опис структури файлів на файловій системі
File structure in the file system:
//Структура файлів на файловій системі:

- master version of the repository is located in the master directory.
//- мастер версія репозиторію знаходиться в каталозі master
- the candidate version has one corresponding directory named reglament-<gerrit-mr-number>. (For example: reglament-127).
//- версія-кандидат має одну, відповідну їй, директорію, що має назву reglamant-<gerrit-mr-number>. (Наприклад: reglament-127)

[listing]
checkout-dir
|- master
|- registry-<gerrit-mr-number>
|        ...
|- registry-<gerrit-mr-number>

=== File lifecycle in the file system
//=== Життєвий цикл файлів на файловій системі

image::architecture/registry/administrative/regulation-management/admin-portal/regulation-repository/git-directory-flow.svg[git-directory-flow]

=== Simultaneous work of several users on several versions of the regulations
//=== Одночасна робота декількох користувачів над декількома версіями регламенту

image::architecture/registry/administrative/regulation-management/admin-portal/regulation-repository/gitflow-concurrent-work.svg[gitflow-concurrent-work]

Each candidate version of the registry regulations has a corresponding "git clone" directory in the file system. All operations on the registry regulations are carried out in relation to this directory (changes in the configuration of the regulations by changing files in the file system).
//Кожна версія-кандидат регламенту реєстру має відповідну їй "git clone" директорію на файловій системі. Всі операції над регламентом реєстру проводяться відносно цієї директорії (зміни в конфігурації регламенту шляхом зміни файлів на файловій системі).

Changes to files on the file system are synchronized using the git client. Each change from the client is implemented using `git commit --amend`.
//Синхронізація змін відносно файлів на файловій системі відбуваються з використанням git клієнту. Кожна зміна від клієнта відбувається з використанням `git commit --amend`.

[CAUTION]
When several users are simultaneously working (executing _git_ commands) on the same version, _Git_ locks part of the repository by creating the _lock_ files. In this case, the task that is executed after creation of the _lock_ file will wait for the repository to unlock or inform the user about the need to run the operation later (the _retry_ mechanism is used to wait for completion of simultaneous actions with the repository at the _jGit_ java level of the service).
//Під час одночасної роботи (виконання _git_ команд) декількох користувачів над однією версією, _Git_ блокує частину репозиторію шляхом створення _lock_ файлів. В такому випадку, задача, яка виконується після створення _lock_ файлу, буде чекати розблокування репозиторію або проінформує користувача про необхідність проведення операції пізніше (використовується _retry_ механізм для очікування завершення одночасних дій з репозиторієм на рівні _jGit_ java сервісу).

[WARNING]
This mechanism of using _git lock_ files works only with the git client and does not guarantee permanent data consistency in the file system during git operations. xref:architecture-workspace/research/admin-portal/gitflow/git-repositories-management.adoc[See the document.]
//Даний механізм використання _git lock_ файлів працює тільки з git клієнтом і не гарантує постійну консистентність даних на файловій системі під час виконання git операцій. xref:architecture-workspace/research/admin-portal/gitflow/git-repositories-management.adoc[Дивись документ.]




