= JUEL-функції: скриптування у бізнес-процесах
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Можливості скриптування

Платформа реєстрів надає багато можливостей для автоматизації бізнес-процесів за допомогою скриптів. Ви можете використовувати різні варіанти скриптування, залежно від ваших потреб. Наприклад, ви можете створювати Groovy-скрипти або використовувати JUEL-функції для додавання логіки в процеси. Ці функції можуть бути застосовані як у скриптах, так і окремо, наприклад, у делегатах певних завдань процесу.
//Також є можливість використовувати xref:bp-modeling/bp/knative-functions/index.adoc[Knative-функції] та підтримку різних мов програмування для інтеграції з іншими сервісами.

Крім того, ви можете застосовувати _JavaScript_ під час моделювання xref:bp-modeling/forms/components/index.adoc[компонентів UI-форм], що забезпечує більшу гнучкість у роботі з користувацькими інтерфейсами.

Підтримка http://juel.sourceforge.net/[JUEL (Java Unified Expression Language)], що є універсальною мовою виразів для Java, допомагає значно спростити моделювання бізнес-процесів, роблячи їх більш зрозумілими та ефективними.

Нижче наведено список доступних JUEL-функцій, які ви можете використовувати при розробці реєстрів. Ці функції легко налаштовуються у xref:registry-develop:registry-admin/admin-portal/registry-modeling/process-models/components/edit-groovy-scripts.adoc[візуальному редакторі коду] для скриптових завдань бізнес-процесу, а також при налаштуванні xref:bp-modeling/bp/element-templates/element-templates-overview.adoc[інтеграційних розширень бізнес-процесів].

== Каталог JUEL-функцій

Платформа підтримує наступний перелік функцій для використання при моделюванні бізнес-процесів:

{empty}

++++
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Каталог JUEL-функцій</title>
    <style>
        .custom-table {
            width: 100%;
            border-collapse: collapse;
        }
        .custom-table th, .custom-table td {
            border: 1px solid #ddd;
            padding: 8px;
        }
        .custom-table th {
            text-align: center;
            background-color: white;
        }
        .status-active {
            background-color: #cffadb;
        }
        .code {
            font-family: monospace;
            background-color: #f9f9f9;
            padding: 2px 4px;
            border-radius: 3px;
        }
    </style>
</head>
<body>

<table class="custom-table">
    <tr>
        <th>JUEL-функція</th>
        <th>Статус</th>
        <th>Має новішу версію</th>
    </tr>
    <tr>
        <td><code><a href="users/initiator.html">initiator()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="users/completer.html">completer()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="forms/submission.html">submission()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="forms/sign-submission.html">sign_submission()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="users/system-user.html">system_user()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="variables/get-variable.html">get_variable()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="variables/set-variable.html">set_variable()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="variables/set-transient-variable.html">set_transient_variable()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="messages/message-payload.html">message_payload()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="processes/process-caller.html">process_caller()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="digital-documents/save-digital-document.html">save_digital_document()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="digital-documents/save-digital-document-from-url.html">save_digital_document_from_url()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="trembita/get-trembita-auth-token.html">get_trembita_auth_token()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="digital-documents/load-digital-document.html">load_digital_document()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="digital-documents/get-digital-document-metadata.html">get_digital_document_metadata()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="signatures/signature-content.html">signature_content()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code><a href="signatures/signature-details.html">signature_details()</a></code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>

</table>

</body>
</html>
++++

////
== Додаткові функції для налаштування у різних середовищах

Платформа підтримує додаткові функції для налаштування локалізації на формах бізнес-процесів. Хоча вирази цих функцій нагадують JavaScript, фактично вони не є стандартним JavaScript-кодом. Замість цього, це умовні вирази, які інтерпретуються в контексті специфічного середовища платформи, такого як конструктор UI-форм або BPM-система.

Ці вирази застосовуються для визначення умов видимості або налаштування локалізації, і платформа обробляє їх у своєму внутрішньому середовищі. Отже, функції працюють у межах обмеженого синтаксису, підтримуваного платформою, але їх можна застосовувати для налаштування інтерфейсу без написання повноцінного JavaScript-коду.

Платформа підтримує наступний перелік таких функцій:

{empty}

++++
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Каталог JUEL-функцій</title>
    <style>
        .custom-table {
            width: 100%;
            border-collapse: collapse;
        }
        .custom-table th, .custom-table td {
            border: 1px solid #ddd;
            padding: 8px;
        }
        .custom-table th {
            text-align: center;
            background-color: white;
        }
        .status-active {
            background-color: #cffadb;
        }
        .code {
            font-family: monospace;
            background-color: #f9f9f9;
            padding: 2px 4px;
            border-radius: 3px;
        }
    </style>
</head>
<body>

<table class="custom-table">
    <tr>
        <th>JUEL-функція</th>
        <th>Статус</th>
        <th>Має новішу версію</th>
    </tr>
    <tr>
        <td><code>getUserLanguage()</code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code>getRegistryLanguage()</code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
    <tr>
        <td><code>getRegistrySupportedLanguages()</code></td>
        <td class="status-active"><p>Активний</p></td>
        <td>Ні</td>
    </tr>
</table>

</body>
</html>
++++

[TIP]
Детальніше дивіться на сторінці xref:bp-modeling/forms/functions/form-functions.adoc[].
////

== Пов'язані сторінки

* xref:bp-modeling/bp/element-templates/element-templates-overview.adoc[]
//* xref:bp-modeling/bp/knative-functions/index.adoc[]
//* xref:bp-modeling/forms/functions/form-functions.adoc[]
//* xref:bp-modeling/forms/components/index.adoc[]