= Installer component structure
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== Definitions

*_Installer_* is a set of software tools for deploying the Platform

The Installer is used to deploy the Platform for state registries, which is delivered as a zip archive.

.Installer structure
[plantuml, structure, svg]
----
@startuml

package "Installer" as installer {
    package "images" as images {
        [external docker images]
        [registry docker images]
    }
    package "nexus" as nexus {
        [liquibase-ext-schema]
    }
    package "repositories" as repositories {
        package "control-plane" as control-plane {
            [codebase-operator]
            [control-plane-console]
            [control-plane-gerrit]
            [control-plane-installer]
            [control-plane-jenkins]
            [ddm-architecture]
            [infrastructure-jenkins-agent]
            [keycloak-operator]
        }
        package "infra" as infra {
            [backup-management]
            [catalog-source]
            [control-plane-nexus]
            [external-integration-mock]
            [keycloak]
            [logging]
            [monitoring]
            [service-mesh]
            [storage]
            [user-management]
        }
        package "registry" as registry {
            [digital-signature-ops]
            [hashicorp-vault]
            [keycloak-operator]
        }
    }
    package "terraform" as terraform {
        [minio]
        [vault]
    }
    [control-plane-installer.img] as installer_image
    [docker_load.sh] as docker_load
    [functions.sh] as functions
    [install.sh] as install
}


@enduml
----

== Platform deployment sequence diagram

.Platform deployment sequence diagram
[plantuml, install_flow, svg]
----
@startuml

actor "Platform administrator" as devops order 10
participant "Installation server" as jumpbox  order 30
participant "Installer container" as docker_load  order 35
participant "Installer" as install.sh  order 40
participant "Openshift cluster" as openshift  order 45
participant "Vault" as vault  order 50
participant "Minio" as minio  order 55

autonumber

title Platform deployment sequence diagram

group Preparing the Installer for deployment
devops -> jumpbox: Uploading the Installer archive
devops -> jumpbox: Uploading certificates digital-signature-ops
devops -> jumpbox: Server readiness check (prerequisites)
devops -> docker_load: Authentication in Openshift
devops -> docker_load: Setting parameters (env)
devops -> docker_load: Launching the Installer (install.sh -i)
end

group Deployment of the Platform
install.sh -> install.sh: Checking input parameters
install.sh -> openshift: Enable encryption ETCD
install.sh -> openshift: Deployment of basic cluster-mgmt resources\n(catalog-sources, storage, keycloak-operator-crd, logging, service-mesh)
install.sh -> openshift: Deployment nexus (control-plane-nexus)
install.sh -> vault: Deployment Vault
install.sh -> minio: Deployment Minio
install.sh -> openshift: Downloading docker images in nexus (control-plane-nexus)
install.sh -> openshift: Deployment of user-management and downloading digital-signature-ops certificates
install.sh -> openshift: Deployment Control Plane
install.sh -> openshift: Loading xsd in nexus (control-plane-nexus)
install.sh -> openshift: Loading access parameters in Minio
devops -> jumpbox: Checking the log and saving the Control Plane access parameters in a safe place
end

@enduml
----

== Platform upgrade sequence diagram

.Platform upgrade sequence diagram
[plantuml, update_flow, svg]
----
@startuml

actor "Platform Administrator" as devops order 10
participant "Installation Server" as jumpbox  order 30
participant "Installer Container" as docker_load  order 35
participant "Installer" as install.sh  order 40
participant "Openshift cluster" as openshift  order 45
participant "Vault" as vault  order 50
participant "Minio" as minio  order 55

autonumber

title Platform deployment sequence diagram

group Preparing the Installer for deployment
devops -> jumpbox: Uploading the Installer archive
devops -> jumpbox: Uploading digital-signature-ops certificates
devops -> jumpbox: Server readiness check (prerequisites)
devops -> docker_load: Authentication in Openshift
devops -> docker_load: Setting parameters (env)
devops -> docker_load: Launching the Installer (install.sh -u)
end

group Deployment of the Platform
install.sh -> install.sh: Checking input parameters
install.sh -> vault: Status update Vault
install.sh -> minio: Status update Minio
install.sh -> openshift: Downloading docker images in nexus (control-plane-nexus)
install.sh -> openshift: Deployment of Control Plane
install.sh -> openshift: Uploading xsd in nexus (control-plane-nexus)
install.sh -> openshift: Uploading access parameters in Minio
devops -> jumpbox: Checking the log and the correctness of the update
end

@enduml

----

== Installer modules description (_functions.sh_)

INIT-CHECK:: checking the necessary parameters and availability of certificates digital-signature-ops (for initial deployment only)

ENCRYPTION-ETCD:: setting up ETCD encryption and validating Openshift certificates

INSTALL-CLUSTER-MGMT:: deploying basic components of the `cluster-mgmt`:
* `catalog-source`
* `storage`
* `keycloak-operator-crd` (subcomponent of the `control-plane-installer`)
* `logging`
* `service-mesh`

INSTALL-NEXUS:: deploying `control-plane-nexus` (docker image repository and xsd)

VAULT-INSTALL:: deploying the central Vault
MINIO-INSTALL:: deploying the central Minio
INIT-NEXUS:: loading docker images
INSTALL-ADDITIONAL-COMPONENTS:: uploading `digital-signature-ops` certificates and deploying `user-management`
INSTALL-CONTROL-PLANE:: deploying the Control Plane components
NEXUS-RESOURCE-UPLOAD:: uploading nexus resources (xsd)
BACKUP-CREDENTIALS:: access parameters in Minio
USAGE:: auxiliary module for displaying usage information _install.sh_