= Автоматичне розгортання компонентів MinIO та Vault

//Секції 1 та 2 актуалізовані і використовуються у docs/ua/modules/admin/pages/installation/platform-deployment/platform-vsphere-deployment.adoc; решта контенту не оновлена.

include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Розгортання кластера Платформи з нуля у середовищі vSphere

=== Передумови

NOTE: Переконайтеся, що встановлено необхідні пакети: `docker`, `wget`, `unzip`.

[prerequisites-plan]
==== План

. Завантажте необхідну версію інсталера.
+
[source,shellscript]
----
сd /tmp
wget -O mdtu-ddm-platform-<version>.zip https://nexus-public-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/nexus/repository/edp-maven-releases/ua/gov/mdtu/ddm/infrastructure/mdtu-ddm-platform/<version>/mdtu-ddm-platform-<version>.zip
----

. Розпакуйте архів у домашній директорії.

+
[source,shellscript]
----
unzip /tmp/mdtu-ddm-platform-<version>.zip -d /home/<user>/workdir/installer-<version>
----

. Перенесіть _kubeconfig_ після встановлення кластера:

+
[source,shellscript]
----
cd /home/<user>/workdir/installer-<version>
cp /path/to/kubeconfig ./
----

. Перенесіть папку _certificates_ для DSO:

+
[source,shellscript]
----
cp /path/to/folder/certificates ./
----

=== Додавання окремого конфігураційного файлу для розгортання в середовищі vSphere

. Відредагуйте _exports.list_ для vSphere.
+
Усі значення необхідно взяти після інсталяції кластера. Також необхідно уточнити актуальні значенння для `idgovuaClientId` та `idgovuaClientSecret`.

+
[source,shellscript]
----
vi exports.list

### vSphere Credentials ###
export VSPHERE_SERVER=""
export VSPHERE_USER=""
export VSPHERE_PASSWORD=""
export VSPHERE_CLUSTER=""
export VSPHERE_DATASTORE=""
export VSPHERE_DATACENTER=""
export VSPHERE_NETWORK=""
export VSPHERE_NETWORK_GATEWAY=""
export VSPHERE_RESOURCE_POOL="" #якщо не використовується, ставимо "/"
export VSPHERE_FOLDER=""

### Minio and Vault IPs ###
export VSPHERE_VAULT_INSTANCE_IP=""
export VSPHERE_MINIO_INSTANCE_IP=""

### id.gov.ua ###
export idgovuaClientId=""
export idgovuaClientSecret=""
----

. Відредагуйте _install.sh_, а саме після `source ./functions.sh` додайте `source ./exports.list`.

+
[source,shellscript]
----
vi install.sh
----
+
Це виглядатиме наступним чином:

+
[source,shellscript]
----
#!/usr/bin/env bash
set -e
#Include function file
source ./functions.sh
source ./exports.list
----

=== Розгортання інсталятора

. Виконайте наступні команди:
+
[source,shellscript]
----
IMAGE_CHECKSUM=$(sudo docker load -i control-plane-installer.img | sed -r "s#.*sha256:(.*)#\\1#" | tr -d '\n');
echo $IMAGE_CHECKSUM
sudo docker tag ${IMAGE_CHECKSUM} control-plane-installer:<version>;
----

. Розгорніть нову версію Платформи з образами з нуля:
+
[source,shellscript]
----
sudo docker run --rm --name control-plane-installer-<version> --user root:$(id -g) --net host -v $(pwd):/tmp/installer --env KUBECONFIG=/tmp/installer/kubeconfig --env idgovuaClientId=mock --env idgovuaClientSecret=mock --env CUSTOM_INGRESS_CIDRS="['0.0.0.0/0', '85.223.209.0/24']" --env deploymentMode=development --entrypoint "/bin/bash" control-plane-installer:<version> -c "./install.sh -i"
----
+
* Де `deploymentMode` може бути `development` чи `production`.

== Оновлення кластера Платформи у середовищі vSphere

=== Передумови

NOTE: Переконайтеся, що встановлено необхідні пакети: `docker`, `wget`, `unzip`.

[prerequisites-plan]
==== План

. Завантажте необхідну версію інсталера.
+
[source,shellscript]
----
сd /tmp
wget -O mdtu-ddm-platform-<version>.zip https://nexus-public-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/nexus/repository/edp-maven-releases/ua/gov/mdtu/ddm/infrastructure/mdtu-ddm-platform/<version>/mdtu-ddm-platform-<version>.zip
----

. Розпакуйте архів у домашній директорії.

+
[source,shellscript]
----
unzip /tmp/mdtu-ddm-platform-<version>.zip -d /home/<user>/workdir/installer-<version>
----

. Перенесіть _kubeconfig_ після встановлення кластера:

+
[source,shellscript]
----
cd /home/<user>/workdir/installer-<version>
cp /path/to/kubeconfig ./
----

. Перенесіть папку _certificates_ для DSO.
+
NOTE: Якщо сертифікати не змінювалися, даний крок можна пропустити.

+
[source,shellscript]
----
cp /path/to/folder/certificates ./
----

=== Додавання окремого конфігураційного файлу для розгортання в середовищі vSphere

. Перенесіть _exports.list_ з минулого релізу.

+
[source,shellscript]
----
cp /home/<user>/workdir/installer-<previous_version>/exports.list ./
----
+
Також необхідно уточнити актуальні значенння для `idgovuaClientId` та `idgovuaClientSecret`.

. Відредагуйте _install.sh_, а саме після `source ./functions.sh` додайте `source ./exports.list`.

+
[source,shellscript]
----
vi install.sh
----
+
Це виглядатиме наступним чином:

+
[source,shellscript]
----
#!/usr/bin/env bash
set -e
#Include function file
source ./functions.sh
source ./exports.list
----

=== Налаштування компонента MinIO при оновленні кластера у середовищі vSphere

. Перенесіть tfstate MinIO з минулого релізу для vSphere.

+
[source,shellscript]
----
cp /home/<user>/workdir/installer-<version>/terraform/minio/vsphere/terraform.tfstate ./terraform/minio/vsphere/
----

. Перенесіть tfstate MinIO (Packer) з минулого релізу для vSphere.

+
[source,shellscript]
----
сp /home/<user>/workdir/installer-<version>/terraform/minio/vsphere/packer/terraform.tfstate ./terraform/minio/vsphere/packer/
----

=== Налаштування компонента Vault при оновленні кластера у середовищі vSphere

. Перенесіть tfstate Vault з минулого релізу.

+
[source,shellscript]
----
cp /home/<user>/workdir/installer-<version>/terraform/vault/vsphere/terraform.tfstate ./terraform/vault/vsphere/
----

. Перенесіть tfstate Vault (Packer) з минулого релізу.

+
[source,shellscript]
----
сp /home/<user>/workdir/installer-<version>/terraform/vault/vsphere/packer/terraform.tfstate ./terraform/vault/vsphere/packer/
----

=== Розгортання інсталятора

. Виконайте наступні команди:
+
[source,shellscript]
----
IMAGE_CHECKSUM=$(sudo docker load -i control-plane-installer.img | sed -r "s#.*sha256:(.*)#\\1#" | tr -d '\n');
echo $IMAGE_CHECKSUM
sudo docker tag ${IMAGE_CHECKSUM} control-plane-installer:<version>;
----

. Оновіть версію Платформи з образами оновлення.
+
[source,shellscript]
----
sudo docker run --rm --name control-plane-installer-<version> --user root:$(id -g) --net host -v $(pwd):/tmp/installer --env KUBECONFIG=/tmp/installer/kubeconfig --env idgovuaClientId=mock --env idgovuaClientSecret=mock --env CUSTOM_INGRESS_CIDRS="['0.0.0.0/0', '85.223.209.0/24']" --env deploymentMode=development --entrypoint "/bin/bash" control-plane-installer:<version> -c "./install.sh -u"
----
+
* Де `deploymentMode` може бути `development` чи `production` в залежності від минулого запуску.

== Розгортання кластера платформи з нуля у середовищі AWS

=== Передумови

NOTE: Переконайтеся, що встановлено необхідні пакети: `docker`, `wget`, `unzip`.

[prerequisites-plan]
==== План

. Завантажте необхідну версію інсталера.
+
[source,shellscript]
----
сd /tmp
wget -O mdtu-ddm-platform-<version>.zip https://nexus-public-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/repository/edp-maven-releases/ua/gov/mdtu/ddm/infrastructure/mdtu-ddm-platform/<version>/mdtu-ddm-platform-<version>.zip
----

. Розпакуйте архів у домашній директорії.

+
[source,shellscript]
----
unzip /tmp/mdtu-ddm-platform-<version>.zip -d /home/<user>/workdir/installer-<version>
----

. Перенесіть _kubeconfig_ після встановлення кластера:

+
[source,shellscript]
----
cp /path/to/kubeconfig ./
----

=== Розгортання інсталера

. Виконайте наступні команди:
+
[source,shellscript]
----
IMAGE_CHECKSUM=$(sudo docker load -i control-plane-installer.img | sed -r "s#.*sha256:(.*)#\\1#" | tr -d '\n');
echo $IMAGE_CHECKSUM
sudo docker tag $\{IMAGE_CHECKSUM} control-plane-installer:<version>;
----

. Розгорніть нову версію платформи з образами з нуля.
+
[source,shellscript]
----
sudo docker run --rm --name control-plane-installer-*(version)* --user root:$(id -g) --net host -v $(pwd):/tmp/installer --env KUBECONFIG=/tmp/installer/kubeconfig --env idgovuaClientId=f90ab33dc272f047dc330c88e5663b75 --env idgovuaClientSecret=cba49c104faac8c718e6daf3253bc55f2bf11d9e --env CUSTOM_INGRESS_CIDRS="['0.0.0.0/0', '85.223.209.0/24']" --entrypoint "/bin/sh" control-plane-installer:*(version)* -c "./install.sh -i"
----

== Оновлення кластера платформи у середовищі AWS

=== Передумови

NOTE: Переконайтеся, що встановлено необхідні пакети: `docker`, `wget`, `unzip`.

[prerequisites-plan]
==== План

. Завантажте необхідну версію інсталера.
+
[source,shellscript]
----
сd /tmp
wget -O mdtu-ddm-platform-<version>.zip https://nexus-public-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/repository/edp-maven-releases/ua/gov/mdtu/ddm/infrastructure/mdtu-ddm-platform/<version>/mdtu-ddm-platform-<version>.zip
----

. Розпакуйте архів у домашній директорії.

+
[source,shellscript]
----
unzip /tmp/mdtu-ddm-platform-<version>.zip -d /home/<user>/workdir/installer-<version>
----

. Перенесіть _kubeconfig_ після встановлення кластера:

+
[source,shellscript]
----
cp /path/to/kubeconfig ./
----

=== Налаштування компонента Minio при оновленні кластера у середовищі AWS

. Перенесіть tfstate minio з минулого релізу.

+
[source,shellscript]
----
cp /home/<user>/workdir/installer-<version>/terraform/minio/aws/terraform.tfstate ./terraform/minio/aws/
----

=== Налаштування компонента Vault при оновленні кластера у середовищі AWS

. Перенесіть tfstate vault з минулого релізу.

+
[source,shellscript]
----
cp /home/<user>/workdir/installer-<version>/terraform/vault/aws/terraform.tfstate ./terraform/vault/aws/
----

=== Розгортання інсталера

. Виконайте наступні команди:
+
[source,shellscript]
----
IMAGE_CHECKSUM=$(sudo docker load -i control-plane-installer.img | sed -r "s#.*sha256:(.*)#\\1#" | tr -d '\n');
echo $IMAGE_CHECKSUM
sudo docker tag $\{IMAGE_CHECKSUM} control-plane-installer:<version>;
----

. Оновіть версію платформи з образами оновлення.
+
[source,shellscript]
----
sudo docker run --rm --name control-plane-installer-*(version)* --user root:$(id -g) --net host -v $(pwd):/tmp/installer --env KUBECONFIG=/tmp/installer/kubeconfig --env idgovuaClientId=f90ab33dc272f047dc330c88e5663b75 --env idgovuaClientSecret=cba49c104faac8c718e6daf3253bc55f2bf11d9e --env CUSTOM_INGRESS_CIDRS="['0.0.0.0/0', '85.223.209.0/24']" --entrypoint "/bin/sh" control-plane-installer:*(version)* -c "./install.sh -u"
----