= Автоматичне розгортання компонентів Minio та Vault
:toc-title: ЗМІСТ
:toc: auto
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

== Розгортання кластера платформи з нуля у середовищі vSphere

=== Передумови

NOTE: Переконайтеся, що встановлено необхідні пакети: `docker`, `wget`, `unzip`.

[prerequisites-plan]
==== План

. Завантажте необхідну версію інсталера.
+
[source,shellscript]
----
сd /tmp
wget -O mdtu-ddm-platform-<version>.zip https://nexus-public-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/repository/edp-maven-releases/ua/gov/mdtu/ddm/infrastructure/mdtu-ddm-platform/<version>/mdtu-ddm-platform-<version>.zip
----

. Розпакуйте архів у домашній директорії.

+
[source,shellscript]
----
unzip /tmp/mdtu-ddm-platform-<version>.zip -d /home/<user>/workdir/installer-<version>
----

. Перенесіть _kubeconfig_ після встановлення кластера:

+
[source,shellscript]
----
cp /path/to/kubeconfig ./
----

=== Додавання окремого конфігураційного файлу для розгортання в середовищі vSphere

. Відредагуйте _exports.list_ для vSphere.
+
Усі значення необхідно взяти після інсталяції кластера.

+
[source,shellscript]
----
vi exports.list

export KUBECONFIG="/home/<user>/workdir/installer-<version>/kubeconfig"

### vSphere Credentials ###
export VSPHERE_SERVER=""
export VSPHERE_USER=""
export VSPHERE_PASSWORD=""
export VSPHERE_CLUSTER=""
export VSPHERE_DATASTORE=""
export VSPHERE_DATACENTER=""
export VSPHERE_NETWORK=""
export VSPHERE_NETWORK_GATEWAY=""
export VSPHERE_RESOURCE_POOL=""
export VSPHERE_FOLDER=""

### Minio and Vault IPs ###
export VSPHERE_VAULT_INSTANCE_IP=""
export VSPHERE_MINIO_INSTANCE_IP=""

### id.gov.ua ###
export idgovuaClientId=""
export idgovuaClientSecret=""
----

. Відредагуйте _install.sh_, а саме після `source ./functions.sh` додайте `source ./exports.list` для vSphere.

+
[source,shellscript]
----
vi install.sh
----
+
Це виглядатиме наступним чином:

+
[source,shellscript]
----
#!/usr/bin/env bash
set -e
#Include function file
source ./functions.sh
source ./exports.list
----

=== Розгортання інсталера

. Виконайте наступні команди:
+
[source,shellscript]
----
IMAGE_CHECKSUM=$(sudo docker load -i control-plane-installer.img | sed -r "s#.*sha256:(.*)#\\1#" | tr -d '\n');
echo $IMAGE_CHECKSUM
sudo docker tag $\{IMAGE_CHECKSUM} control-plane-installer:<version>;
----

. Розгорніть нову версію платформи з образами з нуля.
+
[source,shellscript]
----
sudo docker run --rm --name control-plane-installer-*(version)* --user root:$(id -g) --net host -v $(pwd):/tmp/installer --env KUBECONFIG=/tmp/installer/kubeconfig --env idgovuaClientId=f90ab33dc272f047dc330c88e5663b75 --env idgovuaClientSecret=cba49c104faac8c718e6daf3253bc55f2bf11d9e --env CUSTOM_INGRESS_CIDRS="['0.0.0.0/0', '85.223.209.0/24']" --entrypoint "/bin/sh" control-plane-installer:*(version)* -c "./install.sh -i"
----

== Оновлення кластера платформи у середовищі vSphere

=== Передумови

NOTE: Переконайтеся, що встановлено необхідні пакети: `docker`, `wget`, `unzip`.

[prerequisites-plan]
==== План

. Завантажте необхідну версію інсталера.
+
[source,shellscript]
----
сd /tmp
wget -O mdtu-ddm-platform-<version>.zip https://nexus-public-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/repository/edp-maven-releases/ua/gov/mdtu/ddm/infrastructure/mdtu-ddm-platform/<version>/mdtu-ddm-platform-<version>.zip
----

. Розпакуйте архів у домашній директорії.

+
[source,shellscript]
----
unzip /tmp/mdtu-ddm-platform-<version>.zip -d /home/<user>/workdir/installer-<version>
----

. Перенесіть _kubeconfig_ після встановлення кластера:

+
[source,shellscript]
----
cp /path/to/kubeconfig ./
----

=== Додавання окремого конфігураційного файлу для розгортання в середовищі vSphere

. Перенесіть _exports.list_ з минулого релізу.

+
[source,shellscript]
----
cd /home/<user>/workdir/installer-<version>
cp /home/<user>/workdir/installer-<previous_version>/exports.list ./
----

=== Налаштування компонента Minio при оновленні кластера у середовищі vSphere

. Перенесіть tfstate minio з минулого релізу для vSphere.

+
[source,shellscript]
----
cp /home/<user>/workdir/installer-<version>/terraform/minio/vsphere/terraform.tfstate ./terraform/minio/vsphere/
----


. Перенесіть tfstate minio (packer) з минулого релізу для vSphere.

+
[source,shellscript]
----
сp /home/<user>/workdir/installer-<version>/terraform/minio/vsphere/packer/terraform.tfstate ./terraform/minio/vsphere/packer/
----

=== Налаштування компонента Vault при оновленні кластера у середовищі vSphere

. Перенесіть tfstate vault з минулого релізу.

+
[source,shellscript]
----
cp /home/<user>/workdir/installer-<version>/terraform/vault/vsphere/terraform.tfstate ./terraform/vault/vsphere/
----

. Перенесіть tfstate vault (packer) з минулого релізу.

+
[source,shellscript]
----
сp /home/<user>/workdir/installer-<version>*/terraform/vault/vsphere/packer/terraform.tfstate ./terraform/vault/vsphere/packer/
----

=== Розгортання інсталера

. Виконайте наступні команди:
+
[source,shellscript]
----
IMAGE_CHECKSUM=$(sudo docker load -i control-plane-installer.img | sed -r "s#.*sha256:(.*)#\\1#" | tr -d '\n');
echo $IMAGE_CHECKSUM
sudo docker tag $\{IMAGE_CHECKSUM} control-plane-installer:<version>;
----

. Оновіть версію платформи з образами оновлення.
+
[source,shellscript]
----
sudo docker run --rm --name control-plane-installer-*(version)* --user root:$(id -g) --net host -v $(pwd):/tmp/installer --env KUBECONFIG=/tmp/installer/kubeconfig --env idgovuaClientId=f90ab33dc272f047dc330c88e5663b75 --env idgovuaClientSecret=cba49c104faac8c718e6daf3253bc55f2bf11d9e --env CUSTOM_INGRESS_CIDRS="['0.0.0.0/0', '85.223.209.0/24']" --entrypoint "/bin/sh" control-plane-installer:*(version)* -c "./install.sh -u"
----

== Розгортання кластера платформи з нуля у середовищі AWS

=== Передумови

NOTE: Переконайтеся, що встановлено необхідні пакети: `docker`, `wget`, `unzip`.

[prerequisites-plan]
==== План

. Завантажте необхідну версію інсталера.
+
[source,shellscript]
----
сd /tmp
wget -O mdtu-ddm-platform-<version>.zip https://nexus-public-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/repository/edp-maven-releases/ua/gov/mdtu/ddm/infrastructure/mdtu-ddm-platform/<version>/mdtu-ddm-platform-<version>.zip
----

. Розпакуйте архів у домашній директорії.

+
[source,shellscript]
----
unzip /tmp/mdtu-ddm-platform-<version>.zip -d /home/<user>/workdir/installer-<version>
----

. Перенесіть _kubeconfig_ після встановлення кластера:

+
[source,shellscript]
----
cp /path/to/kubeconfig ./
----

=== Розгортання інсталера

. Виконайте наступні команди:
+
[source,shellscript]
----
IMAGE_CHECKSUM=$(sudo docker load -i control-plane-installer.img | sed -r "s#.*sha256:(.*)#\\1#" | tr -d '\n');
echo $IMAGE_CHECKSUM
sudo docker tag $\{IMAGE_CHECKSUM} control-plane-installer:<version>;
----

. Розгорніть нову версію платформи з образами з нуля.
+
[source,shellscript]
----
sudo docker run --rm --name control-plane-installer-*(version)* --user root:$(id -g) --net host -v $(pwd):/tmp/installer --env KUBECONFIG=/tmp/installer/kubeconfig --env idgovuaClientId=f90ab33dc272f047dc330c88e5663b75 --env idgovuaClientSecret=cba49c104faac8c718e6daf3253bc55f2bf11d9e --env CUSTOM_INGRESS_CIDRS="['0.0.0.0/0', '85.223.209.0/24']" --entrypoint "/bin/sh" control-plane-installer:*(version)* -c "./install.sh -i"
----

== Оновлення кластера платформи у середовищі AWS

=== Передумови

NOTE: Переконайтеся, що встановлено необхідні пакети: `docker`, `wget`, `unzip`.

[prerequisites-plan]
==== План

. Завантажте необхідну версію інсталера.
+
[source,shellscript]
----
сd /tmp
wget -O mdtu-ddm-platform-<version>.zip https://nexus-public-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/repository/edp-maven-releases/ua/gov/mdtu/ddm/infrastructure/mdtu-ddm-platform/<version>/mdtu-ddm-platform-<version>.zip
----

. Розпакуйте архів у домашній директорії.

+
[source,shellscript]
----
unzip /tmp/mdtu-ddm-platform-<version>.zip -d /home/<user>/workdir/installer-<version>
----

. Перенесіть _kubeconfig_ після встановлення кластера:

+
[source,shellscript]
----
cp /path/to/kubeconfig ./
----

=== Налаштування компонента Minio при оновленні кластера у середовищі AWS

. Перенесіть tfstate minio з минулого релізу.

+
[source,shellscript]
----
cp /home/<user>/workdir/installer-<version>/terraform/minio/aws/terraform.tfstate ./terraform/minio/aws/
----

=== Налаштування компонента Vault при оновленні кластера у середовищі AWS

. Перенесіть tfstate vault з минулого релізу.

+
[source,shellscript]
----
cp /home/<user>/workdir/installer-<version>/terraform/vault/aws/terraform.tfstate ./terraform/vault/aws/
----

=== Розгортання інсталера

. Виконайте наступні команди:
+
[source,shellscript]
----
IMAGE_CHECKSUM=$(sudo docker load -i control-plane-installer.img | sed -r "s#.*sha256:(.*)#\\1#" | tr -d '\n');
echo $IMAGE_CHECKSUM
sudo docker tag $\{IMAGE_CHECKSUM} control-plane-installer:<version>;
----

. Оновіть версію платформи з образами оновлення.
+
[source,shellscript]
----
sudo docker run --rm --name control-plane-installer-*(version)* --user root:$(id -g) --net host -v $(pwd):/tmp/installer --env KUBECONFIG=/tmp/installer/kubeconfig --env idgovuaClientId=f90ab33dc272f047dc330c88e5663b75 --env idgovuaClientSecret=cba49c104faac8c718e6daf3253bc55f2bf11d9e --env CUSTOM_INGRESS_CIDRS="['0.0.0.0/0', '85.223.209.0/24']" --entrypoint "/bin/sh" control-plane-installer:*(version)* -c "./install.sh -u"
----