= Вимоги до OKD-кластерів щодо інсталювання Платформи
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

Для виведення Платформи реєстрів у промислову експлуатацію слід обов'язково використовувати віртуальні інфраструктури, що отримують офіційну підтримку. Наразі це: https://aws.amazon.com/[Amazon Web Services (AWS)], https://azure.microsoft.com/[Microsoft Azure (Azure)], https://cloud.google.com/[Google Cloud Platform (GCP)] та https://www.vmware.com/products/vsphere.html[VMWare vSphere]. На таких інфраструктурах необхідно встановити OKD-кластер, версія якого відповідає вимогам Платформи, визначеним нижче.

.Вимоги до OKD-кластерів щодо інсталювання Платформи реєстрів
[options="header"]
|===
| +++<b style="font-weight: 700">Версія Платформи<b>+++ | +++<b style="font-weight: 700"> Підтримувані версії OKD <b>+++
| `1.9.2` | `4.11`
| `1.9.3` | `4.11`
| `1.9.4` | `4.11`
| `1.9.5` | `4.11`
| `1.9.6` | `4.11`
|===

Встановлення та налаштування Платформи виконується відповідно до вказівок, наданих в офіційній документації Платформи:

* xref:admin:installation/platform-deployment/platform-deployment-overview.adoc[]