:sectanchors:
:sectlinks:
= Встановлення та налаштування

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

В цьому розділі описані усі аспекти, пов'язані з розгортанням Платформи.

В підрозділі *Вимоги до OKD-кластерів щодо інсталювання Платформи* можна знайти опис віртуальних інфраструктур, які підтримуються, а також вимоги до встановлення кластеру OKD залежно від версії Платформи.

Підрозділ *Розгортання Платформи на цільових оточеннях* надає покрокові інструкції для розгортання Платформи в чотирьох хмарних середовищах.

Підрозділ *Налаштування внутрішнього SMTP-сервера* надає необхідну інформацію для забезпечення налаштування компонента `smtp-server`, що використовується для надсилання сповіщень користувачам Платформи.

У підрозділі *Зміна мережевого провайдера кластера OKD 4.x* ви можете дізнатися про доступні варіанти зміни мережевого провайдера.

Підрозділ *Безпечне налаштування адміністративних акаунтів* описує детальні політики безпеки для налаштування облікових записів користувачів.

== Огляд розділу

* xref:installation/okd-requirements.adoc[Вимоги до OKD-кластерів щодо інсталювання Платформи]
* xref:installation/platform-deployment/platform-deployment-overview.adoc[Розгортання Платформи на цільових оточеннях]
* xref:installation/internal-smtp-server-setup.adoc[Налаштування внутрішнього SMTP-сервера]
* xref:installation/changing-network-provider.adoc[Зміна мережевого провайдера кластера OKD 4.x]
* xref:installation/admins-security/overview.adoc[]