//:imagesdir: ../../../images
= Облік джерел походження даних реєстру

image::architecture/registry/operational/registry-management/data-provenance.drawio.svg[width=640,float="center",align="center"]

* **JSON документ форми**: документ який містить дані які були внесені та підписані на формі бізнес-процесу. Бізнес-процес що змінює дані може бути як користувацьким так і автоматичним. В разі якщо зміна відбулась в результаті роботи користувацького бізнес-процесу, дані підписує користувач своїм КЕП та цей підпис зберігається в документі. В разі якщо дані міняє автоматичний бізнес-процес то ці дані підписуються системним підписом який так само зберігається в документі.
* **JSON документ API**: похідний від _JSON документу форми_ документ, дані в якому відповідають контракту API підсистеми управління даними реєстру. Створюється автоматично в результаті трансформації структури даних з _JSON документу форми_ в формат сумісний з API. Один _JSON документу форми_ може породити декілька _JSON документів API_ вразі якщо на формі було внесено інформацію яка зберігається в декількох таблицях. Всі дані в цьому документі підписано системним підписом.
* **Первинне завантаження**: частина регламенту реєстру яка містить дані та правила для первинного завантаження. Зберігаються як файли в герріт репозиторії регламенту реєстру, який зберігає інформацію про користувача який створив або змінив ці файли.
* **Історія запису таблиці реєстру**: запис який створюється при кожній зміні даних реєстру. В ній зберігається стан запису реєстру на момент зміни. Також вона містить посилання на процес який зробив цю зміну, це може бути або бізнес-процес, або процес первинного завантаження. В разі якщо зміна відбулася в результаті роботи бізнес процесу зберігається посилання на бізнес-процес, _JSON документ форми_ та _JSON документ API_. В разі якщо зміна відбулася в результаті роботи первинного завантаження, зберігається лише інформація про те що джерело даних initial load (первинне завантаження).
* **Запис таблиці реєстру**: запис в якому зберігається актуальний стан запису реєстру.
* **Файли**: вкладені цифрові документи реєстру (файли). Посилання на ці файли разом з контрольною сумою є частиною даних реєстру, які підписуються згідно з описаними вище правилами.

== Інформація про походження в залежності від джерела

[cols="h,^.^,^.^,^.^"]
|===
| |Користувацький бізнес-процес|Автоматичний бізнес-процес|Первинне завантаження

|Документ джерело|✓|✓|✓
|Інформація про автора|✓|✓|✓
|Документ підписано системою|✓|✓|✕
|Документ підписано користувачем|✓|✕|✕

|===