= Публічний API для читання даних.

== Загальний опис

Для забезпечення доступу широкого загалу до даних реєстру які вважаються публічними та забезпечення можливості для сторонніх систем отримувати такі дані в актуальному стані, обробляти та візуалізувати їх, надається можливість позначати окремі пошукові критерії (`search conditions`) як публічні, що дозволить надалі використовувати їх без необхідності автентифікуватись.


== Функціональні сценарії

* Публікація пошукових запитів
* Отримання документації та використання публічного API
* Моніторинг стану та використання публічних пошукових критеріїв
* Масштабування публічного API

== Ролі користувачів

* Розробник регламенту
* Технічний адміністратор реєстру

== Загальні принципи та положення

* Публічним вважаються той API який не потребує автентифікації з боку клієнта.
* Запити до Дата Фабрики здійснюються від імені системного користувача
* В якості публічного API може бути представлені тільки пошукові запити (`search conditions`)
* Обмеження доступу до публічного API (rate limits, ip blacklist, geoip, захист від ddos-атак) поза межами даного дизайну


== Високорівневий дизайн рішення

image::arch:architecture-workspace/platform-evolution/public-api/context.svg[]

[NOTE]
В першій ітерації вирішено не виділяти окремий екземпляр API Gateway для публічного API.

=== Діаграма міжсервісної взаємодії

[plantuml]
----
autonumber
actor "Особа" as user
participant "API Gateway\n(Kong)" as g
participant "Platform Gateway" as pg
participant "Keycloack" as um
participant "REST API\n(public)" as rest
user -> g: /api/public/data-factory/{public-search}
g -> pg:  /public/data-factory/{public-search}
pg -> pg: перевірка наявності токена
pg -> um: автентифікація публічним користувачем
return JWT-токен
pg -> pg: кешування токена
pg -> rest: http://registry-rest-api-public.{registry}.svc.cluster.local:8080\n/{public-search}
return результати запиту
pg --> g:
g --> user:
----


== Моделювання регламенту реєстру

=== Структура регламенту

Управління доступом здійснюється на рівні конфігурації дата моделі за допомогою тегу `exposeSearchCondition`

=== Розширення для моделювання

[source, xml]
----
<exposeSearchCondition public="true" trembita="true"  name="public-search-condition"/>
----

При виставленні API як публічне, та моделюванні `searchCondition` для них моделювальнику слід взяти до уваги наступні рекомендації:

* Кожен `searchCondition` який має бути опублікований як публічний, має бути створений окремо для цього сценарію, не варто виставляти до публічного доступу `searchCondition` яки використовуються для кабінетів, бізнес процесів та інтеграцій з _ШБО Трембіта_.
* Рекомендований тип пагінації `page`, оскільки він дає змогу бачити загальну кількість записів не відображаючи їх.
* `limit` для таких `searchCondition` має бути підібраний в залежності від типу даних і має бути найменшим достатнім.

== Розгортання сервісів

Для забезпечення відмовостійкості та відокремлення публічних запитів від інших задля підвищення безпеки розгортається окремий екземпляр сервісу `rest-api`.
Налаштування

=== Конфігурація NetworkPolicy

Публічний екземпляр `REST API` можу бути доступний лише:

* Користувач `public-user` з `realm`-у `external-system`
* Тільки за допомогою метода `GET`
* Тільки до `url` які були виставлені публічно та посилання до OpenAPI специфікації
* Технічні лінки для актуатора та health-check мають бути доступні тільки в середині кластеру

== Низькорівневий дизайн сервісів

=== Компоненти та їх призначення

|===
|Компонент|Призначення

|infrastructure/monitoring
|Встановлення та конфігурація моніторингу платформи
|data-architecture/libraries/ddm-starter-swagger
|Бібліотека для генерації `OpenAPI`-специфікації на основі внутрішніх правил
|general/registry-configuration
|Конфігурація та створення ресурсів реєстру
|===

=== Ключові сценарії

==== Моніторинг стану та навантаження для публічних API

Створення `ConfigMap` з дашбордом для моніторингу
.monitoring/deploy-templates/dashboard/public-api.yaml
[source, yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-public-api
data:
  public-api-statistic.json: |-
  ...
----


.monitoring/deploy-templates/values.yaml
[source, yaml]
----
dashboardsConfigMaps:
  - configMapName: grafana-public-api
    fileName: public-api-statistic.json
----


Ключові метрики:

* Кількість запитів по кожній точці інтеграції
* Кількість успішних 2хх кодів, помилок сервера 5хх, та помилок клієнту 4хх, всі інші коди можуть бути винесені в окрему групу
* Статистика швидкодії (найдовший запит, середні, найшвидший )

==== Отримання документації до публічного API
Отримання специфікації (`OpenAPI`) для API який був позначений як публічний. (https://springdoc.org/faq.html#how-can-i-agreagte-external-endpoints-exposing-openapi-3-spec-inside-one-single-application[приклад])


==== Створення користувача

Створення службового користувача `public-user` для реєстру.

.general/registry-configuration/values.yaml
[source, yaml]
----
    publicUser:
      name: public-user
      clientId: public-user
      public: false
      secretName: keycloak-public-user-client-secret
      targetRealm:
        name: external-system
    ...
----

Також налаштування JVM машини доступні для конфігурації Технічному адміністратору реєстру через технічну консоль адміністратора.