= Локалізація Redash Admin та Redash Viewer

[IMPORTANT]
--
Сторінка технічної документації є баченням майбутньої реалізації, актуальність якого може бути застарілою.
--

== Загальний опис

Необхідно реалізувати можливість підтримки декількох мов інтерфейсу перегляду звітів для посадових осіб (Redash Viewer) та інтерфейсу для створення та налаштування аналітичних звітів та дашбордів (Redash Admin) в залежності від обраної мови реєстру.

== Актори та ролі користувачів
* Технічний адміністратор Платформи
* Технічний адміністратор реєстру
* Адміністратор реєстру (користувач Admin Portal, а саме Redash Admin)
* Посадова особа (користувач Office Portal, а саме Redash Viewer)

== Функціональні сценарії
* Cтворення та налаштування аналітичних звітів та інформаційних панелей мовою реєстра.
* Перегляд та маніпуляція відображенням даних реєстру на інформаційних панелях мовою реєстра.
* Перегляд та аналіз даних журналу подій аудиту реєстру на інформаційних панелях мовою реєстра.

== Поточна реалізація

Кожен екземпляр сервісу аналітичної звітності реєстру Redash (Viewer та Admin) розгортається українською мовою без можливості зміни при розгортанні.
Вихідний redash докер образ збирається англійською мовою.
Локалізація українською мовою відбувається на етапі збірки `redash-chart` за допомогою додаткового main.py скрипта та заготовленого файлу з перекладом слів та словосполучень redash_localization_words.csv.

Така поточна реалізація не дозволяє встановити залежність між обраною мовою реєстру з розділу Керування реєстрами у адмінпанель Control Plane та процесом розгортання екземплярів Redash (Viewer та Admin).

== Загальні принципи та положення

* Redash не локалізується українською на етапі збірки `redash-chart`.
* Існуючий файл `redash_localization_words.csv` з перекладом слів пакується в докер образ `redash-chart` на етапі збірки.
* Дії по локалізації redash виносяться з існуючого `redash-chart/main.py` у новий `redash-chart/uk_localization.py` та пакуються в докер образ `redash-chart` на етапі збірки.
* Обробляти global.language змінну в `redash-chart`. Якщо `uk`, тоді запускати скрипт 'uk_localization.py' при розгортанні контейнерів `redash-admin` та `redash-viewer`, якщо `en` - не запускати, лишаючи Redash не локалізованим.
* По можливості доповнити та виправити поточний український переклад.

== Цільовий дизайн

=== Збірка

Наразі процес локалізації відбувається за допомогою запуску `redash-chart/main.py` скрипта на етапі збірки `redash-chart` докер образу через інструкції:

.Dockerfile
[source,bash]
----
FROM nexus-docker-registry.apps.cicd2.mdtu-ddm.projects.epam.com/mdtu-ddm-edp-cicd/redash-master:1.7.0-SNAPSHOT.30 as source

FROM python:3.9.6 as local
COPY --from=source /app/client/dist/app.*.js /app/
...

COPY . /app
WORKDIR /app
RUN pip install pipenv
RUN pipenv install
RUN pipenv run python main.py

FROM source
COPY --from=local /app/app.*.js /app/client/dist/.
...
----

Необхідно винести процес локалізації в окремий `uk_localization.py` скрипт. Відповідно видаливши з `main.py`

.uk_localization.py
[source,python]
----
import ...

def load_excel_to_dict():
...

def wrap_as_variable(str):
...

def wrap_as_tag(str):
...

def localize(dict):
...

translations = load_excel_to_dict()
localize(translations)
----

Та додатково запакувати `uk_localization.py` скрипт в `redash-chart` докер образ для подальшого виклику при розгортанні:

.Dockerfile
[source,bash]
----
COPY uk_localization.py /app/
----

Видалити обробку `app.*.js` файлів з `Dockerfile`.

Перейменувати існуючий файл `redash_localization_words.csv` в `uk_redash_localization_words.csv` та також запакувати в `redash-chart` докер образ:

.Dockerfile
[source,bash]
----
COPY redash_localization_words.csv /app/
----

Привести шляхи до фалів у `uk_localization.py` скрипті до актуального стану.

=== Розгортання

Мова визначатиметься через змінну `global.language` у `values.yaml` кожного реєстру, що наразі матиме допустимі значення `uk` та `en`. За замовчуванням `en`.
Необхідно додати обробку значення `global.language` у `_helpers.tpl` файлі `redash-chart`, що визначатиме чи запускати скрипт локалізації `uk_localization.py` при розгортанні екземпляра Redash.
В результаті, якщо мова `en`, то скрипт не запускати. Якщо мова `uk`, то скрипт запускати. Наприклад, таким чином:

.admin-server-deployment.yaml
[source,yaml]
----
apiVersion: apps/v1
kind: Deployment
...
spec:
...
  containers:
  ...
      command: ["/bin/sh"]
      args: ["-c", "python ./uk_localization.py && . /config/dynamicenv.sh && /app/bin/docker-entrypoint server"]
----

Отже, при зміні мови реєстру через Адмінпанель Control Plane буде створений новий запит на оновлення, що призведе до зміни параметру `global.language` у `values.yaml` та перерозгорне екземпляри `redash-admin` та `redash-viewer` із актуальним значенням.

== Компоненти системи та їх призначення в рамках дизайну рішення

У даному розділі наведено перелік компонент системи, які задіяні або потребують змін в рамках реалізації дизайну.

|===
|Підсистема|Компонент|Модуль|Опис змін

|Підсистема аналітичної звітності реєстру
|*redash-viewer*
.2+|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/data-architecture/devops-application/redash-chart[gerrit:/mdtu-ddm/data-architecture/devops-application/redash-chart]
.2+|Винесення скриптів локалізації з процесу збірки докер образа на рівень розгортання. Опрацювання варіантів ввімкнення і вимкнення локалізації. Виправлення помилок поточного перекладу.

|Підсистема моделювання регламенту реєстру
|*redash-admin*

|Підсистема управління Платформою та Реєстрами
|*control-plane-console*
|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/data-architecture/devops-application/redash-chart[gerrit:/mdtu-ddm/data-architecture/devops-application/redash-chart]
|Розширення інтерфейсу управління реєстру коментарем.

|===

== Підтримка зворотної сумісності
За замовчуванням мова локалізації англійська, що може бути задано у `values.yaml` за допомогою встановлення параметру `global.language` в значення `en`.
Для існуючих реєстрів, що не потребують переключення на англійську мову, необхідно встановити `global.language` в значення `uk`.

== Високорівневий план розробки
=== Технічні експертизи
* _DevOps_
* _FE_

=== Попередній план розробки
* Винести процес локалізації в окремий `uk_localization.py` скрипт та запакувати в `redash-chart` докер образ.
* Запакувати uk_redash_localization_words.csv файл локалізації в `redash-chart` докер образ.
* Прибрати обробку `app.*.js` файлів з `Dockerfile`.
* В `_helpers.tpl` `redash-chart` обробляти змінну, що визначає мову на рівні реєстру.
* В залежності від мови запускати або ні скрипт `uk_localization.py` через `args` в темплейтах розгортання `redash-admin` та `redash-viewer`.
* По можливості доповнити та виправити поточний український переклад.
* В Control Plane в табі Реєстри на сторінці Загальні налаштування в розділі "Локалізація" під текстом "Кабінет адміністратора регламенту" додано фразу: Веб-інтерфейс моделювання звітів.

== Поза скоупом
* Адміністратор платформи чи адміністратор реєстру обирає для Redash Admin та/або Viewer мову, відмінну, від мови реєстру.
* Адміністратор платформи чи адміністратор реєстру обирає свою індивідуальну мову інтерфейсу.
* Визначення мови користувача в "Accept-Language" заголовку запиту або у разі відсутності перекладів для мови - використання налаштувань за замовчуванням обраних на етапі встановлення екземпляру Платформи.
* Локалізація елементів, недоступних для зміни після збірки redash компонента.
