= Компоненти та звʼязки підсистеми формування витягів реєстру

== Загальний опис
Ця сторінка відображає діаграму компонент підсистеми формування витягів реєстру.

Наступна діаграма відображає критичні залежності між окремими компонентами підсистеми, розподіленими по трьом ключовим рівням:

* Рівень Helmfile – залежності helm-чартів та порядок розгортання
* Рівень Readiness Probes – залежності на готовність компонента до прийому трафіку
* Рівень Init-контейнерів – залежність на ініціалізацію компонента підсистеми.

.Діаграма компонент та їх залежностей
[plantuml]
----
@startuml
skinparam Linetype ortho

package "Підсистема формування витягів реєстру" #MediumSeaGreen {
component [excerpt-service-api]
}

package "Підсистема управління реляційними базами даних" #SkyBlue {
component [operational pool]
}

package "Підсистема управління нереляційними базами даних" #SkyBlue {
component [rfs-redis-sentinel]
}

package "Підсистема асинхронного обміну повідомленнями" #SkyBlue {
component [kafka-cluster]
}

[excerpt-service-api] -down-> [operational pool]
[excerpt-service-api] -down-> [rfs-redis-sentinel]
[excerpt-service-api] -> [kafka-cluster]
note top of [excerpt-service-api]
 1. To Start: init container (postgres, kafka),
 readiness probe (to Redis, to Postgres, to Kafka)
 2. Helmfile needs: kafka, postgres
end note
@enduml

----

Діаграма служить як комплексний графічний засіб для допомоги наданню більш прозорого розуміння структури підсистеми,
розв'язання проблем сполучення компонентів і планування оптимізації підсистеми реєстру.
