= Використання платформного Nexus замість реєстрового при створенні реєстру

В цьому перехідному дизайні розглядається надання опційної можливості використання для потреб реєстру центрального сховища артефактів Платформи.

[IMPORTANT]
--
Сторінка технічної документації є баченням майбутньої реалізації, актуальність якого може бути застарілою.
--

== Актори та ролі користувачів
* Технічний адміністратор Платформи
* Технічний адміністратор реєстру
* Моделювальник регламенту реєстру

== Загальний опис
З точки зору роботи підсистем розгортання та моделювання регламенту реєстру, необхідно мати сховище для зберігання згенерованих
артефактів реєстрових компонентів (registry-rest-api, registry-kafka-api, registry-soap-api, registry-model), а саме їх
Docker образи та JAR (Java Archive) файли.

Задля економії ресурсів реєстру (CPU, RAM) пропонується надати можливість адміністратору Платформи при створенні реєстру
обирати потрібне сховище.

== Функціональні сценарії
* Створення нового реєстру
* Розгортання регламенту реєстру

== Поточна реалізація
В поточній реалізації Платформи, для виконання цієї вимоги під кожний реєстр розгортається своє власне сховище артефактів (SonarType Nexus).

.Фрагмент діаграми взаємодії між компонентами підсистем
image::architecture-workspace/platform-evolution/optional-registry-nexus/as-is-nexus.drawio.svg[]

[TIP]
--
Докладніше про поточну реалізацію описано у відповідних підсистемах:

* xref:arch:architecture/platform/administrative/config-management/overview.adoc[]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[]
--

== Загальні принципи та положення
* При створенні реєстру, на адмін-консолі доступний вибір типу сховища артефактів (центральне або виділене реєстрове сховище)
* Налаштування типу сховища артефактів недоступне для редагування після створення.
* При обраному "центральному" сховищі, відбувається налаштування відповідних компонентів в реєстрі для роботи з ним.
* При обраному "виділеному" реєстровому сховищі відбувається розгортання компонентів `nexus-operator` що і розгортає реєстровий nexus.
* Реєстр має свій окремий maven репозиторій в Платформному сховищі Nexus.
* Реєстр не має свій окремий docker репозиторій в Платформному сховищі Nexus, а використовує вже існуючий.

== Цільовий дизайн
Після розробки та впровадження цього перехідного дизайну, адміністратор Платформи буде мати можливість обрати в якості сховище артефактів:

* Центральне сховище артефактів Платформи
* Виділене реєстрове сховище артефактів

image::architecture-workspace/platform-evolution/optional-registry-nexus/to-be-nexus.drawio.svg[]



== Компоненти системи та їх призначення в рамках дизайну рішення

== Високорівневий план розробки
=== Технічні експертизи
* _DevOps_

=== Попередній план розробки
