= File component
include::platform:ROOT:partial$templates/document-attributes/default-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== Component description

//Компонент *File* є елементом інтерфейсу, який дозволяє користувачам завантажувати або скачувати файли у формі. Form.io не розміщує жодних завантажених файлів у формах. Натомість файли зберігаються у постачальника сховища, в нашому випадку у _digital-document-service_.
The *File* component is a UI element that allows users to upload or download files in a form. Form.io does not host any uploaded files on forms. Instead, files are stored in a storage provider, in our case, _digital-document-service_.

CAUTION: There is no access to _digital-document-service_ in the _admin portal_.

CAUTION: Use File component from the list of _Latest_ components.

== Basic functions

//Компонент *File* підтримує велику кількість опцій для застосування при взаємодії із формою процесу, які розподілені за вкладками.
File component supports a large number of options for interaction with the process form, which are distributed across tabs.

[tabs]
====
Display ::
include::../general/common-descriptions/display/label.adoc[]
include::../general/common-descriptions/display/label-position.adoc[]
include::../general/common-descriptions/display/description.adoc[]
include::../general/common-descriptions/display/tooltip.adoc[]
include::../general/common-descriptions/display/tabindex.adoc[]
include::../general/common-descriptions/display/hidden.adoc[]
include::../general/common-descriptions/display/disabled.adoc[]

////
File ::
* *`Display as image(s)`*: замість назви завантаженого файлу у вікні буде відображатися зображення.
* *`File Pattern`*: вказує, які розширення файлів дозволено завантажувати. Файли, не вказані в цьому полі, будуть заборонені для завантаження.
* *`File Minimum Size`*: встановлює мінімальний розмір файлу. Значення має бути додатнім числом, з крапкою в якості розділового знаку у випадку десяткових дробів, з одиницями виміру В, КВ, МВ чи GB (значення без одиниці виміру буде читатися у байтах) та не перевищувати значення поля «File Maximum Size».
* *`File Maximum Size`*: встановлює максимальний розмір файлу. Значення має бути додатнім числом, з крапкою в якості розділового знаку у випадку десяткових дробів, з одиницями виміру В, КВ, МВ чи GB (значення без одиниці виміру буде читатися у байтах) та не перевищувати значення за замовчуванням, яке встановив адміністратор реєстру».
* *`Minimum total size`*: встановлює мінімальний розмір файлів. Значення має бути додатнім числом, з крапкою в якості розділового знаку у випадку десяткових дробів, з одиницями виміру В, КВ, МВ чи GB (значення без одиниці виміру буде читатися у байтах) та не перевищувати значення поля «Maximum total size». Відображається після активації _Multiple Values_.
* *`Maximum total size`*: встановлює максимальний розмір файлів. Значення має бути додатнім числом, з крапкою в якості розділового знаку у випадку десяткових дробів, з одиницями виміру В, КВ, МВ чи GB (значення без одиниці виміру буде читатися у байтах) та не перевищувати значення за замовчуванням, яке встановив адміністратор реєстру». Відображається після активації _Multiple Values_.
////

File ::
* *`Display as image(s)`*: instead of the uploaded file name, an image will be displayed in the window.
* *`File Pattern`*: specifies which file extensions are allowed to be uploaded. Files not specified in this field will be prohibited from being uploaded.
* *`File Minimum Size`*: Sets the minimum file size. The value must be a positive number, with a dot as the decimal separator, with units of B, KB, MB, or GB (a value without units will be read in bytes) and may not exceed the value of the «File Maximum Size».
* *`File Maximum Size`*: gpt-35-turbo icon
Sets the maximum file size. The value must be a positive number, with a dot as the decimal separator, with units of B, KB, MB, or GB (a value without units will be read in bytes) and may not exceed the default value set by the registry administrator.
* *`Minimum total size`*: sets the minimum file size. The value must be a positive number, with a dot as the decimal separator, with units of B, KB, MB, or GB (a value without units will be read in bytes) and may not exceed the value of the «Maximum total size» field. This is displayed after activating _Multiple Values_.
* *`Maximum total size`*: Sets the maximum file size. The value must be a positive number, with a dot as the decimal separator, with units of B, KB, MB, or GB (a value without units will be read in bytes) and may not exceed the default value set by the registry administrator. This is displayed after activating _Multiple Values_.

Data ::
* *`Multiple Values`*:Allows selecting multiple values.
include::../general/common-descriptions/data/clear-value-when-hidden.adoc[]
include::../general/common-descriptions/data/custom-default-value.adoc[]
include::../general/common-descriptions/data/calculated-value.adoc[]

Validation ::
include::../general/common-descriptions/validation/required.adoc[]
* *`Resource for validation`*: specifies which resource will be used to validate the file. This field is displayed when the user has specified the file extension _*.csv_ в _File Pattern_.
include::../general/common-descriptions/validation/custom-error-message.adoc[]
include::../general/common-descriptions/validation/custom-validation.adoc[]

API ::
include::../general/common-descriptions/api/index.adoc[]

Conditions ::
include::../general/common-descriptions/conditional/index.adoc[]

Table ::
include::../general/common-descriptions/table/index.adoc[]

====

=== Data format

.Submission
[source,typescript]
----
 // The data obtained from the digital-document-service after uploading the file.
[
    {
        checksum: "61b7aeab944b33b867550c4c4d94d66620228ea1094ed2dedb5003cc43807201",
        id: "f8ef4f2b-c37c-49a5-ba9a-a04c51507240"
    }
]
----
