= Примітки до релізу 1.9.7. Частина 6
:toc:
:toc-title: ЗМІСТ
:sectnums:
:sectlinks:
:sectanchors:
:note-caption: Покращено
:tip-caption: Розроблено
:caution-caption: Інше
:important-caption: Виправлено
:warning-caption: Покращення безпеки

== Використання _Дія.Підпис_ для автентифікації та підпису
//MDTUDDM-23534
//TODO: first.xlsx

[TIP]
====

* [*] Впроваджено використання _Дія.Підпис_ у нашій системі. Тепер отримувачі послуг -- фізичні особи та ФОП -- мають можливість використовувати _Дія.Підпис_ для автентифікації та підпису даних на формах у Кабінеті.

* [*] Для _Дія.Підпису_ тепер підтримуються такі ж правила валідації, як і для інших типів КЕП (Кваліфікованих Електронних Підписів).
====

== Використання хмарного ключа для автентифікації та підпису даних у Кабінеті
//MDTUDDM-23533
//TODO: first.xlsx

[TIP]
====

Надано можливість використання хмарного ключа для автентифікації та підпису: ::

* [*] Отримувач та надавач послуг може автентифікуватись на користувацькому порталі за допомогою хмарного ключа.

* [*] Отримувач та надавач послуг може підписувати дані, внесені через форми на користувацькому порталі, за допомогою хмарного ключа.

* [*] Додано можливість рендерингу QR-коду в компоненті `SignatureWidget` для Keycloak.

* [*] Додано можливість рендерингу QR-коду в компоненті `SignatureWidget` для Кабінету користувача.
====

== Перевірка підписаних даних, отриманих зі сторонньої системи: валідація КЕП та ідентифікація підписантів у файлах ASICS/CADES
//MDTUDDM-26500
//TODO: first.xlsx

[TIP]
====
Надано можливість перевіряти валідність підпису КЕП та його джерела, _коли підпис надійшов у бізнес-процес по API разом із даними (контейнер типу ASICS або CADES)_.

Розробник Регламенту тепер має делегат для перевірки валідності підпису даних та архіву файлів, що містять підпис: ::

* [*] Імплементовано необхідні ендпоінти в `digital-signature-ops` та `ddm-dso-client`.

* [*] Розроблено делегат та element template.

Розробник Регламенту тепер має відповідні JUEL-функції для отримання деталей про підписанта даних та архіву файлів, що містять підпис, та отримання контенту підписаних даних та архіву файлів, що містять підпис: ::

* [*] Розроблено JUEL-функцію `signature_details(...)`.

* [*] Розроблено JUEL-функцію `signature_content(...)`.

Розробник Регламенту тепер має референтний приклад можливості перевіряти валідність підпису КЕП і ким підписано контент: ::

* [*] Створено референтний бізнес-процес, як приклад валідації.
====

== Інструкція по розгортанню Платформи з Інсталера у цільовому приватному хмарному середовищі _vSphere_
//MDTUDDM-26142
//TODO: first.xlsx

[TIP]
====
* [*] Розроблено детальну покрокову інструкцію для адміністратора по розгортанню Платформи з нуля на кластері у приватному хмарному середовищі _vSphere_.
====

== Створення пам'ятки: виведення Платформи та реєстрів у промислову експлуатацію
//MDTUDDM-22886
//TODO: first.xlsx

[TIP]
====
* [*] Для полегшення процесу виводу реєстру та Платформи у промислове середовище, ми розробили спеціалізовану пам'ятку. Цей документ стане незамінним помічником для вашої команди під час переходу від тестової стадії до промислової експлуатації.

* [*] Пам'ятка містить вичерпний перелік передумов, послідовність кроків, докладний опис налаштувань, корисні рекомендації, а також інформацію про можливі проблеми, які можуть виникнути під час цього процесу, та шляхи їх вирішення.

* [*] Впровадження цього інструменту сприятиме більш гладкому та ефективному переходу вашої платформи та реєстрів в промислове середовище, зменшуючи ризики та забезпечуючи високу надійність системи.
====

== Зміна назви кабінету посадової особи на нейтральну з урахуванням користувачів-представників бізнесу
//MDTUDDM-26959
//TODO: first.xlsx

[TIP]
====
Змінено назву Кабінету посадової особи (надавача послуг) на нейтральну, яка є зрозумілою всім категоріям його користувачів, зокрема представникам бізнесу, що надають реєстраційні послуги.

* [*] Назву `Кабінет посадової особи` змінено на `Кабінет користувача`.
====

== Оновлення сертифікатів АЦСК для Платформи та реєстру через Control Plane без зміни ключа послуг
//MDTUDDM-22895
//TODO: first.xlsx

[TIP]
====
* [*] Запроваджено можливість оновлення сертифікатів надавачів послуг (файли _CA.json_, _CACertificates.p7b_) в адміністративній консолі Control Plane для адміністраторів Платформи та реєстру. Тепер оновлення можливе без внесення інформації про ключ для перевірки та формування підпису в Кабінетах користувачів.

* [*] Додатково, адміністраторам надана можливість оновлення переліку дозволених ключів. Це спрощує процес управління сертифікатами та підвищує гнучкість у роботі з сертифікатами надавачів послуг.

Це оновлення робить управління сертифікатами більш зручним та ефективним, мінімізуючи зусилля адміністраторів при забезпеченні безпеки та актуальності даних.
====

== Налаштування параметрів автентифікації та підпису даних через віджет, параметрів підпису через id.gov.ua для отримувачів послуг та автентифікація отримувачів послуг з _Дія.підпис_
//MDTUDDM-22796
//TODO: first.xlsx

[TIP]
====

* [*] Внесено зміни, що дозволяють адміністраторам реєстру налаштовувати для користувачів Кабінету отримувачів послуг специфічний спосіб підпису даних та вибирати віджет як метод автентифікації. Користувачам Кабінету тепер доступний лише один, визначений адміністратором, спосіб автентифікації.

* [*] Для користувачів ФО та ФОП імплементована можливість автентифікації за допомогою _Дія.підпису_ та _BankID_ з урахуванням обраного ними режиму автентифікації: "Для громадян" чи "Для бізнесу".

* [*] Користувачам ФОП і представникам ФОП та ЮО надана можливість автентифікації в Кабінеті через сервіс `id.gov.ua`, використовуючи КЕП.

* [*] Забезпечено можливість для користувачів підписувати дані за допомогою файлового та апаратного КЕПу у віджеті підпису, налаштованому через `id.gov.ua`, що підвищує гнучкість та зручність у використанні платформи.

Ці оновлення значно розширюють функціональність Кабінету отримувачів послуг, пропонуючи більше варіантів автентифікації та підпису, тим самим вдосконалюючи взаємодію користувачів із системою.
====

////

== Створення proxy-сервера для geoserver для підтримки розподілення за ієрархічною моделлю (RLS)

[TIP]
====
* [*] Введено підтримку для розподілення рівнів доступу користувачів за ієрархічною моделлю Row-level security (RLS) для компонента `geoserver`.

* [*] Користувач може мати доступ до даних з геосервера відповідно до свого рівня доступу в RLS.

* [*] Згідно з налаштуванням RLS із метаданих (регламенту), сервіс зчитує `jwtAttribute` із токена поточного користувача, і використовує результат для внесення додаткового параметра запита в геосервері.
====

== Публічний API на читання даних

[TIP]
====

Розробка публічних інтерфейсів ::

* [*] У цьому релізі ми розширили можливості нашого API. Тепер, окрім внутрішнього API, розробники можуть відкривати публічний API для доступу до даних. Користувачі, які не пройшли аутентифікацію, тепер можуть переглядати публічні дані реєстру.

* [*] Імплементовано можливість налаштовувати доступ до представлень та REST API реєстру для неавтентифікованих користувачів.

Автоматична публікація в Open API ::

* [*] Тепер налаштовані точки доступу автоматично публікуються в openapi-специфікації API-сервісу. Це робить інтеграцію та документацію API простішою.

Оптимізація завантаження ::

* [*] Впроваджено TTL-based кешування для `GET`-запитів, коли йде мова про посилання до API-документації. Це зменшує навантаження на наш сервіс Kong API Gateway та прискорює доступ до інформації.

Розширені можливості в адмін-консолі Control Plane ::

* [*] В адмін-консолі Control Plane додано новий інструмент для керування публічним доступом. Ви зможете налаштовувати, редагувати, блокувати або розблоковувати доступ до публічних даних реєстру.

Моніторинг API::

* [*] Імплементовано моніторинг показників виконання та кількості запитів до публічного API. Тепер ці метрики можна легко контролювати завдяки новому Grafana-dashboard.
====

== Рейт-ліміти на запити на читання даних публічного API

[TIP]
====

Розширені можливості в адмін-консолі Control Plane ::

* [*] Реалізовано можливість в адміністративній панелі Control Plane встановлювати рейт-ліміти для запитів на читання даних для публічних точок доступу API.

Моніторинг рейт-лімітів ::

* [*] Імплементовано моніторинг показників виконання та кількості запитів до публічного API. Тепер ці метрики можна легко контролювати завдяки новому Grafana-dashboard.
====

== Використання dependency track для збереження даних інвентаризації компонентів Платформи

[TIP]
====

Механізм для збереження даних інвентаризації ::

* [*] Реалізовано механізм збору даних інвентаризації залежностей у форматі BOM's (_наприклад, CycloneDX SBOM_).

* [*] Встановлено та налаштовано dependency track-додаток з необхідними модулями: автентифікація, моніторинг, резервні копії тощо.

* [*] Налаштовано Dependency Track Vulnerability Policies та інтегровано з зовнішніми сервісами для аналізу вразливостей.

* [*] Проведено аналіз Rest API dependency track та визначено механізм доставки репорту inventory management до кінцевого користувача.

Надано можливість отримувати Dependency Management Report ::

* [*] Перелік 3rd party залежностей, їх версій, ліцензій, аналіз по кожному компоненту системи.

* [*] Порівняння використовуваних версій з поточними версіями кожної залежності.

* [*] Визначення major чи minor оновлень.

* [*] Інформація про LTS дати для кожної залежності (потребує POC).

Це оновлення значно покращує процес управління інвентаризацією компонентів Платформи, забезпечуючи більшу прозорість та контроль над залежностями та вразливостями системи.
====

== Можливість вивантаження файлів з Edit Grid

[TIP]
====

* [*] Розширено можливості компонента моделювання форм -- *Edit Grid*. Надавачі та отримувачі послуг тепер можуть легко завантажувати та переглядати файли прямо з табличного компонента одним натисканням кнопки.
====

== Можливість завантажувати файли більші за 50 рядків

[TIP]
====

* [*] Додано можливість завантаження csv-файлу з кількістю записів, що перевищує 50. Так отримувач та надавач послуг можуть з легкістю вносити масивні зміни в рамках бізнес-процесу за одну транзакцію.

* [*] Введено новий компонент моделювання UI-форм -- *Data Import*. З його допомогою розробник регламенту може легко налаштовувати імпорт даних з csv-файлу прямо в бізнес-процес. Це значно спрощує та автоматизує роботу з даними.

* [*] Розроблено делегат *Async Data Load Csv Delegate* для відправлення повідомлень в Kafka про CSV batch load. Це поліпшує комунікацію та забезпечує швидке отримання статусів.

* [*] При завантаженні даних з csv-файлу в дата-фабрику, імплементовано попередню валідацію. Це дозволяє швидко виявляти та виправляти помилки.

* [*] Listener у bpms-сервісі тепер може отримувати повідомлення від Kafka та інформувати БП про завершення обробки csv-файлу, що робить процес більш прозорим.

* [*] Розроблено референтний приклад використання batch-load у бізнес-процесі. Він демонструє можливість завантаження понад 50 рядків.
====

== Можливість редагувати параметри реєстру залежно від його версії

[TIP]
====

* [*] Впроваджено можливість в інтерфейсі Control Plane редагувати параметри реєстру, враховуючи його конкретну версію. Це гарантує сумісність і стабільність роботи реєстрів незалежно від їхньої версії.

* [*] Реалізовано можливість підтримки декількох версій Control Plane, що збігаються із версіями реєстрів. Таким чином, кожна версія реєстру має свої специфічні налаштування, адаптовані під її особливості.

====

== Спрощений процес розробки регламенту через мастер-версію для форм і бізнес-процесів та захист від перезапису змін

[TIP]
====

* [*] Полегшено розробку регламенту реєстру. Тепер для внесення до UI-форм та моделей процесів не потрібно створювати окрему версію-кандидат. Розробник та моделювальник можуть вносити зміни прямо у мастер-версію.

* [*] Моделювальник регламенту тепер може прямо у мастер-версії створювати, копіювати, редагувати чи видаляти бізнес-процеси та UI-форми. Це сприяє швидшому застосуванню змін. Результат публікації змін можна перевірити у розділі "Огляд версії".

* [*] Реалізовано вбудований механізм, який гарантує, що зміни не будуть випадково перезаписані, забезпечуючи надійний захист від непередбачуваних ситуацій у процесі розробки.
====

== Інструкція для перегляду та перевірки внесених змін до моделі даних версії-кандидата в ізоляції без необхідності їх інтеграції в мастер-версію

[TIP]
====

* [*] Впроваджено стандартну процедуру для перевірки змін моделі даних перед їх інтеграцією в мастер-версію.

* [*] Розроблено детальну інструкцію, яка включає кроки для створення таблиць, налаштування критеріїв пошуку, первинного завантаження даних та перевірки у тимчасовій БД через pgAdmin. Цей посібник гарантує правильне та ефективне впровадження змін розробниками регламенту.

====

== Індикація наявності конфліктних змін на рівні складових версії-кандидата при перегляді

[TIP]
====

* [*] Розширено можливості Адміністративного порталу. Тепер розробники може з легкістю виявляти та переглядати конфліктні зміни відносно майстер-версії на сторінці Огляд версії.

* [*] Яскраві індикатори поруч із назвами файлів допомагають миттєво розібратися в статусі змін. При наведенні курсора, розробник отримує зрозумілу підказку.

* [*] При виявленні конфліктних змін у складовій регламенту, їх деталі автоматично розгортаються, що допомагає розробникам швидко орієнтуватися у ситуації.
====

== Частковий відкат окремих складових версії-кандидату до стану мастер-версії для спрощення розв'язання конфліктів

[TIP]
====
* [*] Реалізовано функціональність для розробників регламенту: тепер можна відкотити зміни в окремих файлах назад до стану майстер-версії. Такий інструмент дозволяє швидко та безболісно уникати конфліктів, не видаляючи або перестворюючи версію-кандидат при зіткненні з конфліктами.
====

== Можливість налаштовувати розмір пула в rest-api та кafka-api

[TIP]
====

* [*] Реалізовано можливість налаштовувати розмір пула з’єднань, специфічного для сервісів `rest-api` та `kafka-api`. Це дозволяє оптимізувати роботу сервісів з урахуванням потреб користувачів.

* [*] Додано параметр *Maximum pool size*, що дозволяє встановити максимальну кількість одночасних з'єднань із базою даних. Пул з'єднань гарантує, що використовується найбільше ефективна кількість з'єднань, забезпечуючи оптимальну продуктивність системи.
====

== Налаштування каналів зв'язку в Кабінеті користувача

[TIP]
====

Керування електронною поштою у Кабінеті користувача ::

* [*] Можливість перегляду налаштувань електронної пошти.

* [*] Внесення або видалення електронної адреси. Підтвердження даних за допомогою OTP-коду.

* [*] Опції активації та деактивації електронних адрес.

Перегляд inbox-повідомлень ::

* [*] Надавачам послуг надана можливість перегляду повідомлень у розділі _Повідомлення_ у Кабінеті. Ця функція активована автоматично.н

Моделювання шаблонів повідомлень ::

* [*] Налаштування шаблону повідомлень у різні Кабінети з урахуванням ролі користувача: CITIZEN/OFFICER.
====

== Відправка inbox- та email-нотифікацій посадовим особам

[TIP]
====

* [*] Реалізовано можливість отримувати та переглядати inbox-повідомлення у Кабінеті користувача надавачами послуг.

* [*] Реалізовано можливість отримувати та переглядати email-повідомлення у Кабінеті користувача надавачами послуг.

{empty}

Моделювання нотифікацій ::

* [*] Моделювання повідомлень доступне для каналів inbox та email.

* [*] Надсилання повідомлень у різні Кабінети з одного шаблону з урахуванням ролі користувача: `CITIZEN`/`OFFICER`.

* [*] Шаблон `channel-confirmation` модифіковано, враховуючи роль користувача.

* [*] Розроблено референтний бізнес-процес для відправлення повідомлень надавачам послуг.

{empty}

Розробка нового інтеграційного розширення ::

* [*] Імплементовано делегат *Send user notification v2*. Шаблон делегата інтегровано в Адміністративний портал для розширення можливостей бізнес-процесів.

====

== Інструкція. Автентифікація посадових осіб, єдина для групи реєстрів завдяки ручним налаштуванням

[TIP]
====

* [*] Впроваджено можливість адміністраторам реєстрів об'єднувати реєстри у групу, щоб забезпечити спрощену та єдину автентифікацію для надавачів послуг у рамках цієї групи.

* [*] Для зручності користувачів, розроблено детальну інструкцію, яка крок за кроком допоможе налаштувати цю функціональність.
====

== Навчальний курс для адміністраторів реєстрів

[TIP]
====

* [*] Представлено новий навчальний курс, призначений для адміністраторів реєстрів, який охоплює весь спектр обов'язків та функціональностей, необхідних для підвищення компетенцій у керуванні та адмініструванні реєстрів на Платформі.

* [*] Курс включає:

** [*] Вступ до ролі адміністратора реєстру.

** [*] Повний огляд обов'язків та вимог до адміністратора.

** [*] Докладні інструкції по розгортанню та редагуванню конфігурації реєстру.

** [*] Налаштування локального та робочого середовища.

** [*] Керування реєстрами через Control Plane, включаючи налаштування конфігурацій, ключів, сертифікатів, DNS-імен та інших компонентів.

** [*] Опис процесів резервного копіювання, відновлення та оновлення реєстру.

** [*] Практичні аспекти логування подій та моніторингу метрик Платформи та адміністрування бізнес-процесів.

** [*] Управління користувачами та ролями.
====

////