= Центральний сервіс управління секретами Платформи
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

Компонент, який забезпечує операції Auto unseal для підсистем управління секретами та шифруванням.

== Функції компоненти

* Забезпечення можливостей автоматичного розблокування (unseal) підсистеми керування секретами та шифруванням Платформи

== Технічний дизайн компоненти

image::architecture/platform-secret-management/platform-secret-management.drawio.svg[width=500,float="center",align="center"]

== Технологічний стек

При проектуванні та розробці були використані наступні технології:

* xref:arch:architecture/platform-technologies.adoc#vault[HashiCorp Vault]

== Складові компоненти

|===
|Назва компоненти|Представлення|Походження|Призначення

|_Центральний сервіс управління секретами Платформи_
|`platform-vault`
|3rd-party
|Забезпечення операції Auto unseal для підсистем управління секретами та шифруванням

|===

== Атрибути якості компоненти

=== _Security_

_Центральний сервіс управління секретами Платформи_ забезпечує операції автоматичного розпакування (_unseal_) підсистем управління секретами та шифруванням Платформи та Реєстрів.