= Центральний сервіс управління секретами Платформи

== Загальний опис

Забезпечення операції Auto unseal для підсистем управління секретами та шифруванням.

== Функції підсистеми

* Забезпечення можливостей автоматичного розблокування (unseal) підсистеми керування секретами та шифруванням Платформи

== Технічний дизайн підсистеми

image::architecture/platform-secret-management/platform-secret-management.drawio.svg[width=500,float="center",align="center"]

== Технологічний стек

При проектуванні та розробці були використані наступні технології:

* xref:arch:architecture/platform-technologies.adoc#vault[HashiCorp Vault]

== Складові підсистеми

|===
|Назва компоненти|Представлення|Походження|Призначення

|_Центральний сервіс управління секретами Платформи_
|`platform-vault`
|3rd-party
|Забезпечення операції Auto unseal для підсистем управління секретами та шифруванням

|===

== Атрибути якості підсистеми

=== _Security_

_Центральний сервіс управління секретами Платформи_ забезпечує операції автоматичного розпакування (_unseal_) підсистем управління секретами та шифруванням Платформи та Реєстрів.