:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
:toc-title: ЗМІСТ
:toc:
:toclevels: 5
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:


=  Імпорт користувачів (посадових осіб) до Keycloak

== Загальний опис

З метою реалізації можливості спрощеного створення великої кількості користувачів (посадових осіб) у Keycloak, впроваджено функціональність для завантаження переліку користувачів у систему через файл.

В Кабінет адміністратора регламентів додано нову сторінку "Управління користувачами", на якій реалізовано можливість завантажити файл з даними користувачів цього реєстру.

З метою мінімізації помилок при створенні нових користувачів запроваджено первинну перевірку валідаційних правил до файлу (розмір, формат, кодування).

Задля виконання вимог безпеки та надійності збереження даних, виконується шифрування файлу та його збереження в об'єктне сховище реєстру (Ceph).

Усі подальші кроки щодо запуск процесу  імпорту користувачів в Keycloak та парсинг і валідація даних користувачів з файлу, обробка даних у файлі та створення користувачів в Keycloak виконується автоматично без участі адміністратора реєстру.

Для моніторингу процесу виконання та його результату реалізовано функціональність в сервісі Kibana. Адміністратор реєстру може переглянути інформацію, що файл було опрацьовано, та підсумковий результат: кількість оброблених записів, кількість успішних, кількість помилкових, а також детальну інформацію за кожним помилковим записом.

Також на основі розробленого в Redash "Журналу подій системи" окремо створено новий -- "Журнал управління користувачами". Адміністратор реєстру в "Журналі управління користувачів" може бачити дії, пов'язані зі створенням користувачів в Keycloak, в т.ч. інформацію щодо імпорту через файл.

== Інструкція імпорту користувачів (посадових осіб) до Keycloak

=== Налаштування атрибутів в Keycloak

Попередньо необхідно в Keycloak разово виконати наступні дії:

. Перейдіть у відповідний `-admin реалм` і виберіть розділ `Users`.
. Оберіть користувача адміністратора, що імпортує файл, і перейдіть у розділ `Attributes`.
. Створіть три ключі для атрибутів:

* `fullName` -- ПІБ;
* `drfo` -- особистий реєстраційний номер облікової картки платника податків (РНОКПП);
* `edrpou` -- унікальний ідентифікаційний номер юридичної особи в Єдиному державному реєстрі підприємств та організацій України (ЄДРПОУ).

. Натисніть `Save`.

+
image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-00.png[]

[IMPORTANT]
====
Якщо не виконати вищезазначених дій буде виникати помилка системи на етапі відправки файлу: ::
В Keycloak не створено необхідні атрибути. Будь ласка, зверніться до адміністратора.
+
image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-00-0.png[]
====

[CAUTION]
====
Налаштування атрибутів в Keycloak виконується один раз. При наступних процедурах імпорту користувачів виконувати її немає потреби.
====

=== Імпорт користувачів через Кабінет адміністратора регламенту

. Перейдіть до Кабінету адміністратора регламентів.
+
image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-01.png[]

. Оберіть розділ `Управління користувачами`.
+
image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-02.png[]

. Натисніть кнопку `Додати користувачів`.
+
image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-03.png[]

. Завантажте шаблон файлу link:{attachmentsdir}/import-users(officer)/users_keyсloak.csv[`Users Keycloak.csv`] для заповнення даними користувачів.
+
. Ознайомтесь з xref:registry-develop:registry-admin/import-users-officer-description-file-csv.adoc[поясненнями до заповнення таблиці «Users KeyCloak»].
+
[IMPORTANT]
====
Обов'язково зверніть увагу на особливості заповнення параметрів шалону файлу, щоб уникнути помилок.

Якщо під час імпорту користувачів з файлу буде виявлена хоча б одна помилка, то процес імпорту буде перервано і жоден з користувачів не буде доданий до системи Keycloak. xref:#validation-rules[Див. схему нижче].
====
+
image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-04.png[]

. Заповніть файл даними користувачів, яким потрібно надати доступ до реєстру.
+
[WARNING]
====
Вимоги до файлу:

* максимальний розмір файлу -- *`30 МБ`*;
* формат файлу -- *`CSV`*;
* кодування файлу -- *`UTF-8`*.

Якщо файл не відповідає одному з вищеописаних критеріїв, користувач отримає відповідне повідомлення:

* kbd:[Файл занадто великого розміру.]
* kbd:[Невідповідний формат файлу.]
* kbd:[Файл невідповідного кодування.]

Це означатиме, що завантаження файлу не відбулося. xref:#validation-rules[Див. схему нижче].
====
+
[NOTE]
====
Валідаційні правила для даних у файлі:

Атрибут `drfo`: ::
обов'язковий до заповнення, є унікальним у зв'язці з атрибутами `edrpou` та `fullName`;
Атрибут `edrpou`: :: обов'язковий до заповнення, є унікальним у зв'язці з атрибутами `drfo` та `fullName`, для введення доступні лише цифри;
Атрибут `fullName`: ::
обов'язковий до заповнення, є унікальним у зв'язці з атрибутами `drfo` та `edrpou`;
Атрибут `Roles`: ::
обов'язковий до заповнення, може містити декілька ролей (системні та регламентні ролі, при наявності), які вказані через кому. Вказані ролі повинні бути вже створені в Officer Realm у відповідному реєстрі у Keycloak.
====

. Завантажте файл перетягнувши його у відповідне поле `Завантажити перелік посадових осіб` або обравши його у відповідній директорії.
+
image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-05.png[]

. Натисніть кнопку `Почати імпорт`.
+
image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-06.png[]

. На наступному кроці буде відображено, що файл прийнято в обробку. Зачекайте декілька хвилин до повного завантаження користувачів реєстру.
Також у повідомленні зазначене посилання на сервіс Kibana, де можна переглянути результат опрацювання файлу: кількість оброблених записів, кількість успішних, кількість помилкових.
+
image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-07.png[]

. Далі перевірте результат виконання процесу імпорту користувачів.

== Перегляд результату виконання процесу в сервісі Kibana

Модуль валідує весь файл і пише всі знайдені проблеми в сховище технічних логів Kibana. У логах фіксується інформація про кожен запис, який був пропущений при створенні, з фіксацією причини пропуску, а успішно відпрацьовані порядково не фіксуються (показується лише загальна кількість успішних). Також присвоюється унікальний ідентифікатор користувача в Keycloak (Username), який дублюється.

[CAUTION]
====
Під час використання сервісу Kibana необхідно створити `index pattern`. Детальніше ознайомитися з процедурою створення індексу та роботою з сервісом ви можете за посиланням:

* xref:registry-develop:bp-modeling/bp/kibana.adoc[]
====

[#validation-rules]
=== Загальні валідаційні правила для перевірки даних користувачів з файлу.

Загальну схему валідаційних правил представлено нижче.

image:registry-develop:registry-admin/import-users(officer)/import-users(officer).jpg[]

У разі порушення валідаційного правила запису даних у файлі буде показана відповідна помилка:

* _обов'язкове поле пусте `або` складається тільки з пробілів `або` має кілька значень через кому замість одного_ -- помилка про відсутність обов'язкового атрибута;
* _поле `edrpou` містить недопустимі символи (має складатися лише з цифр)_-- помилка про присутність неприпустимих символів;
* _вказана роль відсутня у переліку наявних ролей Officer Realm відповідного реєстру у Keycloak_ -- помилка про відсутність вказаної ролі;
* _структура файлу не відповідає заданій_  -- помилка про невідповідність файлу закладеній структурі.

В такому випадку процес імпорту користувачів не відбувається.

[CAUTION]
====
Якщо імпорт користувачів у Keycloak відбувся з порушенням валідаційних правил, потрібно повторно з самого початку повторити процедуру імпорту користувачів з файлу, попередньо виконавши потрібні корегування.
====

{empty} +

Виконання часткового імпорту користувачів з помилкою можливе в наступних випадках:

. користувач із таким username і такими атрибутами (drfo, edrpou, fullName) вже є в Keycloak;
. користувач із таким username, але з іншими атрибутами вже є в Keycloak;
. користувач із такими атрибутами, але з іншим username вже є в Keycloak (тоді в логах напишеться, який реальний username у нього в Keycloak);
. користувач із такими атрибутами вже зустрівся в CSV-файлі раніше (дублювання записів).
. в процесі імпорту виникла помилка в Keycloak

В такому випадку процес імпорту користувачів відбувається частково, записи користувачів з помилками фіксуються в логах Kibana як `Failed to import` та `Skipped` і вони не додаються до системи Keycloak, а усі інші успішні записи користувачів додаються до системи Keycloak.

Алгоритм запису логів при імпорті користувачів з помилкою:

* Якщо один із запитів в групі з N записів повертає помилку, запис користувачів саме з цієї групи починається порядково. Користувач, на якому сталася помилка, пропускається;
* У логах фіксується інформація про всі записи, пропущені при створенні, з фіксацією причини пропуску (позначені як `Skipped` або `Failed  to import`).

[CAUTION]
====
Якщо імпорт користувачів у Keycloak відбувся з помилками (часткове створення користувачів), потрібно наново завантажити файл з користувачами, яких не вдалося створити, виконавши потрібні корегування.
====

=== Результату виконання процесу імпорту з помилкою

Першочергово необхідно в логах знайти відповідний запис з загальним результатом опрацювання імпорту.

image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-08.png[]

* `Total users in file` -- відображає загальну кількість користувачів, що було додано через файл;
* `Successfully imported` -- кількість успішно доданих користувачів;
* `Skipped` - кількість пропущених користувачів;
* `Failed  to import` -- кількість користувачів, що не вдалося додати через помилку з сервісом Keycloak.

За кожним користувачем, що не вдалося додати до сервісу (пропущені) буде показано окремий запис у лолах з інформацією про валідаційну помилку.

image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-09.png[]

Якщо імпорт користувачів у Keycloak відбувся з помилками (часткове створення користувачів), потрібно наново підвантажити файл з користувачами, яких не вдалося створити (виконавши потрібні корегування).

=== Успішний результат виконання процесу імпорту користувачів
У разі успішного проходження валідаційних правил виконується процес імпорту всіх користувачів з файлу у Keycloak. `Skipped` та `Failed to import` вказуються с нулями.
`Total users in file` відповідає кількості `Successfully imported`.

image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-10.png[]

Створення користувачів у Keycloak відбувається групами (окремими запитами) по N записів (значення N задається в налаштуваннях процесу).

За результатом успішного проведення імпорту користувачів у Keycloak створюються облікові записи користувачів з відповідними атрибутами та ролями.

image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-11.png[]

== Перегляд логів аудиту в "Журналі управління користувачами" системи Redash

Адміністратор безпеки (з відповідним правом доступу) має можливість переглянути в Redash "Журнал управління користувачами", наприклад, з метою проведення аудиту надання доступу користувачам.

[NOTE]
====
Для надання прав доступу до системи Redash у користувача має бути роль `redash-admin`.

Посилання до системи Redash можна знайти в консолі Openshift → _Networking_ → _Routes_, та обравши необхідний проєкт знайти реалм `redash-viewer`.

image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-14.png[]
====

У журналі відображено всі записи, які відповідають наступним параметрам: applicationName="Keycloak", type="SYSTEM_EVENT".

Кожен користувач, якого було створено через імпорт файлом, відображається окремим рядком з зазначеним набором додаткових параметрів.

image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-12.png[]

Звіт містить наступні параметри::
|===
|_Назва в Redash_|_Назва параметру_|_Опис параметру_
|Ідентифікатор запиту|`requestId`|Ідентифікатор запиту з MDC
|Назва події в БД|`name`|"USER_CREATE"
|Назва додатку/поди	|`sourceApplication`	|Назва пайплайну для імпорту користувачів (pod_name)
|Дата та час операції	|`timestamp`|Мітка часу
|ПІБ адміністратора	|`userName`|ПІБ користувача який запустив процес імпорту
|Ідентифікатор адміністратора	|`userKeycloakId`|Keycloak ідентифікатор користувача який запустив процес імпорту
|ДРФО адміністратора	|`userDrfo`|ДРФО код користувача який запустив процес імпорту
|ID створеного користувача	|`userId`|Keycloak  ідентифікатор створеного користувача
|Username створеного користувача	|`username`|username створеного користувача
|Користувач активний	|`enabled`|true/false
|Ідентифікатор реалму	|`realmId`|Keycloak  ідентифікатор реалму в якому був створений користувач
|Ім'я реалму	|`realmName`|Ім'я  реалму в якому був створений користувач
|Ім'я клієнта в Keycloak	|`clientId`|Значення "Client ID" атрибуту реалма від імені якого був створений користувач
|Ідентифікатор клієнта в Keycloak	|`keycloakClientId`	|Keycloak-ідентифікатор клієнта від імені якого був створений користувач
|Ролі створеного користувача	|`roles`|Ролі створеного користувача
|Ідентифікатор CSV файлу	|`sourceFileId`|Ідентифікатор CSV файлу у Ceph бакеті
|Оригінальне ім'я CSV файлу	|`sourceFileName`|Оригінальне ім'я CSV файлу, з якого проводився імпорт користувачів
|Контрольна сума CSV файлу 	|`sourceFileSHA256Checksum`	|Чек сума завантаженого користувачем CSV файлу (незашифрованого)
|===

Функціональністю сервісу Redash передбачено можливість фільтрування, сортування параметрів та експорту сформованої вибірки.

image:registry-develop:registry-admin/import-users(officer)/import-users(officer)-13.png[]


