= Підсистема управління геоданими

[NOTE]
--
Сторінка технічної документації у процесі розробки.
--

== Загальний опис

Підсистема, призначенням якої є пошук та представлення географічно привʼязаних обʼєктів реєстру у стандартизованих форматах.

== Функції підсистеми

* Пошук та представлення заздалегідь підготовлених структур БД у якості _геошарів_.
* Пошук та представлення географічних обʼєктів (точка, лінія та полігон) у стандартизованому форматі.

== Технічний дизайн підсистеми

На даній діаграмі зображено компоненти, які входять в _Підсистему управління геоданими_ та їх взаємодію з іншими підсистемами в рамках реалізації функціональних сценаріїв.

image::architecture/registry/operational/geo/gis-overview.svg[float="center",align="center",width=600]

_Підсистема управління геоданими_ побудована на базі відкритого програмного забезпечення https://github.com/geoserver/geoserver[_GeoServer_] та надає _API_ для пошуку географічно привʼязаних обʼєктів і повʼязаних з ними атрибутів в _Операційний БД реєстру_ та представленні їх у стандартизованому форматі для подальшої візуалізації.

[TIP]
--
Детальніше з підходом до обробки геолокаційних запитів можна ознайомитись у розділі xref:architecture/registry/operational/relational-data-storage/rdbms-gis.adoc[]
--

Контроль доступу до даних реєстру (_RLS_) реалізовано на рівні _Istio Envoy_ за допомогою налаштованого на рівні регламенту переліку правил для _EnvoyFilter_.

== Складові підсистеми

|===
|Назва компоненти|Представлення в реєстрі|Походження|Репозиторій|Призначення

|_Сервіс гео-даних_
|`geo-server`
|3rd-party
|https://github.com/geoserver/geoserver
|Пошук об'єктів реєстру за атрибутами та представлення гео-даних у стандартизованому форматі

|_Фільтр прав доступу до даних_
|`geoserver-rls`
|origin
|_генерується_
|Застосування RLS на читання даних згідно прав доступу користувача
|===

== Технологічний стек

* xref:arch:architecture/platform-technologies.adoc#geoserver[GeoServer]
* xref:arch:architecture/platform-technologies.adoc#postgis[PostGIS]
* xref:arch:architecture/platform-technologies.adoc#leaflet[Leaflet]

== Атрибути якості підсистеми

=== Interoperability

Сумісність підсистеми з іншими геопросторовими системами забезпечується завдяки використанню галузевих стандартів для представлення даних:

* _OGC_ (_Open Geospatial Consortium_)
* _WMS_ (_Web Map Service_)
* _WFS_ (_Web Feature Service_)
* _WCS_ (_Web Coverage Service_)

=== Scalability

Компоненти підсистеми не зберігають стану, що забезпечує можливість горизонтального масштабування шляхом додавання додаткових екземплярів для обробки зростаючих робочих навантажень.

[TIP]
--
Детальніше з масштабуванням підсистем можна ознайомитись у розділі xref:architecture/container-platform/container-platform.adoc[]
--