= Моніторинг систем Платформи
:sectlinks:
:sectanchors:

_Моніторинг_ -- це ключовий елемент ефективної роботи будь-якої IT-платформи. Для забезпечення повного контролю за роботою наших систем та вчасного виявлення й усунення можливих проблем ми використовуємо потужний інструмент моніторингу -- *Grafana*.

У Grafana ми розробили різноманітні дашборди, що дозволяють налаштовувати та відстежувати ключові показники продуктивності, зокрема:

* Роботу різних компонентів Платформи (як-от Camunda або Strimzi Kafka);
* Стан баз даних та файлової системи (наприклад, PostgreSQL чи Ceph cluster);
* Метрику і статистику запитів у Public API Kong;
* Аналітичні дані через Redash;
* Стан кеш-пам'яті за допомогою Redis;
* Метрики зі Spring Boot, Prometheus та інші.

Ці дашборди надають глибокий аналіз роботи нашої Платформи та розгорнутих на ній реєстрів, що допомагає нам забезпечувати стабільність, продуктивність та відзначати можливі відхилення або проблеми ще до того, як вони стануть критичними.

TIP: Повний перелік доступних дашбордів для моніторингу можна знайти на сторінці xref:arch:architecture/platform/operational/monitoring/overview.adoc[].

== Огляд секції

* xref:registry-develop:registry-admin/grafana-monitoring/grafana-alerting-notifications.adoc[]
* xref:registry-develop:registry-admin/grafana-monitoring/grafana-camunda-metrics.adoc[]
* xref:registry-develop:registry-admin/grafana-monitoring/public-api-kong-metrics.adoc[]