= Аудит бізнес-процесів

== BP-01. X-Access-Token в сервісних задач
Використовувати X-Access-Token в сервісних задач, який був отриманий в поточній транзакції бізнес-процесу

=== Критичність: висока

=== Опис
При використанні _juel_ функцій для отримання користувацького авторизаційного токену (наприклад,
_completer('ActivityId').accessToken_, _initiator().accessToken_) треба впевнитись, що місце використання функції та
відповідна актівіті (користувацька задача, або початкова подія) знаходяться в одній транзакції бізнес-процесу. +

=== Вплив
Термін дії користувацького авторизаційного токен може закінчитися, поки бізнес-процес дійде до точки використання.
Може бути не виявлено на етапі розробки та тестування через відсутність відповідних умов (задача, яку не беруть у
виконання більше 5 хв, довга транзакція, тимчасова недоступність сервісу тощо) +

=== Рекомендації
Використовувати токен користувача найближчої до точки використання задачі або токен системного користувача
(_system_user().accessToken_)

== BP-02. Транзакції в циклах
При наявності циклів в бізнес-процесі, розпочинати кожну ітерацію в окремій транзакції (async after/before)

=== Критичність:

=== Опис

=== Вплив

=== Рекомендації

== BP-03. Retry policy для асинхронних задач
Налаштовувати retry policy для асинхронних задач (async after/before)

=== Критичність:

=== Опис

=== Вплив

=== Рекомендації

== BP-04. Пагінація для критеріїв пошуку
Задавати параметри пагінації (offset/limit) при викликах критеріїв пошуку на вибірку даних

=== Критичність:

=== Опис

=== Вплив

=== Рекомендації