= Аудит бізнес-процесів

== BP-01. X-Access-Token в сервісних задач
Використовувати X-Access-Token в сервісних задач, який був отриманий в поточній транзакції бізнес-процесу

IMPORTANT: Критичність: висока

=== Опис
При використанні _juel_ функцій для отримання користувацького авторизаційного токену (наприклад,
_completer('ActivityId').accessToken_, _initiator().accessToken_) треба впевнитись, що місце використання функції та
відповідна актівіті (користувацька задача, або початкова подія) знаходяться в одній транзакції бізнес-процесу. +

=== Вплив
Термін дії користувацького авторизаційного токен може закінчитися, поки бізнес-процес дійде до точки використання.
Може бути не виявлено на етапі розробки та тестування через відсутність відповідних умов (задача, яку не беруть у
виконання більше 5 хв, довга транзакція, тимчасова недоступність сервісу тощо) +

=== Рекомендації
Використовувати токен користувача найближчої до точки використання задачі або токен системного користувача
(_system_user().accessToken_)

== BP-02. Транзакції в циклах
При наявності циклів в бізнес-процесі, розпочинати кожну ітерацію в окремій транзакції
// TODO: Перевірити transactional boundaries для multi-instance актівіті і окремо паралельне виконання
// TODO: Подивитись дефлотні ретрай полісі для transactional boundaries

IMPORTANT: Критичність: висока

=== Опис
При моделюванні циклів в бізнес-процесах необхідно застосовувати асинхронне виконання для кожної ітерації для надійності виконання та реагуванні на можливі помилки.

=== Вплив
При наявності циклів, які мають велику кількість ітерацій _Camunda Engine_ тримає транзакцію на базі даних протягом всього
часу його виконання, що може призвести до вичерпання пулу з'єднань до бази даних і блокування інших бізнес-процесів.
Окрім цього, при виникненні помилки, політики повтору (retry policy) будуть виконуватися від початку транзакції. Тобто,
при виникненні помилки на 100-ій ітерації, буде спроба виконати першу ітерацію, а потім будуть виконані всі ітерації
від початку.

=== Рекомендації
Проставляти _camunda:asyncBefore_ атрибут після першої актівіті у циклі (це може бути сервісна задача, або початкова
подія у випадку під-процесу) або _camunda:asyncAfter_ останньої актівіті у циклі. Потрібно також врахувати та виключити
використання несталих (transient) змінних, які були отримані у бізнес-процесі до першої операції у циклу.

NOTE: Детальніше про транзакції у Camunda можна ознайомитись https://docs.camunda.org/manual/7.19/user-guide/process-engine/transactions-in-processes/[за посиланням]

== BP-03. Retry policy для асинхронних задач
Налаштовувати retry policy для асинхронних задач (async after/before)

IMPORTANT: Критичність:

=== Опис

=== Вплив

=== Рекомендації

== BP-04. Пагінація для критеріїв пошуку
Задавати параметри пагінації (offset/limit) при викликах критеріїв пошуку на вибірку даних

IMPORTANT: Критичність:

=== Опис

=== Вплив

=== Рекомендації

== BP-05. Довгі транзакції бізнес-процесів

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-06. Складна логіка в скриптових задачах

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-07. Робота з несталими (transient) змінними

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-08. Декілька викликів фабрики даних в одній транзакції
// TODO: Перевірити чи можна уникнути цього та використовувати комлекс сутність
IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-09. Ініціалізація та використання змінних

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-10. Ідентифікатори елементів бізнес-процесів

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-11. Моделювання зліва направо

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-12. Мультіінстанс задачі та кол актівіті

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-13. Логування в скриптових задачах
// TODO: Перевірити відповідну juelку
IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-14. Авторизаційні токени для викликів зовнішніх сервісів
// TODO: Перевірити можливості по роботі з токенами через секрети
IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації


// TODO: Перевірити Роботу з компенсаціями в документації, демо реєстру та в РПЗМ

