= Аудит бізнес-процесів

== BP-01. X-Access-Token в сервісних задач
Використовувати X-Access-Token в сервісних задач, який був отриманий в поточній транзакції бізнес-процесу

IMPORTANT: Критичність: висока

=== Опис
При використанні _juel_ функцій для отримання користувацького авторизаційного токену (наприклад,
_completer('ActivityId').accessToken_, _initiator().accessToken_) треба впевнитись, що місце використання функції та
відповідна актівіті (користувацька задача, або початкова подія) знаходяться в одній транзакції бізнес-процесу. +

=== Вплив
Термін дії користувацького авторизаційного токен може закінчитися, поки бізнес-процес дійде до точки використання.
Може бути не виявлено на етапі розробки та тестування через відсутність відповідних умов (задача, яку не беруть у
виконання більше 5 хв, довга транзакція, тимчасова недоступність сервісу тощо) +

=== Рекомендації
Використовувати токен користувача найближчої до точки використання задачі або токен системного користувача
(_system_user().accessToken_)

== BP-02. Транзакції в циклах
При наявності циклів в бізнес-процесі, розпочинати кожну ітерацію в окремій транзакції (async after/before)

IMPORTANT: Критичність:

=== Опис

=== Вплив

=== Рекомендації

== BP-03. Retry policy для асинхронних задач
Налаштовувати retry policy для асинхронних задач (async after/before)

IMPORTANT: Критичність:

=== Опис

=== Вплив

=== Рекомендації

== BP-04. Пагінація для критеріїв пошуку
Задавати параметри пагінації (offset/limit) при викликах критеріїв пошуку на вибірку даних

IMPORTANT: Критичність:

=== Опис

=== Вплив

=== Рекомендації

== BP-05. Довгі транзакції бізнес-процесів

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-06. Складна логіка в скриптових задачах

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-07. Робота з несталими (transient) змінними

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-08. Декілька викликів фабрики даних в одній транзакції
// TODO: Перевірити чи можна уникнути цього та використовувати комлекс сутність
IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-09. Ініціалізація та використання змінних

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-10. Ідентифікатори елементів бізнес-процесів

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-11. Моделювання зліва направо

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-12. Мультіінстанс задачі та кол актівіті

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-13. Логування в скриптових задачах
// TODO: Перевірити відповідну juelку
IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-14. Авторизаційні токени для викликів зовнішніх сервісів
// TODO: Перевірити можливості по роботі з токенами через секрети
IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації


// TODO: Перевірити Роботу з компенсаціями в документації, демо реєстру та в РПЗМ

