= Аудит бізнес-процесів

== BP-01. X-Access-Token в сервісних задач
Використовувати X-Access-Token в сервісних задач, який був отриманий в поточній транзакції бізнес-процесу

IMPORTANT: Критичність: висока

=== Опис
При використанні _juel_ функцій для отримання користувацького авторизаційного токену (наприклад,
_completer('ActivityId').accessToken_, _initiator().accessToken_) треба впевнитись, що місце використання функції та
відповідна актівіті (користувацька задача, або початкова подія) знаходяться в одній транзакції бізнес-процесу. +

=== Вплив
Термін дії користувацького авторизаційного токен може закінчитися, поки бізнес-процес дійде до точки використання.
Може бути не виявлено на етапі розробки та тестування через відсутність відповідних умов (задача, яку не беруть у
виконання більше 5 хв, довга транзакція, тимчасова недоступність сервісу тощо) +

=== Рекомендації
Використовувати токен користувача найближчої до точки використання задачі або токен системного користувача
(_system_user().accessToken_)

== BP-02. Транзакції в циклах
При наявності циклів в бізнес-процесі, розпочинати кожну ітерацію в окремій транзакції
// TODO: Перевірити transactional boundaries для multi-instance актівіті і окремо паралельне виконання
// TODO: Подивитись дефлотні ретрай полісі для transactional boundaries

IMPORTANT: Критичність: висока

=== Опис
При моделюванні циклів в бізнес-процесах необхідно застосовувати асинхронне виконання для кожної ітерації для надійності виконання та реагуванні на можливі помилки.

=== Вплив
При наявності циклів, які мають велику кількість ітерацій _Camunda Engine_ тримає транзакцію на базі даних протягом всього
часу його виконання, що може призвести до вичерпання пулу з'єднань до бази даних і блокування інших бізнес-процесів.
Окрім цього, при виникненні помилки, політики повтору (retry policy) будуть виконуватися від початку транзакції. Тобто,
при виникненні помилки на 100-ій ітерації, буде спроба виконати першу ітерацію, а потім будуть виконані всі ітерації
від початку.

=== Рекомендації
Проставляти _camunda:asyncBefore_ атрибут після першої актівіті у циклі (це може бути сервісна задача, або початкова
подія у випадку під-процесу) або _camunda:asyncAfter_ останньої актівіті у циклі. Потрібно також врахувати та виключити
використання несталих (transient) змінних, які були отримані у бізнес-процесі до першої операції у циклу.

NOTE: Детальніше про транзакції у Camunda можна ознайомитись https://docs.camunda.org/manual/7.19/user-guide/process-engine/transactions-in-processes/[за посиланням]

== BP-03. Стратегія повторних спроб (retry time cycle)
Перевизначати стратегію повторних спроб (retry time cycle) для асинхронних задач.

IMPORTANT: Критичність: висока

=== Опис
За замовчуванням при виникненні помилки при виконанні асинхронних задач виконавець робіт (job executor) буде пробувати
виконати задачу ще 3 рази без пауз між ними. У більшості випадків причиною помилки може бути виклик іншого сервісу як
всередині системи, так і за її межами, який міг бути тимчасово недоступний. В такому випадку негайний повтор не призведе
до якихось змін і врешті решт задачу буде помічена невдалою (failed) і може бути перезапущена тільки  вручну
_Адміністратором реєстру_ у _Сервісі адміністрування бізнес-процесами_

=== Вплив
При виникненні помилки при виконанні асинхронних задач в більшості випадків повторні спроби не призводять до успішного
завершення задачі, а лише ще більше навантажують сервіс з яким могла виникнути проблема.

=== Рекомендації
Для асинхронних задач встановити атрибут циклу повторних спроб _camunda:failedJobRetryTimeCycle_ з певною затримкою,
наприклад, 5 спроб кожні 5 хвилин _R5/PT5M_. В процесі експлуатації значення може бути адаптоване відповідно до поведінки
бізнес-процесу.

NOTE: Детальніше про повторні спроби у Camunda можна ознайомитись https://docs.camunda.org/manual/7.19/user-guide/process-engine/the-job-executor/#retry-time-cycle-configuration[за посиланням]

//TODO:Розглянути перевизначення конфігурації на рівні платформи

== BP-04. Ліміт для критеріїв пошуку
При використанні сервісної задачі з пошуку сутностей в фабриці даних, треба явно задавати параметр по максимальній
кількості даних (limit), які можуть бути отримані.

IMPORTANT: Критичність: середня

=== Опис
При використанні задач з пошуку даних в реєстрі, параметр з максимальною кількістю даних (limit) не є обов'язковим, і
часто не вказується при роботі з таблицями, які на етапі розробки містять невелику кількість даних. Однак, при використанні
в промисловому середовищі такі запити потенційно можуть нести набагато більше даних, що може призвести до деградації роботи
системи.

=== Вплив
Велика кількість даних, отримана при використанні сервісної задачі з відсутнім параметром ліміту, може призвести до
наступних потенційних проблем:

* Додаткове навантаження на сервіси системи:
** Реляційна база даних
** Сервіс синхронного управління даними реєстру
** Сервіс виконання бізнес-процесів

* Збільшений час виконання бізнес-процесу
* Збільшений час виконання окремої транзакції бізнес-процесу

=== Рекомендації
Завжди вказувати параметр ліміту (limit) для сервісних задач з пошуку даних. Можливі сценарії використання:

==== Пошук обмеженої кількості елементів
Якщо за бізнес-логікою відомо що після виконання запиту обробляється тільки певна кількість даних (наприклад, перший
елемент зі списку), то треба явно обмежити запит цією кількістю.

==== Обробка всіх даних за результатами пошуку
Якщо бізнес-процес повинен обробити всі дані, то треба розглянути поетапну обробку елементів (можливо, пачками)
в циклі та пагінацією при використанні сервісних задач з пошуку даних.

==== Інтеграція з зовнішніми системами
При необхідності запитів зовнішніми системами для вибірки даних з реєстру в першу чергу треба розглянути можливість
використання напряму АПІ для читання даних без залучення бізнес-процесу (але все одно з обов'язковими параметрами пагінації).
Якщо ж відповідна інтеграція потребує певної логіки бізнес-процесу, то треба додати відповідні параметри пагінації як
вхідні атрибути бізнес-процесу та імплементувати логіку пагінації на системі, що інтегрується.

== BP-05. Довгі транзакції бізнес-процесів

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-06. Складна логіка в скриптових задачах

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-07. Робота з несталими (transient) змінними

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-08. Декілька викликів фабрики даних в одній транзакції
// TODO: Перевірити чи можна уникнути цього та використовувати комлекс сутність
IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-09. Ініціалізація та використання змінних

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-10. Ідентифікатори елементів бізнес-процесів

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-11. Моделювання зліва направо

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-12. Мультіінстанс задачі та кол актівіті

IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-13. Логування в скриптових задачах
// TODO: Перевірити відповідну juelку
IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації

== BP-14. Авторизаційні токени для викликів зовнішніх сервісів
// TODO: Перевірити можливості по роботі з токенами через секрети
IMPORTANT: Критичність

=== Опис

=== Вплив

=== Рекомендації


// TODO: Перевірити Роботу з компенсаціями в документації, демо реєстру та в РПЗМ

