= Аудит моделі даних

|===
|Назва | Критичність

|<<_dm_01>> |Висока
|<<_dm_02>> |Середня
|<<_dm_03>> |Низька
|<<_dm_04>> |Висока
|<<_dm_05>> |Висока
|<<_dm_06>> |Висока
|<<_dm_07>> |Середня
|<<_dm_08>> |Висока
|<<_dm_09>> |Висока

|===

[#_dm_01]
== DM-01. Індекси для критеріїв пошуку
IMPORTANT: Критичність: висока

.Опис
placeholder

.Вплив
placeholder

.Рекомендації
placeholder

[#_dm_02]
== DM-02. Зайві чендж сети в рамках 1 релізу
IMPORTANT: Критичність: середня

.Опис
placeholder

.Вплив
placeholder

.Рекомендації
placeholder

[#_dm_03]
== DM-03. Іменування ідентифікаторів чендж сетів
IMPORTANT: Критичність: низька

.Опис
placeholder

.Вплив
placeholder

.Рекомендації
placeholder

[#_dm_04]
== DM-04. Перелік колонок в критеріях пошуку
IMPORTANT: Критичність: низька

.Опис
Додавати в критерії пошуку тільки ті колонки, що використовуються в бізнес-процесі, формах чи зовнішньому АПІ.
Якщо колонка не використовується в пошуку, то вона не повинна бути включена в критерії пошуку.

.Вплив
* Наявність файлів в критеріях пошуку і їх виклик з бізнес-процесу призводить до перекладання файлів між постійним та
тимчасовим сховищем, що впливає на час виконання операції та призводить до додаткового навантаження на систему

.Рекомендації
* Не робити 1 критерій пошуку для всіх потреб (аналогія антипатерну _"God Object"). Краще зробити декілька критеріїв
пошуку, що будуть задовільняти конкретні потреби.

[#_dm_05]
== DM-05. Ліміти на критерії пошуку
IMPORTANT: Критичність: висока

.Опис
Завжди вказувати ліміт при моделюванні критеріїв пошуку

.Вплив
placeholder

.Рекомендації
placeholder

[#_dm_06]
== DM-06. Нормалізація схеми бази даних
IMPORTANT: Критичність: висока

.Опис
Моделювати схему бази даних в нормальній формі. При цьому використовувати 3-ю нормальну форму (3NF) як базову. Розглядати
де-нормалізацію як виняток, який потребує обґрунтування.

.Вплив
placeholder

.Рекомендації
placeholder

[#_dm_07]
== DM-07. Часткове оновлення
IMPORTANT: Критичність: середня

.Опис
При необхідності оновлення сутності в бізнес-процесі надавати перевагу частковому оновленню (partial update) замість
стандартного повного оновлення сутності.

.Вплив
* Спрощує логіку бізнес-процесу
* Менше викликів до бази даних. Немає потреби додатково вичитувати сутність для подальшого її оновлення

NOTE: Треба пам'ятати, що при використанні часткового оновлення, всі поля, які в ньому присутні повинні бути передані.
Інакше, вони будуть встановлені в NULL.

.Рекомендації
placeholder

[#_dm_08]
== DM-08. SQL тег Liquibase
IMPORTANT: Критичність: висока

.Опис
Використовувати _Liquibase sql_ тільки з обґрунтованої причини. В усіх інших випадках використовувати теги з розширення
для маніпуляцій зі структурою схеми бази даних.

.Вплив
placeholder

.Рекомендації
placeholder

[#_dm_09]
== DM-09. Пагінація на критеріях пошуку
IMPORTANT: Критичність: висока

.Опис
Використовувати можливості пагінації при моделюванні критеріїв пошуку

.Вплив
* Зменшує потенційну вибірку даних і навантаження на систему

.Рекомендації
placeholder

