= Аудит шаблонів витягів

|===
|Назва | Критичність

|<<_ex_01>> |Середня
|<<_ex_02>> |Середня

|===

[#_ex_01]
== EX-01. Набір даних для витягів
IMPORTANT: Критичність: середня

.Опис
В процесі тестування перевіряти витяги з різним набором даних і обсягом наближеним до промислового. В процесі розробки
можуть бути непокриті сценарії з перенесенням елементів шаблону на нову сторінку в залежності від обсягу даних.
Потенційно помилковими в цьому випадку можуть бути таблиці з правильним рендерінгом заголовків та рядків.

[#_ex_02]
== EX-02. Обов'язкові параметри шаблонів витягів
IMPORTANT: Критичність: середня

.Опис
Враховувати обов'язковість за замовчуванням всіх вхідних параметрів для шаблонів витягів. Якщо в генерацію витягу з
бізнес-процесу не буле переданий певний параметр, то генерація витягу буде зупинена з помилкою, яку потенційно буде
складно ідентифікувати. Якщо відсутність певного параметра є допустимою ситуацією, то в шаблоні витягу це повинно бути
враховано. Якщо параметр є дійсно обов'язковим і його відсутність є виключною ситуацією, то рекомендується додати
відповідну перевірку в бізнес-процес перед викликом на генерацію витягу.
