= Аудит UI-форм бізнес-процесів

|===
|Назва | Критичність

|<<_fr_01>> |Висока

|===

[#_fr_01]
== FR-01. Великі форми
IMPORTANT: Критичність: Висока

NOTE: https://nngroup.com/articles/web-form-design/[]

== FR-02. Lazy load для комбо боксів
IMPORTANT: Критичність

== FR-03. Складна javascript логіка в компоненті
IMPORTANT: Критичність

.Рекомендації
* Бути обережним з логіка при рендерінгу елементу в селекті після виконання СК (зміна дісплей нейм в залежності від
значення елементу пошуку)

== FR-04. Зовнішні АПІ сервіси в компоненті Select
IMPORTANT: Критичність

,Опис
При інтеграції з зовнішніми АПІ сервісами враховувати чи підтримує сервіс cookie для автентифікації,
що вплине на налаштування відповідного компоненту select (Add authentication cookies for cross-site
requests)

== FR-05. Компонент карти. Інтеграція з підкладинками

.Опис
При необхідності інтеграції з кастомними підкладинками на картах, враховувати CORS політики, які додатково
повинні бути налаштовані на API-Gateway https://jiraeu.epam.com/browse/MDTUDDM-23166[MDTUDDM-23166]

== FR-06. Вкладеність компонентів зі складними зв'язками

== FR-07. Експериментальні компоненти

== FR-08. Ліміти на критеріях пошуку для селектів

== FR-09. Математичні обчислення

== FR-10. Компонент Number

== FR-11. Маска на текст філді

== FR-12. Edit grid. Велика кількість записів
// TODO: Подивитись на приклади у Еміля та РПЗМ
// TODO: Почитати про optimized rendering фічу

== FR-13. Функції без сайд ефектів в компонентах

== FR-14. Ручні зміни в дефінішенах компонентів форми