= Аудит UI-форм бізнес-процесів

|===
|Назва | Критичність

|<<_fr_01>> |Висока
|<<_fr_02>> |Середня
|<<_fr_03>> |Висока
|<<_fr_04>> |Висока
|<<_fr_05>> |Висока

|===

[#_fr_01]
== FR-01. Великі форми
IMPORTANT: Критичність: Висока

.Опис
Робити форми якомога простішими та короткими

.Вплив
* Зниження продуктивності при рендерінгу форми в браузері
* Ускладнення внесення змін до форми розробниками регламенту
* Погіршення користувацького досвіду при заповненні або перегляді форми
* Збільшення ймовірність виникнення системної помилки у користувача при роботі з формою (наприклад, втрата заповнених даних через закінчення сесії користувача)

.Рекомендації
* При внесенні даних, розбивати форму на декілька окремих і робити збір даних поетапно
* При перегляді даних:
** Показувати обмежений набір даних за замовчуванням
** Для перегляду детальної інформації використовувати звіти чи витяги


NOTE: Детальніше про кращі практики по розробці WEB форм можна ознайомитись https://nngroup.com/articles/web-form-design/[за посиланням]

[#_fr_02]
== FR-02. Lazy load для компоненту _Select_
IMPORTANT: Критичність: середня

.Опис
При наявності великої кількості компонентів _Select_ на формі, використовувати _lazy load_ для підвантаження даних по URL.
За замовчуванням компонент _Select_ заздалегідь дістає дані (_eager load_) по URL в наступних випадках:

* При первинному рендерінгу форми
* При зміні в пов'язаному компоненті
* При оновленні користувацького токена (системна поведінка, яка відбувається безумовно незалежно від дій користувача)

.Вплив
* Додаткове навантаження на сервери та мережу
* Збільшення часу рендерінгу форми
* На момент написання документа в деяких випадках при значній кількості компонентів _Select_ у користувача може виникати
системна помилка з оновленням авторизаційного токена

.Рекомендації
* Уникати створення великих форм (див. <<_fr_01>>)
* Використовувати _lazy load_ для компонентів _Select_ якщо їх кількість на формі достатньо велика (понад 5)
* Використовувати _eager load_ у випадках, коли це дійсно може покращити користувацький досвід. Наприклад, для першого
компоненту _Select_ на формі, щоб у користувача відразу після рендерінгу форми були необхідні дані для вибору

[#_fr_03]
== FR-03. _Javascript_ логіка в компонентах форми
IMPORTANT: Критичність: висока

.Опис
Конструктор форм дозволяє втілити значну кількість обробки даних та валідацій за допомогою вбудованих можливостей.
Додатково, існує можливість для певного переліку налаштувань (validation, conditional, custom default value)
реалізувати індивідуальну логіку на javascript. Це дозволяє з одного боку гнучко налаштовувати форму, однак, складна
та об'ємна логіка створює приховану складність, яка може призвести до проблем, що важко відлагоджуються або
непередбачуваної поведінки форми.

.Вплив
Підтримка та розвиток складної _javascript_ логіки на рівні моделювання форми стають крайно незручними. Це може призвести
до додаткового часу, витраченого на відлагодження, а також збільшити ймовірність помилок. Особливо це стає актуальним,
коли команда розробників змінюється або проєкт передається на підтримку.

.Рекомендації
* Контроль обсягу використання Javascript. Обмежувати складність _javascript_ логіки в формах. Намагатися зберігати логіку
якомога простішою та більш прямолінійною.
* Використовувати вбудовані можливості конструктора форм для валідації та обробки даних
* Уникати побічних ефектів в місцях використання. Кожна вставка _javascript_ логіки має єдину відповідальність (валідація,
умовне відображення, обробка даних тощо) та не має впливати на інші частини форми

[#_fr_04]
== FR-04. Зовнішні АПІ сервіси в компоненті _Select_
IMPORTANT: Критичність: висока

.Опис
Компонент _Select_ як джерело даних може використовувати зовнішні АПІ сервіси за довільним доменом, наприклад,
як довідник. Додатково існує можливість додавання кук (cookie) домену АПІ сервісу у виклик, який може містить куку
(cookie) для авторизації. Треба узгодити налаштування на такому АПІ сервісі (якщо є можливість впливати на ці
налаштування) та формою, яка виконує цей запит.

NOTE: Безпосередньо отримання авторизаційної кукі (cookie) поза скоупом рішення і не є предметом цього документу.

.Вплив
* Браузер заблокує виконання запиту до АПІ сервісу через CORS політики
* АПІ сервіс заблокує запит через відсутність необхідної Cookie

.Рекомендації
* Якщо АПІ сервіс відкритий і не потребує авторизації:
** В налаштуваннях компонента _Select_ виключити передачу авторизаційної інформації при запиті на АПІ сервіс (параметр
_Add authentication cookies for cross-site requests_ = false)
** Значення заголовка _Access-Control-Allow-Origin_ у відповіді АПІ сервісу повинно мати значення домену кабінету
користувача або вайлкард _*_
* Якщо АПІ сервіс потребує авторизації та рішення припускає наявність кукі (cookie) для авторизації на домен АПІ сервісу
в браузері необхідні наступні умови:
** В налаштуваннях компонента _Select_ додати передачу авторизаційної інформації при запиті на АПІ сервіс (параметр _Add
authentication cookies for cross-site requests_ = true)
** Значення заголовка _Access-Control-Allow-Origin_ у відповіді АПІ сервісу повинно мати значення домену кабінету
користувача (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials[вайлдард _*_
 не допускається])
* Додатково перед виходом в промислове середовище потрібно перевірити налаштування АПІ сервісу та форми та впевнитися, що
вони заздалегідь адаптовані до вимог CORS політик. Наприклад, домен користувача кабінету доданий в налаштування зовнішнього
АПІ сервісу

[#_fr_05]
== FR-05. Компонент карти. Нестандартні тайл-сервери
IMPORTANT: Критичність: висока

.Опис
При використанні нестандартних тайл-серверів для базового шару карти необхідно провести додаткові налаштування
на сервері для оновлення _Content-Security-Policy_ (CSP) заголовка відповіді.

NOTE: На момент написання документа стандартними тайл-серверами вважаються _tile.openstreetmap.org_ та _visicom.ua_.

.Вплив
Без додаткових налаштувань на сервері браузер буде блокувати запити на тайл-сервер і карта не буде працювати.

.Рекомендації
Заздалегідь провести налаштування на відповідному оточенні, якщо відомо, що будуть використовуватися нестандартні
тайл-сервери.

NOTE: На момент написання статті конфігурація _Content-Security-Policy_ (CSP) задається у файлі
_deploy-templates/templates/kong-response-transformer-plugin.yaml_ репозиторію _common-web-app_

== FR-06. Вкладеність компонентів зі складними зв'язками

== FR-07. Експериментальні компоненти

== FR-08. Ліміти на критеріях пошуку для селектів

== FR-09. Математичні обчислення

== FR-10. Компонент Number

== FR-11. Маска на текст філді

== FR-12. Edit grid. Велика кількість записів
// TODO: Подивитись на приклади у Еміля та РПЗМ
// TODO: Почитати про optimized rendering фічу

== FR-13. Ручні зміни в дефінішенах компонентів форми