= Аудит шаблонів аналітичних звітів

|===
|Назва | Критичність

|<<_rp_01>> |Висока
|<<_rp_02>> |Висока
|<<_rp_03>> |Низька
|<<_rp_04>> |Середня
|<<_rp_05>> |Середня
|<<_rp_06>> |Висока
|<<_rp_07>> |Середня

|===

[#_rp_01]
== RP-01. Фільтрація в CTE
IMPORTANT: Критичність: висока

.Опис
При використанні спільних табличних виразів (common table expression) в SQL-запитах вкрай важливо виконувати фільтрацію
безпосередньо у тілі CTE, а не у основному виразі, що використовує CTE.

.Вплив
Застосування фільтрів у основному виразі замість тіла CTE може призвести до значно більшого часу обробки. Нефільтровані
CTE можуть спричинити витягування зайвих даних з бази даних, унаслідок чого обчислення CTE та цілого запиту стають
набагато повільнішими.

.Рекомендації
Завжди застосовуйте фільтри в тілі CTE, а не у основному виразі. Це оптимізує ваші SQL-запити, зменшує непотрібне
обчислювальне навантаження та покращує загальний час обробки даних.

[#_rp_02]
== RP-02. Індекси для аналітичних представлень
IMPORTANT: Критичність: висока

.Опис
При створенні аналітичних представлень (за допомогою тегу _ext:createAnalyticsView_), необхідно також створювати індекси
для полів, за якими буде відбуватися пошук.

.Вплив
Невикористання індексів може суттєво сповільнити продуктивність запитів до бази даних. Це може негативно вплинути на
загальну продуктивність системи, час відклику на запити користувачів та задоволеність користувачів.

.Рекомендації
Створювати індекси для полів, які використовуються для пошуку в аналітичних представленнях, за допомогою тегу
_ext:createAnalyticsIndex_. Це забезпечує швидке пошукове звернення до даних та зменшує час відповіді на стороні сервера.

[#_rp_03]
== RP-03. Типові SQL-функції
IMPORTANT: Критичність: низька

.Опис
Використовувати SQL функції, розроблені в платформі для розв'язання типових задач при моделюванні запитів для аналітичних
звітів

.Вплив
* Використання типових SQL функцій дозволяє зменшити кількість коду, який потрібно писати для розв'язання типових задач
* Функції, щр постачаються в платформі, вже оптимізовані і враховують більше варіантів використання
* Зменшення часу розробки внаслідок перевикористання рішень, які вже реалізовані в платформі

.Рекомендації
Для наступних типових задач можуть бути використані SQL функції:

* Екранування спеціальних символів в параметрах пошуку - _f_regexp_escape_, _f_like_escape_
* Застосування RLS (Row Level Security) - _f_starts_with_array_

NOTE: Детальніше про типові SQL функції можна ознайомитись за посиланням: xref:registry-develop:data-modeling/data/physical-model/liquibase-ddm-ext.adoc[]


xref:architecture-workspace/platform-evolution/registry-audit-instruction/modules/sec-audit.adoc#_sc_01[Принцип найменших привілеїв]

[#_rp_04]
== RP-04. Зміни в аналітичних звітах для різних ролей
IMPORTANT: Критичність: середня

.Опис
Вносити зміни в кожну копію звіту для кожної окремої ролі при необхідності внесення змін в звіт чи відповідний запит.
Авторизаційна модель для аналітичних звітів побудована таким образом, що для кожної ролі створюється окрема директорія,
що містить всі необхідні запити та звіти, що для цієї ролі доступні. Це призводить до того, що фактично йде копіювання
файлів описів запитів та звітів для кожної ролі в регламенті.

.Вплив
* Неконсистентний стан звітів для різних ролей. Наприклад, при виправленні помилки для однієї з ролей, інші ролі будуть
бачити стару версію звіту, доки не буде внесено зміни в кожну копію звіту.
* Потенційно збільшена кількість ітерацій для випуску релізу чи хотфіксу

.Рекомендації
* Після внесення змін у відповідний звіт у _Веб-інтерфейсі моделювання звітів_ треба розповсюдити його по всім ролям, що
його використовують.
* Якщо на якомусь етапі розробки було виявлено, що звіт для окремої ролі повинен відрізнятися чи має специфічні вимоги -
винести його як окремий звіт для цієї ролі зі своїм життєвим циклом
* При копіюванні звітів для ролей не змінювати імена файлів та ідентифікатори ресурсів в файлах, які були згенеровані
при створені звітів у _Веб-інтерфейсі моделювання аналітичних звітів_ для можливостей простежуваності (traceability)
копій.

[#_rp_05]
== RP-05. Заплановані запити (Scheduled Queries)
IMPORTANT: Критичність: середня

.Опис
Мінімізувати кількість запитів аналітичних звітів, що виконуються за розкладом, на одиницю часу. Чим частіше буде
виконуватися такого роду запити, тим більше буде навантаження на тимчасове сховище, яке зберігає результати запитів.

[#_rp_06]
== RP-06. Налаштування прав доступ до аналітичних представлень
IMPORTANT: Критичність: висока

.Опис
При налаштуванні прав доступу до аналітичних представлень (_ext:grant_) застосовувати
xref:architecture-workspace/platform-evolution/registry-audit-instruction/modules/sec-audit.adoc#_sc_01[Принцип найменших привілеїв]
Тобто необхідно надавати доступ тільки для тих представлень, які використовуються в звітах, а не для всіх представлень.
Тег _ext:grantAll_ рекомендується використовувати виключно для розробки у _Веб-інтерфейсі моделювання аналітичних звітів_
Також рекомендується використовувати атрибути тегів _ext:grant_ та _ext:grantAll_ _runAlways="true"_ для підтримання
налаштувань авторизації при оновленні звітів

[#_rp_07]
== RP-07. Підтримка налаштування прав доступ
IMPORTANT: Критичність: середня

.Опис
Використовувати атрибут _runAlways="true"_ тегів _ext:grant_ та _ext:grantAll_  для підтримання налаштувань авторизації
при оновленні звітів