= Аудит шаблонів аналітичних звітів

|===
|Назва | Критичність

|<<_rp_01>> |Висока
|<<_rp_02>> |Висока
|<<_rp_03>> |Середня
|<<_rp_04>> |Середня
|<<_rp_05>> |Середня
|<<_rp_06>> |Висока
|<<_rp_07>> |Середня

|===

[#_rp_01]
== RP-01. Фільтрація в CTE
IMPORTANT: Критичність: висока

.Опис
При застосуванні CTE (common table expression) виразів, використовувати фільтрацію в CTE, а не в основному виразі, який
його застосовує

[#_rp_02]
== RP-02. Індекси для аналітичних представлень
IMPORTANT: Критичність: висока

.Опис
При створенні аналітичних представлень (тег _ext:createAnalyticsView_) додатково створювати індекси для полів, по яких
буде відбуватися фільтрація

[#_rp_03]
== RP-03. Типові SQL-функції
IMPORTANT: Критичність: середня

.Опис
Використовувати SQL функції, розроблені в платформі для розв'язання типових задач таких як санітайзінг параметрів
(_f_regexp_escape_, _f_like_escape_), застосування RLS (Row Level Security) у звітах (_f_starts_with_array_) тощо

[#_rp_04]
== RP-04. Управління змінами в аналітичних звітах
IMPORTANT: Критичність: середня

.Опис
При наявності декількох ролей для перегляду одного і того ж самого звіту, він копіюється в регламенті для кожної ролі
окремо. При необхідності внесення змін в звіт чи відповідний запит треба вносити зміни в кожну копію звіту для
консистентності ресурсів, або розділяти звіти по функційному призначенню і моделювати їх окремо. Не змінювати імена
файлів та ідентифікатори ресурсів в файлах, які були згенеровані при створенні звітів у _Веб-інтерфейсі моделювання
аналітичних звітів_ для можливості ідентифікації копій звітів в регламенті (використання одного і того ж самого звіту
в декількох ролях)

[#_rp_05]
== RP-05. Заплановані запити (Scheduled Queries)
IMPORTANT: Критичність: середня

.Опис
Мінімізувати кількість запитів аналітичних звітів, що виконуються за розкладом, на одиницю часу. Чим частіше буде
виконуватися такого роду запити, тим більше буде навантаження на тимчасове сховище, яке зберігає результати запитів.

[#_rp_06]
== RP-06. Налаштування прав доступ до аналітичних представлень
IMPORTANT: Критичність: висока

.Опис
При налаштуванні прав доступу до аналітичних представлень (_ext:grant_) застосовувати
xref:architecture-workspace/platform-evolution/registry-audit-instruction/modules/sec-audit.adoc#_sc_01[Принцип найменших привілеїв]
Тобто необхідно надавати доступ тільки для тих представлень, які використовуються в звітах, а не для всіх представлень.
Тег _ext:grantAll_ рекомендується використовувати виключно для розробки у _Веб-інтерфейсі моделювання аналітичних звітів_
Також рекомендується використовувати атрибути тегів _ext:grant_ та _ext:grantAll_ _runAlways="true"_ для підтримання
налаштувань авторизації при оновленні звітів

[#_rp_07]
== RP-07. Підтримка налаштування прав доступ
IMPORTANT: Критичність: середня

.Опис
Використовувати атрибут _runAlways="true"_ тегів _ext:grant_ та _ext:grantAll_  для підтримання налаштувань авторизації
при оновленні звітів