= Аудит безпеки

|===
|Назва | Критичність

|<<_sc_01>> |Висока
|<<_sc_02>> |Висока
|<<_sc_03>> |Висока
|<<_sc_04>> |Висока
|<<_sc_05>> |Висока
|<<_sc_06>> |Висока

|===

[#_sc_01]
== SC-01. Принцип найменших привілеїв
IMPORTANT: Критичність: висока

.Опис
При налаштуванні прав доступу до бізнес-процесів кожна окрема роль повинна мати лише ті права, які необхідні для
виконання її функцій. Це дозволить уникнути можливості використання ролі для виконання дій, які не передбачені її
функціональним призначенням.

.Вплив
- **Збільшення ризику несанкціонованого доступу:** Якщо ролі надаються занадто широкі права, користувачі можуть отримати доступ до інформації або функцій, які повинні бути обмежені.

- **Несанкціонована зміна даних**: Користувачі можуть внести зміни в дані або конфігурацію, що може призвести до неправильної роботи регламенту.

- **Збільшення ризику витоку інформації:** Доступ до даних, який не передбачено роллю, може призвести до ненавмисного або навмисного розголошення конфіденційної інформації.

.Рекомендації
- Необхідно розробити та поставити процес регулярного огляду налаштувань прав доступу, щоб гарантувати, що кожна роль має лише відповідні права.

- Завжди надавайте ролям мінімум необхідних прав.

- Навчання розробників регламенту основам інформаційної безпеки й важливості обмеження доступу.

[#_sc_02]
== SC-02. Мінімізація ролей з розширеними правами
IMPORTANT: Критичність: висока

.Опис
При створенні моделі прав доступу до даних рекомендується використовувати обмежену кількість ролей які мають високий рівень доступу до ресурсів, таких як адміністративні. Недотримання цього принципу може призвести до серйозних ризиків безпеки.

.Вплив
- **Збільшення ризику шахрайства та зловживань:** Користувачі з розширеними правами можуть здійснювати небезпечні зміни, які не можуть бути легко виявлені або відновлені.

- **Ризик втрати даних:** Користувачі з великими повноваженнями можуть випадково або навмисно видалити важливі дані.

- **Збільшений ризик взломів:** Якщо багато користувачів мають розширені права, атакуючі будуть мати більше цілей для спроб взлому, що може призвести до компрометації системи.

- **Розголошення конфіденційної інформації:** Більше користувачів з високим рівнем доступу означає більше можливостей для витоку або розголошення конфіденційної інформації.

.Рекомендації
- Неодхідно розробити та поставити процес регулярного огляду ролей в системі та визначення, хто дійсно потребує розширених прав.

- Завжди надавайте користувачам та системам лише ті права, які вони дійсно потребують для виконання своїх завдань.

- Обмежте тривалість часу, протягом якого розширені права присвоюються ролям у разі необхідності, і встановіть процес перегляду та відновлення цих прав.

- Проводьте регулярні сесії навчання з інформаційної безпеки для користувачів яким було присвоєно ролі з розширеними повноваженнями.

[#_sc_03]
== SC-03. Принцип розділення обов'язків
IMPORTANT: Критичність: висока

.Опис
При моделюванні прав доступу до бізнес-процесів чи баз даних надавати перевагу створенню декількох ролей які будуть залучені для виконання ключових функцій, особливо тих, що стосуються критично важливих операцій, щоб уникнути зловживань, помилок або шахрайства.

.Вплив
- **Збільшення ризику шахрайства:** Якщо одна особа контролює всі етапи критичного процесу, їй легше скоїти шахрайство, не будучи виявленою.

- **Відсутність контролю:** Без розділення обов'язків складно виявити помилки або неналежні дії, що можуть призвести до втрати даних, збитків або інших проблем.

- **Конфлікти інтересів:** Одна особа може здійснювати дії на користь собі та на шкоду організації.

- **Збільшення ризику втрати конфіденційної інформації:** Без належного розділення обов'язків особа з надмірними повноваженнями може мати доступ до інформації, яка їй не потрібна для роботи, і може використовувати або розголошувати цю інформацію неналежним чином.

.Рекомендації
- Основна мета полягає в тому, щоб жодна окрема особа не мала досить авторитету або можливості виконувати, одноосібно, всі етапи критичного процесу.

- Розділення обов'язків забезпечує, що окремі особи виконують різні функції, що зменшує ризик зловживань.

- Коли кілька осіб перевіряє та підтверджує дії одна одної, існує менший ризик несанкціонованих або помилкових дій.

- Розділення обов'язків ускладнює вчинення шахрайства, оскільки це вимагає співпраці кількох осіб.

[#_sc_04]
== SC-04. RLS (Row Level Security) на моделі даних
IMPORTANT: Критичність: висока

.Опис
Для забезпечення гранулярного доступу до даних слід використовувати механізм RLS (Row Level Security). RLS дозволяє обмежити доступ для читання до певних
рядків (сутностей) на основі зазначеного атрибута користувача. Наприклад, розділити доступ до даних за підрозділом організації, до якого належить користувач.

.Вплив
- **Зменшення ризику витоку даних:** Для отримання доступу до всіх даних необхідно широка площа атаки на всіх користувачів.

- **Підвищення контролю доступу:** Кількість отриманих даних обмежена не залежно від запиту користувача атрибутами які присвоєні даному користувачу.

.Рекомендації
- При побудові централізованих реєстрів, які мають децентралізовану природу та базуються на територіальній приналежності можна використовувати КАТОТТГ коди в якості атрибутів користувачів.

- Для зменшення ризиків витоку конфіденційної інформації не слід використовувати таку інформацію як атрибут для користувачів
для обмеження доступу до даних на базі RLS

[#_sc_05]
== SC-05. RBAC (Role Based Access Control) на моделі даних
IMPORTANT: Критичність: висока

.Опис
Для забезпечення безпеки даних та гранулярності доступу до даних використовувати механізм RBAC (Role Based Access Control).
RBAC дозволяє обмежити доступ до певних атрибутів сутності (колонок таблиці) в залежності від ролі користувача.

.Вплив
- **Зменшення ризику несанкціонованого доступу:** Дані мають додатковий рівень захисту, таким чином у разі зловживань або помилок у бізнес-процесі виконується додаткові перевірки доступності операції.

- **Несанкціонована зміна даних**: Можливість надання користувачу доступ тільки на читання на рівні дата моделі зменшує шанс несанкціонованої зміни даних.

.Рекомендації
- Використовувати мінімальні необхідні доступні права до даних.

[#_sc_06]
== SC-06. Конфіденційні дані
IMPORTANT: Критичність: висока

.Опис
При проєктуванні та моделюванні регламенту реєстру мінімізувати використання і зберігання конфіденційних даних в базі даних та
_Підсистемі управління користувачами та ролями_ до мінімально можливих для функціонування системи.

.Вплив
- **Ризик витоку даних:** Збільшується ймовірність витоку конфіденційних даних, якщо база даних буде скомпрометована.

- **Збільшення цілей для атак:** Збільшена кількість конфіденційних даних у базі робить її більш цінною ціллю для зловмисників.

- **Ускладнення відновлення:** У випадку втрати даних буде важче відновити систему без ризику для конфіденційності інформації.

- **Недотримання законодавчих та нормативних вимог:** Збільшення ймовірності виникнення проблеми з дотриманням вимог
законодавства щодо захисту конфіденційних даних.

.Рекомендації
- Зберігайте лише ті дані, які дійсно необхідні для функціонування системи.