= Аудит безпеки

|===
|Назва | Критичність

|<<_sc_01>> |Висока
|<<_sc_02>> |Висока
|<<_sc_03>> |Висока
|<<_sc_04>> |Висока
|<<_sc_05>> |Висока
|<<_sc_06>> |Висока

|===

[#_sc_01]
== SC-01. Принцип найменших привілеїв
IMPORTANT: Критичність: висока

.Опис
При налаштуванні прав доступу до бізнес-процесів кожна окрема роль повинна мати лише ті права, які необхідні для
виконання її функцій. Це дозволить уникнути можливості використання ролі для виконання дій, які не передбачені її
функціональним призначенням.

.Вплив
placeholder

.Рекомендації
placeholder

[#_sc_02]
== SC-02. Мінімізація ролей з розширеними правами
IMPORTANT: Критичність: висока

.Опис
placeholder

.Вплив
placeholder

.Рекомендації
placeholder

[#_sc_03]
== SC-03. Принцип розділення обов'язків
IMPORTANT: Критичність: висока

.Опис
При моделюванні прав доступу до бізнес-процесів чи баз даних надавати перевагу створенню декількох ролей з обмеженими
правами ніж одній ролі з розширеними правами. Це дозволить уникнути можливості використання ролі для виконання небажаних
дій.

.Вплив
placeholder

.Рекомендації
placeholder

[#_sc_04]
== SC-04. RLS (Row Level Security) на моделі даних
IMPORTANT: Критичність: висока

.Опис
Для забезпечення безпеки даних використовувати механізм RLS (Row Level Security). RLS дозволяє обмежити доступ до певних
рядків (сутностей) на основі певного атрибута користувача. Наприклад, розділити доступ до даних за підрозділом організації,
до якого належить користувач.

.Вплив
placeholder

.Рекомендації
placeholder

[#_sc_05]
== SC-05. RBAC (Role Based Access Control) на моделі даних
IMPORTANT: Критичність: висока

.Опис
Для забезпечення безпеки даних використовувати механізм RBAC (Role Based Access Control). RBAC дозволяє обмежити доступ
до певних властивостей сутності (колонок таблиці) в залежності від ролі користувача.

.Вплив
placeholder

.Рекомендації
placeholder

[#_sc_06]
== SC-06. Sensitive дані
IMPORTANT: Критичність: висока

.Опис
При проєктуванні та моделюванні регламенту реєстру мінімізувати використання і зберігання sensitive даних в базі даних та
_Підсистемі управління користувачами та ролями_ до мінімально можливих для функціонування системи.

.Вплив
placeholder

.Рекомендації
placeholder