= Розширення можливостей редактору коду за допомогою _Language Server Protocol (LSP)_

У якості єдиного редактора коду для внесення змін до регламенту реєстру та порівняння версій обрано рішення https://microsoft.github.io/monaco-editor/[monaco-editor].

Регламент реєстру складається з набору декларативних описів важливих аспектів функціонування реєстру у вигляді конфігураційних файлів наступних типів:

- _XML_
- _JSON_
- _YAML_
- _HTML_
- _CSV_
- _Groovy_

Для забезпечення розширених можливостей по роботі з визначеними типами конфігураційних файлів через _Систему Управління Регламентом Реєстру_ та формуванням єдиного підходу до реалізації підтримки нових типів файлів та мов, рекомендовано розглянути https://microsoft.github.io/language-server-protocol/[Language Server Protocol], який стандартизує інтеграцію зовнішніх мовних серверів та редактора коду.

== Ключові вимоги до редактора коду

В залежності від природи окремої складової регламенту, редактор коду має реалізовувати особливі вимоги для спрощення використання на зниження вірогідності внесення помилок.

=== BPMN XML

* ...
* ...

=== Liquibase XML

* ...
* ...

=== JSON

* ...
* ...

=== YAML

* ...
* ...

=== HTML

* ...
* ...

=== CSV

* ...
* ...

=== Groovy

* ...
* ...

== Опис _Language Server Protocol_

[TIP]
Please describe general concept & motivation behind LSP

== Дизайн інтеграції редактора коду та мовних серверів

[TIP]
Please add visual diagram and describe how to integrate monaco-editor with XML / Groovy / JSON / etc. Language Server
