= Побудова аналітичних звітів

== Вступ

Побудова аналітичних звітів на Платформі є можливою завдяки сервісу https://redash.io/help/[Redash] -- інструменту для візуалізації даних, призначеного для вивчення, запита, візуалізації та обміну даними з будь-яких джерел даних та побудови відповідних інформаційних панелей (дашбордів) за цими даними.

**Процес побудови аналітичних звітів у Redash поділяється на декілька основних етапів**:

. Підключення до Redash джерела даних, тобто, підключення БД, звідки Redash отримуватиме дані для аналітики (_див. https://redash.io/help/user-guide/getting-started#1-Add-A-Data-Source[]_).

. Створення (написання) пошукових запитів до БД (_див. https://redash.io/help/user-guide/querying_).

. Створення візуалізацій (візуальних зображень отриманих даних) на основі запитів (_див. https://redash.io/help/user-guide/visualizations_).

. Побудова інформаційних панелей (дашбордів) -- поєднання візуалізацій та текстових полів, що надають контексту даним, що візуалізуються Redash (_див. https://redash.io/help/user-guide/dashboards_).

:sectnums:
:sectanchors:

== Загальний опис

Функціонування аналітичної звітності забезпечують два кластери Redash, що вибудовують систему звітності на базі репліки операційної бази даних реєстру.

Один кластер (`admin`) розгортатиметься в мінімальному об’ємі для адміністрування, розробки та публікування звітності. З міркувань безпеки його відокремлено від іншого -- `viewer`, що міститиме опублікований контент для потреб користувачів.

Доступ до контенту серверів Redash розмежовується за приналежністю користувача до групи, що, своєю чергою, асоційована із джерелом даних.

Розмежування доступу до даних реалізується за допомогою користувачів бази даних, що використовуються відповідним джерелом даних для виконання запитів до репліки БД.

=== Діаграма дизайну

image:admin:data-analytics-architecture.svg[]

== Надання прав доступу до звітності

Область видимості доступних об’єктів Redash визначається джерелом даних -- користувач бачить ті запити (Queries) та інформаційні панелі (dashboards), що утилізують доступне користувачеві джерело даних.

Рівень прав доступу до об’єктів системи звітності регулюється **групами**. На етапі первинного розгортання системи, групи асоціюються з відповідними **джерелами даних**.

== Доступ до даних та розмежування прав

Для кожного джерела даних, доданого на Redash-екземплярах, необхідно створити також відповідного користувача бази даних. Представлена нижче таблиця задає назву користувача бази даних для кожного джерела даних Redash:

[cols="2*^"]
|===
|Data source |Database User

|`registry`
|`analytics_admin`

|`registry_auditor`
|`analytics_auditor`

|`registry_<назва ролі>`
|`analytics_<назва ролі>`

|===

TIP: `<назва ролі>` -- _змінна, що потребує значення для назви ролі_.

WARNING: *[red]##_Важливо!##* Користувачі бази даних створюються лише **в репліці** операційної бази даних, **не в операційній БД**! +
Створення користувачів відбувається по факту внесення змін до файлу `roles/officer.yaml` Gerrit-репозитарію реєстру_.

**Доступ до даних реєстру має надаватися через окремий прошарок представлень (`view`)**.

Для цього в моделі даних, з використанням шаблону Liquibase, необхідно створити відповідний критерій пошуку в БД (**Search Condition**) з обов'язковим вказанням контексту (`context`) -- *`sub`*. Контекст `sub` скерує Liquibase до створення представлення лише на репліці операційної бази даних, що також дозволить уникнути створення API для об'єктів аналітики.

.Приклад створення представлення для подальшого використання при побудові звітності:
[source,xml]
----
<changeSet author="registry owner" id="searchCondition labs_by_towns" context="sub">
        <comment>CREATE analytical view labs_by_towns</comment>
        <ext:createSearchCondition name="pd_processing_consent_1" indexing="like">
            <ext:table name="laboratory" alias="l">
                <ext:column name="name" alias="laboratory_name" returning="true"/>
                <ext:column name="phone_number" returning="true"/>
                <ext:column name="edropou" returning="true" />
            </ext:table>
            <ext:table name="koatuu" alias="k">
                <ext:column name="type" returning="true"/>
                <ext:column name="name" alias="koatuu_name" returning="true"/>
            </ext:table>
            <ext:join type="inner">
                <ext:left alias="l">
                    <ext:column name="koatuu_id"/>
                </ext:left>
                <ext:right alias="k">
                    <ext:column name="koatuu_id"/>
                </ext:right>
            </ext:join>
        </ext:createSearchCondition>
    </changeSet>
----

TIP: _За детальною інформацією щодо створення моделі даних за допомогою шаблонів Liquibase зверніться до розділу xref:admin:liquibase-changes-management-sys-ext.adoc[Створення сценаріїв побудови фізичної моделі даних реєстру за допомогою функціональних розширень Liquibase] цього керівництва_.

Після створення представлення, необхідно відповідній ролі надати доступ до створеного об'єкта, в залежності від того, які ролі мають право доступу до звітів, що будуватимуться на створених представленнях.

Надавати доступ користувачеві до представлення необхідно через окремий тег в XML-шаблоні Liquibase, що детально описано в розділі xref:admin:data-analytical-data-access-rights.adoc[Права доступу до аналітичних даних] цього керівництва.
