= Автоматизація експорту звітів Redash

:sectnums:
:sectanchors:

== Загальний опис

Панель адміністратора містить окрему сторінку для управління звітами Redash -- перелік інформаційних панелей (дашбордів). Для кожної панелі міститься:

* посилання на дашборд в Admin-екземплярі Redash;
* посилання на <<Сервіс експорту звітності, експорт дашборду>>.

<<Сервіс експорту звітності>> повертає архів з JSON-файлом дашборду та всіма залежними запитами в окремій теціfootnote:[**Тека** -- елемент файлової системи, що може містити групу файлів.] **queries**.

Для внесення змін до реєстру та публікації звітів, моделювальникові даних необхідно завантажити отримані файли до репозиторію Gerrit, виконавши `git commit`. Така дія, своєю чергою, відслідковується інструментом автоматизації Jenkins, який запускатиме відповідний pipeline.

.Діаграма процесу публікації звітів Redash через панель адміністратора:
image:admin:data-analytical-reports-export-automation.svg[dsfg, 100%]

== Сервіс експорту звітності

=== REST API

Запит до ендпоінта (кінцевої точки інтеграції) створеного сервісу повертає перелік інформаційних панелей, наявних в admin-екземплярі Redash:

.Структура параметрів запита:
----
GET /
[
    {
        "id": ...
        "name": ...
        "slug": ...
        "created_at": ...
        "updated_at": ...
    },
    ...
]
----

У випадку зазначення `slug`-дашброрду, ендпоінт повертає архів з інформаційними панелями у форматі JSON.

.Приклад GET-запита із параметром `slug`:
----
GET /slug_id

----

**Сервіс виконує наступні дії**:

* приймає на вхід `slug_id` (ідентифікатор дашборду);
* отримує JSON дашборду з Redash Admin REST API (`dashboard_<slug>.json`)
* для кожного із залежних запитів отримує JSON запита від Redash Admin REST API та зберігає як масив у `queries/parameters_<slug>.json`(<<parameter_queries, формат файлу>> зазначено нижче);
* формує <<archive, zip-пакет>> для повернення.

NOTE: _За детальною інформацією щодо формату запитів до Redash API зверніться до секції xref:data-analytical-reports-creation.adoc#object-publishing[Об'єкти для публікації звітності] цього керівництва_.

[#archive]
=== Структура файлів, що містяться в архіві
[plantuml, format=png]
----
@startuml
    skinparam monochrome true
    note as N1
      dashboard_<slug>.zip
      |_ queries
        |_ parameters_<slug>.json
      |_ dashboard_<slug>.json
    end note
@enduml
----

[#parameter_queries]
.Формат файлу із залежними запитами:
[source, json]
----
{
  "count": 3,
  "page": 1,
  "page_size": 25,
  "results": [
    {"id": ...},
    {"id": ...},
    {"id": ...}
  ]
}
----
