= Керування змінними середовища (global-vars)

Система надає можливість налаштування глобальних змінних для реєстру адміністратором регламенту.

Глобальні змінні є частиною регламенту та зберігаються у директорії з назвою `global-vars`.

Змінні налаштовуються у відповідних конфігураційних файлах із розширенням `.yml`.

Наразі глобальні змінні можуть бути використані для:

- налаштування шляху до фабрики даних (`dataFactoryBaseUrl`);
- налаштування Email служби підтримки (`supportEmail: support_test_mdtuddm@epam.com`).

== Формат глобальних змінних

Глобальні змінні мають наступний формат:

----
{Назва змінної}: параметр змінної
----

[TIP]
====
_Наприклад, посилання до фабрики даних налаштовується у файлі `camunda-global-system-vars.yml` і має наступний вигляд:_

----
dataFactoryBaseUrl: http://registry-rest-api:8080
----
====

Конфігурація для Email служби підтримки також виконується у файлі `camunda-global-system-vars.yml` і виглядає наступним чином:

----
supportEmail: some_email@somedomain.com
----

== Застосування глобальних змінних

Глобальна змінна `dataFactoryBaseUrl` застосовується у делегатах-конекторах до фабрики даних із підтримкою всіх CRUD операцій.

Змінна `supportEmail` використовується на сторінках усіх критичних помилок у Кабінетах посадової особи та отримувача послуг для відображення Email служби підтримки.