= Управління змінними середовища (global-vars)

Система надає можливість конфігурування глобальних зміних для реєстру адміністратором регламенту.
Глобальні змінні є частиною регламенту та зберігаються у директорії з назвою global-vars.
Змінні налаштовуються у відповідних файлах .yml

На даний час глобальні змінні можуть бути використані для:

- конфигурації шляху до дата-фабрики (dataFactoryBaseUrl)

- конфігурації Email служби підтримки (supportEmail: support_test_mdtuddm@epam.com)

== Формат глобальних зміних
Глобальні змінні мають такий формат:
----
{Назва змінної}: параметр змінної
----
Наприклад:

Посилання на дата-фабрику налаштовується у файлі camunda-global-system-vars.yml та має такий вигляд:

----
dataFactoryBaseUrl: http://registry-rest-api:8080
----

Налаштування для Email служби підтримки також налаштовується у файлі camunda-global-system-vars.yml та виглядає таким чином:
----
supportEmail: some_email@somedomain.com
----


== Застосування глобальних змінних

Глобальна змінна `dataFactoryBaseUrl` застосовується в делегатах-конекторах до дата-фабрики з підтримкою всіх CRUD операцій.

`supportEmail` змінна використовується на сторінках усіх критичних помилок в кабінетах Чиновника та Громадянина для відображення Email служби підтримки.










