= Спрощення моделювання бізнес-процесів за допомогою JUEL-функцій
:sectnums:
:sectanchors:

== Доступні функції
- `initiator()`
- `completer(<task_id>)`
- `submission(<activity_id|event_id>)`
- `sign_submission(<activity_id|event_id>)`
- `system_user()`


=== initiator()
Функція потрібна для отримання та подальшого використання ініціатора у процесі та повертає `UserDto`.

* `UserDto` -- клас що являє собою обгортку даних користувача (в цьому випадку ініціатора).
Завжди містить у собі userName та токен і JwtClaimsDto до першої задачі користувача.
Надає методи:
** getUserName() -- повертає ім'я користувача, що можна використовувати в Assignee та Candidate Users полях задач користувача
** getAccessToken() -- повертає токен користувача, що можна використовувати в інтеграційних конекторах для інтеграції від імені користувача
** getDrfo() -- делегує виклик на JwtClaimsDto та повертає Keycloak атрибут 'drfo' користувача
** getEdrpou() -- делегує виклик на JwtClaimsDto та повертає Keycloak атрибут 'edrpou' користувача
** getFullName() -- делегує виклик на JwtClaimsDto та повертає Keycloak атрибут 'fullName' користувача


NOTE: Токен ініціатора, а разом з ним і всі Keycloak атрибути, будуть доступні тільки до першої "User task" у бізнес-процесі

=== completer(<task_id>)

Фунція дозволяє отримати виконавця користувацької задачі для подальшого використання в процесі та повертає `UserDto`.

* `UserDto` -- клас що являє собою обгортку даних користувача (в цьому випадку ініціатора).
Завжди містить у собі userName та токен і JwtClaimsDto до першої задачі користувача.
Надає методи:
** getUserName() -- повертає ім'я користувача, що можна використовувати в Assignee та Candidate Users полях задач користувача
** getAccessToken() -- повертає токен користувача, що можна використовувати в інтеграційних конекторах для інтеграції від імені користувача
** getDrfo() -- делегує виклик на JwtClaimsDto та повертає Keycloak атрибут 'drfo' користувача
** getEdrpou() -- делегує виклик на JwtClaimsDto та повертає Keycloak атрибут 'edrpou' користувача
** getFullName() -- делегує виклик на JwtClaimsDto та повертає Keycloak атрибут 'fullName' користувача

NOTE: Функція комплітера доступна для використання після успішного завершення користувацької задачі.


=== submission(<activity_id|event_id>)

Фунція дозволяє отримати дані форми користувацької задачі та повертає `UserFormDataDto`.

* `UserFormDataDto` -- клас що являє собою обгортку даних форми користувача.

NOTE: Функція submission(<activity_id|event_id>) доступна для використання після успішного завершення користувацької задачі або стартової форми.

=== sign_submission(<activity_id|event_id>)

Функція потрібна для отримання  підпису та даних форми користувацьких задач та повертає `SignUserFormDataDto`.

* `SignUserFormDataDto` -- клас що являє собою обгортку для даних форми користувача, підпису та ключа цеф документа де зберігається підпис.


NOTE: Функція sign_submission(<activity_id|event_id>) доступна для використання після успішного завершення підписуючої користувацької задачі або стартової форм

=== system_user()

Необхідна для отримання системного користувача з Keyclock та повертає `UserDto`.

* `UserDto` -- клас що являє собою обгортку даних користувача (в цьому випадку ініціатора).
Завжди містить у собі userName та токен і JwtClaimsDto до першої задачі користувача.
Надає методи:
** getUserName() -- повертає ім'я користувача, що можна використовувати в Assignee та Candidate Users полях задач користувача
** getAccessToken() -- повертає токен користувача, що можна використовувати в інтеграційних конекторах для інтеграції від імені користувача
** getDrfo() -- делегує виклик на JwtClaimsDto та повертає Keycloak атрибут 'drfo' користувача
** getEdrpou() -- делегує виклик на JwtClaimsDto та повертає Keycloak атрибут 'edrpou' користувача
** getFullName() -- делегує виклик на JwtClaimsDto та повертає Keycloak атрибут 'fullName' користувача





