= Модель розгортання регламенту

Розгортання системи відбувається на підставі одного або декількох регламентів.

:sectnums:

== Структура регламенту

Каталог регламенту реєстру повинен мати чітко визначену структуру папок. Нижче схематично зображено приклад структури базового регламенту.

[plantuml]
----
@startsalt
{
{T
+ <&folder> registry-regulations-catalogue

++ <&folder> bpmn
+++ <&file> process.bpmn
+++ ...

++ <&folder> dmn
+++ <&file> validation-rule.dmn
+++ ...

++ <&folder> forms
+++ <&file> form.json
++++ ...

++ <&folder>data-model
+++ <&folder> changeLog
+++ <&file> model.xml
+++ <&file> settings.yaml

++ <&folder> reports
+++ <&file> report.json
+++ ...
}
}
@endsalt
----

[options="header"]
|=======================================================================
| Значення      | Пояснення
| `bpmn`          | Папка, що містить змодельовані бізнес-процеси
| `dmn`           | Папка, що містить змодельовані перевірчі правила
| `forms`         | Папка, що містить змодельовані користувацькі форми
| `data-model`    | Папка, що містить дані для розгортання бази даних та API
| `changeLog`     | Папка, що містить файли Liquibase для опису фізичної моделі даних в БД
| `main.xml`      | Файл, з якого створюватиметься база даних (підключення файлів із changeLog)
| `settings.yaml` | Файл, що містить опис додаткових налаштувань для розгортання фізичної моделі даних
| `reports`       | Папка, що містить шаблони звітів
|=======================================================================

== Сценарії використання

Керування регламентом реєстру можна умовно поділити на три етапи:

- **Створення реєстру**

Розгортання системи відбувається на підставі завантаженого регламенту.

- **Внесення критичних змін**

Внесення критичних змін має супроводжуватись обов'язковим збільшенням версії в її другому розряді.
До критичних змін можна віднести будь-які зміни до моделі даних та бізнес-процесів.

- **Внесення незначних змін**

При внесенні навіть незначних змін, версія має бути збільшена у своєму третьому розряді. Незначними змінами вважаються ті, для внесення яких не вимагається перезапуск сервісів.

== Неперервна інтеграція та доставлення (CI/CD)

image:mdtuddm:ROOT:deployment-pipeline.svg[]

=== Процес Registry Regulation Pipeline

Кроки виконання процесу можна розділити на **службові** та **породжувальні**.

NOTE: _Всі **службові** кроки є обов'язковими для виконання. **Породжувальні** -- кроки, які відповідальні за розгортання/внесення змін до компонентів, можуть бути пропущенні, якщо змін вносити не треба._

==== Підготовчі кроки

[plantuml, preparation, svg]
----
@startuml
skinparam monochrome true

left to right direction

rectangle "Checkout" as checkout
rectangle "Валідація\n конфігураційних файлів" as validation
rectangle "Штатне вимкнення сервісів" as shutdown
rectangle "Створення\n резервної копії" as backup

checkout --> validation
validation --> shutdown
shutdown --> backup

@enduml
----

==== Кроки розгортання системи

[plantuml, deployment, svg]
----
@startuml
skinparam monochrome true

left to right direction


rectangle "Розгортання\n моделі даних" as createDatafactory
rectangle "Розгортання\n бізнес процесів" as createBpmn
rectangle "Створення\n правил" as createDmn
rectangle "Створення\n форм" as createForms
rectangle "Створення\n звітів" as createReports
rectangle "Запуск автотестів" as autotest

createDatafactory --> createBpmn
createBpmn --> createDmn
createDmn --> createForms
createForms --> createReports
createReports --> autotest
@enduml
----

==== Обробка помилок

[plantuml, error, svg]
----
@startuml

skinparam monochrome true

left to right direction


rectangle "Розгортання\n моделі даних" as stepExample
rectangle "..." as abstractStep
rectangle "Запуск автотестів" as autotest
rectangle "Відновлення стану\n з резервної копії" as rollback


stepExample -[dashed]-> rollback: помилка виконання
abstractStep -[dashed]-> rollback: помилка виконання
autotest -[dashed]-> rollback: тести не пройшли
@enduml
----

===== Валідація конфігураційних файлів
Перевірка відповідності завантаженого регламенту до схем та правил. +
_Наприклад, відповідність зміни версії до типу внесених змін_.

===== Розгортання моделі даних
Оскільки розгортання моделі даних є складним процесом, то його створення винесено в окремий pipeline.
//TODO: після перенесення документації по datafactory-pipeline додати посилання на нього

===== Автоматизовані тести

Автоматизовані тести призначені для перевірки успішного старту всіх компонентів.






