= Platform administrator tools
include::platform:ROOT:partial$templates/document-attributes/default-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== Introduction

A Platform Administrator should master administrative tools for maintaining and monitoring the cluster's performance where the Platform is deployed.

TIP: For more details about the duties of the Platform Administrator, please refer to the page xref:admin:admin-study/admin-profile.adoc[].

== Setting up a local environment

We recommend configuring your local environment to make working with the Platform more convenient. Install the following tools on your machine:

include::registry-develop:partial$snippets/study/local-environment-setup-en.adoc[]

== Development tools: working environment

include::registry-develop:partial$snippets/study/platform-tools-en.adoc[]

The Platform Administrator should be able to use the tools of the xref:admin:registry-management/control-plane-quick-links.adoc#platform-admin-zone[Platform's administrative zone] and xref:admin:registry-management/control-plane-quick-links.adoc#platform-operational-zone[Platform's operational zone].

We also recommend familiarizing yourself with the tools of the administrative and operational zones of the registry, as Platform Administrators sometimes participate in registry processes.

//TODO: Note: Some parts (like "include::" and "xref:") are kept unchanged because they seem to be part of the AsciiDoc syntax, and translating them might break their functionality.