= Схема бази даних process_history

[plantuml, process_history-schema, svg]
----
@startuml
hide circle
skinparam linetype ortho
skinparam monochrome true

entity "**bpm_history_process**" {
  + ""process_instance_id"": //text [PK]//
  --
  ""super_process_instance_id"": //text //
  *""process_definition_id"": //text //
  *""process_definition_key"": //text //
  ""process_definition_name"": //text //
  ""business_key"": //text //
  *""start_time"": //timestamp without time zone //
  ""end_time"": //timestamp without time zone //
  ""start_user_id"": //text //
  *""state"": //text //
  ""excerpt_id"": //text //
  ""completion_result"": //text //
}

entity "**bpm_history_task**" {
  + ""activity_instance_id"": //text [PK]//
  --
  *""task_definition_key"": //text //
  ""task_definition_name"": //text //
  *""process_instance_id"": //text //
  *""process_definition_id"": //text //
  *""process_definition_key"": //text //
  ""process_definition_name"": //text //
  *""root_process_instance_id"": //text //
  *""start_time"": //timestamp without time zone //
  ""end_time"": //timestamp without time zone //
  ""assignee"": //text //
}
@enduml
----
.Умовні позначення
[%collapsible]
====
include::partial$architecture-workspace/documentation-templates/component-design-template/db-schema-legend.adoc[]
====

Відношення/зв'язок між таблицями не встановлено навмисно, оскільки в результаті денормалізації вони містять весь необхідний набір атрибутів для обслуговування історичних запитів та наповнюються даними незалежно одна від одної. 

== bpm_history_process
Історичні дані бізнес-процесів

[options="header",cols="a"]
|======
|Ім'я колонки +
Опис
| `*process_instance_id* _text_ *(PK)*` + 
Ідентифікатор екземпляру бізнес-процесу.  
| `super_process_instance_id _text_` + 
Ідентифікатор батьківського екземпляру бізнес-процесу. 
| `*process_definition_id* _text_` + 
Ідентифікатор поточної версії бізнес-процесу. 
| `*process_definition_key* _text_` + 
Унікальний ідентифікатор для всіх версій бізнес-процесу
| `process_definition_name _text_` + 
Назва бізнес-процесу
| `business_key _text_` + 
Специфічний для домену ідентифікатор екземпляра процесу 
| `*start_time* _timestamp without time zone_` + 
Час початку бізнес-процесу
| `end_time _timestamp without time zone_` + 
Час завершення бізнес-процесу 
| `start_user_id _text_` + 
Ідентифікатор користувача що почав бізнес-процес
| `*state* _text_` + 
Стан бізнес-процесу 

* ACTIVE
* COMPLETED
| `excerpt_id _text_` + 
Ідентифікатор витягу для бізнес-процесів що формують витяги 
| `completion_result _text_` + 
Текстове повідомлення з інформацією про результат виконання бізнес-процесу  

|======

== bpm_history_task
Історичні дані задач

[options="header",cols="a"]
|======
|Ім'я колонки +
Опис
| `*activity_instance_id* _text_ *(PK)*` + 
Ідентифікатор рядка 
| `*task_definition_key* _text_` + 
Унікальний ідентифікатор задачі
| `task_definition_name _text_` + 
Ім'я задачі 
| `*process_instance_id* _text_` + 
Ідентифікатор екземпляру бізнес-процесу якому належить задача 
| `*process_definition_id* _text_` + 
Ідентифікатор поточної версії бізнес-процесу
| `*process_definition_key* _text_` + 
Унікальний ідентифікатор для всіх версій бізнес-процесу 
| `process_definition_name _text_` + 
Назва бізнес-процесу 
| `*root_process_instance_id* _text_` + 
Ідентифікатор кореневого екземпляру бізнес-процесу 
| `*start_time* _timestamp without time zone_` + 
Час початку задачі
| `end_time _timestamp without time zone_` + 
Час завершення задачі 
| `assignee _text_` + 
Ідентифікатор користувача якому була призначена задача

|======
