= Структура компонента

== Взаємодія з сервісами платформи

image::architecture/registry/operational/bpms/services/bpms/business-process-management.svg[]

.Критичні залежності:
* *База даних Postgres* - впливає на весь функціонал веб-сервісу.

.Не критичні:
* *КЕП сервіс (dso)* - вливає тільки на один сценарій: Виконання системного підпису даних
* *Ceph сховище* - має вплив тільки на сценарії, в яких присутня взаємодія з сховищем.

== Модульна / структурна діаграма

image::architecture/registry/operational/bpms/services/bpms/microservice-internals.svg[]

- Camunda authorization + Spring Security + Keycloak JWT - для авторизації використовується механізм авторизації Camunda у зв'язку з Spring Security та Keycloak JWT
- BPMS Client over Camunda REST API + Spring Web - Web доступ до ресурсів Camunda через Feign клієнт
- BPMS Client over Custom Jersey controllers - Web доступ до інших ресурсів компоненти через Feign клієнт (кастомні контроллери які зареєстровані у Jersey контексті)
- Camunda core + Postgres - ядро Camunda з використанням бази даних Postgres
- Extensions:
* Core Extensions - розширення ядра Camunda
* Custom Delegates - делегати системи які адресують виконнання типових задач в бізнес-процесах
* Custom Connector Delegates - делегати системи які адресують виконання межсервісних інтеграцій (з дата-фабрикою, КЕП-сервісом тощо)
* Custom task/execution listeners - компоненти системи які адресують виконання типових задач у залежності від події
* Dso Feign Client - Feign клієнт для інтеграції з КЕП-сервісом
* Ceph S3 Client - клієнт для взаємодії зі сховищем Ceph
- Зовнішні залежності
* Spring Cloud Sleuth - розподілений трейсинг
* Spring Cloud Kubernetes - можливість конфігурувати сервіс через Config Map
* Spring Boot Actuator - моніторинг
* SLF4J/Log4J - логування

[NOTE]
Для більш поглибленого знайомства зі стеком технологій ласкаво просимо xref:bpms:technologies.adoc[тут]
