= Сервіс виконання бізнес-процесів

== Загальний опис

Бекенд-сервіс для виконання `bpmn` бізнес-процесів на базі движку Camunda, та надання доступу до таких ресурсів Camunda як: бізнес-процеси(process-definition), екземпляри бізнес-процесів (process-instance), задачі користувача(task) та історичні дані (history).

.Сервіс надає наступний функціонал:
- Доступ до списку бізнес-процесів, їх старт та виконання (з урахуванням ролей та прав доступу)
- Доступ до списку екземлярів бізнес-процесів та їх змінних
- Доступ до задач користувача та їх виконання
- Надавання доступу до виконнання типових розширеннь в бізнес-процесах (delegates, listeners тощо)

=== Загальні принципи

- Авторизація прав доступу з урахуванням ролей користувача та можливість налаштовувати авторизацію як частину регламенту
- Захищеність даних користувача, їх повна відсутність в базі даних Camunda та відсутність доступу до даних через Camunda API (читання та запис даних користувача відбуваєтся у захищеному сховищі *Ceph* через делегати та/або лісенери тільки в рамках бізнес-процесу)

.Системні ролі користувачів
* *Чиновник*
* *Людина*

== Компонента в системі

- Приклади swagger API: **у роботі**
- Jenkins: https://jenkins-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/job/bpms/[BPMS]


