= Використання екстерналізованих JavaScript-функцій при моделюванні UI-форм.

== Загальний опис

При моделюванні форм для задач часто виникає необхідність використовувати одні й ті самі Javascript функції які доводиться дублювати. Це стосується як функцій актуальних для будь-якого реєстру, так і тих які мають сенс перевикористовувати саме у рамках конкретного регламенту або навіть бізнес процесу.

Для обробки всіх цих сценаріїв пропонується використовувати збереження окремих javascript файлів *на рівні регламенту*. Ці файли доступні через API у form-schema-provider та використовуються при виконанні задач.

=== Ролі користувачів

- Розробник регламенту

== Функціональні сценарії

* Перевикористання Javascript функцій, що повторюються у рамках Javascript вставок при моделюванні форм. Підтримуються такі параметри форм:
** Custom Default Value
** Calculated Value
** Custom Validation
** Advanced Conditions
** інші, включаючи специфічні для деяких компонентів (наприклад, Filter Query та Custom Filter на компоненті Select)

== Цільовий дизайн

=== Компоненти системи та їх призначення в рамках дизайну рішення

У даному розділі наведено перелік компонент системи, які задіяні або потребують змін/створення в рамках реалізації функціональних вимог згідно технічного дизайну рішення.

|===
|Компонент|Службова назва|Призначення / Суть змін

|_Регламент реєстру_
|*registry-regulations-publications*
|Додати папку form-scripts для зберігання екстерналізованих скриптів.

|_Пайплайн публікації регламенту_
|*registry-regulations-publication-pipeline*
|Додати обробку екстерналізованих скриптів - їх зберігання та оновлення у сервісі *form-provider* (аналогічно до форм).

|_Сервіс постачання форм_
|*form-provider*
|Для роботи форм тепер будуть потрібні екстерналізовані скрипти. На сервісі form-provider треба додати можливість зберігати та оновлювати скрипти окремо від форм. Також треба додати окремий ендпоінт GET formScriptList для того, щоб він віддавав усі скрепти разом у форматі String.

|_Сервіс управління регламентом_
|*registry-regulation-management*
|Для правильної роботи з попереднім переглядом форми на *admin-portal* екстерналізовані скрипти повинні буди підключені до форми. Тому окрім *form-provider* зміни необхідні також і у сервісі управління регламентом. У рамках цих змін треба додати ще один ендпоінт для кандидат та майстер версій який буде зчитувати файли скриптів та віддавати їх у форматі String.

|_Сервіс валідації даних UI-форм_
|*form-submission-validation*
|Для правильної валідації введених даних необхідно зробити ті самі обчислення, що і на кабінетах. Тому сервіс валідації повинен теж враховувати екстерналізовані скрипти.

|_Кабінет адміністратора реєстру_
|*admin-portal*
|Змінити компонент форми так щоб він приймав довільні скрипти у вигляді текста та виконував усі Javascript обчислення з урахуванням цих скриптів.

|_Кабінет посадової особи_
|*officer-portal*
|Додати обробку даних скриптів та передати їх у компонент форми у вигляді тексту)

|_Кабінет громадянина_
|*citizen-portal*
|Додати обробку даних скриптів та передати їх у компонент форми у вигляді тексту)

|===

=== Регламент реєстру

Додати папку *form-scripts* у герріт регламента для зберігання скриптів:

.Структура регламенту реєстру
[plantuml, registry-config-regulation-structure, svg]
----
include::partial$architecture-workspace/platform-evolution/form-scripts/form-scripts-structure.puml[]
----

=== Пайплайн публікації регламенту

Необхідно додати у *registry-regulations-publications* файл `UploadFormScripts.groovy` у `/platform/pipelines/stages/impl/lowcode`. Реалізація цього скрипта буде подібна до `UploadFormChanges.groovy` - скрипта по зберіганню форм.

=== Портали та сервіс валідації

Портали будуть так чи інакше отримувати екстерналізовані скрити у форматі `String` та передавати у компонент форми. Компонент форми до будь-якого Javascript атрибута компонентів форм буде додавати текст скриптів. Таким чином усі функції та константи будуть доступні при обчисленні Javascript атрибутів. Це стосується officer-portal, citizen-portal, admin-portal та form-submission-validation.

.Порядок виконання Javascript атрибута
[plantuml, registry-config-regulation-attribute, svg]
----
include::partial$architecture-workspace/platform-evolution/form-scripts/form-scripts-attribute.puml[]
----

=== Сервіс постачання форм

==== Додати ендпоінти:

.form-provider нові API
[%collapsible]
====
swagger::{attachmentsdir}/architecture-workspace/platform-evolution/form-scripts/form-provider-swagger.yml[]
====

=== Сервіс управління регламентом

==== Додати ендпоінт:

.registry-regulation нові API
[%collapsible]
====
swagger::{attachmentsdir}/architecture-workspace/platform-evolution/form-scripts/registry-regulation-swagger.yml[]
====

== План розробки
=== Технічні експертизи
- FE (зміни у порталах)
- BE (зміни в сервісах)
- DevOps (зміни у пайплайні публікації)

=== План

- Додати ендпоінт до сервіса *registry-regulation-management* для отримання скриптів
- Додати ендпоінти до сервіса *form-provider* для збереження, зміни та отримання скриптів
- Оновити компонент форми
- Запросити екстреналізовані скрипти на admin-portal та передати у компонент форми
- Обробити параметр екстреналізованих скриптів на citizen та officer portal та передати у компонент форми
- Додати зміни у пайплайн публікації
