= Структура регламенту реєстру
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

Розгортання системи відбувається на підставі одного або декількох регламентів.

Адміністратор формує та розгортає регламент реєстру, що передбачає внесення змін до набору сутностей -- елементів регламенту.

Розгортання регламенту реєстру автоматизовано інструментами CI/CD. За розгортання регламенту відповідає Jenkins-пайплайн `*MASTER-Build-registry-regulations*` та пов'язані пайплайни.

Каталог регламенту реєстру має чітко визначену структуру директорій. Нижче показано схему типового регламенту.

._Структура типового регламенту реєстру_
[%collapsible]
====
[plantuml]
----
@startsalt
{
{T
+ <&folder> registry-regulations

++ <&folder> bp-auth
+++ <&file> role.yml
+++ ...

++ <&folder> bp-grouping
+++ <&file> bp-grouping.yaml

++ <&folder> bp-trembita
+++ <&file> config.yml
+++ ...

++ <&folder> bpmn
+++ <&file> process.bpmn
+++ ...

++ <&folder>data-model
+++ <&folder> data-load
++++ <&file> dict.csv
++++ ...
+++ <&file> model.xml
+++ ...

++ <&folder> dmn
+++ <&file> rule.dmn

++ <&folder> excerpts
+++ <&file> index.html.ftl
+++ ...

++ <&folder> excerpts-csv
+++ <&file> excerpt.csv
+++ ...
++ <&folder> excerpts-docx
+++ <&file> excerpt.docx
+++ ...

++ <&folder> forms
+++ <&file> form.json
+++ ...

++ <&folder> global-vars
+++ <&file> global-vars.yml

++ <&folder> mock-integrations
+++ <&file> mock-1.json
+++ <&file> mock-2.json
+++ ...

++ <&folder> notifications
+++ <&folder> diia
++++ <&folder> notification-template
+++++ <&file> notification.diia
+++++ <&file> notification.yml
++++ <&folder> channel-confirmation
+++++ <&file> notification.diia
+++++ <&file> notification.yml
+++ <&folder> email
++++ <&folder> notification-template
+++++ <&file> notification.ftlh
+++++ <&file> notification.yml
++++ <&folder> channel-confirmation
+++++ <&file> notification.ftlh
+++++ <&file> notification.yml
+++ <&folder> inbox
++++ <&file> notification.ftl
++++ <&file> notification.yml

++ <&folder> reports
+++ <&file> report.json
+++ ...

++ <&folder> roles
+++ <&file> role.yml
+++ ...

++ <&folder> settings
+++ <&file> settings.yml

+ <&file> settings.yaml

}
}
@endsalt
----
====

._Пояснення до структури регламенту_
[%collapsible]
====

.Пояснення до структури регламенту
[width="100%",cols="19%,19%,62%",options="header"]
|===

| Регламент
| Директорія/Файл
| Опис

| _registry-regulations_
|
| Верхньорівнева тека, що містить вкладені директорії із сутностями регламенту.

|
| _bp-auth_
| Тека, що містить `YAML`-файли доступу до бізнес-процесів для реалмів `citizen` (отримувач послуг), `officer` (посадова особа/надавач послуг) та `external-system` (зовнішні системи та реєстри).

|
| _bp-grouping_
| Тека, що містить конфігураційний файл _bp-grouping.yaml_. Налаштування цього файлу призначені для групування бізнес-процесів реєстру.

|
| _bp-trembita_
| Тека, що містить конфігураційні файли для налаштування взаємодії із зовнішніми сервісами та системами через SOAP-інтерфейси ШБО «Трембіта», а також через REST.

|
| _bpmn_
| Тека, що містить схеми бізнес-процесів у форматі ._bpmn_ (різновид XML)

|
| _data-model_
| Тека, що містить схеми для розгортання БД та API-представлень, а також CSV-довідники для подальшого наповнення даними таблиць-довідників.

|
| _dmn_
| Тека, що містить змодельовані перевірчі правила (таблиці прийняття рішень) у форматі ._dmn_ (різновид XML)

|
| _excerpts_
| Тека, що містить шаблони PDF-витягів реєстру

|
| _excerpts-csv_
| Тека, що містить шаблони витягів-звітів у форматі CSV

|
| _excerpts-docx_
| Тека, що містить шаблони витягів (проєктів наказів) у форматі DOCX

|
| _forms_
| Тека, що містить змодельовані користувацькі форми введення даних у форматі JSON

|
| _global-vars_
| Тека, що містить глобальні змінні бізнес-процесів реєстру

|
| _mock-integrations_
| Тека, що містить змодельовані шаблони емуляцій зовнішніх інтеграцій у форматі JSON.

|
| _notifications_
| тека, що містить шаблони для відправлення повідомлень через канали зв'язку `diia`, `email`, та `inbox`

|
| _reports_
| Тека, що містить сформовану аналітичну звітність (запити та дашборди) у JSON-форматі

|
| _roles_
| Тека, що містить конфігураційні файли для налаштування ролей у реєстрі (officer.yml -- для призначення посадових осіб різних рангів, `citizen.yml` -- для визначення отримувачів послуг)

|
| _settings_
| Тека, що містить загальні налаштування регламенту (повна та скорочена назви реєстру тощо)

|
| _settings.yaml_
| Конфігураційний файл, що містить системні налаштування реєстру та деяких сервісів

|===
====

TIP: Детальніше про регламент та особливості розгортання див. на сторінці xref:arch:architecture/registry/administrative/regulation-management/registry-regulation/registry-regulation.adoc[].








