= Як власнику реєстру виставити SOAP API: Ваш путівник
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

Цей документ служить керівництвом для реалізації вхідної інтеграції за допомогою SOAP API через інтеграційний безпековий шлюз "Трембіта", призначений для ефективного обміну даними між вашим реєстром, який є власником даних, і зовнішніми системами.

[context]
== Контекст

Платформа реєстрів пропонує два основних протоколи інтеграції: SOAP та REST. В Україні, для забезпечення безпеки даних, SOAP-інтеграція здійснюється виключно через інтеграційний безпековий шлюз "Трембіта", що стає основним способом взаємодії. Ця методика вимагає від учасників входження до спеціалізованого середовища — СЕВДЕІР "Трембіта", забезпечуючи високий рівень безпеки обміну даними.

[NOTE]
====
ШБО "Трембіта" не є частиною самої Платформи, але відіграє ключову роль у забезпеченні безпеки даних.
====

Юридично, для інтеграції з "Трембітою" необхідно бути учасником СЕВДЕІР "Трембіта", що передбачає використання спеціального програмного забезпечення — інтеграційного шлюзу безпечного обміну (ШБО). Кожен учасник має свій екземпляр ШБО "Трембіта", зазвичай розміщений поруч з інфраструктурою вашого продукту, але на окремій віртуальній машині.

Управління ШБО "Трембіта" здійснюється призначеним адміністратором, незалежно від технічних адміністраторів Платформи та реєстрів, що вимагає окремої угоди про доступ до інтерфейсу ШБО.

Розглянемо більш детально подальші кроки для налаштування вхідної інтеграції через SOAP API за допомогою ШБО "Трембіта".

== Реєстрація підсистеми нового реєстру на ШБО "Трембіта" для Платформи

Виконайте необхідні кроки для приєднання до СЕВДЕІР "Трембіта", згідно з інструкцією xref:registry-admin/external-integration/registration-subsystem-trembita/registration-subsystem-trembita.adoc[].

== Налаштування взаємодії через ШБО "Трембіта"

. Отримайте доступ до інтерфейсу ШБО "Трембіта". Для цього зверніться до адміністратора інфраструктури, де розгорнуто ШБО. Він має видати вам IP-адресу та порт, а також облікові дані (логін та пароль) для автентифікації.

. Запитайте IP-адресу сервера ШБО "Трембіта" для забезпечення whitelisting між сервісами реєстру та ШБО. Додайте отриману IP-адресу до списку дозволених. Наприклад, `172.16.0.0`.
+
[NOTE]
====
* *Налаштування whitelisting*: для впровадження безпечного з'єднання між вашим реєстром та екземпляром ШБО "Трембіта", необхідно налаштувати *whitelisting*. Це можна зробити на рівні реєстру в адміністративній панелі *Control Plane*. За деталями зверніться до сторінки xref:admin:registry-management/control-plane-soap-api-access-trembita.adoc[].

* *Рівні налаштувань Платформи*: Платформа реєстрів пропонує два основні рівні налаштувань:

** *Конфігурація реєстру*: Централізовано керується через адміністративну панель *Control Plane*. Перегляньте розділ xref:admin:registry-management/overview.adoc[Control Plane] для отримання деталей.

** *Конфігурація регламенту реєстру*: Виконується через налаштування цифрового регламенту (`registry-regulations`) в Адміністративному порталі або напряму через сервіс Gerrit, в якому фізично зберігається регламент. Більше деталей про згадані сервіси ви можете отримати на сторінках xref:registry-admin/admin-portal/overview.adoc[Адміністративний портал] та xref:registry-admin/regulations-deploy/registry-admin-deploy-regulation.adoc[Gerrit].

Ми рекомендуємо спочатку провести всі необхідні налаштування на рівні *Control Plane*, дочекатись набуття ними чинності, а потім переходити до налаштувань регламенту.
====

. Для того, щоб інші реєстри на Платформі або зовнішні системи могли звернутися до бізнес-процесів вашого реєстру через ШБО "Трембіта", виконайте кроки, описані на сторінці xref:registry-admin/external-integration/api-publish/rest-soap-api-expose.adoc[].

== Реєстрація API-ендпоінтів у ШБО "Трембіта": активація та виклик бізнес-процесів

Далі ви маєте увійти до інтерфейсу ШБО "Трембіта" та додати бажані точки інтеграції із бізнес-процес-процесами. Основні кроки включатимуть:

* Додавання WSDL-файлу
* Налаштування прав доступу до WSDL-файлу
* Додавання ендпоінтів (ACL-об'єктів) для інтеграційної взаємодії з бізнес-процесами

TIP: Дізнайтеся більше про налаштування ШБО "Трембіта" на сторінці xref:registry-admin/external-integration/api-publish/trembita-bp-invoking.adoc[].

== Реєстрація API-ендпоінтів у ШБО "Трембіта": активація та виклик API-представлень

Далі ви маєте увійти до інтерфейсу ШБО "Трембіта" та додати бажані точки інтеграції з API фабрики даних -- API-представленнями. Основні кроки включатимуть:

* Додавання WSDL-файлу
* Налаштування прав доступу до WSDL-файлу
* Додавання ендпоінтів (ACL-об'єктів) для інтеграційної взаємодії з API-представленнями (search conditions) реєстру, які розгорнути на базі змодельованої структури даних.

TIP: Дізнайтеся більше про налаштування ШБО "Трембіта" на сторінці xref:registry-admin/external-integration/api-publish/trembita-data-invoking.adoc[].

