@startuml
actor "Розробник регламенту" as dev
participant "Сховище регламенту" as gerrit
participant "Пайплайн публікації" as pipe
participant "Keycloak" as keycloak
participant "Camunda Auth CLI" as cli
participant "Сервіс виконання бізнес-процесів" as bpms

skinparam responseMessageBelowArrow true

title Налаштування прав доступу до бізнес-процесів регламенту

dev -> gerrit: Зміни до карти\nдоступу до\nбізнес-процесів
activate gerrit
gerrit -> gerrit: Процес рев'ю змін
gerrit <- pipe: Відслідковує нові зміни
activate pipe
gerrit -> dev: 200, OK
deactivate gerrit
pipe -> pipe: Інші кроки\nпайплайну публікацій
pipe -> pipe: BPMS_URL = http://bpms:8080 (за замовчуванням)
pipe -> keycloak: Отримати токен\nсервіс аккаунта\njenkins-keycloak-client
activate keycloak
keycloak -> pipe: BPMS_TOKEN
deactivate keycloak
pipe -> cli: Налаштувати права доступу\nBPMS_URL\nBPMS_TOKEN\nAUTH_FILES=\nbp-auth/officer.yml,bp-auth/citizen.yml
activate cli
cli -> bpms: Видалити всі\nавторизаційні правила
cli -> bpms: Створити авторизаційні\nправила згідно файлів AUTH_FILES
cli -> pipe : ОК
deactivate cli

@enduml