@startuml
actor "Regulations developer" as dev
participant "Regulations storage" as gerrit
participant "Publication pipeline" as pipe
entity "Keycloak CR API" as cr
participant "Keycloak" as keycloak

skinparam responseMessageBelowArrow true

title Configuring Regulations roles

dev -> gerrit: Changes to regulations \nroles files
activate gerrit
gerrit -> gerrit: Changes review process
gerrit -> pipe: Monitors new changes
activate pipe
gerrit -> dev: 200, OK
deactivate gerrit
pipe -> pipe: Other steps of the \npublication pipeline
loop For roles/citizen.yml and roles/officer.yml files
pipe -> cr: Create\nKeyclokRealmRoleBatch CR
activate cr
cr -> keycloak: Roles created by\nKeycloak Operator
activate keycloak
deactivate keycloak
cr -> pipe
deactivate cr
end

deactivate pipe

@enduml