= Подієвий підпроцес

_Подієвий підпроцес_ (*Event Subporcess*) -- це підпроцес, що розміщується всередині іншого процесу. Він починає виконуватися, якщо ініціюється його початкова подія. Подієвий підпроцес може переривати батьківський підпроцес або виконуватися паралельно з ним. Він може виконуватися один або декілька разів, або не виконуватися взагалі.

////
Ініціюється власною стартовою подією та не має вхідних та вихідних потоків операцій. Це є його основною відмінністю від звичайного підпроцесу, який ініціюється потоком операцій батьківського підпроцесу. Повинен містити оча б одну стартову подію.
////

Підпроцес, який може виконуватися один чи кілька разів, або не виконуватися взагалі.
Ініціюється власною стартовою подією та не має вхідних та вихідних потоків операцій. Це є його основною відмінністю від звичайного підпроцесу, який ініціюється потоком операцій батьківського підпроцесу. Повинен містити оча б ону стартову подію.
Підпроцес, який може виконуватися один чи кілька разів, або не виконуватися взагалі.
