= Configuring user authentication

This section describes the process of configuring user authentication for two key user groups: *officers* (_service providers_) and *citizens* (_service recipients_). All configurations are performed through the *Control Plane* console, which provides a convenient unified interface for basic registry configurations.

The platform allows administrators to configure the authentication type for the Officer portal by using their own IIT widget for authentication with the Qualified Electronic Signature (_QES_) or by integrating with an external provider such as ID.GOV.UA (_ICEI_). As a result, officials of the registry will be able to use one of two authentication types when accessing the Cabinet: either QES or ID.GOV.UA.

Щодо отримувачів послуг, система передбачає можливість налаштування перевірки наявності активного запису в ЄДР для бізнес-користувачів. Такий механізм забезпечує зв'язок між КЕП користувача та їх юридичною особою чи фізичною особою-підприємцем, зареєстрованими в Єдиному державному реєстрі (ЄДР). Він відіграє важливу роль у забезпеченні відповідності даних користувача та підтвердження їх особистості, що є важливим аспектом безпеки та надійності системи.


Additionally, the platform provides the ability to configure self-registration for officers. This simplifies the user registration process as it does not require administrator involvement. With this approach, officers can register themselves, optimizing the work of administrators and improving the overall user experience.

== Section overview

[%collapsible]

.*Officers*
====
* xref:registry-admin/cp-auth-setup/cp-auth-setup-officers.adoc[]
* xref:registry-admin/cp-auth-setup/cp-officer-self-registration.adoc[]
====

////
[%collapsible]
.+++<b style="font-weight: 700">Отримувачі послуг </b>+++
====
* xref:registry-admin/cp-auth-setup/cp-auth-setup-citizens.adoc[]
====
////