openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
paths:
  /api/settings/me/channels/{channel}/verify:
    post:
      tags:
        - settings-controller
      summary: створити ресурс
      description: Використовується для створення ресурсу.
      operationId: verifyChannelAddress
      parameters:
        - name: channel
          in: path
          required: true
          schema:
            type: string
            enum:
              - email
              - diia
              - inbox
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerificationInputDto'
        required: true
      responses:
        '200':
          description: OK з результатом
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/VerificationCodeExpirationDto'
        '400':
          description: Некоректні вхідні дані (наприклад, неправильний тип поля)
        '401':
          description: Помилка аутентифікації (відсутній токен або цифровий підпис)
        '422':
          description: Помилка валідації, запит містить дані, що не відповідають правилам вказаним в домені
        '500':
          description: Внутрішня помилка сервера
  /api/settings/me/channels/{channel}/deactivate:
    post:
      tags:
        - settings-controller
      summary: створити ресурс
      description: Використовується для створення ресурсу.
      operationId: deactivateChannel
      parameters:
        - name: channel
          in: path
          required: true
          schema:
            type: string
            enum:
              - email
              - diia
              - inbox
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SettingsDeactivateChannelInputDto'
        required: true
      responses:
        '200':
          description: OK з результатом
        '400':
          description: Некоректні вхідні дані (наприклад, неправильний тип поля)
        '401':
          description: Помилка аутентифікації (відсутній токен або цифровий підпис)
        '422':
          description: Помилка валідації, запит містить дані, що не відповідають правилам вказаним в домені
        '500':
          description: Внутрішня помилка сервера
  /api/settings/me/channels/{channel}/activate:
    post:
      tags:
        - settings-controller
      summary: створити ресурс
      description: Використовується для створення ресурсу.
      operationId: activateChannel
      parameters:
        - name: channel
          in: path
          required: true
          schema:
            type: string
            enum:
              - email
              - diia
              - inbox
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivateChannelInputDto'
        required: true
      responses:
        '200':
          description: OK з результатом
        '400':
          description: Некоректні вхідні дані (наприклад, неправильний тип поля)
        '401':
          description: Помилка аутентифікації (відсутній токен або цифровий підпис)
        '422':
          description: Помилка валідації, запит містить дані, що не відповідають правилам вказаним в домені
        '500':
          description: Внутрішня помилка сервера
  /api/settings/me/channels/email/validate:
    post:
      tags:
        - settings-controller
      summary: створити ресурс
      description: Використовується для створення ресурсу.
      operationId: validateEmailAddress
      parameters:
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SettingsEmailInputDto'
        required: true
      responses:
        '200':
          description: OK з результатом
        '400':
          description: Некоректні вхідні дані (наприклад, неправильний тип поля)
        '401':
          description: Помилка аутентифікації (відсутній токен або цифровий підпис)
        '422':
          description: Помилка валідації, запит містить дані, що не відповідають правилам вказаним в домені
        '500':
          description: Внутрішня помилка сервера
  /api/settings/{userId}:
    get:
      tags:
        - settings-controller
      summary: отримати ресурс по ідентифікатору
      description: Використовується для отримання об’єктів. Не змінює стан ресурсу
      operationId: findUserSettingsById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK з результатом
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SettingsReadDto'
        '400':
          description: Некоректні вхідні дані (наприклад, неправильний тип поля)
        '401':
          description: Помилка аутентифікації (відсутній токен або цифровий підпис)
        '500':
          description: Внутрішня помилка сервера
  /api/settings/me:
    get:
      tags:
        - settings-controller
      summary: отримати ресурс по ідентифікатору
      description: Використовується для отримання об’єктів. Не змінює стан ресурсу
      operationId: findUserSettingsFromToken
      parameters:
        - name: X-Access-Token
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK з результатом
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SettingsReadDto'
        '400':
          description: Некоректні вхідні дані (наприклад, неправильний тип поля)
        '401':
          description: Помилка аутентифікації (відсутній токен або цифровий підпис)
        '500':
          description: Внутрішня помилка сервера
components:
  schemas:
    VerificationInputDto:
      required:
        - address
      type: object
      properties:
        address:
          type: string
    VerificationCodeExpirationDto:
      type: object
      properties:
        verificationCodeExpirationSec:
          type: integer
          format: int32
    SettingsDeactivateChannelInputDto:
      required:
        - deactivationReason
      type: object
      properties:
        address:
          type: string
        deactivationReason:
          type: string
    ActivateChannelInputDto:
      required:
        - address
        - verificationCode
      type: object
      properties:
        address:
          type: string
        verificationCode:
          type: string
    SettingsEmailInputDto:
      required:
        - address
      type: object
      properties:
        address:
          type: string
    ChannelReadDto:
      type: object
      properties:
        channel:
          type: string
          enum:
            - email
            - diia
            - inbox
        activated:
          type: boolean
        address:
          type: string
        deactivationReason:
          type: string
    SettingsReadDto:
      type: object
      properties:
        settingsId:
          type: string
          format: uuid
        channels:
          type: array
          items:
            $ref: '#/components/schemas/ChannelReadDto'
