@startuml

actor "Розробник регламенту" as dev
participant "Сховище\nрегламенту" as gerrit
participant "Пайплайн\nпублікацій змін\nдо регламенту" as pipe
participant "Keycloak-operator" as keycloak_operator
participant "Keycloak" as keycloak
participant "OpenShift" as openshift

autonumber

dev -> gerrit : Оновлення файлу\n**trembita/consumers.yml**
note right of dev
name
description
subsystemCode
memberClass
memberCode
end note
pipe -> gerrit : Отримання\nзмін регламенту
note over pipe : Інші кроки з публікації змін
pipe -> keycloak_operator : Додавання\nнових ролей у CR\nKeycloakRealmRoleBatch\n**external-system-roles**
keycloak_operator -> keycloak : Створення нових ролей
note over of keycloak
Всі операції виконуються
у реалмі **external-system**
end note
loop для кожного нового зовнішнього клієнту
pipe -> keycloak_operator : Створення CR\nKeycloak Client
keycloak_operator -> keycloak_operator : Генерація паролю\nдля Keycloak CLient
keycloak_operator -> openshift : Створення Secret\nз паролем Keycloak Client
keycloak_operator -> keycloak : Створення Keycloak client\n(service-account)
note right of keycloak_operator
clientSecret = згенерований пароль
end note
keycloak_operator --> pipe: Посилання на Secret\nу статусі CR Keycloak Client
pipe -> openshift: Отримання\nOpenShift Secret\nза посиланням
openshift --> pipe: Secret з паролем\nKeycloak Client
end

@enduml