= Посадова інструкція для адміністратора реєстру

Обов'язки та вимоги до адміністратора реєстру передбачають обслуговування, підтримку та моніторинг реєстру і його компонентів, та включають:

Керування реєстрами: ::
* Використання централізованого адміністративного інтерфейсу Control Plane для керування реєстрами.

Призначення адміністраторів реєстру: ::
* Створення адміністраторів реєстру та надання їм прав доступу.

Управління користувачами та доступом: ::
* Використання Keycloak для управління ідентифікацією та доступом користувачів реєстру.

Резервне копіювання та відновлення: ::
* Налаштування резервного копіювання та аварійного відновлення ресурсів і бази даних реєстру за допомогою автоматизованих процесів у Jenkins.
* Досвід роботи з інструментами для резервного копіювання, зокрема Velero, та об'єктними сховищами, такими як Minio, для збереження бекапів.

Оновлення компонентів реєстру: ::
* Виконання оновлень компонентів реєстру.

Налаштування інтеграційних взаємодій: ::
* Налаштування доступу до реєстрів для інших реєстрів на платформі та зовнішніх систем.
* Налаштування взаємодії з реєстрами та зовнішніми системами через REST API.
* Налаштування взаємодії з реєстрами через ШБО "Трембіта" за SOAP-протоколом.

Робота з ключами цифрового підпису ::
* Налаштування ключів та сертифікатів цифрового підпису для реєстру (ЕЦП/КЕП).

Налаштування доменних імен (DNS): ::
* Налаштування доменних імен для порталів реєстру.

Налаштування обмежень доступу до компонентів реєстру: ::
* Обмеження доступу до реєстрових компонентів за допомогою CIDR.

Підтвердження запитів на внесення змін: ::
* Підтвердження або відхилення запитів на внесення змін до реєстру.

Налаштування автентифікації кінцевих користувачів: ::
* Встановлення та налаштування процесів автентифікації для кінцевих користувачів.

Робота з OpenShift-консоллю: ::
* Використання централізованого інтерфейсу OpenShift для моніторингу ресурсів реєстру.

Моніторинг та логування: ::
* Моніторинг та аналіз метрик системи за допомогою Grafana та Prometheus.
* Моніторинг логів з використанням Kibana або Openshift-консолі.
* Розуміння принципів моніторингу та трейсингу сервісів, використання Kiali та Jaeger.

Адміністрування бізнес-процесів: ::
* Використання Camunda BPM для моніторингу та відлагодження екземплярів виконання бізнес-процесів, описаних у BPMN-нотації.

Автоматизація: ::
* Знання Jenkins для моніторингу процесів безперервної інтеграції та розгортання (CI/CD).
* Навички налаштування та використання VCS git та Gerrit для інтеграції, версіонування та рецензування коду.
* Знання Nexus для моніторингу та управління артефактами.

Управління налаштуваннями та лімітами доступу до внутрішніх ресурсів: ::
* Конфігурування Kong API шлюзу, включаючи налаштування лімітів на кількість запитів від клієнта (Rate Limiting).

Управління секретами: ::
* Використання Hashicorp Vault для управління секретами.

Моніторинг API-ресурсів реєстру: ::
* Розуміння концептів REST API.
* Знання OpenAPI Specification (OAS).
* Використання Swagger для перегляду згенерованих API-точок доступу реєстру.

Робота з даними реєстру: ::
* Знання PostgreSQL. Робота з операційними та аналітичними даними реєстру за допомогою pgAdmin та подібних інструментів.

Налаштування поштового сервера: ::
* Налаштування сервера для обміну повідомленнями, зокрема Mailu.