@startuml
participant "Web Клієнт" as client  order 10
participant "Сервіс управління бізнес-процесами" as service  order 20
participant "Cервіс виконання бізнес-процесів" as bpms order 30
skinparam responseMessageBelowArrow true

title Отримання переліку ініційованих бізнес-процесів
  client -> service: Отримати перелік ініційованих бізнес-процесів
  activate service
  service -> bpms: Отримати перелік ініційованих бізнес-процесів
  activate bpms
    bpms -> service: Перелік ініційованих бізнес-процесів, 200 OK
  deactivate bpms
  service -> bpms: Отримати перелік задач \nдля ініційованих бізнес-процесів
  activate bpms
    bpms -> service: Перелік задач \nдля ініційованих бізнес-процесів, 200 OK
  deactivate bpms
  service -> service: Визначення статусу для кожного бізнес-процесу
  service -> client: Перелік ініційованих бізнес-процесів
  deactivate service
@enduml