@startuml
participant "Web Клієнт" as client  order 10
participant "Сервіс управління бізнес-процесами" as service  order 20
participant "Cервіс виконання бізнес-процесів" as bpms order 30
skinparam responseMessageBelowArrow true

title Отримати завершений бізнес-процес
    client -> service: Отримати завершений бізнес-процес за ідентифікатором
    activate service
    service -> bpms: Отримати завершений бізнес-процес за ідентифікатором
    activate bpms
      bpms -> service: Завершений бізнес-процес, 200 OK
    deactivate bpms
    service -> bpms: Отримати перелік історичних екземплярів змінних
    activate bpms
      bpms -> service: Перелік історичних екземплярів змінних, 200 OK
    deactivate bpms
    service -> service: Визначення статусу \nдля завершенного бізнес-процесу
    service -> client: Завершений бізнес-процес, 200 OK
    deactivate service
@enduml