@startuml
participant "Web Клієнт" as client  order 10
participant "Сервіс управління бізнес-процесами" as service  order 20
participant "Cервіс виконання бізнес-процесів" as bpms order 30
skinparam responseMessageBelowArrow true

title Отримання переліку доступних бізнес-процесів
  client -> service: Отримати перелік доступних бізнес-процесів
  activate service
  service -> bpms: Отримати перелік доступних бізнес-процесів
  activate bpms
    bpms -> service: Перелік доступних бізнес-процесів, 200 OK
  deactivate bpms
  service -> bpms: Отримати стартові форми доступних бізнес-процесів
  activate bpms
  service <- bpms: Cтартові форми доступних бізнес-процесів, 200 OK
  deactivate bpms
  service -> client: Перелік ініційованих бізнес-процесів
  deactivate service
@enduml