@startuml
participant "Web Клієнт" as client  order 10
participant "Сервіс управління бізнес-процесами" as service  order 20
participant "Cервіс виконання бізнес-процесів" as bpms order 30
skinparam responseMessageBelowArrow true

title Ініціювання бізнес-процесу
  client -> service: Ініціювати бізнес-процес за вказаним ідентифікатором
  activate service
  service -> bpms: Отримати бізнес-процес за вказаним ідентифікатором
  alt Бізнес-процес не знайдено
    bpms -> service: Бізнес-процес не знайдено 404
    service -> client: Бізнес-процес не знайдено 404
  end
  activate bpms
  bpms -> service: Бізнес-процес, 200 OK
  deactivate bpms
  service -> bpms: Ініціювати бізнес-процес
  activate bpms
  bpms -> service: Ініційований бізнес-процес, 200 OK
  deactivate bpms
  service -> client: Ініційований бізнес-процес
  deactivate service
@enduml