:toc-title: On this page:
:toc: auto
:toclevels: 5
:experimental:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Managing registry data model table structures
//= Управління структурами таблиць моделі даних реєстру

include::ROOT:partial$admonitions/language-en.adoc[]

include::admin-portal-data-model-problem-description.adoc[]

include::admin-portal-data-model-scenarious.adoc[]

== Out of scope
- Working with data types
//- Робота з типами даних
- Working with analytical representations
//- Робота з аналітичними представленнями
- Resolving conflicts using the administrative portal of the registry regulations management
//- Вирішення конфліктів з використанням адмінпорталу менеджменту регламенту реєстру

== Principles of working with changes in the database
//== Принципи роботи зі змінами в БД

=== Existing mechanism for working with changes in the database
//=== Існуючий механізм роботи зі змінами в БД

The existing mechanism for working with changes in the database is based on two principles:
//Існуючий механізм роботи зі змінами в БД базуєтсья на двух принципах:

- Creation of liquibase changeset
//- Cтворення liquibase changeset
- Saving liquibase changeset in git
//- Збереження liquibase changeset в git

image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-luqibase-current-flow.svg[]

=== Advanced mechanism for working with changes in the database
//=== Розширений механізм роботи зі змінами в БД
It is suggested to extend the existing mechanism for working with database changes by adding a DataModelSnapshot document to the git repository, which will reflect the state of the data model.
//Пропонується розширити існуючий механізм роботи зі змінами БД шляхом додавання DataModelSnapshot документу в git репозиторій, котрий буде відображати стан моделі даних.

image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-luqibase-extended-flow.svg[]

=== Basic concepts
//=== Основні концепції
- DataModelSnapshot model: JSON documents reflecting the state of the registry regulations data model.
//- DataModelSnapshot model - JSON документи, що відображають стан моделі даних регламенту реєстру
- Diff Document: The document showing the difference between the two states of the registry regulations data model.
//- Diff Document - документ, що відображає різницю між двома станами моделі даних регламенту реєстру
- History Document: The document reflecting the history of changes made to the master version or the candidate version of the registry regulations.
//- History Document - документ, що відображає історію змін мастер версії або версії- кандидату регламенту реєстру

=== DataModelSnapshot structure description
//=== Описання структури DataModelSnapshot
[NOTE]
The above data model was obtained as the result of the analysis of the existing state of lqiuibase changelogs (including the functionality analysis of the custom liquibase tags).
//Вищенаведена модель даних була отримана в результаті аналізу існуючого стану lqiuibase changelogs (включно з аналізом функціональності custom liquibase тегів)

[plantuml, db-tables-management-er, svg]
----
include::partial$architecture/registry/administrative/regulation-management/admin-portal/db-tables-management-er.puml[]
----


=== Description of the file structure in the file system
//=== Опис структури файлів на файловій системі

The DataModelSnapshot model has the following file structure in the file system:
//DataModelSnapshot model має наступну структуру файлів на файловій системі

image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-datamodel-filestructure.svg[]

- The list of tables is determined by the list of files in the file system.
//- Перелік таблиць визначається переліком файлів на файловій системі
- The name of the table file matches the name of the table and is `<table-name>.json`.
//- Ім'я файлу таблиць відповідає назві таблиці та має наступний вигляд: `<table-name>.json`
- The name of the role permission file corresponds to the name id role permission and is the following: `<role-id>.json`.
//- Ім'я файлу role permission відповідає назві id role permission та має наступний вигляд: `<role-id>.json`

==== Temporary file structure in the file system (first iteration)
//==== Тимчасова структура файлів на файловій системі (first iteration)

image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-datamodel-filestructure-simple.svg[]

=== Description of the DataModelSnapshot data format
//=== Опис DataModelSnapshot формату даних
The Json format is used as a technical tool for describing the data structure of DataModelSnapshot. As a description of the contract document, https://json-schema.org/ [JsonSchema] is used.
//В якості технічного інструменту опису структури даних DataModelSnapshot використовується Json формат. В якості опису контракту документу використовується https://json-schema.org/[JsonSchema]

xref:arch:architecture/registry/administrative/regulation-management/admin-portal/data-model/admin-portal-data-model-json-schema-description.adoc[DataModelSnapshotSchema]

include::domain-model-description.adoc[]
include::domain-attributes-description.adoc[]

include::admin-portal-data-model-principles.adoc[]

== Description of the technical solution
//== Опис технічного рішення

=== Container
image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-c4-container.svg[]

=== Admin portal API container
image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-c4-apiContainer.svg[]

=== CICD container
image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-c4-cicd-container.svg[]

== System component interaction scenario when editing the structure of the registry tables
//== Сценарій взаємодії компонентів системи під час редагування структури таблиць регламенту реєстру
[plantuml, db-tables-management-sequence, svg]
----
include::partial$architecture/registry/administrative/regulation-management/admin-portal/db-tables-management-sequence.puml[]
----

== General diagram of the system components interaction when editing the data model of the registry regulations
//== Загальна діаграма взаємодії компонентів системи під час редагування моделі даних регламенту реєстру

image::architecture/registry/administrative/regulation-management/admin-portal/data-model/tables-management-component-structure.svg[]
