== Problem description
//== Опис проблеми
The part of the process of creating/editing registry rules is to describe the registry data model. The current approach uses only configuration files to create a registry data model.
//Частиною процесу створення/редагування регламенту реєстру є опис моделі даних реєстру. Поточний підхід передбачає використання лише файлів конфігурації для створення моделі даних реєстру.
The user must use liquibase changelog data model description format, which is de facto a description of the database structure.
//Користувач повинен використовувати liquibase changelog формат опису моделі даних, що де-факто є описом структури БД.

The part of the web-based admin portal for editing the version of the registry regulations is editing the database structure.
It is necessary to develop a technical design of the subsystem for creating a registry data model.
//Частиною web-based адмін порталу редагування версії регламенту реєстру є редагування структури БД.
// Необхідно розробити технічний дизайн підсистеми створення моделі даних реєстру.

=== Key points of the problem
//=== Ключові пункти проблеми
- Simultaneous work of several users with one candidate version of the regulations.
//- Одночасна робота декількох користувачів з однією версією-кандидатом регламенту
- Preserving the mechanism for ensuring the existing life cycle of the version rules (gerrit, jenkins).
//- Збереження механізму забезпечення існуючого життєвого циклу регламенту версій (gerrit, jenkins)
- Preserving the technical tool for recreating the database structure (liquibase).
//- Збереження технічного інструменту відтворення структури БД (liquibase)
- Preserving the mechanism for changing the rules by changing the configuration files in git.
//- Збереження механізму зміни регламенту шляхом зміни конфігураційних файлів в git
- Synchronization between changes made from the admin portal and changes made through Gerrit.
//- Забезпечення синхронізації між змінами з адмін порталу і змінами внесеними через Gerrit
- Creation of GUI based mechanism for changing registry regulations.
//- Створення GUI based механізму зміни регламенту реєстру