== General implementation principles
//== Загальні принципи реалізації
- The mechanism allows CRUD operations with the objects of the domain model.
//- Механізм дозволяє проводити CRUD операції відносно об'єктів доменної моделі
- Simultaneous editing of the registry regulations both using the admin portal and by changing the configuration files in the regulations repository.
//- Одночасне редагування регламенту реєстру як з використанням адмін порталу, так і шляхом зміни конфігураційних файлів в репозиторії регламенту
- The status of the database structure and metadata is fully reflected in the DataModelSnapshot documents.
//- Стан структури БД і метаданих повністю відображений DataModelSnapshot документами
- The structure of the DataModelSnapshot json documents is described using JSONSchema.
//- Структура DataModelSnapshot json документів описана за допомогою JSONSchema
- The DataModelSnapshot documents (with JSONSchema) shall be used as a data exchange structure at the RestAPI level between the Front-End application and Backend services.
//- DataModelSnapshot документи (з JSONSchema) мають бути використані як структура обміну даними на рівні RestAPI між Front-End додатком та Backend сервісами
- Conflict resolution when editing registry regulations using the administrative portal is required only at the level of the DataModelSnapshot documents.
//- Вирішення конфліктів при редагуванні регламенту реєстру з використанням адмінпорталу необхідний лише на рівні DataModelSnapshot документів
- Maintaining consistent DataModelSnapshot model and liquibase changelog.
//- Підтримання консистентними DataModelSnapshot моделі та liquibase changelog
- DataModelSnapshot model synchronization process on the basis of liquibase changelog is idempotent.
//- Процес синхронізації DataModelSnapshot моделі по liquibase changelog є ідемпотентним
- Changes made from the administrative portal are in a separate liquibase changeset. The candidate version ID is a part of the liquibase changeset id attribute.
//- Зміни внесені через адміністративний портал знаходяться в окремому liquibase changeset. Ідентифікатор версії-кандидату є частиною liquibase changeset id атрибуту.

