= Розміщення сервіса публікування аналітичної звітності Redash за Kong

include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

В поточній версії Платформи публічний доступ до Redash відбувається через OpenShift HAProxy. Це спричиняє дві проблеми:

* Потенційна вразливіть сервіса публікування Redash, коли він розміщений поза виокремленого API шлюзу для зовнішнього трафіку
* При налаштуванні власного xref:admin:registry-management/control-plane-custom-dns.adoc[DNS-імені для Кабінетів]
зʼявляється потреба в налаштуванні також і окремого імені для сервіса публікування аналітичної звітності Redash.

Внесення Redash за Kong вирішить ці проблеми.

== Ролі користувачів

* Посадова особа

== Загальні принципи та положення

* Винесення стосується тільки сервісу публікування аналітичної звітності Redash (redash-viewer)
* Трафік до Redash повинен йти через основний Kong, використовуючи роут кабінету чиновника зі шляхом `/reports`
* Конг повинен перевіряти наявніть JWT-токену та у випадку відсутності переадресовувати користувача на підсистему
управління користувачами та ролями (Keycloak) для авторизації.

== Функціональні сценарії

.Потік мережевого трафіку до Redash
[plantuml, flow, svg]
----
@startuml
autoactivate on

actor user as "Посадова особа"
participant browser as "Браузер"
participant haproxy as "Ingress HAProxy"
participant istio as "Istio ingress шлюз"
participant kong as "API шлюз Kong"
participant redash as "Redash Viewer"

user -> browser: адреса кабінету чиновника /reports
browser -> haproxy: перенаправлення на "istio ingress"
haproxy -> istio: перенаправлення на "istio ingress"
istio -> kong: перенаправлення на "API шлюз Kong"
kong -> redash: перенаправлення на сервіс
redash --> kong: стартова сторінка
kong --> istio
istio --> haproxy
haproxy --> browser
browser --> user: стартова сторінка
@enduml
----

.Діаграма розгортання
[plantuml, flow, svg]
image::architecture/registry/operational/reporting/kong-redash/deployment-diagram-redash.svg[redash,350]

== План розробки

=== Технічні експертизи

* _BE_
* _Frontend_
* _DevOps_

=== План розробки

* Змінити контекстний шлях у Redash
* Змінити контекстний шлях з рутового у всіх компонентах де зустрічається URL на Redash, а саме _registry-regulation-publication-pipeline_, _registry-configuration_, _redash_chart_
* Внести Redash за Kong шляхом створення необхідних налаштувань в Kong ресурсах
* Змінити URI в кабінеті чиновника на новий
* Дозволити трафік з Kong на Redash Viewer
* Видалити в коді адмін-консолі приховані поля налаштування DNS для Redash та в common-web-app налаштування custom DNS для Redash

== Безпека

== Глосарій та акроніми

[cols="3,6"]
|===
|Термін|Опис

|_Kong_
|API шлюз для зовнішнього трафіку
|_URI_
|Уніфікований ідентифікатор ресурсів (англ. Uniform Resource Identifier, URI) — компактний рядок літер, який однозначно ідентифікує окремий ресурс в інтернеті.

|===
