//:imagesdir: ../../../../../images
= Підсистема аналітичної звітності реєстру

== Загальний опис

Підсистема, призначенням якої є візуалізація даних реєстру у вигляді інформаційних панелей (_дашбордів_) змодельованих за допомогою _Підсистеми моделювання регламенту реєстру_.

Інформаційні панелі можуть складатися з табличних форм представлення даних, діаграм та графіків, елементів фільтрації та іншими елементами управління відображенням даними.

[TIP]
--
Детальніше з підходом до обробки аналітичних запитів можна ознайомитись у розділі xref:arch:architecture/registry/operational/relational-data-storage/rdbms-analytical-workload.adoc[]
--

== Функції підсистеми

* Перегляд та маніпуляція відображенням даних реєстру на інформаційних панелях
* Перегляд та аналіз даних журналу подій аудиту реєстру на інформаційних панелях

== Технічний дизайн підсистеми

[NOTE]
--
Секція у процесі розробки. Необхідно додати опис загальних принципів роботи та взаємодії між компонентами.
--

image::architecture/registry/operational/reporting/reporting.svg[float="center",align="center"]

== Складові підсистеми

[options="header",cols="a,a,a,a"]
|===
|Назва компоненти|Представлення в реєстрі|Походження|Призначення

| _Redash Server_
|`redash-viewer`
| 3rd-party
| Надання користувацького Web UI та адміністративного API

| _Redash Worker_
|`redash-viewer-adhocworker`
| 3rd-party
| Обробка інтерактивних запитів до джерел даних

| _Redash Scheduler_
|`redash-viewer-scheduler`
| 3rd-party
| Обробка запитів до джерел даних за розкладом

| _Prometheus Exporter_
|`redash-exporter`
| 3rd-party
| Збір метрик для моніторингу і їх публікація у форматі Prometheus

| _Redash Redis_
|`redash-viewer-redis-master`
| 3rd-party
| Управління чергою запитів

| _Redash Postgres_
|`redash-viewer-postgresql`
| 3rd-party
| Зберігання метаданих Redash (запитів, інформаційних панелей, налаштувань тощо)

|===

== Джерела даних

|===
|Назва компоненти|Представлення в реєстрі

|_Аналітична БД реєстру_
a|
* `analytical:registry`

|_Операційна БД подій аудиту_
a|
* `operational:audit`
|===

== Технологічний стек

* xref:arch:architecture/platform-technologies.adoc#redash[Redash]
* xref:arch:architecture/platform-technologies.adoc#python[Python]
* xref:arch:architecture/platform-technologies.adoc#reactjs[ReactJS]
* xref:arch:architecture/platform-technologies.adoc#postgresql[PostgreSQL]
* xref:arch:architecture/platform-technologies.adoc#redis[Redis]
* xref:arch:architecture/platform-technologies.adoc#helm[Helm]

== Атрибути якості підсистеми

=== _Observability_

_Підсистема аналітичної звітності реєстру_ підтримує журналювання та збір метрик продуктивності для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--

=== _Security_

_Підсистема аналітичної звітності реєстру_ розмежована на користувацький інтерфейс та адміністративний з додатковим мережевим захистом що сприяє безпеці керування підсистемою та зменшує поверхню атаки.

Автентифікація та розмежування прав виконуєтсья централізовано xref:architecture/platform/operational/user-management/overview.adoc[підсистемою управління користувачами та ролями].

За замовчуванням користувачу надаються мінімальні права необхідні для виконання поставлених завдань. Також підсистема обмежує доступ до інформаційних панелей та до джерел даних на основі рольової моделі. Таким чином користувач може бачити тільки ті інформаційні панелі та дані тільки з тих джерел які дозволені для його ролі.

Використовується багаторівнева система мережевого захисту між компонентами підсистеми а самі компоненти постійно скануються на відомі вразливості.