:imagesdir: ../../../../../images
= Підсистема аналітичної звітності реєстру

== Загальний опис

Підсистема, призначенням якої є візуалізація даних реєстру у вигляді інформаційних панелей (_дашбордів_) змодельованих за допомогою _Підсистеми моделювання регламенту реєстру_.

Інформаційні панелі можуть складатися з табличних форм представлення даних, діаграм та графіків, елементів фільтрації та іншими елементами управління відображенням даними.

[TIP]
--
Детальніше з підходом до обробки аналітичних запитів до даних реєстру можна ознайомитись у розділі xref:arch:architecture/registry/operational/relational-data-storage/rdbms-analytical-workload.adoc[]
--

== Функції підсистеми

* Перегляд та маніпуляція відображенням даних реєстру на інформаційних панелях
* Перегляд та аналіз даних журналу подій аудиту реєстру на інформаційних панелях

== Технічний дизайн підсистеми

image::architecture/registry/operational/reporting/reporting.drawio.svg[float="center",align="center"]

Підсистема побудована на основі https://redash.io/help/[Redash], відкритого програмного забезпечення для візуалізації та дослідження даних, яке дозволяє користувачам підключатися до різних джерел даних, запитувати та візуалізувати дані, а також створювати інтерактивні інформаційні панелі та звіти. Воно використовує архітектуру мікросервісів і складається з таких компонентів:

* _Redash Server_: Сервер Redash відповідає за обробку запитів користувачів, управління аутентифікацією та авторизацією користувачів, а також надання веб-інтерфейсу Redash та адміністративного API. Користувачі взаємодіють з Redash через веб-інтерфейс, а підсистеми розгортання регламенту та розгортання реєстру, через API. _Redash Server_ асинхронно взаємодіє з іншими сервісами за допомогою черги завдань https://python-rq.org/[RQ (Redis Queue)], для виконання запитів та отримання даних.

* _Обробники черги завдань_: Redash використовує робочі процеси для виконання завдань з черги асинхронно. Обробники черги виконують завдання, такі як виконання запитів до джерел даних, генерація результатів запитів та надсилання оновлень виконання запиту до інтерфейсу користувача.

** _Redash Worker_: Обробник що відповідає за виконання завдань, які надійшли в чергу з сервера Redash в результаті взаємодії з користувачем. Наприклад завдання запиту на отримання даних з джерела даних, коли користувач відкриває інформаційну панель.

** _Redash Scheduler_: Цей обробники черги відповідає за виконання запитів з певною періодичністю за заданим графіком. Наприклад виконання завдань оновлення даних для збережених запитів для яких налаштовано розклад.

* _Redash DB_: Redash використовує реляційну базу даних PostgreSQL, як основне сховище метаданих. База даних зберігає різні метадані, пов'язані з користувачами, запитами, інформаційними панелями та візуалізаціями. Вона також зберігає результати запитів та кешовані дані. Сервіси Redash взаємодіють з базою даних для отримання та збереження необхідної інформації.

* _Redis Queue_: База даних черги завдань в Redis - це сховище даних у пам'яті, яке Redash використовує для керування загальними блокуваннями виконання запитів та розподілу завдань між робочими процесами.

Взаємодія між цими компонентами підсистеми може бути узагальнена наступним чином:

* Коли користувач взаємодіє з веб-інтерфейсом Redash, їх запити обробляються сервером Redash. Сервер аутентифікує користувача, за допомогою _підсистеми управління користувачами та ролями_, перевіряє запит і взаємодіє з відповідними сервісами на основі дій користувача.

* Коли користувач виконує запит, сервер отримує запит та відправляє його до робочого процесу через систему черги завдань (Redis Queue). Робочий процес Redash Worker бере завдання і виконує запит асинхронно, періодично оновлюючи стан запиту та надсилаючи оновлення до інтерфейсу користувача.

* Після завершення виконання запиту робочий процес зберігає кінцевий результат, і сервер отримує його для відображення користувачу.

== Складові підсистеми

[options="header",cols="a,a,a,a"]
|===
|Назва компоненти|Представлення в реєстрі|Походження|Призначення

| _Redash Server_
|`redash-viewer`
| 3rd-party
| Надання користувацького Web UI та адміністративного API

| _Redash Worker_
|`redash-viewer-adhocworker`
| 3rd-party
| Обробка завдань із черги

| _Redash Scheduler_
|`redash-viewer-scheduler`
| 3rd-party
| Обробка завдань за розкладом

| _Prometheus exporter_
|`redash-exporter`
| 3rd-party
| Збір метрик для моніторингу і їх публікація у форматі Prometheus

| _Сховище черги завдань_
|`redash-viewer-redis-master`
| 3rd-party
| Зберігання черги завдань

| _Сховище метаданих_
|`redash-viewer-postgresql`
| 3rd-party
| Зберігання бази метаданих Redash (запитів, інформаційних панелей, налаштувань тощо)

|===


== Джерела даних

|===
|Назва компоненти|Представлення в реєстрі

|_Аналітична БД реєстру_
a|
* `analytical:registry`

|_Операційна БД подій аудиту_
a|
* `operational:audit`
|===

== Технологічний стек

* xref:arch:architecture/platform-technologies.adoc#redash[Redash]
* xref:arch:architecture/platform-technologies.adoc#python[Python]
* xref:arch:architecture/platform-technologies.adoc#postgresql[PostgreSQL]
* xref:arch:architecture/platform-technologies.adoc#redis[Redis]
* xref:arch:architecture/platform-technologies.adoc#helm[Helm]

== Атрибути якості підсистеми

=== _Observability_

_Підсистема аналітичної звітності реєстру_ підтримує журналювання та збір метрик продуктивності для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--

=== _Security_

_Підсистема аналітичної звітності реєстру_ розмежована на користувацький інтерфейс та адміністративний з додатковим мережевим захистом що сприяє безпеці керування підсистемою та зменшує поверхню атаки.

Автентифікація та розмежування прав виконуєтсья централізовано xref:architecture/platform/operational/user-management/overview.adoc[підсистемою управління користувачами та ролями].

За замовчуванням користувачу надаються мінімальні права необхідні для виконання поставлених завдань. Також підсистема обмежує доступ до інформаційних панелей та до джерел даних на основі рольової моделі. Таким чином користувач може бачити тільки ті інформаційні панелі та дані тільки з тих джерел які дозволені для його ролі.

Використовується багаторівнева система мережевого захисту між компонентами підсистеми а самі компоненти постійно скануються на відомі вразливості.