= Моделювальникам бізнес-процесів
:sectanchors:
:sectlinks:

*_Моделювальники бізнес-процесів_* створюють ядро Платформи Реєстрів -- *бізнес-процеси (БП)*, які є фундаментом для всіх послуг.

Використовуючи такі інструменти, як *Адміністративний портал*, Camunda Modeler, а також *BPMN* та DMN стандарти, моделювальники БП створюють *процеси*, *UI-форми* та *інтеграції*.
Складні моделі часто включають *Groovy-скрипти*, *JUEL-функції* та *JSON-структури*.
Моделювальники та розробники використовують *REST* і *SOAP* конектори для налаштування зв'язків із зовнішніми системами, або іншими Реєстрами на Платформі.

Детальну інформацію з моделювання бізнес-процесів можна знайти на сторінках розділу.

== Огляд секції

* [*] xref:bp-modeling/bp/index.adoc[]
* [*] xref:bp-modeling/bp/bpmn/index.adoc[]
* [*] xref:bp-modeling/forms/bp-modeling-forms-general-description.adoc[]
* [*] xref:bp-modeling/bp/element-templates/element-templates-overview.adoc[]
* [*] xref:bp-modeling/bp/element-templates/soap-integration/soap-connectors-overview.adoc[]