= Моделювальникам бізнес-процесів

:sectanchors:
:sectlinks:

*_Моделювальники бізнес-процесів_* створюють ядро Платформи Реєстрів -- *бізнес-процеси (БП)*, які є фундаментом для всіх послуг.

Використовуючи такі інструменти, як *Адміністративний портал*, Camunda Modeler, а також BPMN та DMN стандарти, моделювальники БП створюють процеси, UI-форми та інтеграції. Складні моделі часто включають Groovy-скрипти, JUEL функції та JSON структури. Моделювальники та розробники використовують REST і SOAP конектори для налаштування зв'язків із зовнішніми системами, або іншими Реєстрами на Платформі.

Більше детальну інформацію по моделюванню бізнес-процесів можна знайти на сторінках розділу.

== Section Overview

* [*] xref:bp-modeling/bp/index.adoc[]
* [*] xref:bp-modeling/bp/bpmn/index.adoc[]
* [*] xref:bp-modeling/forms/bp-modeling-forms-general-description.adoc[]
* [*] xref:bp-modeling/bp/rest-connector.adoc[]
* [*] xref:bp-modeling/external-integration/api-call/connectors-external-registry.adoc[]