//== Загальний опис
== Overview

//В Платформі реєстрів параметри конфігурації зберігаються в сервісі інспекції та зберігання змін конфігурації (Gerrit) реалізуючи таким чином `GitOps` підхід до зберігання та застосування конфігурації.
The Platform for state registries stores its settings in the configuration changes review and storage service (Gerrit) according to the `GitOps` approach.

//TIP: GitOps — це підхід до оркестрації інфраструктури Платформи та розгортання реєстрів заснований на використанні Git-репозиторію як єдиного джерела для конфігураційних файлів підсистем. GitOps забезпечує автоматизоване розгортання, спрощений контроль версій, легке скасування змін та підвищену видимість змін системи через організацію процесу роботи на базі Git та декларативного опису бажаного стану Платформи та реєстру.
TIP: The GitOps approach relies on the Git repository as the sole source of the subsystem configuration files when orchestrating the Platform infrastructure and deploying registries. GitOps provides automated deployment, streamlined version control, effortless change reversals, and enhanced visibility of system changes through Git-based workflows and declarative descriptions of the desired state of the Platform and registry.