{{- if .Values.database.required }}
apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.name }}-db
    labels:
        app: {{ .Values.name }}-db
spec:
    ports:
        - name: {{ .Values.name }}-db
          port: 5432
    selector:
        app: {{ .Values.name }}-db
    type: ClusterIP
    sessionAffinity: None
{{- end }}