apiVersion: v1
kind: ConfigMap
metadata:
  name: update-demo-registry-vars
data:
  40-update-demo-registry-vars.sh: |
    #!/bin/bash

    {{`find /usr/share/nginx/html -name '*.html' -exec sed -i "s/{{{registry-name}}}/$REGISTRY_NAME/g" {} \;
    find /usr/share/nginx/html -name '*.html' -exec sed -i "s/{{{cluster-name}}}/$CLUSTER_NAME/g" {} \;
    find /usr/share/nginx/html -name '*.html' -exec sed -i "s/{{{dns-wildcard}}}/$DNS_WILDCARD/g" {} \;`}}
