apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.name }}
    labels:
        app: {{ .Values.name }}
spec:
    replicas: 1
    selector:
      matchLabels:
        app: {{ .Values.name }}
    strategy:
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: {{ .Values.name }}
        spec:
            serviceAccountName: {{ .Values.name }}
            containers:
                - name: {{ .Values.name }}
                  image: "{{ .Values.image.name }}:{{ .Values.image.version }}"
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                        protocol: TCP
                  livenessProbe:
                      failureThreshold: 5
                      initialDelaySeconds: 180
                      periodSeconds: 20
                      successThreshold: 1
                      tcpSocket:
                          port: 80
                      timeoutSeconds: 5
                  readinessProbe:
                      failureThreshold: 5
                      initialDelaySeconds: 60
                      periodSeconds: 20
                      successThreshold: 1
                      tcpSocket:
                          port: 80
                      timeoutSeconds: 5
                  resources:
                      requests:
                          memory: 500Mi
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30