{{- if .Values.database.required }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.name }}-db
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.database.capacity | quote}}
    storageClassName: {{ .Values.database.storageClass }}
{{- end }}