{{- if .Values.ingress.required }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
    name: {{ .Values.name }}
    annotations:
        description: "Route for {{ .Values.name }} application"
    labels:
        app: {{ .Values.name }}
spec:
    tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
{{- if .Values.ingress.site }}
    host: {{ .Values.ingress.site }}-{{ .Values.namespace }}.{{ .Values.dnsWildcard }}
{{end}}
    path: {{ .Values.ingress.path }}
    port:
      targetPort: 8080
    to:
      kind: Service
      name: {{ .Values.name }}
      weight: 100
    wildcardPolicy: None
status:
  ingress: []
{{end}}