apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.name }}
    labels:
        app: {{ .Values.name }}
spec:
    ports:
        - name: {{ .Values.name }}
          port: 80
          protocol: TCP
          targetPort: 80
    selector:
        app: {{ .Values.name }}
    type: ClusterIP