//== Ролі регламенту
== Registry roles

//Система надає можливість розширювати перелік ролей для чиновників та громадян. В подальшому ролі регламенту можуть бути використані для налаштування карти доступу на рівні фізичною моделі чи налаштування доступу до окремих бізнес-процесів регламенту.
The system allows for the extension of the role list for citizens and officers. Eventually, Regulations roles will be used to configure access map on the physical model level, or configure access to separate Regulations Business Processes.

[NOTE]
// Детальніше про налаштування доступу до бізнес-процесів можна ознайомитися xref:architecture/platform/operational/user-management/registry-authz.adoc[за посиланням].
Learn more about configuring access to Business Processes xref:architecture/platform/operational/user-management/registry-authz.adoc[here].

//=== Структура файлів
=== File structure
//Регламентні ролі є частиною регламенту та зберігається у директорії з назвою *roles*. Ролі налаштовуються окремо для чиновників та громадян у відповідних файлах *officer.yml* та *citizen.yml*
Regulations roles are part of Regulations, and are stored in the *roles* directory. Roles for citizens and officers are stored in the corresponding files - *officer.yml* and *citizen.yml*.


////
[plantuml]
----
@startsalt
{
{T
+ <&folder> registry-regulations
++ <&folder> bpmn
++ <&folder> dmn
++ ...

++ <&folder> roles
+++ <&file> officer.yml
+++ <&file> citizen.yml
}
}
@endsalt
----
[source, yaml]
----
roles:
  - name: officer-first-rank
    description: Роль для чиновників першого рангу
  - name: officer-second-rank
    description: Роль для чиновників другого рангу
----
////

[plantuml]
----
@startsalt
{
{T
+ <&folder> registry-regulations
++ <&folder> bpmn
++ <&folder> dmn
++ ...

++ <&folder> roles
+++ <&file> officer.yml
+++ <&file> citizen.yml
}
}
@endsalt
----
[source, yaml]
----
roles:
  - name: officer-first-rank
    description: Role for first-rank officers
  - name: officer-second-rank
    description: Role for second-rank officers
----

//=== Опис структури елементів конфігурації
=== Configuration elements structure
==== Role

////
|===
|Назва |Схема |Коментар

|*name*
|string
|Назва регламентної ролі. Повинна мати унікальне значення у реалмі.

|*description* (_optional_)
|string
|Короткий опис для ролі
|===
////

|===
|Name |Scheme |Comment

|*name*
|string
|Name of Regulations role. Must have a value unique to the realm.

|*description* (_optional_)
|string
|Short role description
|===


//=== Публікація змін
=== Changes publication
//Регламентні ролі підпадають під загальні правила роботи з регламентом реєстру в контексті відстеження та публікації змін. Тобто, у разі наявності змін до файлів регламентних ролей (*roles/officer.yml*, *roles/citizen.yml*) пайплайн публікації змін до регламенту буде запущений. В рамках виконання пайплайну крок *create-keycloak-roles* відповідає за публікацію змін до регламентних ролей. При успішному проходженні цього кроку система буде мати регламентні ролі відповідно до змісту файлів.
Regulations roles are subject to the general Registry regulations operation rules in terms of changes monitoring and publication. In case there are changes to regulations roles files (*roles/officer.yml*, *roles/citizen.yml*), the changes publication pipeline will be started. Pipeline execution includes the *create-keycloak-roles* step that is responsible for regulations roles changes publication. After successful execution of this step the system will have regulations roles according to the files contents.

[NOTE]
//Для налаштування ролей використовується Kubernetes CR KeycloakRealmRoleBatch як частина API
Kubernetes CR KeycloakRealmRoleBatch is used as part of API for role configuration:
https://github.com/epam/edp-keycloak-operator/tree/master#keycloak-operator[Keycloak operator]

//=== Діаграма послідовності публікації змін
=== Changes publication sequence diagram

//TODO check if the uml diagram translated

[plantuml]
----
include::partial$architecture/platform/operational/user-management/publish-registry-roles.puml[]
----

