:toc-title: On this page:
:toc: auto
:toclevels: 5
:experimental:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:
= Simplified regulations development process using the master version for forms and business processes and protection against changes overwrite
//= Спрощений процес розробки регламенту через мастер-версію для форм і бізнес-процесів та захист від перезапису змін

== Abstract
//== Загальний опис
In the process of developing or correcting minor errors that do not require significant changes in the regulations, the developer still has to do a large number of actions, namely -- create a candidate version in the Admin portal, make changes to the regulations and integrate changes into the master version. It consumes a lot of time and effort. To improve the modeling experience, it is necessary to provide an opportunity to introduce changes directly into the master version of regulations.
//В процесі розробки або виправлення незначних помилок які не потребують значних змін в регламенті розробнику все одно доводиться робити велику кількість дій, а саме: створення версії кандидати в Адмін порталі, внесення змін в регламент та інтеграція змін в мастер-версію. Це вимагає великої кількості часу та зусиль. Для покращення досвіду моделювання необхідно надати можливість вносити зміни в безпосередньо в мастер-версію регламенту.

== Functional scenarios
//== Функціональні сценарії
* Editing a form directly in the master version of the registry regulations.
//* Редагування форми безпосередньо в мастер-версії регламенту реєстру
* Editing a business process directly in the master version of the registry regulations.
//* Редагування бізнес-процесу безпосередньо в мастер-версії регламенту реєстру
* Creating a form directly in the master version of the registry regulations.
//* Створення форми безпосередньо в мастер-версії регламенту реєстру
* Creating a business process directly in the master version of the registry regulations.
//* Створення бізнес-процесу безпосередньо в мастер-версії регламенту реєстру
* Editing a form in the master version of the registry regulations with a simplified process of creating a candidate version.
//* Редагування форми в мастер-версії регламенту реєстру зі спрощеним процесом створення версії кандидату
* Editing a business process in the master version of the registry regulations with a simplified process of creating a candidate version.
//* Редагування бізнес-процесу в мастер-версії регламенту реєстру зі спрощеним процесом створення версії кандидату
* Creating a form in the master version of the registry regulations with a simplified process of creating a candidate version.
//* Створення форми в мастер-версії регламенту реєстру зі спрощеним процесом створення версії кандидату
* Creation a business process in the master version of the registry regulations with a simplified process of creating a candidate version.
//* Створення бізнес-процесу в мастер-версії регламенту реєстру зі спрощеним процесом створення версії кандидату
* Copying a form to the master version of the registry regulations.
//* Копіювання форми в мастер-версії регламенту реєстру
* Copying a business process to the master version of the registry regulations.
//* Копіювання бізнес-процесу в мастер-версії регламенту реєстру
* Deleting a form from the master version of the registry regulations.
//* Видалення форми в мастер-версії регламенту реєстру
* Deleting a business process from the master version of the registry regulations.
//* Видалення бізнес-процесу в мастер-версії регламенту реєстру

[NOTE]
--
All the functional scenarios refer to the _Regulations modeling web interface_.
//Всі функціональні сценарії відносяться до _Веб-інтерфейсу моделювання регламенту_
--


== User roles
//== Ролі користувачів
* Regulations developer
//* Розробник регламенту

== General principles and provisions
//== Загальні принципи та положення
* The regulations developer can edit, create or delete a form or business process directly in the master version of the registry regulations.
//* Розробник регламенту може редагувати,створювати або видаляти форму або бізнес-процес безпосередньо в мастер-версії регламенту реєстру
* _Entity_ is the general name of a form or business process in this document.
//* _Сутність_ - це загальна назва форми або бізнес-процесу в цьому документі
* The simplified process of creating a candidate version includes an automated sequence of steps after clicking the edit/create/delete _entity_ button, namely entering information about the candidate version, creating a candidate version, making changes to the _entity_ and saving changes to a candidate version.
//* Спрощений процес створення версії кандидату містить в собі автоматизовану послідовність кроків при натисканні кнопки редагування/створення/видалення _сутності_, а саме внесення інформації про версію-кандидат, створення версії кандидату, внесення змін в _сутність_ та збереження змін в версії кандидату
* When editing, creating and deleting an _entity_, it is necessary to ensure protection against overwriting the changes that may be made by other modelers.
//* При редагуванні, створенні та видаленні _сутності_ необхідно забезпечити захист від перезапису змін, які можуть бути внесені іншими моделювальниками
* When creating an entity, a verification for existence of an entity having the same name must be performed.
//* При створенні сутності повинна виконуватися перевірка на наявність сутності з таким іменем
* When editing and deleting an entity, a verification must be performed to ensure that the changes are applied in relation to the latest version of the entity (regardless of the candidate or master version).
//* При редагуванні та видаленні сутності повинна виконуватися перевірка на те що зміни застосовуються відносно останньої версії сутності (незалежно у версії-кандидаті чи мастер-версії)
* When checking for availability of changes, it has to be taken into account that changes can be made both in the Admin portal and directly in Gerrit.
//* При перевірці на зміни повинно враховуватися що зміни можуть бути внесені як через Адмін портал, так і напряму у Gerrit
* When editing and deleting an entity (http method PUT, DELETE), the general xref:arch:architecture/registry/administrative/regulation-management/services/registry-regulation-management/rest-api/rest-api-partials/optimistic-locking.adoc[] approach has to be used that is used in the system.
//* При редагуванні та видаленні сутності (http method PUT, DELETE) використовується загальний xref:arch:architecture/registry/administrative/regulation-management/services/registry-regulation-management/rest-api/rest-api-partials/optimistic-locking.adoc[] підхід який використовується в системі
* If conflicting changes are available, the system must remain in a consistent state after processing such a request.
//* При наявності змін, що конфліктують система після обробки такого запиту повинна залишатися в консистентному стані
* If conflicting changes are available, a user must manually copy the edited content, refresh the _entity_ page and make changes manually.
//* При наявності змін, що конфліктують користувач повинен власноруч скопіювати контент, який редагував, оновити сторінку з _сутністю_ та внести зміни вручну
* When making changes directly to master, a Gerrit MR must be created together with the submit and private parameters. Submit indicates that the changes must be integrated immediately. Private is used for separation to mark changes that do not require for running the pipeline to check the regulations (additional setting in the Jenkins-Gerrit integration).
//* При заведенні змін безпосередньо в мастер повинен створюватися Gerrit MR з параметром submit та private. Submit - вказує на те, що зміни повинні бути відразу інтегровані. Private - використовується для розділення для маркування змін, які не потребуються запуски пайплайну перевірки регламенту (додаткове налаштування в Jenkins-Gerrit інтеграції)

== High-level design of the solution
//== Високорівневий дизайн рішення

.Component diagram
//.Компонентна діаграма
image::architecture/registry/administrative/regulation-management/platform-evolution/master-development/component.svg[]

.Action chart. Creating an entity
//.Діаграма діяльності. Створення сутності
image::architecture/registry/administrative/regulation-management/platform-evolution/master-development/create-entity.svg[]

.Action chart. Updating an entity
//.Діаграма діяльності. Оновлення сутності
image::architecture/registry/administrative/regulation-management/platform-evolution/master-development/update-entity.svg[]

.Action chart. Deleting an entity
//.Діаграма діяльності. Видалення сутності
image::architecture/registry/administrative/regulation-management/platform-evolution/master-development/delete-entity.svg[]

=== Overwrite protection
//=== Захист від перезапису

.Creating a form/business process. Protection against changes overwriting
//.Створення форми/бізнес-процесу. Захист від перезапису змін
[plantuml, req1, svg]
----
@startuml
actor User as user
participant rrm as "RRM"
participant git as "Local Git repo"
participant gerrit as "Origin Gerrit"
actor counterpart as "Counterpart"

user -> rrm: creates form/bp
activate rrm
group Concurrent validation
    rrm -> git: file exists?
    git --> rrm: response
end

alt file already exists
    rrm --> user: HTTP 412 Precondition Failed
end

alt concurrent work in Admin Portal
    counterpart -> git: creates form/bp with the same name
else concurrent work in Gerrit
    counterpart -> gerrit: creates form/bp\nwith the same name
end

rrm -> rrm: do some side stuff
rrm -> rrm: acquire lock
activate rrm #DarkSalmon
group Concurrent validation
    rrm -> git: file exists?
    git --> rrm: response
end

alt file already exists
    rrm --> user: HTTP 412 Precondition Failed
end
rrm -> git: write file content

rrm -> git: git add\ngit commit\ngit push
git -> gerrit: push changes
alt merge conflict
    gerrit --> git: merge conflicts
    git --> rrm: merge conflicts
    rrm -> git: git fetch
    git -> gerrit: git fetch
    rrm -> git: hard reset on origin head branch
    rrm --> user: HTTP 412 Precondition Failed
end
rrm -> rrm: release lock
deactivate rrm
rrm --> user: ok
deactivate rrm

@enduml
----

.Updating a form/business process. Protection against changes overwriting
//.Оновлення форми/бізнес-процесу. Захист від перезапису змін
[plantuml, req2, svg]
----
@startuml
actor User as user
participant rrm as "RRM"
participant git as "Local Git repo"
participant gerrit as "Origin Gerrit"
actor counterpart as "Counterpart"

user -> rrm: update form/bp
activate rrm
group Concurrent validation
    rrm -> git: get file content
    git --> rrm: file content
    rrm -> rrm: compare etags
end

alt etags are different
    rrm --> user: HTTP 412 Precondition Failed
end

alt concurrent work in Admin Portal
    counterpart -> git: updates form/bp
else concurrent work in Gerrit
    counterpart -> gerrit: updates form/bp
end

rrm -> rrm: do some side stuff
rrm -> rrm: acquire lock
activate rrm #DarkSalmon
group Concurrent validation
    rrm -> git: get file content
    git --> rrm: file content
    rrm -> rrm: compare etags
end
alt etags are different
    rrm --> user: HTTP 412 Precondition Failed
end
rrm -> git: write file content

rrm -> git: git add\ngit commit\ngit push
git -> gerrit: push changes
alt merge conflict
    gerrit --> git: merge conflicts
    git --> rrm: merge conflicts
    rrm -> git: git fetch
    git -> gerrit: git fetch
    rrm -> git: hard reset on origin head branch
    rrm --> user: HTTP 412 Precondition Failed
end
rrm -> rrm: release lock
deactivate rrm
rrm --> user: ok
deactivate rrm

@enduml
----

.Deleting a form/business process. Protection against changes overwriting
//.Видалення форми/бізнес-процесу. Захист від перезапису змін
[plantuml, req3, svg]
----
@startuml
actor User as user
participant rrm as "RRM"
participant git as "Local Git repo"
participant gerrit as "Origin Gerrit"
actor counterpart as "Counterpart"

user -> rrm: deletes form/bp
activate rrm
group Concurrent validation
    rrm -> git: get file content
    git --> rrm: file content
    rrm -> rrm: compare etags
end

alt etags are different
    rrm --> user: HTTP 412 Precondition Failed
end

alt concurrent work in Admin Portal
    counterpart -> git: updates form/bp
else concurrent work in Gerrit
    counterpart -> gerrit: updates form/bp
end

rrm -> rrm: do some side stuff
rrm -> rrm: acquire lock
activate rrm #DarkSalmon
group Concurrent validation
    rrm -> git: get file content
    git --> rrm: file content
    rrm -> rrm: compare etags
end
alt etags are different
    rrm --> user: HTTP 412 Precondition Failed
end
rrm -> git: deletes content

rrm -> git: git add\ngit commit\ngit push
git -> gerrit: push changes
alt merge conflict
    gerrit --> git: merge conflicts
    git --> rrm: merge conflicts
    rrm -> git: git fetch
    git -> gerrit: git fetch
    rrm -> git: hard reset on origin head branch
    rrm --> user: HTTP 412 Precondition Failed
end
rrm -> rrm: release lock
deactivate rrm
rrm --> user: ok
deactivate rrm

@enduml
----

== Scope of work
//== Обсяг робіт

=== Preliminary decomposition
//=== Попередня декомпозиція
* [FE] Add the ability to create/edit a form/business process in the master version.
//* [FE] Додати можливість створення/редагування форми/бізнес-процесу з мастер-версії
* [BE] Extend the API for working with forms and business processes in the master version.
//* [BE] Розширити API для роботи з формами та бізнес-процесами в мастер-версії
* [DEVOPS] Configure the regulations checks pipeline to work only with the public Gerrit changes (exclude Private changes).
//* [DEVOPS] Налаштувати пайплайн перевірки регламенту на роботу тільки з публічними змінами Gerrit (exclude Private changes)
* [FE] Add a simplified process for creating a candidate version from the _entity_ creation page.
//* [FE] Додати спрощений процес створення версії кандидату зі сторінки створення _сутності_
* [FE] Add a link to Jenkins to track the regulations publication result in the Admin Portal.
//* [FE] Додати посилання на Jenkins для відстежування результату публікації регламенту в Адмін Порталі
* [FE] Add user action prompts in handling of errors containing conflicts.
//* [FE] Додати обробку помилок з конфліктами з підказками по діям користувачу
* [BE] Implement _BusinessProcessEtagInterceptor_ to check etag when updating a business process.
//* [BE] Реалізувати _BusinessProcessEtagInterceptor_ для перевірки etag при оновленні бізнес-процесу
* [BE] Add a check for duplicate names when creating an entity at the _VersionedFileRepository_ level.
//* [BE] Додати перевірку на дублікат імен при створенні сутності на рівні _VersionedFileRepository_
* [BE] Add the etag check when updating an entity at the _VersionedFileRepository_ level.
//* [BE] Додати перевірку по etag при оновленні сутності на рівні _VersionedFileRepository_
* [BE] Add handling of merge conflicts when publishing changes to Gerrit.
//* [BE] Додати обробку merge conflicts при публікації змін в Gerrit
* [BE] Extend HeadFileRepositoryImpl with support for writing files to the repository.
//* [BE] Розширити HeadFileRepositoryImpl підтримкою запису файлів в репозиторій
* [BE] Extend HeadFileRepositoryImpl with support for deleting files in the repository.
//* [BE] Розширити HeadFileRepositoryImpl підтримкою видалення файлів в репозиторій
* [FE] Add the ability to copy _entity_ in the master version.
//* [FE] Додати можливість копіювання _сутності_ в мастер-версії
* [FE] Add the ability to delete _entity_ in the master version.
//* [FE] Додати можливість видалення _сутності_ в мастер-версії
* [DEVOPS] Add account service rights to RRM to perform the _update by submit_ operation in Gerrit.
//* [DEVOPS] Додати права сервіс акаунту RRM на виконання update by submit операції в Gerrit

=== Changes to the REST API
//=== Зміни в REST API

.Registry Regulation Management
[%collapsible]
====
swagger::{attachmentsdir}/architecture/registry/administrative/regulation-management/platform-evolution/master-development/rrm-swagger.yml[]
====

=== Limitations of the solution
//=== Обмеження рішення
* In case of conflicting changes, a user needs to manually copy the content, refresh the page and repeat saving and conflict analysis.
//* При змінах, що конфліктують користувачу потрібно власноруч скопіювати контент, оновити сторінку та повторити збереження з аналізом конфліктів
* The current design does not cover the actual deletion of forms and business processes in Form-management-provider and BPMS respectively.
//* Поточний дизайн не покриває фактичне видалення форм та бізнес-процесів в Form-management-provider та BPMS відповідно