@startuml
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "Table" as table {
  *id : UUID
  --
  name: string
  historicalFlag: boolean
  objectReference:
  description: String
}

entity "Index" as index {
  *id : UUID
  --
  name: string
  columns: array[Index.Column]
}

entity "Index.Column" as index_column {
  name: string
  sorting: enum[ASC, DESC, NONE]
}

entity "UniqueConstraint" as unique_constraint extends index

entity "PrimaryKeyConstraint" as primary_key_constraint extends unique_constraint

entity "Column" as column {
  *id : UUID
  --
  name: string
  description: string
  type: enum[clarify types]
  defaultValue: object
  notNull: boolean
}

entity "ForeignKey" as foreign_key {
  *id : UUID
  --
  name: string
  targetTable: string
  columnPairs: array[ForeignKey.ColumnPair]
}

entity "ForeignKey.ColumnPair" as foreign_key_column_pair {
  sourceColumnName: string
  targetColumnName: string
}

entity "DdmRolePermission" as ddm_role_permission {
  *permissionId : UUID
  --
  roleName : string
  objectName : string // it's table name
  columnName : string
  operation: enum[INSERT, SELECT, UPDATE, DELETE]
}


table ||..o{ index
table ||..o{ column
table ||..o{ foreign_key
table ||..o{ unique_constraint
table ||..o{ primary_key_constraint

foreign_key +-- foreign_key_column_pair
index +-- index_column
@enduml