= Адміністративна зона реєстру

== Загальний опис

_Адміністративна зона Реєстру_ - це сукупність підсистем, що забезпечують функції розробки та розгортання цифрового регламенту реєстру за допомогою _GitOps_-підходу шляхом внесення змін у відповідний репозиторій системи контроля версій та автоматичного їх застосування.

_Підсистема моделювання регламенту реєстру_ адміністративної зони надає веб-інтерфейси для адміністраторів, за допомогою яких можна створювати модель даних, бізнес-процеси інформаційних та адміністративних послуг, визначати організаційну структуру та права доступу, налаштовувати зовнішні інтеграції, будувати аналітичні звіти та витяги, тощо.

[TIP]
--
Детальніше з ролями службових адміністраторів можна ознайомитись у розділі xref:arch:architecture/platform/operational/user-management/platform-actors-roles.adoc#_службові_адміністратори[Актори та ролі Платформи].
--

== Технічний дизайн адміністративної зони реєстру

На даній діаграмі зображено підсистеми, які входять в _Адміністративну зону Реєстру_ та їх взаємодію з іншими підсистемами в рамках реалізації функціональних сценаріїв.

image::architecture/registry/administrative/administrative-zone-subsystems.svg[]

== Підсистеми адміністративної зони реєстру

[TIP]
--
Перелік підсистем та відповідних репозиторіїв наведено в таблиці нижче. У разі, якщо компоненти підсистеми реалізовано в окремих репозиторіях, вони наведені в переліку складових підсистеми.
--

|===
|Назва підсистеми|Службова назва

|xref:architecture/registry/administrative/ext-api-management/overview.adoc[Підсистема управління зовнішнім трафіком]
|_ext-api-management_

|xref:architecture/registry/administrative/regulation-management/overview.adoc[Підсистема моделювання регламенту реєстру]
|_regulation-management_

|xref:architecture/registry/administrative/regulation-publication/overview.adoc[Підсистема розгортання регламенту реєстру]
|_regulation-publication_

|xref:architecture/registry/administrative/officer-management/overview.adoc[Підсистема управління надавачами послуг]
|_officer-management_

|xref:architecture/registry/administrative/operational-maintenance/overview.adoc[Підсистема обслуговування операційної зони реєстру]
|_operational-maintenance_
|===