global:
  registry:
    adminPortal:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    analyticalInstance:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    bpAdminPortal:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=50  -XX:MaxRAMPercentage=50 -XX:ActiveProcessorCount=1  -XX:+UseSerialGC
        resources:
          limits:
            memory: 600Mi
          requests:
            memory: 600Mi
      istio:
        sidecar:
          enabled: false
      replicas: 1
    bpWebserviceGateway:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=50  -XX:MaxRAMPercentage=50 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 600Mi
          requests:
            memory: 600Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    bpms:
      container:
        envVars:
          JAVA_OPTS: >-
            -Xms384m -Xmx384m -XX:MaxMetaspaceSize=217578K -Xss512k
            -XX:MaxDirectMemorySize=10M -XX:CompressedClassSpaceSize=30M -XX:ReservedCodeCacheSize=20M
            -XX:ActiveProcessorCount=2 -XX:+UseParallelGC -XX:ParallelGCThreads=4
            -Dserver.tomcat.threads.max=4 -Dserver.tomcat.max-connections=64
            -Dspring.datasource.hikari.minimum-idle=4
            -Dspring.datasource.hikari.maximum-pool-size=4
            -Dcamunda.bpm.job-execution.core-pool-size=1
            -Dcamunda.bpm.job-execution.max-pool-size=1
        resources:
          limits:
            memory: 850Mi
          requests:
            memory: 850Mi
      istio:
        sidecar:
          enabled: false
      replicas: 1
    citizenPortal:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    ddmLanguageServer:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=60  -XX:MaxRAMPercentage=60 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 500Mi
          requests:
            memory: 500Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    ddmNotificationService:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=60  -XX:MaxRAMPercentage=60 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 700Mi
          requests:
            memory: 700Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    digitalDocumentService:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=60  -XX:MaxRAMPercentage=60 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 700Mi
          requests:
            memory: 700Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    digitalSignatureOps:
      container:
        envVars:
          JAVA_OPTS: >-
            -Xms64m -Xmx64m -XX:MaxMetaspaceSize=98632K -Xss512k
            -XX:MaxDirectMemorySize=10M -XX:CompressedClassSpaceSize=15M -XX:ReservedCodeCacheSize=20M
            -XX:ActiveProcessorCount=1 -XX:+UseSerialGC
            -Dserver.tomcat.threads.max=4 -Dserver.tomcat.max-connections=64
        resources:
          limits:
            memory: 350Mi
          requests:
            memory: 350Mi
      istio:
        sidecar:
          enabled: false
      replicas: 1
    excerptServiceApi:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=60  -XX:MaxRAMPercentage=60 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 700Mi
          requests:
            memory: 700Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    excerptWorker:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=60  -XX:MaxRAMPercentage=60 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 600Mi
          requests:
            memory: 600Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    excerptWorkerCsv:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=60  -XX:MaxRAMPercentage=60 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 600Mi
          requests:
            memory: 600Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    excerptWorkerDocx:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=60  -XX:MaxRAMPercentage=60 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 600Mi
          requests:
            memory: 600Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    externalSecrets:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    formSchemaProvider:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=60  -XX:MaxRAMPercentage=60 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 800Mi
          requests:
            memory: 800Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    formSubmissionValidation:
      container:
        resources:
          limits:
            memory: 300Mi
          requests:
            memory: 300Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    geoServer:
      container:
        envVars:
          INITIAL_MEMORY: 500m
          JAVA_OPTS: -XX:ActiveProcessorCount=2
          MAXIMUM_MEMORY: 500m
        resources:
          limits:
            memory: 800Mi
          requests:
            memory: 800Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 80Mi
      replicas: 1
    hashicorpVault:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    istioIngressGateway:
      container:
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 128Mi
      istio:
        sidecar:
          enabled: false
      replicas: 1
    jenkins:
      container:
        envVars:
          JAVA_OPTS: -Xmx1000m
        resources:
          limits:
            memory: 2000Mi
          requests:
            memory: 500Mi
      istio:
        sidecar:
          enabled: false
      replicas: 1
    kafkaApi:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=65  -XX:MaxRAMPercentage=65 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 1500Mi
          requests:
            memory: 1500Mi
      datasource:
        maxPoolSize: 10
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    kafkaClusterEntityOperator:
      container:
        resources:
          limits:
            memory: 500Mi
          requests:
            memory: 400Mi
      istio:
        sidecar:
          enabled: false
      replicas: 1
    kafkaClusterKafkaExporter:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    kafkaClusterZookeper:
      container:
        envVars:
          JAVA_OPTS: -XX:ActiveProcessorCount=2 -XX:InitialRAMPercentage=50  -XX:MaxRAMPercentage=50 -XX:+UseG1GC
        resources:
          limits:
            memory: 600Mi
          requests:
            memory: 600Mi
      istio:
        sidecar:
          enabled: false
      replicas: 1
    kafkaConnectClusterConnect:
      container:
        envVars:
          JAVA_OPTS: -Xms400m -Xmx400m -XX:ActiveProcessorCount=2 -XX:+UseG1GC
      istio:
        sidecar:
          enabled: false
      replicas: 1
    kafkaSchemaRegistry:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    kafkaUi:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=50  -XX:MaxRAMPercentage=50 -XX:ActiveProcessorCount=2 -XX:+UseG1GC
        resources:
          limits:
            memory: 500Mi
          requests:
            memory: 500Mi
      istio:
        sidecar:
          enabled: false
      replicas: 1
    kong:
      istio:
        sidecar:
          enabled: true
      replicas: 1
    kongAdminTools:
      istio:
        sidecar:
          enabled: true
      replicas: 1
    nexus: {}
    officerPortal:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    operationalInstance:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    operationalPool:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    pgAdmin:
      container:
        resources:
          limits:
            memory: 300Mi
          requests:
            memory: 300Mi
      istio:
        sidecar:
          enabled: false
      replicas: 1
    platformGateway:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=50  -XX:MaxRAMPercentage=50 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 600Mi
          requests:
            memory: 600Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    processHistoryServiceApi:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=50  -XX:MaxRAMPercentage=50 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 700Mi
          requests:
            memory: 700Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    processHistoryServicePersistence:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=60  -XX:MaxRAMPercentage=60 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 700Mi
          requests:
            memory: 700Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    redashAdmin:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashAdminAdhocworker:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashAdminRedisMaster:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashAdminScheduler:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashExporter:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashViewer:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashViewerAdhocworker:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashViewerRedisMaster:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redashViewerScheduler:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    redis:
      istio:
        sidecar:
          enabled: false
      replicas: 2
    registryRegulationManagement:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=60  -XX:MaxRAMPercentage=60 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 1200Mi
          requests:
            memory: 1200Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    reloader:
      istio:
        sidecar:
          enabled: false
      replicas: 1
    reportExporter:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=60  -XX:MaxRAMPercentage=60 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 500Mi
          requests:
            memory: 500Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    restApi:
      container:
        envVars:
          JAVA_OPTS: >-
            -Xms128m -Xmx128m -XX:MaxMetaspaceSize=158105K -Xss512k
            -XX:MaxDirectMemorySize=10M -XX:CompressedClassSpaceSize=20M -XX:ReservedCodeCacheSize=20M
            -XX:ActiveProcessorCount=1 -XX:+UseSerialGC
            -Dserver.tomcat.threads.max=4 -Dserver.tomcat.max-connections=64
        resources:
          limits:
            memory: 500Mi
          requests:
            memory: 500Mi
      datasource:
        maxPoolSize: 4
      istio:
        sidecar:
          enabled: false
      replicas: 1
    sentinel:
      istio:
        sidecar:
          enabled: true
      replicas: 3
    soapApi:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=60  -XX:MaxRAMPercentage=60 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 600Mi
          requests:
            memory: 600Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    userProcessManagement:
      container:
        envVars:
          JAVA_OPTS: >-
            -Xms64m -Xmx64m -XX:MaxMetaspaceSize=115625K -Xss512k
            -XX:MaxDirectMemorySize=10M -XX:CompressedClassSpaceSize=15M -XX:ReservedCodeCacheSize=20M
            -XX:ActiveProcessorCount=1 -XX:+UseSerialGC
            -Dserver.tomcat.threads.max=4 -Dserver.tomcat.max-connections=64
        resources:
          limits:
            memory: 300Mi
          requests:
            memory: 300Mi
      istio:
        sidecar:
          enabled: false
      replicas: 1
    userSettingsServiceApi:
      container:
        envVars:
          JAVA_OPTS: -XX:+UseContainerSupport -XX:InitialRAMPercentage=60  -XX:MaxRAMPercentage=60 -XX:ActiveProcessorCount=2 -XX:+UseG1GC  -XX:+ExplicitGCInvokesConcurrent
        resources:
          limits:
            memory: 700Mi
          requests:
            memory: 700Mi
      istio:
        sidecar:
          enabled: true
          resources:
            limits:
              memory: 140Mi
            requests:
              memory: 80Mi
      replicas: 1
    userTaskManagement:
      container:
        envVars:
          JAVA_OPTS: >-
            -Xms64m -Xmx64m -XX:MaxMetaspaceSize=112792K -Xss512k
            -XX:MaxDirectMemorySize=10M -XX:CompressedClassSpaceSize=15M -XX:ReservedCodeCacheSize=20M
            -XX:ActiveProcessorCount=1 -XX:+UseSerialGC
            -Dserver.tomcat.threads.max=4 -Dserver.tomcat.max-connections=64
        resources:
          limits:
            memory: 300Mi
          requests:
            memory: 300Mi
      istio:
        sidecar:
          enabled: false
      replicas: 1
    wiremock:
      container:
        resources:
          limits:
            memory: 400Mi
          requests:
            memory: 400Mi
      istio:
        sidecar:
          enabled: false
      replicas: 1