= Перегляд стану складових версії регламенту реєстру та формування запиту на внесення змін

== Функціональні сценарії

- Перегляд поточного стану HEAD основної гілки репозиторію регламенту / перелік файлів UI-форм
- Отримання контенту файлу HEAD основної гілки репозиторію регламенту / JSON-контент UI-форми
- Перегляд переліку сформованих запитів на внесення змін до регламенту (Користувач, Версія, Опис зміни, Дата створення, Дата останньої модифікації, Статус інспекції, Наявність конфліктів з HEAD)
- Створення запиту на внесення змін до регламенту з описом зміни ([<version>] <Опис запиту на зміни>)
- Створення нових файлів схем UI-форм
- Зміна існуючих файлів схем UI-форм
- Видалення існуючих файлів схем UI-форм
- Внесення зміни до створеного запиту на внесення змін до регламенту
- Перегляд поточного стану / переліку змін окремого запиту на внесення змін до регламенту
- Перегляд поточного стану регламенту з урахуванням стану HEAD основної гілки та переліку змін, виконаних в рамках окремого запиту на внесення змін до регламенту
- Отримання контенту файлу з урахуванням стану HEAD основної гілки та переліку змін, виконаних в рамках окремого запиту на внесення змін до регламенту
- Маркування запиту на внесення змін, як того, який пройшов інспекцію адміністратором (Code-Review)
- Маркування запиту на внесення змін, як того, який був відхилений інспекцією адміністратором (Code-Review)
- Інтеграція запиту на внесення зміни до основної гілки репозиторію регламенту
- Ініціювання _<rebase>_ запиту на внесення змін у разі наявності конфліктів з HEAD версією

== Дизайн рішення

image::architecture/registry/administrative/regulation-management/admin-portal/poc/git-gerrit-poc.svg[git-gerrit-integration,700]

== Технологічний стек

|===
|Технологія / Бібліотека|Версія|Ліцензія|Документація|Опис

|https://www.eclipse.org/jgit/[jGit]|6.1.0.202203080745-r|EDL license|https://download.eclipse.org/jgit/site/6.2.0.202206071550-r/apidocs/index.html[Документація]|JGit - це EDL ліцензована _Java_ бібліотека, яка реалізує систему контролю версій _Git_.
|https://github.com/uwolfer/gerrit-rest-java-client[gerrit-rest-java-client]|0.9.4|Apache-2.0 license|https://gerrit-review.googlesource.com/Documentation/[Документація]|_Java_ імплементація _Gerrit Code Review REST API_.

|===

== Аналіз опцій по роботі з копією репозиторію користувача

|===
|Сценарій|In Memory|File System

|clone | + | +
|fetch / pull | + | +
|commit | - | +
|push | - | +

|===

== Рішення за результатами аналізу

В результаті аналізу було виявлено, що InMemoryRepository обмежена та призначена лише для тестування, тому вирішили відмовитись від даної реалізації репозиторія:

[NOTE]
--
http://javadox.com/org.eclipse.jgit/org.eclipse.jgit/5.6.0.201912101111-r/org/eclipse/jgit/internal/storage/dfs/InMemoryRepository.html#:~:text=It%20is%20not%20very%20efficient%20and%20exists%20only%20for%20unit%20testing%20and%20small%20experiments[_InMemoryRepository_ не є фективним і існує лише для модульного тестування та невеликих експериментів.]

https://stackoverflow.com/questions/31271278/clone-a-git-repository-into-an-inmemoryrepository-with-jgit#:~:text=The%20CloneCommand%20will%20always%20create%20a%20file%2Dbased%20repository[_CloneCommand_ завжди стрворює репозиторій, який базується на файловій системі.]
--
