:toc-title: ЗМІСТ
//:toc: auto
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
//:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Розгортання Платформи на цільових оточеннях

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

Платформа реєстрів є *_cloud-agnostic_*, що означає її здатність працювати ефективно на різних хмарних сервісах без особливих залежностей від конкретного хмарного середовища. Така гнучкість дає можливість клієнтам та розробникам обирати найбільш відповідний хмарний сервіс на основі їх конкретних потреб та вимог, не прив'язуючись до одного постачальника.

Розгортання Платформи реєстрів обов'язково має відбуватися на віртуальних інфраструктурах, що отримують офіційну підтримку. Наразі такими є:


* [*] _Публічні хмари_: такі як https://aws.amazon.com/[Amazon Web Services (AWS)], https://azure.microsoft.com/[Microsoft Azure (Azure)], та https://cloud.google.com/[Google Cloud Platform (GCP)]. Ці сервіси надають доступ до віртуальних ресурсів через інтернет і є доступними для загальної публіки.

* [*] _Приватні хмари_: це хмари, які призначені виключно для використання однієї організації.
https://www.vmware.com/products/vsphere.html[VMWare vSphere], наприклад, є платформою, що дозволяє створювати приватні, зокрема локальні (on-premises) хмарні інфраструктури.

На вищезгаданих інфраструктурах має бути встановлений OKD-кластер, версія якого відповідає вимогам Платформи, згідно з рекомендаціями, викладеними в офіційній документації Платформи: xref:admin:installation/okd-requirements.adoc[].

Встановлення та налаштування Платформи виконується відповідно до вказівок, наданих в офіційній документації Платформи.

== Огляд секції

* xref:installation/platform-deployment/platform-aws-deployment.adoc[]
* xref:installation/platform-deployment/platform-azure-deployment.adoc[]
* xref:installation/platform-deployment/platform-gcp-deployment.adoc[]
* xref:installation/platform-deployment/platform-vsphere-deployment.adoc[]

