= Функція _message_payload()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`message_payload(String taskDefinitionKey): MessagePayloadReadOnlyDto`* використовується для отримання даних повідомлення, пов'язаних із завданням або початковою подією процесу.

== Параметри

.Параметри функції
|===
|*Аргумент*            | *Опис*
| `taskDefinitionKey`  | Ключ завдання або початкової події, для якого потрібно отримати дані повідомлення.
|===

== Що повертає

Ця функція повертає об'єкт типу `MessagePayloadReadOnlyDto`, що містить дані повідомлення.

.MessagePayloadReadOnlyDto
|===
|*Поле*            | *Опис*
| `data`           | Дані повідомлення у вигляді мапи `Map<String, Object>`.
|===

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

== Приклади використання

Цей розділ демонструє приклади використання JUEL-функції у завданнях бізнес-процесу.

[TIP]
====
[%collapsible]
.Де можна знайти приклад бізнес-процесу?
=====
include::partial$snippets/demo-reg-reference-examples-ua.adoc[]

Застосування функції `message_payload()` представлено у деяких великих бізнес-процесах.

Ви можете використати один із прикладів процесів за пошуком по ключовим словам — *_feature-start-process-by-end-message-event_*.

У Кабінеті користувача бізнес-процес буде доступний у розділі *Доступні послуги*.
=====
====

Нижче наведено приклад використання функції `message_payload()` для отримання даних повідомлення, що пов'язані із завданням або подією. Він демонструє, як зібрати дані з xref:bp-modeling/bp/bpmn/events/message-event.adoc[події "Повідомлення"], отримати ідентифікатор процесу, що викликав поточний, і використати їх у бізнес-процесі.


[source,groovy]
----
var cephData = [:]

cephData['callerProcess'] = process_caller().id

message_payload('startEvent2').data.keySet().each {
    cephData[it] = message_payload('startEvent2').data.get(it)
}

set_transient_variable('payload', S(cephData, 'application/json'))
----

Пояснення ::

. *`cephData['callerProcess'] = process_caller().id`* -- отримує ідентифікатор процесу, що викликав поточний, і зберігає його в об'єкті `cephData` (див. детальніше -- xref:bp-modeling/bp/juel-functions/processes/process-caller.adoc[]).
. *`message_payload('startEvent2')`* -- отримує дані повідомлення, пов'язаного з подією або завданням під ідентифікатором `'startEvent2'`.
. *`.data.keySet()`* -- отримує всі ключі з даних повідомлення.
. *`.data.get(it)`* -- отримує значення для кожного ключа і зберігає його в об'єкті `cephData`.
. *`set_transient_variable()`* -- зберігає зібрані дані у форматі JSON як тимчасову змінну для подальшого використання в процесі (див. детальніше -- xref:bp-modeling/bp/juel-functions/variables/set-transient-variable.adoc[]).

== Пов'язані сторінки

* xref:bp-modeling/bp/juel-functions/processes/process-caller.adoc[]
* xref:bp-modeling/bp/juel-functions/variables/set-transient-variable.adoc[]
* xref:bp-modeling/bp/bpmn/events/message-event.adoc[]