= Функція _message_payload()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`message_payload(String taskDefinitionKey): MessagePayloadReadOnlyDto`* використовується для отримання даних повідомлення, пов'язаних із завданням або початковою подією процесу.

== Параметри

.Параметри функції
|===
|*Аргумент*            | *Опис*
| `taskDefinitionKey`  | Ключ завдання або початкової події, для якого потрібно отримати дані повідомлення.
|===

== Що повертає

Ця функція повертає об'єкт типу `MessagePayloadReadOnlyDto`, що містить дані повідомлення.

.MessagePayloadReadOnlyDto
|===
|*Поле*            | *Опис*
| `data`           | Дані повідомлення у вигляді мапи `Map<String, Object>`.
|===

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

== Приклад

Цей розділ демонструє приклади використання JUEL-функції у завданнях бізнес-процесу.

//TODO: ADD

TIP: Застосування функції `message_payload()` детально представлено у референтному прикладі на сторінці xref:best-practices/bp-message-payload-access.adoc[].