@startuml

autoactivate on

skinparam shadowing false
skinparam DatabaseBackgroundColor white
skinparam DatabaseBorderColor #2688d4
skinparam QueueBackgroundColor white
skinparam QueueBorderColor #2688d4
skinparam NoteBackgroundColor white
skinparam NoteBorderColor #2688d4
skinparam sequence {
    ArrowColor #2688d4
    ActorBorderColor #2688d4
    LifeLineBorderColor #2688d4
    ParticipantBorderColor #2688d4
    ParticipantBackgroundColor white
    BoxBorderColor #2688d4
    BoxBackgroundColor white
}

skinparam responseMessageBelowArrow true

actor "Розробник\n регламенту" as Dev

participant "Admin portal" as ap
participant "Registry Regulation\nManagement" as rrm
participant "Language Server" as ls

Dev -> ap: відкриває перспективу редагування структури таблиць
  ap -> rrm: [HTTPS] GET /versions/candidate/<vcId>/data-model/tables
  rrm --> ap: 200, (text/xml) createTables.xml document
ap --> Dev: MonacoEditor з createTables.xml

Dev -> ap: редагування структури моделі даних
  ap -> ls: [LSP] ініціалізація редагування файлу
  ls --> ap: result

  ap -> ls: [LSP] validation, autocompletion requests
  ls --> ap: result

ap --> Dev: підказки, автодоповнення


Dev -> ap: Зберігає зміни в структурі таблиць
  ap -> rrm: PUT (text/xml) /versions/candidate/<vcId>/data-model/tables
  rrm --> ap: status: 200
ap --> Dev: статус збереження змін (включаючи optimistic locking статуси)




@enduml