@startuml

actor "Розробник регламенту" as dev
participant "Сховище\nрегламенту" as gerrit
participant "Пайплайн\nпублікацій змін\nдо регламенту" as pipe
participant "Keycloak-operator" as keycloak_operator
participant "Keycloak" as keycloak
participant "OpenShift" as openshift
participant "Сервіс вхідних\nзовнішніх інтеграцій" as gateway
participant "Сервіс виконання\nбізнес-процесів"  as bpms
participant "Трембіта" as trembita
participant "Фабрика даних" as data_factory

autonumber 1.1.1

title Розмежування прав на ініціювання бізнес-процесу між зовнішніми клієнтами

== Реєстрація нового зовнішнього клієнта  ==

pipe -> openshift : Оновлення ConfigMap\n**bp-webservice-gateway-consumers**\nновими зовнішнім клієнтами
note right of pipe
name
subsystemCode
memberClass
memberCode
end note
pipe -> openshift : Оновлення Secret\n**bp-webservice-gateway-consumers**\nновими зовнішнім клієнтами
note right of pipe
<<**name**>>: пароль
end note
pipe -> gateway : Рестарт сервісу
gateway -> openshift : Читання конфігурацій\nз ConfigMap та Secret\n**bp-webservice-gateway-consumers**

== Надання прав для ініціювання бізнес-процесу зовнішнім клієнтом ==
autonumber inc B
dev -> gerrit : Оновлення файлу\n**bp-auth/external-system.yml**
note right of dev
process definition
role
end note
pipe -> gerrit : Отримання\nзмін регламенту
note over pipe : Інші кроки з публікації змін
pipe -> bpms : Оновлення авторизаційних\nправил для ролей\nзовнішніх клієнтов

== Реєстрація бізнес-процесу для запуску зовнішнім клієнтом ==
autonumber inc B
dev -> gerrit : Оновлення файлу\n**trembita/business-processes.yml**
note right of dev
process definition
start vars
return vars
end note
pipe -> gerrit : Отримання\nзмін регламенту
note over pipe : Інші кроки з публікації змін
pipe -> openshift : Оновлення ConfigMap \n**bp-webservice-gateway-business-processes**
note right of pipe
process definition
start vars
return vars
end note
pipe -> gateway : Рестарт сервісу
gateway -> openshift : Читання конфігурацій з ConfigMap\n**bp-webservice-gateway-business-processes**

== Запуск бізнес-процесу зовнішнім клієнтом ==
autonumber inc A
trembita -> gateway : Запит на\nініціювання\nбізнес-процесу
note left of trembita
process definition
start vars values
subsystemCode
memberClass
memberCode
end note
gateway -> gateway : Валідація **start vars**\nта **process definition**
gateway -> gateway : Пошук зареєстрованого\nзовнішнього клієнту та\nпаролю в конфігурації
note left of gateway
Отримання **consumer-name**
та паролю за
subsystemCode
memberClass
memberCode
end note
gateway -> keycloak : Отримання токену за consumer-name та паролем
note left of gateway
auth flow = client credentials
end note
keycloak --> gateway : accessToken
gateway -> bpms: Запуск бізнес-процесу \n\
**X-Access-Token**: accessToken
note right of gateway
process definition
start vars values
access token
end note
bpms -> bpms : Перевірка\nавторизаційних правил\nдля ролі зовнішнього клієнту
bpms -> data_factory : Виклик фабрики даних \n\
**X-Access-Token**: accessToken
note over bpms
Виконання інших кроків в рамках бізнес-процесу
end note
bpms --> gateway : Завершення бізнес-процесу
note left of bpms
return vars values
end note
gateway --> trembita : Відповідь\nпро успішне виконання\nбізнес-процесу
note right of gateway
return vars values
end note
@enduml