= Платформа оркестрації контейнерів

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

OpenShift є платформою управління контейнерами з відкритим кодом, що забезпечує розширені можливості оркестрації та
розгортання контейнеризованого програмного забезпечення. Вона розроблена на базі Kubernetes, надає повноцінний стек рішень
та абстракцій для розробки, розгортання, керування та моніторингу контейнерів. Ця платформа надає можливість розгорнути своє програмне
забезпечення в будь-якому публічному хмарному середовищі, приватному хмарному середовищі або на власній локальній інфраструктурі,
забезпечуючи стійкість, надійність та безпеку для розгорнутого програмного забезпечення.

OpenShift є гнучкою платформою, що може бути легко розширена, доповнена та інтегрована з іншими інструментами,
платформами та програмним забезпеченням. Це дозволяє мати:

* можливості моніторингу та логування, які надають інформацію про стан та продуктивність програмного забезпечення та інфраструктури
* політики мережевої безпеки та контроль доступу на основі ролей (RBAC), що дозволяють безпечно публікувати та надавати доступ кінцевим користувачам
* резервне копіювання та масштабування платформи та розгорнутого програмного забезпечення, що дозволяє швидко відновлювати стан системи
та реагувати на збільшення чи зменшення навантаження.
* розподілені сховища даних для зберігання стану та інформації stateful-застосунків

Таким чином, OpenShift є потужною та гнучкою платформою для розгортання та управління контейнеризованими додатками, з
комплексним набором інструментів та функцій, OpenShift є ідеальним рішенням для організацій, які бажають модернізувати
свою інфраструктуру програмного забезпечення та прискорити процеси цифрової трансформації.


== Функції

* Оркестрація контейнерів
* Балансування навантаження
* Масштабування застосунків
* Моніторинг застосунків
* Забезпечення безпеки та надійності

== Технічний дизайн

image::architecture/container-platform/container-orchestration.svg[width=750,float="center",align="center"]

== Атрибути якості

=== _Scalability_

Openshift використовує автоматичне масштабування (HAP), запускаючи додаткові контейнери та автоматично масштабуючи їх у відповідь на попит.
Також сам кластер OpenShift може бути легко масштабований.

=== _Availability_

...

=== _Portability_

Контейнери з програмним забезпеченням є переносними на різні середовища, починаючи від публічних або приватних хмарних
платформ або на власній локальній інфраструктурі.

=== _Operability_

...

=== _Security_

...

=== _Observability_

...

=== _Extensibility_
Openshift забезпечує широкі можливості по розширенню API власними ресурсами та контролерами що обробляють ці ресурси.
