= Архітектурна документація

== Загальний опис

_Платформа Реєстрів_ - це інформаційна система для швидкого створення, моделювання, розгортання та обслуговування державних реєстрів з ціллю ефективного надання державних послуг в цифровому вигляді.

Головною метою рішення є реалізація _децентралізованого_ та _регульованого_ підходу в управлінні державними реєстрами та забезпечення оптимального балансу між вимогами до безпеки даних, інтероперабельністю, швидкістю розгортання та вартістю володіння реєстрами.

== Проблематика

_Платформа Реєстрів_ направлена на вирішення ряду проблем з поточним станом державних інформаційних реєстрів, що ускладнюють процес цифровізації державних послуг:

* Низька якість даних через відсутність master data management
* Для кожного реєстру створюється власна інформаційна інфраструктура
* Інформаційні системи реєстрів застарілі та потребують оновлення
* Відсутня класифікація реєстрів та диференціація вимог щодо їх захисту
* Створення кожного реєстру визначається окремим законом, який запроваджує різні визначення та підходи
* Вартість супроводу кожного реєстру відносно висока; в сумі витрати на супровід реєстрів дуже великі
* Реєстри обслуговуються великою кількістю різних команд, з різним рівнем кваліфікації та досвідом

== Бізнес-драйвери

* 100% державних послуг доступні громадянам та бізнесу у цифровому вигляді

== Бізнес-цілі

* Побудова єдиного державного інформаційного простору
* Стандартизація процесу розробки на експлуатації реєстрів
* Оптимізація витрат на розробку, розгортання та володіння реєстрами
* Зниження вимог до розробників та адміністраторів реєстрів
* Забезпечення довіри суспільства та унеможливлення корупційних дій
* Ефективна взаємодія реєстрів між собою
* Формування підґрунтя для надання цифрових послуг
* Висока надійність зберігання даних реєстрів

== Функціональні можливості

* Розгортання _Платформи Реєстрів_ в хмарному середовищі або локальній інфраструктурі ЦОД
* Створення групи реєстрів на базі одного екземплярі Платформи з підтримкою SaaS-моделі “Реєстр як сервіс”
* _Low-code_ підхід до розробки реєстрів включно з моделлю даних, бізнес-процесами інформаційних та адміністративних послуг, організаційною структурою, зовнішніми інтеграціями, тощо.
* Забезпечення відповідності реєстрів на Платформі вимогам безпеки та відмовостійкості
* Централізований підхід до розповсюдження оновлень екземплярів _Платформи Реєстрів_
* ...

== Розділи архітектурної документації

* xref:arch:architecture/platform-conceptual.adoc[]
* xref:arch:architecture/platform-logical.adoc[]
* xref:arch:architecture/platform-deployment.adoc[]
* xref:arch:architecture/platform-quality-attributes.adoc[]
* xref:arch:architecture/platform-technologies.adoc[]
* Високорівневий дизайн підсистем Платформи
* xref:arch:architecture/registry-cost.adoc[]
