= Архітектурна документація

== Загальний опис

_Платформа Реєстрів_ - це інформаційна система для швидкого створення, моделювання, розгортання та обслуговування державних реєстрів з ціллю ефективного надання державних послуг в цифровому вигляді.

Головною метою рішення є реалізація _децентралізованого_ та _регульованого_ підходу в управлінні державними реєстрами та забезпечення оптимального балансу між вимогами до безпеки даних, інтероперабельністю, швидкістю розгортання та вартістю володіння реєстрами.

== Проблематика

_Платформа Реєстрів_ направлена на вирішення ряду проблем з поточним станом державних інформаційних реєстрів, що ускладнюють процес цифровізації державних послуг:

* Низька якість даних через відсутність _master data management_
* Для кожного реєстру створюється власна інформаційна інфраструктура
* Інформаційні системи реєстрів застарілі та потребують оновлення
* Відсутня класифікація реєстрів та диференціація вимог щодо їх захисту
* Створення кожного реєстру визначається окремим законом, який запроваджує різні визначення та підходи
* Вартість супроводу кожного реєстру відносно висока; в сумі витрати на супровід реєстрів дуже великі
* Реєстри обслуговуються великою кількістю різних команд, з різним рівнем кваліфікації та досвідом

== Бізнес-драйвери

* 100% державних послуг доступні громадянам та бізнесу у цифровому вигляді

== Бізнес-цілі

* Побудова єдиного державного інформаційного простору
* Стандартизація процесу розробки на експлуатації реєстрів
* Оптимізація витрат на розробку, розгортання та володіння реєстрами
* Зниження вимог до розробників та адміністраторів реєстрів
* Забезпечення довіри суспільства та унеможливлення корупційних дій
* Ефективна взаємодія реєстрів між собою
* Формування підґрунтя для надання цифрових послуг
* Висока надійність зберігання даних реєстрів

== Функціональні можливості

* Розгортання _Платформи Реєстрів_ в хмарному середовищі або локальній інфраструктурі _ЦОД_
* Створення одного або групи реєстрів на базі єдиного екземпляра Платформи з підтримкою _SaaS_-моделі “_Реєстр як сервіс_”
* Централізований підхід до розповсюдження оновлень екземплярів _Платформи Реєстрів_
* _Low-code_ підхід до розробки реєстрів включно з моделлю даних, бізнес-процесами інформаційних та адміністративних послуг, організаційною структурою, зовнішніми інтеграціями, тощо.
* Кабінети користувачів для отримання та надання державних послуг
* Транзакційна модель внесення змін до реєстру з використанням _КЕП_ для підпису запитів на зміну даних
* Підтримка швидкої побудови інтеграцій реєстрів на Платформі з зовнішніми системами та учасниками інформаційного обміну _СЕВДЕІР "Трембіта"_
* Підтримка версійності зберігання даних реєстру
* Побудова аналітичних звітів по даним реєстру
* Управління правами доступу до даних реєстру за допомогою _RBAC_
* Забезпечення відповідності реєстрів на _Платформі_ вимогам безпеки та відмовостійкості
* Підтримка автоматичного масштабування реєстрів в залежності від вимог та навантаження
* Підтримка резервного копіювання та відновлення даних реєстру
* ...

== Розділи архітектурної документації

Пакет технічної документації _Платформи Реєстрів_ включає:

* xref:arch:architecture/platform-conceptual.adoc[] - опис концептуального дизайну рішення, кінцевих користувачів _Платформи Реєстрів_ та зовнішніх систем, з якими побудована взаємодія
* xref:arch:architecture/platform-logical.adoc[] - високорівнева структура рішення з описом декомпозиції на складові (зони, підсистеми, тощо.) та взаємодію між ними
* xref:arch:architecture/platform-deployment.adoc[] - концептуальна діаграма розгортання _Платформи Реєстрів_
* xref:arch:architecture/platform-quality-attributes.adoc[] - ключові атрибути якості з описом підходів та техник до їх адресування
* xref:arch:architecture/platform-technologies.adoc[] - опис переліку та категорій ключових технологій , які застосовані для побудови рішення _Платформі Реєстрів_
* _Високорівневий дизайн зон та підсистем Платформи_ - набір розділів з високорівневою архітектурою, описом складових та їх взаємодії, ключових аспектів рішення, тощо.
* xref:arch:architecture/registry-cost.adoc[] - опис підходу до оцінки вартості володіння реєстрами, які розгорнуті на _Платформі Реєстрів_
