= Архітектура Платформи

== Загальний опис

_Платформа Реєстрів_ - це інформаційна система для швидкого створення, моделювання, розгортання та обслуговування державних реєстрів з ціллю ефективного надання державних послуг в цифровому вигляді.

_Платформа Реєстрів_ реалізує _децентралізований_ та _регульований_ підхід в управлінні державними реєстрами та забезпечує оптимальний баланс між вимогами до безпеки даних, інтероперабельністю, швидкістю розгортання та вартістю володіння реєстрами.

_Платформа Реєстрів_ передбачає можливості розгортання як в хмарному середовищі, так і на базі власного _ЦОД_, таким чином надаючи органам влади можливість створювати та вести реєстри за моделлю SaaS _“Реєстр як сервіс”_.

== Контекст рішення

На даній контекстній діаграмі зображено _Платформу Реєстрів_ в екосистемі державних інформаційних систем, з якими побудована інформаційна взаємодія.

Для забезпечення інтероперабельності, _Платформа Реєстрів_ підтримує дві основні опції налаштування інформаційного обміну:

* Через використання шини безпечного обміну "_Трембіта_" у якості захищеного транспорту
* Через налаштування прямих інтеграцій на базі _REST_ та _SOAP_ протоколів взаємодії для систем, які не під'єднані до _ШБО "Трембіта"_

У якості зовнішніх систем можуть виступати як існуючі інформаційні системи, так і реєстри розгорнуті на окремих екземплярах _Платформи Рєестрів_.

image::architecture/ddm-platform-context.svg[]

== Взаємодія з зовнішніми системами

=== _АЦСК_

_Платформа Реєстрів_ взаємодіє з _Акредитованими Центрами Сертифікації Ключів_ з ціллю отримання переліку відкликаних сертифікатів, отримання ланцюжка сертифікатів користувача та перевірку їх статусу, формування мітки часу, тощо.

=== _Сервіс цифрової ідентифікації (id.gov.ua)_

_Платформа Реєстрів_ надає можливість здійснювати автентифікацію отримувачів та надавачів послуг реєстру за допомогою _Інтегрованої системи електронної ідентифікації (ІСЕІ)_.

=== _Зовнішні картографічні сервіси_

_Платформа Реєстрів_ використовує зовнішні картографічні сервіси для завантаження геопросторових даних, шарів та геокодування з ціллю забезпечення можливостей внесення, пошуку та відображення об'єктів реєстру, які мають прив’язку до місцевості.

=== _СЕВДЕІР "Трембіта"_

_Платформа Реєстрів_ інтегрована до _Системи Електронної Взаємодії Державних Електронних Інформаційних Ресурсів (СЕВДЕІР) "Трембіта"_ з ціллю забезпечення захищеного інформаційного обміну даними державних реєстрів та інших інформаційних систем.

=== _Сервіси Дії (diia.gov.ua)_

_Платформа Реєстрів_ інтегрована з екосистемою державних сервісів цифрових послуг _Дія_ для покращення та забезпечення цілісності досвіду отримання державних послуг кінцевими користувачами.

=== _Зовнішні системи_

_Платформа Реєстрів_ підтримує налаштування зовнішніх інтеграцій через _ШБО "Трембіта"_ або прямих інтеграцій згідно вимог цільових реєстрів та рівню інтероперабельності зовнішніх систем.

== Актори

* _Неавторизовані користувачів_ - категорія користувачів, які мають доступ виключно до публічних даних та сторінки автентифікації.
* _Отримувачі послуг_ - фізичні або юридичні особи, які пройшли автентифікацію та самореєстрацію в реєстрі з ціллю отримання електронних послуг.
* _Надавачі послуг_ - офіційні представники державних органів, які надають послуги в рамках своїх службових обов'язків або особи, які зареєструвались у якості надавачів послуг (в залежності від вимог окремого реєстру).
* _Службові адміністратори_ та _Адміністратори інфраструктури_ - категорія користувачів, які відповідають за встановлення та обслуговування _Платформи Реєстрів_.

[TIP]
--
Детальніше з категоріями користувачів Платформи Реєстрів можна ознайомитись у розділі xref:arch:architecture/platform/operational/user-management/platform-actors-roles.adoc[].
--

== Архітектурні принципи

* [*] Платформа побудована на принципах [.underline]#мікросервісної архітектури# на базі хмарної інфраструктури, побудованої на основі https://www.okd.io/[OKD].

* [*] Один екземпляр Платформи підтримує розгортання та роботу декількох реєстрів.

* [*] Платформа відповідає належним безпековим вимогам https://cip.gov.ua/ua/news/perelik-dokumentiv-sistemi-tekhnichnogo-zakhistu-informaciyi-nd-tzi[НД ТЗІ] та https://cip.gov.ua/ua/news/poradi-rekomendaciyi-shodo-stvorennya-kszi-v-its-yaki-vikoristovuyutsya-dlya-nadannya-poslug-dostupu-do-merezhi-internet[КСЗІ], і є [.underline]#відмовостійкою#.

* [*] Розробка реєстру, що розгорнуто на Платформі, базується на принципах https://en.wikipedia.org/wiki/Low-code_development_platform[Low-code] (https://bpmn.io/[BPMN], користувацькі форми, Декларативний опис API для бази даних, REST API-взаємодія між сервісами").

* [*] Система підтримує [.underline]#логування (фіксацію подій)# та [.underline]#моніторинг# компонентів реєстру.
+
Таким чином усі зміни на платформі та в реєстрах і доступи до даних логуються. Журнали доступу надійно захищені від змін.

* [*] Система забезпечує [.underline]#резервне копіювання компонентів та даних# реєстру, центральних компонентів платформи, а також відновлення майстер-нод кластера OpenShift. Це убезпечує користувачів від втрати будь-яких критично важливих даних.

* [*] Платформа забезпечує [.underline]#надійний захист конфіденційних даних#. Конфіденційні дані надійно захищені від непередбаченого доступу і «витоку» інформації.

* [*] Платформа забезпечує [.underline]#надійність зберігання даних#, завдяки чому база даних кожного окремого реєстру захищена від втрати даних та знищення.

* [*] Платформа дозволяє [.underline]#зберігати всю історію змін#. З реєстру дані не видаляються. Оновлення даних відбувається з обов'язковим збереженням версійності. Журнал транзакцій захищений від змін.

* [*] Платформа підтримує [.underline]#транзакційну модель змін# у реєстрі. Зміни до бази даних не виконуються напряму. Усі дії з БД проводяться лише у межах регламентованих бізнес-процесів. Усі транзакції є підтверджені (наприклад, запити на зміни, підписані КЕП тощо).

* [*] Платформа [.underline]#унеможливлює несанкціоновані зміни#. Зміни у даних реєстру неможливі:

** без відповідних прав доступу (згідно зі змодельованими бізнес-процесами);
** без автентифікації та авторизації;
** за межами регламентованих бізнес-процесів.

* [*] Платформа забезпечує [.underline]#можливість розподілу прав# на основі xref:registry-develop:bp-modeling/bp/access/roles-rbac-bp-modelling.adoc[RBAC]. Розподіл прав організовано таким чином, що немає «супер адміністратора», який може виконати будь-які дії у системі. Це дозволяє нівелювати ризики незаконних дій із даними системи.
