= Атрибути якості Платформи

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Scalability

Даний атрибут якості визначає здатність системи опрацьовувати підвищення навантаження без значного впливу на загальну продуктивність, або здатність швидко адаптуватись завдяки збільшенню ресурсів.

[TIP]
--
Детальніше можна ознайомитись у відповідних розділах:

* xref:arch:architecture/container-platform/container-platform.adoc#_scalability[Платформа оркестрації контейнерів]
* xref:arch:architecture/registry/operational/relational-data-storage/overview.adoc#_scalability[Підсистема управління реляційними базами даних]
* xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc[Підсистема управління нереляційними базами даних]
* xref:arch:architecture/platform/operational/distributed-data-storage/overview.adoc[Підсистема розподіленого зберігання даних]
--

== Portability

Даний атрибут якості визначає ступінь незалежності системи від типу інфраструктури, на якій вона може бути розгорнута.

[TIP]
--
Детальніше можна ознайомитись у відповідних розділах:

* xref:architecture/container-platform/container-platform.adoc[Платформа оркестрації контейнерів]
--

== Observability

Даний атрибут якості визначає здатність системи фіксувати та надавати детальну інформацію у вигляді журналів подій, метрик моніторингу та даних трасування транзакцій користувачів з ціллю спрощення ідентифікації та вирішення проблем адміністраторами системи.

[TIP]
--
Детальніше можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/monitoring/overview.adoc[Підсистема моніторингу подій та сповіщення]
* xref:arch:architecture/platform/operational/logging/overview.adoc[Підсистема журналювання подій]
* xref:arch:architecture/platform/operational/distributed-tracing/overview.adoc[Підсистема трасування запитів]
--

== Interoperability

Даний атрибут якості визначає здатність системи ефективно взаємодіяти з іншими системами з ціллю інформаційного обміну.

[TIP]
--
Детальніше можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/operational/external-integrations/overview.adoc[Підсистема зовнішніх інтеграцій]
* xref:arch:architecture/data-exchange/overview.adoc[Шлюз безпечного обміну "Трембіта"]
--

== Auditability

Даний атрибут якості визначає здатність системи фіксувати та надавати інформацію про значимі технічні та бізнес події, пов'язані з експлуатацією системи кінцевими користувачами. Надана інформація може бути використана для виявлення та вирішення проблем в коректності функціонування системи.

[TIP]
--
Детальніше можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/operational/audit/overview.adoc[Підсистема журналювання подій аудиту]
--

== Reliability

== Performance

== Security

== Operability

== Maintainability

== Supportability

== Modifiability

== Accessibility

== Usability
