= Логічна архітектура Платформи

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

_Платформа Реєстрів_ представляє собою розподілену систему з мікросервісною архітектурою, яка побудована на базі платформи оркестрації контейнерів _OpenShift_.

В основу дизайну рішення закладено декілька ключових ідей:

* Незалежність від інфраструктури для розгортання
* Простота встановлення та розповсюдження оновлень
* Спрощення ведення розробки реєстрів
* Забезпечення відповідності реєстрів єдиним нефункціональним вимогам
* Оптимізація вартості володіння реєстрами
* Простота адміністрування реєстрів

Концептуально, рішення складається з:

* _Інфраструктура як Сервіс_ - це може бути як публічне або приватне хмарне середовище, так і локальна інфраструктура ЦОД
* _Платформа оркестрації контейнерів_ -
* _Підсистема обслуговування Платформи_ -

image::architecture/ddm-platform-structural-view.svg[]

== Складові рішення

|===
|Назва|Призначення

|xref:architecture/platform/administrative/overview.adoc[Адміністративна зона Платформи]
|Cукупність підсистем, які забезпечують функції управління Платформою Реєстрів

|xref:architecture/platform/operational/overview.adoc[Операційна зона Платформи]
|Cукупність підсистем, які забезпечують функції загального призначення та використовуються реєстрами

|xref:architecture/registry/administrative/overview.adoc[Адміністративна зона реєстру]
|Cукупність підсистем, які забезпечують функції розробки, розгортання та обслуговування регламенту реєстру

|xref:architecture/registry/operational/overview.adoc[Операційна зона реєстру]
|Cукупність підсистем, які забезпечують функціонування реєстру згідно розгорнутого регламенту

|xref:architecture/maintenance/overview.adoc[Підсистема обслуговування Платформи]
|Підсистема, яка забезпечує встановлення та оновлення платформи технічним адміністратором.

|xref:architecture/data-exchange/overview.adoc[Шлюз безпечного обміну "Трембіта"]
|Підсистема, яка забезпечує приєднання та комунікацію з системою електронної взаємодії державних електронних інформаційних ресурсів «Трембіта».

|xref:architecture/container-platform/container-platform.adoc[Платформа оркестрації контейнерів]
|Платформа оркестрації контейнерів _OpenShift_ для забезпечення можливостей розгортання рішення в будь-якому публічному хмарному середовищі, приватному хмарному середовищі або на власній локальній інфраструктурі.
|===

== Опис взаємодії

...

== Архітектурні принципи

[NOTE]
--
Перелік архітектурних принципів у процесі формування...
--

* _Платформа Реєстрів_ побудована з використанням відкритих стандартів на базі технологій з відкритим кодом.
* _Платформа Реєстрів_ представляє собою розподілену систему з мікросервісною архітектурою, кожен компонент якої має чітко визначену функцію, а міжкомпонентна взаємодія базується на стандартизованих протоколах інформаційного обміну.
* _Платформа Реєстрів_ є _Cloud-native_ системою, яка побудована на базі платформи оркестрації контейнерів _OpenShift_ для забезпечення надійності, масштабованості та незалежності від інфраструктури.
* _Платформа Реєстрів_ використовує _GitOps_-підхід для автоматизації налаштування інфраструктури, розгортання компонентів та системи в цілому.
* _Платформа Реєстрів_ базується на принципах безпеки _Zero-Trust_ для забезпечення захищеної міжсервісної взаємодії з використанням обов'язкової аутентифікації, авторизації та шифрування трафіку.
* Зовнішній доступ до компонентів _Платформа Реєстрів_ надається через API-шлюзи з обов'язковою автентифікацією та авторизацією.
* Компоненти _Платформи Реєстрів_ використовують стандартизований підхід до експортування метрик моніторингу, даних трасування бізнес-транзакцій та журналювання подій.
* Екземпляри компонентів _Платформи Реєстрів_ не зберігають критичних даних стану системи або даних сесій користувачів в пам'яті.
* Всі дії користувачів над даними та системно-важливі події _Платформи Реєстрів_ підлягають обов'язковій фіксації в журналі аудиту.
* Бізнес-дані реєстрів, які розгорнуті на _Платформи Реєстрів_ підлягають обов'язковому шифруванню для довгострокового зберігання.