= Атрибути якості Платформи

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== _Portability_

_Даний атрибут якості визначає ступінь незалежності системи від типу інфраструктури, на якій вона може бути розгорнута._

В архітектуру рішення _Платформи Реєстрів_ закладено можливості розгортання в публічному та приватному хмарних середовищах або на власній локальній інфраструктурі.

За процедуру встановлення відповідає xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи], який розроблено з урахуванням сумісності між різними постачальниками інфраструктури.

Поточна версія _Платформи Реєстрів_ має задокументовані та протестовані процедури на прикладі двох типів хмарної інфраструктури:

* Публічне хмарне середовище (_AWS_)
* Приватне хмарне середовище (_vSphere_)

[TIP]
--
Детальніше з процедурою встановлення _Платформи Реєстрів_ можна ознайомитись у відповідних розділах:

* xref:admin:installation/platform-deployment/platform-vsphere-deployment.adoc[Розгортання Платформи в цільовому ЦОД на базі приватної хмари vSphere]
* xref:admin:installation/platform-deployment/platform-aws-deployment.adoc[Розгортання Платформи з нуля в AWS-середовищі]

Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи]
* xref:architecture/container-platform/container-platform.adoc#_portability[Платформа оркестрації контейнерів]
--

== _Scalability_

_Даний атрибут якості визначає здатність системи опрацьовувати підвищення навантаження без значного впливу на загальну продуктивність, або здатність швидко адаптуватись завдяки збільшенню ресурсів._

_Платформа Реєстрів_ побудована на базі платформи оркестрації контейнерів _OpenShift_...

[TIP]
--
Детальніше з процедурою масштабування _Платформи Реєстрів_ можна ознайомитись у відповідних розділах:

* xref:admin:scaling/vertical-scaling-master-nodes.adoc[Вертикальне масштабування master nodes для OKD у AWS та vSphere]
* xref:admin:file-system/ceph_scaling.adoc[Масштабування розміру файлової системи Ceph]
* xref:architecture/container-platform/cluster_node_autoscaler.adoc[Автоматичне горизонтальне масштабування екземплярів нод кластера]

Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:arch:architecture/container-platform/container-platform.adoc#_scalability[Платформа оркестрації контейнерів]
* xref:arch:architecture/registry/operational/relational-data-storage/overview.adoc#_scalability[Підсистема управління реляційними базами даних]
* xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc#_scalability[Підсистема управління нереляційними базами даних]
* xref:arch:architecture/platform/operational/distributed-data-storage/overview.adoc#_scalability[Підсистема розподіленого зберігання даних]
--

== _Performance_

_Даний атрибут якості визначає здатність системи опрацьовувати будь-який запит у межах визначеного інтервалу часу та забезпечувати обробку необхідної кількості запитів у визначений інтервал часу без погіршення показників часу, відведеного на їх опрацювання._

Вимоги до продуктивності _Платформи Реєстрів_ поділяються на дві основні категорії:

* _Latency_ - затримка / час необхідний для опрацювання запиту (_95 процентиль_)
** Операція читання (за ключем та одним полем, без запитів до сторонніх реєстрів): ~ 33 мс
** Операція запису: ~ 911 мс

* _Throughput_ - пропускна здатність системи, що задається кількістю опрацьованих запитів за час
** Операція читання: 110.83 запитів/с
** Операція запису: 59.438 запитів/с
** Усереднена для усіх типів запитів, включно з логіном, опрацюванням бізнес-процесів: 408 запитів/c

[TIP]
--
Детальніше з результатами тестування продуктивності можна ознайомитись у відповідних розділах:

* xref:testing:perf-test/1-9-5/perf-test-1-9-5-1500-1.adoc[Тестування продуктивності Платформи 1.9.5 при навантаженні 1500 користувачів на 1 годину]
* xref:testing:perf-test/1-9-5/perf-test-1-9-5-1500-8.adoc[Тестування продуктивності Платформи 1.9.5 при навантаженні 1500 користувачів на 8 годин]
--