= Атрибути якості Платформи

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== _Portability_

_Даний атрибут якості визначає ступінь незалежності системи від типу інфраструктури, на якій вона може бути розгорнута._

В архітектуру рішення _Платформи Реєстрів_ закладено можливості розгортання в публічному та приватному хмарних середовищах або на власній локальній інфраструктурі.

За процедуру встановлення відповідає xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи], який розроблено з урахуванням сумісності між різними постачальниками інфраструктури.

Поточна версія _Платформи Реєстрів_ має задокументовані та протестовані процедури на прикладі двох типів хмарної інфраструктури:

* Публічне хмарне середовище (_AWS_)
* Приватне хмарне середовище (_vSphere_)

[TIP]
--
Детальніше з процедурою встановлення _Платформи Реєстрів_ можна ознайомитись у відповідних розділах:

* xref:admin:installation/platform-deployment/platform-vsphere-deployment.adoc[Розгортання Платформи в цільовому ЦОД на базі приватної хмари vSphere]
* xref:admin:installation/platform-deployment/platform-aws-deployment.adoc[Розгортання Платформи з нуля в AWS-середовищі]

Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи]
* xref:architecture/container-platform/container-platform.adoc#_portability[Платформа оркестрації контейнерів]
--

== _Scalability_

_Даний атрибут якості визначає здатність системи опрацьовувати підвищення навантаження без значного впливу на загальну продуктивність, або здатність швидко адаптуватись завдяки збільшенню ресурсів._

_Платформа Реєстрів_ побудована на базі xref:arch:architecture/container-platform/container-platform.adoc[платформи оркестрації контейнерів _OpenShift_], що забезпечує можливості ефективного масштабування підсистем та компонентів реєстру відповідно до поточного навантаження.

xref:arch:architecture/platform/administrative/control-plane/overview.adoc[Підсистема управління Платформою та Реєстрами] надає адміністраторам веб-інтерфейс управління ресурсами кластера та реєстрів з підтримкою двох підходів до масштабування:

* _Вертикальне масштабування_ (_scale-up_) - виділення додаткових ресурсів CPU та пам'яті окремим компонентам, зміни типів та характеристик віртуальних машин кластера, збільшення розмірів системних дисків, тощо.
* _Горизонтальне масштабування_ (_scale-out_) - збільшення ресурсів кластера та реєстру шляхом розгортання додаткових віртуальних машин, створення додаткових копій компонентів з ціллю балансування навантаження, тощо.

[TIP]
--
Детальніше з процедурою масштабування _Платформи Реєстрів_ можна ознайомитись у відповідних розділах:

* xref:admin:scaling/vertical-scaling-master-nodes.adoc[Вертикальне масштабування master nodes для OKD у AWS та vSphere]
* xref:admin:file-system/ceph_scaling.adoc[Масштабування розміру файлової системи Ceph]
* xref:architecture/container-platform/cluster_node_autoscaler.adoc[Автоматичне горизонтальне масштабування екземплярів нод кластера]

Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:arch:architecture/container-platform/container-platform.adoc#_scalability[Платформа оркестрації контейнерів]
* xref:arch:architecture/registry/operational/relational-data-storage/overview.adoc#_scalability[Підсистема управління реляційними базами даних]
* xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc#_scalability[Підсистема управління нереляційними базами даних]
* xref:arch:architecture/platform/operational/distributed-data-storage/overview.adoc#_scalability[Підсистема розподіленого зберігання даних]
--

== _Performance_

_Даний атрибут якості визначає здатність системи опрацьовувати будь-який запит у межах визначеного інтервалу часу та забезпечувати обробку необхідної кількості запитів у визначений інтервал часу без погіршення показників часу, відведеного на їх опрацювання._

Вимоги до продуктивності _Платформи Реєстрів_ представлені двома ключовими метриками:

* _Latency_ - часова затримка між відправкою запиту та отриманням відповіді системи (_95-й процентиль_)
* _Throughput_ - пропускна здатність системи, що задається кількістю опрацьованих запитів за визначений час

При визначенні цільових значень для вищезгаданих метрик, враховується класифікація реєстрів, умови експлуатації та прогнозоване навантаження.

Реєстри за цільовим призначенням поділяються на:

* _Стратегічні_
* _Тактичні_
* _Оперативні_

Умови експлуатації за навантаженням поділяються на:

* _Продуктивні години_
* _Години пік_
* _Вечірні години_
* _Тіньові години_

.Цільові значення метрик продуктивності для стратегічного реєстру
|===
.2+|Метрика .2+|Тип запиту 4+^|Цільове значення
|_Продуктивні години_|_Години пік_|_Вечірні години_|_Тіньові години_
.2+|_Latency (мс)_|Операція читання (за ключем та одним полем, без запитів до сторонніх реєстрів)|`1000`|`1500`|`1000`|`1000`
|Операція запису|`3000`|`4500`|`3000`|`3000`
.2+|_Throughput (запитів/c)_|Операція читання|`500`|`1000`|`200`|`100`
|Операція запису|`5`|`10`|`5`|`0`
|===

.Цільові значення метрик продуктивності для тактичного реєстру
|===
.2+|Метрика .2+|Тип запиту 4+^|Цільове значення
|_Продуктивні години_|_Години пік_|_Вечірні години_|_Тіньові години_
.2+|_Latency (мс)_|Операція читання (за ключем та одним полем, без запитів до сторонніх реєстрів)|`1500`|`2000`|`1500`|`1500`
|Операція запису|`3500`|`5000`|`3500`|`3500`
.2+|_Throughput (запитів/c)_|Операція читання|`200`|`400`|`75`|`50`
|Операція запису|`5`|`10`|`5`|`0`
|===

.Цільові значення метрик продуктивності для оперативного реєстру
|===
.2+|Метрика .2+|Тип запиту 4+^|Цільове значення
|_Продуктивні години_|_Години пік_|_Вечірні години_|_Тіньові години_
.2+|_Latency (мс)_|Операція читання (за ключем та одним полем, без запитів до сторонніх реєстрів)|`1500`|`2000`|`1500`|`1500`
|Операція запису|`3500`|`5000`|`3500`|`3500`
.2+|_Throughput (запитів/c)_|Операція читання|`50`|`75`|`30`|`10`
|Операція запису|`5`|`10`|`5`|`0`
|===

[TIP]
--
Детальніше з результатами тестування продуктивності можна ознайомитись у відповідних розділах:

* xref:testing:perf-test/1-9-5/perf-test-1-9-5-1500-1.adoc[Тестування продуктивності Платформи 1.9.5 при навантаженні 1500 користувачів на 1 годину]
* xref:testing:perf-test/1-9-5/perf-test-1-9-5-1500-8.adoc[Тестування продуктивності Платформи 1.9.5 при навантаженні 1500 користувачів на 8 годин]
--