= Архітектура розгортання Платформи
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

За процедуру інсталяції _Платформи Реєстрів_ відповідає xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи],
що розроблений з урахуванням сумісності між різними постачальниками інфраструктури.

За процедуру інсталяції _Платформи оркестрації контейнерів OpenShift_ відповідає https://github.com/okd-project/okd/releases[OKD installer] від _RedHat_.

[TIP]
--
Детальніше з процедурою встановлення _Платформи оркестрації контейнерів OpenShift_ та _Платформи Реєстрів_ можна ознайомитись у відповідних розділах:

* xref:admin:installation/platform-deployment/platform-deployment-overview.adoc[]

Детальніше з технічним дизайном підсистем та компонент, які залучені в інсталяції, можна ознайомитись у розділах:

* xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи]
* xref:architecture/container-platform/container-platform.adoc#_portability[Платформа оркестрації контейнерів]
--

Подана діаграма показує розгортання інфраструктури _Платформи Реєстрів_ в одному регіоні (_AZ_) публічного хмарного середовища _AWS_.

.Архітектура розгортання _Платформи Реєстрів_ в _AWS_-середовищі
image::architecture/ddm-platform-infrastructure-deployment.drawio.svg[]