= Атрибути якості Платформи

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Observability

Даний атрибут якості визначає здатність системи фіксувати та надавати детальну інформацію у вигляді журналів подій, метрик моніторингу та даних трасування транзакцій користувачів з ціллю спрощення ідентифікації та вирішення проблем адміністраторами системи.

[TIP]
--
Детальніше можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/monitoring/overview.adoc[Підсистема моніторингу подій та сповіщення]
* xref:arch:architecture/platform/operational/logging/overview.adoc[Підсистема журналювання подій]
* xref:arch:architecture/platform/operational/distributed-tracing/overview.adoc[Підсистема трасування запитів]
--

== Interoperability

Даний атрибут якості визначає здатність системи ефективно взаємодіяти з іншими системами з ціллю інформаційного обміну.

[TIP]
--
Детальніше можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/operational/external-integrations/overview.adoc[Підсистема зовнішніх інтеграцій]
* xref:arch:architecture/data-exchange/overview.adoc[Шлюз безпечного обміну "Трембіта"]
--

== Auditability

Даний атрибут якості визначає здатність системи фіксувати та надавати інформацію про значимі технічні та бізнес події, пов'язані з експлуатацією системи кінцевими користувачами. Надана інформація може бути використана для виявлення та вирішення проблем в коректності функціонування системи.

[TIP]
--
Детальніше можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/operational/audit/overview.adoc[Підсистема журналювання подій аудиту]
--

== Reliability

== Performance

== Security

== Operability

== Maintainability

== Supportability

== Modifiability

== Accessibility

== Usability
