= Архітектура Платформи

image::architecture/ddm-platform-context.svg[]

[TIP]
--
Детальніше з категоріями користувачів Платформи Реєстрів можна ознайомитись у розділі xref:arch:architecture/platform/operational/user-management/platform-actors-roles.adoc[].
--

== Архітектурні принципи

* [*] Платформа побудована на принципах [.underline]#мікросервісної архітектури# на базі хмарної інфраструктури, побудованої на основі https://www.okd.io/[OKD].

* [*] Один екземпляр Платформи підтримує розгортання та роботу декількох реєстрів.

* [*] Платформа відповідає належним безпековим вимогам https://cip.gov.ua/ua/news/perelik-dokumentiv-sistemi-tekhnichnogo-zakhistu-informaciyi-nd-tzi[НД ТЗІ] та https://cip.gov.ua/ua/news/poradi-rekomendaciyi-shodo-stvorennya-kszi-v-its-yaki-vikoristovuyutsya-dlya-nadannya-poslug-dostupu-do-merezhi-internet[КСЗІ], і є [.underline]#відмовостійкою#.

* [*] Розробка реєстру, що розгорнуто на Платформі, базується на принципах https://en.wikipedia.org/wiki/Low-code_development_platform[Low-code] (https://bpmn.io/[BPMN], користувацькі форми, Декларативний опис API для бази даних, REST API-взаємодія між сервісами").

* [*] Система підтримує [.underline]#логування (фіксацію подій)# та [.underline]#моніторинг# компонентів реєстру.
+
Таким чином усі зміни на платформі та в реєстрах і доступи до даних логуються. Журнали доступу надійно захищені від змін.

* [*] Система забезпечує [.underline]#резервне копіювання компонентів та даних# реєстру, центральних компонентів платформи, а також відновлення майстер-нод кластера OpenShift. Це убезпечує користувачів від втрати будь-яких критично важливих даних.

* [*] Платформа забезпечує [.underline]#надійний захист конфіденційних даних#. Конфіденційні дані надійно захищені від непередбаченого доступу і «витоку» інформації.

* [*] Платформа забезпечує [.underline]#надійність зберігання даних#, завдяки чому база даних кожного окремого реєстру захищена від втрати даних та знищення.

* [*] Платформа дозволяє [.underline]#зберігати всю історію змін#. З реєстру дані не видаляються. Оновлення даних відбувається з обов'язковим збереженням версійності. Журнал транзакцій захищений від змін.

* [*] Платформа підтримує [.underline]#транзакційну модель змін# у реєстрі. Зміни до бази даних не виконуються напряму. Усі дії з БД проводяться лише у межах регламентованих бізнес-процесів. Усі транзакції є підтверджені (наприклад, запити на зміни, підписані КЕП тощо).

* [*] Платформа [.underline]#унеможливлює несанкціоновані зміни#. Зміни у даних реєстру неможливі:

** без відповідних прав доступу (згідно зі змодельованими бізнес-процесами);
** без автентифікації та авторизації;
** за межами регламентованих бізнес-процесів.

* [*] Платформа забезпечує [.underline]#можливість розподілу прав# на основі xref:registry-develop:bp-modeling/bp/access/roles-rbac-bp-modelling.adoc[RBAC]. Розподіл прав організовано таким чином, що немає «супер адміністратора», який може виконати будь-які дії у системі. Це дозволяє нівелювати ризики незаконних дій із даними системи.

== Атрибути якості

* [*]  Performance
* [*]  Security
* [*]  Scalability
* [*]  Reliability
* [*]  Installability
* [*]  Portability
* [*]  Operability
* [*]  Observability
* [*]  Interoperability
* [*]  Auditability
* [*]  Maintainability
* [*]  Supportability
* [*]  Modifiability
* [*]  Accessibility
* [*]  Usability