= Логічна архітектура Платформи
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

_Платформа Реєстрів_ -- це розподілена система з мікросервісною архітектурою, в дизайн якої закладено декілька важливих ідей:

* Незалежність від інфраструктури для розгортання
* Централізованість розробки та розповсюдження оновлень
* Забезпечення _достатнього_ рівня ізоляції реєстрів
* Сумісне (_пере-_)використання типових служб реєстрами
* Використання захищеного транспорту для інтеграцій
* Відповідність реєстрів вимогам безпеки, масштабованості та відмовостійкості

== Архітектурні принципи

* _Платформа Реєстрів_ побудована з використанням відкритих стандартів на базі технологій з відкритим кодом.
* _Платформа Реєстрів_ є розподіленою системою з мікросервісною архітектурою, кожен компонент якої має чітко визначену функцію, а міжкомпонентна взаємодія базується на стандартизованих протоколах інформаційного обміну.
* _Платформа Реєстрів_ є _Cloud-native_ системою, яка побудована на базі платформи оркестрації контейнерів _OpenShift_ для забезпечення надійності, масштабованості та незалежності від інфраструктури.
* _Платформа Реєстрів_ використовує _GitOps_-підхід для автоматизації налаштування інфраструктури, розгортання компонентів та системи в цілому.
* _Платформа Реєстрів_ реалізує комплексний підхід до кібербезпеки, що включає обов'язкову аутентифікацію та авторизацію всіх взаємодійних сервісів, суворий контроль доступу, а також шифрування даних у русі для забезпечення їхнього захисту.
* Зовнішній доступ до компонентів _Платформа Реєстрів_ надається через _API_-шлюзи з обов'язковою автентифікацією та авторизацією.
* Компоненти _Платформи Реєстрів_ використовують стандартизований підхід до експортування метрик моніторингу, даних трасування бізнес-транзакцій та журналювання подій.
* Екземпляри компонентів _Платформи Реєстрів_ не зберігають критичних даних стану системи або даних сесій користувачів в пам'яті.
* Всі дії користувачів над даними та системно-важливі події _Платформи Реєстрів_ підлягають обов'язковій фіксації в журналі аудиту.
* Бізнес-дані реєстрів, які розгорнуті на _Платформи Реєстрів_ підлягають обов'язковому шифруванню для довгострокового зберігання.

== Високорівнева структура

На даній структурній діаграмі зображено декомпозицію _Платформи Реєстрів_ на _рівні_, _зони_, _підсистеми_ та загальні сценарії їх взаємодії.

Окремий рівень системи може включати дві зони з підсистемами, які відповідають за обслуговування адміністративного та операційного трафіку.

Підсистеми, своєю чергою, складаються з сукупності сервісів, які адресують блок функціональних та нефункціональних вимог.

image::architecture/ddm-platform-structural-view.svg[]

=== _Інфраструктура_

_Платформа Реєстрів_ підтримує розгортання в публічному та приватному хмарному середовищі.

[TIP]
--
Детальніше можна ознайомитись у відповідних розділах:

* xref:admin:installation/platform-deployment/platform-deployment-overview.adoc[]
--

=== _Платформа оркестрації контейнерів_

[TIP]
--
Детальніше можна ознайомитись у відповідних розділах:

* xref:architecture/container-platform/container-platform.adoc[]
--

=== _Центральні компоненти Платформи_

Кожен екземпляр _Платформи Реєстрів_ включає рівень _Центральних компонентів Платформи_, який складається з двох логічних зон:

* xref:architecture/platform/administrative/overview.adoc[] - сукупність підсистем, які забезпечують функції адміністрування екземпляра Платформи та реєстрів, які на ній розгорнуті
* xref:architecture/platform/operational/overview.adoc[] - сукупність підсистем, які забезпечують функції загального призначення для сумісного використання реєстрами

=== _Реєстри_

Один екземпляр _Платформи Реєстрів_ може обслуговувати групу реєстрів, ізольованих один від одного. Кожен тенант реєстру представлений двома окремими зонами:

* xref:architecture/registry/administrative/overview.adoc[] -- сукупність підсистем, які забезпечують функції розробки, розгортання та обслуговування цифрового регламенту реєстру
* xref:architecture/registry/operational/overview.adoc[] -- сукупність підсистем, які забезпечують функціонування реєстру згідно з розгорнутим цифровим регламентом.

=== _Компонент керування станом ресурсів Платформи_

[TIP]
--
Детальніше можна ознайомитись у відповідних розділах:

* xref:architecture/platform-installer/overview.adoc[]
--

=== _Шлюз безпечного обміну "Трембіта"_

[TIP]
--
Детальніше можна ознайомитись у відповідних розділах:

* xref:architecture/data-exchange/overview.adoc[]
--

=== _Програмно-апаратний криптомодуль "Гряда"_

[TIP]
--
Детальніше можна ознайомитись у відповідних розділах:

* xref:architecture/network-crypto-module/overview.adoc[]
--