= Атрибути якості Платформи

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== _Portability_

_Даний атрибут якості визначає ступінь незалежності системи від типу інфраструктури, на якій вона може бути розгорнута._

В архітектуру рішення _Платформи Реєстрів_ закладено можливості розгортання в публічному та приватному хмарних середовищах або на власній локальній інфраструктурі.

За процедуру встановлення відповідає xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи], який розроблено з урахуванням сумісності між різними постачальниками інфраструктури.

Поточна версія _Платформи Реєстрів_ має задокументовані та протестовані процедури на прикладі двох типів хмарної інфраструктури:

* Публічне хмарне середовище (_AWS_)
* Приватне хмарне середовище (_vSphere_)

[TIP]
--
Детальніше з процедурою встановлення _Платформи Реєстрів_ можна ознайомитись у відповідних розділах:

* xref:admin:installation/platform-deployment/platform-vsphere-deployment.adoc[Розгортання Платформи в цільовому ЦОД на базі приватної хмари vSphere]
* xref:admin:installation/platform-deployment/platform-aws-deployment.adoc[Розгортання Платформи з нуля в AWS-середовищі]

Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи]
* xref:architecture/container-platform/container-platform.adoc#_portability[Платформа оркестрації контейнерів]
--

== _Scalability_

_Даний атрибут якості визначає здатність системи опрацьовувати підвищення навантаження без значного впливу на загальну продуктивність, або здатність швидко адаптуватись завдяки збільшенню ресурсів._

_Платформа Реєстрів_ побудована на базі xref:arch:architecture/container-platform/container-platform.adoc[платформи оркестрації контейнерів _OpenShift_], що забезпечує можливості ефективного масштабування підсистем та компонентів реєстру відповідно до поточного навантаження. Це включає здатність відслідковувати використання ресурсів та застосовувати вертикальне або горизонтальне масштабування згідно заданих правил, автоматично створюючи та розгортаючи додаткові ресурси, такі як нові контейнери або віртуальні машини, для обробки збільшеного навантаження, а також здатність видаляти ресурси під час періодів зниженого попиту для оптимізації використання ресурсів та коштів.

_Платформа Реєстрів_ надає можливості управління ресурсами кластера та реєстрів за допомогою веб-інтерфейсу xref:arch:architecture/platform/administrative/control-plane/overview.adoc[Підсистеми управління Платформою та Реєстрами] та декларативної конфігурації наявних механізмів _OpenShift_:

* *_HPA_* (_Horizontal Pod Autoscaler_)
* *_HNA_* (_Horisontal Node Autoscaler_)

[TIP]
--
Детальніше з процедурою масштабування _Платформи Реєстрів_ можна ознайомитись у відповідних розділах:

* xref:admin:scaling/vertical-scaling-master-nodes.adoc[Вертикальне масштабування master nodes для OKD у AWS та vSphere]
* xref:admin:file-system/ceph_scaling.adoc[Масштабування розміру файлової системи Ceph]
* xref:architecture/container-platform/cluster_node_autoscaler.adoc[Автоматичне горизонтальне масштабування екземплярів нод кластера]

Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:arch:architecture/container-platform/container-platform.adoc#_scalability[Платформа оркестрації контейнерів]
* xref:arch:architecture/registry/operational/relational-data-storage/overview.adoc#_scalability[Підсистема управління реляційними базами даних]
* xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc#_scalability[Підсистема управління нереляційними базами даних]
* xref:arch:architecture/platform/operational/distributed-data-storage/overview.adoc#_scalability[Підсистема розподіленого зберігання даних]
--

== _Performance_

_Даний атрибут якості визначає здатність системи опрацьовувати будь-який запит у межах визначеного інтервалу часу та забезпечувати обробку необхідної кількості запитів у визначений інтервал часу без погіршення показників часу, відведеного на їх опрацювання._

Вимоги до продуктивності _Платформи Реєстрів_ представлені двома ключовими метриками:

* _Latency_ - часова затримка між відправкою запиту та отриманням відповіді системи (_95-й процентиль_)
* _Throughput_ - пропускна здатність системи, що задається кількістю опрацьованих запитів за визначений час

При визначенні цільових значень для вищезгаданих метрик, враховується класифікація реєстрів, умови експлуатації та прогнозоване навантаження.

Реєстри за цільовим призначенням поділяються на:

* _Стратегічні_
* _Тактичні_
* _Оперативні_

Умови експлуатації за навантаженням поділяються на:

* _Продуктивні години_
* _Години пік_
* _Вечірні години_
* _Тіньові години_

Відповідно до вимог, заданих оперативному реєстру, _Платформа_ має забезпечувати досягнення значень цільових метрик _latency_ (затримка) та _throughput_ (пропускна здатність) при планованому повному навантаженні в робочий час.

.Цільові значення метрик продуктивності оперативного реєстру
|===
|Метрика|Тип запиту|Цільове значення
.2+|_Latency_|Операція читання (за ключем та одним полем, без запитів до сторонніх реєстрів)|`1500 мс`
|Операція запису|`3500 мс`
.2+|_Throughput_|Операція читання|`50 запитів/c`
|Операція запису|`5 запитів/c`
|===

[TIP]
--
Детальніше з результатами тестування продуктивності можна ознайомитись у відповідних розділах:

* xref:testing:perf-test/1-9-5/perf-test-1-9-5-1500-1.adoc[Тестування продуктивності Платформи 1.9.5 при навантаженні 1500 користувачів на 1 годину]
* xref:testing:perf-test/1-9-5/perf-test-1-9-5-1500-8.adoc[Тестування продуктивності Платформи 1.9.5 при навантаженні 1500 користувачів на 8 годин]
--