= Діаграма розгортання Платформи

== Діаграма розгортання Платформної інфраструктури

За процедуру інсталяції Платформи реєстрів відповідає xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи],
що розроблений з урахуванням сумісності між різними постачальниками інфраструктури.

За процедуру інсталяції Платформи оркестрації контейнерів OpenShift відповідає https://github.com/okd-project/okd/releases[OKD installer],
що розроблен та постачаєтся RedHat.

Дана діаграма відображає розгортання ресурсів в публічному хмарному середовищі AWS.

[TIP]
--
Детальніше з процедурою встановлення _Платформи оркестрації контейнерів OpenShift_ та _Платформи Реєстрів_ можна ознайомитись у відповідних розділах:

* xref:admin:installation/platform-deployment/platform-deployment-overview.adoc[]

Детальніше з технічним дизайном підсистем та компонент, які задіяні в інсталяції, можна ознайомитись у розділах:

* xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи]
* xref:architecture/container-platform/container-platform.adoc#_portability[Платформа оркестрації контейнерів]
--

.Платформна архітектура на AWS
image::architecture/ddm-platform-infrastructure-deployment.drawio.svg[]
