= Архітектура розгортання Платформи

== Загальний опис

За процедуру інсталяції _Платформи Реєстрів_ відповідає xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи],
що розроблений з урахуванням сумісності між різними постачальниками інфраструктури.

За процедуру інсталяції _Платформи оркестрації контейнерів OpenShift_ відповідає https://github.com/okd-project/okd/releases[OKD installer] від _RedHat_.

[TIP]
--
Детальніше з процедурою встановлення _Платформи оркестрації контейнерів OpenShift_ та _Платформи Реєстрів_ можна ознайомитись у відповідних розділах:

* xref:admin:installation/platform-deployment/platform-deployment-overview.adoc[]

Детальніше з технічним дизайном підсистем та компонент, які задіяні в інсталяції, можна ознайомитись у розділах:

* xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи]
* xref:architecture/container-platform/container-platform.adoc#_portability[Платформа оркестрації контейнерів]
--

На даній діаграмі зображено розгортання інфраструктури _Платформи Реєстрів_ в одному регіоні (_AZ_) публічного хмарного середовища _AWS_.

.Архітектура розгортання _Платформи Реєстрів_ на _AWS_
image::architecture/ddm-platform-infrastructure-deployment.drawio.svg[]