= Архітектура Платформи

== Загальний опис

_Платформа Реєстрів_ - це інформаційна система для швидкого створення, моделювання, розгортання та обслуговування державних реєстрів з ціллю ефективного надання державних послуг в цифровому вигляді.

Головною метою рішення є реалізація _децентралізованого_ та _регульованого_ підходу в управлінні державними реєстрами та забезпечення оптимального балансу між вимогами до безпеки даних, інтероперабельністю, швидкістю розгортання та вартістю володіння реєстрами.

== Контекст рішення

На даній контекстній діаграмі зображено _Платформу Реєстрів_ в екосистемі державних інформаційних систем, з якими побудована інформаційна взаємодія та категорії користувачів, які взаємодіють з системою.

Для забезпечення інтероперабельності, _Платформа Реєстрів_ підтримує дві основні опції налаштування інформаційного обміну:

* Через використання шини безпечного обміну "_Трембіта_" у якості захищеного транспорту
* Через налаштування прямих інтеграцій на базі _REST_ та _SOAP_ протоколів взаємодії для систем, які не є учасниками інформаційного обміну _СЕВДЕІР "Трембіта"_

У якості зовнішніх систем для інтеграції можуть виступати як існуючі інформаційні системи, так і реєстри розгорнуті на окремих екземплярах _Платформи Рєестрів_.

image::architecture/ddm-platform-context.svg[]

[TIP]
--
Детальніше з технічним дизайном _Платформи Реєстрів_ можна ознайомитись у розділі xref:arch:architecture/platform-solution-structure.adoc[].
--

== Користувачі Платформи

Основних користувачів _Платформи Рєестрів_ можна поділити на наступні категорії в залежності від сценаріїв взаємодії з системою та прав доступу:

* _Неавторизовані користувачі_ - користувачі, які мають доступ виключно до публічних даних та сторінки автентифікації.
* _Отримувачі послуг_ - фізичні або юридичні особи, які пройшли автентифікацію та самореєстрацію в реєстрі з ціллю отримання електронних послуг.
* _Надавачі послуг_ - офіційні представники державних органів, які надають послуги в рамках своїх службових обов'язків або особи, які зареєструвались у якості надавачів послуг (в залежності від вимог окремого реєстру).
* _Службові адміністратори_ та _Адміністратори інфраструктури_ - категорія користувачів, які відповідають за встановлення та обслуговування _Платформи Реєстрів_ та екземплярів реєстрів, які на ній розгорнуті.

[TIP]
--
Детальніше з категоріями користувачів Платформи Реєстрів можна ознайомитись у розділі xref:arch:architecture/platform/operational/user-management/platform-actors-roles.adoc[].
--

== Взаємодія з зовнішніми системами

=== _Акредитований Центр Сертифікації Ключів (АЦСК)_

_Платформа Реєстрів_ взаємодіє з _Акредитованими Центрами Сертифікації Ключів_ з ціллю отримання переліку відкликаних сертифікатів, отримання ланцюжка сертифікатів користувача та перевірку їх статусу, формування мітки часу, тощо.

=== _Сервіс цифрової ідентифікації (id.gov.ua)_

_Платформа Реєстрів_ надає можливість здійснювати автентифікацію отримувачів та надавачів послуг реєстру за допомогою _Інтегрованої системи електронної ідентифікації (ІСЕІ)_.

=== _СЕВДЕІР "Трембіта"_

_Платформа Реєстрів_ інтегрована до _Системи Електронної Взаємодії Державних Електронних Інформаційних Ресурсів (СЕВДЕІР) "Трембіта"_ з ціллю забезпечення захищеного інформаційного обміну даними державних реєстрів та інших інформаційних систем.

=== _Сервіси Дії (diia.gov.ua)_

_Платформа Реєстрів_ інтегрована з екосистемою державних сервісів цифрових послуг _Дія_ для покращення та забезпечення цілісності досвіду отримання державних послуг кінцевими користувачами.

=== _Зовнішні картографічні сервіси_

_Платформа Реєстрів_ використовує зовнішні картографічні сервіси для завантаження геопросторових даних, шарів та геокодування з ціллю забезпечення можливостей внесення, пошуку та відображення об'єктів реєстру, які мають прив’язку до місцевості.

=== _Зовнішні системи_

_Платформа Реєстрів_ підтримує налаштування зовнішніх інтеграцій через _ШБО "Трембіта"_ або прямих інтеграцій згідно вимог цільових реєстрів та рівню інтероперабельності зовнішніх систем.

== Архітектурні принципи

[NOTE]
--
Перелік архітектурних принципів у процесі формування...
--

* _Платформа Реєстрів_ представляє собою розподілену систему з мікросервісною архітектурою, кожен компонент якої має чітко визначену функцію, а міжкомпонентна взаємодія базується на стандартизованих протоколах інформаційного обміну.
* _Платформа Реєстрів_ є контейнеризованою системою, яка побудована на базі платформи оркестрації контейнерів _OpenShift_ для забезпечення надійності, масштабованості та незалежності від інфраструктури.
* _Платформа Реєстрів_ використовує _GitOps_-підхід до автоматизації налаштування інфраструктури, розгортання компонентів та системи в цілому.
* _Платформа Реєстрів_ використовує _OpenShift Operator SDK_ для автоматизації розгортання та налаштування компонентів системи.
* Екземпляри компонентів _Платформи Реєстрів_ не зберігають критичних даних стану системи в пам'яті та є рівнозначними.
* Компоненти _Платформи Реєстрів_ підтримують вертикальне та горизонтальне масштабування в залежності від навантаження на систему.
* Компоненти _Платформи Реєстрів_ використовують стандартизований підхід до експортування метрик моніторингу, даних трасування бізнес-транзакцій та журналювання подій
* _Платформа Реєстрів_ реалізує шифрування даних при міжкомпонентній взаємодії (_data-in-transit_) та зберіганні (_data-at-rest_).
* ...
* _Платформа Реєстрів_ розділяє зовнішній операційний та адміністративний трафік на рівні окремих API-шлюзів з можливостями налаштування обмежень.
* _Платформа Реєстрів_ включає в себе набір службових компонентів для збору, аналізу та відображення даних моніторингу стану системи, журналів подій, даних трасування бізнес-транзакцій.
* _Платформа Реєстрів_ використовує
* _Платформа Реєстрів_ використовує _Istio Service Mesh_ для управління міжкомпонентною взаємодією та стандартизації підходу до реалізації пов'язаних з нею нефункціональних вимог по безпеці, надійності, тощо.
