= Логічна архітектура Платформи

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

_Платформа Реєстрів_ представляє собою розподілену систему з мікросервісною архітектурою, яка побудована на базі платформи оркестрації контейнерів _OpenShift_.

В основу дизайну рішення закладено декілька ключових ідей:

* Незалежність від інфраструктури для розгортання
* Простота встановлення та розповсюдження оновлень
* Зменшення вартості та вимог до розробки реєстрів
* Забезпечення відповідності реєстрів нефункціональним вимогам
* Оптимізація вартості володіння реєстрами
* Простота адміністрування реєстрів

Концептуально, рішення складається з:

* _Інфраструктура як Сервіс_ - це може бути як публічне або приватне хмарне середовище, так і локальна інфраструктура ЦОД
* _Платформа оркестрації контейнерів_ -
* _Підсистема обслуговування Платформи_ -

image::architecture/ddm-platform-structural-view.svg[]

== Складові рішення

|===
|Назва|Призначення

|xref:architecture/platform/administrative/overview.adoc[Адміністративна зона Платформи]
|Cукупність підсистем, які забезпечують функції управління Платформою Реєстрів

|xref:architecture/platform/operational/overview.adoc[Операційна зона Платформи]
|Cукупність підсистем, які забезпечують функції загального призначення та використовуються реєстрами

|xref:architecture/registry/administrative/overview.adoc[Адміністративна зона реєстру]
|Cукупність підсистем, які забезпечують функції розробки, розгортання та обслуговування регламенту реєстру

|xref:architecture/registry/operational/overview.adoc[Операційна зона реєстру]
|Cукупність підсистем, які забезпечують функціонування реєстру згідно розгорнутого регламенту

|xref:architecture/maintenance/overview.adoc[Підсистема обслуговування Платформи]
|Підсистема, яка забезпечує встановлення та оновлення платформи технічним адміністратором.

|xref:architecture/data-exchange/overview.adoc[Шлюз безпечного обміну "Трембіта"]
|Підсистема, яка забезпечує приєднання та комунікацію з системою електронної взаємодії державних електронних інформаційних ресурсів «Трембіта».

|xref:architecture/container-platform/container-platform.adoc[Платформа оркестрації контейнерів]
|Платформа оркестрації контейнерів _OpenShift_ для забезпечення можливостей розгортання рішення в будь-якому публічному хмарному середовищі, приватному хмарному середовищі або на власній локальній інфраструктурі.
|===

== Опис взаємодії

...

== Архітектурні принципи

[NOTE]
--
Перелік архітектурних принципів у процесі формування...
--

* _Платформа Реєстрів_ представляє собою розподілену систему з мікросервісною архітектурою, кожен компонент якої має чітко визначену функцію, а міжкомпонентна взаємодія базується на стандартизованих протоколах інформаційного обміну.
* _Платформа Реєстрів_ є контейнеризованою системою, яка побудована на базі платформи оркестрації контейнерів _OpenShift_ для забезпечення надійності, масштабованості та незалежності від інфраструктури.
* _Платформа Реєстрів_ використовує _GitOps_-підхід до автоматизації налаштування інфраструктури, розгортання компонентів та системи в цілому.
* _Платформа Реєстрів_ використовує _OpenShift Operator SDK_ для автоматизації розгортання та налаштування компонентів системи.
* Екземпляри компонентів _Платформи Реєстрів_ не зберігають критичних даних стану системи в пам'яті та є рівнозначними.
* Компоненти _Платформи Реєстрів_ підтримують вертикальне та горизонтальне масштабування в залежності від навантаження на систему.
* Компоненти _Платформи Реєстрів_ використовують стандартизований підхід до експортування метрик моніторингу, даних трасування бізнес-транзакцій та журналювання подій
* _Платформа Реєстрів_ реалізує шифрування даних при міжкомпонентній взаємодії (_data-in-transit_) та зберіганні (_data-at-rest_).
* ...
* _Платформа Реєстрів_ розділяє зовнішній операційний та адміністративний трафік на рівні окремих API-шлюзів з можливостями налаштування обмежень.
* _Платформа Реєстрів_ включає в себе набір службових компонентів для збору, аналізу та відображення даних моніторингу стану системи, журналів подій, даних трасування бізнес-транзакцій.
* _Платформа Реєстрів_ використовує
* _Платформа Реєстрів_ використовує _Istio Service Mesh_ для управління міжкомпонентною взаємодією та стандартизації підходу до реалізації пов'язаних з нею нефункціональних вимог по безпеці, надійності, тощо.