= Атрибути якості Платформи

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Portability

Даний атрибут якості визначає ступінь незалежності системи від типу інфраструктури, на якій вона може бути розгорнута.

В архітектуру рішення _Платформи Реєстрів_ закладено можливості розгортання в публічному хмарному середовищі, приватному хмарному середовищі або на власній локальній інфраструктурі.

За процедуру встановлення у цільове середовище відповідає xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи], який розроблено з урахуванням сумісності між різними постачальниками інфраструктури та може бути розширено підтримкою додаткових постачальників інфраструктури за необхідністю.

Наразі _Платформа Реєстрів_ надає перевірені можливості встановлення:

* В публічне хмарне середовище (_AWS_)
* В приватне хмарне середовище (_vSphere_)

[TIP]
--
Детальніше з процедурою встановлення _Платформи Реєстрів_ можна ознайомитись у відповідних розділах:

* xref:admin:installation/platform-deployment/platform-vsphere-deployment.adoc[Розгортання Платформи в цільовому ЦОД на базі приватної хмари vSphere]
* xref:admin:installation/platform-deployment/platform-aws-deployment.adoc[Розгортання Платформи з нуля в AWS-середовищі]

Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:architecture/platform-installer/overview.adoc[Компонент керування станом ресурсів Платформи]
* xref:architecture/container-platform/container-platform.adoc#_portability[Платформа оркестрації контейнерів]
--

== Scalability

Даний атрибут якості визначає здатність системи опрацьовувати підвищення навантаження без значного впливу на загальну продуктивність, або здатність швидко адаптуватись завдяки збільшенню ресурсів.

_Платформа Реєстрів_ побудована на базі платформи оркестрації контейнерів _OpenShift_, що забезпечує можливості ефективного масштабування відповідно до поточного навантаження.

Це включає здатність відслідковувати використання ресурсів та застосовувати вертикальне або горизонтальне масштабування згідно заданих правил, автоматично створюючи та розгортаючи додаткові ресурси, такі як нові контейнери або віртуальні машини, для обробки збільшеного навантаження, а також здатність видаляти ресурси під час періодів зниженого попиту для оптимізації використання ресурсів та коштів.

[TIP]
--
Детальніше з процедурою масштабування _Платформи Реєстрів_ можна ознайомитись у відповідних розділах:

* xref:admin:scaling/vertical-scaling-master-nodes.adoc[Вертикальне масштабування master nodes для OKD у AWS та vSphere]
* xref:architecture/container-platform/cluster_node_autoscaler.adoc[Автоматичне горизонтальне масштабування екземплярів нод кластера]

Детальніше з технічним дизайном підсистем та компонент, які адресують атрибут якості, можна ознайомитись у розділах:

* xref:arch:architecture/container-platform/container-platform.adoc#_scalability[Платформа оркестрації контейнерів]
* xref:arch:architecture/registry/operational/relational-data-storage/overview.adoc#_scalability[Підсистема управління реляційними базами даних]
* xref:arch:architecture/registry/operational/nonrelational-data-storage/overview.adoc#_scalability[Підсистема управління нереляційними базами даних]
* xref:arch:architecture/platform/operational/distributed-data-storage/overview.adoc[Підсистема розподіленого зберігання даних]
--