= Концептуальна архітектура Платформи

== Загальний опис

_Платформа Реєстрів_ - це інформаційна система для швидкого створення, моделювання, розгортання та обслуговування державних реєстрів з ціллю ефективного надання державних послуг в цифровому вигляді.

Головною метою рішення є реалізація _децентралізованого_ та _регульованого_ підходу в управлінні державними реєстрами та забезпечення оптимального балансу між вимогами до безпеки даних, інтероперабельністю, швидкістю розгортання та вартістю володіння реєстрами.

== Концептуальний дизайн

На даній контекстній діаграмі зображено _Платформу Реєстрів_ в екосистемі державних інформаційних систем, з якими побудована інформаційна взаємодія та категорії користувачів, які взаємодіють з системою.

Для забезпечення інтероперабельності, _Платформа Реєстрів_ підтримує дві основні опції налаштування інформаційного обміну:

* Через використання шини безпечного обміну "_Трембіта_" у якості захищеного транспорту
* Через налаштування прямих інтеграцій на базі _REST_ та _SOAP_ протоколів взаємодії для систем, які не є учасниками інформаційного обміну _СЕВДЕІР "Трембіта"_

У якості зовнішніх систем для інтеграції можуть виступати як існуючі інформаційні системи, так і реєстри розгорнуті на окремих екземплярах _Платформи Рєестрів_.

image::architecture/ddm-platform-context.svg[]

[TIP]
--
Детальніше з технічним дизайном _Платформи Реєстрів_ можна ознайомитись у розділі xref:arch:architecture/platform-logical.adoc[].
--

== Користувачі Платформи

Основних користувачів _Платформи Рєестрів_ можна поділити на наступні категорії в залежності від сценаріїв взаємодії з системою та прав доступу:

* _Неавторизовані користувачі_ - користувачі, які мають доступ виключно до публічних даних та сторінки автентифікації.
* _Отримувачі послуг_ - фізичні або юридичні особи, які пройшли автентифікацію та самореєстрацію в реєстрі з ціллю отримання електронних послуг.
* _Надавачі послуг_ - офіційні представники державних органів, які надають послуги в рамках своїх службових обов'язків або особи, які зареєструвались у якості надавачів послуг (в залежності від вимог окремого реєстру).
* _Службові адміністратори_ та _Адміністратори інфраструктури_ - категорія користувачів, які відповідають за встановлення та обслуговування _Платформи Реєстрів_ та екземплярів реєстрів, які на ній розгорнуті.

[TIP]
--
Детальніше з категоріями користувачів Платформи Реєстрів можна ознайомитись у розділі xref:arch:architecture/platform/operational/user-management/platform-actors-roles.adoc[].
--

== Взаємодія з зовнішніми системами

=== _Акредитований Центр Сертифікації Ключів (АЦСК)_

_Платформа Реєстрів_ взаємодіє з _Акредитованими Центрами Сертифікації Ключів_ з ціллю отримання переліку відкликаних сертифікатів, отримання ланцюжка сертифікатів користувача та перевірку їх статусу, формування мітки часу, тощо.

[TIP]
--
Детальніше з дизайном підсистем, в яких задіяна інтеграція, можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/operational/digital-signatures/overview.adoc[]
* xref:arch:architecture/platform/operational/user-management/overview.adoc[]
--

=== _Сервіс цифрової ідентифікації (id.gov.ua)_

_Платформа Реєстрів_ надає можливість здійснювати автентифікацію отримувачів та надавачів послуг реєстру за допомогою _Інтегрованої системи електронної ідентифікації (ІСЕІ)_.

[TIP]
--
Детальніше з дизайном підсистем, в яких задіяна інтеграція, можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/user-management/overview.adoc[]
--

=== _СЕВДЕІР "Трембіта"_

_Платформа Реєстрів_ інтегрована до _Системи Електронної Взаємодії Державних Електронних Інформаційних Ресурсів (СЕВДЕІР) "Трембіта"_ з ціллю забезпечення захищеного інформаційного обміну даними державних реєстрів та інших інформаційних систем.

[TIP]
--
Детальніше з дизайном підсистем, в яких задіяна інтеграція, можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/user-management/overview.adoc[]
* xref:arch:architecture/registry/operational/bpms/overview.adoc[]
* xref:arch:architecture/registry/operational/external-integrations/overview.adoc[]
* xref:arch:architecture/data-exchange/overview.adoc[]
--

=== _Сервіси Дії (diia.gov.ua)_

_Платформа Реєстрів_ інтегрована з екосистемою державних сервісів цифрових послуг _Дія_ для покращення та забезпечення цілісності досвіду отримання державних послуг кінцевими користувачами.

[TIP]
--
Детальніше з дизайном підсистем, в яких задіяна інтеграція, можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/operational/notifications/overview.adoc[]
--

=== _Зовнішні картографічні сервіси_

_Платформа Реєстрів_ використовує зовнішні картографічні сервіси для завантаження геопросторових даних, шарів та геокодування з ціллю забезпечення можливостей внесення, пошуку та відображення об'єктів реєстру, які мають прив’язку до місцевості.

[TIP]
--
Детальніше з дизайном підсистем, в яких задіяна інтеграція, можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/operational/geo/overview.adoc[]
--

=== _Зовнішні системи_

_Платформа Реєстрів_ підтримує налаштування зовнішніх інтеграцій через _ШБО "Трембіта"_ або прямих інтеграцій згідно вимог цільових реєстрів та рівню інтероперабельності зовнішніх систем.

[TIP]
--
Детальніше з дизайном підсистем, в яких задіяна інтеграція, можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/operational/cross-registry-integrations/overview.adoc[]
* xref:arch:architecture/registry/operational/external-integrations/overview.adoc[]
* xref:arch:architecture/registry/operational/bpms/overview.adoc[]
--