= Структура компонента

== Контекст
// Взаємодія з іншими компонентами платформи та опис інтерфейсів

image::arch:architecture/registry/operational/portals/services/officer-portal/officer-portal-services.svg[]

*Критичні залежності:*

- Сервіс керування доступом - впливає на можливість увійти до кабінету, та отримати інформацію про користувача
- Сервіс постачання форм - впливає на можливість отримати JSON метадані форм
- Дата фабрика - впливає на можливість отримання даних з реєстру, які заповнюються на користувацьких формах
- Сервіс управління бізнес процесами - отримання доступних та ініційованих послуг
- Сервіс управління задачами користувача - отримання та виконання задач

*Не критичні залежності:*

- id.gov.ua - впливає на можливість зчитування КЕП та підписання форм
- сервіс звітності - впливає на можливість переглядати звіти

== Структурна діаграма
// Структурна діаграма
image::arch:architecture/registry/operational/portals/services/officer-portal/officer-portal-structure.svg[]
