= Розгортання

== Діаграма розгортання

// Діаграми та опис розгортання компоненти
// Відповідь на питання яким чином розгортається компонента (nginx, etc.)

image::officer-portal-deploy.svg[]

=== Розгортання додатку

- Чиновники використовують браузер для доступу до веб-додатку
- *React* з *Redux* є основними бібліотеками для розробки веб додатку
- Після збірки додаток представляє собою набір файлів серед яких тільки один *html* файл, та деяка кількість *js*, *css* та інших необхідних статичних файлів
- Веб додаток чиновника відображає контент використовуючи *Nginx* як вебсервер для статичного контенту. Єдиний *html* файл віддається на усіх веб-шляхах додатка.
- Конфігурація веб додатку відбувається через конфіг мапи *officer-portal-environment-js* та *officer-portal-nginx-config*

=== Зовнішні сервіси

- Користувацькі форми веб додатку отримують данні реєстру з *API Дата фабрики*
- Авторизація користувачів веб додатку та отримання інформації про користувача відбувається за рахунок сервісу *Управління користувачами та ролями*
- JSON метадані форм веб додаток отримує з *Сервісу постачання мета-даних форм*
- *Сервіс управління задачами* надає веб додатку інформацію про задачі користувача
- *Сервіс управління процесами користувача* надає веб додатку данні щодо доступних та ініційованих чиновником послуг
- Веб додаток для взаємодії з усіма сервісами використовує сервіс *Управління API системи* 
