:toc-title: On this page:
:toc: auto
:toclevels: 5
:experimental:
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

//= Відправлення повідомлень користувачам
= User notifications

//Платформа підтримує відправлення електронних повідомлень громадянам із використанням різних каналів зв'язку, а саме:
The Platform supports sending electronic messages to citizens using various communication channels, namely:

[%interactive]
//* [*] xref:registry-admin/user-notifications/inbox/inbox-overview.adoc[_inbox_] -- відправлення _in-app_-повідомлень у скриньку _Кабінету отримувача послуг_.
* [*] xref:registry-admin/user-notifications/inbox/inbox-overview.adoc[_inbox_]: sending in-app notifications using a citizen portal inbox.
//* [*] xref:registry-admin/user-notifications/email/email-overview.adoc[_email_] -- відправлення поштових повідомлень користувачам з використанням _платформного_ або _зовнішнього_ поштового сервера.
* [*] xref:registry-admin/user-notifications/email/email-overview.adoc[_email_]: sending email messages using a Platform or external mail server.
//* [*] xref:registry-admin/user-notifications/diia/diia-overview.adoc[_diia_] -- відправлення _push_-нотифікацій у мобільний додаток "Дія".

//The following section was commented out in the original doc.
////
== Функціональні сценарії

- Налаштування каналів зв'язку реєстру через _Веб-інтерфейс Платформи_
- Моделювання шаблонів формування повідомлень на рівні окремих каналів зв'язку
- Моделювання кроків відправлення повідомлень користувачам на рівні бізнес-процесу
- Відправлення повідомлень користувачам згідно з налаштованими преференціями за каналами зв'язку
- Відправлення службових повідомлень користувачам _Платформою_ за окремими каналами зв'язку (_OTP_-код, тощо.)
- Перегляд переліку _in-app_ повідомлень у _Кабінеті Громадянина_ користувачем
- Підтвердження перегляду _in-app_ повідомлення у _Кабінеті Громадянина_ користувачем

== Ролі користувачів

- _Адміністратор платформи_ - створення та налаштування реєстрів _Веб-інтерфейс управління платформою_ (_канали зв'язків тощо._)
- _Адміністратор реєстру_ - налаштування реєстру через _Веб-інтерфейс управління платформою_ (_канали зв'язків тощо._)
- _Адміністратор регламенту_ - створення шаблонів повідомлень, моделювання бізнес-процесів з кроками відправлення повідомлень користувачам
- _Користувач кабінету громадянина_ - отримання повідомлень про стан чи результат виконання бізнес-процесу згідно налаштувань каналів зв'язку, отримання службових повідомлень

////

//Адміністратор регламенту повинен змоделювати шаблони формування повідомлень на рівні окремих каналів зв'язку для того, щоб відправлення повідомлень запрацювало.
The regulations administrator needs to define message templates for each communication channel to enable user notifications.

//Налаштування шаблонів відбувається в регламенті реєстру, у директорії *_notifications_*.
Templates are defined in the registry regulations, in the *_notifications_* directory.

//Також користувач (отримувач послуг) повинен дозволити отримання повідомлень, тобто верифікувати відповідний канал зв'язку у профілі Кабінету.
A user needs to opt in to receive messages by enabling a corresponding communication channel in their user portal profile.

//NOTE: Канал зв'язку _inbox_ активований за замовчуванням.
NOTE: The _inbox_ is activated by default.

//CAUTION: Відправка повідомлень системою можлива лише зареєстрованим користувачам.
CAUTION: The system can only send messages to registered users.

//NOTE: Якщо активовані всі 3 доступні користувачеві канали зв'язку, то за умови змодельованих шаблонів у структурі регламенту реєстру, повідомлення надсилатимуться на кожний канал зв'язку.
NOTE: If all communication channels are enabled, the messages will be sent through each channel, provided that the registry regulations structure contains a corresponding template.