= Налаштування логотипів та favicon для кабінетів реєстру
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Огляд

Впроваджено функцію, що дозволяє адміністраторам та розробникам регламентів кастомізувати зображення логотипів, loaders та favicon для Кабінетів користувачів та Адміністративного порталу кожного реєстру Платформи. Це оновлення додає новий рівень персоналізації, дозволяючи створювати унікальний візуальний стиль для кожного ресурсу.

== Основні можливості

* *Індивідуальне налаштування логотипів*: можливість змінювати зображення логотипа, loader та favicon за замовчуванням для кожного реєстру.

* *Уніфікація візуального стилю*: логотипи, налаштовані на рівні регламенту реєстру, автоматично застосовуються до Адміністративного порталу та Кабінетів користувачів.

* *Гнучкість у кастомізації*: можливість налаштовувати різні логотипи для різних реєстрів однієї Платформи, забезпечуючи індивідуальний підхід до кожного середовища.

* *Застосування змін через Gerrit*: налаштування зображень для логотипа, loader та favicon виконується через систему Gerrit, що забезпечує зручність і ефективність у процесі кастомізації.

[TIP]
====
* *Header logo* (*логотип у заголовку*) -- це зображення або емблема, яке відображається у верхній частині сторінки чи програми, наприклад, на панелі навігації. Воно допомагає користувачам ідентифікувати бренд або платформу.

* *Loader logo* (*логотип завантаження*) -- це зображення, яке відображається під час завантаження сторінки або процесу. Наприклад, коли ви чекаєте, поки щось відкриється, замість простої "крутилки" може з'явитися логотип вашого продукту.

* *Favicon* (*значок сайту*) -- це маленька іконка, яка відображається на вкладці браузера поруч із назвою сайту. Вона допомагає швидко знайти потрібну вкладку серед інших.
====

== Налаштування

[step-1]
=== Крок 1: Клонування репозиторію регламенту

Скопіюйте на локальну машину репозиторій із регламентом реєстру за допомогою команди:

[source,bash]
----
git clone <url_репозиторію>
----

[step-2]
=== Крок 2: Локальне оновлення зображень

Змініть зображення логотипа, loader та favicon, скопіювавши відповідні файли до папки `assets` у репозиторії регламенту:

* `header-logo.svg`
* `loader-logo.svg`
* `favicon.png`

[NOTE]
Файл для favicon має бути у форматі `.png` із розміром 32x32 пікселі.

[step-3]
=== Крок 3: Збереження змін у репозиторії

Виконайте наступні команди у git-консолі в репозиторії реєстру:

[source,bash]
----
git add .
git commit -m "updated logos"
git push origin HEAD:refs/for/master
----

[step-4]
=== Крок 4: Застосування змін через Gerrit

Перейдіть до сервісу Gerrit реєстру і виконайте `git merge` змін, застосувавши створений Merge Request (MR) до master-версії регламенту.

[step-5]
=== Крок 5: Очікування завершення збірки

Дочекайтеся успішного виконання збірки *MASTER-Build-registry-regulation* у реєстровому Jenkins.

[step-6]
=== Крок 6: Перевірка змін

. Відкрийте посилання для:

* Кабінету посадової особи;
* Кабінету отримувача послуг;
* Кабінету адміністратора регламентів.

. Перевірте, що зображення логотипа, loader та favicon змінено відповідно до файлів у master-гілці репозиторію.

== Примітки щодо роботи інтерфейсу

* Змінені логотипи та інші зображення автоматично відображаються на всіх сторінках Кабінетів користувачів та Адміністративного порталу.
* Усі налаштування зберігаються в master-гілці репозиторію та застосовуються без потреби ручного втручання або додаткових дій з боку користувачів Кабінетів.
