@startuml

title Дизайн системи резервного копіювання та відновлення реєстру

actor "Адміністратор платформи" as admin order 10
participant "Control Plane" as cp order 15
participant "Platform Keycloak" as keycloak order 20
participant "Platform Jenkins" as jenkins order 30
box "Registry Forlder" #LightSkyBlue
participant "Registry backup Pipeline" as backup_pipeline order 40
participant "Backup Pipeline Job" as run_pipeline order 50
end box

autonumber

cp -> jenkins: "Move forward"
jenkins -> keycloak: Request Token
keycloak -> jenkins: Succesful login with right permissions

backup_pipeline -> run_pipeline

@endumlß