//= Зміна налаштувань поведінки API які вказуються на рівні структури створення таблиці
= Changing API behavior settings specified at the table creation structure level
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

//== Загальний опис
== General overview

//У моделювальника регламенти при створенні нових таблиць є можливість зазначити атрибут "bulkLoad" для можливості завантаження даних до таблиці з файлів або масивом. На данний момент відсутня можливість змінити це після створення таблиці. Оскільки цей атрибут не міняє структури даних, а лише впливає на генерацію коду - необхідно додати можливість зміни значення атрибуту і після створення таблиць.
When creating new tables, regulations modeler has an ability to specify the "bulkLoad" attribute to enable data loading from files or an array to the table. Currently, there is no option to change this after table creation. Since this attribute does not alter the data structure but only affects code generation, it is necessary to add the ability to change the attribute value after table creation.

//== Функціональні сценарії
== Functional scenarios

//* Як моделювальник регламенту я хочу мати змогу змінювати налаштування які впливають на поведінку згенерованого коду API, але вказуються на рівні створення таблиць.
* As a regulations modeler, I want to be able to modify settings that affect the behavior of the generated API code but are specified at the table creation level.
//** Включення/виключення можливості збереження масиву даних з CSV або через REST API.
//** Зміна режиму читання даних синхронного/асинхронного.
** Enabling/disabling the ability to save an array of data from _CSV_ or via REST API.
** Changing the data read mode from synchronous/asynchronous.

//== Ролі користувачів
== User roles

//* Розробник/моделювальник регламенту
* Regulations developer/modeler

//== Загальні принципи та положення
== General principles and provisions

//* Вже створені структури даних можуть лише розширюватись.
//* Теги в регламенті які вже було опрацьовано не можуть бути змінені.
* Already created data structures can only be extended.
* Tags in the regulation that have already been processed cannot be changed.

//== Моделювання регламенту реєстру
== Registry regulations modeling

//=== Розширення для моделювання
=== Extension for modeling

[source,xml]
----

<databaseChangeLog>
    <changeSet author="..." id="initial creation">
        <ext:createTable name="example_bulk" bulkLoad="false">
             <column name="id" type="UUID" defaultValueComputed="uuid_generate_v4()">
                            <constraints nullable="false" primaryKey="true" primaryKeyName="pk_example_bulk_id"/>
                        </column>
            <column name="first_name" type="text"/>
            ...
            ...
        </ext:createTable>

        <ext:createTable name="example_read_mode" readMode="sync">
             <column name="id" type="UUID" defaultValueComputed="uuid_generate_v4()">
                            <constraints nullable="false" primaryKey="true" primaryKeyName="pk_example_read_mode_id"/>
                        </column>
            <column name="first_name" type="text"/>
            ...
            ...
        </ext:createTable>
    </changeSet>

    <changeSet author="..." id="change api behavior">
        <ext:alterTableApi table="example_bulk">
            <ext:attribute name="bulkLoad" value="true"/>
            <ext:attribute name="readMode" value="sync"/>
        </ext:alterTableApi>

        <ext:alterTableApi table="example_bulk">
            <ext:attribute name="bulkLoad" value="true"/>
        </ext:alterTableApi>
    </changeSet>
</databaseChangeLog>
----

//== Низькорівневий дизайн сервісів
== Low-level service design

//=== Ключові сценарії
=== Key scenarios

//* При зазначенні атрибута в тегу його значення відображається в таблиці метаданих.
//* Відпрацювання тега в рамках декількох `changeSet`-ів є ідемпотентним.
//* За умови відсутності атрибутів в тегу значення в таблиці метаданих залишаєтеся незмінним.
* When specifying an attribute in a tag, its value is reflected in the metadata table.
* Processing the tag within multiple `changeSets` is idempotent.
* If attributes are not present in the tag, the values in the metadata table remain unchanged.

//=== XSD-схема валідації
=== XSD validation schema

//Обовʼязковим є вказання назви таблиці та хоча б один атрибут.
Specifying the table name and at least one attribute is mandatory.

//=== Структура даних
=== Data structure

//.Структура таблиці ddm_liquibase_metadata
.ddm_liquibase_metadata table structure
|===
|metadata_id | change_type | change_name | attribute_name |attribute_value

|%id%
|bulkLoad
//|%назва таблиці%
|%table name%
|bulkLoad
|*true/false*

|%id%
|readMode
|createTable
//|%назва таблиці%
|%table name%
|*sync/async*
|===

//== Високорівневий план розробки
== High-level development plan

//=== Технічні експертизи
=== Technical expertise
//* BE(Java) розробник
* BE (Java) developer

//=== План розробки
=== Development plan

//* Додавання схеми нового тега до `liquibase-ext-schema`.
//* Розширення  `liquibase-ddm-ext` новим тегом.
* Adding a schema for the new tag to `liquibase-ext-schema`.
* Extending `liquibase-ddm-ext` with the new tag.
