//= Повернення інформації про загальну кількість записів при пагінації критеріїв пошуку
= Returning information about the total number of records in pagination of search conditions
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

//== Загальний опис
== General overview

//Наявна функціональність пагінації не надає можливості через API отримати загальну кількість елементів по критерію пошуку, по якому був виконаний запит. Зовнішнім системам доводиться перебирати всі сторінки ресурсу до пустої відповіді. Це незручно в розробці, та ускладнює можливість надати зручний інтерфейс кінцевому користувачу.
The current pagination functionality does not provide an API-based way to retrieve the total number of items based on the search conditions used in the query. External systems are required to iterate through all resource pages until an empty response is encountered. This is inconvenient in development and complicates the ability to offer a user-friendly interface to end-users.

//Для поліпшення досвіду користувача пропонується реалізувати можливість створення критеріїв пошуку з новим типом пагінації, які будуть додатково повертати інформацію про поточну сторінку, кількість елементів на сторінці, загальну кількість елементів та загальну кількість сторінок.
To enhance the user experience, it is proposed to implement the capability to create search conditions with a new pagination type that additionally returns information about the current page, the number of items per page, the total number of items, and the total number of pages.

//== Актори та ролі користувачів
== Actors and user roles
//* Розробник регламенту
//* Зовнішні системи
* Regulations developer
* External systems

//== Загальні принципи та положення
== General principles and provisions

//* Поведінка і контракт існуючих критеріїв пошуку не змінюється.
//* Зберігається зворотня сумісність конфігурації критеріїв пошуку.
* The behavior and contract of existing search conditions remain unchanged.
* Backward compatibility of search conditions configuration is maintained.

//== Функціональні сценарії
== Functional scenarios

//* Налаштування критеріїв пошуку
//* Генерація сервісів критеріїв пошуку
//* Синхронний виклик API критерію пошуку
//* Асинхронний виклик API критерію пошуку
//* Виклик API критерію пошуку із зовнішніх систем, з "Трембіта" і без
* Setting search conditions
* Generation of search conditions services
* Synchronous API call of search conditions
* Asynchronous API call of search conditions
* API call of search conditions from external systems, with and without Trembita (secure exchange gateway name in Ukraine, UA-specific)

//== Поточна реалізація
== Current implementation

//Поточна реалізація надає можливість передавати offset та limit при визові API критерію пошуку. Ця можливість включена за замовчанням для всіх критеріїв пошуку, ала може бути вимкнута за допомогою атрибута тега _createSearchCondition_ `pagination=false`.
The current implementation allows passing offset and limit when calling the API of search conditions. This capability is enabled by default for all search conditions but can be disabled using the attribute tag _createSearchCondition_ `pagination=false`.

//Відповідь API, незалежно від того включена опція пагінації чи ні, містить тільки масив елементів по яким був здійснений пошук. Інформація про загальну кількість елементів чи сторінок у відповіді не передбачена. При цьому якщо були передані offset та limit то відповідь формується з їх урахуванням.
The API response, regardless of whether the pagination option is enabled or not, contains only an array of elements based on which the search was performed. Information about the total number of items or pages is not included in the response. If offset and limit were passed, the response is formulated considering them.

//== Цільовий дизайн
== Target design

//=== Схема та модуль розширення тегів Liquibase
=== Schema and liquibase tags extension module

//В схемі розширених тегів тип атрибуту _pagination_ змінюється на enum, який складається з наступних значень  _offset_, _none_, _page_ та  _true_ і _false_ які є синонімами _offset_ та _none_ для зворотньої сумісності.
In the schema of extended tags, the attribute type pagination changes to an enumeration, consisting of the following values: _offset_, _none_, _page_, and _true_ and _false_, which are synonyms for offset and none for backward compatibility.

//.Схема розширених тегів Liquibase
.Schema of extended Liquibase tags
[source, xml]
----
	<xsd:simpleType name="paginationType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="offset"/>
			<xsd:enumeration value="page"/>
			<xsd:enumeration value="none"/>
      <!--Following is for the backward compatibility-->
			<xsd:enumeration value="true"/> <!--Synonym for "offset"-->
			<xsd:enumeration value="false"/> <!--Synonym for "none"-->     
		</xsd:restriction>
	</xsd:simpleType>
  ....
	<xsd:complexType name="selectSearchConditionType">
		....
		<xsd:attribute name="pagination" type="paginationType" use="optional" default="offset"/>
	</xsd:complexType>
----

//В модуль розширення тегів Liquibase додається можливість запису значення атрибуту _pagination_ для нових типів пагінації в таблицю метаданих `ddm_liquibase_metadata`, при обробці тегу _createSearchCondition_.
In the Liquibase tags extension module, the ability to record the pagination attribute value for new pagination types is added to the  `ddm_liquibase_metadata` metadata table when processing the _createSearchCondition_ tag.

//=== Сервіс генератор
=== Service generator
//IMPORTANT: Значення _offset_ і _none_ є заміною для _true_ і _false_. Якщо на критерій пошуку атрибут _pagination_ встановлено в _offset_ чи _none_, логіка генерації сервісів має бути такою як вона я є для _true_ і _false_ відповідно.
IMPORTANT: The values of _offset_ and _none_ are equivalent to _true_ and _false_. If the pagination attribute is set to offset or none for the search condition, the logic of generating services should be the same as it is for true and false, respectively.

//Якщо на критерій пошуку атрибут _pagination_ встановлено в _page_, має бути згенерований сервіс який додатково до фільтрів заданих в критерії пошуку приймає:
If the _pagination_ attribute is set to _page_ for the search condition, a service should be generated that, in addition to the filters defined in the search condition, accepts:

pageSize::
//бажана кількість елементів на сторінці. За замовчанням 10
desired number of items per page. Default is 10
pageNo::
//бажаний номер сторінки. За замовчанням 0
//У відповіді мають міститися наступні атрибути
desired page number. Default is 0.

The response should contain the following attributes:

content::
//масив елементів по яким відбувся пошук, обмежений номером сторінки та кількістю елементів на сторінці
an array of elements based on which the search was performed, limited by the page number and number of items per page
totalElements::
//загальна кількість елементів по запиту
the total number of elements based on the query
totalPages::
//загальна кількість сторінок по запиту
the total number of pages based on the query
pageSize::
//кількість елементів на сторінці
number of items per page

pageNo::
//номер сторінки що повертається
returned page number


//.Наприклад
.For example
[source, json]
----
{
  "content": [
    {
      "col1": "ADMIN"
    },
    {
      "col1": "USER"
    }    
  ],
  "totalElements": 1,
  "totalPages": 1,
  "pageNo": 0,
  "pageSize": 20,
}
----

//Для отримання _content_ сервіс виконує запит до БД, який генерується таким же чином як і в поточній реалізації обробки запиту з limit та offset. При цьому значення limit та offset беруться не напряму з запиту API, а вираховуються з отриманих pageSize і pageNo. Де *limit=pageSize*, а *offset=pageSize*pageNo*
To obtain the _content_, the service sends a query to the database, generated in the same way as in the current implementation with `limit` and `offset`. In this case, the values of `limit` and `offset` are not taken directly from the API query but are calculated from the received `pageSize` and `pageNo`. Where *limit=pageSize* and *offset=pageSize*pageNo*.

//Для отримання _totalElements_ сервіс виконує додатковий запит до БД, який генерується за наступним шаблоном
To obtain _totalElements_, the service sends an additional query to the database, generated according to the following template:

[source, sql]
----
SELECT COUNT(*)
  FROM <search_condition_view>
 WHERE <filtering conditions>
----

//*totalPages* дорівнює *ceil(totalElements/pageSize)*
*totalPages* equals *ceil(totalElements/pageSize)*

//*pageNo* та *pageSize* ті які були застосовані у запиті - за вхідними параметрами чи за замовчанням.
*pageNo* and *pageSize* are the values applied in the query - either from input parameters or by default.

//.Приклад OpenAPI специфікації
.Example OpenAPI specification
//(xref:attachment$/architecture/registry/operational/registry-management/sc-pagination-count/swagger.yml[Завантажити])
(xref:attachment$/architecture/registry/operational/registry-management/sc-pagination-count/swagger.yml[Download])
[%collapsible]
====
swagger::{attachmentsdir}/architecture/registry/operational/registry-management/sc-pagination-count/swagger.yml[]
====

//Також має бути згенерований еквівалентний Kafka API для асинхронної взаємодії і SOAP для взаємодії з зовнішніми системами, якщо відповідні опції включені в регламенті реєстру для критерію пошуку.
Additionally, an equivalent Kafka API for asynchronous interaction and SOAP for interaction with external systems should be generated if the corresponding options in the registry regulations for the search condition are enabled.

//TIP: Spring має стандартні засоби для реалізації пагінації цього типу. Приклад імплементації
TIP: Spring has standard tools for implementing this type of pagination. Example implementation: https://www.petrikainulainen.net/programming/jooq/using-jooq-with-spring-sorting-and-pagination/[Using jOOQ With Spring: Sorting and Pagination]


//=== Компоненти системи та їх призначення в рамках дизайну рішення
=== System components and their roles within the solution design
//У даному розділі наведено перелік компонент системи, які задіяні або потребують змін/створення в рамках реалізації функціональних вимог згідно з технічним дизайном рішення.
This section lists the system components that are involved or require changes/creation within the implementation of the functional requirements according to the technical design of the solution.

|===
//|Компонент|Службова назва|Призначення / Суть змін
|Component|Service name|Purpose / Aim of changes

//|Сервіс Генератор
|Service Generator
|service-generation-utility 
//|Генерація Java-проектів для сервісів
|Generation of Java projects for services

//|Схема розширених тегів Liquibase
|Liquibase extended gags schema
|liquibase-ext-schema
//|Валідація схеми
|Schema validation

//|Модуль розширення тегів Liquibase
|Liquibase tags extension module
|liquibase-ddm-ext
//|Обробка розширених тегів на етапі розгортання регламенту
|Processing of extended tags during regulation deployment

|===

//== Моделювання регламенту реєстру
== Registry regulations modeling
//=== Моделювання критеріїв пошуку
=== Search conditions modeling
//Адміністратору регламенту надається можливість обирати тип пагінації _page_ при моделюванні критеріїв пошуку.
The registry regulations administrator is provided the ability to choose the pagination type _page_ when modeling search conditions.

//.Структура регламенту реєстру
.Registry regulations structure
[plantuml, registry-sc-regulation-structure, svg]
----
@startsalt
{
{T
+ <&folder> registry-regulation
++ <&folder> bpmn
++ <&folder> dmn
++ <&folder> <b>data-model</b>
+++ <&file> <b>searchConditions.xml</b>
++ ...
}
}
@endsalt
----

//.Приклад конфігурації
.Configuration example
[source, xml]
----
    <changeSet author="registry owner" id="create pageable SC factor_chemical_host_contains_name">
        <ext:createSearchCondition name="factor_chemical_host_contains_name_pageable"  pagination="page">
            <ext:table name="factor" alias="f">
                <ext:column name="factor_id"/>
                <ext:column name="name" sorting="asc" searchType="contains"/>
            </ext:table>
            <ext:where>
                <ext:condition tableAlias="f" columnName="factor_type" operator="eq" value="'Chemical: HOST'"/>
            </ext:where>
        </ext:createSearchCondition>
    </changeSet>
----

//Для адміністратора регламенту також доступні опції _offset_ та _none_ в атрибуті _pagination_.
The options _offset_ and _none_ are also available to the registry regulations administrator in the `pagination` attribute.

//_offset_ - дає той самий результат що і _true_ в поточній реалізації і є опцією за замовчанням.
_offset_ -- provides the same result as _true_ in the current implementation and is the default option.

//_none_ - дає той самий результат що і _false_ в поточній реалізації.
_none_ -- provides the same result as false in the current implementation.

//Опції _true_ та _false_ стають застарілими і можуть бути видалені з часом. Але наразі, в наявних регламентах реєстрів вони продовжать працювати так само як і в поточній реалізації.
The options _true_ and _false_ become deprecated and may be removed in the future. However, for existing registry regulations, they will continue to function the same way as in the current implementation.

//=== Валідація регламенту реєстру
=== Registry regulations validation
//В рамках реалізації рішення, необхідно розширити xml схему розширених тегів liquibase по якій проходить валідація.
As part of the solution implementation, it is necessary to extend the XML schema of extended Liquibase tags against which validation takes place.

//== Високорівневий план розробки
== High-level development plan
//=== Технічні експертизи
=== Technical expertise
* _BE_

//=== План розробки
=== Development plan
//* Розширення схеми розширених тегів Liquibase.
//* Розширення модуля розширення тегів Liquibase.
//* Розширення сервіс генератору.
//* Розробка інструкцій для розробника регламенту та референтних прикладів.
* Extension of the liquibase extended tags schema.
* Extension of the liquibase tags extension module.
* Extension of the service generator.
* Development of instructions for the regulation developer and reference examples.