= Classes of IT systems that can be built on the Registries Platform
include::platform:ROOT:partial$templates/document-attributes/default-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== What is the Registries Platform?

The *_Registries Platform_* is a flexible, secure, low-code digital backend for building various IT systems. Let's elaborate:

* *Flexible*: The Platform for state registries is cloud-agnostic, meaning it can function effectively on different cloud services without relying on a specific environment.
* *Secure*: As one of the digital transformation tools of Ukraine's government services, the Platform is built with security in mind.
* *Low-code*: Using the Platform does not require large teams or high-level experts. The system can be administered with minimal programming, and end-users need only basic computer skills.
* *Digital backend*: The Platform provides the infrastructure and components necessary to build the IT system according to your business needs.
* *IT systems*: The Platform can accommodate different classes of IT systems with a wide range of functionality across industries and applications.

[NOTE,caption=GDPR-readiness]

The Platform is designed with a focus on the _Personal Data Protection Law_ and thus, transitively, on GDPR-readiness, aiming to align with the key principles and requirements of data privacy regulations. To learn more about our standards and compliance (including the right to be forgotten), refer to our xref:arch:architecture/security/standards-and-compliance.adoc[Standards and compliance] page.

== Which IT systems can be built on the Platform?

The Platform can be tailored to accommodate a wide range of IT systems. Here are just some of the possibilities that were already implemented in practice.

=== By purpose

* *Registry*. A registry maintains and manages digital records of citizens, businesses, organizations, or other entities. This information can include data about individuals, licenses, permits, property, companies, and more. Registries can be used to ensure data accuracy, facilitate efficient digital services, and enable seamless information sharing between different agencies and departments.
* *Reporting system*. A reporting system collects, analyzes, and generates reports based on data and information related to operations, services, and performance. Reporting systems help make data-driven decisions, enhance transparency, and provide accountability to the public and stakeholders.
* *Directory*. A directory is a digital database that contains structured information about various entities, officials, departments, agencies, services, and resources. These directories serve as a centralized and easily accessible source of information for citizens, businesses, and other stakeholders. Directories facilitate efficient navigation and retrieval of relevant information, improving public access and transparency.
* *Complaint management system*. Businesses, government agencies, or organizations use a complaint management system to effectively receive, process, and respond to customer, client, or stakeholder complaints and feedback. It provides a structured approach to handling and addressing complaints, ensuring that each complaint is recorded, tracked, and resolved promptly and efficiently.

=== By industry

Here are some examples of how the Platform is implemented across the various industries in Ukraine.

* *Medicine*. The _registry of medical products_ is one of the most important healthcare registries, containing records of over 450,000 medical products allowed for distribution in Ukraine. Each record contains detailed information about the product, such as the manufacturer, responsible persons, and related declarations.
* *Education*. The _registry of students and schools_ is one of the largest registries developed by the Ministry of education and science. It aids in analyzing and planning the development of school education and implementing the digital grading system.
* *Publishing*. The _registry of publishers_ provides the public with open data about existing publishers and enables online applications for a publishing license. It handles the verification of submitted data and even facilitates reducing registration errors.
* *Agriculture*. The _registry of breeding achievements_ serves as a single source of animal breeds with a pedigree value. The registry can be used as a basic directory of animal breeds in various systems in animal husbandry. The main goal is to maintain a single nomenclature and up-to-date information.
* *Mass media*. The _registry of media subjects_ is meant to enhance the mass media registration and licensing process. The system can get licensing and registration online using an automated verification process. In addition, it supports conducting competitions for the licenses, making the whole process more transparent and convenient.

These examples are just a glimpse of what can be achieved using the Platform. Each implementation depends on the individual task statement.

== Which IT systems should NOT be built on the Platform?

We do not recommend using the Platform’s capabilities for the following purposes:

* *Web development*. The Platform operates via several web interfaces but should not be considered a website-building tool.
* *Analytics tool*. The Platform supports limited analytical reports and dashboards tailored for internal monitoring, not as the main feature. However, it may be integrated with any other analytical systems.
* *Exchange or trading platform*. The Platform’s functionality is not focused on online trading.
