= Примітки до релізу 1.9.7. Частина 3
:toc:
:toc-title: ЗМІСТ
:sectnums:
:sectlinks:
:sectanchors:
:note-caption: Покращено
:tip-caption: Розроблено
:caution-caption: Інше
:important-caption: Виправлено
:warning-caption: Покращення безпеки

== Нормалізація апострофа та інших спецсимволів ПІБ у КЕП та id.gov.ua
//https://jiraeu.epam.com/browse/MDTUDDM-20479
//TODO: first.xlsx

[TIP]
====
* [*] Розроблено новий механізм порівняння імені користувача (параметр `fullName`) при автентифікації з КЕП, або id.gov.ua. Тепер не враховуються усі символи, окрім літер кирилиці, латиниці та цифр, не враховується регістр символів. Така логіка застосовується до всіх реєстрів, що розгорнуті на Платформі.

//https://jiraeu.epam.com/browse/MDTUDDM-22074
* [*] При автентифікації посадової особи, або отримувача послуг, з ПІБ у ключі та системі видаляються усі спецсимволи. Це надає можливість входити до кабінетів при наявності допустимих відмінностей.

* [*] Змінено логіку роботи сервісів автентифікації посадових осіб та отримувачів послуг.
====

== Автентифікація через id.gov.ua в Кабінеті посадової особи
//https://jiraeu.epam.com/browse/MDTUDDM-22266
//TODO: first.xlsx

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-18659
* [*] Можливість виконувати вхід в кабінет через `id.gov.ua` у Кабінеті посадової особи.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-22782
* [*] Можливість налаштовувати тип автентифікації через `id.gov.ua` для Кабінету посадової особи.

[TIP]
//https://jiraeu.epam.com/browse/MDTUDDM-22803
* [*] Можливість налаштовувати тип автентифікації через IIT-віджет для Кабінету посадової особи.
====

////
== Редагування скриптів бізнес-процесів реєстру через візуальний редактор коду
//https://jiraeu.epam.com/browse/MDTUDDM-13328

[TIP]
====
* [*] Розробник регламенту реєстру може у вбудованому редакторі діаграм *BPMN.iO* переглядати (для майстер-версії) та редагувати (для версії-кандидата) https://uk.wikipedia.org/wiki/Groovy[*Groovy*]-скрипти через візуальний редактор коду. Для цього імплементовано рішення https://microsoft.github.io/monaco-editor/[Monaco Editor], візуалізоване темою *Visual Studio Dark*.

Підтримуються наступні функції при роботі з редактором: ::

* [*] Автодоповнення
* [*] Автодоповнення для кастомних функцій
* [*] Синтаксичний аналіз коду та перевірка помилок
* [*] Підтримка коментарів
* [*] Згортання та розгортання блоку з кодом
====

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-3032
* [*] Зміни до скриптів бізнес-процесів (через візуальний редактор скриптів) у VCS автоматично розгортаються у сервісі виконання бізнес-процесів.

//https://jiraeu.epam.com/browse/MDTUDDM-3030
* [*] Скрипти, які використовуються у бізнес-процесах, зберігаються згідно з регламентованою структурою у VCS.

//https://jiraeu.epam.com/browse/MDTUDDM-3031
* [*] Зміни до скриптів бізнес-процесів у VCS автоматично відстежуються.
====

== Управління налаштуваннями та секретами зовнішніх систем
//https://jiraeu.epam.com/browse/MDTUDDM-20495

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-19044
* [*] Можливість бачити в Control Plane перелік зовнішніх інтеграцій через "Трембіту" після створення реєстру.

//https://jiraeu.epam.com/browse/MDTUDDM-19045
* [*] Можливість бачити в Control Plane запис щодо інтеграції із зовнішньою системою "Дія" після створення реєстру.

//https://jiraeu.epam.com/browse/MDTUDDM-19046
* [*] Можливість налаштовувати зовнішні інтеграції через "Трембіту" в Control Plane при створенні реєстру.

//https://jiraeu.epam.com/browse/MDTUDDM-19048
* [*] Можливість налаштовувати зовнішню інтеграцію з "Дія" в Control Plane.

//https://jiraeu.epam.com/browse/MDTUDDM-19049
* [*] Можливість видаляти налаштування зовнішньої системи.

//https://jiraeu.epam.com/browse/MDTUDDM-19050
* [*] Можливість налаштовувати зовнішні інтеграції на рівні регламенту (мінімальні налаштування).

//https://jiraeu.epam.com/browse/MDTUDDM-19053
* [*] Можливість налаштовувати зовнішні інтеграції (окрім інтеграцій через Трембіту та інтеграції з "Дія") у Control Plane.

//https://jiraeu.epam.com/browse/MDTUDDM-20996
* [*] При оновленні версії реєстру, всі оновлення щодо винесення секретів з конфігураційного файлу відбуваються автоматично.

//https://jiraeu.epam.com/browse/MDTUDDM-21106
* [*] Додано обробку помилок при винесенні секретів.
====

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-20035
* [*] Видалено поле `*Authorization Token*` з шаблонів.

//https://jiraeu.epam.com/browse/MDTUDDM-23207
* [*] Автоматичне злиття змін до реєстру після додавання/зміни інтеграцій для "Трембіта"/"Дія"/Зовнішня система.

//https://jiraeu.epam.com/browse/MDTUDDM-23209
* [*] Додано підказку до полів `Адреса зовнішньої системи` та `Адреса ШБО Трембіти`.

//https://jiraeu.epam.com/browse/MDTUDDM-23397
* [*] Змінено колір кнопки `Підтвердити` на зелений згідно з шаблонами.
====

== Перегляд переліку таблиць моделі даних реєстру у режимі читання для версії-кандидата
//https://jiraeu.epam.com/browse/MDTUDDM-20609

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-19038
* [*] Перегляд списку таблиць для версії-кандидата у режимі читання.

//https://jiraeu.epam.com/browse/MDTUDDM-22606
* [*] Періодичне видалення застарілих схем БД по всіх версіях-кандидатах.

//https://jiraeu.epam.com/browse/MDTUDDM-22997
* [*] Можливість бачити стан розгортання тимчасової БД для Кандидат-версії.

//https://jiraeu.epam.com/browse/MDTUDDM-23068
* [*] Видалення всіх тимчасових БД для версій-кандидатів cleanup-процесом.

//https://jiraeu.epam.com/browse/MDTUDDM-23089
* [*] Механізм генерації "data model snapshot" видаляється для Майстер-версії.
====

[NOTE]
====
//https://jiraeu.epam.com/browse/MDTUDDM-22996
* [*] Видалення з переліку таблиць для Майстер-версії ознаки історичності.
====

== Можливість моделювання на навігаційних кнопках поп-апу підтвердження дії із заданням тексту на кнопках дій поп-апу
//Моделювання спливних вікон для підтвердження дії у компоненті Button
//https://jiraeu.epam.com/browse/MDTUDDM-21378

[TIP]
====
* [*] Розроблено функціональність моделювання спливних вікон для підтвердження, або скасування дій на UI-формах.

* [*] Адміністратор може налаштовувати спливні вікна у розділі моделювання UI-форм Кабінету адміністратора регламентів за допомогою компонента `*Button*` («Кнопка») та параметра `*Pop-up should display*`. Налаштування працюватимуть для форм введення даних у Кабінетах посадових осіб та отримувачів послуг.
====

== Скриптування вивантаження файлів за віддаленою адресою із подальшим збереженням до реєстру у бізнес-процесі
//Завантаження цифрових документів за зовнішнім посиланням
//https://jiraeu.epam.com/browse/MDTUDDM-21544

[TIP]
====
* [*] Можливість завантажувати цифрові документи за віддаленою адресою у зовнішній системі та зберігати їх до реєстру для подальшого використання у бізнес-процесах.

* [*] Наразі система дозволяє отримувати цифрові документи за зовнішнім посиланням із типом автентифікації `*NO_AUTH*`, коли запит виконується до публічних API.

* [*] Для отримання цифрових файлів за віддаленою адресою розроблена JUEL-функція `*save_digital_document_from_url ()*`, яку можна використовувати для спрощення моделювання процесів у скриптах.

* [*] Створення REST-ендпоінту для завантаження файлу.

* [*] Створено новий репозиторій `ddm-digital-document-client`.

* [*] Створення JUEL-функції для завантаження з використанням бібліотеки клієнта dds.
====

[NOTE]
====
* [*] Винесено REST-клієнт `digital-document-service` в окрему бібліотеку.
====

== Спрощення моделювання поля Url в оновленому компоненті File
//https://jiraeu.epam.com/browse/MDTUDDM-22302

[NOTE]
====
* [*] Поле `Storage` у компоненті `File` передзаповнюється значення `Digital-document-service` та є прихованим.
+
Раніше при моделюванні компоненти *File* існувала можливість обрати в полі `Storage` одну з опцій: `Digital-document-service`, або `Custom Url`.
+
Опцію "Custom Url" прибрано.
====

== Впровадження Маркер Кластера на мапі при відображенні великої кількості об'єктів

[TIP]
====
* [*] Імплементовано лічильник кількості об'єктів, що належать до одного просторового кластера.
Функціональність полегшує візуалізацію великої кількості об'єктів на мапі у Кабінетах отримувача та надавача послуг.
+
Ця зміна дозволяє користувачам швидше сприймати інформацію про об'єкти та їхні кластери на карті, покращуючи візуальний досвід.
====

== Централізоване розповсюдження типових розширень БП як частини Платформи

[TIP]
====
* [*] Було впроваджено централізовану систему розповсюдження типових розширень бізнес-процесів як частини платформи, що дозволяє їх використання у моделюванні бізнес-процесів з метою забезпечення сумісності між різними версіями.
+
У попередніх версіях `admin-portal` зчитував розширення `business-process-modeler-extensions` з hardcoded-конфігурації.
+
Механізм зчитування змінено. Наразі зчитування відбувається із файлу `business-process-modeler-element-templates.js`.
====

== Керування розкладом створення резервних копій центральних компонент та часом їх зберігання
//https://jiraeu.epam.com/browse/MDTUDDM-21045

[TIP]
====
* [*] Імплементовано можливість керувати розкладом створення резервних копій наступних центральних компонентів, а також часом зберігання таких резервних копій у сховищі бекапів:

** [*] Бекапування центрального *Nexus* (сховище артефактів);
** [*] Бекапування центрального *Control Plane* (панель керування Платформою та реєстрами);
** [*] Бекапування центрального *user-management* (Керування користувачами);
** [*] Бекапування центрального *monitoring* (моніторинг).

* [*] Значення зберігаються до конфігурації *_values.yaml_* у репозиторії  *_cluster-mgmt_*.

* [*] Відповідні параметри застосовуються завдяки Jenkins-пайплайну `Cluster-mgmt`.
====

== Оновлення Платформних ключів та сертифікатів з адмін-консолі адміністратором Платформи

[TIP]
====
//https://jiraeu.epam.com/browse/MDTUDDM-17503
* [*] Можливість оновлювати Платформні ключі та сертифікати цифрового підпису з адмін-консолі Control Plane адміністратором Платформи.
====

////
