= Адміністративна зона Платформи

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

_Адміністративна зона Платформи_ - це сукупність підсистем, що забезпечують керування станом та налаштуваннями екземпляра _Платформи_ та розгорнутих на ній реєстрів за допомогою _GitOps_-підходу шляхом внесення змін у відповідні репозиторії системи контроля версій та автоматичного їх застосування.

_Підсистема управління Платформою та Реєстрами_ адміністративної зони надає веб-інтерфейси для адміністраторів, за допомогою яких можна керувати оновленням, конфігурацією, масштабуванням, резервним копіюванням, відновленням та іншими службовими функціями _Платформи_.

[TIP]
--
Детальніше з ролями службових адміністраторів можна ознайомитись у розділі xref:arch:architecture/platform/operational/user-management/platform-actors-roles.adoc#_службові_адміністратори[Актори та ролі Платформи].
--

== Технічний дизайн адміністративної зони Платформи

На даній діаграмі зображено підсистеми, які входять в _Адміністративну зону Платформи_ та їх взаємодію з іншими підсистемами в рамках реалізації функціональних сценаріїв.

image::architecture/platform/administrative/administrative-zone-subsystems.svg[]

== Підсистеми адміністративної зони Платформи

|===
|Назва підсистеми|Службова назва|Репозиторії|Призначення

|xref:architecture/platform/administrative/control-plane/overview.adoc[Підсистема управління Платформою та Реєстрами]
|_control-plane_
|https://github.com/openshift/console[github.com/openshift/console]

https://github.com/openshift/console-operator[github.com/openshift/console-operator]

https://github.com/epam/edp-ddm-control-plane-console[github.com/epam/edp-ddm-control-plane-console]

https://github.com/epam/edp-admin-console-operator[github.com/epam/edp-admin-console-operator]

|Підсистема керування центральними компонентами Платформи, реєстрами та ресурсами OpenShift.

|xref:architecture/platform/administrative/config-management/overview.adoc[Підсистема розгортання та налаштування Платформи та Реєстрів]
|_config-management_
|https://github.com/epam/edp-ddm-control-plane-gerrit[github.com/epam/edp-ddm-control-plane-gerrit]

https://github.com/epam/edp-ddm-control-plane-jenkins[github.com/epam/edp-ddm-control-plane-jenkins]

https://github.com/epam/edp-ddm-control-plane-nexus[github.com/epam/edp-ddm-control-plane-nexus]

https://github.com/epam/edp-codebase-operator[github.com/epam/edp-codebase-operator]

https://github.com/epam/edp-jenkins-operator[github.com/epam/edp-jenkins-operator]

https://github.com/epam/edp-gerrit-operator[github.com/epam/edp-gerrit-operator]

https://github.com/epam/edp-nexus-operator[github.com/epam/edp-nexus-operator]

|Підсистема розгортання, налаштування, оновлення компонентів Платформи та Реєстрів і їх конфігурацій.

|===
