= Адміністративна зона Платформи

== Загальний опис

_Адміністративна зона Платформи_ - це сукупність підсистем, що забезпечують керування станом та налаштуваннями екземпляра _Платформи_ та розгорнутих на ній реєстрів за допомогою _GitOps_-підходу шляхом внесення змін у відповідні репозиторії системи контроля версій та автоматичного їх застосування.

_Підсистема управління Платформою та Реєстрами_ адміністративної зони надає веб-інтерфейси для адміністраторів, за допомогою яких можна керувати оновленням, конфігурацією, масштабуванням, резервним копіюванням, відновленням та іншими службовими функціями _Платформи_.

[TIP]
--
Детальніше з ролями службових адміністраторів можна ознайомитись у розділі xref:arch:architecture/platform/operational/user-management/platform-actors-roles.adoc#_службові_адміністратори[Актори та ролі Платформи].
--

== Технічний дизайн адміністративної зони Платформи

На даній діаграмі зображено підсистеми, які входять в _Адміністративну зону Платформи_ та їх взаємодію з іншими підсистемами в рамках реалізації функціональних сценаріїв.

image::architecture/platform/administrative/administrative-zone-subsystems.svg[]

== Підсистеми адміністративної зони Платформи

[TIP]
--
Перелік підсистем та відповідних репозиторіїв наведено в таблиці нижче. У разі, якщо компоненти підсистеми реалізовано в окремих репозиторіях, вони наведені в переліку складових підсистеми.
--

|===
|Назва підсистеми|Службова назва

|xref:architecture/platform/administrative/control-plane/overview.adoc[Підсистема управління Платформою та Реєстрами]
|_control-plane_

|xref:architecture/platform/administrative/config-management/overview.adoc[Підсистема розгортання та налаштування Платформи та Реєстрів]
|_config-management_

|===
