= Адміністративна зона Платформи

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

_Адміністративна зона Платформи_ - це сукупність підсистем, що забезпечують керування станом та налаштування екземпляра Платформи та реєстрів, які на ній розгорнуті.

[TIP]
--
Детальніше з ролями адміністраторів Платформи Реєстрів можна ознайомитись у розділі xref:arch:architecture/platform/operational/user-management/platform-actors-roles.adoc#_службові_адміністратори[Службові адміністратори].
--

== Технічний дизайн адміністративної зони Платформи

image::architecture/platform/administrative/administrative-zone-subsystems.svg[]

== Підсистеми адміністративної зони Платформи

|===
|Назва підсистеми|Службова назва|Призначення

|xref:architecture/platform/administrative/control-plane/overview.adoc[Підсистема управління Платформою та Реєстрами]
|_control-plane_
|Підсистема керування центральними компонентами Платформи, реєстрами та ресурсами OpenShift.

|xref:architecture/platform/administrative/config-management/overview.adoc[Підсистема розгортання та налаштування Платформи та Реєстрів]
|_config-management_
|Підсистема розгортання, налаштування, оновлення компонентів Платформи та Реєстрів і їх конфігурацій.

|===