= Функція _registry()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`registry(): RegistryDto`* використовується для отримання інформації про реєстр, розгорнутий на Платформі, включаючи поточну мову та підтримувані мови.

== Параметри

Ця функція не приймає аргументів.

== Що повертає

Ця функція повертає об'єкт типу `RegistryDto`, що містить наступні дані:

.RegistryDto
|===
|*Поле*                 | *Опис*
| `language`            | Поточна мова реєстру / мова за замовчуванням.
| `supportedLanguages`  | Набір підтримуваних мов у реєстрі.
|===

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

== Приклади використання

Функція `registry()` дозволяє отримати поточну мову реєстру та список підтримуваних мов для налаштування локалізації бізнес-процесу. Це корисно для відображення інформації, адаптованої до мовних налаштувань реєстру, або для налаштування умовного відображення компонентів у процесі.

[example-1]
=== Приклад 1. Отримання мови реєстру за замовчуванням

У цьому прикладі показано, як отримати мову реєстру за замовчуванням. Це значення можна використовувати для налаштування інтерфейсу за замовчуванням, якщо мова користувача не визначена.

.Приклад. Отримання мови реєстру для налаштування локалізації
[source,groovy]
----
${registry().language}
----

Цей метод дозволяє встановити мову інтерфейсу або повідомлень у бізнес-процесі відповідно до налаштувань реєстру.

[example-2]
=== Приклад 2. Отримання списку підтримуваних мов реєстру

Функція `registry().supportedLanguages` повертає набір мов, які налаштовані в реєстрі. Це корисно для умовного відображення контенту на основі наявних мов, доступних у реєстрі.

.Приклад. Отримання підтримуваних мов для умовного відображення
[source,groovy]
----
${registry().supportedLanguages}
----

Цей метод дозволяє отримати список підтримуваних мов, що може бути використано для налаштування умовного відображення компонентів або повідомлень залежно від доступних мов у реєстрі. Наприклад, ви можете налаштувати процес таким чином, щоб він відображав повідомлення тільки доступними мовами, забезпечуючи узгодженість локалізації.

//TIP: Застосування функції `registry()` детально представлено у референтному прикладі на сторінці xref:best-practices/bp-registry-access.adoc[].