= Конфігурація доступу до ШБО "Трембіта"
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

IMPORTANT: Документ застарів і є НЕактуальним.

[WARNING]
====
Для версій реєстру 1.9.2 та нижче налаштувати інтеграцію можливо на рівні регламенту реєстру у файлі _bp-trembita/configuration.yml_.

Для версій реєстру 1.9.3 і вище налаштування взаємодії доступне на рівні екземпляра реєстру в адміністративній панелі Control Plane (_зверніться до сторінки xref:registry-admin/external-integration/cp-integrate-trembita.adoc[]_).
====

== Загальні положення

Щоб мати змогу використовувати розроблені на Платформі SOAP-інтеграційні конектори до зовнішніх сервісів та отримувати інформацію від інших реєстрів через ШБО "Трембіта", необхідно попередньо виконати конфігурації на рівні регламенту реєстру.

Для цього потрібно налаштувати параметри `trembita-exchange-gateway` у конфігураційному файлі _bp-trembita/configuration.yml_.

[NOTE]
====
* Налаштування підключення до "Трембіти" є частиною регламенту реєстру та зберігаються у файлі *_bp-trembita/configuration.yml_*.
* Будь-які зміни у файлі *_bp-trembita/configuration.yml_* призводять до зміни (або створення у разі відсутності) *Config Map* `*trembita-configuration*` та перезапуску сервісу *`bpms`* у пайплайні публікацій.
* Config Map `*trembita-configuration*` має один ключ -- `*trembita-configuration.yml*` та значення -- зміст файлу *bp-trembita/configuration.yml* із додаванням префікса `*_trembita-exchange-gateway*`.
** Наприклад, при змісті файлу:
*** `registries.edr-registry.trembita-url: trembita.cicd2.epam.com`
** значення config map має бути наступне:
*** `data:`
+
`trembita-configuration.yml: |-
trembita-exchange-gateway.registries.edr-registry.url:trembita.cicd2.epam.com`

* Config Map `*trembita-configuration*` додається до контексту `bpms`, та визначена у Config Map конфігурація є доступною у процесі роботи сервісу.
* Зміни у файлі *_bp-trembita/configuration.yml_* призводять до зміни `CR KeycloakAuthFlow` *`citizen-portal-dso-citizen-auth-flow`* у пайплайні публікацій.
====

[configuration-mapping]
=== Мапінг конфігурації

.Мапінг (зіставлення) конфігурації файлу *_bp-trembita/configuration.yml_* із параметрами з `*citizen-portal-dso-citizen-auth-flow*`
|===
|*citizen-portal-dso-citizen-auth-flow*|*bp-trembita/configuration.yml*

|`trembitaUrl`|`trembita-exchange-gateway.registries.edr-registry.trembita-url`
|`trembitaUserId`|`trembita-exchange-gateway.registries.edr-registry.user-id`
|`trembitaProtocolVersion`|`trembita-exchange-gateway.registries.edr-registry.protocol-version`
|`clientXRoadInstance`|`trembita-exchange-gateway.registries.edr-registry.client.x-road-instance`
|`clientSubsystemCode`|`trembita-exchange-gateway.registries.edr-registry.client.subsystem-code`
|`clientMemberCode`|`trembita-exchange-gateway.registries.edr-registry.client.member-code`
|`clientMemberClass`|`trembita-exchange-gateway.registries.edr-registry.client.member-class`
|`registryToken`|`trembita-exchange-gateway.registries.edr-registry.authorization-token`
|`registryXRoadInstance`|`trembita-exchange-gateway.registries.edr-registry.service.x-road-instance`
|`registryMemberClass`|`trembita-exchange-gateway.registries.edr-registry.service.member-class`
|`registryMemberCode`|`trembita-exchange-gateway.registries.edr-registry.service.member-code`
|`registrySubsystemCode`|`trembita-exchange-gateway.registries.edr-registry.service.subsystem-code`

|===

== Приклади конфігурації сервісів та опис структурних параметрів

.Приклад конфігурації підключення до сервісу ЄДР
[%collapsible]
====
[source,yaml]
----
trembita-exchange-gateway:
  registries:
    edr-registry:
      user-id: 'DDM'
      protocol-version: '4.0'
      trembita-url: 'https://trembita-edr-registry-mock.apps.envone.dev.registry.eua.gov.ua/mockEDRService'
      secret-name: 'trembita-registries-secrets'
      client:
        x-road-instance: 'SEVDEIR-TEST'
        member-class: 'GOV'
        member-code: '43395033'
        subsystem-code: 'IDGOV_TEST_01'
      service:
        x-road-instance: 'SEVDEIR-TEST'
        member-class: 'GOV'
        member-code: '00015622'
        subsystem-code: '2_MJU_EDR_prod'
----
====

.Приклад конфігурації підключення до сервісу ДРАЦС
[%collapsible]
====
[source,yaml]
----
trembita-exchange-gateway:
  registries:
    dracs-registry:
          trembita-url: 'https://trembita-dracs-registry-mock.apps.envone.dev.registry.eua.gov.ua/dracsMock'
          user-id: 'DDM'
          protocol-version: '4.0'
          client:
            x-road-instance: 'SEVDEIR-TEST'
            member-class: 'GOV'
            member-code: '43395033'
            subsystem-code: 'IDGOV_TEST_01'
          service:
            x-road-instance: 'SEVDEIR-TEST'
            member-class: 'GOV'
            member-code: '22956058'
            subsystem-code: 'TEST_DRAC'
----
====

.Приклад конфігурації підключення до сервісу ЄІБДВПО
[%collapsible]
====
[source,yaml]
----
trembita-exchange-gateway:
  registries:
    idp-exchange-service-registry:
          trembita-url: https://trembita-idp-mock-server.apps.envone.dev.registry.eua.gov.ua/idpMock
          user-id: DDM
          protocol-version: '4.0'
          client:
            x-road-instance: SEVDEIR-TEST
            member-class: GOV
            member-code: '43395033'
            subsystem-code: IDGOV_TEST_01
          service:
            x-road-instance: SEVDEIR-TEST
            member-class: GOV
            member-code: '37567866'
            subsystem-code: 51_IDP_prod
----
====

.Опис структурних параметрів
[width="100%",cols="30%,70%",options="header",]
|===
|+++<b style="font-weight: 600">Параметр</b>+++|+++<b style="font-weight: 600">Опис</b>+++

|`registries`|Назва реєстру, до якого буде сформовано запит
2+|_Заголовки, що ідентифікують користувача, який робить запит_
|`trembita-url`|Адреса до ШБО
|`secret-name`| Назва секрету. Регламент не повинен містити конфіденційних даних користувача. Токен авторизації `authorization-token` винесено за межі регламенту до налаштувань OpenShift.
|`user-id`|Ідентифікатор користувача, який ініціює запит
|`protocol-version`|Версія протоколу, за яким обмінюються повідомлення ШБО.

_На цей час версія протоколу 4.0_

2+|_Заголовок (client), який ідентифікує учасника сервісу_
|`x-road-instance`|Код середовища, який ідентифікує екземпляр учасника
|`member-class`|Ідентифікатор класу учасника
|`member-code`|Ідентифікатор учасника
|`subsystem-code`|Код, який ідентифікує підсистему учасника, якщо сервіс надається підсистемою

2+|_Заголовок (service), який ідентифікує сервіс_
|`x-road-instance`|Код середовища, який ідентифікує екземпляр сервісу
|`member-class`|Ідентифікатор класу сервісу
|`member-code`|Ідентифікатор сервісу
|`subsystem-code`|Код, який ідентифікує підсистему сервісу, якщо сервіс надається підсистемою
|===

[#list-of-services-trembita]
Перелік сервісів СЕВ ДЕІР "Трембіта", що використовуються на Платформі: ::
+
[%collapsible]
.Міністерство юстиції України
====

.Єдиний державний реєстр (ЄДР)
[%collapsible]
=====
* https://directory-test.trembita.gov.ua:8443/SEVDEIR-TEST/GOV/00015622/2_MJU_EDR_prod/SearchSubjects[Сервіс пошуку суб'єкта в ЄДР (SearchSubjects)]
* https://directory-test.trembita.gov.ua:8443/SEVDEIR-TEST/GOV/00015622/2_MJU_EDR_prod/SubjectDetail[Сервіс отримання детальної інформації про суб'єкт в ЄДР (SubjectDetail)]
=====

.Державний реєстр актів цивільного стану (ДРАЦС)
[%collapsible]
=====
* https://directory-test.trembita.gov.ua:8443/SEVDEIR-TEST/GOV/00015622/3_MJU_DRACS_prod/GetCertByNumRoleNames[Сервіс отримання даних Свідоцтва про народження за вказаними серією і номером Свідоцтва та ПІБ (GetCertByNumRoleNames)]
* https://directory-test.trembita.gov.ua:8443/SEVDEIR-TEST/GOV/00015622/3_MJU_DRACS_prod/GetCertByNumRoleBirthDate[Сервіс отримання даних Свідоцтва про народження за вказаними серією і номером Свідоцтва, та датою народження (GetCertByNumRoleBirthDate)]
=====
====

+
.Міністерство соціальної політики України
[%collapsible]
====

.Єдина інформаційна база даних внутрішньо переміщених осіб (ЄІБДВПО)
[%collapsible]
=====
* https://directory-test.trembita.gov.ua:8443/SEVDEIR-TEST/GOV/37567866/51_IDP_prod/IDPexchangeService[Сервіс пошуку довідки ВПО (IDPexchangeService)]
=====
====
+
[TIP]
====
Повний каталог вебсервісів системи ШБО "Трембіта", де можна отримати необхідні ідентифікатори, представлено за посиланнями:

* link:https://directory-test.trembita.gov.ua:8443/[Каталог вебсервісів (тестове середовище)]
* link:https://directory-prod.trembita.gov.ua:8443/[Каталог вебсервісів (промислове середовище)]
====