= Сервіс отримання даних Свідоцтва про народження (_GetCertByNumRoleBirthDate_)
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Огляд сервісу

Сервіс *`GetCertByNumRoleNames`* надає можливість здійснити пошук у _Державному реєстрі актів цивільного стану_ (ДРАЦС) та отримати відомості щодо Свідоцтва про народження дитини за вказаними серією і номером Свідоцтва, та датою народження через ШБО "Трембіта".

Пошук Свідоцтва про народження в ДРАЦС здійснюється за критеріями:

* `ByParam`
* `CertNumber` -- номер свідоцтва;
* `CertSerial` -- серія свідоцтва;
* `DateBirth` -- дата народження;
* `Name` -- ім'я;
* `Patronymic` -- по батькові;
* `Role` -- Роль особи;
* `Surname` -- Прізвище.

.Запит у форматі XML
[source, xml]
----
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Header>
    ...
  </s:Header>
  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <CeServiceRequest xmlns="http://tempuri.org/">
      <ByParam>3</ByParam>
      <CertNumber>218727</CertNumber>
      <CertSerial>IV-AM</CertSerial>
      <DateBirth>2021-21-10T00:00:00</DateBirth>
      <Name xsi:nil="true" />
      <Patronymic xsi:nil="true" />
      <Role>1</Role>
      <Surname xsi:nil="true" />
    </CeServiceRequest>
  </s:Body>
</s:Envelope>
----

.Відповідь у форматі JSON
[source, json]
----
{
   "certificate":[
      {
         "certStatus":1,
         "certRepeat":0,
         "certSerial":"IV-AM",
         "certNumber":"218727",
         "certSerialNumber":null,
         "certOrg":null,
         "certDate":null,
         "arOrg":null,
         "arNumb":null,
         "arComposeDate":null,
         "childSurname":"Сидоренко",
         "childName":"Павло",
         "childPatronymic":"Іванович",
         "childBirthdate":null,
         "fatherSurname":null,
         "fatherName":null,
         "fatherPatronymic":null,
         "fatherCitizenship":null,
         "fatherCitizenshipAnother":null,
         "motherSurname":null,
         "motherName":null,
         "motherPatronymic":null,
         "motherCitizenship":null,
         "motherCitizenshipAnother":null,
         "oldSurname":null,
         "oldName":null,
         "oldPatronymic":null,
         "newSurname":null,
         "newName":null,
         "newPatronymic":null,
         "dateOfBirth":null,
         "placeofBirth":null,
         "husbandOldSurname":null,
         "husbandSurname":null,
         "husbandName":null,
         "husbandPatronymic":null,
         "husbandCitizenship":null,
         "husbandBirthdate":null,
         "husbandPlaceofBirth":null,
         "wifeOldSurname":null,
         "wifeSurname":null,
         "wifeName":null,
         "wifePatronymic":null,
         "wifeCitizenship":null,
         "wifeBirthdate":null,
         "wifePlaceOfBirth":null
      }
   ]
}
----

.Опис структурних параметрів
|====
|Параметр |Опис |Тип |Важливість
|ErrorInfo|Текстова інформація про помилки|string|необов'язково
|ResultCode|Результат запиту|string|необов'язково
|ResultData|XML з вихідними даними згідно з форматом в документі та з набором заданих полів в Base64|string|необов'язково
|====

Опис `ResultCode` результат запиту:

*	0 - успішно виконано;
*	1 - внутрішня помилка;
*	2 - не дозволено для даного клієнта;
*	3 - більше ніж один активний сервіс;
*	4 - поля не задано;
*	5 - некоректні вхідні параметри (валідація неуспішна).

.Опис складу результату вивантаження даних свідоцтва `ResultData`
|====
|Параметр |Опис |Тип |Важливість|Примітки
|CertStatus|Статус свідоцтва|number|обов'язково|1 – дійсне; 3 - анульоване;
|CertRepeat|Ознака «Повторне»|number|необов'язково|0 – ні; 1 - так;
|CertSerial|Серія свідоцтва |string|обов'язково|
|CertNumber|Номер свідоцтва |string|обов'язково|
|CertSerialNumber|Серія та  номер свідоцтва|string|обов'язково|Частина Serial – символи (до 10 символів); Частина Number - тільки цифри (до 11 символів);
|CertOrg|Орган, що видав свідоцтво|string|обов'язково|
|CertDate|Дата видачі свідоцтва|string|обов'язково|Дата. Приклад (10.10.2018)
|ArOrg|Місце державної реєстрації|string|необов'язково|
|AR_NUMB|Номер актового запису в книзі державної реєстрації	|string|необов'язково|
|AR_COMPOSEDATE|Дата складання актового запису в книзі державної реєстрації |string|необов'язково|
|ChildSurname|Прізвище дитини|string|обов'язково|
|ChildName|Власне ім'я дитини|string|обов'язково|
|ChildPatronymic|По батькові дитини (за наявності)|string|обов'язково|
|ChildBirthdate|Дата народження дитини|string|обов'язково|
|PlaceofBirth|Місце народження|string|необов'язково|
|FatherSurname|Прізвище батька |string|необов'язково|
|FatherName|Власне ім'я батька |string|необов'язково|
|FatherPatronymic|По батькові батька (за наявності)|string|необов'язково|
|FatherСitizenship|Громадянство батька |number|необов'язково|82 – особа без громадянства; 83 - громадянин України; 84 - громадянка України; 85 – інше;
|FatherСitizenship Another|Громадянство батька|number|необов'язково|Надається при значенні  FatherСitizenship = 85
|MotherSurname|Прізвище матері |string|необов'язково|
|MotherName|Власне ім'я матері |string|необов'язково|
|MotherPatronymic|По батькові матері (за наявності)|string|необов'язково|
|MotherСitizenship|Громадянство матері|number|необов'язково|82 – особа без громадянства; 83 - громадянин України; 84 - громадянка України; 85 – інше;
|MotherСitizenship Another|Громадянство матері (тип інше)|string|необов'язково|Надається при значенні  MotherСitizenship = 85
|====

[TIP]
====
Актуальну інформацію щодо необхідних ідентифікаторів сервісу та його постачальника, а також опис параметрів і WSDL, ви можете отримати в https://catalog.trembita.gov.ua/?env=SEVDEIR[офіційному каталозі "Трембіта"].
====

== Пов'язані сторінки

* xref:registry-develop:bp-modeling/bp/element-templates/soap-integration/dracs/get-certificate-by-birthdate.adoc[SOAP-конектор _Get Certificate By Birthdate_]