= Сервіс пошуку суб'єкта в ЄДР (_SearchSubjects_)
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Огляд сервісу

Сервіс *`SearchSubjects`* надає можливість здійснити пошук в Єдиному державному реєстру юридичних та фізичних осіб (ЄДР) та отримати відомості щодо загальної інформації про суб'єкта відповідно до критеріїв пошуку через ШБО "Трембіта".

Пошук суб'єкта в ЄДР здійснюється за параметрами:

* `code` -- код ЄДРПОУ або РНОКПП;
* `passport` -- серія та/або номер документа, що посвідчує фізичну особу;
* `name` -- назва організації юридичної особи або ПІБ фізичної особи-підприємця (ФОП).

[NOTE]
====
Серія та номер паспорта використовується для фізичної особи-підприємця, якщо особа відмовилась від отримання ІПН (РНОКПП). Формат: серія (дві кириличні літери у верхньому регістрі), об'єднана з шістьма цифрами номера, наприклад: СН012345; або, у разі нового пластикового паспорта, номер у вигляді дев'яти цифр
====

.Запит у форматі XML
[source, xml]
----
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:edr="http://nais.gov.ua/api/sevdeir/EDR" xmlns:xro="http://x-road.eu/xsd/xroad.xsd" xmlns:iden="http://x-road.eu/xsd/identifiers">
   <soapenv:Header>
      <edr:AuthorizationToken>00000000000000000000000000000000000000</edr:AuthorizationToken>
      <xro:protocolVersion>4.0</xro:protocolVersion>
      <xro:id>MDTUDDM</xro:id>
      <xro:userId>MDTUDDM</xro:userId>
      <xro:service iden:objectType="SERVICE">
         <iden:xRoadInstance>SEVDEIR-TEST</iden:xRoadInstance>
         <iden:memberClass>GOV</iden:memberClass>
         <iden:memberCode>00015622</iden:memberCode>
         <!--Optional:-->
         <iden:subsystemCode>2_MJU_EDR_prod</iden:subsystemCode>
         <iden:serviceCode>SearchSubjects</iden:serviceCode>
         <!--Optional:-->
      </xro:service>
      <xro:client iden:objectType="SUBSYSTEM">
         <iden:xRoadInstance>SEVDEIR-TEST</iden:xRoadInstance>
         <iden:memberClass>GOV</iden:memberClass>
         <iden:memberCode>43395033</iden:memberCode>
         <!--Optional:-->
         <iden:subsystemCode>IDGOV_TEST_01</iden:subsystemCode>
      </xro:client>
   </soapenv:Header>
   <soapenv:Body>
      <edr:SearchSubjects>
         <edr:code>0000000000</edr:code>
      </edr:SearchSubjects>
   </soapenv:Body>
</soapenv:Envelope>
----

.Відповідь у форматі XML
[source, xml]
----
<soap11env:Envelope xmlns:soap11env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tns="http://nais.gov.ua/api/sevdeir/EDR" xmlns:xroad="http://x-road.eu/xsd/xroad.xsd" xmlns:id="http://x-road.eu/xsd/identifiers">
   <soap11env:Header>
      <tns:AuthorizationToken>00000000000000000000000000000000000000</tns:AuthorizationToken>
      <xroad:userId>MDTUDDM</xroad:userId>
      <xroad:client id:objectType="SUBSYSTEM">
         <id:xRoadInstance>SEVDEIR-TEST</id:xRoadInstance>
         <id:memberClass>GOV</id:memberClass>
         <id:memberCode>43395033</id:memberCode>
         <id:subsystemCode>IDGOV_TEST_01</id:subsystemCode>
      </xroad:client>
      <xroad:service id:objectType="SERVICE">
         <id:xRoadInstance>SEVDEIR-TEST</id:xRoadInstance>
         <id:memberClass>GOV</id:memberClass>
         <id:memberCode>00015622</id:memberCode>
         <id:subsystemCode>2_MJU_EDR_prod</id:subsystemCode>
         <id:serviceCode>SearchSubjects</id:serviceCode>
      </xroad:service>
      <xroad:protocolVersion>4.0</xroad:protocolVersion>
      <xroad:id>MDTUDDM</xroad:id>
      <xroad:requestHash algorithmId="http://www.w3.org/2001/04/xmldsig-more#gost34311">0000000000000000000000000000000</xroad:requestHash>
   </soap11env:Header>
   <soap11env:Body>
      <tns:SearchSubjectsResponse>
         <tns:SubjectList>
            <tns:SubjectInfo>
               <tns:state>1</tns:state>
               <tns:state_text>зареєстровано</tns:state_text>
               <tns:name>МІНІСТЕРСТВО ЮСТИЦІЇ УКРАЇНИ</tns:name>
               <tns:url>http://zqedr-api.nais.gov.ua/1.0/subjects/00000000</tns:url>
               <tns:code>00000000</tns:code>
               <tns:id>1234567</tns:id>
            </tns:SubjectInfo>
         </tns:SubjectList>
      </tns:SearchSubjectsResponse>
   </soap11env:Body>
</soap11env:Envelope>
----

.Опис структурних параметрів
|====
|Параметр| Опис| Тип| Важливість
4+|Блок SubjectInfo "Інформація про суб'єкта"
|id|Внутрішній унікальний ідентифікатор суб'єкта в БД ЄДР|string|необов'язково
|state|Код стану суб'єкта|string|необов'язково
|state_text|Текстове відображення стану суб'єкта|string|необов'язково
|code|ЄДРПОУ; якщо суб'єкт - фізична особа-підприємець - замість ІПНа буде десять нулів|string|необов'язково
|name|Назва суб'єкта|string|необов'язково
|url|Посилання на деталізовану інформацію про суб'єкта (при використанні API)|string|необов'язково
4+|Блок errors "Помилки"
|code||string|необов'язково
|message||string|необов'язково
|inner_code||string|необов'язково
|inner_message||string|необов'язково
|====

[#edr-subject-state]
.Можливі значення стану (`state`) суб'єкта з ЄДР
|====
|`statusValue` (Стан)|Мапінг|Опис
|`-1`|`SUSPENDED`|Призупинено
|`1`|`ACTIVE`|Суб'єкт є активним
|`2`|`CANCEL_STATE`|У процесі анулювання
|`3`|`CANCELED`|Анульовано
|`4`|`BANKRUPTCY_PROCEEDINGS_INITIATED`|Ініційовано процедуру банкрутства
|`5`|`BANKRUPTCY_PROCEEDINGS_INITIATED_SANITATION`|Ініційовано процедуру банкрутства з санацією
|`6`|`ACTIVE_GOV_REGISTRATION_INVALID`|Суб'єкт є активним, але є проблеми з державною реєстрацією
|====

[TIP]
====
Актуальну інформацію щодо необхідних ідентифікаторів сервісу та його постачальника, а також опис параметрів і WSDL, ви можете отримати в https://catalog.trembita.gov.ua/?env=SEVDEIR[офіційному каталозі "Трембіта"].
====

== Пов'язані сторінки

* xref:registry-develop:bp-modeling/bp/element-templates/soap-integration/edr/search-subjects-edr-registry.adoc[SOAP-конектор _Search Subjects Edr Registry_]