= Сервіс отримання детальної інформації про суб'єкта в ЄДР (_SubjectDetail_)
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Огляд сервісу

Сервіс *`SubjectDetail`* надає можливість здійснити пошук у _Єдиному державному реєстру юридичних та фізичних осіб_ (ЄДР) та отримати відомості щодо детальної інформації про суб'єкта відповідно до критеріїв пошуку через ШБО "Трембіта".

Пошук суб'єкта в ЄДР здійснюється за параметром:

* `id` -- внутрішній унікальний ідентифікатор суб'єкта в БД ЄДР;

.Запит у форматі XML
[source, xml]
----
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:edr="http://nais.gov.ua/api/sevdeir/EDR" xmlns:xro="http://x-road.eu/xsd/xroad.xsd" xmlns:iden="http://x-road.eu/xsd/identifiers">
   <soapenv:Header>
      <edr:AuthorizationToken>00000000000000000000000000000000000000</edr:AuthorizationToken>
      <xro:protocolVersion>4.0</xro:protocolVersion>
      <xro:id>MDTUDDM</xro:id>
      <xro:userId>MDTUDDM</xro:userId>
      <xro:service iden:objectType="SERVICE">
         <iden:xRoadInstance>SEVDEIR-TEST</iden:xRoadInstance>
         <iden:memberClass>GOV</iden:memberClass>
         <iden:memberCode>00015622</iden:memberCode>
         <!--Optional:-->
         <iden:subsystemCode>2_MJU_EDR_prod</iden:subsystemCode>
         <iden:serviceCode>SubjectDetail</iden:serviceCode>
         <!--Optional:-->
      </xro:service>
      <xro:client iden:objectType="SUBSYSTEM">
         <iden:xRoadInstance>SEVDEIR-TEST</iden:xRoadInstance>
         <iden:memberClass>GOV</iden:memberClass>
         <iden:memberCode>43395033</iden:memberCode>
         <!--Optional:-->
         <iden:subsystemCode>IDGOV_TEST_01</iden:subsystemCode>
      </xro:client>
   </soapenv:Header>
   <soapenv:Body>
      <edr:SubjectDetail>
         <edr:id>1234567</edr:id>
      </edr:SubjectDetail>
   </soapenv:Body>
</soapenv:Envelope>
----

.Відповідь у форматі XML
[source, xml]
----
<soap11env:Envelope xmlns:soap11env="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tns="http://nais.gov.ua/api/sevdeir/EDR" xmlns:xroad="http://x-road.eu/xsd/xroad.xsd" xmlns:id="http://x-road.eu/xsd/identifiers">
   <soap11env:Header>
      <tns:AuthorizationToken>00000000000000000000000000000000000000</tns:AuthorizationToken>
      <xroad:userId>MDTUDDM</xroad:userId>
      <xroad:client id:objectType="SUBSYSTEM">
         <id:xRoadInstance>SEVDEIR-TEST</id:xRoadInstance>
         <id:memberClass>GOV</id:memberClass>
         <id:memberCode>43395033</id:memberCode>
         <id:subsystemCode>IDGOV_TEST_01</id:subsystemCode>
      </xroad:client>
      <xroad:service id:objectType="SERVICE">
         <id:xRoadInstance>SEVDEIR-TEST</id:xRoadInstance>
         <id:memberClass>GOV</id:memberClass>
         <id:memberCode>00015622</id:memberCode>
         <id:subsystemCode>2_MJU_EDR_prod</id:subsystemCode>
         <id:serviceCode>SubjectDetail</id:serviceCode>
      </xroad:service>
      <xroad:protocolVersion>4.0</xroad:protocolVersion>
      <xroad:id>MDTUDDM</xroad:id>
      <xroad:requestHash algorithmId="http://www.w3.org/2001/04/xmldsig-more#gost34311">00000000000000000000000000000000000000=</xroad:requestHash>
   </soap11env:Header>
   <soap11env:Body>
      <tns:SubjectDetailResponse>
         <tns:Subject>
            <tns:open_enforcements>
               <tns:open_enforcement>2015-10-07</tns:open_enforcement>
               <tns:open_enforcement>2015-09-21</tns:open_enforcement>
               <tns:open_enforcement>2014-09-05</tns:open_enforcement>
               <tns:open_enforcement>2014-06-17</tns:open_enforcement>
               <tns:open_enforcement>2015-08-13</tns:open_enforcement>
               <tns:open_enforcement>2015-03-02</tns:open_enforcement>
               <tns:open_enforcement>2016-08-11</tns:open_enforcement>
               <tns:open_enforcement>2016-01-25</tns:open_enforcement>
               <tns:open_enforcement>2015-11-30</tns:open_enforcement>
               <tns:open_enforcement>2016-01-28</tns:open_enforcement>
               <tns:open_enforcement>2016-07-19</tns:open_enforcement>
               <tns:open_enforcement>2016-04-11</tns:open_enforcement>
               <tns:open_enforcement>2015-08-06</tns:open_enforcement>
               <tns:open_enforcement>2015-08-25</tns:open_enforcement>
               <tns:open_enforcement>2015-05-08</tns:open_enforcement>
               <tns:open_enforcement>2015-07-27</tns:open_enforcement>
               <tns:open_enforcement>2015-10-23</tns:open_enforcement>
            </tns:open_enforcements>
            <tns:state>1</tns:state>
            <tns:heads>
               <tns:head>
                  <tns:role>2</tns:role>
                  <tns:first_middle_name>ІГОР ВОЛОДИМИРОВИЧ</tns:first_middle_name>
                  <tns:last_name>БОНДАРЧУК</tns:last_name>
                  <tns:appointment_date>2014-03-14</tns:appointment_date>
                  <tns:role_text>підписант</tns:role_text>
                  <tns:restriction>ВІДПОВІДНО ДО ПОВНОВАЖЕНЬ ВИЗНАЧЕНИХ КЕРІВНИЦТВОМ</tns:restriction>
               </tns:head>
               <tns:head>
                  <tns:role>2</tns:role>
                  <tns:first_middle_name>АНТОН ВОЛОДИМИРОВИЧ</tns:first_middle_name>
                  <tns:last_name>ЯНЧУК</tns:last_name>
                  <tns:appointment_date>2014-06-23</tns:appointment_date>
                  <tns:role_text>підписант</tns:role_text>
                  <tns:restriction>ВІДПОВІДНО ДО ПОВНОВАЖЕНЬ ВИЗНАЧЕНИХ КЕРІВНИЦТВОМ</tns:restriction>
               </tns:head>
               <tns:head>
                  <tns:role>2</tns:role>
                  <tns:first_middle_name>ОКСАНА ПАВЛІВНА</tns:first_middle_name>
                  <tns:last_name>ІВАНЧЕНКО</tns:last_name>
                  <tns:appointment_date>2014-12-29</tns:appointment_date>
                  <tns:role_text>підписант</tns:role_text>
                  <tns:restriction>ВІДПОВІДНО ДО ПОВНОВАЖЕНЬ ВИЗНАЧЕНИХ КЕРІВНИЦТВОМ</tns:restriction>
               </tns:head>
               <tns:head>
                  <tns:role>3</tns:role>
                  <tns:first_middle_name>ПАВЛО ДМИТРОВИЧ</tns:first_middle_name>
                  <tns:last_name>ПЕТРЕНКО</tns:last_name>
                  <tns:appointment_date>2014-02-27</tns:appointment_date>
                  <tns:role_text>керівник</tns:role_text>
                  <tns:restriction/>
               </tns:head>
            </tns:heads>
            <tns:state_text>зареєстровано</tns:state_text>
            <tns:predecessors/>
            <tns:assignees/>
            <tns:registrations>
               <tns:registration>
                  <tns:name>ГОЛОВНЕ УПРАВЛІННЯ РЕГІОНАЛЬНОЇ СТАТИСТИКИ</tns:name>
                  <tns:start_date>1994-09-03</tns:start_date>
                  <tns:code>21680000</tns:code>
                  <tns:type/>
               </tns:registration>
               <tns:registration>
                  <tns:start_num>30215</tns:start_num>
                  <tns:name>ДПI У ПЕЧЕРСЬКОМУ Р-НI ГУ МIНДОХОДIВ У М.КИЄВI</tns:name>
                  <tns:start_date>1997-08-19</tns:start_date>
                  <tns:description>дані про взяття на облік як платника податків</tns:description>
                  <tns:code>38748591</tns:code>
                  <tns:type>4002</tns:type>
               </tns:registration>
               <tns:registration>
                  <tns:start_num>01-029284</tns:start_num>
                  <tns:name>ДПI У ПЕЧЕРСЬКОМУ Р-НI ГУ МIНДОХОДIВ У М.КИЄВI</tns:name>
                  <tns:start_date>2002-03-19</tns:start_date>
                  <tns:description>дані про взяття на облік як платника єдиного внеску</tns:description>
                  <tns:code>38748591</tns:code>
                  <tns:type>4001</tns:type>
               </tns:registration>
            </tns:registrations>
            <tns:id>1095734</tns:id>
            <tns:executive_power>
               <tns:name>КАБІНЕТ МІНІСТРІВ УКРАЇНИ</tns:name>
               <tns:code>00015622</tns:code>
            </tns:executive_power>
            <tns:founders>
               <tns:founder>
                  <tns:capital>0</tns:capital>
                  <tns:role>4</tns:role>
                  <tns:name>указ президента україни від 30.12.1997 №1396/97</tns:name>
                  <tns:role_text>засновник</tns:role_text>
               </tns:founder>
            </tns:founders>
            <tns:activity_kinds>
               <tns:activity_kind>
                  <tns:name>Державне управління загального характеру</tns:name>
                  <tns:is_primary>true</tns:is_primary>
                  <tns:code>84.11</tns:code>
               </tns:activity_kind>
            </tns:activity_kinds>
            <tns:object_name>Відділ державної реєстрації юридичних осіб та фізичних осіб - підприємців Печерського району реєстраційної служби Головного управління юстиції у місті Києві</tns:object_name>
            <tns:registration>
               <tns:is_transformation>false</tns:is_transformation>
               <tns:record_number>10701200000024285</tns:record_number>
               <tns:is_separation>false</tns:is_separation>
               <tns:is_division>false</tns:is_division>
               <tns:record_date>2006-12-05</tns:record_date>
               <tns:date>1997-12-30</tns:date>
               <tns:is_merge>false</tns:is_merge>
            </tns:registration>
            <tns:contacts>
               <tns:tel>
                  <tns:tel_item>2796664</tns:tel_item>
                  <tns:tel_item>2711530</tns:tel_item>
               </tns:tel>
               <tns:email>MINJUST.GOV.UA</tns:email>
               <tns:fax>2711745</tns:fax>
               <tns:web_page/>
            </tns:contacts>
            <tns:authorised_capital>
               <tns:value>0</tns:value>
            </tns:authorised_capital>
            <tns:branches/>
            <tns:olf_name>ОРГАН ДЕРЖАВНОЇ ВЛАДИ</tns:olf_name>
            <tns:olf_code>410</tns:olf_code>
            <tns:address>
               <tns:address>м.Київ, Печерський район ВУЛИЦЯ АРХІТЕКТОРА ГОРОДЕЦЬКОГО буд. 13</tns:address>
               <tns:country>УКРАЇНА</tns:country>
               <tns:parts>
                  <tns:atu_code>8038200000</tns:atu_code>
                  <tns:street>ВУЛИЦЯ АРХІТЕКТОРА ГОРОДЕЦЬКОГО</tns:street>
                  <tns:building/>
                  <tns:house>13</tns:house>
                  <tns:atu>м.Київ, Печерський район</tns:atu>
                  <tns:num/>
                  <tns:house_type>буд.</tns:house_type>
               </tns:parts>
               <tns:zip>01001</tns:zip>
            </tns:address>
            <tns:management>КАБІНЕТ МІНІСТРІВ УКРАЇНИ</tns:management>
            <tns:primary_activity_kind>
               <tns:name>Державне управління загального характеру</tns:name>
               <tns:code>84.11</tns:code>
               <tns:class&gt;1</tns:class&gt;
               <tns:reg_number>01-029284</tns:reg_number>
            </tns:primary_activity_kind>
            <tns:names>
               <tns:short>МІН'ЮСТ</tns:short>
               <tns:include_olf>false</tns:include_olf>
               <tns:name_en/>
               <tns:display>МІНІСТЕРСТВО ЮСТИЦІЇ УКРАЇНИ</tns:display>
               <tns:name>МІНІСТЕРСТВО ЮСТИЦІЇ УКРАЇНИ</tns:name>
               <tns:short_en/>
            </tns:names>
            <tns:is_modal_statute>false</tns:is_modal_statute>
            <tns:code>00015622</tns:code>
         </tns:Subject>
      </tns:SubjectDetailResponse>
   </soap11env:Body>
</soap11env:Envelope>
----

.Опис структурних параметрів
|====
|Параметр| Опис| Тип| Важливість
4+|Блок SubjectInfo "Інформація про суб'єкта"
|id|Внутрішній унікальний ідентифікатор суб'єкта в БД ЄДР|string|необов'язково
|state|Код стану суб'єкта|string|необов'язково
|state_text|Текстове відображення стану суб'єкта|string|необов'язково
|code|ЄДРПОУ; якщо суб'єкт - фізична особа-підприємець - замість ІПНа буде десять нулів|string|необов'язково
4+|Блок name Перелік найменувань суб'єкта
|olf_code|Код організаційно-правової форми суб’єкта, якщо суб’єкт – юридична особа|string|необов'язково
|olf_name|Назва організаційно-правової форми суб’єкта, якщо суб’єкт – юридична особа|string|необов'язково
|founding_document|Назва установчого документа, якщо суб’єкт – юридична особа|string|необов'язково
4+|Блок executive_power Центральний чи місцевий орган виконавчої влади, до сфери управління якого належить державне підприємство або частка держави у статутному капіталі юридичної особи, якщо ця частка становить не менше 25 відсотків
|object_name|Місцезнаходження реєстраційної справи|string|необов'язково
4+|Блок founders Засновники
4+|Блок branches Відокремлені підрозділи юридичної особи
4+|Блок authorised_capital Дані про розмір статутного капіталу (статутного або складеного капіталу) та про дату закінчення його формування, якщо суб’єкт – юридична особа
|management|Відомості про органи управління юридичної особи|string|необов'язково
|managing_paper|Найменування розпорядчого акта, якщо суб’єкт – юридична особа|string|необов'язково
|is_modal_statute|Дані про наявність відмітки про те, що юридична особа створюється та діє на підставі модельного статуту|boolean|необов'язково
4+|Блок activity_kinds Види економічної діяльності
4+|Блок heads Призначені уповноважені особи
4+|Блок address Адреса
4+|Блок registration Дата державної реєстрації, дата та номер запису в Єдиному державному реєстрі про включення до Єдиного державного реєстру відомостей про юридичну особу
4+|Блок bankruptcy Дані про перебування юридичної особи в процесі провадження у справі про банкрутство, санації
4+|Блок termination Дата та номер запису про державну реєстрацію припинення юридичної особи, підстава для його внесення
4+|Блок termination_cancel Дата та номер запису про скасування державної реєстрації припинення юридичної особи, підстава для його внесення
4+|Блок assignees Дані про юридичних осіб-правонаступників: повне найменування та розташування юридичних осіб-правонаступників, їх ідентифікаційні коди
4+|Блок predecessors Дані про юридичних осіб, правонаступником яких є зареєстрована юридична особа
4+|Блок registrations Відомості, отримані в порядку взаємного обміну інформацією з відомчих реєстрів органів статистики, Міндоходів, Пенсійного фонду України
4+|Блок primary_activity_kind
|prev_registration_end_term|Термін, до якого юридична особа перебуває на обліку в органі Міндоходів за місцем попередньої реєстрації, у разі зміни розташування юридичної особи|string|необов'язково
4+|Блок contacts Дані органів статистики про основний вид економічної діяльності юридичної особи, визначений на підставі даних державних статистичних спостережень відповідно до статистичної методології за підсумками діяльності за рік
4+|Блок open_enforcements Дата відкриття виконавчого провадження щодо юридичної особи (для незавершених виконавчих проваджень)
4+|Блок errors "Помилки"
|code||string|необов'язково
|message||string|необов'язково
|inner_code||string|необов'язково
|inner_message||string|необов'язково
|====

[TIP]
====
Актуальну інформацію щодо необхідних ідентифікаторів сервісу та його постачальника, а також опис параметрів і WSDL, ви можете отримати в https://catalog.trembita.gov.ua/?env=SEVDEIR[офіційному каталозі "Трембіта"].
====

== Пов'язані сторінки

* xref:registry-develop:bp-modeling/bp/element-templates/soap-integration/edr/subject-detail-edr-registry.adoc[SOAP-конектор _Get Subject Detail Edr Registry_]