= Функція _sign_submission()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`sign_submission(String activityOrEventId): SignUserFormDataDto`* використовується для отримання підпису та даних форми користувацьких задач.

== Параметри

.Параметри функції
|===
|*Аргумент*            | *Опис*
| `activityOrEventId` | Ідентифікатор задачі або події, для якої потрібно отримати дані форми.
|===

== Що повертає

Ця функція повертає об'єкт типу `SignUserFormDataDto`, що містить дані форми користувача, підпису та ключа CEPH-документа, де зберігається підпис.

.SignUserFormDataDto
|===
|*Поле*            | *Опис*
| `formData`       | Дані форми у вигляді об'єкта `SpinJsonNode`.
| `signature`      | Підпис користувача.
| `signatureDocumentId` | Ідентифікатор документа в CEPH, де зберігається підпис.
|===

TIP: `SignUserFormDataDto` -- клас, що є обгорткою для даних форми користувача, підпису та ключа CEPH-документа, де зберігається підпис.

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

NOTE: Функція `sign_submission(String activityOrEventId)` доступна для використання після успішного завершення задачі, що потребує валідації підписом користувача, або стартової форми.

== Приклади використання

Існує декілька варіантів використання функції `sign_submission()` у бізнес-процесі.

Один із найпоширеніших сценаріїв -- це використання функції в інтеграційних розширеннях (делегатах) для передачі *X-Digital-Signature source* у бізнес-процесі. Вона передає ідентифікатор документа з цифровим підписом, який підтверджує автентичність дій користувача. Це поле вказує на джерело цифрового підпису, що зберігається у Ceph-документі та містить дані КЕП-підпису, накладеного користувачем на одній із попередніх користувацьких форм.

.Приклад використання JUEL-функції
[source,groovy]
----
${sign_submission('UserTask_SignDataBuildInfo').signatureDocumentId}
----

* `'UserTask_SignDataBuildInfo'` -- ID завдання користувача, де було ініційовано процес накладення цифрового підпису.
* `signatureDocumentId` -- унікальний ідентифікатор документа з цифровим підписом, збереженого в системі.

TIP: Застосування функції `sign_submission()` детально показано на прикладі налаштування в інтеграційному розширенні xref:bp-modeling/bp/element-templates/service-task-templates/entity-management/create-entity.adoc[].

== Пов'язані сторінки

* xref:bp-modeling/bp/juel-functions/forms/submission.adoc[]
* xref:bp-modeling/bp/element-templates/service-task-templates/entity-management/create-entity.adoc[]

