= Функція _sign_submission()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`sign_submission(String activityOrEventId): SignUserFormDataDto`* використовується для отримання підпису та даних форми користувацьких задач.

== Параметри

.Параметри функції
|===
|*Аргумент*            | *Опис*
| `activityOrEventId` | Ідентифікатор задачі або події, для якої потрібно отримати дані форми.
|===

== Що повертає

Ця функція повертає об'єкт типу `SignUserFormDataDto`, що містить дані форми користувача, підпису та ключа CEPH-документа, де зберігається підпис.

.SignUserFormDataDto
|===
|*Поле*            | *Опис*
| `formData`       | Дані форми у вигляді об'єкта `SpinJsonNode`.
| `signature`      | Підпис користувача.
| `signatureDocumentId` | Ідентифікатор документа в CEPH, де зберігається підпис.
|===

TIP: `SignUserFormDataDto` -- клас, що є обгорткою для даних форми користувача, підпису та ключа CEPH-документа, де зберігається підпис.

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

NOTE: Функція `sign_submission(String activityOrEventId)` доступна для використання після успішного завершення задачі, що потребує валідації підписом користувача, або стартової форми.

== Приклад

Цей розділ демонструє приклади використання JUEL-функції у завданнях бізнес-процесу.

//TODO: ADD

TIP: Застосування функції `sign_submission()` детально представлено у референтному прикладі на сторінці xref:best-practices/bp-sign-submission-access.adoc[].
