= Функція _submission()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`submission(String activityOrEventId): UserFormDataDto`* дозволяє отримати дані форми користувацької задачі або стартової форми та повертає клас `UserFormDataDto`.

== Параметри

.Параметри функції
|===
|*Аргумент*            | *Опис*
| `activityOrEventId` | Ідентифікатор задачі або події, для якої потрібно отримати дані форми.
|===

== Що повертає

Ця функція повертає об'єкт типу `UserFormDataDto`, що містить дані форми користувача.

.UserFormDataDto
|===
|*Поле*      | *Опис*
| `formData` | Дані форми у вигляді об'єкта `SpinJsonNode`.
|===

TIP: `UserFormDataDto` -- клас, що є обгорткою даних форми користувача.

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

NOTE: Функція `submission(String activityOrEventId)` доступна для використання після успішного завершення користувацької задачі або стартової форми.

== Приклад

Цей розділ демонструє приклади використання JUEL-функції у завданнях бізнес-процесу.

//TODO: ADD

TIP: Застосування функції `submission()` детально представлено у референтному прикладі на сторінці xref:best-practices/bp-submission-access.adoc[].
