= Функція _submission()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`submission(String activityOrEventId): UserFormDataDto`* дозволяє отримати дані форми користувацької задачі або стартової форми та повертає клас `UserFormDataDto`.

== Параметри

.Параметри функції
|===
|*Аргумент*            | *Опис*
| `activityOrEventId` | Ідентифікатор задачі або події, для якої потрібно отримати дані форми.
|===

== Що повертає

Ця функція повертає об'єкт типу `UserFormDataDto`, що містить дані форми користувача.

.UserFormDataDto
|===
|*Поле*      | *Опис*
| `formData` | Дані форми у вигляді об'єкта `SpinJsonNode`.
|===

TIP: `UserFormDataDto` -- клас, що є обгорткою даних форми користувача.

== Методи взаємодії

Ця функція не надає додаткових методів взаємодії.

NOTE: Функція `submission(String activityOrEventId)` доступна для використання після успішного завершення користувацької задачі або стартової форми.

== Приклад використання

Цей розділ демонструє різні сценарії використання JUEL-функції `submission()` у бізнес-процесах.

=== Використання у завданнях користувача

Функція `submission()` може бути корисною при налаштуванні шаблонів делегатів у завданнях користувача, таких як:

* xref:bp-modeling/bp/element-templates/user-task-templates/user-form.adoc[User Form Template]
* xref:bp-modeling/bp/element-templates/user-task-templates/officer-sign-task.adoc[Officer Sign Task]
* xref:bp-modeling/bp/element-templates/user-task-templates/citizen-sign-task.adoc[Citizen Sign Task]

Ви можете використовувати функцію у полі *Form data pre-population*, щоб перенести дані з попереднього завдання:

[source,groovy]
----
${submission('Previous user task ID').formData}
----

*Розбір прикладу:*

* `submission()` -- назва JUEL-функції.
* `'Previous user task ID'` -- ідентифікатор попередньої задачі користувача, яка містила подібний набір полів.
* `formData` -- метод, що дозволяє отримати дані з попередньої форми та передати їх на іншу форму.

Це забезпечує безперервний зв'язок між діями, виконаними у попередньому завданні, і поточним завданням, де такі дані передаються.

=== Використання у сервісних завданнях

Функція `submission()` також корисна у сервісних завданнях, особливо коли потрібно передати дані з UI-форми у вигляді *Payload*:

[source,groovy]
----
${submission('Previous user task ID').formData}
----

**Пояснення:**

У цьому прикладі передаються ID задачі (`'Previous user task ID'`) та дані, введені користувачем на UI-формі, за допомогою методу `formData`.

=== Передача даних як _map_ ключів-значень у сервісних завданнях

Іноді потрібно отримати конкретне значення поля з форми для подальшої обробки. Наприклад:

[source,groovy]
----
submission('Previous user task ID').formData.prop('userName').value()
----

*Розбір прикладу:*

. *`submission('Previous user task ID')`* викликає функцію `submission()` для отримання даних форми, яка була надіслана на етапі процесу, позначеному ідентифікатором `Previous user task ID`.
. *`.formData.prop('userName').value()`* витягує значення поля з ідентифікатором `userName` з форми.

TIP: Детальні приклади дивіться на сторінці xref:best-practices/bp-officer-self-register-manual.adoc[].

=== Використання у скриптових завданнях

Функція `submission()` може бути інтегрована у Groovy-код для обробки цифрових документів або файлів:

[source,groovy]
----
def file = submission('Previous task ID').formData.prop('file').elements().get(0)
----

*Пояснення:*

1. *`submission('Previous task ID')`* викликає функцію `submission()` для отримання даних форми з етапу, позначеного як `Previous task ID`.
2. *`.formData.prop('file')`* витягує поле з ідентифікатором `file`.
3. *`.elements().get(0)`* вибирає перший файл зі списку завантажених файлів, якщо форма дозволяє завантаження кількох файлів.

TIP: Більше інформації дивіться на сторінці xref:bp-modeling/bp/bp-async-data-load.adoc[].

== Пов'язані сторінки

* xref:bp-modeling/bp/element-templates/element-templates-overview.adoc[]
* xref:best-practices/bp-officer-self-register-manual.adoc[]
* xref:bp-modeling/bp/bp-async-data-load.adoc[]