= Об'єктне сховище даних

[NOTE]
--
Сторінка технічної документації у процесі розробки.
--

== Структури даних

=== user-import

Зберігання файлів з переліком посадових осіб для імпорту в реєстр

.Опис атрибутів мета-даних об'єкту
|===
|Атрибут|Тип даних|Опис

|name
|String (Base64)
|Назва файлу з якого відбувається завантаження користувачів
|===

.Опис структури документу для зберігання
|===
|Атрибут|Тип даних|Опис

|vault:v1:
|String
|Зашифрований вміст файлу з якого відбувається завантаження користувачів
|===

.Приклад документу для зберігання
[source,text]
----
vault:v1:q5Rd32QX1bg4CZAmCqeZtliQBZUVfmnqS4wMIXCi9lAp95FRf0Tzx0a7tyFom87ebEbPzR91Yoe2lbAaWbf+Gi547r7MI+YEiFEYXPNeWorO2XReVXJ8pMRdUOz8AxOPkmfOG2/gbDN2cYuWWOpqpXGHrz/QHmKSt7PdT66E7Dc49u3hDxbkiMVwfd0bYxph8ysV7XEkbmxZMK7OEPv07CKx93ePfdGVyQuvNOLNpmocDf
----

Зі структурою CSV-файлу можна ознайомитись в xref:registry-develop:registry-admin/import-users-officer-description-file-csv.adoc[статті]

=== user-import-archive

Зберігання файлів з переліком посадових осіб, які було імпортовано в реєстр нічим не відрізняється від структури що зберігається в бакеті `user-import`
