= Об'єктне сховище даних

== Загальний опис

_xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Підсистема моделювання регламенту реєстру]_ використовує об'єктне сховище xref:arch:architecture/platform-technologies.adoc#ceph[Ceph] з  xref:arch:architecture/platform/operational/distributed-data-storage/overview.adoc[_Підсистеми розподіленого зберігання даних_] для зберігання CSV-файлів з переліком посадових осіб запланованих для імпорту або вже імпортованих в реєстр.

== Структури даних

=== user-import

Бакет для зберігання CSV-файлів з переліком посадових осіб для імпорту в реєстр

[NOTE]
--
Зі структурою CSV-файлу можна ознайомитись в xref:registry-develop:registry-admin/import-users-officer-description-file-csv.adoc[статті]
--

.Опис атрибутів мета-даних об'єкту
|===
|Атрибут|Тип даних|Опис

|`name`
|_String (Base64)_
|Назва файлу з якого відбувається завантаження користувачів
|===

.Опис структури документу для зберігання
|===
|Атрибут|Тип даних|Опис

|`vault:v1:`
|_String_
|Зашифрований вміст файлу з якого відбувається завантаження користувачів
|===

.Приклад документу для зберігання
[source,text]
----
vault:v1:q5Rd32QX1bg4CZAmCqeZtliQBZUVfmnqS4wMIXCi9lAp95FRf0Tzx0a7tyFom87ebEbPzR91Yoe2lbAaWbf+Gi547r7MI+YEiFEYXPNeWorO2XReVXJ8pMRdUOz8AxOPkmfOG2/gbDN2cYuWWOpqpXGHrz/QHmKSt7PdT66E7Dc49u3hDxbkiMVwfd0bYxph8ysV7XEkbmxZMK7OEPv07CKx93ePfdGVyQuvNOLNpmocDf
----

=== user-import-archive

Бакет для зберігання файлів з переліком посадових осіб, які було імпортовано в реєстр. Документи мають аналогічно структуру та мета-дані, що і в бакеті `user-import`.