= Цифровий регламент реєстру

_Регламент реєстру_ - цифрове представлення важливих аспектів функціонування реєстру, яке складається з декларативних описів організаційної структури, моделі даних, інформаційних та адміністративних послуг, інтеграцій з зовнішніми системами, тощо.

Регламент реєстру зберігається в окремому репозиторії системи контроля версій _Git_ (_Gerrit_), що забезпечує реалізацію вимог безпеки, аудиту та відновлюваності.

== Структура регламенту реєстру

=== Логічна структура

На даній структурній діаграмі представлено складові частини _регламенту реєстру_, які наразі підтримуються _Платформою Реєстрів_. В залежності від вимог кожного окремого реєстру, набір необхідних для реалізації складових може змінюватись.

image::architecture/registry/administrative/regulation-management/regulation-structure.svg[]

=== Структура репозиторію

Представлення регламенту реєстру на файловій системі в _Git_-репозиторії:
[plantuml, registry-regulation-structure, svg]
----
@startsalt
{
{T
+ <&folder> <i><registry-regulation></i>
++ <&folder> <b>data-model</b>
+++ <&file> main-liquibase.xml
+++ <&file> <i><liquibase-file></i>.xml
+++ <&file> ...
++ <&folder> <b>bpmn</b>
+++ <&file> <i><bp-name></i>.bpmn
+++ <&file> ...
++ <&folder> <b>bp-grouping</b>
+++ <&file> bp-grouping.yml
++ <&folder> <b>dmn</b>
+++ <&file> <i><rule-name></i>.dmn
+++ <&file> ...
++ <&folder> <b>forms</b>
+++ <&file> <i><form-name></i>.json
+++ <&file> ...
++ <&folder> <b>form-scripts</b>
+++ <&file> <i><script-name></i>.js
+++ <&file> ...
++ <&folder> <b>roles</b>
+++ <&file> citizen.yml
+++ <&file> officer.yml
++ <&folder> <b>bp-auth</b>
+++ <&file> citizen.yml
+++ <&file> external-system.yml
+++ <&file> officer.yml
++ <&folder> <b>excerpts-csv</b>
+++ <i><template-name></i>.json
+++ <&file> ...
++ <&folder> <b>excerpts-docx</b>
+++ <i><template-name></i>.docx
+++ <&file> ...
++ <&folder> <b>excerpts</b>
+++ <&folder> <i><template-name></i>
++++ <&file> index.html.ftl
+++ <&folder> ...
++ <&folder> <b>reports</b>
+++ <&file> <i><report-name></i>.json
+++ ...
++ <&folder> <b>notifications</b>
+++ <&folder> <b>inbox</b> (<i>channel</i>)
++++ <&folder> <i><template-name></i>
+++++ <&file> notification.ftl
+++++ <&file> notification.yml
++++ <&folder> ...
+++ <&folder> <b>email</b> (<i>channel</i>)
++++ <&folder> <i><template-name></i>
+++++ <&file> notification.ftlh
+++++ <&file> notification.yml
++++ <&folder> ...
+++ <&folder> <b>diia</b> (<i>channel</i>)
++++ <&folder> <i><template-name></i>
+++++ <&file> notification.diia
+++++ <&file> notification.yml
++++ <&folder> ...
++ <&folder> <b>bp-trembita</b>
+++ <&file> configuration.yml
+++ <&file> external-system.yml
++ <&folder> <b>global-vars</b>
+++ <&file> camunda-global-system-vars.yml
++ <&folder> <b>settings</b>
+++ <&file> settings.yml
++ <&folder> <b>mock-integrations</b>
+++ <&file> <i><external-system-name></i>.json
+++ <&file> ...
++ <&folder> <b>autotests</b>
+++ <&file> ...
++ <&file> settings.yml
}
}
@endsalt
----

== Складові регламенту реєстру

=== Інформаційні панелі реєстру

Інформаційні панелі реєстру, які доступні через _Підсистему аналітичної звітності_ для перегляду даних та журналу подій аудиту реєстру. Представлені у вигляді файлів _JSON_-формату, сумісного з _Redash_ в директорії `./reports`.

[TIP]
--
Детальніше з дизайном підсистем, які відповідають за моделювання та використання складової регламенту можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[]
* xref:arch:architecture/registry/operational/reporting/overview.adoc[]
--

=== Загальні налаштування реєстру

Складова представлена двома директоріями та файлами налаштувань в _YAML_-форматі:

- `./settings` - Налаштування кастомізацій реєстру (коротка назва, повна назва, тощо.)
- `./global-vars` - Налаштування реєстру (активна тема кабінетів, поштова адреса служби підтримки, тощо.)


=== Налаштування інструментів тестування реєстру

Складова представлена наступними директоріями:

- `./autotests` - набір _BDD_ функціональних тестів для автоматизованого тестування реєстру
- `./mock-integrations` - набір _JSON_-файлів у _Wiremock_-форматі з описом правил мокування API зовнішніх систем з ціллю їх подальшої симуляції у процесі ручного та автоматизованого тестування реєстру.

[TIP]
--
Детальніше з дизайном підсистем, які відповідають за моделювання та використання складової регламенту можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[]
* xref:arch:architecture/registry/operational/ext-systems-simulation/overview.adoc[]
--
=== Шаблони витягів з реєстру

Складова представлена наступними директоріями:

- `./excerpts` - ...
- `./excerpts-docx` - ...
- `./excerpts-csv` - ...

[TIP]
--
Детальніше з дизайном підсистем, які відповідають за моделювання та використання складової регламенту можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[]
* xref:arch:architecture/registry/operational/excerpts/overview.adoc[]
--

=== Шаблони інформаційних повідомлень реєстру

Складова представлена наступними директоріями:

- `./notifications/inbox` - ...
- `./notifications/email` - ...
- `./notifications/diia` - ...

[TIP]
--
Детальніше з дизайном підсистем, які відповідають за моделювання та використання складової регламенту можна ознайомитись у відповідних розділах:

* xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[]
* xref:arch:architecture/registry/administrative/regulation-publication/overview.adoc[]
* xref:arch:architecture/registry/operational/notifications/overview.adoc[]
--

=== Права доступу до бізнес-процесів реєстру

=== Інтеграція реєстру з зовнішніми системами

=== Бізнес-процеси реєстру

=== UI-форми бізнес-процесів реєстру

=== Модель даних реєстру
