= Підсистема журналювання подій

== Загальний опис

Підсистема, що забезпечує централізоване зберігання технічних журналів логування як компонентів платформи, так і реєстру в уніфікованому вигляді,
повнотекстовий пошук по ним та побудову інформаційно-аналітичних представлень через спеціалізовані веб-інтерфейси.

== Функції підсистеми

* Збереження журналів подій застосунків Платформи.
* Збереження журналів подій платформи оркестрації контейнерів OpenShift.
* Обробка журналів подій та збереження їх до пошукового сервера.
* Візуалізація даних журналів подій через вебінтерфейси.

== Технічний дизайн підсистеми
Підсистема журналювання збирає інформацію про події з усього кластера, як платформні, так і реєстрові, та зберігає їх у спеціальному сховищі.
Для візуалізації даних використовується веб-інтерфейс `Kibana`.

Підсистема журналювання подій агрегує такі типи журналів:

* Реєстрові компоненти: журнали контейнерів, що складають собою реєстр.
* Інфраструктура: журнали, створені контейнерами інфраструктури, які працюють на платформі оркестрації контейнерів OpenShift.
+
TIP: Інфраструктурні компоненти — це поди, які працюють у проектах `openshift*`, `kube*` або `default`.

* Аудит віртуальних машин: журнали, створені `auditd`, системою аудиту віртуальних машин OpenShift, які зберігаються у файлі `/var/log/audit/audit.log`, та аудиторські журнали Kubernetes APIServer та OpenShift APIServer.
+
TIP: За замовчуванням, підсистема журналювання не зберігає журнали аудиту в сховищі `Elasticsearch`.
За потребою можливо налаштувати це, щоб, наприклад, переглядати їх у `Kibana`.

Компоненти підсистеми журналювання подій містить наступні основні компоненти:

* Експортери — агрегує журнали з компонентів Платформи та реєстрів, форматує їх та пересилає до сховища журналів. Поточна реалізація — `Fluentd`.
* Сховище журналів — зберігає журнали компонентів. За замовчуванням використовується `Elasticsearch`, що оптимізований для короткотривалого зберігання.
* Візуалізація — це інтерфейс користувача, що використовується для перегляду журналів та інформаційних панелей. Поточна реалізація - `Kibana`.

На даній діаграмі зображено компоненти, які входять в _Підсистему журналювання подій_ та їх взаємодію з іншими підсистемами.

.Компонентна діаграма _Підсистеми журналювання подій_
image::architecture/platform/operational/logging/logging-subsystem.drawio.svg[width=800,float="center",align="center"]

== Складові підсистеми

|===
|Назва компоненти|Namespace|Deployment|Походження|Репозиторій|Призначення

|_Веб-інтерфейс перегляду журналу подій Платформи_
|`openshift-logging`
|`kibana`
|3rd-party
.4+|https://github.com/epam/edp-ddm-logging[github:/epam/edp-ddm-logging]
|Веб-інтерфейс для доступу, пошуку та відображення технічних журналів подій в Платформі.

|_Сховище журналів Платформи_
|`openshift-logging`
|`elasticsearch-cdm`
|3rd-party
|Виконує роль сховища журналів, де зберігаються всі зібрані експортерами дані. Elasticsearch дозволяє швидко та ефективно
проводити пошук та аналіз агрегованих даних з журналів.

|_Оператор підсистеми журналювання подій_
|`openshift-logging`
|`cluster-logging-operator`
|3rd-party
|Забезпечення налаштування, розгортання та обслуговування підсистеми журналювання подій в OpenShift.

|_Оператор сховища журналів_
|`openshift-operators-redhat`
|`elasticsearch-operator`
|3rd-party
|Забезпечення налаштування, розгортання та обслуговування сховища журналів подій Elasticsearch в OpenShift.

|===

== Інформаційні панелі Kibana
Наведені нижче інформаційні панелі встановлюються вручну за відповідними інструкціями для адміністраторів.

|===

|Інформаційна панель|Технічна назва|Призначення|Посилання

|Інформаційна панель запитів
|`request-dashboard`
|Надає оглядову інформацію про роботу реєстру, зокрема статуси виконання зовнішніх запитів.
|https://raw.githubusercontent.com/epam/edp-ddm-logging/main/dashboards/kibana/request-dashboard.json[edp-ddm-logging/main/dashboards/kibana/request-dashboard.json]

|Інформаційна панель журналів подій
|`kibana-logs-dashboard`
|Надає консолідовану інформацію з усіх зібраних журналів подій.
|https://raw.githubusercontent.com/epam/edp-ddm-logging/main/dashboards/kibana/request-dashboard.json[edp-ddm-logging/main/dashboards/kibana/request-dashboard.json]

|===

== Технологічний стек
При проєктуванні та розробці підсистеми, були використані наступні технології:

* xref:arch:architecture/platform-technologies.adoc#elasticsearch[Elasticsearch]
* xref:arch:architecture/platform-technologies.adoc#kibana[Kibana]
* xref:arch:architecture/platform-technologies.adoc#fluentd[Fluentd]
* xref:arch:architecture/platform-technologies.adoc#okd[OKD]

== Атрибути якості підсистеми
=== _Scalability_
_Підсистема журналювання подій_ розгортнута в High Availability режимі з декількома екземплярами ключових компонентів, що
дозволяє ефективно опрацьовувати журнали подій навіть при наявності великої кількості розгорнутих реєстрів на Платформі.

=== _Performance_
_Підсистема журналювання подій_ забезпечує швидкий повнотекстовий пошук та аналіз даних з журналів подій завдяки оптимізованому сховищу Elasticsearch та пошуковому синтаксису Lucene.

=== _Reliability_
_Підсистема журналювання подій_ може працювати надійно та продовжувати реєструвати події навіть при відмові в роботі окремих
компонентів чи віртуальних машин.

=== _Observability_
_Підсистема журналювання подій_ фіксує та надає детальну інформацію про події в Платформі з метою спрощення ідентифікації
та розв'язання можливих збоїв та проблем адміністраторами Платформи при промисловій експлуатації Платформи.
