:toc-title: ЗМІСТ
:toc: auto
:toclevels: 5
:experimental:
:important-caption:     ВАЖЛИВО
:note-caption:          ПРИМІТКА
:tip-caption:           ПІДКАЗКА
:warning-caption:       ПОПЕРЕДЖЕННЯ
:caution-caption:       УВАГА
:example-caption:           Приклад
:figure-caption:            Зображення
:table-caption:             Таблиця
:appendix-caption:          Додаток
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Налаштування шаблону push-повідомлення з кодом для підтвердження каналу зв'язку "Дія"

== Загальний опис

Для налаштування функції відправлення _push_-сповіщень користувачам у мобільний застосунок "Дія", користувач має спочатку підтвердити, тобто авторизувати канал зв'язку `diia`. Таким чином, користувач верифікує обмін даними (push-повідомленнями) між двома системами -- Кабінетом отримувача послуг та мобільним застосунком "Дія".

Підтвердження каналу зв'язку використовує механізм верифікації даних за допомогою псевдовипадкового 6-значного OTP-коду, що генерується платформою і надходить до "Дії".

Власне відправлення OTP-коду -- це вже повідомлення, що містить OTP-код. І відправлення такого повідомлення вимагає попередньо xref:#registry-regulations-modeling[змодельованого шаблону] у структурі регламенту реєстру.

[#registry-regulations-modeling]
== Моделювання регламенту

Базовий репозиторій розгортання регламенту _registry-regulations_ розширено директорією _channel-confirmation_, яка містить шаблон https://uk.wikipedia.org/wiki/%D0%A2%D0%B5%D1%85%D0%BD%D0%BE%D0%BB%D0%BE%D0%B3%D1%96%D1%8F_push[_push_-повідомлення] із плейсхолдеромfootnote:[Плейсхолдер (_англ. -- *placeholder_*) -- заповнювач тексту.] для OTP-кодуfootnote:[Одноразовий пароль (_англ. -- *one time password, OTP_*) -- це пароль, який є дійсним тільки для одного сеансу автентифікації. Його дія також може бути обмежена певним проміжком часу. Перевага такого пароля перед статичним полягає у тому, що його неможливо використовувати повторно.], що генеруватиметься системою та надсилатиметься громадянам у мобільний додаток "Дія".

Типовий шаблон для підтвердження каналу зв'язку "Дія" має наступну структуру: ::

[plantuml, email-notification-structure, svg]
----
@startsalt
{
{T
+ <&folder> registry-regulations
++ ...
++ <&folder> notifications
+++ <&folder> diia
++++ <&folder> <b>channel-confirmation</b>
+++++ <&file> notification.diia
+++++ <&file> notification.yml
++++ ...
}
}
@endsalt
----

Шлях до шаблону виглядає наступним чином: ::
----
registry-regulations/notifications/diia/channel-confirmation
----

Директорія _channel-confirmation_ містить 2 файли: ::

* _notification.diia_ -- це текстовий формат шаблону повідомлення з плейсхолдером для OTP-коду.

+
.Шаблон із кодом підтвердження каналу зв'язку
====
[source,text]
----
Код підтвердження: ${verificationCode}
----
`${verificationCode}` -- плейсхолдер для коду підтвердження/OTP-коду.
====

* _notification.yml_ -- Конфігураційний файл з метаданими для відправлення повідомлення.

+
.Шаблон з атрибутами відправлення push-нотифікацій для підтвердження каналу зв'язку
====
[source,yaml]
----
title: "Підтвердження каналу зв'язку реєстру"
attributes:
  actionType: "message"
  templateType: "attention"
  shortText : "Підтвердження каналу зв'язку реєстру"
----
Обов'язкові атрибути: ::

* `title` -- Заголовок повідомлення. Вкажіть будь-який текст за бажанням.
* `actionType` -- Тип дії.
+
IMPORTANT: Необхідно вказати саме тип `actionType: "message"`, інакше "Дія" не зможе приймати повідомлення.

* `templateType` -- Тип шаблону.
+
IMPORTANT: Необхідно вказати саме тип `templateType: "attention"`, інакше "Дія" не зможе приймати повідомлення.

* `shortText` -- Короткий зміст повідомлення. Вкажіть будь-який текст за бажанням.
====

Згенерований 6-значний псевдовипадковий код (наприклад, `010203`) автоматично надсилатиметься користувачеві у мобільний застосунок "Дія" для перевірки та підтвердження контактних даних, за умови активації каналу зв'язку "Дія" у профілі Кабінету отримувача послуг.

TIP: Перегляньте сторінку xref:user:citizen/user-notifications/diia-push-otp.adoc[] для отримання деталей.

IMPORTANT: Після оновлення наявного реєстру, для правильної роботи функціональності, адміністратор регламенту має в ручному режимі додати до каталогу _notifications/diia_ папку _channel-confirmation_ із відповідними файлами шаблону підтвердження, як показано на прикладах вище.
