= Моделювання бізнес-процесів за допомогою веб-редактора

== Функціональні сценарії

[TIP]
Описати функціональні сценарії, які необхідно реалізувати в рамках дизайну рішення

- Створення нових _BPMN_ моделей бізнес-процесів
- Внесення змін до існуючих _BPMN_ моделей бізнес-процесів
- Перегляд _BPMN_ моделей бізнес-процесів
- Перегляд _XML_-коду представлення _BPMN_ моделей бізнес-процесів
- Використання каталогу типових розширень для спрощення моделювання бізнес-процесів

== Ключові вимоги

[TIP]
Описати основні вимоги, які необхідно врахувати в рамках обрання підходу для реалізації рішення

- Надання адміністратору єдиного веб-інтерфейсу моделювання бізнес-процесів без необхідності встановлення спеціального ПЗ _Camunda Modeler_ на локальну машину
- Веб-інтерфейс має повторювати усі функціональні можливості _Camunda Modeler_, необхідні для роботи з _BPMN_ моделями бізнес-процесів
- Веб-інтерфейс моделювання має підтримувати локалізацію
- Веб-інтерфейс моделювання має підтримувати темування та стилізацію задля цілісної інтеграції у інтерфейс _Системи адміністрування регламенту реєстру_
- Веб-інтерфейс моделювання має підтримувати усі існуючи типові розширення каталогу моделювання, розроблені у вигляді _Element Templates_
- Веб-інтерфейс моделювання має генерувати _BPMN 2.0_ _XML_-код представлення моделі бізнес-процесів сумісний з поточною версією _Camunda BPM_

== Out of Scope

[TIP]
Описати вимоги, які не було розглянуто детально у процесі аналізу та дизайну

== Технологічний стек

[TIP]
Описати технології, які обрано для реалізації рішення

|===
|Технологія / Бібліотека|Версія|Ліцензія|Документація|Опис

|https://...[ReactJS]
|...
|...
|...
|...

|https://...[TypeScript]
|...
|...
|...
|...

|https://...[bpmn-js]
|...
|...
|...
|...

|https://...[bpmn-js-properties-panel]
|...
|...
|...
|...

|...
|...
|...
|...
|...

|===

== Підтримка типових розширень _Element Templates_

[TIP]
Описати механізм підключення та оновлення каталогу типових розширень

== Підтримка темування та стилізації

[TIP]
Описати механізм реалізації вимоги

== Підтримка локалізації

[TIP]
Описати механізм реалізації вимоги

== Інтерфейс моделювання

[TIP]
Додати екрани для візуалізації досвіду моделювання згідно функціональних сценаріїв