= Порівняння версій бізнес-процесів регламенту реєстру

== Функціональні сценарії

[TIP]
Описати функціональні сценарії, які необхідно реалізувати в рамках дизайну рішення

- _Side-by-side_ порівняння версій _BPMN_ моделей бізнес-процесів регламенту реєстру
- _Side-by-side_ порівняння _XML_-коду представлень версій _BPMN_ моделей бізнес-процесів
- Перегляд деталей змін на рівні властивостей окремих _Activity_ бізнес-процесів, переходів, тощо

== Ключові вимоги

[TIP]
Описати основні вимоги, які необхідно врахувати в рамках обрання підходу для реалізації рішення

* Синхронність _Side-by-Side_ перегляду версій бізнес-процесів
* Маркування кольорами відмінностей на рівні окремих _Activity_
** [green]#Додано#
** [yellow]#Змінено#
** [red]#Видалено#
* Перегляд змін властивостей при наведенні на _Activity_
* Перегляд агрегованого переліку відмінностей між бізнес-процесами

== Out of Scope

[TIP]
Описати вимоги, які не було розглянуто детально у процесі аналізу та дизайну

== Технологічний стек

[TIP]
Описати технології, які обрано для реалізації рішення

|===
|Технологія / Бібліотека|Версія|Ліцензія|Документація|Опис

|https://...[ReactJS]
|...
|...
|...
|...

|https://...[TypeScript]
|...
|...
|...
|...

|https://...[bpmn-js]
|...
|...
|...
|...

|https://...[bpmn-js-properties-panel]
|...
|...
|...
|...

|...
|...
|...
|...
|...

|===

== Інтерфейс користувача

[TIP]
Додати екрани для візуалізації досвіду моделювання згідно функціональних сценаріїв