= Аналіз XML-редакторів на відповідність ключовим вимогам

== Функціональні сценарії

[TIP]
Описати функціональні сценарії, які необхідно реалізувати в рамках дизайну рішення

- Внесення змін до _Liquibase_ XML-Changelog файлів опису дата моделі
- Внесення змін до _BPMN_ XML-файлів моделей бізнес-процесів

== Приклади коду для редагування

=== Liquibase XML-Changelog опису дата моделі

[source, xml]
----
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.5.xsd
        http://www.liquibase.org/xml/ns/dbchangelog-ext https://nexus-public-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/repository/extensions/com/epam/digital/data/platform/liquibase-ext-schema/latest/liquibase-ext-schema-latest.xsd">

<changeSet id="table koatuu" author="registry owner">
        <createTable tableName="koatuu" ext:historyFlag="true">
            <column name="koatuu_id" type="UUID" defaultValueComputed="uuid_generate_v4()">
                <constraints nullable="false" primaryKey="true" primaryKeyName="pk_koatuu_id"/>
            </column>
            <column name="code" type="TEXT">
                <constraints nullable="false"/>
            </column>
            <column name="level1" type="TEXT">
                <constraints nullable="false"/>
            </column>
            <column name="level2" type="TEXT">
                <constraints nullable="false"/>
            </column>
            <column name="type" type="TEXT"/>
            <column name="category" type="CHAR(1)"/>
            <column name="name" type="TEXT">
                <constraints nullable="false"/>
            </column>
        </createTable>
    </changeSet>
</databaseChangeLog>
----

=== BPMN XML-файл моделі бізнес-процесу

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bioc="http://bpmn.io/schema/bpmn/biocolor/1.0" xmlns:data="http://data.sh4.red" id="Definitions_0cjpvm2" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="4.6.0">
  <bpmn:collaboration id="Collaboration_0pn1cv8">
    <bpmn:participant id="Participant_02zjlbh" name="" processRef="add-lab" />
  </bpmn:collaboration>
  <bpmn:process id="add-lab" name="" isExecutable="true">
    <bpmn:userTask id="addLabFormActivity" name="" camunda:modelerTemplate="formUserTaskTemplate" camunda:formKey="add-lab-bp-add-lab" camunda:assignee="${initiator}">
      <bpmn:extensionElements>
        <camunda:properties>
          <camunda:property name="eSign" value="" />
        </camunda:properties>
        <camunda:inputOutput>
          <camunda:inputParameter name="userTaskInputFormDataPrepopulate">${payload}</camunda:inputParameter>
        </camunda:inputOutput>
      </bpmn:extensionElements>
    </bpmn:userTask>
  </bpmn:process>
</bpmn:definitions>
----

== Ключові вимоги до редактора

[TIP]
Описати основні вимоги, які необхідно врахувати в рамках обрання підходу для реалізації рішення

- ...

== Out of Scope

[TIP]
Описати вимоги, які не було розглянуто детально у процесі аналізу та дизайну

== Розглянуті рішення

[TIP]
Додати перелік рішень та технологій, які було розглянуто у процесі підготовки дизайну

- ...

== Аналіз на відповідність вимогам

[TIP]
Додати результати аналізу _pros/cons_ розглянутих рішень та технологій

|===
|Критерій / Функціональність|...

|...
|...

|===

== Рішення за результатами аналізу

[TIP]
Додати резолюцію за результатами проведеного аналізу

== Підтримка темування та стилізації

[TIP]
Описати механізм реалізації вимоги

== Інтерфейс веб-редактора

[TIP]
Додати екрани для візуалізації досвіду моделювання згідно функціональних сценаріїв