@startsalt
{
{T
+ <&folder> registry-regulation
++ <&folder> bpmn
++ <&folder> dmn
++ ...
++ <&folder> <b>notifications</b>
+++ <&folder> templates
++++ <&folder> email (<i>channel</i>)
+++++ <&folder> excerpt-generated (<i>template_name</i>)
++++++ <&folder> css
+++++++ <&file> style.css
++++++ <&folder> images
+++++++ <&file> image.jpg
++++++ <&file> notification.ftlh
+++++ ...
++++ <&folder> diia (<i>channel</i>)
+++++ <&folder> excerpt-generated (<i>template_name</i>)
++++++ <&folder> notification.ftl
++++ <&folder> messenger (<i>channel</i>)
+++++ <&folder> excerpt-generated (<i>template_name</i>)
++++++ <&folder> notification.ftl
}
}
@endsalt