= Backup and restore subsystem
include::platform:ROOT:partial$templates/document-attributes/arch-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== Overview

Subsystem that provides safe backup copy and restore operations for Registry and central Platform components and performs Registry disaster recovery.

== Subsystem functions

* Safe backup copy and restore operations for Registry and central Platform components
* Safe backup copy and restore operations for Registry data
* Recovery of Registry and central Platform components
* Registry operation disaster recovery
* Registry resources migration to another Registry Platform instance

== Subsystem technical design

The following diagram displays the components included in the _Backup and restore subsystem_and their interaction with other subsystems within functional scenarios realization.

image::architecture/platform/operational/backup-recovery/backup-subsystem.drawio1.svg[width=800,float="center",align="center"]

== Subsystem components

|===
|Component name|Namespace|Deployment|Source|Repository|Function

|_Backup and recovery service_
|`velero`
|`velero`
|3rd-party
|https://github.com/epam/edp-ddm-backup-management[github:/epam/edp-ddm-backup-management]
|The component for cluster data backup and recovery

|_S3 objects recovery service_
|`velero`
|`restore-job`
|origin
|https://github.com/epam/edp-ddm-backup-management[github:/epam/edp-ddm-backup-management]
|Recovery service for the S3 objects of the Registry

|_S3 objects replication service_
|`velero`
|`replication-job`
|origin
|https://github.com/epam/edp-ddm-backup-management[github:/epam/edp-ddm-backup-management]
|Replication service for the S3 objects of the Registry
|===

== Technological stack

The following technologies were used in system design and development:

* xref:arch:architecture/platform-technologies.adoc#velero[Velero]
* xref:arch:architecture/platform-technologies.adoc#okd[OKD]
* xref:arch:architecture/platform-technologies.adoc#bash[bash]

== Subsystem quality attributes

=== _Reliability_

The _Backup and restore subsystem_ was designed to provide reliable creation of backup copies and allows for the use of backup and recovery operations systematically and on demand.

=== _Scalability_

The _Backup and restore subsystem_ can operate with large volumes of Registry and Platform data and continuously growing amounts of data.

=== _Recoverability_

_Backup and restore subsystem_ allows the Registry Platform to recover Platform and Registry data in case of failure or unplanned situations.