@startuml

participant "ШБО Трембіта" as trembita
participant "ШБО Gateway" as gateway
participant "Конфігурація зовнішніх клієнтів" as config
participant "OpenShift Secret" as secret
participant "Keycloak" as keycloak
participant "Внутрішній сервіс" as service

autonumber
skinparam responseMessageBelowArrow true

note over gateway
Сервіс який налаштован
для роботи з викликами
з "ШБО Трембіта"
Має 2 реалізації: окремо
для бізнес-процесів та
викликів фабрики даних
end note

trembita -> gateway: __Зовнішній виклик__ \n\
**subsystemCode** \n\
**memberClass** \n\
**memberCode**

gateway -> config: __Отримання сервіс аккаунта__ \n\
**subsystemCode** \n\
**memberClass** \n\
**memberCode**

config --> gateway: **serviceAccountName** \n\
**serviceAccountSecretRef**

gateway -> secret: __Отримання паролю сервіс аккаунта__ \n\
**serviceAccountSecretRef**

secret --> gateway: **clientSecret**

gateway -> keycloak: __Отримання токену сервіс аккаунта__ \n\
**serviceAccountName** \n\
**clientSecret**

keycloak --> gateway: **accessToken**

gateway -> service: __Цільовий виклик__ \n\
Headers: \n\
X-Access-Token: **accessToken**

service --> gateway: Відповідь

gateway --> trembita: Відповідь

@enduml