= Компонент File
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Опис компонента

Компонент *File* є елементом інтерфейсу, який дозволяє користувачам вивантажувати або завантажувати файли у формі. Form.io не розміщує жодних завантажених файлів у формах. Натомість файли зберігаються у постачальника сховища, в нашому випадку у _digital-document-service_.


CAUTION: В _admin portal_ немає доступу до _digital-document-service_.

CAUTION: Використовуйте *File* з переліку _Оновлених_ компонентів.

== Основні функції

Компонент *File* підтримує велику кількість опцій для застосування при взаємодії із формою процесу, які розподілені за вкладками.

[tabs]
====
Display ::
include::../general/common-descriptions/display/label.adoc[]
include::../general/common-descriptions/display/label-position.adoc[]
include::../general/common-descriptions/display/description.adoc[]
include::../general/common-descriptions/display/tooltip.adoc[]
include::../general/common-descriptions/display/tabindex.adoc[]
include::../general/common-descriptions/display/hidden.adoc[]
include::../general/common-descriptions/display/disabled.adoc[]

File ::
* *`Display as image(s)`*: замість назви завантаженого файлу у вікні буде відображатися зображення.
* *`File Pattern`*: вказує, які розширення файлів дозволено завантажувати. Файли, не вказані в цьому полі, будуть заборонені для завантаження.
* *`File Minimum Size`*: встановлює мінімальний розмір файлу. Значення має бути додатнім числом, з крапкою в якості розділового знаку у випадку десяткових дробів, з одиницями виміру В, КВ, МВ чи GB (значення без одиниці виміру буде читатися у байтах) та не перевищувати значення поля «File Maximum Size».
* *`File Maximum Size`*: встановлює максимальний розмір файлу. Значення має бути додатнім числом, з крапкою в якості розділового знаку у випадку десяткових дробів, з одиницями виміру В, КВ, МВ чи GB (значення без одиниці виміру буде читатися у байтах) та не перевищувати значення за замовчуванням, яке встановив адміністратор реєстру».
* *`Minimum total size`*: встановлює мінімальний розмір файлів. Значення має бути додатнім числом, з крапкою в якості розділового знаку у випадку десяткових дробів, з одиницями виміру В, КВ, МВ чи GB (значення без одиниці виміру буде читатися у байтах) та не перевищувати значення поля «Maximum total size». Відображається після активації _Multiple Values_.
* *`Maximum total size`*: встановлює максимальний розмір файлів. Значення має бути додатнім числом, з крапкою в якості розділового знаку у випадку десяткових дробів, з одиницями виміру В, КВ, МВ чи GB (значення без одиниці виміру буде читатися у байтах) та не перевищувати значення за замовчуванням, яке встановив адміністратор реєстру». Відображається після активації _Multiple Values_.

Data ::
* *`Multiple Values`*: дозволяє вибрати декілька значень.
include::../general/common-descriptions/data/clear-value-when-hidden.adoc[]
include::../general/common-descriptions/data/custom-default-value.adoc[]
include::../general/common-descriptions/data/calculated-value.adoc[]

Validation ::
include::../general/common-descriptions/validation/required.adoc[]
* *`Resource for validation`*: вказує який ресурс буде використовуватися для валідації файлу, це поле відображається коли користувач вказав розширення файлу _*.csv_ в _File Pattern_.
include::../general/common-descriptions/validation/custom-error-message.adoc[]
include::../general/common-descriptions/validation/custom-validation.adoc[]

API ::
include::../general/common-descriptions/api/index.adoc[]

Conditions ::
include::../general/common-descriptions/conditional/index.adoc[]

Logic ::
include::../general/common-descriptions/logic/index.adoc[]

Table ::
include::../general/common-descriptions/table/index.adoc[]

====

=== Формат даних

.Submission
[source,typescript]
----
 // дані отримані від digital-document-service, після завантаження файлу
[
    {
        checksum: "61b7aeab944b33b867550c4c4d94d66620228ea1094ed2dedb5003cc43807201",
        id: "f8ef4f2b-c37c-49a5-ba9a-a04c51507240"
    }
]
----