@startuml
participant "Web клієнт" as client order 1
participant "Модуль роботи з\nбізнес-процесами" as businessProcessModule order 2
participant "Модуль роботи з файлами" as fileModule order 3
participant "Файловий\nсервіс" as fileService order 4

skinparam responseMessageBelowArrow true

title Читання бізнес-процесу регламенту з вказаної версії

client -> businessProcessModule: запит на видалення\nбізнес-процесу за ім'ям
activate businessProcessModule

  businessProcessModule -> fileModule: отримати файловий\nсервіс для вказаної версії
  activate fileModule
    create fileService
    fileModule -> fileService: ініціалізувати
    alt вказана версія не існує
      fileModule <-- fileService: помилка ініціалізації
      businessProcessModule <-- fileModule: помилка ініціалізації\nфайлового сервісу
      client <-- businessProcessModule: помилка зі статусом\n404 Not Found
    end
    fileModule <-- fileService
    return файловий сервіс
  deactivate fileModule

  businessProcessModule -> fileService: перевірити чи існує бізнес-процес з вказаним ім'ям
  activate fileService
    return ознака існування
  deactivate fileService
  alt бізнес-процес з таким ім'ям не існує
  client <-- businessProcessModule: помилка зі статусом\n404 Not Found
  end

  businessProcessModule -> fileService: видалити файл бізнес-процесу з вказаним ім'ям
  activate fileService
    return
  deactivate fileService

  client <-- businessProcessModule: відповідь зі статусом\n204 No Content
deactivate businessProcessModule
@enduml