= [BN-08-03][S23][A] Можливість збирати окремий інсталер для open source версії Платформи

== Загальний опис

Діаграма послідовності поточного CI/CD процесу:
[plantuml, cicd, svg]
----
@startuml
autoactivate off
actor "Адміністратор SIT" as user order 10
participant "SIT" as sit order 20
participant "control-plane-\nversioner" as versioner order 30
database "control-plane\n-gerrit.git" as cpgerrit order 40
participant "control-plane-\ngerrit" as controlplanegerrit order 50
database "control-plane\n-installer.git" as installer order 60
participant "control-plane\n-installer" as cpinstaller order 70

database "Gerrit" as gerrit order 80
database "Nexus" as nexus order 90

user -> sit: Approve SIT with\nnew component versions
activate sit
sit -> versioner: Start Build
activate versioner
versioner -> sit: Pick component versions from SIT
deactivate sit
versioner -> cpgerrit: Push new component versions to\nstageCR.json, helmfile.yaml
return success
versioner -> controlplanegerrit: Start Build
activate controlplanegerrit
controlplanegerrit -> cpgerrit: Clone repo
controlplanegerrit -> controlplanegerrit: Build cp gerrit
controlplanegerrit -> nexus: Push
return success
versioner -> installer: Push platform component versions\nto helmfile.yaml
return success

activate cpinstaller
versioner -> cpinstaller: Start Build
versioner -> user: Success build
deactivate user
deactivate versioner
cpinstaller -> nexus: Download components images
return success
cpinstaller -> gerrit: Clone components repos
return success
cpinstaller -> cpinstaller: Building archive
cpinstaller -> nexus: Upload installer archive
return success
deactivate nexus
deactivate user
cpinstaller -> user: Success
@enduml

----

=== Обсяг епіку

* Вводиться поняття "Регіону"
+
[source,yaml]
----
global:
  region: global #valid values: global, ua
----
+
* Екзепляр Платформи знає для якого регіону він був зібраний через відповідний параметр у `values.yaml`.
* Набір компонентів в архіві інсталлеру Платформи може змінюватись в залежності від регіону. Наприклад, `conset-data` або `empty-template-registry-regulation` тощо не мають бути присутні в архіві.
* Компонент має знати в якому регіоні він працює через відповідний параметр у `values.yaml` та
  ** має підлаштувати себе сам під роботу в цьому регіоні (feature toggle). Наприклад, адмін-консоль, кабінети, dso тощо.
  ** або його підлаштує пайплайн розгортання реєстру (параметри helm chart). Наприклад, bp-modeller-extensions (element template) налаштується через registry-configuration chart, а `sign-widget-mock` — через `external-integration-mocks` chart.
* Реалізація налаштувань та адаптація кожного компонента не входить в обсяг робіт, та буде відбуватись у рамках інших епіків.
* Global версія Платформи і її компоненти будуть містити всі необхідні ресурси, щоб працювати і в тому числі UA регіоні. Наприклад, в Global версію Keycloak все ще будуть пакуватись автентифікатори.

== Питання

* Reverse engineering opensource збірки Платформи?
* Тестування Global версії. SIT?
