= Розширення для моделювання бізнес-процесів

image::bp-extensions-interaction.svg[]

== Основні принципи
* Розширення бізнес-процесів знаходяться в модулі `business-process-modeler-extensions` та мають свій власний release flow.
[NOTE]
Тимчасово попередні релізи `business-process-modeler-extensions` до 1.8.0.6 включно, знаходяться в `extensions` nexus репозиторії. Наступні релізи будуть знаходитись в `release` репозиторії.

* Під час розгортання `common-web-app` компоненту за допомогою механізму migration scripts відбувається зчитування потрібної версії (значення необхідної версії знаходиться в values.yaml) `business-process-modeler-extensions` ти створення відповідної ConfigMap з необхідним контентом шаблонів розширення
* `admin-portal` модуль використовує файл `business-process-modeler-extensions.js`, створений на основі інформації з відповідної ConfigMap.

== Формат даних `business-process-modeler-extensions.js`

Файл має один масив з елементами розширень бізнес-процесів:

[source,javascript]
----
var ELEMENT_TEMPLATES =
{[
    {template1},
    {template2},
    {templateN}
]}
----

Під час опрацювання `business-process-modeler-extensions` відбувається послідовне зчитування кожного з розширень бізнес-процесів з директорії `element-templates` та збереження контенту кожного розширення як окремого елемента масиву `ELEMENT_TEMPLATES`.

[TIP]
При необхідності перелік та зміст розширень може бути змінено без окремого релізу та розгортання `common-web-app`. Зміни можуть бути внесені шляхом зміни файлу `business-process-modeler-extensions.js` на файловій системі. Зміни збережуться до наступного розгортання нової версії `common-web-app`.
