== Загальний опис

Бекенд-сервіс надання конфігурації регламенту реєстру

*Сервіс надає наступний функціонал:*

[NOTE]
Розділ доповнюється в процесі розробки компоненту

* Версіонована розробка регламенту реєстру

* Створення та редагування:
** Форм
** Бізнес-процесів
** Сутностей моделі даних

* Пакетне завантаження даних користувачів в keycloak
* Отримання переліку шаблонів звітів реєстру

[NOTE]
Всі інші необхідні операції над сутностями конфігурації регламенту реєстру повинні бути виконані з використанням _git та gerrit_ розробником регламенту реєстру

== Загальні принципи реалізації
* Кожній версії-кандидату відповідає Merge Request в Gerrit
* Кожна версії-кандидат має свою власну _git clone_ директорію
* Мастер версія регламенту має власну директорію _git clone_
* Файлова система контейнеру _registry-regulation-management_ є _persistent volume_
* RestAPI для отримання інформації про сутності регламенту реєстру використовує git репозиторії на файловій системі
* Для забезпечення організації одночасної роботи в рамках однієї версії-кандидату використовується Optimistic locking на рівні RestAPI
* Для сутностей _Форми_ та _Бізнес-процеси_ є 1-1 відношення в розрізі сутність та файл на файловій системі
* Сутності _Дата моделі_ знаходяться в в відношенні _1 tabel - 1 file_

