= [DRAFT] Можливість налаштовувати сервіс id.gov.ua як спосіб автентифікації для отримувачів послуг на рівні реєстру

[IMPORTANT]
--
Сторінка технічної документації є баченням майбутньої реалізації, актуальність якого може бути застарілою.
--

== Загальний опис
При розгортанні декількох реєстрів на одному екземплярі платформи може виникати потреба в інтеграції з сервісом id.gov.ua
для отримувачів послуг на рівні окремого реєстру. При цьому ключ шифрування, який є обов'язковим для використання
сервісу id.gov.ua, повинен бути різним для кожного реєстру. Управління цими ключами та налаштуваннями інтеграції
повинно відбуватися через_Веб-інтерфейс управління платформою та реєстрами_.

NOTE: Детальніше з архітектурою інтеграції з id.gov.ua можна ознайомитися
https://id.gov.ua/downloads/IDInfoProcessingD.pdf[за посиланням]

== Концепти
* _Ключ за замовчуванням_ _Сервісу цифрових підписів_ - ключ з яким виконується первинна ініціалізація та контекст якого
використовується для виконання операцій якщо не вказано інший ключ
* _Ключ шифрування_ - ключ який використовується для інтеграції з сервісом id.gov.ua.
* _Ключ підпису_ - ключ який використовується для накладання цифрового підпису системи (електронна печатка)
* _Платформена інтеграція з id.gov.ua_ - інтеграція з сервісом id.gov.ua на рівні платформи

== Функціональні сценарії
* Налаштування інтеграції з id.gov.ua на рівні окремого реєстру для _Кабінету отримувача послуг_ _Адміністратором реєстру_
* Налаштування інтеграції з id.gov.ua на рівні окремого реєстру для _Кабінету надавача послуг_ _Адміністратором реєстру_
* Управління ключами _Адміністратором платформи_
* Вибір _Ключа шифрування_ для інтеграції з id.gov.ua на рівні окремого реєстру для _Кабінету отримувача послуг_
_Адміністратором реєстру_ зі списку попередньо зареєстрованих ключів
* Вибір _Ключа шифрування_ для інтеграції з id.gov.ua на рівні окремого реєстру для _Кабінету надавача послуг_
_Адміністратором реєстру_ зі списку попередньо зареєстрованих ключів
* Вибір _Ключа підпису_ для реєстру _Адміністратором реєстру_ зі списку попередньо зареєстрованих ключів

== Ролі користувачів
* Адміністратор платформи
* Адміністратор реєстру

== Загальні принципи та положення

=== _Сервіс цифрових підписів_
* Доступ до всіх операцій з ключем забезпечується _Сервісом цифрових підписів_
* _Сервіс цифрових підписів_ ініціюється з ключем за замовчуванням в контексті (поточна реалізація)
* У _Сервіс цифрових підписів_ можуть бути додані додаткові ключі з вказанням псевдоніма (alias)
* Додаткові ключі можуть бути як файловими, так і з фізичного носія (Гряда-301, Алмаз тощо)
* При виклику методів _Сервісу цифрових підписів_ можна вказати псевдонім ключа, який буде використовуватися для тієї чи
іншою операції
* Якщо псевдонім ключа не вказано, то використовується ключ за замовчуванням
* Вказати псевдонім ключа необхідно тільки для операцій, в яких результат операції залежить від контексту ключа
(наприклад, методи _/officer/verify_, _/citizen/verify_, _/owner_ не залежать від контексту ключа і результат буде
однаковий для будь-якого ключа)

=== Інтеграція з id.gov.ua
* Для можливості реєстрової інтеграції з id.gov.ua використовуються тіж самі реалізації автентифікатора (first login flow)
та identity провайдерів, що і для платформеної інтеграції з id.gov.ua (_IdGovUaIdentityProviderV2_ та _IdGovUaAuthenticator_)
* Автентифікатори, які відповідають за інтеграцію з id.gov.ua, повинні використовувати _Сервіс цифрових підписів_,
розгорнутий в _Підсистемі управління користувачами та ролями_ (_platform-dso_) (поточний стан)
* Конфігурація автентифікаторів розширюється параметром для вказання _Ключа шифрування_ для інтеграції з id.gov.ua
* Автентифікатор посадових осіб для інтеграції з id.gov.ua так само розширюється параметром для вказання
_Ключа шифрування_
* Параметр _Ключ шифрування_ може мати пусте значення. В такому випадку автентифікатор не буде передавати псевдоним
_Ключа шифрування_ в _Сервіс цифрових підписів_ і буде використовуватися _Ключ за замовчуванням_
* Для інтеграції з id.gov.ua  на рівні реєстру додається новий ідентіті провайдер з типом _IdGovUaIdentityProviderV2_
* Для логіну в кабінет отримувача послуг може бути обраний один з 3 типів автентифікації: widget, platform-id-gov-ua та
registry-id-gov-ua
* Тип автентифікації задається на рівні автентифікатора _ds-citizen-authenticator_
* В залежності від обраного типу автентифікації на сторінці логіну відображається віджет або кнопка
"Увійти через id.gov.ua"
* Кнопка формує посилання або на платформений ідентіті провайдер або на реєстровий ідентіті провайдер для id.gov.ua в
залежності від обраного параметру автентифікації
* При використанні реєстрової або платформеної інтеграції з id.gov.ua не користувач все одно повинен обрати режим громадянина
або фізичної особи на сторінці в _Веб-інтерфейсі управління користувачами та ролями_

=== Керування ключами
* _Адміністратор платформи_ має можливість керувати ключами в окремій секції _Веб-інтерфейсу управління платформою та
реєстрами_
* Всі ключі зберігаються у _Підсистемі управління секретами та шифруванням_
* При налаштуванні Автентифікації отримувачів послуг _Адміністратор реєстру_ може вказати тип "Реєстрова інтеграція з
id.gov.ua" з можливістю вказати Посилання на id.gov.ua, ідентифікатор клієнта, секрет клієнта та обрати _Ключ шифрування_
з переліку заздалегідь створених ключів  _Адміністратором платформи_
* При налаштуванні Автентифікації надавачів послуг _Адміністратор реєстру_ додається необхідність обрати _Ключ шифрування_
з переліку заздалегідь створених ключів  _Адміністратором платформи_
* Для раніше налаштованих інтеграцій значення в конфігурації реєстру залишається пустим і відповідний автентифікатор
використовує _Ключ за замовчуванням_. При першому редагуванні секції, потрібно буде обрати ключ з переліку
* Якщо немає жодного ключа для вибору то _Адміністратор реєстру_ повинен бачити повідомлення про відсутність ключів і
необхідність звернутися до _Адміністратора платформи_

== Високорівневий дизайн рішення

.Діаграма варіантів використання
image::arch:architecture-workspace/platform-evolution/citizen-id-gov-ua/use-case-key-mng.drawio.svg[]

.Компоненти _Сервісу управління користувачами та ролями_
image::arch:architecture-workspace/platform-evolution/citizen-id-gov-ua/component-citizen-id-gov-ua.drawio.svg[]

=== Зміни в ідентіті провайдері IdGovUaIdentityProviderV2

=== Контракти налаштувань в Хелм чартах

== Журнал рішень
* Автентифікатори з _Підсистеми управління користувачами та ролями_ не повинні отримувати доступ до _Сервісу цифрових
підписів_ _Оперативної зони реєстру_, а продовжувати використовувати сервіс зі своєї підсистеми
* Система повинна надавати можливість керувати ключами централізовано у _Веб-інтерфейсі управління платформою та реєстрами_

== Обсяг робіт

* Додати опис для секції _Керування платформою/Дані про ключ_ текстом, що це _Ключ за замовчуванням_
_Сервісу цифрових підписів_ _Підсистеми управління користувачами та ролями_ _Веб-інтерфейсу управління платформою
та реєстрами_
* Додати опис для секції _Керування платформою/Дані про ключ_ текстом, що це _Ключ за замовчуванням_
_Сервісу цифрових підписів_ _Підсистеми управління користувачами та ролями_ _Веб-інтерфейсу управління платформою
та реєстрами_

=== Попередня декомпозиція

* Як _Адміністратор Платформи_ я хочу мати можливість керувати ключами через _Веб-інтерфейсу управління платформою
та реєстрами_
** [FE] Додати можливість додавати файловий ключ в систему
** [FE] Додати можливість додавати апаратний ключ в систему
** [FE] Додати сторінку з переглядом ключів, які були внесені в систему
** [FE] Додати можливість видаляти ключ, який був внесений в систему
** [BE] Додати можливість вказувати додаткові ключі в _Сервісі цифрових підписів_
** [BE] Додати можливість передавати псевдоним ключа в _Сервіс цифрових підписів_ при виклику методів
** [DEVOPS] Зберігати ключ, який був доданий у систему у _Сервіс управління секретами та шифруванням_
** [DEVOPS] Видаляти ключ, який був видалений з систему з _Сервісу управління секретами та шифруванням_
** [DEVOPS] Зберігати ключ, який був доданий у систему як додатковий ключ у _Сервіс цифрових підписів_ _Підсистеми
управління користувачами та ролями_
** [DEVOPS] Видаляти ключ, який був видалений з системи як додатковий ключ у _Сервісі цифрових підписів_ _Підсистеми
управління користувачами та ролями_

* Як _Адміністратор реєстру_ я хочу мати можливість налаштовувати інтеграцію з id.gov.ua для отримувачів послуг на рівні
реєстру через _Веб-інтерфейсу управління платформою та реєстрами_
** [FE] Розширити секцію _"Автентифікація отримувачів послуг"_ можливістю обрати тип автентифікації "Реєстрова інтеграція
з id.gov.ua" (включно з вибором ключа шифрування з переліку)
** [DEVOPS] Додати налаштування реалму _Сервісу управління користувачами та ролями_ при реєстровій інтеграції з id gov ua
(identity provider, authenticator, auth flow тощо)
** [BE] Передавати псевдоним ключа при виклику методів _Сервісу цифрових підписів_ з налаштувань в IdGovUaIdentityProviderV2
** [BE] Помітити реалізацію IdGovUaIdentityProvider як deprecated
** [FE/BE] Формувати посилання на кнопку "Вхід з id.gov.ua" на ідентіті провайдер який відповідає за реєстрову інтеграцію
з id.gov.ua при відповідному налаштуванні
** [BE] Додаткові потенційні зміни в автентифікаторах та ідентіті провайдері, які відповідають за реєстрову інтеграцію
(перевірити чи потрібні зміни, для того щоб не додавати нову реалізацію)

* Як _Адміністратор реєстру_ я хочу мати можливість обирати _Ключ шифрування_ при налаштуванні інтеграції з id.gov.ua
для надавачів послуг через _Веб-інтерфейсу управління платформою та реєстрами_
** [FE] Розширити секцію _"Автентифікація надавачів послуг"_ для типу автентифікації _id.gov.ua_ можливістю обрати ключ
шифрування з переліку
** [DEVOPS] Передавати налаштування по псевдониму ключа в ідентіті провайдер по інтеграції з id.gov.ua для надавачів послуг
** [BE] Передавати псевдоним ключа при виклику методів _Сервісу цифрових підписів_ з налаштувань в IdGovUaOfficerIdentityProvider

NOTE: Всі налаштування зроблені в попередніх версіях повинні працювати і використовувати ключ за замовчуванням для шифрування

=== Поза скоупом
* Авторизація використання конкретного ключа при виклику методів _Сервісу цифрових підписів_
* Вказання типу додаткового ключа (шифрування/підпису) в _Сервісі цифрових підписів_
* Обмеження _Адміністратора реєстру_ на використання певних ключів з переліку (всі ключі відкриті для використання всім
_Адміністраторам реєстру_)
* Налаштування _Платформеної інтеграція з id.gov.ua_ через _Веб-інтерфейс управління платформою та реєстрами_ (включно
з можливістю вибору _Ключа шифрування_ іншого від _Ключа за замовчуванням_)
* Можливість вибору _Ключа підпису_ для реєстру з переліку заздалегідь створених ключів  _Адміністратором платформи_
* Автоматичний редірект на сторіну id gov ua з _Кабінета отримувача послуг_  і подальший вибір режиму роботи (фізична особа/
юридична особа)

== Обмеження рішення
* Список сертифікатів та дозволених ключів налаштовуються для _Сервісу цифрових підписів_ взагалі, а не для кожного ключа