= Можливість налаштовувати сервіс id.gov.ua як спосіб автентифікації для отримувачів послуг на рівні реєстру

== Загальний опис
При веденні декількох реєстрів на одному екземплярі платформи може виникати потреба в інтеграції з сервісом id.gov.ua
для отримувачів послуг на рівні окремого реєстру. При цьому ключ шифрування, який є обов'язковим для використання
сервісу id.gov.ua, повинен бути різним для кожного реєстру. Управління цими ключами повинно відбуватися через
_Веб-інтерфейс управління платформою та реєстрами_.

NOTE: Детальніше з архітектурою інтеграції з id.gov.ua можна ознайомитися
https://id.gov.ua/downloads/IDInfoProcessingD.pdf[за посиланням]

== Концепти
* _Ключ шифрування_ - ключ який використовується для інтеграції з сервісом id.gov.ua.
* _Ключ підпису_ - ключ який використовується для накладання цифрового підпису системи (електронна печатка)

== Функціональні сценарії
* Налаштування інтеграції з id.gov.ua на рівні окремого реєстру для _Кабінету отримувача послуг_ _Адміністратором реєстру_
* Налаштування інтеграції з id.gov.ua на рівні окремого реєстру для _Кабінету надавача послуг_ _Адміністратором реєстру_
* Управління ключами _Адміністратором платформи_
* Вибір _Ключа шифрування_ для інтеграції з id.gov.ua на рівні окремого реєстру для _Кабінету отримувача послуг_
_Адміністратором реєстру_ зі списку попередньо зареєстрованих ключів
* Вибір _Ключа шифрування_ для інтеграції з id.gov.ua на рівні окремого реєстру для _Кабінету надавача послуг_
_Адміністратором реєстру_ зі списку попередньо зареєстрованих ключів
* Вибір _Ключа підпису_ для реєстру _Адміністратором реєстру_ зі списку попередньо зареєстрованих ключів

== Ролі користувачів
* Адміністратор платформи
* Адміністратор реєстру

== Загальні принципи та положення

* Доступ до всіх операцій з ключем забезпечується _Сервісом цифрових підписів_
* _Сервіс цифрових підписів_ ініціюється з ключем за замовчуванням в контексті (поточна реалізація)
* У _Сервіс цифрових підписів_ можуть бути додані додаткові ключі з вказанням псевдоніму (alias)
* При виклику методів _Сервісу цифрових підписів_ можна вказати псевдонім ключа, який буде використовуватися для тієї чи
іншою операції
* Якщо псевдонім ключа не вказано, то використовується ключ за замовчуванням
* Вказати псевдонім ключа необхідно тільки для операцій, в яких результат операції залежить від контексту ключа
(наприклад, методи _/officer/verify_, _/citizen/verify_, _/owner_ не залежать від контексту ключа і результат буде
однаковий для будь-якого ключа)

== Високорівневий дизайн рішення


== Журнал рішень

== Обсяг робіт

=== Попередня декомпозиція

=== Поза скоупом
* Авторизація використання конкретного ключа при виклику методів _Сервісу цифрових підписів_

== Обмеження рішення
* Список сертифікатів та дозволених ключів налаштовуються для _Сервісу цифрових підписів_ взагалі, а не для кожного ключа