= Перегляд переліку таблиць моделі даних реєстру у режимі читання для версії-кандидату

== Загальний опис
Розробка регламенту реєстру включає в себе розробку моделі даних реєстру. Адміністративний портал надає функціонал по перегляду переліку таблиць моделі даних реєстру та їх структури.

== Опис проблеми
Адмін портал дозволяє перегляд переліку таблиць моделі даних тільки для мастер версії регламенту реєстру. Цей функціонал дозволяє отримати перелік таблиць регламенту, що розгорнутий на прод оточенні, але не дозволяє перегляд таблиць регламенту реєстру моделі даних версії-кандидату.

- Під час розробки моделі даних регламенту реєстру необхідно оперувати переліком таблиць моделі даних, що описані в liquibase конфігурації версії-кандидату.

- Під час редагування моделі даних розробниками реєстру шляхом внесення змін в gerrit, необхідно відображати актуальну інформацію зі списком таблиць моделі даних в адміністративному порталі.

- Невизначений стан змін в моделі даних до моменту публікації регламенту реєстру

== Актори
- Адміністратор регламенту реєстру
- Розробник регламенту реєстру

== Голосарій
- rrm - registry-regulation-management backend service
- DataModelSnapshot - файл для зберігання стану моделі даних регламенту реєстру
- DataModelSnapshot files - набір файлів (файл per table), що відображають стан моделі даних регламенту реєстру по кожній із таблиць

== Функціональні сценарії
- Перегляд поточного стану моделі даних регламенту реєстру (перелік таблиць), що розробляється (в рамках версії-кандидату)
- Перегляд значення атрибуту "суб'єктність" в переліку таблицьї
- Отримання результату перевірки можливості успішного розгортання моделі даних

== Дизайн інснуючого рішення

image::architecture-workspace/platform-evolution/data-model-version-candidates/current-design.svg[]

- Розгортання схеми БД відбувається в 2 етапи:
** OKD run-db-scripts job, що запускається під час розгортання Citus. Розгортає preconditions для розгортання моделі даних регламенту реєстру (actual detailed behaviour out of scope)
** Jenkins pipeline розгортання регламенту реєстру, а саме <registry-name>-data-model job. Розгортає модель регламенту реєстру.

- registry-regulations-management зчитує та зберігає структуру БД в файли `DataModelSnapshot table file`. Кожна таблиця має свій окремий файл DataModelSnapshot. Дія відбувається під час запуску registry-regulations-management сервісу один раз
- Rest API через сервіси доступу до DataModelSnapshot зчитують перелік таблиць шляхом зчитування переліку файлів `DataModelSnapshot table file`.

== Загальні принципи
- Внесення змін в модель даних регламенту реєстру відбувається шляхом внесення змін у відповідні liquibase файли
- Структура liquibase файлів регламенту реєстру на файловій системі не змінюється
- Кожна версія-кандидат використовує свою виділену схему БД для розгортування моделі даних
- Використання еталонної схеми БД для створення тимчасових схем БД для версій-кандидатів регламенту реєстру. Дана схема не містить даних реєстру
- Підсистема розгортання регламенту реєстру (регламентний jenkins) створює структуру схеми БД шляхом розгортання liquibase конфігурацій регламенту реєстру
- registry-regulation-management зчитує стан розгортання регламенту реєстру (розгортання liquibase) з gerrit відповідного MR. Стан виконання відповідної jenkins job відображається в Gerrit MR по версії-кандидату за допомогою specific label (Verified +1).


== Технічний дизайн рішення

image::architecture-workspace/platform-evolution/data-model-version-candidates/target-design.svg[]

- OKD run-db-script job створю еталонну схему БД під час створення та розгортання схеми БД згідно з налаштування в citus repository. Еталонна схема не повинна містити тільки структуру БД без будь-яких даних відповідного реєстру.
- Підсистема розгортання регламенту реєстру проводить розгортання регламенту реєстру для версій кандидатів після внесення будь-яких змін в відповідний Gerrit MR.
- Підсистема розгортання регламенту реєстру створює тимчасові БД для кожної з версій-кандидатів, що знаходяться в роботі.
- Підсистема розгортання регламенту реєстру створює тимчасову БД для мастер версії, що необхідно для отримання DataModelSnapshot для мастер версії до фактичного розгортання регламенту реєстру після інтеграції версії-кандидату
- Підсистема розгортання регламенту реєстру розгортає модель даних регламенту реєстру шляхом використання liquibase конфігурацій з регламенту реєстру
- rrm зчитує структуру даних з тимчасової БД в `DataModelSnapshot files`

[CAUTION]
Еталонна та тимчасова схеми БД повинні бути створені тільки на DEV оточенні

=== Діаграми послідовності

.Отримання переліку таблиць версії-кандидату
[plantuml, data-model-version-candidates data-model-version-candidate-sequence, svg]
----
include::partial$architecture-workspace/platform-evolution/data-model-version-candidates/data-model-version-candidate-create-sequence.puml[]
----

=== Розширення підсистеми розгортання регламенту реєстру:

Необхідно розширити регламентний jenkins новим механізмом розгортання:

- При створенні нового MR для версії-кандидату - створити тимчасову БД для відповідной версії та розгорнути схему БД для неї
- При збереженні змін версії-кандидату (новий patchset в gerrit) - перестворити тимчасову схему БД для відповідної версії-кандидату і розгорнути liquibase changelog з мастер-версії і потім з версії-кандидату

[NOTE]
За вищенаведені дії відповідає єдиний jenkins codereview pipeline

==== Опис роботи з тимчасовими схемами БД

Лоігка роботи:

- Створити тимчасову схему БД для версії кандидату використовуючи еталонну схему БД.

[source,sql]
----
CREATE DATABASE [registry-dev-<vcid>] WITH TEMPLATE registry-template OWNER [our owner user?];
----

[NOTE]
`registry-template` - ім'я еталонної БД, отриманої після роботи OKD run-db-script-job. `registry-dev-<vcid>` - шаблон імені тимчасової БД для версії-кандидату (registry-dev-master для тимчасової БД мастер версії).

- Розгортання liquibase структури з відповідної версії регламенту реєстру (стан майстер версії, з якої було створено версію-кандидат, або на яку останній раз відбувалась rebase операція)
- Розгортання поточної liquibase структури з версії-кандидату

Для доступу registry-regulation-management до схем БД необхідно створити окремого користувача registry_dev_role. Користувач повинен мати права:

- CREATE/DROP тимчасових схем БД
- READ еталонної БД
- ALTER * onto registry-dev* databases

==== Періодичний reconciliation процес
Reconciliation процес необхідний для видалення застарілих схем БД по версіям-кандидатам (версії кандидати що були інтегровані в мастер версію або ті, що були видалені без інтеграції). Необхідно створити окремий jenkins pipeline для reconciliation процесу.

==== Логіка роботи reconciliation процесу

- Отримати перелік версій-кандидатів в gerrit
- Отримати перелік тимчасових БД для версій-кандидатів в БД
- Створити недостаючі схеми в БД для версій-кандидатів
- Видалити тимчасові схеми БД версій-кандидатів для яких не існує відкритих MR в gerrit

==== Schedule налаштування

- Виклик процесу reconciliation кожні N годин (раз на добу?)

=== Використання AbstractRoutingDatasource для доступу до тимчасових БД

==== Опис проблеми

Для доступу до тимчасових БД необхідно використовувати `DataSource` bean для кожної тимчасової БД. Існуючий код, що забезпечує роботу з БД мастер версії, використовує Spring bean типу DataSource.
Для перевикористання механізму зчитування структури БД в DataModelSnapshot file пропонується використати https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/datasource/lookup/AbstractRoutingDataSource.html[`AbstractRoutingDatasource`] механізм, що дозволяє створювати DataSource динамічно, в залежності від версії-кандидату, з якою наразі ведеться робота.

=== RestAPI
Поточний RestAPI розширюється можливістю отримувати перелік таблиць моделі даних регламенту реєстру.
Логіка роботи та структура запитів повторює роботу xref:registry-regulation-management:rest-api/rest-api-generated/index.adoc#_get_versionsmastertablestablename[відповідних запитів для мастер версії]
для мастер версії регламенту реєстру

==== Приклад запитів та відповідей на отримання переліку таблиць моделі даних версії-кандидату

Запит:

[source,http,options="nowrap"]
----
GET /versions/candidates/{versionCandidateId}/tables/
----

Структура відповіді:

[source,http,options="nowrap"]
----
[
    {"name":"Table 1","description":"Table 1 description","objectReference":true},
    {"name":"Table 2","description":"Table 2 description","objectReference":true},
    ...
    {"name":"Table n","description":"Table 2 description","objectReference":true},
]
----

[CAUTION]
Необхідно використати ті ж самі структури даних та коди помилок для запитів та відповідей, що використовуються для отримання переліку таблиць моделі даних в мастер версії

== Розширення блоку відображення стану версії-кандидату інформацією про стан процесу розгортання тимчасових схем БД

Під час розгортання тимчасових БД проводиться також перевірка працездатності існуючої конфігурації liquibase changelog регламенту реєстру. При виниканні будь-яких проблем під час цього процесу необхідно передати цю інформацію в клієнтський додаток для відображення її розробнику реєстру.

Необхідно розширити `VersionInfoDetailed` інформацією про стан розгортання регламенту реєстру на тимчасове оточення шляхом додавання нового типу валідації в `Validation` bean.

Змінити `ResultValues` на:

- UNKNOWN: процес розгортання не відбувся/не відбувався
- SUCCESS: процес розгортання успішний
- FAILED:  процес розгортання не успішний

Додати в resultDetails інформацію (link) на відповідний gerrit MR.

[NOTE]
TODO: пропрацювати UI дизайн

== Розширення env cleanup процесу
Необхідно розширити існуючий механізм cleanup оточення шляхом додавання змін в `delete-registry` stage.
Необхідно видалити всі тимчасові схеми БД для мастер версії та версій-кандидатів. Зміни передбачають внесення відповідних інструкцій по видаленню схем БД в `CleanupRegistry.sql` або створення окремого відповідного sql файлу з інструкціями. Видалення можливе по масці імені БД `registry-dev-*`. Також необхідно видалити еталонну БД з іменем `registry-template`.

== Високорівневий план розробки
=== Необхідні експертизи
- DevOps
- BE
- FE
- QA/AQA

=== DevOps

- Створити користувача в БД для registry-regulation-management сервісу. Permissions:
** READ тимчасові БД

- Розширити механізм розгортування БД в citus repository для створення еталонної БД
- Розширити механізм cleanup env видаленням тимчасових БД та еталонної БД
- Розширити підсистему розгортання регламенту реєстру механізмом розгортування liquibase конфігурацій регламенту реєстру в тимчасові схеми БД
- Додати reconciliation and cleanup механізм між переліком версій кандидатів та тимчасовими БД

=== Backend
- Створити механізм зчитування схеми БД по заданому DataSource
- Забезпечити створення DataSource spring bean для кожної версії-кандидату та майстер версії окремо.
- Розширити RestAPI для опрацювання запитів по моделі даних для версій-кандидатів

=== Frontend
- Додати відображення стану розгортання тимчасової БД в блок з результатами перевірки версії-кандидату
- Створити сторінку з переліком таблиць для версій-кандидатів
