== Низькорівневий дизайн рішення

=== Сервіс відправки повідомлень користувачів

image::lowcode/notifications/notifications-service.svg[]

За реалізацію вимог по формуванню та відправці повідомлень користувачам відповідає окремий компонент "_Сервіс відправки повідомлень користувачам_".

Інтерфейсом для зовнішньої взаємодії з сервісом виступає окремий _Kafka_-топік "_user-notifications_", а основою рішення є реагування та обробка подій-запитів на генерацію повідомлень з використанням _FreeMarker_-шаблонів, попередньо завантажених у сховище та їх послідуюча відправка згідно налаштувань користувача.

[NOTE]
У разі, якщо подію-запит на відправку повідомлення через "_user-notifications_" топік не вдалося обробити, система проводить N спроб згідно поточної конфігурації і за відсутності результату перенаправляє повідомлення в окремий службовий топік "_user-notifications.DLT_".

.Приклад налаштувань сервісу для отримання повідомлень через Kafka-топік (на прикладі використання *ddm-starter-kafka* бібліотеки)
[source, yaml]
----
data-platform:
   kafka:
     consumer:
       group-id: <consumer-group>
       key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
       value-deserializer: org.springframework.kafka.support.serialize.ErrorHandlingDeserializer
       custom-config:
         "[allow.auto.create.topics]": false
         "[retry.backoff.ms]": 10000
     topics:
       "<topic-name>": "<topic-name>"
     error-handler:
       initial-interval: 1500
       max-elapsed-time: 6000
       multiplier: 2
----

TIP: Існує необхідність реалізації автоматичного створення Kafka-топіків "_<topic-name>.DLT_" в рамках *ddm-starter-kafka* бібліотеки (_StartupKafkaTopicsCreator_) для коректного відпрацювання _DeadLetterPublishingRecoverer_ стратегії при неможливості обробки повідомлення.

==== Загальний сценарій обробки повідомлень

.Загальний сценарій обробки повідомлень kafka-топіком user-notifications
[plantuml, notification-to-channels-flow.puml, svg]
----
include::partial$lowcode/notifications/general/notification-to-channels-flow.puml[]
----

==== Обробка запиту на відправлення поштового повідомлення

.Обробка запитів на відправку поштових повідомлень користувачам
[plantuml, email-notification-flow, svg]
----
include::partial$lowcode/notifications/email/email-notification-flow.puml[]
----

==== Обробка запиту на відправлення push-нотифікації в Дію

TIP: З детальною інформацією щодо взаємодії з сервісом нотифікація Дії можна ознайомитись у розділі xref:lowcode/notifications/diia-notifications-api.adoc[API відправки push-нотифікацій у мобільний додаток "Дія"].

.Обробка запитів на відправку push-нотифікацій користувачам у мобільний додаток Дія
[plantuml, diia-notification-flow, svg]
----
include::partial$lowcode/notifications/diia/diia-notification-flow.puml[]
----


==== Обробка запиту на відправлення in-app повідомлень у inbox користувача Кабінету Громадянина

[plantuml, inbox-notification-save-flow, svg]
----
include::partial$lowcode/notifications/inbox/inbox-notification-save-flow.puml[]
----

==== Діаграма послідовності взаємодії компонентів системи для отримання користувачем inbox повідомлень

[plantuml, inbox-notification-read-flow, svg]
----
include::partial$lowcode/notifications/inbox/inbox-notification-read-flow.puml[]
----
