== Функціональні можливості

Для забезпечення вимог по роботі з повідомленнями, платформа реалізує наступні сценарії:

- Налаштування каналів зв'язку для відправлення повідомлень на рівні реєстру
- Налаштування шаблонів формування повідомлень для каналу зв'язку
- Налаштування кроків відправлення повідомлень на рівні бізнес-процесу
- Налаштування преференцій за каналами зв'язку на рівні профілю користувача для отримання повідомлень
- Відправлення повідомлень користувачам з підтримкою шаблонізації

== Ролі користувачів

- _Адміністратор платформи_ - створення та послідуюче налаштування реєстрів _Адміністративний інтерфейс управління платформою_ (_канали зв'язків, тощо._)
- _Адміністратор реєстру_ - налаштування реєстру через _Адміністративний інтерфейс управління платформою_ (_канали зв'язків, тощо._)
- _Адміністратор регламенту_ - створення шаблонів повідомлень, моделювання бізнес-процесів з використанням елементів відправки повідомлень користувачам
- _Користувач кабінету громадянина_ - отримання повідомлень про стан чи результат виконання бізнес-процесу згідно налаштувань каналів зв'язку

== Базові принципи

* Відправка повідомлень системою можлива лише зареєстрованим користувачам
* Кожен користувач має обрати активний канал зв'язку та внести контактні дані при проходженні реєстрації
* Відправка повідомлень користувачам є значущою подією, яка підлягаю фіксації в журналі аудиту системи
* Платформа надає можливість перевикористання шаблонів повідомлень між бізнес-процесами
* Платформа надає можливість налаштування шаблонів повідомлень окремо для кожного з каналів зв'язку
* Платформа надає спеціалізовані елементи у каталозі типових розширень для спрощення моделювання бізнес-процесів з відправкою повідомлень
* Платформа розповсюджується з налаштованими сервісами для обслуговування каналів зв'язку реєстру у якості опцій за замовчуванням
* Платформа підтримує можливість налаштування декількох каналів зв'язку для реєстру
** *email* - _Підтримується_
** *diia* - _Наразі не підтримується_
** *messenger* - _Наразі не підтримується_
* Відправка повідомлень не має блокувати потік виконання бізнес-процесу та виконуватись асинхронно
* Для реалізації інтерфейсу асинхронної взаємодії з підсистемою відправки повідомлень обрано підхід з використанням _Kafka_ у якості брокера повідомлень, яка забезпечує гарантії доставки та _Exactly-Once_ семантику обробки повідомлень

