== Kafka-топіки опрацювання подій відправки повідомлень користувачам

=== "_user-notifications_"

Цільовий топік, який використовується для публікації/обробки подій-запитів на відправку повідомлень користувачам.

|===
|Властивість|Значення|Опис

|*num-partitions*
|_1_
|Кількість розділів в рамках топіку для збереження повідомлень

|*replication-factor*
|_1_
|Кількість реплік цільового топіка

|*retention-policy-in-days*
|_7_
|Кількість днів збереження повідомлення в Kafka
|===

=== "_user-notifications.DLT_"

Службовий топік, який використовується для публікації та тимчасового збереження подій-запитів на відправку повідомлень користувачам, які не вдалося обробити з ціллю їх подальшого повторного опрацювання.

|===
|Властивість|Значення|Опис

|*num-partitions*
|_1_
|Кількість розділів в рамках топіку для збереження повідомлень

|*replication-factor*
|_1_
|Кількість реплік цільового топіка

|*retention-policy-in-days*
|_7_
|Кількість днів збереження повідомлення в Kafka
|===

[NOTE]
Перегляд та моніторинг подій, які не вдалося опрацювати, можливий через окремий адміністративний інтерфейс *kafka-ui*.

TIP: У разі необхідності відправлення подій адміністратором на повторне опрацювання, розглядається опція побудови окремого службового процесу на базі _Kafka Connect_, який буде переносити події з _user-notifications.DLT_ у цільовий топік _user-notifications_.

=== Канонічний вигляд структури повідомлення
[source, json]
----
{
  "context": {
    "system": "Low-code Platform",
    "application": "<bpms.app.name>",
    "businessProcess": "",
    "businessProcessDefinitionId": "",
    "businessProcessInstanceId": "",
    "businessActivity": "",
    "businessActivityInstanceId": ""
  },
  "notification": {
    "recipient": "",
    "subject": "",
    "template:": "",
    "templateModel:": {
      "key1": "val1",
      "key2": "val2",
      "key3": "val3"
    }
  }
}
----