== Фіксація подій відправки повідомлень користувачам у журналі аудиту системи

Усі події відправки повідомлень користувачам системою фіксуються у журналі аудиту з повним контекстом.

[NOTE]
Детальніше з дизайном підсистеми "_Журнал аудиту_" можна ознайомитися
xref:datafactory/audit.adoc[за посиланням]

=== Структура події аудиту

Нижче наведено xref:datafactory/audit.adoc#_події[структуру події аудиту] та її відповідність структурі та значенням отриманого через Kafka-топік повідомлення про необхідність відправки нотифікації користувачу.

TIP: З детальним описом структури Kafka-повідомлення відправки нотифікації можна ознайомитись xref:lowcode/notifications/user-notifications-kafka-topics.adoc#_канонічний_вигляд_структури_повідомлення[за посиланням].

|===
|Атрибут|Значення

|*timestamp*
|_now()_

|*application_name*
|"_notification-service_"

|*name*
|"_SEND_NOTIFICATION_"

|*type*
|"_SYSTEM_EVENT_"

|*request_id*
|_<MDC.traceId>_

|*source_system*
|_<context.system>_

|*source_application*
|_<context.application>_

|*source_business_process*
|_<context.businessProcess>_

|*source_business_process_definition_id*
|_<context.businessProcessDefinitionId>_

|*source_business_process_instance_id*
|_<context.businessProcessInstanceId>_

|*source_business_activity*
|_<context.businessActivity>_

|*source_business_activity_id*
|_<context.businessActivityInstanceId>_

|*context*
|_<JSON-представлення деталей події>_

|===

.JSON-представлення деталей події для фіксації
[source, json]
----
{
  "notification": {
    "recipient": "<Username користувача, якому було відправлено повідомлення>",
    "subject": "<Заголовок повідомлення>",
    "channel:": "[email|diia|messenger] - Канал зв'язку, який було використано для відправки повідомлення користувачу згідно поточних налаштувань профілю"
  }
}
----