==== API доступу до inbox повідомлень користувача

[WARNING]
Отримання доступу до API можливе лише в рамках виконання запиту автентифікованого користувача в системі

===== Отримання переліку in-app повідомлень у Кабінеті Користувача

[NOTE]
Данний API-роут є публічним та має бути опублікованим для зовнішнього доступу через окремий _Kong Route_ для _Кабінету Громадянина_.

_GET /api/notifications/inbox_

|===
|Параметр|Тип|Частина запиту|Опис

|*X-Access-Token*
|JWT
|HTTP заголовок
|Токен доступу користувача

|*limit*
|int
|Параметр запиту
|Кількість повідомлень для одноразового отримання (для пагінації)

|*offset*
|int
|Параметр запиту
|Відступ від першого повідомлення (для пагінації)
|===

[NOTE]
Ідентифікатор користувача для фільтрації повідомлень отримується з токену доступу (поле _RECIPIENT_ID_).
Отримані записи мають бути впорядковані у зворотньому напрямку за параметром _created_at_ (created_at DESC)

.Приклад відповіді
[source, json]
----
[
  {
    "id": "id1",
    "subject": "SUBJECT",
    "message": "Some content",
    "isAcknowledged": true,
    "createdAt": "2022-07-29 11:08:16"
  },
  {
    "id": "id2",
    "subject": "SUBJECT2",
    "message": "Some different content",
    "isAcknowledged": false,
    "createdAt": "2022-07-27 16:04:17"
  }
]
----

.Коди відповіді
|===
|Код|Опис

a|[green]#200#
|OK
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації (відсутній токен доступу)
a|[red]#500#
|Серверна помилка обробки запиту
|===

===== Підтвердження перегляду in-app повідомлення у Кабінеті Користувача

[NOTE]
Данний API-роут є публічним та має бути опублікованим для зовнішнього доступу через окремий _Kong Route_ для _Кабінету Громадянина_.

_POST /api/notifications/inbox/{id}/ack_

|===
|Параметр|Тип|Частина запиту|Опис

|*X-Access-Token*
|JWT
|HTTP заголовок
|Токен доступу користувача

|*id*|Text
|Параметр запиту
|Ідентифікатор повідомлення

|===

.Коди відповіді
|===
|Код|Опис

a|[green]#200#
|OK
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації (відсутній токен доступу)
a|[yellow]#403#
|Заборонений доступ (при спробі оновити чуже повідомлення)
a|[red]#500#
|Серверна помилка обробки запиту
|===

