==== API управління шаблонами повідомлень

===== Створення або внесення змін до шаблону для каналу зв'язку за назвою

[WARNING]
Призначенням API-роута є службове використання _Пайплайном публікації регламенту_ для наповнення даними сховища шаблонів. Роут не доступний для зовнішнього доступу через _Kong_.

_PUT /api/notifications/templates/{channel}:{name}_

|===
|Параметр|Тип|Частина запиту|Опис

|*channel*
|Текстовий
|Параметр запиту
|Назва каналу [email, diia, inbox]

|*name*
|Текстовий
|Параметр запиту
|Унікальна назва шаблону в рамках каналу
|===

.Приклад тіла запиту
[source, json]
----
{
  "title": "{title}",
  "content": "{content}",
  "attributes": [
    {
      "name": "actionType",
      "value": "message"
    },
    {
      "name": "templateType",
      "value": "attention"
    },
    {
      "name": "shortText",
      "value": "{shortText}"
    }
  ]
}
----

.Приклад відповіді
[source, json]
----
{
  "name": "{template_name}",
  "channel": "{channel}",
  "title": "{title}",
  "content": "{content}",
  "checksum": "{sha256-hash}",
  "attributes": [
    {
      "name": "actionType",
      "value": "message"
    },
    {
      "name": "templateType",
      "value": "attention"
    },
    {
      "name": "shortText",
      "value": "{shortText}"
    }
  ],
  "createdAt": "{timestamp}",
  "updatedAt": "{timestamp}",
  "externalTemplateId": "{external-id}",
  "externallyPublishedAt": "{timestamp}"
}
----

.Коди помилок
|===
|Код|Опис

a|[green]#200#
|OK з поверненням результату даних зміненого шаблону
a|[green]#201#
|Created з поверненням результату даних шаблону
a|[red]#400#
|Некоректно сформований запит
a|[yellow]#401#
|Помилка автентифікації (відсутній токен доступу)
a|[red]#500#
|Серверна помилка обробки запиту
|===
