== Низькорівневий дизайн рішення

На даній діаграмі зображено залучені для реалізації вимог сервіси платформи та взаємодію між ними.

image::lowcode/notifications/notifications-design.svg[notifications-design,700]

include::user-notifications-system-components.adoc[]

include::user-notifications-system-network-policies.adoc[]

=== Сервіс виконання бізнес-процесів

image::lowcode/notifications/notifications-starter.svg[]

В основу рішення покладено використання Camunda-концепції _Java Delegate_ для виконання операцій по відправці повідомлень з бізнес-процесу. Спрощення досвіду моделювання реалізовано за допомогою окремих  xref:lowcode/notifications/user-notifications-modelling.adoc#_моделювання_бізнес_процесів_з_відправкою_повідомлень_користувачам[типових розширень].

Задля запобігання блокування основного потоку виконання бізнес-процесу використовується принцип розділення публікації події про необхідність виконання операції від фактичного її виконання з використанням _publish-subscribe_ підходу, реалізованому за допомогою _Kafka_. З повним переліком, налаштуваннями та структурами об'єктів подій можна ознайомитись xref:lowcode/notifications/user-notifications-kafka-topics.adoc[за посиланням].

=== Сервіс відправки повідомлень користувачів

image::lowcode/notifications/notifications-service.svg[]

За реалізацію вимог по формуванню та відправці повідомлень користувачам відповідає окремий компонент "_Сервіс відправки повідомлень користувачам_".

Інтерфейсом для зовнішньої взаємодії з сервісом виступає окремий _Kafka_-топік "_user-notifications_", а основою рішення є реагування та обробка подій-запитів на генерацію повідомлень з використанням _FreeMarker_-шаблонів, попередньо завантажених у сховище та їх послідуюча відправка згідно налаштувань користувача.

=== Взаємодія значущих компонентів системи

На даній діаграмі послідовності зображено взаємодію компонентів системи в рамках реалізації сценарію відправлення повідомлень користувачам кабінетів з бізнес-процесу. Додатково відображено структури даних та деталі реалізації окремих компонентів системи.

[plantuml, bp-notification-flow, svg]
----
include::partial$lowcode/notifications/bp-notification-flow.puml[]
----
