= Managing external integrations
include::platform:ROOT:partial$templates/document-attributes/default-set-en.adoc[]

include::platform:ROOT:partial$admonitions/language-en.adoc[]

== General description

Management of external integrations plays a critical role in ensuring information exchange between different systems and data sources.

*_REST_* (*_Representational State Transfer_*) and *_SOAP_* (*_Simple Object Access Protocol_*) are the primary protocols for interacting with other registries and systems to transmit data.

Based on the HTTP protocol, *_REST_* allows interaction with other registries on the Platform and external systems by sending requests and receiving responses in JSON format. +
On the other hand, *_SOAP_* uses an XML schema to interact with other systems, invocating methods and passing parameters using a specific set of rules.

Fundamental principles of integration with other registries on the Platform and external systems: ::

. The registry regulations do not contain environment-specific settings to ensure configuration consistency across all instances.
. The registry regulations do not contain any confidential data in any form to prevent unauthorized use.
. Configuration settings for external integrations are not duplicated and are centrally used to ensure consistency.
. Adding external systems for integration with the registry does not require manual configuration of network policies to facilitate fast and secure integration.
. Secrets with access parameters to external systems are stored in a secure vault service called *HashiCorp Vault* to prevent unauthorized access to this data.
. The registry administrator configures integrations with other systems at the registry instance level in the *Control Plane* administrative panel, including integration protocol, address, authentication protocol, secrets, etc.
. The registry administrator is responsible for secret rotation and access parameter management for external systems.
. The administrator provides minimal pre-configuration at the registry regulation level for external integrations in business processes.
. Cross-registry SOAP integration uses standard extension connectors in the registry and does not require additional configuration at the regulation level. Such integration is performed via the Ukrainian https://trembita.gov.ua/["Trembita" Secure exchange gateway].
+
include::ROOT:partial$admonitions/ua-specific.adoc[]

. The SOAP integration is also possible through the universal SOAP connector that extends Platform capabilities. See xref:#soap-integration[] for more details.

. Integration with third-party systems requires additional configuration at the registry regulation level, including defining a list of operations and their types used by the registry through the standard *REST* integration extension—*Connect to external system* or simply *REST connector*.
+
[IMPORTANT]
====

For Platform versions 1.9.3 and above, major configurations are performed at the registry instance level in the *Control Plane* console.

For versions 1.9.2 and below, all configurations are performed at the registry regulations level.
====

[NOTE]
====
Interaction settings with external systems are only possible during registry editing.

By default, when deploying the registry, three unconfigured endpoints are created for the "Trembita" SOAP services and one for the external system "Diia".

TIP: "Trembita" and "Diia" services are specific to the Ukrainian implementation and may not apply or function as described in other contexts or regions. Please consult the local guidelines or documentation if you are implementing this outside Ukraine.
====

== Integration types

The Platform allows for flexible integration with other registries and systems and supports the following interaction: ::

*SOAP API* ::
_Interaction through the API using SOAP integration connectors_ is the primary type of integration interaction. An instance of the API is installed at the Platform level. Each external system of this kind must have an instance of the API installed on its side and be a registered participant in the unified, secure space where SOAP is the primary protocol for integration.

*REST API* ::
_Interaction with other registries on the Platform and external systems beyond its boundaries through REST interfaces_ is an additional universal connection that extends the integration capabilities.

[#soap-integration]
=== Data exchange via SOAP

The Platform allows modeling data exchange with other registries and their services in the regulation's business processes using SOAP integration connectors.

Data exchange between such systems occurs via the SOAP (Simple Object Access Protocol) in XML format.

TIP: For more details see xref:bp-modeling/external-integration/api-call/connectors-external-registry.adoc[].

[#exchange-data-ext-system]
=== Data exchange via REST

The REST integration of registries with other registries on the Platform and external systems allows data transfer from one registry to another or between external systems using REST requests.

*REST (Representational State Transfer)* is a software architecture style for creating web services. In the REST architecture, there is a set of constraints that ensure the interaction between the client and the server. REST utilizes the *HTTP* protocol for data transmission.

Such interaction utilizes the *REST API* and *HTTP* requests to obtain information. The interface can access the registry's functionality and allow reading and modifying data. Data is transmitted in the *JSON* format. Data can be transferred in both directions—from the external system to the registry or from the registry to the external system.

To set up the interaction with other systems using REST, you need to: ::
+
. Configure the interaction with registries in the *Control Plane* administrative panel.
+
TIP: For more information, see
xref:registry-admin/external-integration/cp-integrate-ext-system.adoc[].
+

. Perform minimal configuration at the registry regulations level.
+
TIP: For more information, see
xref:registry-develop:bp-modeling/bp/rest-connector.adoc#regulations-configuration[REST connector: Registry regulations' settings].

. Model data exchange with other systems in business processes using the *Connect to external system* REST integration connector.
+
TIP: For more information, see
xref:registry-develop:bp-modeling/bp/rest-connector.adoc#bp-modeling[REST connector: Business process modeling].

NOTE: For detailed information on REST integration, see
xref:registry-admin/external-integration/rest-api-no-trembita.adoc[].

== Related pages

* xref:bp-modeling/external-integration/api-call/connectors-external-registry.adoc[]
* xref:registry-admin/external-integration/cp-integrate-ext-system.adoc[]
* xref:registry-develop:bp-modeling/bp/rest-connector.adoc[REST connector]
* xref:registry-admin/external-integration/rest-api-no-trembita.adoc[]

