= Підсистема управління Платформою та Реєстрами

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Підсистема управління Платформою та Реєстрами забезпечує спрощене керування центральними компонентами Платформи, реєстрами та
ресурсами OpenShift. Дозволяє створювати та конфігурувати реєстри, а також, агрегує в собі посилання на всі наявні в Платформі WEB API та являє собою єдину точку
старту роботи з Платформою реєстрів.

Загалом, підсистема складається з компонентів, що надають користувачам та адміністраторам Платформи зручні інтерфейси, які
доступні з браузера, спрощують промислову експлуатацію Платформи реєстрів.

== Функції підсистеми

* Розгортання реєстрів
* Перегляд, керування та конфігурування ресурсів Платформи та Реєстрів
* Керування Адміністраторами та користувачами
* Налаштування IP-фільтрів доступу до сервісів Платформи та Реєстрів
* Керування зовнішніми інтеграціями
* Масштабування Платформи та Реєстрів
* Налаштування резервного копіювання Платформи та Реєстрів
* Відновлення Платформи та Реєстрів
* Перегляд та управління логуванням, метриками та важливою інформацією про стан кластера
* Оновлення кластера
* Оновлення Платформи та реєстрів

== Технічний дизайн підсистеми

Підсистема складається з адміністративних інтерфейсів користувачів для взаємодії з Платформою, реєстрами та платформою
оркестрації контейнерів на рівні технічного адміністратора.

Кожен з компонентів підсистеми та зʼвязки з іншими підсистемами зображені на наступній діаграмі:

.Діаграма компонентів підсистеми
image::architecture/platform/administrative/control-plane/control-plane.svg[width=600,float="center",align="center"]

== Складові підсистеми

|===
|Назва компоненти|Namespace|Deployment|Походження|Призначення

|_Веб-інтерфейс управління кластером OpenShift_
|`openshift-console`
|`console`
|3rd-party
|Вебконсоль OpenShift Container Platform — це інтерфейс користувача, доступний із веббраузера. Адміністратори Платформи
можуть використовувати OpenShift вебконсоль для візуалізації, перегляду та керування вмістом або ресурсами OpenShift
кластера, Платформи та реєстрів.

|_Веб-інтерфейс інтерфейс управління Платформою та реєстрами_
|`control-plane`
|`control-plane-console`
|origin
|Єдиний вебінтерфейс для керування Платформою реєстрів та реєстрами. Дозволяє додавати адміністраторів, налаштовувати
доступи, DNS, оновлювати реєстри тощо.

|_Адмін-консоль оператор_
|`control-plane`
|`admin-console-operator`
|epam-origin
|Допоміжне програмне забезпечення, яке виконує функції розгортання, налаштування та відновлення адмін-консолі, як
компонента підсистеми.

|_OpenShift-консоль оператор_
|`openshift-console-operator`
|`console-operator`
|3rd-party
|Допоміжне програмне забезпечення, яке виконує функції розгортання, налаштування та відновлення openshift-консолі, як
компонента підсистеми.

|===

== Атрибути якості підсистеми

=== _Portability_
Контейнери з компонентами підсистеми можуть бути розгорнуті або перенесені на різні хмарні середовища або на власну
локальну інфраструктуру.

=== _Scalability_
Підсистема управління Платформою та Реєстрами підтримує як горизонтальне, так і вертикальне масштабування.
[TIP]
--
Детальніше з масштабуванням підсистем можна ознайомитись у розділі xref:architecture/container-platform/container-platform.adoc[]
--


=== _Observability_
Підсистема управління Платформою та Реєстрами підтримує журналювання вхідних запитів, логування подій та збір метрик
продуктивності для подальшого аналізу через веб-інтерфейси відповідних підсистем Платформи.

[TIP]
--
Детальніше з дизайном підсистем можна ознайомитись у відповідних розділах:

* xref:arch:architecture/platform/operational/logging/overview.adoc[]
* xref:arch:architecture/platform/operational/monitoring/overview.adoc[]
--
