= Підсистема обслуговування Платформи

== Загальний опис

Підсистема що забезпечує технічні послуги та сервіси для Платформи реєстрів.

== Функції підсистеми

* Встановлення Платформи реєстрів
* Оновлення Платформи реєстрів
* Розгортання сервісу управління секретами Платформи для зберігання чутливої інформації в надійному сховищі
* Забезпечення функціоналу по автоматичному розблокуванню (unseal) підсистеми керування секретами та шифруванням Платформи
* Зберігання резервних копій центральних компонент
* Зберігання резервних копій реєстрів, розгорнутих на платформі
* Зберігання резервних копій даних операційних S3-сховищ*
* Зберігання ключів шифрування для інтеграції з id.gov.ua та системних ключів для накладання підпису в програмно-апаратному
криптомодулі "Гряда"

== Технічний дизайн підсистеми

На даній діаграмі зображено компоненти, які входять в _Підсистема обслуговування Платформи_ та їх взаємодію з іншими підсистемами.

image::architecture/maintainance/platform-maintainance-subsystem.drawio.svg[width=800,float="center",align="center"]

== Складові підсистеми

|===
|Назва компоненти|Представлення|Тип додатка|Походження|Призначення

|_Компонент керування станом ресурсів Платформи_
|`control-plane-installer`
|backend
|origin
|Архів з компонентів Платформи та реєстрів, скриптів та складових для розгортання Платформи реєстрів з сукупними компонентами
на підготовленій інфраструктурі

|_Програмно-апаратний криптомодуль "Гряда"_
|`-`
|backend
|3rd-party
|Програмно-апаратний компонент, що забезпечує надійне зберігання сертифікатів та забезпечує операції з цифровим підписом
та печаткою

|_Управління секретами Платформи_
|`platform-vault`
|terraform
|3rd-party
|Забезпечення операції Auto unseal для підсистем управління секретами та шифруванням

|_Сховище резервних копій Платформи_
|`platform-minio`
|terraform
|3rd-party
|S3-сумісне сховище даних, що забезпечує надійне та масштабоване сховище резервних копій Платформи та реєстрів
|===

== Технологічний стек

При проектуванні та розробці підсистеми, були використані наступні технології:

* xref:arch:architecture/platform-technologies.adoc#minio[MinIO]
* xref:arch:architecture/platform-technologies.adoc#okd[OKD]
* xref:arch:architecture/platform-technologies.adoc#vault[HashiCorp Vault]

== Атрибути якості підсистеми

=== _Reliability_
Підсистема обслуговування Платформи розроблена із забезпеченням надійності та безпечного збереження резервних копій Платформи та реєстрів.

=== _Usability_
Підсистема обслуговування Платформи проста для розуміння та використання та має чіткі і стислі інструкції застосування.

=== _Portability_
Підсистема обслуговування Платформи розроблена з урахуванням сумісності між різними постачальниками інфраструктури та встановлюється
як у хмарні інфраструктурні середовища (AWS), так і в локальне серверне обладнання (vSphere).

=== _Modularity_
Компоненти підсистеми обслуговування реєстрів складаються з модулів та функцій, що забезпечує легку підтримку, повторне використання
та спрощує розуміння підсистеми.

=== _Backward Compatibility_
Підсистема розроблена з урахуванням зворотної сумісності та зберігає наявні функції, інтеграції та взаємодію з користувачами,
тим самим зменшуючи порушення та забезпечуючи плавний перехід при впровадженні нових оновлень та поліпшень Платформи реєстрів.
