= Підсистема обслуговування Платформи

[NOTE]
--
Сторінка технічної документації у процесі розробки...
--

== Загальний опис

Підсистема, яка забезпечує встановлення та оновлення платформи технічним адміністратором.

== Функції підсистеми

* Зберігання переліку створених ресурсів в інфраструктурі (_terraform state_), включаючи керування конфігурацією сховища резервних копій та секретів
* Встановлення оновлень платформи
* Зберігання секретів платформи в надійному сховищі
* Автоматичне розблокування підсистеми керування секретами та шифруванням платформи
* Зберігання резервних копій центральних компонент
* Зберігання резервних копій реєстрів, розгорнутих на платформі
* Зберігання ЕЦП адміністраторів платформи та реєстру в програмно-апаратному модулі

== Технічний дизайн підсистеми

На даній діаграмі зображено компоненти, які входять в _Підсистема обслуговування Платформи_ та їх взаємодію з іншими підсистемами.

image::architecture/maintainance/platform-maintainance-subsystem.drawio.svg[width=800,float="center",align="center"]


== Складові підсистеми

|===
|Назва компоненти|Представлення|Тип додатка|Походження|Призначення

|_Керування станом ресурсів Платформи_
|`control-plane-installer`
|backend
|origin
|-

|_Програмно-апаратний криптомодуль "Гряда"_
|`-`
|backend
|3rd-party
|-

|_Управління секретами Платформи_
|`platform-vault`
|terraform
|3rd-party
|-

|_Сховище резервних копій Платформи_
|`platform-minio`
|terraform
|3rd-party
|-
|===
