@startuml

autonumber
skinparam responseMessageBelowArrow true

actor "Адміністратор\n платформи" as Client

participant "Control Plane Console" as CP
participant "Control Plane Gerrit" as Gerrit
participant "Control Plane Jenkins" as Jenkins

activate Client

activate CP
Client -> CP :Enable mocking for external system
activate Gerrit
CP -> Gerrit :Save configuration
activate Jenkins
Gerrit -> Jenkins : Start registry build
Gerrit <-- Jenkins

deactivate CP
deactivate Client
deactivate Gerrit
deactivate Jenkins


@enduml