@startuml

autonumber
skinparam responseMessageBelowArrow true

actor "Розробник\n регламенту" as Client

participant "Registry Gerrit" as Gerrit
participant "Registry Jenkins" as Jenkins
participant "Registry Wiremock" as Wiremock
participant "Registry Service" as Service



activate Client

activate Gerrit
Client -> Gerrit: Add a new mock
activate Jenkins
Gerrit -> Jenkins: Start new registry-regulations build
activate Wiremock
Jenkins -> Wiremock: Import new mapping
Jenkins <-- Wiremock: Mapping added
deactivate Wiremock
deactivate Jenkins
Gerrit <-- Jenkins: Build successful
deactivate Gerrit
activate Service
Client -> Service: Act business process
activate Wiremock
Service -> Wiremock: Request mocked API
Service <-- Wiremock: Return mapping
Client <-- Service: Business process completed

deactivate Client

@enduml