= Функція _initiator()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`initiator(): UserDto`* використовується для отримання та подальшого використання xref:registry-develop:bp-modeling/bp/bp-modeling-instruction.adoc#initial-event[ініціатора] (`initiator`) в процесі.

== Параметри

Ця функція не приймає параметрів.

== Що повертає

Ця функція повертає об'єкт типу `UserDto`, що містить дані про ініціатора процесу.

.UserDto
|===
|*Поле*            | *Опис*
| `userName`      | Ім'я користувача.
| `accessToken`   | Токен користувача.
| `language`      | Мова користувача.
| `drfo`          | Ідентифікаційний код користувача.
| `edrpou`        | Код ЄДРПОУ користувача.
| `fullName`      | Повне ім'я користувача.
| `roles`         | Ролі користувача.
| `subjectType`   | Тип суб'єкта користувача.
| `isRepresentative` | Чи є користувач представником.
| `attributes`    | Інші атрибути користувача у вигляді ключів-значень.
|===

TIP: Клас `UserDto` є обгорткою даних користувача.

== Методи взаємодії

Функція надає наступні методи:

|===
|*Метод*            | *Опис*
| `getUserName()`  | Повертає ім'я користувача, що можна використовувати в полях *Assignee* та *Candidate Users* задач користувача.
| `getAccessToken()` | Повертає токен користувача, що можна використовувати в інтеграційних конекторах для інтеграції від імені користувача.
| `getLanguage()` | Повертає мову користувача, що можна використовувати для налаштування інтерфейсу.
| `getDrfo()` | Делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `drfo` користувача.
| `getEdrpou()` | Делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `edrpou` користувача.
| `getFullName()` | Делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `fullName` користувача.
| `getRoles()` | Повертає ролі користувача.
| `getSubjectType()` | Повертає тип суб'єкта користувача.
| `isRepresentative()` | Повертає, чи є користувач представником.
| `getAttributes()` | Повертає інші атрибути користувача у вигляді ключів-значень.
|===

NOTE: Токен ініціатора, а разом з ним і всі атрибути Keycloak, будуть доступні _ЛИШЕ_ до першої користувацької задачі (**User Task**) у бізнес-процесі. Надалі використовуйте токен xref:bp-modeling/bp/juel-functions/users/completer.adoc[_completer()_].

== Приклади використання

Цей розділ демонструє приклади використання JUEL-функції у завданнях бізнес-процесу.

[TIP]
====
[%collapsible]
.Де можна знайти приклад бізнес-процесу?
=====
include::partial$snippets/demo-reg-reference-examples-ua.adoc[]

Застосування функції `initiator()` представлено у багатьох бізнес-процесах.

Ви можете використати один із багатьох прикладів процесів за пошуком по ключовим словам — *_officer-selfregistration-handmoderation_*.

У Кабінеті користувача бізнес-процес буде доступний у розділі *Доступні послуги*.
=====
====

Існує декілька варіантів використання функції `initiator()` у бізнес-процесі.

Один із найбільш розповсюджених сценаріїв -- застосування функції в інтеграційних розширеннях (делегатах) для передачі *X-Access-Token* у бізнес-процесі, тобто токена доступу користувача, під яким виконується операція. Цей токен забезпечує повноваження виконавця задачі щодо доступу до даних.

.Приклад. Отримання токена доступу ініціатора процесу для виконання завдання
----
${initiator().accessToken}
----

Другий можливий варіант використання -- передача параметрів ключ-значення (*map*) із даними користувача. Наприклад, для автентифікації. Надсилати такі параметри можна, наприклад, через Подію "Повідомлення". Ця подія повідомлення являє собою елемент у бізнес-процесі, який відправляє повідомлення з даними (`ПІБ`, `РНОКПП` та `ЄДРПОУ` з токена) про користувача до іншого учасника процесу або іншого процесу.

.Приклад. Отримання імені користувача
----
${initiator().userName}
----

TIP: Детальніше про використання функції у бізнес-процесах див. сторінку xref:best-practices/bp-officer-self-register-manual.adoc[].

== Пов'язані сторінки

* xref:bp-modeling/bp/juel-functions/users/completer.adoc[]
* xref:bp-modeling/bp/juel-functions/users/system-user.adoc[]
* xref:best-practices/bp-officer-self-register-manual.adoc[]