= Функція _system_user()_
include::platform:ROOT:partial$templates/document-attributes/default-set-ua.adoc[]

== Опис

JUEL-функція *`system_user(): UserDto`* необхідна для отримання системного користувача з Keycloak.

== Параметри

Ця функція не приймає параметрів.

== Що повертає

Ця функція повертає об'єкт типу `UserDto`, що містить дані про системного користувача.

.UserDto
|===
|*Поле*            | *Опис*
| `userName`      | Ім'я користувача.
| `accessToken`   | Токен користувача.
| `language`      | Мова користувача.
| `drfo`          | Ідентифікаційний код користувача.
| `edrpou`        | Код ЄДРПОУ користувача.
| `fullName`      | Повне ім'я користувача.
| `roles`         | Ролі користувача.
| `subjectType`   | Тип суб'єкта користувача.
| `isRepresentative` | Чи є користувач представником.
| `attributes`    | Інші атрибути користувача у вигляді ключів-значень.
|===

TIP: `UserDto` -- клас, що є обгорткою даних користувача (тут -- системного користувача). Завжди містить у собі `userName`, токен і `JwtClaimsDto`.

== Методи взаємодії

Функція надає наступні методи:

.Методи взаємодії
|===
|*Метод*            | *Опис*
| `getUserName()`  | Повертає ім'я користувача, що можна використовувати в полях *Assignee* та *Candidate Users* задач користувача.
| `getAccessToken()` | Повертає токен користувача, що можна використовувати в інтеграційних конекторах для інтеграції від імені користувача.
| `getLanguage()` | Повертає мову користувача, що можна використовувати для налаштування інтерфейсу.
| `getDrfo()` | Делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `drfo` користувача.
| `getEdrpou()` | Делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `edrpou` користувача.
| `getFullName()` | Делегує виклик на `JwtClaimsDto` та повертає Keycloak-атрибут `fullName` користувача.
| `getRoles()` | Повертає ролі користувача.
| `getSubjectType()` | Повертає тип суб'єкта користувача.
| `isRepresentative()` | Повертає, чи є користувач представником.
| `getAttributes()` | Повертає інші атрибути користувача у вигляді ключів-значень.
|===

NOTE: Функція `system_user()` використовується для отримання інформації про системного користувача, що зберігається в Keycloak.

== Приклади використання

Один із можливих випадків використання функції `system_user()` -- це передача *X-Access-Token* системного користувача для автентифікації під час виконання інтеграційних операцій у бізнес-процесі. Наприклад, у розширенні xref:bp-modeling/bp/element-templates/service-task-templates/signature/system-signature-by-dso-service.adoc[System signature by DSO service] можна передати токен системного користувача, використовуючи функцію `system_user()` та метод `accessToken`.

[source,groovy]
----
${system_user().accessToken}
----

* `system_user()` — викликає системного користувача, під яким відбувається процес.
* `accessToken` — отримує токен доступу системного користувача.

Цей сценарій дозволяє використовувати токен для інтеграції з іншими сервісами або виконання дій від імені системного користувача, забезпечуючи необхідні права доступу.

[TIP]
====
Використання токенів інших користувачів ::

Крім токена системного користувача, є інші варіанти роботи з токенами в процесі:

. Використання токена ініціатора процесу. Ви можете отримати токен ініціатора, тобто користувача, який запустив процес, за допомогою функції xref:bp-modeling/bp/juel-functions/users/initiator.adoc[_initiator()_]:
+
[source,groovy]
----
${initiator().accessToken}
----
+
Цей токен зручно використовувати, коли процес потребує автентифікації від імені користувача, який ініціював поточний бізнес-процес.

. Використання токена виконавця попередньої задачі. Функція xref:bp-modeling/bp/juel-functions/users/completer.adoc[_completer()_]: дозволяє отримати токен користувача, який завершив попереднє завдання у процесі:
+
[source,groovy]
----
${completer('Task definition ID').accessToken}
----
+
`'Task definition ID'` — ідентифікатор попередньої задачі користувача.
+
Цей сценарій зручний, коли вам потрібно продовжувати роботу від імені користувача, який завершив одну із попередніх задач у процесі.
====

== Пов'язані сторінки

* xref:bp-modeling/bp/juel-functions/users/initiator.adoc[]
* xref:bp-modeling/bp/juel-functions/users/completer.adoc[]
* xref:bp-modeling/bp/element-templates/service-task-templates/signature/system-signature-by-dso-service.adoc[]

