= Динамічні змінні у документації

== Загальний опис

У цій статті буде розглянута можливість подання актуальної інформації для користувачів конкретної платформи. У поточній реалізації неможливо використовувати актуальні посилання чи іншу інформацію, що стосується платформи на якій розгорнута документація та її реєстрів.

Необхідно, щоб така можливість була для зручності використання. Також у рамках цього дизайна враховується необхідність робити посилання на демо реєстр, що потребує можливості обирати основний демо реєстр для таких посилань.

== Сценарії адміністрування налаштувань реєстру

- Позначення реєстру як демо-реєстру у control plane
- Вибір демо-реєстру за замовчуванням у control plane

== Сценарії використання змінних у документації

- Формування актуальних посилань та текстових описів

== Цільовий дизайн управління налаштуваннями

=== Компоненти системи та їх призначення в рамках дизайну рішення

У даному розділі наведено перелік компонент системи, які задіяні або потребують змін/створення в рамках реалізації функціональних вимог згідно технічного дизайну рішення.

|===
|Компонент|Службова назва|Призначення / Суть змін

|_Документація_
|*ddm-architecture*
|Зміни в структурі файлів що використовують змінні, оновлення пайплайнів розгортання

|_Control plane консоль_
|*control-plane-console*
|Додати можливість позначати реєстр як демо-реєстр та обрати демо реєстр за замовчуванням

|===

=== План змін

Рішення має враховувати наступні факти:

- актуальні змінні не відомі на момент build фази документації
- частина змінних відома на момент встановлення платформи
- інша частина залежить від налаштуваннь платформи у процесі експлуатації (наприклад, посилання на демо-реєстр)
- у випадку посиланнь на демо-реєстр необхідно залишити у документації інформацію про те, як формується це посилання
- посилання на демо-реєстр враховуючи попердній пункт будуть мати однакову структуру тому треба знайти підхід який спростить формування таких посиланнь

==== Необхідні зміни у репозиторію документації

===== 1. Використання змінних

- Необхідно знайти усі змінні що використовуються.
- Всі змінні треба привести до єдиної конвенції:
[source]
----
Нова змінна: {{{MY_VARIABLE}}}
----
-  Створення окремої папки `ROOT/partials/links` у якій розмістити файли для посиланнь
-  Використати include цих файлів де це необхідно

Приклад використання include:

`include::ROOT:partials$/links/nexus.adoc`

Приклад файла для посилання на `jenkins nexus.adoc`:
[source]
----
https://nexus-{{{CP-NAMESPACE}}}.{{{DNS-WILDCARD}}}/ footnote:[CP-NAMESPACE -- назва namespace (простору імен) у Nexus;
DNS-WILDCARD -- значення DNS wildcard]
----

{{{CP-NAMESPACE}}} та {{{DNS-WILDCARD}}} трансформуються у актуальні дані в процесі розгортання.

===== 2. Зміни процесу розгортання

Всі змінні які підходять під паттерн обраний на минулому кроці треба замінити на актуальні дані у процесі розгортання документації. Таким чином ми уникнемо помилок та легко досягнемо необхідного рівня гнучкості (а саме, можливості змінювати посилання у процесі життя платформи). Це включає:

* додавання відомих змінних у структуру `ddm-architecture/deploy-templates/values.yaml`
** для кожної змінної треба задати значення за замовчуванням
* написання скрипта якій замінить усі входження змінних за паттерном
** паттерн - `{{{VARIABLE}}}`
** при відсутності даних для зазначеної назви змінної - залишити текст без змін
** значення змінних беруться з environment змінних (див. наступний крок)
* застосування скрипта для розгортання платформи
** зміни стосуються файла `ddm-architecture/deploy-templates/templates/deployment.yaml`
** у секції `env` цього файлу треба додати змінні які заповнюються з `values.yaml`
* застосування скрипта для зовнішього розгортання документації (*github*)
** зміни стосуються файла `ddm-architecture/.github/workflows/antora-build.yml`
** тут використовуються лише змінні за замовчуванням із файла `ddm-architecture/deploy-templates/values.yaml`
** перед застосуванням цих змін у *master* необхідно перевірити разгортання документації через github

==== Control plane

===== 1. Позначити реєстр як демо-реєстр

Для формування посиланнь у документації необхідно обрати демо-реєстр за замовчуванням із наявних. Для цього треба спочатку мати чіткий спосіб зрозуміти чи є реєстр демо-реєстром:

- Додати чекбокс `Демо-реэстр` до вкладки ЗАГАЛЬНІ сторінки створення/редагування реєстра.
- Значення цього чекбокса зберігати разом з іншими даними реєстра у Codebase yaml:
[source]
----
apiVersion: v2.edp.epam.com/v1alpha1
kind: Codebase
metadata:
  name: myname
  annotations:
    registry-parameters/demo: true    <-----
  ...
----
* Це *не потребує* змін у схемі Codebase


===== 2. Вибір демо-реєстру за замовчуванням

- У вкладці `КЕРУВАННЯ ПЛАТФОРМОЮ` при переході у редагування треба додати нову вкладку `ДОКУМЕНТАЦІЯ`.
- На цій новій вкладці `ДОКУМЕНТАЦІЯ` додати компонент Select, який буде дозволяти обрати з реєстрів позначених як "Демо" (Крок 1)
- Опції для вибору треба взяти з переліку Codebase ресурсів за значенням параметра `demo: true`
- Зберігати  обране значення треба у файлі `values.yaml` репозиторія *cluster-mgmt* разом з іншими параметрами платформи вкладки `КЕРУВАННЯ ПЛАТФОРМОЮ`
- Зміни цього `values.yaml` вже перерозгортають документацію тому додатково змін до цього процесу не передбачується


