= Підсистема симуляції API зовнішніх систем
include::platform:ROOT:partial$templates/document-attributes/arch-set-ua.adoc[]

include::platform:ROOT:partial$admonitions/language-ua.adoc[]

== Загальний опис

_Підсистема симуляції API зовнішніх систем_ забезпечує можливості по розробці та тестуванню реєстру в ізоляції від зовнішніх систем.

Налаштування правил симуляції згідно з вимогами реєстру доступне через службовий вебінтерфейс xref:arch:architecture/registry/administrative/regulation-management/overview.adoc[Підсистеми моделювання регламенту реєстру]. Управління використанням симуляції зовнішніх інтеграцій та використанням реальних систем доступне через вебінтерфейс налаштування _операційної конфігурації реєстру_ xref:arch:architecture/platform/administrative/control-plane/overview.adoc[Підсистеми управління Платформою та Реєстрами].

== Функції підсистеми

* Симуляція API зовнішніх систем в рамках виконання бізнес-процесів
* Симуляція віджета підпису даних в функціональних сценаріях накладання підпису та автентифікації користувачів кабінетів

== Технічний дизайн підсистеми

На даній діаграмі зображено компоненти, які входять у _Підсистему симуляції API зовнішніх систем_ та їх взаємодію з іншими підсистемами в рамках реалізації функціональних сценаріїв.

image::arch:architecture/registry/operational/ext-systems-simulation/ext-systems-simulation-design.svg[float="center",align="center"]

_Підсистема симуляції API зовнішніх систем_ представлена двома компонентами, які відповідають за мокування основних інтеграційних сценаріїв реєстру з зовнішніми системами:

* _Віджет симуляції підпису даних_ - статична копія віджету підпису, яка обслуговується веб-сервером _Nginx_.
* _Сервер симуляції API зовнішніх систем_ - сервер симуляції _API_ на базі https://wiremock.org/[Wiremock], який підтримує _REST_ та _SOAP_ протоколи інтеграції.

== Складові підсистеми

|===
|Назва компоненти|Представлення в реєстрі|Походження|Репозиторій|Призначення

|_Віджет симуляції підпису даних_
|`sign-widget-mock`
|origin
|https://github.com/epam/edp-ddm-sign-widget-mock[github:/epam/edp-ddm-sign-widget-mock]
|Статична копія віджета підпису

|_Сервер симуляції API зовнішніх систем_
|`wiremock`
|3rd-party
|https://github.com/epam/edp-ddm-wiremock[github:/epam/edp-ddm-wiremock]
|Сервер мокування API зовнішніх систем з підтримкою декларативного підходу до опису контрактів

|_Мок-сервіс інтеграції з ЄДР_
|`trembita-edr-registry-mock`
|origin [_deprecated_]
|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/low-code-platform/mock/trembita-edr-registry-mock[gerrit:/mdtu-ddm/low-code-platform/mock/trembita-edr-registry-mock]
|Сервіс мокування SOAP API реєстру ЄДР

|_Мок-сервіс інтеграції з ДРАЦС_
|`trembita-dracs-registry-mock`
|origin [_deprecated_]
|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/low-code-platform/mock/trembita-dracs-registry-mock[gerrit:/mdtu-ddm/low-code-platform/mock/trembita-dracs-registry-mock]
|Сервіс мокування SOAP API реєстру ДРАЦС

|_Мок-сервіс інтеграції з ЄІБДВПО_
|`trembita-idp-mock-server`
|origin [_deprecated_]
|https://gerrit-mdtu-ddm-edp-cicd.apps.cicd2.mdtu-ddm.projects.epam.com/admin/repos/mdtu-ddm/low-code-platform/mock/trembita-idp-mock-server[gerrit:/mdtu-ddm/low-code-platform/mock/trembita-idp-mock-server]
|Сервіс мокування SOAP API ЄІБДВПО

|===

== Технологічний стек

При проектуванні та розробці підсистеми, були використані наступні технології:

* xref:arch:architecture/platform-technologies.adoc#javascript[JavaScript]
* xref:arch:architecture/platform-technologies.adoc#java[Java]
* xref:arch:architecture/platform-technologies.adoc#wiremock[Wiremock]

== Атрибути якості підсистеми

=== _Testability_

_Підсистема симуляції API зовнішніх систем_ забезпечує можливості тестування реєстру з симуляцією різних сценаріїв поведінки зовнішніх систем та проводити перевірку коректності опрацювання результатів, помилок, тимчасової недоступності зовнішніх систем, сповільнення їх швидкодії, тощо.