:toc-title: ЗМІСТ
:toc:
:toclevels: 5
:experimental:
:important-caption: ВАЖЛИВО
:note-caption: ПРИМІТКА
:tip-caption: ПІДКАЗКА
:warning-caption: ПОПЕРЕДЖЕННЯ
:caution-caption: УВАГА
:example-caption: Приклад
:figure-caption: Зображення
:table-caption: Таблиця
:appendix-caption: Додаток
:sectnums:
:sectnumlevels: 5
:sectanchors:
:sectlinks:
:partnums:

= Пояснення до заповнення таблиці «Users Keycloak»

Для автоматичного завантаження користувачів до Keycloak:

. Відкрийте Кабінет адміністратора регламентів. Увійдіть до секції «Управління користувачами».

. Завантажте шаблон CSV-файлу link:{attachmentsdir}/import-users-officer/users-keycloak.csv[`Users Keycloak.csv`] за посиланням на екрані.

. Відкрийте завантажений файл та заповніть колонки шаблону своїми значеннями згідно з поясненнями, поданими нижче. Заповнені поля не повинні мати додаткових пробілів на початку та в кінці значення. CSV-роздільник між колонками – крапка з комою.

. Завантажте заповнений файл на сторінку Кабінету адміністратора регламентів та натисніть кнопку підтвердження. Зачекайте декілька хвилин до повного завантаження користувачів реєстру. Результат можна переглянути на інтерфейсі сервісу Kibana.

Пояснення до заповнення таблиці «Users Keycloak», для мінімізації помилок:

. `drfo` – особистий реєстраційний номер облікової картки платника податків (РНОКПП). Код РНОКПП містить 10 цифр. Якщо через релігійні переконання особа не отримувала РНОКПП, необхідно вказати серію та номер паспорта або номер ID-картки. При внесенні серії та номера паспорта необхідно звернути увагу, як саме ці дані записані у КЕП з точністю до символу (з пробілом чи без). `Поле обов’язкове до заповнення`.
+
Для перевірки даних у КЕП можна скористатися порталом Дія: https://id.diia.gov.ua/. Виконайте вхід та оберіть спосіб авторизації _Файловий ключ_ або _Апаратний ключ_, залежно від вашого носія. У правому верхньому куті сторінки відкрийте меню `«Мій профіль»`. У блоці `«Персональні дані»` ви побачите інформацію про свій КЕП.

. `edrpou` – унікальний ідентифікаційний номер юридичної особи в Єдиному державному реєстрі підприємств та організацій України. Ідентифікаційні коди ЄДРПОУ містять 8 цифр. Якщо перша цифра в ЄДРПОУ – нуль, то спочатку обов’язково потрібно змінити формат клітинки на _Текстовий_ (натисність правою клавішею на поле та оберіть «Формат клітинок») і після цього ввести значення. `Поле обов’язкове до заповнення`.

. `fullName` – прізвище, ім'я, побатькові (за наявності). Має містити більше 3-х, але не менше 2-х слів. ПІБ повинне мати 100% співпадіння із даними у КЕП з точністю до символу. `Поле обов’язкове до заповнення`.
+
У разі невідповідності значень атрибутів до значень, вказаних у КЕП, користувач не матиме можливості увійти до Кабінету посадової особи та підписувати задачі КЕП.

. `Realm Roles` – перелік системних та регламентних (за наявності) ролей користувача. Для Кабінету посадової особи використовується лише одна системна роль – `officer`. `Вона є обов’язковою до заповнення`. Якщо посадова особа має додатково визначені регламентні ролі, вони вносяться через кому після значення `officer`. Управління регламентними ролями здійснює Адміністратор реєстру, інформацію про те, чи передбачені у конкретному реєстрі регламентні ролі, і які саме, можна дізнатися у нього.
+
За відсутності системної ролі, користувач не матиме доступу до Кабінету посадової особи.

* Системна роль officer автоматично створюється Платформою під час розгортання реєстру.
* Регламентні ролі створюються під час розгортання реєстру та налаштовуються Адміністратором у регламенті відповідного реєстру → директорія `roles` → конфігураційний файл `*.yml`.

Якщо імпорт користувачів у Keyсloak відбувся із помилками (часткове створення користувачів), потрібно повторно завантажити файл із користувачами, яких не вдалося створити (здійснивши необхідні коригування).

'''

.Приклад заповнення файлу:
|===
|drfo|edrpou|fullName|Realm Roles
|1010101014|34554362|Сидоренко Василь Леонідович |officer,head-officer``*``
|3030303030 |33333333|Степанченко Степан Степанович |officer
|СО 522654 |20559371|Алмаз-заде Гайяне Мухамедівна |officer
|2354689712 |20553149 |Петру Іон |officer
|===

`*` - _приклад регламентної ролі, яка може бути створена в реєстрі додатково до основної системної ролі officer. У кожному реєстрі перелік регламентних ролей налаштовується індивідуально і може відрізнятися._